### ISSUE TITLE
Preview should reuse an existing window

### ISSUE THREAD

**Issue by vadi2** [maqetta/maqetta#1]
Currently, previewing something will open a new window, regardless if an existing one is open already. Wordpress admin panel handles it better - if a window is already open, it will refresh that tab.

It'd be nice to have this behavior here as well to cut down on closing the old and obsolete preview widows.

**Comment by peller** [comment]
Good idea.  Perhaps a unique window per file, since we currently allow for multiple files (tabs) on the screen?  I know, still too many windows.

**Comment by jhpedemonte** [comment]
See #276, which suggests moving Preview to a tab within Maqetta itself, rather than a separate browser tab.

**Comment by JonFerraiolo** [comment]
A long time ago, we reused an existing browser window for preview. As I remember, this was easy to do. I think you just need to use the same window name or something like that.

**Comment by peller** [comment]
trivial to do.  just pass a target name (2nd param) into window.open.  but do we really want to do this?

**Comment by JonFerraiolo** [comment]
@peller: yes, I don't see why it's good for the user to have N different preview tabs open for the same HTML file. We should reuse the same tab whenever we can for the same HTML file. (Note: if a user is working on two files, such as file1.html and file2.html, and previews both, there should be 2 preview tabs, not one shared tab.)

**Comment by jhpedemonte** [comment]
Reopening.  @peller, your fix made it so all Previews show up in one tab, which is different than what Jon last stated ("... there should be 2 preview tabs, not one shared tab").
