### ISSUE TITLE
Could anybody build Maqetta from the latest github

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#10]
Could anybody build Maqetta from the latest github source repository
using Eclipse (Helios) on Mac OS X 10.6? By following the
documentation at https://github.com/maqetta/maqetta/wiki/Developer-Setup,
I couldn't build it. Especially configuring the OSGi framework looks
different from the doc.

I tried to select all available bundles, but Java is throwsing several
errors.

Finally, when I try to access via browser, I get the following 404

**Comment by billreed63** [comment]
This issue is from a thread on the dev group http://groups.google.com/group/maqetta-devs/browse_thread/thread/732418b92063bd0f

**Comment by jhpedemonte** [comment]
There were some Eclipse project files in the top level that were accidentally checked in.  I've removed those.  Also updated the wiki to better describe pulling in the source.  Got confirmation in dev group thread that it now works.
