### ISSUE TITLE
(Maybe not critical issue) No more iPhone theme if no silhouette

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1000]
@billreed63, @peller, @jhpedemonte

We have a regression, but I'm trying to think how much it matters for the M3 release.

If you don't choose a silhouette, and just start dragging/dropping mobile widgets, no device CSS files are loaded. When you choose a silhouette, everything looks fine. It's arguable that users should really already have picked a silhouette if they are using any dojox.mobile widgets, so maybe it's OK as is for M3, but I'd like things to default to iPhone in M4 if not M3.

**Comment by peller** [comment]
Yeah, that would have been my checkin d6870739d3bc7d56c0a2d04bf0325a42ca4614a6  I probably should have checked for device == "none" in MobileCreateTool
