### ISSUE TITLE
Update browsers messages on Maqetta.org about Safara 5.1

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1001]
@peller, @waynevicknair

THIS DOESN'T AFFECT THE APP! Just the Joomla stuff.

I tried to run Preview 3 on Win/IE and I saw a message about Safari 5 instead of Safari 5.1 on the "Launch Maqetta" page. We need to grep for Safari within the Joomla files and make sure to include 5.1.

**Comment by waynevicknair** [comment]
done.
