### ISSUE TITLE
New Theme Dialog Hangs on Mac/Safari 5.1

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1004]
From the ThemeEditor test script
- Click 'New' menu and select 'Theme...'
  *\* The clone a theme dialog appears. 
- Select 'claro' from the drop down and click the 'OK' button

Result:
OK button stays highlighted and dialog never closes. In the browser error console the following message appears:
    TypeError: 'null' is not an object (evaluating '_ef9.file')
which corresponds to `davinci.ui.NewTheme.js` line 113 where it calls the workbench's `openEditor` method.

**Comment by peller** [comment]
FWIW, if there's an error, the dialog stays up w/o any error UI, and it's possible to click 'ok' multiple times during or after the processing.  Many of our dialogs have this problem.

**Comment by JonFerraiolo** [comment]
@billreed63

**Comment by waynevicknair** [comment]
Additional note: The theme actually gets created. So the user can cancel or close (click on the 'x' icon) the dialog and resume activities.

**Comment by billreed63** [comment]
I put a breakpoints on the server and it appears to me that for some reason the savefile for the new theme (a1.theme) was being delayed until the browser stops executing NewTheme._createTheme. So I added a check if the theme is not found we setTimeout and wait a small amount of time to get safari to execute the savefile..

**Comment by peller** [comment]
Maybe it's maxing out on HTTP resources?
