### ISSUE TITLE
Replace setTimeout logic in NewTheme.js with something less ugly

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1006]
@waynevicknair, @billreed63, @peller

Doesn't have to be Brad, but he is the server guru. For some reason, the findResource "*.theme" command on Safari doesn't return the newly created theme in the list of themes due to a timing issue. Bill patched around the problem with c24afbbe8f63fe761b45603430b60c860c5f7aed. We should come up with a solution that doesn't involve a setTimeout.

**Comment by peller** [comment]
FWIW, I could only reproduce this problem on Safari with a build

**Comment by JonFerraiolo** [comment]
I was seeing the Safari problem (#1004) running from Eclipse, also.

**Comment by JonFerraiolo** [comment]
Maybe @peller or @waynevicknair could snatch this one and see if there is a (reasonably) safe fix

**Comment by childsb** [comment]
moving to m5

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
-> @billreed63 M7 Prio-Low

**Comment by billreed63** [comment]
This code was removed a while ago
