### ISSUE TITLE
iPad authoring not working - needs both iphone.css and ipad.css?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1010]
@jhpedemonte, @peller

Styling is messed up if you choose to author for an iPad. Could it be that dojox.mobile requires both iphone.css and ipad.css for the iPad, rather than just a single CSS file?

**Comment by JonFerraiolo** [comment]
Yes, we need both. What I think is happening is that our code properly loads both iphone.css and ipad.css, but the loadRequires on deviceTheme.js triggers initialization logic that appears to reload the CSS files and somehow in the process removes the iphone.css file. (But I haven't found the removal code)

**Comment by jhpedemonte** [comment]
I think this is Adam's code, which removes *_iphone.css_ in MobileCreateTool.

**Comment by jhpedemonte** [comment]
I know it's probably too late, but my patch (pull request 990) handled this correctly.  Or we can create another patch on top of all the other patches!

**Comment by peller** [comment]
ok, I was not aware when I stepped in the other day that it was not a 1:1 mapping.  Choices seem to be: apply Javier's patch or put in `device != "ipad"` in MobileCreateTool... all of which should go away soon.

**Comment by peller** [comment]
that makes ipads work as well as iphones, anyway.  We can continue to debate Javier's patch in #990
