### ISSUE TITLE
Android includes iPhone CSS files in page editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1014]
@billreed63, @peller

In page editor, Heading, EdgeToEdgeCategory and TabBar are all mis-styled in page editor because we are including some iphone css files when Android is chosen. Unfortunate, but has to be pushed to M4.

**Comment by peller** [comment]
see #1011

**Comment by jhpedemonte** [comment]
This might be fixed by fixes for #1011.  Need to investigate.

**Comment by peller** [comment]
works for me
