### ISSUE TITLE
Download as ZIP on Maqetta.org generates slow JavaScript warnings

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1016]
@jhpedemonte

Using Mac/Chrome just now, I saw 2 messages telling me about slow JavaScript and asking me whether to kill the current web page (i.e., Maqetta).

Are we waiting for the server to copy Dojo before the browser download dialog comes up? Is there an option for preventing these warniing dialogs from appearing?

**Comment by billreed63** [comment]
Maybe we could use HTML5 web workers to do the zip file processing on a different thread
http://www.codediesel.com/javascript/introducing-html5-web-workers/

**Comment by jhpedemonte** [comment]
I'm guessing that we're doing a synchronous get. Need to move to async.

Using web workers would work if we were actually doing processing on the client, but as I understand it, we're just waiting for the server to create the zip.

**Comment by billreed63** [comment]
Web workers can be used  for async communication with severs as well.

woker.js

``` javascript
function getJson(data){
            var request = new XMLHttpRequest();  
            request.open('GET', data.url, false);   
            request.send(null);  

            if (request.status == 200)  {
              postMessage(request.responseText);
            } else{
              postMessage('error');
            }           

}

/* 
   Add a event listener to the worker, this will
   be called when the worker receives a message
   from the main page.
*/
this.onmessage = function (event) {
    var data = event.data;
        getJson(data);

};
```

and the html that drives it

``` html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html dir="ltr">

    <head>
        <style type="text/css">
            body, html { font-family:helvetica,arial,sans-serif; font-size:90%; }
        </style>
        <script src="http://ajax.googleapis.com/ajax/libs/dojo/1.6/dojo/dojo.xd.js"
        djConfig="parseOnLoad: true">
        dojo.require('dojox.io.xhrScriptPlugin');
        dojox.io.xhrScriptPlugin("http://localhost:8081/test4/TestService","callback");
        </script>
        <script>
            function getJson() {
                /* Create a new worker */
                xhrWorker = new Worker("worker.js");
                /* 
                    Add a event listener to the worker, this will
                    be called whenever the worker posts any message.
                */
                xhrWorker.onmessage = function (event) {
                    debugger;
                    dojo.byId("container").innerHTML = event.data;
                };
                message = {
                    'url' : 'http://localhost:8081/test4/TestService'


                };
                debugger;
                xhrWorker.postMessage(message);
            }


             dojo.addOnLoad(getJson);
        </script>
        <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/dojo/1.6/dijit/themes/claro/claro.css"
        />
    </head>

    <body class=" claro ">
          <div id="container" style="height: 200px;">
        </div>
        <!-- NOTE: the following script tag is not intended for usage in real
        world!! it is part of the CodeGlass and you should just remove it when
        you use the code -->
        <script type="text/javascript">
            dojo.addOnLoad(function() {
                if (document.pub) {
                    document.pub();
                }
            });
        </script>
    </body>

</html>

```

**Comment by childsb** [comment]
download is sync (it was async, but async is bad design in this case. you dont want the server to do pre-processing-- the zip should be done on-the-fly when the client makes a request and writes the zip directly to the IO stream.)  it's like making a request for an image file.

most likely there is a problem in the URL encoding (looks like spaces in your path maybe aren't processed correctly) and the server threw an exception that wasn't visible on the client.  the client then hung waiting for the server to continue writing the output stream.

i'll investigate further.

**Comment by JonFerraiolo** [comment]
Could we send an async request to server asking to create the ZIP and then post some UI (dialog or toaster) that tells user the download request has been sent and, when completed, the browser will present a download dialog?

**Comment by childsb** [comment]
Theres no need to pre-build the zip as the zip is being sent to the user while it's being assembled.  This absolutely should NOT cause a non responsive script dialog. There's something else going on here.

**Comment by childsb** [comment]
there was a path problem where the project was being processed for downloads multiple times.
