### ISSUE TITLE
Commented out requires still loaded by context.js

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1023]
I tried to comment out a requires but it is still being loaded by ve.Context.js

``` html
<script type="text/javascript">
dojo.require('dojox.mobile');
dojo.require('dojox.mobile.parser');
//dojo.require('dojox.mobile.deviceTheme');
//dojo.require('dojox.mobile.compat');
</script>

```

Context.js about line 1750 Context._parse

``` javascript
if (text.length>0)
            {
                var func = text.indexOf("dojo" + ".require(");
```

**Comment by peller** [comment]
yeah, I think the Dojo builder (pre 1.7) had similar issues, so maybe it's not worth addressing?

**Comment by billreed63** [comment]
Actually I found another case where this code hangs the load of the file

``` html
<script type="text/javascript">
dojo.require('dojox.mobile');
dojox.mobile.themeMap=[["Android","android",["themes/custom_android/android.css"]],["BlackBerry","blackberry",[]],["iPad","iphone",[require.toUrl("dojox/mobile/themes/iphone/ipad.css")]],["Custom","custom",[]],[".*","iphone",[]]];
dojo.require('dojox.mobile.parser');
dojo.require('dojox.mobile.deviceTheme');
dojo.require('dojox.mobile.compat');</script>
```

The code attempts to load Android as a requires and throws an exception

**Comment by peller** [comment]
so this is fun... our _parse routine to seek out the dojo.require's looks for dojo.require, then searches for a double-quoted string at that offset before looking for a single-quoted string... so it sees "dojo.require(" for dojox.mobile, but comes back with "Android"  Sort of related to the commenting out thing, but separate in that this particular glitch is NOT an issue in the Dojo build algorithms, so it MUST be fixed.
