### ISSUE TITLE
Create Mobile Theme Editor

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1024]
To create a theme editor for mobile widget
- We can copy the dojox/mobile/theme/custom to the dojo_1_7/themes folder. Should we rename custom to mobile?
  - Create a dojo-theme_editor.html containing mobile widgets.
  - Create a mobile.theme 
  - Create a mobile.json file containing mobile theme meta data.
  - Change the way we handle mobile themes. this effects issue #1011

@peller @JonFerraiolo @jhpedemonte

**Comment by billreed63** [comment]
I may have come up with a better idea so we can leave the dojox.mobile.deviceTheme.

If we copy the custom theme and add a theme class name to all the selectors, this will override device specific styles.

example:

selector from custom.css 

``` css
.mblHeading

```

new selector

``` css
.custom .mblHeading {
```

**Comment by billreed63** [comment]
I have come up with 3 options for mobile themes customization.

<ol>
   <li>leveraging dojox.mobile.deviceTheme 
   <ul>
      <li>My understanding of deviceTheme is that we would need to add the theme=Custom parm to the url.</li>
       <li>The user could only have one custom theme</li>
       <li>We would need to copy the dojo toolkit to the users workspace</li>
    </ul>
    </li>
    <li>Removing dojox.mobile.deviceTheme for custom mobile theme and adding custom mobile theme link to css files.
     <ul>
        <li>Would require changes to the way we switch themes in page editor, when the user switches a mobile page to a custom theme we would need to remove the requires for the dojox.mobile.deviceTheme </li>
         <li>No changes to the mobile custom theme css files just a copy</li>
     </ul>
    </li>
     <li>Modify Custom by adding theme class tag to selectors - this is analogous to  page editor app.css
      <ul>
        <li>We can leave the require dojox.mobile.deviceTheme</li>
        <li>We could use the existing theme switching logic </li>
         <li>We would need to add a theme class name to all mobile custom selectors </li>
         <li>deviceTheme css files are loaded but not used </li>
       </ul>
    </li>
</ol>

**Comment by JonFerraiolo** [comment]
I expect that the dojox.mobile guys would agree that it's OK to:
- have the CSS files for custom themes stored outside of the dojox.mobile area
- allow the user to have multiple different "custom themes"

so I don't like #1 as it stands above because (to point to one particular flaw) we need to allow for multiple custom themes.

I'm not sure I fully understand #2, but I'll say that I think we need to leave the dojo.require('dojox.mobile.deviceTheme') in the metadata because it's needed at runtime. For the page editor, however, my instincts are that we need to find a way to disable it or render it harmless. One idea I have for how to disable particular REQUIRE directives found in the OAM files would be to add a mechanism to the widgets.json file which allow the entry in widgets.json to override parts of the OAM file, in this case the widgets.json file would provide an alternate list of REQUIRE directives for use within the page editor that overrides what's in the OAM files. I like this whole notion of widgets.json having the ability to override the OAM files. This would allow us to minimize the number of widget-specific properties that show up in Maqetta for particular widgets. (Some widgets have a zillion widget-specific properties, and almost none of them make sense to designers)

Regarding #3 (prefix each selector with .custom or whatever), I think we need to ask the Dojo guys about what's the right policy. The Dijit theme CSS rules are all prefaced by the theme name (e.g., .claro .dijitButton .dijitButtonNode { ... }) but the dojox.mobile themes don't have this. What's up with that? Perhaps the theory is that mobile UIs are simpler and there won't be mixing and matching like you might find on desktop, but to me that would be a bogus argument because tablet UIs are going to be just as complex as desktop UIs. Maybe the extra CPU overhead from processing an extra class selector on each rule has a tangible performance impact on low-end smart phones. My instincts are that the dojox.mobile guys will say they have strong conviction that there should not be a prefix such as .custom and all of the "mbl*" class names are sufficient to prevent CSS classname collisions. (Although IMO better to pick a prefix less likely to collide with other classes)

My instincts are to go with an option 4 which is a variation of some aspects from 1-3. 
- I would leave the require for deviceTheme so that it is there for runtime suage, but find a way to not include it within page editor or render it harmless. 
- I wouldn't add a prefix to the CSS rules and instead (for mobile themes) only change the LINK or @import statements to pull in a different theme. 
- I would allow for multiple custom themes
- I would treat the existing "custom" theme as a read-only theme just like claro and sketch (and maybe if we can do the same for iphone, ipad, android, and blackberry themes) but maybe rename it for the sake of Maqetta to a different name such as "generic".
- It's OK for us to copy the read-only mobile themes out of dojox.mobile just like we do for claro. This is under the hood and users aren't aware of this.

**Comment by billreed63** [comment]
I agree with most of option 4, leaving the require for deviceTheme. requires that we add a theme class selector to the mobile theme css files. dojox.mobile.deviceTheme dynamically adds the device css files at runtime. They end up winning the cascade and therefore any style changes that are made in our theme are overridden (remember bug #1011). This is why I suggested adding a theme class selector to the css theme, if we leave the deviceTheme in the html, to ensure that the users style changes win the cascade. If we do not add the theme class name to the css selectors then we need to remove the deviceTheme requires, both at page deign and a run time to ensure that the users style changes are used. Removing the require deviceTheme could be complicated. 

When a mobile widget is dropped we would need to check the pages current theme, is the current theme a mobile theme? if not add the require deviceTheme. 

When the theme on the page is switched from the tool bar, is the theme being switched to a mobile theme? If so remove require deviceTheme. If the theme being switched from is a mobile theme and we are switching to a non mobile theme and there are mobile widgets on the page and the require deviceTheme.

The more I think about it the solution I like best for lack of complexity, making it less error prone and more predictable is:
option 3, I also like the idea of not coping the whole mobile theme just the selectors that are changed through theme editing.

**Comment by peller** [comment]
you can override the theme selection for deviceTheme now by simply defining config.mblUserAgent (#1011)  If we maintain that for custom themes, I don't think we would have to worry about a race condition anymore?

**Comment by peller** [comment]
I think the scheme proposed in #1011 would work fine for custom themes, no extra selectors necessary, if:
1. "custom" is passed to the deviceTheme API -- see setMobileDevice/setMobileTheme in the patch
2. dojox.mobile.loadCssFile is used to load the theme -- the css will get automatically unloaded if the theme switches
3. config.mblUserAgent is set in the document so that the custom theme is unconditionally used at runtime
4. a LINK for the CSS is injected directly into the model so it's there at runtime (it would have to be removed on theme switch)

Note that there's also a dojox.mobile.themeMap which we could manipulate at design time, but I don't think there's any easy way to modify that for runtime... might get into the same sorts of race conditions we had before.

**Comment by billreed63** [comment]
I like the config.mblUserAgent='custom' idea. When can we move the fix for #1011 to the master?

**Comment by billreed63** [comment]
Adam, Bill and I went over Adam's proposals for how to manage mobile theme switching and we liked what we heard. These fixes address both #1011. Here is my attempt at a summary:
- Normally with dojox.mobile, deviceTheme.js sniffs out the device and auto-loads the correct CSS
- If dojox.mobile sees "custom", it doesn't load any CSS files (did I get that right?)
- Adam worked with Kamiyama-san to add hooks to dojox.mobile so that the default behavior could be overridden. In particular:
  -- There is a new dojo config (mobileUserAgent?) that, if set, will cause dojox.mobile to skip the sniffing logic
  -- loadDeviceTheme() function now takes an argument, so an external agent (e.g., Maqetta) can tell dojox.mobile to load CSS files for a particular device
- Adam added a dojo.connect listener to loadCSSFile() so that Maqetta can know when dojox.mobile has loaded a CSS file, so we can maintain a list of CSS stylesheets to remove when we switch to a different device

Now that I'm writing these notes, I'm not sure I fully comprehended all aspects of the approach. 
- For standard devices using built-in themes (e.g., iphone using iphone.css), will Maqetta let dojox.mobile pull in the appropriate CSS files, or does Maqetta prevent dojox.mobile from doing auto-loading and instead Maqetta loads the CSS files itself?
- For custom themes built with theme editor, it sounds like Maqetta needs to load the CSS files itself because dojox.mobile doesn't load CSS files when the device is "custom". Right?

Also, we aren't going to add extra .iphone, .android or .mytheme selectors to the dojox.mobile CSS files. Instead, the original iphone, android, etc. CSS files will be left exactly as is. 

Jon

**Comment by billreed63** [comment]
I have done some testing with the proposed fix for #1011, and have found some issues that we still need to address. Granted they may just be my lack of understanding...

dojox.mobile.deviceTheme loads iphone.css if it can not find a theme name match in the dojox.mobile.themeMap. So in the case of 'custom' (which does not match the default 'Custom') iphone.css is loaded. We can change this behavior by changing the dojox.mobile.themeMap before deviceTheme require.

``` html

<script type="text/javascript" djConfig="parseOnLoad: true, mblUserAgent: 'mobile3'" src="lib/dojo/dojo/dojo.js"></script>
<script type="text/javascript">
dojo.require('dojox.mobile');
dojo.require('dojox.mobile.parser');
dojox.mobile.themeMap=[["Android","android",[]],["BlackBerry","blackberry",[]],["iPad","iphone",[require.toUrl("dojox/mobile/themes/iphone/ipad.css")]],["Custom","custom",[]],["mobile3","",["themes/mobile3/mobile3.css"]],[".*","iphone",[]]];
dojo.require('dojox.mobile.deviceTheme');
dojo.require('dojox.mobile.compat');</script>

```

I also played with the loadDeviceTheme(), we need to add code to dojox.mobile.deviceTheme to remove the old css themes. The current implantation just adds the new themes

``` javascript
dm.loadDeviceTheme = function(/*String?*/userAgent){
        // summary:
        //      Loads a device-specific theme according to the user-agent
        //      string.
        // description:
        //      This function is automatically called when this module is
        //      evaluated.
        var t = config["mblThemeFiles"] || dm.themeFiles || ["@theme"];
        if(!lang.isArray(t)){ console.log("loadDeviceTheme: array is expected but found: "+t); }
        var i, j;
        var m = dm.themeMap;
        userAgent = userAgent || config["mblUserAgent"] || (location.search.match(/theme=(\w+)/) ? RegExp.$1 : navigator.userAgent);
        for(i = 0; i < m.length; i++){
            if(userAgent.match(new RegExp(m[i][0]))){
                var theme = dm.currentTheme = m[i][1];
                var files = m[i][2];
                for(j = t.length - 1; j >= 0; j--){
                    var pkg = lang.isArray(t[j]) ? (t[j][0]||"").replace(/\./g, '/') : "dojox/mobile";
                    var name = lang.isArray(t[j]) ? t[j][1] : t[j];
                    var f = "themes/" + theme + "/" +
                        (name === "@theme" ? theme : name) + ".css";
                    files.unshift(require.toUrl(pkg+"/"+f));
                }
                    //remove old css files
                        if (dojox.mobile.loadedCssFiles){
                           var lcss = dojox.mobile.loadedCssFiles;
                           for(j=0;j<lcss.length;j++){
                              dojo.query('link[href="' + lcss[j].toString() + '"]').orphan();
                          }
                        }
                        dojox.mobile.loadedCssFiles = files;
                                /////////////////
                for(j = 0; j < files.length; j++){
                    dm.loadCssFile(files[j].toString());
                }
                domClass.add(win.doc.documentElement, theme + "_theme");
                break;
            }
        }
    };
```

**Comment by peller** [comment]
right now, Maqetta is responsible for removing the old css (see `//remove old css files`)

**Comment by peller** [comment]
> - For standard devices using built-in themes (e.g., iphone using 
>   iphone.css), will Maqetta let dojox.mobile pull in the appropriate 
>   CSS files, or does Maqetta prevent dojox.mobile from doing auto-
>   loading and instead Maqetta loads the CSS files itself?

Right now, an attribute stored on the BODY tag is used to serialize this state and set the config.mblUserAgent override when loaded in design mode. Basically, the logic for actually loading the CSS is all left to dojox.mobile.deviceTheme.

> - For custom themes built with theme editor, it sounds like Maqetta 
>   needs to load the CSS files itself because dojox.mobile doesn't load
>   CSS files when the device is "custom". Right?

Correct.  Maqetta will have to set config.mblUserAgent=custom in the source AND make sure the appropriate LINK is in the document for the CSS.  On theme switch, it will have to yank that info.

**Comment by billreed63** [comment]
if we define dojox.mobile.themeMap before dojox.mobile.deviceTheme is included we do not need to include the link in the document.

``` html
dojox.mobile.themeMap=[["mobile3","",["themes/mobile3/mobile3.css"]],[".*","iphone",[]]];
dojo.require('dojox.mobile.deviceTheme');
```

or better yet, this would make setting the device irrelevant 

``` html
dojox.mobile.themeMap=[[".*","",["themes/mobile3/mobile3.css"]]];
dojo.require('dojox.mobile.deviceTheme');
```

adding our theme to the existing themeMap is more difficult. dojox.mobile.themeMap is not defined until deviceTheme executes which adds the theme files to the document. We would then need to add the theme to the beginning of the themeMap array, remove the currently added CSS files and then load the new theme

``` html
<script type="text/javascript" djConfig="parseOnLoad: true, mblUserAgent: 'mobile3'" src="lib/dojo/dojo/dojo.js"></script>
<script type="text/javascript">
dojo.require('dojox.mobile');
dojo.require('dojox.mobile.parser');

dojo.require('dojox.mobile.deviceTheme');
dojo.require('dojox.mobile.compat');</script>
<script type="text/javascript">
function setMobileTheme(){

var dm = dojo.getObject("dojox.mobile", true);

dm.themeMap.unshift(["mobile3","",["themes/mobile3/mobile3.css"]]);
// need to add code to remove the old theme here
dm.loadDeviceTheme('mobile3');
}
dojo.ready(setMobileTheme);

```

**Comment by jhpedemonte** [comment]
If a user selects a custom mobile theme, then we don't need to have **deviceTheme.js** in the file anymore.  Let's just add logic that removes that resource if the user selects a custom theme.

**Comment by billreed63** [comment]
It's not that simple:

<ul>
<li>
Theme change would need to remove the deviceTheme and add the link, or reverse this if going back.
</li>
<li>
Every mobile widget that is dropped would need to check the current theme in use and add deviceTheme if no custom mobile theme is in use. If the custom mobile theme is in use do not add deviceTheme.
</li>
<li>
The user could only have one custom mobile them and could not automatically switch themes based on device. We have a question on the maqetta's user group "What is the method if I only need to customize the android theme ? (without modify the android.css contained in the dojo framework)" It would be nice to let the user customize themes for each device.
</li>
</ul>


It seems like a reasonable request to provide the user with a way to modify themes for each device. This can be done by modifying the themeMap.

**Comment by billreed63** [comment]
#1023 needs to be fixed so we can use dojox.mobile.themeMap

**Comment by billreed63** [comment]
I do not think we need to copy the complete theme folder from mobile, I think the themes are compiled into one css file. @peller who would I ask about this?

**Comment by peller** [comment]
anything with @imports should get inlined, so, at least _when we have a build_ only the top css file should be needed.  In the meantime, I think we'll need the whole thing.

**Comment by billreed63** [comment]
When the user changes a theme for a mobile page we need to:
- Determine if the page is using dojox.mobile, add require fro deviceTheme if missing.
- Determine what mobile device(s) the theme supports.
  - We can assign devices for theme at theme creation time, based on base theme copied.
  - Let user select devices when adding theme to page
- If we allow users to create themes for each device then the theme selection dialog will need to allow users to select multiple themes. One for each device.

I am thinking that we need a different implementation of the theme selection for mobile html pages, that would allow users to select a mobile theme for each mobile device.

**Comment by JonFerraiolo** [comment]
Yes, I think what you say in last paragraph above is correct. One more comment - if we are going to do anything architectural like that, we need to take a step back and decide if this is the time to address the "delta themes" idea or continue with the old process of cloning existing themes.

**Comment by billreed63** [comment]
I like the delta theme's my only concern is that we have a short runway to preview 4. I think we can do this in two phases, use the copy approach for phase one and if time permits add in the delta logic.

I am also starting to think that we may need to introduce the idea of a themeMap for mobile devices. If the user creates multiple themes say one for each device and then wants to use these themes instead of the default mobile themes It would be nice if they could create a custom mobile theme map and use that on new pages instead of forcing them to redo that map on every page.

**Comment by JonFerraiolo** [comment]
@billreed63 - everything you say in previous comment makes sense to me.

**Comment by billreed63** [comment]
# Use cases:

## 1) Native styling is fine with author.

**Details:** Either the author wants native look&feel for his mobile application, or doesn't care about styling and is happy with whatever default styling we provide. 

**Proposed workflow:**

<ul>
<li> Defaults just work. Author never deals with mobile themes.</li>
</ul>


## 2) Author wants to create a custom theme that applies to all mobile devices.

**Details:** The organization which has commissioned the mobile app has its own visual styling standards, which are different than Dojo's default themes. These visual styling standards apply to all mobile devices. The author specifically does not want different styling for different devices.

**Proposed workflow:** 

<ul>
 <li>Author clones one of the built-in Dojo mobile themes via the New Theme... command. Our docs would suggest that in this scenario (i.e., one theme across multiple devices) that the user clone the "custom" theme.
 <li>After clicking on OK button in New Theme... dialog, the mobile theme editor appears and the user can modify the cloned theme to his heart's content. (Subsequently, user can use Open Theme... command to do further mods)
<li>To apply the theme to a particular HTML file:
<ul>
  <li> User clicks on the Switch Themes icon, chooses his new theme, clicks on radio button to apply to all devices, and
clicks OK
</ul>

<li>To apply the theme across all future HTML files:

<ul>
   <li>User opens up the "Settings->Theme sets..." dialog, with default theme set selected, chooses his new theme, clicks on radio button to apply to all devices, and clicks OK
</ul>

<li>To apply the theme across all existing and future HTML files: (Probably not available in Preview 4)

<ul>
 <li>User opens up the "Settings->Theme sets..." dialog, with default theme set selected, chooses his new theme, clicks on radio button to apply to all devices, click on a different checkbox near OK/CANCEL buttons that says apply to existing HTML files also, and then click OK
</ul>

</ul>

## 3) Author wants to create different custom themes for different devices

**Details:** The organization which has commissioned the mobile app has its own visual styling standards, where there are different visual standards for different mobile platforms. This is mostly in the case where the organization wants a mostly native look, but tweaks some of the visual design to match corporate branding standards.

**Proposed workflow:**

<ul>
<li>For each target device, the author clones one of the built-in Dojo mobile themes via the New Theme... command. Our docs would suggest that in this scenario that the user clone the "iphone" theme for iphone devices, clone the "android" theme for android devices, etc.
 <li>After clicking on OK button in New Theme... dialog for each of these themes, the mobile theme editor appears and the user can modify the cloned theme to his heart's content. (Subsequently, user can use Open Theme... command to do further mods)
<li>To apply the themes to a particular HTML file:
<ul>
  <li>User clicks on the Switch Themes icon, chooses one of his new themes, clicks on radio button to apply to selected devices, makes sure the correct devices are selected, and then clicks OK. Repeat for other target devices.
</ul>

 <li>To apply the theme across all future HTML files:

<ul>
  <li>User opens up the "Settings->Theme sets..." dialog, with default theme set selected, for each device, chooses the relevant theme, choose the relevant devices, and clicks OK
</ul>

<li>To apply the theme across all existing and future HTML files: (Probably not available in Preview 4)

<ul>
  <li>User opens up the "Settings->Theme sets..." dialog, with default theme set selected, for each device, chooses the relevant theme, choose the relevant devices, click on a different checkbox near OK/CANCEL buttons that says apply to existing HTML files also, and then click OK
</ul>

</ul>

## 4) Author wants to create and manage multiple custom per-device themes as a "theme set"

**Details:** The author might want to try out various mobile themes and send his prospective themes around for others to review. Sometimes, he will want to make parallel changes for different devices simultaneously. For example, he might have larger and smaller typeface themes for both iPhone and Android and want to see which theme people prefer.

**Proposed workflow:**

<ul>
<li>User can create new themes using New Theme... and then can create new theme sets via Edit->Theme Sets... and the "New" button that appears on that dialog.
<li>To have a particular HTML document switch from one theme set to another
<ul>
 <li>Bring up the Switch Themes dialog and choose a different option from the Theme Sets... menu.
</ul>

<li>To cause all existing HTML documents to switch to a different theme set (Probably not for Preview 4)

<ul>
<li>In the Theme Sets... dialog, select the new theme set, click on a different checkbox near OK/CANCEL buttons that says apply to existing HTML files also, and then click OK  
</ul>

</ul>

**NOTE:** We are proposing that the list of target devices includes an "other" option which applies whenever the user is running the application on an unknown device.

**Comment by billreed63** [comment]
Do we need two default theme sets, a desktop and a mobile?

desktop would not include the deviceTheme requires. Or do we have one theme set and always add the requires for mobile ?

**Comment by JonFerraiolo** [comment]
This opens up the whole issue of Dojo Mobile being sort of its own separate beast while at the same time largely interopable with Dijit. I'm not sure what's the right thing to do and what's feasible to do, but here goes:
- Desktop themes and mobile themes are largely orthogonal
- Only mobile themes participate in the theme set feature
- We put another tag in the metadata that indicates to which "theme category" that widget belongs (basically, desktop and mobile when talking about Dojo)
- We make a stab at making our features toolkit independent by defining our initial theme categories as 'dijit' (for Dojo desktop widgets) and 'dojox.mobile (for Dojo mobile widgets), or something like that
- If the page contains any widgets in the 'dijit' category (or on first widget added), then we stuff in an appropriate desktop theme into the doc. If the page contains any widgets in the 'dojox.mobile' category (or on first widget added), then we stuff in an appropriate mobile theme set into the doc. 
- (We really should have a server config file that lists the various themes that are available versus hardcoding the list)

Not sure if the above is good or practical...

**Comment by billreed63** [comment]
Theme sets have added an extra layer of complexity for round tripping,

When the user wants to change a theme on and existing page.

The HTML file would not contain the theme set directly, we would need to attempt to match the dojox.mobile.themeMap and the @import/body class to "known" them sets. If we do not find a match what do we do, select the default theme set and adjust the page to match?

If we have an existing page that does not contain any mobile widgets, and the user drops a mobile widget. We use the pages current desktop theme to attempt to locate a theme set? if no theme set match do we just default the mobile.

I am thinking we need a "hard" default if we can't figure out the theme set and the desktop needs to be set we set it to claro and if the themeMap needs to be set we just use the dojo.mobile.themeMap defaults.

I guess what I am saying is round trip theme sets would be "best effort"

**Comment by billreed63** [comment]
ToolbarButton -  is an oversight, It can only be dropped on a heading so I will make it a sub widget of header
slider - I has hopping slider could slide into the extra credit bag???
ContentPane - ContentPane currently has no styling rules in mobile themes, 
FixedSpliter/fixedSplitterPane - extra credit??
Overlay - is currently in untested is this correct? extra credit?

So I am thinking I update the theme switching/setting UI's and then come back and get the extra credit widgets...

**Comment by billreed63** [comment]
Update UI to this design
 http://maqetta.org:55556/maqetta/review/jferrai@us.ibm.com?revieweeuser=jferrai@us.ibm.com

**Comment by billreed63** [comment]
depends on #1091

**Comment by billreed63** [comment]
Hi Bill,
I've been poking around and discovered that there are actually 2 different vision stylings for TabContainer defined in the Claro theme. There is the default styling (what we are using today in Maqetta) and then there is an alternate "nested:true" styling (i.e., the styling you get if property nested:true is passed to widget constructor). When we talked with Janet and Julie in the past, they suggested that we use the alternate TabContainer styling for the theme editor's own tabs, but until now I didn't know how one activated this alternate styling. So, I suspect that we have figured out how to do the visual styling for a multi-tab user interface for theme editing.

The next question is how to organize the mobile widgets within the various tabs. My thinking is that we should align the widget breakdown that we have in the theme editor with the future widget breakdown that we will have when we do the Widget palette makeover. Pretty obvious: we shouldnt' confuse the user by offering different breakdowns in two different places within the app. Given that, here is an initial strawman proposal for how to organize the mobile widgets in both the widget palette and mobile theme editor:

Tab 1: Global - (In widget palette, this would be "Views") A single View widget with comments about how the same styling applies to View, ScrollableView and SwapView, plus another widget to allow global font changes. The long-term vision is that "Global" is where the cross-widget LESS variables can be changed.

Note: In the current mobile theme editor, you did the clever trick of updating the background of the whole mobile theme editor to match the background used for View widgets. But my opinion is that's going too far and I suggest using the idea, but scaling it back a bit. What I suggest is that for subsequent tabs there we use various container DIVs behind the various other widgets, and these container DIVs use the same background as used for View widgets

Tab 2: Headings & TabBars - Heading, ToolBarButton, TabBar and TabBarButton
Tab 3: Rects & Lists - RoundRect_, EdgeToEdge_, ListItem
Tab 4: Controls - Button, ToggleButton, Switch, CheckBox, RadioButton, TextBox, ComboBox, TextArea, ExpandingTextArea, Slider
Tab 5: Other - FixedSplitter, FixedSplitterPane, IconContainer, IconItem, Carousel, Overlay

Reasonable?

Jon

**Comment by billreed63** [comment]
Jon Ferraiolo: So, I'm hesitant about making the TextBox with the theme set name into a read/write field. I was thinking that the field would be read-only and that user would have to take an explicit action (click on Rename) to bring up a dialog to rename the theme set. But where are you thinking the add/delete buttons would be? On the left under the list of theme sets?
3:57:34 PM: Jon Ferraiolo: As + and - icons?
3:59:37 PM: William D. Reed: No, I was thinking replace the rename button with a plus and x icons  if the user hits plus we make a copy of the current theme set with the same name_1  x deletes the theme set ...
4:00:05 PM: William D. Reed: if the user types a new name in the edit box we rename the current theme set to that name...
4:00:33 PM: William D. Reed: We could add confirms for rename and delete if you like
4:03:35 PM: Jon Ferraiolo: I expect Julie&team would say put small plus/minus icons under the list of themes at the left. Then we could also add a 3rd icon for renaming. Would it be hard to change things in a few days? Seems like it wouldn't be a big deal, mostly finding the right icons, right? What I'm thinking is that you should implement something and then show it to Julie on Friday for feedback.
4:06:30 PM: William D. Reed: Yeah, that works.. I will leave the rename button since I have no idea what a rename icon would look like....
4:06:45 PM: Jon Ferraiolo: sounds fine
4:08:20 PM: William D. Reed: Can I leave the edit box readonly then when the user clicks rename change the edit box to read/write.. or is that subtle 
4:08:56 PM: Jon Ferraiolo: How hard to post a small dialog to change the name?
4:10:37 PM: William D. Reed: Seems simple....
4:11:15 PM: Jon Ferraiolo: famous last words, but maybe this time it turn out to be true?
4:12:04 PM: William D. Reed: can a dialog have a dialog.... doesn't that mess with the time space continuum???
4:12:44 PM: Jon Ferraiolo: there is that worry. Might mean the end of life as we know it, but to me it's well worth the risk

**Comment by billreed63** [comment]
- The (nested) tabs at the top should be pixel-perfect renditions of the claro theme nested tab treatment. I believe the only thing that is amiss now is the font, which can be fixed as follows (I believe):

#tcNestedParent .dijitTabContainerNested .dijitTabContainerTop-tabs {
background-color: white;
font-family: Verdana, Arial, Helvetica, sans-serif;
font-size: 12px;
color: #131313;
}
- The first tab "Primitive Widgets" is getting its border clipped on the left and top. This is because there is an outer DIV with margin:-5px. To fix the clipping, there are multiple options. On Chrome, the clipping mysteriously went away by simply changing to margin:-4px. But I wonder if the better approach would be to inject a ContentPane parent around the nested TabContainer and remove the margin:-5px entirely because the ContentPane should provide an 8px default padding inside.
- Per the email below (see down at the bottom), I would put "Global" as the first tab. I'm thinking ahead to when we support LESS and the global section would tend to have multiple global variables. I realize that there won't be much on the "Global" tab with Preview 4, but I think that's OK.
- As I describe in the email below, I'm sticking to my guns and would like to see 5 tabs total for Preview 4 as described below. I'm not sure if we will have any themeable widgets for the "Other" tab with Preview 4. If no widgets for Other, then of course we can leave that tab out for Preview 4.
- Within each pane, I would have the widgets organized vertically rather than horizontally. This will prepare the theme editor for the "longer-term" bullet below.
- For the form widgets, I would create a <table> with the form widget name in the first column and then the actual widget in the second column, resulting in:
  Button:         [widget]
  ToggleButton:   [widget]
  CheckBox:       [widget]
  Switch:         [widget]
  etc:
  In fact, this might be a good general approach across all of the panes, including the "Global" where we might say:
  View:           [widget]
- I'm not sure what's going on with the widget just below TextBox/ComboBox. Is it part of ComboBox?
- I would make the View widget bigger (e.g., 250px square) and include some text saying that changes to View will also apply to ScrollableView and SwapView. (Same sort of comment needed for styling sharing between the *List widgets)
- Even though ToolBarButton can only appear inside of a Heading, I suggest that it be separated out visually from the Heading widgets. It will be too confusing to users if we don't offer a simple "each widget is separate" approach on the theme editor. 
  
  > > ToolBarButton can only be placed as a dependent of  Header, we enforce this in the page editor. We would need a second header on the page wich would be confusing.
- I would make all of the List-oriented widgets widers, which should be possible given the vertical layout approach I am suggesting.
- For TabBar and TabBarButton, I would have a label that says:
  TabBar/TabBarButton:  [widget]
- The theme editor shows dotted outlines on the TD elements that are used for layout. This comes from content.css:91. The theme editor should override that style declaration somehow so we don't see the dotted lines.
- Longer-term (after Preview 4), I think it would be good to put the widgets inside of a silhouette. I think having a life-size silhouette for theme editing is equally valuable as having a life-size silhouette for page editing. Given the implementation issues, what I would suggest to pull this off:

For each pane in the theme editor, surround the content as follows:
   <div class="silhouette_and_pane">
      <object data="...the svg file" style="position:absolute; z-index:-1; left:..., top:..., width:..., height:..."></object>
      <div class="pane_content">...widgets are here...</div>
   </div>
I can probably do the work to integrate in the silhouettes.

Feel free to disagree with any of this.

**Comment by billreed63** [comment]
coding of this feature is complete changes and bugs will be tracked by other issues
