### ISSUE TITLE
Reviewer change emails should include link to review session

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1026]
@EldonReturn, @jmockler, @jhpedemonte

Javier noticed that when he received an email notifying him about review comments I had made, the email did not include a hyperlink to the relevant review session. We agreed that it would be a big time-saver for the author to be able to click on a link to open up the review session.

However, I wouldn't make this change right away. @waynevicknair might be evaluating the possibility of rolling the review UI into the core, at which point our URL strategies for review sessions are likely to change.

**Comment by JonFerraiolo** [comment]
Pushing to M5, Priority-Med

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
-> @aerwin M7 Prio-High

**Comment by aerwin** [comment]
Closing with above commit.
