### ISSUE TITLE
Files in 2-level deep nested folder do not show up without page refresh

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1027]
- Create a folder using default name "folder1"
- Select "folder1" and create a child folder named "folder1_child1"
- Select "folder1_child1"
- Click "New" menu and select "HTML..."
- Drop a couple widgets in the file and click save.

Result: the files view shows the folder but not the new file. Refresh page and files view is accurate again.

**Comment by billreed63** [comment]
Also second level folders are not used in the where drop down:

1) create folder1
2) Select folder1 and then create folder2 as sub folder of folder 1
3) Select folder2
4) From menu bar select new html file

The "Where" field"  of the new file dialog has the root folder not the folder selected in the file explorer

**Comment by jhpedemonte** [comment]
I was also seeing this for a single level folder on the build from early morning Jan 4.  However, I just tested from source and it worked fine.  Will need to retest with tomorrow's build (Jan 5).

**Comment by childsb** [comment]
The current resource selection from the explorer view isn't populating the new file dialog parent folder properly.  This can be avoided by changing the "where" manually to the new nested folder.  Then the new html file should show up.

**Comment by childsb** [comment]
moving to m5

**Comment by childsb** [comment]
This is working in m5
