### ISSUE TITLE
Custom widgets, SaveAs widget, widget import/export

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1030]
I couldn't find an existing bug for creating/sharing/importing custom widgets. What we are looking for is the ability to save the existing HTML file as a "widget" so that it can be added to the widget palette and used within other compositions, along with ability to share that widget with others and import widgets created by others.

One of the challenging parts of this issue is figuring out how to make variable aspects of the widget, particularly how to allow users to define widget properties.

**Comment by jhpedemonte** [comment]
@childsb, what's the current status of this?  I thought it was only available if a preference was set, but I don't see that preference.

**Comment by JonFerraiolo** [comment]
Pushed to M5

**Comment by JonFerraiolo** [comment]
Reset to Prio-Med for M5

**Comment by jhpedemonte** [comment]
-> M6

**Comment by childsb** [comment]
Finished first pass impl.
