### ISSUE TITLE
Some ability to recover when hung

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1032]
@peller, @billreed63

This one probably will take some discussion.

There are various situations where Maqetta just sits there spinning on a particular file and a user can only get out of the problem by appealing to a sysadmin (ie. us) to hand-edit their .workbenchSettings file so that the offending file is removed from the list of open files. Of course, most of these hangs reflects an underlying bug in Maqetta, so we should fix those bugs. But because Maqetta is so open-ended, even when we fix many, many bugs, users will be able to hang themselves by telling Maqetta to open a file that has some content that triggers an obscure bug.

Two options come to mind. We should probably do both, or some similar alternative:
- Define a URL parameter that tells the server to clear the list of currently open editors
- Put some sort of setTimeout that sees if initialization is complete, and if not, puts up a warning to user and allows him to cancel file opening.

**Comment by jhpedemonte** [comment]
Yes to both options.  Maybe add a third as well:
- Define a URL paramour that tells the server to clear the workspace.

**Comment by billreed63** [comment]
We need a checkbox on the log in screen that enables this parameter. "Force close of open editors"

**Comment by peller** [comment]
First rule: if there's an error, surface it: #883.  Right now, if an exception throws, it blows right through the stack and leaves the loading UI up. We should put up an "aw, snap" sort of thing.  The end result isn't much different, but it will go a long way toward troubleshooting and perhaps make things a bit less frustrating for the user.

**Comment by jhpedemonte** [comment]
Yes, agreed with Adam.  We need better error handling all around.

**Comment by JonFerraiolo** [comment]
Pushing to M5 with Priority-Med

**Comment by jhpedemonte** [comment]
How much of an issue is this any more?  I think that due to our many bug fixes, it is rare that something like this happens.  

And now that most everything is async, the app should fully load, but a file may not.  The user will then be able to close that file.  Or delete it.  Or create a new project.

Close this?

**Comment by JonFerraiolo** [comment]
I suspect it's rare for _us_ to have this problem now because we know how to operate the product but our _users_ will do things that we won't anticipate.

I suggest leaving this open for awhile longer as a reminder, but probably we will break this down into a few separate tasks. As @peller suggests, maybe part of the "solution" is better catching of exceptions and better surfacing of the problem so users will be able to report what went wrong. 

But nevertheless, I think we still need a magic URL parameter (or alternative) that says "restart with no open files", and another major URL parameter  (or alternative) that resets the user's workspace, and one more that says "ZIP up my workspace" in case the user wants to have a copy of his files before he resets his workspace.

**Comment by jhpedemonte** [comment]
-> M7

Opened #1914 to handle URL param.  Moving this bug further into future.

**Comment by peller** [comment]
#1914 is a good take away.  Otherwise, I don't think this issue is worth keeping open unless we have a specific code path to address.

**Comment by jhpedemonte** [comment]
Given Adam's comment, closing this, unless we have a definite path in mind.
