### ISSUE TITLE
Outline palette should show region attribute for ContentPane children of BorderContainer

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1038]
@billreed63, @peller, @jhpedemonte

Right now looking at the Outline palette users don't have a clue about which ContentPane is which region. Perhaps we can add [region=top] or whatever as part of the "meaningful name", as in:

ContentPane [region=top]

which would appear in both Outline palette and Properties palette.

Would want to generalize this somehow so similar things can happen for other widgets, perhaps more widget metadata that identifies attributes that should appear as part of "meaningfulname".

**Comment by peller** [comment]
I like this as an alternative to #1037

**Comment by jhpedemonte** [comment]
Perhaps a `Helper.getDescriptor()` function that could be defined per widget?

**Comment by JonFerraiolo** [comment]
Pushed to M5

**Comment by JonFerraiolo** [comment]
Reassigned to @doronrosenberg , M6, Prio High

**Comment by doronrosenberg** [comment]
Looks like we have a Helper.getWidgetText() that is called at the right place (Widget.getLabel()), sounds like the right place to  me.

**Comment by JonFerraiolo** [comment]
I don't think getWidgetText is the right hook. It looks to me like getWidgetText is restricted to what it says: it gets the widget's innerText/textContent, where a helper can pull in the text. The getLabel() function then surrounds that text with double quotes (using CSS :before and :after with content: property). For ContentPane and regions, I don't think we want double-quotes, and certainly in the general case there will be times we don't want the double-quotes.

OK, if you buy the above argument, then the question is what to do instead? My best suggestion is that we add yet another section to the string returned by getLabel(). As things stand now, we have 3 sections: widget name, class, and text. Maybe we should add an optional 4th section where a widget can provide a helper that returns some additional rich HTML markup to tack onto the end of the getLabel() string, where getLabel() provides a SPAN element into which the custom markup will go as an innerHTML assignment.
