### ISSUE TITLE
Current flow-vs-absolute status shows on toolbar

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1039]
@jmockler, @billreed63

Somehow or other, the toolbar should tell people at a glance whether they are in absolute or flow positioning mode. Here are a couple of UI options:
- Alternating toolbar icons. (I got alternating icons working for device rotation, but the implementation is sort of kludgy)
- Change into a dropdownselect or dropdownbutton where button reflects current status

**Comment by jhpedemonte** [comment]
Alternating toolbar icon

**Comment by JonFerraiolo** [comment]
Push to M5, along with #1149?

**Comment by jhpedemonte** [comment]
-> M6

**Comment by peller** [comment]
-> M7

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo M7 Prio-Med should be fixed as part of M7 UI makeover effort

**Comment by JonFerraiolo** [comment]
Closing. Was fixed as part of M7 UI makeover effort.
