### ISSUE TITLE
Sometimes files appear as dirty even when not changed

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1040]
@peller, @jhpedemonte, @billreed63, @childsb

We still have some situations where files are flagged as dirty even though no changes have been made to the file.

(Need to beef up this bug report with reproducible scenarios)

**Comment by peller** [comment]
see #1138 for a scenario

**Comment by childsb** [comment]
Fixed with a couple commits #08dd0e7313fd2f7813d1a21c68ec9b257750d251  and others...
