### ISSUE TITLE
View icons should toggle on/off?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1042]
@jmockler

A user says: 3. The “Split Vertically/Horizontally” button does not toggle on and off as one would expect it to. 

I find myself also wishing that the view icons would toggle on/off or that there was a close button (and "X") on the source pane.

**Comment by aerwin** [comment]
--> no milestone to M7

Maybe a dup of #2761.

**Comment by jhpedemonte** [comment]
"Toggle" doesn't sound right to me.  As I mentioned in #2761, I would expect the current view of the 4 to be _highlighted_.

Also, I don't like your 2nd idea, which is to have a close button on the source pane.  That doesn't jibe with our current setup and would treat the source view as an "overlay" on top of the VE, which isn't the case.

**Comment by JonFerraiolo** [comment]
Should be addressed as part of M7 UI makeover effort.

**Comment by JonFerraiolo** [comment]
Fixed as part of M7 UI makeover.
