### ISSUE TITLE
Some folders shouldn't allow new HTML files inside

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1045]
A user says: "Since users cannot create a new page in any default folder other than “.” (e.g., “lib” or themes”), those folders should not be selectable when creating a page. Otherwise no error message given, and the new page is simply not created – which can lead to some confusion."

Note that with Preview 3 we fixed bugs with putting HTML files in nested folders. Nevertheless, we should find a way to prevent users from putting HTML files into "lib" or "themes.

**Comment by jhpedemonte** [comment]
Well, we should have the concept of **read-only** folders (if we don't already, then we should do that).  Then, in the file dialog, when displaying the files of the project, grey out (disable) any read-only folders.

**Comment by JonFerraiolo** [comment]
This bug goes beyond read-only and says that certain directories might allow users to edit some files (e.g., css files), but maybe not allow saving of HTML files. That part of this bug is questionable about whether we should include special code to disallow HTML files into particular folders while allowing other file types. My thinking now is that read-only support is sufficient for time being and adding logic to constrain what files types can be saved in particular folders should either never get implemented (90% likelihood) or we should push that off into future for when we would have more clarity about how to deal with constaints on file saving (10% likelihood).
