### ISSUE TITLE
Should Maqetta-created ZIP files work via file:

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1048]
Users are trying to create a ZIP and then run on their local system via File Open (which results in file: protocol). Docs with Dojo widgets won't work with the way Maqetta sets up Dojo - only works if the ZIP is unzip'd into a web server and launched via http://localhost/*.

Is there any way we can get Maqetta-created ZIPs to work with file: protocol? I realize this is low priority in short-term, but maybe this would work if we used dojo.xd.js instead of dojo.js or maybe offered a CDN option???

**Comment by peller** [comment]
Not sure why they wouldn't work.  Some browsers have security restrictions that prevent the xhrs over file: necessary to bootstrap Dojo (at least pre 1.7) but that can be worked around with various security settings like [this one for Firefox](http://kb.mozillazine.org/Security.fileuri.strict_origin_policy).  FWIW, starting with Dojo 1.7, there is no more XD loader.  The regular loader is supposed to work cross-domain.  AMD was based on some of the early Dojo XD work.

**Comment by peller** [comment]
I suggest we close this.  Whether the content works over file: or not depends on the toolkit used and the user's browser configuration.  We can document this limitation, but I don't think we should go too far except to point out that these are external factors.

**Comment by JonFerraiolo** [comment]
closing
