### ISSUE TITLE
Wrong inlineEdit metadata for dojox.mobile.Button?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1055]
@billreed63, @peller

In widgets.json, the inlineEdit target for dojox.mobile.Button is:

```
"property": "label",
```

but Dirk says below that this fails when he actually deploys on the device. It might be that inlineEdit should point to innerHTML instead of the label attribute.

(From http://groups.google.com/group/maqetta-users/browse_thread/thread/dbf6edabbfcea7e5)

Hi,

I developed a mobile app. However, I am not able to transfer this into
a native Android-App using phonegap. Creating a dojox mobile app
directly in Eclipse works fine. For example the button widget created
by Maqetta seems to cause problems (when I remove the label option it
works fine).

<button label="Help" dojoType="dojox.mobile.Button" style="height:
4.5em; margin-top: 1em; width: 85%;"></button>

Can anyone point out the reason for this to me? Is there a tutorial
describing the process of Maqetta --> native app?

Thanks,

Dirk

---

Dirk,
Fantastic that you are going the full path from Maqetta to PhoneGap!

Regarding the problem with 'label', I'm on the expert in this area,
but my guess is that Maqetta Preview 3 has a bug because it is
stuffing the Button's text into the 'label' attribute rather than
innerHTML. Maybe the 'label' approach works fine when running the UI
within Maqetta (because maybe various other parts of Dojo get pulled
in), but when you run the page outside of Maqetta, things die (because
those other parts of Dojo are missing). If my theory is correct, it's
a Maqetta bug that we should be able to fix easily for the next
release (November).

For the time being, what I suggest trying is manually removing the
'label' attribute and putting the button's label as the content of the
<button> element, such as <button dojoType="dojox.mobile.Button"
style="height:4.5em; margin-top: 1em; width: 85%;">Help</button>

I hope one of the Maqetta team members with more depth of knowledge in
this area will also respond to confirm whether my theory is correct.

Regarding whether there is any documentation on going from Maqetta to
PhoneGap, no, at this time we don't have any specific documentation on
that. Given that early adopters such as you are going all the way from
Maqetta to PhoneGap, it seems likely we will provide such
documentation in the coming months. (Not now: we are all occupied
writing code these days.)

However, Maqetta creates the same Dojo HTML markup that you would
create if coding Dojo Mobile by hand, so other documentation on how to
use Dojo Mobile with PhoneGap should apply to Maqetta-created HTML
files, also. In doing a search, I found this article from my IBM
colleagues: http://www.ibm.com/developerworks/library/wa-getstarteddojo/.
(If you are already using PhoneGap, uou might already know everything
from that article.)

Jon

**Comment by jhpedemonte** [comment]
To Dojox Mobile, it doesn't matter whether you put the value in the **label** attribute or in **innerHTML**.  For example, just check the [developerworks](http://www.ibm.com/developerworks/library/wa-getstarteddojo/) link you posted -- it shows several widgets using 'label'.

If the use of 'label' attribute really is the issue with the Maqetta->PhoneGap transfer, then I'd say that's a bug with PhoneGap, not fully supporting Dojox Mobile.

But more study is necessary, need to investigate PhoneGap.

**Comment by JonFerraiolo** [comment]
You could be right that 'label' is supported in dojox.mobile.Button, but I really don't see how PhoneGap would affect dojox.mobile. It's orthogonal technology. PhoneGap simply provides a cross-platform shim layer for device APIs that is independent (and works with) a variety of mobile toolkits, including both dojox.mobile and jQuery mobile. Maybe there is some surprising clash between the technologies, but I think it's more likely that there is an bug with dojox.mobile or a bug with how Maqetta creates source code (e.g., maybe we are missing a dojo.requires). One way to tell would be to try to run Dirk's application on a mobile phone in the browser and see if it fails there, too, when PhoneGap is not involved at all.

**Comment by billreed63** [comment]
This one might be hard to figure out without actually doing the maqetta -> phoneGap -> steps. And in it would be a good article to publish on devloperworks.

**Comment by jhpedemonte** [comment]
Bill, we're looking into that right now.

**Comment by JonFerraiolo** [comment]
Note that I changed ListItem to use innerHTML rather than 'label': 3e700f4da9 . 

OK to push to M5 and raise to Priority-High. We really shouldn't keep pushing this one out, but I think it's too late in M4 cycle to attempt to fix.

**Comment by jhpedemonte** [comment]
I'm thinking that for this to be done properly, we'll need to refactor @JonFerraiolo's changes from 3e700f4da935ea9e4c55a3462eb22e0e332ff936 and make them general to all widgets.  See my comments in that commit.

Based on that, moving to M5/Priority-high.

**Comment by doronrosenberg** [comment]
fyi, dojo 1.7 and the new Phonegap 1.5 do not like each other, namespace pollution fun.

**Comment by doronrosenberg** [comment]
So right now we already have textContent, which will use innerHTML.  Does changing it to "maqetta.innerHTML" to make it namespaced sound good?

**Comment by peller** [comment]
@doronrosenberg, what's the namespace pollution between dojo and phonegap?

**Comment by peller** [comment]
should we be using innerHTML or innerText?

**Comment by doronrosenberg** [comment]
@peller, they define a global require/declare, see http://groups.google.com/group/phonegap/browse_thread/thread/f5726de4433289d

**Comment by doronrosenberg** [comment]
We want innerHTML in case you want html markup inside

**Comment by JonFerraiolo** [comment]
Yes, innerHTML. The whole point of this bug in going from 'label' to innerHTML is to allow for rich markup for the ListItem content. 

Aside: also note that Firefox doesn't support innerText. Have to use textContent instead to work across all browsers if you want text-only content where markup characters aren't parsed.
