### ISSUE TITLE
Moving widget doesn't preserve all attributes/properties

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1056]
When a widget is moved from one location to another, under the covers Maqetta destroys the old widget and creates a new one.  However, it seems that all the attributes/properties of the old widget aren't passed on to the new widget, and that can cause some issues.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
Be sure to trace through the debugger carefully with some of the existing widgets where moving a widget doesn't drop attributes/properties. As I remember, this is working pretty well now with existing widgets. With some of the dojo mobile widgets, maybe some of the assumptions in the code are no longer true.

**Comment by jhpedemonte** [comment]
# Test Case 1
- Add Heading. Set custom text (i.e. "Fixed Heading").
- In Properties, add an 'id' (i.e. "h1_0") and set 'fixed' to "top".
- Add ScrollableView after Heading.
- Drag Heading into ScrollableView.

## Before Move

src:

``` html
<h1 label="Fixed Heading" dojoType="dojox.mobile.Heading" id="h1_0" fixed="top"></h1>
```

dom:

``` html
<h1 label="Heading" id="h1_0" dojotype="dojox.mobile.Heading" class="mblHeading mblHeadingCenterTitle" style="" widgetid="h1_0">
    <span class="mblHeadingSpanTitle" style="">Fixed Heading</span>
    <div class="mblHeadingDivTitle">Fixed Heading</div>
</h1>
```

## After Move:

src:

``` html
<h1 label="Fixed Heading" dojoType="dojox.mobile.Heading" fixed="top"></h1>
```

dom:

``` html
<h1 label="Heading" id="Heading_1" dojotype="dojox.mobile.Heading" class="mblHeading mblFixedHeaderBar mblHeadingCenterTitle" style="top: 0px; " widgetid="Heading_1">
    <span class="mblHeadingSpanTitle" style="">Fixed Heading</span>
    <div class="mblHeadingDivTitle">Fixed Heading</div>
</h1>
```

## Notes:
- DOM doesn't show the `fixed` property either before or after the move, but it is there in the object instance. I assume this is because we change the property in the **Properties** view, which adds it to the object instance, but not to the DOM.
- The custom `id` property was lost in the source and DOM.

**Comment by jhpedemonte** [comment]
# Test Case 2
- Add Heading. Set custom text (i.e. "Fixed Heading").
- In Properties, add an 'id' (i.e. "h1_0") and set 'fixed' to "top".
- Add ScrollableView after Heading.
- **Save file, close, reopen.**
- Drag Heading into ScrollableView.

## Before Move

src:

``` html
<h1 label="Fixed Heading" dojoType="dojox.mobile.Heading" id="h1_0" fixed="top"></h1>
```

dom:

``` html
<h1 label="Fixed Heading" dojotype="dojox.mobile.Heading" id="h1_0" fixed="top" class="mblHeading mblFixedHeaderBar mblHeadingCenterTitle" style="" widgetid="h1_0">
    <span class="mblHeadingSpanTitle" style="">Fixed Heading</span>
    <div class="mblHeadingDivTitle">Fixed Heading</div>
</h1>
```

## After Move:

src:

``` html
<h1 label="Fixed Heading" dojoType="dojox.mobile.Heading"></h1>
```

dom:

``` html
<h1 label="Heading" id="Heading_0" dojotype="dojox.mobile.Heading" class="mblHeading" style="" widgetid="Heading_0">
    <span class="mblHeadingSpanTitle" style="">Fixed Heading</span>
    <div class="mblHeadingDivTitle">Fixed Heading</div>
</h1>
```

## Notes:
- After move, `id` & `fixed` properties lost in both src and DOM.

**Comment by JonFerraiolo** [comment]
I'm not sure about the details of this particular case, but this might be due to the following. When we do a ModifyCommand and create a "data" object that holds the data for the old widget and from which we create the new widget, we pull properties from the canvas DOM (i.e., from the dijitwidget), but with ScrollableView and "fixed", under the hood Dojo is moving things around underneath us, so the logic ends up pulling the data for the "data" object from the wrong nodes. As I remember from my forays a month ago, this was one reason I created a getPropertyValue helper. But my memory is somewhat fuzzy.

**Comment by jhpedemonte** [comment]
The test cases above are very similar, except that in the 2nd one we save, close and reopen the file before doing the widget move.

There are some differences in the **before** state, mainly that the `fixed` property does not get added to the DOM when adding it through the **Properties** view.

Not that it matters, since the `fixed` DOM attribute is lost when moving the widget, in Test Case 2.

**Comment by jhpedemonte** [comment]
(cc @childsb, who might have some insight on the old smash code)
- `id` isn't saved because `getData()` is called with `identity` === false, from `SelectTool.onExtentChange()`.
  - _Why? Why wouldn't we want to save the ID when moving a widget?_
- `fixed` isn't saved because `_Widget.getPropertyValue()` returns false.  This is because the Heading object instance doesn't have a `fixed` property.
  - _Jon has a fix for this (created a `getPropertyValue()` helper for Heading and TabContainer widgets), but I'm still not completely sold on it._
- Of course, the latter wouldn't be a problem if the DOM attrs were carried over in the move. As it stands, the widget after the move is different than the widget before the move.

I don't really like the way this is architected (remove DOM of old widget, pull properties of old widget, create new widget using those properties). I'm assuming that's the old smash code.

The main issue is that the 3rd step (create new widget using properties of old widget) pulls the HTML source from the metadata, rather than from the old widget. I think that's a major flaw here. At least, that would preserve any DOM attributes that aren't handled by the widget's object instance properties.

I can see the reason for doing a destroy/recreate, as happens in other parts of the code -- if we're moving a widget to have a new parent, that can affect how that widget gets initialized.  So we need to keep that step.

So if we want to make minimal changes here, I think the steps for **moving a widget** would be something like this:
- Get properties and data from old widget (i.e. call `getData()`).
- Get the source from the old widget (`_srcElement.getText()`?)
  - How is this affected by widgets with children?
  - This could probably be a step of `getData()`.
- Create new widget from that data.
  - Amend `createWidget()` to use source from old widget instead of from metadata (if widget source is provided).
- Create CompoundCommand, consisting of AddCommand (new widget) and RemoveCommand (old widget).

Does that sound about right?

**Comment by jhpedemonte** [comment]
Opened #1062 to track issue with the `id` attr not persisted when moving widgets.

**Comment by jhpedemonte** [comment]
Actually, on **master** branch, I notice that moving a **Label** causes its text to be duplicated.  Need to fix that.

**Comment by jhpedemonte** [comment]
Had to revert the main part of first commit, since it was causing other issues (#1176).

While we were able to fix the problem of the `fixed` attribute hot being copied, issues remain (see `label` from the DOM in [test case 2](https://github.com/maqetta/maqetta/issues/1056#issuecomment-2230144).

Currently the code path is something like this:
1. Save data (properties/attributes) of widget to be moved.
2. Delete that widget.
3. Create a new widget (source and DOM) of same type, pulling all info from metadata.
4. Instantiate object instance (JS) of object, based on new DOM node.  Pass in saved data, which sets those properties/attributes on new widget.

This algorithm works for the "easy" case, but starts to fall apart when adding any complexity.

At the very least, the code should be rewritten to do what I had previously: when moving or copying, take the source from the moved/copied widget, not from metadata.

---

Two failures with current code (in addition to that mentioned above):

> 1. Add label to page.
> 2. In source view, add `data-label="foo"` attribute to `<label>`.
> 3. Copy and paste.
> 
> Result: New label does not have the attribute.

and:

> 1. Add label to page.
> 2. In source view, add bold elements around the inner string: `<b>Label</b>`.
> 3. Copy and paste.
> 
> Result: New label consists only of `<label></label>`; inner text is missing.

**Comment by jhpedemonte** [comment]
The correct way to do this (for move/copy of widgets):
1. Create a new widget (in DOM and HTML model) based on source from original widget.
2. Instantiate the widget instance (i.e. DijitWidget, HTMLWidget, etc), passing in newly created node.

This should basically shadow what we do when a page is first loaded.  There, the code already exists, but it is parsed to create the model and the widget instance is created depending on the type (I believe during the `attach()` phase).  This may require refactoring this startup code so that it can work on both full pages and partial code, and can then be called from MoveCommand/CopyCommand (instead of having the latter calling `createWidget()`).

**Comment by JonFerraiolo** [comment]
I poked around the code some and here is what I'm seeing today when we open an existing document:
- We create a model from the HTML sources (PageEditor.js:196)
- We temporarily set the user iframe's body's innerHTML to the text version of the BODY (Context.js:929)
- We invoke the dojo parser on the innerHTML content (Context.js:1008)
- We call `_attachAll()`, which recursively calls _attachChildren on all DOM nodes (Context.js:1072)
- `_attachChildren()` calls `getWidget()` on each DOM node (Context.js:1077)
- `getWidget()` looks at the DOM node for 'widgetid' and other attributes, and (as a side effect) invokes the appropriate dvWidget constructor to build the Maqetta authoring data structures (widget.js:685)
- Finally, the widget.attach() function is called, but in most cases its a no-op (_Widget.js:667)

Note that `createWidget()` is never invoked when opening an existing file.

Reminder: we have talked forever about cleaning up `getWidget()` to remove its "side effect" of invoking the dvWidget constructors if the dvWidget data hasn't been added to a widget yet.

So, I'm thinking that it might require multiple refactorings in order to have common code for using the same code path for ModifyCommand and file opening, but just looking at cleaning up ModifyCommand, maybe this approach will work:
- Extract "outerHTML" for the widget's DOM node from the model, stash away for later use
- When adding the widget back in, stuff in this outerHTML, then invoke the dojo parser on this root node of the outerHTML, then recursively call _attachChildren() on outerHTML nodes

**Comment by jhpedemonte** [comment]
@JonFerraiolo, responding to your [previous comment](https://github.com/maqetta/maqetta/issues/1056#issuecomment-2735933), couldn't we just do the exact same steps for initial widget creation, also?

It's wrong to have two different code paths here (opening/parsing existing page vs. adding a widget to existing page).  With the latter, we should be able to just add the widget HTML to the page, then follow the exact same code page as the former case.

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
Fixed now. I'm pretty sure I fixed the very last problem in this bug (IDs not preserved) with this commit: 74c6ad393a
