### ISSUE TITLE
ID isn't persisted when moving widget

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1062]
(Spun off from #1056. See that issue for further discussion.)

When moving a widget that has an **'id'** attribute set, that attr is not persisted after the move.

The relevant code is in **SelectTool.js** `onExtentChange()`.  Here's the general flow of what currently happens in that function when moving a widget:
1. Get data for current widget.
2. Create a new widget based on this data.
3. Create an **AddCommand** for new widget.
4. Create a **RemoveCommand** for old widget.
5. Execute commands.

While working on #1056, I tried to copy over the `id` but ran into trouble with Dijit widgets. Specifically, when creating the new widget (step 2), the Dijit code would throw an exception because there is already a widget with that ID on the page.

I had thought about running **RemoveCommand** first, in order to remove the old widget before the new one is added, but that won't work -- the problem in in the widget creation (step 2), which happens before the 2 commands are executed.

@JonFerraiolo @peller

**Comment by JonFerraiolo** [comment]
Wow, I'm surprised we still have this bug. 

Based on your description, maybe we are getting bit by the architectural problem with createWidget(). IMO, we shouldn't be called createWidget outside of command stack execution. If people agree with me, then the question is how hard is it to refactor the code. It might be a bear.

Ideally, the set of steps would be:
1. Get data for current widget
2. RemoveCommand on old widget
3. AddCommand for new widget (calls createWidget)
4. Execute command

**Comment by jhpedemonte** [comment]
Yes, you beat me to it. That's basically what I had in mind, and I think what makes the most sense.

I have no problem taking on this refactoring, which is something that was brought up several months back, but I never got around to actually doing.

**Comment by jhpedemonte** [comment]
Plus, I think the Commands themselves should be as sparse as possible.  All they should do is call out to methods that live elsewhere (probably in Context.js). I don't now how doable this will be, but I wanted to record this idea for future reference.

**Comment by jhpedemonte** [comment]
-> M6

All fixes I can think of are too risky for M5.
