### ISSUE TITLE
Icon(s) missing from menus

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1063]
In the Files view context menu (right-click on file), the red **X** from the **Delete** item is now missing. I had previously added it in M3.

Icons are also missing from the context menus in the VE and the Outline view (when right-clicking on widgets).

@JonFerraiolo @peller @childsb Do you guys have any idea why this regressed?

**Comment by peller** [comment]
fixed in f3e942ecf092a11181ec776af452b34cd3993131
