### ISSUE TITLE
Copy/paste broken for Tree and DataGrid

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1070]
@jonferraiolo

Bill, this may have been a regression with the Dojo 1.7 upgrade.  Feel free to bounce back to me.  It's getting stuck in a JSON eval of `(ForestStoreModel_1)`for the model attribute in DijitWidget's constructor (called from createWidget).  Note: there are no quotes.  I think this is where it uses some sort of global variable to define the model?  I seem to remember some recent workaround so the global wasn't necessary.  Maybe there's another way to do this?

**Comment by jhpedemonte** [comment]
Dupe to #1025.
