### ISSUE TITLE
Drag out CheckBox, then drag/drop CheckBox => RangeError

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1073]
I'm pretty sure this is a long-standing bug. With Preview3, there was a bug but different error reported.

Using Mac/Chrome:
- Refresh browser window
- New HTML File
- Click on CheckBox in widget palette, then on canvas drag out a rectangle. (Even though this doesn't make sense for CheckBox) A CheckBox widget will appear on canvas
- Try to drag/drop a second CheckBox by dragging from widget palette onto canvas

Result=> Uncaught RangeError: Maximum call stack size exceeded

No stack trace, and I didn't try to debug, so I don't know where exactly the problem is. I wouldn't be surprised if the same fix for #54 also fixes this one.

**Comment by jhpedemonte** [comment]
Infinite loop, sounds like. I never see a stack trace for those.  Just need to go through the scenario, then hit pause in the debugger, to see where it's looping.

**Comment by peller** [comment]
Chrome happily provides the stack.  onDragStart clones data.data (see 8969e0a8 and discussion: fc7e7e2eda908df4a36924ac402d2347528416cf)  There's a cycle in there, probably in the context property (context references widgets which reference contexts)

Dup of #881

**Comment by peller** [comment]
@billreed63
