### ISSUE TITLE
Theme editor - Calendar selection fails

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1074]
@peller, @jonferraiolo

Not sure who broke this. Maybe there was a change to Focus.js or Context.js in page editor that didn't get propagated to theme editor?

Uncaught TypeError: Object /davinci/ui/subwidgetSelectionChanged has no method 'remove'
connect.disconnectdojo/_base/connect:184
dojo.declare._clearListdavinci/ve/Focus:561
dojo.declare._updateSubwidgetListdavinci/ve/Focus:554
dojo.declare.movedavinci/ve/Focus:106
dojo.declare.resizedavinci/ve/Focus:128
dojo.declare.focusdavinci/ve/Context:1605
dojo.declare.selectdavinci/ve/themeEditor/Context:209
dojo.declare.onMouseDowndavinci/ve/themeEditor/SelectTool:118
dojo.declare.editFrameOnMouseDowndavinci/ve/themeEditor/ThemeEditor:741
hitch

**Comment by peller** [comment]
wow, looks like very old code that must have never run before...

``` js
            dojo.unsubscribe("/davinci/ui/subwidgetSelectionChanged");
            dojo.unsubscribe("/davinci/states/state/changed");
```

dojo.unsubscribe takes a handle from a subscribe call, not a string.  We should keep an array from the subscribe calls and just do a forEach(dojo.unsubscribe) on it.  Also, dojo.subscribe takes a context argument, so the hitches shouldn't be necessary.

**Comment by billreed63** [comment]
Works now, must have been fixed by some other commit
