### ISSUE TITLE
Absolute layout and View widgets

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1077]
@jhpedemonte, @peller

Assigned to Jon to think this one through.

If you go into absolute layout and add a mobile View widget, the debugger shows that the widget gets element.style='height: 100%; position: absolute; left: 40px; top: 33px; visibility: visible; display: block;' (assuming the drop point was (40,33)), which is probably not a result that is particularly helpful to a user.

Some possibilities here:
1. Tell users "don't do that!" (same answer doctor gives when patient says it's hurts when I do this)
2. We make sure View widgets have appropriate helper logic that stuff in more reasonable element.style values, perhaps forcing all View widgets to have flow layout even if Maqetta is in absolute layout mode
3. Disallow the operation and post an error dialog telling user they need to be in flow layout mode

Of course, this question applies to multiple scenarios, not just View widgets.

**Comment by jhpedemonte** [comment]
I like option (2) -- we create a metadata property that says the given widget cannot be applied in absolute layout and must use flow layout.

**Comment by JonFerraiolo** [comment]
Pushing to M5

**Comment by JonFerraiolo** [comment]
Reassigning to @jhpedemonte who can feel free to push to M6 (but probably with higher priority)

**Comment by jhpedemonte** [comment]
-> M6/Med

**Comment by JonFerraiolo** [comment]
Closing this. I actually dealt with this issue by disallowing users to add View widgets in absolute positioning, and posting a readable message when they attempt the operation. Absolute positioning just doesn't work because dojox.mobile logic always stuffs top:0px for view widgets.
