### ISSUE TITLE
Focus backoff logic not working with silhouettes

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1079]
@jhpedemonte

When a device silhouette is present, we are getting a scrollbar in the editing canvas when some widgets are selected because the selection chrome extends off of the "canvas". Maybe the selection rectangle adjustment logic doesn't take into account the device silhouette properly? I noticed that if I change the 'left' and 'width' properties on the selection DIVs and back off by 6px, then the scrollbar disappears, so I suspect the backoff logic isn't taking the silhouettes into account.

**Comment by peller** [comment]
are there any borders involved?

**Comment by JonFerraiolo** [comment]
I don't know about borders on the widgets that on on the page, but I don't think that's a factor\ because the scrollbar went away when I backed selection DIVs and nobs off by 6px (4px for inside the nob and 1px each side for borders on the nobs).

**Comment by peller** [comment]
yeah, I think the 100% focus behavior regressed on non-silhouettes as well.  I've also noticed that (without a silhouette) the editor no longer expands to fill the full width of the editor.

**Comment by JonFerraiolo** [comment]
Yep, that problem, too. Not sure there is a bug for why the page editor is a few pixels short on the right.

**Comment by peller** [comment]
looks ok now?

**Comment by JonFerraiolo** [comment]
as best as I can tell
