### ISSUE TITLE
app.css cannot accept custom styles?

### ISSUE THREAD

**Issue by arisAlexis** [maqetta/maqetta#1084]
ive been trying to do simple things such as 
# myelement {

```
width: 425px;
height: 300px;
border: 2px solid #DDD;
-moz-border-radius: 8px;
-webkit-border-radius: 8px;
background-color: #FEFFEC;
text-align: center;
color: #BBB;
font-size: 2em;
font-family: Arial, sans-serif;
```

}
then putting a tag in html and reference this, and it doesn't work.

**Comment by waynevicknair** [comment]
i cut your CSS from this issue and dropped it into 'app.css'. then i created a new HTML file. i added a DIV from the HTML widget palette. then i added some sample text in the DIV. i clicked the preview button and saw a rounded rectangle with a cream colored background and gray border on Mac/Safari. i inspected the DIV element and saw that it was inheriting its style from 'app.css'. 

can you expand on the scenario you went through?

**Comment by waynevicknair** [comment]
oops! forgot to include the step where i edited the DIV's id property in the property palette and set it to 'myelement'.

**Comment by jhpedemonte** [comment]
@JonFerraiolo, weren't you were looking into issues with app.css recently?

**Comment by JonFerraiolo** [comment]
@jhpedemonte - the only issue I am looking at with app.css is #1068 - ensuring that app.css is loaded after theme CSS files
