### ISSUE TITLE
Review/commenting encoding of special characters

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1094]
@waynevicknair

@EldonReturn says:

It turns out that this is a bug which exists in the R&C client JS. Unfortunately I didn't encode/decode the special characters such as the quotation marks in the Text annotation (I encoded them in the comments). So when you wrote Folder"<?>" in the Text annotation, it broke the json string.

Because the code is in flux, I recommend that the fix be put into a branch, then close this bug, and then @waynevicknair can merge into code as part of issue #1095

**Comment by JonFerraiolo** [comment]
@waynevicknair - Is this fix merged into master? If so, we can close this bug

**Comment by waynevicknair** [comment]
yes. i committed it to master.
