### ISSUE TITLE
Merge in escaping fix for review/commenting

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1095]
@EldonReturn

A fix will be coming sometime soon for #1094, probably done in a branch. This issue is a reminder to merge fix for #1094 into master branch.

**Comment by peller** [comment]
dup? just leave #1094 open?

**Comment by waynevicknair** [comment]
dropped in commit f43e0d23f718fe8b5f6f8ac80f4b81a54a1f67a8
