### ISSUE TITLE
Cannot drag widget to bottom of page

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1096]
@peller
- Open Sample1.html
- Add a CheckBox within first ContentPane of TabContainer. (In Normal state, the CheckBox will be under the DIV containing "Sort by:")
- Try to drag that CheckBox to bottom of page

Result=> Can't do it. CheckBox will stay inside of current ContentPane

**Comment by jhpedemonte** [comment]
I think I've seen something like this.  This has to do with the location cursor that appears, right?  You can see the cursor in many places, but not as the final thing in the page.

**Comment by peller** [comment]
Should be addressed with new dnd logic that uses chooseparent

**Comment by JonFerraiolo** [comment]
See #1215

**Comment by jhpedemonte** [comment]
See #675 and #1559.

**Comment by JonFerraiolo** [comment]
Yes! Fixed by new dnd logic that uses chooseparent. Closing.
