### ISSUE TITLE
Some user id colors make it very hard to read the text

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1101]
Sometimes, the user's id shows up in **yellow** on a **white** background, making it impossible to read unless I highlight the text:

![review](http://i.imgur.com/YGA5S.png)

Need to tweak the colors, to make them darker and usable on a white background.

**Comment by JonFerraiolo** [comment]
Pushing to M5, reassigning to @waynevicknair

**Comment by jhpedemonte** [comment]
-> M6
