### ISSUE TITLE
Restore VE selection after refresh

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1102]
#856 added the ability to refresh the Visual Editor iframe when certain properties are changed.  After the refresh, we need to **restore the widget selection** in the VE.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
Pushing to M5

**Comment by jhpedemonte** [comment]
**Issue:**

Need a way to specify a particular widget in the model (or VE?), such that we can save that information before the refresh, then use the info to re-select the widget.  We cannot depend on the 'id' attribute -- many widgets have a temporary ID, which may change when the page is refreshed.

**Options:**
- CSS Selectors
  - Can use basic child selectors, along with ~~`:nth-child`~~.
    - Using [`:nth-of-type`](https://developer.mozilla.org/en/CSS/%3Anth-of-type).
  - Can use `dojo.query()` to select DOM element.
  - For example, selecting the _New_ button in **Sample1.html** would look like this:
    
    DOM: `dojo.query("body > div:nth-of-type(1) > div:nth-of-type(3) > div:nth-of-type(1) >`
        `div:nth-of-type(1) > span:nth-of-type(1)")`
    Model: `body > span > div:nth-of-type(1) > div:nth-of-type(1) > input:nth-of-type(1)`
- XPath
  - More compact than CSS Selectors.
  - Modern browsers (but no IE?) can use XPath for HTML DOM, using `document.evaluate()`.
  - Can be easily transformed to CSS selector format above.
  - Select _New_ button in **Sample1.html**:
    
    DOM: `document.evaluate("/html/body/div[1]/div[3]/div[1]/div[1]/span[1]",`
        `document, null, 9, null ).singleNodeValue`
    Model: `/html/body/span/div[1]/div[1]/input[1]`

**Proposal:**

Use **XPath** notation.  It's more compact than using CSS selectors and natively supported for use with HTML DOM in most modern browsers.

Update the Model code with an API similar to `document.evaluate`.  Create an XPathUtils object with a function that returns the full XPath for the given Model element. (Also support HTML DOM?)

Algorithm:
1. Before iframe refresh, get XPath of Model element for selected widget.
2. Refresh iframe.
3. Once iframe is loaded, call `Model.evaluate` with saved XPath to get widget to be re-selected.
4. Emit `selectionChanged` event with Model element.

---

**Update: 2012-02-27:** Using `:nth-child` was incorrect, since that takes into account all children, not just children of a given type. Instead, need to use `:nth-of-type` (which is supported on same browsers as `:nth-child`).

**Comment by jhpedemonte** [comment]
cc @waynevicknair. See above.

**Comment by JonFerraiolo** [comment]
@jhpedemonte: Good job researching this! Your recommendation looks good to me. XPath lives!

**Comment by jhpedemonte** [comment]
Reopening.  After fixing #1813, when setting `fixed` prop to "bottom", selection for widget stays at top.

The reason for this seems to be that the widget selection process is running before the VE DOM has fully reflowed, after the call to `Context.refresh()`.

At the moment, I'm publishing the _selectionChanged_ event by connecting to the `Context.setSource()` method (such that my publish event runs after `setSource` finishes).  And this seems to be the latest than I can get an event related to resetting the source in the Context.

I don't know of any DOM event that can be used for this.  The various 'unload' style events don't work after the initial load of the document.  @peller, do you know any such event?

The only thing I can come up with is to inject a `<script>` into the source at the end of `<body>` -- the script would then publish an event in the app context saying that the source has finished loading in the VE iframe.

**Comment by jhpedemonte** [comment]
Note to self:

> actually, this all belongs in VE.  when it gets a selectionChanged event, it should make sure that the VE DOM has finished loading, and only then do the selection.

**Comment by jhpedemonte** [comment]
> The only thing I can come up with is to inject a `<script>` into the source at the end of `<body>` -- the script would then publish an event in the app context saying that the source has finished loading in the VE iframe.

Doesn't work.  Runs into the same problem as before, wherein the publish happens before the widget gets put to the bottom.

Adam speculated that this is a CSS issue: when resetting the source, we again reset the CSS files.  And this means that we have to wait for the CSS to fully reload.

I'm thinking that we need a way to reset the source without resetting the scripts and CSS files in `<head>`.  This would also be useful when resetting the VE due to source changes.

**Comment by jhpedemonte** [comment]
In the end, I had to go with a `setTimeout`, in order to give the DOM some time to get properly set.  Nothing else I tried worked.

Maybe the only events that could work here are the DOM Mutation Events.  However, those are deprecated, mostly because they cause a serious performance impact.

If you have a better idea, I'm all ears.

**Comment by JonFerraiolo** [comment]
Actually, I did think of something else to try, but too difficult for M5: use AMD (or ensure) to load everything in the refreshed document. I'm thinking that we could look at the current (old) model, make a list of all resources, then reconstruct/refresh by loading everything through AMD. I'm not sure this is feasible or that it would actually fix this particular problem, but I thought I'd mention it to see what people think. Also, if we chose this approach for the refresh operation, we might also want to use this method for regular old doc loading so that we don't have two separate code paths for pretty much the same operation.

**Comment by peller** [comment]
I'm not sure it's the Javascript loading that's the issue here, but the rendering and, perhaps, the css loading.  Are we using that AMD css! plugin here?  It may also not provide the logic to tell when the css loading is actually complete, and it may very well still take an extra timeout to let the browser render the page.

**Comment by JonFerraiolo** [comment]
I wonder if it is possible to check for a CSS file having completed loading by checking the DOM for something, such as the stylesheet showing in the list of document.stylesheets. If that check is reliable, then we could use a deferred to cause a wait before we invoke selection

**Comment by peller** [comment]
I'll have to find the reference, but we discussed this several months ago for some other bug.  IIRC, it's not easy to do, based on browser quirks.  One reliable workaround was to load the stylesheet with a (gasp) img tag and use the onload event.

**Comment by jhpedemonte** [comment]
Yes, as Adam states, I think this is an issues of CSS loading.  But I think we'll just have to live with the setTimeout for now.  Every other option is too cumbersome or not fully cross-browser.
