### ISSUE TITLE
Change arrow key increment to 1px, with shift key for 10px

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1103]
Easy fix now that I've found the code.

In SelectTool.js, we default to 6px for arrow key widget movements:

```
var pitch = this._context.getPreference("keyboardMovePitch") || //TODO: enable this preference
                    6;
```

We don't need a preference here. Just change '6' to 1 for normal movements, and set to 10 if the shift key is down.

**Comment by jhpedemonte** [comment]
I like it, that's a good idea.  Also, I would suggest adding a tooltip on hover: `Shift+click increment 10px`.
