### ISSUE TITLE
Make sure file dialogs deal with Return and Esc keys properly

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1111]
@childsb, @jhpedemonte

(Brought up in phone call today) We are working on tweaks to the New HTML File dialog. As part of those fixes, we need to make sure that the Return key properly maps to the OK button (or equivalent, such as Create or Save) and the Esc key maps to the Close button or close icon ("x").

**Comment by JonFerraiolo** [comment]
Assigned to Brad because he has just finished a rewrite of file dialogs

**Comment by JonFerraiolo** [comment]
Pushing to M5

**Comment by jhpedemonte** [comment]
-> M6

**Comment by jhpedemonte** [comment]
See #1475 (master plan for keyboard nav)

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg
