### ISSUE TITLE
Error in maqetta.local.win.bat

### ISSUE THREAD

**Issue by fprijate** [maqetta/maqetta#1117]
Hi 

There is an error in maqetta.local.win.bat.

Wrong quoting in command:

java -Dorg.eclipse.equinox.http.jetty.http.port=%port%  "-Dmaqetta.localInstall=true 

Franček

**Comment by jhpedemonte** [comment]
@childsb, since you know Win scripts better than I do, can you please take a look?

**Comment by childsb** [comment]
Resolved by @JonFerraiolo.  @fprijate - Thanks for the bug.
