### ISSUE TITLE
Drag and Drop DataGrid internal error

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1119]
When I drag and drop any widget with a data store I get internal error message

**Comment by billreed63** [comment]
This is a regression caused commit 307b86fc4afa151fd47ca2abbb428090d976b4e8
if data.data is an instance of array dojo.mixin({},data.data) returns an instance of object dojo.clone returns instance of array

**Comment by peller** [comment]
1ace246cd72acdc05648fc5119b0304983f9b400 Undoing Javier's undo of my commit (!) replacing with mixin+concat combo
