### ISSUE TITLE
*List UI consistency

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1122]
@billreed63, @jhpedemonte

This is a UI research bug for @jonferraiolo.

In creating mobile UIs, I find it confusing that double-clicking on an "item" within a RoundRectDataList shows me all of the items in the list, but if I have a RoundRectList and double-click on an item, I only get smart input for that one list item. Also note that many other Dijit widgets have smart input work on the complete-list level (e.g., ComboBox) versus editing each item individually.

Therefore, I'm wondering if it would be better from a user perspective to have double-click on a ListItem should show entire list, not just the one ListItem.

**Comment by jhpedemonte** [comment]
What about single click? Would that still select a single ListItem?  This is necessary to change the properties of the individual items.

**Comment by JonFerraiolo** [comment]
I think we need to try things out before we'll know for sure which way is the best to go, but my thinking now is:
- single-click on ListItem selects the ListItem
- double-click on ListItem brings up smart input for ListItem's parent

If anyone else has alternate ideas, please speak up.
