### ISSUE TITLE
Foundation data structures

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1124]
(Maybe this needs to be broken into multiple separate issues)

At some point we need to finalize ours strategies around the topics listed at:

https://github.com/maqetta/maqetta/wiki/Foundation-data-structures

and then implement our decisions.

**Comment by jhpedemonte** [comment]
-> M7

Much of this is dependent on how much we use Orion as a base.

**Comment by JonFerraiolo** [comment]
@childsb maybe we can close this issue, and open separate issues for any architecture topics that aren't resolved yet.

**Comment by JonFerraiolo** [comment]
Closing. We adopted Orion for many of the "foundation data structure" issues. We can open new issues for any remaining questions.
