### ISSUE TITLE
security: restrict access in single user mode to localhost

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1125]
"Single user mode" leaves the users workspace unrestricted open to the the adjacent network.  Single user mode should either be removed or incoming request checked that they come only from localhost.

Another option is firewall blocking the maqetta port from outside connections.

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
-> @childsb (so this doesn't fall through cracks)

**Comment by JonFerraiolo** [comment]
@childsb @jhpedemonte - no more single user, right? So can this issue be closed?

**Comment by jhpedemonte** [comment]
Closing.
