### ISSUE TITLE
security: remove the OSGi console port

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1126]
The launch scripts bind the OSGi console to a port.  A user could discover the port and disable/remove the server or possibly other things.

**Comment by jhpedemonte** [comment]
Not sure if this is an issue.  Use must specifically pass port number as a command-line argument to the startup script.  This is only really used for testing.

Please close if this is no longer an issue.

**Comment by jhpedemonte** [comment]
@childsb please see preceding comment.
