### ISSUE TITLE
Security: email spamming

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1135]
The review and commenting feature doesn't prevent or limit the number of reviewers or the amount of email a user could send.  A malicious user could use this to send large amounts of email to lots of users.

**Comment by childsb** [comment]
wayne, can you take a look at this? i know you're in the R&C code pretty deep.

**Comment by waynevicknair** [comment]
surely. i can tell you without looking that it would be very tedious to send mail to lots of people. while the HTTP spec does not limit URL length, browsers and HTTP servers (413 Entity Too Long error) have practical limits on the length they will support. also, the R&C code generates the content of all messages. thus spammers could not inject their own content, but still flood mailboxes with review invitations. 

anyway, i'll take a look at a general way to limit commands processed on the server to those we know to have come from the maqetta UI only.

**Comment by waynevicknair** [comment]
i think we're ok on this one.
