### ISSUE TITLE
DropDownButton popups (Menu) is visible on reload

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1137]
Create a DropDownButton.  The menu is constructed inside it and is hidden on the outline view.
Save, close, and reopen the file.  A div with the menu is visible on the outline at the bottom of the outline view.  This is an implementation detail, where Dijit constructs a top-level popup widget.  It should be hidden from the user.  The code in DropDownButton.create only seems to work on the initial creation of the widget.  Perhaps it's a timing issue on reload, and we need to refresh the outlineview?

@billreed63

**Comment by JonFerraiolo** [comment]
Raised this to Priority-Med for M4
