### ISSUE TITLE
Exit without saving deletes css file

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1138]
1) Create new theme
2) Change background color
3) close theme editor click ok exit without saving...

reopen theme editor notice no theme.. Look in uers work space and theme css file is missing

I did this on my themeEditorBranch with the android theme, but we need to ensure this does not happen on the master

**Comment by peller** [comment]
I see this happen for all file types, on master

@childsb

**Comment by JonFerraiolo** [comment]
Assigned to @billreed63 so that someone is assigned. @billreed63, if you want to pass onto someone else, go ahead.

**Comment by childsb** [comment]
bill - do you have additional info? i can't recreate this on master.

**Comment by billreed63** [comment]
I just recreated on the master windows chrome

1) create new user
2) new html file (file1.html) DO NOT SAVE
3) new html file (file2.html) DO NOT SAVE
4) new html file (file3.html)
5) Drop button on fille3.html
6) Save file3.html (leave file1 and file2 dirty)
7) Refresh browser
8) close file3.html tab, click "ok" for exit without savinging
9) look in users workspace file is gone...

**Comment by peller** [comment]
it seems the _editorSelectionChanged code is getting triggered.  I need to look at why.  Meanwhile, I backed out a change which probably caused this regression 37c8f9a69663e7ce6f6ab162f0211bc42b0ab205

**Comment by peller** [comment]
the file is no longer deleted, but it still shows up dirty, even immediately after reloading the browser.   Assigning to @childsb for further investigation.

**Comment by peller** [comment]
closing in favor of #1040
