### ISSUE TITLE
Cloned theme read only on fist create

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1139]
1) Create new user
2) Clone android theme (a1)
3) Select view and change background color. You should see the message about the theme being read only

If you look in the file exploer you will notice the theme folder and a1 folder are both read only (grayed out), if I refresh the browser the a1 themes and a1 folder are now read/write (not grayed)...

**Comment by childsb** [comment]
This appears fixed in a previous change.  Cloned themes no longer show as "read only" in the UI, and i'm able open/modify them upon creation.

please reopen if you continue to see this problem.
