### ISSUE TITLE
Support dropdown menus in toolbars

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1149]
Add support for drop down menus in the Visual Editor toolbars.

(See #1039 for a specific situation where this feature _may_ be useful.)

**Comment by JonFerraiolo** [comment]
@peller - I recommend pushing this to M5 - too late to do this for M4

**Comment by peller** [comment]
-> M8

**Comment by peller** [comment]
M7 UI makeover included dropdowns in the toolbar
