### ISSUE TITLE
Can double-click on read-only JS files in lib/dojo but no content shows

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1160]
@peller, @waynevicknair

After pulling code this morning, I see that ./lib/dojo is read-only, but I can navigate into ./lib/dojo/dojo and double-click on the JS files (e.g., dojo.js). A text editor opens, but contains no content.

**Comment by childsb** [comment]
this is working for me, maybe fixed with another bug.. please reopen if you still see this issue.
