### ISSUE TITLE
Turn folder field from dijit.form.TextBox into dijit.form.Select

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1168]
Nice to have, but not essential for M4.

Right now the folder field on file dialogs is a text input box. What I'd like to have instead is a dijit.form.Select that shows the current folder and all parent folder up to the user's "base folder" (i.e., the bottommost folder that we allow the user to descend into). When a user first launches Maqetta, the only folder listed should be "project1/".

I fooled around with this a bit and it looks pretty easy. 

(1) Change davinci/ui/widgets/templates/NewFile.html as follows:

```
-               <input dojoType="dijit.form.TextBox" type="text" dojoAttachPoint="fileDialogParentFolder"></input>
+               <select dojoType="dijit.form.Select" type="text" dojoAttachPoint="fileDialogParentFolder">
+                   <!-- options filled in dynamically -->
+               </select>
```

(2) Add the following CSS to davinci/ui.css (note: the 'width' value probably will need tweaking)

```
+.fileDialog .folderNameRow .dijitButtonContents {
+   width:14.4em;
+}
```

(3) Add logic to davinci/ui/widgets/NewFile.js that calls the `addOption(opts)` method on the dijit.form.Select widget, where opts is an object that holds the dynamically-computed list of parent folders. To see examples of how to use addOption(), see davinci/ui/widgets/NewHTMLFileOptions.js

I didn't finish the task myself because I wasn't sure about how to deal with all of the logic for the user's "base folder".

**Comment by JonFerraiolo** [comment]
@peller, @jhpedemonte: this relates to recent discussion about making the "where" field reflect its read-only status. If we used a dropdown that showed the ancestor folders, then I think we have both read-only styling and a more useful UI. Nevertheless, probably push to M5.

**Comment by peller** [comment]
Agreed.  See #1289

**Comment by jhpedemonte** [comment]
Status?  Is this fixed now?

**Comment by JonFerraiolo** [comment]
Closing. The file dialogs now use a DropDownButton widget, which is read-only.
