### ISSUE TITLE
helper.create called twice for DijitWidgets

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1169]
@peller, @billreed63, @jhpedemonte

If looks like the create() helper functions gets called twice whenever you add a new Dijit to the page:
1. First, at the bottom of the DijitWidget constructor.
2. Second, from the attach() method

When saving then reopening, the create() helper gets invoked from the attach() method.

I don't see any code for other widget types (e.g., HTML widgets) for calling the create() helper function from the constructor.

Must to see, I commented out the helper.create() call from the DijitWidget constructor and things seem to work after commenting it out.

Anyone see any problems if I remove the helper.create() call from the DijitWidget constructor?

**Comment by peller** [comment]
makes sense to me.  attach() seems like the right place.
