### ISSUE TITLE
Review all cookies

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1170]
@childsb

I just had a situation where I couldn't view Maqetta's docset because the request header was >4K due to lots of cookies being passed up to server. It looks like most of the cookies are from Dojo widgets. We should figure out how to disable these cookies or how to clean them up so that users don't run into Maqetta bugs because cookies are too large.

**Comment by peller** [comment]
Could you paste an example here of what the cookie content was?

**Comment by JonFerraiolo** [comment]
Pushing to M5 and reassigning to @peller.

I haven't run into the cookie limit lately and it looks like it is unlikely that early users would run into cookies max'ing out on the browser side, but maybe Jetty might max out on the server side. Looking below at our current use of cookies, the biggest worry are the Tree widgets (Files palette and Reviews palette) that have persist=true and therefore store the state of open/closed folders within cookies. There is a chance that a user with lots of folders in his workspace and/or long folder names might bust the 4K limit on an individual cookie, and the combination of multiple big cookies might bust browser overall limits or server limits. For example, I had a few folders with short names (folder1, folder2, etc) and the relevant cookie was already at 1300 bytes. It's definitely possible that users will go over the 4K limit if they create a bunch of folders. We should eliminate the risk of overrunning limits before going to 1.0. 

What I would suggest is storing open/closed state on the server as part of user state and then set persist=false so that we don't store open/closed information within a cookie.

Here are cookies I currently have when running localhost:

```
Cookie:SaveStateCookie=myapp;

davinci_ui_Panel_1.id1SaveStateCookie=.%2Fproject1%2C.%2Fproject1%2F.%2Fproject1%2Flib%2F.%2Fproject1%2Flib%2Fclipart;

prefTreeSaveStateCookie=%2C%2F0%2C%2F2; 

davinci_ui_Panel_0.id1SaveStateCookie=.%2Fproject1; 

preview=1; DAVINCI.USER=maqettaUser; 

resourceTreeSaveStateCookie=.%2Fproject1%2C.%2Fproject2%2C.%2Fmyeproj1%2C.%2Fmyeproj1%2F.%2Fmyeproj1%2FWebContent%2C.%2Fproject1%2F.%2Fproject1%2Flib%2F.%2Fproject1%2Flib%2Fdojo%2F.%2Fproject1%2Flib%2Fdojo%2Fdijit%2C.%2Fproject1%2F.%2Fproject1%2Fsample_data%2F.%2Fproject1%2Fsample_data%2Fimages%2C.%2Fproject1%2F.%2Fproject1%2Flib%2F.%2Fproject1%2Flib%2Fclipart%2F.%2Fproject1%2Flib%2Fclipart%2Fart%2C.%2Fproject1%2F.%2Fproject1%2Fthemes%2F.%2Fproject1%2Fthemes%2Fbbb%2C.%2Fproject1%2F.%2Fproject1%2Flib%2F.%2Fproject1%2Flib%2Fwidgets%2C.%2Fproject1%2F.%2Fproject1%2Flib%2F.%2Fproject1%2Flib%2Fshapes%2C.%2Fproject1%2F.%2Fproject1%2Flib%2F.%2Fproject1%2Flib%2Fclipart%2C.%2Fe1%2C.%2Fe1%2F.%2Fe1%2FWebContent%2C.%2Fproject1%2F.%2Fproject1%2Ffolder5%2C.%2Fproject1%2F.%2Fproject1%2Ffolder5%2F.%2Fproject1%2Ffolder5%2Ffolder1%2C.%2Fproject1%2F.%2Fproject1%2Ffolder2%2C.%2Fproject1%2F.%2Fproject1%2Ffolder2%2F.%2Fproject1%2Ffolder2%2Ffolder3%2C.%2Fproject1%2F.%2Fproject1%2Ffolder1%2F.%2Fproject1%2Ffolder1%2Ffolder2%2C.%2Fproject1%2F.%2Fproject1%2Ffolder4%2C.%2Fproject1%2F.%2Fproject1%2Ffolder4%2F.%2Fproject1%2Ffolder4%2Ffolder5; 

reviewCommentExplorerViewTreeSaveStateCookie=.review%2Fsnapshot; 

undefined=myapp; 

DAVINCI.USER=; 

JSESSIONID=m39d8mvcv9kdsd66j6a9j98h

Host:localhost:8081
```

**Comment by peller** [comment]
Wiki doc to track cookie usage: https://github.com/maqetta/maqetta/wiki/Cookie-list
