### ISSUE TITLE
Use AMD in user content, widget metadata

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1174]
AMD style require calls (instead of old dojo.require) is a prerequisite to the user turning on asynch loading in their application on deployment.  It will also make it trivial for us to turn on asynch for preview.

See also #1093, which is about turning on the asynch loader for the visual editor itself, and may be a bit more complicated.

I think this should be as simple as fixing the metadata.  Minimally, to be AMD-compliant, we need to use the new require API instead of dojo.require. It would be nice to bunch them all up into a single require call with an array, but individual calls will suffice.  We could just do a global search/replace of dojo.require to require, but I'd like to consider a more robust definition in our widget metadata.  We had discussed something like

In Button_oam.json:

``` javascript
{
    "id": "http://dojotoolkit.org/dijit/form/Button",
    "name": "dijit.form.Button",
    "spec": "1.0",
    "version": "1.0",
    "require": [
        {
            "type": "javascript",
            "src": "dojo/dojo.js",
            "$library": "dojo"
        },
        {
            "type": "css",
            "src": "dojo/resources/dojo.css",
            "$library": "dojo"
        },
 -        {
 -           "type": "javascript",
 -          "$text": "dojo.require('dijit.form.Button');"
 -      }
 +      {
 +         "type": "amd",
 +         "path": "dijit/form/Button"
 +     }
    ],
```

@jhpedemonte need your review of metadata changes, and determination of whether we could give this a shot for M4, or push to M5

@childsb there's a reference to "dojo.require" in RebuildBase.  If we can't get rid of this, we may need to check for both "dojo.require" and "require"

**Comment by peller** [comment]
Once this is accomplished, we can simply save our documents with dojoConfig={async:true} and in addition to being AMD compliant, preview and deployed apps should load much faster.  Visual editor would have to override with async:false until #1093 is fixed.  We'd also need to make sure existing documents can still load and that they get migrated over when saved.

**Comment by peller** [comment]
@EldonReturn may want to write OneUI metadata to use the new AMD scheme, if we can have it ready in time.  Otherwise, perhaps just using require() in the $text would work for now.

**Comment by jhpedemonte** [comment]
I think we can make this work without adding a new `require` type to OAM.  It will just take some minor tweaking of our existing metadata.  See proposal here: https://gist.github.com/1347093.

**Comment by jhpedemonte** [comment]
Adam pointed out one issue with the proposal: there's really no good way to differentiate between a JS module file and a plain JS file (which would be handled differently).

Jon suggested adding a "module" attribute (boolean) to the "require" element in OAM.  This would allow the following metadata (in XML):

``` xml
    <library name="dojo" src="../dojo/dojo.js">
        <require type="javascript" src="../dijit/form/Button.js" module=true/>
    </library>
    <require type="javascript" src="../unrelated/Code.js"/>
```

An OAM loader that understood the "module" attribute would be able to do the correct thing (convert to module id).  OAM loaders that didn't know about "module" could still load the files the standard way (script tag in head).

**Comment by peller** [comment]
I think I could live with that :)  Perhaps it could say module="amd" or module="commonjs"  I think it probably does matter, since they are generally not interchangeable.

**Comment by jhpedemonte** [comment]
Discussed that with Jon.  My view is that loading at that point becomes a function of the base library ("dojo.js" in our case).  So I'm not sure if we need to specify module type.  But again, this is easily changeable in the future.

**Comment by peller** [comment]
It's conceivable that the library may not define the loader format.  Why couple the two if we don't have to?

**Comment by jhpedemonte** [comment]
OK, I'm fine with putting `module="amd"`...

**Comment by jhpedemonte** [comment]
Created a branch called **1174-amd-metadata** and changed the Dojo OAM files based on what we discussed here.  Note that I just changed the metadata -- I didn't update any of the code that reads this metadata.

**Comment by peller** [comment]
We should specify the module as an opaque "path" or "mid" string, not a relative file path.  Not all modules are file paths, and they happen to be relative to the root and without extensions.

**Comment by jhpedemonte** [comment]
OK, based on Adam's latest concern, I updated the [proposal](https://gist.github.com/1347093) once again.  In particular, read the README.md and look at the Heading_oam.\* example files.

**Comment by peller** [comment]
I like the latest proposal and the reasoning behind it.  I'll raise a few questions, perhaps questions we could deal with later:

1) While these are javascript-driven loaders, the modules themselves may be any content type, given plugins (javascript, css, text, or some invented format)  Do we call them javascript-modules or just modules or something else?  Doesn't really matter?
2) Is it worth calling out the difference between an AMD module and a commonjs or perhaps even ECMA or other future modules?  They're not necessarily compatible, so it may be a good idea.  AMD happens to support commonJS convention for define.  I take that back, the _requirejs loader_ does... that may be outside the scope of AMD, so if someone writes in pure AMD your metadata shouldn't imply that you can use a commonjs loader to load it, right?
3) Any idea if this scheme would work with whatever it is TC-39 is proposing for modules?

**Comment by peller** [comment]
...and instead of using 'src' what would you think of 'path' or 'mid'?  It's not really the same as the src attribute we use elsewhere.

**Comment by jhpedemonte** [comment]
Re: (1) That's a tough one.  As far as I can tell, the AMD and CommonJS specs are only concerned with JS files.  But some (all?) loaders have extra functionality that allow non-JS dependencies.

Secondly, the OAM spec already supports types for those non-JS files (`require` type values can be: javascript, css, folder, image, media, markup, other).  An OAM parser/loader can choose to use a module loader for the non-JS types as well.

Re: (2) Maybe have a `format` attribute?  I think it makes sense to just call them all `javascript-module` types, but provide an extra bit of sugar to distinguish between them.

Re: (3) How far along are they with that section of the spec? Can you point to a reference or summary of where they're currently at?

Re: src or path:  I chose to keep it as `src` so as to not introduce yet another attribute to `<require>`.  I think it's easy to see that `src` had a different meaning when `type` is "javascript-module".

Would like to hear what @JonFerraiolo thinks of the latest discussion.

**Comment by peller** [comment]
1) I think plugins are part of the AMD spec, and there's at least a proposal in CommonJS for LoaderPlugins.  The dependency is not necessarily JS, only the caller can be assumed to be JS.

2) yeah, guess that makes sense

3) http://wiki.ecmascript.org/doku.php?id=harmony:modules but I wouldn't worry about this too much right now.  Just something to look at in your spare time :)

**Comment by JonFerraiolo** [comment]
My opinions:

Re: (1) and (3) Based on the talk with Simon just now and other recent info, the loader world is likely to be in a state of flux for a long time and I don't think we should attempt to guess the future in that space (although the ECMA guys have a history of delivering, with notable exception of ECMA4). I would focus mostly on our immediate requirements and put a discount factor on anything that attempts to solve all existing and potential future situations. Our immediate concern is loading Dojo 1.7 JavaScript files. I would try to find a simple, straightforward solution for that that is reasonably future-proof (eg, easily ignorable attributes/properties). IMO, the best hope for industry unity is with something coming out of ECMA. Because the browsers are involved in ECMA and tend to ship those specs, ECMA things tend to stick, and also note that ECMA tends to only care about JS (which lessens the chance that the industry will coalesce around a module system that supports multiple format types).

Re: (2) I'm ok with anything here, but simplicity is always the best. Given the uncertain state of the industry in the loader space, I would be inclined to a single attribute that is useful for loading Dojo and anything else that uses the same loader as Dojo.

**Comment by peller** [comment]
Agreed, with one exception: this isn't a Dojo thing.  It's AMD, and there's some real hope for interop here before TC-39 and the browser world figure it out, which could be several years off, easy.

ES4 is notable because it was an incompatible change, as are proposals for Harmony, ES6-8 and anything relating to modules (modules were part of the ES4 spec as well.  I recommend looking at the Harmony stuff only as a curiosity, and in case it happens to show some brilliant pattern we're missing... definitely not expecting to be future proof, and supporting future ES revisions should not be a goal for us.  The non-JS loading problem is an important one, and it's actually an indicator that TC-39 may _not_ be able to solve the problem completely.  Other things have fallen into this category as being important but outside the scope of TC-39, and they never seem to get done.  i18n is one example.
