### ISSUE TITLE
SmartInput after copy/paste shows duplicate text content

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1176]
@peller
- New HTML File
- Add a LABEL
- Copy/paste the LABEL
- Double-click on cloned LABEL to bring up SmartInput

Result=> SmartInput shows "LabelLabel" instead of just "Label"

**Comment by peller** [comment]
@jhpedemonte

The SmartInput isn't the problem.  The source actually has "LabelLabel"  Any idea when this regressed?

I see in widget.createWidget(d) that data is passed an object with these properties

``` js
children: "Label"
content: "<label>Label</label>"
```

about a page down, it does

``` js
if (node.innerHTML) {
        srcElement.addText(node.innerHTML);
}
```

which establishes "Label" as a child text node in the model (srcElement).  Then a little bit further down, it iterates through data.children and adds that to this.node, the live DOM and then adds the string to the model a second time:

``` js
 srcElement.addText(children);
```

so the on screen display looks right, but the source is wrong in the source editor, and once you use SmartInput, the visual matches the model.

**Comment by jhpedemonte** [comment]
I committed a change a while back where when moving a widget, the widget's content was pulled from source rather than from metadata.  I remember fixing one regression where content was duplicated -- this may be another area that needs to be updated following that original commit.

**Comment by jhpedemonte** [comment]
See #1056.
