### ISSUE TITLE
Set disabled to true then false causes disabled=false in HTML source

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1177]
@jhpedemonte, @peller
- New HTML File
- Go into split view
- Add a Button
- Under Widget-specific, click on disabled property to check it. Notice that the source view shows disabled="true"
- Click again on disabled property to uncheck it.

Result=> source code now says disabled="false". This is a problem with IE8 because disabled="anything" on IE8 causes the control to be disabled, including disabled="false". What we need to do is remove the disabled attribute from the source tree.

**Comment by peller** [comment]
I think it's supposed to be disabled="disabled" or maybe even just "disabled"  There's special code in Dijit to translate the boolean... somewhere.  We may have to do the same.

**Comment by JonFerraiolo** [comment]
@peller - assigned this one to you. Hope that's ok
