### ISSUE TITLE
Can't target style change to new rule - get erroneous readonly theme message

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1178]
- New HTML File
- Add a Button
- Try to set 'width' to '12em' - you get the cannot modify a read-only theme dialog, which is good
- Add a new class 'aaa'
- Open up detailed CSS view and click on the radio button by new class 'aaa' (at top of list)
- In text input field for 'width', type '12em' and click enter - button changes width
- Go to background section of Properties palette and open up detailed CSS view for background-color
- Click on radio button by rule for class 'aaa'
- Choose a different background color

Result => You get the cannot modify a read-only theme dialog, but app.css isn't read-only

**Comment by childsb** [comment]
This seems to be working (though its sort of a bug that it does!) app.css IS read only (it's being included as a library).  I did the steps, and maqetta created app.css with the rule in the workspace (as it should).  please re-open if you see this issue again.
