### ISSUE TITLE
Keyboard usability of Smart Input

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1180]
Some keyboard usability issues with Smart Input:
1. Default action is inconsistent between different types of Smart Input.  Hitting **enter** works for single line ones.  But for multiline, that just adds another line -- there is no way to execute the default action for these type from the keyboard.
   - Proposal: standardize on **Ctrl+Enter** for all Smart Inputs.
2. Keyboard actions on buttons: if user **tabs** to the OK or Cancel buttons, neither **enter** (for default action) nor **esc** (cancel action) work on the Smart Input dialog.
3. Continuation of above: shouldn't continually hitting **tab** cycle between Smart input content and the 2 buttons?  Currently, it does this: Content -tab-> OK -tab-> Cancel -tab-> Widgets tab (dismisses Smart Input)

**Comment by jhpedemonte** [comment]
-> M6

**Comment by jhpedemonte** [comment]
-> M7

see #1475

**Comment by doronrosenberg** [comment]
The main problem with ctrl-enter is that we don't have a consistent validation story.

**Comment by doronrosenberg** [comment]
@jhpedemonte @JonFerraiolo So smartinput isn't a real dialog and thus you can tab out of it and back into the main DOM of the document, hence why it gets hidden when you tab a few times.

The only way to really fix that would be to dump the custom code and use something like dijit.TooltipDialog.  I assume its too late to switch to it though, so I could try to fix the focus but that will take some time as the focus code in dijit is pretty complex.

**Comment by JonFerraiolo** [comment]
I say defer to a future release.

|------------>
| From:      |
|------------>

> --------------------------------------------------------------------------------------------------------------------------------------------------|
>   |doronrosenberg notifications@github.com                                                                                                         |
> --------------------------------------------------------------------------------------------------------------------------------------------------|
> |------------>
> | To:        |
> |------------>
> --------------------------------------------------------------------------------------------------------------------------------------------------|
>   |maqetta/maqetta maqetta@noreply.github.com                                                                                                      |
> --------------------------------------------------------------------------------------------------------------------------------------------------|
> |------------>
> | Cc:        |
> |------------>
> --------------------------------------------------------------------------------------------------------------------------------------------------|
>   |Jon Ferraiolo/Menlo Park/IBM@IBMUS                                                                                                                |
> --------------------------------------------------------------------------------------------------------------------------------------------------|
> |------------>
> | Date:      |
> |------------>
> --------------------------------------------------------------------------------------------------------------------------------------------------|
>   |08/06/2012 03:10 PM                                                                                                                               |
> --------------------------------------------------------------------------------------------------------------------------------------------------|
> |------------>
> | Subject:   |
> |------------>
> --------------------------------------------------------------------------------------------------------------------------------------------------|
>   |Re: [maqetta] Keyboard usability of Smart Input (#1180)                                                                                           |
> --------------------------------------------------------------------------------------------------------------------------------------------------|

@jhpedemonte @JonFerraiolo So smartinput isn't a real dialog and thus you
can tab out of it and back into the main DOM of the document, hence why it
gets hidden when you tab a few times.

The only way to really fix that would be to dump the custom code and use
something like dijit.TooltipDialog. I assume its too late to switch to it
though, so I could try to fix the focus but that will take some time as the
focus code in dijit is pretty complex.

**Comment by jhpedemonte** [comment]
Did that last commit break using **Enter** on single line smart input?

Test with TextBox -- hitting enter adds a new line, rather than accepting value.

I guess I wasn't clear in the summary:  use **Ctrl-Enter** for _all_ smart inputs, but also allow **Enter** press for single-line smart inputs.  Make sense?

Moving back to M7 to handle this.

---

As for tabbing:  if the tab order is `Content -> OK -> Cancel`, could we add code that says when hitting Tab on Cancel, cycle back to Content?  And when doing Shift-Tab on Content, cycle to Cancel?

**Comment by doronrosenberg** [comment]
Messing with focus order is dangerous, I would rather just switch to a correct widget that handles it for us
