### ISSUE TITLE
Update davinci.dojo_1_7 plugin css to Dojo 1.7.0 final

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1181]
The dojo_1_7 plugin apparently has backlevel css (dojo 1.7.0b2?)  Hopefully there aren't many major structural changes, but there are a good deal of diffs -- bug fixes, comments, etc.  This should solve a keyframe syntax problem @waynevicknair was seeing.

I just updated the dojo/ tree to the final release in #829, but I'm letting @billreed63 update the maqetta/themes directory

**Comment by billreed63** [comment]
done

**Comment by peller** [comment]
I noticed that claro.css is built, but the rest of the themes are apparently unbuilt, resulting in many separate HTTP requests.  Is that intentional?

**Comment by JonFerraiolo** [comment]
@peller - maybe you can look into this if you have time?

**Comment by peller** [comment]
It's really an open question for Bill when he gets back.  There's no bug at the moment.  It would be more efficient to use the built versions, but I do not feel comfortable making such a change without Bill.

**Comment by JonFerraiolo** [comment]
Raised to Priority-High. Performance is abysmal and unacceptable when testing on my Windows machine without building the mobile theme CSS files.

**Comment by billreed63** [comment]
If we use the compiled versions for the users workspace, we should remove all the individual css files as they are not used. The theme's will consist of only device.css, device-compat.css, device-app.css and device-app-compat.css

The above applies to claro.css and sketch also

**Comment by billreed63** [comment]
fixed by above commits
