### ISSUE TITLE
Context menu goes off screen if canvas is scrolled

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1187]
If the page content is so large that you get a vertical scrollbar, and then scroll down to bottom of page, and then bring up the context menu on the page canvas, the menu appears off the bottom of the iframe. Bug existed in Preview 3 and is still present.

**Comment by peller** [comment]
This may have regressed with the addition of the silhouette container.  Using dojo.getScroll() on the document should be more robust.
