### ISSUE TITLE
datagrid should support CSV file format for URL

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#119]
DataGrid should be able to create a grid and dummy data from a URL source that
supplies a CSV format data.

**Comment by billreed63** [comment]
I believe the best approach to this would be to replace the ItemFileReadStore with the CsvStore when the user has selected URL and CSV format. http://docs.dojocampus.org/dojox/data/CsvStore
What should the user interface be for this, currently the SmartInput has a TextArea with radio buttons for csv input or URL. 
Maybe we need something like:
radioButton "csv input data"
     checkBox "HTML"    <<< this would only be displayed if csv radio is selected and input contains markup chars
radioButton "URL"
     checkBox "CSV format"  <<< this would only be displayed if URL radio is selected

What do you think @JonFerraiolo

**Comment by JonFerraiolo** [comment]
@billreed63: My initial thinking is two separate and independent sets of UI options:
Data source: 
  (radioButton) User-entered data (multiline, comma-separated)
  (radioButton) Remote data:
     URL: [............]
     Format of data: (radioButton) JSON (radioButton) CSV
Cell data should be treated as: 
  (radioButton) Plain text
  (radioButton) HTML markup

In terms of distinguishing between JSON data and CSV data, can we examine the data and determine automatically? If not, then I would suggest:

Data source: 
  (radioButton) User-entered data (multiline, comma-separated)
  (radioButton) Remote data:
     URL: [............]
     Format of data: (radioButton) JSON (radioButton) CSV
Cell data should be treated as: 
  (radioButton) Plain text
  (radioButton) HTML markup

**Comment by billreed63** [comment]
We could interrogate the URL to determine the format of the datastore. The code below is an example of how this could be done, order is important. The URL must be checked for JSON first, a json URL can be read and parsed by CsvStore no error is generated, but ItemFileStore will generate an error if the file is not JSON.

var store = new dojo.data.ItemFileReadStore({url: "support/movies.csv"});
store.fetch({
    query: this.query,
    queryOptions:{deep:true},
    onBegin: dojo.hitch(this, function(total){ 
        debugger; 
        console.log("There are ", total, " items in this store."); 
        } ),
    onComplete: dojo.hitch(this, function(items){
        debugger;
        for (var i = 0; i < items.length; i++) {
            var item = items[i];
            console.warn("i=", i, "item=", item);
        }
    } ),
    onError: dojo.hitch(this, function(errData, request){
        debugger;
          console.log("Failed Loading data.");

```
} )
```

});
var store2 = new dojox.data.CsvStore({url: "support/movies.csv"});
store2.fetch({
    query: this.query,
    queryOptions:{deep:true},
    onBegin: dojo.hitch(this, function(total){ 
        debugger; 
        console.log("There are ", total, " items in this store."); 
        } ),
    onComplete: dojo.hitch(this, function(items){
        debugger;
        for (var i = 0; i < items.length; i++) {
            var item = items[i];
            console.warn("i=", i, "item=", item);
        }
    }),
    onError: dojo.hitch(this, function(errData, request){
        debugger;
          console.log("Failed Loading data.");

```
})
```

});

<i>Note: For our purpose we only need the onBegin and onError, onComplete is not needed.</i>

We need to take into account that this is a onError, OnComplete, onBegin are all callbacks. The UI may have to provide a spinner to keep the user entertained with we are processing the URL

**Comment by JonFerraiolo** [comment]
Are you thinking of a synchronous data pull from server or async? Of course, we want to be fully async at some point across the board. If async, then if we post a spinner, we would need to include some sort of timeout logic to remove the spinner if the server never responds. Also if async, then we have to decide whether to block further editing in the app until the action is completed, or program the app such that further editing is possible, but the DataGrid widget gets updated when the server request is completed, but that would mean we would want to hold off updating the DataGrid widget until the app was in an idle state.

**Comment by billreed63** [comment]
I think we want to do it sync, if the user clicks away we assume the edit session is over.  They could "Cancel" out of the edit if it takes to long.

**Comment by JonFerraiolo** [comment]
@billreed63, should we push this one to M4?

**Comment by billreed63** [comment]
Yes

**Comment by billreed63** [comment]
we have several DataStore capable widgets. Currently we have duplicated code in DataGridHelper/Input, RondRecDataListHelper/Input, and possible TreeHelper/Input. RoundRecDataList needs JSONP support added I would assume CSV also. I started the process of re-factoring all the code  around these widget, but did not get very far in this milestone. So as part of 119 we should re-factor the code so all the Store based widgets are using the same code.

**Comment by JonFerraiolo** [comment]
Reassigned to @doronrosenberg , M6, Prio High

**Comment by doronrosenberg** [comment]
So the idea is that "Data from URL" will support JSON/JSONP/CSV.  Since JSONP requires an additional argument (callback), we will need a checkbox to distinguish JSONP.

I would say having 2 radio buttons, JSON/CSV and the JSON panel would have a JSONP checkbox that shows/hides the callback input.

**Comment by billreed63** [comment]
Currently we have a drop down selection box that allows the user to chose from 3 options:
1) Enter data in CSV format
2) load data from a file in their workspace
3) load data from a JSONP service

I was think the user would chose option 2 and select the file from their workspace we would then interrogate the URL to determine the format of the datastore. The sample code at the top of this defect should allow determine the format.
