### ISSUE TITLE
support editing json files

### ISSUE THREAD

**Issue by jrlacy** [maqetta/maqetta#1190]
If you open a .json file, you can edit it but there is no mechanism to save the changes.  This would be useful if you wanted to use json sample data for data driven widgets like the grid.  Having the ability to create a new .json file from the New... menu might also be handy.

**Comment by jhpedemonte** [comment]
Hmm, I thought we had something open for this already.  Thanks.

@JonFerraiolo @childsb  How easy is to to make a file type "editable" so that it can be saved?

**Comment by JonFerraiolo** [comment]
@peller, @waynevicknair 

Assigning to @childsb for time being so it doesn't fall through cracks.

**Comment by JonFerraiolo** [comment]
I think that if we fix #43, this one will be fixed.

**Comment by JonFerraiolo** [comment]
@waynevicknair - any chance you could grab this one?

**Comment by waynevicknair** [comment]
surely, i'll take a look tomorrow while i'm in the code.

**Comment by waynevicknair** [comment]
i verified that in the current build you can edit an existing JSON file and save it.
