### ISSUE TITLE
Move ./maqetta/* files into lib/*

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1193]
@peller, @waynevicknair

I don't think we want to make this change for M4 - no need to add to our short-term migration burden. Fixing this bug would mean existing user files would need to be migrated. Better to wait until we batch together multiple workspace cleanup items at once.

This issue here is that there is no good reason why we have:

```
./lib/
   dojo/
./maqetta
```

Probably we should go with something like this to simplify the default user workspace setup:

```
./lib/
  dojo/
  maqetta/
```

**Comment by jhpedemonte** [comment]
-> M6/Med
