### ISSUE TITLE
dojo/, maqetta/ and themes/ folders should be closed by default

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1194]
@childsb

Assigning to Adam because I suspect here is a cookie aspect to this - tree controls by default write out a cookie so that the next time you use a given tree control the previous state is preserved.

What I would like is that when a brand new user launched Maqetta, all of the geeky folders are closed by default. Probably better if the open/closed state of particular folders is preserved across sessions unless this causes cookies that are going to bust the 4K limit on HTTP headers.

**Comment by peller** [comment]
I believe the tree persistence behavior is on (right now) by default.  I don't think we'd ever want to mess with the cookies directly, but simply use the Tree API to open/close folders.

Isn't the initial state to come up with all folders in the "Files" explorer closed by default?  What is the request?

**Comment by JonFerraiolo** [comment]
Closing this issue. I removed cookies and cleared the cache and the Files view does indeed open with the folders closed. I opened lib/ and then refreshed the browser, and lib/ upon refresh was expanded and the other folders weren't. So I think we are fine as is.
