### ISSUE TITLE
Do we really need N editor toolbars for N editors?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1195]
@waynevicknair

Low priority.

As I remember, each editor contains its own editor toolbar. If you have 10 docs open, there are 10 toolbars. This seems like an artifact of programming expedience from long ago. Other such things in our UI (e.g., Properties palette) only have 1 instance for the whole application. We'd use less memory and have faster performance if the editor windows shared the same toolbar.

**Comment by jhpedemonte** [comment]
Good point.  Would be good to have a single toolbar, and just disable icons that have no use for certain files.  Or have a base toolbar that stays the same across all files and allow the editors for file types to append file-type-specific icons.

**Comment by peller** [comment]
Remember, different editor types will have different commands to enable/disable, and unless you also want to unify editor instances, you'll have to genericize the way they call to the editor. Right now, toolbars are hard-coded to the editor and incorporated in their layout.  It may be more trouble than it's worth.

**Comment by JonFerraiolo** [comment]
Yes, maybe be more trouble than worth. I just wanted to log the bug for future reference.

One approach would be to have a single toolbar instance for all visual html editors, another for source editors, etc, with the result of one toolbar instance for each type of editor, rather than one toolbar instance for each editor.

**Comment by peller** [comment]
Toolbars aren't that heavyweight.  The heaviest thing about them is probably the images.  I'm hoping that by using CSS, they're sharing image resources.

**Comment by peller** [comment]
-> future

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo M7 Prio Med might be addressed as part of M7 UI makeover effort

**Comment by JonFerraiolo** [comment]
Closing. Was addressed as part of M7 UI makeover effort.
