### ISSUE TITLE
Open CSS file, dirty bit goes on before any changes

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1198]
@peller, @waynevicknair

Double-click on app.css. Notice that the editor tab has an asterisk (*) showing that the dirty bit is on even though no changes have happened yet to the file.

**Comment by peller** [comment]
dup of #1040

**Comment by peller** [comment]
and dup of #1138

**Comment by childsb** [comment]
In editor.js I moved the model onChange event binding to AFTER the initial content is set.

**Comment by peller** [comment]
I still see this problem

**Comment by childsb** [comment]
Fixed earlier in the milestone.
