### ISSUE TITLE
No toolbar when opening JavaScript files

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1199]
Double-click on SampleJs.js. Source editor comes up, but no toolbar, so no ability to Save or SaveAs. (CSS files work fine)

**Comment by childsb** [comment]
@peller - adam, do you have any idea about this bug? could this have happened on the orion editor upgrade?

**Comment by JonFerraiolo** [comment]
@waynevicknair Closing this as dupe of #1227 which has more detail

**Comment by peller** [comment]
I'm fairly certain the toolbar was there after the upgrade.  I do not know when it regressed or why.
