### ISSUE TITLE
Cut/paste of sticky note loses data inside of note

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#12]
I create a sticky note and accepted default content ("Enter note"). With the
sticky note selected, I clicked on the Cut icon and then performed a paste
operation (click on Paste icon and then click on canvas). A sticky note appears
but there is nothing inside of it.

**Comment by billreed63** [comment]
missing html metadata for `<i>`, `<b>` and `<li>` had the wrong tag in the metadata

**Comment by billreed63** [comment]
May 2011

**Comment by billreed63** [comment]
review by @peller

**Comment by peller** [comment]
+1
