### ISSUE TITLE
Switch theme desktop -> android -> desktop causes corruption

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1204]
The following sequence resulted in a visually corrupted page in the page editor:
- Open Sample1.html
- Switch to Sketch (works!)
- Switch to Android (corrupted - not surprising)
- Switch to claro

Result => Corrupted visuals. Seems like this should work. Also, maybe mobile themes should be disabled from switch theme dialog if no mobile widgets? (Not sure how easy that is to do)

**Comment by billreed63** [comment]
fixed 1004829641899555a6bcd8e5ff715109562bed6a
