### ISSUE TITLE
Sometimes SelectTool/Focus onMouseUp on nob doesn't take

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1207]
(Happens on Mac/Chrome with Preview 3 and latest code. Haven't tried other browsers yet)

Sometimes when dragging a nob on a Calendar, the onMouseUp handler either doesn't get fired (most likely) or doesn't complete its work because the modified Focus box stays on the canvas after mouseup but the widget isn't resized.

Intermittent, but this is how to reproduce:
- Absolute positioning mode
- Add Calendar
- Drag top/right nob up and to right, let go of left mouse button

Result=> Sometimes you get the result described above

**Comment by peller** [comment]
does the document get modified?  is this just a redraw problem, or does the change really not stick?  any exceptions on the console?  (may need to wrap try/catches around the onMouseUp handler to find out?)

**Comment by JonFerraiolo** [comment]
document does not get modified - that's the problem. To make the changes stick, you have to click on object again and resize once again. 

My instincts are that onMouseUp never gets called. I'm suspecting that there are situations where event.target for the mouseup event is a different DOM node so the mouseup goes to a node which doesn't have a mouseup handler. Wild guess: maybe in some situations there is a hidden node at a higher z-index?

**Comment by JonFerraiolo** [comment]
Closing. Couldn't reproduce with latest code. Maybe some of the SelectTool.js and Focus.js changes over last several weeks fixed this.
