### ISSUE TITLE
focus ring regressions

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1209]
drag a calendar on to a new page

drag the right, middle nob to the right.  the focus ring ends up with a height of zero, yet the widget does not resize.

drag the bottom, middle nob down.  The widget resizes to be wider and taller

**Comment by JonFerraiolo** [comment]
Works for me. I think I've committed some changes recently in this area. Are you running a build or launching from Eclipse? If a build, what's the commit# on the About box?

**Comment by peller** [comment]
running the nightly build (maqetta-20111110-0603) from the command line.  revision is d5d7e8fcd2ac9bb01278b3a66325e0e2cedb3ea1

**Comment by JonFerraiolo** [comment]
Yep, thanks. I broke something yesterday.

**Comment by JonFerraiolo** [comment]
I think I have a fix. Probably will check in within next couple of days.

**Comment by JonFerraiolo** [comment]
Fixed with adca6100ac
