### ISSUE TITLE
widget filter control should be fixed to top

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1210]
with lots of widgets visible, if you scroll down, the filter control scrolls out of view

perhaps use a "ToolbaredContainer" (sic) here?

**Comment by JonFerraiolo** [comment]
Pushed this one to M5

**Comment by jhpedemonte** [comment]
-> M6

**Comment by peller** [comment]
-> M8

**Comment by peller** [comment]
got fixed by @JonFerraiolo when he cleaned up the widget palette
