### ISSUE TITLE
buildtime missing from about box

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1211]
About box shows

Date: @buildtime

**Comment by JonFerraiolo** [comment]
@childsb

**Comment by waynevicknair** [comment]
where were you running from? launching from inside eclipse will not show the date as the build scripts do the string substitution. however, all published builds should have a date.

**Comment by peller** [comment]
I was running a nightly

**Comment by waynevicknair** [comment]
adam, this was caused when you dropped the AMD conversion of 'repositoryinfo.js'. you left off the trailing '@' in the '@buildtime@' token.

fix with commit e52d72fcd8de9fc4ec1f270ef207d11f074a2578
