### ISSUE TITLE
incorrect string math +/- on zindex

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1212]
in the z-index property box, enter a number like 5.  +/- works ok.

enter 0.  hit - and you get -1.

now , with the value -1, hit + and the negative value decreases, - and the negative value increases towards 0 (this is backwards)

When you get to 0, it will say "-0".  Keep hitting - and it will say --1, --2, etc.  As you pass 0, you accumulate another minus sign.

**Comment by JonFerraiolo** [comment]
Closing. I don't see this behavior anymore.
