### ISSUE TITLE
Add smtp.mailServer as defined variable in launch scripts

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1225]
@childsb, @jhpedemonte

Users can set the Java property `smtp.mailServer` by hand-editing the java command in the launch scripts (e.g., maqetta.server.mac.command and maqetta.server.win.bat). We should provide a handy variable in that launch script such that users can pass a command-line argument to the launch script or more easily hand-edit a copy of the launch script.

Maybe if no value is provided for the mail server, then don't include the `smtp.mailServer` in the command line arguments, but if there is a value, then include that property in the java command?

Might as well inlcude this command-line option in _local_ versions of launch scripts, too, just in case.

**Comment by waynevicknair** [comment]
fixed in commit d45988ac9dcb9aa74301d0c4e9545a742344615f
