### ISSUE TITLE
Save Icon Does Not Show Up in JavaScript Editor

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1227]
Menubar tests running build from commit f1426c32b113146435504d14bdd9f847572fa90d

New menu: New JavaScript File - different filename in root directory, with save

Steps
From the New menu on the banner, choose "JavaScript File..."
Don't accept the default filename. Instead, type a new file name, but within the default directory.
Add some text to the file, such as "// a comment"
Click the "Save" button on editor toolbar
Close the editor by clicking "x" on editor's tab
Double-click on the filename in Files palette to reopen
Close the editor by clicking "x" on editor's tab

Expected results
The new JavaScript file should be visible in the Files palette and upon reopening show the content you entered.

**Comment by JonFerraiolo** [comment]
I'm not sure why this bug slipped through cracks. Wasn't assigned to M4 and wasn't listed as Priority-High.

**Comment by waynevicknair** [comment]
cannot recreate on build from commit 4c150f322b449b2067a40948614d43ce11869b6c
