### ISSUE TITLE
YUI Calendar widget does not work

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1229]
Create new file drag and drop YUI calendar widget

**Comment by peller** [comment]
dup of #918?

**Comment by jhpedemonte** [comment]
From Jon in #918:

> Reopening. (@childsb)
> 
> Running from both daily builds and launching from Eclipse, jQuery and YUI widgets aren't working. HTTP requests for jQuery libraries is failing with 404:
> 
> ```
> Problem accessing /maqetta/user/maqettaUser/ws/workspace/project1/lib/jquery-ui/jquery-1.4.4.min.js. Reason:
> NOT_FOUND
> ```
> 
> One hint: I don't see jQuery and YUI folders in my workspace within ./lib

**Comment by jhpedemonte** [comment]
Dupe of #1328.
