### ISSUE TITLE
New Folder problems

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1237]
- Clear out your workspace, clear browser cache and restart the server
- Launch Maqetta
- New HTML File
- Open up file list and click on New Folder
- Accept default "folder1"

Bug#1: "folder1" should be selected in the list and become the current parent folder - that's what most other S/W does
- Click on "folder1" to select it
- Click OK to attempt to create "file1.html" inside of "folder1"

Bug#2: Alert comes up saying file1.html already exists

**Comment by childsb** [comment]
Fixed the bug and opened #1237 to track selecting the created resource in explorer (prob too risky for m4).
