### ISSUE TITLE
CSSParser breaks on non-quoted url() data types

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1241]
In CSS, the **url()** data type takes a string which can be quoted or not:

```
   <a_css_property>:  url("http://mysite.example.com/mycursor.png")
   <a_css_property>:  url(http://mysite.example.com/mycursor.png)
```

See https://developer.mozilla.org/en/CSS/uri.

The non-quoted variant breaks the CSSParser.

**Comment by JonFerraiolo** [comment]
Hope it's ok, but I changed to Priority-Low for M4. I'm worried that this bug will cause problems in short-term if not fixed.

**Comment by waynevicknair** [comment]
moving to M5

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
-> @billreed63 M7 Prio-Med (unfortunately for @billreed63, he has become our expert in CSSParser.js)

**Comment by billreed63** [comment]
NO ONE told me if you touch it you own it ;)

**Comment by JonFerraiolo** [comment]
If it's any consolation, I have the same situation with HTMLParser.js.

**Comment by billreed63** [comment]
at some point this issue has been resolved. It is not a problem on M7 code
