### ISSUE TITLE
Drag clone image is shifted when page is scrolled

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1243]
@peller

Maybe I introduced a bug with some of the changes I made to drag clone.

Steps: Add a bunch of content to a page until there is a vertical scrollbar, then drag/drop a CheckBox or other widget towards the bottom. The drag/clone box is shifted. if the drag/clone is off the bottom of the page, the drag/drop operation fails.

**Comment by peller** [comment]
works for me.  is a drag/clone box the focus box?  how did it fail?
