### ISSUE TITLE
HTML table creation should allow inline edit, including at creation time

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#125]
For both datagrid and HTML table, we should allow a user to enter table data by
double clicking and also at initial creation time (uon dropping a table onto
design editor).

This would provide a quick and easy way for users to set up a table that they
know beforehand has to be a certain way. For example, for a form for personal
## info, they could type:

First name: ,
Last name: ,
Street: ,
## ...

 then a knowledgeable user could enter the following
## by hand:

<label for="firstname">First name: </label>,
<label for="lastname">Last name: </label>,
<label for="street">Street: </label>,
## ...

and they quickly will have their form along ways along

**Comment by JonFerraiolo** [comment]
Reassigning to @aerwin

**Comment by aerwin** [comment]
@JonFerraiolo Per earlier discussion today, moving table feature requests in my name to M6.

**Comment by aerwin** [comment]
-> M7

**Comment by JonFerraiolo** [comment]
@aerwin - should we close this bug? We have SmartInput for tables now, even if it isn't exactly what was described in this issue.

**Comment by aerwin** [comment]
@JonFerraiolo Yes, agreed. Closing.
