### ISSUE TITLE
Mobile theme editor broken by recent commit

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1250]
@billreed63

The new mobile theme editor works in commit just before b1f4badf3eb037deb651f107f98a2a4e4da8d2bf and quits working with that commit.
- New theme...
- Choose android as the theme to clone, pick whatever name you want for the new theme

Result => 

```
1441Uncaught TypeError: Cannot read property 'firstChild' of undefined
declare.getTopWidgetsdavinci/ve/Context:1441
dojo.mixin._switchEditor
```

**Comment by peller** [comment]
Jon, I've been seeing this also.  Are you sure it was that commit, and not the gigantic merge I mentioned a little bit prior to that at 2ae989290cebbe489fca8b39dc53436b6e7968d5?   (even clicking on that link hangs my browser)

**Comment by JonFerraiolo** [comment]
All I can say is that on Mac/Chrome, theme editor comes up for we went I do a git checkout 2ae9892 (or the commit just before b1f4bad) but fails when I do git checkout b1f4bad . (In both cases, before testing, I had removed my user workspace, restarted the server and cleared browser cache) I haven't looked at why things are failing. I was hoping you and/or Bill would figure out why the fixes are colliding with each other.

**Comment by peller** [comment]
ok, thanks for verifying that.  I think I need to make things sane before I can debug this one, though.

**Comment by peller** [comment]
works for me
