### ISSUE TITLE
Use existing file name in New File dialog, simply exits

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1251]
1. **New HTML Page**.
2. For file name, choose that of an existing file.
3. Click **Create**. 
4. Dialog saying "File already exists" appears.
5. Click on **OK**

Both dialogs disappear.  A few days ago, I saw an error in the console, but now the New File dialog exits without error.

@JonFerraiolo

**Comment by peller** [comment]
dup of #1396
