### ISSUE TITLE
How to control label strings and widths in composite widgets?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1257]
(Note: @jhpedemonte is on vacation at the time this issue was raised)

@EldonReturn

Just suppose there was a widget library that included various composite widgets that included both an HTML <label> and a Dojo widget such as TextBox, and this composite widget was named something like MyWidget.form.TextBox. Perhaps some large company created a whole library of such widgets.

Users will need to edit the label's text and the width of the TextBox. How would we support this:
- By turning the composite widget into a container widget so that the Outline palette showed both the <label> and the TextBox, which would allow a user to customize the <label> and <TextBox> by selecting them and then changing properties?
- By adding various widget-specific properties and helper functions to allow changing specific properties?

**Comment by jhpedemonte** [comment]
Push to M5, set priority High.

**Comment by jhpedemonte** [comment]
The second option is the best solution.  A composite widget should only surface the properties from internal components that it wants to.  In many cases, these "composite" widgets will be constructed in such a way that there is only a little bit of configurability and shouldn't surface all properties from the internal components.

Then, there must be code that makes the correct changes based on changes to the properties, changing the internal components if necessary.

But this is all to the discretion of the widget creator -- there is nothing we need to do in Maqetta to support this.
