### ISSUE TITLE
Background dialog gradients: different icons that "+" and "-" for adding/removing stops

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1261]
@jmockler, @peller

The Background dialog has "+" and "-" icons for adding/removing gradient stops. These aren't good visual clues to the user, and are especially confusing since this is confusing versus the "+" and "-" icons on the Properties palette (which increments/decrements a property value). We need better icons. (Actually, right now, these aren't even icons - they are text)

Adam suggested using a green + and a red X instead, which would be better than what is there now, but maybe we should have a couple of new icons that graphically reflect "add new gradient stop", "remove current gradient stop"

**Comment by jhpedemonte** [comment]
If we can't figure out something for this quickly, I would say go with Adam's suggestion for M4, then leave open for M5 for further work.

**Comment by JonFerraiolo** [comment]
Very good chance we will have nice new icons that can be integrated quickly and easily in time for M4

**Comment by JonFerraiolo** [comment]
Closing this bug. We had a UI discussion and decided to leave the +/- icons as is and just put tooltips on the buttons

**Comment by JonFerraiolo** [comment]
Fixed by adding tooltips
