### ISSUE TITLE
Mobile theme editor: first attempt to change property brings up global CSS file warning

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1264]
@childsb - Assigning to you with idea that you will know how to research/fix and maybe you have some bandwidth.

@billreed63

I'm getting an error dialog when I attempt to change a property after bringing up a mobile theme editor via the "New Theme..." command. I'm 99% sure the error dialog is coming from Cascade.js. The error dialog's title is "Error modifying value" and the dialog's contents read as follows:

```
This property change cannot be completed because the operation attempts to modify a read-only theme CSS file.

To change this property, one technique is to add a class to this widget (at top of Properties palette) and then open up the CSS Details pane to target a style rule within your app.css file, as described at Creating Style Rules with app.css.
```

Steps to reproduce:
- Virgin environment (wipe out workspace, restart server, clear browser cache, etc)
- Launch Maqetta app
- Immediately issue a "New Theme..." command and clone the "Android" theme
- Select on global widget at top
- In Properties palette, try to change 'color' (under Fonts and Text). 

Result=> You should see the error dialog described above.

**Comment by childsb** [comment]
fixed with check in 712397781125563492ff8c8e29632ac3c82515b3
