### ISSUE TITLE
Mobile theme editor: exception in Workbench/switchEditor with browser refresh

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1266]
@childsb, @billreed63

If I have a single editor open which holds a mobile theme editor (clone of Android in my case), and then I refresh the browser (eg Cmd-R), after refreshing there is an exception in Workbench.js/switchEditor()

Assigning to myself to research this further. I'm seeing this in the built version. Haven't tested yet in Eclipse.

**Comment by peller** [comment]
what is the exception?

**Comment by JonFerraiolo** [comment]
Closing - pretty sure this is the same as #1339
