### ISSUE TITLE
Drag and drop a dojox.mobile.View results in an internal exception alert box

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1270]
@jonferraiolo

The exception happens in the select code, after all the important code in create has run.  So you see the widget on the page and it's functional, it's just not selected.

The exception is at StyleCommand line 85:

``` js
newValues.push(a)
```

where newValues is not an array (it looks like {display:""})

**Comment by JonFerraiolo** [comment]
Reassigning to @childsb to see if he can address before @jhpedemonte returns
