### ISSUE TITLE
Widgets not displayed when reopening html page

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1273]
I produced this on the nightly build, but was able to reproduce on my dev system with the latest code from git
Chrome/Win

1) Create html file
2) Drag n Drop TabContainer 
3)  DnD button in TabContainer
4) Save file
5) Close file
6) Reopen file

Canvas is blank, but outline and source look correct.

**Comment by peller** [comment]
anything suspicious on the console?

**Comment by billreed63** [comment]
nothing in the console, but it seems to be limited to the tab container. Another interesting thing is that the tab container in sample1.html is displayed correctly

**Comment by JonFerraiolo** [comment]
Other container widgets are broken in other ways. TabContainer ends up with computed height of 0px. AccordionContainer has the wrong initial size. BorderContainer also had problems when I tested

**Comment by JonFerraiolo** [comment]
After doing some binary search through history, @peller and I suspect 8c515e2f780f45012421cd8bc1e8c9ec4921712d

**Comment by peller** [comment]
I was wrong.  It was a88dc607084d07b5ccc32a9b435a2af31c62f319 though I'm not sure why.  Brad, any ideas?

**Comment by peller** [comment]
Note that, following the instructions above, the content generated after a88dc607084d07b5ccc32a9b435a2af31c62f319 result in an empty page even when run outside of Maqetta.  It's got something to do with the content itself -- the delta being that there are width and height measurements on the widgets.
