### ISSUE TITLE
Sticky note broken

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1279]
1) Create new html file
2) Click on sticky note
3)Change text in sticky note
4) Click ok

Sticky note disappears text added at div at bottom of html

**Comment by JonFerraiolo** [comment]
@peller

**Comment by JonFerraiolo** [comment]
Reassigning to @peller because @billreed63 is all booked up on mobile theme editor issues

**Comment by peller** [comment]
works for me.  perhaps related to the stylecommand regression?
