### ISSUE TITLE
Save/Cancel in Preferences dialog has inactive scrollbar

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1287]
At least in Chrome, there's a scrollbar without a thumb visible to the right of the Save/Cancel buttons in the Preferences dialog

One fix would be to increase the size of the 'bottom' pane, but a better fix and a way to simplify the code might be to remove the bottom pane from the BorderContainer entirely, putting the two buttons as peers to the BorderContainer, leaving just the two panes inside the BorderContainer side-by-side with a splitter.

**Comment by JonFerraiolo** [comment]
Pushing to M5

**Comment by jhpedemonte** [comment]
-> M7

**Comment by doronrosenberg** [comment]
fixed as part of my dialog work
