### ISSUE TITLE
OpenFile dialog - tree is not nested

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1288]
all elements in the tree appear at the same level.  children should be indented

**Comment by peller** [comment]
same for new file dialog

**Comment by childsb** [comment]
@peller more details?  I removed the "project"/root node from the tree (per a bug earlier in the m4), so the first level of elements is no longer indented.  

If i expand any of the folders (lib, themes etc..), their children are indented in FF.  are you seeing something else?

**Comment by peller** [comment]
Everything is indented at exactly the same level.  Nested files/folders should be nested extra from their parents.

http://skitch.com/alpeller/gta2c/screen-shot-2011-12-15-at-4.22.04-pm

**Comment by childsb** [comment]
Is the screenshot from Safari?  The indentation is correct for me on FF.

**Comment by peller** [comment]
@childsb: during the startup sequence, resize() is getting called on the dijit.Tree before it's visible, so when it tries to calculate _nodePixelIndent it comes up with 0px instead of 19px.  It's got something to do with the startup sequence of the custom widget.  I notice one difference between NewFile and OpenFile is the startup method...

**Comment by JonFerraiolo** [comment]
@peller: Looking at this page (http://animaldiversity.ummz.umich.edu/changethinking/labs/species4/0/util/docscripts/_browse2.php?ns=dijit&file=Tree.js&showall=1) I see the following text:

```
Number of pixels to indent tree nodes (relative to parent node).
Default is 19 but can be overridden by setting CSS class dijitTreeIndent
and calling resize() or startup() on tree after it's in the DOM.
```

In debugger, I see that the Tree widget for OpenFile does indeed have a DIV with `data-dojo-attach-point="indentDetector"`:

```
<div class="dijitInline dijitTreeIndent" style="position: absolute; top: -9999px" data-dojo-attach-point="indentDetector"></div>
```

and looking at the Style tab in debugger it looks like the code is indeed bringing in the CSS file that specifies indent size of 19px (dijit.css:1486):

```
.dijitTreeIndent {
width: 19px;
}
```

so II strongly suspect that all we need to do to fix this bug is to call resize() on the Tree after the Tree has been added to the DOM. In fact, when fooling around, I somehow triggered a resize on the Open File dialog, and indents magically appear. @peller, do you know how to do that?

**Comment by peller** [comment]
Yes, that was my finding as well.  `startup()` is getting called, just at the wrong time, and I don't think you can call startup a second time.  You're right that you can call `resize()` but you'd have to call it directly on the Tree.  That's a workaround, but not a good long-term fix.  I suspect the problem here is a Dijit bug and I will try to isolate and report it.  One of the contentPane's is calling `layout()` from `startup()`, thinking that the element is showing, but it isn't.  `_isShown` on ContentPaneMixin apparently checks `style.display` on the ContentPane in question and its parent, which I guess is usually enough, but due to the complexity in our Dialogs, there are something like 4 layers of containers between the Tree and the Dialog (the one with `display:none` until the show happens)

**Comment by peller** [comment]
Looking again at the debugger, I realize the breakpoint was triggered to resize other dialogs on body as well and I was looking at the wrong one, so most of what I wrote yesterday was wrong.  Now I'm thinking it's simply because the custom widget OpenFile doesn't follow Dijit's pattern to pass along the `startup` command to the child Tree widget -- I think `ContentPane` only does this if there's a single widget child?

I'll take this one.

**Comment by peller** [comment]
I'll stand by my earlier comments that we should avoid these custom widgets.  Lots of unneeded complexity.
