### ISSUE TITLE
yui/jquery widgets fail

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1293]
I see 404s in the network console when trying to dnd widgets like jquery datepicker to the canvas.  It looks like a path/server/metadata issue.  Note the 'undefined' in the url:

http://localhost:8081/maqetta/user/undefined/ws/workspace/project1/lib/jquery-ui/jquery-1.4.4.min.js

**Comment by JonFerraiolo** [comment]
Maybe reassign to @jhpedemonte?

**Comment by childsb** [comment]
A couple notes here--
- Adam is running in "single user mode".  The "undefined" should be "maqettaUser" or something similar.  
- You must copy the YUI/JQuery deps into your plugins to try this in dev mode

I can't reproduce this.

**Comment by peller** [comment]
see #1328
