### ISSUE TITLE
download selected files dialog overflows bounds

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1294]
click the download selected files button on the file palette.  Note that there's some extra space in the dialog.  The content overflows the dialog.  perhaps the height and width are being set on the dialog (shouldn't be -- dialog resizes based on its contents)

**Comment by jhpedemonte** [comment]
Is this about how if you select a **single file** and then click on the **Download Selected Files** button, there is some empty space under the file location?

**Comment by peller** [comment]
there is some unnecessary space, yes, but I was just making a note of that.  The bug was that the contents didn't fit in the dialog.  I can't seem to reproduce that problem now.
