### ISSUE TITLE
Choose custom Claro theme and mobile CSS files kick in

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1297]
- Clone claro into claro1
- New HTML file
- Click on switch theme button and in theme switch dialog choose "claro1" instead of "claro" for desktop theme

Result-> Canvas turns black
- Drag a Calendar onto canvas

Result-> Calendar gets mobile styling (e.g., larger-size font)

**Comment by billreed63** [comment]
Fixed by commit 1004829641899555a6bcd8e5ff715109562bed6a
