### ISSUE TITLE
Docs for deploying a Maqetta-created mobile app

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1298]
@jhpedemonte, @billreed63, @peller

Need to post public docs. Here are some notes:

To deploy your app so it works but with poor network performance:
- In Files palette, click on first icon (download entire workspace) to create a ZIP file for everything in your workspace. (Second icon allows you to download only selected files.)
- Transfer the ZIP file to your web server
- Create a new folder (e.g., <public_html_root>/f1/) in the public area of your web server
- Unzip into that folder. You should be able to run the mobile app in a browser by going to http://<mydomain>/f1/file1.html (or whatever you named the HTML file)

However, 2 significant problems with Preview 3:
- Bug: Preview 3 injects duplicate dojo.require() statements into the HEAD. You'll want to manually edit the HTML file(s) on your web server to remove the dupes
- Performance: Preview 3 doesn't integrate with Dojo's build system. Builds are essential for reasonable performance in mobile browsers. Adam Peller (cc'd on this list) ran the Dojo build system on the sample mobile file (http://maqetta.org/dojoconf) we showed at Dojo Conference in September. I don't know the details for now to run the Dojo build system on Maqetta-generated files. Preview 3 uses Dojo 1.7 and I don't know if the Dojo Web Builder service (http://build.dojotoolkit.org/) supports Dojo 1.7 yet. Adam, do you know, and if Dojo Web Builder isn't ready, yet, can you sketch out manual steps for Mandeep?

To deploy as an "app":

The approach most people take for installing a webapp as a native app is to use PhoneGap (http://phonegap.com). It provides tools for taking HTML+CSS+JS and making it into a natively installed app. We know at least one Maqetta.org user who succeeded with going all the way to PhoneGap, but running Maqetta content in PhoneGap triggers one more bug in the content that Preview 3 generates. For some reason, the text content of a dojox.mobile.ListItem cannot be in the 'label' attribute and must be child content. This user had to manually edit his HTML files to move the text content to get things to work.

**Comment by JonFerraiolo** [comment]
More notes on doing builds:

When you deploy using the standard Dojo release, the profile actually shouldn't be too bad and may not require customization.  The require for "dojox.mobile" is optimized to include all the dojox.mobile dependencies as well as a handful of the most common widgets, so you should actually find that there are only a few .js network requests to fetch your page.  When running on mobile, you can remove the dojo.require for dojox.mobile.compat to tighten things up a bit.  When we move to Dojo 1.7 final in Preview 4, you should notice an even smaller build based on refined dependency chains and an asynchronous loader.  If you wish to dabble in custom builds to further combine .js or .css files, you can use the command line Dojo build tool until the web builder Jon mentions gets a 1.7 upgrade.  The Dojo build tool documentation can be found here

http://dojotoolkit.org/reference-guide/build/

You'd do something like

./build.sh profile=myprofile action=release

where myprofile resembles what you'd find in the util/buildscripts/profiles directory of the Dojo source tree.  This will generate a copy of the entire Dojo tree, concatenating and minifying Javascript and CSS files to your specifications.  You'd then copy this over to your app which you deployed from Maqetta.  Again, I bet for basic cases, this level of optimization is unnecessary.

The duplicate dojo.require statements are no-ops.  You can remove them to clean up the page, but they shouldn't impact performance.

**Comment by peller** [comment]
So Preview 3 mobile apps run against a built version of Dojo, and the standard dojo.mobile profile seems to do fairly well.  Jon, I'm trying to remember why the dojoconf demo was unbuilt.  Perhaps it was assembled outside Maqetta?

DWB is not 1.7 ready yet, and we can refer people to the Dojo build docs to create their own profile, but that shouldn't be necessary most of the time http://dojotoolkit.org/reference-guide/build/  dojox/mobile.js on a built copy of Dojo includes most of the major mobile widgets and their dependencies, concatenated and minified, along with concatenated CSS.

The duplicate requires should be no-ops, but users could remove the dojox.mobile.compat dependency when running on mobile.

On Preview 4, the dijit/dijit dependency should also be removed, and dojo/parser should be replaced with dojo/mobile/parser, until we come up with a better solution.  The improved "baseless" Dojo dependencies along with the async loader in 1.7.0 final should further improve performance over Preview 3.

**Comment by JonFerraiolo** [comment]
I'm not going to have time to do this before we ship M4, so pushing to M5 with Priority-High

**Comment by peller** [comment]
I have started a document on how to [build a phonegap app](https://github.com/maqetta/maqetta/wiki/Deploying-Maqetta-projects-to-PhoneGap) from your web content and one on how to [manually fix up and build a Dojo-based page](https://github.com/maqetta/maqetta/wiki/Optimizing-and-Deploying-your-Dojo-based-page) with references to all the TODOs to make this task simpler or eventually automatic.

**Comment by peller** [comment]
Need better link and/or examples for creating a profile
