### ISSUE TITLE
Outline panel: invisibility does not persist across save/reopen file

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1299]
on today's internal build. running outline palette tests. setting widget visibility section.

Steps:
1) create a new HTML file
2) drop in a TabContainer
3) drop a Button into the TabContainer
4) click the eyeball icon in the outline palette and verify that the TabContainer disappears
5) save the file
6) reopen the file 

the result is that the outline palette visibility state for the TabContainer widget does not match the widget's appearance on the canvas.

**Comment by peller** [comment]
I suggest retesting after #1273 is fixed

**Comment by jhpedemonte** [comment]
Still broken after #1273 fix, but it's now a bit different than what Wayne described.

I see an error in console in **davinci.ve.commands.StyleCommand**.
