### ISSUE TITLE
Outline palette: cannot make a button invisible

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1300]
on Mac/Safari 5.1.2 with today's build

1) create an HTML file
2) drag a Button onto the canvas
3) click the eyeball icon in the outline palette to make the button invisible

result is that the outline palette blinks but the closed eye icon does not appear nor does the Button become invisible.

**Comment by jhpedemonte** [comment]
This is working for me with Dec 4 nightly.  But still getting console error as in #1299.
