### ISSUE TITLE
Switch theme dialog fails on second switch

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1304]
- New HTML File - Mobile, iPhone, default theming
- Add a View and Heading
- Switch theme for all devices to "android"

==> good so far
- Switch theme for all devices to "blackberry"

Result=> white background and 2 black unstyled "Heading" blocks on screen, indicating no styling

It doesn't seem to matter which themes are used. It seems to fail on the second theme switch.

**Comment by billreed63** [comment]
This is a video bug, if I switch to source and then back the proper style is displayed

**Comment by billreed63** [comment]
fixed above
