### ISSUE TITLE
Global button styling widget for mobile theme editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1306]
@jhpedemonte 

I realize this is a late feature request, but I think we should hold up shipping until we do this. I'm hoping it's just a day or two of work. I might be able to do this if @billreed63 is unavailable.

Right now there are a handful of dojox.mobile widgets that use the same background color: Heading, ToolbarButton, Button, a few more. To change this color in the current theme editor, the user has to remember the colors he used for one of these widgets and then manually update the others. If he iterates through multiple color tweaks, then all of this manual effort will be a huge pain.

IMO, providing convenient editing for all of these widgets at once is a big enough productivity benefit to users (and a big impact on users's opinions of the usefulness of the mobile theme editor) that it's worth waiting a day or two for this.

**Comment by jhpedemonte** [comment]
Isn't this really an issue with the Dojox Mobile CSS files?  I believe Dijit works correctly:  background is defined in one place and affects all widgets (correct me if I'm wrong).  Dojox Mobile should do likewise.

**Comment by JonFerraiolo** [comment]
I'm pretty sure it's an issue with the mobile theme metadata. There is a special syntax in the desktop/claro theme metadata for the global stuff. We just haven't written the corresponding metadata for mobile.

**Comment by billreed63** [comment]
They may be set using a LESS variable but we use the post LESS versions of the CSS files. At that point the LESS variable in the css rule has been replaced with the corresponding value. Mobile uses the same approach. 

the background color is scattered around the rules in dijit just like mobile.

**Comment by billreed63** [comment]
For mobile widgets the we would need to set the background-image as well. the widgets use -webkit-gradient.

In the case of global widget in the desktop theme editor, the global widget has states, the value of the state color is calculated based on a delta of the "Normal" state color. that delta is then applied to the new "Normal" color to determine the new state color.  This becomes much more complex in the case of gradient's.

A few mobile widgets do have states, ToolBarButton for example

**Comment by JonFerraiolo** [comment]
For a good number of mobile widgets, the gradients on background-image are just opacity filters. Users can simply change background-color and leave gradient alone and that will get them in the right ballpark visually. That's probably all we will be able to do for M4 via automatic cross-widget features: just allow background-color changes.

**Comment by billreed63** [comment]
the widgets that are currently supported in the mobile theme editor are all gradient dependent. 

For Heading, ToolBarButton, TabBarButton, EdgeToEdgeCategory, Button, ToggleButton  changing the background color has no effect. I must change (remove) the gradient to see the new background color.  This was the reason we added gradient support for background-image

**Comment by billreed63** [comment]
Jon is referring about the mobile custom theme, where as I was talking about the device themes..
We can create a global that only changes background-color for the custom theme.
