### ISSUE TITLE
Border properties not working in mobile theme editor on ComboBoxList

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1307]
@billreed63

In Mobile Theme editor, changing border properties on ComboBox list widget doesn't change anything visually on the mobile theme editor canvas.

This is probably a theme metadata bug, but the ComboBox list "widget" in the theme editor is more of a fake widget that provides the user the ability to edit the styling on the menus that pop up from the ComboBox widget.

**Comment by JonFerraiolo** [comment]
Reassigned to @billreed63

**Comment by billreed63** [comment]
Seems to be working now...
