### ISSUE TITLE
Custom theme shows as %20.css in preview-as-browser

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1308]
- New HTML File, choose Mobile, Android, and click on pencil icon. Choose custom theme for all devices
- Add a View and Heading
- Preview in browser

Result=> Nothing shows and debugging console shows this:

`States.js:1108Uncaught TypeError: Cannot read property 'parse' of undefined
http://localhost:8081/maqetta/user/maqettaUser/ws/workspace/project1/lib/dojo/dojox/mobile/themes/%20/%20.css
Failed to load resource: the server responded with a status of 404`

**Comment by billreed63** [comment]
fixed by above commit
