### ISSUE TITLE
BackgroundDialog problems with non-default cascade choices

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1309]
@childsb

The BackgroundDialog logic changes mutliple properties at once, and this causes problems with Cascade.js logic when a non-default choice is made about which style rule to target.

I tried to change background properties in a Calendar with a custom CSS class in app.css. Changing background-color in the dialog targeting a new CSS rule actually worked, but probably there are multiple problems. One clear manifestation is that there are multiple "cannot change read-only CSS rules" prompts.

**Comment by peller** [comment]
I noticed a for loop in Cascade which accumulates hashes.  Was this deliberate?

**Comment by JonFerraiolo** [comment]
Do you have a line# for Cascade.js? There's a lot of code there.

**Comment by peller** [comment]
yah sorry, had to dial in to some daily conference call :-)

I was thinking of Cascade.js around line 200 and meant to bring it up.  The var "a" was reused and accumulated values.  Looks like @JonFerraiolo fixed it c33767f83fedf1171c872a54ed657dbb236e2a5c
