### ISSUE TITLE
Dialog doesn't expand to fit its content

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1314]
- add a Dialog
- drag/drop Calendar widgets until the Calendar drop off bottom of Dialog

Result=> No auto-resizing of Dialog based on content

**Comment by peller** [comment]
so noted.  A default size is assigned to the Dialog in metadata, which prevents resizing (and perhaps shouldn't even be allowed)  Without a size, Dialog acts a little quirky in the visual editor.  Need to look at this more.
