### ISSUE TITLE
jQuery and YUI widgets not working

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1328]
tested on lab9

dnd a YUI Calendar on the page and get

```
Uncaught ReferenceError: YAHOO is not defined
(anonymous function):50010/maqetta/:1
require.cache.davinci/ve/_Widget._f04.addChilddavinci/davinci:20432
require.cache.davinci/ve/commands/AddCommand.dojo.declare.executedavinci/davinci:23690
require.cache.davinci/commands/CompoundCommand.dojo.declare.executedavinci/davinci:34223
dojo.withDocdojo.js:5106
require.cache.davinci/commands/CommandStack.dojo.declare.executedavinci/davinci:31194
require.cache.davinci/ve/tools/CreateTool._fc6._createdavinci/davinci:21882
require.cache.davinci/ve/tools/CreateTool._fc6.createdavinci/davinci:21860
require.cache.davinci/ve/tools/CreateTool._fc6.onMouseUpdavinci/davinci:21750
require.cache.davinci/ve/Context._1c56.onMouseUpdavinci/davinci:45433
_312
```

dnd a jQuery DatePicker and get something similar

**Comment by jhpedemonte** [comment]
I'm a bit confused.  The jQuery JS files are loaded through this bit of code in `Context.addJavaScriptSrc()`:

``` javascript
    dojo.withGlobal(this.getGlobal(),
        function() {
            dojo.xhrGet({
                url: absoluteUrl,
                sync: true,
                handleAs: "javascript"
            });
        });
```

But `this.getGlobal().$` is **undefined**, whereas `window.$` is.  So jQuery's **$** is set in the app's context, not the VE frame's context.

Internally, `xhrGet` calls `dojo.eval()` for the `"javascript"` handler.  There doesn't seem to be anything in `dojo.eval()` that evaluates the code using `dojo.global`.  Not sure how this works for anything.

**Comment by peller** [comment]
dojo.withGlobal redefines the value used for window by Dojo code within the enclosed block, or at least it's supposed to.  I've got a feeling dojo.eval() broke that in 1.7

**Comment by jhpedemonte** [comment]
Dojo 1.7 regressed `dojo.eval`, so that it no longer uses `dojo.global` -- instead, everything is evaled into the global context.  That means that using `dojo.withGlobal()` had no effect in this case.

I worked around it for now, and Adam filed a bug with Dojo (http://bugs.dojotoolkit.org/ticket/14406).
