### ISSUE TITLE
Refactor states code to use Dojo base

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1337]
Use Dojo Nano on every user page and use that to load necessary pieces of Dojo, remove copy of Dojo base in States.js  States and maqetta files themselves would become AMD modules and participate in AMD optimization.
Investigate "cache" variable and preserve/restore States code, whether cache should be preserved through the closure or just passed as a local variable.

@JonFerraiolo @jhpedemonte

**Comment by jhpedemonte** [comment]
-> M6/Med

**Comment by peller** [comment]
fixed by 6bae0ed64f843abc9d5c3446540b79230498c664
