### ISSUE TITLE
FF: this.rootNode is null with new theme command in built version

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1339]
@peller, @billreed63 

This one has been there for awhile. It might already be reported but I don't see it in bug base.
- Use FF
- Clean user workspace (e.g., pull down a nightly and run it for first time)
- Launch maqetta
- Immediately say "New Theme" and clone custom to custom1

Result=> this.rootNode = null in setWorkbenchState

**Comment by peller** [comment]
@JonFerraiolo, you don't say what the end result is, but if it's the blank tab, that seems entirely unrelated to the exception.

**Comment by peller** [comment]
didn't mean to close it last night, but it does indeed fix the bug
