### ISSUE TITLE
FF: Mobile theme editor - Build - Change global background - exception

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1340]
@peller, @billreed63

FF only bug when running built version. Works with Chrome and works with FF when using Eclipse/localhost.
- Clone "custom" to a new theme (e.g., "custom1"). (May run into #1339. If so, close the theme editor that opens will a blank screen, then "Open->Theme Editor" on the theme you just created
- Select topmost widget (Font and background styling)
- In Properties palette, click on color swatch next to background-color property. Choose a different background color.

Result=> Console shows  `_ld10 undefined`

**Comment by peller** [comment]
@waynevicknair 

running an unminified version of the build, I see it fail on this line in davinci.html.CSSParser.parse where property is null:

``` js
} // END while (nextToken().content != '}')
if (pushComment != null) { 
>>>  property.postComment = pushComment;
```

it's being called from cssFile.setText(selector) where selector is `.mobile body{}`

Wayne, can you shed any light on what this might mean?

(?)(text=".mobile body{}", parentElement=Object { elementType="CSSFile", startOffset=0, endOffset=0, more...})
getProperty(text=".mobile body{}")
(?)(selector=".mobile body{}")
(?)(selector=".mobile body")
(?)(widget=davinci.ve.DijitWidget{...}, subwidget=null, state="Normal")
addShortHandProps()
NewFile(command=davinci.ve.themeEditor.commands.StyleChangeCommand{...})
disableWidget(value=Object { values=[1], appliesTo={...}})
(?)()
(?)()
emit(target=uniqName_0{...}, type="/davinci/ui/styleValuesChange", event=Object { values=[1], appliesTo={...}})
emit(target=uniqName_0{...}, type="/davinci/ui/styleValuesChange", event=Object { values=[1], appliesTo={...}})
emit(type="/davinci/ui/styleValuesChange", event=Object { values=[1], appliesTo={...}})
publish(topic="/davinci/ui/styleValuesChange", event=Object { values=[1], appliesTo={...}})
publish(topic="/davinci/ui/styleValuesChange", args=[Object { values=[1], appliesTo={...}}])
(?)(targetIndex=2, value="#7837b4")
(?)()
(?)()
(?)()
(?)(event=undefined)
(?)(value="#7837b4")
(?)(name="value", value="#7837b4")
(?)(name="value", value="#7837b4")
postscript()
(?)(popup=[dijit_TooltipDialog_0 (Widget dijit.TooltipDialog)])
(?)()
method()
(?)()
(?)()
(?)()
(?)()
(?)(e=click clientX=1226, clientY=367)
inherited(args=[click clientX=1226, clientY=367], a=undefined, f=function())
(?)(e=click clientX=1226, clientY=367)
(?)()
(?)(e=click clientX=1226, clientY=367)

**Comment by peller** [comment]
for me the operation completes despite the exception, so this may not be a critical bug.  I see the selection every time I select the "font and background styling" box, whether or not I mess with the background color.

**Comment by peller** [comment]
@waynevicknair any chance it's confused by the lack of spacing before the "{"?

**Comment by peller** [comment]
Wayne, please take a look.  @JonFerraiolo I think we can safely downgrade this from 'high' priority, perhaps even bump to M5 if there are no negative side-effects.

**Comment by JonFerraiolo** [comment]
if no negative side-effects, sure, M5

**Comment by waynevicknair** [comment]
here's the stack trace i see on todays internal build on Mac/FF:

getWidgetTopDom()
r = Object { elementType="CSSRule", startOffset=0, endOffset=74, more...}
(?)(e=Object { elementType="CSSRule", startOffset=0, endOffset=74, more...})
(?)()
(?)()
(?)()
(?)()
(?)()
(?)()
(?)(arg=undefined)
CSSCombinedSelector(_122e="background-color")
getUniqueID(rule=Object { elementType="CSSRule", startOffset=0, endOffset=74, more...}, _1d1a=[Object { background-color="#efedf1"}])
(?)(_bd=[Object { elementType="CSSRule", startOffset=0, endOffset=74, more...}, Object { elementType="CSSRule", startOffset=76, endOffset=221, more...}, Object { elementType="CSSRule", startOffset=159, endOffset=250, more...}], _be=[Object { background-color="#efedf1"}])
(?)()
(?)(_152e=Object { _themeEditor={...}, _values=[1], _firstRun=true, more...})
(?)(_27c=Object { values=[1], appliesTo={...}})
(?)()
(?)()
emit(_3a9=Object { declaredClass="uniqName_0", on/davinci/ui/libraryChanged=function(), on/davinci/states/state/changed=function(), more...}, type="/davinci/ui/styleValuesChange", _3aa=Object { values=[1], appliesTo={...}})
emit(_3ad=Object { declaredClass="uniqName_0", on/davinci/ui/libraryChanged=function(), on/davinci/states/state/changed=function(), more...}, type="/davinci/ui/styleValuesChange", _3ae=Object { values=[1], appliesTo={...}})
emit(type="/davinci/ui/styleValuesChange", _328=Object { values=[1], appliesTo={...}})
publish(_331="/davinci/ui/styleValuesChange", _332=Object { values=[1], appliesTo={...}})
publish(_44f="/davinci/ui/styleValuesChange", args=[Object { values=[1], appliesTo={...}}])
_buildCssRuleset(_589=2, _58a="#efedf1")
(?)()
(?)()
(?)()
(?)(event=undefined)
(?)(value="#efedf1")
(?)(name="value", _2ae="#efedf1")
_1f9(name="value", _1d4="#efedf1")
(?)()
(?)(_27d=[Widget dijit.TooltipDialog, dijit_TooltipDialog_0] { _attachPoints=[1], _attachEvents=[0], _inherited={...}, more...})
(?)()
_314()
(?)()
(?)()
(?)()
(?)()
(?)(e=click clientX=874, clientY=381)
_260(args=[click clientX=874, clientY=381], a=undefined, f=function())
(?)(e=click clientX=874, clientY=381)
(?)()
(?)(e=click clientX=874, clientY=381)

the offending code is where we try to reference a property of an undefined document (_1d18), namely '.styleSheets':

``` javascript
var _1d18=this.getDocument();
var _1d19=_1d18.styleSheets; 
```

i don't see the CSSParser throwing an exception here. but the color change succeeds. so, downgrading and moving to M5.

**Comment by jhpedemonte** [comment]
-> M6

**Comment by waynevicknair** [comment]
hey @billreed63 , i just tried to recreate this on macwayne2 running Mac/FF and i don't see any console errors. can you please verify that this bug still exists for you?

**Comment by billreed63** [comment]
This bug appears to have been fixed
