### ISSUE TITLE
fixed=top/bottom problems

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1344]
@peller 

I can't get the 'fixed' attribute to work properly with latest code. I'm running a daily build (http://maqetta.org/nightly/maqetta-20111209-0603.zip) on Mac/Chrome right now.
- New HTML File (mobile, iphone, default theme)
- Add a View, a Heading, RoundRectList, and TabBar
- Under widget-specific, set fixed=top for Heading and fixed=bottom for TabBar

Result=> TabBar doesn't jump to bottom as it should
- Double-click on RoundRectList and add many lines of text (to force scrolling)
- Save
- Preview in browser

Result=> fixed=top and fixed=bottom logic appears to be at least partly broken. TabBar doesn't appear on initial screen. Source code and DOM structure all look correct. Based on what I'm seeing, it looks like there might be a bug in Dojo, but that would be shocking for something this basic, so it's probably something we aren't doing right.

**Comment by jhpedemonte** [comment]
Remember, **"fixed"** only works for **ScrollableView**.  Do the above with that widget, instead of **View**, and the "fixed" bits will work as expected.

Now, I am still seeing some issues, with RoundRectList overlaying Heading. Not sure what's up with that, but that's not this bug.

**Comment by JonFerraiolo** [comment]
Reopening. On Mac/Safari, using Blackberry, if I add a Heading (fixed=top) and then TabBar (fixed=bottom) and then various mobile widget until there is too much for ScrollableView, then in Preview the other widgets overlap either the TabBar or the Heading.

**Comment by jhpedemonte** [comment]
Closing this.  Only remaining issue I see is #1577 (widgets mispositioned in ScrollableView).
