### ISSUE TITLE
state change publish should pass editor object, subscribe should check

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1349]
@billreed63 

I think this is the cause of various intermittent bugs, which is why I assigned it to Priority-Med

Various parts of the code publish `*/state/changed` and various other parts of the code subscribe to this event. The problem is the event doesn't pass any information about which editor window the state change applies to. As a result, in some cases, state change events published in editor A are received by editor B. I think the safest and most reliable fix is to always pass an editor pointer on the event object with each publish and then check that pointer with each subscribe.

Note that I checked in a bandaid fix for one particular problem in this area: where the theme editor publishes `*/state/changed` with '$all' as the widget (i.e., a string instead of a widget object) but one of the open page editor has subscribed to this event and was trying to call `getParent` on '$all'. My bandaid was making sure that "widget" is an object (and not a string): 0b90104b3f 

It might be that there is existing logic that (mostly) prevents such a scenario from happening, but I've been able to trigger such a scenario by having four editors open at once: mobile html page editor, mobile theme editor, mobile theme editor and mobile html page editor (in that order) and then try various combinations of switching editors and refreshing the Maqetta browser window.

**Comment by peller** [comment]
I'm wondering why we don't pass something like null for widget instead of '$all' which is a bit awkward, but if it's working, that's fine.

Regarding the proposed change, I'm thinking perhaps we should pass `context` instead of `editor` as the object for comparison.  Most of the time this is trivial, except for the States.js file, which has no exposure to Maqetta and is designed to be used outside the workbench.  @JonFerraiolo, thoughts on that?

**Comment by JonFerraiolo** [comment]
I created a separate issue (#1421) to look into $all.

Passing `context` instead of `editor` sounds fine and is probably better. But is there a Context during preview-in-browser? Sorry, I don't remember the details in this part of the code.

**Comment by peller** [comment]
preview-in-browser just runs in a plain browser window, so there isn't a context or an editor,  same as when you run an app outside the workbench and use the States.js code (see question above)   The same event is published whether you're in the workbench or not, so it's a little unclear how to handle the new parameter.

**Comment by peller** [comment]
@JonFerraiolo and @peller will review this code in M6

**Comment by JonFerraiolo** [comment]
Closing. Researched the code and everything looks OK as is, except maybe for some of the theme editor logic. I logged issue #2185 to research that.
