### ISSUE TITLE
davinci/library debugger statements in code

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1353]

**Comment by childsb** [comment]
where?

**Comment by peller** [comment]
davinci/library.js, lines 47, 193, 208

**Comment by JonFerraiolo** [comment]
@jhpedemonte: For assert logic that checks to see if valid parameters are passed in correctly, wouldn't it be better to:
- Fail gracefully (if at all possible)
- Report the problem using console.error() (versus using a debugger statement)

**Comment by peller** [comment]
failing not-so-gracefully is fine, too, maybe even best.  Unfortunately, in this case, the array look-ups would probably succeed if the value is undefined.  console.error doesn't stop the flow of execution.  Causing or explicitly throwing an exception here is probably the right thing to do.

**Comment by childsb** [comment]
moving to m5
