### ISSUE TITLE
Need to load "library" OAM props, even if no "require" references it.

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1355]
Here's the "library" & "require" part of the **circle_oam.json** metadata file from the **Drawing Tools** library:

``` js
    "library": {
        "shapes": {
            "src": "../../../shapes"
        },
        "dojo": {
            "src": "../../../dojo/dojo.js"
        }
    },
    "require": [
        {
            "type": "javascript-module",
            "format": "amd",
            "src": "shapes/Circle",
            "$library": "shapes"
        },
        {
            "type": "css",
            "src": "shapes.css",
            "$library": "shapes"
        }
    ],
```

Notice that, while there is a "dojo" library, none of the "require" members reference "dojo".  In our current code, that means that **dojo.js** doesn't get loaded.

From my reading of the [OAM spec](http://openajax.org/member/wiki/OpenAjax_Metadata_1.0_Specification_Widget_Metadata#.3Clibrary.3E), it seems that this shouldn't be the case, and we should always be handling the "library" property.

@JonFerraiolo @peller

**Comment by peller** [comment]
It seems odd that "src" on library indicates either a directory or a resource.  The OAM spec does seem like you need to specify within the library element that it actually requires the js file.

**Comment by jhpedemonte** [comment]
As you said, the OAM spec allows for "src" in "library" element to indicate either a directory or JS file.  This was done for the one-file libraries, such as Prototype or jQuery.
