### ISSUE TITLE
SaveAs shows incorrect file name

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1360]
- New HTML File - accept defaults (e.g., file1.html) and click ok/Create
- Drag a Button onto canvas
- Click SaveAs icon

Result=> SaveAs dialog appears with `./project1/file1.html` in the file name field instead of just `file1.html`

**Comment by childsb** [comment]
Fixed this and another bug I noticed when saving into nested folder:

/folder1/file1.html is show as file name instead of "file1.html" as file name and "folder1" in "where"
