### ISSUE TITLE
claro shows in list for Open->Theme Editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1365]
@billreed63 
- New Theme... and clone claro to claro1
- Save the theme
- Go to Open Theme Editor... menu command

Result=> Dialog shows both claro and claro1 in the list. If you try to select "claro", an exception appears in console.

**Comment by peller** [comment]
OpenThemeDialog.okButton, newTheme is null

**Comment by JonFerraiolo** [comment]
Of course, 'claro' shouldn't be listed as an option in the first place.
