### ISSUE TITLE
findResource of *_widgets.json call is very slow - build only

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1368]
Reproduced on both Chrome and FF.  Out of a total startup time of ~15 seconds, this one call takes about 7 seconds.  It happens during the initial Maqetta load, even when no files are open, such as the initial launch after installation.  The performance problem only occurs when running a built copy of Maqetta from the command line.  The same call when running from Eclipse takes ~300ms.  However, the call likely should not be occurring at all.  

I also wonder whether we can reduce the need for findResource, in general, by using naming conventions, keeping track of files, or reducing the scope of files searched to a small number of directories.

**Comment by childsb** [comment]
removed this call for now.

**Comment by peller** [comment]
fixed by 9d64a6c69b08b914a35a1c2e50476367acf4d980
