### ISSUE TITLE
No caret appears in SourceEditor

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1369]
Mac/Chrome

Steps:
1) create new HTML file accepting defaults
2) drag dojox mobile view onto canvas
3) drag dojox mobile header onto canvas
4) drag dojox mobile view onto canvas
5) switch to source view

Expected result: source view with insert caret

Actual result: source view with no insert caret. can click around in source,  but still no caret appears.

**Comment by peller** [comment]
@JonFerraiolo 

Preliminary investigation shows that the regression occurred on or around 3f670519b1f73f8679b0e4a808ff169a4d2b429b
