### ISSUE TITLE
New HTML File -> New Folder -> Save in new folder: Files palette doesn't refresh

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1371]
Priority-High because it's a must-fix before shipping, but not the most urgent bug in the queue.
- New HTML File
- In dialog, open up file listing, and click on New Folder
- Create a new folder

PROBLEM #1: The new folder name doesn't appear in "Where". (Also mentioned in #1362)
- Click on new folder make it the current folder (to overcome PROBLEM #1)
- Click "Create" to create a new file in the new folder
- Add a Button
- Save and close the editor tab

PROBLEM #2: The Files palette doesn't update to show the new file. The new folder continues to look like it is empty of any child files. Only way to get the new folder to have the expando "+" next to it is to refresh the browser window.

**Comment by childsb** [comment]
This was weird.  There was an extra / in the resource path, causing the project name to get truncated.  the new files were being created in the base workspace.
