### ISSUE TITLE
Focus (selection handles) get created for invisible widget

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1372]
Mac/Chrome

Steps:
1) create new HTML file accepting defaults
2) drag dojox mobile view onto canvas
3) drag dojox mobile header onto canvas
4) drag dojox mobile view onto canvas
5) switch to horizontal split view
6) click in source view on mobile heading which is hidden in visual editor view

Expected result: no-op

Actual result: a small Focus object appears in the upper left hand corner of the visual editor frame. if you ignore the focus object and select a visible element such as the second mobile view object, the empty focus object disappears. however, if you resize the empty focus object it resizes the invisible mobile heading such that it will show its new size when it becomes visible again.

**Comment by waynevicknair** [comment]
the code below in PageEditor.js selects the widget in the visual editor without regard for the widget's 'display' style setting.

``` javascript

    _modelSelectionChange: function (selection) {
        /*
         * we do not want to drive selection on the view editor unless:
         *     - we are in an editor mode which has a view editor (not source mode)
         *     - we are the current editor
         */
        if( this._displayMode == "source" || davinci.Runtime.currentEditor !== this ) {
            return;
        }

        this._selectionCssRules = null;
        if ( selection.length ) {
            var htmlElement = selection[0].model;
            if ( htmlElement && htmlElement.elementType == "HTMLElement" ) {
                var id = htmlElement.getAttribute("id");
                if ( id && this._displayMode!="source" ) {
                    var widget = davinci.ve.widget.byId(id, this.visualEditor.context.getDocument());
                    this.visualEditor.context.select(widget);
                }
            }
        }
    },
```

**Comment by JonFerraiolo** [comment]
@waynevicknair - just curious, what version of software are you using? I fixed a bug in this general area yesterday (8a02a1f261), but my fix only took care of deselecting widgets with state changes due to clicking in the States palette. As part of that fix, I added a utility function `Context.js: deselectInvisible()`. Maybe we can call that routine as part of the fix for this bug.

Assigned for time being to @waynevicknair because we probably can't attempt to fix this until the source editor is solid. Changed to Priority-Low for M4.

**Comment by waynevicknair** [comment]
i'm currently running out of eclipse on commit 2c5acf925da137de1cbd86e50004d9867dbbf3d1 which came after yours.

**Comment by JonFerraiolo** [comment]
@waynevicknair - can we keep this assigned to you until the source editor beast has been tamed, and then think about whether to reassign to me at that point? Like I said above, I don't think it makes sense to try to fix this until the source editor fixes are in place. At that point, then probably I would be best to take it from there.

**Comment by jhpedemonte** [comment]
Also see #57.

**Comment by JonFerraiolo** [comment]
Another issue blocking this issue is #1435

**Comment by waynevicknair** [comment]
moving to M5

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo M7 Prio-Med

**Comment by JonFerraiolo** [comment]
This seems to have been fixed along the way. We now have logic that makes the currently selected view visible.
