### ISSUE TITLE
Start and End offsets wrong on selection highlite in horizontal split view

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1373]
Mac/Chrome

Steps:
1) create new HTML file accepting defaults
2) drag dojox mobile view onto canvas
3) drag dojox mobile header onto canvas
5) switch to horizontal split view
6) select mobile header in visual editor frame

Expected results: <H1> element in source frame will be highlighted 

Actual results: highlighting starts in middle of H1 line and goes to end of file

**Comment by JonFerraiolo** [comment]
This one had been unassigned. Assigned to @waynevicknair

**Comment by waynevicknair** [comment]
duplicate of issue #1258
