### ISSUE TITLE
Can't switch themes if New HTML Page starts with "custom"

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1374]
- New HTML File
- Choose iPhone as composition type, click on New Theme... and choose "custom" for all devices, click OK/Create to create a new page with an iPhone silhouette
- Click on Switch Theme icon

Result=> At top of dialog, it says "custom_default" and all options are disabled, which means you can't switch themes.

**Comment by billreed63** [comment]
"custom_default" is the "out of the box" default theme set we create for the user.  That theme set is claro for desktop and custom for all devices. When the user switches themes we use the definitions in the html file to match to the users theme sets. In this case it matches the "custom_default" theme set, so we set the theme set in the theme switching dialog. The user can use the drop down and select "(none)" for the theme set and then the other drop downs are enabled.

**Comment by JonFerraiolo** [comment]
Ah, I see what's happening now. I'm opening a different bug (#1442) to think through how to make what's happening clearer to users.
