### ISSUE TITLE
Need confirmation dialog when deleting project

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1375]
There's no confirmation when clicking on the **red X** beside the project name.  Since this deletes the project files, we must confirm such a destructive operation.

(Assigning to Brad and M4, but feel free to change.)

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
I think it's OK to push this to M5 and Priority-High, which I have done.

**Comment by aerwin** [comment]
While working on this issue, I noticed there was no flyover text for the Delete and Rename buttons, so I addresses that. I also fixed a place I saw an English string in ProjectToolbar.js.
