### ISSUE TITLE
New File dialog: "Where" shouldn't be blank on first show

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1376]
In the **New File dialog**, the **Where** field is initially blank.  This doesn't look good and can be confusing to users (i.e. what am I supposed to type in that field?).

There should be **default text** for that field, using the current top level folder (the project name -- "project1").

Some other additions that would help this field:
- Clicking in the text field should have the same result as clicking on the arrow -- it displays the files tree.
- Also when clicking in text field, we should display a tooltip letting users know they can either select a folder from the files tree or write a name to create a new folder.

**Comment by JonFerraiolo** [comment]
Good feedback and suggestions.

@childsb

**Comment by JonFerraiolo** [comment]
Mostly a duplicate with #1289. Pushing to M5.

**Comment by jhpedemonte** [comment]
I think we should do something for M4.  The **New File** dialog has changed quite a bit since M3 and now there's an empty text box in the middle.  Could be confusing.

At the very least, we can make the **Where** text box non-editable.

**Comment by peller** [comment]
confusing, but consistent.  We don't show the top-level folder in the tree, so blank is actually correct.  Putting project1 in that box makes sense only if we put project1 back as the root node in the tree.  I don't like lots of tooltip popups.  If the dialog is complex enough to require a guide, something's wrong.  I think we have a separate proposal to make this field a choice popup.  I think I like that best.

**Comment by JonFerraiolo** [comment]
restored to M4. Maybe what we can do in short-term until we put a menu instead of the textbox is to is put "(project root folder)" in the text box if it would otherwise be empty and then set the read-only bit on the textbox so that it gets read-only styling.
