### ISSUE TITLE
Can't copy/paste TabContainer

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#138]
@JonFerraiolo reports:

I am running http://maqetta.org:55555/maqetta using Mac/Chrome. Here is how to
reproduce:
- Login to maqetta.org, which opens the app
- Close any open editors
- Refresh the browser
- Create 2 new HTML pages, both empty
- In the first page, add a TabContainer, then "copy"
- Switch to second page, and the "paste"

Console says: Uncaught TypeError: Cannot read property 'prototype' of undefined

**Comment by peller** [comment]
dies in createWidget calling the DijitWidget constructor, at this line

``` js
var proto = c.prototype
```

c is undefined because the initialization failed

``` js
var c = davinci.ve.widget._dojo(node).getObject("dijit.layout.ContentPane");
```

It looks like it's pulling in the resources for the TabContainer widget itself, but not the child (ContentPane)  If you drop a ContentPane in the page before doing the paste, it works fine.

**Comment by JonFerraiolo** [comment]
Adding this to M3

**Comment by peller** [comment]
We're part way there.  context.loadRequires seems to do what's necessary to load the code onto the page and the paste looks successful, but the dependencies are not making it to the source view until the file gets reparsed -- you must close and reopen the file to see the dojo.requires in source view.
