### ISSUE TITLE
New folder in new folder - Files palette not updated

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1383]
- New HTML File
- Open up files view and click on New Folder, create project1/folder1
- Click on New Folder again (with folder1 highlighted), and create project1/folder1/folder1 (or whatever)
- Click Create to create a new HTML File
- Add a Button
- Save, close

Result=> Files palette doesn't show the nested folder. The nested folder shows if you hit refresh.

**Comment by childsb** [comment]
I verified that this is working OK now, closing
