### ISSUE TITLE
Properties palette - background properties don't show for mobile UIs 

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1384]
@childsb, @billreed63 

This is a strange one. For mobile UIs (and of course using mobile themes), the Properties palette isn't showing background properties for mobile widgets.
- New HTML File - blackberry
- Add a View
- Add a Heading
- Open up background section of Properties palette 

Result=> No background properties show

**Comment by JonFerraiolo** [comment]
Reassigning to @billreed63. I suspect it's a theme metadata issue.

**Comment by billreed63** [comment]
This is do to the dynamic theme loading by dojox.mobile.deviceTheme. The themes are added to the head at run time, so the CSS files are not parsed by the CSSModeler.

**Comment by JonFerraiolo** [comment]
Pushing this to M5. Way too risky for M4 to attempt to get model to work with dynamic theme loading.

**Comment by billreed63** [comment]
fixed by #1574
