### ISSUE TITLE
Don't URL encode PUT requests (manual save, auto save)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1388]
What about the path string: /maqetta/.%2Fproject1%2Ffile3.html.workingcopy? Why does the URL use entities for the slashes instead of just using slashes? When I open a file, I see a GET request to something like 

http://localhost:8081/maqetta/user/maqettaUser/ws/workspace/project1/file6.html

whereas the PUT request for either auto-save or manual save shows this:

http://localhost:8081/maqetta/.%2Fproject1%2Ffile6.html

(@peller says: I think we should only be using encoding on query parameters.)

**Comment by jhpedemonte** [comment]
-> M6

**Comment by peller** [comment]
@childsb, wasn't this fixed?

**Comment by peller** [comment]
fixed in dd5b7fc9
