### ISSUE TITLE
this._fadeOutDeferred is undefined error after creating a new HTML file

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1393]
1) create a new HTML file in FF
2) when the dialog closes you see a "this._fadeOutDeferred is undefined" in Dialog.js

i noticed this off and on after the themeset changes to the new file dialog.

**Comment by jhpedemonte** [comment]
@peller 

This is an error in **dijit/Dialog.js**.  Dojo error, or are we doing something wrong?

**Comment by peller** [comment]
The dialog is getting hidden twice.   First by an "onClose" event fired by the custom dialog in _okButton and handled in Workbench.js, then by the Dialog itself.  As a result, the onEnd/fadeOut animation gets created twice and steps on the handle twice.

All that logic to manually close the dialog should be unnecessary.

**Comment by jhpedemonte** [comment]
Which is unnecessary?  The one in `_okButton` or in **Workbench.js**?

**Comment by peller** [comment]
I'm not sure what other logic is involved in the `callBack` function onClose is bound to, but minimally we can remove the line that calls `hide()` in Workbench.js (line 498)

I'd prefer we do away with custom dialogs entirely, perhaps just using templates with the stock dijit.Dialog.
