### ISSUE TITLE
multiple errors when switching to source view

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1394]
1) open Sample1.html on a built version of maqetta
2) click one of the source view icons
3) If firebug is on with break on error enabled, you'll stop in some dojo compiled code with "_1a29 is null"
4) hit resume, then notice a second similar error.  If you resume here the source editor will eventually load.

**Comment by peller** [comment]
this is likely the pixelX error.  has no impact whatsoever, and should be resolved next time we upgrade Orion.

**Comment by peller** [comment]
errors occur in the non-built version, too, including many caught errors in the parser.  I recommend closing.

**Comment by JonFerraiolo** [comment]
Yeah, the parser leverages exceptions as part of normal processing (vs using exceptions just for errors).

**Comment by peller** [comment]
we should try to capture stacks when this sort of thing happens, even if they appear to be garbage.  The pixelX exception I often saw (may or may not be what @childsb saw) is gone with the update using the I201112182230 Orion build in 45cc11f3aad5af77d27438fd18bf2197b3470a26 I still see some undefined references, such as this one "Cannot set property 'className' of null" (document.body is null):

```
TextView._setThemeClass() at orion/textview/textView:5551
TextView._createContent() at orion/textview/textView:3750
TextView._createView._createViewTimer() at orion/textview/textView:3736
```

and this one: "Cannot call method 'getPropertyValue' of undefined" where the value for getComputedStyle is null

```
TextView._getPadding() at orion/textview/textView:4447
TextView._calculatePadding() at orion/textview/textView:3041
TextView._createContent() at orion/textview/textView:3874
TextView._createView._createViewTimer() at orion/textview/textView:3736
```

There appear to be no negative side effects, so I'm marking this low priority and will report to the Orion team.

**Comment by peller** [comment]
see also #1889

**Comment by peller** [comment]
-> M6 where perhaps we'll want to try an Orion refresh before tackling this

**Comment by peller** [comment]
seems to be fixed with orion-I201204091010
