### ISSUE TITLE
delete state results in NPE

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1395]
1. in FF, enable "break on error" in firebug
2. Issue a "New HTML File" command.
3. In the States palette, click on the + icon to define two states "aaa" and "bbb"
4. In the States palette, select the "bbb" state and click on the - icon to delete that state

observe
"_fr1[i] is undefined" deep within built code.

**Comment by peller** [comment]
unbuilt, on Chrome, it looks like it's setting the `newState` to be `undefined` and it bombs in davinci/ve/_Widget _sortStyleValues:

``` javascript

            for(var i=0;i<cleaned.length;i++){
                if(cleaned[i].hasOwnProperty(value)) return i;
            }
```

where cleaned[0] is undefined.  There appear to be no negative side-effects.
