### ISSUE TITLE
New File dialog disappears abruptly when showing "File already exists" alert

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1396]
Steps to reproduce:
1. Create a new file "file1.html".  Save and close.
2. Create a new file, again with name "file1.html".  Click **Create** button.
3. This will display **"File already exists"** alert.  Click **OK**.

Both alert and New File dialog disappear.

Expected results:

Only alert should disappear, leaving New File dialog so user can choose new name.

@peller @childsb

**Comment by jhpedemonte** [comment]
Perhaps related to #1393.

**Comment by peller** [comment]
sorta.  The OK button generates an onSubmit event and tears down the dialog.  Perhaps you could put the check in as an onSubmit handler, returning false and preventing the teardown, or disable the OK button if the file already exists?  I've got a big problem with this dialog logic leading the user to this state to begin with.  An error shouldn't be the default -- see #1290

dup of #1251?

**Comment by jhpedemonte** [comment]
Good point.  So we do a check while user is typing.  If name is already taken, we bring up an error tooltip and disable the **Create** button.

**Comment by JonFerraiolo** [comment]
Changed to Priority-High. We should hold up release until this is fixed.

**Comment by jhpedemonte** [comment]
I'm seeing this again.  Testing with Firefox.

**Comment by peller** [comment]
looks like a regression from 8c235b9ed3514b1bec7a1404121af8887420fe07
