### ISSUE TITLE
setting properties for a state not working

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1397]
1) add a calendar and 2 button widgets
2) add a states, bb
3) for select state bb, go to properties palette and set the width on calendar to 50000px 
4) click 1 of the buttons and under its event tab, have it change state to  NORMAL
5) click the other button and under its event tab, have it change state to BB

you can also notice if you switch to the normal state, the "width" doesn't change on the canvas.  If you "preview in browser" and try click the buttons the width stays at 200px

**Comment by peller** [comment]
@JonFerraiolo: did states ever support property changes?  This doesn't seem to work in M3 either.

**Comment by JonFerraiolo** [comment]
Changed to Priority-Med with this rationale: at this point, changing properties on a per-state basis other than display is mostly a hidden feature that most users won't find (you have to open the cascade for a widget, scroll down to the bottom, and click a checkbox that says "only apply to current state"), and the feature wasn't all that solid in M3 anyway. Nevertheless, I've seen some things that have indeed regressed so leaving it open for M4 for the time being.

**Comment by JonFerraiolo** [comment]
This is now fixed, probably by other cleanups I've done in the past couple of days. But I want to point out that per-state property changes are only applied when you click the "only apply to current state" checkbox at the bottom of the cascade listing.
