### ISSUE TITLE
source editor: left text clipped when opening

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1399]
1) open sample1.html
2) switch to source editor
3) notice that the first few letters of all the text are clipped.  You can scroll around and this goes away.

**Comment by jhpedemonte** [comment]
At least for me, this goes away when clicking inside of source editor.  Pushing to M5.  Assigning to @waynevicknair for now -- not sure if he or @peller are the better choice in this case.

**Comment by peller** [comment]
dup of #1242
