### ISSUE TITLE
OSGi console complains 'Library file not found!' for yui and jQuery

### ISSUE THREAD

**Issue by proshno** [maqetta/maqetta#14]
While running maqetta on my desktop, the OSGi console shows the following warning:
    Library file not found! :WebContent/yui
    Library file not found! :WebContent/jquery-ui-1

I could get rid of this warning by making the following changes:
    1. /davinci.yui_2_6_0/plugin.xml
        Replace all '2.8.2r1' phrases with '2.6.0'
    2. /davinci.jqueryui_1_8/plugin.xml
        Replace all '1.8.11' phrases with '1.8'

**Comment by jhpedemonte** [comment]
Those libraries aren't checked in to the GitHub source.

==> Need to add lines to Developer Setup on downloading and adding the jQuery and YUI library code into their respective bundles

**Comment by jhpedemonte** [comment]
Updated https://github.com/maqetta/maqetta/wiki/Developer-Setup with info on jQuery UI and YUI sources.
