### ISSUE TITLE
errors when DND widget in design/source split view

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1401]
1) new HTML file
2) switch to split view
3) DND a Button

You get a "dialog.hide is undefined", followed by "this action was interupted by an error", last theres a "this._focus is undefined" error.

**Comment by peller** [comment]
this may be unrelated to the dialog.hide error @childsb saw, but I also see it failing in this loop, where `this._focuses` is undefined

``` javascript

    // Returns true if inline edit is showing
    inlineEditActive: function(){
        return this.getSelection().some(function(item, i){
            return this._focuses[i].inlineEditActive();
        }, this);
    },
```

@JonFerraiolo - weren't there some changes here recently regarding focus?
