### ISSUE TITLE
DND DataGrid results in errors

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1402]
1) new html file
2) DND a Dojo Data Grid

Observe error:
"this.headerContainerNode.firstChild is null" inside DataGrid.js

**Comment by jhpedemonte** [comment]
Don't see this on Chrome.

Does Data Grid still appear in page and function properly, even with error?

**Comment by jhpedemonte** [comment]
Hmm, no, doesn't seem to work afterwards.  Not even on Chrome.

**Comment by peller** [comment]
I took a quick look at this.  It seems that the grid has a problem with the helper doing an updateStore before the grid has rendered... something called flexCells is truthy in _View, which triggers the error above.  Strangely, I don't see any significant changes in this area, so I don't know why it would have regressed.  Would be great if @billreed63 had a chance to look at this, so I'll leave it in his queue for a bit.

**Comment by billreed63** [comment]
Fixed by above commits
