### ISSUE TITLE
Cut down on `findResource` and `listFiles` requests to server

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1404]
Goal: Reduce number of server requests in order to improve performance.

We need to cut down on the number of unnecessary calls to `findResource` and `listFiles`.

Ideally, we should treat the workspace as a **write-through** cache.  At startup, we load a directory listing of the whole workspace (one request), which removes the need for all the subsequent `listFiles` requests (which seem to go directory-by-directory for some reason).

Cutting down on `findResource` may be difficult, since I believe it already works as a write-through cache:  first call loads from server, subsequent calls (unless file is changed) are loaded from the "cache".  (But I may be wrong here.)

@childsb @peller

**Comment by peller** [comment]
We could trust the client and use it as a write-through cache, but I think we could probably continue to do what we're doing now and rely on the server, just more efficiently.

**Comment by jhpedemonte** [comment]
Well, the multiple `listFiles` calls have to go.  Getting the full workspace directory at the beginning doesn't seem to me to be much overhead.

**Comment by jhpedemonte** [comment]
Assigning to @peller for now, since you've been doing performance work.  But might require input from @childsb.

**Comment by peller** [comment]
Not within scope for M5.  Pushing to M6 to see the impact of async calls with @childsb's Orion work

**Comment by peller** [comment]
-> M7 where we will create async resource APIs

**Comment by peller** [comment]
continue to look at consolidating files and converting Resource calls to async in future releases -> M8

**Comment by JonFerraiolo** [comment]
-> M8 Prio-Med

**Comment by peller** [comment]
rather than accelerate our in memory resource cache by batching listFiles calls, we should consider a lighter approach  see #3517 then implement an async version of findResource() #3518
