### ISSUE TITLE
OK/Cancel button order

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1405]
@JonFerraiolo, @childsb 

New File has "Create" (the OK button) on the right, and Cancel on the left; new project and folder have it reversed.  Also, the use of a verb like "Create" vs. "OK" might not be consistent.

**Comment by JonFerraiolo** [comment]
The New File dialog has the exact pixel-perfect layout that we got from the UI folks so that should be the reference that other dialogs should follow.

**Comment by jhpedemonte** [comment]
I like how it's done in the New File dialog:  the **action button** ("Create") is on the right.

And we should cut down on the use of "OK" as much as possible -- the button should be named with the action that will be performed (as in "Create").

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg M7 Prio Med

**Comment by doronrosenberg** [comment]
Do we want to try to use the platform the user is one to determine the button order - mac users get the mac ordering, windows/linux the default one?

**Comment by JonFerraiolo** [comment]
nah, it's a browser app, we can ignore platform-specific conventions, and just make sure we are consistent within ourselves

**Comment by peller** [comment]
fixed by @doronrosenberg's dialog work
