### ISSUE TITLE
Prevent console.error messages for missing nls files in review code

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1407]
When I run a build, I see dozens of red-colored console messages about nls (localization) files not loading properly. According to @peller, we added code to the core to prevent this, and @waynevicknair might have added code to the upcoming merged R/C branch code, but for M4, it would be great to prevent these messages from appearing in the console.

**Comment by peller** [comment]
Files actually were loading properly.  The 404's were just an artifact of unbuilt nls bundles in Dojo's old loader.  @waynevicknair will need to make sure this gets merged with his branch next time he does a pull.
