### ISSUE TITLE
Come dialogs don't close after clicking OK

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1410]
Missed a couple  - Open theme editor dialog doesn't go away after clicking OK.
- New theme (clone claro to claro1)
- Close theme editor
- Open theme... choose claro1.

Result=> Theme editor comes up, but shaded because dialog doesn't go away until clicking on the close "x"

**Comment by JonFerraiolo** [comment]
Also the new Background dialog (by clicking on "..." button in Background section of Properties palette) doesn't come down after clicking OK.

**Comment by peller** [comment]
yeah, it's throwing an exception for some reason.  Each Dialog seems to have a personality all its own.
