### ISSUE TITLE
Sample.1.html loads gray, not blue

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1411]
@peller 

I may have broke something recently. If I load Sample1.html, all of the widgets are gray instead of blue.

**Comment by peller** [comment]
May be related to my checkin for #1177 -- disabled="disabled" is set on those three form widgets once it's loaded, for some reason

**Comment by peller** [comment]
disabled="false" may be invalid markup (see http://www.whatwg.org/specs/web-apps/current-work/multipage/common-microsyntaxes.html#boolean-attribute)  but apparently it worked in all the browsers, so I'll make sure it continues to do so
