### ISSUE TITLE
States exception in combination with sorting shorthands

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1412]
@peller , @childsb 
- New HTML File
- Add CheckBox, DropDownButton, DropDownSelect
- Add a DIV
- Inside the DIV, add 3 Buttons
- Define new states "a" and "b"
- Go to "a" state. Make DropDownButton invisible by clicking on its eyeball
- Go to "b" state. Make DropDownSelect invisible by clicking on its eyeball
- Go to "a" state. Everything works normally.
- Go to "Normal" state. 

Result=> Eyeball icon is still on DropDownSelect. Looking at console, there is a TypeError exception States.js:428 (davinci/maqetta/States.js) called from _sortStyleValues in _Widget.js. I think the problem is a bit upstream from _sortStyleValues.

Having tested yet against M3. Wouldn't be surprised if bug was there too.

**Comment by peller** [comment]
see #1395
