### ISSUE TITLE
Selecting hidden widget in outline erases selection in splitview source

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1416]
steps to recreate:
1) create a new HTML file
2) drag and drop a dojox mobile View and Heading onto the page
3) drag and drop another dojox mobile View onto the page
4) switch from design mode to splithorizontal mode in the page editor by clicking the spit horizontal icon in the toolbar
4) in Outline pane select the first View which was made invisible on the canvas when the second View was dropped

expected result: the first View becomes visible and selected on canvas and source HTML is selected in source view

actual result: the first View becomes visible and selected on canvas and the source HTML is briefly selected followed by cursor position being set to first character of the file. see issue #1078 for more info on what's happening here.

**Comment by JonFerraiolo** [comment]
@peller 
On Mac/Chrome, when I try the above scenario, I can't get View widgets to show selection in source pane. If I click on Heading, the source pane shows the Heading as selected, but if I click below the heading to select the View, no highlights in source pane. @waynevicknair can you try that out and report what you are seeing?

How serious is this issue? I classified as Priority-Low for M5, but maybe I'm missing something.

**Comment by jhpedemonte** [comment]
@waynevicknair, please answer Jon's question in previous comment.  If this is still an issue, then move to M6.

**Comment by waynevicknair** [comment]
seeing odd behavior in Outline panel. it takes two clicks to get selection correct in either visual editor or source editor. pushing to M6. too risky for now.

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo M7 Prio-Low

**Comment by JonFerraiolo** [comment]
Closing. Seems to have been fixed by the various changes we have made over past few months (e.g., my fixes to ViewHelper's selection logic and @peller's source editor changes).
