### ISSUE TITLE
Rewrite HTML source formatting logic

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1417]
@jhpedemonte 

We don't have adequate source formatting logic in HTMLModel.js. We indent children, which is fine, and we attempt to not indent certain elements where it would be wasteful to indent (e.g., `<b>` and `<i>`), but we arbitrary don't force newlines and indent on <span> although usually we should because usually SPANs are used the wrapper element for widgets, and if we don't wrap SPANs than how come we continue to wrap LIs?

What we need are proposals for dealing with source formatting, followed by careful review, and then implementation, so that we can implement optimal HTML source formatting once and for all, and (hopefully) then not have to look at it again. 

I expect we will need some heuristics for how to distinguish between different situations. For SPAN and LI items that just contain text content, then we should probably put both start tag and end tag on the same line:

```
<li>Item 1</li>
```

But if there are dvWidgets inside, then those child widgets should be on their own lines:

```
<li dojoType='dijit.form.something'>
  <span dojoType='dijit.form.something'></span>
  <img ...></img>
</li>
```

Overall, what I'm going for is for Maqetta to create as beautiful source code as we possibly can. Bear in mind that the Orion source editor will be able to help with source beautification, particularly the line folding feature. (In case of Maqetta, would also be nice if there were something in Orion for attribute folding or squishing because some widgets can have numerous attributes with long-winded attribute names and/or attribute values.)

**Comment by jhpedemonte** [comment]
I'm a bit worried about this.  I think this will be a very hard issue to fix correctly for all cases and might be too much trouble.

I wonder if a better approach would be to take the code, pass it through a beautifier, and then reread it into the model.  Main downside to this is performance.

A shortcut would be to beatify the code off in a separate area, then compare the model to the beautified code and only change the model where necessary.  Also, beatification process wouldn't be called in all instances (for example, when simply updating the `id` of an element.

We could make use of **WebWorkers** for the beautification process.

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo M7 Prio-High

**Comment by JonFerraiolo** [comment]
@doronrosenberg - Any interest in studying this one and seeing if you can find a good path forward, whether it is just tweaking our current code or integrating somehow with a beautifier.

**Comment by jhpedemonte** [comment]
@childsb 

Does Orion provide any functionality for formatting/beautifying code?  If so, we should build on top of that.

**Comment by childsb** [comment]
not that i'm aware of.  there may be a plugin that does.

formating with a model isn't too hard.  phil did it once for javascript i believe.

**Comment by JonFerraiolo** [comment]
-> M7 Prio-Med really need this fix but not going to stop us from shipping

**Comment by JonFerraiolo** [comment]
-> M8

**Comment by JonFerraiolo** [comment]
Closing as dupe of #376
