### ISSUE TITLE
Undo not working when adding style rule to app.css

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1419]
@billreed63, @childsb 
- New HTML File
- Add a Button
- Set class to zzz on the Button
- Go to cascade for 'color' property, select radio button to target a new rule for class zzz, then change the color property to red or whatever
- Click the Undo button
- Save and close the editor
- Open app.css

Result=> Button doesn't revert back to black text and app.css still includes a new style rule that sets color for class zzz. Apparently, we aren't undo'ing changes to app.css (ModifyStyleRule?).

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo

**Comment by JonFerraiolo** [comment]
I fixed this about a month ago. The undo code was present, but there was a small bit of logic that was wrong that I fixed. (I don't remember the details).

Anyway, can't reproduce with latest code, so closing.
