### ISSUE TITLE
Upload dialog doesn't show current folder

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1422]
@childsb 

The Upload command in the context menu of Files palette doesn't show the current folder. The parent folder field is always blank.
- Add a folder to your workspace (e.g., folder1)
- In Files palette, click to select the new folder
- With mouse over the new folder name, bring up context menu and issue an Upload... command

Result=> Notice that there is no text to the right of the label "Parent folder:". Also note that if you do in fact upload a file, it does go into folder1 successfully.

We had the same problem with Preview 3.

**Comment by jhpedemonte** [comment]
-> M6

**Comment by peller** [comment]
works for me
