### ISSUE TITLE
Read-only dialog has lost its width

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1425]
@peller , @childsb
The are-you-sure dialog used to be about 300px wide, and now it stretches horizontally into infinity.

Also, the OK button no longer works. You can only close the dialog by clicking on the Close button.

**Comment by peller** [comment]
I'm sure it's something I did.  Which dialog is this?

**Comment by peller** [comment]
Fixed in 4ac529f5aa7318458874770f9fd08f86e4b61fa5
