### ISSUE TITLE
500 internal error saving read-only file

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1426]
Open themes/claro/claro.css, a read-only file

make some changes (note that the parser is unbearably slow... this is a very large file and it parses the whole thing)

Hit save

A server error occurs:

`2011-12-29 15:42:00.245:WARN::/maqetta/.%2Fproject1%2Fthemes%2Fclaro%2Fclaro.css: java.io.IOException: No such file or directory`

on the client browser console, you see

`PUT http://localhost:8081/maqetta/.%2Fproject1%2Fthemes%2Fclaro%2Fclaro.css 500 (No such file or directory)`

There are several problems here:

1) the escaped values in the url probably shouldn't be escaped, nor should there be a "." in the path -- I think there are separate bugs for these already
2) the IOException is not handled on the server -- bug or proper behavior?
3) the xhr error is not handled on the client
4) there's no UI to let the user know that they can't save the read only file -- perhaps the save button should be disabled?

**Comment by jhpedemonte** [comment]
@childsb, is this fixed now, by your commit?

**Comment by childsb** [comment]
The bug is fixed, but there are some "future feature" requests by Adam so I left it open.

**Comment by peller** [comment]
we should probably break out into separate bugs as needed.  my bad

**Comment by peller** [comment]
part (1) with the escapes appears to have been fixed by dd5b7fc9, dup of #1388
