### ISSUE TITLE
mobile silhouette choice should persist with subsequent open

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#143]
If a user saves a file showing the iPhone silhouette, and then reopens the
file, he should see the page inside the iPhone silhouette just like it was when
he saved.

**Comment by peller** [comment]
@billreed63 refers to the code to save the flowlayout mode as a data-davinci- attribute on the body tag here:
davinci.core/WebContent/davinci/action/SelectThemeAction.js

**Comment by peller** [comment]
It seems a little odd to stash design-specific attributes on the document itself, but I suppose we should follow the same pattern.

@JonFerraiolo writes:
"We should revisit that. Maybe for things that matter at preview time (e.g., the whitespace collapse stuff) we need to have an attribute in the HTML file, but for authoring state things such as last theme used or abs/flow layout, we should put things into settings."

It seems like we need something in between... persistent info for individual files (metadata) stored outside the file.

**Comment by billreed63** [comment]
This was fixed with issue #460

July 2011
