### ISSUE TITLE
We're leaking Dialogs

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1436]
Use a function like Open File... multiple times and take a look at the `<body>` element.  Notice that each dialog appends a new Dialog instance.  showModal is constructing a `dijit.Dialog` and calling `show()`, but it never gets destroyed.  Dialogs need to be destroyed when closed (hidden)  or reused.

**Comment by jhpedemonte** [comment]
@JonFerraiolo 

I wonder what the best approach is here?  I think we'd want to reuse the New File dialog, since that one may be called multiple times in a session.  Others we'd probably want to destroy on hide.

**Comment by peller** [comment]
I don't think the resources are that expensive to create.  It's probably not worth the effort/code to reuse them.  I think we should avoid all code to abstract dialogs and just use plain dijit.Dialogs throughout.

**Comment by childsb** [comment]
@peller can you review 8c235b9?  Is that enough to fix the leak?

**Comment by peller** [comment]
Yes, inspecting the DOM shows that dialogs like New File disappear when closed and that there is only one Dialog appended to BODY at a time.
