### ISSUE TITLE
Move *.html files up into themes/ folder

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#144]
theme editor in the context of Eclipse projects where Dojo is included.
When we talked about how Eclipse might launch the theme editor, the Eclipse 
team said there wasn't a good UI way to add an "Open Claro Theme Editor" like
we have in maqetta now and instead what they need is a reasonable way to find
*.theme files and then double-click on them.

But the way maqetta is set up now, the theme files are hard to find. For
example, ./themes/mytheme/mytheme.theme (in the middle of dozens of files in
the mytheme folder).

The easy fix is to move the *.theme files into the themes/ folder. Maybe move
both the *.theme and *.json files should move to the themes/ folder. Wouldn't
that make the mytheme/, sketch/ and lotusoneui/ folders into pure,
unadulterated theme content.

**Comment by JonFerraiolo** [comment]
See #393, which maybe Bill would feel should be closed as a duplicate of this bug.

Also, one more comment. It would be great if the *.theme and *.json files could be located in a totally different area of the file system versus the theme itself. We did something like this for the widget metadata. @jhpedemonte is the expert on that.

**Comment by peller** [comment]
note also that claro references some files outside of its own theme folders, such as ../../icons/commonIcons.css, which are presently 404 in our source tree

**Comment by JonFerraiolo** [comment]
@jmockler

**Comment by JonFerraiolo** [comment]
Moving to M4. Too late in M3 to even think about this change.

**Comment by JonFerraiolo** [comment]
Moved to M5

**Comment by jhpedemonte** [comment]
-> M6

Is this still something we want to do?

**Comment by JonFerraiolo** [comment]
yes, still something we need to do. It is both a cleaner way of implementing themes, but also helps when integrating Maqetta as a component to other tools.

**Comment by billreed63** [comment]
With the delta theme #23 the html file is not copied. it is left in the original theme folder. The .theme file is copied and update to reflect the correct location of the original .html

**Comment by billreed63** [comment]
With the delta theme #23 the html file is not copied. it is left in the original theme folder. The .theme file is copied and update to reflect the correct location of the original .html
