### ISSUE TITLE
Create folder, add files, delete folder, create folder => error

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1440]
- In Files palette, use context menu command "New Folder" to create a new folder
- Click-select the new folder and use context menu to issue "Add files" command and add at least one file to that folder (beware of bug #1422)
- Click-select the new folder and issue a "Delete" command. The folder and the uploaded files should disappear from Files palette.
- (Once again) In Files palette, use context menu command "New Folder" to create a new folder using the same name as you used earlier

Result=> The child contents reappear in the Files palette even though the child files have been deleted. If you double-click on one of the child files, you cause Maqetta to crash and burn (page editor gets replaced by server error message). If you refresh Maqetta, the folder shows no children.

**Comment by jhpedemonte** [comment]
-> M6/Med

May point to larger underlying bug.

**Comment by childsb** [comment]
This is working
