### ISSUE TITLE
Click away from Dialog widgets doesn't unselect/hide Dialog

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1444]
- New HTML File (flow layout)
- Add a Button, then a Dialog, then add a Button inside the Dialog
- Click on the first button

Result=> Nothing happens. Everything under the dialog is inactive because the Dialog covers everything else on the page. I'm not sure what to do about this, but logging it as a bug for time being because the test plan says this (note first bullet under "Expected results"):

```
Dialog placement

Steps
  Continuing from the previous example, drag a Dialog on the canvas.
  Drag a Button widget onto the Dialog. Set the label to "Close".
Expected results
  Click on another element and the Dialog should go away.
  Click on the Dialog in the Outline view and it should be made visible again.
  Examine the States view. In addition to the "Normal" and Tooltip states, you should see a state representing the Dialog visible state with a unique ID, e.g. _show:dijit_Dialog_0.
```

**Comment by peller** [comment]
fixed by 1b8fd55d8bcaffe7ed89ea6f5b5ef354669456d0
