### ISSUE TITLE
Open Theme... with no read/write themes pops up an empty dialog

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1447]
@billreed63

Hit open theme on a new workspace without any cloned themes
You get an alert telling you that the themes are read-only
then you get an empty open theme dialog

Is the dialog supposed to appear (so you can use the theme editor in read-only mode)?

**Comment by JonFerraiolo** [comment]
I think it's OK to ship the application as is, even if the Open Theme... dialog is highly clumsy when the application first launches. So, I'm moving this to M5 Priority-Med. There are a number of related UI issues around management of themes that we need to work through in upcoming releases. For example, the switch theme dialog is quite intimidating right now and also see #1442 and #1374.

Long-term, I'd like the ability to open read-only themes in the theme editor such that the user can view but not change the theme, and allow something like a "SaveAs" to create a new theme. Maybe in shorter-term we can improve what the user sees if there are no read-write themes yet.

**Comment by peller** [comment]
dup of #1488?

**Comment by childsb** [comment]
Bug portion of issue resolved.  User prompted but no "open" dialog is shown

I'm re-adjusting the tags and re-assigning to Javier for UI work and prioritization.

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
@jhpedemonte I think we can close this. I think the UI is fine: an alert that says you have no custom themes to edit.

**Comment by jhpedemonte** [comment]
Closing.

**Comment by peller** [comment]
The original bug is gone.  It used to pop up an empty dialog after the alert.
