### ISSUE TITLE
Widget palette icons for Drawing Tools and Clipart

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1448]
Oops, forgot about adding icons for Drawing Tools and Clipart. Coming soon...

**Comment by JonFerraiolo** [comment]
@jhpedemonte 

Committed widget icons with 6e3c6295f1 . @jhpedemonte has volunteered to run script that creates the base64 version of the icons (base64 for network performance reasons).

Still waiting on 2 icons for the widget folders (Clip Art and Drawing Tools).

**Comment by jhpedemonte** [comment]
For reference:

```
cd maqetta.clipart/WebContent/metadata
node ../../../utils/icon2Base64.js widgets.json
```
