### ISSUE TITLE
Dynamically resizing via side knobs should only change width or height not both

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#145]
@JonFerraiolo reports:
"Right now, if you have an object that is resizable in both dimensions (height
and width) and you pull on any of the knobs to resize, daVinci will change both
width and height to pixel values. This has the unfortunate side-effect of
removing any 100% settings on width or height that the user might have already
set (or that was set initially upon dropping the widget).

What we need to do is have some extra logic to be a little bit smart about
which knob the user selected. If they select a corner knob, ok, we resize two
dimensions. But if they select the knob that is on the middle of the top,
right, bottom or left sides, then we should only update either width or height
but not both."

Could this be two different issues?  1) Replacing % with actual pixels 2) the overall widget size not changing as specified?  Additional logic should not be required to satisfy #2.  It's likely some inconsistency in box model or widget behavior that is causing the problem.

**Comment by JonFerraiolo** [comment]
Moved this up to M3, but with Priority-Low.

@billreed63 - If Adam doesn't have time for this, maybe you could take a look?

**Comment by JonFerraiolo** [comment]
Bug is still there in M4. Really would like to fix this one.

**Comment by jhpedemonte** [comment]
@peller, push to M6?
