### ISSUE TITLE
Hover state not present in States pane

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1452]
i created a new theme and set a font color for hover state on button text. when i create a new HTML file, switch themes to myclaro and drop a button the normal text style shows up. but when i switch to the States pane "Hover" state is not there. if i add "Hover" state manually and select it, my hover color settings do not appear in the properties palette.

Steps:
1) clone claro theme into myclaro
2) select the Button widget
3) select Hover in the States pane
4) make sure the Button is still selected and change font color to green in the properties palette
5) save and close theme editor
6) create new HTML file and drop a Button widget onto canvas

Result: Button does not exhibit hover behavior and States pane does not contain Hover state.

**Comment by JonFerraiolo** [comment]
This is a UI problem, not a logic problem, assigning to me. You see, there are 2 types of "states" that both use the States palette: widget interactivity states (Normal, Selected, Hover, ..., which you see in the Theme Editor) and application states (Normal, Add Task, Task Added, etc.). Today, these are two (nearly) totally separate things that share the same terminology ("states") and the same palette (States palette).

One of the reasons why these two features use the same terminology is to be forward-looking for creating custom widgets, where a designer might want to use the page editor's States palette to define "application states" named Normal, Hover, Selected, etc, that ultimately will map to "widget states" once a "Save as Widget" operation happens. Adobe Catalyst has a similar notion of unification between application states and widget states.

**Comment by JonFerraiolo** [comment]
Pushing to M6.

**Comment by JonFerraiolo** [comment]
Closing. Not really a bug, and I don't see us doing any fixes in this area any time in foreseeable future.
