### ISSUE TITLE
Exception when file save as on FF

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1453]
on FF, built version for testing

Standard setup things: Clear the browser cache. Launch the Maqetta server. Login if necessary. In some cases, you'll want to a virgin user environment by creating a whole new user login.
On main menubar, choose "New HTML File" to create a new file
Drag a few widgets onto the canvas (e.g., Button, TextBox, Calendar).
Click on the "SaveAs" icon on the main toolbar to save the new file. In the dialog that appears, choose a new file name.

this.fileDialogParentFolder is null

Line 32437

**Comment by billreed63** [comment]
Just noticed on new file also

**Comment by jhpedemonte** [comment]
I'm currently working on this.  Dup of #1086.
