### ISSUE TITLE
File disappears after save as

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1455]
1. Create new folder, folder1
2. In that folder, create file1.html.  Editor opens in a tab.  Hit the "+" in the file view and observe that file1.html is there.
3. In the same folder, create file1.css.  Editor opens in another tab.  See file1.css also appear in the file tab.
4. Hit save as... save as in the file1.css editor, enter the fielname "file2.css".  Notice that **file1.html** disappears from folder1.

If I try to create file1.html in folder1 again, I'm told it's already there and an exception occurs in Resource.newHTML, line 72

```
    resource.isNew = true;
```

**Comment by jhpedemonte** [comment]
Did you do **save as** on "file1.css"?  If so, "file1.html" did not disappear for me.

**Comment by peller** [comment]
@jhpedemonte yup, that's exactly what I did.  save as on the css file, and the other one disappeared.  Did it several times, on Chrome.

**Comment by childsb** [comment]
this is working for me on local.  i'll try again monday on lab9.

**Comment by peller** [comment]
this all happened for me on local.  I can't make it happen anymore either.
