### ISSUE TITLE
Copy/paste of multiple absolute-positioned widgets places them in on top of each other

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1456]
In **absolute layout**, align 2 or 3 widgets vertically.  Copy and paste beside existing widgets.  The new widgets are placed in same location, one on top of the other.

**Comment by JonFerraiolo** [comment]
Let's fix this in M5. I really want sketching to work well as early as possible. It's pretty good now and I'd like to make it as bulletproof as possible as early as possible.

**Comment by JonFerraiolo** [comment]
The above commit fixes the 90% case where all of the selected widgets have the same parent. Leaving open (but pushing to M6) because we need a more robust implementation to deal with selected widgets having different parents. (Need to add offsetParent logic in there.)

**Comment by JonFerraiolo** [comment]
Can easily be pushed to M7. The case that's broken is more on the rare side and the results aren't catastrophic to the user.

**Comment by JonFerraiolo** [comment]
Fixed with 39cc937332
