### ISSUE TITLE
In Choose Parent overlay, current parent displayed twice

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1459]
**VE part 3->Choose Parent->8**: when moving calendar, `Content Pane (Tab 1)` shown twice (numbers 1 & 4) and both are selected.

**Comment by JonFerraiolo** [comment]
Yeah, I noticed this, too. Should be fairly easy to fix.

**Comment by jhpedemonte** [comment]
Had been assigned to me.  @JonFerraiolo, is this already fixed?

**Comment by JonFerraiolo** [comment]
I have a fix for this in 7ac6daedb2 , but for now it's only in the ChooseParentRepeatFix-1459 branch. Seemed too risky of a fix for this late in the M5 cycle. 

Pushing to M6, Priority-High
