### ISSUE TITLE
Selected widget should be automatically scrolled into view

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1462]
When a widget is selected in VE, it should automatically be scrolled into view, if not already in view.

I saw this when adding many different widgets to the page.  As I added more to the end, they were hidden from view since the page didn't automatically scroll to show them.  This issue would probably show in other situations as well (such as clicking on widget in Outline view).

**Comment by jhpedemonte** [comment]
-> M6/Med

**Comment by JonFerraiolo** [comment]
@peller - Two notes;
- I've recently added some handy routines that compute the page-relative margin box coordinates for a given node: davinci/ve/utils/GeomUtils. (I discovered that dom-geometry.js in Dojo is using getClientRect() which factors in CSS3 transforms to provide where the node truly is on screen, but for Maqetta's calculations, we need instead the CSS box model values. All of this was discovered while tracing down #2136)
- Be warned that BODY.scrollLeft and BODY.scrollTop are quirky on Firefox. Have to use window.pageXOffset and window.pageYOffset instead for Firefox. I added handy utility routines getScrollLeft() and getScrollTop() in davinci/ve/utils/GeomUtils to deal with this.

@doronrosenberg

**Comment by peller** [comment]
-> M7

**Comment by peller** [comment]
-> M8

**Comment by peller** [comment]
could we accomplish this by temporarily setting focus on the node?

**Comment by JonFerraiolo** [comment]
I'm not absolutely certain, but I don't think so. Only a few HTML elements can be focused, like INPUT and A. For other widgets, calling `element.focus()` on them would do nothing. If you are thinking that maybe we could call a Dojo function to set focus (if that exists), then that would only work on dojo widgets and not html elements.

**Comment by peller** [comment]
I wonder if you could (temporarily) create one of those nodes (INPUT, A) at the same location as the focus only for the purposes of scrolling the pane?  I tried a brief experiment, but failed.

**Comment by JonFerraiolo** [comment]
I would try the approach of getting the bounding box on the widget (using GeomUtils) and then call the browser function (whatever it is) to scroll the iframe so that those bounds are visible.
