### ISSUE TITLE
"No projects are found to import"

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1464]
Perhaps I'm doing something wrong.  Following the "Eclipse Project Testing" test plan.  When I go to import my eclipse project, I get this error message from the Eclipse import wizard after selecting workspace1.zip:

"No projects are found to import"

There is a WebContent directory as well as a folder1 subdirectory and an html file I created.

**Comment by jhpedemonte** [comment]
Well, I get an error when clicking on **OK** in the **Download** workspace dialog.  So i don't even get as far as you.

**Comment by jhpedemonte** [comment]
Hmm, I don't get the error when running from source.  Either the error I'm seeing only occurs in a build, or its been fixed since the last build was created.  I'll check again tomorrow morning.

**Comment by peller** [comment]
Brad said something about a download fix yesterday afternoon

**Comment by JonFerraiolo** [comment]
Yes: 2d17d20        fix for issue #1429

**Comment by childsb** [comment]
I missed checking in some files ((I believe they are considered 'meta' files by git and were ignored)).  should be fixed now.

**Comment by jhpedemonte** [comment]
I just ran through the Eclipse test and this worked fine. Closing this bug.
