### ISSUE TITLE
Switch to a different theme, focus box should be reset

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1467]
Theming often changes the layout, so even though the selection doesn't change, the coordinates need to be checked.
1. drop a calendar and a button on the page
2. select the button
3. set the theme to sketch

the focus box does not match the widget location

**Comment by peller** [comment]
@billreed63

**Comment by jhpedemonte** [comment]
Have a look at `VisualEditor.refresh()`.  Saves an XPath for current selection [1], refreshes the source, then uses the XPath to reselect the widget.  The good thing about this is that it goes only through the model, not through the VE DOM (well, until it finally draws the focus rectangle around the widget).

We could use something similar here.  Maybe refactor `refresh()` to take a function as a param.  That way, this function (with new name) saves the XPath, runs the command, and reselects the widget using the XPath -- where "command" could be a source refresh or a theme switch.

[1] We need to expand this to handle multiple selections.

**Comment by jhpedemonte** [comment]
-> M6

**Comment by jhpedemonte** [comment]
-> M7/Med

**Comment by peller** [comment]
-> M8

**Comment by JonFerraiolo** [comment]
Closing this. When you switch themes now, the selection goes away. That seems reasonably.

**Comment by peller** [comment]
it's not terrible, but why shouldn't the selection remain?  the structure of the page hasn't changed, just the look and feel
