### ISSUE TITLE
set theme for both desktop and mobile and odd things happen

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1469]
I set both claro and android fields on the set theme dialog, now I have the appearance of both in the visual editor, as well as the previous custom theme css (c1.css) in my source

I wonder if it makes sense to be able to set both of these fields in the UI?

Sorry for not providing more details.  I can go back and try to get more if needed.

**Comment by jhpedemonte** [comment]
Assigning to Bill for evaluation.  @JonFerraiolo
