### ISSUE TITLE
setting background image on calendar does not work

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1470]
In the properties editor with a simple document with a calendar in the VE, I tried using the SampleBanner.jpg and removing the color.  The calendar is white.

Works for widgets like button.  Not sure if this is a metadata problem or a path problem.

**Comment by JonFerraiolo** [comment]
Closing. The problem was that one of the style sheets had background-position:0px 480px. Once setting background-position to "0px 0px", then SampleBanner.jpg appears.

The real bug here is that the Properties palette isn't showing computed values. See #1033
