### ISSUE TITLE
Create master plan for keyboard shortcuts/navigation

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1475]
I like what Google Docs does: it overrides the default system keyboard shortcuts in order to work within the app (for example, on Mac, to close a window in the app, I would press Cmd-W, which is what I normally use in Mac apps).  This is beneficially, since the users already have muscle memory for those shortcuts.

@JonFerraiolo @peller

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg

**Comment by doronrosenberg** [comment]
The main technical concern here is we need to listen to events in the iframes for each design view.

**Comment by jhpedemonte** [comment]
In `Context.js::_setSource()`, we already add some stuff into each editor iframe, before even loading the actual source from the file.  We could do the same for key listeners, **routing them up to the parent**, where they would be handled.

**Comment by JonFerraiolo** [comment]
Right, we need key event listeners in each editor iframe and also in the Maqetta app's frame - user might hit Ctrl-S with the focus in either an editor iframe or in the Maqetta app's frame.

**Comment by doronrosenberg** [comment]
@JonFerraiolo @jhpedemonte Moving to m7 for now, might be able to get to it in m6

**Comment by doronrosenberg** [comment]
@jhpedemonte In #1180 it was decided to use ctrl-enter to submit smart inputs.  Do we want to use ctrl-enter for regular dialogs as well? I assume yes.
