### ISSUE TITLE
Arrowhead doesn't appear upon first dropping an Arrow widget

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1476]
- New HTML File (desktop hi-fi page)
- Drag/drop an Arrow widget (from Drawing Tools)

Result=> No arrowhead. If you resize that arrow, the arrowhead appears. Only problematic if arrow widget is the first shape added to a particular page.

**Comment by billreed63** [comment]
backward arrow heads do not display even after dragging

**Comment by JonFerraiolo** [comment]
Backward arrowheads are actually an independent bug, but reopening this issue to look into why backward arrowheads aren't working.
