### ISSUE TITLE
Can't reopen file with DataGrid if moving DataGrid earlier in HTML file

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1481]
- New HTML File
- Add 3 DIVs
- Add a DataGrid
- Drag/drop the DataGrid into the first DIV
- Save, close, reopen

Result=> Exception on reloading file because the ItemFileReadStore is after the DataGrid in the HTML file.

I expect we have had this bug all along, and that a fix would have some risk associated with it, so we might want to ship M4 with this bug and fix for M5.

**Comment by billreed63** [comment]
In the DataGridHelper create we need to get the store and move (add/remove) the store so it is in the dom under the same parent as the DataGrid but before the DataGrid.

I suggest creating a compound Command Containing AddCommand(storeWidget, DataGridParent, index 0) and a RemoveCommand(storeWidget). Then execute the command in the create method of DataGridHelper

**Comment by billreed63** [comment]
We have a similar issue when we re-parent in the outline
