### ISSUE TITLE
changing state / properties in mobile theme editor causes widget selection problems

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1482]
1) create a new ipad theme, call it ipad1
2) when the theme editor opens, select the "Page Background and Fonts" section
3) change the background color
4) in the states palette, change the state to selected
5) back in the properties palette, change the background color to blue.

notice that nothing happens and you're unable to select the global styling widget again

**Comment by billreed63** [comment]
The "Page Background and Fonts" widget does not have a "selected" state, so the gray out box is placed over the widget in the theme editor.

 I have added a comment to   #226 Disable any properties that won't have an effect (page and theme editors) for theme editor states.
