### ISSUE TITLE
problems when deleting project on built maqetta

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1485]
1) create a new eclipse project
2) delete the eclipse project
3) sometimes the workbench fails to load

**Comment by childsb** [comment]
*\* only happens on safari, chrome / FF ok.

**Comment by jhpedemonte** [comment]
I had to back out your move of `_initializeWorkbenchState()`.  See my comments in #1329.

**Comment by childsb** [comment]
Sorry, didn't think this would (or should) cause any impact.

Opened issue #1493 to move inilizeWorkbenchState call to top of run(...) method for m5.  Having it as the last call is causing duplicate XHRs on workbench load (once for the current project by library metadata, then another xhr when initilizeWorkbenchState).
