### ISSUE TITLE
Selection on TD extends over edge of canvas, causes scroll bar

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#149]
@JonFerraiolo reports:
- New HTML File
- Add a TABLE (2x2 table created)
- Set width to 100%
- Click in one of the cells in the 2nd column

Result=> Horizontal scrollbar appears on design canvas. Remove selection and
scrollbar disappears.

We are backing off the selection chrome from edge of canvas in some cases, but
doesn't seem to be working for table cell selection.

**Comment by JonFerraiolo** [comment]
Closing - back-off logic works universally now.
