### ISSUE TITLE
Undoing Font Changes Problematic in Theme Editor

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1490]
Environment: Chrome and downloaded GitHub-only build

Example steps to reproduce:
1. Create new theme based on Claro
2. Select the button widget
3. Change font attribute (e.g. change font color to red)
4. Remove value from attribute (or click Undo button) and button text does not revert (e.g., if color changed to red, it's still red)

**Comment by JonFerraiolo** [comment]
This step is part of our tutorials. We should at least investigate to see why it's not working, and hopefully fix before M4.
