### ISSUE TITLE
Review edits lead to confirmation dialog

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1495]
@JonFerraiolo 

Make comments on a R&C page, and when you try to close the tab, you're prompted with an ok/cancel dialog telling you that you made changes.  This isn't applicable here; there's no save action.

**Comment by waynevicknair** [comment]
i cannot recreate this issue on commit a0708e74bbb9edb7d98f17d2fe2910e4d3030b92. please re-open if issue recurs.
