### ISSUE TITLE
Where is onChange handler for workspace model? ResourceTreeModel unused?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1498]
@peller 

I set this bug to Priority-High for M4 just so @childsb can look at this. Things look very fishy to me as I will guess that we have a bug where there is no onChange handler for the workspace tree model (the model that holds the data used in the Files palette). 

ResourceTreeModel has an onChange handler, but ResourceTreeModel.js doesn't appear to be ever invoked in our current code. I put breakpoints in its constructor and other functions and the breakpoint is never hit. @childsb, can you look into this and make sure we  aren't missing a define() or initialization call for this routine and that in fact it should be used. If it is dead code, then let's push this issue to M5 and remove this routine then.

Another thing that looks really fishing to me is that I put a `debugger;` statement in the onChange function within system/resource.js (in the maqetta.core.server.standalone plugin). I see the `debugger` statement when looking at source code in the Chrome debugger, but adding or removing files to the Files palette doesn't get to that debugger statement. Is something overriding the onChange function in system/resource.js? Why doesn't it get called?

**Comment by childsb** [comment]
After investigating--

The tree monitors both onChange(...) and onChildrenChange(...).

The onChange(...) call is if the root node changes.  The onChildrenChange(...) call is for any of the roots children or sub children changing.

In our case, the root element never changes, so theres not a call to onChange(...).  You can set a breakpoint in onChildrenChange(...) which will fire any time a child is added or removed.
