### ISSUE TITLE
Empty workbench when reload Maqetta with file open  (w/ local install)

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1502]
1. Go to http://localhost:50000/maqetta/
2. Note reloading page works fine
3. Open HTML file (e.g., Sample1.html)
4. Reload page and note workbench is entirely empty except for the black title bar that only has "Welcome maqettaUser Log Out" on it (no menu choices)
5. Even after restarting browser and server, going to http://localhost:50000/maqetta/ fails to work properly
6. Delete workbenchState.settings file in user/.settings directory and note reloading page works again

Environment: Chrome, local install (Does NOT appear to happen on server install lab9:50020)
Version: Preview 4
Date: Jan 6, 2012 12:32:26 PM
Build: 5c5b769e17f129b...

**Comment by peller** [comment]
Any exceptions on the client or server?

**Comment by aerwin** [comment]
Good question... it looks like there's one on the client:

Uncaught TypeError: Cannot call method 'addChild' of undefined
require.cache.davinci/Workbench.dojo.mixin._createEditordavinci/davinci:5019
require.cache.davinci/Workbench.dojo.mixin.openEditordavinci/davinci:4990
require.cache.davinci/Workbench.dojo.mixin._initializeWorkbenchStatedavinci/davinci:5286
require.cache.davinci/Workbench.dojo.mixin.rundavinci/davinci:4309
require.cache.davinci/Runtime.dojo.mixin.rundavinci/davinci:44846
run:50000/maqetta/:94
(anonymous function):50000/maqetta/:66
dojo.ready.dojo.addOnLoad._414dojo.js:5236
_410dojo.js:5203
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_410dojo.js:5210
_40cdojo.js:5218
_40fdojo.js:5196
_2e9dojo.js:3624

**Comment by jhpedemonte** [comment]
This looks like what I ran into and fixed with d6f49ead8e3b5789c7fc6e71831312b0f10bcb2b.  Closing as fixed.

Please retest and reopen this issue if you still see this problem.

**Comment by aerwin** [comment]
Awesome... I just got the latest build and confirmed this is fixed.
