### ISSUE TITLE
VE3 Test: possible parents UI not shown for Dojo Controls

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1506]
testing with Mac/Safari

Steps:
1) Standard setup things: Clear the browser cache. Launch the Maqetta server. Login if necessary. In some cases, you'll want to setup a virgin user environment by creating a whole new user login.
2) Go to preferences and look at "When dragging, show possible parents" setting.
It should be off by default.
Turn this preference on and click OK and close the Preferences dialog.
3) Click on the "New file" icon on the main toolbar. Set composition type to "Desktop hi-fi page". Choose any filename.
4) Drag BorderContainer onto the canvas, accepting default options. Drag a TabContainer into the middle pane of BorderContainer, accepting defaults. Drag 3 DIVs into the TabContainer (siblings DIVs, not DIVs within DIVs). Drag a SPAN into the first DIV. As you drag all of the above widgets, you should see some UI what shows a list of candidate parents.
5) Drag a Button from Widgets palette onto canvas 

Result: 
while dragging, notice the list of candidate parents does _not_ appear.

**Comment by waynevicknair** [comment]
i forgot to mention that the possible parents UI works correctly for Dojo Containers and HTML widgets.

**Comment by JonFerraiolo** [comment]
I just tried localhost:8081 (from Eclipse) and lab9:50010 using Mac/Safari in both cases and I'm seeing the candidate parents. I'm running Safari Version 5.1.2 (6534.52.7)

**Comment by waynevicknair** [comment]
i was running from macwayne2 with Mac/Safari Version 5.1.2 (7534.52.7). it worked for me from Eclipse. then Safari slowed way down and started getting beach ball of doom. after a restart and a clear everything, i cannot recreate this. (i also tested on Mac/Chrome after the restart.) 

closing bug. will reopen if i see that behavior again.
