### ISSUE TITLE
Props4 Test: cascade does not show up for cloned theme

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1508]
testing on Mac/Safari

Steps:
1) Clone the "claro" theme into a new theme using the "New Theme" command. For example, create theme "mytheme".
2) Issue a "New HTML File" command.
3) Drag a Button onto canvas.
4) Go to Properties palette and go to 'width' property. Click on the right-pointing icon at the right side of the 'width' property to show the CSS cascade. You see a list of CSS selectors, at least one of which should include within it ".claro .dijitButtonNode". You do not see an "element.style" entry.
5) Click on the Switch themes icon on the toolbar, and change to your new theme ("mytheme").
6) Go again to Properties palette and go to 'width' property and the CSS cascade view for that property. 

Result: all you see in the cascade list is an "element.style" entry.

**Comment by waynevicknair** [comment]
more info: if i refresh the page or save and re-open the file, the cascade for the cloned theme will appear correctly.

**Comment by JonFerraiolo** [comment]
Probably also gets fixed by unselecting, reselecting the widget. Assigned to me.

**Comment by JonFerraiolo** [comment]
@billreed63 - closing this. First off, I'm pretty sure it's a dupe. Second, we changed our logic so that changing themes removes the selection, so this bug is masked away because it only happened when we were preserving selection across theme changes.
