### ISSUE TITLE
user error from source editor can destroy visual editor

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1509]
@jhpedemonte 

Some errors cause an exception in parsing -- for example, try changing the dojoType in a dijit.Calendar to something invalid like dijit.TextBox.  This causes the 'red screen of death'.  Exactly how we present the error to the user is one thing... the bug here is that you can fix the error and the visual editor does not regenerate as it should.

**Comment by aerwin** [comment]
As for relation to 1511, I never edited the source (since I couldn't use the split pane) so Maqetta itself must have corrupted the file.

**Comment by peller** [comment]
moving back to M4.  It looks like everything proceeds correctly, we just need to tear down the red error message left from the previous parse.  It covers the working visual editor!

**Comment by peller** [comment]
I propose adding this code to Context.js._setSource at line 943, in the else clause just before the call to _continueLoading:

``` javascript

            // tear down old error message, if any
            dojo.query(".loading", this.frameNode.parentNode).orphan(); 
```

**Comment by jhpedemonte** [comment]
1. Does this result in some sort of flickering?  For example, if there is invalid source and user keeps typing, but source is still invalid.
2. "loading" seems like quite a generic identifier.  Is there a case where that could cause issues, where some other element has the same class?  After all, `dojo.query` will return all elements with that class.
3. `orphan()`: does that mean that the error overlay (?) is getting recreated each time?

**Comment by peller** [comment]
1. it does not, and I'm not sure why it doesn't flicker in that case, but I'm not sure that's much of a concern.  The error text does get updated in the event that that the error condition persists and changes slightly as the user types (for example, each invalid character added to `dojoType` is echoed in the error message
2. this div is a peer of the iframe, and therefore in the workbench, not the user content, so no worries about conflicting with user code.  The dojo.query is scoped to the so-called frameNode's parent, so it's a pretty narrow search. 
3. yes and yes.

**Comment by billreed63** [comment]
looks good

**Comment by jhpedemonte** [comment]
Well, it's not a narrow search, since your `dojo.query` search will look for all nodes that are children of frameNode's parent, right?  Not sure if it will also follow into iframe, but I don't see why it wouldn't.

Are there any perf implications with destroying/recreating the overlay?  I'm guessing probably not.

**Comment by jhpedemonte** [comment]
Sorry, picking nits!  Assuming the `dojo.query` is ok, then patch is fine.

**Comment by peller** [comment]
Quite alright.

framenode's parents are exactly this loading div (which would only exist if the previous run were an error) and the iframe, that's it.  To get to an iframe's children, don't you have to go through ownerDocument?  I don't think dojo.query will recurse down into the iframe.
