### ISSUE TITLE
Filter "internal"-only libraries from Download Workspace dialog

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1512]
Need to filter the libraries shown in the **Download Workspace** dialog.

Currently, I see this list:
- html
- maqetta
- dojo
- DojoThemes
- clipart
- shapes

We should remove **html** and **maqetta** from that list.  Not sure about **DojoThemes**, whether it needs to stay.

---

**Tasks:** _(updated 2012-08-15)_
- In the _User Libraries_ dialog, do not show:
  - dojo-src (see #2769)
  - DojoThemes
  - maqettaSamples
  - maqetta
- In the _Download_ dialog, hide the same libs as above.  However, still download the **_maqetta**_ library contents.

**Comment by jhpedemonte** [comment]
Proposal: Create a property, on library metadata, called "internal".  When set to `true`, code such as the **Download Workspace** dialog, can ignore these "internal" libraries.

**Comment by JonFerraiolo** [comment]
I think we still need to download maqetta/ because we want the downloaded app to run and the maqetta/ logic is needed at runtime.

**Comment by jhpedemonte** [comment]
Right, but we don't need to give the user the option of disabling the **maqetta** lib, since it's needed to run the generated code.

**html** lib provides nothing, therefore there is no reason to download that.

And **DojoThemes**?

**Comment by peller** [comment]
...and zazl

**Comment by jhpedemonte** [comment]
Raising to Priority High; we don't want to allow disabling these libs for v1.0.

**Comment by jhpedemonte** [comment]
See #2769 for handling of **dojo-src**.

**Comment by jhpedemonte** [comment]
Added a list of tasks to the summary.  One question:  when downloading, we must always download the files from the "maqetta" library.  Does the same apply to "DojoThemes"?  I'm not even sure why that's a library.
