### ISSUE TITLE
While changing props, theme editor not auto-refreshed with changes

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1515]
Running through the **ThemeEditor:Claro** tests, which state that the Theme Editor should auto-refresh based on changes I make in the properties view.  However, I'm not seeing that.  Instead, I have to refresh the page or close/reopen theme editor in order to see changes.
1. Cloned **claro** to **myclaro**.
2. Selected **TextBox** widget.
3. Changed **font** to Monaco, then changed **color** to green.

Result: Theme editor didn't immediately show changes.

Testing with Safari against both (1) macwayne2 (build f5b8f94efd1d7b2bc9529e3c8aa4d8764d214895) and (2) local base build (e57f533dce686620d639f23a9f6d590381a0caa5).

@JonFerraiolo

**Comment by billreed63** [comment]
Dup of #114, which I just fixed
