### ISSUE TITLE
Undo prop change if change cannot be completed due to read-only theme

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1518]
Running **Properties part 5** test, section "button using claro":

When typing "yellow" for "background-color", get **warning that I can't make change to read-only theme**.  Click OK.  However, "yellow" still remains as value in text box.

When displaying the dialog that the intended action couldn't be completed due to a read-only theme, then the intended action must be undone and the Properties view returned to its previous state.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
Working correctly for me now. The swatch is never updated with "yellow". Closing.
