### ISSUE TITLE
ComboButton shows Menu as its child 

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1521]
@aerwin , @billreed63 
- New HTML File
- Add a ComboBox and ComboButton
- Look at Outline palette

Result=> ComboBox doesn't show any children (which is correct), but ComboButton shows a Menu as a child (which is not correct)

**Comment by peller** [comment]
I'd argue that ComboButton (and DropDownButton) have the correct behavior, as there is a proper widget associated it and you should be able to inspect and modify it.  Alas, dijit.Menu has regressed (again) #1154 Yes, there's some inconsistency with the (simpler) ComboBox, where there is only one type of tag as a child and it's a simple one.

**Comment by peller** [comment]
Discussed with @JonFerraiolo and @billreed63 and we all agreed that subwidgets shown in the markup should appear in the outline view and the user should be able to manipulate them directly.  Seems to fit well with the way Maqetta works.
