### ISSUE TITLE
a new themes css rules don't show up

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1524]
1) create a new project
2) new-->theme, select claro, type claro2 as new theme name.
3) new HTML file
4) switch theme to claro2
5) add a button
6) go to the background (or any property) for button and expand the cascade
7) notice that only element.style shows up.

**Comment by jhpedemonte** [comment]
@JonFerraiolo

**Comment by jhpedemonte** [comment]
@billreed63

**Comment by JonFerraiolo** [comment]
Same as #1516? I wouldn't hold up M4 for this.

**Comment by jhpedemonte** [comment]
Could be related, but the scenario is a bit different.  Best to keep both open for now.

Pushing to M5.

**Comment by JonFerraiolo** [comment]
Ok to assign to me. I know this part of the code pretty well by now.

**Comment by jhpedemonte** [comment]
I am able to recreate this **without creating a new project**, just using the existing one.

**Comment by jhpedemonte** [comment]
A **refresh** makes this work properly again, showing all the items in the cascade (not just element.style).

---

Before refreshing, though, I wasn't able to change the dijit Button's **background color**, although I could change its text size and color.

**Comment by billreed63** [comment]
I think I introduced this bug fixing #1449, if I put that code back this issue is resolved.

**Comment by childsb** [comment]
Looks like the ChangeThemeCommand isn't forcing the import elements that it adds or changes to load & parse.  The quick fix is to reset the models text --

ChangeThemeCommand.js:

```
_changeTheme: function(newThemeInfo, oldTheme){
    if (!oldTheme.desktopTheme){ // not a themeSet
        this.removeTheme(oldTheme);
    } else {
        this.removeThemeSet(oldTheme);
    }
    if (!newThemeInfo.desktopTheme){ // not a themeSet
        this.addTheme(newThemeInfo);
    } else {
        this.addThemeSet(newThemeInfo);
    }
    if(this.resetDojoxMobileNeed){
        // this is here due to timing if deleting and then adding themeMap
        this._resetDojoxMobileTheme(this._context);
        this.resetDojoxMobileNeed = false;
    }
   var text = this._context.getModel().getText();
   this._context.getModel().setText(text);
    //var e = davinci.Workbench.getOpenEditor();
    //e.setContent(e.fileName,text); // force regen of HTML Model to load new theme
 // Recompute styling properties in case we aren't in Normal state
  //  davinci.ve.states.resetState(this._context.rootWidget);
}
```

This doesn't seem to impact issue #1449

**Comment by jhpedemonte** [comment]
This doesn't work.  While I do see some rules now in the Cascade, they aren't the same rules I get if everything is working correctly.

Also, after switching theme and dropping a dijit Button, with button selected and Properties->Background showing, I don't see any values in any of the fields.  If this were working correctly, some of those fields should be filled.

**Comment by billreed63** [comment]
The fix that Brad suggests does not work for me on Chrome/Win.. The rules that are displayed in the properties palette are not from the theme, It looks like they are the default dijit rules...

```
Apply to which style rule:

element.style

[theme] .dijitToggleButton, .dijitButton, .dijitDropDownButton, .dijitComboButton (project1/themes/myclaro/myclaro.css line: undefined)
background-color:green;


[theme] .dijitInline (project1/themes/myclaro/myclaro.css line: undefined)

[theme] .dijitReset (project1/themes/myclaro/myclaro.css line: undefined)
```

They should be:

```
Apply to which style rule:

[theme] .myclaro .dijitButton .dijitButtonNode, .myclaro .dijitDropDownButton .dijitButtonNode, .myclaro .dijitComboButton .dijitButtonNode, .myclaro .dijitToggleButton .dijitButtonNode (project1/themes/myclaro/myclaro.css line: undefined)
background-color:red;


[theme] .myclaro .dijitButtonNode (project1/themes/myclaro/myclaro.css line: undefined)

[theme] .dijitButtonNode, .dijitButtonNode * (project1/themes/myclaro/myclaro.css line: undefined)

[theme] .dijitButtonNode (project1/themes/myclaro/myclaro.css line: undefined)

[theme] .dijitInline (project1/themes/myclaro/myclaro.css line: undefined)

[theme] .dijitReset (project1/themes/myclaro/myclaro.css line: undefined)
```
