### ISSUE TITLE
Dirty file - refresh - dirty bit not restored

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1526]
(Discovered on Win/FF)
- New HTML File
- Add a Button (note; asterisk indicates that dirty bit is on for the new file)
- Refresh the browser

Result=> No asterisk . If you click on the "x" to attempt to close the editor for the new file, there is no prompt and the file (and all of your editing in that file) are lost.

**Comment by childsb** [comment]
Resolved in 088c8102e956f5be3ef5cc5f6fba9c4a18b24fbe
