### ISSUE TITLE
Problems mixing jQuery and YUI

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1527]
(Tested on both Win/FF and Win/Chrome)
- New HTML File
- Add jQuery TabContainer
- Add YUI Calendar
- Add a second jQuery TabContainer

Result=> Visual styling is messed up for the 2nd TabContainer. No problem if you skip the 3rd step. Somehow the YUI calendar is confusing jQuery

**Comment by jhpedemonte** [comment]
There might be some issues with the inline JS used by these libraries.  I wonder if fixing #1354 would also fix this.

**Comment by jhpedemonte** [comment]
-> M7

**Comment by jhpedemonte** [comment]
Closing since we no longer support these libraries.
