### ISSUE TITLE
Split view - change size with "+" icons looses selection

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1528]
@peller, @jhpedemonte, @childsb 
- New HTML Page
- Split view
- Add a ContentPane, and put a Calendar inside. 
- With mouse, pull on one of the right-side resize knobs to make the Calendar a little wider
- Repeat:  Add a ContentPane, and put a Calendar inside. With mouse, pull on one of the right-side resize knobs to make the Calendar a little wider
- Select 2nd Calendar.
- In Properties palette, click on "+" button for 'width' property twice to increase the width of the Calendar

Result=> Calendar gets unselected with first click on "+", so only the first click works. This is because the source view is triggering reparsing of the design view (I believe), losing the current selection or resetting the current selection to point to a different widget. This seems totally wrong. If the design view is initiating the change to the document, the source view updates should not retrigger an update to the design view such as changing the selection.

Actually, it's not just clicking on the "+" icon. Pretty much any change to design view will surface this problem.

**Comment by waynevicknair** [comment]
@JonFerraiolo the behavior I'm seeing today is the "+" button works for multiple clicks and the calendar remains selected in the visual editor. selection is wiped out in the source view; however, I can watch the width attribute count up in the source view as I click the "+" button to change the width of either calendar. 

technically, the source that was selected has changed invalidating the source selection. the visual editor selection does _not_ change.
