### ISSUE TITLE
Outline view w/ scrollbar -- avatar still available after drop

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1532]
This is a weird one to explain so I'll also be sending some screen shots...
1. Open Sample1.html
2. Open nodes in outline view until scrollbar appears
3. Within Outline view, move the New button into the 2nd div in the "Tasks" content pane (really doesn't matter the move operation)
4. Click the down arrow at the bottom of the scroll bar
5. The DIV that was shown during drag and drop (e.g., the one showing information about what's selected) gets incorrectly made visible and follows my mouse around

Environment:
Chrome, local install
Release Candidate
Version: Preview 4
Date: Jan 10, 2012 2:58:23 PM
Build: 3c236b1c2ec48a5...

**Comment by peller** [comment]
I want to say this is a known dijit bug, or perhaps we even reported it... trying to locate the ticket

**Comment by peller** [comment]
I was thinking of this one: http://bugs.dojotoolkit.org/ticket/13964  Perhaps related?

**Comment by jhpedemonte** [comment]
Dup of #1018.
