### ISSUE TITLE
Label styling doesn't work in PE 4, app.css test case

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1533]
In the app.css section of "Properties palette basic tests (part 4)", the font size of the 2nd label does not change.

Environment:
Chrome, local install
Release Candidate
Version: Preview 4
Date: Jan 10, 2012 2:58:23 PM
Build: 3c236b1c2ec48a5...

**Comment by JonFerraiolo** [comment]
Worked for me when I ran the same test. Are you sure you changed the ID on the second label to 'label1' (instead of changing the class attribute)?

**Comment by aerwin** [comment]
You're right... my bad... I set the class, and not the id.
