### ISSUE TITLE
Open css file and it's marked dirty despite no changes

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1534]
1. Create css file
2. Save and close it
3. Reopen css file and note \* appears and when I try to close the css file it prompts me that changes have been made

Environment:
Chrome, local install
Release Candidate
Version: Preview 4
Date: Jan 10, 2012 2:58:23 PM
Build: 3c236b1c2ec48a5...

**Comment by waynevicknair** [comment]
i cannot recreate this one on the latest code.

**Comment by aerwin** [comment]
@waynevicknair This still happens with local install on Windows. I just tried the following driver from Chrome:

Version: Preview 5
Date: Mar 8, 2012 3:21:31 PM
Build: 539c988df3b6566...

**Comment by waynevicknair** [comment]
bizarre. it works fine on Mac/Chrome.

**Comment by JonFerraiolo** [comment]
-> @peller M7 Prio-Med

**Comment by peller** [comment]
@childsb, is this one for you?

**Comment by peller** [comment]
-> @childsb

**Comment by jhpedemonte** [comment]
-> @doronrosenberg.  Also see #554.
