### ISSUE TITLE
Server error deleting folder with multiple items

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1536]
1. Create folder
2. Create 2 HTML files in new folder (I saved both and closed their tabs)
3. Attempt to delete folder and get a page showing the following:

> Problem connecting to the Maqetta Server...
> Return to Maqetta Login
> 
> Error description:
> 
> Error: Unable to load cmd/deleteResource?path=.%2Fproject1%2Ffolder1 status:400
1. When I get back into Maqetta, I see the folder still in the File palette and it contains the 2nd HTML file (e.g., looks like first HTML file was deleted)

Environment: 
Chrome, local install (windows)
Release Candidate
Version: Preview 4
Date: Jan 10, 2012 2:58:23 PM
Build: 3c236b1c2ec48a5...

**Comment by JonFerraiolo** [comment]
I tried but couldn't reproduce on macwayne2. I wonder if the session had timed out or somehow the server process had been restarted. The steps I took:
- From main manu, New Folder (folder2 in my case)
- I clicked on folder2 in Files palette, and then issues two New HTML File commands and put a Button in each file, saved, closed the two files
- In Files palette, I used context menu to delete folder2 - worked ok, no error messages, no redirect to other pages

**Comment by JonFerraiolo** [comment]
Ah, I did succeed in reproducing. 
- New HTML File, accept default name. Save, Close. 
- In Files palette, delete the new html file.
- New HTML File, accept default name (same as before). Save, Close.
- In Files palette, delete the new html file.

Result=> File doesn't go away from Files palette. It's still there.
- In Files palette, try once again to delete the file you just deleted.

Result=> You get redirected to the Maqetta error page.

**Comment by jhpedemonte** [comment]
See #1535.

**Comment by aerwin** [comment]
@JonFerraiolo as @jhpedemonte mentions I think you reproduced a version of #1535. I can still reproduce the originally reported problem (deleting folder with multiple items) on windows and local install.

**Comment by childsb** [comment]
@aerwin can you still reproduce this?  i've tried on mac/FF and mac/chrome and can't.

please reopen if you can!

**Comment by aerwin** [comment]
@childsb 

Still happens with local install on windows using Chrome.

**Comment by childsb** [comment]
The problem is on Windows--

When we create files on the server, we skip over writing if the content length = 0.

For some reason, just getting a URLConnection on windows then not writing anything would cause the JVM to lock the file in the thread.  This resulted in any file.delete() to fail (and leave the file on the file system).

I changed the code to write 0 bytes and set content length to 0 for empty files.  This resolved the file lock.

**Comment by aerwin** [comment]
Confirm this is fixed in latest.
