### ISSUE TITLE
Renaming file does not stay in synch with open tabs

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1537]
1. Create HTML file (say, tony.html)
2. Use content menu to rename new file (say, tony2.html)
3. File name changes in File Palette, but not in tab for HTML file
4. Double click on tony2.html and it opens in another tab (so, I have one tab labeled tony.html and one labeled tony2.html)

Environment:
Chrome, local install (windows)
Release candidate build
Version: Preview 4
Date: Jan 10, 2012 2:58:23 PM
Build: 3c236b1c2ec48a5...

**Comment by jhpedemonte** [comment]
Saw this as well.  What's interesting is that if you click on **Preview**, then it opens the correct (renamed) file, even though the tab contains a different name.

**Comment by jhpedemonte** [comment]
-> M6/Med
