### ISSUE TITLE
Delete file when file is open in editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1538]
- Create folder
- Create two CSS files inside that folder
- Open one of the CSS files
- In Files palette, delete the folder

Result=> folder and the two files are deleted, but the editor is still open

Not sure what's the best way to handle this situation. My best suggestion is that before doing a delete action we check to see if the action would affect any open editors, and if so, put up an error dialog telling user he needs to close the editors before the action can be effected.

**Comment by jhpedemonte** [comment]
> before doing a delete action we check to see if the action would affect any open editors, and if so, put up an error dialog

I would amend this.  If user tries to delete an open file:
1. Does file have unsaved changes?  If so, display dialog stating that user is trying to delete a file that is currently being edited.  Display buttons for **Cancel** and **Delete**.
2. If no unsaved changes, just delete.

When deleting, close open editor.

**Comment by jhpedemonte** [comment]
-> M6/Med

**Comment by childsb** [comment]
i implemented basic function (close editors).

if the user is deleting a directory, then saving a dirty file would result in the file still being deleted or the delete operation aborted.  i think it's generally accepted that if you're deleting a folder with resources, one prompt of "are you sure" is enough.  after that theres no reason to prompt on every "dirty" resource.  not to mention its probably 2x the amount of code for the check than the basic feature alone.
