### ISSUE TITLE
Duplicate command as accelerator for group copy+paste

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#154]
Suggestion from BJ Scheid:

Add a duplicate options for elements on the page. For example, I create a label and drop down button wrapped in a div. My design needs 5 of these sort of elements in the UI. Using duplicate is faster than copy and paste.

**Comment by JonFerraiolo** [comment]
-> M7 Prio-Med. Accelerated to consideration for M7 because latest UI mockups include a duplicate command on ActionBar.

**Comment by JonFerraiolo** [comment]
I actually implemented a duplicate command for M7, but I then removed it from the UI mostly because I didn't want to take up real estate on the toolbar. There is still a DuplicateAction.js in the code base. Easily resurrected.

-> future

**Comment by JonFerraiolo** [comment]
Actually, closing. If people want to restore the duplicate command, then we can reopen.
