### ISSUE TITLE
Firefox adds .2 to pageX - affects snapping

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1540]
Need to investigate this.

The dojo.coords() call in Snap.js is returning floating point values for x and y such as x:20.199999 even though there is no evidence of any fractional values anywhere in the document. According to Dojo's docs, the x and y values come from pageX and pageY. Looking at Firebug's various panels, I don't see a reason for the fractional values.

So far, this doesn't appear to be a huge problem. Instead of snapping to "20", the snap result is "20.2".

**Comment by jhpedemonte** [comment]
Is there any division involved?  Since all number values in JS are stored as **double**, sometimes even simple division can yield odd fractional results.

**Comment by JonFerraiolo** [comment]
I haven't found any divisions in our code. The fractional number is coming from dojo.coord() as the x: and y: values.

**Comment by JonFerraiolo** [comment]
Pushing to M6 Prio High

The fractional part in this particular case is because the Claro theme puts a .2em margin on Button, which turns into a fractional computed value (in px units) in Firefox.

This bug exposes a rather sinister browser layout issue due to sub-pixel rounding and truncation. WebKit tends to truncate fractional values when going from specified to computed values, whereas Firefox includes intelligence that attempts to honor the fractional pieces as best it can, while doing integer pixel layouts at the end of the day. As a result, if you have 4 SPANs with width:12.5px, WebKit ends up with 48px whereas Firefox will end up at either 50px or something close with some SPANs being 12px and others being 13px.

My first thought is that the snapping logic needs to add a Firefox-specific round-to-nearest-integer feature for calculating the margins.

Here are some URLs for discussion about the fractional px problem:
- http://ejohn.org/blog/sub-pixel-problems-in-css/
- http://www.simonbattersby.com/blog/browsers-and-fractional-pixels/
