### ISSUE TITLE
Server error deleting recently created Eclipse project

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1541]
1. Create project with **Eclipse support**.  Maqetta will be reloaded.
2. Immediately **delete** new project (click on red X beside project name in Files view).

_Results_\* in a **server error** page, but this only lasts about 10 secs before the page is reloaded with the previous project ("project1").

The description on the server error page is something like:

> TypeError: 'null' is not an object; evaluating 'responseObject.length'

Seen on macwayne2 and lab9:50020, using Safari.

@childsb @JonFerraiolo

**Comment by childsb** [comment]
This is working.
