### ISSUE TITLE
Error when trying to change dijit textbox width (Props 2 test)

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1542]
In the **Properties part 2** test, **Layout Props #7** fails -- try to change width of textbox in Properties view fails, showing error dialog that the CSS of read-only theme cannot be changed.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
@billreed63, @childsb

Yeah, time to take a deeper look at the logic in Cascade.js for choosing the default target rule (element.style vs specified CSS rule). We might need to add another option to theme metadata.

**Comment by JonFerraiolo** [comment]
@billreed63 fixed this a week or two ago.
