### ISSUE TITLE
cut/copy/paste in context menu don't work with area under mouse cursor

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1543]
The cut/copy/paste commands in the VE context menu don't actually work on the "context" (whatever is right underneath the mouse cursor).

Try this for cut/copy:
1. Place several widgets on the page.
2. Select one of them.
3. Right-click on a **different widget** than was selected, in order to show context menu.
4. Select **cut** or **copy** from context menu.
5. **Paste** somewhere else in the page.

Notice that the select widget, rather than the one which was right-clicked, gets cut or copied.

---

**Paste** is a bit different -- when selecting it from context menu, it brings up the cross hairs, allowing you to click somewhere in the page to complete the paste action.  But that is unnecessary, since the user has already selected that location when right-clicking.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
Pushing to M6

**Comment by JonFerraiolo** [comment]
-> M7 Prio High

**Comment by peller** [comment]
see #570

**Comment by peller** [comment]
the openCallback in the createPopup call in Explorer.js does this...  I think we used to have other similar workaround scattered throughout the code, but not sure what happened to them

**Comment by JonFerraiolo** [comment]
Closing - @doronrosenberg fixed this a couple of days ago
