### ISSUE TITLE
Dojo Containers test case -- can't drop new container at end after scrolling

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1559]
Noticed this while doing "Dojo Containers" portion of "Widget palette basic tests"...
1. Create new HTML file
2. Drag and drop AccordionContainer, BorderContainer, and ContentPane
3. Scroll down to bottom of canvas
4. Try to drag and drop and additional container next to the Content Pane and nothing is added

![Screenshot of problem](http://i.imgur.com/ZaxSl.jpg)

Environment:
Chrome, local install (windows)
Release Candidate 2
Version: Preview 4
Date: Jan 11, 2012 3:32:25 PM
Build: 7965a7a4d400ac3...

**Comment by jhpedemonte** [comment]
Related to #1559?

**Comment by peller** [comment]
> Related to #1559?

RangeError: Maximum call stack size exceeded.

**Comment by jhpedemonte** [comment]
Let's try this again:  related to #675?

**Comment by aerwin** [comment]
I just went to macwayne using Chrome and outline indicates new container (a TabContainer) was added after the content pane. But, scrolling in the canvas is really messed up, and I can't find the new TabContainer. The canvas just keeps getting bigger and bigger as a scroll down.

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
-> @aerwin - does this issue still exist? If so, please reassign back to me. If not, please close. (Note: there have been some significant changes with drag/drop logic in past few months)

**Comment by aerwin** [comment]
Tried it out and looks like it's working pretty well now. So, closing.
