### ISSUE TITLE
Review invitations from cn server

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1568]
@childsb, @peller , @EldonReturn

When hooking up to intranet server, mail is going through a server with "cn" in its name, even though all users are in US. We should investigate to see why this is the case.

**Comment by waynevicknair** [comment]
fixed in commit eeae505892548ad043b0af02b33f294445a5d76 to private repository

configuration settings were incorrect in plugin.xml

**Comment by peller** [comment]
Should probably leave ticket open until the change is pushed with a reference
