### ISSUE TITLE
Choose parent test: moving widget doesn't go into intended place

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1572]
In the **Choose Parent** test, I placed a button inside of a SPAN inside of DIV inside of a ContentPane...

Grabbed button and started to move it around.  Hovered back over same button (inside of span), selected **option 3** ("ContentPane Tab 1"), and released mouse button.  Instead of placing button inside ContentPane, after the 3 DIVs, it placed it in the DIV which is a parent of the SPAN.

**Comment by JonFerraiolo** [comment]
The Button was in flow layout, right? Yes, there are bugs with Choose Parent feature with flow layout. I need to redo the drag/drop logic for widgets in flow layout. Absolute layout is working pretty well, though.

**Comment by JonFerraiolo** [comment]
Fixed with the rewrite of the flow cursor logic. There is a new bug, however, because the ChooseParent key codes will almost always place the object "before" but intuitively I think most of the time people would expect "after":
