### ISSUE TITLE
Error while dragging multiple widgets in Outline

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1573]
1. Drop a dijit **Button** and **Textbox** on page.
2. Under those, drop a **ContentPane** and then a **Button** within the pane.
3. In Outline, select both the top Button and Textbox.
4. Move them underneath the ContentPane.

Move fails to finish -- only one of the widgets actually gets placed underneath the ContentPane.  I also get an error in the console: `childTreeNode.getParent() is null`.  (Unfortunately, stack was junk)

@JonFerraiolo @peller

**Comment by JonFerraiolo** [comment]
Clarification please: the drag operation is within the outline palette, right?

**Comment by jhpedemonte** [comment]
correct.

**Comment by peller** [comment]
easy to trap in the debugger in a non-debug build.  source.getItem is returning a sourceItem of type TreeNode, but data is undefined, leading to this error.  will investigate.

**Comment by peller** [comment]
the exception apparently looks different than what I saw a month ago.  what I'm seeing now is that the first element gets pasted with a ReparentCommand, and that reparent command triggers a select() call which changes the selection such that the second item to be pasted is no longer parented, leading to an exception.

How can we prevent the select() from firing for multiple paste operations?

**Comment by jhpedemonte** [comment]
Well, should selection even be part of ReparentCommand?  Doesn't seem like it to me.  Probably better to remove that and have the caller of ReparentCommand handle the selection afterwards.  Of course, that means we have to have a way of doing the selection only once the commands have finished.

**Comment by jhpedemonte** [comment]
We can also create a SelectCommand, for just such an occasion -- where we have to run commands on several widgets and then select them all after the other commands have run.

**Comment by JonFerraiolo** [comment]
Having a SelectCommand might allow us to restore the selection with undo/redo. I'm not sure about all of the implications, but it might result in better user experience for certain operations.

**Comment by jhpedemonte** [comment]
Status?  What's the risk assessment on this for M5?

**Comment by peller** [comment]
this line from Context.activate:

```
            dojo.connect(this._commandStack, "onExecute", this, "onContentChange"),
```

causes each paste to force a change in selection.  onContentChange triggers a change in selection.  Because dijit/Tree is iterating and calling pasteItem on the model, we have no way to intercept this, so the only workaround I can find is to do the onContentChange on a timer, which will occur after Tree has finished its iteration and the stack unwinds.  onContentChange will still get invoked n times when the sequence is complete.
