### ISSUE TITLE
RoundRectDataList disappears from Outline when changing content

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1576]
1. New Page, iPhone view.
2. Add **ScrollableView**.
3. Add **Heading** inside view, and set `fixed` to `top` in Properties->Widget-specific.
4. Drop a **RoundRectDataList** under Heading.
5. In Outline, expand the ScrollableView.  Notice that everything looks as expected.
6. Double-click on RoundRectDataList and enter new content.  Click OK to set content.
7. **_Check Outline.  Notice that RoundRectDataList isn't listed any more.**_
8. Select ScrollableView and change its ID in the Properties view.  **_RoundRectDataList disappears from VE.**_

@billreed63 

---

A "workaround" for this is to save, close and reload the page once the RoundRectDataList disappears from the Outline.

**Comment by aerwin** [comment]
@jhpedemonte I'm not able to reproduce this either in my local dev environment or on lab9. Could you confirm this is still broken?

**Comment by jhpedemonte** [comment]
Well, it's a bit odder now.

After **step 5**, I don't see **RoundRectDataList** in the Outline.  Double-click to open smart input, press OK -> now it **does** show up in the Outline.  Repeat and RoundRectDataList **disappears** yet again from the Outline.  Very strange.

(running from source, testing on Chrome)

**Comment by aerwin** [comment]
Talked with @billreed63 after scrum on Friday, and he thinks this might go away with some other work he's doing related to RoundRectDataList and data stores. I think the other work he's doing is related to #1797 and #1803.

**Comment by billreed63** [comment]
It looks like my fix for #1797 fixed this issue also
