### ISSUE TITLE
investigate why maqetta download went from 23mb to 45mb

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1580]
The maqetta download went grew from 25MB for M3 to 45MB for m4.  The maqetta.core.client itself is 96MB uncompressed!

**Comment by JonFerraiolo** [comment]
@waynevicknair @peller @jhpedemonte

**Comment by peller** [comment]
The Dojo source zip got ~50% larger... new code, plus a lot of deprecated baggage they can't get rid of until 2.0, but not necessarily more code in memory at runtime.  Might explain for a good chunk of this increase.

**Comment by JonFerraiolo** [comment]
@waynevicknair - could you please analyze how much is Dojo versus other things? Regarding the size of Dojo, for ZIP downloads, couldn't we only include the parts that Maqetta actually uses directly or indirectly (e.g., all of Dijit is needed for the widget palette) and exclude the rest? Low priority and of course much easier said than done.

**Comment by jhpedemonte** [comment]
Well, we already do a build of the Dojo source, so we shouldn't need to include anything that isn't include in our build profiles, correct?

**Comment by peller** [comment]
Yes, except not everything we use is in our build profiles -- In particular, R&C, but there may be some other exceptions where individual files are loaded from the tree.  Still, we ought to be able to remove large portions of dojox with zero risk.  I'd like to link directly to the Dojo git repository in the future, though, so it will be difficult to pick and choose until Dojo undertakes a more radical package restructuring (being discussed now)

**Comment by jhpedemonte** [comment]
I'm fine if we have this thing in the source.  I'm saying that after building though, all the cruft should be removed.  Since we test against built code, we should see fairly quickly if we're missing something from our build profiles.

**Comment by peller** [comment]
Unfortunately, that's not how it works.  The build tool processes everything in the source tree, as well as building the 'layer' files, and we do not use the layer files exclusively.

**Comment by JonFerraiolo** [comment]
Also, remember that we support Dojo widgets, some from dojox, and we plan to allow for widget extensibility, so users will need more of Dojo than what Maqetta uses directly.

**Comment by peller** [comment]
right, but those are in the Dojo plugin, not the main client code, at least...  so we have to ask ourselves two different questions: what to package with the maqetta client, and what to package with the dojo_1_7

**Comment by waynevicknair** [comment]
@JonFerraiolo surely. i'll take a look at it this weekend.

**Comment by waynevicknair** [comment]
maqetta.core.client&nbsp;&nbsp;&nbsp;&nbsp;grew&nbsp;&nbsp;&nbsp;&nbsp;3959035 bytes
davinci.dojo_1_7_1&nbsp;&nbsp;&nbsp;&nbsp;grew&nbsp;&nbsp;&nbsp;&nbsp;3722181 bytes
maqetta.clipart&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;added&nbsp;&nbsp;&nbsp;&nbsp;5849612 bytes

the above are the significant size differences between Preview3.1 and Preview4. looks like around 14MB.

**Comment by JonFerraiolo** [comment]
The 5.8M from maqetta.clipart will shrink to approximately zero once I address #1561

**Comment by jhpedemonte** [comment]
Since both **maqetta.core.client** and **davinci.dojo** were upgraded to Dojo 1.7, would that explain most of the size increase in those 2?

Also, did you mean to close this bug, Jon?

**Comment by JonFerraiolo** [comment]
I thought @waynevicknair had closed this bug before I commented about maqetta.clipart. @waynevicknair, if you didn't close this and I accidentally closed it, could you please reopen?

**Comment by waynevicknair** [comment]
surely. i don't believe i closed it.

**Comment by waynevicknair** [comment]
@childsb @jhpedemonte @JonFerraiolo

i propose we close this issue and move on if there is no further discussion.

**Comment by JonFerraiolo** [comment]
yes, it does seem like "investigate" happened, so please close
