### ISSUE TITLE
Active edit in Properties View not committed when change selection in Outline

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1581]
1. Create new HTML file
2. Drag 2 buttons onto canvas
3. Select 1st button and type a value into an attribute in Properties View (say "abcd" for Value attribute in widget-specific section)
4. Use Outline view to select other button
5. Select 1st button again and note that "abcd" was not saved

In every other case I've seen, a property change is committed whenever there is a focus change.

**Comment by jhpedemonte** [comment]
-> M6/Med
