### ISSUE TITLE
Review invitation should open file for recipient

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1596]
@EldonReturn @JonFerraiolo 

When a user clicks on the link in an e-mail, right now they see the workbench with a special welcome page.  In the case where there are multiple review requests, it's important to note which file (or files?) are being sent for review.  Right now, you just see the file tree, everything is collapsed.  Perhaps editors should automatically open with the relevant files?

**Comment by JonFerraiolo** [comment]
Closing. @childsb and @aerwin figured out how to get reviews to open.
