### ISSUE TITLE
Upgrade Dojo from 1.5

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#16]
We should upgrade to the current Dojo release (1.6 at the time of filing) or perhaps skip straight to trunk in order to work with the latest dojox.mobile and AMD functionality.  The latter carries risk, as the code is in flux right now.  I'll try this on a branch.

Both the workbench code and the user library must be upgraded separately.

**Comment by peller** [comment]
While we're at it, we should consider removing test directories and unneeded dojox subprojects.

@jhpedemonte has suggested checking in a built copy.  This probably makes the most sense for the user library, where debugging will be rare and can be done from a different image.  Does this make sense for the workbench as well?

**Comment by jhpedemonte** [comment]
For the workbench, let's keep around the source code;  just remove unused dirs, such as test, etc.  Will help if we need to debug into Dojo.  Plus, we do a build that compresses all of this for a release, anyway.

When creating branch, make sure to push it up to github repo, so others can pull it and work on it, as well.

**Comment by peller** [comment]
What websphere is using for their "GM" (there's no actual alpha tag)  They will upgrade to the Dojo beta for their GA.

Version:  1.7.0.alpha0

http://svn.dojotoolkit.org/src/dojo/trunk  Revision: 25014
http://svn.dojotoolkit.org/src/dojox/trunk Revision: 25023
http://svn.dojotoolkit.org/src/dijit/trunk Revision: 24988
http://svn.dojotoolkit.org/src/demos/trunk Revision: 25024
http://svn.dojotoolkit.org/src/util/trunk  Revision: 25063   ( + picked up new version.js file in util\build )

**Comment by peller** [comment]
see Javier's checkin 3fefeec0e358c295979d9947cdb9a371f5da5388 from #409 to properly fix the metadata version issue

**Comment by jhpedemonte** [comment]
Marking as closed. @peller, I assume everything is done with this bug?

**Comment by peller** [comment]
yeah, filing a separate issue to upgrade the workbench to 1.7: #481
