### ISSUE TITLE
Questionable loops in Context.js

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1601]
Two loops are flagged with FIXME comments.  The instruction in the loop is invariant.  You'd expect it to repeat with the iteration from the array, instead it passes the whole array.  Either the recipient of this data expects the array, cancelling out the error, or there's a bug we're not noticing (or the code isn't used?)

First, in Context.loadTheme:

``` javascript
            if (theme.files){ // #1024 some themes may not contain files, themeMaps
              //FIXME: Brad: this can't be right...
                theme.files.forEach(function(){
                    themeHash[theme.files] = theme;
                });
            }           
```

then in Context.getRelativeMetaTargetSelector:

``` javascript
        return target.map(function(){
            //FIXME: Brad, is it intentional to add the same thing to the selector array for each element in target?
            return theme.metadata.getRelativeStyleSelectorsText(widgetType, state, null, target);
        });
```

**Comment by childsb** [comment]
Fixed by bill reed early in the sprint.

**Comment by peller** [comment]
the second FIXME comment is still awaiting a response

**Comment by childsb** [comment]
sorry i ment to remove this too.

the target values are coming in as an array (as a fix for background).  it's basically just unraveling the array.

the unraveling should probably be done by the callers of the function, but this change was the last impacting ((and works)).  i'll remove the TODO.

**Comment by peller** [comment]
how is it unravelling the array?  It's calling the method with the same inputs each time.

**Comment by childsb** [comment]
sorry, my brain isn't functioning today.  i thought that 'target' was coming in from the map call.

so i just removed the loop.
