### ISSUE TITLE
Provide nicer UI for dealing with HTML widgets with dependencies on child elements (e.g., like SELECT, OPTGROUP, and OPTION)

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1602]
This is a spin-off from #398...

There are certain tags whose behavior is largely driven by child elements that could benefit from a nicer user experience. This is not unlike how we handle TABLE so users don't have to drag TBODY, TR, TD, etc. from the palette into the table..

Examples that could be improved are:
- SELECT, OPTGROUP, and OPTION
- FIELDSET and LEGEND
- VIDEO/AUDIO and TRACK/SOURCE
- and perhaps others

The [HTML Tags in Widget Palette](https://github.com/maqetta/maqetta/wiki/HTML-Tags-in-Widget-Palette) page in the wiki contains full details on the HTML tags in the Widget Palette.

**Comment by jhpedemonte** [comment]
Please add some details about the exact issues and some suggestions (if you have any) about how to handle them.

@JonFerraiolo

**Comment by aerwin** [comment]
Maybe to put in different terms... This is really intended to add some smart input for these elements. For example, the smart input for SELECT could use a similar dialog to the one used for the Dojo widget DropDownSelect.

**Comment by aerwin** [comment]
The highest priority item here is SELECT. So, this issue will be used to handle SELECT, OPTGROUP, and OPTION.

Other tags will be handled as follows:
- #1644 will be used for FIELDSET and LEGEND.
- #1761 will be used for VIDEO/AUDIO and TRACK/SOURCE
