### ISSUE TITLE
Investigate CreateTool files with evals

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1603]
The following file all have basically the same code, using **eval**:
- OptionsCreateTool.js
- TreeCreateTool.js
- TreeInput.js
- ItemFileReadStoreHelper.js
- DataGridCreateTool.js
- DataGridHelper.js
- TreeGridCreateTool.js
- TreeGridHelper.js
- TreeGridInput.js
- EdgeToEdgeDataListCreateTool.js
- EdgeToEdgeDataListHelper.js

---
1. First, do we even need these files any more?
2. If so, get rid of the **eval** statements in the code.

@billreed63

**Comment by jhpedemonte** [comment]
Adding **TreeCreateTool.js**, which has same **eval** code.

**Comment by jhpedemonte** [comment]
Adding **TreeInput.js** (evals).

**Comment by jhpedemonte** [comment]
Reassigning to Bill.  While I could easily fix some of these, many require knowledge of the create tools, which I think Bill is better able to handle.

Also, Bill, it seems that there is a lot of duplicated code amongst these files (particularly the ones that use stores).  Take a look at refactoring in order to prevent duplication of code.

**Comment by jhpedemonte** [comment]
See #620.

**Comment by JonFerraiolo** [comment]
@billreed63 - how come this issue was closed? I thought this issue was about code refactoring (to eliminate copy/paste of similar code). Have we done any cleanup? If not, then better to reopen and defer to future.

**Comment by billreed63** [comment]
This code was re factored, months ago. the common code is in DataStoreBasedWidgetHelper/Input
