### ISSUE TITLE
Need icons for new HTML elements added to palette

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1604]
@JonFerraiolo 

This is a spin-off from #398...

Per discussion this morning, we need some icons for newly added HTML elements.

These elements are AUDIO, EMBED, FIELDSET, LEGEND, OPTGROUP, OPTION, VIDEO. I'm currently using element.gif as a placeholder.

In addition, the icons for BUTTON, INPUT, SELECT, and TEXTAREA were copied from the Dojo Control icons, and should perhaps be re-evaluated graphic design for the HTML elements. These flles are button.png, textarea.gif, dropdown.png respectively.

**Comment by JonFerraiolo** [comment]
@jmockler

**Comment by JonFerraiolo** [comment]
@aerwin - FYI we base64 the widget palette icons to eliminate network requests for the icons. @jhpedemonte has a tool for that. He and I will take care of the base64 process once we get the icons.

**Comment by aerwin** [comment]
@JonFerraiolo 

Just to close the loop here with somre recent e-mails.... icons are _not_ required for LEGEND, OPTGROUP, or OPTION.
