### ISSUE TITLE
AMD conversion for action, html, js, and model

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1606]
From Adam:

core.client
- action/ (11) Tony
- html/ (9) Tony
- js/ (5) Tony
- model/ (5) Tony

**Comment by aerwin** [comment]
@waynevicknair @jhpedemonte @JonFerraiolo 

The `html`, `js`, and `model` packages contain a number files that aren't entirely straightforward for AMD conversion. I've taken an initial stab at getting all of those those packages ready. But, since I'm a "newbie" and these packages are really in @waynevicknair 's domain, he was going to start with what I had and take on the remaining work for those packages. So, I pushed the my 1606_core_client_amd_conversion branch out to the repository for @waynevicknair to use.

Also, based on the scrum call this morning, it sounds like much of the `js` package (like `JSModel`) is dead code. And, it doesn't appear it worked even before taking a stab at AMD conversion (e.g., "it" being formatting a JS file in the editor which crapped out in code in `js.plugin`).

Finally, the 1606_core_client_amd_conversion branch also contains my changes for the `actions` package which were pretty straighforward and shouldn't need additional changes.

**Comment by aerwin** [comment]
@waynevicknair @jhpedemonte @JonFerraiolo @peller

Apparently, from the scrum today it appears @waynevicknair decided not to use this branch I pushed out early last week. So, I'll create a new branch with _just_ the `actions` package changes and merge those.

@peller You appear to have already reviewed the 2223a05a5c601d3aa3ad066e98ced4db6c36ab3a commit. You only had 2 comments and they were on the packages Wayne took over. So, I'm assuming you're ok with the `actions` package changes?

**Comment by peller** [comment]
Go for it
