### ISSUE TITLE
maqetta.local.win.bat change for Windows 7

### ISSUE THREAD

**Issue by wnm3** [maqetta/maqetta#1613]
I found I needed to edit the 2nd to last line so it would work in Windows 7.

The original line was:
FOR /F "tokens=_" %%R IN ('dir /b plugins\org.eclipse.equinox.launcher_.jar') DO SET EQUINOX=%%R

however, to get it to work for me, I replaced this line with the following (note: no quotes required):
FOR /R plugins %%R IN (org.eclipse.equinox.launcher*.jar) DO SET EQUINOX=%%~nR%%~xR

I'm using preview 4.

**Comment by JonFerraiolo** [comment]
@childsb, @jhpedemonte 

I have a Windows7 box...

**Comment by jhpedemonte** [comment]
@doronrosenberg, do you have Windows 7?  If so, can you take this as well?

**Comment by doronrosenberg** [comment]
hmm, I can start the nightly builds just fine on Windows 7 64 bit without any changes.

**Comment by JonFerraiolo** [comment]
I dusted off a junky low-end Windows 7 box that we normally never use here at home because everything is so painfully slow and difficult, and then downloaded today's nightly build and ran the 2 launch scripts (maqetta.server.win.bat and maqetta.local.win.bat) and everything worked fine for me, too. I even verified the launch scripts when running from a folder where there is a space in the name.

@doronrosenberg : can you research the command syntax on windows to see what the difference is between the code we are using now and the recommended code in this bug report?

**Comment by wnm3** [comment]
Can you please send me a copy (or paste content here and I'll try testing what you are using)? Thanks in advance.

**Comment by doronrosenberg** [comment]
I used the latest build at http://maqetta.org/nightly/

**Comment by wnm3** [comment]
Installed maqetta-20120315-0604.zip and tried both local and server_win.bat and get:

C:\maqetta>maqetta.server.win.bat

Java version:
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02, mixed mode)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
NOTE: CLOSING THIS WINDOW WILL
      STOP THE MAQETTA SERVER PROCESS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Using directory : C:\maqetta\users
The system cannot find the file specified.
Unable to access jarfile C:\maqetta\plugins" -console -noExit

and

C:\maqetta>maqetta.local.win.bat

Java version:
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02, mixed mode)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
NOTE: CLOSING THIS WINDOW WILL
      STOP THE MAQETTA SERVER PROCESS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Using directory : C:\maqetta\users
start your browser at http://localhost:50000/maqetta
The system cannot find the file specified.
Unable to access jarfile C:\maqetta\plugins" -console -noExit

Using Winows 7 Professional 64-bit (Version 6.1 (Build 7601: Service Pack 1)

However, running the old script I'd modified works:

C:\maqetta>cat save_maqetta.local.win.bat
@ECHO OFF
echo.
echo Java version:
java -version
echo.
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
echo NOTE: CLOSING THIS WINDOW WILL
echo       STOP THE MAQETTA SERVER PROCESS
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
echo.

## wnm3: set port=50000

set port=8081
set scriptdir=%~dp0

rem #########################
rem Comment out logic to set default directories for XP and Vista
rem Instead, users directory will be in current folder
rem set usersdir=%APPDATA%
rem if "%usersdir%" == "" set usersdir=%USERPROFILE%\Application Data
rem set usersdir=%usersdir%\maqetta\users
rem #########################
set usersdir=%scriptdir%users
mkdir "%usersdir%" 2>nul
echo Using directory : %usersdir%

echo start your browser at http://localhost:%port%/maqetta
rem ## out for win7 FOR /F "tokens=_" %%R IN ('dir /b plugins\org.eclipse.equinox.launcher_.jar') DO SET EQUINOX=%%R
FOR /R plugins %%R IN (org.eclipse.equinox.launcher*.jar) DO SET EQUINOX=%%~nR%%~xR
java -Dorg.eclipse.equinox.http.jetty.http.port=%port%  -Dmaqetta.localInstall=true -Dmaqetta.baseDirectory="%usersdir%"
 -DloginUrl="/maqetta/welcome" -jar "%scriptdir%plugins\%EQUINOX%" -console -noExit

C:\maqetta>

**Comment by doronrosenberg** [comment]
@JonFerraiolo the suggested changes work fine for me, so we can just accept them if you are ok with that.

**Comment by JonFerraiolo** [comment]
Yes, almost certainly the changes are good, but we should still study the Windows command reference to make sure we understand what this change is doing so we feel confident that the fix doesn't break something else. Do you have the ability to study Windows command reference? If not, we can find someone else on team to do that due diligence.

**Comment by doronrosenberg** [comment]
@wnm3 do these commands work for you:

FOR /R plugins %%R IN (org.eclipse.equinox.launcher*.jar) DO SET EQUINOX=%%R
java -Dorg.eclipse.equinox.http.jetty.http.port=%port%  -Dmaqetta.localInstall=true -Dmaqetta.baseDirectory="%usersdir%" -DloginUrl="/maqetta/welcome" -jar "%EQUINOX%" -console -noExit

**Comment by wnm3** [comment]
yes -- result of running just those commands is the osgi> prompt. Thanks.

**Comment by wnm3** [comment]
note: accessing maqetta from the browser resulted in some output that my be related to the nightly build status:

osgi> servlet parm 'maqetta.localInstall' is : true
servlet parm 'inWar' is : null
servlet parm 'maqetta.serverDebug' is : null
servlet parm 'maqetta.baseDirectory' is : C:\maqetta\users

Setting [user space] to: C:\maqetta\users
servlet parm 'maqetta.maxUsers' is : null
servlet parm 'maqetta.baseDirectory' is : C:\maqetta\users

which I assume is to be expected.
