### ISSUE TITLE
Object selection in Outline, then on slider tacks on tooltip

### ISSUE THREAD

**Issue by wnm3** [maqetta/maqetta#1614]
I have deeply nested objects so when using the outline I need to adjust what is visible by using the slider bars.  Unfortunately, if I've selected an object (not dragging, just clicked to highlight it) and then I click on the horizontal or vertical slider bar, it appears as though this triggers a "feature" as though the object is selected for drag/drop because a tooltip like box is attached to the mouse pointer and highlights valid drop locations.

Is there a way to disable this feature?  There are times when the tooltip doesn't get completely cleaned up, leaving a rectangle with a number, the visibility icon and object type floating over the Outline content and you can't get rid of this (not refresh option) unless you close and reopen the browser.

I would prefer enabling this feature if one were holding down the Ctrl key when selecting an item (or some similar key combination) so the slider bars are used solely for scrolling the outline window content.

**Comment by JonFerraiolo** [comment]
@peller

**Comment by peller** [comment]
see also #1532  There is an underlying Dojo DnD bug with the scrollbar.

**Comment by jhpedemonte** [comment]
Dup of #1018.
