### ISSUE TITLE
Switching display views loses Outline context

### ISSUE THREAD

**Issue by wnm3** [maqetta/maqetta#1615]
Often, I want to copy portions of html (e.g., to add a new row in a table) but I'm in the Display Design mode.  If I have selected the row I want to copy in the outline (which may have required expanding several containers) and then I change the Display Source, or one of the Split views, the Outline window is collapsed to its highest level and I need to navigate again to the area where I was before.  Is there any way to preserve the object selection in the Outline view (or at least not collapse the tree) so we can [re]select the object to highlight the code we want to copy?

Also, is it possible to allow copying and pasting an object in the Outline view when the Display Design view is being shown? It seems the copy/paste only works when there is a Display view showing html.

**Comment by JonFerraiolo** [comment]
@waynevicknair - this one may to a village to get right since it involves coordination across various complex parts of the code.

@peller

**Comment by waynevicknair** [comment]
the drag and drop support added to outline view in preview 4 should handle cut/copy/paste/delete directly from the outline. if that does not fit your requirements, please re-open this issue. thanks.
