### ISSUE TITLE
Remove/replace dojo.require calls in DataGridHelper.js

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1617]
Found these in **DataGridHelper.js**:

``` javascript
    dj["require"]('dojo.data.ItemFileReadStore');
    dj["require"]('dojox.io.xhrScriptPlugin');
```

We've moved on from using dojo.require, so these should be changed.  Or removed, if no longer necessary.

There may be other helpers/createTools in the Dojo lib that do the same thing...

---

Also **davinci.dojo/WebContent/metadata/dojox/mobile/ThemeHelper.js**.

---

And **ItemFileReadStoreHelper.js**, which has similar code to **DataGridHelper.js**.  Might consider refactoring that, rather than duplicating in two separate files.

@peller

**Comment by billreed63** [comment]
This are required for the code to work..

**Comment by peller** [comment]
...but they do need to be converted to use context.getGlobal().require() instead of dojo.require.  May be non-trivial, since the call will become asynchronous, and everything beyond the return of the method may need to use a callback or Deferred.

**Comment by jhpedemonte** [comment]
Also **davinci.dojo/WebContent/metadata/dojox/mobile/ThemeHelper.js**.
