### ISSUE TITLE
Panel.js openDialog approach to layout should be improved

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1621]
The `davinci.libraries.html.html.HtmlSrcAttributeInput` class passes a definition to `davinci.ui.Panel.openDialog` consisting of a `tree` and two `textBox`'s. The resulting dialog created by the `Panel` has no vertical padding between the two text boxes (or between the last text box and the OK button). In addition, there's is a lot of extraneous space below the OK button.

This has become especially apparent when I recently modified the text field labels to be a little shorter in length.

See the screenshot below:

![Example screenshot](http://i.imgur.com/ulBia.jpg)

**Comment by jhpedemonte** [comment]
Perhaps adding a CSS file to properly style the content is all that is necessary.

**Comment by aerwin** [comment]
This will be naturally taken care of as part of #1638. So, closing this one.
