### ISSUE TITLE
HTML <img> and <iframe> elements generate console error messages

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1625]
When adding an IMG or IFRAME element to a page, the following messages appear in console. Looks like the globalization file isn't available. 

@jhpedemonte, @peller: did we make fixes to other widgets to prevent loading of nls (natural language system) files? Why is this widget generating messages when others don't? 

```
GET http://localhost:50000/maqetta/app/metadata/html/0.8/html/nls/en/html.js?8da95027480039fc6bdb00b4ce46d2c01fc3963e 404 (ProxyServlet: /maqetta/app/metadata/html/0.8/html/nls/en/html.js)
dojo.js:4103
Error
dojo.js:1736
Error
dojo.js:1736
Error
dojo.js:1736
Error
GET http://localhost:50000/maqetta/app/metadata/html/0.8/html/nls/en-us/html.js?8da95027480039fc6bdb00b4ce46d2c01fc3963e 404 (ProxyServlet: /maqetta/app/metadata/html/0.8/html/nls/en-us/html.js)
dojo.js:4103
Error
dojo.js:1736
Error
dojo.js:1736
Error
dojo.js:1736
Error

```

**Comment by aerwin** [comment]
I don't think this happens since #398 went in (at least it doesn't my my local dev environment). Been waiting to confirm in an official build, but that's still held up by #1628.

**Comment by JonFerraiolo** [comment]
Can't test with the latest code because I'm running into #1643

**Comment by peller** [comment]
seems to be fixed
