### ISSUE TITLE
Background image - can't manually enter value

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1627]
@childsb 

background-image works fine if user brings up Background dialog and then clicks on button to bring up file picker, but doesn't work if user types in a value into text field on Properties palette or into text field on Background dialog.

**Comment by JonFerraiolo** [comment]
@childsb can you look at this bug (fixing some bugs that I introduced)? The most important parts for M5:
- Can't type `url(SampleBanner.jpg)` into type-in field for background-image in the Properties palette. Instead, you get a console message that says `GET http://localhost:8081/maqetta/user/maqettaUser/ws/workspace/SampleBanner.jpg 404 (Not Found)`
- Can't type a full URL into type-in field for background image. For example, I tried `url(http://www.w3.org/html/logo/img/html5-topper.png)`. This value causes the value to revert to a previous value.

The background dialog also has problems. If you set background-image type to "image", and enter `http://www.w3.org/html/logo/img/html5-topper.png` as the value and click OK at bottom of dialog, the actual URL value gets set to `http://localhost:8081/http://www.w3.org/html/logo/img/html5-topper.png`

**Comment by childsb** [comment]
er.. not sure why that closed but re-opened.

Most of the issue were around an assumption that quotes are required in the url(...).  Fixed around that, but still have an issue if the user brings up the dialog and manually enters a value for the image url.  the value "../" is prepended to the typed in value.
