### ISSUE TITLE
Can't create new HTML file

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1628]
With the last couple builds on http://macwayne2.austin.ibm.com/buildAdmin/index.php (installed locally), I get the following exception when trying to create a new HTML file. I'm using Chrome. 

I think the offending line in VisualEditor is `var loc = Workbench.location();`, so perhaps related to recent AMD changes to `Workbench.js`?

``` javascript
Uncaught TypeError: Object #<Object> has no method 'location'
require.cache.davinci/ve/Context._1d66.constructordavinci/davinci:45463
adojo.js:2771
require.cache.davinci/ve/VisualEditor._107._setContentRawdavinci/davinci:1422
require.cache.davinci/ve/VisualEditor._107._setContentdavinci/davinci:1407
require.cache.davinci/ve/VisualEditor._107.setContentdavinci/davinci:1403
require.cache.davinci/ve/PageEditor.dojo.declare.setContentdavinci/davinci:26431
require.cache.davinci/workbench/EditorContainer._765.setEditordavinci/davinci:9444
require.cache.davinci/Workbench._37f._createEditordavinci/davinci:4872
require.cache.davinci/Workbench._37f.openEditordavinci/davinci:4835
require.cache.davinci/ui/Resource.dojo.mixin.openResourcedavinci/davinci:12031
require.cache.davinci/ui/Resource.dojo.mixin.newHTML._932davinci/davinci:11713
(anonymous function)davinci/davinci:4445
_312dojo.js:3801
_421.(anonymous function)dojo.js:5337
require.cache.davinci/ui/widgets/NewFile.dojo.declare._okButtondavinci/davinci:31789
_312dojo.js:3797
_421.(anonymous function)dojo.js:5337
require.cache.dijit/form/_ButtonMixin._1a8._onClickdavinci/davinci-common:2035
_260dojo.js:2641
require.cache.dijit/form/Button._126._onClickdavinci/davinci-common:1378
_312dojo.js:3797
require.cache.dijit/_OnDijitClickMixin._1e3dijit/dijit:1936
```

**Comment by JonFerraiolo** [comment]
I verified what @aerwin is seeing by pulling down today's nightly build from maqetta.org/nightly. Looking in debugger, the parameters passed into the AMD function (matching the first 6 items in the dependency array) don't look right.

**Comment by JonFerraiolo** [comment]
Upon further exploration, I'm seeing that, in a build, the define() function in Context.js is getting called before the define() function in Workbench(), and I can see NewTheme.js as being involved in the stack. Note that NewTheme.js isn't yet converted to AMD.

**Comment by peller** [comment]
this may be fixed.  in tomorrow's build, if the problem still occurs, capture an enumeration of the Workbench variable.

**Comment by aerwin** [comment]
Seems like it's worse after downloading the build this morning. Failing in a different place.

Uncaught TypeError: Object #<Object> has no method 'workbenchStateCustomPropGet'
require.cache.davinci/ui/widgets/NewHTMLFileOptions._1727.postCreatedavinci/davinci:33186
require.cache.dijit/_WidgetBase._288.createdijit/dijit:2704
require.cache.dijit/_WidgetBase._288.postscriptdijit/dijit:2676
adojo.js:2748
require.cache.davinci/ui/widgets/NewFile._14ee.postCreatedavinci/davinci:29527
require.cache.dijit/_WidgetBase._288.createdijit/dijit:2704
require.cache.dijit/_WidgetBase._288.postscriptdijit/dijit:2676
adojo.js:2748
require.cache.davinci/ui/Resource.dojo.mixin._createNewDialogdavinci/davinci:10175
require.cache.davinci/ui/Resource.dojo.mixin.newHTMLdavinci/davinci:10179
(anonymous function)
require.cache.davinci/Workbench._2f6._runActiondavinci/davinci:3943
_380dojo.js:4540
require.cache.dijit/_MenuBase._1c9.onItemClickdavinci/davinci-common:2233
require.cache.dijit/MenuItem._1ae._onClickdavinci/davinci-common:2083
_385dojo.js:4556
require.cache.dijit/_OnDijitClickMixin._1e3

**Comment by peller** [comment]
yup. the eval on the stack makes me nervous

**Comment by peller** [comment]
fixing the circular dependency solved this problem
