### ISSUE TITLE
Red screen of death if Menubar has no dijit.Menu inside

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1629]
@billreed63 

Priority-High to investigate. I realize this sort of bug (where dojo markup is not correctly specified) might be very difficult to fix.

Here is a file that causes red screen of death in Preview 4:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<style>@import "themes/claro/claro.css";@import "lib/dojo/dojo/resources/dojo.css";@import "app.css";
</style>
<script type="text/javascript" src="maqetta/maqetta.js"></script>
<script type="text/javascript" data-dojo-config="'async':true,'parseOnLoad':true,'packages':[{'name':'maqetta','location':'../../..'},{'name':'clipart','location':'../../clipart'},{'name':'shapes','location':'../../shapes'},{'name':'jquery-ui','location':'../../jquery-ui'},{'name':'yui','location':'../../yui'}]" src="lib/dojo/dojo/dojo.js"></script>
<script type="text/javascript" src="maqetta/States.js"></script>
<script type="text/javascript">
require(["dijit/dijit"]);
require(["dojo/parser"]);
require(["dijit/Toolbar"]);
require(["dijit/form/Button"]);
require(["dijit/MenuBar"]);
require(["dijit/PopupMenuBarItem"]);
require(["dijit/MenuItem"]);
require(["dijit/Menu"]);</script>
</head>
<body class="claro" dvFlowLayout="true" data-davinci-ws="collapse" id="myapp">
 <div id="bannerDiv" class="header">
<img id="banner" src="http://maqetta.org:55556/maqetta/user/roman.chanclor@eim-usa.com/ws/workspace/UMI-3/WebContent/UMI%20Banner%202012.png" class="bannerImg"></img>
</div>
 <div id="menuBar" class="menuBarDiv">
   <span dojoType="dijit.MenuBar" tabIndex="0"><span dojoType="dijit.PopupMenuBarItem" label="Menu 1" iconClass="dijitNoIcon"></span><span dojoType="dijit.PopupMenuBarItem" label="Menu 2" iconClass="dijitNoIcon"></span>
   </span>
 </div>
</body>
</html>
```

After investigation, the problem is that the PopupMenuBarItems do not have a dijit.Menu child element. If I change the two PopupMenuBarItem widgets to have an empty dijit.Menu child element:

```
<span dojoType="dijit.PopupMenuBarItem" label="Menu 2" iconClass="dijitNoIcon"><span dojoType="dijit.Menu"></span></span>
```

then the red screen of death disappears.

Obviously, we want to avoid situations where users see the red screen of death, so if there is a way to recover from missing dijit.Menu, that would be great.

**Comment by peller** [comment]
Given the way Dijit works, I don't think it's feasible to do any sort of partial rendering.  I think what we have now is the right approach, but we could certainly make it friendlier (matching UI, helpful messages, etc.).  We should also try to separate the user content-driven exceptions, like this one, from internal exceptions in the product.  It's reasonable for the latter to continue to spawn some rough screen with a stack trace.
