### ISSUE TITLE
logging / investigate JVM heap space on server

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1632]
Add server logging and find tools to attach to JVM.  The heap is running out on maqetta.org with default heap settings.  Are we leaking?  Are file handles not being closed?

**Comment by jhpedemonte** [comment]
Server leaks were fixed in #1806.  Is this still necessary?

@peller

**Comment by peller** [comment]
we now run with a setting that generates a heap file on failure, such that we can inspect it with the jhat tool.  If we could update to a newer JVM, we'd be able to inspect the heap concurrently.

**Comment by childsb** [comment]
Should we list upgrade JVM as a migration issue so we can do inspections on next release?

**Comment by peller** [comment]
it would be a nice-to-have, but @waynevicknair suggested it was a hosting limitation.
