### ISSUE TITLE
Remove old, inactive accounts from maqetta.org

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1641]
Steps:
1. Archive the workspaces from the accounts that we will be deleting. We have an archival backup of the whole system run by our hosting servcie. For extra backup, we'll store a ZIP of old workspaces on a different server.
2. No notification to users about deleting the accounts. If someone actually had content of value that they discover down the road that they need, then they can post on maqetta-users or twitter asking what happened to their data, and we can send them their files on a one-off basis. My guess though is that no one will make such a request. 
3. Delete both the user's login from the Maqetta.org list of users and the workspace. Use the deleteUser command and listener plugin. Use the Maqetta.org user manager to drive the clean up process. 
4. Our general strategy is to delete any accounts that haven't been used since the N-1th release. What this means right now is that, with Preview 4, we would delete any accounts that haven't been modified since we ran the migration scripts on Preview 3 workspaces. 
5. Enhance the text at Maqetta.org that talks about possible data deletion to specifically mention the above account deletion strategy as an example of something that might happen to user accounts.  (DONE: See http://maqetta.org/index.php?option=com_content&view=article&id=13&Itemid=12)
6. Adopt the same approach for all hosting environments

**Comment by waynevicknair** [comment]
done. step 3 changed as follows:
1. Delete both the user's login from the Maqetta.org list of users and the workspace. Drive deletion through the Joomla User Manager. The Maqetta Joomla user plugin writes a file named 'deleted_users.txt' which is easily converted to a script -- 'deleted_users.sh' -- and run to remove the workspace directories for the users deleted from the Joomla user database.
