### ISSUE TITLE
Can't drag/drop IMG or IFRAME

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1643]
@peller 

With latest code, if you drag/drop an IMG or IFRAME, you get the (most unhelpful) error dialog from CreateTool that says "The action was interrupted by an internal error.". When turning on "stop on all exceptions", the error happens in HtmlSrcAttributeInput.js:66 with an attempt to call `davinci.ui.Panel.openDialog()`

**Comment by peller** [comment]
perhaps should we spit out the stack trace to the console.  The console.\* APIs don't seem to provide any help for logging exceptions.

**Comment by JonFerraiolo** [comment]
Seems to be fixed now
