### ISSUE TITLE
Sticky note not bringing up RTE

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1645]
@childsb, @peller 

Probably something broke during AMD conversions with sticky note widget. With latest code, if you click on the sticky note icon on toolbar or drag/drop a sticky note from widget palette, up comes regular-old SmartInput, not the dojo RTE.

Note: "Rich Text" widget works OK - dojo RTE comes up for that.

**Comment by billreed63** [comment]
The `dvwidget="html.stickynote"` is missing on the div widget that gets created,  I can't create a new Rich Text widget I get an exception in the StyleChangeCommand the ``define[divinci/vi/widget]` is not returning a widget object...
