### ISSUE TITLE
Windows 7 64 bit - Problem with new HTML file not loading into WYSIWYG Editor View

### ISSUE THREAD

**Issue by jdxpointe1** [maqetta/maqetta#1647]
Windows 7 64 bit - Problem with new HTML file not loading into WYSIWYG Editor View. Spin turns indefinitely and visual content is never displayed. Using the 1/26/2012 build.

**Comment by jdxpointe1** [comment]
Its a Local Maqetta installation.

Google Chrome
16.0.912.77 m

java version "1.6.0_23"
Java(TM) SE Runtime Environment (build 1.6.0_23-b05)
Java HotSpot(TM) 64-Bit Server VM (build 19.0-b09, mixed mode)

**Comment by JonFerraiolo** [comment]
(@jdxpointe1: sorry about broken nightly build. We are in the midst of major code changes that touch almost every file. The current code generally runs OK if you pull down all of the source code and run the product as a developer (launching from the Eclipse IDE), but the nightly builds are the result of "compiling" the code and we have some outstanding issues on that front that might take a few days to fix.)

I pulled down today's build and same problem on Mac/Chrome and Mac/FF. 

May be same underlying problem as #1628

**Comment by jdxpointe1** [comment]
Ah sorry to duplicate.. Thanks for the quick response and info. I will tune back in through the next few days for another build...
