### ISSUE TITLE
Please Disable Terrible Helper Feature

### ISSUE THREAD

**Issue by ghost** [maqetta/maqetta#1652]
I'm learning Maqetta and have run into the absolutely most frustrating feature I could imagine.

When I go over the outline view and my mouse goes off the screen then comes back, there is a floating window that appears to represent the activation of a feature that will insert a piece of my tree into another part of my structure even though I'VE PRESSED NOTHING. And I can't make it go away most time (Escape, right click, anything). Worse, it often just decide to insert itself into another piece of my tree.

Please turn this off or tell me how to - I've looked at the project settings but can't tell how to turn it off. Thought it was the "when dragging, show possible parents", but that is off. I can provide an image but don't see how to upload into this comment.

**Comment by peller** [comment]
possibly related to #1532

**Comment by peller** [comment]
Hi milanchotai.  The tracker doesn't have a place to upload pictures.  You'd have to use something like skitch, flickr, etc.

What you're looking at sounds like the Dijit DnD UI, which is used by the outline Tree.  Does it look like [this](http://dojotoolkit.org/documentation/tutorials/1.6/store_driven_tree/images/dndTreeScreenshot.png)?  #1532 references a bug where the scrollbar causes the DnD UI to stay around.  I'm unaware of any situation where the DnD UI would appear without clicking and dragging the mouse.  Can you provide more information on how to reproduce this?  Which browser are you using?

**Comment by peller** [comment]
see also #1614

**Comment by ghost** [comment]
Hi Peller,

Apologies for delay in response - yes, #1532 exactly describes my issue. Couldn't determine cause at first but noted it strangely seemed related to scrollbar on the outline view / tree. It is the DnD UI floating window. Luckily, I realized and have avoided additional issues of corruption by simply clicking when it indicates red / invalid node for drop. Clicking left mouse button when this happens makes the DnD UI go away so I can continue.

**Comment by JonFerraiolo** [comment]
Adam's workaround is best thing to try, but if that doesn't work, I would expect another workaround would be to refresh the browser. Sort of a heavy-handed workaround, but browser refresh with Maqetta is somewhat equivalent to a reset button.
