### ISSUE TITLE
[AMD regression] SaveAs not working

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1655]
(Note: was able to reproduce 1 hour ago, but just did a git pull and nothing works right now, so I couldn't verify if this bug still exists.)

@childsb 
- New HTML File
- Add a Button
- SaveAs to a different name

Results=> Hangs

**Comment by waynevicknair** [comment]
fixed in commit 33f95c0a52bed07be7612dd3fdf25b3cbf0253d3.

there was a circular dependency in CSSImport.
