### ISSUE TITLE
[AMD regression] New CSS file, New JS file broken

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1656]
(Note: was able to reproduce 1 hour ago, but just did a git pull and nothing works right now, so I couldn't verify if this bug still exists.)

@childsb
- New CSS File or New JavaScript File

Results=> Hangs

**Comment by waynevicknair** [comment]
fix in commit 08ec9200e2f472ec4a363c6ac8e94510959f407a.

there were some unset variables resulting from AMD changes.
