### ISSUE TITLE
CSSModel shorthand needs to be static, not instance-based

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1660]
The shorthand object defined in CSSModel.js is now on the instance object rather than statically defined. Previously, before the AMD conversion, the shorthand object was a global static object located at davinci.html.CSSModel.shorthand and is referenced as a global static object by _Widgets.js and Context.js.

To make it into a global status object, look at similar (and redundant, but that's a different bug: #1659) definition in davinci/ve/utils/CSSShortHand.js

**Comment by waynevicknair** [comment]
fixed in commit 6be8504ca1a047462bacba60085e103e4637561c. made CSSModel.shorthand static.
