### ISSUE TITLE
[AMD Regression] Switch themes icon not working

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1662]
@peller 

This might be a well-known issue, but logging it just in case no one else has noticed.

If you click on the Switch Theme icon on the toolbar, the code dies at Theme.js:186 because the Workbench object doesn't include a getProject method.

Circular dependency:
- pagedesigner.html requires Workbench
- which requires NewTheme
- which requires Theme (and Workbench)
- which requires Workbench

**Comment by peller** [comment]
looks like it's the Preferences reference, not the getProject one
