### ISSUE TITLE
Orion exception when going into split view

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1663]
@waynevicknair 

With latest code just pulled, if you go into split view following the steps below, you get this exception:

`orion/textview/textView:5551Uncaught TypeError: Cannot set property 'className' of null`
- New HTML File
- Add a Button
- Go to split view
- Change button label from "Button" to "aaa". (Notice that button's selection goes away, but that's a different bug)
- Go back to design view
- Select Button
- Go to split view

Result=> See exception above

Note: in Preview4 release code (built) the above steps result in a different exception at textView.js:4447:

`orion/textview/textView:4447Uncaught TypeError: Cannot call method 'getPropertyValue' of undefined`

**Comment by peller** [comment]
dup of #1394
