### ISSUE TITLE
Too many cookies, sometimes too large

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1666]
@childsb 

When I looked at Chrome "under the hood" at my localhost cookies, there were about 70 cookies. I noticed this because I was testing "download entire workspace" and I was busting through the limit on web request size, causing download action to fail. When I removed all cookies, everything worked ok.

Unfortunately, I didn't save all of the cookies so that we could examine them, but I looked at a couple and it looks like we get extra cookies when doing a preview in browser. (Maybe if preview in browser includes a Tree widget?)

But can we put in some checks at Maqetta startup to look at the size of all of the existing cookies and removing cookies if the total size is over a particular size? For example, maybe limit total cookie size to 2K?

**Comment by peller** [comment]
how about running the preview on a different port to isolate it from the app?

**Comment by JonFerraiolo** [comment]
Adam and I did some research, such as examining the cookies that Maqetta creates and looking at http://www.quirksmode.org/js/cookies.html. 59 of the cookies were "davinci.user", but each with a different path (for all of the different folders that Maqetta might ever visit).

What Adam and I concluded is that the server should set the path on the davinci.user cookie so that there is one and only one davinci.user cookie for an entire Maqetta session. Maybe set path to `/` or `/maqetta`? 

One curious thing is that I often run 2 versions of Maqetta: one at localhost:8081 (for development) and localhost:50000 (to test builds and/or do demos). When I had just run the multi-user version of localhost:50000 as user JonFerraiolo, when I then ran single-user localhost:8081, my davinci.user cookie said "JonFerraiolo" instead of "maqettaUser" or whatever is used for single user.

Note: I'm not sure if things will break if we make such a change. Definitely shouldn't make this change just before a release.

Question: does the server actually use the davinci.user cookie?

**Comment by peller** [comment]
Raising priority.  Perhaps this is a must-fix for M5?

**Comment by JonFerraiolo** [comment]
I actually don't think this is a must-fix. Users don't see to be seeing this, and if they do, maybe they'll ask on the forum and we can suggest that they clear cookies. But I'm certainly not against fixing this!

**Comment by peller** [comment]
Any idea why @aerwin ran into this?

**Comment by JonFerraiolo** [comment]
Probably because he has been doing lots of testing recently. My guess is that the culprits are the Tree widgets that store the list of open nodes in cookies.

**Comment by childsb** [comment]
i only see one DAVINCI.USER cookie defined on /

theres 2 other cookies, both for dijit trees then a JSESSIONID.

is this still a bug?  maybe this was fixed previously

**Comment by JonFerraiolo** [comment]
Reopening and reassigning to me to test against tomorrow's build

**Comment by JonFerraiolo** [comment]
Closing again. I think we are OK now except maybe if a user's workspace has an awful, awful lot of open tree nodes that might end up busting the 8K cookie limit found on many servers.
