### ISSUE TITLE
decouple review code from davinci/Runtime

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1670]
There are 4 methods called from davinci/review:

> Yeah, there are six methods in Runtime which were moved from the redundant review/Runtime file which was deleted. They are `getRole()`, `getDesigner()`, `getDesignerEmail()`, `publish()` which as a review action reference, getMode() and getColor() which also has a review reference. 

These are all static methods, and merging them into davinci/Review results in pulling in additional code dependencies on davinci/review/\*  In order to keep our code lighter and to make it possible to defer loading, etc., let's decouple them.  The 4 methods can go back to a module in davinci/Review.  The `publish()` method probably isn't even needed -- the call through `PublishAction` can just be inlined in the review.plugin, preferably through a require() call -- see ui.plugin for an example.

**Comment by peller** [comment]
the same seems to be true of Workbench.  Some code is mixed into Workbench, which seems to be redundant with code already in workbench and in some cases not even related (e.g. the Explorer view is now loaded by Review code)  Need to straighten this out.

**Comment by jhpedemonte** [comment]
-> M6

Doesn't seem like a ship issue, but something we want to do soon.  Keeping priority high.

**Comment by childsb** [comment]
checkin #8712df9 broke the publish command (Runtime.publish is not defined)

**Comment by peller** [comment]
see my notes on the publish method (now on Workbench?)  It should just go away entirely.

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte (so this doesn't fall through cracks)

**Comment by jhpedemonte** [comment]
-> M7, @aerwin.  Tony, please take a look at this at the start of M7 so we can finally close it out.

**Comment by aerwin** [comment]
Think we can close with the above commit (which removes the `publish` function from `Runtime`).
