### ISSUE TITLE
[AMD Regression] [Build] Exception first time adding a widget of a particular type

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1671]
I created a build about 30 minutes ago on macwayne2 and tried to run it, and found I get an exception the first time I attempt to add a widget of a particular type:

GET http://localhost:50000/maqetta/app/dojo/davinci.libraries.dojo.dijit.form.CheckBoxHelper.js?15eab01ed8b573a6a12199453819c07294b2fbbe 404 (ProxyServlet: /maqetta/app/dojo/davinci.libraries.dojo.dijit.form.CheckBoxHelper.js)

But the second time I attempt to add that particular widget, it works, although I found that with TabContainer, I needed to try a 3rd or 4th time (I lost track)

**Comment by jhpedemonte** [comment]
I'm assuming this is done now.  Was there any thing left, @JonFerraiolo?

**Comment by JonFerraiolo** [comment]
If there are other issues, we can create new bugs. Closing this one.
