### ISSUE TITLE
[AMD Regression] [Build] No SmartInput for dojox.mobile.RoundRectList

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1672]
(Works ok when running from Eclipse, only has problem when running a build)
- Pull down a build
- New HTML FIle - composition type = iphone
- Add View, Heading and RoundRectList

Result=> No SmartInput prompt for RoundRectList. (But you do get one for Heading)

@billreed63

**Comment by peller** [comment]
works for me using 8e8af59130725d8b2eafe2af60533a532c8a5bda

**Comment by JonFerraiolo** [comment]
Verified with a new build, closing
