### ISSUE TITLE
Dirty bit not preserved across browser refresh (user data loss)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1682]
(Same problem with Preview4 release and latest code)
- Go to Maqetta.org and click on "Give it a Try", then "Launch Maqetta" to get a virgin workspace in cloud
- New HTML File
- Add a Button (notice: dirty bit shows)
- Browser refresh

Result=> page refreshes with the HTML file containing the Button, file1.html is listed in Files palette, but dirty bit doesn't show on editor tab.
- Click "x" close on editor

Result=> editor closes without a prompt, file1.html disappears from files palette, so user's work since last save has been lost

**Comment by childsb** [comment]
Fixed with commit 088c8102e956f5be3ef5cc5f6fba9c4a18b24fbe
