### ISSUE TITLE
[AMD Regression] Double-clicking SampleJS.js in Files Palette Fails

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1687]
Using Chrome and locally installed build on Windows, I get the following exception:

Uncaught TypeError: Cannot call method 'getOpenEditor' of undefined
require.cache.davinci/js/js.plugin.define.davinci.editorActions.editorContribution.actions.isEnableddavinci/davinci:22113
require.cache.davinci/Workbench._36b._createToolBardavinci/davinci:3878
require.cache.davinci/workbench/_ToolbaredContainer._129a._createToolbardavinci/davinci:23464
require.cache.davinci/workbench/EditorContainer._6b3.setEditordavinci/davinci:7877
require.cache.davinci/Workbench._36b._createEditordavinci/davinci:4458
require.cache.davinci/Workbench._36b.openEditordavinci/davinci:4421
require.cache.davinci/workbench/Explorer._6e7._dblClickdavinci/davinci:8152
_383dojo.js:4555
_492.(anonymous function)dojo.js:6092
require.cache.dijit/Tree._22a6._onDblClickdavinci/davinci:49874
require.cache.dijit/Tree._22a6._onDblClickdavinci/davinci:49555
_383dojo.js:4551

**Comment by JonFerraiolo** [comment]
Also dies on Mac and when running dev version from Eclipse at js.plugin:107
