### ISSUE TITLE
[AMD Regression] Can't set title

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1690]
1) New HTML (or old, who cares!?!?)
2) DND a button
3) Highlight the button, go to common properties
4) set the title to any string and click away.  Notice error in console (or break on error):

_2161 is not a constructor
[Break On This Error](47722 out of range 6274)

**Comment by JonFerraiolo** [comment]
@peller @jhpedemonte 

Dies in CommonProperties:105

The ModifyCommand variable (from closure) has bogus information on it. I think this is just a easy-to-fix coding error in the AMD declarations at the top of the file.

**Comment by JonFerraiolo** [comment]
Reassigning to @peller, with hope that he might have a clue about why things aren't working in build but OK when running from Eclipse.

**Comment by peller** [comment]
looks ok to me.   I had reopened the bug simply because I hadn't tested it... yet the bug appears to be in a closed state.  If you think it should be re-opened, please do so
