### ISSUE TITLE
Overlay widget throws exception

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1693]
Tooltip placement

Steps
Standard setup things: Clear the browser cache. Launch the Maqetta server. Login if necessary. In some cases, you'll want to setup a virgin user environment by creating a whole new user login.
Click on the "New file" icon on the main toolbar. Choose any filename.
Drag a Button onto the canvas. Set the text on the Button to "Show Dialog"
Drag a Tooltip on to the Button. The Toolbar will be associated with the Button. Put text in the tooltip like "click here to show the dialog"

I get internal error msge box

**Comment by peller** [comment]
possible dup of #1398

**Comment by peller** [comment]
don't know what the underlying exception was, but this no longer occurs
