### ISSUE TITLE
New Project not working

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1696]
(Maybe this is due to AMD'ing the plugins?)

@peller, @jhpedemonte

When I issued a New Project command, and clicked OK in the dialog, nothing happens and the following appears in console:

```
Uncaught TypeError: Object #<Object> has no method 'loadProject'
```

**Comment by peller** [comment]
could be related to 84704239a84dcc3862bbc8937b1a55671ca81f67  I see a couple of references to `Runtime.loadProject` that need to be updated.
