### ISSUE TITLE
More spriting

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#170]
The Net panel in Firebug shows that there are still a bunch of unsprited
images.

**Comment by JonFerraiolo** [comment]
-> @peller M7 Prio-Low. Leaving at M7 just in case @peller has a few cycles to investigate and see whether we have any remaining unsprited images.

**Comment by peller** [comment]
with @JonFerraiolo's UI work, it looks like everything is sprited except metadata icons (presently inlined in the metadata with data: urls) and various dijit/dojox icons
