### ISSUE TITLE
Need to shuffle stores when reparenting data-bound widgets

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1701]
@aerwin 

WIth latest code, I had a flowable document with the following: Button, DataGrid, Calendar, and then selected the DataGrid and interactively dragged it to the end of the doc (i.e., after the Calendar). Looking at browser debugger showing the DOM tree of the user HTML document, I see things in this order: Button, ItemFileReadStore, Calendar, DataGrid (plus a mysterious iframe).

Are we properly moving the store objects when moving the data-bound widgets? I couldn't find any logic in the code for such re-ordering.

**Comment by billreed63** [comment]
We have code in DataGridHelper.js that insure that the store is declared in the html before the DataGrid. This is handled for re-parent and create. The MoveCommand just changes the style attribute so Store DataGrid order does not change. The ModifyCommand removes the old widget and creates a new widget so the DataGridHelper.create is called to fix the Store.

**Comment by JonFerraiolo** [comment]
But it appears that ModifyCommand isn't deleting the old datastore widgets so if you go through ModifyCommand you end up with both the old datastores and the new datastores, and these multiple stores are persisted within user's HTML files.

**Comment by billreed63** [comment]
I can't reproduce this, I tried a HTML page wit flow layout
1) DND Button
2) DND DataGrid
3) DND Calendar
4) Select the DataGrid in page designer and drag to following the Calendar widget ans release..

My outline tree now has..

Button
ItemFileReadStore
Calendar
DataGrid
<iframe>   

I see only one store...

**Comment by JonFerraiolo** [comment]
I guess this one can be closed, but from a user perspective,wouldn't it be better if the DIV associated with the store were always just before the DIV associated with the DataGrid? Otherwise, there might be an ItemFileReadStore far away from the DataGrid and the user might be more tempted to delete the ItemFileReadStore, and even if they don't succumb to temptation, when they hand off to a developer, it will be a lot clearer to the developer what's going on if the ItemFileReadStore is next to the DataGrid.

Also, #1700 might require more complete cleanup each time a DataGrid is modified to ensure that we delete unused and move any associated stores.

**Comment by jhpedemonte** [comment]
There's 2 commits references here, but I'm wondering if the first isn't for #1700?  @billreed63?

**Comment by billreed63** [comment]
Yes, I got the wrong issue number and did not notice until after I pushed upstream. So I tried to modify my last commit but git created a second commit... Can we delete the 95beaft commit, or at least change the text?

**Comment by jhpedemonte** [comment]
**Reviewer:** Only review e3426554f5eb220caedd960f58e438e53812f5f1 (ignore 95beafcb9a4aaef97896dc0df8a07aa3c2ea076e).

Deleting a commit after it's been pushed can lead to bad things.  I'll see if I can change the text.
