### ISSUE TITLE
Properties Palette -- values typed in combo boxes aren't committed

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1706]
1. New HTML file
2. Add button to an HTML file
3. Select button and go to Font Properties
4. Type "60px" (or any value) in size combo box
5. Change focus and note value is _not_ applied

However, if I choose value directly from the drop down (or click the +/- buttons next to the drop down) the sizing _is_ applied.

Similar behavior seems to occur with the font-family property.

**Comment by JonFerraiolo** [comment]
@childsb

**Comment by JonFerraiolo** [comment]
@aerwin - what gesture did you use to change focus? I'm having trouble reproducing.

**Comment by aerwin** [comment]
@JonFerraiolo I was just tabbing out of the field. But, I'm not able to reproduce tonight. Strange... I must have somehow gotten my workspace into a bad state yesterday. I'll close this for now and keep my eyes open for it happening again.
