### ISSUE TITLE
Remove console.warn at DataGridHelper.js:189?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1712]
Re

**Comment by aerwin** [comment]
--> no milestone to M7

**Comment by billreed63** [comment]
closing DataGrid is being deprecated, user GridX

**Comment by aerwin** [comment]
--> @aerwin

Reopening... DataGridHelper is still used.

**Comment by aerwin** [comment]
I no longer see that console.warn statement, so closing.
