### ISSUE TITLE
error when switching states in theme editor

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1714]
no observable effects of this exception; state change appears to work

`if(!((9 == root.nodeType) || nospace)){ throw ""; }`

_queryFuncCacheQSA.(anonymous function)() at dojo/selector/acme:1182
query() at dojo/selector/acme:1454
query() at dojo/query:656
declare._updateStyle() at davinci/ve/themeEditor/metadata/CSSThemeProvider:258
declare.removeWidgetStyleValues() at davinci/ve/themeEditor/metadata/CSSThemeProvider:293
declare.execute() at davinci/ve/themeEditor/commands/StateChangeCommand:31
declare.execute() at davinci/commands/CommandStack:26
declare._widgetStateChanged() at davinci/ve/themeEditor/ThemeEditor:89
hitch() at dojo/_base/lang:153
target.(anonymous function)() at dojo/aspect:181
on.emit() at dojo/on:261
on.emit() at dojo/on:297
Evented.emit() at dojo/Evented:28
define.publish() at dojo/topic:21
connect.publish() at dojo/_base/connect:193
declare.publish() at davinci/workbench/ViewPart:33
declare._createStateList() at davinci/ve/views/StatesView:202
hitch() at dojo/_base/lang:155
target.(anonymous function)() at dojo/aspect:181
hitch() at dojo/_base/lang:153
target.(anonymous function)() at dojo/aspect:181
declare.addToSelection() at dojox/grid/Selection:148
declare.addToSelection() at dojox/grid/DataSelection:53
declare.select() at dojox/grid/Selection:123
declare.clickSelect() at dojox/grid/Selection:239
declare.clickSelectEvent() at dojox/grid/Selection:257
declare.onRowClick() at dojox/grid/_Events:303
declare.onCellClick() at dojox/grid/_Events:256
declare.doclick() at dojox/grid/_Grid:1209
declare._dispatch() at dojox/grid/_Grid:1186
declare.dispatchContentEvent() at dojox/grid/_Grid:1196
declare.onContentEvent() at dojox/grid/_Events:27
declare.doContentEvent() at dojox/grid/_View:738
hitch() at dojo/_base/lang:153

**Comment by peller** [comment]
hmm... this exception is probably ok.  It was another exception I was actually seeing in ViewPart, but I can't reproduce that right now.

**Comment by peller** [comment]
aha, I see it now.  Still not sure exactly how to make this happen  Seems to happen if I click around on states with a widget like Calendar selected, then click off the calendar and keep switching states

widget is null: `if (widget.id === 'all' && state != 'Normal'){`

```

declare.isStateValid() at davinci/ve/themeEditor/metadata/CSSThemeProvider:525
declare._updateSubwidgetListForState() at davinci/ve/Focus:780
declare._updateSubwidgetListForState() at davinci/ve/Focus:774
hitch() at dojo/_base/lang:155
target.(anonymous function)() at dojo/aspect:181
on.emit() at dojo/on:261
on.emit() at dojo/on:297
Evented.emit() at dojo/Evented:28
define.publish() at dojo/topic:21
connect.publish() at dojo/_base/connect:193
declare.publish() at davinci/workbench/ViewPart:33
declare._createStateList() at davinci/ve/views/StatesView:202
hitch() at dojo/_base/lang:155
target.(anonymous function)() at dojo/aspect:181
hitch() at dojo/_base/lang:153
target.(anonymous function)() at dojo/aspect:181
declare.addToSelection() at dojox/grid/Selection:148
declare.addToSelection() at dojox/grid/DataSelection:53
declare.select() at dojox/grid/Selection:123
declare.clickSelect() at dojox/grid/Selection:239
declare.clickSelectEvent() at dojox/grid/Selection:257
declare.onRowClick() at dojox/grid/_Events:303
declare.onCellClick() at dojox/grid/_Events:256
declare.doclick() at dojox/grid/_Grid:1209
declare._dispatch() at dojox/grid/_Grid:1186
declare.dispatchContentEvent() at dojox/grid/_Grid:1196
declare.onContentEvent() at dojox/grid/_Events:27
declare.doContentEvent() at dojox/grid/_View:738
hitch() at dojo/_base/lang:153
```

**Comment by aerwin** [comment]
--> no milestone to M7

**Comment by billreed63** [comment]
seems to have been fixed
