### ISSUE TITLE
make sure gzip is enabled

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1730]
@waynevicknair 

I see gzip in the response headers when running locally in Eclipse, but I do not see it on our lab test machine or on maqetta.org

**Comment by jhpedemonte** [comment]
Odd. We used to have it.

Actually, I don't see it locally or on maqetta.org.  The response headers should have `Content-Encoding:gzip`.

**Comment by waynevicknair** [comment]
Brad would you please look at this? You implemented gzip originally.

**Comment by childsb** [comment]
Fixed with commit b64ad90e08118a47904c4471d4c7734dbc721194

**Comment by peller** [comment]
Unfortunately, I'm still not seeing gzip content on lab9

**Comment by childsb** [comment]
working on lab9 after maqetta was redeployed.
