### ISSUE TITLE
No cache busting URL build parameter on packages.json and widgets.json

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1734]
@jhpedemonte , @waynevicknair, @childsb 

I had this mysterious problem when trying to run today's build from maqetta.org using http://localhost:50000 - the helper JavaScript files weren't coming down correctly. When I chatted with @peller, he did not have this same problem when running off of a server (:50010) and then I tried same thing and also did not have the problem. Then I cleared my browser cache and voila things worked for me.

This caused me to look at the network panel in the debugger. Turns out we aren't putting the build# as a url param to packages.json and widgets.json. That mean we don't have cache busting working on those files. Seems like we want to have cache busting on everything - otherwise, what's the point of putting cache busting on everything else?

**Comment by peller** [comment]
So those urls are "versioned" in the URL, but we made changes to existing versions.  I suppose that wouldn't normally happen, but we ought to allow for the possibility that these files need to be patched, I suppose.  @jhpedemonte, do you think cache-busting is the right thing to do here?  Are there other json/data files like this anywhere?

**Comment by jhpedemonte** [comment]
Well, as you stated, they should be versioned according to the library to which they belong (i.e. for Dojo, use version "1.7.1" in the URL), not the build version.  I think in this case, we'll just have to be on the look out and every so often will need to clear cache while editing files in the libraries.

**Comment by JonFerraiolo** [comment]
I disagree. Sure, the files in davinci.dojo_1_7/WebContent/dojo should be versioned according to the library they belong (e.g., "1.7.1"), but all of the other files in the project are Maqetta files that are subject to considerable change even when the Dojo version stays static and should be handled from a cache-busting perspective just like the files in davinci.maqetta-core-client/WebContent.

**Comment by jhpedemonte** [comment]
And I disagree with that. Right now, there is indeed some flux with those files, but looking into the future, the changes in library metadata/code will be more dependent on the library than on Maqetta.  Also, if library metadata/code is changed due to changes in Maqetta itself, then maybe we could update the version of the library ("1.7.1" -> "1.7.1.1").

I just don't think using the build number has anything to do with the libraries themselves (in the long run).

**Comment by JonFerraiolo** [comment]
But until the long run happens, we will have things break for users. Things need to work one way or another, without telling users that 99% of the files use cache busting, but you still need to clear your browser cache because of the 1% we didn't do.

**Comment by peller** [comment]
our short term workaround could then be to change the version number whenever an incompatible change is made, even if the version didn't change.  e.g. dojo/1.7/package.json could become dojo/1.7d1/package.json (Ok, how many other things would that impact?)

We typically shouldn't have to change metadata to support patch releases like Dojo 1.7.1, but the scheme certainly makes that possible.

**Comment by peller** [comment]
@jhpedemonte, supposing we did use the cache-busting hammer, what's the down-side?  I'll also point out that cache busting won't safe us until the _next_ release.  They only way we're going to avoid this issue for M5 is renaming the directory or instructing users to clear the cache.

**Comment by jhpedemonte** [comment]
> dojo/1.7d1/package.json

Yes, this works for me.  Makes more sense than using the Maqetta build id for a widget library.

**Comment by JonFerraiolo** [comment]
I continue to disagree. I would rather put cache busting on the entire dojo library (thereby preventing caching) than put a burden on us to remember to change the folder name with each release. We'll forget. Reliability trumps performance. 

Ideally, I'd like to put cache busting on all libraries but add an exclusion option that our server supports where we do cache busting on everything EXCEPT on particular folders (e.g., cache bust everything in davinci/dojo_1_7 except davinci.dojo_1_7/WebContent/dojo).

**Comment by peller** [comment]
We shouldn't be doing this each release, only when an incompatible change is introduced to an existing library, which should be the exception.  We have to rename the directory this release either way.

**Comment by JonFerraiolo** [comment]
Sorry, I'm not giving up. I don't think it's that big of a deal if we cache-bust Dojo with each release. So what if users have to wait for Dojo to come down again once every two months (our normal release cycle)? I think it will be the rule, not the exception, that for each release we will be making changes within the library files such as callback.js, or the theme CSS files, or the helper JS files, and we need to cache-bust those files one way or another, either by doing the manual (and error-prone) process of renaming a folder, or by doing the automatic process of leveraging the cache-busting logic we already use in other parts of the product. I really fear that we will overlook the requirement to rename the folder because we didn't realize someone made a change to one of the files inside the library and we will have a bad release where things crash for users (without them having cleared their cache).

**Comment by JonFerraiolo** [comment]
I hit this problem again today. Here is another rant.

```
So, I downloaded the nightly from maqetta.org, ran the single-user launch script, typed http://localhost:50000/maqetta into the URL bar on chrome, did New HTML File, added a TabContainer and a ComboBox, and here is console: 
8:18:39 AM: jferrai@us.ibm.com - Jon Ferraiolo/Menlo Park/IBM: 2event.layerX and event.layerY are broken and deprecated in WebKit. They will be removed from the engine in the near future.
http://localhost:50000/maqetta/app/dojo/davinci.libraries.dojo.dijit.layout.TabContainerHelper.js?52ed7bcac1e81ebabae409fa5985d0a8800960c6Failed to load resource: the server responded with a status of 404 (ProxyServlet: /maqetta/app/dojo/davinci.libraries.dojo.dijit.layout.TabContainerHelper.js)
... other similar errors ...

8:19:16 AM: apeller: sounds like the cache problem you hit earlier 
8:19:53 AM: apelle: it's not picking up Javier's changes to the metadata 
8:20:18 AM: apeller: try it on a different browser, maybe? 
8:20:29 AM: jferrai: I'm checking network panel... 
8:22:29 AM: jferrai: ah, yes, the problem is that I had been running Preview4 on the same port, and it's using the cached version of package.json from Preview4 
8:25:59 AM: jferrai: which points to a cached version of widgets.json 
8:26:16 AM: jferrai: which has old/erroneous info in it 
```

I'm adamant about this need to cache bust. An important aspect of our testing process is that we should be running new builds without having to clear cache to make sure we don't have any cache-busting bugs and oversights. By sticking to religion on not cache-busting the library files, that forces everyone of us to have to clear cache to successfully run daily builds, which precludes us finding cache-busting problems during our day-to-day testing.

**Comment by jhpedemonte** [comment]
Just want to make a correction and better explain what I was saying.

>  I would rather put cache busting on the entire dojo library (thereby preventing caching) than put a burden on us to remember to change the folder name with each release.

There's no folder name that has to be changed.  **package.json** (and other library files) have a URL like this: _http://localhost:8081/maqetta/app/metadata/jquery-ui/1.8.11/package.json_.  The version number there comes from the version string in the plugin.xml file.  This is what we should be using to "cache bust".

But I understand what you are saying, that most of us will not remember to update that version string when we make changes.  So here's my proposal:

Add the build number as part of the version string for the URLs:  _http://localhost:8081/maqetta/app/metadata/&lt;library name>/&lt;version>.d&lt;build number>/package.json_. (The 'd' stands for 'development'!!!)  This way, we won't run into these issues during development.

Then, when creating the "production" builds, we build with a `--production` switch that removes the `.d<build number>` from the URL.  We'll need to make sure that the actual library version strings are updated if there have been updates since the last release.

Yes, I know, I'm being pedantic here, but I don't see the point of having 2 different version strings in the URL...

**Comment by peller** [comment]
I prefer using two methods, one that is logically sound, and the other would just be a safety net.  Perhaps after things settle down, we can just remove the safety net.  Build steps introduce a whole other can of worms.

**Comment by peller** [comment]
I think I was confusing cache headers with cache busting.  Renaming the path is not required if we do the cache busting workaround, so this is fixed.
