### ISSUE TITLE
Download entire workspace fails

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1737]
When I try to download entire workspace, after I hit OK I get redirected to a blank page and nothing gets downloaded.

There are no JS errors in Chrome console or server errors in server console.

Environment: Chrome, locally installed on windows ("internal" w3ibm build)

**Comment by JonFerraiolo** [comment]
Could your session have timed out? I had a problem with ZIP download failing but when I logged out and logged in, the download worked. I'm suspicious that there might be some actions like download that don't recover properly if invoked when session has timed out.

**Comment by aerwin** [comment]
No... unless session times out in a matter of seconds.

**Comment by childsb** [comment]
i can't reproduce this on master.  tony will you try to reproduce again and reopen if you can?

**Comment by aerwin** [comment]
This appears to be now un-reproducible now. So, agree with closing.
