### ISSUE TITLE
Sample1.html doesn't render after modifying Dojo library location

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1738]
1. Click Modify Libraries button
2. Change Dojo location to `mylocation/lib/dojo`
3. Click ok and see library moved in workspace
4. Open Sample1.html and nothing renders (looking at source it doesn't seem path changed to new location)

Environment: Chrome with local windows install ("internal" w3ibm build)

**Comment by JonFerraiolo** [comment]
I was able to reproduce this problem with Mac/Chrome

**Comment by peller** [comment]
may be related to #1739?

**Comment by peller** [comment]
@childsb, I traced through this and I'm not seeing any connection to the changes I made to metadata.init and getMetaRoot.  It seems that if you use modify libraries and open a new file, everything is fine, but if you try to open an existing file, it reads the dojoUrl right out of the HTML.  Is there code that is supposed to override this?
