### ISSUE TITLE
Modify Libraries doesn't work in some cases with Eclipse projects

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1739]
@aerwin 
- New Eclipse project (e.g., "eproj1")
- Click on Modify Libraries icon. Change path to dojo from "WebContent/lib/dojo" to "WebContent/myloc/lib/dojo". Click OK

Result=> Dojo hasn't moved

**Comment by peller** [comment]
@childsb, I see this without using eclipse libraries also.  Upon refresh, everything is ok. Seems unrelated to #1738

**Comment by peller** [comment]
@JonFerraiolo I think there were two bugs.  Now it's just that the Files view doesn't seem to get a resourceChanged event to refresh, but everything works otherwise?

**Comment by childsb** [comment]
Jon's scenario is working for me.  Is there another bug here I'm missing?
