### ISSUE TITLE
Delete View, then Undo => multiple Views are visible

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1744]
- New HTML File (iphone)
- Add View, Heading, View, Heading
- Select second view
- Delete using context menu in Outline palette
- Click on Undo button in editor toolbar

Result=> Two Views have their eyeballs turned on

**Comment by jhpedemonte** [comment]
-> M6

**Comment by jhpedemonte** [comment]
-> M7 / @doronrosenberg

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo M6 Prio-Med - this might be a quick and safe thing to fix. There is a single "refresh States palette" routine that gets called in response to several different events. We just might need to add a dojo.publish() in the right place.

**Comment by JonFerraiolo** [comment]
This seems to be fixed now. Closing.
