### ISSUE TITLE
Should be able to multi-select widgets in Outline palette

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1745]
Right now, you can multi-select on canvas, but not on Outline View. If you Ctl-click on Outline palette, the outline palette seems to show multiple widgets selected, but in actuality only one widget is selected.
- New HTML File
- Add 3 Buttons
- With 3rd button selected, in Outline palette, Ctrl-click (or Cmd-click) on second widget in Outline palette

Result=> 2nd and 3rd button appear to be selected in outline palette, but on canvas there is only a selection on the 3rd Button

**Comment by peller** [comment]
-> M7

**Comment by JonFerraiolo** [comment]
Dupe of #2498, closing
