### ISSUE TITLE
onFirstAdd not called when opening existing files

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1747]
Set Priorit-High because I might need this to get mobile views working in review/commenting, but if not, then maybe not Priority-High.

onFirstAdd is only invoked by CreateTool. If you create an HTML file with a widget from a particular library that uses onFirstAdd, save the file leaving the editor open, then do a browser refresh, the onFirstAdd method isn't called even though the HTML file that appears upon refreshing Maqetta includes a widget from the given library.

Note that right now only maqetta.shapes has an onFirstAdd method within callbacks.js.

**Comment by peller** [comment]
could I have broken this with the async metadata loading?  the callback load is still synchronous and should block the deferred

**Comment by jhpedemonte** [comment]
No, Adam, as Jon states, this is only called in CreateTool.  It's not called when parsing an existing page.

**Comment by jhpedemonte** [comment]
@JonFerraiolo, is this still Priority High?  Did you not work through your issue using **onDocInit**?

I'm not pleased with the current callbacks that we have and would like to redo them.  But probably not for M5.

**Comment by JonFerraiolo** [comment]
Yeah, this isn't needed for M5 anymore. As far as I know, we are only using onDocInit now.

**Comment by jhpedemonte** [comment]
Closing, since we're also using `onDocInit`.  All of this will eventually need to be cleaned up and standardized.
