### ISSUE TITLE
Remove eval use in Review ExchangeTool

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1749]
See #620

davinci.review.drawing.tools.ExchangeTool.exportShapesByAttribute constructs a JSON string which is later eval'd by import shapes.  If there's a reason to serialize this out as a string, let's use "proper" JSON with quoted names, etc., and replace the eval with an ES5 JSON.parse.  Otherwise, perhaps we could avoid the JSON altogether and just construct the object directly?

**Comment by JonFerraiolo** [comment]
-> @aerwin M7 Prio-Med

**Comment by aerwin** [comment]
@JonFerraiolo @jhpedemonte 

--> M8

**Comment by billreed63** [comment]
code no longer exsists
