### ISSUE TITLE
Main menu test: cloned theme has wrong content on first view

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1752]
Browser: Chrome for Mac
Commit: 4babff0976d6ee1b5e77160322505618e99d7a5e
Running in Eclipse / local install

testing New Menu: New Theme... chose the claro theme and call new theme "mytheme1". theme editor opens on clone, but styling is incorrect. for example, background color is grey instead of light blue.

**Comment by JonFerraiolo** [comment]
Could it be that the style sheets for the theme aren't loading and you are just seeing what Dojo widgets look like if the theme CSS files are missing?

**Comment by peller** [comment]
works for me

**Comment by JonFerraiolo** [comment]
Adding on to my comment from above, I'm pretty sure there is a long-standing intermittent bug where the theme editor sometimes comes up without the theme CSS files, and I'm wondering if that's what @waynevicknair is seeing.

**Comment by waynevicknair** [comment]
considering that the theme appears correctly on second viewing (i.e. close theme editor, navigate to theme file, double click to open cloned theme in theme editor) i'd agree with @JonFerraiolo.

**Comment by billreed63** [comment]
Yes, that is the bug @waynevicknair

**Comment by billreed63** [comment]
I think I have fixed this with #1461
