### ISSUE TITLE
Properties Test 2: DIV's "text" widget-specific property does not appear

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1753]
Browser: Chrome for Mac
Commit:  4babff0976d6ee1b5e77160322505618e99d7a5e
Running: Eclipse / local install

box-shadow test - drop DIV onto canvas. look for widget-specific property "text". property palette lists no widget specific properties for DIV. 

workaround: if you double-click on the DIV you get smart input which allows you to set necessary text per test instructions.

**Comment by JonFerraiolo** [comment]
In short-term, this is just an error in test plan. Longer-term, we do want to have a text property for DIV, but for expediency we decided to leave it off for now and only provide SmartInput.

**Comment by JonFerraiolo** [comment]
-> M7 Med

**Comment by JonFerraiolo** [comment]
Test plan got fixed somewhere along the way. Closing.
