### ISSUE TITLE
Sliders broken after bb4a311b279aab01792f1e03a679e30796690671

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1754]
@jhpedemonte 

Looks like sliders broken after refectoring done in bb4a311b279aab01792f1e03a679e30796690671. Basically, `HorizontalSliderHelper`'s definition is missing:

``` javascript
return HorizontalSliderHelper;
```

**Comment by jhpedemonte** [comment]
How embarrassing!  Good catch.
