### ISSUE TITLE
Remove 'url' property until we have a good solution for snippets

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1756]
@peller 

Until we provide reasonable authoring support for 'url' property, shouldn't we remove 'url' from list of properties for mobile widgets? I don't see how a user could easily make use of that property given the features that Maqetta supports today. It seems like all that a user can use with reasonable convenience is 'moveTo' (for Views that are part of current document) or 'href' (to jump to a different HTML page).

**Comment by jhpedemonte** [comment]
What about leaving it for more experienced users?

**Comment by JonFerraiolo** [comment]
I figure advanced users can type url= into the source pane. 

In general, my thinking is that in general less-is-more when it comes to widget-specific properties. It has a negative effect if we populate that panel with a bunch of seldom-used or partially-working options because it makes it more difficult for users to find the things they are more likely to use.

**Comment by jhpedemonte** [comment]
Handling of the 'url' prop is #1053.
