### ISSUE TITLE
States.js - Uncaught TypeError: Object #<Object> has no method 'subscribe' 

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1759]
load maqetta app. see this message in browser console:

> Uncaught TypeError: Object #<Object> has no method 'subscribe'

in States.js line 448

**Comment by JonFerraiolo** [comment]
When you see this, are you running a build or running from Eclipse?

**Comment by peller** [comment]
I think this happens on Eclipse and is a timing issue with async turned on.  Something to do with how dojo _base was broken up in 1.7.

**Comment by peller** [comment]
I'd like to just put in the necessary require() for the subscribe method, but we've still got that strange davinci.dojo stuff going on.  See #1337

**Comment by JonFerraiolo** [comment]
Sounds like a reasonable short-term fix.
