### ISSUE TITLE
Can't put clipart on top of Heading

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1762]
(This is the same bug as #1321, but I had to revert that commit in order to fix #1552.)

Can't put clipart on top of Heading using absolute positioning.  Probably affects other widgets as well.

---

Setting a `z-index` on Heading isn't the correct answer (see #1552).  However, it might work if we add it to the widget being added (clipart in this case).

But we should be smart about it (if possible), and only add it if necessary.  Is there a programmatic way to determine if a widget is above/below another?

**Comment by JonFerraiolo** [comment]
Changing to High just so this gets investigated, then maybe lower priority depending on what we find.

**Comment by JonFerraiolo** [comment]
Dojo Mobile uses z-index all over the place. Views and Headings have z-index of 1. Overlay mobile widgets are at z-index:2000. 

Right now I am thinking that we assign a high z-index value for all new absolutely positioned widgets.
