### ISSUE TITLE
Error when setting value for MenuBar

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1765]
On a Dijit MenuBar, when setting a value through smart input, there is an error in **MenuBarInput.js**: `popupMenuBarItem.children` is null.

@peller @JonFerraiolo

**Comment by jhpedemonte** [comment]
In _Preview 4_, the initial MenuBar data was:

```
Menu 1
> Menu Item 1.1
> Menu Item 1.2
Menu 2
> Menu Item 2.1
```

But in the latest code, it comes up as:

```
Menu 1
Menu 2
```

**Comment by billreed63** [comment]
working with latest code updates
