### ISSUE TITLE
Placeholder: detailed fixes Maqetta->Eclipse workflow

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1767]
This is a placeholder bug. We need to do a detailed assessment of the Maqetta->Eclipse workflow and fix critical bugs we find. There will probably be a series of other bugs after doing the assessment.

**Comment by JonFerraiolo** [comment]
Reassigning to @aerwin

**Comment by aerwin** [comment]
@JonFerraiolo 

Is this a dup of #1548?

**Comment by JonFerraiolo** [comment]
closing as dupe
