### ISSUE TITLE
Copy/paste of Dijit Tree fails w/ error

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1768]
Copy/paste of Dijit **Tree** fails, with error in **TreeCreateTool.js**.

There is a **Deferred** in the call stack.

@peller

**Comment by peller** [comment]
additional helpers are requested which weren't in the _preProcess, in this case ItemDataReadStore. The helpers for new widgets (via Create or Paste Tools) as well as any helpers those tools require must be loaded asynchronously before they're needed.
