### ISSUE TITLE
ViewHelper not loading

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1771]
@jhpedemonte , @peller 

ORIGINAL REPORT:

With Preview 4, if you add a View and then drop a second View into the first View, the second View becomes a sibling of the first View, but with latest code, it becomes a child. 

In Preview 4, I had some helper logic to cause subsequent Views to become siblings. I'll guess that helper logic was broken recently.

AFTER INVESTIGATING FURTHER:

I think we have faulty helper loading logic after various changes having to do with Deferred. If you follow these steps:
- New HTML File (iphone)
- Add a View

the ViewHelper.js is not loaded. This is because the first call to `_Widget.js:getHelper()` is coming out of the dragMoveUpdate logic (used by snapping and ChooseParent), which then calls `widget.js:getWidgetHelper()`. This routine never calls `requireWidgetHelper()` (next function below) and instead looks at `helperCache[type]` which has no value, which bubbles back to `_Widget.js:getHelper()`, which sets the _edit_helper to true, preventing further attempts to pull in the helper.

**Comment by peller** [comment]
where can I find that code?

**Comment by JonFerraiolo** [comment]
Changed bug title and description and assigned to @peller because I investigated and it's a helper loading problem.

**Comment by peller** [comment]
see #1768

**Comment by peller** [comment]
fixed by 6e1bdff810a75429e1cac1e7b3425b746997a38b
