### ISSUE TITLE
Can't successfully reopen HTML files after changing mobile theme

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1772]
- New mobile theme (clone custom to custom1)
- New HTML File (iphone)
- Add a View, Heading, RoundRectList
- Switch theme to custom1
- Save, close, reopen

Result=> Looks like theme files aren't working - just see the text, no widgets

**Comment by billreed63** [comment]
KI have not been able to reproduce this on win/chrome, if you still are seeing this problem reopem
