### ISSUE TITLE
Can't drag out size of Rectangle, resize handles missing

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1773]
@peller 

With Preview 4, I could click on the Rectangle widget, then drag out a rectangle on the canvas, and that's how big the Rectangle would be. Not working now. If you drag out the size for the rectangle, you just end up with a square of the default size.

Also, you can't resize the Rectangle because no knobs are showing on the selected widget.

**Comment by aerwin** [comment]
--> no milestone to M7

**Comment by JonFerraiolo** [comment]
I think this has been fixed for a long time. Closing.
