### ISSUE TITLE
DataGrid and Tree problems

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1774]
I pulled latest code and tried out DataGrid and Tree.
- DataGrid brings up SmartInput, but upon clicking OK, nothing appears on canvas
- Tree works OK, but if I copy the Tree and then paste, a second Tree does not appear on the canvas

**Comment by peller** [comment]
Tree copy/paste problem is duplicate of #1768

**Comment by JonFerraiolo** [comment]
@peller might be related to #1771

**Comment by peller** [comment]
There's an exception deep in the construction of the DataGrid, as triggered by the ModifyCommand in DataGridInput.  Apparently this.store is a string, not an object (e.g. "ItemFileReadStore_1")

Uncaught TypeError: Object ItemFileReadStore_1 has no method 'getFeatures'

@billreed63, at which point should the string in the markup (store=) get converted to a data store object?
