### ISSUE TITLE
States not showing for Sample1.html

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1775]
Somehow commit 11a9984a00 broke something so that the States palette doesn't show the states for Sample1.html

**Comment by peller** [comment]
I notice that if I do something that causes it to refresh, like add another state, the other states appear.  The async loading must cause the states to get initialized after the view loads, and I guess there's no event-based mechanism to keep them in sync?

**Comment by JonFerraiolo** [comment]
Yeah, it must not be solidly coded. There is an ordering difference now where the StatesView is updating its list of states before the list of states are available. Note that you can also get the proper states list by simply switching to a different editor and then switching back to Sample1.html.

Reassigning to me. I'm hopeful I can fix this without too much effort. (Fingers crossed.)
