### ISSUE TITLE
AMD with version.js - can't be right

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1777]
Maybe I don't understand things, but the use of version.js can't be right. First off, we don't have a require() for it in pagedesigner.html. Secondly, the contents of version.js are just this right now, which causes me to scratch my head:

```
define("Preview 4");
```

Maybe we just need to add a dependency to pagedesigner.html.

**Comment by peller** [comment]
It's picked up through davinci.js, which lists version.js as a dependency.  There are no dependencies, and no need for a closure.  The value of the module is just the string.

**Comment by JonFerraiolo** [comment]
Reopening. I think you misunderstood. You see, in pagedesigner.html, davinci.version has no value, so we get "undefined" in the banner instead of "Preview 4" or whatever. That's because davinci.version never gets a value, even after the application is fully initialized.

I did some trial change to version.js to have the following content, and with this change, davinci.version has a value and the version number appears in the banner:

```
define([
], function() {
    dojo.getObject("davinci", true); // Make sure [window.]davinci exists
    return davinci.version = "Preview 5";
});
```

But I'm not sure if this is the best way to code it up so I didn't check it in.
