### ISSUE TITLE
Delete folder with files, then add folder of same name => old children still there

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1780]
- Create a new folder (eg folder1)
- Upload a couple of files into that folder
- Delete the new folder
- Create a new folder with same name

Result=> Old children files appear to be there still. However, if you refresh your browser, the children disappear.

I wouldn't be surprised if this were a dupe, but I couldn't find a bug that exactly matched this one.

**Comment by childsb** [comment]
dijit tree was holding onto the folder object.  needed to call onChildrenChange(parent,[]) to delete the children before deleting the resource.
