### ISSUE TITLE
publishing a review causes error

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1783]
((probably already aware, please close if this is a dupe))

1) New Review
2) add files/reviewers/etc
3) click "publish"

note the error:

Problem connecting to the Maqetta Server...
Return to Maqetta Login

Error description:

Error to publish review session , response=Error: Unable to load http://lab9.austin.ibm.com:50020/maqetta/cmd/publish status:500, reason=Error 500 INTERNAL_SERVER_ERROR

**Comment by waynevicknair** [comment]
cannot reproduce on commit a0708e74bbb9edb7d98f17d2fe2910e4d3030b92. please re-open if issue recurs.
