### ISSUE TITLE
background image no "remove value"

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1785]
((per test scenario, properties palette #5))

1) create a new HTML file
2) add a DIV
3) Select DIV, go to background--->background image and click the "..." to bring up dialog
4) select sample.jpg image and click ok
5) select the div with the background image. go to background--->background image, and click the drop down.  notice no "Remove value" (as stated in test scenario).

**Comment by JonFerraiolo** [comment]
Menu values are defined by Background.js:89, built simply from 'values' for the given property defined in big property table at top of SwitchingStyleView.js:91.
