### ISSUE TITLE
rename failed for themesets

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1789]
got this when I hit 'rename' on Safari

`Error: Tried to register widget with id==rename but that id is already registered`

also noticed that the text box uses the editable UI but is read-only.  The UI suggests that I should be able to type directly in the textbox and then hit rename.  Perhaps it should be possible to edit the name in place without either a button or a dialog?

**Comment by billreed63** [comment]
The use of the text box read-only is Jon's UI design choice.

**Comment by peller** [comment]
@JonFerraiolo let's reconsider -- I think the UI could be much slicker if we just had an editable text field.  It would be less code, and more in line with the rest of our UI.  And, it might make this bug go away :)
