### ISSUE TITLE
Properties 2, Step 7: Text box width cannot be set via Properties palette

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1790]
Step 7 in the Properties 2 test case says:

> Select the TextBox. There should be only horizontal resize handles. Try to change the Width property on the Properties palette. It should work.

However, when I try to change to the width property I get a dialog stating that it cannot be changed.

**Comment by aerwin** [comment]
Note: I am able to follow the CSS overrides cascade and change the width that way though.

**Comment by JonFerraiolo** [comment]
@billreed63, @childsb

**Comment by billreed63** [comment]
This works for me, was this local or lab9

**Comment by aerwin** [comment]
Chrome, lab9

**Comment by billreed63** [comment]
works on build cd61e9cf19a6d4dca924c6bbbb119a0512110cdd

**Comment by aerwin** [comment]
Confirmed.
