### ISSUE TITLE
themesets: device-specific settings aren't sticking

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1791]
running the themesets tests, I tried setting the individual device themes (Android, blackberry, etc.) and upon closing and reopening the themesets dialog, the changes are gone and everything goes back to "custom2"

**Comment by peller** [comment]
(on safari)

**Comment by JonFerraiolo** [comment]
Yeah, I noticed this, too, and wondered if there were a better approach. Might be an artifact of how it is implemented and fixing the UI might be more difficult than you would think.

**Comment by peller** [comment]
perhaps, though I'll reiterate my view that dialogs are evil and read-only text fields which don't have a read-only UI are bound to frustrate users. [nm... I think I was confusing this with the dialog / rename bug?]

**Comment by billreed63** [comment]
I can't reproduce this issue, what are the steps:

Is this in theme sets or setting the device theme?

Theme sets are not saved unless the ok button is selected, the user can walk through all the theme set changing them but if they do not select ok they will no be saved.

Switching theme's the themes are retrieved from the HTML page, if the user changes a theme and then exits the page without saving the theme will revert.

**Comment by peller** [comment]
this was in the themesets dialog, after hitting 'ok' to save, the theme sets dialog would come back up with the old settings, however using the theme switcher, I saw the correct themes.

**Comment by billreed63** [comment]
I can't reproduce this, I may have fixed this issue with #1787
