### ISSUE TITLE
Properties 2, Step 10: Can't change position of calendar to absolute

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1792]
When performing Step 10 in the first test case in Properties 2, I get the dialog saying I can't because of a read-only theme. But, the instructions don't indicate that should be an issue.

> Select the Calendar. Change the Position property to "absolute". Try to move the widget on the canvas. It should now move. Change the left and top properties on the Properties palette.

Note: I am able to follow the CSS overrides cascade and change the position though.

**Comment by JonFerraiolo** [comment]
@billreed63, @childsb

**Comment by billreed63** [comment]
Seems to be working now 0447cfd2af9ee56d553906ef3fc5101c6ad07050

**Comment by aerwin** [comment]
Confirmed.
