### ISSUE TITLE
Need to elements to mobile theme metadata

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1793]
I found this while building tweetView, assigned to Jon for him to evaluate

mobile theme meta data is missing elements for widget, we also need to add elements to the tech documentation on the wiki

```
"elements": {
    "$root": [ 
        "color",
        "font-family",
        "font-size",
        "font-weight" 
    ]
}
```

**Comment by jhpedemonte** [comment]
Forgive me, I don't know much about the theme metadata:  what would this give us?  What is currently missing?

**Comment by JonFerraiolo** [comment]
The issue here is that the properties palette is mixed up for some widgets where an attempt to change a property brings up the "Sorry, read-only theme" error dialog, but in fact it should have been possible to put the property value on element.style.

**Comment by billreed63** [comment]
For example if the user is using the default themes for mobile and Drops a TabBarButton on the Heading widget. By default the button floats:left, but the user wants the buton at the far right of the Heading (a refresh button maybe) If the user try to change the float property in the palette they will get the nasty message john mentioned. The user can open the cascade and select the "element" item from the cascade and the float property will be place on the element instead of the theme css. But the default for TabBatButton:float should be element not the css theme. 

This is what the "element" in the theme meta data does for us...

**Comment by billreed63** [comment]
One thing - my first impression is that our theme metadata is likely greatly incomplete regarding this "elements" stuff. I only see it for Button and Calendar. I would think that nearly every widget would have the font properties on "elements", and also "float", "clear", "width", "height" would be common

we might need some combo variable like we have for $std10 or whatever that was so we are duplicating the same list of properties all over the place

**Comment by billreed63** [comment]
I think I figured out what's wrong and how to fix a bunch of Property palette bugs, like:

https://github.com/maqetta/maqetta/issues/1792: Properties 2, Step 10: Can't change position of calendar to absolute
https://github.com/maqetta/maqetta/issues/1790: Properties 2, Step 7: Text box width cannot be set via Properties palette

Also, this fix might make it so that we don't have to create a zillion new entries in the theme metdata of the form:

 elements: {'$root':.[...]}

What I'm thinking is that we need someway to recognize that a particular selector targets the root node of the widget. For example, ".claro .dijitCalendar" is the root node of the calendar, so any properties that are allowed on ".claro dijitCalendar" should also be allowed on element.style, and the cascade list in the Properties palette should default to element.style in this case.

My best idea to accomplish this would be to add one more property to each widget in the theme metadata, for example:

"rootSelectors":[".claro .dijitCalendar"]

and then include some extra code in the _getDefaultSelection() method within Cascade.js so that if the default selector that is picked happens to be in the list of rootSelectors, then that routine would return "element.style" instead of the selector string.

**Comment by billreed63** [comment]
The code is complete, but I still need to update the theme metadata documentation of the wiki.

**Comment by billreed63** [comment]
doc is done
