### ISSUE TITLE
Unable to select mobile widget below view in mobile overlay 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1796]
tweetView:

Unable to select the TabBar elow the views when in designer iphone device overlay

Use the source code below to reproduce:

```

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<style>@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="maqetta/maqetta.js"></script>
<script type="text/javascript" data-dojo-config="'async':true,'parseOnLoad':true,'packages':[{'name':'yui','location':'../../yui'},{'name':'jquery-ui','location':'../../jquery-ui'}]" src="lib/dojo/dojo/dojo.js"></script>
<script type="text/javascript" src="maqetta/States.js"></script>
<script type="text/javascript">
require(["dijit/dijit"]);
require(["dojo/parser"]);
require(["dojox/mobile"]);
require(["dojox/mobile/deviceTheme"]);
require(["dojox/mobile/compat"]);
require(["dojox/mobile/ScrollableView"]);
require(["dojox/mobile/TabBar"]);
require(["dojox/mobile/TabBarButton"]);</script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"></meta>
</head>
<body class="claro" dvFlowLayout="true" data-davinci-ws="collapse" id="myapp" data-maqetta-device="iphone">
 <div data-dojo-type="dojox.mobile.ScrollableView" id="tweets" keepScrollPos="false" style="height: 490px;" selected="selected">
<h1 label="Tweets" data-dojo-type="dojox.mobile.Heading">
<div data-dojo-type="dojox.mobile.ToolBarButton" icon="images/refresh.png" sync="true" style="float: right;" class="mblDomButton tweetviewRefresh"></div>
</h1>

</div>
 <div data-dojo-type="dojox.mobile.ScrollableView" id="mentions" keepScrollPos="false" style="display: none; height: 490px;">
<h1 label="Mentions" data-dojo-type="dojox.mobile.Heading">
 <div data-dojo-type="dojox.mobile.ToolBarButton" icon="images/refresh.png" sync="true" style="float: right;" class="mblDomButton tweetviewRefresh"></div>
</h1>
  <ul data-dojo-type="dojox.mobile.RoundRectList">
    <li data-dojo-type="dojox.mobile.ListItem" sync="true">
    Mention tweet item here</li>
    <li data-dojo-type="dojox.mobile.ListItem" sync="true">
      Mention tweet item here2</li>
  </ul>
</div>
 <div data-dojo-type="dojox.mobile.ScrollableView" id="settings" keepScrollPos="false" style="display: none; height: 490px;">
<h1 label="Settings" data-dojo-type="dojox.mobile.Heading"></h1>
  <div label="Show" data-dojo-type="dojox.mobile.RoundRectCategory"></div>
  <ul data-dojo-type="dojox.mobile.RoundRectList">
    <li data-dojo-type="dojox.mobile.ListItem" sync="true">
    Setting item here</li>
    <li data-dojo-type="dojox.mobile.ListItem" sync="true">
      Setting item here2</li>
  </ul>
</div>
 <ul data-dojo-type="dojox.mobile.TabBar" iconBase="images/iconStrip.png" style="margin-top: -49px;">
   <li label="Tweets" data-dojo-type="dojox.mobile.TabBarButton" icon1="images/iconStrip.png" iconPos1="0,0,29,30" iconPos2="29,0,29,30" moveTo="tweets" sync="true" selected="selected" style="width: 76px;"></li>
   <li label="Mentions" data-dojo-type="dojox.mobile.TabBarButton" icon1="images/iconStrip.png" icon2="images/iconStrip.png" iconPos1="0,29,29,30" iconPos2="29,29,29,30" moveTo="mentions" sync="true"></li>
   <li label="Settings" data-dojo-type="dojox.mobile.TabBarButton" icon1="images/iconStrip.png" icon2="images/iconStrip.png" iconPos1="0,58,29,30" iconPos2="29,58,29,30" moveTo="settings" sync="true"></li>
 </ul>
</body>
</html>

```

**Comment by JonFerraiolo** [comment]
Reassigned to @jhpedemonte - there might be some issues with the order of the widgets in this file where dojox.mobile or Maqetta can't deal with things in a particular order but maybe would work if things were in a different order?

@billreed63 - do you know about the 'fixed' property?

@peller

**Comment by jhpedemonte** [comment]
-> M6

**Comment by jhpedemonte** [comment]
-> @doronrosenberg

**Comment by doronrosenberg** [comment]
You mean the tabbar at the bottom? I can select them fine in Firefox.

**Comment by JonFerraiolo** [comment]
I pulled the latest code and everything works for me. This is way cool! Three things that would be nice extensions:
1. Remember the last folder where you pulled an icon so that next time you bring up file picker it shows the same folder where last picked on icon
2. Show image previews in file picker.
3. Would be good to have a visual designer help with the visual styling for the smart input

@doronrosenberg What do you think? Neither are high priority, and #2 is a whole project in and of itself and likely won't get done for quite awhile.

**Comment by doronrosenberg** [comment]
@JonFerraiolo Smart input for tabbar would make a lot of sense, probably 2-3 days for that.

As for the file picker, we really need to build a generic, reusable one rather than having the same code in multiple files.  Probably also add a image-only mode if possible.  I'd say 1-2 days for a reusable picker with img preview

**Comment by JonFerraiolo** [comment]
Regarding file picker, we will probably want to coordinate with the Orion guys on that. They have a "navigator" that is pretty much "list" view in the Mac Finder. Our own UI folks are proposing a navigator page for Maqetta that is similar to the icons view in the Mac Finder. 

So, I'm thinking ultimately we will want something comparable to Mac Finder or Windows Explorer that can run on its own (i.e., navigator page), or embedded in another page (i.e., Files palette or Files popup), or can appear in a dialog (i.e., file picker).

@childsb

**Comment by jhpedemonte** [comment]
So this bug can be closed, right?  Any other issues can be spun off into other bugs.
