### ISSUE TITLE
Memory leak on server

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1806]
Looking at the heap from our last crash (roughly once a week now) I see mostly VLibraryResources and their associated URLs and ZipBundleEntry/Handler/ZipFiles.  I'm not sure if the latter might be cleaned up by a close() operation or if they're resident in memory, but the entire workspace seems to be kept in memory for each user, which grows over time.  The root cause would seem to be the caching of User objects in a Hashtable (on the Session?) which locks down each large doubly-linked tree of resources via the workspace member.  The User objects need to be aged, maybe with weakrefs, or perhaps just let go?

**Comment by peller** [comment]
@waynevicknair @childsb @JonFerraiolo

**Comment by childsb** [comment]
@jhpedemonte what was your a54aa43 change doing towards this bug?  was that a mistake?

Should be fixed with a1d3da now.  I'm removing the Users hashtable cash, and leaving it in the session. the session now ages/expires after 60 mins of inactivity.
