### ISSUE TITLE
Scenes/States palette cleanup items

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1807]
(@JonFerraiolo updates to original issue noted with "@JonFerraiolo UPDATE")

@JonFerraiolo UPDATE: After going through the big states reconciliation, I concluded that it was best to leave the plus and minus icons. It was too confusing for user to put plus icon on a TreeNode. Therefore, some of the items above become moot points.

Some UI things on the Scenes/States palette that we probably won't get to for M5:
- Get rid of the toolbar in all cases (@JonFerraiolo UPDATE: moot point now)
- Add a "+" icon on right edge of any objects that can have application states. (In short-term, that means the item that holds the current file name. In future, that would include mobile views and various Dojo containers such as Dialog) (@JonFerraiolo UPDATE: moot point now)
- When an item is selected or hover is happening, show a red "x" to allow that scene/state to be deleted. (@JonFerraiolo UPDATE: moot point now)
- Allow drag/drop reordering within the context of a particular parent (@JonFerraiolo UPDATE: still needs to be done, but there is an old issue for this: #342)

**Updated 2012-04-02:**
- View cannot be scrolled.(@JonFerraiolo UPDATE: the palette now has a scroll bar)
- Allow renaming items.(@JonFerraiolo UPDATE: there is a 3rd icon -- modify -- which allows a state to be renamed)

**Comment by jhpedemonte** [comment]
Added a few more items to summary, based on user feedback. Feel free to break out into separate bugs, if necessary.

**Comment by JonFerraiolo** [comment]
-> M7 Prio High

**Comment by JonFerraiolo** [comment]
Given the @JonFerraiolo UPDATE comments above, closing this bug. Everything listed here either has been addressed, won't ever be addressed, or has a separate issue already.
