### ISSUE TITLE
Chrome doesn't work with local install on Windows

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1809]
I was noticing Chrome was working very well with Maqetta running from my Eclipse on Windows, so I downloaded the latest ""external" GitHub-sources-only build" and see that doesn't  work with Chrome either. NOTE: This seems to  be browser specific as there are no issues with Firefox. It also appears to be limited to local install, so perhaps some weird Chrome-specific  timing issue or something?

When I go to http://localhost:50000/maqetta/ with Chrome on windows with the local install, I just get a web page that's all white with one word on it ("Maqetta"). There are also a number of errors in the Javascript console.

Build info:
Version: Preview 5
Date: Feb 26, 2012 11:22:12 PM
Build: 1934e2b343b0aaa..

Javascript console errors:

``` preformatted
GET http://localhost:50000/maqetta/app/davinci/workbench.css?1934e2b343b0aaad0a9cb9638913a31a9b02862b 413 (FULL head)
GET http://localhost:50000/maqetta/app/dijit/form/ValidationTextBox.js?1934e2b343b0aaad0a9cb9638913a31a9b02862b 413 (FULL head)
GET http://localhost:50000/maqetta/app/davinci/review/resources/Comment.css?1934e2b343b0aaad0a9cb9638913a31a9b02862b 413 (FULL head)
GET http://localhost:50000/maqetta/app/dijit/layout/_ContentPaneResizeMixin.js?1934e2b343b0aaad0a9cb9638913a31a9b02862b 413 (FULL head)
dojo.js:2489Uncaught Error: declare dijit.layout.ContentPane: mixin #1 is not a callable constructor.
```

Expanded:

``` preformatted
GET http://localhost:50000/maqetta/app/davinci/workbench.css?1934e2b343b0aaad0a9cb9638913a31a9b02862b 413 (FULL head)
GET http://localhost:50000/maqetta/app/dijit/form/ValidationTextBox.js?1934e2b343b0aaad0a9cb9638913a31a9b02862b 413 (FULL head)
req.injectUrldojo.js:928
_32dojo.js:835
_9dojo.js:31
_71dojo.js:324
_9dojo.js:31
_76dojo.js:876
_ecdojo.js:761
_32dojo.js:776
_9dojo.js:31
_71dojo.js:324
_9dojo.js:31
_76dojo.js:876
_ecdojo.js:761
_32dojo.js:776
_9dojo.js:31
_71dojo.js:324
_9dojo.js:31
_76dojo.js:876
_ecdojo.js:761
_32dojo.js:776
_9dojo.js:31
_71dojo.js:324
_9dojo.js:31
_76dojo.js:876
_ecdojo.js:761
_32dojo.js:776
_9dojo.js:31
_71dojo.js:324
_9dojo.js:31
_76dojo.js:876
_ecdojo.js:761
req.injectUrl._107
GET http://localhost:50000/maqetta/app/davinci/review/resources/Comment.css?1934e2b343b0aaad0a9cb9638913a31a9b02862b 413 (FULL head)
placedojo.js:4312
createdojo.js:4330
loaddavinci.js:3631
_e1dojo.js:699
_cc.loadQdojo.js:583
_9dojo.js:31
_cbdojo.js:580
_35dojo.js:611
_36dojo.js:647
_77dojo.js:660
_ecdojo.js:769
req.injectUrl._107
GET http://localhost:50000/maqetta/app/dijit/layout/_ContentPaneResizeMixin.js?1934e2b343b0aaad0a9cb9638913a31a9b02862b 413 (FULL head)
req.injectUrldojo.js:928
_32dojo.js:835
_9dojo.js:31
_71dojo.js:324
_9dojo.js:31
_76dojo.js:876
_ecdojo.js:761
req.injectUrl._107
Uncaught Error: declare dijit.layout.ContentPane: mixin #1 is not a callable constructor.
errdojo.js:2489
_256dojo.js:2499
_273dojo.js:2830
(anonymous function)ContentPane.js:33
_c2dojo.js:568
_36dojo.js:646
_36dojo.js:637
_36dojo.js:637
_36dojo.js:637
_36dojo.js:637
_36dojo.js:637
_77dojo.js:660
_ecdojo.js:769
req.injectUrl._107dojo.js:922
```

**Comment by JonFerraiolo** [comment]
Worked for me just now with Mac/Chrome

@aerwin - did you clear your browser cache before running the build? I changed package.json over the weekend and there was a cache busting open issue with that file (#1734) that supposedly was fixed by d808598

@peller, @jhpedemonte

**Comment by aerwin** [comment]
Yes, I've cleared cache a number of times.

**Comment by JonFerraiolo** [comment]
Worked just now for me on Win/Chrome. Same build#.

@billreed63 - can you please try today's build on your machine using Win/Chrome?

**Comment by JonFerraiolo** [comment]
@aerwin - next thing to try is to clear cookies for http://localhost. We have another bug where cookies can be so large that the HTTP request is too large. #1666

**Comment by aerwin** [comment]
Awesome! Clearing cookies fixed it. Thanks! I'll go ahead and close.

**Comment by peller** [comment]
Interesting.  Never saw one of these: HTTP Error 413 Request entity too large
