### ISSUE TITLE
Mobile widget that use DataStores should support remote URL

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1811]
All widget that use data stores should support remote data sources (JSONP) like data grid

**Comment by billreed63** [comment]
I created a sample service at http://maqettaservice.appspot.com/sampledatalistservice

**Comment by JonFerraiolo** [comment]
Assigned to @billreed63 - seems like he's the guy for this area

**Comment by billreed63** [comment]
Moving to M6

**Comment by aerwin** [comment]
After discussion with @billreed63 this morning, it sounds like this one will encompass refactoring data store code so it can be shared by all data store-enabled widgets. I'll eventually need that for GridX support (#2034).

**Comment by doronrosenberg** [comment]
DataStoreBasedWidgetInput.js exists now and is used by the 2 mobile datalist widgets

**Comment by doronrosenberg** [comment]
And I should have noted that they support JSONP urls already.

**Comment by aerwin** [comment]
@doronrosenberg @billreed63 

Ok, cool... then maybe a lot of this refactoring has already been done by @doronrosenberg . I see in commit 12b4bfc43ffcaeca61171dc450632ec63349259 ("Move some code from DataGridInput to the generic DataStoreBasedWidget") that DataGridInput started using DataStoreBasedWidgetInput. (And, then there were a number of subsequent commits including additional clean-up, etc.) When I was last in this code in February, this was not the case.
