### ISSUE TITLE
Error when unsetting `fixed` prop for Heading

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1813]
To reproduce:
1. New page, drop a **ScrollableView**.
2. Add a **Heading**.
3. In **Properties->Widget-specific**, set `fixed` to `top`.
4. Now unset that command (select _blank_ option in `fixed` dropdown).

-> While the property is removed (check the source), we get an error in **dojox/mobile/View**.

Not exactly sure what's going on here.

I can properly set the `fixed` property of Dojox mobile **Heading** to `top` or `bottom`.  However, if I try to unset it, I get an error in the `setTimeout` inside of **dojox.mobile.View** `startup()`.

I tried debugging this, but it goes through a confusing amount of Maqetta code.  The end result, though, is that `View.startup()` gets **called twice** for some reason.

@JonFerraiolo @peller

**Comment by jhpedemonte** [comment]
In the failing case (unsetting `fixed`), `Context.refresh()` is getting called twice for some reason (as are several functions up the stack).

**Comment by jhpedemonte** [comment]
(cc @aerwin)

You guys are more then welcome to help debug this.  I'm a bit stuck. As previously mentioned, `Context.refresh()` is getting called twice when unsetting the `fixed` property for **Heading**.  And this causes an error.

**Comment by JonFerraiolo** [comment]
Put a breakpoint at WidgetProperties.js:158. When you change the value in the Widget-Specific section, the _onChange handler gets invoked multiple times. I wouldn't be surprised if that's part (or all) of the problem.

**Comment by JonFerraiolo** [comment]
I've done some more digging. Put breakpoints at WidgetProperties.js 115 and 116 and 134. It looks like _refresh is called once when the property is changed in the Properties palette from 'top' to empty string, and then after the refresh has completed, then the reselect operation causes the Widget-specific properties to be reassigned in WidgetProperties.js, which causes reestablishing the onchange handlers, and for some reason the value of one of the properties (presumable 'fixed') triggers the onchange event, which cycles back ultimately to Context.refresh() once again.

**Comment by JonFerraiolo** [comment]
More digging. It looks like we are calling _disconnectAll, then _setValue, then _connectAll, all in the proper order. But the this._connects array is never cleared, and I'm not sure that line 155 actually achieves the disconnect. Gotta go now.

**Comment by jhpedemonte** [comment]
Thanks, Jon.  I'd noticed some similar things, but I think you got further than I did. I'll look into this more tomorrow.

**Comment by jhpedemonte** [comment]
For some reason, GitHub didn't link the commits that mentioned this bug:

7a38de9bfc37f3553c2e221819126f56570fc989
4e3b7ec1fab4b697f0472d3104c61197eb549676
70b126da2ce065abc53ae523dccdd2dd7acde04c
08be6ffea9b253445c4e6478a539aa6e31fbd538
