### ISSUE TITLE
Single-user local install: can't open *.rev file from Reviews palette

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1818]
(Need to fix before shipping, but no immediate urgency, other things more important in next few days)

You can open a *.rev file when running multi-user version of Maqetta, but if you double-click on a *.rev file when running the single-user version localhost version of Maqetta, the middle of the screen shows the login page rather than the HTML file on which you double-clicked.

**Comment by waynevicknair** [comment]
cannot reproduce on commit a0708e74bbb9edb7d98f17d2fe2910e4d3030b92. please re-open if issue recurs.
