### ISSUE TITLE
file upload selection limited to single file (and other issues)

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#182]
the file upload local file selection dialog is limited to a single file at a
time even though multiple uploads are supported.

recreate: 
1. login to davinci server
2. right click on root and select "add files"
3. click "select files" button
4. try and select multiple files

you can still add multiple files by re-clicking "select files" and adding
individually.
## 

@JonFerraiolo writes:
Phil recently implemented multiple file download via ZIP. We need a
corresponding multiple file upload. 

Here are two approaches that we should implement over the course of time:
- First off, we should enable uploading a ZIP file (this should already be
  working) and then offer a context menu command on the Explorer palette to
  extract the contents of the ZIP file into a particular folder. Brings up the
  file dialog in model/Resources.js. Will need to add a "New Folder" button to
  the file dialog to make this work reasonably.
- Down the road, let's get Add Files working with multiple selection of input
  files
## 

@jhpedemonte writes:
Some other file upload dialog issues:
(1) Dialog should be renamed to "Upload files" (instead of "Add files").
(2) Dialog shows files to be uploaded as "C:\fakepath...".
(3) Dialog does not disappear after upload completes, I assume in order to show
progress in the text area.  If we need a progress dialog, then we should do
that instead;  it would disappear automatically at the end.  If there was an
error, dialog stays up and displays error message.
## 

from bugzilla 4475

**Comment by JonFerraiolo** [comment]
Adam updated to the new Dojo uploader, and we now can upload multiple files at once. Yay! But most of the other issues listed above are still pending.

**Comment by peller** [comment]
Can you recap for me?  C:\fakepath should be gone also.  Perhaps the "Add Files" change would be best made on the Globalization branch.

Yeah, not sure what to do about the Upload button.  Perhaps it could turn into a "Done" button after completion?

**Comment by jhpedemonte** [comment]
I would prefer it if, upon clicking **Upload** button, the dialog disappeared and a new progress dialog appeared (or a tooltip at bottom of page).  The progress dialog/tooltip/whatever would show progress and maybe linger a couple of seconds once complete, but then fade out on its own.

I don't see why user should have to click **Upload** and then again **Done** to complete the process.

**Comment by JonFerraiolo** [comment]
Yes, I agree with Javier. We should ask @jmockler about whether after closing the dialog we should: (a) post a modal dialog that says "files upload" with an OK button, (b) bring up a toaster which requires user to click in order to make it go away, (c) bring up a toaster that appears only for a few moments, or something else.

**Comment by peller** [comment]
It seems common to have to dismiss a progress dialog, at least in desktop applications...  well, let's put it this way... the UI we have today was free.  I could do the Upload/Done thing in about a minute for M2 while we figure this out.  It seems like there's a bigger question of reporting status and exceptions in a consistent way.

**Comment by jhpedemonte** [comment]
Toaster is a good idea, assuming that will be the **consistent** way we handle such notifications.  But a fix based on this discussion can wait until after M2.  Feel free to close this issue and open another to track the latest discussion.

**Comment by peller** [comment]
I'm not sure the toaster widget would fit here, since we need to show progress.  Toasters are generally just for notification.  Jon, ok to close, or were there other open issues here?

**Comment by jmockler** [comment]
@peller I disagree.. I think the toaster could be leveraged to show progress as well.

**Comment by peller** [comment]
what you're describing isn't what I see on the web that's generally considered a toaster.  It sounds more like a dialog.

**Comment by JonFerraiolo** [comment]
See #591
