### ISSUE TITLE
Data Grid test case w/ JSONP reopening file doesn't re-fetch data

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1822]
In the _Data from URL (JSONP)_ section of the _dataGrid.html_ test page, Step 8 asks the tester to reopen the HTML file containing a the DataGrid pointing at a URL.

Reopening the HTML file works, but the data isn't fetched from the URL unless I double click to bring up Smart Input and hit OK. 

Environment: Chrome on windows running against lab9

**Comment by billreed63** [comment]
fixed by commit fbdb38459de1603b32961cedebbd19ec09dd1e8e
