### ISSUE TITLE
Outline Tree not expanding upon widget selection

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1823]
Open Sample1.html.  Click on the TabContainer in the visual editor.  Notice that the TabContainer is selected in the outline view. 

Now click on the 'New' Button.  Notice that there is no selection in the outline view.  Expand the tree under the first contentpane enough to see the New button and you'll see the selection.

The event should expand the tree as necessary to show the selection.

**Comment by JonFerraiolo** [comment]
We have had this limitation all along, haven't we? Seems like it would be fairly easy to fix: do a query into the store to find the item that matches the current widget, then build a path by prepending/splicing the id's of parent nodes from the store, and then calling set('path',...) on the Tree.

**Comment by peller** [comment]
no, set path is supposed to do this.  I think this is a regression.

**Comment by peller** [comment]
so we're using set('paths') elsewhere, but not on ToggleTree, our custom Tree widget.  ToggleTree carries over some old API like selectNode, so until we clean all that up, we have to carry it over to the new API.  Also, to find the paths, we need to traverse the dom tree from the widget model, but skip dom elements not represented in the widget model.
