### ISSUE TITLE
States theming: font size for text box not sensitive to state

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1824]
testing states theming. mac/chrome running in eclipse on latest code.

clone claro theme into mytheme1 per test instructions and perform steps in "States theming" section. 

result: after setting font size to 20pt for hover state and saving. preview in browser shows large font for _all_ states versus only hover state.

**Comment by JonFerraiolo** [comment]
@billreed63 @jhpedemonte there are some bugs with States.js that might be causing this, or might not be causing this. But I thought I should mention that I am hoping to do an A-Z code cleanup on States.js in the coming days. I have some bugs that need fixes to States.js, and I expect @jhpedemonte also has bugs that relate to States.js.

**Comment by billreed63** [comment]
This seems to be working now, 0447cfd2af9ee56d553906ef3fc5101c6ad07050 if you are still seeing this reopen and specify which widget
