### ISSUE TITLE
Visual overlay test: dropping Dialog on canvas fails

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1826]
Visual Overlay testing. Mac/Chrome running latest code in Eclipse:

perform steps in Dialog placement script. When dropping Dialog get DOMException "NOT_FOUND_ERR: DOM Exception 8" at line 374 of CreateTool.js.

**Comment by jhpedemonte** [comment]
This is my code.

**Comment by jhpedemonte** [comment]
OK, I fixed the error.  Now Dialog gets added (I can see it in VE DOM), but is not visible.
-> back to Adam
