### ISSUE TITLE
Editor tab show .html.html

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1830]
Double-click on Sample1.html and the editor's tab says "Sample1.html.html"

**Comment by JonFerraiolo** [comment]
Perhaps we need to add an optional helper function to ReviewEditor.js to transform the default filename? Workbench checks the editor to see if the editor object has such a helper function, and if so, calls it, that way no side effects for page editor and theme editor.

**Comment by peller** [comment]
I think @waynevicknair fixed that in a0708e74bbb9edb7d98f17d2fe2910e4d3030b92

**Comment by waynevicknair** [comment]
@peller is correct.
