### ISSUE TITLE
(Firefox) After login, opens as maqettaUser instead of login

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1832]
I was testing localhost install, and then on the lab9 50010 and 50020 server. If I go to /maqetta/welcome, I get taken to the login screen, but then Maqetta opens single-user (maqettaUser). If I just go to /maqetta after logging in, Maqetta also comes up single user (maqettaUser).

Fails with Mac/Firefox. Works with Mac/Chrome.

**Comment by childsb** [comment]
Fixed this yesterday.. forgot to add the username cookie to the register command.

**Comment by JonFerraiolo** [comment]
Reopening to ask a question: When I tried today's build, I saw the same problem, but if I cleared my cookies and cache, the problem went away. What will happen with existing users when they run the M5 release? Will they run into this bug (assuming they don't clear their cookies)?

**Comment by childsb** [comment]
i had a bug on the cookie setting.  unless they were running a build of maqetta from yesterday they should be fine.

**Comment by JonFerraiolo** [comment]
Reopening I'm seeing this problem again with today's build

**Comment by childsb** [comment]
@JonFerraiolo did you try clearing your cache?

I logged into both lab9 ports OK before and after clearing cache on osx/FF.

**Comment by JonFerraiolo** [comment]
Ah, it isn't cache that needs to be cleared - it's cookies that need to be cleared. OK, I cleared my cookies and during remainder of this testing sprint I'll see if everything is OK in Firefox in subsequent sessions (when things should work without having to clear cookies each time)
