### ISSUE TITLE
Mobile previews broken in builds

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1834]
@jhpedemonte 

Mobile previews (preview in browser)  is broken in builds. The previewer dies when trying to do xhr gets on /maqetta/app/davinci/nls/webContent.js and /maqetta/app/preview/nls/preview.js
- Run a build version of Maqetta
- New HTML file - iphone
- Preview-in-browser

Look at Network panel and you'll see that those two files were not retrieved successfully.

**Comment by peller** [comment]
could be another 1.7.2 regression?  see #1837

**Comment by peller** [comment]
backed out 1.7.2: fd15157f77e9b5c4e1def2988b3c0bdb8fddc66d
