### ISSUE TITLE
Mobile UIs that use custom themes show default themes in review editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1836]
@billreed63 - this bug might be coming your way, but assigning to @jonferraiolo at first to do some initial investigation
- Clone custom to custom2, change some styling, save
- New html file, use any device.
- Add some widgets (View, Heading, RoundRectList)
- Change theme to custom2
- Save
- New Review, using this new HTML file, invite yourself, click Publish
- In Reviews palette, double-click on the new HTML file that has been published for review

Result=> In review editor, the default device theme is used instead of custom2

**Comment by billreed63** [comment]
My bet would be that Context._configDojoxMobile() is not being called by the review logic.. This is the code that fixes up the mobile themes in the preview editor

**Comment by JonFerraiolo** [comment]
@billreed63 @peller 

I only see this problem when running lab9:50020. When running a build on localhost:50000, no problem. Maybe a timing problem? 

@billreed63: can you try to reproduce this by running lab9:50020?

@billreed63: any ideas about how there could be a timing issue with running the JS logic that loads the proper theme?

**Comment by billreed63** [comment]
So here is what I am thinking....
 the themeMap has to be defined before the mobile/deviceTheme object is created or you get the default themeMap...
 So assuming that all the requires[] run asyn (all at the same time) the deviceTheme require could be returning before the function in  the mobile require has run to define the new themeMap...

**Comment by billreed63** [comment]
So I think if we change the require so that the `require(["dojox/mobile/deviceTheme"]);` is inside the function callback of the `require(["dojox/mobile"]);`  should eliminate the timing issues

```
require(["dojox/mobile"],function(dojoxMobile){ dojoxMobile.themeMap=[["Android","",["themes/custom/custom.css"]],["BlackBerry","",["themes/custom/custom.css"]],["iPad","",["themes/custom/custom.css"]],["iPhone","",["themes/custom/custom.css"]],[".*","",["themes/custom/custom.css"]]]; dojoxMobile.themeFiles = []; require(["dojox/mobile/deviceTheme"]);} );

```

**Comment by JonFerraiolo** [comment]
@peller, @jhpedemonte 

@billreed63 - do you think you'll attempt this change today?

**Comment by billreed63** [comment]
@peller @jhpedemonte  I was thinking we could add callback functions to the requires for the mobile widgets.

I propose we do something like:

add the amdFunction to  *_oam.json

```
"require": [
        {
            "type": "javascript-module",
            "format": "amd",
            "src": "dojox/mobile",
            "amdFunction": 'function(dojoxMobile){ require(["dojox/mobile/deviceTheme"]);}',
            "$library": "dojo"
        },
```

and add and add to ve/Context.loadRequires

```
                           case "javascript-module":
                    // currently, only support 'amd' format
                    if (r.format !== 'amd') {
                        console.error("Unknown javascript-module format");
                    }
                    if (r.src) {
                        this.addJavaScriptModule(r.src, updateSrc || doUpdateModelDojoRequires,
                                skipDomUpdate, r.amdFunction);
                    } else {
                        console.error("Inline 'javascript-module' not handled");
                    }
                    break;
```

and add to ve/Context.addJavaScriptModule

```
addJavaScriptModule: function(mid, doUpdateModel, skipDomUpdate, amdFunction) {
        if (!skipDomUpdate) {
            if (amdFunction){
                var f = dojo.fromJson(amdFunction);
                this.getGlobal().require([mid], f); 
            } else {
                this.getGlobal().require([mid]); 
            }

        }
        if (doUpdateModel) {
            //TODO: keep all requires in a single statement?
            var str = 'require(["' + mid + '"]'
            if (amdFunction) {
                debugger;
                str += ', ' + amdFunction;
            }
            str +=');';
            this.addHeaderScriptText(str);
        }
    },
```

Does this seem like a reasonable approach?

**Comment by billreed63** [comment]
I think I will wait on this change until I get back on 3/11  I think this will have ripple effects in theme switching as well

**Comment by billreed63** [comment]
I may have found a better way to deal with this, I have added a dojo.ready and a call to loadDeviceTheme if the device is mobile.

**Comment by jhpedemonte** [comment]
Why is fix necessary for Mobile themes only?  And only the custom theme at that?

How will this work for non-Dojo themes (whenever we get there)?

**Comment by billreed63** [comment]
Mobile theme's are added dynamically based on user agent, or theme on the url. Review was not setting the device so the correct mobile theme was not being used. Desktop uses a static theme that in `@import`  It was not only needed for custom theme, if you used the iphone device it appeared that way but you could use the default theme and pick a differnt device (android) and the theme that was being used was iphone.
