### ISSUE TITLE
Review and Commenting confused about who is commenting

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1838]
I created two user
billreed63 and billreed
I requested a review from billreed63@gmail.com (billreed63) to have billreed@us.ibm.com (billreed) review my page
When I log in as billreed to review the page the I added a comment put when I clicked on the show participants ICON in the review palette it showed billreed@us.ibm.com ad red and billreed63 as blue.. but all my comments have blue borders, should they not be red?

**Comment by JonFerraiolo** [comment]
Raising to Prio-High.

One note: I fixed a coloring problem in the old review code (davinci.review) sometime in last few months, but I don't remember when exactly, and now that project is gone from master, so it will take a bit of effort to restore. I'll try to remember to research this later today.

**Comment by waynevicknair** [comment]
fixed in commit fb2051ad40132689c90221c60bb354e7dd4f24e5
