### ISSUE TITLE
States changes don't work in split view

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1846]
@jhpedemonte @waynevicknair 

This bug was in Preview 4 also, so targeting M6 for this issue.
- Open Sample1.html
- Go into split view
- Click on different states

Result=> Nothing happens - state change doesn't happen. Even if you go back to design view, you still can't change states without closing the editor and reopening it. 

Somehow or other bringing the act of bringing up the source editor wipes out the "states" property on the widget object corresponding to the BODY. (I figured this out by putting a breakpoint in davinci/maqetta/States.js:setState()) Just a theory, but maybe upon bringing up the source editor, we are doing a short-circuit document reparse, and that document reparse isn't doing the _preserveStates/_restoreStates logic we do on initial page load.

**Comment by peller** [comment]
body has the states property, but other nodes, which should, do not.  what does that indicate?

**Comment by peller** [comment]
confirmed: _preserveStates is called, but _restoreStates is not because callback is undefined for _setSource.  Usually it has a callback which invokes activate()
