### ISSUE TITLE
Mobile theme editors show nothing for background-image for Heading and Button

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1847]
@billreed63 
- Clone custom2 or android or whatever
- Click on global Heading and look at background-color and background-image values in Properties palette

Result=> background-color and background-image shows blank instead of their correct values

**Comment by JonFerraiolo** [comment]
@childsb could you take a look at this one, too. See #1848

**Comment by JonFerraiolo** [comment]
Closing. Somehow GitHub didn't recognize that it should auto-close based on comment just above.

**Comment by billreed63** [comment]
I don't think this is the correct fix. We don't want to use cascade to determine the values to put in the properties palette for widgets in the them editor, we only want to display the values from the theme meta data selectors.

As an example when the user selects the Calendar widget and then selects the sub widget selectedDate the background values should only display values from the selector `.claro .dijitCalendarSelectedDate .dijitCalendarDateLabel` That is the only selector that will have change applied. effects this widget. Also it appear that cascade collects the values for the top widget not the sub widget.
