### ISSUE TITLE
'Where' dropdown menu is empty after opening a review

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1853]
@peller 
- Create a New Review
- Open up an HTML file from that review
- Issue a New HTML FIle command

Result => Not that where dropdown button is blank (instead of showing "<root>".

Assigning to @childsb only because I expect he'll get to this before I can.

**Comment by childsb** [comment]
review editor was publishing the same resource change event as the file explorer causing the resource selection item to be a review object.
