### ISSUE TITLE
Hide all or parts of Properties palette with theme and review editors

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1857]
Don't have a spec for this bug yet, but clearly class and id shouldn't show in theme editor, nor should the non-CSS sections (e.g., widget-specific, events, ...). 

Haven't looked to see what happens with review editor.

**Comment by jhpedemonte** [comment]
Should be easy enough with a set of CSS classes which can be added/removed to Properites view.  Then create CSS rules for hiding/showing, based on presence of ancestor CSS classes.

**Comment by JonFerraiolo** [comment]
Pushing to M6, Prio High
