### ISSUE TITLE
data-davinci-ws="collapse" not appearing in initial source view

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1862]
Minor bug.

We are adding `data-davinci-ws="collapse"` to all user HTML files but this attribute doesn't appear in source view immediately after opening a new file.
- New HTML File (hi fi page)
- Split view

Result=> You don't see attribute `data-davinci-ws="collapse"` , but if you look at the actual HTML code after the file is saved, that attribute is in the file. Perhaps the source code text is built before data-davinci-ws is added to the model?

**Comment by aerwin** [comment]
--> no milestone to M7
--> prio not set to low

**Comment by JonFerraiolo** [comment]
Closing. This got fixed along with way, and I have a vague memory of having made the change to fix this problem.
