### ISSUE TITLE
Source editing not working in Firefox (Mac and Windows)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1863]
@waynevicknair, @jhpedemonte 

In Mac/FF or Win/FF:
- New HTML File
- Split View (top/bottom)
- Try to type this between `<body ...>` and `</body>`:

`<div style='color:red'>abc</div>``

Result=> almost all characters get dropped - source editing is unusable in FF

**Comment by peller** [comment]
wondering if it's possible to avoid the additional network hits from the modeler for css files in this situation.  also, if it's possible to avoid updating the model until the user goes back to do something in the visual editor.  Beyond that, it's probably the modeler itself responsible for the performance.  That leaves tuning the modeler #381 or something more drastic, like partial modeling in #1522 or replacing the model altogether.

**Comment by peller** [comment]
see #1554

**Comment by peller** [comment]
-> M7

**Comment by peller** [comment]
looks ok now that selection problems have been fixed d006ad0b30587e7f878faa6bd4839ab1fa08f30c
