### ISSUE TITLE
Attempt to create HTML file that already exists: exception: isNew is undefined

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1864]
Logging this without fully investigating.

I'm running today's build off of lab9:50020 using Mac/Chrome. Earlier in day, I was running lab9:50020 using Win/FF. In my earlier session, I had created file6.html, and my Mac/Chrome browser wasn't aware of that. When I issued a New HTML File command in Mac/Chrome using the default name of file6.html, of course it fails because file6 exists on the server.

But what's broken now is that I am seeing an exception: Uncaught TypeError: Cannot set property 'isNew' of undefined. The offending line of source code is:

```
_9b5.isNew=true;
```

Here is the neighboring contents showing in the debugger:

```
var _9a8={newHTML:function(){
var _9ad="davinci/ui/widgets/NewHTMLFileOptions";
var _9ae=_99c(_99a.fileName,_99a.create,"html",_9ad);
var _9af=function(){
var _9b0=true;
if(!_9ae.cancel){
var _9b1=_9ae.dialogSpecificWidget;
var _9b2=_9b1.getOptions();
var _9b3=_9ae.get("value");
var _9b4=_9aa(_9b3);
if(_9b4){
var _9b5=_98c.createResource(_9b3);
_9b5.isNew=true;
              Uncaught TypeError: Cannot set property 'isNew' of undefined
var text=_98c.createText("HTML",{resource:_9b5});
if(text){
_9b5.setText(text);
}
```

**Comment by childsb** [comment]
Fixed with checking 3d008c2e306847cfa116b7c46d2308cb3086b0e  (wrong issue # in commit)
