### ISSUE TITLE
Can't do source editing on Button inside of Accordion

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1865]
@waynevicknair, @jhpedemonte 
- New HTML File
- Split view (top/bottom)
- Add Accordion
- Add Button inside of Accordion
- In source view, change button's label from "Button" to "abcdef"

Result=> Button disappears from the design canvas [peller: clicking on the source view editor switches to the second accordion pane, before you actually start typing]

**Comment by peller** [comment]
works for me

**Comment by peller** [comment]
tried on lab9 + FF, still could not reproduce.  If you can make this happen, can you confirm that no exceptions appear on the console or in the debugger with catch on throw?

**Comment by JonFerraiolo** [comment]
@billreed63 

I think what's going on isn't that the Button is going away, but that I was fooled because Accordion tabs are getting switched automatically, so the Button is still there, but invisible because the tabs have been switched.

I'm not sure exactly how many problems we have here, but here is one scenario that is problematic:
- Mac/FF or Mac/Chrome, running off of 50020 server
- New HTML File (hi-fi page)
- Split view (top/bottom)
- Add Accordion. When SmartInput appears, click OK to accept default values

Result=> Accordion switches to pane 2. 

This only happens when the above steps are followed exactly. If you change order of operations, no problem. If not in split view, no problem. I wonder if SmartInput isn't stopping event propagation on the OK button and somehow the event is bubbling up to higher-level code?

**Comment by jhpedemonte** [comment]
Given Jon's last comment, moving to Priority Low.

**Comment by JonFerraiolo** [comment]
I'm moving this to M6 Priority High. Make sense? I'm thinking that this particular scenario may not be all that important, but it might be exposing a deeper problem that is likely to have lots of different problems.

**Comment by peller** [comment]
-> M7

**Comment by peller** [comment]
@JonFerraiolo @billreed63 

I cannot reproduce this problem.  Is it fixed?  If not, let's update the description.  Sounds like the issue has to do with the smartinput ok button event?

**Comment by peller** [comment]
Hmmm... I see now the first problem (clicking in the source view changes the tab) but not the second problem with the smartinput (unrelated bug?)  I'm wondering if perhaps the model isn't updated when I first click in the source view, so it has the wrong offset.  That condition persists for a few seconds, then clicking on the button's source selects the button widget properly.

**Comment by JonFerraiolo** [comment]
I'm going to close this bug. I believe the source editor quirks we had when the issue was first written have been fixed. 

There is one problem remaining, captured in #3382, which captures the remaining problem where if you change the label in source view for a Button with is in the second Accordion pane, the design pane switches back to the first pane.
