### ISSUE TITLE
Widget Palette that has a filter doesn't reapply when reopened, leading to empty result list

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#1866]
- Open a file
- Filter on the widget palette by entering text into the filter textbox
- Close the file
- Open any file

The filter textbox retains whatever you entered, but the result list is now empty.

**Comment by JonFerraiolo** [comment]
@doronrosenberg Not something that we need to fix for M5, but maybe you can fix this in a branch that we can include in M6.
