### ISSUE TITLE
Textbox Confusion

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1871]
1) new html
2) add a content pane
3) add a label inside the content pane
4) type in "text" in the widget search field to look for "TextBox"
5) notice that multiple text boxes show up, all identical
6) add each one to the content pane.  if you add happen to choose the dojox.mobile.textbox the entire page will change (background etc..)

this is probably more a usability issue, but from the filter view its not clear that there is a difference in the text boxes, and accidentally adding the dojox.mobile version changes the background of the entire page to grey.

**Comment by JonFerraiolo** [comment]
@doronrosenberg

**Comment by jhpedemonte** [comment]
What happened here?  For M4, I added code that put a category name next to each widget when using the filter list.

Has someone changed the Widgets code recently?

**Comment by JonFerraiolo** [comment]
Try this in WebKit and Firefox. innerText works in WebKit but not in Firefox:

```
<script type="text/javascript">
window.onload = function(){
    var txt = '<b>hello\'\"\&</b>';
    var div1 = document.getElementById('div1');
    div1.innerHTML = txt;
    var div2 = document.getElementById('div2');
    div2.innerText = txt;
    var div3 = document.getElementById('div3');
    div3.textContent = txt;
    var div4 = document.getElementById('div4');
    div4.innerHTML = escape(txt);
}
</script>
<div>innerHTML</div>
<div id='div1'></div>
<div>innerText</div>
<div id='div2'></div>
<div>textContent</div>
<div id='div3'></div>
<div>escape</div>
<div id='div4'></div>
```
