### ISSUE TITLE
(UI) Shouldn't enable 'fixed' unless widget is in ScrollableView

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1876]
I find myself falling into the trap of trying to set 'fixed' to top or bottom when using View or SwapView, but that property only works when inside of ScrollableView. We should disable the 'fixed' property if the given widget is not a child of ScrollableView. (I realize this will mean yet more metadata and probably yet another helper)

**Comment by jhpedemonte** [comment]
Just wanted to emphasize that the property should be **disabled**, not removed.  User should see that there is such a property, but not currently useable.

Also, would be good to have a tooltip explaining why the property is disabled.

**Comment by doronrosenberg** [comment]
We could add a metadata override called `mustHaveAncestor` which lists required ancestor classes in an array.  If not found, the property gets disabled.  this would get checked every time the widget props are rendered obviously, sound good?

**Comment by JonFerraiolo** [comment]
Sounds like a good solution to me.
