### ISSUE TITLE
Error while autosaving file:TypeError: Cannot call method 'getText' of undefined

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1879]
@JonFerraiolo @waynevicknair 

It seems that when Maqetta does an autosave on a ReviewEditor, this exception shows up in the JavaScript console:

``` preformatted
Error while autosaving file:TypeError: Cannot call method 'getText' of undefined
saveDirtyWorkbench.js:1437
forEacharray.js:283
Workbench._autoSaveWorkbench.js:1442
hitch
```

I did a little investigation to make sure my #1867 work didn't cause it, and it looks like `this.model` is undefined in the save function of `ModelEditor` (one of `ReviewEditor`'s ancestors).

``` javascript
save: function () {
        this.model.setText(this.getText());
        this.inherited(arguments);
    },
```

I don't think this really has any negative side effects since `ReviewEditor` is not saved in a classical sense and`'Workbench` catches the exception. But, someone who's worked on review stuff should think about this (e.g., is `ModelEditor` the right thing to override?, should `save` be overridden, etc.).

**Comment by JonFerraiolo** [comment]
@childsb - can you look at this one, too? My first guess is that the review editor shouldn't be doing auto-saves given it's current "submit" approach, so one possible fix would be to find a way to disable auto-save for the review editor.

**Comment by childsb** [comment]
tony - can you provide more info?  i created a review, then opened it and added a comment.. but i dont see an error.

**Comment by aerwin** [comment]
Had a chat with @childsb to give him some better steps, but I'll include here as well:
1. Open review  
   2  add comment (but do NOT submit it) ... this makes the editor "dirty" 
2. click backspace button  (this happens to force an autosave)

I think the key is to have a "dirty" review an an autosave occurs.
