### ISSUE TITLE
Themeset dialog slow in updating right-side content

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1881]
I'm using Mac/FF.

If I switch theme sets on left side of theme set dialog, it takes over a second for the right side content to update. How come? Are there server requests happening in the background? If something slow is happening, maybe we should post some sort of hourglass.

**Comment by peller** [comment]
looks like it calls findResource to find the themes each time the multiselect is changed.  That value should only need to be loaded once for the dialog.

**Comment by billreed63** [comment]
fixed #2206
