### ISSUE TITLE
Review e-mail link doesn't take me to reviews

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1882]
The link in the e-mail I got when I created a review invitation doesn't take me to anything to do with reviews (even when I click on it a 2nd time as the e-mail instructions indicate). It just redirects to http://lab9.austin.ibm.com:50020/maqetta/ and doesn't even active the Review tab (let alone take me to the actual review).

```
aerwin@us.ibm.com (aerwin@us.ibm.com) has invited you to review the page.
Description:

Click on the Review Link below to enter Maqetta's review and commenting module. If you haven't registered yet with Maqetta and/or are not currently logged into Maqetta, you may need to go through a registration and/or sign-in process before you can start reviewing. If so, you may need to click on the Review Link below once to go to the login and/or registration pages, and then once logged in, you may need to click on the Review Link again.

Review Link: http://lab9.austin.ibm.com:50020/review/aerwin@us.ibm.com?revieweeuser=aerwin@us.ibm.com
```

**Comment by JonFerraiolo** [comment]
@waynevicknair  - I'll bet there are a handful of adjustments in R/C like this one we haven't logged as bugs yet. I hope to take a pass through the whole R/C UI soon and log issues for things I find.

**Comment by aerwin** [comment]
@JonFerraiolo @waynevicknair 

I think this is probably now covered by the design @JonFerraiolo has subsequently put into #1886.
