### ISSUE TITLE
(Firefox) Exception when opening theme editors

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1883]
@billreed63 

@childsb - could you please look into this one?

When running Firefox builds, I'm getting an exception in `getType()` in the line that is doing a substring. To recreate, clone claro to claro2 or custom to custom2 and look in Firebug console. 

Here is the stack trace from the built version:

```
getType(_226d=[])
getRelativeMetaTargetSelector(_2053=["background-color"])
_getClassSelector(_5d8="dvThemeWidget")
_getAllRules()
_buildCssRuleset()
_updateCascadeList()
```

The debugger shows the following code, where the last line below is the line which is getting the exception:

```
,"davinci/ve/themeEditor/metadata/query":function(){
define(["dojo/_base/declare"],function(_226b){
return _226b("davinci.ve.themeEditor.metadata.query",null,{constructor:function(files,_226c){
this.files=files;
this.cache={};
this.lastLoaded=-1;
this.modules=_226c;
this.modulePrefix=null;
this.modulePrefix=".";
if(_226c){
for(var i=0;i<_226c.length;i++){
this.modulePrefix+="/"+_226c[i];
}
}
},getType:function(_226d){
var type=null;
if(_226d.declaredClass){
type=_226d.type;
}else{
type=_226d;
if(type.substring(0,5)=="html."){
tagName=type.substring(5);
}
```

**Comment by aerwin** [comment]
Per scrum today, I'll take a look at this one.

@JonFerraiolo which build and/or server were you using? I'm not seeing that particular exception with FF or Chrome with local install, lab9:50020, or when running from my dev environment.

BUT, in all cases, I see the following where it's having trouble loading the css file for the new theme::

"NetworkError: 404 Not Found - http://localhost:50000/maqetta/user/maqettaUser/ws/workspace/project1/themes/claro3/project1/themes/claro3/claro3.css"

Looks like "project1/themes/claro3" appears twice in the path. So, I can look into that (which could potentially lead to exceptions like you mention).

**Comment by aerwin** [comment]
@JonFerraiolo Ok, I finally saw an exception, but I had to change something in the new theme (like button background) and then reopen. Using Chrome when running Maqetta from Eclipse, I see the following (which maps to the `tagName = type.substring(5);` line in Jon's exception):

```
Uncaught TypeError: Object  has no method 'substring'
declare.getTypequery.js:25
declare.getRelativeMetaTargetSelectorContext.js:2386
declare._getClassSelectorCascade.js:1077
declare._getAllRulesCascade.js:410
declare._buildCssRulesetCascade.js:456
declare._updateCascadeListCascade.js:573
declare._widgetSelectionChangedCascade.js:1006
declare._updatePaletteValuesSwitchingStyleView.js:357
declare._stateChangedSwitchingStyleView.js:367
hitchlang.js:155
target.(anonymous function)aspect.js:181
on.emiton.js:261
on.emiton.js:297
Evented.emitEvented.js:28
publishtopic.js:21
connect.publishconnect.js:193
declare.setContent.context._setSource.dojo.hitch.initialSetVisualThemeEditor.js:113
hitch
```

**Comment by aerwin** [comment]
@JonFerraiolo @billreed63 @childsb 

Per the scrum, I've pushed out changes in my branch that I think address the core problem seen by @JonFerraiolo. I'll schedule a short discussion for this afternoon to quickly review.

These changes do not address the error loading [themename].css I mentioned a couple posts ago. I've opened a separate problem (#1899) for that (less critical) one.

**Comment by aerwin** [comment]
I've merged the fixes for this into master.
