### ISSUE TITLE
Clicking on overlay widget in Scenes palette should select widget

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1884]
Maybe this worked before I rewrote the States palette (and renamed Scenes), but not working now.

You should be able to click on an overlay widget in Scenes palette and cause it to be selected just like clicking on it in Outline palette.

But not until after M5!

**Comment by billreed63** [comment]
AppStates throws exception when opening theme editor

```
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined AppStates.js:896
(anonymous function) AppStates.js:896
target.(anonymous function) aspect.js:181
on.emit on.js:261
on.emit on.js:297
Evented.emit Evented.js:28
publish topic.js:21
connect.publish connect.js:193
declare.setContent.context._setSource.initialSet VisualThemeEditor.js:100
hitch lang.js:155

```

**Comment by peller** [comment]
@billreed63 works for me, and there appears to be ample null checking at that line.  What steps are needed to see this?

**Comment by billreed63** [comment]
it is working in todays code from master
