### ISSUE TITLE
Cascade.js and ViewLite.js exceptions

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1887]
@childsb - I'm hitting a couple of exceptions in Cascade.js. Can you please investigate/fix?

First exception I ran into is in this code (starting ~485), almost surely because variable `i` is used as the index for both the inner and outer loops:

```
                    else if(!allRules[i].shorthand && allRules[i].type=="element.style"){
                        for(var i=0;i<rule.length;i++){
                            if(rule[i].hasOwnProperty(this.target[0])){
                                allRules[i].value = rule[i][this.target[0]];
                            }
                        }
                    }

```

Second exception is in ViewLite.js:37 where widget is undefined with an attempted reference to widget.subwidget. I get this when the Background pane of the Properties palette is open and I unselect widgets by clicking on part of the canvas where there are no widgets.

**Comment by childsb** [comment]
Good spot on that first code snippet.  Do you have a recreate of the problem so I can verify it's fixed?

**Comment by JonFerraiolo** [comment]
I don't have a concrete scenario for duplicating the problem. What I was doing was simply create a DIV with a fixed size height, then set background-image to point to an image file, and then in right-side properties palette change background-repeat and background-size, and then selecting/deselecting the DIV. Playing around in this general area generated the two exceptions I listed above.

**Comment by childsb** [comment]
Also on the second problem, is there any specific widget that needs to be on the page?  I've added a handful and cant reproduce.
