### ISSUE TITLE
Exception when switch to split source view

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1889]
1. New HTML file
2. Click Split Vertically toolbar button
3. Click Split Horizontally toolbar button

```
Uncaught TypeError: Cannot call method 'getPropertyValue' of undefined
_1b6d._getPaddingdavinci.js:40068
_1b6d._calculatePaddingdavinci.js:38672
_1b6d._createContentdavinci.js:39506
_1b6d._createView._createViewTimerdavinci.js:39376
```

Making low priority because not noticing any negative side effects.

Environment: Chrome, local install on windows

**Comment by peller** [comment]
appears not to happen on FF, and it appears to be coming from a timer in Orion, so the exception doesn't blow the davinci stack, at least.  It's been a while, maybe we should attempt an Orion upgrade.

`this._frameWindow.getComputedStyle(node, null)` returns undefined on a valid node

**Comment by jhpedemonte** [comment]
If we upgrade Orion editor, let's wait for M6.

**Comment by peller** [comment]
dup of #1663
