### ISSUE TITLE
Enter/return key should complete field or map to OK button on all dialogs and palettes

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#189]
Need to research all of the dialogs and make sure all of them allow the
Enter/Return key to do the right thing.

**Comment by JonFerraiolo** [comment]
Assigned to @jhpedemonte who might pass onto others

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg

**Comment by jhpedemonte** [comment]
-> M7

see #1475

**Comment by doronrosenberg** [comment]
fixed by db1bf569043c65dced7cca92d9d2ebbc659fda6c - ctrl-enter will now submit
