### ISSUE TITLE
Reopening 4404944: Outline is collapsed when changing views

### ISSUE THREAD

**Issue by wnm3** [maqetta/maqetta#1890]
The problem isn't related to support for copy/paste... it is related to having a lengthy expanded outline that gets collapsed when you change views. The problem was exacerbated by another problem where clicking on the slider bar caused an attached window to the mouse pointer...

The use case is:
I've expanded the outline to find and select a particular widget that may be within several containing widgets.  I make a change and switch views to see how things look (not using the split view so I can see more code in the editor). Switching back from display to the html mode the outline is collapsed and I have to go through manually expanding the outline tree to get back to my widget.

The request is:
Don't collapse the outline view when switching views, please leave it as it was unless an action is taken on the display content to reposition on another widget.

Thanks for your help.

**Comment by JonFerraiolo** [comment]
Setting to Prio-High for M6. This is an important usability issue. I'm not sure all that we need to do here to provide a good UI, but one thing is that we should auto-expand and auto-scroll the Outline to show the currently selected widget.

**Comment by peller** [comment]
if there's a way to get at the tree's cookie information, we should use it to save/restore the state of the tree when switching views

**Comment by peller** [comment]
the right way to fix this is to redo the outline tree to use a model and not refresh by replacing all the items.  the wrong way to fix this was [this workaround](https://github.com/maqetta/maqetta/commit/9ab001e506b781739138db9885908a4c62e0d88b) which I was hoping would provide a temporary fix here as well.  When switching views, multiple refresh events (command stack + setSource) seem to be hitting the tree in such a way that it gets in a bad state and no longer expands nodes.  Thinking we should push this issue to a future release when we can fix it properly.

**Comment by JonFerraiolo** [comment]
> which I was hoping....

How well does the workaround work? When I tried it last night, it seems to keep the Tree expanded in the cases I tried (although with some screen flashing)

**Comment by peller** [comment]
I think the tree flashes as it did before, since all of the elements are being replaced in the model.  The workaround appears to work well for #2045 (command execution) but not for switching views in this issue, as mentioned above, where the two refreshes in a row result in closed tree nodes.

**Comment by peller** [comment]
-> M7

**Comment by peller** [comment]
see #750

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg hopefully falls out of #2524

**Comment by doronrosenberg** [comment]
@JonFerraiolo 

The design and source view should both show the same outline palette contents, there should be no difference right?

**Comment by JonFerraiolo** [comment]
that's correct

**Comment by doronrosenberg** [comment]
In that case #2524 should fix that.

The bigger question is what about switching files.  Right now we rebuild the tree each time we change files via tabs, but we don't persist expansion.

**Comment by JonFerraiolo** [comment]
would be good to persist the expansion, wouldn't it? if non-trivial, then we could create a bug to persist expansion sometime in the future

**Comment by doronrosenberg** [comment]
I opened #2596 for that.

**Comment by doronrosenberg** [comment]
fixed by #2524
