### ISSUE TITLE
images can't be dropped onto cavas (old issue #510 resurfacing?)

### ISSUE THREAD

**Issue by airazabal** [maqetta/maqetta#1891]
When I drop an image onto Maqette - it opens a new browser window - although it does seem to recognize the dnd operation since I see a green + ...
I am using Chrome on Mac OSX 10.7

**Comment by peller** [comment]
We don't support dragging files from the desktop, only from the files palette in maqetta

**Comment by airazabal** [comment]
well, that explains it then...thanks.

**Comment by JonFerraiolo** [comment]
Supplemental comments: (1) at some point we probably will support drag/drop from desktop leveraging the new drag/drop features in HTML5, (2) the "+" icon is from Chrome, not from Maqetta
