### ISSUE TITLE
Editing custom theme throws js errors, can't switch states

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#1894]
I cloned Claro, changed the button backgroundcolor/textcolor for normal state and the same for textbox.  I then changed the colors for the Hover state as well for the 2 widgets.

After saving, I close then tab, reopen the theme and get the following error:

type.substring is not a function
http://lab9.austin.ibm.com:50010/maqetta/app/davinci/davinci.js?af251c22df58d35291d804d3110089cda802b44d
Line 49022

Same error happens each time I change states.

Reloading the page fixes it.  edit the theme, save, close tab, reopen and same errors again.

Firefox 10.0.1 on windows.

**Comment by aerwin** [comment]
This sounds a lot like #1883 (though I don't think you have to change states to see it). Hoping a dup, but will leave open for time being.

**Comment by aerwin** [comment]
I've decided this isn't really a dup of #1883. The fixes for #1883 help the situation here (eliminating the JS error), but that JS error is independent of state changing. From what I can tell after the fixes for #1883, the first state change initiated by the user is not recognized. And, I believe this is due to code involving the `this._silent` in `davinci.ve.views.StatesView` that blocks the first publication of the state change event:

```
 if (this.isThemeEditor()){
                    if (!this._silent) {
                        this.publish("/davinci/states/state/changed", 
                                [{editorClass:currentEditor.declaredClass, widget:'$all', 
                                newState:item.name[0], oldState:this._themeState, context: this._editor.context}]);
                    }
                    this._themeState = item.name[0];
                    this._silent = false;
                } else if(currentEditor.declaredClass == 'davinci.review.editor.ReviewEditor') {
                    this.publish("/davinci/states/state/changed", 
                            [{editorClass:currentEditor.declaredClass, widget:context ? context.rootWidget : null, 
                            newState:item.name[0]}]);
                } else {
```

**Comment by aerwin** [comment]
Upon further exploration, it appears the only time the value of `this._silent` is consulted is in the "onclick" handler for the states view. Perhaps the flag once served a purpose, but it really doesn't make sense to ever ignore the user-initiated click in the "onclick" handler. So, my proposal is to remove all code related to the `_silent` flag in `StatesView`.

**Comment by aerwin** [comment]
@doronrosenberg I've merged the fixes for this into master.
