### ISSUE TITLE
Clicking on review link should auto-open review editors

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1896]
@jhpedemonte, @childsb, @peller , @aerwin 

I didn't see a bug for this, but we have certainly talked about this.

When an author creates a review invitation, reviewers each receive an email with a hyperlink for a given review, and that review might consist of N files (usually HTML files).

With the integration of reviews into the main application, it is imperative from a usability perspective that clicking on the hyperlink will not only launch maqetta, but also open up review editors for the N files that are included in the review.

What I propose is the following:
- The email invitation includes a URL parameter that provides some sort of ID that can be mapped to a particular review session
- Clicking on the hyperlink causes the URL parameter to be passed to the Maqetta server, which somehow gets transmitted to the client, and the client then opens up review editors for each of the N files that are included in this review session, and makes sure that the first file in the review session is selected when the session starts. (We should not auto-close editors from workbenchSettings because doing so might cause unsaved files to become unsaved zombies)

Assigning to @waynevicknair, but I'm wondering if maybe @childsb or @aerwin could help out here

**Comment by JonFerraiolo** [comment]
Another thought. If N > 10, maybe only open first 10 files, just in case an author is confused by the "new review" wizard and somehow picks all files in his workspace instead of just a few files.

**Comment by childsb** [comment]
Partial fix in branch https://github.com/maqetta/maqetta/tree/RC_open_editor

Caveat: review editors aren't persisted on browser refresh.  The format of workbench.settings isn't compatible with the R&C paths which require version + path string.

**Comment by childsb** [comment]
Fixed with this merge from branch RC_open_editor:

https://github.com/maqetta/maqetta/commit/7dba479b287ea3d7efafd3ef2a0d8072ad842b63

Reviewed by @waynevicknair before merging.
