### ISSUE TITLE
Auto-expand current review in Reviews palette

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1897]
Assigning to @waynevicknair, but maybe @peller or @aerwin can help here

Related to #1896

When a reviewer clicks on the hyperlink in the review email, issue #1896 says that the files associated with that review should appear in newly opened review editors.

This issue is that in addition to opening the review editors, the Reviews palette should auto-expand the given review (i.e., the one in the URL parameter) so that the HTML files show at startup, and auto-close all of the other reviews. Right now, the default behavior is that all reviews are closed and user has to manually click on + icons to open.

**Comment by aerwin** [comment]
Per phone discussion with @JonFerraiolo, @childsb, and @billreed63 just a bit ago, I'll take ownership of this one.

**Comment by aerwin** [comment]
@JonFerraiolo @childsb @JonFerraiolo 

Given the design in #1896 to open up to 10 review files....Do we really just want the tree in the Reviews tab to be expanded when a review is opened via e-mail link, or do we perhaps want to make independent of clicking a link and just go ahead and always tie this to editor selection? 

My proposal would be that when an editor is selected that if it's a Review Editor, the tree in the Review Tab would be expanded to show the review represented in the editor. In addition, I'd select this node in the tree. Thoughts?

**Comment by JonFerraiolo** [comment]
My opinion on this subject:
- Whenever a review editor is opened at startup, we open up the corresponding review's tree node in the Reviews palette
- (As @aerwin suggests above) Whenever a review editor becomes the current editor, we open up  the corresponding review's tree node in the Reviews palette
- At startup, we always open the tree node for the most recent review (if it wasn't already opened by the previous bullet)
- We don't persist (into cookies) the state of Review's palette Tree widget across sessions

I'm trying to make it so that users will tend to see the HTML files within any active (or the most recent) reviews in which they are participating. For first-time reviewers, I expect they will have trouble understanding that they need to (a) go to the Reviews palette (b) then open up reviews (c) then double-click on HTML files. At least we can help them with (a)/(b)/(c) if they click on the link in the review invitation, and by preserving open editors across sessions, and we can at least help with (b) in case the review editors haven't been preserved across sessions.

**Comment by aerwin** [comment]
Thanks, @JonFerraiolo... For clarification, for this particular issue I will be subscribing to "/davinci/ui/editorSelected" so when a review editor is selected, I'll expand the review tree based on the file in the editor. @childsb is working separately on opening editors at start-up. But, my code should work no matter how an editor is opened (whether by user or by @childsb's start-up code).

**Comment by aerwin** [comment]
@childsb I merged my changes, and I think things work like we want now. E.g., when I used the link in the message for a new review it brought up the review and my new code expanded the tree.
