### ISSUE TITLE
Reviewers shouldn't be able to close/open/edit reviews

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1898]
@aerwin, @peller, @childsb, @jhpedemonte ,

The Reviews palette shows 3 icons at the top: close, open and edit. 

The author who created a review session should be able to close, open and edit reviews, but reviewers (who are not the author) should only be able to open the files within a review.

We probably should have different visual styling for reviews that the user created and reviews that other people created. We should have separate CSS classes for these two cases so we can fool around with visual styling of these two cases. My initial thought is that reviews that the user owns should be boldface and other reviews should use normal text styling.

**Comment by jhpedemonte** [comment]
Reassign to @aerwin.  Assess risk for M5, push to M6 if too risky.

**Comment by aerwin** [comment]
@JonFerraiolo @peller @childsb @jhpedemonte @waynevicknair 

Looks like the behavior has changed sometime in the last 12 days, and when I come in as the reviewer the toolbar with the 3 buttons is not shown. In addition, all of the menu options (when right-clicking on the resources in the Reviews tab) are disabled. So, @JonFerraiolo , unless you disagree I think that part of the defect is no longer an issue.

For the 2nd part, in theory it would be pretty easy to implement a getLabelClass handler for the tree (like we do for getIconClass). But, there's a larger issue in that there doesn't appear to be a way to show both reviews you've created and reviews you've been invited to in the tree. 

I think that is perhaps the intent of #360 from 11 months ago (which is unprioritized and unassigned). If so, I'd suggest we close this issue and get #360 on the books for M6 (perhaps as a high priority feature request). Are there any thoughts/disagreements?

**Comment by jhpedemonte** [comment]
> But, there's a larger issue in that there doesn't appear to be a way to show both reviews you've created and reviews you've been invited to in the tree.

Can you give more details here?  Are you saying that we don't have the proper APIs to query both self-created reviews and subscribed reviews?  Or that those are not both added to the tree?

Assuming others don't have any insight that might help this bug for M5, I'm fine with your suggestions about #360.

**Comment by aerwin** [comment]
There are both not added to the tree... E.g., If you log-in you _only_ see reviews you've created _unless_ you log-in with the link in the e-mail in which case you _only_ see reviews that you've been invited to. This is just how it's been coded up, and I think the point of #360 would be to revisit that design point.

**Comment by aerwin** [comment]
Closing per comments above.
