### ISSUE TITLE
R&C not sending invites from localhost 

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1900]
On OSX running in eclipse:
1) new review
2) add an html file
3) add a reviewer email
4) publish
5) notice error "Can not send email"

This worked previously from localhost with no issue

**Comment by jhpedemonte** [comment]
Setting to priority low for now, since this doesn't seem like a huge deal (at least to me).  Feel free to elevate as necessary, but this will probably have to wait for M6.

@JonFerraiolo

**Comment by jhpedemonte** [comment]
-> M6

**Comment by waynevicknair** [comment]
this is a result of our flakey smtp relay server. i am loath to add complex retry logic to the R&C for what seems a _very_ specific case, namely running localhost inside the firewall.

closing. re-open is feelings are strong. seems like a non-issue to me.
