### ISSUE TITLE
Review tab toolbar buttons fail

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1901]
1. Create review
2. Activate Reviews Palette
3. Select top-level node (say "version 1") to enable toolbar buttons
4. Click ""Close Version" button (1 st button)
5. Click on on "Are you sure you want to close this version?" dialog and see following exception:

```
Uncaught TypeError: Cannot read property 'resource' of undefined
declare.runCloseVersionAction.js:18
declare._closeVersionCommentExplorerView.js:155
hitchlang.js:153
declare._onClick_ButtonMixin.js:44
inheriteddeclare.js:191
declare._onClickButton.js:70
hitchlang.js:153
handles_OnDijitClickMixin.js:82

```

the problematic line in `CloseVersionAction` is the following:

```
var item = selection[0].resource.elementType=="ReviewFile"?selection[0].resource.parent:selection[0].resource;
```

The "Edit Version" button fails similarly, but in `EditVersionAction`.

**Comment by JonFerraiolo** [comment]
@billreed63, @aerwin, @childsb - if any of you want to grab this one, please reassign to yourself

**Comment by aerwin** [comment]
I'll go ahead and take it since I found it.

**Comment by aerwin** [comment]
@billreed63 @childsb @JonFerraiolo 

I've got a good handle on how to fix the exceptions, but I'm a little confused about what `davinci.review.actions.CloseVersionAction` and `davinci.review.actions.OpenVersionAction` are supposed to do. They both do a dojo.xhrGet to "maqetta/cmd/managerVersion" and end up changing the tree expansion (e.g., CloseVersionAction collapses node) based on the result. But, nothing else happens.

Are these legacy actions that perhaps need to be rethought now that review stuff is more tightly integrated? Is the xhrGet necessary? Is the real intent to actually open/close review editors based on the selection when the action is taken?

**Comment by aerwin** [comment]
I got clarification on these actions during a post-scrum discussion... It turns out CloseVersionAction and OpenVersionAction are poorly named and are really intended to "lock" and "unlock" the review (or "freeze" and "unfreeze"). The group agreed they should be labeled differently in the UI, but @JonFerraiolo wanted to wait until M6 after more discussions with the UI design folks. I've opened a separate issue for these label changes (#1905).

**Comment by aerwin** [comment]
Work on this one turned out to be more than it appeared when I started. Aside from getting toolbar buttons not to crash with an exception when clicked, there were also issues with the tree not refreshing after tasks were executed, pop-up menu tasks failing, etc. But, things are working a lot better now after merging my changes.
