### ISSUE TITLE
Need error handlng for registration failure

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1903]
Best I could guess, one of our users tried registering at a point where the Java process was out of memory and hung, but Joomla was still running.  The registration failed, and the user directory was not created, but Joomla left the user logged in with no error.  The user could not attempt to re-register until manually signing out (and possibly clearing cookies to register with the same filename), and the user had no idea that she had to re-register.

Joomla should
- post an error message
- leave the user logged out, clearing session cookies as needed
- possibly log the event somewhere

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte (so this doesn't fall through cracks)

**Comment by JonFerraiolo** [comment]
@childsb 

-> @jhpedemonte M7 Prio High (so this doesn't fall through cracks)

**Comment by jhpedemonte** [comment]
Closing.  With Orion, use can re-register with same address, sending out another email.
