### ISSUE TITLE
R&C: Clean up terminology on menu items and toolbar buttons

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1905]
This is a spin-off from #1901. The Close/Open actions in the Review tab are really intended to lock/unlock or freeze/unfreeze the selected review. So, we need to find some better terminology for the UI other than "Close Version" and "Open Version".

**Comment by aerwin** [comment]
@waynevicknair @childsb @JonFerraiolo

**Comment by jhpedemonte** [comment]
-> M7/Tony

**Comment by aerwin** [comment]
-> Changing label from "Usability: Close/Open actions in Review tab need to be labeled differently" to "R&C: Clean up terminology on menu items and toolbar buttons"

**Comment by aerwin** [comment]
Closing with above commit.
