### ISSUE TITLE
Outline doesn't open to show ToolbarButton

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1909]
(Not sure if you wanted to handle this for M5, since you've already done most of the work.)

Adam fixed it so the Outline tree opens to the currently selected widget.  But it doesn't work in all cases:
1. New page.
2. Drop **ScrollableView**.
3. Add **Heading** to view.  -> Will see an error in console here.
4. Add **ToolbarButton** to Heading.  -> Outline will not open up to show ToolbarButton (most likely because of error).

**Comment by peller** [comment]
Follow on from #1823.  Hopefully we're no worse off than we were before, but sometimes it doesn't work.  In such cases, the set('paths') line in ToggleTree.js throws an exception (currently squelched)

Jon pointed out another scenario where this happens - a tabcontainer with a button inside a contentpane.  For some reason, the tabcontainer was showing up twice when traversing the widget hierarchy, and that clearly does not match up with the widget path in the outline.

**Comment by peller** [comment]
fixed in 8dee9a95b9735730e34273bbc88c9d726aa6ed9a
