### ISSUE TITLE
Only open review editors for HTML files

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1912]
.js and .jpg files do not permit commenting, so clicking on one of those files in the review tab should probably just open a regular editor.

**Comment by JonFerraiolo** [comment]
Actually, I think we should close this issue. The review editor works on any file: images, SVG, CSS, JS. It shows the content and then allows commenting and annotations, even on source editor such as *.css. That's goodness!

**Comment by JonFerraiolo** [comment]
After chatting with @peller, closing this.
