### ISSUE TITLE
URL param for opening w/o any open editors

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1914]
(spun off from #1032)

Add support for a URL param to the main maqetta URL which loads Maqetta without any open editors (overriding persisted editors).

Main reason is to recover from errors where open files may cause loading issues.

---

One complication with this approach:  what do we do about persisted open editors which had unsaved changes?

@JonFerraiolo @peller

**Comment by JonFerraiolo** [comment]
Regarding "persisted open editors which had unsaved changes", I think we are generally OK. To the user, it will look like they have a file1.html in their workspace and they won't know that it is in a dirty state. If they open it, then they will get the workingcopy version (95% certainty). But we need to test this to make sure nothing breaks in this scenario where there are workspace files that have unsaved workingcopies that aren't active editors.

**Comment by JonFerraiolo** [comment]
I poked around a bit on this one. I tried to add a magic keyboard key that a user could press while Maqetta was loading, which would cause Maqetta to launch without any open editors, but I don't think that approach is viable for two reasons: (1) keyboard focus at launch time is often in the browser chrome (e.g., URL bar) and not in the Maqetta document, (2) with AMD, the application often starts so fast that the user would have difficulty anyway pressing a key before the app started loading editors. In my experiments, I wasn't able to register a keydown event (although keyup was caught).

My current thinking:
- URL parameter `fresh=1`
- DavinciPageServlet.java checks for that parameter and saves yet another cookie (`fresh`) depending on whether the URL parameter is present or not.
- Runtime/Workbench look at the `fresh` cookie. If its value is `1` then don't open existing editors

**Comment by jhpedemonte** [comment]
Well, we shouldn't even need a cookie. Just write JS code to check for the URL parameter.

**Comment by JonFerraiolo** [comment]
Hasn't the URL parameter been tossed away by the server? If not, then sure, we don't need a cookie.

**Comment by jhpedemonte** [comment]
URL parameters (i.e. "http://foo.com/bar?param=1") get passed to the server.  Hash values (i.e. "http://foo.com/bar#param") are only client side.

But we don't need to involve the server here.  The client side JS is what opens the editors.  We just check for the param at that point.

**Comment by childsb** [comment]
There's a couple issues to keep in mind--

1) This will duplicate functionality as we have workbench.settings file to load open editors on startup.
2) Not all of our code appreciates URL parameters.  Leaving URL params in the location.href  may break things.

We have a nearly identical issues with selected project.  I got around these by:

1) Parsing URL paremeters in pagedesigner.html.  After you get the values, modify the workbench.settings file to line up
2) Remove URL parameters and refresh the page.  

This synchronizes the two areas of functionality and cleans out URL parameters.

In regards to the "what to do about open/dirty editors", you may get this function for free.  I believe if there is a file1.html.workingcopy on the server, and you try to open file1.html from explorer view, it will open the working copy and show the file as the dirty state.

**Comment by childsb** [comment]
You can now use URL parameter resetWorkbenchState to totally reset the workbench state.  

I also added a checkbox on the login page to do the same thing as extra credit.  Let me know if that should be removed or renamed.

**Comment by JonFerraiolo** [comment]
Reopening issue. When I set URL to this: `http://localhost:50000/maqetta/?resetWorkbenchState=1`, the application did in fact open with no editors open, but then the URL bar said `http://localhost:50000/maqetta/?` and when I double-clicked on Sample1.html, the app just kept spinning without the file ever appearing.

If I then remove the `?` from the URL bar and hit return, then Sample1.html appears correctly.

**Comment by childsb** [comment]
jon, what browser?

**Comment by JonFerraiolo** [comment]
Mac Chrome

**Comment by childsb** [comment]
Fixed the ? issue with this checkin:

14a3498ac303a49a4c8c1a35705489d53397cc9b
