### ISSUE TITLE
Smart Input appears, then immediately disappears

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1917]
Testing on Firefox:
1. New HTML page, set to **android_340x480**.
2. Add a **Heading** widget.

Notice that the smart input appears then immediately disappears.

**Comment by billreed63** [comment]
It appears that FF 11  is firing a onBlur event, smartInput is catching the onBlur and closing the smartInput.
I tested preview 4 on maqetta.org and it has the same problem. So this is a problem with FF, I will keep looking for a work around..

**Comment by billreed63** [comment]
In ve/Context.onMouseUp we are calling `this.getContainerNode().focus();` this is happening after the smart Input is opened. This call to focus is what is causing FF to fire the onblur, which dojo is catching add calling the smart input onBlur.

I removed the call to  `this.getContainerNode().focus();` in ve/Context.onMouseUp It fixes the issue on FF and seems to have not negative side effects. I don't think it was needed in the first place...
