### ISSUE TITLE
Auto-create User Account if Joomla Login Successful

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1920]
at some point in time we used to create the user directory if it didn't exist but a user successfully logged in through Joomla. it looks like we somehow lost this logic.

**Comment by jhpedemonte** [comment]
So what does that mean?  What is the problem currently?

@JonFerraiolo

**Comment by peller** [comment]
is this what happens if the JVM is hung (out of memory) when the user creates the account initially?

**Comment by JonFerraiolo** [comment]
My theory is yes

**Comment by waynevicknair** [comment]
commit 4724bf4567e2756eb24ac0c13b683924d85911c3 contains java changes

corresponding PHP changes in commit 9f8b1a366dd2f4722dadbe633179f22d716f685f to INTERNAL repository

**Comment by jhpedemonte** [comment]
Are there any security implications here?  For example, where does the plugin name ("joomla" in this case) come from?  If it's just a URL param, is there the possibility of someone creating a malicious request to have the app generate workspaces for unregistered users?

**Comment by jhpedemonte** [comment]
Reverted by ab8f2d659b5d4ef4eb0c0df8d12a4355b7577ee8 (github repo) and 8ac90534767541ce6848ca39b7518feab932d635 (internal repo).

Reopening bug for M6.

**Comment by waynevicknair** [comment]
this is a duplicate of issue #1903 which is broader and allows more latitude in solutions.
