### ISSUE TITLE
Background dialog console message if choosing image

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1923]
Very much OK to push this to M6, but it might be a fairly safe fix.
- New HTML File - desktop hi-fi page
- Add a DIV
- Bring up Background dialog
- Set background-image type to "image"
- Click on button to bring up file selector dialog. 
- Choose SampleBanner.jpg

Result=> Console message: `GET http://localhost:8081/maqetta/SampleBanner.jpg 404 (Not Found)`

This message is coming from BackgroundDialog.js:447, when we attempt to put a background-image property onto the preview rectangle within the Background dialog. We need to transform the URL from user doc URLs into Maqetta URLs - instead of setting background-image to `SampleBanner.jpg` we need to set background image to something like `<serverroot>/maqetta/users/<username>/ws/workspace/projects1/SampleBanner.jpg`. 

There is some logic in ImageDragSource.js that shows how to do this transformation, but I thought I should leave this code change to the expert (@childsb) to make sure that I didn't mess up.

In particular, it seems we have to be careful to take care of the case where there is an Eclipse project with an extra `WebContent/` folder.

One quick note. In function `_updateBackgroundPreview()` there are two data structures, `a` which holds the text version of the background-image property that will end up getting stuffed into the user's source code, and also `this.bgddata` which holds the raw data from the dialog. It is probably easier and simpler to use `this.bgddata.url` instead of trying to parse `a`.

**Comment by childsb** [comment]
I fixed the relativity URL calculation in background image (would have broken for images in sub directories).  However, the image preview part was a bit too complicated for this milestone.  It would require unspinning the URL relativity.

So for now, if the background is an image its not shown in the preview (and no error in console).
