### ISSUE TITLE
Can't change padding on Button in clone of sketch theme

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1929]
- Clone sketch theme to sketch2
- Select Button
- In Properties palette, Padding/Margins, change padding from '2px 4px 4px 4px' to '0px 2px 2px 2px'

Result=> Nothing happens. The change doesn't take for some reason. (Works if you clone claro, however)

**Comment by billreed63** [comment]
fixed with delta themes, sketch now uses the same theme meta data as claro.
