### ISSUE TITLE
Session timeout logic problems

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1930]
@peller, @jhpedemonte, @aerwin 

After experience lots of unexplained problems that I had with Maqetta where session timeouts didn't seem to be happening in a predictable way, I tried to some experiments to see what happens if I had a very short session timeout out (e.g., 12sec).

I need to dig in deeper, but I'm pretty sure that we aren't checking HTTP return codes for all possible requests. As a result, there are situations where the session has timed out, but the client still runs, and only with the next server request where we actually check the HTTP return code do we redirect to the login page.

For example, in doing a grep for xhrPut, I am seeing this:

```
Workbench.js:1494:      dojo.xhrPut({
model/resource/File.js:66:      var defered = dojo.xhrPut({
workbench/Preferences.js:14:        dojo.xhrPut({
```
- The first one (Workbench.js:1494) is _updateWorkbenchState, which does not check the server return code for error.
- The second one (File.js:66) appears to check for errors, but simply echoes the error to console instead of invoking Runtime.handleError().
- The third one (Preferences.js) does not check for error.

For xhrGet, we have about 10 calls, and as far as I can tell, only a couple of them check the HTTP return code and redirect to Runtime.handleError. The main one is Runtime.js:serverJSONRequest(). I'm pretty sure that 99% of the time that the user gets redirected to the handleError() logic is due to something going through serverJSONRequest. 

But as I said earlier, the lack of similar checks in other parts of the code appears to result in the user being able to continue doing various editing tasks even though server requests are failing silently in the background.

**Comment by peller** [comment]
I'm not usually a big fan of pub/sub, but if the behavior we seek is that ALL xhr requests should redirect on certain types of errors (auth errors only?) then we might want to use djConfig.ioPublish.  xhr has a facility which will publish an event on each error, which can then be handled by a single handler (the Workbench?) with no need to wrap or repeat code.

**Comment by jhpedemonte** [comment]
Or, we can make sure that all server calls go through one point in the code, and then add the correct logic there -- check return codes to see if the server says user session has expired.  That is, instead of doing direct XHR calls (or Dojo XHR calls), create an object whose sole responsibility is to handle requests and calls to the server.

**Comment by peller** [comment]
They do go through one point in the code: dojo.xhr.  We don't need to create another layer for this.

**Comment by JonFerraiolo** [comment]
Assigning to @billreed63 

Session timeout value is set at:

```
maqetta.core.server/src/org/maqetta/server/IDavinciServerConstants.java:97: 
     public static final int SESSION_TIMEOUT = 60 * 60; // time in seconds
```

**Comment by billreed63** [comment]
After doing a little testing and coding this is what I think we are seeing..
if the client does a put the season inactivity is reset, but we only do a put if the file is dirty. so we put a "working" version to the server on the auto save. once we have auto saved the working copy we do not do another auto save unless the content has changes.

so by doing as @peller suggests and adding the code to subscribe to all `/dojo/io/error`   we can check for 403 errors and then send the user to `Runtime.handleError`

**Comment by peller** [comment]
My suggestion would be to wire `/dojo/io/error` directly to `Runtime.handleError` and put the logic to check for 401 as well as the redirect in there, and do the same for `Runtime.serverJSONRequest`  Also, have handleError put up a console.error or console.warn for everything that isn't a 401.  If our server is returning a 403, it probably shouldn't be.  The spec says that for a 403,
    "Authorization will not help and the request SHOULD NOT be repeated."

**Comment by JonFerraiolo** [comment]
Isn't it 401, not 403?

```
Unauthorized 401

The parameter to this message gives a specification of authorization schemes which are acceptable. The client should retry the request with a suitable Authorization header.

Forbidden 403

The request is for something forbidden. Authorization will not help. 
```

**Comment by billreed63** [comment]
we get a 403 when we attemp a put after a season time out a 401 on a get
