### ISSUE TITLE
Dragging button into Dialog throws error

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#1940]
Dragging button into Dialog throws the following error, as does changing the button label:

Could not expand path at dijit_Dialog_0
http://lab9.austin.ibm.com:50010/maqetta/app/dojo/dojo.js?dcd61d1e5e98b2ff9fbfd8589c9e774badc6be44
Line 1746

**Comment by JonFerraiolo** [comment]
Assigning to @peller as a M5/Med because it smells like an outline path bug.

**Comment by doronrosenberg** [comment]
Same happens putting buttons in a Tabcontainer

**Comment by JonFerraiolo** [comment]
After pulling latest code, I'm seeing this with TabContainer also. The error message appears if you drag a TabContainer, then drag a Button into it, but doesn't appear if you save, close, reopen, and then add a Button to the TabContainer that was loaded from the saved file.

**Comment by peller** [comment]
dup of #1913 and #1909
