### ISSUE TITLE
Tutorial: Nested BorderContainer link is broken

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1941]
http://lab9.austin.ibm.com:50010/maqetta/app/docs/index.html#tutorials/BCtutorials

click on "Nested BorderContainers"

The first time, it appears to reload the page.  The next time, this error is seen in the console:

Bad hyperlink. currently_viewed_page=tutorials/BCtutorials, target=tutorials/BCNestecBC.html

The typo is easy enough to fix Nestec->Nested.  But there's something strange -- instead of getting a 404, I think the server (servlet) is sending back a copy of the base url.  At one point, I even saw this send me into an infinite loop, but I cannot reproduce that.

**Comment by JonFerraiolo** [comment]
Reassigned to @peller. Shouldn't this be closed?

**Comment by JonFerraiolo** [comment]
One thing to note: at this point, the content of tutorials cannot contain hyperlinks. It's a long story, but there is logic that does some munging of hyperlinks, and that logic messes up normal hyperlinks to other pages. I've removed all embedded hyperlinks in most of the content because of this.

**Comment by peller** [comment]
I left it open because the server was returning content instead of 404s.  Now I can't reproduce that.
