### ISSUE TITLE
Error trying to switch themes

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1943]
Bill, not sure if you'll be able to reproduce.  Maybe @JonFerraiolo can give it a try as well.

Steps:
1. Download latest "base" build.
2. Start up, testing in Chrome. _Since this was from new download, we're running on a new, clean workspace._
3. I was running the **VE1:SwitchThemes** test, where I added a bunch of widgets on the page, did some copy/paste, undo/redo.
4. Click on **switch theme** button.

=> Got error in **davinci/library.js::getThemes()**,  Line 71 (`system.resource.findResource("*.theme", ...)`) returns an array of length 7, but with each item `undefined`.

**Comment by billreed63** [comment]
I have not been able to reproduce this bug, but I have noticed the following messages in the servers console anytime I open or close a HTML file editor:

```
2012-03-21 10:24:11.691:WARN::/maqetta/cmd/setWorkbenchState: java.io.IOExceptio
n: Access is denied
2012-03-21 10:29:43.312:WARN::/maqetta/cmd/setWorkbenchState: java.io.IOExceptio
n: Access is denied
2012-03-21 10:30:49.868:WARN::/maqetta/cmd/setWorkbenchState: java.io.IOExceptio
n: Access is denied
```

**Comment by jhpedemonte** [comment]
Closing.  I cannot recreate now.
