### ISSUE TITLE
Error when enabling split views

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1945]
While testing VE1 on the latest "base" build on Chrome, I had added quite a few Dojo widgets to page, switched to **absolute positioning** and added some more; added a **sticky note**.

Then I started switching between the different **View Modes**.  I get an error when enabling one of the switch views.

Error is in `_setThemeClass()`, where there is a line like:

```
_1da8.body.className = _1da9
```

In the error cases, `_1da8` is an HTMLDocument, but `body` is undefined.  `_1da9` is "viewContainer".

@peller @JonFerraiolo

**Comment by peller** [comment]
dup of #1394
