### ISSUE TITLE
Unable to select subwidgets in theme editor

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1947]
In desktop theme editor I am unable to select a subwidget if the subwidget menu is over another widget. example calendar/monthContainer. the event is passed through and the widget under is selected.

**Comment by JonFerraiolo** [comment]
Theories:
- Maybe there is a mousedown handler on the document but an onclick handler on the popup. Mousedown events get fired before onclick events.
- We might need a stopPropagation or stopEvent on the subwidget selection event handler to prevent further processing
