### ISSUE TITLE
403 Forbidden should not be used when authorization is needed

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1950]
It seems that we should only be using 401, and the i/o error logic handling in Workbench (handleIoError) should be simplified to drop the 403 condition.

from http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**10.4.4 403 Forbidden**

The server understood the request, but is refusing to fulfill it. _Authorization will not help and the request SHOULD NOT be repeated._ If the request method was not HEAD and the server wishes to make public why the request has not been fulfilled, it SHOULD describe the reason for the refusal in the entity. If the server does not wish to make this information available to the client, the status code 404 (Not Found) can be used instead.

see also #1930
@billreed63

**Comment by JonFerraiolo** [comment]
The world is often using 401 to mean strictly that username/password were wrong, not session timeout, and it appears common that 403s are used for timeouts. I have a link of my own that helps to explain this: http://lists.w3.org/Archives/Public/ietf-http-wg/2011AprJun/0256.html

**Comment by JonFerraiolo** [comment]
A better writeup is at http://www.missiondata.com/blog/web-development/83/handling-session-timeouts-and-other-errors-using-ajax/
