### ISSUE TITLE
Runtime.serverJSONRequest issues

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1951]
several issues in this method:
1. the do/while loop seems unnecessary and `ready` is invariant
2. `resultObj` is set in a then callback, but returned.  This will fail for async.  Therefore, this method ought to either return a `Deferred` or, preferably, the callers should just use dojo.xhr directly.  The only thing this method seems to be doing is mixing in the handleAs:json arg, and I think the issues caused by the wrapper hiding the xhr API might outweigh any convenience.  Including this arg probably has less overhead than the method call.

**Comment by peller** [comment]
as an added bonus, removing this method would remove several dependencies on the Runtime module

**Comment by peller** [comment]
can now remove handleError also in favor of the private `sessionTimedOut` function in Workbench with nls resources.

**Comment by peller** [comment]
@childsb, wanted your review of this.  Feel free to reassign to me if you approve.

**Comment by childsb** [comment]
All these changes looks good.

I do like a single entry point for JSON requests (doesn't have to be in Runtime) just to ensure everyone is doing it the same way.

**Comment by peller** [comment]
that would just result in dead code and unneeded dependencies, IMO

**Comment by peller** [comment]
-> @peller

given that we're late in the milestone, I'll do this first thing in M7

**Comment by peller** [comment]
ongoing task to remove references to this function, particularly as we move to async Resource APIs (e.g. #1404)
