### ISSUE TITLE
in CommentView replies expand over other comments

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1952]
in a review session with multiple comments, reply to a comment in the middle of the list. the comment to which you replied will then show a '+' button, the number of replies and the work "Reply". click on the plus button or "Reply" link to expand the reply text. the reply will expand downwards and bleed into the comment below versus having the comment below be shifted downwards to accommodate the required reply real estate.

**Comment by jhpedemonte** [comment]
@aerwin, can you take a look at this?

@JonFerraiolo

**Comment by aerwin** [comment]
Should now be fixed with commit above.
