### ISSUE TITLE
Review asks for log-in when running from maqetta-single-user script from Eclipse

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1957]
With all of the latest code running with the maqetta-single-user from my dev environment... if I create and then try and open a review, I get a log-in screen where the content to review should be:

![Screenshot](http://i.imgur.com/Of4vW.jpg)

**Comment by jhpedemonte** [comment]
-> M6/low

Reason being that running Review & Commenting in single-user mode kinda defeats the purpose.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo to see if this issue still exists

**Comment by JonFerraiolo** [comment]
Closing. I'm pretty sure this got fixed along the way (lots of URL handling server fixes in past month or so). @childsb
