### ISSUE TITLE
Severity change when editing review comment not reflected until review reloaded

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1958]
1. Create a new comment in a review with severity "Unassigned" 
2. Submit the new comment
3. Edit comment and change severity to Low, Medium, or High
4. Hit submit and notice severity icon for edited comment remains "Unassigned"

NOTE: If you set the severity to Low, Medium, or High on creation, then this issue doesn't seem to occur.

**Comment by waynevicknair** [comment]
pushed to M6
