### ISSUE TITLE
Severity icons in review comment pull-down don't reflect severity

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1959]
When adding or editing a review comment, the pull-down for severity has incorrect icons next to each option:

![Screenshot](http://i.imgur.com/MSqLv.jpg)

For example, see the icon with a horizontal yellow bar on it next to Medium for the actual value of the severity field. But, then see the clipboard like icon next to the medium option in the pull-down.

**Comment by jhpedemonte** [comment]
Reassigning to @aerwin.  You just committed a patch dealing with the review CSS, so this might be something similar.

**Comment by aerwin** [comment]
Fixed with e9643ec92db41c9e5e243368186256e65c8a1bae .
