### ISSUE TITLE
Workbench._updateWorkbenchState issues

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1962]
Hopefully this is an easy one...

Can we make this xhr async?  Are there any implicit dependencies on its completion?

Also, should we use handleAs:"json" instead?  JSON.stringify instead of dojo.toJson?

**Comment by childsb** [comment]
handleAs:JSON seems to be only for server RESPONSE.  Not the data posted (got an error when i tried, and the docs indicate the same).

Here's what I arrived at:

_updateWorkbenchState: function(){

```
    if(!this._updateWorkbench){
        this._updateWorkbench = new Deferred();
        this._updateWorkbench.resolve();
    }

    this._updateWorkbench.then(dojo.hitch(this,function(){
        this._updateWorkbench = dojo.xhrPut({
            url: "cmd/setWorkbenchState",
            putData: dojo.toJson(Workbench._state),
            handleAs:"text",
            sync:false
        });
    }));

},
```

my thinking is we need semaphores to prevent multiple XHRs from happening at once and to preserve the ordering.

**Comment by peller** [comment]
hm, ok, but how about using JSON.stringify instead of dojo.toJson?

There are no semaphores in JS, and moving to async I/O is really important.  If ordering is really an issue, I suppose you can add a timestamp to the message and we can toss anything that arrives out of order, though it seems unlikely.

**Comment by peller** [comment]
I'm confused. Why is the Deferred necessary?

**Comment by peller** [comment]
reopening.  Should consider putting these requests on a timed queue, also canceling pending requests rather than waiting for them.  @jhpedemonte
