### ISSUE TITLE
New comment button disabled

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1963]
Created a new review from **Sample1.html** (straight up, no changes).  Later, opened review and tried to add a comment, but the **Add Comment** icon is disabled or inactive.

@aerwin saw the same thing.  He was copied on review.

@JonFerraiolo

**Comment by jhpedemonte** [comment]
Interesting:  **Add Comment** icon is only disabled if I **add an end date**.  If I skip that part, then the icon is properly enabled and I can add comments.

**Comment by waynevicknair** [comment]
update: the date is getting serialized incorrectly in the 'versions.xml' file. specifically, the year is set to 0012 versus 2012. if i hand edit the date in the XML file the review shows as open and the button is enabled. i'm hunting down where the versions get serialized now.

**Comment by peller** [comment]
see also #1969
