### ISSUE TITLE
New Review dialog visual artifacts

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1964]
I noticed a few unwanted visual artifacts/inconsistencies in the **New Review** dialog:
1. There's a small grayish "T" that appears underneath _"1. General Information"_ and _"2. Select Review Files"_ as you go through the wizard.
2. On the first page, the "No files selected" warning should be a single line.

Both of these are **_regressions**_ from M4.

**Comment by aerwin** [comment]
Fixed with 6b4220667782172bbb705c98994ef89652194b12 .
