### ISSUE TITLE
Cannot select text on "Invitation not sent" dialog

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1965]
Testing on Firefox.

I cannot select the text of the **Invitation not sent** dialog.  Users see this dialog when either (1) the SMTP server hasn't been configured or (2) the SMTP server is unreachable or times out.

@JonFerraiolo @waynevicknair 

@peller @billreed63, can either of you guys take a look?  Assign the bug to yourself if you are investigating.

**Comment by peller** [comment]
why is this M5?

**Comment by peller** [comment]
No idea why this regressed.  There are -moz specific tags to make the dialog contents only selectable.  We can easily disable this (and make everything in the dialog, including the title) selectable by removing the -moz-user-select rule in .contentNoSelect in Comment.css

**Comment by JonFerraiolo** [comment]
I researched the old code (when review was off on its own) and the error dialog seems to have had -moz-user-select:none forever. It's certainly there in M4. I figure the contentNoSelect classname on that dialog was a bit of over-reaching by the folks who wrote the original code, so I took it out. Hard to see how removing this class would cause problems.

**Comment by peller** [comment]
It was intended to make the dialog title non-selectable, but the contents selectable.  Makes sense, and seems to work on webkit.  Not sure whether it ever worked on FF.

**Comment by JonFerraiolo** [comment]
My guess is that WebKit allows inner elements with *-user-select:text to override *-user-select:none that is placed on ancestor elements, but Mozilla implements *-user-select:none such that it makes element and all descendants unselectable no matter what *-user-select values are on descendant elements.
