### ISSUE TITLE
Changing style on widget in split screen selects wrong widget

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1971]
1) Create new html file
2) DnD div
3) DnD textbox and drop inside div
4) DnD button inside div
5) split screen vertically
6) select div in visual designer
7) style palette change layout -> width 200px

Result the div style is change to 200px, but then the selects changes to the textbox

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<style>@import "themes/claro/claro.css";@import "lib/dojo/dojo/resources/dojo.css";@import "app.css";
</style>
<script type="text/javascript" src="maqetta/maqetta.js"></script>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'async':true,'parseOnLoad':true,'packages':[{'name':'clipart','location':'../../clipart'},{'name':'shapes','location':'../../shapes'},{'name':'jquery-ui','location':'../../jquery-ui'},{'name':'yui','location':'../../yui'}]"></script>
<script type="text/javascript" src="maqetta/States.js"></script>
<script type="text/javascript">
require(["dijit/form/Button"]);
require(["dijit/dijit"]);
require(["dojo/parser"]);
require(["dijit/form/TextBox"]);</script>
</head>
<body class="claro" dvFlowLayout="true" data-davinci-ws="collapse" id="myapp">
<div style="height: 200px; width: 200px;">
<input type="text" data-dojo-type="dijit.form.TextBox" intermediateChanges="false" trim="false" uppercase="false" lowercase="false" propercase="false" selectOnClick="false"></input>
 <input type="dijit.form.Button" data-dojo-type="dijit.form.Button" intermediateChanges="false" label="Button" iconClass="dijitNoIcon"></input>
</div>
</body>
</html>
```

**Comment by peller** [comment]
I suggest M6.

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte 

Note that the operation succeeds, it's just that the selection goes away when in split mode. Therefore, I'd say this is on the low end of Prio-High. Definitely should fix. Assigned to @jhpedemonte because he has done magic before in restoring selection (e.g., using xpath), but he might want to parcel it out to someone else.

**Comment by jhpedemonte** [comment]
-> @doronrosenberg 

Doron, check out `VisualEditor.refresh()`.  I created this function to record the current selection as an XPath, update the source, then redo the selection using the saved XPath.  As Jon suggests above, may be useful to fix this.

**Comment by peller** [comment]
note that ids are changing again now that #2258 was backed out. might impact your xpaths.

**Comment by JonFerraiolo** [comment]
-> @peller

**Comment by peller** [comment]
seems to work now.
