### ISSUE TITLE
E-mail link for review fails

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1973]
@JonFerraiolo @jhpedemonte @waynevicknair 

Got this e-mail from @JonFerraiolo :

> When I click on the link, I only see a review that I created earlier this morning. Tony's review session doesn't show up in the Reviews palette (let alone does the HTML file appear within a review editor). I copied/pasted the URL into the URL bar of both Firefox and Chrome.
> 
> Jon

Here's what I had sent to Jon (had to send manually because got the dialog that e-mall wasn't configured correctly):

> aerwin@us.ibm.com (aerwin@us.ibm.com) has invited you to review the page.
> Description:
> 
> Click on the Review Link below to enter Maqetta's review and commenting module. If you haven't registered yet with Maqetta and/or are not currently logged into Maqetta, you may need to go through a registration and/or sign-in process before you can start reviewing. If so, you may need to click on the Review Link below once to go to the login and/or registration pages, and then once logged in, you may need to click on the Review Link again.
> 
> Review Link: http://lab9.austin.ibm.com:50020/review/aerwin@us.ibm.com?revieweeuser=aerwin@us.ibm.com&version=20120322103455

**Comment by aerwin** [comment]
@jhpedemonte just sent me a link to a different review that worked for me... not sure if it matters but the review that failed for @JonFerraiolo was named _tony's review_ (note the apostrophe) and had 3 files.

**Comment by JonFerraiolo** [comment]
-> @aerwin

**Comment by JonFerraiolo** [comment]
@aerwin - I didn't close this one, but I suspect this one is fixed too by 4524033d55 . Please close if you believe it is fixed.

**Comment by aerwin** [comment]
@JonFerraiolo Yes, I believe this is fixed.
