### ISSUE TITLE
Annotations not showing on review comments unless edit them

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1974]
@jhpedemonte @JonFerraiolo @waynevicknair 

I went into a review from @jhpedemonte . I added a comment, and then I replied to my comment. The reply included an arrow annotation, but I can only see the arrow if I edit the comment. That is, I don't see it by just selected.

In addition, @jhpedemonte reports the following going to my review:

> so on your review, file1.html.rev, i see the annotations just fine, but mine was the 2nd comment 
> 11:09:30 AM: Javier H. Pedemonte: on Sample1.html.rev, i don't see annotations until i edit the comment; that was comment #1

**Comment by jhpedemonte** [comment]
-> @waynevicknair

**Comment by waynevicknair** [comment]
i was seeing this phenomenon until yesterday morning. i cannot recreate it running eclipse. i'll go to lab9 and see if i can debug from there.

**Comment by JonFerraiolo** [comment]
-> @jonferraiolo

**Comment by JonFerraiolo** [comment]
Fixed by 4524033d55
