### ISSUE TITLE
Cannot see own reviews

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1975]
Testing on lab9:50020.

(using FF)
- Created a new review, with @aerwin and @JonFerraiolo as reviewers.  **Publish failed**, so copied text and manually sent an email to them.
- Tony had created his own review, and I opened his link in the same browser (but different tab).  I was able to see his review and add comments with annotation.
- Closed that tab and refreshed my original tab.  **Only showed Tony's review, but not mine.**
- Tried to log out and back in, but stayed the same.

At this point, Tony had the idea to try a new browser.  So:
- Log out of Maqetta in FF.
- Switch to Chrome and log in there.
- Now I see my review (but not Tony's -- that's #360).

---

So for some reason, the URL parameters from clicking on someone's review seem to hang around and prevent the user from seeing their own reviews.  These params should be cleared when user refreshes the page.

Due to #360, that means that if a user wants to see someone's review, then they must always go through the URL in the email.  But, user should always be able to see their own reviews when refreshing Maqetta.

**Comment by JonFerraiolo** [comment]
-> @aerwin

**Comment by JonFerraiolo** [comment]
Fixed by 4524033d55
