### ISSUE TITLE
Console errors when viewing comments w/ annotations

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1978]
@billreed63 added some comments to a review I created on lab9:50020.  The comments had annotations.

When loading the review and also when clicking on each comment, I got a lot of errors in the console:

```
this.shapeNode.ownerDocument.defaultView has no value
this.shapeNode.ownerDocument.defaultView has no value after setTimeout
```

The annotations seem to display fine.  When clicking on an individual comment, the annotations that don't belong to that comment are "disabled".  So all that is working as expected.

Given that, not sure how big of an issue this is, but console errors (especially so many) concern me.

@JonFerraiolo @aerwin

**Comment by doronrosenberg** [comment]
Firefox only it seems, not seeing in chrome.

error is in _ShapeCommon.js (davinci/review/drawing/shapes/_ShapeCommon)

**Comment by JonFerraiolo** [comment]
Reassigning to me. This is like the same code paths as #1974

**Comment by JonFerraiolo** [comment]
@jhpedemonte - I'm going to push this to M6 given that "annotations seem to display fine". Attempting to fix this code in the proper introduces risk (undoubtedly requiring the addition of a deferred).

Here is the offending code, which should be self-explanatory. In case it isn't self-explanatory, occasionally the `style()` method is called before the given shapeNode has been properly added to the DOM. I don't remember the exact code path that causes this scenario, but checking to see if the DOM is ready first, and if not, using a short setTimeout to make the style assignment async, took care of most problems.

```
    style: function(style) {
        //FIXME: Quick hack before Preview 4. For some reason, sometimes this.shapeNode doesn't yet
        // have a defaultView at this point. If it doesn't, try again within a setTimeout().
        if (this.shapeNode && this.shapeNode.ownerDocument && this.shapeNode.ownerDocument.defaultView) {
            dojo.style(this.shapeNode, style);
        } else {
            console.error('this.shapeNode.ownerDocument.defaultView has no value');
            var that = this;
            setTimeout(function() {
                if (that.shapeNode && that.shapeNode.ownerDocument && that.shapeNode.ownerDocument.defaultView) {
                    dojo.style(that.shapeNode, style);
                } else {
                    console.error('this.shapeNode.ownerDocument.defaultView has no value after setTimeout');
                }
            },10);
        }

    },

```
