### ISSUE TITLE
Review link - doesn't show .rev file, instead login screen shows

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#1979]
![Login Issue](http://i.imgur.com/ZruDz.png)

**Comment by jhpedemonte** [comment]
cc @waynevicknair @JonFerraiolo

**Comment by doronrosenberg** [comment]
Note - I can't reproduce this anymore, happened the first time I clicked on the link (so first time I visited that specific installation)

**Comment by aerwin** [comment]
This could be a dup of #1973... though maybe a little different symptom than #1973 after all of the refactoring we're in hte middle of.

**Comment by jhpedemonte** [comment]
See [this comment](https://github.com/maqetta/maqetta/issues/360#issuecomment-4663836) from #360 for some more info.

**Comment by JonFerraiolo** [comment]
Fixed by 4524033d55

**Comment by JonFerraiolo** [comment]
Reopening -  still not working on Joomla. @waynevicknair - you want to take this? If not, could you provide guidance for how to fix and test?

**Comment by aerwin** [comment]
@JonFerraiolo Per e-mail discussion yesterday, should this be re-routed to @waynevicknair or @childsb who know about the macwayne Joomla environment?

**Comment by waynevicknair** [comment]
i'll look at this one @aerwin @JonFerraiolo @jhpedemonte ...

**Comment by waynevicknair** [comment]
fixed in commit 09f2f6c1592dca17f77692cd5910c14ceddef180 to INTERNAL repository.
