### ISSUE TITLE
Annotation color is black in review for Android device

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1982]
@billreed63 sent me a review for an Android page.  Consisted of a View (black background) and a Heading (grey background).  I tried to add an annotation, but it was colored black, making it impossible to see:

![android](http://i.imgur.com/Y3B9M.png)

@JonFerraiolo @aerwin

**Comment by JonFerraiolo** [comment]
reassigned to me. I'm hoping that @aerwin's next fixes will magically fix this, if not, I'll debug and fix.

**Comment by JonFerraiolo** [comment]
Fixed by 4524033d55
