### ISSUE TITLE
Silhouettes should be available as clip art

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1988]
@jmockler 

Sometimes users want to sketch using a mobile silhouette as the page background. 

It shouldn't be very difficult to package up the silhouettes as clipart widgets.

**Comment by jmockler** [comment]
@JonFerraiolo 

I agree.. you have the silhouettes already. Is that correct? 

Do you need them in a different format? and icons for the widget palettes?

**Comment by JonFerraiolo** [comment]
We may have to coordinate on updates to the silhouette SVG files to allow them to be used as clipart, but leave that on me for the time being. Let me look at them and see if I can hand-edit them in a way that allows subsequent editing in Illustrator.

Are there more silhouettes for other devices that have been created, that aren't in Maqetta yet?

And yes we will need icons for widget palette.
