### ISSUE TITLE
Upgrade workbench and dojo plugin to 1.8

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1997]
see also #1584

**Comment by peller** [comment]
paying special attention to http://bugs.dojotoolkit.org/changeset/28276/dojo

**Comment by JonFerraiolo** [comment]
push to M7?

**Comment by peller** [comment]
see also #2047 -- need to undo that workaround

**Comment by JonFerraiolo** [comment]
yes, push to M7
