### ISSUE TITLE
Enter wrong password, still get 'launch maqetta' button

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1999]
I think this is specific to Joomla installs

Enter "peller" for user and "password" for password.  There will be a message in blue about the login failure, but you still get a "Launch Maqetta" button

**Comment by jhpedemonte** [comment]
And clicking on **Launch Maqetta** button just sends you back to front page.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo M7 Prio High

**Comment by jhpedemonte** [comment]
This is no longer relevant, as we are using Orion to handle authentication.
