### ISSUE TITLE
Support dijit.DateTextBox

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#200]
It is not yet possible to customize the dropdown arrow in DateTextBox, but oneUI may change it to look like a calendar icon.

old description/rumor: In Dojo 1.5 and before, there was a calendar widget that showed a whole calendar, but no standard small icon that launched the bigger calendar widget when clicked. Rumor has it that there is now such a calendar icon in Dojo 1.6 and should be added to Maqetta.

**Comment by peller** [comment]
@billreed63

`dijit.Calendar` always displays just a calendar.  `dijit.form.TextBox` has a dropdown arrow which can be styled by the theme: http://bugs.dojotoolkit.org/ticket/5151

**Comment by JonFerraiolo** [comment]
I guess the primary need is for us to promote DateTextBox from untested to actually working so that designers have at least one way to create a UI that brings up calendars as popups. But is there also a way to launch a Calendar popup via an icon instead of a TextBox?

**Comment by peller** [comment]
> is there also a way to launch a Calendar popup via an icon instead of a TextBox?

you'd have to have a button or img onclick to set the visibility on a Calendar, or something like that

**Comment by JonFerraiolo** [comment]
Any way to hook into Dojo facilities to locate the popup next to the image?

**Comment by peller** [comment]
there's always dijit.popup... but I thought either the Claro or the OneUI guys were going to make this part of their DateTextBox theming?  Obviously, to customize the theme for us would be a bit difficult right now, since it involves images -- not sure we support that yet.

**Comment by JonFerraiolo** [comment]
Ignoring today's reality and thinking from an idealistic perspective, maybe dijit.Calendar should be treated as an overlay widget, like TooltipDialog? I realize that for such an approach to work in practice, we probably need some minor mods to dijit.Calendar, such as a new property holding the IDs of the widgets that might cause the Calendar to pop up, and then a more general integration with dijit.popup.

**Comment by peller** [comment]
Calendar isn't a popup.  It's just a calendar.  Perhaps you're suggesting that there should be a widget to pop up and contain a widget?  TooltipDialog sort of does this, but it has bubble UI.  There's code in DateTextBox that does the popup, but I don't think it's 'widgetized'

**Comment by jhpedemonte** [comment]
So is the point of this bug to support the [DateTextBox](http://docs.dojocampus.org/dijit/form/DateTextBox) widget?

**Comment by peller** [comment]
no.  Perhaps Jon is asking for functionality that was rumored to be added to DateTextBox widget (ORIA team) but never happened.  It might also be possible to use a DropDownButton with a Calendar.

**Comment by peller** [comment]
So @JonFerraiolo, are you ok with enabling DropDownButton to host a Calendar as a popup?  That's the Dijit way to do this.  We'd then need to support rich text / images within the DropDownButton, something I think we're discussing elsewhere...

**Comment by JonFerraiolo** [comment]
I looked into this issue. I believe the short-term priority here is to what @jhpdemonte speculated above: 

So is the point of this bug to support the [DateTextBox](http://docs.dojocampus.org/dijit/form/DateTextBox) widget?

What this bug was about was that users seldom put a Calendar widget onto a page and instead they put another widget or icon onto page which when clicked on brings up the Calendar as a popup overlay. I would think that the most common scenario for triggering a Calendar widget would be from a DateTextBox because most of the time you'll want the UI to show the actual date value in text form after forcing the Calendar to appear.

**Comment by peller** [comment]
Ok then, should we change the issue to "support DateTextBox"?  Does anyone know the status Cindy had on this widget?
