### ISSUE TITLE
Custom themes not downloaded with Download selected

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2004]
@billreed63 

When I download entire workspace, my custom theme (claroJon) is included in the ZIP, but if I download selected files, my custom theme is not included.

I guess this is arguably the correct behavior - downloaded selected gives you all selected files, plus anything in your workspace that is built-in (e..g, dojo library and themes). However, it surprised me that I needed to explicitly specify my custom themes.

@cihldsb: In your mind, is this a feature or a bug? If a feature, please close this issue. I assume at some point we will change the UI on the download palettes.

**Comment by childsb** [comment]
yes this is intended.  assumption being the user only wants one or two files, and not the entire theme file tree.  if they wanted everything, they should do "download workspace".
