### ISSUE TITLE
Do we update 'packages:' when relocating Dojo?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2005]
@childsb 

I haven't tested this, but just wondering if either of @jhpedemonte or @childsb know offhand whether moving Dojo (via ModifyLibraries or download buttons) will properly update the relative URLs in the packages: list that is added to the SCRIPT tag whenever a user file includes shapes or clipart.

**Comment by jhpedemonte** [comment]
-> M7/Brad

**Comment by jhpedemonte** [comment]
-> M8, Prio High to investigate.

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo M8 Prio-High

**Comment by JonFerraiolo** [comment]
Closing. I checked and everything is cool.
