### ISSUE TITLE
edit review, selected files are gone

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2006]
- create a review
- open it in the review view for editing
- the wizard will warn you that no files selected.  when you get to the second pane in the wizard, the selection is empty. you must add the file(s) again before publishing.

probably not critical for M5?

**Comment by JonFerraiolo** [comment]
Yes, I wouldn't hold shipping M5 for this bug. Pushing to M6/High.

**Comment by jhpedemonte** [comment]
-> M6

No loss of data, just inconvenient for an uncommon operation.

@JonFerraiolo
