### ISSUE TITLE
Add white translucent background to Choose Parent list

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2008]
While running through the tests **VE 3 > Choose Parent > 8**:

I had a calendar selected and moved it to the right a bit, making the Choose Parent list appear.  However, the list was difficult to read, as it was overlaid on the calendar contents.

To fix, we should add a slight white translucent background to the list, so it is easy to read in all situations, but translucent enough that some of the underlying page can be seen.

**Comment by JonFerraiolo** [comment]
Closing. It looks like I added the translucent white background somewhere along the way, but forgot to close this bug.
