### ISSUE TITLE
New File -> opens existing file

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2009]
2nd time I've run into this issue over the past few weeks:

I was working on a file, name **file2.html**, during testing.  I had Previewed (which automatically saves the file), then closed and reopened.

Then I closed that file and clicked **New File**.  I just took the default and clicked **OK**.  This lead to **file2.html** to be opened again.

I noticed that when closing this file again, file2.html **disappeared** from the Files view.  I could then repeat the same scenario above:  New File opens file2.html instead of creating a new file.

I don't really have a recreate scenario for this.  It just happens sometimes.  But we should definitely study the logic here to see if we can find the issue.

@JonFerraiolo @peller

**Comment by childsb** [comment]
i haven't been able to reproduce this.

**Comment by JonFerraiolo** [comment]
Reopening and reassigning to me just to try to reproduce. I saw this problem as recently as this weekend. If I can't reproduce, I'll re-close (is that a word?)

**Comment by JonFerraiolo** [comment]
Closing. I tried to reproduce using similar patterns that caused me trouble this weekend and couldn't reproduce. (Let's hope that I don't reopen 2 minutes later! :-)

**Comment by jhpedemonte** [comment]
Reopening.  Ran into this again.

Testing on **lab9:50020**, running through **MainMenu: Overview** test plan.

In the 2nd test there, I created a new file with default name ("file1.html") and, as stated in summary of this bug, I clicked on **Preview**.  All that worked fine.  Closed preview and closed file tab.  At this point, **the file disappeared from the Files view**.

Created a new file, using the same name and the new file had **the old file's content**, rather than being a blank page.

**Comment by jhpedemonte** [comment]
Back to @childsb.

**Comment by jhpedemonte** [comment]
Checked server log but showed no errors.

I'm guessing this is a bug in our client-side resource code which, for whatever reason, loses track of the created file.  So when creating a new file, it uses the name of an existing file.  Then, it does a server call (to create file?), which instead returns the contents of the existing file.  Or something like that.  @childsb knows that code better.

**Comment by jhpedemonte** [comment]
Brad, if you can't recreate this, at least add a comment here letting us know **what we should look for in the debugger**.  That way, next time it happens, I can inspect the state of the app.

**Comment by childsb** [comment]
First thing I'm noticing is that preview auto saves the file. The editor is no longer dirty after a preview, and the working copy is removed.  So it's an actual hard save.

I can't reproduce this given those steps.  Snooping around the code, the best I can guess is that the save command isn't finishing before the preview / browser launches and theres some race condition around the resource.

We could try to do some hack-fix, like a set timeout or wrap the save command in a deferred, but I'm not sure its worth it.  If we get async resource handling next release, this will probably fix itself.

**Comment by peller** [comment]
wouldn't async make it worse?

**Comment by childsb** [comment]
async loading will force ordering with the deferred return.  It would turn into something like:

editor.save().then(function(){editor.showPreview()});

ensuring that save completed the round trip before the preview shows.

**Comment by JonFerraiolo** [comment]
@jhpedemonte : have you seen this recently? If not, maybe push to M8?

**Comment by jhpedemonte** [comment]
Haven't seen it recently.  Perhaps @childsb [was right](https://github.com/maqetta/maqetta/issues/2009#issuecomment-5749172)!
