### ISSUE TITLE
Reviewers cannot load read-only libs/themes

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2010]
With latest R&C code, reviewers (not review creators) cannot properly load page.  Dojo (and other read-only libs) aren't loaded in the Joomla build.

@waynevicknair @JonFerraiolo @peller

**Comment by peller** [comment]
@childsb checked in a fix at bc95473f0e74d81df975dd4e97c7582c0dde171b

**Comment by jhpedemonte** [comment]
This seems to be working now, for Jon and I.  Closing.
