### ISSUE TITLE
Exception in subscribe of "/davinci/ui/editorSelected"

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2013]
I had a bunch of different editors open (HTML, JS, CSS, image).  When switching from a JS editor (actually, a JSON file, which uses the JS editor) to the CSS editor, I got an exception in the subscribe to "/davinci/ui/editorSelected", in review's Context.js.

``` javascript
 dojo.subscribe("/davinci/ui/editorSelected", dojo.hitch(this, function(obj){
     if (obj.oldEditor!=null && this === obj.oldEditor.getContext()) {
         // Determine if the editor is closed, if the editor is closed then
```

The issue is that the `JSEditor` does not have a `getContext()` function.  It is not defined anywhere in that prototype chain.

Assigning to @peller, since I think he worked on this.

**Comment by peller** [comment]
seems to have been fixed by e0a35a376905c5eca5735ec47539d20b5c577345
