### ISSUE TITLE
Loading... editor progress indicator doesn't last long enough

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2015]
Should be posted as soon as the frame is created, perhaps should stay up until an onload event on the document?

@billreed63 @jhpedemonte

**Comment by peller** [comment]
see #87

**Comment by jhpedemonte** [comment]
Best way to test this:  load **Sample1.html** from a remote build (i.e. lab9).

I see the blank editor open up, pause like this for a bit, then the **Loading** indicator briefly flashes before the content appears.
