### ISSUE TITLE
cookie with name=="undefined"

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2018]

**Comment by jhpedemonte** [comment]
From an email I sent out:

> OK, I cleared cookies and loaded latest M5.  After loading, did not see the `undefined` cookie.
> 
> Then I opened **app.css** and **Sample1.html**.  Rechecked cookies and the `undefined` cookies was there...

**Comment by peller** [comment]
OutlineView didn't have an id and was posting this value.  Apparently, Trees without an id just use 'undefined' for the cookie -- I [reported this problem](http://bugs.dojotoolkit.org/ticket/15088) to Dojo.  OutlineView shouldn't persist its state anyway, since it's a singleton and handles multiple editors.  I'll push the commit with a workaround shortly.

**Comment by peller** [comment]
hrm... this didn't get picked up.  Fixed in 7f81deb69d91831524822247fcddf3c2cc68bc89
