### ISSUE TITLE
about the plugin technology of maqetta

### ISSUE THREAD

**Issue by jessusniww** [maqetta/maqetta#2019]
now ,i am learn the maqetta source code ,i want to know the plugin technology of maqetta ?
 i mean is the Maqetta's current plugin system,how it works?what is the principle?
could anyone explain for me?

**Comment by jhpedemonte** [comment]
-> Closing.  This isn't an issue.

Please open a new topic in the [maqetta-devs](https://groups.google.com/forum/#!forum/maqetta-devs) forum.  It's the big red button at the top labelled **NEW TOPIC**.

Also, as I [replied earlier](https://groups.google.com/d/msg/maqetta-devs/x2yFriiMQfE/1_aqpvsGcEAJ), you will have to provide more detail in your topic post.  I'm not sure what you are asking.
