### ISSUE TITLE
Better way than cloning CSS and theme JSON files?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2021]
@peller, @jhpedemonte, @childsb 

During phone call today, we wondered if there was a better way to accomplish theme cloning (without caching problems) than having to clone the CSS and theme JSON files, and then rename.

**Comment by aerwin** [comment]
--> no milestone to M7
--> prio: not set to med

**Comment by billreed63** [comment]
The has been fixed in M7 by the use of delta themes
