### ISSUE TITLE
Preview requires browser refresh in Firefox

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2023]
Environment: FF, Mac going to lab9:50020...

Step 10 in the "Comma separated data" section of the Data Grid (/test/testplan/WidgetPalette/dataGrid.html) test case asks me to click the Preview in Browser button. When I do so, I get a new browser tab (as expected) but nothing is rendered. I have to reload the page in the new tab to see the content.

This happens consistently... e.g., if I close the tab and preview again, I must again reload the new tab.

I tried with a simpler HTML file (e.g., with just a Dojo button) and the extra reload doesn't seem to be necessary.

In addition, I tried on Mac Chrome and the HTML file containing the data grid also renders correctly without the extra reload.

I'm going to open this as "High" priority for discussion, but I can see where we could decide this is "Medium" if limited to some subset of pages on Mac FF.

**Comment by aerwin** [comment]
I'm going to lower priority on this one to medium... as I keep testing, this only seems to happen with the first HTML file created in the Data Grid test case. Here's my source:

```

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<style>@import "themes/claro/claro.css";@import "lib/dojo/dojo/resources/dojo.css";@import "lib/dojo/dojox/grid/resources/Grid.css";@import "lib/dojo/dojox/grid/resources/claroGrid.css";@import "app.css";
</style>
<script type="text/javascript" src="maqetta/maqetta.js"></script>
<script type="text/javascript" data-dojo-config="'async':true,'parseOnLoad':true,'packages':[{'name':'clipart','location':'../../clipart'},{'name':'shapes','location':'../../shapes'},{'name':'oneui','location':'../../oneui'}]" src="lib/dojo/dojo/dojo.js"></script>
<script type="text/javascript" src="maqetta/States.js"></script>
<script type="text/javascript">
require(["dijit/dijit"]);
require(["dojo/parser"]);
require(["dojo/data/ItemFileReadStore"]);
require(["dojox/io/xhrScriptPlugin"]);
require(["dojox/grid/DataGrid"]);</script>
</head>
<body class="claro" dvFlowLayout="true" data-davinci-ws="collapse" id="myapp">
<span dojoType="dojo.data.ItemFileReadStore" id="ItemFileReadStore_1" jsId="ItemFileReadStore_1" data="{&quot;identifier&quot;:&quot;uniqe_id&quot;,&quot;items&quot;:[{&quot;uniqe_id&quot;:1,&quot;one&quot;:&quot;data 1&quot;,&quot;_two&quot;:&quot; data 2&quot;,&quot;_three&quot;:&quot; data 3&quot;},{&quot;uniqe_id&quot;:2,&quot;one&quot;:&quot;xxxx&quot;,&quot;_two&quot;:&quot; yyy&quot;,&quot;_three&quot;:&quot; zzz&quot;},{&quot;uniqe_id&quot;:3,&quot;one&quot;:&quot;111&quot;,&quot;_two&quot;:&quot; 222&quot;,&quot;_three&quot;:&quot; 3333&quot;}]}"></span><span data-dojo-type="dojox.grid.DataGrid" structure="[{&quot;width&quot;:&quot;auto&quot;,&quot;name&quot;:&quot;one&quot;,&quot;field&quot;:&quot;one&quot;},{&quot;width&quot;:&quot;auto&quot;,&quot;name&quot;:&quot; two&quot;,&quot;field&quot;:&quot;_two&quot;},{&quot;width&quot;:&quot;auto&quot;,&quot;name&quot;:&quot; three&quot;,&quot;field&quot;:&quot;_three&quot;}]" autoWidth="false" autoHeight="false" singleClickEdit="false" columnReordering="false" selectable="false" delayScroll="false" style="width: 300px; height: 300px;" store="ItemFileReadStore_1" escapeHTMLInData="true"></span></body>
</html>

```

**Comment by jhpedemonte** [comment]
-> M6

We've been having issues with Preview for a while, although it has gotten much better lately.  However, not going to hold up M5 for this.

@JonFerraiolo

**Comment by jhpedemonte** [comment]
-> M7

It seems to have gotten better for me as of late.  Not sure what changed.

Tony, if it's working better for you, feel free to close.

**Comment by aerwin** [comment]
Yes, this looks like it's working better. The DataGrid test case mentioned in the original report seems to work now. So, closing.
