### ISSUE TITLE
Investigate background image quoting

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2028]
@childsb 

Dartas reports that sometimes background-image urls are placed into HTML files with unescaped single quotes, which causes a runtime error because the url() is inside of another single quote. This problem seems to occur only when changing background-image to different values for different states.

**Comment by JonFerraiolo** [comment]
Oops. Meant M6.

**Comment by jhpedemonte** [comment]
Is this the same as #2032?

**Comment by JonFerraiolo** [comment]
Closing. Dupe of #2032
