### ISSUE TITLE
Remove type, severity, status icons from review UI?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2030]
@jmockler, @aerwin, @waynevicknair , @jhpedemonte 

@jhpedemonte and @jonferraiolo are thinking that for Maqetta we should simplify the UI and remove the type, severity and status icons from the Comments palette. Our thinking is that if people want to track that sort of thing, they should use a real issue tracking system for that info, and just refer to a formally tracked issue in the review comment somehow.

**Comment by jmockler** [comment]
I'm fine with that approach.

**Comment by jhpedemonte** [comment]
-> M7/Tony

**Comment by aerwin** [comment]
Closing with above commit.
