### ISSUE TITLE
Investigate single-quotes and escaping for background-image urls and states

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2032]
Need to investigate single-quotes and escaping for background-image urls and states. There must be bugs, just haven't found them yet.

Dartas writes:

Well I actually got it to work! I simply removed the singlequotes on
the url argument. Here is the code:

<div id="test_div"
style="background-image: url(images/unclicked.png); width: 4em;
height: 4em; background-size: cover;"
dvStates="{'unclicked_state':{'style':{'background-image':'url(images/
unclicked.png)'}},'clicked_state':{'style':{'background-
image':'url(images/clicked.png)'}}}"></div>

I did have to code it by hand but it works :) I am guessing there
shouldn't be any problems in the reading of the url in a production
environment since it's local.
Perhaps adding " ./ " would be more correct but I guess it will work
just fine.

Now following exclusively the graphical interface for adding an image
as background to a div results
in the url('...') to be added with no backslashes to the respective
field. It does work and the image
is added. I imagine the backslash was already so that when changing
background-images on state
changes (or any url field) would make the parser ignore the
singlequote character. However, when
using \' \' manually added on the code there is no error on the
states... but the image is not found.

I am having in mind Preview 5 so for now I am merely creating the
different screens (activities)
of the mobile web app setting divs and alike plus some minor general
CSS editing, then as
I go I test the platform for what I will need to add once I start the
process after having the initial
html skeleton in place (so although I have tested states here and
there I have nothing official on
those grounds).

Thanks a lot! :)
Look forward for Preview 5.

Cheers!

**Comment by peller** [comment]
just happened to notice that EventSelection.js does replace without assignment.  See _onChange:

``` javascript

            var value = widget.get('value');

            value.replace(/'/,"\\'");
            value.replace(/"/,'\\"');
```

**Comment by JonFerraiolo** [comment]
Merging #2028 into this bug:

@childsb

Dartas reports that sometimes background-image urls are placed into HTML files with unescaped single quotes, which causes a runtime error because the url() is inside of another single quote. This problem seems to occur only when changing background-image to different values for different states.
