### ISSUE TITLE
Can't cut and paste widget that has absolute position 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2033]
1) New hifi HTML
2) DnD button widget
3) change layout property for button to position absolute
4) copy and paste

I get the cross hairs for paste but when I click on the canvas nothing...

**Comment by JonFerraiolo** [comment]
I took a quick look at the code and I'm not sure what's the best fix. It looks like some of the logic is based on current mode (flow vs absolute) and other parts are based on the position property for the pasted widget.

**Comment by JonFerraiolo** [comment]
Fixed by 8f9d75a7f6  and 9e64befa22 . Closing.

**Comment by JonFerraiolo** [comment]
Fixed by 8f9d75a7f6  and 9e64befa22
