### ISSUE TITLE
Investigate dojo isInstanceOf without SelectTool.js

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2042]
@peller - NOTE: this problem is in my private branch, which I hope to move into master soon.

The following check for isLayout in SelectTool.js isn't working for a ContentPane that is a child of TabContainer:

```
if(!parent || !parent.isLayout || !parent.isLayout()){
```

We are calling isLayout() on a TabContainer object, and isLayout (in DijitWidget.js) is making this check:

```
return this.dijitWidget.isInstanceOf(dijit.layout._LayoutWidget);
```

but the above check is returning false even though debugger shows a nested prototype with declaredClass of `dijit.layout._LayoutWidget`

**Comment by peller** [comment]
it's probably comparing against the wrong instance of dijit (iframe vs. Workbench)

**Comment by JonFerraiolo** [comment]
yes, that was it. Thanks! Closing. (Commit with fix will be coming today or tomorrow.)
