### ISSUE TITLE
dojox.mobile.Button loses its label upon dragging to different location

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2043]
- New HTML File - iPhone
- Add the following dojox.mobile widgets: View, ToggleButton, CheckBox and Button
- Select the Button and drag in between the ToggleButton and CheckBox, waiting to make sure the blinking cursor shows a drop point between those two widgets. Upon seeing the blinking cursor at the correct spot, mouseup to drop the Button

Result=> Button loses its text. 

Note that the Button is still usable. If you double click on the Button, you can restore the text.

**Comment by doronrosenberg** [comment]
So issue is the label is a child textnode, and regular dijit Button has a special Helper class to just get the label.

We could write a Helper for the mobile button or have a generic "copy textcontent" flag in the oam.json file.

**Comment by JonFerraiolo** [comment]
We already have at least one widget that supports innerHTML content instead of using the 'label' attribute: dojox.mobile.ListItem.

I made changes sometime in the past few months to allow innerHTML rich text so that LIstItem could contain <img> elements and not just plain text. You can see this by double-clicking on a RoundRectList, enter "abc<i>def</i>" for one of the ListItems, and then you'll see radio buttons appear, and click on the "HTML markup" radio button.  I see that there is a getChildrenData() helper in ListItemHelper.js. That's probably what I did to make rich text possible within ListItem. But I'm not sure that same approach will fix this particular problem.

@billreed63 @jhpedemonte

**Comment by doronrosenberg** [comment]
Doing this via a helper will work as that is what dijit.form.Button does.  If that is ok (adding another helper), easy fix.
