### ISSUE TITLE
Outline palette collapses unnecessarily upon changing states/scenes

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2045]
I'm scratching my head on this recent regression.
- Open Sample1.html
- In Outline palette, expand the first tab's contents until the MultiSelect is visible
- In Scenes palette, click on the "Add Task" scene

Result=> The outline for the first tab collapses.

This behavior was not there in M5. I tried to find the check-in that caused this regression by systematically doing "git checkout <number>" to find the commit that caused this bug to appear, and my search points to this commit - 78281004e1 - but this innocuous set of changes for Selenium shouldn't have any effect on the Outline palette. Also, I tried to take a working version of the code (previous commit) and add in the changes from this commit, and everything continues to work, and vice versa (take the apparently guilty commit, and manually revert back the suspicious code changes).

At this point, I figure I should send this to the Outline expert.

**Comment by peller** [comment]
the state change triggers /davinci/states/state/changed which triggers /davinci/states/state/changed/end which triggers a refresh() in VisualEditorOutline...

**Comment by JonFerraiolo** [comment]
If you want to reassign to me, that would be find. I'm all up to my armpits with /davinci/states/state/changed

**Comment by peller** [comment]
It's not the states events so much as the refresh() call, which was always a kludge.  Trees are supposed to be data-driven.

**Comment by JonFerraiolo** [comment]
I did a "git checkout Preview5", put a breakpoint in the refresh() routine in VisualEditorOutline.js, opened Sample1.html, opened up the first ContentPane in the outline palette, and then changed state in the Scenes palette.

What I see is that the refresh() routine is doing a full refresh of the outline, and the outline temporarily closes, but then it opens up again just like it was before the refresh.

Did we remove saved cookies for the outline palette since Preview5?

**Comment by peller** [comment]
note that in preview 5 there was much flashing and the selection in the tree was lost.  I thought we had removed cookies prior to preview 5, but that's the only way I can see how a tree might preserve its turndown knobs across a refresh.   Best thing here would be to avoid the refresh call (both for changed/setState, but also for command stack execution)  Best way to do that would be to have a model that reflects changes directly to the tree.   Kludge would be to just somehow update the eyeball icons without reconstructing the tree -- not sure how to do that.
