### ISSUE TITLE
Main code has davinci.review.model.resource.root dependencies

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2046]
@waynevicknair @aerwin 

see b6d3a8bef3d412ff51fd22165166499e0d7e4af7

The `davinci.review.model.resource.root` module is referenced in Workbench.js initializeWorkbenchState() as well as directly from pagedesigner.html (that code should be refactored to some module)
1. The reference should be done through a dependency (AMD), not a global reference.
2. I think this is the only module left from review which is coupled directly to the main bootstrap code.  Is it possible to refactor this such that we can load the review code later?  If not, perhaps we'll have to build this one module into the main app, then build the rest of review separately?
#60 depends on this.

**Comment by childsb** [comment]
Cleaned up these non-amd ref in commit: befc6d7796e704d256c73b753377a54000d8c65e

As a bonus I tried removing the Review/Resource class all together but wasn't successful.   There is some re-design on how the review editors are identified before we can get rid of the review resource classes all together.
