### ISSUE TITLE
Intermittent dom exception on startup

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2047]
@childsb @peller @waynevicknair @billreed63 @aerwin 

When I pull the latest sources, I got the following exception when starting up the program using the maqetta-single-user launch script (under Run Configurations):

```
Uncaught TypeError: Object #<Object> has no method 'set'
createdom-construct.js:346
loadcss.js:22
injectPlugindojo.js:1204
plugin.loadQdojo.js:1030
forEachdojo.js:93
resolvePluginLoadQdojo.js:1022
finishExecdojo.js:1064
execModuledojo.js:1124
checkCompletedojo.js:1146
onLoadCallbackdojo.js:1311
req.injectUrl.onLoad
```

Things work fine with the maqetta-multi-user launch script.

The above stack is not particularly helpful. The loader is attempting to load file css.html, but I have to believe the problem is in an entirely different location.

Does anyone have any thoughts about what recent changes might have broken single-user mode?

**Comment by JonFerraiolo** [comment]
I'm seeing the dom-construct.js exception intermittently in both the multi-user and single-user configurations. I'm not sure why it was coming up more often in the single-user configuration because you'd think all of the same code paths were getting exercised.

**Comment by peller** [comment]
I think the loader is actually trying to load a .css file using our davinci/css loader plugin, at least in the cases I've seen.  The stack above supports this.  It seems like there's a race condition with the loading dependencies of the css plugin itself (dom-attr, two dependencies deep)

**Comment by jhpedemonte** [comment]
Jon, in that stack, are the functions and file names conjoined?  Should it look like this?

```
create      dom-construct.js:346
load        css.js:22
...
```

**Comment by jhpedemonte** [comment]
Given what [Adam wrote](https://github.com/maqetta/maqetta/issues/2047#issuecomment-4955746), is this a Dojo loader issue, then?  I'm not doing anything special with the dependencies in **davinci/css.js**.

**Comment by peller** [comment]
it _seems_ to be.  the dojo-attr dependency (a dependency of dom-construct) is not resolved, even though I did see the network request.  Perhaps the loader has some problem resolving all the sub-dependencies in time. We could try working around this by putting a dojo-attr dependency (and whatever else gets pulled in) elsewhere in our code, maybe even in css.js.

**Comment by peller** [comment]
Do we have any idea when this might have regressed?  Seems like it started happening just a few days ago.

**Comment by JonFerraiolo** [comment]
No idea when this regressed, but I don't remember seeing it during the M5 development phase, which ended with this build:

```
Version: Preview 5
Date: Mar 28, 2012 10:29:29 AM
Build: 3837bd9b58f6b69...
```

**Comment by peller** [comment]
It's a circular dependency within Dojo.  Our plugin must be loading things in a different order than Dojo normally does.  Reported a [dojo bug](http://bugs.dojotoolkit.org/ticket/15131)

davinci/css -> dojo/dom-construct -> dojo/dom-attr -> dojo/dom-prop -> dojo/dom-construct

**Comment by JonFerraiolo** [comment]
Great work!
