### ISSUE TITLE
CSSParse displays ERROR: expecting ':' when parsing inline image

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2057]
If the CSS file has the following code I set the above error message in the console

```
.myclass.dijitDownArrowButton{

  background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2Y0ZjRmNCIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNkYmRiZGIiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);

}
```

**Comment by jhpedemonte** [comment]
This might be the same as #1241.

**Comment by JonFerraiolo** [comment]
I'm not sure about #1241, but in this case I can see why our code falls short. Here is the current logic in CSSParser.js:

```
                    property.name = propertyName;
                    if (!skipNext) {
                        if (nextToken().content != ":")  {
                            error("expecting ':'");
                        }
                    }
                    nextToken();
                    property.value = token.value;
                    while ((nextToken()).content != ";" && token.content != "}") {
                        property.value += token.value;
                    }
```

Notice that the `while` statement keeps grabbing tokens until it encounters a a `;` or `}` character, but the base64 syntax allows a `;` inside. Browsers must have special case parsing logic for the url() case to deal with base64 content where the url content keeps going until they reach a close parenthesis (and pass over any semicolons inside the parens).

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg (so this won't fall through cracks, although I suspect any of us could fix this)

**Comment by billreed63** [comment]
The fix above is dropping the ')'  on url corrupting the CSS file
`url('xxxx.png')` is being parsed as `url('xxxx.png'` so when the CSSProperty is written out it is invalid

**Comment by billreed63** [comment]
@JonFerraiolo @jhpedemonte  We need to push this out to Maqetta.org it is a big bug.
