### ISSUE TITLE
AMD Compliance in a couple of modules

### ISSUE THREAD

**Issue by rbackhouse** [maqetta/maqetta#2058]
I have been attempting to get maqetta loading with another AMD loader and ran into a couple of modules that are not AMD compliant :

/maqetta.core.client/WebContent/davinci/maqetta/States.js 

It has no "define" call. Instead it has a global "require" call. Simply changing the "require" to "define" should be sufficient. Note the global "require" is not an AMD spec'd requirement.

/maqetta.core.client/WebContent/davinci/version.js

The "define" call signature is invalid. The spec (https://github.com/amdjs/amdjs-api/wiki/AMD) dictates that if there is only one argument it must be a function :

factory

The third argument, factory, is a function that should be executed to instantiate the module or an object. If the factory is a function it should only be executed once. If the factory argument is an object, that object should be assigned as the exported value of the module.

If the factory function returns a value (an object, function, or any value that coerces to true), then that value should be assigned as the exported value for the module.

Changing the code to :

define(function() {return "Preview 5";});

will make it compliant.

**Comment by JonFerraiolo** [comment]
-> @peller M6/High

**Comment by peller** [comment]
States.js was converted to use AMD on a branch: 332f77d8469fc51a5067936cb46784c7cb48dbc5  Will land on master soon.
