### ISSUE TITLE
Adding Switch throws js error

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2065]
Could not expand path at Switch_1
http://192.168.1.122:8081/maqetta/app/dojo/_base/Deferred.js?@revision@
Line 216

**Comment by JonFerraiolo** [comment]
-> @peller M6/High

**Comment by doronrosenberg** [comment]
Feel free to throw it my way if busy.

**Comment by doronrosenberg** [comment]
Also happening with RadioButton/Checkbox/ToggleButton/TextBox/Slider/SpinWheel and probably more mobile widgets

**Comment by doronrosenberg** [comment]
Looks like we are calling _select before the tree node for the new widget has been created.

Tree.selectPath shows only one tree node, which is the root node.  Adding a setTimeout helps in CreateTool, so timing issue

**Comment by doronrosenberg** [comment]
@peller @jhpedemonte 

Happening because of Context.js::activate does:

``` javascript
dojo.connect(this._commandStack, "onExecute", function(){setTimeout(this.onContentChange.bind(this), 0);}.bind(this)),
```

Removing that setTimeout fixes it.

If we keep it, then Context::select should do the following to line 1884.

Change from

``` javascript
this.onSelectionChange(selection, add);
```

to:

``` javascript
window.setTimeout(dojo.hitch(this, this.onSelectionChange, selection, add), 0);
```

**Comment by peller** [comment]
setTimeouts are viral.

The line above was put in a timeout to resolve #1573

**Comment by doronrosenberg** [comment]
I guess one potential solution would be to do selection lazy - store the selectionChange data and fire that off when onContentChange has finished doing its thing.

In fact onContentChange already kinda supports this, as it calls select() on everything in getSelection - just happens that array is empty.
