### ISSUE TITLE
Build scripts need to init and update submodules after cloning git repository

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2068]
@waynevicknair @jhpedemonte @JonFerraiolo @peller 

This issue is part of the fall out of adding the new davinci.gridx plug-in (#2034)...

The GridX project is hosted on github (https://github.com/evanhw/gridx) so we made the decision to use git submodules to pull in the GridX code rather than check-in GridX source into the Maqetta repository. The Maqetta build scripts clone the Maqetta repository and use that to source the build. But, with the addition of submodules we need to run the following commands after cloning the repository so that we also pull down the GridX code:
- git submodule init
- git submodule update

These commands should be run from the top-level of repository.

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte (so this doesn't fall through cracks)

**Comment by jhpedemonte** [comment]
The build script has two paths: (1) for pulling down completely new source; and (2) for using existing source.

For (1) we need to do `git submodule init`.  And we should always do `git submodule update` for both (1) and (2).  (I think.)

Sending back to @aerwin, who may want to work with @childsb to properly update the build script.

**Comment by aerwin** [comment]
Closing with 318f040089983bbd192690843370bab4b2e16aef .

**Comment by jhpedemonte** [comment]
That commit isn't handling the case where `maqettaCode` is set (which is when using existing code, rather than having the script clone the repo).

As mentioned [above](https://github.com/maqetta/maqetta/issues/2068#issuecomment-5769117), the `init` is probably in the correct location, but we need to do `update` for both cases.  Maybe put `update` right after that `if` block (around line 176)?

**Comment by aerwin** [comment]
Since we're not doing a git pull when pointing at Maqetta code, it doesn't make sense to me to do a git submodule update. Am I missing something? E.g. the user would have been responsible for getting their repo directory to the level of everything they want.

**Comment by jhpedemonte** [comment]
Ah, quite right.  Nevermind then.  Closing.
