### ISSUE TITLE
Changing to source view throws exception, doesn't show anything

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2069]
Switching to source view always throws in Firefox windows and the source view never shows up:

```
doc is undefined
http://192.168.1.122:8081/maqetta/app/davinci/UserActivityMonitor.js?@revision@
Line 54
```

**Comment by doronrosenberg** [comment]
Giving to peller as might be related to Orion stuff

**Comment by doronrosenberg** [comment]
Seeing on chrome as well

**Comment by doronrosenberg** [comment]
So Editor.js does:

```
this._activityConnections = UserActivityMonitor.addInActivityMonitor(this.contentDiv.firstChild.contentDocument);
```

this.contentDiv.firstChild is:

```
<div class="textviewContainer" tabindex="-1" style="position: absolute; overflow: hidden; line-height: normal; width: 0px; height: 305px;" role="application">
```

That node has no contentDocument property set.  If I change it to use ownerDocument, things work again

**Comment by peller** [comment]
@billreed63

**Comment by doronrosenberg** [comment]
contentDocument is an frame/iframe thing

**Comment by peller** [comment]
and firstChild is now a div; perhaps it used to be an iframe?  I don't know why I don't see this error running on lab9 (multiuser) but changing the reference to ownerDocument does seem to be the right thing to do

**Comment by billreed63** [comment]
That does seem like the correct fix.
