### ISSUE TITLE
Use of SSL/TLS for SMTP not supported

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2070]
> Maqetta uses hard- coded port numbers for SMTP and POP3 which are 25 and 110, so there is no possibility to use an SSL-secured mail server listening on port 465.
> 
> The code does not enable Java Mail’s StartTLS property and there is no way to configure it. SSL authentication is not possible either. That is, none of the following properties is set:
> 
> ```
> mail.smtp.ssl.enable
> mail.smtp.starttls.enable
> ```
> 
> As a consequence, Maqetta supports only plain-text SMTP authentication.

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte (had been unassigned)

**Comment by jhpedemonte** [comment]
@childsb, can you please check if Orion supports anything along these lines?  I know we can enable HTTPS access, but not sure about using SSL for the emails it sends out.

**Comment by jhpedemonte** [comment]
TLS/SSL/Auth/etc are all supported by JavaMail, which we use.  We should just be able to set the appropriate properties in the **javax.mail.Session** object we create.

In **SmtpPop3Mailer.java**, we create Session by passing in `System.getProperties()`.  I thought this would mean that we could just do something like `-Dmail.smtp.sll.enable=true`, but it wasn't working for me.  Needs more investigation.

-> M8

**Comment by jhpedemonte** [comment]
> ... we create Session by passing in System.getProperties(). I thought this would mean that we could just do something like `-Dmail.smtp.sll.enable=true`, but it wasn't working for me.

If this isn't the case, we can fix this by pulling in all command line args matching `mail.*` and automatically add them to the Session properties.

**Comment by jhpedemonte** [comment]
Now using Orion email APIs, which support this.  Closing.
