### ISSUE TITLE
Theme editor should simulate browser states :hover

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2075]
We need a way to simulate browser states in the theme editor for example

```
a:hover{
text-decoration: underline;
}
```

At runtime the user moves the mouse over the link and the browser adds the browser state :hover, finds the correct styling rule. 
What we are doing in the theme editor is making hover a static state. the user selects the "hover" from the states palette and we then apply the correct styling to each widget in the theme editor that supports the hover state simulating what each widget would appear like at runtime when a your hovers. I do not know of a way to fake the :hover state on a widget, but if we have a idxLinkHover class we can add that to the widget in the theme editor an simulate the :hover.

**Comment by billreed63** [comment]
Maybe if we looked at the widget metadata and the selector have has a browser state like :hover we could
find that CSSRule and add a runtime selector for example

if we have the rule

```
a:hover{
text-decoration: underline;
}

```

We could modify the rule to

```
a:hover, a.maqHover{
text-decoration: underline;
}
```

And then add the ``.maqHover` to the widget in the theme editor to simulate the browser state

**Comment by JonFerraiolo** [comment]
Yes, I believe the .maqHover approach you outline above is the only visable option.

**Comment by billreed63** [comment]
@JonFerraiolo @jhpedemonte 
-> M8
