### ISSUE TITLE
Transition property should be a dropdown

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2078]
transition  String  “slide”     

A type of animated transition effect. You can choose from the standard transition types, “slide”, “fade”, “flip”, or from the extended transition types, “cover”, “coverv”, “dissolve”, “reveal”, “revealv”, “scaleIn”, “scaleOut”, “slidev”, “swirl”, “zoomIn”, “zoomOut”. If “none” is specified, transition occurs immediately without animation.

**Comment by doronrosenberg** [comment]
@jhpedemonte sound good?

**Comment by jhpedemonte** [comment]
Yes, I agree that this should be a drop down.

Where do the type values come from?  Are they specified in the metadata?

**Comment by doronrosenberg** [comment]
Yeah, we would store them in the oam as they are predefined values.
