### ISSUE TITLE
Mobile silhouette rotation broken in Chrome 19

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2080]
The silhouette isn't rotating on Chrome19. The iframe resizes, but the SVG silhouette doesn't do its 90 degree rotation.

I have a fix. Just need to create a updated Preview 5.0.1 build

**Comment by JonFerraiolo** [comment]
@waynevicknair, @childsb, @billreed63, @jhpedemonte

**Comment by JonFerraiolo** [comment]
I merged in the 5.0.1 fixes, so closing this now.

**Comment by jhpedemonte** [comment]
is there another bug open for using CSS to do the rotation?  Or we'll just keep it as it stands now?

(If we are to attempt CSS rotation, I would classify it as Priority Low)

**Comment by JonFerraiolo** [comment]
#1051, which is Prio-Low with no milestone
