### ISSUE TITLE
fix cookies from R&C

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#2084]
after removing the review servlet, we need to revisit the milestone 5 cookies we put in and see if they're still needed.

**Comment by jhpedemonte** [comment]
@waynevicknair 

Also, I think at some point we discusses moving them back to "/maqetta" (from M5's "/").

**Comment by jhpedemonte** [comment]
@childsb, I believe you changed some things related to R&C cookies.  Is there anything left to do here?  If so, push off to M7.

**Comment by childsb** [comment]
still used but prob can take a 2nd refactoring. reduced priority/moving to M7

**Comment by JonFerraiolo** [comment]
@jhpedemonte 

Too late to be messing with cookies. -> M8

**Comment by jhpedemonte** [comment]
-> @peller, is there anything left to do here?

**Comment by peller** [comment]
Sorry, I have no idea what this is.
