### ISSUE TITLE
M6 Migration: states.js script tag needs to be converted to require()

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2085]
see #1337

**Comment by peller** [comment]
we still need to decide whether to rename the file and combine with maqetta.js

**Comment by peller** [comment]
M5 files should now load against M6, but states code will not be functional until page is loaded/saved (or a migration script is run) to include new bootstrap info.  @JonFerraiolo @waynevicknair  Need to decide whether it's worth doing migration for this.

**Comment by JonFerraiolo** [comment]
I would say migrating user files to fix up their require and States.js items in HEAD as a nice-to-have for M6. If we can figure out how to write a shell script in 30 minutes for this migration, then we really try to make this happen to minimize the number of user support issues we have to respond to with the M6 release, but if the migration script is tricky and time-consuming, then we might not find the time.

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte to reassign

**Comment by jhpedemonte** [comment]
Not necessary to do anything for migration.  Since _States.js_ was renamed to _AppStates.js_, old script will silently fail to load when opening in M6.  Also, our code automatically adds the "maqetta" scripts to the page, ensuring that states will correctly work.  I verified this.

Closing.
