### ISSUE TITLE
Manually added style rules doesn't apply in design mode

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2089]
@JonFerraiolo @peller @jhpedemonte 

If I add this using source editor:

```
<style>
  .red {
    color : red;
  }

  .blue {
    color : blue;
  }

</style>
</head>
<body class="claro" dvFlowLayout="true" data-davinci-ws="collapse" id="myapp">
 <div class="blue">
   test</div>
 <div class="red">
 test2</div>
 <div class="blue">
test3</div>
 <div class="red">
   test 4</div>
</body>
```

None of those custom defined styles rules are applied when in design mode, even if I reload the html page.  They only show up correctly when previewed.

I couldn't find any existing bug for this, but my search skills are quite lacking.

**Comment by doronrosenberg** [comment]
Also should add: setting the class names using the properties panel also doesn't apply the style rules

**Comment by billreed63** [comment]
@JonFerraiolo @jhpedemonte 

-> M8

**Comment by JonFerraiolo** [comment]
I think this is mostly a dupe of #156

**Comment by jhpedemonte** [comment]
Closing as duplicate of #156.
