### ISSUE TITLE
Sample.html doesn't work with Preview in Browser

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2095]
@jhpedemonte @waynevicknair 

Since this commit (6bae0ed64f) which converted States.js to use AMD, Sample1.html no longer works with Preview in Browser. I expect this is because the old Sample1.html files had this in their headers:

```
<script type="text/javascript" src="maqetta/States.js"></script>
```

whereas newly created files now have this in their headers:

```
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" ... ,{'name':'maqetta','location':'../../../maqetta'}]"></script>
<script type="text/javascript">
require(["maqetta/States"]);</script>
```

So what are we going to do? Are we going to have to migrate all user HTML files? This is not a particularly pretty scenario since I expect the majority of users aren't running from Maqetta.org and instead using localhost (or in some cases their own intranet servers).

**Comment by peller** [comment]
see #2085

**Comment by peller** [comment]
We're talking about renaming the new module anyhow.  I suppose we could leave the old States.js around (but still migrate as many files as we can)

**Comment by jhpedemonte** [comment]
Or, this is an opportunity for adding migration code when loading a workspace:
1. Check version of Maqetta which last opened workspace.
2. If old (currently running 0.6, but workspace last opened by 0.5) then call migration code.
3. Migration code (in this case) changes the _State.js_ includes.
4. Update version in workspace settings files.

**Comment by peller** [comment]
I'm -1 on adding special migration code to our codebase, especially at this early stage, unless perhaps the migration code just did a simple round-trip open/save (which, in many cases, I think might do the trick)

**Comment by peller** [comment]
nah, still don't think this belongs on the client.

**Comment by JonFerraiolo** [comment]
I noticed two separate problems here. 

I tried opening Sample1.html in Maqetta page editor and then click on Preview button, and noticed in debugger that there is a duplicate set of require() calls in the version of Sample1.html that is used in Preview, with the second set of require() calls including a require(maqetta/States), which fails with old files because the old SCRIPT tag for dojo.js in that file doesn't define a location for the maqetta package. As a result, there is loader error because of inability to load `...project1/dojo/dojo/maqetta/States.js`

Then I got clever. I copied the preview URL from the browser address bar, then cleared my workspace and restarted the server, launched Maqetta, and without opening Sample1.html in the page editor, opened a second browser window and then pasted the preview URL into the address bar. In this case, we don't have the redundant set of requires(). But in this case, for a reason I don't understand, Dojo fails with a failure to load class dijit.layout.TabContainer.

**Comment by jhpedemonte** [comment]
Had a discussion with @peller yesterday, regarding my [previous comment](https://github.com/maqetta/maqetta/issues/2095#issuecomment-5167578).  He correctly pointed out some issues with running such migration code on the client.

However, my comment/algorithm applies just as well to migration code that gets run on server-side.  When a user loads a new version of the Maqetta server, it will notice that the version string in the _users_ directory is from an older server version and initiate the migration code.

In essence, this is similar to what we already do when upgrading maqetta.org.  Except now the migration code would be written in Java instead of a shell script.  And this would work for people who run their own server instance of Maqetta.

**Comment by JonFerraiolo** [comment]
I think I figured out a workaround (at least a sketch of one). I took the latest version of maqetta.core.server/WebContent/project/base/maqetta/States.js and added two lines, one at the top and one at the bottom. At the top I added:

```
require({"packages":[{'name':'maqetta','location':'../../../maqetta'}]});

```

At the bottom I added:

```
require(["maqetta/States"]);
```

With these chances, an old version of Sample1.html works just fine with preview in browser. (And presumably the same thing for any old user files.)

The above fixes aren't complete for two reasons:
- They don't take into account HTML files that are stored in nested folders. The first line shown above needs to be wrapped in logic that figures out where dojo is relative to the HTML file, and then add the right number of `.../`.
- If I make the above changes to States.js for both the page editor version of States.js and the maqetta.core.server version, I get  console errors in the page editor when refreshing a session where Sample1.html is open:

```
dojo.js: 1544 GET http://localhost:8081/maqetta/States.js?@revision@ 404 (Not Found)
Context.js:515 metadata resource (javascript-module, maqetta/States) does not specify 'library'
```

My guess about how to fix this second bullet would be to wrap both of my proposed fixes (i.e., the top stuff and bottom stuff) with some sort of check that amounts to "don't do this when loaded from the page editor". I'm not sure how best to check page editor vs otherwise, though.

Also, remember States.js is used by the review editor. I didn't see what happens with my proposed fixes for the review editor.

**Comment by peller** [comment]
short of providing a script to migrate files on the user's machine, we could tell them that existing content will only work after a load/save cycle.  Renaming the maqetta/States.js file would solve the script include problem without making it necessary to remove the script tag (it will just result in a 404 if not cleaned up)  Then, we would just need to make sure that the 'maqetta' packages setting makes it onto the page -- right now, it does not.

**Comment by jhpedemonte** [comment]
re: @peller's [last comment](https://github.com/maqetta/maqetta/issues/2095#issuecomment-5265556):

`maqetta/States.js` was renamed to `maqetta/AppStates.js`.  So what needs to be done here for migration?
