### ISSUE TITLE
Swipe gesture w/ SwapViews doesn't update Scenes in R&C

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2096]
The **SwapView** widget allows a swipe gesture for moving between the views.  But that gesture isn't accounted for in our code.

In particular, in R&C, which shows a "live" app, the user can use the swipe gesture.  However, the **Scenes** view isn't updated when the current view changes.  Afterwards, trying to select a new view from **Scenes** doesn't function correctly.

I believe that Dojox Mobile publishes an event when a new view is selected.  Might need to check for that in States, somehow -- but how to do it so it's not specific to this one case?

@doronrosenberg 

(see #2091 for related issue)

**Comment by JonFerraiolo** [comment]
Depends on #2157
