### ISSUE TITLE
review email should retry on failure

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#2099]
sometimes the review invitation errors out due to problems with the email relay.

the emails should be auto-retried.  this would involve moving the publish() logic to it's own thread and return from the /cmd/publish before the email is actually sent.

**Comment by peller** [comment]
let's try to rely on sendmail for this.  In the case where a reliable mail server isn't available, perhaps we should run our own relay on localhost?

There's a related issue where perhaps we should be directing failures from sendmail back to the user somehow.

**Comment by jhpedemonte** [comment]
For our internal server (lab9), I set up forwarding through **sendmail** -- which queues up outgoing messages and retries in case of failure.

---

In general, I agree with Adam -- why write this into our code when solutions (such as sendmail) already exist.  At most, I would say we mention this issue/solution in our release/setup notes.

@JonFerraiolo

**Comment by peller** [comment]
"In general, I agree with Adam" -- I like this quote.

So, taking this a bit further, I suppose we should have a way to redirect failure messages from sendmail to a particular user (lower priority)  That could probably be accomplished with some fancy .forward script.

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte so this doesn't fall through cracks

**Comment by jhpedemonte** [comment]
Given discussion above, I'm closing this.  Reopen if you disagree.
