### ISSUE TITLE
Share Dojo library between runtime and user libs

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#21]
Right now, we have duplicate versions of Dojo:  one for the runtime and one for the user library.  This is an artifact of how the user library code is set up.  We should amend that code to make use of the Dojo version used by the workbench, so we cut down on the duplication.

Later, we'll probably allow multiple versions of libraries, but at least one of those versions will be the Dojo used by the workbench.

**Comment by peller** [comment]
We split 'em out on purpose to make multiple versions of libraries possible... we may even be there now?  Are you looking to cut down on duplication in memory, on disk, over the network?

**Comment by childsb** [comment]
not sure i understand the goal with this bug....  what is 2 copies of dojo hurting?

**Comment by jhpedemonte** [comment]
> Are you looking to cut down on duplication in memory, on disk, over the network?

Yes, but mainly the latter.  But this may not be worth it, and we'll stick with the current situation.

**Comment by peller** [comment]
we may need the extra copy for security reasons (IFRAME) though I hear it's possible to cheat and share dojo across frames, iff the versions match, of course... again, may not be worth it.

**Comment by JonFerraiolo** [comment]
@jhpedemonte: OK to close this?

**Comment by jhpedemonte** [comment]
Closing.
