### ISSUE TITLE
UI fixes to color properties

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#210]
- Right now you can't easily remove a color value - not a ComboBox (no
  dropdown)
- We might offer a set of standard colors from the dropdown
- Lots of usability issues with dojo color picker

------- Comment #1 From Jon Ferraiolo 2010-11-10 11:55 [reply] -------

Right now we are showing "..." in some cases. That might be OK for complex
values, but need to think through whether we want to show the current color
value as a colored rectangle instead, or also offer the colored rectangle next
to the type-in box.

**Comment by childsb** [comment]
fixed with checking 06f26002115d99bc7725

review by @waynevicknair

**Comment by waynevicknair** [comment]
reviewed: OK. @childsb
