### ISSUE TITLE
Incorrect URLRewrite logic in ThemeModifier.js

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2101]
Prio-High just so @childsb will look at this and respond. Not urgent to fix.

In VisualEditor.js:233, we have this code:

```
                        var oldUrl = new Path(URLRewrite.getUrl(value.values[i][name]));
                        if(!oldUrl.isAbsolute){
                            var newUrl = oldUrl.relativeTo(filePath).toString();
                            var newValue = URLRewrite.replaceUrl(value.values[i][name], newUrl);
                            allValues.push(a);

                        }else{
                            var a ={};
                            a[name] = value.values[i][name];

                            allValues.push(a); //FIXME: combine with below
                        }
```

The `isAbsolute` check seems to be wrong because it appears to be checking against a boolean flag, but instead `isAbsolute` is a function. Therefore, you'd think the statement should be changed from `if(!oldUrl.isAbsolute){` to `if(!oldUrl.isAbsolute()){`, but when I tried that, then some path calculations got messed up. Therefore, my conclusion is that we should remove the `if(...)` and the then-clause, and just leave the code found in the else-clause.

@childsb - any thoughts?

**Comment by childsb** [comment]
yeah it seems like this case would always fall through to the else.  We probably take care of the URL re-write somewhere else in code.

As far as design goes, if we're having to relativize many style values, it would be better to do it in one place (like here).  If we have relative URL bugs in the future, this may be worth re-investigating and fixing.

**Comment by childsb** [comment]
I looked for this code in visual editor and it seem to be removed.  closing issue.

**Comment by JonFerraiolo** [comment]
@billreed63 moved the code from VisualEditor.js to ThemeModifier.js with this commit: https://github.com/maqetta/maqetta/commit/17d52700518bd1476722b28df4f0d9f5ac3bd65e#maqetta.core.client/WebContent/davinci/ve/VisualEditor.js

Reopening and assigning to @billreed63
