### ISSUE TITLE
R&C: Link in invitation fails

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2108]
I'm on a server without e-mail, so I copied the link in the new review dialog and pasted it into my browser bar. The link was ( http://localhost:50000/review/tonyErwin?revieweeuser=tonyErwin&version=20120420112637 ).

When doing so, I see the following in my browser:

```
HTTP ERROR 404

Problem accessing /review/tonyErwin. Reason:

    ProxyServlet: /review/tonyErwin
Powered by Jetty://
```

**Comment by JonFerraiolo** [comment]
Reassigned to @aerwin.
@childbs

**Comment by aerwin** [comment]
@childsb , I think you may have recently disabled the review servlet? Is that true? If so, what was your plan for handling review links?

**Comment by aerwin** [comment]
Fixed with above commit.
