### ISSUE TITLE
ipad theme doesn't look right

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2110]
When working on the mobile theme editor test suite, the iPad theme doesn't look right. I first noticed when cloned iPad theme, but also see the same thing if open original iPad theme directly.

It doesn't look like the background gradients are right when compared to iPhone:

iPad theme:
![iPad theme](http://i.imgur.com/2SJK3.png)

iPhone theme:
![iPhone theme](http://i.imgur.com/wygdI.png)

**Comment by billreed63** [comment]
theme Ipad theme is different from the iPhone theme. for ipad the some of the selectors are overloaded by ipad.css.

So the theme is correct

**Comment by aerwin** [comment]
Hmmm... yeah, guess you're right. Sorry about that... guess I never noticed the subtle difference when doing theme editing testing in the past. :)
