### ISSUE TITLE
Theme Editor: Selection and Props Palette Behaving Strangely

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2111]
After cloning a mobile theme (such as iphone), I'm seeing a lot of strange behavior with selection and updating of the props palette making it very difficult to make progress:
- Some widgets (like Heading) through an exception when selected:

```
Uncaught TypeError: Cannot read property 'rootNode' of null
_1b1b._createWidgetRows.prop.valuesdavinci.js:36459
_383dojo.js:4555
_44fdojo.js:5668
_1b1b._createWidgetRowsdavinci.js:36458
_1b1b.onWidgetSelectionChangedavinci.js:36433
_65._widgetSelectionChangeddavinci.js:508
_383dojo.js:4555
_492.(anonymous function)dojo.js:6092
on.emitdojo.js:5349
on.emitdojo.js:5371
_396.emitdojo.js:4635
publishdojo.js:4685
_4b7.publishdojo.js:6255
_2019.onSelectionChangedavinci.js:46696
_25edojo.js:2636
_257.onSelectionChangeThemeEditor.js:2668
_497.around.advicedojo.js:6099
_492.(anonymous function)dojo.js:6088
_257.selectThemeEditor.js:2665
_1.onMouseDownThemeEditor.js:48
_2cc.editFrameOnMouseDownThemeEditor.js:3654
_383dojo.js:4551
```
- Selecting some widgets (like Button) shows wrong information (refreshed page to ensure not caused by previous exception). Note Button selected in screen shot, but vastly different background color shown in Props Palette:

![Bad info after selection](http://i.imgur.com/cdk5C.png)
- It seems that sometimes after a widget has been selected, the values for that widget stay in Prop Palette as select other widgets. For example:
  - Go to controls tab on theme page
  - Select Button and notice Background in Props Palette seems correct
  - Select Switch and notice Background in Props Palette seems to update correctly to show Switch info
  - Select Button again and continue to see Switch info in Props Palette

**Comment by aerwin** [comment]
There's also a whole lot of inconsistency in terms of whether making changes to the Props palette are reflected immediately. In a many cases, I have to reload the page to get the theme editor to update.

**Comment by JonFerraiolo** [comment]
I'm guessing these regressions are a result of my changes to States.js. The 'rootNode'  being null is what makes me suspicious. You see, with States.js and application states, I changed everything to use nodes instead of widgets, and therefore rootNode instead of rootWidget.
