### ISSUE TITLE
gmail treats Maqetta.org invitations as spam

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2114]
@childsb @jhpedemonte @aerwin @peller

One of our users has reported that a review invitation didn't get to his gmail account, so I checked with @waynevicknair who said:

> Gmail may have put the review request in the 'Spam' folder. It always does that for me. 

So I tried inviting myself (using my gmail account) to a review and discovered, yes, gmail put the invitation into the Spam folder. Here are the steps I took to fix my gmail account to accept review invitation from maqetta.org:
- In Gmail, on the left side, I pressed on "More" which makes "Spam" visible.
- Then I clicked on Spam, and voila, there is the review invitation email
- I clicked the checkbox next to the Maqetta review invitation, and then under the "More" menu above the list of spam emails, I issued command "Filter messages like these"
- In dialog that appears, I clicked on the "Create filter with this search" link at the bottom right to bring up a supplemental dialog. On that dialog, I checked the option "Never send to spam".
- Then I clicked on "Create filter" to create the filter that allows review invitations from maqetta.org
- Then I returned back to Spam view, and with the review invitation email selected, I clicked on "Not spam"

It is an understatement to say that gmail is widely used.

What can we do to overcome this limitation? Ideally, gmail wouldn't treat maqetta.org emails as spam, but I would guess they are filtering against the kinds of emails we send out (eg, no return email address). We could offer an option whereby we build an email that the user could send from his own email account (i.e., browser causes his local mail program to appear). I'm not sure how hard that approach would be to implement or what side effects that approach offers.

Another angle is to warn authors about this somehow, so that they can tell the reviewers to look in their spam folders. Of course, that's less than ideal.

**Comment by peller** [comment]
We will probably never know what Google uses for criteria, but we ought to take a look at software like spam assassin.  Here are the headers I see on my mailer:

X-Spam-Checker-Version: SpamAssassin 3.2.3 (2007-08-08) on
    nibbler.dojotoolkit.com
X-Spam-Level: 
X-Spam-Status: No, score=0.8 required=5.0 tests=BAYES_00,HTML_MESSAGE,
    MIME_HTML_ONLY,RDNS_NONE,WEIRD_PORT autolearn=no version=3.2.3

I suspect the fact that we use HTML and embed a link doesn't help, and the "weird port" number may also be a contributing factor.

We could also look at using [SPF](http://en.wikipedia.org/wiki/Sender_Policy_Framework)

**Comment by jhpedemonte** [comment]
-> M7

**Comment by peller** [comment]
possible short-term fix, in lieu of having a reverse proxy and getting rid of the port=55556: how about setting up a servlet or equivalent in Joomla to forward r&c requests on port 80 to port 55556, then put the (default) port 80 in the e-mails?  We'd probably have to establish a config setting for this.

**Comment by jhpedemonte** [comment]
Yes, I was thinking along these lines as well, I just don't know how to do it.

@JonFerraiolo, do you know how we could do something like this in Joomla?

**Comment by JonFerraiolo** [comment]
I'd focus on getting the app running on :80 with user management in the app (vs Joomla) rather than investing time in various short-term trickery to work around Joomla issues.

**Comment by JonFerraiolo** [comment]
I upgraded to M7/Prio-High. Isn't the spam problem one of the top priority problems we have?

**Comment by aerwin** [comment]
Potentially related issues?:
- #437 ("Review and Commenting Email notifications sender")
- #2896 ("review invitation has bogus e-mail")

**Comment by JonFerraiolo** [comment]
When I used my gmail account when testing on maqetta-test today, the activate notice went to my gmail spam folder

**Comment by jhpedemonte** [comment]
I wonder why?  No longer using odd port number.

**Comment by peller** [comment]
wonder if it has something to do with the address being behind a firewall and not verifiable... and the from: address still says maqetta.org which doesn't match the sender, in this case

**Comment by JonFerraiolo** [comment]
Note that the email came from the maqetta-test server, not maqetta.org.

**Comment by peller** [comment]
Right, that's my point... the from address still says maqetta.org, which is not verifyable and does not match the actual SMTP server used.

**Comment by jhpedemonte** [comment]
With removal of odd port number in the link, and posting correct "from" address, we haven't seen any more instances of the registration or review/commenting emails going to spam.

Closing this one as fixed.  If we come across any more issues, open a new bug.
