### ISSUE TITLE
ActionBar, floating properties palette

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2116]
The idea here is to support a more table based UI where we would move the toolbar to an action bar that is displayed when the user selects a widget, also to move the properties palette from the right to a floating palette that can be moved around the screen as well as hidden, pinned, shown. Combining the existing SmartInput with properties palette to create an uber smartInput

**Comment by billreed63** [comment]
Jin's notes from a couple of months ago about future interactive behavior:

---
- (Question) What would happen if the user:

a) single-clicks (single-tap on tablet) on the Button's text content; selected state. The second single - clicks on the text content >  edit text mode

b) single-clicks (single-tap on tablet) on part of the Button that isn't the text content (e.g., the border) selected state with action bar 

c) double-clicks (double-tap on tablet) on the Button's text content : edit text mode

d) double-clicks (double-tap on tablet) on part of the Button that isn't the text content (e.g., the border) : action bar with property box (I mean both : action bar AND property dialog)

Which of the above (a-d) would cause:
- Text editing of the button's label : the second single click on the Button's text content(= single click after selected state on the text) or c) 
- Action Bar to appear : b) or d)
- Property dialog to appear:   d) or click on the property icon on the action bar

---

Could you please walk through what she says carefully to see what you think she is saying? 

After you do that, my thinking is that we should tweak her recommendations just a bit (mostly to take into account some advanced features such as complex widgets such as Tree, and also the radio buttons for rich HTML vs plain text). Here is what I would propose:
- User drops a new widget on page =>
  Show Focus chrome around the widget
  Show SmartInput:
  Short-term: same as today
  Long-term (as time permits): for simple widgets like Button or <label>, SmartInput puts a edit control positioned as best we can over the widget's text, but retain the radio buttons for rich HTML content
- Upon closing SmartInput or click (or tap) on an unselected widget =>
  Show Focus chrome around the widget
  Show ActionBar
- User clicks on currently selected widget (either quickly (<.5s = doubleclick) or slowly (>.5s)) =>
  Second click is over the widget's text is (e.g., over dijitButtonTextContent)
  Show Focus chrome around the widget
  Show SmartInput (see above)
  Second click is not over the widget's text, or we have a complex widget (e.g., TabContainerm, Tree or gridx)
  Show Focus chrome around the widget
  Show ActionBar
  Show floating Properties palette
- ActionBar contains the following 2 buttons, along with a few others:
  Button which will bring up SmartInput (disabled for widgets that don't offer SmartInput)
  Button which will bring up Properties overlay palette

**Comment by JonFerraiolo** [comment]
@jmockler

Some details to work out:
- With proposed UI makeover which a more tablet-friendly approach to various parts of the UI, are we still contemplating an ActionBar?
- What happens with ActionBar with multiple selection? We could show an ActionBar over each selected widget, but imagine if you had a toolbar filled with 16x16 icons and the user wanted to select several of these icons at once. The ActionBars would sit on top of each other and dominate over those poor little icons. Perhaps there would only be a single ActionBar then.

**Comment by JonFerraiolo** [comment]
Pushing to M7 - no way we can implement this for M6

**Comment by JonFerraiolo** [comment]
Reassigned to me. I'm actively working on it.

**Comment by JonFerraiolo** [comment]
Fixed by ui makeover mega checkin: a7d8ede1ced8f2e4ef2c7c
