### ISSUE TITLE
SIngle user - do we timeout?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2119]
(Research and investigate)

@childsb @billreed63  

When running as single user (maqettaUser), it seems like I sometimes get timed out. What I'm seeing in particular is that I download a build, run localhost as single-user, and if I neglect my Maqetta window, I get redirected to http://localhost:50000/maqetta/welcome, which will totally baffle our users who run locally since the welcome page forces them to login, but the server is running single-user.

**Comment by billreed63** [comment]
We have code in to prevent this

UserActivityMonitor

```
setUpInActivityMonitor: function(doc) {
        if (!this._runtime){
            // we need to wait to add runtime to avoid chicken or egg
            try{
                this._runtime = require("davinci/Runtime");
           }catch(e){
                console.warn("FAILED: failure for loading davinci/Runtime");
                return;
           }
        } 
        if (this._runtime.singleUserMode()) {
            this._MaxInactiveInterval = -1; // no timeout
        } else {
            this._firstPoll = true;
            this._MaxInactiveInterval = 60 * 5; // defalt this will be changed when we get from server
            this.keepAlive(); // get the timeout value
            this.addInActivityMonitor(doc);
            this.subscribe('/dojo/io/load', this.lastServerConnection);
            this.userActivity(); // prime the value
        }

    },
```

What are you seeing, if you are seeing warning div across the top, that would be the activity monitor. If you are seeing the 
"Your session has timedout" dialog that gets displayed on any communication error with the server.

**Comment by JonFerraiolo** [comment]
actually, I suspect it's the server that's timing out, not the client

**Comment by JonFerraiolo** [comment]
-> @childsb 
I'm pretty sure that if running single-user, we never set an explicit timeout value. As I analyze the code, the only time we set an explicit session timeout interval is in Login.java, which is only invoked when running multi-user. Therefore, my guess is that we end up using Java's default timeout of 15 minutes. (Note: I'm guessing that the server tells the client the session length is 60 minutes even if it is actually 15 minutes)

What I'd really like is for us to set session timeout to a very large value if running single-user. Basically, in single user mode, we should just run forever.

**Comment by billreed63** [comment]
What I have seen in my testing is that we get a -1 from the server for a timeout value in single-user mode

**Comment by childsb** [comment]
Do we have a good recreate for this scenario?

Here's how it works with localhost user.  If we're not running in localhost mode, we create the User object, and dangle it off the session user variable with an explicit time out.  If we're are running in localhost mode, the user object isn't dangled.  Instead there's a getLocalHostUser(..) call that returns the localHost user object.

So there shouldn't be a timeout on any of the localhost stuff.  Has this been a problem in M5?  Could it be the client side timeout logic not understanding the value?

**Comment by billreed63** [comment]
The client side code checks for single user mode and if true we set the timeout on the client side to -1 which tells the rest of the code that the timeout logic is disable.

```
if (this._runtime.singleUserMode()) {
            this._MaxInactiveInterval = -1; // no timeout
```

```
addInActivityMonitor: function(doc) {
        if (this._MaxInactiveInterval === -1) { // no session timeout
            return []; // no montioring
        } else {
            var connections = [
            //dojo.connect(doc.documentElement, "mousemove", this, "userActivity"),
            dojo.connect(doc.documentElement, "keydown",  this, "userActivity"),
            //dojo.connect(doc.documentElement, "DOMMouseScroll", this, "userActivity"),
            //dojo.connect(doc.documentElement, "mousewheel",  this, "userActivity"),
            dojo.connect(doc.documentElement, "mousedown",  this, "userActivity")
            ];
            return connections;
        }


    },
```

**Comment by childsb** [comment]
I did a big cleanup around userInfo / single user mode: 24121c3d98b0319df5a02931771cf03ce9fecd7d

Some changes:
1) Refactored userName --> userId (unique, may be auto generated)
2) Added first name / last name fields (not implemented in UI
3) Replaced userName in UI with email address (notably in the toolbar)
4) Moved all single user mode to one point.  Bypassed the session variable when in localMode
