### ISSUE TITLE
Use deferred/promises when loading resources in `loadRequires()`

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2126]
The code in `loadRequires()` makes a simple call to `require()` in the context of the VE iframe, in order to load the given module.  Later, we instantiate objects assuming that resources have been properly loaded.

The only reason this works now is because we put the Dojo loader in synchronous mode (the default until Dojo 2.0, I assume).  See commit d54d19c78f5896fb86739872e9abf4ca8ab34bcb.

In order to fix this, we have to use Deferreds/promises in the `loadRequires()` code, such that later code runs in the `then()` callback.  This will ensure that the resources have been loaded before we attempt to use them.

---

Might not be an issue until Dojo 2.0, so feel free to push off into future.

**Comment by peller** [comment]
Good point - we should try moving the VE to async:true, for performance reasons, though Dojo probably won't force us to do this until 2.0.  Compared to moving the Workbench and the user output to async, this is relatively low-priority.

**Comment by peller** [comment]
still need to turn on async:true and convert usage in some metadata helpers
