### ISSUE TITLE
Sticky note icon not working

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2127]
(Running Mac/Chrome)

If you drag/drop a Sticky Note from widget palette, the RTE control appears, but if you click on the Sticky Note icon on the toolbar, a default sticky note widget is added to the page, but the RTE control doesn't appear.

Double-clicking on the sticky note widget doesn't work either. However, double-clicking on the selection border works fine.

(I suspect I broke it when I made massive changes to SelectTool.js and Focus.js to allow dragging widgets by pulling on the interior)

**Comment by billreed63** [comment]
When I make a div position absolute I can no longer get the smart input by double clicking, along the same lines if I make the sticky notes postion relative I can get smart input by double clicking. What does position have to do with selection?

**Comment by billreed63** [comment]
We have never display RTE on creation of sticky note from the toolbar, but when you doubleClick on the sticky note we should be displaying the RTE...
