### ISSUE TITLE
Column editing/resizing in HTML tables

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2129]
#331 ("Column width control for tables") got taken over by the GridX Set-up Wizard. We'll need to re-examine the design for HTML tables. Perhaps aspects of the preview panel in the GridX Wizard that allows column resizing is applicable, but I don't think most of the GridX Wizard design makes sense for HTML tables.

**Comment by aerwin** [comment]
At one point, I was thinking at least parts of the third panel of the GridX wizard could be leveraged for HTML tables. Though I had envisioned changing the styling to be more of a "sketch" to mimic a plain HTML table rather than look like a full-fledged GridX.

![screenshot](http://i.imgur.com/yxcMn.png)

The main advantage of this approach would be gaining the rich support GridX already has for column & row resizing/rearranging.

However, I no longer think this makes much sense because:
- one of the big goals of HTML table support would be to help the designer build layouts (meaning absolutely anything could be put in placed in each cell) 
- would at least eventually need to support more advanced table-related props like rowspan, colspan, etc. (that don't mean as much to a data source driven widget like GridX)

So, I'm still thinking it through, but guessing we probably need to go with something more in line with @JonFerraiolo 's original proposal from #331:

> Our &lt;table&gt; element support is actually pretty good right now, but the one big
> thing that users need is the ability to control column widths. Right now, all
> columns are set to auto-sizing (the browser default). Often, the user needs to
> set fixed widths (eg 100px or 10em) or percentages (e.g., 33%) when using
> tables either for tabular information or (sorry, this is going to happen) for
> layout.
> 
> Here is a proposal. 
> - Add a Select Column command to the context menu when a table cell is
>   selected. This in effect selects one of the <col> elements in the current
>   table. (If the table doesn't have <col> elements, then add them as <col/>, one
>   for each column.)
> - When a column in selected, the canvas should put a selection highlight around
>   the given column and the Properties palette should show <col> as the widget
>   name.
> - The user can set anything on the Properties palette, but our "dealing with
>   tables" tutorial(s) should warn users that browsers only support a few CSS
>   properties on <col> elements. (width, borders, backgrounds - that's about it, I
>   think)
> 
> Looking at the list above, this is a non-trivial assignment that will touch
> several sections of the code.

**Comment by JonFerraiolo** [comment]
@jmockler @billreed63 

@aerwin - your analysis and proposal make sense to me so far. 

Note that we are likely to have an ActionBar in the next release. One of things we might put into the ActionBar is a select dropdown button which shows relevant select actions that you can apply to the current widget. In this case, if you have a table selected or any part of a table selected (e.g., a cell), maybe the ActionBar would expose "Select column". If a cell or column is selected, then expose a "Select table" action. And of course we will usually want to show the various select commands that I added to the Preview 6 context menu: Select parent, Select ancestor..., and Unselect all.

I suspect we will need to beef up SelectTool.js to show column selection. Have you thought about that yet? My instincts are that we need yet another well-placed helper function.

**Comment by aerwin** [comment]
@JonFerraiolo - thanks for the pointer to `SelectTool`. I've not really been in there, so I'll have to look around a bit and give it some thought. But, yes, I imagine you're right we'll have to augment that with a helper.

As for actions in the action bar, are we thinking the mechanism for plugging in the actions to show will be the same as the mechanism for plugging into the context menu today? Or, will we invent something new? Either way, this leads me to a few other issues I've been thinking about....
- We need a mechanism for widget library plug-ins to be able to contribute actions specific to widgets in that library. (And, this probably needs to be spun off into it's own issue.)

Currently, workbench plugins can specify actions (like `ve.plugin.js`, but not widget libraries. I had alluded to this in #331, but it became irrelevant once we decided to use a wizard for GridX smart input:

> NOTE: In order to add a new menu option, Maqetta architectural changes would need to be made to allow for widget libraries to supply custom actions. One way this could possibly be done is for a new getActions function to be added to the widget helper interface that returns an array of actions.
- Presumably , **Select table**, **Select column**, and **Select row** should come from the `davinci.html` widget library. 
  - Since these actions are related to selection, I'd think we'd want them to appear next to the selection actions from `ve.plugin.js` which implies some intelligence needs to be applied to actions contributed by widget libraries (e.g., need some sort of categorization metadata).
- **Select table**, **Select column**, and **Select row** are in many ways special cases of **Select parent** and **Select anscestor...** options. Will this lead to confusion?

```
               {
                    iconClass: "editActionIcon",
                    label: "Select parent",
                    action: "davinci/ve/actions/SelectParentAction",
                    menubarPath: "davinci.edit/cut"
                },
                {
                    iconClass: "editActionIcon",
                    label: "Select ancestor...",
                    action: "davinci/ve/actions/SelectAncestorAction",
                    menubarPath: "davinci.edit/cut"
                },
                {
                    iconClass: "editActionIcon",
                    label: "Unselect all",
                    action: "davinci/ve/actions/UnselectAllAction",
                    menubarPath: "davinci.edit/cut"
                },
```
- Currently, HTML table actions (like **Insert column after**, **Insert column before**, etc.) are contributed by `ve.plugin.js`, but I think those need to be moved to the davinci.html plugin to live with all the other HTML-table related actions to be built.

```
                {
                    iconClass: "editActionIcon",
                    label: "Insert column after",
                    action: "davinci/ve/actions/AddColumnAction",
                    menubarPath: "davinci.edit/cut"
                },
                {
                    iconClass: "editActionIcon",
                    label: "Insert column before",
                    action: "davinci/ve/actions/AddColumnBeforeAction",
                    menubarPath: "davinci.edit/cut"
                },
                {
                    iconClass: "editActionIcon",
                    label: "Remove column",
                    action: "davinci/ve/actions/RemoveColumnAction",
                    menubarPath: "davinci.edit/cut"
                },
                {
                    iconClass: "editActionIcon",
                    label: "Insert row after",
                    action: "davinci/ve/actions/AddRowAction",
                    menubarPath: "davinci.edit/cut"
                },
                {
                    iconClass: "editActionIcon",
                    label: "Insert row before",
                    action: "davinci/ve/actions/AddRowBeforeAction",
                    menubarPath: "davinci.edit/cut"
                },
                {
                    iconClass: "editActionIcon",
                    label: "Remove row",
                    action: "davinci/ve/actions/RemoveRowAction",
                    menubarPath: "davinci.edit/cut"
                },
```

**Comment by JonFerraiolo** [comment]
I agree with all of the above. 

One worry is that getting this all implemented in the right way may take a ton of work and time. It might not be feasible to complete in the M7 cycle. 

Another issue is that (I'm pretty sure) no one likes our current plugin system (eg ve.plugin.js). At some point we wanted to redo all of that. If moving some action definitions into the widget libraries slided into a more general re-write of our plugin system, then that's even more time and effort.

**Comment by aerwin** [comment]
In the spirit of trying to keep the plugin system simple for now and avoiding redesigning/rewriting it (as @JonFerraiolo points out we want to avoid in M7)... with the above commit I added the capability for UI plugins to specify "davinci.actionSets" in package.json. Actions found by this approach are just added to the end of action sets defined by the base Maqetta plugins.

**Comment by aerwin** [comment]
This is all coming along pretty well with the three commits above, but there are still a number of items to think about and deal with. A rough, high-level list of some of the items is included below. Some of these items are already represented by separate issues, and I may create additional issues for some of the others. Some of the items are likely to to be deferred to a future release.
- Resizing
  - resize knobs are enabled on selected COL, TD, and ROW elements. @JonFerraiolo and I have debated disabling resize knobs on these entities for a few reasons, but I want to take a closer look at this before we make that final determination. Especially since resizing with the knobs is equivalent to changing width/height in the props palette.
- Selection chrome on selected column becomes less accurate (too small) as more rows and columns are involved in the selection
- Add smart input on table creation (#2567)
- Undo of row/col additions doesn't seem to work (#2566)
- Need to expose cellpadding and cellspacing on TABLE element
- multi-selection of table-related elements
- need to think about standard Cut, Copy, Paste, DELETE actions in toolbar when table item selected (one issue is Delete when <col> is selected is just going to remove the <col>, but not any of the cells)
- area select selects colgroup element in addition to table cells/rows since since colgroup isn't parent of them (which looks really odd)
- Add HTML table test plan
- I currently have span, colspan, and rowspan attributes visible in widget-specific properties, but thinking we need to hide them as the implications of setting them are kind of dangerous. E.g., if a user makes a TD have col span 3, he's going to have too many TD elements in the row unless he deletes them. Implies we eventually need actions for things like Merge Cells, Split Cells, etc.
- if user has set colspan on a TD, a column selection chrome (to be really accurate), should not be rectangular
- COLGROUP and COL elements are not parents of table cells, so potential exists for users to muck around with them. So, when we go to do a column action (like Select column) on a given cell we might not actually find a COL element. Currently, writing out warning messages to console, but one coud argue we should try to clean this up for the user.
- User dragging of rows/cols to rearrange table

**Comment by JonFerraiolo** [comment]
> - Resizing
>   - resize knobs are enabled on selected COL, TD, and ROW elements. @JonFerraiolo and I have debated disabling resize knobs on these entities for a few reasons, but I want to take a closer look at this before we make that final determination. Especially since resizing with the knobs is equivalent to changing width/height in the props palette.

I played with the current resize nobs and what we have now seems to work reasonably well, although the nobs are (from a visual perspective) a little weird and unexpected. What would be ideal is if we _not_ show the nobs, and when the mouse is hovering over the divider between columns (or even rows) we should a custom cursor with a double-vertical-line (double-horizontal-line if for rows). The current underlying column resizing code might be good enough as is.

> - Selection chrome on selected column becomes less accurate (too small) as more rows and columns are involved in the selection

See my comment on this commit: https://github.com/maqetta/maqetta/commit/f13b6c8408bddd88c99152e537e0ed8ebd6c1796#commitcomment-1465613

> - Add smart input on table creation (#2567)

I'm thinking #rows, #cols, cellspacing (default:0), cellpadding (default:0), border (default:0), table-layout (default:true)

> - Undo of row/col additions doesn't seem to work (#2566)

That will be a bit of work

> - Need to expose cellpadding and cellspacing on TABLE element

See notes above. I think we also want to expose border attribute, and put table-layout on SmartInput (and probably also need to add it to Properties palette, which should be just adding a row to SwitchingStyleViews.js.)

> - multi-selection of table-related elements

Is there something really broken without multi-select of table cells and cols? What can someone do today with multi-select since prop palette doesn't support changes with multiple selection

> - need to think about standard Cut, Copy, Paste, DELETE actions in toolbar when table item selected (one issue is Delete when <col> is selected is just going to remove the <col>, but not any of the cells)

Seems to me either we turn off CUT and DELETE for cells. For columns, either turn off those commands (and require use of "delete column" command) or make sure the cells are deleted when deleting the column.

> - area select selects colgroup element in addition to table cells/rows since since colgroup isn't parent of them (which looks really odd)

Hmm. That might take some work to do something reasonable.

> - Add HTML table test plan
> - I currently have span, colspan, and rowspan attributes visible in widget-specific properties, but thinking we need to hide them as the implications of setting them are kind of dangerous. E.g., if a user makes a TD have col span 3, he's going to have too many TD elements in the row unless he deletes them. Implies we eventually need actions for things like Merge Cells, Split Cells, etc.

Fine with me

> - if user has set colspan on a TD, a column selection chrome (to be really accurate), should not be rectangular

Non-rectangular Focus seems really complex...

> - COLGROUP and COL elements are not parents of table cells, so potential exists for users to muck around with them. So, when we go to do a column action (like Select column) on a given cell we might not actually find a COL element. Currently, writing out warning messages to console, but one coud argue we should try to clean this up for the user.

How would user muck with COLGROUP and COL? You mean they might delete a COL by selecting in outline palette and then deleting it? I expect we won't have time to idiotproof that feature for M7

> - User dragging of rows/cols to rearrange table

I tried to drag TR elements in outline palette and there seemed to be no problem with that - it did what you would expect. For COL elements, it moved the COL elements ok, which caused column width assignments to move, but of course a user might expect that moving a COL would move the cells too. Do you know what happens if you drag/drop COLs in page editor?

**Comment by aerwin** [comment]
@JonFerraiolo thanks for the thorough feedback! To make for easier tracking and continued discussion on some of the issues, I've started to spin off some new ones:

#2578 Eliminate resize knobs on table columns (and replace with custom cursor on hover)

#2579 Update selection chrome for col with span > 1

**Comment by aerwin** [comment]
With the creation of the following additional spin-off issues (and a couple small commits), I'm going to close #2129:

#2581 Think about multi-select issues with HTML tables

#2585 Deal with Copy/Cut/Delete actions on HTML table elements

#2584 HTML tables -- area select selects COLGROUP element

#2582 Add HTML table test plan

#2586 Provide robust means for editing span/colspan/rowspan attributes on HTML table-related elements

#2587 Selection rectangle for column containing cells that span can overlap non-selected columns

#2588 HTML tables -- Correct situations where user has incorrectly edited table-related elements in outline or source pane

#2589 Dragging/dropping of COL elements
