### ISSUE TITLE
Properties view - make id/class use dijits and separate rows

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2132]
@jhpedemonte @JonFerraiolo 

Playing with TweetView I found that the generated ids for ScrollViews were quite long and hard to edit with such a small input field.

My suggestion is to have them on separate rows, with the combo/input taking up as much space as possible.  Also use that time to switch IDs to use a dijit textbox.

Sound good?

**Comment by jhpedemonte** [comment]
Yeah, I've noticed the same issue before.  I'm fine with this.

> Also use that time to switch IDs to use a dijit text box.

What will this get us?  Is this just for consistency, or can we make use of the added functionality?

Setting for M6/Med, but may (probably) slip.

**Comment by JonFerraiolo** [comment]
I expect it would take 1-4 hours to switch to separate lines for class and ID. That would be nice to have as soon as possible, but I agree other things are higher priority. 

I'm also curious why we need a dijit text box. Aren't we using regular old INPUT elements in other places in the properties palette?

**Comment by doronrosenberg** [comment]
@JonFerraiolo For class we have to use a dijit as we want a dropdown that is editable.  Dijits are usually larger than html widgets and usually have a slightly larger default font size (depends on your browser/os), so having dijits and html widgets together will look inconsistent.

**Comment by JonFerraiolo** [comment]
ah, that makes sense
