### ISSUE TITLE
Support Dojox Mobile 1.8 additions (widgets, changes)

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2135]
The changes/additions in dojox.mobile 1.8 seem fairly straightforward.

Most of the new widgets should be easy to support.  There are some new transitions, but I don't think there's anything we need to do there other than to make sure those transitions appear as choices in the Properties view (probably. just need to add to add to metadata).  And there are some additions to existing widgets, making them "editable" -- again, not sure what (if anything) we need to do in that case.

A few of the widgets will require some more thought.  There are a couple of "overlay" widgets (_dialog_ and _menu_), and we've yet to have a good solution for overlay widgets (whether mobile or desktop).

And then there's the **badge** "widget", which doesn't seem to be a widget at all, but functionality that you can add to the page or an existing widget.  Might be similar to dojox.mobile.ProgressIndicator (#462).

**Comment by doronrosenberg** [comment]
New widgets:
- ~~Accordion (work is there, but widget is broken)~~
- ~~Badge~~
- ~~Grid Layout (think tables for mobile)~~
- ~~IconMenu~~
- Audio
- Video
- Opener (shows a dialog with a arrow, ios like)
- ~~ProgressIndicator~~
- ScreenSizeAware (allow 2 views next to eachother if wide enough, else panel to panel)
- SimpleDialog
- Treeview (view a tree using EdgeToEdge)
- ~~Valuepicker~~
- ~~ValuePickerDatePicker~~
- ~~ValuePickerTimePicker~~
- ~~DatePicker~~
- ~~TimePicker~~
- ~~SearchBox~~
- ~~Container~~

Broken widgets
- ~~Carousel~~
- ~~RoundRectList (nothings shows when you dnd it)~~
- ~~Tabbar looks ugly when first added~~

Existing widgets than need changes
- ~~FixedSplitter (no properties to edit width, might need a smartinput like border container)~~
- ~~Rating needs to move from untested~~
- ~~Scrollpane is now ScrollablePane~~

**Comment by doronrosenberg** [comment]
@peller Accordion is currently broken (see http://bugs.dojotoolkit.org/ticket/15672 which I just filed), so we won't be able to support it unless it gets fixed.

**Comment by doronrosenberg** [comment]
So looks like this is now complete, as TreeView won't work as pure markup (!) and also only supports data structures that have one root only.  I'll check in my changes under untested for now.
