### ISSUE TITLE
Eclipse project, new file, download: bad reference to claro.css

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2141]
@peller @billreed63 

I created a new Eclipse project, new HTML File, added a Button, saved. Then tried to download a ZIP. The file I created did not preview correctly when unzip'd into my localhost web service because the reference to claro.css looks like this in the HTML file:

```
<style>@import "../../eproj1/WebContent/themes/claro/claro.css";@import "lib/dojo/dojo/resources/dojo.css";@import "app.css";
</style>

```

The problem is the `../../eproj1/WebContent/`, which doesn't work with ZIP download because the ZIP starts with the `WebContent/` folder and doesn't include the project folder. What's weird is that the `../../eproj1/WebContent/` is unnecessary. The file shows up correctly if I hand-edit the HTML file (after download) and remove the `../../eproj1/WebContent/`

**Comment by childsb** [comment]
Error in findResource(...) was returning theme files for all projects.  since the claro in project1 showed up first in the search results, it was the one being added to the new html.  this would load OK in editor but not after download.

fixed here:

387d021fc3a194901e85b9804824989623c64320
