### ISSUE TITLE
Duplicate module definitions for 'maqetta'

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2142]
When we create a new HTML file and add the file Dojo widget, there is a SCRIPT tag in the user's doc that looks like this:

```
<script type="text/javascript" data-dojo-config="'async':true,'parseOnLoad':true,'packages':[

NOTE THIS ONE:
{'name':'maqetta','location':'../../../'},
{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'shapes','location':'../../shapes'},

NOTE THIS ONE, TOO
{'name':'maqetta','location':'../../../maqetta'}]" src="lib/dojo/dojo/dojo.js"></script>
```

You see, there are two definitions for 'maqetta', and the first one is incorrect.

**Comment by peller** [comment]
I only see one maqetta when I do it, and it's the latter one (with /maqetta) which I think is correct.

**Comment by JonFerraiolo** [comment]
Ah, duplicate definition only happens with Eclipse projects.

**Comment by peller** [comment]
@jhpedemonte 

When called for an Eclipse project, `cmd/getUserLibs` returns maqetta with root: WebContent/  Because lib.root is truthy, Context.getLoaderPackages appends an extra entry to `packages`

When run with a non-Eclipse project, lib.root is "" in that situation, so no extra package entry for 'maqetta' is added.

**Comment by jhpedemonte** [comment]
In `Context.getLoaderPackages()`, the call to `library.getUserLibs()` returns this (in the Eclipse project case):

``` javascript
[
  {
    "id": "html",
    "version": "0.8",
    "metaRoot": "app/metadata/html/0.8"
  },
  {
    "id": "clipart",
    "version": "1.0",
    "metaRoot": "app/metadata/clipart/1.0",
    "root": "WebContent/lib/clipart"
  },
  {
    "id": "yui",
    "version": "2.8.2r1",
    "metaRoot": "app/metadata/yui/2.8.2r1",
    "root": "WebContent/lib/yui"
  },
  {
    "id": "shapes",
    "version": "1.0",
    "metaRoot": "app/metadata/shapes/1.0",
    "root": "WebContent/lib/shapes"
  },
  {
    "id": "jquery-ui",
    "version": "1.8.11",
    "metaRoot": "app/metadata/jquery-ui/1.8.11",
    "root": "WebContent/lib/jquery-ui"
  },
  {
    "id": "maqetta",
    "version": "0.3",
    "metaRoot": "app/metadata/maqetta/core/0.3",
    "root": "WebContent/"
  },
  {
    "id": "gridx",
    "version": "1.0",
    "metaRoot": "app/metadata/gridx/1.0",
    "root": "WebContent/lib/dojo/gridx"
  },
  {
    "id": "dojo",
    "version": "1.7",
    "metaRoot": "app/metadata/dojo/1.7",
    "root": "WebContent/lib/dojo"
  },
  {
    "id": "DojoThemes",
    "version": "1.7",
    "metaRoot": "",
    "root": "WebContent/themes"
  },
  {
    "id": "dojo",
    "version": "1.7",
    "metaRoot": "app/metadata/dojo/1.7",
    "root": "eclipse_yo/WebContent/lib/dojo"
  }
]
```

(For the regular (non-Eclipse) project case, remove the "WebContent/" prefix from "root" properties.)

In the "maqetta" entry, the "root" value should actually be "WebContent/maqetta" (or "maqetta" in non-Eclipse projects).

Also, notice that there are two "dojo" entries -- the last one is wrong.

@childsb, you know this code better.  Please take a look.

**Comment by jhpedemonte** [comment]
I made the following change:

```
diff --git a/maqetta.core.server/plugin.xml b/maqetta.core.server/plugin.xml
index 6956b0a..4487d2c 100644
--- a/maqetta.core.server/plugin.xml
+++ b/maqetta.core.server/plugin.xml
@@ -40,7 +40,7 @@
         </extension>
         <extension point="maqetta.core.server.ajaxLibrary">
                 <ajaxLibrary name="maqetta" id="maqetta" version="0.3">
-                     <libraryPath location="WebContent/project/base" name="/"></libraryPa
+                     <libraryPath location="WebContent/project/base" name="/maqetta"></li
                      <metadata location="app/metadata/maqetta/core/0.3" />
                 </ajaxLibrary>
         </extension>
```

While that did fix the "root" value for the "maqetta" entry (it now lists as "maqetta" in a non-Eclipse project; now consistent with other entries), the Files view now shows this:

```
+ maqetta
    + maqetta
         AppStates.js
         space.js
```

Is there a special case for the "maqetta" 'lib' somewhere else?

**Comment by jhpedemonte** [comment]
Marking as a migration issue.  We'll need to update listing for "maqetta" in the file `<Project Name>/.settings/libs.settings`.

**Comment by peller** [comment]
@childsb @jhpedemonte why do we need libs.settings at all?

**Comment by jhpedemonte** [comment]
I assume it has to do with the **Modify Libraries** feature, where the user can rewrite the path for the libraries, primarily to allow easy exporting of files to an established server.

**Comment by childsb** [comment]
We need libs.settings to map AJAX library dependancies (JS, HTML, CSS0 into the users workspace.  The file has to exist within the projects file tree so that mappings are preserved if a project is shared.
