### ISSUE TITLE
Theme Editor: Cannot modify custom theme

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2144]
In both FF and Chrome on Mac...
1. Clone custom theme (and name something like "custom2")
2. Try to change global background color
3. Nothing happens

This doesn't appear to be isolated to background as I also tried to change font properties on both a global and a widget scope.

**Comment by aerwin** [comment]
And, one other thing, I was able to clone another mobile theme (e.g., ipad) and successfully changed background color there.

**Comment by billreed63** [comment]
fixed by #2207
