### ISSUE TITLE
DataGrid loses its data if parent TabContainer gets a new tab

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2149]
@aerwin, @doronrosenberg 
- New HTML File
- Add a TabContainer
- Switch to tab2 (note: because of #2148, you might have to click away first, and then click on tab2)
- Add a DataGrid, accept defaults
- Double-click at top of TabContainer to bring up TabContainer smartinput
- Add a 3rd tab name, and click OK

Result=> The datagrid within Tab 2 has lost its data

**Comment by jhpedemonte** [comment]
DataGrid is **deprecated**.  Please retest with **GridX**.

**Comment by aerwin** [comment]
I'm not able to reproduce this with GridX... Reassigning to @JonFerraiolo for verification.

**Comment by JonFerraiolo** [comment]
Closing. When I tested, the grid retained its content. However, there was an exception deep inside of the gridx widget. I sent email to the gridx development team about that.
