### ISSUE TITLE
AUDIO and BR - no size?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2150]
Sorry, my memory might have faded, but when I added an AUDIO widget, it had no size and the widget selection box shows the AUDIO widget as having now size and being located at top/left of page even if it is located elsewhere (e.g., dropped inside of a container). Is it correct that AUDIO has no size? It seems like it should have a minimum size (e.g., 1em x 1em).

Same thing with BR element

Note that we force a minimum size of 1em x 1em for various widgets (e.g., SPAN) via entries in ve/resources/content.css.

**Comment by jhpedemonte** [comment]
I think this happens if you haven't selected an audio file to attach to the widget.  Should we add sample audio and video files?

**Comment by aerwin** [comment]
I think Jon's issue is a dup of #2002. I'll close this one and raise priority of #2002.

Javier's suggestion for sample files is a dup of #1609.
