### ISSUE TITLE
Can't dnd jQuery/YUI (missing js file 404 error)

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2156]
Trying to dnd jQuery/YUI widgets I get a error (here is the jquery one):

Unable to load http://192.168.1.122:8081/maqetta/user/Doron/ws/workspace/project1/lib/jquery-ui/jquery-ui-1.8.11.custom.min.js status:404

**Comment by jhpedemonte** [comment]
Wasn't able to reproduce this locally or with nightly build on lab9:50010.  Did you copy in library files (see jQuery/YUI section in [Developer Guide](https://github.com/maqetta/maqetta/wiki/Developer-Setup))?
