### ISSUE TITLE
Viewing my own review throws JS errors

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2157]
Create a review and send it to someone.

Go and view the newly created review.  The page is broken and the following js errors:

```
"NetworkError: 404 Not Found - http://lab9.austin.ibm.com:50010/maqetta/user/Doron/ws/workspace/.review/snapshot/20120501171647/project1/lib/dojo/dojo/dojo.js"
dojo.js
"NetworkError: 404 Not Found - http://lab9.austin.ibm.com:50010/maqetta/user/Doron/ws/workspace/.review/snapshot/20120501171647/project1/themes/claro/claro.css"
claro.css
"NetworkError: 404 Not Found - http://lab9.austin.ibm.com:50010/maqetta/user/Doron/ws/workspace/.review/snapshot/20120501171647/project1/lib/dojo/dojo/resources/dojo.css"

require is not defined
http://lab9.austin.ibm.com:50010/maqetta/user/Doron/ws/workspace/.review/snapshot/20120501171647/project1/file1.html
Line 10
```

**Comment by doronrosenberg** [comment]
@jhpedemonte @JonFerraiolo not sure who owns review, giving it to javier for now.

**Comment by JonFerraiolo** [comment]
-> M6, Prio-High

I created a new review, and then double-clicked on the *.rev file in the Reviews palette, and saw the same problem @doronrosenberg reported above.

@aerwin, @childsb, @peller

**Comment by jhpedemonte** [comment]
@aerwin, I'm swamped with other things.  Can you please take a look at this bug?

**Comment by aerwin** [comment]
Taking ownership.

**Comment by aerwin** [comment]
@jhpedemonte @JonFerraiolo @doronrosenberg @childsb @peller 

I don't know why yet, but this might help folks who are blocked in testing.... it appears if you log out and log back in after creating a review you can open it. And, the exact same URL's that fail before suddenly start working after logging in and out.

**Comment by aerwin** [comment]
Fixed with above commit.
