### ISSUE TITLE
DataGrid does not render in preview with JSONP source

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2158]
Create a HTML
Drop a DataGrid
JSONP from the drop down in smart input
http://maqettaservice.appspot.com/sampleservice
click preview in browser
in the preview browser I see the following in the console

```
Uncaught TypeError: object is not a function dataGridUrlTestCase.html:19
(anonymous function) dataGridUrlTestCase.html:19
_c2 dojo.js:15
_36 dojo.js:15
_77 dojo.js:15
_ec dojo.js:15
req.injectUrl._107 dojo.js:15
```

Break on erroros stops on the single requires 

```
],function(xhrScriptPlugin){xhrScriptPlugin("http://maqettaservice.appspot.com/sampleservice","callback");});
```

**Comment by jhpedemonte** [comment]
This is the final issue on my plate as part of #1750.  See [this comment](https://github.com/maqetta/maqetta/issues/1750#issuecomment-5411241).
