### ISSUE TITLE
'Number' property value unexpected revert back to default

### ISSUE THREAD

**Issue by pchuong** [maqetta/maqetta#2159]
When you change a widget's property that has a 'number' datatype, it revert back to the default value if other property is change after reopen the same html file.

Test case:
- drag the NumberSpinner widget onto the VE
- in the 'widget-specific' properties, modify the 'Default Timeout' property value to 600
- save the file and open it again
- now change the 'Name' property to something else

Note that the 'Default Timeout' reverted back to 500.

It looks like the _Widget.js, line 390 - line 420 doesn't check for datatype 'number', or perhaps all widget properties with 'number' datatype in the oam files need to be either 'dijit' or 'object' type.

**Comment by JonFerraiolo** [comment]
Thanks for the report!

**Comment by JonFerraiolo** [comment]
@doronrosenberg fixed this with 575d3f8d3e Closing
