### ISSUE TITLE
Could not expand path at errrors when dnd into RoundrectList

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2162]
If I drag a radiobutton (either dijit or dojox.mobile) into a RoundrectList (so into a listitem) I get:

```
Could not expand path at RadioButton_0
http://192.168.1.122:8081/maqetta/app/dojo/_base/Deferred.js?@revision@
Line 216
```

Happens with many other widgets as well.  Since I added support for dnd into ListItems, assigned to me.

@peller @jhpedemonte 

Any hints where I should look to figure this out?

**Comment by JonFerraiolo** [comment]
I'm pretty sure the problem(s) are with the Outline palette logic that sets the "path". I see some code in ui/widgets/ToggleTree.js that looks like something to investigate:

```
ui/widgets/ToggleTree.js:59:                    this.set('paths', paths);
```

**Comment by peller** [comment]
As you'll see, paths is a list.  Each path itself is a list, or a path of nodes down the tree.  The code just prior to line 59 constructs that list by looking at the model and filtering out what it thinks are widgets (has a _dvWidget property)  There must be a mismatch between the widgets in that model and what's in the outline tree.

**Comment by doronrosenberg** [comment]
Not a toggletree issue but a issue with my fix for #1799.

**Comment by JonFerraiolo** [comment]
I thought we were having path problems with the Outline palette for other scenarios, too. For example: https://github.com/maqetta/maqetta/issues/2045

**Comment by doronrosenberg** [comment]
The issue here was that the widgets were not always being added in the DOM correctly for Listitem.  This should now be correctly handled

**Comment by peller** [comment]
@JonFerraiolo, #2045 is about the refresh mechanism for the Outline palette, not any data mismatch
