### ISSUE TITLE
resize for single state broken

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#2163]
((per the states test plan, holding down s while resizing or moving a widget should only resize the widget in a given state))

1) add a calendar widget to the page
2) add state aa and state bb
3) select state aa
4) hold down "s" and change the size of the calendar widget
5) switch back to normal state. notice that the calendar widget goes back to original size
6) select state aa, notice the calendar widget is resized
7) select state bb.  notice the calendar widget size is unchanged
8) go back to normal state, and notice the calendar widgets size doesn't change

it seems the "change only for this state" works once.  then after clicking around other states the size change trickles into each other state.

**Comment by JonFerraiolo** [comment]
When I follow steps above and go through step 4 and look at source view, I see that source view is messed up. The change that was supposed to be applied only to the 'aa' state is also stuffed into inline style.

**Comment by JonFerraiolo** [comment]
After a little poking around:
- I suspect that this bug is only for widgets which don't get an initial set of 'width' and 'height' properties
- I suspect that the cause of the bug is this logic in _Widget.js: getStyleValues(), which causes the 'model' to get updated using the current property values on the canvas:

```
            if(style.position == "absolute" || style.position == "relative") {
                var parent = this.getParent();
                removeProperty('position');
                removeProperty('left');
                removeProperty('top');
                //FIXME: This is Dojo-specific logic within a toolkit-independent file
                if(parent && parent.dijitWidget && parent.dijitWidget.addChild && !parent.acceptsHTMLChildren) {
                    // Do nothing - logic above removed position/left/top
                }else{
                    values.push({position:style.position});
                    values.push({left:style.left});
                    values.push({top:style.top});
                }
            }
            var resizable = metadata.queryDescriptor(this.type, "resizable");
            if(style.width) {
                if(resizable == "both" || resizable == "width") {
                    removeProperty('width');
                    values.push({width:style.width});
                }
            }
            if(style.height) {
                if(resizable == "both" || resizable == "height") {
                    removeProperty('height');
                    values.push({height:style.height});
                }
            }

```
