### ISSUE TITLE
Update Developer-Setup to pull down gridx submodule

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2164]
@childsb @jhpedemonte 

Don't we need to update the instructions at https://github.com/maqetta/maqetta/wiki/Developer-Setup to tell developers how to pull down gridx code?

As @aerwin says:

If you do a git pull, you'll notice a new davinci.gridx project in our repository. As of a merge into master a couple hours ago, a submodule has been created for one its directories. ...

Basically, the intent is that the davinci.gridx/WebContent/gridx directory will hold the contents of the GridX repository. If you care about the gory details, if you look at the contents of the new .gitmodules file, you'd see the definition:

Anthonys-MacBook-Pro:maqetta aerwin$ cat .gitmodules 
[submodule "davinci.gridx/WebContent/gridx"]
    path = davinci.gridx/WebContent/gridx
    url = git://github.com/evanhw/gridx.git

But, here's the rub... when you do a git pull, it does not automatically pull down code for submodules. So, you'll see the davinci.gridx/WebContent/gridx directory is empty.

To fix that, you can run the following git commands from the top-level of the repository:

git submodule init
git submodule update

Alternatively, if you don't use the git command line much, you can update the submodules using eGit in Eclipse. More details can be found in the link below (thanks Javier for the link):

http://wiki.eclipse.org/EGit/User_Guide#Working_with_Submodules 

... If you want more details on submodules in general, check out: http://progit.org/book/ch6-6.html

**Comment by aerwin** [comment]
@JonFerraiolo 

Thanks for opening this issue. My intent had been to do this once the following issues are addressed:
- Update of build scripts for GridX submodules (#2034)
- Need mechanism for libs to use code from "ancestor" libs (#2067)
- Promote GridX from Untested widgets to Dojo Controls (#2161)

**Comment by aerwin** [comment]
The wiki page (https://github.com/maqetta/maqetta/wiki/Developer-Setup) has just been updated, so marking as closed.
