### ISSUE TITLE
gridx problems

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2165]
@billreed63 - it would be good for you to give a testing pass on current implementation of gridx.

Here are some problems I noticed trying out the new gridx support (which incidentally is very cool). It might be better to have separate bugs for each of these, but for the time being I'm making a list within this bug:
- Missing a space after "2." and before "Select columns"?
- In the wizard, clicking on "2. Select columns" doesn't switch to that pane. Can only switch panes with Next/Prev buttons.
- Finish doesn't work correctly unless you go through the whole wizard all the way to pane 3. If I type in this data in pane 1:

```
ID,Label,aaa,bbb,ccc
1,Label 1,a1,b1,c1
2,Label 2,a2,b2,c2
```

then go to pane 2 to move bbb to the left column and immediately click Finish, I see all 5 columns on the canvas, whereas if I navigated to pane 3 before clicking Finish, then I won't see the bbb column on the canvas.
- I see a phantom scrollbar (without an elevator) in the gridx widget on the page editor even if the grid is smaller than the widget's bounds. The phantom scrollbar appears in both page editor and in preview.
- Is the only mechanism for column resize the ability to drag column separators? No ability to type in a column width? What if someone wants to put percentage values for column widths?
- Wizard doesn't have a resize control at lower-right. I would think that we need one for cases where users have lots of columns.

**Comment by aerwin** [comment]
@JonFerraiolo 

Thanks for the thorough review. I had already logged many of these issues last night under #2152. So, I'm inclined to close this one as a dup and move your unique findings over to that other issue.

The ones I see as unique are:
- Missing a space after "2." and before "Select columns"?
- I see a phantom scrollbar (without an elevator) in the gridx widget on the page editor even if the grid is smaller than the widget's bounds. The phantom scrollbar appears in both page editor and in preview.
- Wizard doesn't have a resize control at lower-right. I would think that we need one for cases where users have lots of columns.

You also mention entering numeric values for widths which I had already logged last night under #2155.
