### ISSUE TITLE
app.css gets mangled when using proposed new rule

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2166]
@childsb 

Sending to @billreed63 in hopes he has cycles.
- Run local version so you can look in your workspace with 3rd party text editor, and have Chrome debugger running
- New HTML File
- Add a Button
- Add a class to button (eg 'aa')
- Bring up cascade for 'width'
- Select first radio button (proposed new rule)
- Enter "20em" into text field and hit return

Result=> Look at Network panel and you'll see that app.css.workingcopy was sent to server. If you look at content of app.css, you'll see that the style rule (HTML/BODY width:100%; height:100%) and the comments at the top of the file have been mangled together.

I suspect there is a bug with the model code.

**Comment by billreed63** [comment]
The way the CSSParser deals with comments is not very robust, the parser pushes all whitespace and comments in to a pushToken variable while looking for the next  non comment or whitespace token.

```
function nextToken() {
        var start,
            stop,
            s;

        token = parser.next();
        while (token.style == "css-comment" || token.style == "whitespace" ||
                (token.content == '/' && stream.peek() == '/')) {
            if (token.style == "css-comment") {
                if (! pushComment) {
                    pushComment = new Comment();
                }
                var commentStart = false;
                s = token.content;
                if (token.content.indexOf("/*") === 0) {
                    s = s.substring(2);
                    commentStart = true;
                }
                if (s.lastIndexOf("*/") == s.length - 2) {
                    s = s.substring(0, s.length - 2);
                }
                if (commentStart) {
                    pushComment.addComment('block', start, stop, s);
                } else {
                    pushComment.appendComment(s);
                }
            } else if (token.content == '/') {
                start = token.offset;
                parser.next();// second slash
                if (! pushComment) {
                    pushComment = new Comment();
                }
                while (!stream.endOfLine()) {
                    stream.next();
                }
                s = stream.get();
                pushComment.addComment('line', start, start + s.length, s);
            } else {
                if (pushComment) {
                    pushComment.appendComment(token.value);
                }
            }
            token = parser.next();
        }
        return token;
    }

```

When it finds the next non comment/whitespace token it returns that token

The code the deals with that token has code that hangs the pushComment on the model  object for example CSSProperty

```
if (pushComment) { 
    property.comment = pushComment;
    pushComment = null;
}`
```

When the CSSFile is written out all the modeled objects are visited and the output is generated added the comments if any for example CSSProperty

```
getText: function(context) {
        var s = "";
        if (this.comment && !context.noComments) {
            s += "\n  " + this.comment.getText(context);
        }
        s += this.name + " : " + this.value;
        if (this.isNotImportant) {
            s += ' !important';
        }
        s += ";";
        if (this.postComment && !context.noComments) {
            s += this.postComment.getText(context);
        }
        return s;
    },
```

The CSSParser nextToken has several problems with the way it deals with comments. By dealing with whitespace in the same loop that adds comments block comments `/* xxx */` get all following whitespace added to the last block comment processed so

```
/*
xxxxx
*/

```

Will be written out as

```
/*
xxxxx

*/
```

Also selctors with comments

```
.claro /*xxx*/ .hideme {
```

will be written out as

```
/*xxx
*/
.claro  .hideme {
```

With this approach of adding comments to the model object as `model.comment  model.postComment` care must be taken to not loss the comment when replacing the model object for example when we modify a CSSProperty we delete and add a new property, we need to ensure that we copy the comments from the old property to to the new property.

**Comment by billreed63** [comment]
I have addressed most of the issues with e4718e6441f82b2a6cf7a61e1b5dfad73bf92790  We still have a couple of outstanding issues 
1) If a CSSProperty is deleted the comments before and/or after after are deleted as well. This is due to the way the CSSParser handles comments an attaches them to the closes CSSProperty.
2) Block comments get newlines added to the end of the comment, again this is due to way the CSSParser parses whitespace and appends the whitespace to the last processed block comment.

I think item one can only be addressed by replacing the CSSParser with a parser that handles comments as separate model items instead of attaching to CSSPoperties or CSSRules 

item 2 may also need a new parser.

**Comment by billreed63** [comment]
I have changed the CSSParser to preserve the comment syntax.  I still have one question @JonFerraiolo  the CSSParser has code to deal with `// comment to EOF`  According to http://www.w3schools.com/css/css_syntax.asp the only valid comments for CSS are `/* comment */` Do we want to leave that code?

**Comment by JonFerraiolo** [comment]
I saw no evidence via web searches of upcoming support for `//` comments, so I think it's OK to remove that code, but clearly not a top priority for M6.

**Comment by billreed63** [comment]
Fixed by above commits
