### ISSUE TITLE
/dojox/mobile/themes//.css 404 (Not Found)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2168]
When I add a first Dojo Mobile widget to a page (in my case, a ScrollableView), the console shows this:

dojo.js:15GET http://localhost:8081/maqetta/user/maqettaUser/ws/workspace/project1/lib/dojo/dojox/mobile/themes//.css 404 (Not Found)
placedojo.js:15
createdojo.js:15
dm.loadCssFiledojox/mobile/deviceTheme:5
dm.loadDeviceThemedojox/mobile/deviceTheme:32
(anonymous function)Context.js:3019
(anonymous function)dojox/mobile/deviceTheme:44
_c2dojo.js:15
_36dojo.js:15
_36dojo.js:15
_16dojo.js:15
reqdojo.js:15
declare.addJavaScriptModuleContext.js:2670
declare.loadRequiresContext.js:431
declare.loadRequiresContext.js:407
declare._create.loadTypeCreateTool.js:586
declare._createCreateTool.js:599
declare.createCreateTool.js:576
notifyDeferred.js:175
dojo.Deferred.promise.then.thenDeferred.js:283
declare.createCreateTool.js:575
declare.onMouseUpCreateTool.js:366
declare.onMouseUpContext.js:2147
hitch

@jhpedemonte says:

Seems to only occur when the first mobile widget is added to the page.

If I recall correctly, Bill said this has to do with the dojox.mobile.themeFiles property -- to get around this issue, we have to set it to an empty array.  But I thought I was already doing that.  Given that it only appears for the first mobile widget on the page, it must be some timing issue...

**Comment by jhpedemonte** [comment]
-> Prio Med.  Yes, it's an error in the console, but does not impact functionality.
