### ISSUE TITLE
'class' and 'id' input fields should grow/shrink as Properties palette grows/shrinks

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2170]
Go to Properties palette and open up any of the CSS sections (e.g., Layout) or the Events section. Pull on the divider between the Properties palette and the canvas to make the Properties palette wider. Notice that the input fields grow as the properties palette grows.

We need to accomplish the same magic for 'class' and 'id' at the top of the Properties palette.

Warning: there be tables.

**Comment by JonFerraiolo** [comment]
Issue #231 is the same sort of request except for the widget-specific section of Properties palette

**Comment by doronrosenberg** [comment]
fixed in rev 7a763f1
