### ISSUE TITLE
Cosmetic fixes for Properties palette toolbar

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2171]
We are using particular CSS styling on the detailed sections of the Properties palette and need to apply the same rules (or at least achieve the same visual result) for font sizes on the form input fields and vertical spacing between the fields. (Right now there are 2 or 3 pixels of white space between vertically stacked fields in various other sections such as Events or the CSS sections. We want the same tightness for 'class' and 'id')

You can see the styling rules if you open up "Common" (or "Events" or whatever), and then in debugger look at the various CSS rules that are being applied to the various DIVs and SPANs that are used by the 'title' property.

There is a related, lower-priority issue: #2170

**Comment by doronrosenberg** [comment]
Do we want to hide the rest of the properties palette when no widget is selected (common, widget specific, etc)?

**Comment by JonFerraiolo** [comment]
> Do we want to hide the rest of the properties palette when no widget is selected (common, widget specific, etc)?

I don't think so. The UI folks want to go in the other direction. Right now we don't show the Widgets palette when no editors are open, and they would prefer we should the Widgets palette always, but with disabled styling (instead of hidden).
