### ISSUE TITLE
Need ability to control ordering of widgets within category in palette

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2175]
Most of the time widgets within a category are controlled by a single package.json file and the ordering on the display is just determined by the order in the file. However, this starts to break down when widgets from multiple plug-ins are put into the same category.

For example, the screen shot below is from in my local environment where I've "promoted" GridX from the Untested section to the Dojo Controls section. You can see GridX is now the first control in the list which is probably not ideal:

![widget palette](http://i.imgur.com/bizIX.png)

I'd propose one of two things (with #2 being better):
1. Widgets within a category are always displayed alphabetically whether metadata comes from 1 or many widget plugins. (I'd say this is less than ideal since alphabetized isn't always optimal.)
2. Add an additional attribute to widget metadata (perhaps called "controls-ordinal" ) which is honored by the widget palette when determining order of display (so then the dojo 1.7 plugin probably would use ordinals like 10, 20, 30, 40, etc. and then the gridx plugin could use an ordinal of ~25 for its widget to ensure it's placed in the middle of the list)

**Comment by jhpedemonte** [comment]
@JonFerraiolo 

I think this is over-engineering.  Using the order based on array is simple.

We've talked about redoing the Widget palette, mostly by creating finer grained categories.  If/when we do that (and there are less than 10 widgets per category), then yes, we can probably just get by using alphabetic sorting.

---

As for this particular case, we can probably improve things slightly:
- Do we want GridX to be part of the overall _Dojo Controls_?  Or should it have it's own category?
- Since the GridX lib depends on the Dojo lib, make sure its widgets are added to the list after those from the library it depends on.

**Comment by JonFerraiolo** [comment]
I am hoping we will do a major makeover for the Widget palette in time for 1.0. Let's see what the UI proposals are there. Those proposals should (I would hope!) make it so that each group of widgets has few members inside, in which case alphabetic might work just fine.

**Comment by aerwin** [comment]
Not sure if it's over engineering or not... I've seen ordinal-based plug-ins in other IBM console frameworks.

At any rate, perhaps a good discussion for the UX call... my thinking was a category for a single widget was overkill, but if that's the future design direction, we can certainly do that. I guess eventually TreeGrid might go in there as well, so that would be 2 widgets.

**Comment by peller** [comment]
I don't think simple category sections on a palette will do.  I've suggested that we need to have multiple "tags" on each widget which can be searched/sorted, and that the palette might be better off giving priority to "frequently used" widgets or otherwise making it configurable to have favorites

**Comment by jhpedemonte** [comment]
Actually, that's a good idea (using tags).  And I think it would be good to have a section for "recently used" at the top, and then a grid based on tags under that.

**Comment by JonFerraiolo** [comment]
@jmockler @doronrosenberg 

I expect everyone will agree with the motherhood and apple pie statement: let's keep it simple and intuitive, particularly for first time users, and then offer tools for advanced users (that don't complicate first-time users!) so they can optimize their productivity. 

I think most everyone likes "Recently used". We have also talked about a Favorites section, but right now I'm thinking we shouldn't do that, and instead, for advanced users, my instincts are that the way to go is to allow them to fully customize their widget palette (i.e., create/delete categories, move widgets into catogories, reorder categories and widgets within categories). Tags might also be a good feature for advanced users.

**Comment by peller** [comment]
I'm suggesting that tags wouldn't be an advanced feature, but rather how we would ship widgets.  Instead of fixed categories, there would be tags and multiple ways of looking at things.  As an advanced features, tags could be added/edited.

**Comment by JonFerraiolo** [comment]
-> M7 Prio High

**Comment by JonFerraiolo** [comment]
Downgrading to M7/Prio-Med. This is dependent on rewriting the widgets palette, which is currently unlikely for M7.

**Comment by JonFerraiolo** [comment]
Pushing to M8, when we hope to do a major UI makeover on the Widgets palette.

**Comment by JonFerraiolo** [comment]
Closing this. We did the UI makeover for the widgets palette in M8.
