### ISSUE TITLE
FF: Can't select widgets using Outline view

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2176]
```
e.srcElement is undefined
http://192.168.1.122:8081/maqetta/app/davinci/ui/widgets/ToggleTree.js?@revision@
Line 76
```

**Comment by doronrosenberg** [comment]
This also happens after a reload of the page

**Comment by jhpedemonte** [comment]
-> @peller 

cc @JonFerraiolo

**Comment by peller** [comment]
FF only, apparently

**Comment by peller** [comment]
see #1018

**Comment by peller** [comment]
so now when I click on an element in the outline view in FF, I get an error if I have a CSS editor up but out of view, as it tries to handle the selection event
