### ISSUE TITLE
ComboBox gets messed up if container has line-height

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2184]
@peller - maybe file a ticket in Dojo/Dijit?
- New HTML File
- Add a DIV, set DIV's height to 36px in the Properties palette
- Add a LABEL, then a ComboBox

Result-> everything OK
- Select the DIV and in Properties palette set its line-height to 36px

Result-> ComboBox gets messed up. Grows to fit available area.
- Select the ComboBox and in Properties palette set it's line-height to Normal using drop-down menu

Result-> ComboBox OK again

My guess is that ComboBox's CSS need some sort of explicit line-height value so it doesn't inherit line-height from parent

**Comment by peller** [comment]
-> M7

**Comment by jhpedemonte** [comment]
-> M8, raising to Prio High so we can investigate early and determine if we need to open bug with Dojo.

**Comment by JonFerraiolo** [comment]
@peller - how best to report this to Bill Keese? I would think it's reasonably common that uses would surround Dijit UI controls with a DIV, and then use line-height on the DIV to achieve vertical alignment of the controls within the DIV. On the Dijit side, just need to explicitly set line-height within the CSS style declarations for the given widget. (I suspect this situation would apply to more widgets than just ComboBox)

**Comment by peller** [comment]
@JonFerraiolo by messed up, you mean the drop down arrow doesn't expand vertically?  The fact that the control expands to allow its embedded text to conform to the inherited line-height seems to be in keeping with the spec.

**Comment by JonFerraiolo** [comment]
> you mean the drop down arrow doesn't expand vertically

No, I mean that the whole control should not grow vertically if line-height is defined. Take a look at the following image which shows the following controls inside of a DIV with height:36px and line-height:36px:
- Dojo ComboBox
- Dojo TextBox
- Dojo Button
- HTML `<select>`
- HTML `<input>`
- HTML `<button>`

![Dojo ComboBox vs HTML select](http://i.imgur.com/TxaMX.png)

> The fact that the control expands to allow its embedded text to conform to the inherited line-height seems to be in keeping with the spec.

Which spec? The Dojo spec? If so, why wouldn't Dojo button grow to fit the space, if that's the Dojo spec? Note that the HTML controls don't grow vertically to fit the space. With the HTML elements, if you want those elements to have a larger height, then you assign a different height to the control.

As I mentioned above, because CSS has some poor vertical alignment options, it's really common for users to achieve "middle" alignment of side-by-side form controls by putting line-height on the container element (in this case the DIV). The browsers will position child elements with "middle" vertical alignment within the container.

I think the fix will take a lot less time than the argument. Just put line-height:normal within .dijitTextBox (or something like that).

**Comment by peller** [comment]
Filed a [Dojo ticket](http://bugs.dojotoolkit.org/ticket/16086)

**Comment by JonFerraiolo** [comment]
-> M8 Prio-Med

**Comment by ghost** [comment]
This only fails for me on Chrome and seems to be a Chrome bug.  dijitComboBox explicitly sets line-height:normal (via dijitReset in dijit.css) and this is being ignored because font:inherit is specified later and is somehow masking the line-height.  Setting font:inherit before line-height:normal in the dijitReset selector rule in dijit.css seems to prevent Chrome from misrendering.

**Comment by JonFerraiolo** [comment]
@doughays-dojo Maybe not a Chrome bug. The 'font' shortcut includes specification of line-height - see http://www.w3.org/TR/CSS21/fonts.html#font-shorthand:

```
The 'font' property is, except as described below, a shorthand property for setting 'font-style', 'font-variant', 'font-weight', 'font-size', 'line-height' and 'font-family' at the same place in the style sheet. 
```

In fact, it looks to me like the 'font' shortcut should indeed override any previous values for 'line-height', or at least the WebKit implementers have a good argument if they interpret the spec that way.

**Comment by peller** [comment]
still happens with Dojo 1.8.3
