### ISSUE TITLE
Subwidget connections not always cleared in Focus.js?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2185]
I was researching another bug and looked at the subwidget logic in Focus.js. It seems to me that the event listeners for /davinci/states/state/changed (attached as this._connections) are not cleared in all cases. It seems like the connections only get cleared when a new widget is selected and the new widget also has subwidgets.

Could you please review the code and perhaps call clearList() in other cases?

Also, could you look at routine _updateSubwidgetListForState() and see if we need to add a check to make sure the current editor is a theme editor?

**Comment by jhpedemonte** [comment]
-> M8.  Prio High to investigate early.

**Comment by billreed63** [comment]
I reviewed the code, the connections are cleared when a new widget is selected regardless if it has subwidgets
Foucus.resize

```
if(this._contexDiv){    // Theme editor only
            var x = box.w + 10;
            this._contexDiv.style.left = x + 'px';
            this._updateSubwidgetList();
        }
```

updateSubwidgetList

```
 _updateSubwidgetList: function() {
        if (this._displayedWidget === this._context._selectedWidget) { return; } // we are already displaying the subwidgets
        this._clearList();
        this._createSubwidgetList();
    },

    _clearList: function() {
        debugger;
        if (this._cm){
            this._cm.destroyRecursive(false);
            delete this._cm;
            while (connection = this._connections.pop()){
                dojo.unsubscribe(connection);
            }
        }
        this._currentItem = null;
    },
```

 currently `_updateSubwidgetListForState()` is only triggered from the theme editor states palette which id different than the page designer states palette. But the code for subwidgets was written with the idea that one day we may want to add subwidget support to the page designer.  So to play it safe I added a check for `_cm` the context menu to ensure it is present.
