### ISSUE TITLE
Sometimes context menu doesn't work in Outline palette

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2186]
@peller 

Intermittently, the context menu doesn't work in Outline palette. Console will show this message:

```
Uncaught Error: Tried to register widget with id==davinci.ve.cut but that id is already registered
```

What I'll guess is happening is that the menu that appears over the canvas is creating a menu widget with id==davinci.ve.cut, and it still exists when the outline palette tries to do the same thing. I haven't looked at the code so I don't know if the problem is that sometimes the context menu on the canvas doesn't get fully destroyed upon closing. Also, maybe we should use a different ID for the menu on the outline palette?

**Comment by JonFerraiolo** [comment]
Actually, I'm pretty sure that if you use the context menu on canvas, you can't use it on Outline palette, and vice versa

**Comment by doronrosenberg** [comment]
@JonFerraiolo The issue here is that the menuitems have ids, and we generate 2 context menus - one for design view and one for outline.

We could remove the ids or reuse the same menu object between the 2

**Comment by doronrosenberg** [comment]
@jhpedemonte 

hmm,since we support multiple parts per context menu, removing hte ids from the actions might be the only answer.  Or we could remove ids during menu creation.

**Comment by JonFerraiolo** [comment]
if things work by removing the ids, that seems the best. However, I'm not sure whether we have some dependencies on menu IDs somehow, particularly in Workbench.js. (I remember the menu code, but I don't remember details about how it works)

**Comment by doronrosenberg** [comment]
We use ids from the main menu dropdowns
