### ISSUE TITLE
CSV in grids - sample file? release notes? allow source editing of *.csv files?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2187]
@aerwin @billreed63 

I see that #119 was closed about a month ago, but I don't see a note in #199 about what commit fixed the issue. Assuming CSV data now works with DataGrid, some follow-on questions:
- Can we include a sample *.csv file within the sample_data folder? (maqetta.core.server/WebContent/samples/sample_data)
- Can we add a mention of CSV support in our Preview 6 release notes (maqetta.core.client/WebContent/docs/releasenotes/preview6.html)
- Our source editor provides limited support for *.json files. Does it make sense to add similar support for *.csv files?

gridx has inherited/shared the data source code from DataGrid, correct? If so, then the release notes should talk about both DataGrid and GridX. (Also note that @aerwin has an issue about how best to deprecate our support for DataGrid)

**Comment by doronrosenberg** [comment]
CSV is currently broken (#2160)

**Comment by doronrosenberg** [comment]
I opened #2242 for csv editing.  I also see no preview6.html file

**Comment by JonFerraiolo** [comment]
preview6.html: https://github.com/maqetta/maqetta/blob/master/maqetta.core.client/WebContent/docs/releasenotes/preview6.html

**Comment by doronrosenberg** [comment]
Release notes checked in, do we need to keep this open?

**Comment by JonFerraiolo** [comment]
Closing
