### ISSUE TITLE
Can't rearrange widgets within outline palette

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2193]
Basically, drag and drop within outline palette seems to be turned off. I thought I heard on scrum this was a known issue, but I don't see any open item for that. Feel free to dup if one exists.

**Comment by peller** [comment]
I think @JonFerraiolo mentioned it.  Works fine for me on master.  There were issues fixed a few days ago.

**Comment by aerwin** [comment]
This was using the orion build we were to use for testing. Perhaps that build doesn't have your fix, or it's orion specific.

**Comment by JonFerraiolo** [comment]
Doesn't work for me on master with latest code. I created a virgin workspace and restarted server, and then opened Sample1.html and tried to rearrange the DIVs within the first pane of TabContainer. Dragging on the DIV caused no visible signs of anything happening.

In fact, I don't see how it is possible to rearrange widgets in outline palette when click-select isn't working in outline palette.

**Comment by JonFerraiolo** [comment]
Working for me now with latest code. Tested on both Chrome and FF. (When I made comment an hour ago, I was a few commits behind because a server commit was preventing app from running, and had to wait for a server fix before I could get latest code)

**Comment by aerwin** [comment]
Verified on orion build that @childsb just posted.

**Comment by peller** [comment]
works for me.  Though the outline view does collapse when you make the change (known issue)
