### ISSUE TITLE
[TweetView] iphone.css and claro.css don't work well together

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2194]
The issue in TweetView with the tabbar cutting of label text is due to claro.css setting a line-height on all li nodes.

@jhpedemonte @JonFerraiolo @peller 

Can we disable claro.css from loading when we are in mobile mode? This probably affects other mobile widgets as well and not just tabbar.

**Comment by JonFerraiolo** [comment]
-> @billreed63 who is the theme set meister

**Comment by jhpedemonte** [comment]
Are we still adding **claro.css** all the time now?  That should come from metadata, shouldn't it?  The mobile widgets don't depend on claro.css.

**Comment by billreed63** [comment]
We are still adding claro by default, we still need to address how to get default desktop theme's from toolkits

**Comment by JonFerraiolo** [comment]
@peller 
The problem in this case is that we are merging dojo.css into claro.css. It's dojo.css that provides generic styling for HTML elements.

**Comment by peller** [comment]
@JonFerraiolo where do we merge dojo.css and claro.css?  I see two distinct @import statements in the user files.

**Comment by JonFerraiolo** [comment]
@billreed63 do you know? (my best two guesses: (1) we create a built version of claro.css manually, (2) our build process creates a built version of claro.css)

**Comment by JonFerraiolo** [comment]
I think I found the culprit. Look at maqetta.core.client/WebContent/dijit/themes/claro/document.css. It imports dojo.css.

_update_ Wait, I don't see who imports document.css, so maybe that's not the culprit afterall.

_update_ The Dijit oam files all include dojo.css. I don't think that's right. Maybe we did that as a temporary hack once upon a time and now it has come back to bite us? @jhpedemonte

_update_
I haven't figured out yet how dojo.css gets built into claro.css, but I'm certain that's what is happening. If you look at the user document, there is no LINK element for dojo.css, and if you look at the Style panel for IconContainer's LI elements, you'll see a rule in claro.css that matches exactly the rule in dojo.css.

**Comment by peller** [comment]
When I look at user source, I _do_ see an @import for dojo.css, also for claro.css.  When I look at the claro.css content, I do not see anything that resembles dojo.css.

**Comment by peller** [comment]
@JonFerraiolo which rule do you see in claro.css that's suspect?

**Comment by JonFerraiolo** [comment]
> which rule do you see in claro.css that's suspect?

Look at davinci.dojo_1_7/WebContent/maqetta/themes/claro/claro.css:1715. Those CSS rules are part of dojo.css. When I add an IconContainer and look at the LI nodes for IconContainer in the debugger, I see these rules (from dojo.css) applied to LI, and browser says the rules are coming from claro.css:1715.

**Comment by peller** [comment]
Wow.

Ok, well looking at the Dojo releases, dojo.css hasn't been directly @imported into the theme files since Dojo 1.5.  @billreed63 do we just need to update this file?   I seem to remember us updating these copies of the theme files on multiple occasions, but maybe it got lost in one of the moves?

**Comment by billreed63** [comment]
If I remember correctly claro was updated when we updated the toolkit to 1.7.  The version that was added to the maqetta themes was a built version to improve network performance, maybe the build process imports dojo.css

So say we remove dojo.css from claro don't we still have an issue if we mix desktop widget and mobile on a page. 

If the page is mobile do we add claro but not dojo.css, and for desktop we add claro and dojo.css. We do not have this capability at present

**Comment by peller** [comment]
I remember updating too, but you may want to try again.  claro.css hasn't referenced dojo.css since Dojo 1.5. Even after a build process, claro.css should not have dojo.css content, so I'm wondering if we have the 1.5 version checked in.

**Comment by JonFerraiolo** [comment]
Maybe all we need to do is overwrite the version at davinci.dojo_1_7/WebContent/maqetta/themes/claro/claro.css with the version found at davinci.dojo_1_7/WebContent/dojo/dijit/themes/claro/claro.css. (Also check mobile themes)

**Comment by peller** [comment]
yes, that's what I suggest.  We should probably do a more careful cleanup of the entire dir.
