### ISSUE TITLE
Can not make style changes for state

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2197]
Drag drop label
add a couple states, select one of the states and try to change the font color of the label for that state for that state

The apply to state chack box is missing from the cascade

**Comment by JonFerraiolo** [comment]
I tried the same steps above with today's build and I see the checkbox. Here is what I did:
- Launch Maqetta in browser (I was using today's Orion build)
- Add a label
- Add two new states aaa and bbb
- Go to aaa state
- In Properties palette, go to Fonts and Text, then go to cascade for 'color'

Result=> Checkbox appears

Now I don't doubt there are bugs in this area, but I suspect the bugs manifest themselves only after a series of steps

**Comment by JonFerraiolo** [comment]
-> @billreed63 Could you please try this again? I tried on a couple of different occasions and had no problems.

**Comment by billreed63** [comment]
seems to work today
