### ISSUE TITLE
Can't select Line/Arrow/PolyLine/etc from Outline

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2199]
Orion build/Firefox.  I dragged one of each drawing tool item to sketch mode.

Selection of any of those items using the outline view doesn't work.  It seems to usually not select anything or sometimes select the last one I selected using the mouse to click on it.

**Comment by JonFerraiolo** [comment]
-> @peller  (almost certainly a dupe - probably not drawing tool specific)

**Comment by JonFerraiolo** [comment]
Works for me using latest code on master.

**Comment by doronrosenberg** [comment]
Indeed, only happens on the orion build, master works fine.

**Comment by doronrosenberg** [comment]
No longer happening on the newest orion build
