### ISSUE TITLE
Cut and paste doesn't work under Firefox

### ISSUE THREAD

**Issue by alphaville76** [maqetta/maqetta#220]
Cut and paste for the source code view doesn't work under Firefox.

Maybe is an issue of Firefox, see this link:
http://kb.mozillazine.org/Rich_text_editing#Can.27t_use_Copy_or_Paste_buttons.3F

Anyway some richt text editors, like that one of Gmail, solved this annoyance.

**Comment by JonFerraiolo** [comment]
Closing. Orion folks solved this issue.
