### ISSUE TITLE
DataGrid csv support is broken

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2200]
@billreed63 @peller 

Looks like something changed and changing stores is throwing an exception.  Looks like DataGrid::reparentTheStore is the issue - when we switch from ItemStore to CSVStore, it is trying to reparent the old ItemStore that has been removed.

**Comment by aerwin** [comment]
Is this a dup of #2160?

**Comment by doronrosenberg** [comment]
indeed it is
