### ISSUE TITLE
Upload of files seems to work, but file doesn't exist

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2201]
1. Upload a file -- I've tried with HTML, JS, CSS and image.  Notice that file is listed in **Files** view.
2. Double click file to open it.  Maqetta will show an editor with the **dirty bit set** and default content, as if you had **created a new file**.
3. Close file and click OK on warning dialog.  File is still listed in Files view.
4. Double click on file to re-open.  -> Maqetta errors out.

It seems that the file does not actually get uploaded.

**Comment by childsb** [comment]
File was getting saved as .workingCopy.  Fixed here: cb741855f246255df96190318845ddb8f3c61125
