### ISSUE TITLE
ThemeSets dialog major performance problems

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2206]
On a slow server with a slow connection, there are a few performance issues with the ThemeSets dialog.
- The ThemeSets... dialog is very slow coming up. Looking at Network panel, we are doing a findResource for *.theme files, and then pulling down the *.theme files. Anyway this info can be cached on the client? Since this is a potentially slow operation, we should at least put up a wait cursor or something
- The plus and minus icons can take several seconds (or more) to complete, and we provide no UI feedback that an operation is underway. Again, looking at the Network panel, we are doing a findResource for *.theme files, and then pulling down the *.theme files.
- Even just selecting a new theme set (so that it can be renamed and modified) takes several seconds. Once again, simply clicking on a theme set in the left-side list causes the same findResource++ actions.
- Same slowness bringing up the Switch themes dialog

**Comment by JonFerraiolo** [comment]
After playing with theme editor for a couple of hours, I think we need to fix these performance problems. Things are slow even when running locally. -> M6 Priority High

**Comment by peller** [comment]
I noticed today that we're pulling down all *.theme files on Workbench startup.  Is that new?

**Comment by jhpedemonte** [comment]
(Copied from duplicate #2235):

> Switching between different **theme sets** is very slow, and the UI becomes unresponsive until the switch has completed.
> 1. Found while running **Tests > Theme sets > Remove theme sets**.  In the **Manage Theme Sets** dialog, switching between entries in the _Theme sets_ list is very slow.  Sometimes the highlight in the list takes a long time to switch.  The **Name** field, though, always takes long to reflect newly selected theme set.  While waiting for switch to complete, all dialog controls are unresponsive.
> 2. Switching theme sets is also slow in the **Select a Theme** dialog (in VE).
> 
> [Tested on Firefox 11/Mac]

**Comment by doronrosenberg** [comment]
Just ran into this myself while testing - we are downloading all .theme files fore each theme you click on
