### ISSUE TITLE
Background properties doesn't show in mobile theme editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2207]
With today's build, you can't see global page background color changes. The themes are changed, but the global page background color changes aren't visible in mobile theme editor.
- Pull down a build (eg http://maqetta.org/nightly/maqetta-20120508-0102.zip)
- New theme custom->custom2
- In mobile theme editor, select Page background and fonts
- Change background-color

Result=> Nothing shows on screen. However, if you create  mobile page and use the new theme, the background color is there.

With latest code (running from Eclipse), I saw the same sort of thing when putting a custom gradient on the global Heading widget: the gradient is visible in HTML files that use the theme, but the gradient doesn't show in the mobile theme editor.

**Comment by billreed63** [comment]
I changed alot of this processing in the themeEditorDeltas branch, I don't see this issue on that branch. So I think we should wait until we merge with master to see if this problem is resolved

**Comment by billreed63** [comment]
Fixed by 05a98364af16b107c1c29b90ef5cf4867afba344
