### ISSUE TITLE
Get selection rectangle when finished dragging scrollbar

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2211]
1. Add **AccordionContainer**.
2. Add enough widgets into Pane 1 such that there are scrollbars.
3. Drag scrollbar to move content.

Notice that after letting up on the mouse (to finish scrolling operation using scrollbar) that a selection rectangle appears.

@peller, is this related to what you did with the Outline view?

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
-> me, changing to Prio High

**Comment by peller** [comment]
@jhpedemonte the fix to #1018 was specifically for the outline tree widget (ToggleTree), but perhaps a similar workaround is needed.  It is a general bug with Dojo DnD.  Are you saying this was a regression?
