### ISSUE TITLE
Blue bar across top of app, when adding SpinWheel* widgets

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2213]
![blue bar](http://i.imgur.com/aLm73.png)

To (attempt to) reproduce:
1. New file.
2. Start dropping any combination of SpinWheel\* widgets.

Assigning to @doronrosenberg for now, but I wonder if it has anything to do with @JonFerraiolo's widget selection code, which employs a similar hue of blue.

**Comment by JonFerraiolo** [comment]
I got into Photoshop to check the color values of the blue rectangle to see how it compares with the Focus.js selection chrome, and the color values are quite a bit different. The blue rectangle is #0042F6, and the selection chrome colors are quite a bit different (#6a94dc, #d3e1ee, #2b7bfc,#246ce4,#042378). I did a `grep -i` across Maqetta and Dojo for 0042F6 and came up empty.

Which browser(s)?

**Comment by jhpedemonte** [comment]
Hey, I said the colors were "similar", not exact!  :-)

This was on Chrome, and I've been able to reproduce quite a few times.

**Comment by doronrosenberg** [comment]
I see the issue in chrome only, and its white for me

**Comment by JonFerraiolo** [comment]
I can't reproduce. Do you guys see this regularly, or just once in awhile?

**Comment by doronrosenberg** [comment]
I can reproduce this consistently by drag and dropping 2 spinwheel widgets.  Funnily enough, if I undo the second drop, the bar goes away, and comes back when I redo

**Comment by doronrosenberg** [comment]
Oh and chrome only.  On firefox it works, but I noticed that once I drop the spinwheels they are not styled correctly while they have the correct style on chrome

**Comment by doronrosenberg** [comment]
ok,this seems to be a z-index issue.  If I change the "davinci_top_bar" z-index to 500 it fixes it.

**Comment by JonFerraiolo** [comment]
is web inspector running when this is happening? If so, what's currently showing in the inspector?

**Comment by doronrosenberg** [comment]
```
"NetworkError: 404 Not Found - http://192.168.1.122:8081/maqetta/user/Doron/ws/workspace/project1/lib/dojo/dojox/mobile/themes//.css"
.css
"NetworkError: 404 Not Found - http://192.168.1.122:8081/maqetta/user/Doron/ws/workspace/project1/lib/dojo/dojox/mobile/themes//-compat.css"
```

I wonder if this is the issue, we aren't loading the right compat files?

**Comment by doronrosenberg** [comment]
The webinspector doesn't show anything above the toolbar, its really weird.

Oddly enough, I can click on the links in "hidden" toolbar and show the dropdowns.  I almost have to wonder if this is a chrome bug.

**Comment by doronrosenberg** [comment]
Safari doesn't exhibit this as well, only chrome

**Comment by jhpedemonte** [comment]
Well, if this is just limited to Chrome and we can't find any reason for it, we'll just have to close this as a browser bug and just live with it.

**Comment by peller** [comment]
does anyone still see this?

**Comment by jhpedemonte** [comment]
I haven't seen it in months.  Closing.
