### ISSUE TITLE
Session timeouts with theme editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2214]
@childsb 

Maybe this will be addressed with @childsb recent server changes.

When testing the themeEditorDeltas branch (and simultaneously testing master using today's build using localhost:50000), in both cases I'm getting regular session timeouts even though I'm running single user and I swear neither session has been idle for 15 minutes.

Is there something special about theme editors where session active logic isn't working like it does in page editor?

I'll try to come up with a reproducible set of steps, but as you know, session timeouts tend to happen when you least expect.

**Comment by billreed63** [comment]
Do you get the warning banner with the 30 second count down? if not what is most likely  happening so a IO error to the server. We catch IO errors and send the user back to the login...

**Comment by jhpedemonte** [comment]
I committed some code a couple days ago that changes how server errors are handled, so this functionality may have changed (for better or worse).  Please retest.

**Comment by billreed63** [comment]
I have not seen this issue for quite a while now, we can reopen if it reappears
