### ISSUE TITLE
Save Icon does not show up in plain text editor

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2218]
When trying to edit a file with an unrecognized extension such as ".txt" or no extension at all, a plain editor appears with the content and the user is able to make edits without any assists (good) but there is no save icon or any toolbar icons at all

**Comment by peller** [comment]
@JonFerraiolo: on a related note, you can create a file like foo.txt by using new Javascript File and changing the filename to "foo.txt" at which point you get the same behavior above and no Javascript handling.  Another reason why, I think, we should have a single create file menu for the various file types, with HTML perhaps being a special case.

**Comment by jhpedemonte** [comment]
dupe of #43?

**Comment by peller** [comment]
yah
