### ISSUE TITLE
focus box clipped by viewport

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2219]
Drag several tall widgets like Calendar on to the canvas until a scrollbar appears
Scroll to the top of the page
Click to select the last visible widget
Observe that the focus box appears in its entirety on the page, even if the widget does not.  This gives a false location of the bottom two corners of the widget.

**Comment by JonFerraiolo** [comment]
Same thing we've had all along, even when we had the hashed focus chrome. The obvious trade-off is: (a) if you don't pull selection chrome into "viewport", then user may not see the selection chrome and has no visual feedback about what is currently selected, (b) if you do pull selection chrome into viewport, then the selection chrome appears to indicate a different size for widget that what it really is.

One thing that will help with this situation is moving the selection chrome out of the user document into the outer application. Then we won't have to back off for the common case where we are selecting a widget whose top/left is at (0,0) or whose bottom/right is at the bottom/right of the user doc's BODY. I'm hoping that we can move the selection chrome out of the user doc in early parts of M7.

**Comment by JonFerraiolo** [comment]
Pushing to M7. Too risky to attempt to fix now.

**Comment by JonFerraiolo** [comment]
This was fixed in M7 because selection chrome is now in the Maqetta frame rather than the user iframe.
