### ISSUE TITLE
DataGrid - support declaritive syntax for structure

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#222]
Currently the DataGrid only supports DataGrid's that declare their structure with the structure= paramater to DataGrid. We should support the more commonly user format of:
&lt;table dojoType="dojox.grid.DataGrid" escapeHTMLInData="false" 
        jsid="grid" id="grid" 
        store="jsonStore" query="{ label: '*' }" rowsPerPage="20" rowSelector="20px">
        &lt;thead>
            &lt;tr>
                &lt;th field="label" class="myGridCell" width="300px">Country/Continent Name</th>
                &lt;th field="type" width="auto">Type</th>
            &lt;/tr>
        &lt;/thead>
    &lt;/table>

**Comment by billreed63** [comment]
move to M5

**Comment by jhpedemonte** [comment]
-> M6

**Comment by billreed63** [comment]
Deprecated going to GridX
