### ISSUE TITLE
Split view on Firefox: click on widget, nothing highlighted in source view

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2225]
@aerwin - you fixed the other direction recently :-)

In Firefox in split view, I'm not seeing highlights in source pane when I click on widgets in the design pane. Works in Chrome, and in Firefox, the other direction works (i.e., click on something in source pane, and then corresponding widgets is indeed selected in design pane).

@peller

**Comment by doronrosenberg** [comment]
If I click on the outline view, chrome also doesn't mark the widget in source view.   And after clicking into the outline view, clicking on widgets in the design view also don't mark in source view until I click into the source view.

**Comment by aerwin** [comment]
-> @doronrosenberg 

I think this belongs with the other FF source view selection things you're tracking down (like #1935). If you disagree or you solve those other problems and this turns out to be unrelated, please send back.

**Comment by JonFerraiolo** [comment]
-> @peller

**Comment by peller** [comment]
selection should be working in both directions now, as of d006ad0b30587e7f878faa6bd4839ab1fa08f30c
