### ISSUE TITLE
DataGrid smart input confused

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2227]
1. Create new HTML file
2. Drag DataGrid onto canvas and enter following data in smart input:

```
one, two, three
data 1, data 2, data 3
xxxx, yyy, zzz
111, 222, 3333
```
1. Create another HTML file
2. Drag DataGrid onto canvas and click OK on smart input without changing any data
3. Save 2nd HTML file
4. Close 2nd HTML file
5. Reopen 2nd HTML file
6. Note table incorrectly has 3 rows and all cells filled with ellipses

![Table with ellipses](http://i.imgur.com/ngnuO.png)
1. Double-click to open smart input and note it incorrectly shows data entered for table in first HTML page

![Smart input](http://i.imgur.com/fbPFK.png)
1. Click cancel
2. Show source in split view (just to cause page to be refreshed) and note table renders correctly:

![Table rendered correctly](http://i.imgur.com/sLBpV.png)

**Comment by JonFerraiolo** [comment]
-> @billreed63

**Comment by jhpedemonte** [comment]
Perhaps the smart input code for DataGrid is getting the wrong editor instance at some point?

**Comment by billreed63** [comment]
this is usually the ItemFileReadDataStore not getting updated correctly in the helper. This is a regression...

**Comment by doronrosenberg** [comment]
Will take a look

**Comment by doronrosenberg** [comment]
Not able to reproduce using those steps on latest master.

**Comment by aerwin** [comment]
Hmmm... I just did a git pull into my local branch and I still see this issue there.

**Comment by doronrosenberg** [comment]
hmm, I can now reproduce in chrome but not firefox.
