### ISSUE TITLE
DIV gets padding:0 from dojo.css

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2231]
@peller , @childsb 

With latest code, if I add a DIV and look at properties palette, there is a `0` for the value, and the cascade has the radio button checked for a rule from dojo.css. Two problems:
- The cascade should have element.style checked, shouldn't it?
- Why are we including dojo.css to begin with? (I think this is from widget metadata)

I discovered this running the desktop tutorial (you know, Add Task, Task Added, etc), so I've done this a thousand times, and it's a regression.

**Comment by billreed63** [comment]
With the latest code from master the element is selected in the cascade. The cascade has always been calculated from the DOM, the metadata is only used to select the default rule for the property.  @childsb  correct me if I misunderstand the code.

**Comment by JonFerraiolo** [comment]
Actually, I made a change in the M6 cycle after working with some designers and changed the logic so that if a widget allows a property to be on element.style, then the element.style radio button is chosen by default.

**Comment by JonFerraiolo** [comment]
This changed in M6 by removing dojo.css (and replacing with document.css). With this change, document.css is not modelled (at least for now). Once we model document.css (#2378), this issue will reappear.

**Comment by JonFerraiolo** [comment]
@billreed63 - I'm closing this issue because the cascade is selecting element.style by default, even though document.css is included, and the cascade shows padding:0 for a rule in document.css. But could you please read through this issue carefully and make sure everything is going to be A-OK for M7?
