### ISSUE TITLE
Editing source loses current application state

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2232]
If you have a custom appstate and that appstate is current, whenever the user changes any document content in a source editor, we revert back to Normal state, but the Scenes palette still shows the previously selected state. (You can reset things by clicking on Normal, then clicking on the custom state)

Two possible ways to "fix":
- When applying source editor changes to the canvas, we could figure out what appstate is currently active, and then after updating the canvas, we could call setState(). Note that it's a bit more complicated than this because we also want to deal with mobile views.
- Or we could always revert back to Normal with each source change, in which case we just need to trigger a redraw of the Scenes palette

The first bullet is much more preferable, of course.

@peller - if you can point me to the code where source editor changes cause the canvas to get recreated, maybe you can reassign this to me and I can attempt to get the first bullet implemented

**Comment by peller** [comment]
davinci/ui/Editor, setContent() calls setValue on the Orion Editor component

**Comment by JonFerraiolo** [comment]
Thanks, I've grabbed this one now.
