### ISSUE TITLE
findResource *.theme returns each entry twice

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2233]
Open an HTML file, look in the network panel, and the call to findResource("*.theme") from Library.getThemes gets the entire list of theme files twice... android.theme, blackberry.theme, claro.theme... android.theme, blackberry.theme, claro.theme... then the Library code proceeds to load each one

Not a huge performance issue, since it just hits the cache, but something seems to have regressed here recently.

see #2206

@billreed63

**Comment by jhpedemonte** [comment]
cc @childsb
