### ISSUE TITLE
Switching between theme sets very slow

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2235]
Switching between different **theme sets** is very slow, and the UI becomes unresponsive until the switch has completed.
1. Found while running **Tests > Theme sets > Remove theme sets**.  In the **Manage Theme Sets** dialog, switching between entries in the _Theme sets_ list is very slow.  Sometimes the highlight in the list takes a long time to switch.  The **Name** field, though, always takes long to reflect newly selected theme set.  While waiting for switch to complete, all dialog controls are unresponsive.
2. Switching theme sets is also slow in the **Select a Theme** dialog (in VE).

[Tested on Firefox 11/Mac]

@peller

**Comment by peller** [comment]
dup of #2206?

**Comment by jhpedemonte** [comment]
Yes, thanks.  I searched but somehow didn't find that one.  I'll move my comment there.
