### ISSUE TITLE
Add support for specifying allowed parents/children for a widget

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#224]
Some widgets should only have certain parents or children (see the dojox.mobile widgets).  Allow developer to specify such attributes in a JS library's **widgets.json** file.

**Comment by jhpedemonte** [comment]
Also see #148.

**Comment by jhpedemonte** [comment]
See _allowedChildren_ and _allowedParents_ properties here: https://github.com/maqetta/maqetta/wiki/JS-Library-API

**Comment by JonFerraiolo** [comment]
Also see #594

**Comment by JonFerraiolo** [comment]
@peller

I added "Mobile" tag and changed to M2 because this bug is particularly important for mobile authoring and we are looking at a partial solution for the M2 release to address common mobile scenarios. One partial solution would be to see if we can fix the drop logic for new widget creation to look at "allowed parents" metadata to make sure that users can't accidentally drop mobile widgets into unsupported container widgets.

**Comment by jhpedemonte** [comment]
Had a discussion with Jon about this earlier, and he had a great idea.  When dropping, **the code can check if the target is an allowed parent** of the dragged widget.  If not, the code can **walk about the parent chain, until it finds an allowed parent**.

For example, consider a page with the following dojox.mobile widgets:

```
View
  |- RoundRectList
        |- ListItem
        |- ListItem
```

If you drag a RoundRectList on to a ListItem, we don't want the RoundRectList to end up as a child of either ListItem or its parent RoundRectList.  Rather, the code will walk the parent chain until it finds an allowed parent -- in this case, View.  In this particular example, dropping a RoundRectList on to one of the ListItems will result in the RoundRectList being added as a sibling to the existing RoundRectList.

**Comment by JonFerraiolo** [comment]
I poked around the code some and I'm pretty sure this is the key function (widget.js:119)

``` javascript
davinci.ve.widget.getEnclosingWidget = function(node){
    var richText = this.getEnclosingWidgetForRichText(node);
    if (richText){
        return richText;
    }
    while(node){
        if (node._dvWidget) {
            return node._dvWidget;
        }
        node = node.parentNode;
    }
};
```

Right now the logic just looks for the nearest ancestor with _dvWidget on its DOM node. Maybe the main thing we need to do is add some additional checks to keep looking until we find an ancestor that matches allowedParents and whose allowedChildren value includes this particular widget type.

**Comment by jhpedemonte** [comment]
`getEnclosingWidget()` is used in several places in the code, and is a good utility method to have.  So we shouldn't touch this function.

It's used by `CreateTool.onMouseUp()`, along with other ways to get the target widget.  This is where we need to plug in the checks.

I'm thinking of a general algorithm around these lines:

```
If target widget allows dropped widget
   Place dropped widget as child of target widget
else
   Travel parent heirarchy of target widget,
      until we find an allowed parent
   Place dropped widget as child of allowed parent,
      right after widget that contains target widget
```

**Comment by JonFerraiolo** [comment]
getEnclosingWidget() should have clearly defined semantics and the things that invoke it should understand those semantics. Maybe existing semantics are fine and shouldn't be changed. If so, then we probably need an alternate general purpose function with its own clearly defined semantics that takes into account allowedParents/etc, and make that function available to everyone, and call that function from CreateTool.onMouseUp(), versus hard-coding in CreateTool.onMouseUp(). I expect we will need to use the allowedParents logic in other places besides CreateTool.

Algorithm looks fine to me, but one question is what happens if you reach BODY without finding an allowed parent?

**Comment by jhpedemonte** [comment]
Agreed with your first paragraph.

Algorithm with BODY taken into account:

```
If target widget allows dropped widget
   Place dropped widget as child of target widget
else
   Travel parent heirarchy of target widget,
      until we find an allowed parent or reach BODY
   Place dropped widget as child of allowed parent or BODY,
      right after widget that contains target widget
```

**Comment by JonFerraiolo** [comment]
If BODY isn't allowed, shouldn't we tell user "invalid drop target" (or something comparable that is more user-friendly)? Long-term, we should change cursor so that while dragging the cursor indicates whether over a valid drop target or not, but until we do that, perhaps a dialog that says "invalid drop target"

**Comment by jhpedemonte** [comment]
Oh, that's right, I forgot to consider the case of widgets that must go into a certain type of parent widget, in which case BODY wouldn't be an appropriate parent.

Yes, maybe for now we can pop up a dialog saying something like:

> Invalid drop target.  &lt;widget type> can only go into &lt;widget type list>.

**Comment by jhpedemonte** [comment]
Last commit has a working impl for CreateTool.js -- so dropping a widget on the page will look at `allowedChild` & `allowedParent` properties.  I've only added those props for a few of the **dojox.mobile** widgets.

To test:
- add a **dojox.mobile.View**
- add a **dojox.mobile.RoundRectList** inside of View
- drop a **dojox.mobile.ListItem** on top of the RoundRectList

Previously, this would have resulted in a ListView nested within a ListView.  Now, the new code will see that ListView is not an allowed parent for ListView and walk up the parent chain.  End result is that the dropped ListView is added to the others in RoundRectList.

One issue: Maqetta currently lets you drop other things inside of ListView (for example, a Heading widget).  This should be handled by the **isContainer** property, right?  Only widgets with `isContainer === true` should allow other widgets inside?

**Comment by JonFerraiolo** [comment]
regarding isContainer, maybe you and I should talk on phone about that. we need a clean strategy for isContainer, acceptsHTMLChildren, allowedChildren, etc.

**Comment by JonFerraiolo** [comment]
I tried the testing scenario, and these changes represent a night-and-day improvement in usability. I'm sure there are a ton of next-level issues we will encounter, but this is major progress.

**Comment by jhpedemonte** [comment]
Yeah, it actually works pretty well.  The next step is to go through all of the widgets and start adding the `allowedChild`/`allowedParent` properties.

**Comment by jhpedemonte** [comment]
From an email from @JonFerraiolo:

> I was looking at related code and the thought came to me that allowedParents/allowedChildren logic ultimately needs to go in multiple places:
> - CreateTool (which I believe you are addressing)
> - PasteTool
> - Drag/drop rearrangement on canvas (Adam would know where that code is - SelectTool?)
> - Drag/drop rearrangement in Outline palette
> - SurroundWith ... (maybe some widgets aren't valid as children of DIV, SPAN or A)
> - (Probably difficult to pull off and therefore low priority) Pasting source code in source editor
> 
> Can anyone thing of any other scenarios?

**Comment by jhpedemonte** [comment]
Based on a discussion between myself, @JonFerraiolo and @peller:

Instead of only allowing widget **types** in `allowedChild`/`allowedParent` (i.e. `"allowedParent": "dojox.mobile.RoundRectList, dojox.mobile.EdgeToEdgeList"`), implement a tagging system (maybe using property `class`?) so that we can group widgets with similar properties and use those tag names in the `allowed*` properties.

For example, all Dojox Mobile widgets could be tagged as **DojoxMobile**, and a subset of them could also be tagged **DojoxMobileContainer**.  Then, some widgets could have something like `"allowedChild": "DojoxMobile"` or `"allowedParent": "DojoxMobileContainer"`.

Since it wouldn't be efficient to only use these tags, we would still allow the use of widgets types in the lists: `"allowedChild": "DojoxMobile dijit.form.Button"`  (that is just an example, not meant to actually mean anything).

**Comment by jhpedemonte** [comment]
Trying to think of all edge cases and define a specification for the two properties.  Tell me if you agree with this:

```
allowedParent ::= "ANY" | { <widget_category> | <widget_type> }+
allowedChild ::= "ANY" | "NONE" | { <widget_category> | <widget_type> }+
```

where,
- **"ANY"** or **"NONE"** must be by themselves as the value.
- If empty or not specified,
  - `allowedParent` defaults to **"ANY"**
  - `allowedChild` defaults to **"NONE"**
- If neither "ANY" or "NONE", can be any combination of **&lt;widget_category>** or **&lt;widget_type>**.
- `<widget_category>` is a single word, camel-cased (i.e. "DijitWidgets") representing a set of widget types.  Matches a value for the `class` property in **widgets.json**.
- `<widget_type>` is period-separated words (i.e. "dojo.form.Button").  Matches a value for the `type` property in **widgets.json**.

**Comment by JonFerraiolo** [comment]
This is looking good. One obvious question is how much we need to worry about global uniqueness for the category names in order to prevent collisions with widget types and other category names. For example, if we had a standard reserved prefix for category names (e.g., always starts with "_i" where "i" stands for "interface", or maybe just a "@" sign, such as @DijitWidgets), then at least the categories wouldn't conflict with the types.

**Comment by jhpedemonte** [comment]
I'm not sure how much of an issue that is.  For the most part, a library will just be worried about its own types or HTML.  Hopefully, they'll do a bit of namespacing (as I did in my last comment with the two Dijit examples).  So its really up to the library metadata writer to avoid collision in their own file.

**Comment by JonFerraiolo** [comment]
I'm thinking ahead to the (potentially mythical) world where users mix-match widgets from libraries written by different people, which might include widgets that don't use dot notation in their widget names. The old global-namespace issue. May not be a big factor going forward, but I've been through similar global namespace things in the past and sometimes you get bitten down the road if you don't have a clean naming convention upfront. But I'm ok with what you have proposed.

**Comment by jhpedemonte** [comment]
OK, I think this is at a good state now.  To see this in action, using **Dojox Mobile** widgets:
- Drop a **View**.
- Drop a **Heading** in View.
- Drop a Heading on to Heading.
  - _Previously, this would have resulted in a Heading within a Heading._
- Drop a **RoundRectList** on to either Heading.
  - _Previously, this would have resulted in a Heading with a RoundRectList child._
- Drop a **ListItem** on to the RoundRectList.
  - _Previously, this would have resulted in a ListItem within a ListItem._
- Drop a **ToolBarButton** on to a RoundRectList.  Then drop on to a Heading.
  - _Now, a ToolBarButton can only be dropped on a Heading._

Still need to go through all of the widgets and define proper values.  I've only done a bit of work with the **Dojox Mobile** widgets.

One requirement, though, was that I define `"allowedChild": "ANY"` for any widget that has `"isContainer": true`.  The latter is now deprecated, replaced by the former.  As we go, we may want to replace `"ANY"` with something more specific for some widgets.

@JonFerraiolo, if you have some time, please test it out.  I think I've covered all the bases, but I may have missed something.  Also, I could use some help cataloging all of the widgets and finding appropriate values for the `allowedChild`/`allowedParent` properties.

**Comment by jhpedemonte** [comment]
Curses, this breaks with widgets that define a `"data"` property in the descriptor, such as **dojox.mobile.ComboBox**.  I had assumed that `this._data` in **CreateTool.js** would have a `type` property.  But in some widgets, `this._data` is an array of widget data, with each array element having a `type` prop.

Not sure how best to handle this, yet.  I really only care about the widget selected by the user -- I need to get that type.

@billreed63

**Comment by jhpedemonte** [comment]
The `data` object that comes in to **CreateTool.js** seems to come from **Palette.js**, in `_createPalette()`.  The simple fix would be to always set the `data` object associated with each Widget palette item to have a `type` property, corresponding to the widget.  Something like this:

``` javascript
    data: {type: item.type, widget_data: item.data} ||
          {type: item.type, properties: item.properties, children: item.children},
```

... some time later ...

Actually, now that I look at it, all of the code in **CreateTool.js** assumes that the `data` object is not an array and contains a `type` prop.  If a widget descriptor defines its own `data`, then there will need to be a corresponding `CreateTool` object to properly handle the data.  Seems inefficient -- I'm sure we're duplicating quite a bit of code amongst all of the `CreateTool` "subclasses".

**Comment by billreed63** [comment]
Looking at the widget.json all the widgets that have data also have a widget specific createTool The data is passed to the create tool and used to create the instance, For the createTools I have worked on (DataGrid, Tree, mobile.ComboBox) I do use the data that is passed in to create the widget, but the createTool helper could define the data within createTool helper  eliminating  the need to have it in the widget.json, Actually think it over it might be cleaner to require that the CreateTool helper define the data, It would remove it from the json and consolidate all the data and logic in the createTool helper. providing a single well defined way to create complicated widgets.

**Comment by jhpedemonte** [comment]
For now, checked in workaround based on my previous comment.  This is low risk.  We can look to redo CreateTool and subclasses after M2.

**Comment by jhpedemonte** [comment]
Commit 2de8c79266283617c506df30163f574f1db118a1 was reverted by commit in #662.

**Comment by jhpedemonte** [comment]
Went through all of the Dojo and HTML widgets and added `allowedChild/Parent` props as best I could.

One question: many of the container Dijits seem to only ever be used with **ContentPane** children, although I haven't seen any mention of this being a requirement.  For now, leaving those widgets as `"allowedChild": "ANY"`.

I think this bug is done.  Open new issues for any remaining bugs.

**Comment by JonFerraiolo** [comment]
Regarding only ContentPane children, you mean BorderContainer, TabContainer and Accordion for example? For those, I'm pretty sure we should only allow ContentPane children. This will greatly help prevent users from getting themselves into trouble via drag/drop on canvas or drag/drop on Outline palette if Maqetta prevents accidental dropping of (for example) a Button as a direct child of a TabContainer.

**Comment by jhpedemonte** [comment]
Spun of last question as separate issue #724.
