### ISSUE TITLE
Red screen of death with this file

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2245]
@peller 

Using a recent nightly build, a user ended up with Maqetta generating the following file, which caused RSOD. He was doing some hand-editing, and was using a nightly build, so in a sense "all bets are off", but nevertheless we should investigate to see what we can do to minimize this sort of problem. This scenario will be commonplace - a user needs to add some custom JavaScript, and therefore needs to do some hand-editing.

I realize that we might not be able to do much before M6, so I wouldn't be surprised if we push this to M7.

Some things that come to mind as things we might do:
-  it might be a good idea for docs to put a big marking where the user/developer is allowed to include his own "include javascript.js" parts to not puzzle Maqetta, when the file is reloaded into the editor. Maybe there could be a "block" within the HEAD part of the HTML Or maybe in the other direction, we can put comments around the sections of the HEAD that Maqetta needs and that the user shouldn't touch.
- Note that there are 2 SCRIPT tags below with `require` inside. Maybe we need a smarter algorithm for finding and updating SCRIPT tags when we update the file to include an updated list of requires. 
- Longer-term, we need to provide better documentation and tools to make it so that users don't have to talk directly to the core team developers just to get a couple of ContentPane's and a button to work! :-) On the tools front, what I'd like to see if that we preserve editing history across sessions and allow a user to go backwards in time on a given file until he can revert back to something that works, plus a comparison tool that will show the source code difference between what worked and what didn't work.

BROKEN FILE:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<style>@import "themes/claro/claro.css";@import "lib/dojo/dojo/resources/dojo.css";@import "app.css";
</style>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'async':true,'parseOnLoad':true,'packages':[{'name':'maqetta','location':'../../../.'},{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'shapes','location':'../../shapes'},{'name':'jquery-ui','location':'../../jquery-ui'},{'name':'yui','location':'../../yui'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "maqetta/space",
  "maqetta/AppStates",
  "dijit/layout/ContentPane"
]);
require(["dojo/parser"]);</script>
<script type="text/javascript" src="maqetta/maqetta.js"></script>
<script type="text/javascript">
require(["maqetta/States"]);
require(["dijit/layout/ContentPane"]);</script>
</head>
<body class="claro" dvFlowLayout="true" data-davinci-ws="collapse" dvStates="{'State1':{'origin':true},'current':'State1'}" id="myapp">
 <div data-dojo-type="dijit.layout.ContentPane" title="Pane" doLayout="false" style="width: 392px; height: 290px; background-color: #f70505;" dvStates="{'State1':{'style':[{'display':''}]}}">
<button title="hello" name="HELLO" onclick="davinci.states.setState('State1')"></button>
<div data-dojo-type="dijit.layout.ContentPane" title="Pane" doLayout="false" style="background-color: #0d05f7; z-index: 9999; display: none; position: absolute; left: 299px; top: 86px; width: 433px; height: 372px;" dvStates="{'State1':{'style':[{'display':''}]}}" onmouseover="davinci.states.setState('Normal')"></div>
</div>
</body>
</html>
```

**Comment by peller** [comment]
What was the error seen in the RSOD?  A stack trace is not provided.

One thing to note - this is apparently a file created on our development 'master' and not a stable release.  I see that the user has some transitional elements from the maqetta.\* module transition, and we didn't do anything to migrate issues between releases.  I don't know if any of this led to his RSOD.

**Comment by JonFerraiolo** [comment]
> I see that the user has some transitional elements from the maqetta.\* module transition, and we didn't do anything to migrate issues

Right, we will like have to ignore the "transitional" part of this issue. Note that I created an adjacent issue: #2248: "For bad user HTML, fewer red screens of death and better fixup information"

**Comment by jhpedemonte** [comment]
Since we're trying to finish M6 quickly, pushing this off to M7.  This requires some further discussion as to what we want to do.

-> M7

**Comment by jhpedemonte** [comment]
We are working better now, especially with the 2nd bullet point (we put all `require` statements in one).

Should we close this?  We've run across other RSODs, but those are handled in other issues.

**Comment by JonFerraiolo** [comment]
I tried to load the above source code using M7 and got a simple red screen in design view. Not even a supporting message. The debugger console shows messages about not being able to load `States.js` (vs `AppStates.js`).

What I suggest is transforming this into a lower-priority M8 issue about better error messages when loading a file that we can't deal with.

**Comment by jhpedemonte** [comment]
Well, that's taking text that Maqetta wouldn't currently generate, so I don't think that's a valid test.

**Comment by JonFerraiolo** [comment]
But we should include a better message if a user tries to import an HTML file that Maqetta can't parse properly.

**Comment by jhpedemonte** [comment]
OK.  How do we handle that?  And do we want to do that for M7?  Probably best to push to M8 in that case.

**Comment by JonFerraiolo** [comment]
> best to push to M8

That's what I said in my comments, push to M8 as a low-priority issue. I'll do that now.

**Comment by peller** [comment]
example seems to run fine now.  Not sure we ever got the stack trace from the RSOD in the original report, so it's not clear what the problem was.  The only error now is a harmless one (runtime, not parse time) that the old require() for maqetta/States does not work.  It's reported to the console.

**Comment by jhpedemonte** [comment]
-> @peller.  Close this one?

**Comment by JonFerraiolo** [comment]
Post-closing comment - the original file was from an older version of Maqetta, when it was still `States.js` and not `AppStates.js`. Basically, M7 and later can't deal with the HEAD produced by releases before the AMD (and AppStates.js) changes.

If instead of copying/pasting the entire file above, I copied/pasted from the original file the content within the BODY into a newly created empty page (using the newer version of the HEAD), then (good news) things sort of work.
