### ISSUE TITLE
Source pane missing first column

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2250]
@aerwin @doronrosenberg 

User report on M6 nightly builds:

I noticed that after loading a HTML and switching to the source display for the first time the scrolling is one step to the right (first column is missing), manually correcting this works fine, though (so it's not a "bug", but a "glitch" :-) )

**Comment by peller** [comment]
sounds like the latest incarnation of #1242

**Comment by peller** [comment]
-> M7

**Comment by peller** [comment]
seems ok after latest Orion integration in d006ad0b30587e7f878faa6bd4839ab1fa08f30c
