### ISSUE TITLE
Migrate preview 5 theme html files

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2251]
The mobile theme html files need to be modified to support the new `data-dojo-config` mobile theme  `data-dojo-config="parseOnLoad: true, async: true, 'themeMap':[['.*',null,[]]],'mblThemeFiles':[]"`

**Comment by jhpedemonte** [comment]
Decided not to handle this during migration (too complex).  Should work for the most part, but if users created a non-standard theme map, they'll have to re-set it for the file.

@JonFerraiolo
