### ISSUE TITLE
Update preview6.html release notes for various UI improvements

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2252]
@doronrosenberg - I've been meaning to register an issue on this for a couple of weeks, but keep forgetting.

In M6, you have added a series of UI improvements, particularly widget-specific UI improvements, such as the new dialog for IconContainer. Could you please try to remember all of these UI improvements and then make judgment calls about how best to mention these UI improvements in the Preview 6 release notes? It seems like we should at least mention a number of these UI improvements. Maybe we need a new higher-level section in the release notes such as "Mobile authoring UI improvements".

**Comment by doronrosenberg** [comment]
Fixed by 8740c1e0a2c584c3cdbd4652bdfeb67be1e733fa
