### ISSUE TITLE
Can incorrectly select individual options in MultiSelect

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2253]
Opening as medium, but in quick testing doesn't seem pervasive across other widgets so could argue for low...
1. New HTML file
2. Drop Button onto canvas
3. Drop MultiSelect onto canvas
4. Select button
5. Select MultiSelect by clicking in the area of one of the items (e.g., Item 2)
6. Note Item2 within MultiSelect is selected and you can now all of the items in the MultiSelect are selectable. And, there is a 0x0 selection box in the upper left hand corner of the canvas representting the selected OPTION element.

![Screenshot](http://i.imgur.com/6uzIA.png)

Using Chrome on Mac.

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo M6 Prio Med
I can reproduce and I want to understand what's broken here before pushing to M7.
