### ISSUE TITLE
need workspace migration plan

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#2254]
We need a better workspace migration plan-

1) Migration scripts should be a "run once at server startup" and not OS specific.  Another option is to run the script at user login.

2) User projects should keep the maqetta version they were authored in (libs.settings).  Then migration scripts can be incrementally run to bring the project up to date.

3) Migration scripts should allow the workspace to upgrade from any version to any other version.  Downgrade not necisary.

**Comment by aerwin** [comment]
--> no milestone to M7
--> prio Med
--> Feature

**Comment by jhpedemonte** [comment]
@childsb, do we currently add a version string to _lib.settings_ or any other file within the project?   The version string should reflect the last version of Maqetta to open that project.

**Comment by jhpedemonte** [comment]
Closing. Fixed through use of pre-upgrade migration script and in-app code to migrate to the Orion workspace format.
