### ISSUE TITLE
Opening a CSS file throws error (this.dndController is undefined)

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2256]
Opening any css file or creating a new one throws:

```
TypeError: this.dndController is undefined
http://192.168.1.122:8081/maqetta/app/dijit/Tree.js?@revision@
Line 0
```

**Comment by JonFerraiolo** [comment]
@doronrosenberg could you please investigate? Maybe we just need to add a check at ToggleTree.js:72 that this.dndController has a value:

```
    var mouseDown = this.dndController.onMouseDown;
```

@peller @childsb

**Comment by JonFerraiolo** [comment]
Also exception at Tree.js:960 (this is in dijit/Tree.js):

```
this.dndController.setSelection(nodes);
```

**Comment by doronrosenberg** [comment]
I think we would want to not build the tree at all in this case

**Comment by doronrosenberg** [comment]
Issue is we can't set a null dndController for a tree
