### ISSUE TITLE
Rich text editor does not show automatically when add sticky note to page

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2257]
According to the "Sticky note" section of the VisualPageEditor/basic1.html test plan the smart input for sticky note should automatically appear when you click on the sticky note icon. However, that does not occur (e.g., you must manually double-click on the note).

> Click on the sticky note icon. After a few seconds, _the Dojo rich text editor should appear as a very large overlay on the page canvas_. Create some rich text, such as bullets. Then click away from the rich text editor to cause your changes to be added to the document as a yellow sticky note that is absolutely positioned.

**Comment by JonFerraiolo** [comment]
-> @billreed63 M6 Prio High - (I thought we fixed this recently)

**Comment by billreed63** [comment]
We have always had two different behaviors for sticky note:

If the note is created from the action bar the RTE is not displayed until the user double clicks on the sticky note. 
If the sticky note is created from the widget palette we display RTE as soon as the widget is created.

@aerwin  did you create the note from the action bar or the widget palette? If from the action bar then we need to fix the testcase. If from the widget palette I can not reproduce with the latest code.

or the third option change the behavior of sticky note from the action bar.

**Comment by aerwin** [comment]
Yes, I was clicking on the toolbar icon. I just tried dragging from palette and that works fine (as @billreed63 reported).

**Comment by JonFerraiolo** [comment]
Why don't we show the RTE immediately if creating a sticky note from toolbar?

**Comment by billreed63** [comment]
You asked me to turn it off....

**Comment by JonFerraiolo** [comment]
Do you remember why I said turn it off? Perhaps a case of temporary insanity?

**Comment by billreed63** [comment]
I think maybe because RTE can be slow to load sometimes, so we thought the user might want to positions the note then add text. No one has ever complained including UI people. Maybe we should just leave it alone unless someone complains..

**Comment by JonFerraiolo** [comment]
-> M7 We can talk about UI for next release

**Comment by JonFerraiolo** [comment]
@peller: question - with Preview6, the first time a user brings up one of our rich text widgets (e.g., sticky note), the network panel shows this:

```
RichTextInput.js
Editor.js
LinkDialog.js
TextColor.js
FontChoice.js
_Plugin.js
EnterKeyHandling.js
html.js
range.js
```

Will any of our new build logic in M7 consolidate the above calls? One thing that should be way faster now than 6 months ago is that Dojo (since 1.7) is loading all of the above using async (and parallelized) web requests.

**Comment by peller** [comment]
@JonFerraiolo, we could create a layer for RichTextInput to consolidate these calls.  It gets a little confusing since the dependencies may be shared by other widgets, so it would have to be done carefully. The async will make a big difference either way, though.
