### ISSUE TITLE
Update to latest Equinox / Jetty 8

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2259]
currently in M7 (Eclipse's, not ours) set to come out in June, but stable.  Among other things, this should get us servlet 3.0 with the ability to set things like httponly cookies.

@childsb, @JonFerraiolo, @jhpedemonte

**Comment by childsb** [comment]
as a note- the orion build with maqetta  is already using the 3.8 eclipse.  john claims that the next release (which is the one we'll prob use for 1.0) will run on eclipse 4 latest stable.

**Comment by peller** [comment]
Orion should have us running on a newer equinox now.  Investigate whether httponly cookies are available -> M8

**Comment by peller** [comment]
transferred to Orion: https://bugs.eclipse.org/bugs/show_bug.cgi?id=389929
