### ISSUE TITLE
Global page background not showing in mobile theme editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2262]
@billreed63 - I thought this bug was logged already, but I couldn't find it.

As things stand now, you can change global page background color in mobile theme editor, and the themes get updated and all of that, but the theme editor doesn't show the result on the theme editor canvas.

Assigning to me because this is likely in the middle of the theme editor hocus pocus that attempts to transfer the BODY background into various parts of the theme editor's UI, and I was involved in that the last go around.

**Comment by billreed63** [comment]
I got this one, the helpers are now asyn so they can return a deferred.

**Comment by JonFerraiolo** [comment]
Reopening. With today's daily build on Mac/Chrome running locally, I'm still having problems where sometimes changes to global background color doesn't show up on the canvas.

**Comment by billreed63** [comment]
I am still seeing this issue, if I have the debugger off in chrome then updates do not happen consistently. Only with the debugger open (which in my case disables cache) do the changes get applied.. 

Works like a champ on FF

**Comment by JonFerraiolo** [comment]
Yes, I'm still seeing this issue too

**Comment by billreed63** [comment]
For some reason using `<style type="text/css"> @import 'theme.css'</style>`  in context.js to load the theme
was not allowing us to consistently load and fine the style sheets for hot modify  on Chrome > 19
so I change the code in Context to use `<link rel="stylesheet" type="text/css" href="'theme.css '">`

Seems to have solved the issue..

**Comment by JonFerraiolo** [comment]
It was easy as that? I'm worried that we have other places in our code that are dependent on @import instead of LINK. @jhpedemonte, have you seen this? Also, are there migration issues?

**Comment by billreed63** [comment]
I don't think it is a migration issue, we added the theme CSS files in Context.js (page designer) so we are just using link to add them dynamically to the head instead of `@import`
