### ISSUE TITLE
Fix tabbing order through Properties view elements

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#227]
The tabbing order of elements in the Properties view is odd.  To see the issue:
- In Padding/Margins section, select "show t/r/b/l" under Padding.
- Select dropdown widget next to "Padding:".
- Tab through elements.

You'll see that elements are not highlighted in a straight forward manner.

**Comment by jhpedemonte** [comment]
Duping to #608, since that has a bit more info.
