### ISSUE TITLE
Improper handling of accented filenames

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2279]
Created a folder called **éttubruté** and a file called **ümlaut.js**.  Files in folder and ümlaut.js were all open.  When I refreshed the browser, none of those files were reopened (some that didn't have accented names were reopened).

Looking at **Files** view, accents had become mangled:

![accented filenames](http://i.imgur.com/a1uJu.png)

**Comment by peller** [comment]
Server streams and responses should all be UTF-8.  Filename on disk is ok, so it seems to be listFiles mangling the names

**Comment by JonFerraiolo** [comment]
@aerwin @doronrosenberg @peller - if one of you has expertise and interest in this one, please grab this issue

**Comment by peller** [comment]
-> @peller

**Comment by jhpedemonte** [comment]
A change to fix this would be too risky for M7, may cause other issues.  -> M8.
