### ISSUE TITLE
Empty non-HTML editors

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2280]
Going through tests with many files left open.  Closed an HTML file and was taken to a CSS editor.  Showed nothing in editor view -- no content, no gutter with line numbers.  Same thing happened for all other open CSS and JS files (HTML files worked fine).  

![empty editor](http://i.imgur.com/TtzAQ.png)

(Worth spending a bit investigating this, but feel free to push to M7 if too risky or too involved to debug.)

@JonFerraiolo

**Comment by peller** [comment]
unable to reproduce so far... any tips would be appreciated.  nothing on the console?

**Comment by peller** [comment]
does it have anything to do with your ümlaut test?  I can't even get an HTML file with an ümlaut to persist right now.

**Comment by peller** [comment]
-> M7

**Comment by jhpedemonte** [comment]
-> Back to me to reproduce.

**Comment by jhpedemonte** [comment]
Couldn't reproduce with latest code.  Closing.
