### ISSUE TITLE
VE update after source changes takes too long

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2281]
In Source view, delete widget and it takes **3 seconds** for deletion to be reflected in VE.

[tested on Firefox 12/Mac]

**Comment by peller** [comment]
Time to render will increase with page complexity and # of widget types.  That said,

One second is spent waiting for the user to stop typing (see onTextChanged in davinci/ui/Editor)  This could be adjusted, but until everything else is snappier, I think we're better off leaving the delay long.

After that, additional time seems to be spent doing GC (in Chrome, about .2 sec)

Model update occurs

_updateDesignTimer fires in davinci/ve/PageEditor after 1 sec causing additional processing, including _setSource.  Looks like the additional delay is unnecessary here.

**Comment by jhpedemonte** [comment]
Much better.  Down from 3 secs to about 1 sec on FF.  Code looks good as well.  Thanks.
