### ISSUE TITLE
Item selection issues in Widgets palette.

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2282]
In **Widgets** view:
1. New HTML file.
2. Select any widget.  Notice that when you move mouse off of Widgets view, item stays selected, and you get a crosshair when moving over VE (implying that you can drop widget in page).
3. Select a different widget in Widgets palette.

At first, it looks like the 2nd widget has been selected.  But once you move the cursor away, you see that the widget is not selected and you cannot drop the 2nd widget on the VE.  User needs to click again in order to properly select widget.

Clicking on another widget with one already selected should (1) deselect old widget, then (2) select new widget.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
Pushing to M8. Too risky to mess with something that is used all the time by nearly all users, and we are going to make major changes to Widgets palette with M8.

**Comment by JonFerraiolo** [comment]
This was fixed in M8 as part of widget palette makeover. Closing.
