### ISSUE TITLE
Project combo box shouldn't be editable

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2283]
The drop down in **Files** view which allows selecting between projects is editable.  User can enter any value and hit enter, causing a refresh.

Should just be a drop down and shouldn't allow editing.

@childsb @JonFerraiolo

**Comment by doronrosenberg** [comment]
This broke project selection, reopning

**Comment by JonFerraiolo** [comment]
This has been fixed. Closing.
