### ISSUE TITLE
M5->M6 migration script

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2284]
Affected issues/commits:
- Update listing of "maqetta" library in `<project>/.settings/lib.settings` [#2142]
- `maqetta/States.js` renamed to `maqetta/AppStates.js` [#2095]
- "maqetta" lib files moved into `<project>/lib` [#1193]
- "maqetta" lib files now using `require()` [#2085]
- New theme map format [#2251]

---

**Tasks:** _(updated 2012-05-16)_
1. Delete `users/.review` dir.
2. Delete guest user workspaces.
3. Delete `users/<workspace>/.review` directories.
4. Change default location of "maqetta" library, in `users/<workspace>/<project>/.settings/libs.settings`:
   
   ```
   -<library id="maqetta" name="maqetta" version="0.3" virtualRoot=""/>
   +<library id="maqetta" name="maqetta" version="0.3" virtualRoot="lib/maqetta"/>
   ```
5. Add line for "grids" library, in `users/<workspace>/<project>/.settings/libs.settings`:
   
   ```
   +<library id="gridx" name="gridx" version="1.0" virtualRoot="lib/dojo/gridx"/>
   ```

**Comment by peller** [comment]
the lib issues seem to require migration, but the states files and require could be resolved by asking users to do a load/save on their files.  Until then, states functionality will not work.  Removing the old script tag for the missing States.js file is optional.

**Comment by jhpedemonte** [comment]
Yesterday, I created a new user on both M5 and latest M6 as follows:
1. Delete any existing `users` dir.
2. Start server in multi-user mode.
3. Create new user.
4. Create new:
   - HTML file - add a Calendar
   - CSS file
   - JS file
   - Theme - clone claro
   - Review of Sample1.html
5. Repeat (4) with a new Eclipse project.

_Note:_ Couldn't create a theme in the Eclipse project, due to an existing bug.

---

[Here's the diff](https://gist.github.com/2707580) of all the major differences between the M5 files and those in M6.

---

I started M6 with the M5 `users` dir and this is what I found:

a. root dir contained (disabled) "AppStates.js" and "space.js" files.  Modify Libraries shows empty string for "maqetta" lib.
b. Modify Libraries shows GridX library disabled and it is not shown in _Widgets_ view.
c. Sample1.html seems to work just fine, including states and during preview.
d. Opened review of Sample1.html.  Only "Normal" shown in Scenes view, and clicking on **New** button in page threw error.

The issue with (a) is that we changed the location of the "maqetta" library files, from "" to "lib/maqetta".  Need to change that in `<project>/.settings/lib.settings`.

For (b), need to add a line to that same settings file for the _GridX_ library.

I'm surprised that Sample1.html works so well, but I think I understand why.  The old includes from the "maqetta" lib will fail, and when we open a VE, we add the correct _AppState.js_ and _space.js_ files.  And so Sample1.html works fine in both VE and preview, including states/scenes.

On the other hand, a review of Sample1.html does not work well.  Since it is a "snapshot", it does not get the new JS files from the "maqetta" lib, and therefore states/scenes do not work in the review.  I guess we can **keep with the existing practice** of **deleting reviews during migration**.

**Comment by peller** [comment]
Correct - we renamed the files specifically so that the old statements would fail gracefully in VE and at runtime

**Comment by jhpedemonte** [comment]
cc @JonFerraiolo @aerwin  @billreed63, please take a look at the [M5->M6 diff](https://gist.github.com/2707580).

@aerwin, there are significant changes in a couple of the Eclipse project files (first 2 in the diff).  Do we need to handle those changes during migration?

**Comment by jhpedemonte** [comment]
Updated summary with known migration tasks.  Let me know if I missed anything.

**Comment by aerwin** [comment]
@jhpedemonte I'd say if we expect M5 users to try to import projects they've migrated to M6 into RAD, it would give them the smoothest experience if we migrated these files.

That said, I'm not sure things would "fail" without migrating. E.g., some of the changes were to better exclude Dojo from validation checking, etc.

If you wanted to export your M5 project, I could probably try and get the latest RAD and see how it goes without migrating the files. But, it typically takes me a bit of time to track down, download, and install the latest RAD. And, the last good one I had installed is on my PC laptop back in MN.

**Comment by JonFerraiolo** [comment]
Regarding importing into RAD, it's a hard enough problem to get files created by our latest and greatest version of Maqetta to import correctly into the latest and greatest version of RAD. I'd drop everything else.

**Comment by aerwin** [comment]
You mean "drop everything else" to get the files migrated?

**Comment by JonFerraiolo** [comment]
No, I mean just worry about getting new projects created exclusively with M6 to export/import into the latest release of RAD, and don't worry about dealing with Maqetta projects/content created with M5 or earlier, and don't worry about dealing with Maqetta M6 projects working with older releases of RAD.

**Comment by jhpedemonte** [comment]
RE: Eclipse projects.  So what I'm hearing is that we should **not** migrate Eclipse projects.  We should probably add something to the release notes about this as well, saying that there were updates to Eclipse/RAD handling in M6 and that users may need to recreate their projects.

**Comment by jhpedemonte** [comment]
Committed a script to handles **tasks 1-5** as written up in the summary.  Took my a while to get it working correctly for Eclipse projects, but it seems to be working well now.  Please have a look.

**Comment by jhpedemonte** [comment]
Note: need to add **Migration** section to release notes, pointing to migration script.

**Comment by jhpedemonte** [comment]
Also, see 8cacea838bfc8c976be24a3a3d0d87a4041f269c.

Migration script seems to have worked well, so closing.  Also added _Migration_ section in the release notes.
