### ISSUE TITLE
theme editor changes not reflected in open documents

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2286]
Open the theme editor for a new theme
Open a file using that theme.  Drop a widget or two on the page.
Flip back to the theme editor and make a visual change to the style of those widgets
Flip back to the editor, no change is seen.  You must save, close and reopen your file to see it.

Not sure if this should be M7. If we switch to a single editor per workspace, this issue obviously goes away.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
Moving to M6 Med for time being so @billreed63 will look at it in short-term. 

> If we switch to a single editor per workspace, this issue obviously goes away.

If you mean that the theme editor and page editor would be in different browser windows, I would think the issue would get worse. At least right now (I believe) we maintain a shared model for CSS files (i.e., themes) that gets shared across all open editors.

**Comment by billreed63** [comment]
This is a regression, the singleton code has been dropped,  by commit 33f95c0a52bed07be7612dd3fdf25b3cbf0253d3
There may be other pieces that are missing..

CSSImport:71
 CSSSelector: 128
 HTMFile 178
