### ISSUE TITLE
VE 2 test case: Difficulty adding new widgets when scrolled to the bottom

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2293]
Using FF on Mac...

Working through VisualPageEditor/basic2.html test cases... got to step 3 of the "Container widgets (continuation of previous)" section where it asks me to drop an HTML DIV onto the panel (after just dropping some Dojo containers).

Basically, I'm not having a lot of luck adding the DIV (or any other widgets) when scrolled to the bottom. 

Comments that follow apply to screen shot below.... First of all, as soon as I drag the DIV over the canvas I lose the little flyover indicator that I'm dropping a DIV. However, it seems to work when I release the mouse over the content pane in the accordion, but not if I try to drop between the accordion and the tab container. Nor does it work if I drop after the tab container.

Also, when I drop over the tab container, it renders a div but incorrectly sized and overlaying both accordion and tab container (see selected widget below):

![Screenshot](http://i.imgur.com/e2mXx.png)

Despite the bad rendering, the outline shows the DIV instead of the first content pane of the tab pane.

![Screenshot](http://i.imgur.com/f5L63.png)

The HTML source for my page follows:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'async':true,'parseOnLoad':true,'packages':[{'name':'maqetta','location':'../../maqetta'},{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'shapes','location':'../../shapes'},{'name':'jquery-ui','location':'../../jquery-ui'},{'name':'yui','location':'../../yui'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dijit/form/Button",
  "dijit/Calendar",
  "dijit/form/TextBox",
  "dijit/layout/ContentPane",
  "dijit/layout/AccordionContainer",
  "dijit/layout/TabContainer"
]);
</script>
<style>@import "themes/claro/claro.css";@import "lib/dojo/dojo/resources/dojo.css";@import "lib/jquery-ui/css/smoothness/jquery-ui-1.8.11.custom.css";@import "lib/yui/calendar/assets/skins/sam/calendar.css";@import "app.css";
</style>
<script type="text/javascript" src="lib/jquery-ui/jquery-1.4.4.min.js"></script>
<script type="text/javascript" src="lib/jquery-ui/jquery-ui-1.8.11.custom.min.js"></script>
<script type="text/javascript" src="lib/yui/yahoo-dom-event/yahoo-dom-event.js"></script>
<script type="text/javascript" src="lib/yui/calendar/calendar-min.js"></script>
</head>
<body class="claro" dvFlowLayout="true" data-davinci-ws="collapse" id="myapp">
 <input type="button" data-dojo-type="dijit.form.Button" intermediateChanges="false" label="Button" iconClass="dijitNoIcon"></input>
 <input data-dojo-type="dijit.Calendar"></input>
 <input type="text" data-dojo-type="dijit.form.TextBox"></input>
 <img src="SampleBanner.jpg"></img>
 <div></div>
<span></span>
<label>
 Label</label>
<div dvwidget="jquery.ui.button">
 <button id="widget_1957">
   Button</button>
 <script>$("#widget_1957").button();</script>
</div>
<div dvwidget="jquery.ui.datepicker">
 <input id="widget_77_datepicker" type="text"></input>
 <script>$('#widget_77_datepicker').datepicker();</script>
</div>
<div dvwidget="YAHOO.widget.Calendar">
 <div class="yui-skin-sam" id="widget_1268cal1Container"></div>
 <script>(new YAHOO.widget.Calendar('widget_1268cal1Container')).render();</script>
</div>
<div data-dojo-type="dijit.layout.ContentPane" title="Pane" doLayout="false" style="width: 250px; height: 250px;"></div>
<span data-dojo-type="dijit.layout.AccordionContainer" style="width: 300px; height: 300px; min-width:1em; min-height:1em;">
<div data-dojo-type="dijit.layout.ContentPane" title="Pane 1" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" selected="selected" closable="false" style="width: 274px; height: 224px;" doLayout="false">
</div>
<div data-dojo-type="dijit.layout.ContentPane" title="Pane 2" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" selected="selected" closable="false" style="width: 274px; height: 224px;" doLayout="false"></div>
</span>
<span data-dojo-type="dijit.layout.TabContainer" style="width: 300px; height: 300px; min-width:1em; min-height:1em;" controllerWidget="dijit.layout.TabController">
<div data-dojo-type="dijit.layout.ContentPane" title="Tab 1" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" selected="selected" closable="false" style="width: 282px; height: 253px;" doLayout="false">
</div>
<div data-dojo-type="dijit.layout.ContentPane" title="Tab 2" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" selected="selected" closable="false" style="width: 282px; height: 253px;" doLayout="false"></div>
</span></body>
</html>
```

**Comment by aerwin** [comment]
Also, if I scroll to the top with this same file and drag the DIV over the top half of the document, I don't really see these sorts of issues

**Comment by aerwin** [comment]
Also, as I play with it some more, I see if I drop a DIV into the accordion and then try to drop widgets into the DIV that the drop indicator is off. E.g., in the screen shot below, note the ghosted "TextBox" flyover hanging out at the bottom of the canvas, well below the DIV I'm trying to drop the TextBox into.

![Screenshot](http://i.imgur.com/dKUGH.png)

**Comment by jhpedemonte** [comment]
-> M7 for now.

We have a bug or two already open about this, I believe.  Please search and see if you can dupe this bug to that one (or vice-versa, since you have a lot of details in this one).

**Comment by JonFerraiolo** [comment]
I played with this some and have concluded this is a must-fix. The visual editor is getting in good shape and this particular scenario, while not super commonplace, is still a common-enough problem that we should try to fix.

I expect there are some math bugs around widget location.

**Comment by JonFerraiolo** [comment]
Looks like this is a Firefox-only bug. Not seeing this with Chrome.
