### ISSUE TITLE
Subwidget theming: Can't modify Tabbed Pane Subwidgets

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2298]
Using FF on Mac...
1. Clone theme
2. Select any of the Tabbed Pane subwidgets
3. Try to change background or font and nothing happens

**Comment by billreed63** [comment]
try to set the tab font color

**Comment by aerwin** [comment]
No, I just tried again and it failed. Font color was one of the font properties I had tried originally.

**Comment by aerwin** [comment]
Also, this time tried Chrome on Mac.

**Comment by billreed63** [comment]
sorry, that was a quick note to remind me what was broken...
