### ISSUE TITLE
Theme editor writes out deltas

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#23]
Right now, to do theme editor, a user first clones one of the standard themes
(e.g., claro) and then brings up the theme editor to change the CSS files in
the clone.

I'm wondering if instead of changing the theme CSS files, it might be better to
store incremental CSS style rules into a delta CSS file that contains overrides
to the base theme. 

Any instant reactions to this idea? My instincts are that this is a better
approach and what we should have been doing from the beginning, but I still
need to think things through from a user perspective. From an implementation
perspective, one reason for optimism that a delta approach is achievable is
that we funnel all property palette changes into a small number of style
modification commands in order to hook into the undo system. Therefore, maybe
the code changes would be isolated into only a few places. (???)

One concern:  what if the base theme changes, say due to an upgrade?  This may
cause issues if all that was saved was the delta.

**Comment by jhpedemonte** [comment]
-> M6

Is this something we still want to do, or should this be closed?

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
Yes, definitely something we still want to do. Whether we can do it for M6, well, we shall see...

**Comment by billreed63** [comment]
Do we still want to copy the theme to the users workspace and allow the user to chose between modifying the theme or adding a new rule, or should we just find the rule in the base theme and create a new rule in the delta file?

**Comment by JonFerraiolo** [comment]
The ideal scenario would be that "claro2" (derivative of claro) would consist of:
- claro2.theme
- claro2.css, which contains an @import for claro.css (which is preserved intact), and override rules over claro

If a user then creates a claro3 that is derivative of claro2, then claro3 would consist of
- claro3.theme
- claro3.css, which contains an @import for claro2.css, and override rules over claro2

However, I don't know if this vision is viable from an implementation perspective. I wouldn't be surprised if your response is that this approach is too difficult or otherwise isn't a good workflow for users.

**Comment by billreed63** [comment]
I have the theme editor writing out delta's for Mobile and Desktop themes, but this presents us with the next UI issue to address. 

In the page editor when the user selects a widget and opens the cascade on a style property we display the rules. In the past if the selected rule in the cascade was read only we would display an error message. The message would tell the user to create a new theme or use app.css. 

With delta themes the user can be using a custom theme that uses delta's and the rule for the existing property may not have been overridden in the delta. 

If the rule has been overridden in the delta, but the specific property has not, the user can select the rule for the delta css file and add the override property.

In the case that the rule has not been overridden yet and is therefore missing from the cascade we must add the rule to allow the user to select the override rule and add it to the delta.css

What is the rule is from anther delta css file from another theme, do we let the user change it?

**Comment by billreed63** [comment]
Still need to test delta inherit from delta theme and delta on preview 5 cloned theme...

**Comment by billreed63** [comment]
done
