### ISSUE TITLE
Review all ve uses of _Widget.getMarginBox

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2303]
There might be bugs...

Seems to be used by MoveCommand and SmartInput

**Comment by jhpedemonte** [comment]
What exactly are you looking for?  What needs to be reviewed?

**Comment by JonFerraiolo** [comment]
I want to do a code scan to see if I see any bugs in the logic. As I was fixing various geometry math bugs over the past week, I noticed that there was some erroneous math logic around dealing with margins.
