### ISSUE TITLE
Cannot set more than one widget-specific property on HTML elements

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2309]
This is a spin-off of #2002 ("AUDIO and IMG tags unusable if click ok on smart input dialog without choosing file"). It was recently observed that the issue in #2002 has  worsened. In investigating, I believe a new much more serious and pervasive problem exists that's entirely separate from the core issue of #2002 (sizing of audio control when no src file specified).

Basically, it looks like for **all** HTML widgets that setting a widget-specific property wipes out all other property settings for that widget. This essentially means the user can only have one widget-specific property set at a time.

To reproduce:
1. Create new HTML file
2. Drop HTML widget onto page (say BUTTON)
3. With button selected, open widget-specific properties
4. Set a property (e.g., check the "autofocus" checkbox)
5. Set another property (e.g., check the "disabled" checkbox) and note "autofocus" from last step becomes unchecked
6. Enter a value in the "name" field and see "disabled" from last step becomes unchecked

**Comment by jhpedemonte** [comment]
-> @doronrosenberg, who may have some spare cycles.

@JonFerraiolo

**Comment by aerwin** [comment]
I've spent a little time setting breakpoints and such. So, maybe I should take this. -> @aerwin

**Comment by aerwin** [comment]
Marking fixed with above commit.
