### ISSUE TITLE
Properties palette: why don't widget-specific and event fields go to right edge?

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#231]
Both the widget-specific and event sections of the properties palette show
extra space along the right edge. Instead, I would expect that the input fields
in those two sections would go all the way to the right edge of the properties
palette. Is there a reason why these two sections don't push their fields all
the way to the right edge? I could see why widget-specific fields might include
numeric values and therefore might get the +/- chrome, but events will never
get the +/- chrome.

bug: 6294

**Comment by JonFerraiolo** [comment]
@doronrosenberg: can we close this issue now?

**Comment by JonFerraiolo** [comment]
Closing. This has been fixed.
