### ISSUE TITLE
Can not open html files

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2310]
I can't open any files on test machine

**Comment by jhpedemonte** [comment]
Which test machine?

**Comment by billreed63** [comment]
macwayne2

**Comment by jhpedemonte** [comment]
Please retry with latest build; after migration.

**Comment by jhpedemonte** [comment]
-> @JonFerraiolo, since I'll be out.  Awaiting confirmation from @billreed63 that this still happens.

**Comment by JonFerraiolo** [comment]
@billreed63 - you still having this problem?

**Comment by billreed63** [comment]
no
