### ISSUE TITLE
Exception when two HTML editors open on FF

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2311]
Have to html files open the active editor is the second tab
Refresh the browser, throws exception. 

s is null

Line 15

**Comment by jhpedemonte** [comment]
cc @JonFerraiolo @peller

**Comment by peller** [comment]
note: exception is only seen with FB (may need to explicitly catch on throw?)

**Comment by peller** [comment]
Seems to be taking measurements on a node not yet added to the DOM

-> @JonFerraiolo 

getMarginExtents(node=span#span_1.HtmlWidget, _318=undefined)
getMarginBoxPageCoords()
withDoc(_468=Document /maqetta/, _469=function(), _46a=undefined, _46b=undefined)
getMarginBoxPageCoords(node=span#span_1.HtmlWidget)
updateFocus(_210f=Object { domNode=span#span_1.HtmlWidget, id="span_1", type="html.span", more...}, index=0, _2110=undefined)
updateFocusAll()
(?)()

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo I think I know how to fix
