### ISSUE TITLE
Vertical slider 404 in preview

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2314]
1) DnD vertical slider 
2) Preview
in console see

"NetworkError: 404 Not Found - http://macwayne2.austin.ibm.com:55556/maqetta/user/_Guest_1337260304177/ws/workspace/project1/themes/claro/form/images/sliderThumbs.png"

**Comment by jhpedemonte** [comment]
see #2212

-> @aerwin

**Comment by aerwin** [comment]
@jhpedemonte @peller @billreed63 

Looks like @peller fixed #2212 by changing case of filename. However, it looks to me that the 

maqetta/themes/claro/form/images directory is generally pretty out of sync with the dojo/dijit/themes/claro/form/images/directory. Who's responsible for keeping maqetta themes in line with Dojo?

**Comment by aerwin** [comment]
per scrum... -> @billreed63
