### ISSUE TITLE
404 when preview dojo.tree

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2315]
1) DnD tree
2) preview
in console

"NetworkError: 404 Not Found - http://macwayne2.austin.ibm.com:55556/maqetta/user/_Guest_1337260304177/ws/workspace/project1/icons/images/commonIconsObjActEnabled.png"

**Comment by jhpedemonte** [comment]
-> @doronrosenberg

**Comment by jhpedemonte** [comment]
See #2314, particularly [this comment](https://github.com/maqetta/maqetta/issues/2314#issuecomment-5765631) -- may be an issue with an out-of-date theme directory.

**Comment by JonFerraiolo** [comment]
Closing. I don't see the 404 with latest code.
