### ISSUE TITLE
HTML audio and video tag does not work

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2316]
Format of the audio tag is incorrect
When a audio tag is added to page the following syntax is added

```
 <audio src="Arizona__Fight_Wildcats_Fight.mp3">
</audio>
```

Which is incorrect the correct syntax is http://www.w3schools.com/html5/tag_audio.asp

```
<audio controls="controls">
  <source src="song.ogg" type="audio/ogg" />
  <source src="Arizona__Fight_Wildcats_Fight.mp3" type="audio/mp3" />
  Your browser does not support the audio tag.
</audio>
```

```

<video src="Maqetta Getting Started.mp4"></video>
```

correct syntax is  http://www.w3schools.com/html5/html5_video.asp

```
<video width="320" height="240" controls="controls">
  <source src="MaqettaGettingStarted.mp4" type="video/mp4" />
  Your browser does not support the video tag.
</video>
```

**Comment by aerwin** [comment]
Dup of #2002 & #2309..

**Comment by aerwin** [comment]
There was some question on the scrum if using `src` was correct, as shown in http://www.w3schools.com/html5/tag_audio.asp (one of the URL's referenced above by @billreed63 ), `src` is one of the valid attributes. There is #1761 open from awhile back to develop smart input for managing TRACK/SOURCE elements.

**Comment by aerwin** [comment]
one other thing on this, to verify `src` works, here are some instructions I sent a user on our Maqetta forum a couple days ago:
1. Create new HTML file 
2. Drag and drop audio element 
3. Choose an audio file (that you've previously uploaded to workspace) 
   or enter URL (e.g., http://www.w3schools.com/html5/song.mp3) in the 
   file dialog 
4. At this point #2002 will occur, but the audio element should still 
   be selected 
5. Go into widget-specific properties in the properties palette and 
   check the "controls" attribute. This should cause the play, stop, etc. 
   buttons to show so you can play the sound when you preview the page.
