### ISSUE TITLE
clip art chat has extra line in selection box

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2317]
The chat clip art widget has a line in the middle of the selection window that gives the user they can resize the pointer

**Comment by billreed63** [comment]
video bug, it is intermittent on FF

**Comment by billreed63** [comment]
it may be do to the debug window open and scroll bars on the canvas...

**Comment by JonFerraiolo** [comment]
I haven't been able to reproduce this after numerous attempts. Pushing to M7.

**Comment by billreed63** [comment]
I think this is just a video bug, when the debugger is open and the widget is half below the visible  screen
