### ISSUE TITLE
GridX loading errors with todays builds

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2321]
This was working well with a build from this morning (~1am central).  But with today's later builds, GridX loading fails:

```
GET http://host:55556/maqetta/app/dojo/metadata/dojo/1.7/dijit/layout/ContainerInput.js?defb96fcb8e4aec1a5baae7b1458fbf03629aca4 404 (ProxyServlet: /maqetta/app/dojo/metadata/dojo/1.7/dijit/layout/ContainerInput.js) dojo.js:928
GET http://host:55556/maqetta/app/dojo/static/lib/gridx/1.0/resources/claro/Gridx.css?defb96fcb8e4aec1a5baae7b1458fbf03629aca4 404 (ProxyServlet: /maqetta/app/dojo/static/lib/gridx/1.0/resources/claro/Gridx.css) dojo.js:4312
GET http://host:55556/maqetta/app/dojo/static/lib/gridx/1.0/resources/claro/Gridx_rtl.css?defb96fcb8e4aec1a5baae7b1458fbf03629aca4 404 (ProxyServlet: /maqetta/app/dojo/static/lib/gridx/1.0/resources/claro/Gridx_rtl.css) dojo.js:4312
GET http://host:55556/maqetta/app/dojo/static/lib/gridx/1.0/Grid.js?defb96fcb8e4aec1a5baae7b1458fbf03629aca4 404 (ProxyServlet: /maqetta/app/dojo/static/lib/gridx/1.0/Grid.js) dojo.js:928
GET http://host:55556/maqetta/app/dojo/static/lib/gridx/1.0/core/model/cache/Async.js?defb96fcb8e4aec1a5baae7b1458fbf03629aca4 404 (ProxyServlet: /maqetta/app/dojo/static/lib/gridx/1.0/core/model/cache/Async.js) dojo.js:928
GET http://host:55556/maqetta/app/dojo/static/lib/gridx/1.0/modules/extendedSelect/Column.js?defb96fcb8e4aec1a5baae7b1458fbf03629aca4 404 (ProxyServlet: /maqetta/app/dojo/static/lib/gridx/1.0/modules/extendedSelect/Column.js) dojo.js:928
GET http://host:55556/maqetta/app/dojo/static/lib/gridx/1.0/modules/move/Column.js?defb96fcb8e4aec1a5baae7b1458fbf03629aca4 404 (ProxyServlet: /maqetta/app/dojo/static/lib/gridx/1.0/modules/move/Column.js) dojo.js:928
GET http://host:55556/maqetta/app/dojo/static/lib/gridx/1.0/modules/dnd/Column.js?defb96fcb8e4aec1a5baae7b1458fbf03629aca4 404 (ProxyServlet: /maqetta/app/dojo/static/lib/gridx/1.0/modules/dnd/Column.js) dojo.js:928
GET http://host:55556/maqetta/app/dojo/static/lib/gridx/1.0/modules/ColumnResizer.js?defb96fcb8e4aec1a5baae7b1458fbf03629aca4 404 (ProxyServlet: /maqetta/app/dojo/static/lib/gridx/1.0/modules/ColumnResizer.js) dojo.js:928
GET http://host:55556/maqetta/app/dojo/metadata/dojo/1.7/dojox/grid/DataGridInput.js?defb96fcb8e4aec1a5baae7b1458fbf03629aca4 404 (ProxyServlet: /maqetta/app/dojo/metadata/dojo/1.7/dojox/grid/DataGridInput.js) dojo.js:928
```

The main commit I'm worried about is @aerwin's update of the submodule for the GridX code.  Not sure why that would break the builds, though.

(Note: only seems to affect builds)

@JonFerraiolo

**Comment by jhpedemonte** [comment]
Perhaps related to #2068?  Need to do a `git submodule update` in the build scripts?

**Comment by aerwin** [comment]
I think this is a different part of the issues surrounding #2067 rather than a submodule issue. E.g., I can fix the first error by changing the reference to "../../metadata/dojo/1.7/dijit/layout/ContainerInput" to "maq-metadata-dojo/dijit/layout/ContainerInput" in `GridWizardInput`.

But, the other references look like this (from `GridWizardPreviewPane`):

```
"../../static/lib/gridx/1.0/Grid",
    "../../static/lib/gridx/1.0/core/model/cache/Async",  
    "../../static/lib/gridx/1.0/modules/extendedSelect/Column",
    "../../static/lib/gridx/1.0/modules/move/Column",
    "../../static/lib/gridx/1.0/modules/dnd/Column",
    "../../static/lib/gridx/1.0/modules/ColumnResizer",
    "davinci/css!../../static/lib/gridx/1.0/resources/claro/Gridx.css",
    "davinci/css!../../static/lib/gridx/1.0/resources/claro/Gridx_rtl.css",
```

I'm thinking perhaps we need `maq-lib-gridx` alias to go along with the new `maq-metadata-gridx` alias? Sending back to @jhpedemonte for consideration/discussion.

**Comment by jhpedemonte** [comment]
(adding @childsb, the resource URL guru and @peller, the AMD guru)

Not exactly sure what you're trying to do with those URLs.  Can't you just do something like `require([gridx/Grid])`?

**Comment by aerwin** [comment]
sorry... yeah, those don't make much sense without the whole context:

```
define(
[
    "dojo/_base/declare",
    "dijit/_WidgetBase",
    "dijit/_TemplatedMixin",
    "dijit/_WidgetsInTemplateMixin",
    "dijit/layout/ContentPane",
    "dijit/layout/BorderContainer",
    "dijit/form/TextBox",
    "dijit/form/ValidationTextBox",
    "dijit/form/Button",
    "dojo/data/ItemFileReadStore",
    "./GridWizardPanel",
    "../../static/lib/gridx/1.0/Grid",
    "../../static/lib/gridx/1.0/core/model/cache/Async",  
    "../../static/lib/gridx/1.0/modules/extendedSelect/Column",
    "../../static/lib/gridx/1.0/modules/move/Column",
    "../../static/lib/gridx/1.0/modules/dnd/Column",
    "../../static/lib/gridx/1.0/modules/ColumnResizer",
    "davinci/css!../../static/lib/gridx/1.0/resources/claro/Gridx.css",
    "davinci/css!../../static/lib/gridx/1.0/resources/claro/Gridx_rtl.css",
    "dojo/i18n!./nls/gridx",
    "dojo/text!./templates/gridWizardPreview.html"
],
function(declare,
        _WidgetBase, 
        _TemplatedMixin, 
        _WidgetsInTemplateMixin, 
        ContentPane, 
        BorderContainer,
        TextBox,
        ValidationTextBox,
        Button,
        ItemFileReadStore,
        GridWizardPanel,
        Grid, 
        Cache,
        SelectColumn,
        MoveColumn,
        DndColumn, 
        ColumnResizer,
        GridXCSS,
        GridXRTL,
        gridxNls,
        templateString) {
```

**Comment by aerwin** [comment]
And, when I try "gridx/Grid" I get the following in the console:

GET http://localhost:8081/maqetta/app/gridx/Grid.js?@revision@ 404 (ProxyServlet: /maqetta/app/gridx/Grid.js)

**Comment by peller** [comment]
I'm a bit surprised those relative paths work at all, given that they go outside the specified package root.  Should we be registering the gridx library as a package?

**Comment by jhpedemonte** [comment]
So here we are trying to use the GridX library files in the app/runtime context.  Is that right?  Normally, we would just be using it in the VE context/iframe.

If that is indeed what we want, then we should register it as a package in the runtime, so that we can use the module **"gridx/Grid"**, etc...

**Comment by aerwin** [comment]
That is what we want (using in runtime context), but currently GridX is only used within the GridX plugin? Do we really want to register it globally? Of course, I guess that's kind of equivalent to my request for a `maq-lib-gridx` alias (though I had envisioned that the latter be built dynamically from the plugin metadata like `maq-metadata-dojo` is).

**Comment by peller** [comment]
You can register it dynamically using a require({}) command with the [config information](http://dojotoolkit.org/reference-guide/1.7/loader/amd.html#id5) in the brackets.  I think that's what you want.

**Comment by aerwin** [comment]
Right... I guess what I'm getting at is @jhpedemonte recently added these lines to `metadata` to dynamically build `maq-metadata-dojo`, etc.:

```
// Register a module identifier for the metadata path; necessary for
        // loading of helper and creation tool classes.
        pkg.$moduleId = 'maq-metadata-' + pkg.name;

        require = require({
            packages: [{
                name: pkg.$moduleId,
                location: new Path(location.href).append(path).toString()
            }]
        });
```

So, when I requested a `maq-lib-gridx` alias, I had expected it would be built in a similar way. E.g., 

```
        pkg.$libId = 'maq-lib-' + pkg.name;

        require = require({
            packages: [{
                name: pkg.$libId,
                location: [something specific for the lib path based on "directories" metadata in file]
            }]
        });
```

So, I guess the question is do we do that so throughout the code base we can say "maqetta-lib-gridx/Grid" or we register it so we can use "gridx/Grid" throughout the code base?
