### ISSUE TITLE
maq-metadata-dojo-1-7 ???

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2323]
@childsb 

When testing on macwayne2, I see this error message in console:

```
/maqetta/app/dojo/maq-metadata-dojo-1.7/dojox/mobile/ThemeHelper.js) dojo.js:928
```

which is the wrong URL. I believe it should be this instead:

```
/maqetta/app/metadata/dojo/1.7/dojox/mobile/ThemeHelper.js
```

grep'ing through source code I see:

```
davinci.dojo_1_7/WebContent/maqetta/themes/android/android.theme:1:..."helper":"maq-metadata-dojo-1.7/dojox/mobile/ThemeHelper"...
davinci.dojo_1_7/WebContent/maqetta/themes/blackberry/blackberry.theme:1:..."helper":"maq-metadata-dojo-1.7/dojox/mobile/ThemeHelper"...
davinci.dojo_1_7/WebContent/maqetta/themes/custom/custom.theme:1:..."helper":"maq-metadata-dojo-1.7/dojox/mobile/ThemeHelper"...
davinci.dojo_1_7/WebContent/maqetta/themes/ipad/ipad.theme:1:..."helper":"maq-metadata-dojo-1.7/dojox/mobile/ThemeHelper"...
davinci.dojo_1_7/WebContent/maqetta/themes/iphone/iphone.theme:1:..."helper":"maq-metadata-dojo-1.7/dojox/mobile/ThemeHelper"...
maqetta.core.client/WebContent/davinci/Theme.js:357:        "helper": "maq-metadata-dojo-1.7/dojox/mobile/ThemeHelper",
maqetta.core.client/WebContent/davinci/ve/metadata.js:206:        pkg.$moduleId = 'maq-metadata-' + pkg.name + '-' + pkg.version;
```

Is there server supposed to be doing magic to create URL named `maq-metadata-...`, or are all of the above files incorrectly referring to `maq-maqetta-..`?

**Comment by aerwin** [comment]
@jhpedemonte added maq-metadata-dojo stuff for #2067.

**Comment by jhpedemonte** [comment]
So I changed **metadata.js:206** (as shown in the log above) to not use the version any more.  See discussion in #2067.

I didn't know this was being used elsewhere.  Fix is to change `maq-metadata-dojo-1.7` to `maq-metadata-dojo`.

I see that it's also in the ***.theme** files.  If we make this change, will this be a **migration issue**?

---

While I prefer making the change as indicated, if it's too much of a hassle/too risky, we can define both `maq-metadata-dojo-1.7` and `maq-metadata-dojo` for now, removing the former for v1.0.

**Comment by childsb** [comment]
there will be a migration issue.  we'll have to replace that string in all the .theme files (referenced helpers).

on another note, why did we kill the version string in the static mapping?  if we're running multiple versions of dojo on a server, this will cause problems..

**Comment by JonFerraiolo** [comment]
I would say wipe out all user themes as part of migration. ("wipe out" = rename or move files so that the themes are still there for user to download, but made such that M6 doesn't recognize the old themes). We've wiped custom themes in past migrations.

**Comment by jhpedemonte** [comment]
After discussion with @childsb, decided to revert previous change and add version string back into package namespace.  Not having a version string could lead to issues -- for example, the GridX wizard code inherits from helpers in the Dojo 1.7 library.  Those files may change in the Dojo 1.8 library, causing GridX wizard to break.  Can't assume that it will work.
