### ISSUE TITLE
SmartInput problems with Accordion

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2325]
@doronrosenberg, @childsb, @peller, @aerwin 

With Preview5, if you double-click on first title pane of an Accordion, up comes SmartInput, but with latest code, if you double-click on first title pane, SmartInput appears momentarily and then disappears.

Assigned to @billreed63 initially as the SmartInput-meister, but maybe others can help. This bug might be the result of my various changes to SelectTool and Focus, so I might end up grabbing this.

**Comment by billreed63** [comment]
dijit/focus._onBlurNode is setting a setTimeout to deal with OnBlur events.

```
           // if the blur event isn't followed by a focus event then mark all widgets as inactive.
            if(this._clearActiveWidgetsTimer){
                clearTimeout(this._clearActiveWidgetsTimer);
            }
            this._clearActiveWidgetsTimer = setTimeout(lang.hitch(this, function(){
                delete this._clearActiveWidgetsTimer;
                this._setStack([]);
                this.prevNode = null;
            }), 100);
```

SmartInput is setting the focus on the smart input widget box so when the dijit.focus setTimeout fires the `_setStack` changes the focus, firing SmartInputs onBlur closing the edit box. This only seems to be an issue for SackContainerInput and mostly for Accordion  So I added the timeout wait until after the diji.focus has fired, there must be a better solution than this!
