### ISSUE TITLE
New HTML iterates through theme directory, loads all themes

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2327]
Results in n*2 HTTP calls, plus a findResource, even though only one theme is used in the document

@billreed63 remind me what's needed here. @childsb perhaps we ought to invent a new REST API to get what's needed

**Comment by billreed63** [comment]
We need to find the theme so we know the location of the CSS files,  The user can choose a theme in the New HTML dialog. what is passed to the open editor is just the theme name so the CSS files for the theme need to be found. But the themes should be cached in the library.getThemes

**Comment by billreed63** [comment]
Changes have been made in the code to cache the themes. The only time I am seeing a find resource on a page create is the very first page that is load that has that theme. Or when the user selects teh "theme" button from the new html file create. 

If the use is using a previously load theme then we do not do a network findResource.
