### ISSUE TITLE
Properties palette and Cascade for theme editor

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2328]
The theme editor is now implemented to leverage cascading to override values from the inherited theme
use the user creates a new theme called myclaro which inherits from claro. 

If the user wants to change a value of claro they are in effect creating an override rule that is placed in myclaro.css

an example would be the user wants to remove the background-image on a button the use would chose the 'none' value for background-image and a rule would be added to myclaro.css. If the user changes their mind and want to restore the button to the inherited theme behavior (back to claro) the user would then select the background-image and remove the 'none' value. The would remove the background-image property from the rule in myclaro.css.

The issue that we need to address is that we have no visual indication in the properties palette are changeable for any given widget or what css rule that value come from.

We have a long standing open issue that the properties palette should only display properties that are value for that widget #226.
Currently we populate only properties in the property palette that the user can change, the issue with this approach is that the user has no visual indication of the rules origin. Is it from the base theme or the delta theme. If it is the base they must override if ti is from the delta they can remove. 

We could include the cascade like we do in page editor, but again we need to make some change to the cascade. to let the user know they can't chose a rule they are informative only.

**Comment by JonFerraiolo** [comment]
See #2398

**Comment by JonFerraiolo** [comment]
(Copying text from #2927, which is now closed as a dupe)

@billreed63 @childsb @jhpedemonte

One of the unintended side effects of the big UI makeover is that the cascade view is available now in the theme editor. (The right arrow is not hidden in the theme arrow.) @JonFerraiolo needs to think about this. Two options:
1. Disallow the cascade in the theme editor (like we had for previous releases)
2. Enable the cascade in the theme editor as a read-only view. That would probably means graying out the text and hiding the radio buttons.

**Comment by jhpedemonte** [comment]
Go with (1).  Displaying a disabled interface will make the user think that there is something that can be done to enable it, but that's not the case in the theme editor (right?).

**Comment by billreed63** [comment]
We just need to put the `davinci_ve_ThemeEditor` class back on the tab container whenever the theme editor is active.
Previous to the UI make over the tab container for the style had an `id=davinci.ve.style` and the code would grab that id and add or remove the class  based on the displayed editor.

**Comment by billreed63** [comment]
the cascade is hidden by these rules in propview.css

```
.davinci_ve_ThemeEditor .showCss.propertyButton{

    display:none;   

}

.davinci_ve_ThemeEditor .cssCascadeSection{
    display:none;   
}
```
