### ISSUE TITLE
Source editor selection is broken

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2330]
@jhpedemonte @JonFerraiolo 

Source selection is right now broken badly - never works in Firefox, somewhat works in Chrome only in split view and even then can be easily broken.

This is all because there is no iframe anymore for the orion editor.  This means focus issues which won't show the selection unless you focus the orion editor.  Setting focus to the editor each time we select is not a viable solution obviously.

I think the best solution would be to have orion style the selection itself rather than relying on the the html5 selection code.  Not sure how feasible that is though.

**Comment by jhpedemonte** [comment]
Assigning to @peller for now.  Not sure if recent commits have helped this issue.

**Comment by peller** [comment]
silenio put in the behavior that @doronrosenberg requested, such that the selection is faked on blur and restored on focus.  merged in d006ad0b30587e7f878faa6bd4839ab1fa08f30c
