### ISSUE TITLE
Exception on file close in ThemeModifier.js

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2331]
I got a null reference exception when closing a theme editor at ThemeModifier.js:22:

```
for(var i = 0;i<this.themeCssfiles.length;i++){
```

where this.themeCss is undefined. I don't know this code, so I'm not sure if we can just add if `if` check before attempting the loop to make sure `this.themeCssfiles` has a value.

One thing that is suspicious: i wonder if there are typo's in the code due to inconsistent capitalization. Note that there are some uses of themeCssfiles where the 'f' is lowercase and other times where the 'F' is uppercase:

```
$ grep -rni themeCssfiles * | grep -v themeCssfiles
library.js:103: var themeCssFiles = theme.files.filter(function(file) {
library.js:115:     css: themeCssFiles,
ve/Context.js:892:              subs.themeCssFiles = '' +
ve/newfile.template.html:24:        {themeCssFiles}
```

**Comment by billreed63** [comment]
I could not reproduce the exception, but change all themeCssfiles -> themeCssFiles
