### ISSUE TITLE
never logged out of macwayne2

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#2333]
i signed in with tonys ID a few days ago,

after a few restarts and redeploys on the macwayne2 server, i'm still logged in as tony.

i haven't explicitly logged out, but shouldn't the restart of the server forced me to log back in?

**Comment by JonFerraiolo** [comment]
I suspect that the macwayne2 version of Joomla doesn't have session timeouts in place. Just a guess.

**Comment by childsb** [comment]
CCin @JonFerraiolo @peller per @jhpedemonte 

a little more on this bug--
i logged in as guest this morning to finish testing, and it brought up a review editor from the guest account i was testing with last night.  the editor showed a 500 error.

further investigating, the R&C editor was making a request for the old user id (who's workspace and snapshot no longer existed).  so i logged out, and logged back into joomla as childsb@us.ibm.com

as soon as the workspace came up, it tried to load the R&C editor from the old guest account and 500 error'ed out again.

Looking at the cookies, I dont see any cookie with the _Guest12301203 user in it:

maqExplorer=.%2Fproject1%2C.%2Fep1%2C.%2Fnull%2C.%2FregularProject1%2C.%2FregularProject1%2F.%2FregularProject1%2Ffolder1%2C.%2FeclipseProject3%2C.%2FeclipseProject3%2F.%2FeclipseProject3%2FWebContent%2C.%2Fnewproject%2C.%2Fproject1%2F.%2Fproject1%2Fthemes%2C.%2Fproject1%2F.%2Fproject1%2Fthemes%2F.%2Fproject1%2Fthemes%2Ftonytheme2%2C.%2Fmyproject%2C.%2Ftest1%2C.%2Ffff; undefined=myapp; UnicaNIODID=kdUclklBOVn-XhB3N1r; 36f366e2d5028d985d1755a0d7e29be1=4bab66eb2fe1717fe22182a10d7a57c1; JSESSIONID=7witjepysbk41sp3qr7ksbnwm; MAQETTA.USER=childsb%40us.ibm.com; DAVINCI.JOOMLA=true

recreate:
1) click try-it on joomla
2) create a new review/add files/publish
3) open review from URL once emails fail
4) log out.
5) log back in as a real user (childsb@us.ibm.com/demo would work)
7) notice that the review editor for the guest account opens up.

**Comment by childsb** [comment]
@aerwin 

Some more info.....

This looks very related to R&C.....

As missing step #6 from above, if you open Sample1.html it will load properly from the childsb@us.ibm.com workspace.
