### ISSUE TITLE
selection chrome on YUI & JQuery widgets is wrong

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#2334]
The blue selection chrome for JQuery and YUI widgets isn't right.

1) New HTML file
2) DND YUI Calendar
3) Notice that the selection bar is one long blue line (and not a box around the calendar)

or

1) new html file
2) add a jquery button
3) select jquery button and notice that the selection box spans the entire canvas.

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte - Selection accurately reflects the bounds of the widget. We had the same problem in Preview 5 (and earlier, I would guess). I'll bet this gets pushed to M7.

**Comment by jhpedemonte** [comment]
I consider our existing YUI and jQuery widgets to be a failed experiment.  We need to remove them from v1.0.  Going forward, we'll only support widgets with a declarative markup (i.e jQuery Mobile).

Therefore, closing.
