### ISSUE TITLE
Download workspace exception on FF

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2336]
Attempted to download complete workspace  FF macwayn2

this.getDocumentElement() is undefined
addJavaScriptSrc(url="lib/dojo/dojo/dojo.js", _2170=true, _2171="dojo/dojo.js", _2172=true)davinc...bf39a23 (line 46820)
_2095(libId="dojo", src="dojo/dojo.js")davinc...bf39a23 (line 45319)
(?)(r=Object { type="javascript", src="dojo/dojo.js", $library="dojo"})davinc...bf39a23 (line 45338)
loadRequires(type="html.body", _208d=true, _208e=true, _208f=true)davinc...bf39a23 (line 45371)
rebuildSource(_1576=undefined, _1577=Object { elementType="File", name="file15.html", startOffset=0, more...})davinc...bf39a23 (line 27464)
_rewriteUrls()davinc...bf39a23 (line 17415)
okButton()davinc...bf39a23 (line 17432)
(?)()dojo.j...bf39a23 (line 4551)
(?)()dojo.j...bf39a23 (line 6092)
_onClick(e=click clientX=736, clientY=405)davinc...bf39a23 (line 31070)
_25e(args=[click clientX=736, clientY=405], a=undefined, f=function())dojo.j...bf39a23 (line 2636)
_onClick(e=click clientX=736, clientY=405)davinc...bf39a23 (line 53875)
(?)()dojo.j...bf39a23 (line 4551)
(?)(e=click clientX=736, clientY=405)dijit....bf39a23 (line 1936)
[Break On This Error]   

...ad"),_2176={async:true,parseOnLoad:true,packages:this._getLoaderPackages()},foun...

**Comment by peller** [comment]
wfm

**Comment by peller** [comment]
stack doesn't make sense... why would it rebuild the page for a download request?

**Comment by peller** [comment]
@jhpedemonte

**Comment by childsb** [comment]
RebuildSource is called for downloads in case the user remaps another lib so that the download will have proper mappings.

i looked at the file15.html that's causing the error and tried to reproduce but can't.  bill can't reproduce now either.

i'll leave open for m7 or until we can find a recreate.

**Comment by JonFerraiolo** [comment]
-> @aerwin - could you please test this issue to see if it still exists? If it does, then up to you - if you want to try to fix, great, otherwise send back to @childsb

**Comment by aerwin** [comment]
I see no exceptions. In addition, @billreed63 and @childsb also cannot reproduce (reported by @childsb 3 months ago). So, closing.
