### ISSUE TITLE
Test plan for SmartInput

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2340]
I discovered some simple SmartInput bugs in Preview 5 (see #2339), which shows we need a test plan for that feature, and need to run that test plan before shipping Preview 6.

**Comment by billreed63** [comment]
We really need to automate test cases,  SmartInput was working correctly for dojo WIdgets, but seems to be incorrect for html widget that used textContent for inline edit (I seem to remember that we were going to change them all to innerHtml).
At any rate we should combine this test case with the widget palette test case and automate to insure full coverage of all widgets.

**Comment by billreed63** [comment]
SmartInput can be very widget specific, do we want to combine SmartInput testing with Widget palette basic tests?

**Comment by JonFerraiolo** [comment]
> do we want to combine SmartInput testing with Widget palette basic tests?

That would be ok. Whatever you think is best.

**Comment by billreed63** [comment]
I have added smartInput testing to the Widget palette basic test cases. I am working on automating  the widget palette basic test cases but that is for M7
