### ISSUE TITLE
Claro them editor: can't change padding on TextBox

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2342]
- Clone claro
- Select TextBox
- In properties palette, enter "6px 6px" for padding (the shortcut)

Result=> Properties palette shows "1px 0" (the original value) instead of "6px 6px", but the screen is updated correctly.
- Save, close, reopen

Result=> Screen looks correct, but value shows "1px 0"

**Comment by billreed63** [comment]
The wrong rule is being selected by cascade.js

**Comment by billreed63** [comment]
fixed by 6435b25a69a4e3f74ad2aa8dc6113d8ea70a6c7b
