### ISSUE TITLE
Format of label change when changing ID

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2349]
1) New HTML
2) DnD label
3)Smart inpute enter `Label < b>bold</b>t test` choice the Plain text radio button
4)enter label_1 in the ID field for the box

Notice the label is now displayed with bold instead of ``Label < b>bold</b>t test`

**Comment by JonFerraiolo** [comment]
-> @billreed63 - can you look into this? If you don't have time, reassign back to me.

**Comment by billreed63** [comment]
When we get th ModifyCommand we retrieve the widget.getData in the case of html label the widget has a child
The child is the HTMLText element. We then call `getChildrenData(options);` In this case that would call
`HTMLWidget.getChildrenData(options)`   which calls `HTMLWidget._getChildrenData(options)`  
This has the following code 

```
        // Check if text node is the only child. If so, return text content as
        // the child data. We do this to match up with the code in
        // davinci.ve.widget.createWidget(), which can take child data either
        // as an array or as a string (representing the innerHTML of a node).
        if (domNode.childNodes.length === 1 && domNode.firstChild.nodeType === 3) {
            return getTextContent(domNode.firstChild);
        }
```

the `getTextContent` only preserves the escape elements if options.serialize true

```
function getTextContent(node) {
            var d = node.nodeValue.trim();
            if (d && options.serialize) {
                d = davinci.html.escapeXml(d);
            }
            return d;
        }
```

**Comment by billreed63** [comment]
I just noticed that if I have label<b>c</b>x when the label is when I change the id the bold c is dropped, that is a different issue #2355

**Comment by billreed63** [comment]
If I change the code in HTMLWidget so that the getTextContent always escapes the text this issue is resolved

```
function getTextContent(node) {
            var d = node.nodeValue.trim();
            if (d && options.serialize) {
                d = davinci.html.escapeXml(d);
            }
            return d;
        }
```

@JonFerraiolo who is the expert on this code, I worry about making this change so close to the release of preview 6
