### ISSUE TITLE
maqetta/* URL problems - downloaded pages don't work

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2351]
I downloaded my entire workspace, and then expanded the ZIP into my local web server. When I tried to open Sample1.html (via http://localhost/installdir/Sample1.html), the file doesn't show correctly and these messages appear in the console:

```
GET http://localhost/.../maqetta/space.js 404 (Not Found) 
GET http://localhost/.../maqetta/AppStates.js 404 (Not Found) 
```

**Comment by JonFerraiolo** [comment]
@peller - there seems to be a problem where some parts of the product think that the maqetta/\* files are in `<projectroot>/maqetta.*` and other parts think they are in `<projectroot>/lib/maqetta/*`.

**Comment by jhpedemonte** [comment]
Brad committed a fix to move the `maqetta` files under `lib`, by default.  Must have missed a few places during that change, which still point to paths without `lib` in them.

**Comment by JonFerraiolo** [comment]
What's weird is that, in the repository, Sample1.html shows maqetta library at `../../../maqetta/*` but when I open Sample1.html in the app and hit preview-in-browser, the view source shows maqetta library at `../../maqetta/*` (one fewer `../`. Maybe the page editor cleans up the module locations?

**Comment by JonFerraiolo** [comment]
@jhpedemonte - I think @peller recently changed the sample HTML files to add a 3rd `../`
