### ISSUE TITLE
Add migration script to generated zip file

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2352]
Not sure who knows the build the best: @childsb or @peller 

Need to add the migration scripts (at `/migration/m5-m6-migrate.sh` in the source) to the zip distributions.  I was thinking we could still keep it in the `migration` top-level directory.

**Comment by childsb** [comment]
i'd store it in the davinci.product/migration directory then copy it out of there with the rest of the *.sh and *.command files.

as a note, we've never included migration scripts....

**Comment by jhpedemonte** [comment]
New proposal: put link directly to GitHub (raw) file for migration script in the release notes, under a migration section.

-> @jhpedemonte

**Comment by peller** [comment]
could also just put in gist, as it's not something which needs to persist in our repository
