### ISSUE TITLE
Missing metadata for HTML elements 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2355]
1) create a new html file
2) DnD a div
3) dblclick on the div
4) type test<b>bold</b> element, and select the HTML radio
5) Add an id to the div from the properties palette

Notice that the word bold is removed from the div, because the `<b> and <i>` are missing from the metadata when the widget .getData is run to get the old data this nodes are skipped because the node._dvWidget is not set.

If I add metadata for `<b> and <i>` all is well..

**Comment by JonFerraiolo** [comment]
Seems to me we should add metadata for B, I, S, U, EM and STRONG, but set the hidden bit on so they don't appear in Widgets palette.
