### ISSUE TITLE
dojo.css not relocated

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2356]
@childsb @doronrosenberg 

Setting to Prio High just so this gets some attention.

If you relocate dojo (either via download action or via Modify Libraries), subsequent loading of HTML files (in page editor, preview in browser, or after download) results in error messages in console about dojo.css not found. 

Multiple things here. Do we really want to include dojo.css in user files anyway? See #2231, #71, but more importantly #2194

**Comment by JonFerraiolo** [comment]
@peller 

The sample files include @import dojo.css. Maybe we should remove that? (Haven't thought this through completely)

**Comment by peller** [comment]
Apparently we have a choice of using ( dojo.css or claro/document.css ) + claro/claro.css, but document.css + claro.css is considered more proper.  The extra file is necessary as a baseline.  Not sure how long it's been this way. I guess we'd need to make sure all of our themes conformed before switching to this pattern.
