### ISSUE TITLE
Intermittent problems in Firefox

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2359]
Need to pound on these area:

FF/Win running a release off of a server:

I got repeated Firefox compile-and-go console message after playing around with changing visibility on widgets in outline palette, saving, opening, and attempting to click on eyeball again.

One time I got a message upon trying to open context menu in outline palette.

**Comment by doronrosenberg** [comment]
Running into this as well

**Comment by doronrosenberg** [comment]
Having trouble reproducing this today

**Comment by jhpedemonte** [comment]
-> M7

**Comment by jhpedemonte** [comment]
@JonFerraiolo, have you run into these issues with latest code?

**Comment by JonFerraiolo** [comment]
Closing - I ran Win/FF for the last 2 testing cycles running off of a slow server, and did not see the above messages.
