### ISSUE TITLE
Allow for multiple file selection with audio and video elements

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2363]
Given that Firefox doesn't support MP4 or MP3, people who use the HTML5 VIDEO and AUDIO elements need to specify at least 2 different content files. For example:

```
    <video controls>  
      <source src="foo.ogg" type="video/ogg">  
      <source src="foo.mp4" type="video/mp4">  
      Your browser does not support the <code>video</code> element.  
    </video>  
```

I think we need to enhance our dialogs for VIDEO and AUDIO elements.

**Comment by aerwin** [comment]
Agreed... but, closing as a dup of #1761 (which I raised severity of and moved into M7).
