### ISSUE TITLE
Mobile theme files do not display correctly in FF

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2365]
The mobile theme's do not display correctly in FF theme editor or  page editor. 

Example the back arrow head is missing on the header widget.

The reason for this is the  theme-compact.css files are not being added to the head, this is not needed for webkit but is required for FF

**Comment by jhpedemonte** [comment]
We require the module **dojox/mobile/compat**, which loads **dojox/mobile/_compat**, which states this,

```
    //      This module provides support for some of the CSS3 features to dojox.mobile
    //      for non-CSS3 browsers, such as IE or Firefox.
```

and this,

```
    //      This module also loads compatibility CSS files, which has -compat.css
    //      suffix. You can use either the <link> tag or @import to load theme
    //      CSS files. Then, this module searches for the loaded CSS files and loads
    //      compatibility CSS files. For example, if you load iphone.css in a page,
    //      this module automatically loads iphone-compat.css.
```

So it seems like it should already be handled for us, and should work just fine in FF.

**Comment by billreed63** [comment]
The code in dojox.mobile._compat.js only checks for and loads -compat.css files from the mobile/themes directory

```
var paths = dm.getCssPaths();
            for(var i = 0; i < paths.length; i++){
                var href = paths[i];
                if((href.match(dm.loadCompatPattern) || location.href.indexOf("mobile/tests/") !== -1) && href.indexOf("-compat.css") === -1){
                    var compatCss = href.substring(0, href.length-4)+"-compat.css";
                    dm.loadCss(compatCss);
                }

```

I think this is a bug in dojox.mobile the code should be something like, where the code uses the dm.loadedCssFiles to check and load -compats 

```
// look for compats for the loadedCss files
            for(var i = 0; i < dm.loadedCssFiles.length; i++){
                var href = dm.loadedCssFiles[i].href;
                if(href.indexOf("-compat.css") === -1){
                    var compatCss = href.substring(0, href.length-4)+"-compat.css";
                    dm.loadCss(compatCss);
                }
            }

```

@peller

**Comment by billreed63** [comment]
to get this to work with our delta themes this turned out to be way more work than I though..
I added a compatFiles to our mobile.theme files to point to the compat css files, it also required adding code to the theme helper to insert the compat-files in the head if we are running on a non webkit browser We still need to address how we allow users to change rules in the *-compat.css files.. #2372

I also had to make changes to dojox.mobile._compat that I still need to create a patch to submit to dojo for 1.8 #2373

**Comment by JonFerraiolo** [comment]
Reopening - see #2380 - but maybe we don't need 2 bugs for this issue.
