### ISSUE TITLE
UI default to proposed rule for delta themes in page edito

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#2369]
rcan't change background color w/custom theme,
1) clone claro ---> claro2
2) new html file
3) change theme to claro2
4) add a button
5) select button and try to change background color to red

you're prompted with "can't change value of read only theme dialog".

**Comment by billreed63** [comment]
We have switched to deltas, so the rule does not exists the first time the user attempts to change the color. The user has to open the cascade and select the proposed new rule, the new rule is added to the new theme css file.

**Comment by billreed63** [comment]
@JonFerraiolo  do we need to change the message to detail this new behavior?

**Comment by billreed63** [comment]
Fixed by #2725
