### ISSUE TITLE
dirty bit appears on untouched file

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2371]
Open Sample1.html
Wait for it to load.  Note that the editor tab does not show a "*" dirty bit
Reload the workbench by hitting the reload button on the browser
Sample1.html re-opens in an editor, but the "*" is there.  Trying to close it without any changes results in a warning.

**Comment by childsb** [comment]
The main cause of this was an auto save call that happened during the Context._setSource(..) madness.  The autosave happened before the init had finished causing the editor to mark dirty.

This erroneous autosave call was propping up another bug where dirty editors aren't being marked dirty on refresh.
