### ISSUE TITLE
Need a way to change *-compat.css files

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2372]
How are we going to handle theme changes for *-compat.css files

**Comment by billreed63** [comment]
I think we should create -moz css properties in the base css files for FF and leave the compat for IE witch we currently do not support

**Comment by billreed63** [comment]
William D. Reed: So do you now what the plan is for dojox.mobile on none webkit? 
3:39:03 PM: Adam L. Peller: on webkit?
3:39:54 PM: William D. Reed: no like right now the themes only have the -webkit prefix, what about -moz
3:40:08 PM: Adam L. Peller: ah
3:40:25 PM: Adam L. Peller: well, there's the compat layer. that's just js, right/
3:40:31 PM: Adam L. Peller: not sure they care about non-webkit
3:40:34 PM: Adam L. Peller: to be honest
3:42:07 PM: William D. Reed: yeah but that is heavy lots of bitmaps firefox has mobile browser so it seems like adding in the -moz would be better for that
3:42:44 PM: Adam L. Peller: but who uses it?
3:42:47 PM: William D. Reed: https://play.google.com/store/apps/details?id=org.mozilla.firefox
3:43:02 PM: Adam L. Peller: we could certainly ask...
3:43:12 PM: Adam L. Peller: christophe and the ilog team are running the show now
3:44:04 PM: William D. Reed: Well I do becouse the base browser on my system is way down level and I can't upgrade to chrome because it requires the lastest android version
3:44:26 PM: William D. Reed: So if I want html 5 I have to use FF mobile
3:45:46 PM: Adam L. Peller: what would the base browser be on an android system like that?  just some old chrome?
3:45:50 PM: Adam L. Peller: not html5-ish?
3:46:05 PM: Adam L. Peller: anyway, supporting "old" systems probably isn't a priority for them
3:46:21 PM: Adam L. Peller: but it's a fair point
3:46:22 PM: William D. Reed: yeah, I have android 2.3 and the browser is not the latest
3:46:37 PM: Adam L. Peller: and it's not good enough?
3:46:59 PM: Adam L. Peller: if FF is only going to penetrate the market to get on old phones… that's the opera strategy.
3:47:01 PM: Adam L. Peller: won't get them far
3:47:01 PM: William D. Reed: not to run page we generate...
3:47:38 PM: William D. Reed: well maybe it is but that is not that does not help the point I am pushing....
3:48:16 PM: Adam L. Peller: it's a fair point.  it's just that they've been able to get away thus far with only dealing with a single browser
3:48:32 PM: Adam L. Peller: and it might be hard to convince them that it's time to do anything different
3:48:38 PM: Adam L. Peller: but you're welcome to try :-)
3:48:44 PM: William D. Reed: We also have a problem in IBM if most of IBMers using Maqetta are running on FF they can not really develop mobile apps
3:49:20 PM: Adam L. Peller: right. mobile development on the desktop.  good use case, probably why they had to do the compat layer in the first place
3:49:34 PM: Adam L. Peller: …though we could just tell people to go get Chrome :-)
3:49:43 PM: William D. Reed: +1
3:49:45 PM: Adam L. Peller: certainly fair game to fire off a note. want me to?
3:50:02 PM: Adam L. Peller: though you're the one who actually has a smart phone… :-)
3:50:09 PM: Adam L. Peller: christophe jolif is the one to ask.  
3:50:17 PM: William D. Reed: Cool, thanks

**Comment by billreed63** [comment]
@JonFerraiolo @jhpedemonte 

->M8

**Comment by billreed63** [comment]
I have spent some time looking at the *-compat.css files for dojo 1.8.

The purpose of the Maqetta theme editor is to provide the user with a tool to make changes to a theme that will be reflected across all browsers, to support this we generate CSS Rules that would support this. So for example if the user where to change the dojox.mobile.Heading backgound color we would generate the following rule:

```
.mblHeading {
    background-image : -webkit-gradient(linear, left bottom, left top, from(#f6f6f6), to(#dededf));
    background-image : -o-linear-gradient(to top,#f6f6f6, #dededf);
    background-image : -ms-linear-gradient(to top,#f6f6f6, #dededf);
    background-image : -moz-linear-gradient(to top,#f6f6f6, #dededf);
    background-image : -webkit-linear-gradient(to top,#f6f6f6, #dededf);
    background-image : linear-gradient(to top,#f6f6f6, #dededf);
}
```

All non webkit browers add *-compat.css to apply non webkit CSS properties for example

```
.dj_gecko .mblHeading {
    background-image: -moz-linear-gradient(center top , #B0BCCD 0%, #889BB3 50%, #8195AF 50%, #6D84A2 100%);
}
```

Here are the options that I have though of to address -compat.css files:

1) Add the rules that are found in the -compat.css files to the theme metadata and update both the standard file and the  compat file. The drawback to this is approach is we will need to load both standard and compat files in the theme editor regardless of the browser being used, this could produce unexpected cascade issues.

2) Work with the dojox.mobile team to move as much as possible into the standard files, for example the `.dj_gecko .mblHeading` could be moved to the `.mblHeading` The down side to this would be a increase in the amount of data being transferred to the mobile device. which already happens for non webkit browsers This approach could improve browser support by adding firefox mobile and opera  

3) The way we construct our user created custom themes is to create a CSS file that imports the dojox mobile base theme and then adding the customized rules below the import

```
@import url("../custom/custom.css");
.mblHeading {
    background-image : -webkit-gradient(linear, left bottom, left top, from(#f6f6f6), to(#dededf));
    background-image : -o-linear-gradient(to top,#f6f6f6, #dededf);
    background-image : -ms-linear-gradient(to top,#f6f6f6, #dededf);
    background-image : -moz-linear-gradient(to top,#f6f6f6, #dededf);
    background-image : -webkit-linear-gradient(to top,#f6f6f6, #dededf);
    background-image : linear-gradient(to top,#f6f6f6, #dededf);
}
```

We could create our own rules in the customize css files an eliminate the need for the -compat.css files

In my mind the best option is 2 but option 3 is the easiest to implement and requires no changes to dojo, but increased maintenance on our part

**Comment by cjolif** [comment]
@billreed63 

Mid/long term (2.0) I envision as you suggested that we will move some of compat work back into main CSS. See one of the items in our enhancements here: https://docs.google.com/document/d/1vwYIx-scMnVXUJS9mK890LC58pDle08rwl1SKHv4YfM/edit#heading=h.g5hxjjhmidjb

That said I don't think this will occur in 1.9 this is more a 2.0 thing. In particular:
1/ this would be a good time because we would probably drop support for old browsers that don't have CSS3 support at that time so this will allow us to have more consistent CSS across browsers.
2/ we currently anyway don't have the resources to support alternate browsers on mobile devices (i.e. non Webkit browsers).

So 2. is probably the right approach (even though it won't work on "old" browsers) but from I can see now this will not be doable in this release cycle.

Option 3 is kind of doing 2 but just for you (not dojo mobile) and in advance of phase right? This should be work but won't work with let's say IE78/9 (-ms-linear-gradient even though these versions are supported by Dojo?

For option 1. Can't you open a file to edit it without actually loading it and having it applied?

 cc @edurocher
