### ISSUE TITLE
Patch for dojox.mobile._compat 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2373]
dojox.mobile._compat that I still need to create a patch to submit to dojo for 1.8
@peller

**Comment by billreed63** [comment]
I opened the following ticket http://bugs.dojotoolkit.org/ticket/15434

**Comment by billreed63** [comment]
@JonFerraiolo @jhpedemonte 
->M8

**Comment by peller** [comment]
Dojo ticket has been closed.  Can we close this issue?
