### ISSUE TITLE
Can't add div infront of label

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2375]
Drop a label into an empty page, try to add a div before it:

```
TypeError: widget is undefined
http://192.168.1.122:8081/maqetta/app/davinci/ve/widget.js?@revision@
Line 0
```

**Comment by JonFerraiolo** [comment]
Setting this to M6 High to make sure we investigate.

I tried to reproduce and couldn't. What browser/platform? Split view or design view? How quickly did you perform the operation (e.g., quick drag/drop, or did you hover and wait for type-in cursor to appear)? What commit were you using (there has been a recent change to metadata for label - see #2379).

**Comment by doronrosenberg** [comment]
Seeing this with latest code, Firefox and Chrome - also on lab9
- New file
- Drag and drop a label.  Click cancel on smart input
- Now drag and drop a div to the left of the label - it does insert it as a child of the div, and throws the js error

**Comment by doronrosenberg** [comment]
fixed now
