### ISSUE TITLE
Firefox: Arrow icon for RoundRectList moveTo doesn't show in page designer

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2380]
Running Mac/Firefox using commit 12d1d3f44f15f45... which is later than commit a8a72dd580 
- New HTML page - iphone
- Add two ScrollableView's (ScrollableView_0 and ScrollableView_1)
- Switch to ScrollableView_0
- Add a RoundRectList and accept defaults
- Select first ListItem and in widget-specific properties set 'moveTo' to ScrollableView_1

Result-> No arrow appears in page editor. However, does show in preview-in-browser, and does show in page editor when using Chrome.

**Comment by billreed63** [comment]
I have reverted the code to not add the *-compat.css files for FF as @JonFerraiolo requested. We will solve this problem in m7 with issue #2372

**Comment by billreed63** [comment]
closed with above commit
