### ISSUE TITLE
Migrate GridX config dialog to resizable one (when available)

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2385]
Once #2182 is complete, `GridWizardInput` should be updated to create the new resizable dialog rather than `dijit.Dialog`. In addition, need to ensure layout of all panels works well when user resizes the dialog.

**Comment by doronrosenberg** [comment]
This is complex, the usage of contentpanes/bordercontainer all throughout the gridx wizard complicates things.  Would have to basically rebuild the whole layout from scratch.

**Comment by aerwin** [comment]
I guess I don't know exactly how the resizable dialog code works, but why should the internal widgets used by the dialog contents matter?

In fact, I went with BorderContainer's and such to make layout _easier_ and less dependent on hard-coded sizes (than the R&C wizard was). So, I'd hesitate to do a massive rewrite.

**Comment by doronrosenberg** [comment]
I need to spend more time looking at what is going on, basically if I split the contents into a content area and an action area the stackcontainer breaks.  It works fine for the new review wizard, so I need to debug it further.
