### ISSUE TITLE
Can make design view appear when in source-only view

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2387]
- Open Sample1.html
- Go to source view
- Pull on splitter that separate left-side palettes from the canvas, and pull to the left

Result=> Design view appears to the left of source view

I think the design/source/split logic is in PageEditor.js and isn't all that complicated. I believe we are using sizing tricks to make source view appear, whereas we should probably hide or remove the ContentPane for design view when source view is active.

I actually played around with PageEditor.js when chasing down something else, but didn't commit my changes. As I remember, there are some curious things about how it uses the 'center' region of BorderContainer. My thinking is that the center pane need to swap between source and design sometimes - when source-only, then it should contain source pane, when design-only, it should contain design pane. In split view, could be either one.

**Comment by peller** [comment]
see #2077

**Comment by JonFerraiolo** [comment]
Closing as dupe of #2077
