### ISSUE TITLE
mytheme.document.css not picked up by modeller

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#239]
(Giving to Brad because primary problem is Properties palette, but seems likely
this might be a model issue)

(I think we can live with this bug for 0.6, so set for 0.7.)

(Running Mac/Chrome with Developer Tools on. I assume you'll see the same thing
in Firefox/Firebug)
- New HTML File
- Drag/drop a LABEL
- In debugger, go to HTML elements view and use the object picker icon (the
  hourglass on Chrome) and use the debugger to pick the <label> element that is
  on the design canvas
- In debugger, look at the cascade for the font-family property. It lists
  /davinci/wsfile/themes/mytheme/document.css:3. 

However, the CSS cascade within daVinci doesn't list this file. bug 6800

**Comment by JonFerraiolo** [comment]
Reassigned to Wayne, set milestone to M5.

**Comment by jhpedemonte** [comment]
-> M7

**Comment by JonFerraiolo** [comment]
-> @billreed63

**Comment by billreed63** [comment]
document.css is now being modeled and rules are being selected.
The issue with label is we do not find the rule for label because it is not on the label element it is inherited from the body.

the rule is 

```
.claro {
    color: red; 
    .
   .
}

```

If I add a rule to document.css for label

```
.claro > LABEL {
    color: red; 
    .
   .
}

```

that rule is found and added to the cascade.

**Comment by billreed63** [comment]
this has been fixed by all the document.css changes added to M7
