### ISSUE TITLE
Do custom build for GridX

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2390]
@peller pointed out that the number of css and JS files in GridX is worrisome from a performance perspective. He says:

> we may be able to just duplicate what's done for Dojo in the maqetta.core.client plugin… lots of eclipse / ant magic to trigger the build scripts

**Comment by peller** [comment]
one problem with this is that gridx is not self-sufficient.  A gridx layer would depend on the dijit.js layer, also dojo.js which are built in separate plugins.  This is like the problem we had with R&C.

**Comment by aerwin** [comment]
Excerpt from @peller e-mail on 5-30-2012:

> So here's the issue: Maqetta needs a layer.  We're wondering whether we should build it, or whether it should be part of the GridX distribution that we get via git submodule.
> 
> I asked around, and it seems the strategy so far for packages to distribute in source mode and hope that someone finishes the toolchain such that a web-based builder, like build.dojotoolkit.org, can easily assemble these things on the fly.  In the meantime, users will be expected to learn not just the cpm tools, but also need to run a build and possibly even write their own profile.  Not good.  I've raised this issue with Dylan.  We have to do better.
> 
> As a workaround, would it make sense to distrute a 'built' layer?  Generally, no, because those layers would depend on other layers, and nobody knows exactly how the user's code will be configured or which other components they'd be using. For example, dgrid is structured to use other packages besides Dojo, like xstyle.  Would a dgrid.js layer include xstyle or reference a built xstyle.js layer?  Which (minimum) version it requires of xstyle and dojo would be baked into the layer.  The complexity increases with the number of components, obviously.  GridX is basically dojo+dijit+gridx, but I'm not sure it makes sense for gridx to package a layer if that's not going to work as a general solution for packages.
> 
> That line of thinking leads me to think we're best off putting together a build script on our end in maqetta.core.client for now, perhaps to copy over the gridx files at build time and build a gridx.js layer specially for the workbench, dependent on the dojo.js and dijit.js layers, perhaps do the same for the user code also (and assume, for now, that it's running the same version of Dojo as the workbench).  Perhaps we can rely on zazl optimization tools in M7 to do this optimization on-the-fly in the VisualEditor, but I'm not betting on that.  So far, it only runs for code preview.
> 
> But for gridx, and packages in general, we're going to have to worry about the bigger problem of how people will easily consume these things.

**Comment by aerwin** [comment]
So, assuming we want to augment the build script for maqetta.core.client to build a layer for gridx (see e-mail from @peller above), then I'm guessing we don't really want to hardcode knowledge of the gridx plugin in the maqetta.core.client build scripts. Which gets me to thinking, gridx is our biggest worry in the short-term (because of # of files, etc.), but wouldn't all of our plugins potentially benefit from their own layer? Or, maybe two layers (one for metadata and one for library)? So, while we're doing this should we just start building layers for all UI plugins as a general practice? 

Then, at runtime, the code in `metadata.js` which registers module ids for metadata and library code paths for all of the plugins could also reference the appropriate layer files? (This starts to get into issues touched upon in #2464.)

```
        // Register a module identifier for the metadata and library code paths;
        // used by helper and creation tool classes.
        pkg.__metadataModuleId = 'maq-metadata-' + pkg.name + '-' + pkg.version;
        pkg.__libraryModuleId = 'maq-lib-' + pkg.name + '-' + pkg.version;
        var libPath = 'app/static/lib/' + pkg.name + '/' + pkg.version;

        require = require({
            packages: [
                {
                    name: pkg.__metadataModuleId,
                    location: new Path(location.href).append(path).toString()
                },
                {
                    name: pkg.__libraryModuleId,
                    location: new Path(location.href).append(libPath).toString()
                }
            ]
        });

```

**Comment by aerwin** [comment]
@peller @jhpedemonte 

The commit above does a custom build of GridX ( 4b2502a469931812917564d5c068975215d1e3dd ) and copies it into the davinci.gridx/WebContent/gridx directory so that it gets used in both the Maqetta runtime scope and the user iframe scope.

The build scripts in the above commit were also updated to build a layer for GridX (`gridx-all.js`). So, the big hole now is how to reference that layer so that it gets used by the Maqetta runtime (I think we've decided not to try and use it for the user space).

I'm wrestling with two things:
1. How should the layer be specified in package.json? Not sure if the server is down or what, but I've not been able to get to the [packages spec](http://wiki.commonjs.org/wiki/Packages/1.0) to see if there's any well-defined way to specify a layer to be used for the library. But, I'm guessing we might need to add some custom metadata to the overlays section.
2. Once we have some metadata that specifies a layer, how do we require it from `metadata.js` conditionally so that we only use it if the layer is there. E.g., only use it when we have a GridX build, but not otherwise (like when running from the Eclipse launch scripts during development).

**Comment by peller** [comment]
Can you use the same module reference (grid-all.js) in both built and unbuilt scenarios, so that no conditional logic is involved?  What you'd typically do is just "build" a .js file which already exists in the source tree, and it would get replaced with all the dependencies inlined.  Sometimes that module is nothing but a require() with a list of dependencies, other times, it's the main module.  If you look in dojo at util/buildscripts/profiles/standard.profile.js, you'll see that DataGrid.js is just replaced with its layer file.

Because gridx has a plugin architecture, it might make more sense to create various configurations as separate modules.  I suppose if you went that route, you'd either have to create these modules outside the gridx tree, or see if Evan wishes to provide them.

**Comment by aerwin** [comment]
That's a good suggestion to replace a file like we do with DataGrid. In the GridX case, I'd replace gridx/Grid. Let me play around with that a bit...

**Comment by peller** [comment]
That wouldn't incorporate any plugins, but perhaps we don't use any yet, or perhaps the plugins don't involve so many individual fetches?

The trick here is that your layer will need to have a dependency on other layers (namely dijit.js) which are not contained in the gridx OSGi plugin

**Comment by aerwin** [comment]
_That wouldn't incorporate any plugins, but perhaps we don't use any yet, or perhaps the plugins don't involve so many individual fetches?_

Yeah, I figured I'd try to include a minimal set of plugins that we currently use, but that's part of what I'm experimenting with.

_The trick here is that your layer will need to have a dependency on other layers (namely dijit.js) which are not contained in the gridx OSGi plugin_

I already had that covered under 4b2502a469931812917564d5c068975215d1e3dd . E.g., was building my own layer dependent on dijit, but was putting it in my own gridx-all.js rather than overwriting Grid.js, so I wasn't actually using that layer at runtime yet.

**Comment by peller** [comment]
so somehow, when the script runs, gridx/\* and dijit/\* are peers?  I guess that would cover it.

**Comment by aerwin** [comment]
Yes, during build time I copy dijit into the tmp directory for the gridx plugin as peer of gridx and then delete it after the build is complete.

**Comment by aerwin** [comment]
Closing with above commits.

**Comment by jhpedemonte** [comment]
Reopening.  I'm coming to this late, but I have an issue with how the library code is registered in **metadata.js**.  Here's my [comment on that commit](https://github.com/maqetta/maqetta/commit/4b2502a469931812917564d5c068975215d1e3dd#commitcomment-1558634):

> I guess what we are trying to do with the `_libraryModuleId` is register an AMD module namespace for the library code, in the context of the app (workbench) itself.  The namespaces _dojo_, _dijit_ and _dojox_ already exist, since that's what we are using to build the app.
> 
> Now we want to add AMD modules namespaces for the widget libraries themselves, in order to facilitate the helpers code.
> 
> One major issue with your implementation is that it does in fact ignore _dojo_ (and this could become an issue if we decide to make use of other code which may also be a widget library).  Technically, the version of Dojo used in for the VE can be different than that used by the app.
> 
> AMD allows us to have two or more versions of one library living alongside each other, in a different namespace.  So while the app will use Dojo from the "dojo" module namespace, for accessing the Dojo widget library we can use the namespace "maq-lib-dojo-1.8".
> 
> So this change needs to be reverted; we'll need to fix the build scripts some other way.

Let's discuss this on Tuesday.

**Comment by aerwin** [comment]
@jhpedemonte We'll probably need to talk about this tomorrow at the scrum, but I don't think the answer is to revert the change... seems like we can go back to registering dojo lib id as you had it before my change with a tweak:

Current code:

```
        // Register a module identifier for the metadata and library code paths;
        // used by helper and creation tool classes.
        pkg.__metadataModuleId = 'maq-metadata-' + pkg.name + '-' + pkg.version;
        var packages = [ {
            name : pkg.__metadataModuleId,
            location : new Path(location.href).append(path).toString()
        } ];
        if (pkg.name != "dojo") {
            //Don't register another "dojo" lib to compete with core.client
            pkg.__libraryModuleId = pkg.name;
            var libPath = 'app/static/lib/' + pkg.name + '/' + pkg.version;

            packages.push({
                   name: pkg.__libraryModuleId,
                   location: new Path(location.href).append(libPath).toString()
                });
        }
```

Untested proposed change in logic to handle dojo:

```
        // Register a module identifier for the metadata and library code paths;
        // used by helper and creation tool classes.
        pkg.__metadataModuleId = 'maq-metadata-' + pkg.name + '-' + pkg.version;
        var packages = [ {
            name : pkg.__metadataModuleId,
            location : new Path(location.href).append(path).toString()
        } ];
        if (pkg.name == "dojo") {
            //Don't want to register another "dojo" lib to compete with core.client, so make
                //specialized module id
               pkg.__libraryModuleId = 'maq-metadata-' + pkg.name + '-' + pkg.version;
       } else {
               pkg.__libraryModuleId = pkg.name;
        }
        var libPath = 'app/static/lib/' + pkg.name + '/' + pkg.version;
        packages.push({
                name: pkg.__libraryModuleId,
                location: new Path(location.href).append(libPath).toString();
        });
```

However, if at some point you actually wanted to use the `maq-lib-dojo-1.8` module id with the built code checked into the dojo_1_8 it would fail (just like I found `maq-lib-gridx-1.0` fails with built GridX code). But, that's an entirely separate issue that existed before I did anything for building GridX.

**Comment by aerwin** [comment]
@jhpedemonte @peller 

Some more background for when we have this discussion...

Let's look at the shapes plug-in since the discussion goes beyond gridx at this point...

When the dojo built is performed, the AMD module path is actually hardcoded into the definition. For example, look at the built `_CircleMixin` from the shapes lib:

```
//>>built
define("shapes/_CircleMixin",["dojo/_base/declare",],function(_1){
//impl removed for clarity of example
});
```

The path ("shapes/_CircleMixin") becomes part of the definition. Obviously, before the build there's not such reference.

If we wanted to reference `CircleMixin` as "maq-metadata-shapes-1_0_CircleMix" in Maqetta (as the metadata.js code set-up before I changed it) we'd have to get the build to look like the following (where "maq-metadata-shapes-1_0/_CircleMixin" in the definition):

```
//>>built
define("maq-metadata-shapes-1_0/_CircleMixin",["dojo/_base/declare",],function(_1){
//impl removed for clarity of example
});
```

However, if we did that, then things wouldn't work in the user's workspace unless the user's HTML loaded using "maq-metadata-shapes-1_0/_CircleMixin" (which we obviously don't want to do).

So, this is why I changed the `metadata.js` code to not create the version based module id for libs. And, why using `maq-lib-dojo-1.8` isn't going to work (even if I reverted the code).

### Metadata

On the flip-side, metadata doesn't need to be referenced from the user's workspace. So, I in the metadata case I went ahead and jumped through the hoops to get our desired module id into the build output. For example, see `_ShapeHelper` built result below:

```
//>>built
define("maq-metadata-shapes-1_0/shapes/_ShapeHelper",["davinci/Runtime","dojo/_base/connect","davinci/ve/tools/CreateTool","davinci/commands/CompoundCommand","davinci/ve/commands/ModifyCommand","davinci/ve/commands/StyleCommand","davinci/ve/widget"],function(_1,_2,_3,_4,_5,_6,_7){
var _8=function(){
};
```

To do this, I had to:
- copy the plug-in's "metadata" directory to a temporary "maq-metadata-shapes-1_0" directory
- do the build
- copy result back to "metadata" directory
- delete  "maq-metadata-shapes-1_0" directory

**Comment by aerwin** [comment]
--> @jhpedemonte 

Last I knew on this, @jhpedemonte was looking into registering package aliases.

**Comment by jhpedemonte** [comment]
Yes, got sidetracked the past couple days with other stuff, but I'll finish this one up today.

**Comment by jhpedemonte** [comment]
Closing this out, since the original intent of this issue has been accomplished.  Further work in #3060.
