### ISSUE TITLE
I saw a loadingDiv.parentNode is null console message

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2393]
I had 4 html editors open and I did a refresh (using Win/FF) and I saw this message as various editors were initializing:

TypeError: this.loadingDiv.parentNode is null.

Looking at the code, I suspect this is happening at VisualEditor.js:393 because there are only two lines of code with this.loadingDiv.parentNode and the other one is bracketed by an `if (this.loadingDiv.parentNode) {` statement. I would suggest we need to add a similar `if (this.loadingDiv.parentNode) {` around VisualEditor.js:393

**Comment by peller** [comment]
was unable to reproduce this in FF for either type of editor, but I will add the statement
