### ISSUE TITLE
Changing any style in non-Normal state isn't reflected in the theme editor for Textbox font color

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2395]
- Clone Claro.
- Change the TextBox style in Normal to red font color
- Switch to Hover, change the textbox font color to green

The "hover" textbox shown is still showing a red font color.  Same happens if you go and create a page with the theme and preview it.

Same for disabled, which is easier to test.  Here is a generated myclaro.css:

```
@import url("../claro/claro.css");.claro .dijitTextBox, .claro .dijitInputInner {
    font-size : 20px;
    color : #d81b1b;
}
.claro .dijitTextBoxHover, .claro .dijitTextBoxHover .dijitButtonNode {
    color : #303c94;
}
.claro .dijitTextBoxDisabled, .claro .dijitTextBoxDisabled .dijitButtonNode {
    color : #ce42b2;
}
.claro .dijitTextBoxFocused, .claro .dijitTextBoxFocused .dijitButtonNode {
    color : green;
}
```

Everything not in normal mode uses `.dijitButtonNode` and not `.dijitInputInner`

**Comment by JonFerraiolo** [comment]
I haven't had time to study this to see how serious of a problem it is for M6.

**Comment by billreed63** [comment]
claro.css has changed from preview 5, in preview 5 the font color for text box was

```
.dijitTextBox {
border: solid black 1px;
width: 15em;
vertical-align: middle;
}
```

In preview 6 the font color has moved to 

```
.claro .dijitTextBox, .claro .dijitInputInner {
color: black;
}
```

And no rule exists for .claro  textBoxHover claro .dijitInputInner
