### ISSUE TITLE
Better default width/height for grids, trees and tables

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2396]
@aerwin, @billreed63, @doronrosenberg 

Right now Tree and gridx default to a particular size (e.g., 300px x 300px). This doesn't work particularly well in flow layout, where it seems to me most of the time users would want width:100% for these widgets. Scenarios where the current defaults don't produce particularly good results:
- It's common for people to put a Tree in the left pane of a BorderContainer. Right now, our defaults usually make the Tree wider than the left pane. To make things work well, users have to go to Properties palette to set width:100%. (IMO, we do that for them by picking a better initial size)
- For gridx, we default to width:300px. If the user wants to have several columns (which is the likely common case), this isn't enough width. Would be better to default to 100% for flow layout scenarios.

We now have helper mechanisms that we use for various widgets to set initial width and/or height depending on their context, particularly absolute vs flow positioning.

What I'm thinking for defaults:
- height:auto
- min-height:2em (for situations where the widget has no content)
- width:
  - flow layout: 100%
  - absolute layout: 300px

The relevant helper function is helper.initialSize. This helper is used by BorderContainer, TabContainer, Accordion, are various mobile widgets.

**Comment by aerwin** [comment]
Looking through the metadata to find widgets where an initial size is specified, I don't think this is limited to grids & trees. I see the following that could benefit from similar logic. This makes me wonder if we need to handle this at a higher-level than pushing off to helpers (especially given the number of widgets in list that don't currently have a helper at all):
- davinci.dojo_1_7
  - AccordionContainer (already has initialSize in helper)
  - BorderContainer (already has initialSize in helper)
  - ContentPane (helper, but no initialSize function)
  - Form (no helper at all)
  - TabContainer (already has initialSize in helper)
  - DataGrid (helper, but no initialSize function)
  - HorizontalSlider (helper, but no initialSize function)
  - TitlePane (already has initialSize in helper)
  - Tree (helper, but no initialSize function)
  - TreeGrid (helper, but no initialSize function)
  - Vertical Slider (though would want height:100%, not width)
  - StackContainer (no helper at all)
  - BarGauge (helper, but no initialSize function)
  - Chart2D (helper, but no initialSize function)
  - SortList (helper, but no initialSize function)
  - GridContainer (no helper at all)
  - ScrollPane (no helper at all)
  - RadioGroup (no helper at all)
  - RadioGroupFade (no helper at all)
  - RadioGroupSlide (no helper at all)
- davinci.gridx
  - GridX (helper, but no initialSize function -- would inherit from DataGridHelper)
- davinci.html
  - form (no helper at all)
  - iframe (no helper at all)

**Comment by JonFerraiolo** [comment]
Good job doing an inventory. Given the above, yes, maybe we need to add new metadata to cover this situation.

**Comment by aerwin** [comment]
With the above commit, I'm going to close this issue. However, I imagine some iteration will be necessary as folks use the new behavior in practice. But, I'd propose we handle those as separate issues.

**Comment by JonFerraiolo** [comment]
After doing 5 minutes of testing, things look good to me so far.

One difference versus previous algorithms (eg Preview 6) is that there was different default sizing logic for BorderContainer vs other containers. If BorderContainer is the first child of BODY with flow layout, then in P6 that would get w=h=100%, but if TabContainer or Accordion are the first child of BODY with flow layout, then default w=h=300px. My thinking was that first-time users might get confused if the first time they dropped a TabContainer or Accordion, those container widget came out at 100%. (Also, note that our desktop tutorial assumes TabContainer comes in at 300px by 300px.) Any thoughts on this particular question?

**Comment by aerwin** [comment]
@JonFerraiolo 

Yeah, I debated TabContainer and Accordion dropped into the BODY case. I think you're right. I can see where filling the entire space (100%x100%) may not be what all users need by default. For example, in a real UI a designer might want to put instructions above the TabContainer (so, of the two I was thinking Accordion would be the most desirable to fill up the whole space).

So, I'm fine with setting the height back to to 300px for TabContainer and Accordion. But, what about width? 100% still seems like the right thing to me for those containers. So, in the end, I'd propose 100%x300px for TabContainer and Accordion dropped into BODY. Thoughts?

**Comment by JonFerraiolo** [comment]
For Accordion and TabContainer, how about 
- 300px by 300px if it's a child of BODY and flow layout, or if absolute
- otherwise, 100%x300px

**Comment by JonFerraiolo** [comment]
For Accordion and TabContainer, how about 
- 300px by 300px if it's a child of BODY and flow layout, or if absolute
- otherwise, 100%x300px

**Comment by aerwin** [comment]
@JonFerraiolo and I chatted and agreed to go with the 100%x300px approach in the BODY for Tab and Accordion. This will be one of the kind of things that we might decide to tweak as the summer goes on and folks get hands on experience with the new initial sizing behavior.
