### ISSUE TITLE
Tree doesn't look right

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2399]
1. Create HTML file
2. Drop Tree onto page editor, and see rendering below:

![tree 1](http://i.imgur.com/iQBYv.png)

Also, see this error message in console:

```
GET http://localhost:8081/maqetta/user/maqettaUser/ws/workspace/project1/icons/images/commonIconsObjActEnabled.png 404 (Not Found) 
```

Tree should look like (from Preview 5):

![tree 2](http://i.imgur.com/JYzud.png)

**Comment by jhpedemonte** [comment]
cc @billreed63 @JonFerraiolo 

Bill, is this related to any of the additions of images you've been doing for the themes?

Also, seems odd that the URL is looking for the _icons_ dir right off of the project directory, rather than from a themes dir.

**Comment by JonFerraiolo** [comment]
-> M6 High. Ship stopper. I suspect the problem here is that we upgraded to the latest claro.css, and the Dojo guys moved location for some of the icons used by the theme.

**Comment by JonFerraiolo** [comment]
I suspect that the dojo folks moved some shared icons out of the themes and are referencing icons found in ./dijit/icons, under assumption that the themes/ folder is at a particular location relative to the ./dijit/icons folder but of course we have the themes folder in a different location

**Comment by JonFerraiolo** [comment]
Here is my proposal:
- For M7, we coordinate with Dojo guys and see if they will revert to the previous approach where themes were all self-contained and didn't depend on being in a particular location relative to the rest of Dojo (and don't reference `../../` files)
- For M6, we hand-edit claro.css and sketch.css and globally replace `../../icons/images/` with `icons/images/`

**Comment by JonFerraiolo** [comment]
Just tried out this fix, and the missing Tree icons appear again.

**Comment by JonFerraiolo** [comment]
OK, I patched things so that Tree and other widgets will show their icons properly, and pushing this issue to M7 for a real solution. As @billreed63 says: I think for M7  now that we are using delta themes we should be able to leave the claro theme where it is in dojo  and in our themes/claro.css just have an @import of the real theme

**Comment by jhpedemonte** [comment]
Yes, I like Bill's proposal.  It seems like every release we have to update/recopy files for the themes, based on changes in the library.  If we can just point to the actual files rather than copying them, that would help us greatly with maintainability.

**Comment by JonFerraiolo** [comment]
What's left with this issue?
