### ISSUE TITLE
theme editor should check version of theme before opening

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2403]
If the user attempts to edit a theme that was cloned on preview 5 the theme can be messed up.

We should not open the theme editor if the theme file is down level. suggest that the user clone the them and edit that version

**Comment by jhpedemonte** [comment]
How big of an issue is this for M6?  At this point, I'd prefer to push this to M7.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
If the fix is quick and safe, I'd prefer fixing it, but I'm not that strong on that point. I understand the benefit/risk ratio isn't compelling.
