### ISSUE TITLE
Clone mobile theme puts error message in console

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2404]
1. Clone mobile theme
2. Theme gets cloned, but note error in JS console (the path is always specific to whatever theme was cloned). 

```
GET http://localhost:8081/maqetta/user/maqettaUser/ws/workspace/project1/themes/android/document.css 404 (Not Found) Context.js:1517
```

**Comment by JonFerraiolo** [comment]
Closing. That 404 is expected for M6 and is harmless. We have a cleanup bug for M7 to prevent the 404.
