### ISSUE TITLE
Mobile subwidget styling: list item rendering different in theme editor and page editor

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2407]
Not sure this is terribly pervasive across any other properties, but in editing the android theme, I changed `text-decoration` on the RoundRectList ListItem to "strikethrough". It didn't render in the theme editor, so I assumed it wasn't a valid change to make:

![screenshot](http://i.imgur.com/3UNQA.png)

But, in the page editor rendering, I see the strikethrough:

![screenshot](http://i.imgur.com/dNzmO.png)

**Comment by jhpedemonte** [comment]
-> M7

**Comment by billreed63** [comment]
fixed with M7 and dojo 1.8
