### ISSUE TITLE
Versioning/migration strategy for themes for 1.0+

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2408]
We need a versioning and migration strategy for custom themes for our 1.0 release. Once we get to 1.0, we can't tell users their custom themes have to be tossed away.

Although maybe we can tie custom themes to particular library releases. For example, if you create a custom theme for dojo 1.8, future versions of maqetta will provide backwards compatibiliy for dojo 1.8, but if the user switches to 1.9, well that's a different story. With delta themes, such upgrades to Dojo will usually work, but probably bottom line for users is that it's there responsibility for migrating their themes (and their apps, for that matter).

@peller @childsb @jhpedemonte

**Comment by billreed63** [comment]
all existing themes that have html files in their theme folder need to be migrated
from 

```
<script type="text/javascript" src="/maqetta/app/static/lib/dojo/1.7/dojo/dojo.js" djConfig="parseOnLoad: true"></script>

```

to

```
<script type="text/javascript" src="/maqetta/app/static/lib/dojo/1.7/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
```

or we get an exception when the themeEditor loads and the spinning wheel.

**Comment by billreed63** [comment]
<h2>To migrate Preview 6 themes which are based on dojo 1.7:</h2>

 in this example the theme would be claro_p6
claro_p6.theme contains:

```
{"className":"claro","name":"claro_p6","version":"1.7","specVersion":"0.81","files":["claro_p6.css"],"meta":["../claro/claro.json"],"themeEditorHtmls":["../claro/dojo-theme-editor.html"]}
```

1) The user would clone the current claro theme (dojo 1.8)  for this example claro_p7
2) Edit the cloned CSS file, example claro_p7/claro_p7,css :

```
@import url("../claro/claro.css");
@import url("../claro_p6/claro_p6.css");
```

**Comment by billreed63** [comment]
<h2> To Migrate pre  preview 6 themes </h2>


These themes are pre delta themes and we should really encourage users to start over.

in this example the theme is green

green.theme file contains:

```
{"className":"green","name":"green","version":"1.7","specVersion":"0.7","files":["green.css"],"meta":["claro.json"],"themeEditorHtmls":["dojo-theme-editor.html"]}

```

1) The user would clone the current claro theme (dojo 1.8) for this example claro_p7
2) Edit the cloned CSS file, example claro_p7/claro_p7,css 

```
@import url("../claro/claro.css");
@import url("../green/green.css");
```

3) Download the theme file example claro_p7/claro_p7,theme
4) Edit the  claro_p7/claro_p7,theme

```
{"className":"claro green","name":"claro_p7","version":"1.8","specVersion":"0.81","files":["claro_p7.css"],"meta":["../claro/claro.json"],"themeEditorHtmls":["../claro/dojo-theme-editor.html"],"helper":"maq-metadata-dojo/dijit/ThemeHelper","conditionalFiles":["document.css"]}
```

5) upload the file.

**Comment by billreed63** [comment]
<h2> Post version 1 </h2> 

We will need to migration code to themeEditor open  and theme clone that checks the version of the theme and if the theme is pre current version asks the user if they would like to migrate the theme.
IWe then migrate the theme to the current level.

**Comment by JonFerraiolo** [comment]
-> M8 Prio-Med
