### ISSUE TITLE
color property should not be available on element.style for TextBox

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2409]
The cascade for TextBox shows that element.style is available for TextBox, but if I change TextBox's color, nothing happens. If I create a new class and add a rule to app.css, then the color changes.

I suspect that claro changed since we created the original theme metadata.

**Comment by billreed63** [comment]
Also if the user has a custom them and selects the correct rule to change font color the rule is not updated and selected with the correct value
