### ISSUE TITLE
Properties palette - event attribute fields don't clear on new document open

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#241]
If you put something in 'onclick' or any of the event fields in the Properties
palette, close that HTML document, the event fields continue to show the values
that had been present with the previously open doc. If you then create a new
HTML doc, the event fields still show the old values. (If you add a widget,
then the event fields will clear.)

bug 6830

**Comment by JonFerraiolo** [comment]
M7/Prio-Low. Non-critical, but should be easy and safe to fix.
