### ISSUE TITLE
embed: editFeedback show cover the widget

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2414]
I was running test plan for HTML elements and added an EMBED that pointed to a flash widget. I tried to click-select the embed and the widget did not get selected. I think it's because the Flash is grabbing the event (see #2413)

**Comment by aerwin** [comment]
@JonFerraiolo @jhpedemonte 

-> M8

**Comment by billreed63** [comment]
Tested on latest code with 

```
 <embed src="http://www.w3schools.com/html5/helloworld.swf"></embed>
```

and the the issue has been resolved, most likely when @JonFerraiolo rewrote the selection editFeedback code
