### ISSUE TITLE
Outline drag operations don't remove dynamic interactivity

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2417]
The UI that Dojo's tree drag-drop feature provides sometimes doesn't remove the dynamic overlay that appears during the drag operation.

**Comment by JonFerraiolo** [comment]
@doronrosenberg

**Comment by JonFerraiolo** [comment]
Moving to M6 so at least we can think about trying to fix. Is there a way we can force bringing down the phantom overlays just in case they haven't been brought down by normal processing?

**Comment by doronrosenberg** [comment]
If they aren't being removed it could be we are eating a js error.

**Comment by JonFerraiolo** [comment]
> If they aren't being removed it could be we are eating a js error.

Could be. I found a way to reproduce if you have Chrome debugger open. (this technique only works if you have debugger open)
- Open Sample1.html
- Drag the bottom ContentPane onto the root node of tree (ends with "...Sample1.html")

Result=> exception in debugger - focus goes into debugger window
- Hit continue arrow to go past the exception

Result=> phantom outline drag image as you move mouse over canvas

One thing I'm wondering is if focus goes somewhere else, maybe drag/drop doesn't cleanup properly.
