### ISSUE TITLE
Properties palette widget-specific: enumerated and numeric values

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#242]
The widget-specific section of the properties palette doesn't yet proper
support for enumerated and numeric values. Widget-specific properties with
enumerated values should show either a ComboBox or SELECT. Widget-specific
properties that allow for numeric values should include +/- icons and validate
that the value is a valid number.

As an example of enumeration, the 'design' property for BorderContainer shows
up in the Properties palette as a text property, but in fact it is an
enumeration. The widget metadata says:

``` javascript
   "property": {
        "design": {
            "datatype": "string",
            "option": [
                {
                    "value": "headline"
                },
                {
                    "value": "sidebar"
                }
            ],
            "defaultValue": "headline",
            "title": "Design"
        },
```

What should happen is as follows:
- If the property has an 'option' and if unconstrained is true (see
  http://www.openajax.org/member/wiki/OpenAjax_Metadata_1.0_Specification_Datatypes#options_element),
  then we should show a ComboBox where the menu shows the list of options but the
  user can type whatever he wants
- If the property has an 'option' but unconstrained is false, then use a SELECT
  element.

Javier, I forgot, how would the 'unconstrained' setting appear in the JSON?

javier - 

(In reply to comment #0)

> Javier, I forgot, how would the 'unconstrained' setting appear in the JSON?

Currently, the oamXml2Json.js script would add the "unconstrained" parameter
like this:

``` javascript
   "property": {
        "design": {
            "datatype": "string",
            "option": [
                {
                    "value": "headline",
                    "$parent_unconstrained": true
                },
                {
                    "value": "sidebar"
                    "$parent_unconstrained": true
                }
            ],
            "defaultValue": "headline",
            "title": "Design"
        },
```

bug 7084

**Comment by JonFerraiolo** [comment]
Given Priority-Medium because we want to leverage menus within widget-specific properties to show possible view ids within dropdown menu for 'moveto' property, and then leverage this feature for other properties, particularly 'id' (show list of permanent IDs in doc: #249), 'class' (show list of classes in doc: #247) and 'href' (#1044)

**Comment by jhpedemonte** [comment]
Brad, what Jon wrote above is correct:  if `unconstrained` is false (its default value), then the user can only choose from the list; if true, users can enter their own value.

Note also that the [OAM spec](http://www.openajax.org/member/wiki/OpenAjax_Metadata_1.0_Specification_Datatypes#options_element) allows for a `multiple` attribute, where if it is set to true, the user can choose more than one item.  I don't think we have any use for that now, so we should just handle the `unconstrained` attribute and open a 'future' issue on `multiple`.
