### ISSUE TITLE
Can't remove SmartInput value

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2424]
- Add a DIV
- Double-click to enter "abc" as text, click OK to accept
- Double-click again and try to set to empty string (or single space character)

Result=> old value "abc" stays in place

**Comment by JonFerraiolo** [comment]
Bug existed in Preview 5, too

**Comment by JonFerraiolo** [comment]
Note: proposed fix is currently off in a branch, not yet in master.

**Comment by billreed63** [comment]
merged with master
