### ISSUE TITLE
Weirdness dropping a Switch into a DIV

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2427]
@peller @jhpedemonte @doronrosenberg 

I was doing a mockup and I had all sorts of trouble putting Switch widgets inside of DIVs. Here is what I wanted to do (inside of a ScrollableView under a Heading and a RoundRectList):

```
DIV
  LABEL
  SWITCH (with float:right)
DIV
  LABEL
  SWITCH (with float:right)
```

But when I attempted to do this, I ran into these problems:
- Even if you drop the Switch inside of a DIV, the Switch ends up below the DIV. When I changed display to inline-block, and then dragged the Switch into the DIV, then it ended up adjacent to the LABEL. 
- On first Switch, after changing to display:inline-block, I changed float to 'right', and everything was good, but when I tried the same approach for the second Switch, it refused to go to the right.

Haven't had time to investigate what's broken.

**Comment by JonFerraiolo** [comment]
@doronrosenberg can you please investigate? Feel free to send back to me if you think it would be better for me to pick this one up.

**Comment by doronrosenberg** [comment]
I can't reproduce this, both switches floated to the right.  Note that you have to add clear:both to the divs if you are using floats.

**Comment by jhpedemonte** [comment]
@JonFerraiolo, care to respond to Doron's last comment?  Can this be closed as working?

**Comment by JonFerraiolo** [comment]
Assigning to me to evaluate

**Comment by JonFerraiolo** [comment]
Closing. I can't reproduce now, either.
