### ISSUE TITLE
Plus icon (+) on opacity changes 0.5 to 1.6

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#243]
I thought the algorithm took the least significant digit and incremented it,
but with opacity it changes 0.5 into 1.6

**Comment by JonFerraiolo** [comment]
Put this as low priority for M4 only because it's embarrassing that we haven't fixed this yet, but OK to push to M5 if we can accept the shame for that long.

**Comment by JonFerraiolo** [comment]
Pushing to M5, Priority-Med
