### ISSUE TITLE
gridx firefox - can't just drag/drop, have to click on canvas

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2433]
With Mac/FF and Win/FF, when I attempt to drag/drop the grid onto the canvas, I find that the drop doesn't "take" and I usually have to click on the canvas after attempting the drag/drop before the gridx actually "takes". One the click happens, all of the various files that are needed by gridx appear as messages in the Firebug console.

**Comment by aerwin** [comment]
I haven't seen this with Mac/FF (and haven't tried with Win/FF), but I wonder if this would be helped by the gridx custom build (#2390)?

**Comment by aerwin** [comment]
I think this seems pretty good after adding the custom build stuff in #2390, so closing. @JonFerraiolo , please reopen if you think still a problem.

**Comment by aerwin** [comment]
With lab9 now updated to use all of the custom build stuff from #2390, I'm seeing this problem (even in Chrome). Though it kind of seems like only the first drop with an empty cache exhibits the problem. At any rate, reopening...

**Comment by aerwin** [comment]
Paying attention to the Network tab in Chrome developer tools, it seem like when the "hang" occurs that `DropDownSelect.js` is the last file loaded. Clicking in the canvas then leads to `ItemFileReadStore_oam.json` and the rest of the needed files to be loaded.

**Comment by aerwin** [comment]
More precisely

/maqetta/app/dojox/form/DropDownSelect.js

and 

/maqetta/app/metadata/dojo/1.7/dojo/data/ItemFileReadStore_oam.json

**Comment by aerwin** [comment]
While discussing #2963, @peller pointed out to me that `GridCreateTool` used an immediate `requires` that could cause problems... in the process of going to clean that up, I've found some much more fundamental problems that probably lead to this issue and other strange timing related problems we've seen intermittently (like #2574).

Basically, `DataGridCreateTool` is not set-up to be asynchronous. It overrides `_create` from its superclass `CreateTool`. And, while the superclass version does a nice job of using `Deferred`'s (e.g., for example when calling `loadRequires`), the version in `DataGridCreateTool` doesn't. 

And, unfortunately, this appears to be rather wide spread. There are 8 other subclasses of `CreateTool` in Maqetta that do the same thing. It''s just that it's most likely to cause problems for GridX with the number of files it loads, its cross bundle metadata requirements, etc.

**Comment by aerwin** [comment]
Quick follow-up... things aren't quite as bad as I thought... my working sets got out of whack in my Eclipse search and I was looking at code from the dojo_1_7 plugin (rather than dojo_1_8). So, I we're no longer talking about a bunch of messed up `CreateTool` subclasses.

**Comment by aerwin** [comment]
Hopefully fixed with above commit.

**Comment by peller** [comment]
see also #2935

**Comment by aerwin** [comment]
--> Reopening

Just tried with a cleared cache on the internal test server and had to click twice.. Ugh...  Keep thinking this one is fixed, but hard to tell as can be intermittent and generally only happens with our test servers.

**Comment by aerwin** [comment]
@doronrosenberg @peller Thoughts here?

Ok... put some break points running against the server and on first drop it gets into the `_create` function in `DataStoreBasedCreateTool`, but does NOT get inside the function inside the `then` on `loadRequires`:

```
        this._loadRequires().then(dojo.hitch(this, function(results) {
            if (!dojo.some(results, function(arg){return !arg;})) {
                // all args are valid
                this._getCreateCommand(args).then(function(command) {
                    this._context.getCommandStack().execute(command);
                    this._select(this._widget);
                }.bind(this));
            } else {
                console.log("DataStoreBasedCreateTool:_loadRequires failed to load all requires");
            }
        }));
```

This has to mean that the promises within load requires are not being fulfilled on first drop, right?

```
_loadRequires: function() {
        var promises = new Array();

        dojo.forEach(this._data, function(item) {
            promises.push(this._context.loadRequires(item.type, true));
        }.bind(this));

        return all(promises);
    }
```

**Comment by peller** [comment]
Yeah, probably worth stepping through loadRequires to see if the type resolves to a javascript module, etc.

**Comment by doronrosenberg** [comment]
hrm, local build here runs fine on firefox windows.

```
if (!dojo.some(results, function(arg){return !arg;})) {
```

That code of mine is meant to check that all the results are not null/undefined, which means the loadRequires wasn't able to load it.

**Comment by aerwin** [comment]
> hrm, local build here runs fine on firefox windows.

Right, that's been the problem all along... only really happens on test server.

My theory is that this._context.loadRequires is never calling deferred.resolve in this test server case (which would be why @doronrosenberg 's `dojo.some` line never gets called). I was hoping whoever wrote `context.loadRequires` to be async could take a look... I've not tried yet, but I'm guessing stepping through the debugger is going to disrupt the timing and cause the issue to go away.

**Comment by peller** [comment]
in order to not get in the then function, either the deferred is getting rejected and not logged (an error condition) which doesn't seem likely given the code, or there's faulty logic where deferred are getting created but never fired at all.

**Comment by aerwin** [comment]
@peller @doronrosenberg 

Putting in break points generally disrupts the timing, so I had put some trace in to help debug when running from the server. And, as far as I can tell `_create` in `DataStoreBasedWidgetInput` is not called in the case where we get just the cross-hair and need to click a 2nd time.  This is slightly different from the conclusion I had drawn before trying to use breakpoints (where I incorrectly thought `_create` was called but the promise for `this._loadRequires` was never fulfilled).

```
_create: function(args) {   
        if(this._data.length !== 2){
            console.error("DataStoreBasedCreateTool:_create incorrect number of items in this._data.");
            return;
        }

        if (this._debug) {
            console.error("!!!!!!!!!DataStoreBasedCreateTool::_create BEFORE this._loadRequires()");
        }
        this._loadRequires().then(dojo.hitch(this, function(results) {
            if (this._debug) {
                console.error("******** DataStoreBasedCreateTool::_create ALL promises fulfilled!");
            }
            if (results.every(function(arg){return arg;})) {
                // all args are valid
                this._getCreateCommand(args).then(function(command) {
                    this._context.getCommandStack().execute(command);
                    this._select(this._widget);
                }.bind(this));
            } else {
                console.error("DataStoreBasedCreateTool:_loadRequires failed to load all requires");
            }
        }));
    },
```

Backing up to `CreateTool` (which calls `_create`) it would appear the promise for `this._requireHelpers` is not being fulfilled:

```
all(this._requireHelpers(this._data)).then(function() {
            this._create({parent: parent, index: index, position: position, size: args.size});          
        }.bind(this));
```

**Comment by aerwin** [comment]
@JonFerraiolo @jhpedemonte 

--> M8

My latest theory (based on my last update about not getting into the `_create` function of `DataStoreBasedCreateTool`) is when the cache is empty that the `CreateTool` is getting into the state consistent with the click-drop approach (e.g., click on widget in palette and then separately click on canvas). But, I don't know a lot about that code logic, so probably time to finally punt on this for M7.

**Comment by JonFerraiolo** [comment]
Interesting theory! If it is possible to recreate at will, then I would debug by putting `console.log()` and `console.trace()` messages in CreateTool.js around code that changes the value of `this._mdPosition`. CreateTool.js assumes it's a click-twice approach if `this._mdPosition` has a value whenever it receives a mousemove event. `this._mdPosition` is cleared in `deactivate()`. 

I wouldn't be surprised if our whole drag/drop logic (which tracks mouse events across two frames) happens to work most of the time but isn't completely robust. That particular code hasn't been touched much since the smash/dojoy days, whereas most of the other visual editing code has been rewritten at least once.

Note that the drag/drop logic from widget palette to canvas is a bit convoluted. Some of that logic is documented on the github wiki. This page has some information about how the code works: https://github.com/maqetta/maqetta/wiki/Widget-Palette

**Comment by peller** [comment]
While it could be drag/drop logic, I'd suspect the logic that tries to asynchronously load the metadata helpers during the drag (something which wouldn't be an issue with a warm cache, and perhaps less of an issue if you took longer to create by clicking instead of dragging)

I'm scratching my head over the logic (I probably wrote) at the end of _requireHelpers:

```
            if(!dojo.every(data.children, function(c){
                return promises.concat(this._requireHelpers(c));
            }, this)){
                return promises;
            }
```

I don't understand the !dojo.every.  Perhaps I meant to reassign promises=promises.concat(this._requireHelpers)?  Could it be dropping helper promises?  That would suggest the promises firing prematurely (and perhaps create failing because the helper isn't ready) rather than the promise failing to fire at all.

Sounds like instrumenting requireHelpers would be in order.  @aerwin, feel free to assign to me and I can look at it over the weekend.

**Comment by billreed63** [comment]
This is working on 
Version: 7
Date: Nov 11, 2012 8:45:31 PM
Build: c7a79624a47c023...
