### ISSUE TITLE
Select/drag rich text widget - loses some content

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2434]
- New HTML File
- Add 2 DIV's. Set height of each DIV to 100px (or whatever, doesn't matter)
- Drop a Rich Text widget into first DIV, set text to 3 lines: aaa, (bulleted) bbb, (bulleted) ccc, click OK
- On canvas, drag the Rich Text widget from first DIV into second DIV

Result=> The bbb and ccc are dropped, only the aaa remains

**Comment by doronrosenberg** [comment]
@JonFerraiolo It seems that the `<li>` nodes aren't getting a _dvWidget, so this code fails:

```
var w = require("davinci/ve/widget").byNode(node);
```

In HTMLWidget.js::getChildrenData.  Not sure if this is a parser issue or if richtext needs a custom helper for this.
