### ISSUE TITLE
*DataList: SmartInput space handling problems

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2435]
@aerwin, @doronrosenberg 

Major problem around space handling with the *DataList widgets.

If you enter `abc, def` (with a space), the code seems to believe the target view is named `def` (with a space), and therefore when you run the app, pressing on the arrow doesn't actually result in a view change. So, when you enter the *DataList smartinput, don't put a space after the comma.

But it's worse. If you enter `abc,def` into SmartInput, and then click OK, and then double-click again to change some of the values, the SmartInput logic adds a space after the comma, and SmartInput shows `abc, def`. If you click OK without removing the spaces after the comma, things break again.

**Comment by doronrosenberg** [comment]
Aren't we planning for better smarinputs for those widgets?  Those would solve this issue

**Comment by JonFerraiolo** [comment]
sure, but I think we should look to see if there is a quick patch we can make in case we find ourselves doing a dot release in next couple of weeks because the current state of affairs with this feature is very bad

**Comment by JonFerraiolo** [comment]
Here is some of the code causing the space problems.

davinci.dojo_1_7/WebContent/metadata/dojo/data/DataStoreBasedWidgetInput:185 always adds an extra space after each comma:

```
                        value += ', ' + item.moveTo[0];
```

davinci.dojo_1_7/WebContent/metadata/dojo/data/EdgeToEdgeDataListInput:77 takes everything after the comma and stuffs it back into the datastore:

```
            var cols = rows[r].split(',');
            var item = {};
            item.label = cols[0];
            if (cols[1]){
                item.moveTo = cols[1];
```

I suggest that we use `dojo.trim()` on both ends of the transaction:
- In DataStoreBasedWidgetInput:185: `value += ', ' + dojo.trim(item.moveTo[0]);`
- In EdgeToEdgeDataListInput:81: `item.moveTo = dojo.trim(cols[1]);`

**Comment by doronrosenberg** [comment]
@JonFerraiolo sounds good to me

**Comment by billreed63** [comment]
I agree with the change to EdgeToEdgeDataListInput as it is the out bound data that we use to update the widget. But I think the inbound (DataStoreBasedWidgetInput) should display exactly what is item.moveTo if the item.moveTo has 20 spaces we want that display so the user sees what is in the moveTo, if we clean it up before we display it the user might assume that the input is correct and cancel out of the smartInput instead of pressing ok to update the widget.
