### ISSUE TITLE
Working copies for app.css and other non-html files

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#244]
I added a new style rule to app.css and then changed a property targeting this
new rule, but did not save the HTML file yet. I then opened app.css and I don't
see my change yet in app.css. But if I close app.css and then save my HTML
file, and then reopen app.css, the change is in app.css.

Need to think this through...

------- Comment #1 From Jon Ferraiolo 2011-01-10 18:59 [reply] -------
I researched this and here is how I believe things are working today:
- When you open an HTML file for editing in visual editor (e.g., file1.html),
  we create a file1.html.workingcopy and as the user changes the HTML file, we
  update the workingcopy until they give an explicit "Save" command, at which
  point we commit the changes to the original file (file1.html)
- In page editor, if we make CSS changes to the theme CSS files, we create
  temporary workingcopies for the theme CSS files that are not committed until
  the user saves the HTML file.
- In theme editor, if we edit the theme (therefore changing the theme CSS
  files), we create temporary workingcopies that are not committed until the user
  saves the theme.

BUT...
- If you edit CSS or JS files with the source editor, there are no working
  copies. The changes appear to get committed "immediately" (i.e., whenever
  client tells server about the update), despite the fact that daVinci still
  shows an asterisk on the editor tab since the user didn't issue a save command.
- If you use the page editor's Add Style Rule feature, the new style rule is
  added to app.css "immediately" (i.e., with next update message from client to
  server) even though the user hasn't issued a save command for either app.css or
  the HTML file.

Here is what I think should happen for the daVinci 1.0 release:
- Any changes to any files should happen on workingcopies
- Workingcopies only get committed when the user issues a Save command (details
  in subsequent bullets)
- Save commands on HTML files commit any pending CSS file changes
- Save commands in CSS and JS source editors commit any pending JS and CSS file
  changes
- Our documentation will need to explain the above rules. 
- It is possible that a source editor, the page editor and the theme editor
  might all be changing the same file at the same time. We have no client-server
  sync'ing logic in daVinci right now. For daVinci 1.0, we should put in
  something to keep the source editing of app.css to be in sync with any changes
  to app.css that might happen via the page editor (e.g., add new rule). 

After daVinci 1.0, we should consider changing these rules. We might want to
change from individual file saves to workspace-level saves, where we might look
at using Git under the hood to somehow log each user change as a new revision
in Git and then label/tag each explicit workspace-save action. Also, we need to
look at robust client/server sync'ing to deal with the situation where userA
and userB might be changing the same file at the same time.

------- Comment #2 From Jon Ferraiolo 2011-01-12 12:50 [reply] -------
Another fix we need to make in the area of workingcopies: with 0.7, if you
click Preview-in-Browser, we commit any pending changes to the currently open
HTML file, as if the user clicked the Save button. But the user hasn't clicked
the save button, so this is wrong. Instead, preview in browser should work off
of the current workingcopy HTML file.

------- Comment #8 From Jon Ferraiolo 2011-03-17 11:25 [reply] -------
Moving this to a P3. We'll want to take a run at this before 1.0, but we can
live with what we have for 0.8. (Should be about the same behavior as 0.71)

**Comment by JonFerraiolo** [comment]
-> M7/Prio-Med. This is an important architecture issue, but it might be too late in cycle to try to address in M7.

**Comment by JonFerraiolo** [comment]
@billreed63

**Comment by JonFerraiolo** [comment]
-> @billreed63 - do we still have this issue? Feel free to push to M8 if it's still a valid problem.

**Comment by billreed63** [comment]
This issue has been resolved at some point in the past
