### ISSUE TITLE
Project preferences: either get working (with test plan) or remove from UI

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2447]
@jonferraiolo: Do either of you know whether the Project Preference for the themes folder (default: themes/) actually work, or at this point is changing the themes folder an unimplemented feature? If unimplemented, is there an issue to implement? If implemented, is there a test plan for the feature?

@childsb: It's unimplemented in most spots.  I believe most of the ThemeEditor code makes assumptions to its location, and things like cloneTheme, findTheme, and some of the theme metadata functions do check.

For M7, either we should get all preferences working, or remove the preferences that aren't yet working.

@billreed63

**Comment by childsb** [comment]
Hidden for now.
