### ISSUE TITLE
Some sample files not migrated

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2451]
@aerwin, @doronrosenberg, @billreed63 

Test plan for Gridx columns says to load this file: sample_data/sampleManyColumns.json

In my migrated workspace from M6, this file doesn't exist. When I run the build as Guest user, the file is there. 

I'm not sure whether there are other sample files that haven't been migrated.

**Comment by jhpedemonte** [comment]
Also **Sample3-mobile.html**.

What action do we want to take here?  Should we copy these files into migrated projects, or just let it slide for now?

**Comment by JonFerraiolo** [comment]
Let's copy the missing files into existing user workspaces.
