### ISSUE TITLE
Theme editor dirty bit inconsistency

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2452]
1. Clone Dojo theme and name something like "myclaro"
2. Close new theme
3. From the Open menu, choose Theme Editor... and open "myclaro"
4. Close the theme (note there was no dirty bit set, so theme editor closes without additional prompt)
5. Find myclaro.theme in the File palette and double-click on it
6. Note editor is marked dirty (despite no changes) and when you try to close theme editor you get warning that you'll lose changes

**Comment by billreed63** [comment]
fixed by #2453
