### ISSUE TITLE
Theme editor selection isn't always reflected in props palette

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2454]
1. Clone claro theme
2. Select text box and change property (say font size to 25px)
3. Select button and values in props palette reflect text box settings (except text-align gets changed to "center" to match button)

![GitHub Logo](http://i.imgur.com/fhk7F.png)

I'm on Chrome/Mac

**Comment by billreed63** [comment]
this is related to #226

**Comment by aerwin** [comment]
I'm not sure I understand how this is related to #226... in this case I select the button and it's showing me what I had set on the text box. I thought #226 was that some properties don't effect the rendering when changed?

**Comment by billreed63** [comment]
Because the widget does not have a rule that is being set for that widget's property cascade does not refresh the field.

#226 is really a catch all to handle the properties palette correctly for each widget.

**Comment by JonFerraiolo** [comment]
@aerwin We should still try to fix this bug for M7 if we can, even if we can't do #226 for M7. My hope is that the property palette refresh for the property is something we can fix without providing a comprehensive fix for #226.
