### ISSUE TITLE
Theme editor: changing style of one widget can affect ability to select another

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2455]
On Chrome/Mac...
1. Clone claro theme
2. Select button and change font size to 25px
3. Try to select text box by clicking on it and tooltip widget gets selected (I'm guessing because changing font size of button made toolbar bigger pushing widgets down page. Reloading theme seems to clear this up.)

![screenshot](http://i.imgur.com/xQvnc.png)

**Comment by billreed63** [comment]
wfm, what browser and machine is this on?

**Comment by aerwin** [comment]
first line of problem report stated: "On Chrome/Mac..." I'm pointing at the server we were supposed to run test matrix on today.

**Comment by billreed63** [comment]
I can only make this happen on 9.41.33.118 , it seems to be a selection problem so I am send it @JonFerraiolo

**Comment by JonFerraiolo** [comment]
yes, good to send to me. I suspect there might be a geometry calculation issue. In the page editor, I gutted/rewrote everything having to do with computing widget location to fix various bugs, including unreliable results produced in some cases by Dojo's various routines (e.g., dojo.position). I wouldn't be surprised if there is something in the theme editor code that I missed when doing my various cleanups.
