### ISSUE TITLE
Theme editor: if clone many times, then can't clone default themes anymore

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2457]
Chrome/Mac...

Kind of stumbled on this one trying to provide reproducible scenarios for some other issues:
1. Clone a theme many times and give it a name that puts it toward top (e.g., clone claro into "claro2", "claro3", etc.)
2. At some point, when you try to clone claro you won't see the original claro on the list (and also won't be able to scroll or arrow to it)

![screenshot](http://i.imgur.com/1mCNa.png)

**Comment by billreed63** [comment]
I am not seeing this issue on dojo 1.8, so I am closing. If anyone sees this issue please reopen
