### ISSUE TITLE
background-image scrollbar partially obscured	

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#246]
On Win/FF, the scrollbar on the popup dialog for background-image is partially
obscured. 

Definitely can wait to 0.8 to fix this. For me, it is operational on Win/FF and
Win/Chrome. Haven't tried on Mac browsers yet.

bug: 7194

**Comment by JonFerraiolo** [comment]
Priority-Medium to investigate to see if it still exists. If it still exists, then we need to assess the priority for fixing it.
