### ISSUE TITLE
Upload files: parent folder is always blank

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2460]
select a folder, like "sample_data"
right-click to upload a a file.  Observe that the label "parent folder:" in the dialog has no text following it
Upload a file.
The file will end up in the folder, even though this was not indicated.

**Comment by aerwin** [comment]
--> no milestone to M7

**Comment by jhpedemonte** [comment]
This seems to be working for me, at least on Firefox.  Can you retest please.

**Comment by peller** [comment]
does appear to be working now
