### ISSUE TITLE
FF: exception selecting root node in outline

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2461]
Unsure how to reproduce, but I had a theme file, a css file, and an html file open, and I clicked on the root node in the outline when looking at the html file

_262 is the local variable "model", and it has the value Object { id="myapp", label="application"}
In CSSEditorContext.js: _262.elementType is undefined 

```
if(_262.elementType.substring(0,3)=="CSS"){
```

_selection(_261=[Object { model={...}, add=false}])
_385()
(?)()
emit(_41a=Object { declaredClass="uniqName_0", on/davinci/states/state/changed=function(), on/davinci/ui/libraryChanged/start=function(), more...}, type="/davinci/ui/selectionChanged", _41b=[Object { model={...}, add=false}])
emit(_41e=Object { declaredClass="uniqName_0", on/davinci/states/state/changed=function(), on/davinci/ui/libraryChanged/start=function(), more...}, type="/davinci/ui/selectionChanged", _41f=[Object { model={...}, add=false}])
emit(type="/davinci/ui/selectionChanged", _399=[Object { model={...}, add=false}])
publish(_3a2="/davinci/ui/selectionChanged", _3a3=[Object { model={...}, add=false}])
publish(_4c0="/davinci/ui/selectionChanged", args=[[Object { model={...}, add=false}], Object { contentDiv=div#dijit_layout_BorderContainer_5.dijitAlignClient, commandStack={...}, _isVisible=true, more...}])
publish(_e8a="/davinci/ui/selectionChanged", data=[[Object { model={...}, add=false}], Object { contentDiv=div#dijit_layout_BorderContainer_5.dijitAlignClient, commandStack={...}, _isVisible=true, more...}])
(?)(item=Object { id="myapp", label="application"}, _21d7=false)
_385()
_selectNode(node=[Widget davinci.ui.widgets._ToggleTreeNode, davinci_ui_widgets__ToggleTreeNode_124] { _attachPoints=[8], _attachEvents=[6], _connects=[21], more...})
focusNode(node=[Widget davinci.ui.widgets._ToggleTreeNode, davinci_ui_widgets__ToggleTreeNode_124] { _attachPoints=[8], _attachEvents=[6], _connects=[21], more...})
_onClick(_25fc=[Widget davinci.ui.widgets._ToggleTreeNode, davinci_ui_widgets__ToggleTreeNode_124] { _attachPoints=[8], _attachEvents=[6], _connects=[21], more...}, e=click clientX=118, clientY=111)
_25e(args=[[Widget davinci.ui.widgets._ToggleTreeNode, davinci_ui_widgets__ToggleTreeNode_124] { _attachPoints=[8], _attachEvents=[6], _connects=[21], more...}, click clientX=118, clientY=111], a=undefined, f=function())
_onClick(item=[Widget davinci.ui.widgets._ToggleTreeNode, davinci_ui_widgets__ToggleTreeNode_124] { _attachPoints=[8], _attachEvents=[6], _connects=[21], more...}, _ff9=click clientX=118, clientY=111)
_onClick(evt=click clientX=118, clientY=111)
(?)()

**Comment by aerwin** [comment]
--> no milestone to M7
--> @doronrosenberg 
--> prio low

Maybe we can close if not reproduced in 2 months?
