### ISSUE TITLE
R&C: Review keeps reopening when I refresh page (even if I closed it)

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2463]
In R&C testing this morning with @peller & @billreed63 , it seems that if I use the link in a review invitation to open a review that it will always get reopened when I reload the browser page (even if I've closed the review before reloading the page). It's like a cookie isn't being cleared.

**Comment by JonFerraiolo** [comment]
@aerwin - can you investigate this one, and if someone else would be better to tackle this, then please reassign to that person.

**Comment by aerwin** [comment]
-> @childsb  Taking a look at when this might have regressed, I suspect this is related to commit 14a3498ac303a49a4c8c1a35705489d53397cc9b where the path was removed from pagedesigner.html:

```
dojo.cookie("davinci_designer", null, {expires: -1, path:"/"});
dojo.cookie("davinci_version", null, {expires: -1, path:"/"});
```

So, routing to @childsb .

**Comment by aerwin** [comment]
@childsb 

It was actually @childsb 's commit d6c5a8704a56e7c1c53ababaf7c82e1d97a63fb5 where path was removed (not 14a3498ac303a49a4c8c1a35705489d53397cc9b as I wrote a couple months ago). Regardless, I'll fix this current issue by putting path back in.

**Comment by aerwin** [comment]
Closing with above commit.
