### ISSUE TITLE
Typo in Tutorial "Building a Task Manager Part 2"

### ISSUE THREAD

**Issue by gers32** [maqetta/maqetta#2466]
Tutorial [Building a Task Manager Part 2] > [Configure the "Task Added" State] > [2. In the Outline palette, under the TabContainer close the eye icon for the MultiSelect widget.]

=> "close the eye icon" should be "open the eye icon".

**Comment by JonFerraiolo** [comment]
Thanks for reporting this!

**Comment by peller** [comment]
thank you for spotting this!

@JonFerraiolo
