### ISSUE TITLE
Put ID on Tree - kaboom

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2469]
- New HTML file
- add a Tree

Problem #1: The Properties palette shows ItemFileReadStore as selected, not the Tree
- One way or another, select the Tree rather than the ItemFileReadStore
- In Prop palette, set ID to a value

Problem #2: Tree disappears. (In fact, if you have other widgets, some of them will also disappear)

You can put an ID on a Tree in source view.

**Comment by JonFerraiolo** [comment]
@aerwin @doronrosenberg @jhpedemonte

**Comment by billreed63** [comment]
I can't reproduce this on windows/chrome, are you still see this problem?

**Comment by doronrosenberg** [comment]
I can reproduce this on Firefox windows.

**Comment by JonFerraiolo** [comment]
I just reproduced in Mac/Chrome. Note that there are multiple problems. First, after dropping a new Tree widget, the Properties palette shows an ItemFileReadStore as the current selection, not a Tree. (Which of course is a bug) To select the Tree requires a few steps. You have to unselect all (or select something else), then use the Outline palette to select the Tree. Once you do that, and try assign an ID using to type-in field at the top of the properties palette, then kaboom.

**Comment by billreed63** [comment]
The issue is SmartInput not DnD, I was canceling out of the SmartInput and the Tree selection is correct.
Only when you change the tree through SI does the selection get messed up.

What changed in SI?

**Comment by billreed63** [comment]
I think the issue is that SmartInput for Tree only changes the ItemStore  Using the ModifyCommand.
ModifyCommand publishes  "/davinci/ui/widgetPropertiesChanged" with the ItemStore being the widget. So the properties palette and possibly others that list to that message think the selected widget is the item store not the tree.
