### ISSUE TITLE
'class' attribute should include dropdown menu

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#247]
It would be nice if the 'class' property included a dropdown that would show
all classes that already exist in the user's document and allow the designer to
pick one of those classes instead of having to retype the classname from
scratch.

Maybe there is a Dojo widget (FilteredSelect?) which would allow the user to
start typing and then show a menu of all classes that match what has been typed
so far.

**Comment by JonFerraiolo** [comment]
Reassigning to @childsb

**Comment by JonFerraiolo** [comment]
Pushing to M5, Priority-Med

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
Reassigning -> @doronrosenberg

**Comment by doronrosenberg** [comment]
So the list would just include classes already being used in the document using className="", not all available classes right?

**Comment by JonFerraiolo** [comment]
I think this is what you said, but to be clear, the effect should be to only show classes that appear in the HTML file's source. If a file looks like this:

```
<body>
  <div class='myclass1'>
    <span dojoType='dijit.form.Button' class='myclass2'>Click me</span>
  </div>
</body>
```

then the dropdown should show `myclass1` and `myclass2`, and should not show any of the dojo classes (e.g., dijitButton).

**Comment by doronrosenberg** [comment]
The tricky part is that we want to exclude anything on the body.

**Comment by JonFerraiolo** [comment]
@doronrosenberg  Have you thought about traversing the model for the list of class names instead of traversing the currently loaded HTML document (i.e., the doc showing in the iframe). The model should only show the classes that the user has defined.

@jhpedemonte

**Comment by doronrosenberg** [comment]
@JonFerraiolo That is what I am doing, using visit() on the model.  The model though still has the body tag in it with the claro class for example.
