### ISSUE TITLE
No error message if you try to create a project that already exists

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2470]
Just now, I tried to create "eproj2" with the Eclipse checkbox on, and Maqetta just sat there with the New Project dialog on the screen. Turns out I already had a project named "eproj2".

Can we please post some sort of error telling user that the project name already exists? It looks like the New Theme command just uses an alert() if you try to create a theme with a name that is already in use.

**Comment by jhpedemonte** [comment]
No alert() please!  Need to get away from that crap.

Best thing is to have a validator on the text box for the project name, and disable the create button if the project already exists.

**Comment by peller** [comment]
agreed.  -1 on alert.

validation is great, but not 100% reliable.  There's still the possibility of a server error, either because the name was taken or for some other reason.  We need a consistent way to report errors, in dialogs, and in general.

@doronrosenberg

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg - can you please see if there is a safe fix for M7?
