### ISSUE TITLE
Include app.js in each user workspace (companion to app.css)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2475]
@jhpedemonte @peller @billreed63 @aerwin @childsb 

In talking with users, they asked why don't we set up our HTML file so that they include an `app.js` file in addition to the existing `app.css`. Even for mockups, it is common that users will want to include a small bit of JavaScript. One common scenario is they want to put an onclick handler onto a DIV, and that handler would choose a different tab in a TabContainer or switch to a different application state. The common scenario is that a designer would work with a developer who would provide a snippet of JavaScript (typically a function) to include in `app.js` and instructions for what to type into the `onclick` field in the Properties palette (typically, invoking a function).

**Comment by JonFerraiolo** [comment]
One more thing - if we include `app.js`, we can quit including `Sample.js`

**Comment by peller** [comment]
Perhaps we could write a helper for SCRIPT (and LINK) tags such that they could prompt for a file and open a new editor of the appropriate type?  I don't think we should be including .js files boilerplate, like we do for our app.css.  The .js file may not be necessary, and the exact structure or usage is best left to the user (supporting an AMD authoring model may be even wiser)  I'm not even sure we should be including app.css boilerplate, if we were able to remove the 100%x100% hack.

**Comment by JonFerraiolo** [comment]
The two main reasons for app.css: (1) we need a CSS file into which we stuff new CSS rules created by the Properties palette, (2) users sometimes want to define CSS rules by hand rather than use the Properties palette.

When talking with users, they easily grok the app.css and app.js approaches and (what I'm hearing) say it's a good idea to provide a standard file that's just there. I've heard this serves similar purpose to companion script files that many UI build systems automatically provide. VisualBasic had a similar scheme, and so did Silverlight's tools (with their code-behind files).

**Comment by peller** [comment]
if we start injecting JS routines, I'd agree, maintaining them in a separate file makes sense.  So far, what we have probably doesn't qualify -- one-liner callbacks like the I/O work done by @billreed63   If users write their own JS, they likely should be factoring it out themselves and maintaining their own files.

**Comment by JonFerraiolo** [comment]
I have this mostly implemented in branch AppJs, with this as a most recent commit: https://github.com/maqetta/maqetta/commit/b04ff22bdcd734a489279776f61d42556b6f31f3. Not merging until I can verify that I didn't break the build process with my changes.
