### ISSUE TITLE
Dead file - davinci.ui.widgets.FileFieldDialog

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2480]
@jhpedemonte @JonFerraiolo 

Going through all the dialogs, I found davinci.ui.widgets.FileFieldDialog which doesn't seem to be used anywhere (but included in a few places).

**Comment by JonFerraiolo** [comment]
@doronrosenberg FileFieldDialog is still used by BackgroundDialog.js via its template HTML file davinci/ve/widgets/templates/BackgroundDialog.html. Would be great if you fix up that code, too. 

The way to bring up FileFileDialog in the product:
- Create a DIV
- In Props palette, open up Background section
- Click on one of the "..." buttons to bring up Background dialog
- Under background-image type, choose "image"
- Then click on the "..." button to the right of the URL field

**Comment by peller** [comment]
I think we removed several uses of this module, but that one does remain. In particular, I tried to remove dependencies on ViewLite/WidgetLite which used to be much more common.  This may be one of the last remaining uses.  It would be good if we could remove that, too.  #1088
