### ISSUE TITLE
Banner wrapping to second line on windows

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2490]
The text on the right side of the banner is wrapping to a second line on chrome/win the "out' from "log out" is below "welcome"

**Comment by JonFerraiolo** [comment]
We have this problem in Preview 6 that users are running?

**Comment by billreed63** [comment]
is that a question, the answer is yes I just checked maqetta.org preview 6 has this problem I am running chrome 21.0.1155.2 dev-m

**Comment by billreed63** [comment]
SmartInput on Tree also has this problem the Ok and Canel buttons are stacked

**Comment by JonFerraiolo** [comment]
@billreed63 - can you get into debugger and figure out what's wrong and how to fix? I'm away from my PC until Thursday.

**Comment by billreed63** [comment]
@JonFerraiolo @jhpedemonte  do we want to update preview 6 on maqetta.org with this fix? It was a change to davinci.css

**Comment by JonFerraiolo** [comment]
Thanks for the fix. I haven't actual had a chance to see the bug in action, but based on the description, I think we have to do an update. If we are going to do an update, we also might consider including some other fixes, such as the Tree ID issue.

**Comment by billreed63** [comment]
If we include the Tree fix we should do a quick regress, I was a little more aggressive with that fix due to the fact we are early in preview 7
