### ISSUE TITLE
Multiple select drag-a-copy - doesn't keep widgets in same order

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2497]
- New HTML FIle - iphone
- Add a View, then a RoundRectCategory and a RoundRectList
- Select the RoundRectList, then select the RoundRectCategory
- Drag a copy by holding down Alt key while dragging

Result=> cloned widgets have the cloned RoundRectList first, then the cloned RoundRectListCategory

**Comment by peller** [comment]
see #963, #1445 (circularly-referenced dup list?)
