### ISSUE TITLE
maqetta claro vs dojo claro

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#25]
There are a few differences between the claro that ships with Dojo 1.5 and the
version of claro that we ship with Maqetta. We need to have a long-term
strategy for how to deal with the small differences that we have had to
introduce.

Of course, the ultimate goal is that we have to make zero changes, but there
might be short-term challenges that prevent the ideal from happening right
away.

Worst case is that the deltas are not documented (i.e., no docs on what changes
were made and why) and not automated (i.e., changes are done by hand, and have
to be reintroduced into new versions of Dojo by hand).

**Comment by JonFerraiolo** [comment]
@billreed63: can we close this? Aren't we using dojo claro now that we have delta themes? Or maybe we aren't yet referring to Dojo's claro and instead have an exact clone of dojo claro now? Maybe the recent changes that @jhpedemonte is making to support library dependencies might impact our ability to address this issue?

Whatever, could you please close, update and open any issues in this space so the issue tracker is up to date in this area?

**Comment by billreed63** [comment]
#2673 is a better description of the current state, so I will close this one and leave the other open

**Comment by billreed63** [comment]
close
