### ISSUE TITLE
We are not properly destroying dialogs (leaking dijits)

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2500]
@jhpedemonte @peller 

In Workbench::showModal, we call destroy on Dialog, which means the contents are not being destroyed.

Changing it to use destroyRecursive works, but we get a js error:

```
this.focusNode is undefined
http://192.168.1.126:8081/maqetta/app/dijit/form/_ButtonMixin.js?@revision@
Line 45
```

Any thoughts on how to fix that?  Steps to reproduce (with the destroyRecursive change):
- New HTML File
- Press OK

**Comment by doronrosenberg** [comment]
OK, I think this is actually not what I thought it was - I think this is because the 2 targets that generate the new html file dialog are either a dropdown menu (which goes away before the dialog is opened) or the Welcome page, which is hidden as well once OK is pressed in the dialog.

The dialog tries to refocus the previously focused item when it is closed.  Though it is odd that no error occurs when you press cancel.

**Comment by peller** [comment]
It's probably calling blur on the item that previously had focus, which no longer exists.  I think you need to call hide() to transfer focus before you destroy the Dialog.  Cancel might do that.

**Comment by doronrosenberg** [comment]
I am already hiding the dialog before destroying.    I even moved the destroyRecursive to onHide on the dialog, which causes errors in fx.js.  Very odd
