### ISSUE TITLE
Move Samples into samples folder, virtualize

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2503]
@JonFerraiolo @jhpedemonte 

Among other things, this will help with the builder (#27) to make it easier for the builder to skip sample code.  OTOH, I still like the idea of putting the sample code in its own plugin so it could be built and treated just like user code, while not polluting the file directories for each project.

**Comment by JonFerraiolo** [comment]
-> @childsb

**Comment by childsb** [comment]
i've got the code ready to go for this bug, but.. how do we want to handle the samples?  Will they always be read only?

We dont really have a UI path for copying libraries into the workspace as read/write.

one option is to copy library files to the workspace if the user saves them.

**Comment by peller** [comment]
I'd be ok if the user had to do a save as... to modify.  But what would happen if the user just started editing?  Would there be a problem saving a "working copy" file in the interim?

**Comment by JonFerraiolo** [comment]
> i've got the code ready to go for this bug, but.. how do we want to handle the samples? Will they always be read only?

I was thinking all of the pre-loaded samples files would all be read-only. If a user wanted to customize one of the files, they would have to do a SaveAs operation.

> We dont really have a UI path for copying libraries into the workspace as read/write.

Right, if it's a magical redirect thing, it should be read-only.

> one option is to copy library files to the workspace if the user saves them.

not sure what you mean here. If you mean the file becomes read/write after a SaveAs operation, then I'm with you.

**Comment by childsb** [comment]
The current behavior (with my changes) is that the user can open/modify the library sample, but is unable to save or have a "working copy".  Browser refresh opens file but any changes are lost.

Save as different file name works.  However, save with same file name would need some fix up.

**Comment by JonFerraiolo** [comment]
@childsb - We need to handle app.js and app.css differently. (app.js is a new file that will be merged into master soon, maybe in next couple of hours) These files need to be (read/write) copies into users project versus all of the other things in the `maqetta-core-server/WebContent/samples/` folder. Maybe we need two different folders, one for things that get linked into user projects as magic redirects, and the other one for things that copied into user projects as actual read/write files. 

Anyways, `maqetta-core-server/WebContent/samples/` is not the most meaningful name. Maybe split into two folders:
- `maqetta-core-server/WebContent/InitialContentReadOnly/`
- `maqetta-core-server/WebContent/InitialContentReadWrite/`

I'm hoping this won't be too difficult to do. Use the old code for the ReadWrite stuff, and the new code for the ReadOnly stuff.

**Comment by peller** [comment]
Sounds magical.

I was thinking of a folder simply named 'samples' that would appear as a 'samples' folder in the user's workspace.  If the user wants to modify and save as, they can create their own folder or save it anywhere they are permitted to.

**Comment by JonFerraiolo** [comment]
> I was thinking of a folder simply named 'samples' 

Yes, my thinking too. If you combine with my proposal above, you'd have:

```
maqetta-core-server/WebContent/InitialContentReadOnly/
    samples/
        Sample1.html
        Sample2.html
        Sample3-mobile.html
        SampleBanner.jpg
        carousel_data.json
        htmlSample.json
        images/
            (many files)
        mobile_edge_to_edge_or_round_rect_data_list.json
        sample.csv
        sampleManyColumns.json
maqetta-core-server/WebContent/InitialContentReadWrite/
    app.css
    app.js
```

**Comment by JonFerraiolo** [comment]
One more thing. I have implemented a new feature, New HTML File from Template, where we have a new `templates/` folder in each project, and users can put their favorite HTML files into that folder, and these HTML files will appear when the user issues a New HTML File from Template.

The reason for bringing this up in this issue is that we will have yet another folder. Users need to be able to save into this folder. Ideally, I'd like the built-in templates that ship with Maqetta to be auto-magical redirects, and any new templates that a user saves would be read/write, but maybe having it both ways isn't feasible, and `templates/` has to be either read-only in its entirety or read-write in its entirety. If so, then I would go for read-only.

But that brings up another problem - the findResource server command doesn't seem to list read-only files. For the templates feature, I need findResource to return the list of files in the `templates/` folder.

**Comment by childsb** [comment]
theres a maqetta.core.server/WebContent/project that contains all the files needed for each project.  Project non sample code (app.js and app.css) should go in there for consistency.  It already houses the maqetta specific project required library.  i can add "common" for for app.css and app.js and set the initialUserFiles extension so they're copied in (and not virtual).  samples should probably be moved there too ((i'll do that))

also, i'll also move the samples into a (virtual) samples folder in the users workspace

**Comment by childsb** [comment]
I stuck with the InitialContentReadWrite, but moved under the project folder.
