### ISSUE TITLE
Parsing error - can't go into source view

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2508]
@billreed63 
- New HTML File
- Add 2 Tree widgets, make the content different so you can tell which tree is which
- Drag/drop the 2nd Tree in front of first Tree
- Save, close, reopen

=> Maqetta says unable to parse the file, go into source to fix. The reason is that the datastore for one of the trees is later in the file. (Note: if this Tree problem gets fixed, I would guess you could find some other way to trigger "unable to parse" message.)

But (the purpose of this bug)

=> if you click on source view icon, nothing happens.

**Comment by jhpedemonte** [comment]
Remind me again: why don't we just put the stores at the top of the file, above everything else?  How many bugs like these will we run into because we insist on putting the stores elsewhere?

**Comment by peller** [comment]
@JonFerraiolo, cannot reproduce this.  Was there a stack trace?
