### ISSUE TITLE
can't open CSS, JS or any other plain text file

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#2510]
1) login to maqetta
2) try and open app.css

notice that an empty editor comes up as if the orion source editor didn't attach to the DOM.

**Comment by JonFerraiolo** [comment]
@peller @doronrosenberg 

Works OK in Preview6.0.1. We must have broken something recently

**Comment by doronrosenberg** [comment]
From what I can tell, the editor widget is never being added to the DOM.

**Comment by peller** [comment]
@billreed63 

regressed here: 703f0b137a1402d43393665997e29f0a9085b435

**Comment by jhpedemonte** [comment]
Fixed now?

**Comment by peller** [comment]
fixed in 6efe4ead1675a64bf5a790032e871f44bb7b4d52
