### ISSUE TITLE
Exception after saving to different folder

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2512]
@childsb 

(Assigning to @billreed63 because I suspect this regression is related to his CSS file management cleanups. Maybe the code right now only works when saving into the root folder or maybe only when resources aren't moved around.)
- New HTML File
- Add a Button
- Save to root folder (e.g., project1/)
- Create new folder (e.g., folder1/)
- SaveAs into the new folder
- Switch to source view and wait a second

Result=> resource undefined exception in Factory.js:55 

What's going on is that there is an attempt to remove workingcopy for resource "project1/folder1/app.css" and that attempt is failing. But of course app.css is in `project1/` not `project1/folder1/`

Here is the stack trace:

```
Factory.closeModel (Factory.js:55)
declare.close (CSSImport.js:55)
declare.setText.visit.visit (HTMLFile.js:130)
declare.visit (CSSImport.js:28)
declare.visit (HTMLElement.js:462)
declare.visit (HTMLElement.js:462)
declare.visit (HTMLElement.js:462)
declare.visit (Model.js:149)
declare.setText (HTMLFile.js:128)
declare.handleChange (ModelEditor.js:30)
dispatcher.around.advice (aspect.js:189)
target.(anonymous function) (aspect.js:176)
onTextChanged (Editor.js:64)
dxt.doLater (doLater.js:41)
```

**Comment by billreed63** [comment]
The issue is that when we save the file to a different folder the source/model does not get updated correctly. The only `@import acc.css` does not get removed so when are attempting remove a working copy of a file that does not exist.

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="../lib/dojo/dojo/dojo.js" data-dojo-config="'async':true,'parseOnLoad':true,'packages':[{'name':'jquery-ui','location':'../../jquery-ui'},{'name':'yui','location':'../../yui'},{'name':'gridx','location':'../gridx'},{'name':'shapes','location':'../../shapes'},{'name':'clipart','location':'../../clipart'},{'name':'maqetta','location':'../../maqetta'},{'name':'idx','location':'../../idx'},{'name':'idxThemes','location':'../../../themes'},{'name':'widgets','location':'../../widgets'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dijit/form/Button"
]);
</script>
<style>@import "../themes/claro/claro.css";@import "app.css";@import "../app.css";
</style>
</head>
<body class="claro" dvFlowLayout="true" data-davinci-ws="collapse" id="myapp">
 <input type="button" data-dojo-type="dijit.form.Button" label="Button"></input>
</body>
</html>

```

**Comment by billreed63** [comment]
This was not a regression it just exposed an existing bug

**Comment by billreed63** [comment]
I fixed the exception but we still have the real issue of the extra app.css that does not exist
1) Do we want to add and app.css in the created folder?  if so this is related to #2401 
2) If we don't want an app.css in the subfolder we need to be smarter about adding app.css inot the html file

**Comment by JonFerraiolo** [comment]
Reassigning to me to investigate. I'm working on adding an app.js file to each user project (#2475) and I'm currently stuck on the "save to different folder" issue with app.js.
