### ISSUE TITLE
document.css sometimes not there for preview-in-browser

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2513]
@billreed63 - document.css isn't always in the source code. I don't have a reproducible scenario right now, but I've been running the old desktop tutorial on the latest code, and document.css is there in the page editor but not there for preview-in-browser, and there is no @import "document.css" in source view.

Is there a chance that your CSS reference counting cleanups aren't dealing with document.css completely?

**Comment by billreed63** [comment]
I think the problem is in the code in Context.js that adds document.css to the model

the code in context.js

```
var imports = this.model.find({elementType:'CSSImport'});
            for(var imp=0; imp<imports.length; imp++){
                if(imports[imp].url.indexOf('document.css') >= 0){
                    documentCssImport = imports[imp];
                }
                if(imports[imp].url.indexOf('themes/') >= 0){
                    themeCssImport = imports[imp];
                }
            }
```

Runs through the imports looking for URL's that contain themes/, so in our case the imports have

```
themes/claro.css
../../lib/dojo/dijit/themes/claro/claro.css
app.css
```

So the code selects the last url with the word "themes/" in it.

Then the code attemps to add the document.css using 

```
if(!documentCssHeader && themeCssHeader){
                    var themeCssRootArr = themeCssHeader.split('/');
                    themeCssRootArr.pop();
                    themeCssRootArr.pop();
                    var documentCssFileName = themeCssRootArr.join('/') + '/' + this.theme.className + '/document.css';
                    header = dojo.clone(header);
                    header.styleSheets.splice(0, 0, documentCssFileName);
                    this.setHeader(header);
                }
                if(!documentCssImport && themeCssImport){
                    var themeCssRootArr = themeCssImport.url.split('/');
                    themeCssRootArr.pop();
                    themeCssRootArr.pop();
                    var documentCssFileName = themeCssRootArr.join('/') + '/' + this.theme.className + '/document.css';
                    var basePath = this.getFullResourcePath().getParentPath();
                    var documentCssPath = basePath.append(documentCssFileName).toString();
                    var documentCssFile = system.resource.findResource(documentCssPath);
                    var parent = themeCssImport.parent;
```

So in this case it has the wrong path to the theme document.css

It is also not showing up in preview due to document.css not being added to the model #2378, which means it is not added to the source.

**Comment by billreed63** [comment]
Not a regression, the change to importing claro from dijit exposed this bug

**Comment by jhpedemonte** [comment]
Reproducible for me by:
1. Load Maqetta anew.
2. New HTML File.
3. Drop Dijit Button.  Notice font of text.
4. Click Preview.  Notice that font is different.

Preview does not have document.css in this case.
