### ISSUE TITLE
DIV gets width/height=100%

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2514]
@aerwin - did you make any initialSize changes for html.div? I thought you were only making fixes for Dojo widgets. Sending your way to see if this rings any bells. If not, feel free to send it back to me.
- New HTML File - desktop hi-fi page
- Drag out a ContentPane of about 200px by 200px
- Drag/drop a DIV into middle of ContentPane

Result=> DIV's width and height are set to 100%. Instead, they should not have values (and as a result use the CSS default value of auto, which in our case will result in block-element defaults of width spanning the parent container's widget and height being MAX(height-of-interior-content, min-height property)

**Comment by aerwin** [comment]
Yes, I made initialSize changes for some HTML elements. I can remove that for DIV (and other similar components).

**Comment by JonFerraiolo** [comment]
Yes, I'd have to see the details, but I would expect that I would leave all of the HTML elements as they were (which in most cases means we accept defaults) _EXCEPT_ table, which I think should have width:100% when added using flow layout.

**Comment by aerwin** [comment]
Fixed with above commit.
