### ISSUE TITLE
Closure problem with ToggleTree.js - prevents outline selection with 2nd file load

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2523]
@doronrosenberg 

I'm not sure what change caused this to regress from Preview6.
- Launch Maqetta with no files open
- Double-click on Sample1.html to open
- In Outline palette, open up the TabContainer and click-select either 2nd or 3rd ContentPane. Notice that click-select in outline causes the corresponding pane to be selected in the TabContainer
- Close Sample1.html
- Double-click on Sample1.html to re-open
- In Outline palette, open up the TabContainer and click-select either 2nd or 3rd ContentPane. 

Result=> No selection

After some time debugging, what I discovered is that there are multiple `_dndSelector` instances, one for Files palette, multiple ones for States/Scenes palette (which gets recreated upon various events), and then a new instance for outline for each HTML editor. (I traced through all of this by modifying the constructor `_dndSelector` and putting a "rand" property (Math.random) on each instance, and also putting console.trace() in the constructor).

The problem boils down to this code in ToggleTree.js:

```
            // Workaround for #13964: Prevent drag/drop from happening when user mouses down on scrollbar
            var mouseDown = dijit.tree.dndSource.prototype.onMouseDown;
            dijit.tree.dndSource.prototype.onMouseDown = function(e){
                if ((" "+(e.srcElement || e.target).className+" ").indexOf(" dojoDndContainerOver ") != -1) {
                    return;
                }
                return mouseDown.call(this.dndController, e);
            }.bind(this);
```

The problem is that we are creating a stack of onMouseDown routines with each open editor. For example, suppose you open Sample1.html twice as described above. If you put a breakpoint inside the onMouseDown inner function (and assuming you put a "rand" property on the instance object), you will see that the onMouseDown function gets called twice: first for the most recent dndController instance object, and then a second time for the previous dndController instance object (i.e., the one corresponding to the first time you opened Sample1.html).

As a result, when the original `dijit.tree.dndSource.prototype.onMouseDown` function gets called, the value of this.dndController is the object corresonding to the first editor (which no longer exists).

I thought it better to leave this to @peller rather than try to fix myself.

**Comment by peller** [comment]
@JonFerraiolo The code you show above is over one month old.  The instance object is now used instead of the prototype (#2179) so the nesting you mention should not happen.  I wonder where you would have seen this code recently?

The problem is no longer reproducible.

**Comment by JonFerraiolo** [comment]
Oh, very sorry about all of this. I'll bet I logged this bug while working in a branch on some new features, and wasn't aware that I was in a branch, and (very bad of me) didn't think to check the offending code versus master/trunk to see if this code had been fixed.
