### ISSUE TITLE
Rewrite Outline palette to use dojo.store

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2524]
Spin off from #750

**Comment by doronrosenberg** [comment]
One interesting part is supporting adding/removing directly on the model.  Which means listening to add/remove/modify/move/etc commands and mimicking those in the dojo.store.Memory.

**Comment by doronrosenberg** [comment]
Or we could just write our own dojo.story.api wrapper around the widget model, basically creating a thin wrapper.
