### ISSUE TITLE
Opening file in text editor doesn't show data

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2527]
1. In files palette, double-click on sample_data/sample.csv or sample.json
2. Text editor opens, but no data is displayed

Using Chrome on Mac.

**Comment by aerwin** [comment]
Actually, don't think file type matters... e.g., looks like neither css nor js work either. So, changing title to "Opening file in text editor doesn't show data"

**Comment by JonFerraiolo** [comment]
Dupe of #2510?

**Comment by aerwin** [comment]
Yep, sorry... closing...
