### ISSUE TITLE
No resize handles for widgets with "resizable": "height" in metadata

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2529]
1. New HTML file
2. Drag/drop Vertical Slider onto canvas
3. With widget selected, you can resize it in the vertical direction. But there are no resize handles on top and bottom edges.

In contrast, widgets with "resizable": "width" in metadata have resize handles on the left and right edges.

Also, we will soon have another widget (&lt;tr&gt;) that will have "resizable": "height" specified in metadata.

**Comment by JonFerraiolo** [comment]
-> me M7/High
