### ISSUE TITLE
Tree indentation wrong at runtime if descendant of ContentPane

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2534]
In some scenarios, Tree widget indentation is wrong at widget startup time, and only gets fixed when the user resizes his browser window (which somehow or other triggers a resize() on the Tree).

@peller needs to work with Dojo team to see if there is a possible fix for this in the dijit.Tree code.

**Comment by peller** [comment]
@wkeese

The only scenario where I see a problem is a Tree embeded in a hidden HTML (e.g. DIV display:none) within a ContentPane)

**Comment by wkeese** [comment]
OK, well it's standard procedure that layout widgets need to be visible before resize() gets called on them, so the issue doesn't surprise me.    Tree tries to get its indentation amount from CSS, measuring the width of the node with class="dijitTreeIndent".

So I guess the other workaround would be to override Tree.resize()  and hardcode a width.

**Comment by wkeese** [comment]
OK, I checked in something that hopefully works around your issue: http://bugs.dojotoolkit.org/changeset/28846/dojo.

Try it out.

**Comment by peller** [comment]
Looks great.  Thanks, @wkeese!  We'll pick this up when we move to 1.8.

**Comment by peller** [comment]
see #1997
