### ISSUE TITLE
Patch code in AppStates.js to resize Trees on state changes?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2535]
If the result of #2534 is that there is no reasonable fixes on the Dojo/Dijit side for the indentation problems that sometimes occur with Tree widgets, we might need to include a Tree-specific patch into AppStates.js. Here is some code that I provided to a user for their `app.js` file to address this issue when using Preview 6.0.1:

```
    dojo.ready(function(){
        if(davinci && davinci.states && davinci.states.setState){
            var origSetState = davinci.states.setState;
            davinci.states.setState = function(){
                origSetState.apply(davinci.states, arguments);
                setTimeout(function(){
                    if(dijit && dijit.registry && dijit.registry.byClass){
                        var trees = dijit.registry.byClass("dijit.Tree");
                        if(trees.forEach){
                            trees.forEach(function(item){
                                if(item.resize){
                                    item.resize();
                                }
                            });
                        }
                    }
                },1);
            }
        }
    }); 

```

@peller

**Comment by peller** [comment]
looks like we can close this, unless you're looking for a short-term fix for Preview 6

**Comment by JonFerraiolo** [comment]
closing, although I'll point out that there is still the obscure scenario where a user wants a different indent amount than 19px and they have a page with a Tree inside of a hidden DIV inside of a ContentPane. They'll get 19px instead of the indentation they want. But for this obscure case, we can tell people to put the snippet I show above into their app.js file.
