### ISSUE TITLE
Keeps adding a space in my CSS stylesheet, in my div tags

### ISSUE THREAD

**Issue by Davpaul** [maqetta/maqetta#2537]
I've tried editing in a text editor then uploading it, i've tried adding it inline or as a style sheet, but for some reason, when ever I go back to my code maqetta has added a space in "div#rssincl -box-491322"

for example:

div#rssincl -box-491322 \* {
    font-family : Verdana, Arial, sans-serif !important;
    margin : 0 !important;
    padding : 0 !important;
    border-radius : 10px !important;
    line-height : 110% !important;
    clear : both !important;

I keep removing it. It keeps coming back..

I just want div#rssincl-box-491322 \* {

It's been frustrating me for hours.

**Comment by JonFerraiolo** [comment]
Thanks for the bug report! I was able to reproduce when I added a STYLE element inside of an HTML file.

As a workaround with Preview 6, can you try to put the above style rules in your app.css file? For me, the extra space wasn't added.

Another possible workaround might be to avoid the dash/hyphen character in IDs until we fix this.

**Comment by Davpaul** [comment]
It works inside the app.css file! Thank you. 

It unfortunately still isn't being applied where I want it too.

I'm embedding a RSS feed using an external site and javascript. (hence the long Div id!) unfortunately the linked script has it's own Style sheet and my CSS is ignored, even with !important on everything

being new relatively new to html5/CSS I assumed it was me and I just have to try harder. Could this be maqetta?

**Comment by JonFerraiolo** [comment]
I actually would be surprised if Maqetta is doing something wrong in this case. I suspect it's the nature of the HTML content and the other CSS that you are using. Unfortunately, to figure out why your CSS isn't getting applied to the element is going to involve some CSS debugging. Do you know how to use the Chrome, Safari or Firefox debuggers to figure out which CSS rules are apply which properties to which dom nodes? There is some learning curve to use those debugging tools effectively. 

(Maqetta has a mini version of the browser CSS debuggers via the `>` icon on the right side of various properties, but in this case I suspect that Maqetta feature isn't going to help, and you'll need to use the browser debuggers.)

Are you running at Maqetta.org? If so, then I might be able to figure out what's going wrong. What's your login at Maqetta.org and what's the name of the HTML file?

**Comment by Davpaul** [comment]
Something very strange just happened. I was installing firebug and had to reset the browser, and low and behold once it reloaded the element was working perfectly! 
It worked!

Thank you for the app.css idea!

on a separate note, Just wondered if maquetta has/plans to get a RSS reader widget?
