### ISSUE TITLE
Dialog tab order does not include buttons

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2539]
Open a dialog like the new HTML file dialog.  Tab takes you through the input fields, but does not include the create/cancel buttons.  Seems to be true for all our new dialogs.

**Comment by doronrosenberg** [comment]
This is because we are removing the buttons and putting them into a different place to allow resizing.

@peller Any idea how that can be fixed?

**Comment by peller** [comment]
Are you sure it's the dynamic placement?  I think it's more likely the nested widget containers which are not able to process the tab order.  I'd flatten the structure so the inputs and buttons are all peers and direct children of the dialog's contentpane.

**Comment by peller** [comment]
see [my comment](https://github.com/maqetta/maqetta/commit/b731265d00aeac3cd10e29fdfa113050c4c717af#L13R11) on DialogContent  You might be able to use dojo/html and dojo/parser directly rather than adding a widget container to the mix.

**Comment by doronrosenberg** [comment]
@peller 

Here is what for example the New File dialog looks like:

```
<div id="davinci_ui_Dialog_0">
  <div class="dijitDialogTitleBar"/>
  <div class="dijitDialogPaneContent">
    <div id="davinci_ui__DialogUI_0">
      <div class="dijitDialogPaneContentArea">
        <div id="davinci_ui_widgets_NewFile_0"/>
      </div>
      <div class="dijitDialogPaneActionBar"/>
    </div>
  </div>
</div>
```

NewFile are the dialog contents, dijitDialogPaneActionBar has the buttons.  davinci_ui__DialogUI_0 is a container widget.

I am unclear how having a string rather than a dijit would help?

**Comment by peller** [comment]
some of those divs, like dijitDialogPaneActionBar, are widgets (created via the DialogContent code, right?).  Also, I think you have widgets inside them, even though these widgets are not Containers.  I believe that may be breaking Dijit's handling of tab order.  It would seem better if the contents were inserted directly into the DOM w/o the extra widgets.  If templates are used, string handling could be done directly, rather than relying on a _WidgetBase/_TemplatedMixin subclass to do it for you, then the results simply inserted into the DOM.  That would be a much lighter approach; the extra DIV may not even be necessary, unless you need it for styling,  The alternative might be to follow Dijit rules of implementing Containers, perhaps some other things.

**Comment by doronrosenberg** [comment]
dijitDialogPaneActionBar is actually just a simple div that contains the buttons, it isn't a widget.  dijitDialogPaneContentArea and dijitDialogPaneActionBar  are classes dijitDialog uses to do some styling.

So here is a thought - what if for example NewFile's template would have 2 sections - dijitDialogPaneContentArea for the dialog contents and dijitDialogPaneActionBar for its buttons.  We would then set that to be the contents of the dialog.  Add the resize handler manually into the containerNode after _setContent is done.  That would remove the need to move buttons around and remove the extra widget container.  Resize logic can then use the 2 classNames to do its magic.
