### ISSUE TITLE
Error converting session timeout Dialog to new ResizableDialog

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2542]
@billreed63 

When my session timed out, I got error messages in the console (and timeout dialog did not appear). Investigating some, I suspect it's a typo in Workbench.js. Here are the first several lines of the `require`:

```
define([
    "./Runtime",
    "./model/Path",
    "./workbench/ViewPart",
    "./workbench/EditorContainer",
    "davinci/ui/Dialog",
```

and here are the first several lines for the corresponding parameter names:

```
], function(
        Runtime,
        Path,
        ViewPart,
        EditorContainer,
        ResizeableDialog,
```

The timeout logic (line 115) refers to Dialog and not ResizeableDialog, so it's undefined instead of pointer to a dialog class.

**Comment by peller** [comment]
yeah, I noticed that also: 0241ec9120d8f363821eba0da0feb59bfa6868b3  Doron, please make sure I got it right.
