### ISSUE TITLE
Can only create new folder or upload files to lib directory

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2544]
All of the root-level files (except for the "lib" folder) are now greyed out (which may be correct given recent efforts to virtualize the samples?). But, as a result, if I following the Files Palette test plan, when I right-click on any of these greyed out files the only option that's enabled is Download. 

The New Folder... and Upload option are disabled, so I can't create a new folder or upload to the root directory.

**Comment by JonFerraiolo** [comment]
Maybe fixed by 5cda584342

**Comment by childsb** [comment]
you'll have to find some white space to context click in.  if you're hovering over the folder line, the folder should get selected (and marked read only)
