### ISSUE TITLE
maqetta.local.win.bat fails to find jarfile

### ISSUE THREAD

**Issue by painbank** [maqetta/maqetta#2545]
I tried running the default bat script to launch maqetta on my WinXP machine.

Process:
1. Download GitHub codebase.  -- I put this in a local directory: c:\maqetta.
2. Download Eclipse J2EE version and following documentation instructions, get the Server to launch from within Eclipse.  This worked fine.
3. I then try to launch it just using the maqetta.local.win.bat file.  

Here is my results:

"
C:\maqetta\maqetta\releng\davinci.product>maqetta.local.win.bat

Java version:
java version "1.7.0_04"
Java(TM) SE Runtime Environment (build 1.7.0_04-b22)
Java HotSpot(TM) Client VM (build 23.0-b21, mixed mode, sharing)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
NOTE: CLOSING THIS WINDOW WILL
      STOP THE MAQETTA SERVER PROCESS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Using directory : C:\maqetta\maqetta\releng\davinci.product\users
start your browser at http://localhost:50000/maqetta
Error: Unable to access jarfile 
"

I then copy all the org.eclipse.equinox.\* files from my Eclipse install to this location:

C:\maqetta\maqetta\releng\davinci.product\plugins\

and try again and here is the results:

"
C:\maqetta\maqetta\releng\davinci.product>maqetta.local.win.bat

Java version:
java version "1.7.0_04"
Java(TM) SE Runtime Environment (build 1.7.0_04-b22)
Java HotSpot(TM) Client VM (build 23.0-b21, mixed mode, sharing)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
NOTE: CLOSING THIS WINDOW WILL
      STOP THE MAQETTA SERVER PROCESS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Using directory : C:\pasa\maqetta\maqetta\releng\davinci.product\users
start your browser at http://localhost:50000/maqetta
Error: Unable to access jarfile C:\maqetta\maqetta\releng\davinci.product\plugins\org.eclipse.equinox.launcher_1.2.
0.v20110502.jar
"

In the process of trying some of these things, I got this result in the log file:

"
!SESSION Wed Jun 13 16:23:00 EDT 2012 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2012-06-13 16:23:00.948
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.RuntimeException: Could not find framework
    at org.eclipse.equinox.launcher.Main.getBootPath(Main.java:978)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:557)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1386)
"

**Comment by JonFerraiolo** [comment]
Closing.

The various launch scripts in davinci.product are only for launching what is produced by the Maqetta build scripts (the result of running davinci.releng/build.sh or davinci.releng/build.bat). When we post automatically-generated nightly builds on http://maqetta.org/nightly, our automatic build scripts will build all of the JARs, copy in the launch scripts such as maqetta.local.win.bat, and then create a big ZIP file out of it all. Those launch scripts will run in that context because all of the JARs have been built and put into the right places.

If you want to launch the Maqetta server from a source download (via git clone), then you have to do so from Eclipse per the instructions at https://github.com/maqetta/maqetta/wiki/Developer-Setup

**Comment by painbank** [comment]
I see thank you.  This wiki instruction set needs updated then to reflect that.  

https://github.com/maqetta/maqetta/wiki/Developer-Setup

Either the need to build locally or to comment on downloading the nightly build or both.

**Comment by painbank** [comment]
That instruction set is fine for building and launching, but not for deploying.  I want to eliminate the Eclipse from the equation.  Thanks for pointing it out and closing the non-bug issue.

https://github.com/maqetta/maqetta/wiki/Creating-a-Build-Manually

followed with a Deploy wiki page.
