### ISSUE TITLE
alert changes to Alert in event attributes

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#255]
I hope this one is really easy to fix.

If you define a state that begins with an uppercase "A", and then try to enter
"alert('hi')" into an event attribute field, the lowercase "a" that at the
front of the word "alert" gets uppercase'd by daVinci. I'm pretty sure it's
because we are using a FilterSelect or something like that that uses some
auto-complete logic, and since the there is a state name that begins with the
uppercase version of "a", then it replaces the "a" with an "A".

The proposed fix is to turn off the auto-complete logic. Switch from
FilterSelect (if that's what's being used) to a ComboBox?

bug: 7342

**Comment by JonFerraiolo** [comment]
Only fix for M4 is super easy and super safe, otherwise push to M5.

**Comment by JonFerraiolo** [comment]
Reassigning to me.
