### ISSUE TITLE
Download as zip fails

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2551]
1. Right-click on app.css
2. Choose Download option
3. Accept defaults on dialog and click ok
4. Get redirected to a blank page 
5. Click back to get into Maqetta and things seem pretty broken until clear cache and reload

**Comment by aerwin** [comment]
I've also tried with an HTML file I created and the dialog doesn't go away and I see JS errors in console:

```
Error
 dojo.js:4857
_3c0 dojo.js:4857
dojo._ioSetArgs.ld dojo.js:4801
_172 dojo.js:1711
_170 dojo.js:1698
dojo.Deferred.reject.errback dojo.js:1742
dojo.Deferred._16f.cancel.cancel dojo.js:1784
dojo.xhr dojo.js:5026
dojo.xhrGet dojo.js:5034
_1fcd.serverJSONRequest davinci.js:44198
_25cd.getText davinci.js:53209
_ee0._rewriteUrls davinci.js:17430
_ee0.okButton davinci.js:17447
_383 dojo.js:4551
_492.(anonymous function) dojo.js:6092
_17ec._onClick davinci.js:31069
_25e dojo.js:2636
_2657._onClick davinci.js:54274
_383 dojo.js:4551
_1e3 dijit.js:1936
Uncaught TypeError: Cannot call method 'getChildElement' of undefined davinci.js:46885
_2072.addJavaScriptSrc davinci.js:46885
_20a9 davinci.js:45370
_2072.loadRequires davinci.js:45389
_2072.loadRequires davinci.js:45380
_156f.rebuildSource davinci.js:27457
_ee0._rewriteUrls davinci.js:17430
_ee0.okButton davinci.js:17447
_383 dojo.js:4551
_492.(anonymous function) dojo.js:6092
_17ec._onClick davinci.js:31069
_25e dojo.js:2636
_2657._onClick davinci.js:54274
_383 dojo.js:4551
_1e3 dijit.js:1936
```

**Comment by aerwin** [comment]
This same error occurs if try to download the entire workspace.

**Comment by JonFerraiolo** [comment]
Download workspace worked for me just now (doing my section of test suite). This is a longshot, but could it be that you have some large cookie values that are causing the HTTP requests to bust on the Jetty/server side? In the past, I've had similar weird problems and they were due to cookies being too large. (Had to clear my cookies) Also, note that our notification dialog for session timeout is broken now, so there is no feedback in UI if the session is dead.

**Comment by aerwin** [comment]
Your suggestion of clearing cookies seems to have cleared things up. So, I guess I'll close the issue.

**Comment by peller** [comment]
why we should perhaps reconsider #1843, even if only for the cmd/ servlet
