### ISSUE TITLE
lab9 system messed up

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2554]
At some point this afternoon, the lab9:50010 became unusable for me with JS errors, etc. I had to force quit Chrome a number of times. I just reset my workspace and now I just get a blank page with the Maqetta banner at the top. And, no JS errors in the console.

**Comment by aerwin** [comment]
I just created a new user profile and I now see a full Maqetta page, but I got JS errors on launch:

```
GET http://lab9.austin.ibm.com:50010/maqetta/app/metadata/gridx/1.0beta-70-gaeea222/package.json?e8055d6b2506f2709b21e8e717bb3f10c48ebdaa  dojo.js:5022
TypeError
 dojo.js:1746
dojo.Deferred.reject.errback dojo.js:1746
dojo.Deferred.reject.errback dojo.js:1747
_172 dojo.js:1723
_170 dojo.js:1698
dojo.Deferred.reject.errback dojo.js:1742
_172 dojo.js:1723
_170 dojo.js:1698
dojo.Deferred.resolve.callback dojo.js:1737
_172 dojo.js:1720
_170 dojo.js:1698
dojo.Deferred.resolve.callback dojo.js:1737
_172 dojo.js:1720
_170 dojo.js:1698
dojo.Deferred.resolve.callback dojo.js:1737
_172 dojo.js:1720
_170 dojo.js:1698
dojo.Deferred.resolve.callback dojo.js:1737
_3cd dojo.js:4961
func dojo.js:4884
_3c6 dojo.js:4903
TypeError
 dojo.js:1746
dojo.Deferred.reject.errback dojo.js:1746
dojo.Deferred.reject.errback dojo.js:1747
_172 dojo.js:1723
_170 dojo.js:1698
dojo.Deferred.resolve.callback dojo.js:1737
_172 dojo.js:1720
_170 dojo.js:1698
dojo.Deferred.resolve.callback dojo.js:1737
_172 dojo.js:1720
_170 dojo.js:1698
dojo.Deferred.resolve.callback dojo.js:1737
_172 dojo.js:1720
_170 dojo.js:1698
dojo.Deferred.resolve.callback dojo.js:1737
_3cd dojo.js:4961
func dojo.js:4884
_3c6 dojo.js:4903
```

I then tried to create a new HTML file and when I click create on the dialog nothing happens except I can't close the browser tab creating Maqetta. So, I'm going to Force Quit Chrome again.

**Comment by JonFerraiolo** [comment]
I'm not sure what's going on for you, but 50010 works fine for me. There is a problem with our session timeout logic, where the dialog doesn't come up but the session is dead. However, restarting the browser should clear up that problem.

**Comment by aerwin** [comment]
Your suggestion of clearing cookies for #2551 seems to have cleared things up for this issue as well. So, I guess I'll close.
