### ISSUE TITLE
Can we enable context menu over any part of Files palette?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2556]
@childsb 

Right now, the context menu on the Files palette only comes up when the mouse is over one of the read/write files. Given that there are a number of read-only files, a user may either never figure out that there is a context menu in the Files palette or experience frustration trying to bring up the context menu.

Can we enable context menu over any part of Files palette?

Note that context menu in Files palette becomes less critical if we ever provide toolbar icons on the Files palette for all of the operations that are available on the context menu.

**Comment by jhpedemonte** [comment]
I cannot reproduce this.  Just tested and i right-clicked on a read-only file.  Got a context menu with only **Download** enabled.

**Comment by JonFerraiolo** [comment]
Closing. I logged this bug from memory - we used to have problems in this area. The context menu didn't work in Preview6 when over the white space at bottom of Files palette or when over a disabled item. I suspect @childsb fixed this recently.
