### ISSUE TITLE
Changing button width with custom theme fails

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2558]
Doing Properties 4 test plan... doing Step 7 (where change button width after switching themes), it fails with:

```
Uncaught TypeError: Cannot read property 'model' of undefined davinci.js:17584
_f13.getCommandForStyleChange davinci.js:17584
_17a._stylePropertiesChange davinci.js:1782
_1451._stylePropertiesChange davinci.js:25654
_383 dojo.js:4555
_492.(anonymous function) dojo.js:6092
on.emit dojo.js:5349
on.emit dojo.js:5371
_396.emit dojo.js:4635
publish dojo.js:4685
_4b7.publish dojo.js:6255
_5ee._changeValue davinci.js:6758
_60c davinci.js:6667
_5ee._onFieldChange._5f4.callBack davinci.js:6706
_383 dojo.js:4555
_1b8b._onChange davinci.js:36533
_1b8b.constructor._onChangeAlways.target davinci.js:36503
_383 dojo.js:4555
```

After this point, my workspace seems rather corrupted and I have to create a new project to continue.

(I also noted when I switched themes, the button wasn't rendered correctly. I think there's a separate issue for document.css missing from some themes.)

**Comment by jhpedemonte** [comment]
-> @billreed63 for now, since theme code seems to be involved.

@JonFerraiolo
