### ISSUE TITLE
(Orion build) Review HTML files not found

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2561]
(using Orion build)
- New review... 
- On second pane of wizard, for files, picked either samples/Sample1.html or save a new HTML file in project root folder. Problem manifests itself either way.
- Invite yourself and click publish. The dialog will come up saying invitation couldn't be set. Click OK.
- Go to reviews palette and double-click on the HTML file that you sent around for review.

Result=> The review editor shows this as its content:

```
HTTP ERROR: 404

Problem accessing /maqetta/user/B/ws/workspace/.review/snapshot/20120614122325/project1/file2.html. Reason:

    Not Found
Powered by Jetty://
```

**Comment by aerwin** [comment]
Closing this issue with the above commits and the opening of #2838 for a loose design end.
