### ISSUE TITLE
Cloned themes need to be read/write

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2562]
@billreed63 

In Preview6, if you cloned a theme (e.g., claro->claro2), the claro2 folder was read-write. This allowed a user to hand-edit the CSS files within the cloned folder to cover cases where our theme editor's GUI doesn't provide a feature that a user needs in his cloned CSS file. With latest changes, cloned themes are read-only.

**Comment by childsb** [comment]
This is working now, not sure where/when it was fixed.
