### ISSUE TITLE
No dirty bit on new HTML file

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2564]
@peller, @aerwin 

Spin off from #2548

With Preview6 and earlier, when you issued a New HTML File command, the dirty bit was set on the new HTML file. With latest code, the dirty bit is temporarily on (you can see it on the tab if your system is slow enough and your eyes quick enough), but then the dirty bit gets turned off.

Per Tony's usability comments on #2548, I think we need to put the dirty bit on all new HTML files. The argument for flagging as dirty when no content is added yet is that before the operation there was no file at all, and it's now dirty because there is now a proposed file that includes a HEAD and a (albeit) empty BODY.

I'm not sure what code change caused the dirty bit to go away with new HTML file commands. I wouldn't be surprised if this is a little bit nasty to fix. Our dirty bit logic is quite a mess.

**Comment by jhpedemonte** [comment]
Priority High since it's a regression.

**Comment by childsb** [comment]
the onLoad(...) update was firing before the visual editor finished initializing triggering an auto save.

the auto save looks for dirty resources, and since all the resources weren't loaded yet it would mark the doc 'not dirty'.

**Comment by peller** [comment]
the last checkin needs to be redone.
