### ISSUE TITLE
Focus not removed from some tool buttons after closing modal dialog

### ISSUE THREAD

**Issue by psema4** [maqetta/maqetta#2569]
_Affected versions:_ Preview 5, Preview 6
_Affected browsers:_ Firefox (10.0.2, 12.0, 13.0), Google Chrome (19.0)

_Steps to reproduce:_
1. Launch Preview 6 from http://maqetta.org/index.php?option=com_content&view=article&id=26&Itemid=24
2. Click Download tool button (Files tab)
3. Close the dialog by any means (OK, Cancel, or Close button)
4. Click Download tool button again (Won't reopen dialog)
5. Click Download tool button again (Will reopen dialog)

_Description:_
Opening the dialogs for `Download` , `Download Selected` or `Modify Libs` will work the first time.  Reopening the same dialog again (say after a Cancel button was clicked) will fail on the first subsequent click. Another click following that will reopen the dialog.

Clicking one of the above tool buttons, closing the dialog and then clicking a different tool button (from the same list) will not present this issue, ie. the new dialog will open on the first click.

Appears to be some form of focus issue.

These tool buttons are defined in `maqetta.core.client/WebContent/davinci/ui.plugin.js`, under the `viewContribution` for `targetId: 'workbench.Explorer'`

**Comment by JonFerraiolo** [comment]
@childsb - probably shouldn't try to fix this until we figure out where the download commands will end up when we shift things around in our new (and wonderful) revised UI for the product

**Comment by jhpedemonte** [comment]
I've noticed this with other buttons as well.  May just be a general Dojo issue.

**Comment by psema4** [comment]
Actually, looks like it might be something to do with the radio group; by removing the `radioGroup: "displayMode"` references, the issue goes away.  I'm uncertain how this might otherwise affect Maqetta however.  (I've only been working with it for a short time.)

**Comment by jhpedemonte** [comment]
cc @doronrosenberg, who has worked on some UI issues.

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg our focus expert
