### ISSUE TITLE
content.css rules for TD and TH mess up column width assignments

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2571]
@billreed63 

If you author a table in Maqetta page editor, we stuff in the following CSS rules onto TD and TH elements:

```
TD.HtmlWidget {
    outline: 1px dotted #AAA;
    outline-color:rgba(128,128,128,0.4);
    width: 1em;
    height: 1em;
}
TH.HtmlWidget {
    outline: 1px dotted #AAA;
    outline-color:rgba(128,128,128,0.4);
    width: 1em;
    height: 1em;
}
```

Note that for most other HTML elements (DIV, SPAN, etc) we use `min-width` and `min-height` instead of `width` or `height`. The reason we are using `width` or `height` on TD and TH is that long ago we put this in as a temporary hack to make the page editor do something reasonable, with the idea that we would find a way to clean this up down the road. I believe this is the time to clean it up.

Here is the dilemma. If we didn't put `width` or `height` on TD elements (even if we put `min-width` and `min-height` of 1em), then upon adding an initial 2x2 table, the cells would have zero width and height, and the way browsers work, without any content, there is no width/height, and even if the TABLE has width:100%, the 4 cells will be zero-size and will have no height and will have zero width (and won't stretch to fill up the 100% width). 

The ways to get around this "cells collapsing to zero size" problem include:
- Putting a 'width' or 'height' property on each cell, such as `width:1em;height:1em;`, which what we are doing now in content.css, which is problematic in multiple ways. First, content.css only applies to the page editor, and isn't there during preview-in-browser, so empty table cells collapse to zero size at runtime. But the new column control features get messed up by the `width:1em;height:1em;` values from content.css because they "win the cascade" in some circumstances and interfere with width assignments on COL elements.
- Put `&nbsp;` or other invisible character within empty table cells. (Actually, the best entity to use is the zero-width non-breaking-space char: `&#8288;`)

Here's what I think we should do:
- At table creation time, or row/column insertion time, set  `&#8288;` as the innerHTML for any TDs or THs that have no content
- In SmartInput for TD and TH, if the innerHTML only consists of `&#8288;`, then remove that character before showing the text value (which means the text value becomes the empty string), and upon saving SmartInput changes for TD or TH, insert a `&#8288;` value if the value is the empty string.
- Remove the `width:1em;height:1em;` (If we put `&#8288;` as the value for empty cells, then we won't need `min-width` and `min-height`)

**Comment by aerwin** [comment]
Closing with above commit.

**Comment by JonFerraiolo** [comment]
Wow, that was fast!
