### ISSUE TITLE
Empty Grid Configuration dialog

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2574]
Running Gridx Columns test plan.  When adding GridX, the **Grid Configuration** dialog comes up empty.

Had to refresh page and double-click on GridX widget in order to get correct dialog.  Seen on lab9:50020.

---

Setting to Priority High for now since it's a regression, but feel free to adjust after investigation.

**Comment by aerwin** [comment]
@jhpedemonte 

I've seen this kind of thing a few random times in FF after the custom build stuff was put in, but I can't reproduce this evening going to lab9 either with FF or Chrome on Mac. What browser were you using?

It's a weird deal... when I have seen it, there were no JS errors. Also, when I tried to inspect the HTML elements using developer tools, the widgets in the dialog would start rendering. So, the issue (when it occurs) doesn't make a lot of sense.

**Comment by jhpedemonte** [comment]
I was using Chrome/Mac.  Unfortunately, this might be a very intermittent issue.  I'd keep it open for a little while longer, but if we don't see it again, we can close it.

Another option is to add some logging.  Not sure if it's fully possible to track this issue, but if we can, then logging might help track down the cause.

**Comment by aerwin** [comment]
@jhpedemonte Have you seen this one lately? I'm thinking of just closing out if not.

**Comment by jhpedemonte** [comment]
Haven't seen it lately, so closing.
