### ISSUE TITLE
Incorrect initial GridX display when using JSON file

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2575]
New file in a subfolder, dropped GridX, used **sampleManyColumns.json** data file.  Initially, GridX in page does show many columns, but **only 2 empty rows**.

Preview looks correct, with 3 rows and proper data.  Save, close, re-open file and widget looks correct in VE as well.

Seen on lab9:50020.

**Comment by aerwin** [comment]
Hmmm... weird... looks like this happens when launched from Eclipse as well.

**Comment by aerwin** [comment]
Closing with above commit.
