### ISSUE TITLE
Can save on top of sample files

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2590]
- Open Sample1.html
- Immediately click the save button
- Close the editor
- Refresh the browser

Result=> Sample1.html is now read-write. Maqetta has saved a read-write version of Sample1.html into ROOTFOLDER/Samples/Sample1.html
- In Files palette, delete Sample1.html

Result=> Sample1.html disappears from Files palette (temporarily)
- Refresh browser

Result=> Sample1.html reappears as read-only

**Comment by childsb** [comment]
The dialog for "save as" has been fixed since this bug.  Backing out previous fix just because its redundant.
