### ISSUE TITLE
Need to migrate data-davinci-ws -> data-maq-ws in space.js

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2591]
@peller 

I think we need to look for both the new attribute name `data-maq-ws` along with old attribute name `data-davinci-ws` in space.js, both copies (i..e, the one used by page editor and one used at runtime) so that old files will get properly migrated in page editor and will continue to look correct in preview-in-browser.

**Comment by peller** [comment]
follow-on from #334

@JonFerraiolo, what are the consequences if we do not migrate this attribute?

**Comment by JonFerraiolo** [comment]
> what are the consequences

We won't remove whitespace in migrated user documents, which means layouts will sometimes be wrong when viewing in page editor or preview-in-browser.

The runtime fix to space.js is pretty much just changing `getAttribute(newAttrName)` into `getAttribute(newAttrName) || getAttribute(oldAttrName)`. In the page editor, we would want to fix the model also (to get rid of the old attribute and replace with the new attribute).

Even though the layout problems from this bug aren't as fatal as some of the other migrated attributes, I'd like to migrate because I don't want to avoid spending precious time having to do support work with users who are asking why their layouts are broken in migrated files.

@jhpedemonte

**Comment by JonFerraiolo** [comment]
Closing. Too late to attempt a fix, and then the problem will mostly go away in future as we can expect most user files will have been created by M7 with the new markup syntax.
