### ISSUE TITLE
Clean up (remove?) Context.widgetAddedOrDeleted (re: document.css)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2592]
To get reasonable behavior for Preview 6, I added some ugly hacks at the end of the cycle centered around Context.widgetAddedOrDeleted().

I expect that we will want to remove that function and remove all logic that calls that function once @billreed63 comes up with a good alternate implementation for including document.css for desktop UIs but not for mobile UIs.

**Comment by billreed63** [comment]
dup #2377
