### ISSUE TITLE
Samples don't render when opened from downloaded zip file

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2593]
1. Download entire workspace as zip file
2. Expand zip file and serve directory from local web server 
3. Open Sample1.html in browser and see JS errors in console:

```
GET http://localhost:8000/samples/lib/dojo/dojo/dojo.js 404 (File not found) Sample1.html:9
Uncaught ReferenceError: require is not defined Sample1.html:11
Uncaught ReferenceError: dojo is not defined app.js:6
```

**Comment by peller** [comment]
The problem is that the lib/dojo/dojo/dojo.js reference is not relative to the page, and the samples were moved to a samples/ subdirectory

@jhpedemonte

**Comment by jhpedemonte** [comment]
Right, what @peller said.  If you look at Sample1.html in Maqetta, the source says,

```
<script type="text/javascript" src="../lib/dojo/dojo/dojo.js" ....
```

That's correct, since `lib` directory is a sibling of `samples`.  However, after downloading, it gets rewritten as,

```
<script type="text/javascript" ... src="lib/dojo/dojo/dojo.js">
```

Doesn't the download code run through the **RebuildPage.js** or **RebaseDownload.js**?

@childsb

**Comment by peller** [comment]
It's a bit embarrassing how simple this one was... when we relocated the sources for the sample files in a subdir, we didn't alter the script src= path for dojo.js.  If you load/save the files, they fix themselves up and download works fine.  It was only if you did a download on the default content that it would fail
