### ISSUE TITLE
Document.css possibly missing from downloaded zip file

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2594]
Using M6 from Maqetta.org...
1. Download entire workspace as zip file
2. Expand zip file and serve directory from local web server 
3. Open Sample1.html in browser and see rendering a little off (like document.css missing)

NOTE: I'm not sure if this problem still exists post-M6. I was trying to determine that, but ran into #2593 where Sample1.html isn't rendering at all from the downloaded zip file. Once #2593 is fixed, this issue should be investigated.

**Comment by JonFerraiolo** [comment]
-> @billreed63 who is fixing the document.css issues

I'm pretty sure this is a problem only when viewing the **sample files** after ZIP download. If you create a new html file, then document.css will get included, even in the ZIP download. I think Maqetta includes document.css with samples if you open/save the samples.
