### ISSUE TITLE
Server logging

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2598]
@jhpedemonte @peller 

Today we talked about adding logging features to our server. The main impetus was to debug user problems such as intermittent file disappearance, causing users to lose their work.

One simple approach that comes to mind is that each file operation, particular save and delete operations, are somehow logged. 

Random thoughts:
- We have concerns about log file explosion on the server. 
  - One approach to minimize log file size is to delete older log file entries. For example, only keep things for a week or a day.
  - Another idea is that if we want to save the HTML and CSS file content that are PUT to the server, we could save deltas over the previous version of the file.
- Should there be one giant log file for all users or different log files for particular users? @JonFerraiolo thinks it would be way more useful to have different log files for different users because most of the problems we have seen so far are within the scope of a single user.
- Ideally, we would log client-side actions, too, such as passing up a JSON serialization of the CommandStack to the server. However, this might be challenging both from a file size bloat perspective, might impact our bandwidth constraints on our hosting server, might compromise client-side performance, and might take a non-trivial amount of programming. (Note: this CommandStack feature could slide into a timeline feature that would allow a user to go back in time for his workspace.)
- We definitely want to track all workspace changes at the file system level. As such, we probably should look at two things: file system changes that are due to Maqetta commands (e.g., /maqetta/cmd/...), and also any file system actions in the server code that are not due to Maqetta commands (because those file system actions might cause users to lose data).

**Comment by jhpedemonte** [comment]
-> M8

**Comment by jhpedemonte** [comment]
Dupe to #3717.
