### ISSUE TITLE
Alignment tools (with snap)

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#26]
Particularly for absolute layout:
- guidelines appear as candidate snap points to align with other widgets as you drag items around on canvas
- alternatively, have items snap to a grid at fixed intervals?

see bugzilla bug 4823

**Comment by JonFerraiolo** [comment]
Reassigned to me and made it an M3 feature. I've already gotten a little bit of this working but haven't checked anything in yet.

**Comment by JonFerraiolo** [comment]
Closing this. Fixed with commit 34adbd4e3684c6ba124a
