### ISSUE TITLE
grep -i for jquery and yui in maqetta-core-client

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2606]
I did a grep -i for jquery in maqetta-core-client and I see some references in Palette.js and in the test plan. We should review those references. (I'm taking care of maqetta-core/client/WebContent/docs with #2605)

**Comment by jhpedemonte** [comment]
-> M8

**Comment by jhpedemonte** [comment]
Actually, I decided to do this quickly.  I saw a few commented out lines in our code.  The rest were in Dojo.  Closing.
