### ISSUE TITLE
Resource case-insensitive checks

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2607]
@childsb 

Some very old code in the resource model uses CASE_SENSITIVE flags, but seems to confuse them (it's undefined on Resource.js, so checks in Folder.js are always falsey, therefore case-insensitive??)  No idea how much is broken but I think it's always been this way.

I think we need to review this and limit the times we ask for case-insensitivity.  Brad points out that file extensions .HTML/.html/.Html etc is a valid scenarios, but it certainly should not be the default.

**Comment by jhpedemonte** [comment]
Why not?  I've always hated case-sensative filenames -- in the past, it made it easier for computers, but humans don't think this way.  Let's break off the shackles of tradition and embrace a new paradigm, brothers and sisters!

**Comment by peller** [comment]
shall we also embrace the bugs that will come with the file mixups?

**Comment by peller** [comment]
Might be fixed.  Need to look at other uses.  -> M8
