### ISSUE TITLE
Recover (not hang) if libs.settings is missing

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2609]
Had a user who had an old workspace without a libs.settings file in one of her projects and Maqetta hung with New HTML File. It seems like at least we could notice that libs.settings wasn't there and tell user their project is in bad shape, even better if we could fix things up for them.

**Comment by peller** [comment]
@childsb 

LibrarySettings.java has a conditional in the constructor to create some default data if lib.settings is not found.  Apparently this led to a 404 for dojo.js, so the defaults may not be valid.  Should it be a fatal error instead of libs.settings is missing?

**Comment by aerwin** [comment]
--> prio from not set to med

**Comment by jhpedemonte** [comment]
@childsb, care to provide some input?

**Comment by childsb** [comment]
Changes from the orion integration may have fixed this. To facilitate opening a folder in maqetta from Orion, i have the server create .settings/libs.settings if its not there.

**Comment by jhpedemonte** [comment]
Closing based on previous comment.
