### ISSUE TITLE
switchEditor: exception: this.tree.getIconClass is undefined 

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2611]
bring up multiple editors and switch between the tabs.  Each time, an exception is thrown in Workbench.js _applyClassAndStyle around line 191:

```
this[clsName] = this.tree["get" + upper + "Class"](item, this.isExpanded);
```

this seems to be undefined on the new OutlineTree

**Comment by doronrosenberg** [comment]
Hmm, I can't reproduce this

**Comment by peller** [comment]
seems to happen only when a mobile doc is involved.  I see the exception when switching from Sample2 to Sample3-Mobile

**Comment by doronrosenberg** [comment]
Can you paste the stack trace?   And this is with trunk I assume?

**Comment by peller** [comment]
Sorry, I should have captured it.  It was very easy to reproduce until this weekend.  I can no longer get it to break on that exception. I do see something in the console, but with a bad stack and a lot of traps in jquery.  Don't know for certain that it's related.

**Comment by peller** [comment]
I'm wondering now if this was a Dojo 1.8 problem.  Ok to close for now, if you can't reproduce.
