### ISSUE TITLE
Table cells: selection chrome off in FF if table has border

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2612]
The selection chrome for table cells is off in FF if table has border. Cellspacing and cellpadding don't seem to have an affect.

![screenshot](http://i.imgur.com/DIafR.png)

**Comment by JonFerraiolo** [comment]
@aerwin: feel free to reassign this issue to mr. css coordinates (i.e., me) unless you think it needs to be fixed right away

**Comment by aerwin** [comment]
-> @JonFerraiolo
