### ISSUE TITLE
Selection in outline doesn't select right widget in page editor after smart input on container

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2613]
Noticed this while working on my table smart input dialog, but seems more general. For example,
1. New HTML file
2. Drop BorderContainer onto page and click OK on smart input
3. Drop Button into center region
4. Go to outline and notice as you select different items in the tree, that items in page editor are properly selected
5. Bring up smart input for border container 
6. Uncheck bottom region and click OK
7. Now notice selecting different children of border container in outline doesn't properly select item in page editor (selection chrome is just a 0x0 rect in upper left corner)
8. But, also notice selection works fine the other way (e.g., selecting item in page editor selects right item in outline)

**Comment by doronrosenberg** [comment]
Also note that outline doesn't get updated - the bottom region is still showing.
