### ISSUE TITLE
Smart Input intermittently launched twice

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2616]
Using Chrome on Mac...
1. New HTML file
2. Drop HTML table widget onto panel
3. Click OK on smart input
4. Clear cache and reload page
5. Select table and double-click to bring up smart input and (intermittently) two smart input dialogs are launched

![screenshot](http://i.imgur.com/rB6W6.png)

When the 2nd dialog comes up, there are JS errors in the console related to duplicate id's.

I put a break point in `TableInput`'s `show` function (which seems to disrupt the timing enough to make seeing the issue less likely) and see that `Focus` is calling it twice:

![screenshot](http://i.imgur.com/7u4pz.png)

**Comment by jhpedemonte** [comment]
-> @billreed63

**Comment by billreed63** [comment]
I can't get this to happen for me on Chrome/Win local host, 
Can you still reproduce? Does this happen with the debugger off?

**Comment by doronrosenberg** [comment]
@aerwin I can't reproduce this as well, still seeing this?

**Comment by aerwin** [comment]
I'm not able to reproduce either. So, closing. Thanks for looking into it.
