### ISSUE TITLE
@import CSS files are not being added to model

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2619]
When I create a new theme the new theme imports the conled CSS file. The imported themes do not get loaded in the model

1) Create a theme  (claro1) the clones claro
2) Create new html file and use your cloned theme (claro1)
3) DnD a button
4) Select the button in the palette open the cascade background color notice that the only rules that are displayed are for the claro1.css the rules for the imported claro.css are missing

**Comment by billreed63** [comment]
I have chased this down to two problems.
1) One is the fix for issue #2557 to fix that issue I change the `@import url("../../lib/dojo/dijit/themes/claro/claro.css");`  to use the static lib path of the toolkit
`@import url("../../../../../../../app/static/lib/dojo/1.7/dijit/themes/claro/claro.css");` 
2) I also change the code in system/resource.js so that if the resource is not found it make the call to the server the serverFind code had been commented out in th doFind function.

```
if (!found /*&& (serverFind || isWildcard)*/)

```

@childsb how do we findResource for a resource that is using the static lib url?

**Comment by childsb** [comment]
findResource(...) is ONLY for user workspace files and wont work for static mappings.

**Comment by peller** [comment]
-> @billreed63 is looking at this

**Comment by billreed63** [comment]
Added theme back to maqetta theme folder but in dijit and dojox folders to make them straight folder replaces when upgrading dojo

**Comment by billreed63** [comment]
fixed with commit a43afbb8f70cd9908cd04767a26df7d3e9342664
