### ISSUE TITLE
Exceptions in VisualOutlineEditor from _widgetChanged function

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2621]
@doronrosenberg 

Not sure if related to another outline issue I observed recently (#2613) or not... but, occasionally seeing exceptions in `VisualOutlineEditor` during certain table operations. So, much so, that I put a try/catch in there as part of the fix for #2566 because these exceptions were often keeping undo/redo operations related to the table from working in the page editor.

Here's one example using Chrome on Mac:
1. New HTML file
2. Drop HTML table element onto page
3. Click OK on Smart Input
4. Select cell in first column
5. Select Remove Column from context menu, and see errors from `VisualOutlineEditor`:

```
VisualEditorOutline._widgetChanged: e = TypeError: Cannot read property '0' of undefined VisualEditorOutline.js:187
declare._widgetChanged VisualEditorOutline.js:187
hitch lang.js:153
target.(anonymous function) aspect.js:181
declare.execute RemoveCommand.js:52
declare.execute CompoundCommand.js:76
dojo.withDoc window.js:107
declare.execute CommandStack.js:24
declare.run RemoveColumnAction.js:81
Workbench._runAction Workbench.js:1004
_hitchArgs lang.js:138
declare.onItemClick _MenuBase.js:225
declare._onClick MenuItem.js:115
hitch lang.js:153
handles _OnDijitClickMixin.js:82
VisualEditorOutline._widgetChanged: e = TypeError: Cannot read property '0' of undefined VisualEditorOutline.js:187
declare._widgetChanged VisualEditorOutline.js:187
hitch lang.js:153
target.(anonymous function) aspect.js:181
declare.execute RemoveCommand.js:52
declare.execute CompoundCommand.js:76
dojo.withDoc window.js:107
declare.execute CommandStack.js:24
declare.run RemoveColumnAction.js:81
Workbench._runAction Workbench.js:1004
_hitchArgs lang.js:138
declare.onItemClick _MenuBase.js:225
declare._onClick MenuItem.js:115
hitch lang.js:153
handles _OnDijitClickMixin.js:82
```

And, this is not restricted to table. As another example:
1. New HTML file
2. Drag BorderContainer onto page
3. Click OK on smart input
4. Delete left ContentPane
5. Delete top ContentPane
6. Delete right Content Pane
7. Click Undo five times to get back to point where there is no BorderContainer
8. Click Redo 3 times (to point where left ContentPane gets removed) and see:

```

VisualEditorOutline._widgetChanged: e = TypeError: Cannot read property 'parentNode' of null VisualEditorOutline.js:187
declare._widgetChanged VisualEditorOutline.js:187
hitch lang.js:153
target.(anonymous function) aspect.js:181
declare.execute RemoveCommand.js:52
dojo.withDoc window.js:107
declare.redo CommandStack.js:70
declare.run RedoAction.js:13
Workbench._runAction Workbench.js:1004
_hitchArgs lang.js:138
declare._onClick _ButtonMixin.js:44
inherited declare.js:191
declare._onClick Button.js:70
hitch lang.js:153
handles _OnDijitClickMixin.js:82
```

**Comment by doronrosenberg** [comment]
fixed in e0dee27d0d9ecd4882b7f502a52b4f1bb9adb3a2
