### ISSUE TITLE
Regressions in New HTML File dialog

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2624]
- When bringing up the **New HTML File** dialog, the drop down menu does not show `(root)`, as it has in the past.
- I had already created a **file1.html**.  Went to create a new file and the default name was still "file1.html".  Should have been "file2.html".
- Even though it said "file1.html" and I already had such a file, I clicked ENTER, which brought up a dialog saying "File already exists."  Clicked OK on alert, and both alert and New HTML File dialog went away.  Only the alert should have disappeared.

@doronrosenberg

**Comment by peller** [comment]
-> @doronrosenberg, can you please take a look?  I suspect the third bullet point might be related to your changes to the "teardown" code in Workbench.  Let me know if you think the others might be related to resource changes or Dojo 1.8

**Comment by doronrosenberg** [comment]
sure

**Comment by doronrosenberg** [comment]
1/2 are easy fixes, 1.8 behavioral changes.

3 is fun - submit buttons always run onExecute, and onExecute always hides the dialog.  Looks like we will have to move the validation to the widget itself so it can cancel the onClick on the button.
