### ISSUE TITLE
Heading placement is off in ScrollableView

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2625]
To reproduce:
1. New HTML page.
2. Add a dojox.mobile **ScrollableView**.
3. Add a **Heading** widget.  Notice that there is space above Heading -- it should be at the very top of the ScrollableView.
4. Click on Preview.  Notice that the Heading isn't even visible in the current viewport -- you must scroll the page in order to see the Heading.  It should be at the very top.
5. Go back to the VE and select the Heading.  In **Properties > Widget-specific**, notice that the `fixed` property is disabled.  User should be able to make use of that drop down when Heading is in a ScrollableView.

(Assigning to @peller for now, since it's a regression after Dojo 1.8 update)
@doronrosenberg @JonFerraiolo

**Comment by peller** [comment]
@doronrosenberg, can you take a look?

**Comment by doronrosenberg** [comment]
Works fine for me in Firefox and Chrome, so closing.
