### ISSUE TITLE
When creating new theme CSS file is not in users file folder tree

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2626]
When I create a new theme the css file is not present in the users theme folder until I refresh the browser

1) Create clone of custom theme
2) When the theme editor opens look at the files palette the theme just created has a .theme file but the .css file is missing from the folder, but it is on the server

**Comment by peller** [comment]
works now, probably fixed by 604bb896fa3352cbb13c4db5059720448c14c0c0
