### ISSUE TITLE
Empty console.error shows up when loading maqetta

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2628]
In Firefox, an empty console.error() is logged when maqetta finishes loading.

**Comment by peller** [comment]
putting a breakpoint in instrumenting.js, the error I'm seeing is

`"Could not expand path at ."`

from dijit/Tree's _setPathAttr, where the error being logged is a string rather than an Error object, so the instrumenting code doesn't seem to know what to do with it.  Anyway, it's one of those tree node expansion problems.  @doronrosenberg, maybe you can take a look at that.  I filed [a ticket against Dojo](http://bugs.dojotoolkit.org/ticket/15579) about the log problem.

**Comment by doronrosenberg** [comment]
Error comes from the files palette.  The path causing the issue is:

```
[.,project1,.,project1,app.js]
```

**Comment by doronrosenberg** [comment]
So the problem here is in _dndSelector - dojo builds the persist cookie by doing:

```
ary = array.map(ary, function(item){
  return model.getIdentity(item);
}, this);
selects.push(ary.join("/"))
```

So we basically call getIdentity on the path - so for app.js that would be the root (./project1) and app.js (./project1/app.js) resulting in the invalid ./project1/.project1/app.js.

**Comment by doronrosenberg** [comment]
@peller  @jhpedemonte 

Actually I could be wrong here - I think previously we didn't persist selection, we just persisted expansion. We only had the maqExplorer cookie, but now we have an additional one that the dndSelector is setting to persist selection as well.

Not sure what to do here, I would assume we don't want to persist selection right?

**Comment by peller** [comment]
That's my recollection also.  Prior to Dojo 1.8, dijit/Tree only saved the expansion state, and we customized the cookie name.  Must be a new 1.8 feature?  Sounds like a harmless failure, at least.  It seems dijit/Tree doesn't let you persist one without the other.  So, I guess the issue -- why is the identity invalid?  The path should be an array of paths up to the file (2 filepaths in an array).  Is it the "./" that's throwing it off?

Related stuff: the cookie name is apparently based on the tree id.  Perhaps we ought to put an id on the tree with a "maq" prefix like "maqExplorer" so the cookie will have that prefix.

**Comment by doronrosenberg** [comment]
I assume its the . path is confusing it, as there is no tree node with that identity.

**Comment by peller** [comment]
see #1208  All the periods in the path should be removed, not just from the UI, but from the implementation. @childsb

**Comment by doronrosenberg** [comment]
Any progress here?  Probably not a good thing to ship with :)

**Comment by jhpedemonte** [comment]
We don't need a cookie to persist selection.  Let's get rid of it.

@JonFerraiolo

**Comment by doronrosenberg** [comment]
@jhpedemonte pretty sure we need the cookie to persist selection

**Comment by jhpedemonte** [comment]
Selection of what?  From comments above, we didn't used to persist selection, so why not just remove that "feature"?

**Comment by JonFerraiolo** [comment]
This is about persisting selection in the Files palette? We don't need to do that (and don't want to do that). We do want to persist which folders are open, though, if that is feasible.

**Comment by doronrosenberg** [comment]
The selection persisting isn't a feature we can turn off without turning off persistence of expansion.  We need to get rid of the ./

**Comment by peller** [comment]
We have a lot of code that removes the selection by matching "./" and removing it.  It would be best to remove it at its source.

**Comment by doronrosenberg** [comment]
```
ary = array.map(ary, function(item){
  return model.getIdentity(item);
}, this);
selects.push(ary.join("/"))
```

The other problem here is joining on / - the id of the app.js node for example is `./project1/app.js` - it seems that using `/` in the id of a tree node is bad, and that is what we are running into.

Changing the code to return the file name as the identity rather than the full path seems to work, but I bet something would break for this

**Comment by doronrosenberg** [comment]
@peller btw looks like the latest dojo we run is eating the exception, not even getting the empty error anymore
