### ISSUE TITLE
Impossible to disable parser onload

### ISSUE THREAD

**Issue by gianluca-sabena** [maqetta/maqetta#2636]
I can't disable dojo parser on load because if I change the line

``` javascript

<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'async':true,'parseOnLoad':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'maqetta','location':'../../maqetta'}]"></script>

```

in 

``` javascript

<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'async':true,'parseOnLoad':false,'packages':[{'name':'gridx','location':'../gridx'},{'name':'maqetta','location':'../../maqetta'}]"></script>

```

Maqetta M6 will revert the line to the original version (parseOnLoad:true)

**Comment by peller** [comment]
Maqetta requires the parser to interact with widgets on the page.  Even if there are not any widgets on the page, they could be added at any time.  Turning off the parser would effectively be turning off widgets and most of the functionality in Maqetta.  It could be implemented that way as a preference, but may I ask, what is the use case?

**Comment by gianluca-sabena** [comment]
Hi, I'm using Maqetta to design a raw form, but since I need to add some flavor using javascript I work this way:
- design a basic form in maqetta
- stop the parser onload
- copy the raw form in a  js variable
- add flavor (for example a group of box to manage a many-to-many relation with another table) based on the current CRUID operation
- parse it

So any time I change the form state I have the raw version and I can change the flavors on it.
Please note that Maqetta M5 is supporting parser stop onload.

**Comment by peller** [comment]
could be some expert mode sort of thing, where the parser could be disabled on a document basis.  I'm not even sure we have document-based settings yet.

@JonFerraiolo @jhpedemonte

**Comment by gianluca-sabena** [comment]
I discovered a workaround! 
It is possible to redefien dojoConfig via the require function (http://dojotoolkit.org/reference-guide/1.7/loader/amd.html#configuration) 

``` javascript

require({
  parseOnLoad: false
});

require([
  "maqetta/space",
  "maqetta/AppStates",
  "dijit/layout/TabContainer",
  "dijit/layout/ContentPane"
]);

```

**Comment by peller** [comment]
excellent.  Perhaps this would still let the visual editor do its thing and add new widgets?

**Comment by JonFerraiolo** [comment]
But won't disabling the parser cause Maqetta-created pages that use Dojo widgets to not work properly in preview-in-browser and other scenarios where the page just runs directly in the browser? Is the idea that custom JavaScript would invoke the Dojo parser at a later point in time? 

Also not that the application states feature hooks into the Dojo parser at runtime (eg preview-in-browser) and if the Dojo parser is disabled, then the application states feature probably won't work.

**Comment by peller** [comment]
Jon, I think the user is invoking the parser from JS code.  If the AppStates code to hook the parser is right, it should get invoked along with the parser regardless of when it runs.

**Comment by peller** [comment]
@intertesto, given that you're dealing with advanced JS scripting outside drag-and-drop operations in Maqetta, your workaround of adding a require seems reasonable given that you're manually invoking the parser from JS.  I'm not sure anything else is warranted right now.  Ok to close this issue?

**Comment by gianluca-sabena** [comment]
I confirm your guesses, I stop the parser, then I manipulate widgets wit JS and at the end I run the parser. The designer and the preview correctly work, but note that I'm not using AppStates so I can't confirm they are properly working. The workaround solves the problem.

``` javascript

require({
  parseOnLoad: false
});

require([
  "maqetta/space",
  "maqetta/AppStates",
  ...
  ...
]);


require(["dojo/ready", "dojo/parser", "dijit/registry", "dijit/Dialog"], function(ready, parser, registry){
      ready(function(){
      /* .. some code ....*/
      dojo.parser.parse();
    });
});

```
