### ISSUE TITLE
Unable to set style on widgets in theme editor and page editor

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2637]
With the latest pull from git I am unable to set styles.

**Comment by JonFerraiolo** [comment]
Reopening and reassigning to @JonFerraiolo. If we need to pass an array, maybe we can convert into an array in one of the utility routines rather than putting arrays into the table at the top of the file.

**Comment by billreed63** [comment]
In SwitchingStylesView.js pageTemplate has a mix of targets that are array already eg.
`{display:"box-sizing", type:"combo", target:['box-sizing','-webkit-box-sizing','-ms-box-sizing','-moz-box-sizing'], values:['','content-box','border-box']}` 
And others that where not eg.
`{display:"height", type:"multi", target:"height", values:['','auto','100%','200px','10em']}`

Cascade.buildRendering set the this.target to an array 

``` if(!dojo.isArray(this.target)){
    this.target = [this.target];
   }
```

but it when Cascade._changeValue `this.target` is set back to what is in the SwitchingStylesView pageTemplate

If I set the targets in the template to an array it all works and seems to be consistent format for the pageTemplate

**Comment by JonFerraiolo** [comment]
OK, thanks, you are probably right, but let's leave it open and give me a chance to study all of this.

**Comment by JonFerraiolo** [comment]
Closing this bug. I did a thorough code review and everything looks good except for the problem I listed in #2880.
