### ISSUE TITLE
Need scrollbar on widget-specific properties

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2644]
This doesn't appear to be anything new, but there's no scrollbar on widget-specific properties if the list of props is too long to fit in the viewable area.
1. Make browser window somewhat small (like if showing developer tools)
2. New HTML file
3. Drop  HTML input widget onto page
4. Look at widget-specific properties

In screenshot below, there are a few props after size (including the very important "value" prop):

![screenshot](http://i.imgur.com/lE0Xz.png)

**Comment by peller** [comment]
dup of #2449
