### ISSUE TITLE
Found more dialogs not sized correctly on launch

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2645]
@doronrosenberg 

Not sure if these are related to Dojo 1.8 upgrade or part of remaining dialog clean-up:

From changing background on button:

![screenshot](http://i.imgur.com/68sAo.png)

Switching theme on HTML file (note wrapping "Theme set" label):

![screenshot](http://i.imgur.com/Ez9P9.png)

**Comment by aerwin** [comment]
Also, Vertical Slider Smart Input:

![screenshot](http://i.imgur.com/3jxsR.png)

**Comment by jhpedemonte** [comment]
As seen in #2657, I'm still seeing this, even after the commit.  Seen on lab9:50010 w/ Chrome/Mac.

**Comment by jhpedemonte** [comment]
New Review dialog as well:

![review dialog](http://i.imgur.com/gqKwM.png)

**Comment by doronrosenberg** [comment]
@jhpedemonte regards to 2657 - what are the exact steps to reproduce?

**Comment by doronrosenberg** [comment]
I still don't see Error modifying dialog issue on lab9:50010 on mac chrome after a cache clear
