### ISSUE TITLE
Can't bring up background dialog

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2647]
Working through Properties 5 test plan on Chrome on Mac...
1. Drop Dojo button onto page
2. Go to background sections of props dialog
3. Click "..." button to bring up background dialog and it fails:

```

Uncaught TypeError: Cannot read property 'comboBox' of undefined davinci.js:63336
_2bd0.postCreate davinci.js:63336
_2d5.create dijit.js:3008
_2d5.postscript dijit.js:2975
a dojo.js:2837
_28bf.startup.connect.dojo.hitch.dueTo davinci.js:58745
lang.hitch dojo.js:4889
```

**Comment by jhpedemonte** [comment]
-> @doronrosenberg to investigate.

**Comment by JonFerraiolo** [comment]
@doronrosenberg @billreed63 - Above commit gets the Background dialog to come up, but choosing a gradient and clicking OK does nothing at this point. The executor function doesn't seem to get invoked.

**Comment by doronrosenberg** [comment]
I'll take a look at the issue

**Comment by JonFerraiolo** [comment]
->@doronrosenberg

I think we need to add type='submit' to the OK button in ve/widgets/templates/BackgroundDialog.html
