### ISSUE TITLE
Download as ZIP has 700 permissions

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#265]
The download-as-ZIP feature is creating a ZIP that, when expanded on the Mac,
has 700 Unix permissions on the root folder, with the owner being the user who
is running the browser (in my case, "jonferraiolo"). The contents within the
folder have permissions 755.

After expanding, if I simply double-click on Sample1.html, the browser will
load the file successfully using the file: protocol. However, if I unpack the
ZIP into my localhost web server area, and then try to reach the file via
http://localhost/.../Sample1.html, I get access denied, probably because the
browser runs as a different user than "jonferraiolo".

Is there a way to set up the ZIP so that when expanded it has 755 permissions
on it?

------- Comment #1 From bradley childs 2011-04-04 10:15 [reply] -------
can't do this without a zip library.

there is an apache library and a few others that will support this, probably a
good idea for speed reasons too. re-targeting to 8.2 as a little too risk for
now.

bug: 7665

**Comment by JonFerraiolo** [comment]
M7->Prio Med. We really should fix this if we can.

**Comment by jhpedemonte** [comment]
Raising to Prio High so we can investigate now for M7.

**Comment by JonFerraiolo** [comment]
-> M8 Prio Med - haven't heard any complaints from users or developers about this.

**Comment by peller** [comment]
no longer an issue
