### ISSUE TITLE
select property missing

### ISSUE THREAD

**Issue by jefftrbo** [maqetta/maqetta#2654]
The RoundRectList and EdgeToEdgeList are both missing the "select" (e.g., select="single", select="multiple") property field in the Properties>Widget Specific list.

**Comment by JonFerraiolo** [comment]
@doronrosenberg can you please investigate?

**Comment by doronrosenberg** [comment]
I'll cover this as part of #2135, looks like something we should support.

**Comment by doronrosenberg** [comment]
fixed by 128b36882c827a67a02afccb301f2dc1972a33ed
