### ISSUE TITLE
Blur of smart input tooltip dialog causes error

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2656]
1. New HTML page.
2. Add Dijit Button.  Notice that smart input automatically appears.
3. Click a different widget entry in Palette.

This action will cause the smart input dialog to hide, but errors our in `hide()`, trying to call `removeChild()`.  The error is:

```
Uncaught Error: NOT_FOUND_ERR: DOM Exception 8
```

Testing on Chrome/Mac.

**Comment by jhpedemonte** [comment]
Hmm, actually happens when clicking **OK** as well.

**Comment by doronrosenberg** [comment]
Tried mac chrome, not seeing this on trunk.  I didn't change the smart input dialogs though.

**Comment by doronrosenberg** [comment]
@jhpedemonte still seeing this?

**Comment by doronrosenberg** [comment]
Closing for now, please reopen if you still can repro this
