### ISSUE TITLE
"Error modifying value" dialog is incorrectly sized

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2657]
1. With (read-only) Claro theme set (the default), add a Dijit Button to page.
2. In **Properties > Layout** set **width** to 200px.

This will bring up the **Error modifying value** dialog, which is not correctly sized:

![dialog](http://i.imgur.com/Pm4BJ.png)

**Comment by aerwin** [comment]
Dup of #2645?

**Comment by jhpedemonte** [comment]
Dupe to #2645.

**Comment by jhpedemonte** [comment]
Reopening.  Saw this again today while testing on _maqetta-test_.  Exactly the same as the attached screenshot in the summary.  (Chrome/Mac)

Seen while running **Tests > Properties 5 > background-color on a Button using claro**.

**Comment by doronrosenberg** [comment]
@jhpedemonte does this happen all the time or just intermittently?

**Comment by doronrosenberg** [comment]
fixed hopefully by 760525d4c3ac6b6c6772c9606275f224c362fa27
