### ISSUE TITLE
Right clicking in Files palette throws error

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2662]
Open Maqetta, then right click on any file in the files palette (note: don't left click on the file first, just right click).

```
item is undefined
http://192.168.1.126:8081/maqetta/app/davinci/ui/Resource.js?@revision@
Line 294
```

**Comment by JonFerraiolo** [comment]
-> @peller to investigate - maybe a dojo 1.8 issue?

**Comment by peller** [comment]
It would appear to be a FF-only bug.  Right clicking doesn't select the item on FF.

**Comment by peller** [comment]
this is not new Dojo behavior.  I feel like we had a workaround to this bug which must have gotten lost in some of our Tree refactoring.

I can't seem to find a Dojo ticket on this, so I [filed one](http://bugs.dojotoolkit.org/ticket/15600)

**Comment by doronrosenberg** [comment]
I see this on the Outline palette too - right click without focus opens the context menu, but all items are disabled.

**Comment by peller** [comment]
see #570

**Comment by peller** [comment]
-> @doronrosenberg you worked on right click on tree widgets recently.  Can you take a look?
