### ISSUE TITLE
Should force cellspacing=0 even if user doesn't set value

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2663]
If you create a new table and accept defaults, no value gets set for cellspacing, so no cellspacing attribute gets added to the table element's root node, so the browser default is used (which I believe is 2). We should instead force a default value of cellspacing=0.

**Comment by aerwin** [comment]
@JonFerraiolo 

With the fix that just went in for #2709, I think this issue disappears. In particular, I believe this because I made `border-collapse` default to "collapse".

So, I'm going to close this one. If you disagree, please reopen.
