### ISSUE TITLE
Double-click on widget in Outline palette should bring up SmartInput

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2664]
@billreed63 @peller - I thought that at one point we supported double-click in Outline palette so that user can bring up SmartInput from Outline palette. Whatever, it isn't working in Preview6 or in latest code.

For HTML tables, it would be really handy if user could double-click on TABLE element to bring up @aerwin's new SmartInput dialog for tables. It will be tough on users to have to first select a cell and then go to context menu to select the TABLE and then double-click on the selection chrome to bring up SmartInput. (Note: double-click on a cell brings up SmartInput for the cell)

**Comment by doronrosenberg** [comment]
What is the correct way to launch an widget's smartinput?

**Comment by JonFerraiolo** [comment]
> What is the correct way to launch an widget's smartinput? 

good question! It hadn't occurred to me that this might be non-obvious. Look at ve/tools/SelectTools.js for routine onDblClick().  At line 315 you should see:

```
this._context.select(widget, null, true);
```

The 3rd parameter says to invoke inline edit (aka SmartInput) as a byproduct of the select() operation. 

(Yes, that code is ugly)
