### ISSUE TITLE
Tutorial(s), video(s) and/or blog(s) on HTML tables

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2666]
We have some major (and very cool) advances with HTML tables, but it would help users an awful lot if we had some instructions materials.

One topic in particular that is almost certain going to be non-obvious to users is how to control column widths in tables. My thinking is that we need to explain 'table-layout' of fixed vs auto, particular around controlling which columns have fixed size versus dynamic/stretchable sizing. With fixed, users can spread the stretching across multiple columns on using percentages (but you lose dynamic auto-sizing based on cell content), whereas auto only allows the use of asterisk for the column width value for columns that should be stretchable.

**Comment by aerwin** [comment]
Remember to consider some of the discussion in #2709 when putting together this documentation.

**Comment by aerwin** [comment]
@JonFerraiolo @jhpedemonte 

-> M8 
-> Prio High

**Comment by aerwin** [comment]
Closing... blog posted: http://ibm.co/U98Uev
