### ISSUE TITLE
ScrollableView not working after 1.8 merge

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2668]
@jhpedemonte @doronrosenberg 

Testing with latest code (both posted builds and run from Eclipse), attempt to drag/drop a ScrollableView widget onto canvas. Result is nothing is added. (eg nothing shows in Outline palette) 

NOTE: View and SwapView widgets are working.

**Comment by peller** [comment]
ScrollableViewHelper calls disableScroll in the constructor (see 9aa897b77c519c53f372d0bb52cbb066593a3304).  That method no longer exists, and I don't see where it ever did exist...  Comment out that line and the widget renders.  @JonFerraiolo, any idea where it came from or what might have replaced it?

**Comment by JonFerraiolo** [comment]
I don't remember for sure, but I'll guess that the call to disableScroll() prevents dojox.mobile from grabbing mouse drag events when the Maqetta page editor is up. 

@peller - can you please comment out the offending line with a commit, and then reassign this issue to me so I can jog my memory about why exactly we were calling disableScroll() and then figure out an appropriate alternative technique?

**Comment by peller** [comment]
-> @JonFerraiolo
