### ISSUE TITLE
Funny file name prompts when downloading as ZIP

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#267]
When you click one of the download buttons, you get prompted for a filename
(default: workspace1.zip). If you type something into the file name field,
sometimes it gets ignored or overridden by subsequent browser prompts. I don't
have details yet - just logging this for now so we don't forget. This bug
report needs further fleshing out by characterizing all of the possible
permutations. Maybe Firefox, Chrome and Safari work differently.

bug: 7762

**Comment by JonFerraiolo** [comment]
I put this as low priority for M4 - not absolutely essential, but a good percentage of users use the download as ZIP feature.

**Comment by JonFerraiolo** [comment]
Pushing to Priority-Med and M5.

**Comment by jhpedemonte** [comment]
-> M6

@childsb, is this still an issue?

**Comment by childsb** [comment]
tested, doesn't seem to be an issue.
