### ISSUE TITLE
remove davinci/ui/widget/ResourceTreeModel?

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2677]
This appears to be unused.  Only reference I see is in davinci/review/model/ReviewTreeModel, and it's not used in that module.  It's also got some incorrect resource usage (e.g. getChildren expects to be executed synchronously)  Can we remove it?

**Comment by JonFerraiolo** [comment]
@billreed63 @aerwin - see any problem with removing davinci/ui/widget/ResourceTreeModel?

**Comment by aerwin** [comment]
Yes, I agree with @peller... looks to be dead code.

**Comment by billreed63** [comment]
sounds like a plan
