### ISSUE TITLE
Event properties show different string for state changes than dropdown menu

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#268]
UI cleanup bug.

Right now the dropdown menu for the event attributes shows strings like "Add
Task: State" (if there is a state named "Add Task"), but the actual text string
for the event attribute will say something different (e.g.,
"davinci.states.setState('Add Task')"). The latter string reflects the actual
textual contents for the onclick attribute.

**Comment by aerwin** [comment]
-> @aerwin 

Addressed this as part of commit 4f74c74b58d1a703c20eeea401d5f66b748719e2 for #79.
