### ISSUE TITLE
Outline palette not updated when BorderContainer changed

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2680]
1) Create new desktop file 
2) DnD BorderContaier, take defaults when smart input is displayed
3) Expand the outline palette you should see BorderContaiener with 5 ContentPane children
4) Double Click on BorderContainer to get SmartInput
5) deselect "right" checkbox, click ok
6) On the canvas the right content pane is gone, as well as in the scource, but it is still displayed in the outline palette. 

The only way to get the outline palette to refresh is to reload the page

preview 6 is ok so maybe a 1.8 regression

**Comment by peller** [comment]
-> @doronrosenberg worked on the outline tree, I think.  If this is some dojo 1.8 mystery, please feel free to send back

**Comment by doronrosenberg** [comment]
Hrm, I had that working (and it works in my branch) but not on trunk, yay regression

**Comment by doronrosenberg** [comment]
OK, this is indeed a dojo 1.8 behavior change for trees, and its actually a good one.
