### ISSUE TITLE
Need toolbar icons for new tree smart input

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2689]
@JonFerraiolo 

Spin-off of #79...

Need toolbar icons for tree smart input. The existing buttons with labels are kind of clunky:

![screenshot](http://i.imgur.com/Iu9uG.png)

This could perhaps could be addressed at same time as tree node icons (#2688).

**Comment by aerwin** [comment]
@JonFerraiolo @jmockler 

Janet, is this something your team could help with?

**Comment by aerwin** [comment]
@JonFerraiolo ... maybe we can add this one to the UI meeting this week for discussion?

**Comment by jinsil** [comment]
Could you let me know what exact size of icons for these?
Is that possible to create the icon request for this item?
Please let me know..

Jin

**Comment by aerwin** [comment]
@jinsil Do we have a standard toolbar icon size used for other icons in Maqetta? I'd tend to think 16x16, but would defer to whatever you and team are putting together for the overall theming during the Maqetta redesign.

**Comment by aerwin** [comment]
@jinsil 

And, while we're talking about toolbar icons for this dialog, it would also be a nice-to-have to get sample icons for use in the tree. E.g., the dialog allows the user to set folder icon, open folder icon, and leaf icons. So, it would be nice to include icons for these in our samples directory so we can reference them in documentation.

The screenshot below shows the default icons that we'd like to describe to the user how to replace:

![screenshot](http://i.imgur.com/uktbl.png)

And, extra credit on top of the extra credit for sample icons, would be to have a couple of different sample leaf icons.

All of these sample icons would need to be 16x16.

**Comment by jmockler** [comment]
@aerwin - could we plan to demo this function in Friday's call. Its not clear to me what icons you're asking for and what the function is.

**Comment by aerwin** [comment]
@jmockler -- Sure, I'd be glad to.

@JonFerraiolo -- could you add this to the agenda?

**Comment by aerwin** [comment]
@JonFerraiolo 

Per ST... reopening while we wait for the toolbar icons.

**Comment by aerwin** [comment]
@JonFerraiolo 

CSS placeholders put in place with commit above for when @JonFerraiolo receives icons tomorrow night.

**Comment by aerwin** [comment]
Closing... looks like @JonFerraiolo updated my CSS placeholders.
