### ISSUE TITLE
onOpen handler for tree node runs in page editor context when tree auto-expanded

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2699]
With the new tree smart input (#79), onOpen handler for tree node runs in page editor context when tree auto-expanded.
1. Nw HTML file
2. Drop tree on page
3. In tree smart input, select the first node and put JS in the "onOpen" field (e.g., `console.log("onOpen!")`)
4. when click OK (or file is reopened), the onOpen JS for the node is run (e.g., in this case see "opOpen!") in console

It's a little worse with more advanced JS in the onOpen handler. E.g., if the onOpen handler switches states, then the state switch occurs in the page editor rendering.

**Comment by aerwin** [comment]
Also... this only happens if _autoExpand_ is set to true on the tree (which is our default).

**Comment by JonFerraiolo** [comment]
Interesting issue! We have logic in Maqetta to look for all HTML event attributes (e.g., onclick, onmouseover) and we deactivate those attributes in the page editor simply by removing those attributes when a page is viewed in the page editor. This is a nice general approach that required about 20 lines of code to pull off. Look at ve/widget.js:495, _Widget.js:468 and Context.js:1236 (search for "event attribute").

Maybe we need to supplement that logic with additional logic that looks for particular properties (generally begin with the string 'on') on Dojo widget constructors. One question would be how best to pull this off. We could possibly require that each widget's events are listed in widget metadata somewhere. (We talked about that at OpenAjax Alliance but that feature never made it into the OpenAjax Widget Metadata spec.)

**Comment by aerwin** [comment]
Thanks for the point to the lines of code... I'll have to go look at those...

This is a little different in that we're doing declarative `dojo.connect`s, so rather than looking for HTML event attributes, we might want to take steps to disable SCRIPT blocks of type "dojo/connect" that are within widget blocks. E.g., remove the JS inside those blocks when the page is viewed. 

```
 <div data-dojo-type="dijit.Tree" autoExpand="true" showRoot="false" childrenAttr="children" openOnClick="false" openOnDblClick="false" persist="false" dndParams="onDndDrop,itemCreator,onDndCancel,checkAcceptance,checkItemAcceptance,dragThreshold,betweenThreshold" dragThreshold="5" style="min-height: 1em; width: 100%; height: auto;" model="ObjectStoreModel_1">
   <script type="dojo/method" data-dojo-event="getIconStyle" data-dojo-args="item, opened">var iconStyle = item.iconStyle;if (opened && item.iconStyleOpen) {   iconStyle = item.iconStyleOpen;};return iconStyle;</script>
   <script type="dojo/connect" data-dojo-event="onClick" data-dojo-args="item, node, evt">if (item.onClick) {   dojo.eval(item.onClick);};</script>
   <script type="dojo/connect" data-dojo-event="onDblClick" data-dojo-args="item, node, evt">if (item.onDblClick) {     dojo.eval(item.onDblClick);};</script>
   <script type="dojo/connect" data-dojo-event="onClose" data-dojo-args="item, node">if (item.onClose) {    dojo.eval(item.onClose);};</script>
   <script type="dojo/connect" data-dojo-event="onOpen" data-dojo-args="item, node">if (item.onOpen) {  dojo.eval(item.onOpen);};</script>
 </div>
```

**Comment by aerwin** [comment]
Closing this one with intent to handle under #2715.
