### ISSUE TITLE
davinci.ve.ObjectWidget doesn't support data-dojo-type

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2700]
The `davinci.ve.ObjectWidget` object (used by data stores) doesn't support `data-dojo-type` (only `dojoType`).

**Comment by jhpedemonte** [comment]
Reopening.  I got most cases where **dojoType** is queried, except for **davinci/workbench/WidgetLite.js**.

**Comment by jhpedemonte** [comment]
-> M8, High

**Comment by jhpedemonte** [comment]
-> M9

**Comment by jhpedemonte** [comment]
-> M10, @peller
