### ISSUE TITLE
re-enable gzip on server

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2704]
at least in the zazl target.  @rbackhouse had a conflict between gzip and his server:

> The Zazl OSGi launch runs without the gzip filter (davinci.server.gzip). This is what hung me up yesterday. The response that the zazl filter was getting had been gzipped and was not readable without first unzipping. Filters are not orderable in Equinox so its hard to know when the content in the HTTP response needs to be unzipped to be read and modified by the zazl filter.

@childsb

**Comment by rbackhouse** [comment]
To clarify, gzip has only been disabled in the new launch added for running with Zazl for preview. I think the solution will be for me to peek at the first 3 bytes of the response to see if its a gzip signature and use a GZIP inputstream to read.

**Comment by rbackhouse** [comment]
The response is now checked for gzip before attempting to be scanned.
