### ISSUE TITLE
document.css messes up cellpadding on tables, need to remove cellpadding (and replace cellspacing)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2709]
@billreed63 @peller 

Sorry about this.

When investigating #2602, to my great disappointment, I see that the claro theme's `document.css` file is forcing margin=padding=0 on all TD and TH elements. This style rule has higher precedence in the CSS cascade than the `cellpadding` attribute on the TABLE element.

We need document.css for proper look/feel of Dojo widgets. I think the only thing we can do in the short term is remove the cellspacing option from the table SmartInput dialog. Sorry. This is unfortunate because we will be losing a key simplicity feature for our users, and I can't think of an alternative way to deliver the feature that is both easy/convenient/intuitive for users and that is feasible for us to implement in a short amount of time because the CSS equivalent requires attaching styling properties on each of the cell nodes (i.e., TD or TH). At this point, the only alternative approach that I can think of in today's browsers is that the user opens app.css and adds lines like this to the file:

```
#myapp td, #myapp th {
  padding:5px;
}
```

And if we are going to get rid of cellpadding, we should probably also get rid of the much-less-useful cellspacing and instead replace it with a checkbox for the 'border-collapse' CSS property, with a default of true.

PS: Did I say I'm sorry about this?

**Comment by aerwin** [comment]
Quick discussion on TH vs. TD w/ @JonFerraiolo ...

6:10:10 PM: aerwin@us.ibm.com - I'm thinking it also means I need to remove the checkbox for header row as well
6:10:23 PM: aerwin@us.ibm.com - TH renders just like TD with document.css 
6:10:43 PM: jferrai@us.ibm.com - really, even fonts are the same? 
6:10:46 PM: aerwin@us.ibm.com -  yes 
6:11:26 PM: jferrai@us.ibm.com -  I'd leave it in, but we will have to have some tutorials or videos or blogs or whatever that explains hand-editing of app.css, including how to put different styling an the TH elements 
6:11:39 PM: aerwin@us.ibm.com - ok

**Comment by aerwin** [comment]
Marking closed with above commit.
