### ISSUE TITLE
app.js code improvements

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2711]
the check for if(dojo...) is incorrect, since if Dojo is not defined, it will throw a ReferenceError.  We should also be using require("dojo/domReady!") here instead.

@JonFerraiolo @rbackhouse

**Comment by peller** [comment]
We generally assume the existence of an AMD loader on the page now, as we do with the states code.  Using AMD, the file might look something more like this:

```
/*
 * This file is provided for custom JavaScript logic that your HTML files might need.
 * Maqetta includes this JavaScript file by default within HTML pages authored in Maqetta.
 */
window.addEventListener("load", function(){     // Browser load event: browser is ready
});

require(["dojo/domReady!"], function(doc) {
    // logic that requires that Dojo is fully initialized should go here
});
```

though I'm not sure there's much point in providing code for the browser load event.  I'm also not sure if it's supported to use this code in a script tag.  It should probably be an AMD module itself, pulled in via require?

**Comment by JonFerraiolo** [comment]
@jhpedemonte 

Yes, our pages assume the Dojo loader is available, so please proceed to change the standard boilerplate around app.js to use AMD, and thanks for noticing this.

Regarding the browser load event, I found that check was necessary when I was testing the feature on user pages. As I remember, using the previous approach for app.js, dojo.ready was undefined at the time the app.js file was parsed. But if we switch to AMD, then require() should be available when app.js is parsed, so I believe we can remove the window.load listener and just have `require(["dojo/domReady!"]`.

Should be easy to test. Just create a new HTML Page in Maqetta, edit the app.js in Maqetta and insert an alert statement inside of the require(). If preview-in-browser doesn't show any exceptions and the alert appears, things should be fine.

**Comment by peller** [comment]
I think it comes down to how the "app.js" module is included.  Presently, it is referenced by script tag.  I'm not sure that's correct.  Dojo may or may not have loaded, so there may be a race condition there, especially with an optimizer running or a large layer for dojo.js.  Alternatively, it could be included as a module like maqetta/states.

Regardless of how it's referenced, I'm not sure I like including this file by default.  It results in an extra network hit.

**Comment by peller** [comment]
Taking this a bit further, are devs going to be surprised to see app.js code run on every page they create, rather than authoring custom JS code on a page-by-page basis?

**Comment by JonFerraiolo** [comment]
I talked this over with some users and they actually recommended the single pre-installed app.js approach. This whole feature was the result of working with users. For a good chunk of our users, it's within their comfort level to add some snippets of JavaScript to a pre-installed app.js file, but too much for them to learn about how to add a SCRIPT tag for their own custom .js file. So far, we have a lot of early adopters who really aren't JavaScript programmers (e.g., UX designers), but are capable of including bits of JavaScript via copy-by-example approaches.

It's worth the extra network hit. But if we switch it to loading via a require() inside of a SCRIPT instead of a separate SCRIPT tag, won't app.js get built along with the rest of the user's page?

**Comment by peller** [comment]
I can understand having a common JS file to contain functions, like a library, but when the act of including the file triggers UI or other action, I'd think making it shared would be confusing.  Just my $.02

Yes, moving to an AMD module instead of a SCRIPT tag would potentially let the optimizers avoid the hit.  Still, it's a dead code reference by default.  Given that we don't yet have a mechanism to add/remove JS modules which aren't widgets in the visual editor, I suppose this is the best we can do.  I'm not sure off hand whether we can add something like add.js without a 'namespace' addition and a folder, though we can probably just reference it as a non-AMD module (no define in the module, but using require to pull it in)

**Comment by jhpedemonte** [comment]
> I think it comes down to how the "app.js" module is included. Presently, it is referenced by script tag. I'm not sure that's correct. Dojo may or may not have loaded, so there may be a race condition there, especially with an optimizer running or a large layer for dojo.js.

Scripts can be _downloaded_ in parallel, but they are _evaluated_ in the order on the page.  So as long as the app.js script tag comes **after** that of dojo.js, it'll be fine.

I think it's fine to keep app.js as a script tag...
