### ISSUE TITLE
Duplicate WIdget palette search box

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2712]
@doronrosenberg @childsb 

One of our users reports:

I tried modifying the user libraries using the "Modify Libraries" option in the "Files" view tool bar and saw a duplicated "Search box" in the widgets palette.

@jhpedemonte responded:

Known issue, although I don't think we have a but open for that. Mainly because we are planning on redoing the Widgets Palette sometime soon.

**Comment by JonFerraiolo** [comment]
Pushing to M8. Haven't seen this problem recently.

**Comment by JonFerraiolo** [comment]
@jhpedemonte - pushed to M8 - haven't seen this recently.

**Comment by jhpedemonte** [comment]
I've seen it recently.  Usually can be recreated by opening a file (so widget palette is visible and populated) then modify libs in order to add/remove the widgets available -> causes filter box to appear.

**Comment by JonFerraiolo** [comment]
Closing this. I'm pretty sure this was fixed when I moved the search box into the Toolbar area. (Previously, it was in the widget list area.)
