### ISSUE TITLE
Go into split view: document becomes dirty

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2716]
@childsb @doronrosenberg 

Dave reports:

When I view the code in the Designer, not even editing, the filename in the tab gets a "*" indicating the file needs to be saved (again)

**Comment by JonFerraiolo** [comment]
@peller 

-> @doronrosenberg Could you please examine this and see if a reasonably safe fix is possible for M7? I guess one possible solution would be, before each attempt to do a setText() using latest source code into the model is to see if the new source text is different than the existing source text.

**Comment by peller** [comment]
Ideally, we wouldn't setText at all when just changing the editors around.

I don't see this problem in the latest code.

**Comment by doronrosenberg** [comment]
Not seeing this anymore as well, probably fixed by my other changes for dirty.
