### ISSUE TITLE
Source editor jumps the cursor to the top of the screen

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2717]
@doronrosenberg 

Dave reports: 

Noticed that quite often (and I'm sure there's a pattern to this), the source editor jumps the cursor to the top of the screen.  Probably when a component is manually entered or modified.  EXTREMELY ANNOYING!

Logging this with Prio-High for the moment to investigate and determine if this is a ubiquitous problem, a common problem, a rare problem, or cannot reproduce with latest code, and then adjust priority accordingly.

**Comment by aerwin** [comment]
--> Prio from High to Critical

**Comment by peller** [comment]
seems to be ok as of the merge at d006ad0b30587e7f878faa6bd4839ab1fa08f30c
