### ISSUE TITLE
Split widgets.json from package.json

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2718]
Originally, when Adam said he was going to combine **widgets.json** into **package.json**, I assumed he meant that we would do this dynamically in the server, not in the source itself.  That wasn't the case, but I ran with it.  However, I've come not to like this situation and think the the two should be separate files in the source.
1. Separate files are easier to document.  **package.json** is its own specification and, while it has some leeway for custom additions, the full contents of **widgets.json** doesn't fit into it.  Likewise, **widgets.json** has its own purpose and function (to list widgets and their metadata) which aren't shared by **package.json**.
2. When we get rid of the OSGi packaging for the widget libraries, the main entry point will be **package.json**.  It should be concise and to the point, listing only the metadata relevant to the library as a whole.
3. In later versions, we will want to allow metadata only libraries, which have a dependency on the library package containing the actual library code (i.e. see the Dojo, Dijit and Dojox packages at the [Dojo Package Repository](http://packages.dojofoundation.org/) [1]).  See the [Library Packages wiki page](https://github.com/maqetta/maqetta/wiki/Library-Packages) for details.  As you can see in the linked wiki, the dependencies are carried through the **package.json** files, which are the the top most level.  The **widgets.json** file resides inside the metadata directory.

[1] There are other JS package repositories appearing, such as [Jam](http://jamjs.org/).

---

Proposal: Split into separate **package.json** and **widgets.json** files.  If we wish to cut down on the number of network requests, then we can handle the merging dynamically on the server (with caching). [2]

[2] Sounds like Zazl cannot handle this type of merging.  Will it even be able to?

@peller @JonFerraiolo @childsb

**Comment by JonFerraiolo** [comment]
I'm ok with either combined or separate.

**Comment by peller** [comment]
The code still supports separate widgets.json files, we'd just have to split out the data again.  However, the code should be restructured so that it kicks off the dojo.xhr requests simultaneously and uses sync:false for both (probably need to use a DeferredList.

**Comment by peller** [comment]
Zazl only deals in AMD.  If you want to concatenate/transform the JSON into some larger structure that could be processed by the client in place of the two files, that should work.

**Comment by jhpedemonte** [comment]
We already have code in **metadata.js** that can handle this split or combined (although I think the the "split" route may need to be updated following Adam's [suggestion above](https://github.com/maqetta/maqetta/issues/2718#issuecomment-6892958)).

So I was proposing that we do the merge in the server and send that down.  To the client, nothing would change from the current code, where the files are merged.  But it should still work in the future, in the case where we get libraries from external sources and the files are separate.
