### ISSUE TITLE
Dojo build of UI plug-ins no longer minifies all the parts

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2719]
@peller @childsb 

Looking at the build output for the various UI plugins (gridx, shapes, clipart, etc.), it seems that the only parts getting built are the layers explicitly listed in the respective profile.js files in each plug-in. It used to be every part was built (giving us advantages with minification, inlining of templates, etc.) even when not explicitly included in a layer. And, this was a good thing because we had expressly decided not to build large, complicated layers.

I don't know for sure when this changed, but I wonder if perhaps the dojo 1.8 build tools behave differently than the dojo 1.7 build tools?

**Comment by aerwin** [comment]
I don't know if something has changed recently to improve the situation, but looking at the files in the most recent build... it looks like all of the parts actually _are_ being built. Perhaps that was the case when I opened the problem. But, it wasn't obvious because:
- there is no `\\built` comment at the top of the files like there used to be (not really a "problem")
- the parts are _not_ being minified (though HTML template inlining is working)

With that in mind, I'm going to:
- change the name of the issue from "Dojo build of UI plug-ins no longer builds all the parts" to "Dojo build of UI plug-ins no longer minifies all the parts"

**Comment by peller** [comment]
-> @peller

**Comment by aerwin** [comment]
--> @aerwin 

I believe my fixes related to #2796 will fix this one too.

**Comment by aerwin** [comment]
Marking closed based on commit 6a1ab9931e7065c1c8554941590c214bd39f1343 put in for #2796.
