### ISSUE TITLE
Document keyboard navigation 

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2721]

**Comment by aerwin** [comment]
--> prio from not set to med

**Comment by jhpedemonte** [comment]
Set to Priority High.  Must for 1.0.  I currently have no idea exactly which keyboard bindings are available.

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg. I created a new page in the docset (maqetta.core.client/WebContent/docs/peKeyboardShortcuts.html) and included entries for all keyboard shortcuts that have keyBinding properties within ve.plugin.js. Could you please review that page, add shortcuts that are missing, and fix errors, and then please close this issue?

Note that you can get to the new page in the Maqetta UI via Help->Documentation, open up Using Maqetta, then open up Page Editor, and the last item in that section is titled "Keyboard Shortcuts".
