### ISSUE TITLE
Invalid target dialog poorly sized

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2723]
Not urgent, but should fix before M7 goes out.
- New HTML File - sketch mode
- Attempt to drop a mobile View widget onto canvas

Result=> Triggers an error dialog because View widgets can't be added in absolute positioning mode. That's fine, but the dialog sizing is messed up.

**Comment by doronrosenberg** [comment]
It just sizes to the widget of the message - are you saying its too long?

**Comment by JonFerraiolo** [comment]
Closing, at least for the time being.

I was seeing a different problem than just that the dialog was wide. There were other problems. (I should have taken a screen capture). But until I see it again, let's close it.
