### ISSUE TITLE
Wrong URL for background-image when overriding value in custom theme

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2737]
@childsb 

See also @2422 
- Create new theme claro2
- New HTML File
- Add a dijit.form.Button
- Switch to claro2 theme
- In Properties palette, click on one of the "..." buttons in the Background section.
- Choose "image" and select one of the images in samples/sample_data/images as the background image
- Click OK, and then click OK in the global theme change warning dialog

Result=> Icon doesn't show in the button. The reason is that the URL is wrong. The URL is relative to the page's base URL, but because of the way CSS works, the image URL needs to be relative to the CSS file that contains the background-image property definition (i.e., the theme's CSS file).

**Comment by billreed63** [comment]
fixed by #2422
