### ISSUE TITLE
changes to theme editor are immediate

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2742]
change the border color on the global widget.  notice that changes take effect immediately in all open html editors. 
now, close the theme editor without saving.  say ok to the prompt that says you'll lose your changes.
the open documents still reflect the changes made.
reopen the theme editor. the theme still has the background color. 

Personally, I prefer this behavior.  We could just remove the 'save' button and rely on autosave.

**Comment by billreed63** [comment]
We changed the code so that all the resources that use the theme share a singleton to the resource. The working copy is only deleted when all the editors that share that resource are closed. 

So it is working as designed, but we at least need to change the wording of the message.

**Comment by JonFerraiolo** [comment]
We can't get rid of the save button at this point. Much too radical a change at this late date. Regarding the new behavior, yes, that's what we agreed to do. As I remember, you only get the prompt if you change themes.

**Comment by aerwin** [comment]
> no milestone to M7, priority Low (wording change)

**Comment by billreed63** [comment]
the message now reads
"The file has unsaved changes, are you sure to want to close?"
