### ISSUE TITLE
ListItem SmartInput doesn't deal with moveTo right arrow properly

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2744]
@billreed63 @doronrosenberg 

When upgrading LIstItemHelper.js for Dojo 1.8, I must have messed up. When SmartInput comes up for a ListItem that has a 'moveTo' property, SmartInput shows the HTML markup for the arrow.

**Comment by doronrosenberg** [comment]
Ugh, ListItem is a bad widget, it has no label getter method
