### ISSUE TITLE
Double-click on ListItem twice in page editor and ListItem is active

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2749]
@billreed63 @aerwin 

With latest code pulled from GitHub:
- Bring up Sample3-Mobile.html
- Double click on the "Alerts" ListItem to bring up SmartInput
- Click Cancel on SmartInput
- Double click again on the "Alerts" ListItem to bring up SmartInput

Result=> SmartInput comes up, but under SmartInput you'll see that the current view has switched to "alerts_view". We are supposed to be intercepting mouse clicks to prevent Dojo from processing interactive events. Somehow or other that interception logic is being thwarted in this particular case.

Note that this might be a really tough bug to figure out. Feel free to send back to @jonferraiolo.

Implementation notes: There is a mostly transparent gray overlay box ("editFeedback") that appears over primitive widgets by logic in _Tool.js (called by mousemove/mouseover routines either in either Context.js or SelectTool,js, I forget the details) and this often helps intercept the mouse clicks. Double-click logic is in SelectTool.js as I remember. I suspect that the first click might be removing the "editFeedback" overlay DIV and the second click is now going through to the widget. However, I don't know what has changed recently to cause mouse clicks to go through because I can't make the same thing happen with Preview 6.0.1.

**Comment by doronrosenberg** [comment]
I'm swapped with mobile issues right now but if it can wait a sprint I can take it back.

**Comment by JonFerraiolo** [comment]
Yes it can wait until next sprint.
