### ISSUE TITLE
Implement dojox.mobile badges on widgets

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2750]
For #2135 - implement badges!

**Comment by doronrosenberg** [comment]
@jhpedemonte @JonFerraiolo 

Some mobile widgets like Tabbarbutton and IconItem support iOS-like badges now.  However, for them to style correctly you have to include `<link href="../themes/common/domButtons/DomButtonRedBadge.css" rel="stylesheet"/>`

Never done this before - would I just include the css file in all widgets that support badges?

**Comment by JonFerraiolo** [comment]
@billreed63 ?

**Comment by billreed63** [comment]
Where are they included from, they are located in maqetta/themes/dojox/mobile/themes/common  but we may have issues when using the standard default mobile themes. It might be best to use the path to the CSS in the dojo `lib/dojo/dojox/mobile/themes/common/....`

**Comment by jhpedemonte** [comment]
Well, normally, since this would be a requirement for a widget, you would include it as a `require` property in the OAM file.
