### ISSUE TITLE
Review editors don't reopen with browser refresh

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2752]
@aerwin @peller 

Something broke after Preview 6.
- Create a new Review
- Open that review so that there is a single review editor open
- Browser refresh

Result=> No editors appear after browser refresh. This is a regression versus Preview 6. The workbenchState.settings file correctly lists the review editor, but upon restarting, Maqetta isn't opening up the current open review editors.

**Comment by aerwin** [comment]
--> @aerwin 

This appears to be working... think this is a dup against some other fixes I made recently. So, closing as well.
