### ISSUE TITLE
Zazl error on initial load

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2754]
When first loading Maqetta, I see the following error in the browser console:

```
GET http://lab9.austin.ibm.com:50010/maqetta/app/metadata/core/0.3/package.json?6892d9c1a7b65a39e79de2e5165983de1fc5f125 404 (ProxyServlet: /maqetta/app/metadata/core/0.3/package.json)
```

I also see that "zazl" is listed in the **Modify Libraries** dialog.  Have we registered the Zazl plugin as a widget library, by accident?

@childsb

**Comment by peller** [comment]
thought I logged a ticket on this, but can't find it.  Yes, we have an issue that the maqetta/zazl adapter plugin uses the ajaxLibrary extension point and puts a file (lib/zazl.js) on the servlet, but does not represent a maqetta library.

Tried a suggestion from @childsb here 0d629ef0c30d24913a5da0f39290984787c1d0fa but it didn't work.  I may have misunderstood the suggestion for the patch.

**Comment by peller** [comment]
fix path: 01b0afe5356caa1ff420fa32041208e07d578585

**Comment by peller** [comment]
exception is gone, but zazl is still visible in the user libraries dialog, along with maqetta, which is also not really a user library.

**Comment by peller** [comment]
see #1512
