### ISSUE TITLE
Very slow to create new file tab/editor

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2755]
Testing on lab9:50010, I created a new file.  Between the time that the _New File_ dialog disappeared and the new file editor appeared, greater than 5 seconds transpired. 

During that time, there was no indication that anything was happening and the app was unresponsive.

---

Proposal:  the editor tab UI should come up **immediately** after the _New File_ dialog disappears, with a spinning wait cursor.

**Comment by jhpedemonte** [comment]
Addendum to the above:  Open a couple of VE tabs and add some widgets in each.  Reload the page (reload Maqetta).  When reloading, I see the black bar at the top appear, but the rest of the page is blank.  About **12 seconds later**, then rest of the UI (including the open VE tabs) appears.

**Comment by peller** [comment]
let's wait until #2126 is done and see where we are on this

**Comment by aerwin** [comment]
--> Prio from High to Critical
