### ISSUE TITLE
Error loading document.css for Preview of file in subfolder

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2756]
Did "Save As" on a page with a couple of TabContainers.  In the Save As dialog, I created a new folder ("asdf") and saved the file as "foobar.html" in that folder.  Loaded Preview and immediately got this error (in the Preview page):

```
Failed to load resource: the server responded with a status of 404 (Not Found) http://lab9:50010/maqetta/user/user@user.com/ws/workspace/project1/avcs/themes/claro/document.css
```

**Comment by aerwin** [comment]
--> Prio from High to Critical

**Comment by billreed63** [comment]
The saveAs code needs to change the path on all CSS files, While this is a bug we need to fix I don't think this is Critical the user can update the path in the source editor.
--> Prio from Critica to High
