### ISSUE TITLE
Preview of table with empty cells shows "?" as content

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2759]
If I preview an HTML table which has some empty cells, the empty cells appear with "?" as the content in the Preview page.

**Comment by aerwin** [comment]
@peller , thoughts?

This appears to be a zazl issue... The question marks appear when only when the zazl=true attribute is added:

```
http://lab9:50010/maqetta/user/aerwin/ws/workspace/project1/file1.html?zazl=true
```

We made a design decision to use the non-breaking white space char  ( & # 8 2 8 8 ;  )  in empty table cells. It looks like zazl is turning them into question marks.

**Comment by peller** [comment]
yes, sounds like an encoding issue.

**Comment by peller** [comment]
@aerwin which file has the special chars?

**Comment by aerwin** [comment]
@peller -- drop an HTML table element from widget palette onto your HTML page and click OK on the smart input. Empty cells will contain the & # 8 2 8 8 ; char.

Within Maqetta code, the & # 8 2 8 8 ; char is referenced in package.json for the davinci.html package as well as the JS files for `TableCellInput`, `TableInput`, and `TableMatrix`.

**Comment by peller** [comment]
ok, so it's inline in the HTML page.  got it.

**Comment by peller** [comment]
This only seems to happen in the built Maqetta, not running from Eclipse.  The page is served up as iso-8859-1 in both situations, though.  The META tag says utf-8, but is probably not known to MaqettaHTMLFilter.java  None of that would be an issue, though, if the HTML escape remained in place.  Something seems to be parsing and serializing the HTML... must be the HTMLParser in the filter.  @rbackhouse, does this make sense?  Would be nice if that filter were aware of the META charset tag.

One possibility is to just override the encoding in MaqettaHTMLFilter.java with UTF-8.

**Comment by rbackhouse** [comment]
The filter is using whatever encoding was set on the response via a call to setCharacterEncoding. I noticed that DavinciPageServlet is setting the encoding to be UTF-8 regardless of what the encoding actually could  be :

line 383
        resp.setCharacterEncoding("UTF-8");

**Comment by peller** [comment]
the character encoding of the response in the filter is definitely ISO-8859-1.  Shouldn't it be UTF-8 based on what you said?
