### ISSUE TITLE
Highlight VE views icons to show active one

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2761]
The icons for the 4 VE views (visual, source and the 2 split views) should highlight to show which one is currently enabled.  Useful when using the keyboard shortcuts to select the views.

@JonFerraiolo @doronrosenberg

**Comment by aerwin** [comment]
Perhaps a dup of #1042?

**Comment by jhpedemonte** [comment]
Good find.  I'll close this one out and comment on that one.
