### ISSUE TITLE
new html file always shows <root> for folder even if other folder is selected

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#2764]
1) create a new project
2) create a new folder (folder1 is fine) notice that its highlighted in the UI
3) leave the selection on the previously created folder and create a new folder (ie folder1/folder1). notice folder1/folder1 is selected in the UI
4) issue a new html file command.  <root> is selected as the default folder even though folder1/folder1 is selected in the explorer tree.

**Comment by JonFerraiolo** [comment]
@doronrsosenberg - if there is too much learning curve on this one, ok to reassign to me. I wrote the new html dialog.

**Comment by doronrosenberg** [comment]
@peller Seems to be a 1.8 bug here, I emailed you and bill keese with my observations.

**Comment by aerwin** [comment]
--> Prio from High to Critical

**Comment by peller** [comment]
Fixed by @wkeese in [Dojo r29266](http://bugs.dojotoolkit.org/changeset/29266/dojo)  We will pick this up when we move to Dojo 1.8.0rc1

**Comment by doronrosenberg** [comment]
fixed now
