### ISSUE TITLE
dojo-src should be removed from userlibs download, by default

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2769]
related to #1512

dojo-src is present for use by zazl.  I suppose it might be nice to optionally provide it in a download (unsure if this is necessary) but we definitely do not want it in the download by default because it is so large.

We need a bit to tell Maqetta not to include dojo-src as a user library in the download by default, or perhaps not at all

@jhpedemonte

**Comment by peller** [comment]
possibly related to #2517  Note that dojo-src is never referenced by code.  Only Zazl uses it by directly manipulating the source.

**Comment by aerwin** [comment]
@childsb @peller @jhpedemonte 

While looking into #2913, I discovered from the RAD team that the RAD 8.5 widget palette doesn't work with built Dojo. So, what this means is I didn't see any Dojo widgets in the RAD 8.5 palette when I created an Eclipse-based project in Maqetta, downloaded it from Maqetta with all of the defaults , and then imported it into RAD 8.5.

However, things seem to work ok when I uncheck `dojo` and leave `dojo-src` checked when I download my Maqetta project. So, some conclusions/proposals for discussion as we debate the presence of `dojo-src` on the download dialog:
- we need to leave `dojo-src` in the download dialog to support scenarios involving integration with other IDE's
- having both `dojo` and `dojo-src` checked at the same time doesn't make sense (at least not with both defaulting to the same path) as it seems the `dojo` "wins" and no unbuilt source makes it into the zip file
- it would be nice for Eclipse projects to default to `dojo-src` being checked and `dojo` being unchecked
- it's almost like we need something like this (even though I know it looks kind of gross and probably more than we want to do for M7) where once they choose to include dojo there's another checkbox whether to use source or not:

![screen](http://i.imgur.com/ms1Qj.png)

**Comment by peller** [comment]
the content in dojo-src, as far as I know, is only used by zazl in preview mode

**Comment by aerwin** [comment]
Right.... what I'm saying is we need to make it available if we want users to be able to easily migrate to other IDE's (like RAD 8.5).

**Comment by jhpedemonte** [comment]
Ugh.

Yes, if we need to, I prefer something along the lines of what Tony has outlined above, rather than both "dojo" and "dojo-src" entries.

**Comment by peller** [comment]
Based on today's call, we can have a single checkbox in the Download... dialog to indicate that the user wishes to download unoptimized sources where available.  Box should be checked by default for Eclipse projects, unchecked by default otherwise.

**Comment by jhpedemonte** [comment]
Reopening.  Need to make the "Download full source" checkbox enabled by default for Eclipse projects.

**Comment by childsb** [comment]
closing.  new work is in #3178
