### ISSUE TITLE
dojox.mobile.TabBar defaults to wrong barType

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2775]
Create a iphone html page
DnD a TabBar on to the page.. Notice that the bar is black (like android) 

in properties palette change the widget specific property "barType" to segmentedControl Now it looks like the device

I have no idea why the phone CSS style looks like to an android but all the themes are that way so apparently to get the device look we need to use the segmented barType

**Comment by doronrosenberg** [comment]
The black bar exists on iOS too (see http://developer.apple.com/library/ios/#DOCUMENTATION/WindowsViews/Conceptual/ViewControllerCatalog/Chapters/TabBarControllers.html), the other barType is the top tabs.
