### ISSUE TITLE
We are eating exceptions during widget creation

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2780]
@peller @jhpedemonte 

Drag and drop a ScreenSizeAware widget from untested - it fails and throws an exception internally, but never shows in the console.  The exception is in DijitWidget.js line 71

**Comment by JonFerraiolo** [comment]
Setting to M7/Prio-Low - would be nice to look at this. I've noticed that something changed in last couple of months where exceptions aren't showing in console in some cases.

**Comment by peller** [comment]
there are known regressions in Deferred/DeferredList which are due to be fixed in 1.8.0rc1

**Comment by peller** [comment]
moving to promise/all seems to have fixed this.
