### ISSUE TITLE
New app.js doesn't work very well

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2788]
@peller 

It looks like 0ad21b2f40131f7c860f6d6e9e630ea5f76e4e1f changed app.js to use dom/ready!. However, when I tried to put some sample app.js code I had put together for a Google groups user, things no longer worked...

So, instead of :

```
/*
 * This file is provided for custom JavaScript logic that your HTML files might need.
 * Maqetta includes this JavaScript file by default within HTML pages authored in Maqetta.
 */
require(["dojo/domReady!"], function(doc) {
    // logic that requires that Dojo is fully initialized should go here
});
```

I think it needs to be the following if we want users to be able to look up dijit's (making use of `dojo/ready` and the `ready` function:

```
/*
 * This file is provided for custom JavaScript logic that your HTML files might need.
 * Maqetta includes this JavaScript file by default within HTML pages authored in Maqetta.
 */
require(["dojo/ready"], function(ready){
     ready(function(){
         // logic that requires that Dojo is fully initialized should go here

     });
});
```

Doing it this way, I was able to start looking up dijit's again. If no objections, I can check that in...

**Comment by peller** [comment]
dojo/ready is deprecated.  dojo/domReady! is supposed to be better...  maybe it's not?

**Comment by aerwin** [comment]
When was it deprecated?

http://dojotoolkit.org/reference-guide/1.7/dojo/domReady.html#dojo-domready says:

```
Note that waiting for dojo/domReady! to fire is often not sufficient when working with widgets. Many widgets shouldn’t be initialized or accessed until the following modules load and execute:

dojo/uacss
dijit/hccss
dojo/parser
Thus when working with widgets you should generally put your code inside of a dojo/ready() callback, or use nested requires statements.
```

**Comment by peller** [comment]
You're right, Tony.  The docs for `dojo/ready` suggest that it has been (mostly) replaced by `dojo/domReady!`, but there are some big exceptions for dijit, in particular, knowing when the parser has run.  Proceed with your change.  Thanks!
