### ISSUE TITLE
CSSParser CSSModel does not support pseudo-classes correctly

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2794]
If a selector has a pseudo-classes in the middle of the selector

```
.claro .dijitCalendarHoveredDate .dijitCalendarDateLabel, .claro .dijitCalendarEnabledDate:hover .dijitCalendarDateLabe1
```

When the `rule.getSelectorText();` is called the returned text is 

```
".claro .dijitCalendarHoveredDate .dijitCalendarDateLabel, .claro .dijitCalendarEnabledDate.dijitCalendarDateLabel:hover"
```

Do to this issue we can't set some selectors in the CSS like dijit.calendar

**Comment by JonFerraiolo** [comment]
-> @billreed63 hope that's OK. At the moment, you are in best position to address this.
