### ISSUE TITLE
dojo metadata build broken with 1.8.0rc1

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2796]
Best I can tell, there were always errors in the build, Dojo just didn't seem to return the error code to halt the build.  Among the problems were references to davinci/\* and dojox/\* from the metadata.  Only dojo and dijit were copied over and referenced via "packages" in the build profile.  Also, it seems that layerDependencies like davinci/davinci should be listed.  Once I added those, other errors appeared, mostly nls references in orion.

**Comment by peller** [comment]
To try to address the missing reference errors, I tried adding packages: to dojo.profile.js to match all the array used in davinci.profile.js (adding dojox, davinci, orion, system,preview...)  and also copying over the corresponding directories in the widgetPluginDojoBuild.xml script.  As a result, those errors went away, but up came new ones: http://pastebin.com/C74qtmLz

**Comment by peller** [comment]
possible culprit in Dojo 1.8.0rc1: http://bugs.dojotoolkit.org/ticket/14127

**Comment by peller** [comment]
I think I fixed the other errors that I was seeing in orion with i18n!   Time to give this another try.

**Comment by aerwin** [comment]
Marking closed based after above commit.
