### ISSUE TITLE
De-emphasize Cancel and other non-default buttons

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2800]
Right now, the **New HTML File** dialog has 3 buttons: _Create_, _Cancel_ and _Theme_.  All of them look the same and it is not readily apparent which button corresponds to the **dialog's default action**.

We should de-emphasize every button that is not associated with the default action.

In the case of the _New HTML File_ dialog, I would prefer if both _Cancel_ and _Theme_ were simple links.  But it doesn't seem that that's the way we are going and we'd keep both as buttons.  What about just making _Theme_ a link?

As for _Cancel_, if it is to remain a button, then we should make it a simple outline of a button.  That is, a thin border in a button shape, with a white background.

This way, _Create_ will clearly stand out in this dialog.

---

Note: I just used _New HTML File_ dialog as an example.  All dialogs currently have this problem.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
Gotta work with UI folks before we make any changes here.

**Comment by doronrosenberg** [comment]
We can style a button to look like a link.  Another choice would be to have cancel be an icon rather than text or perhaps adding an icon only to the default action button.

**Comment by jhpedemonte** [comment]
Something as simple as specifying a white background for non-default buttons would work:

![buttons](http://i.imgur.com/bvWOc.png)

**Comment by jhpedemonte** [comment]
-> @JonFerraiolo, who is driving UI issues.

**Comment by JonFerraiolo** [comment]
@jmockler and @jinsil - Note that all our dialogs right now are styled using claro defaults. I'm pretty sure we will want to restyle our dialogs to have a grayscale look like the new UI for the main application (and maybe that's the best time to change styling on Cancel buttons). 

I know we've talked about this before, and sorry for asking again, but how should we style Cancel buttons on dialogs, under the assumption that we overhaul the visual styling of dialogs? (It's too late and too risky in the M7 cycle to attempt to do major restyling of dialogs, but probably can do it for M8)

**Comment by jinsil** [comment]
We can make Create button : bold , Cancel : normal. But I also Iike the idea above too-Create : blue, Cancel: white.

**Comment by JonFerraiolo** [comment]
@jinsil Thanks. I would vote for using **boldness** to identify the default action button for the short-term, and then within next few months talk about restyling dialogs away from claro's blue tint into something more grayscale that matches the application's main UI. Making non-default buttons have a white background is too radical a change for one particular aspect of the UI, whereas everything else about our dialogs isn't changing. If we are going to do something more visually radical, we should do so in conjunction with a more comprehensive visual redesign of how we style dialogs in general (i.e., when we implement a different styling than the claro blue tint)

@doronrosenberg Now the question is how we can implement this. In the debugger, don't see any special CSS classname for the default "Create" button on the New HTML file dialog. I guess we will just have to go through every dialog and manually add a particular classname to each default action button within the dialog's template.

**Comment by jinsil** [comment]
The bold text can be class name "primary" for now...

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg
