### ISSUE TITLE
can maqetta.core.server project split into two layers?

### ISSUE THREAD

**Issue by xiaohulu** [maqetta/maqetta#2801]
hi,
I use maqetta in my project, but some data that saved in files, i need to save in mysql.
if maqetta.core.server is split into two project, one is servlet and another is the persist layer.
So people who integrate maqetta in their osgi projects can replace the persist layer easily!

**Comment by JonFerraiolo** [comment]
-> @childsb to respond

**Comment by aerwin** [comment]
--> assigning from "no milestone" to "M7" so it gets tracked better
--> no prio to Prio High to get response

**Comment by childsb** [comment]
Our 'persist' layer is abstracted into interfaces & extension points.  You should be able to break out all of the storage by overriding the User class without splitting up the plugin.

Look at the maqetta.server.orion package as example.  it replaced the java.io.File storage structure with IFileStore.
