### ISSUE TITLE
client javascript library, reference not include

### ISSUE THREAD

**Issue by xiaohulu** [maqetta/maqetta#2802]
maqetta.core.client include dojo in the WebContent dir.
It's not the best practise, should refernce dojo bundle, not direct include dojo in the project.

so, maybe it's better to split the dojo in one plugin project  like [orion-client](https://github.com/eclipse/orion.client/tree/master/bundles) ' org.eclipse.orion.dojo bundle

**Comment by JonFerraiolo** [comment]
-> @peller to respond

**Comment by peller** [comment]
on master, we're referencing dojo using submodules now.  In order to run the Dojo build scripts, we really need it to reside in the same plugin structure, or additional copying/moving of files would be required.

**Comment by xiaohulu** [comment]
If there are two client bundle A and maqetta.core.client, they are all depend on dojo.
maqetta.core.client access the dojo.js file by url like '/maqetta/app/dojo/dojo.js'.
but project A bundle A can't access dojo.js use the same url.
I mean it should be better to use the common url  access dojo.js like "/dojo/dojo.js", not use the maqetta dependence prefix.

If so, we can easily integrat maqetta in osgi projects, is it?

**Comment by peller** [comment]
OSGi packaging for Dojo sounds like a good idea, we just haven't found an elegant way to make it work with Dojo's build system, which may combine Dojo and Maqetta code into layers.  How we structure URLs is orthogonal to the OSGi packaging, I think.  Both are areas which could use improvement, I agree.
