### ISSUE TITLE
"dojo-src" shows up in Modify Libraries dialog

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2806]
In the **Modify Libraries** dialog, I see a listing for **dojo-src** from `/lib/dojo`.  This is in addition to the **dojo** listing from the same directory.  "dojo-src" should not be listed here.

@childsb

**Comment by peller** [comment]
dup of #2769  You could argue that providing sources of Dojo for download might be helpful, but it should certainly be disabled by default.  "Zazl" also shouldn't be downloaded, probably should never be shown at all.
