### ISSUE TITLE
Browser tab for Maqetta shows Orion's 3-dot icon

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2809]
When running the Maq+Orion build, the browser tab on both Firefox and Chrome show the 3-dot Orion icon to the left of the words "Maqetta Designer". We should either get rid of that icon or replace with a Maqetta icon. The favicon.ico has to be 16x16. I'm not sure how Orion is setting that icon.

Good news: I think I have a fix in hand.  We actually have a Maqetta 16x16 icon already in our project. I believe if we add the following line into the HEAD of pagedesigner.html, we will get a Maqetta icon instead of an Orion icon:

```
<link rel="shortcut icon" href="app/davinci/img/maqetta.png" />
```

@jmockler: We might want to update that icon. Here is a snapshot of how the new icon looks when I played around with things:

![browser tab snapshot](http://i.imgur.com/OTjkd.png)

**Comment by JonFerraiolo** [comment]
I found the 16x16 icon that the UI team created for us. I'll replace maqetta.png with the correct image. @childsb: I expect all you will need to do is add the LINK element as shown above to pagedesigner.html

**Comment by JonFerraiolo** [comment]
Actually, I tried out the new icon and I think we need something smaller. Here is how the updated icon looks:

![updated 1616 icon](http://i.imgur.com/OTjkd.png)

**Comment by JonFerraiolo** [comment]
Sending back to me because of having to coordinate on the new icon.

**Comment by jmockler** [comment]
@JonFerraiolo - I FW a revised version of the icon via internal email

**Comment by JonFerraiolo** [comment]
Here is how the browser tab looks now, after using the icon that @jmockler provided:

![snapshot](http://i.imgur.com/sUVFT.png)
