### ISSUE TITLE
preview launches browser with second instance of maqetta

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2813]
Latest build on http://maqetta-test.austin.ibm.com:55556/maqetta/ maqetta/orion when I preview a mobile html page a second instance of maqetta is started in the windowinstead of just the preview

**Comment by billreed63** [comment]
Seems to be limited to mobile pages

**Comment by peller** [comment]
see #1

**Comment by jhpedemonte** [comment]
Might be an issue on the server side, with the Maqetta+Orion build.  cc @childsb 

I saw no errors in the server log.

**Comment by peller** [comment]
-> @childsb
