### ISSUE TITLE
Different styles per state isn't reflected in properties palette.

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2814]
- Drag and drop a label
- Add 2 states
- In state 1, set the color of the label to red.  Be sure to click on the arrow and select "apply to current state"
- In state 2, do the same as above but set it as green
- Switch states, note the color changes
- Select the label in both states and check the color value - same color is shown both times.

**Comment by JonFerraiolo** [comment]
@billreed63 

Investigated this a bit. Two problems I see here:
1. Regression described in this bug. Cascade.js doesn't seem to be taking current state into account when showing the current property value.
2. Changing state causes current selection to go away.
