### ISSUE TITLE
Theme selection dialog does not default to "(none)" on new theme

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2817]
Running **Tests > Theme Sets > Applying theme sets to HTML**:  Open theme selection dialog, and automatically defaults to **dojo_theme_set**.

Since this is a new file, it should have defaulted to **(none)**.  Whenever I reset theme set to **(none)**, next time I open the dialog it always comes up as **dojo_theme_set**.

**Comment by billreed63** [comment]
If the user has created a theme set with claro as the desktop and mobile devices of android=andrid, bb=bb, ipad=ipad, iphone=iphone, other=iphone. 

When a new page is created by default that page is created with the same themes by default.

this is more or less a dup of issue #2147
