### ISSUE TITLE
Orion integration outstanding issues

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2824]
@jhpedemonte 

I was assigned the "Orion" test plan and attempted to follow the rules. It seems like there are a bunch of things yet to be completed. Here are a few:
- How will login work on maqetta.org? When I go to the root folder of maqetta-test, I see the regular-old Joomla page, with it's login, signup and give it a try links. When I click on login, I'm taken to the Joomla login page. What are we going to do about all of this?
- When I registered on the Orion login screen, I was able to create a "JonFerraiolo" login, it didn't check and force me to enter an email address as my login name, and there was no email activation step.
- Orion button at top of Files palette should open Orion in a new browser tab, not use the same browser tab
- Login screen still shows Orion logo and Orion twitter icon, etc.
- If you are in the Orion source editor on a file (e.g., file1.html), how do you open that file in Maqetta? I thought we had an "open in Maqetta" feature at one point.
- The URLs for all of the Orion features are still at the root level. (#2565)
  - Navigator URL: http://maqetta-test.austin.ibm.com:55556/navigate/table.html#
  - Source editor URL: http://maqetta-test.austin.ibm.com:55556/edit/edit.html#/file/D/file1.html
  - Login page URL: http://maqetta-test.austin.ibm.com:55556/mixloginstatic/LoginWindow.html?redirect=../maqetta/

---

**Tasks:** _(updated 2012-08-09)_
- Joomla integration: (#3103)
  - In Joomla, point **login** link to Orion instance.
  - In Joomla, remove **Give it a try** link.
- ~~Allow only registration with email.~~
- ~~Orion button should open in new tab.~~
- ~~Add menu item **Open > Orion Workbench**, and remove Orion link at top of Files view.~~
- ~~Cleanup login screen. (#2862)~~
- ~~Reimplement **open in Maqetta** feature when in Orion.~~
- URLs for all Orion features are still at root level. (#2565)

**Comment by childsb** [comment]
- Javier is working on the maqetta.org configuration.  The plan is to host maqetta/orion on app.maqetta.org, and content on www.maqetta.org.  It wasn't possible to move the URL space for the application itself.
- The hosted version forces you to sign up with email.  maqetta-test is running the standard login which doesn't force email.  I will fix this though.

Will fix the login screen and launch in new window for this bug.

**Comment by childsb** [comment]
Remaining work: Fix the "open in maqetta" integration in Orion.  The 0.5 release broke their previous extension points, and i'm waiting to hear back from Simon about the new ones.

**Comment by jhpedemonte** [comment]
With the new UI, having the **Orion** button at the toolbar for the Files view doesn't make sense.  I think it would be better to put a new item in the **Open** menu at the top; maybe called **Orion Workbench**.

_(Is Orion a "workbench", a "platform"?  It's not just an "editor".  Not sure what to call it.)_

**Comment by JonFerraiolo** [comment]
@jhpedemonte Good suggestions. "Orion workbench" sounds fine to me. At some point we might want to ask the Orion folks what they think.

**Comment by jhpedemonte** [comment]
Added a **Tasks** list to summary.  Please keep it updated as work is done or new tasks are required.

**Comment by childsb** [comment]
closing for m7
