### ISSUE TITLE
Exception when publishing review request

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2825]
I get the following exception when I attempt to publish a review on Orion build

POST http://maqetta-test.austin.ibm.com:55556/maqetta/cmd/publish?emails=jferrai%40us.ibm.com%2C&message=&versionTitle=teste&resources=project1%2Ffile2.html&desireWidth=1024&desireHeight=768&dueDate=infinite&receiveEmail=true 500 (Server Error) xhr.js:210
xhr xhr.js:210
dojo.xhr xhr.js:657
dojo.rawXhrPost.dojo.xhrPost xhr.js:689
declare.publish PublishWizard.js:717
declare._initButtons.invite.Button.onClick PublishWizard.js:352
lang.hitch lang.js:375
declare._onClick _ButtonMixin.js:43
inherited declare.js:189
declare._onClick Button.js:64
lang.hitch

**Comment by aerwin** [comment]
-> aerwin

Imagine this is a dup of #2561 which was just fixed (reviews were pretty much entirely broken on orion). So, closing. Please reopen if you run into again.
