### ISSUE TITLE
Confusion over Carousel vs. Data Carousel in widget palette

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2834]
@doronrosenberg 

Working through the Carousel parts of the "Widget Palette: Mobile Data Store Based (Basic)" test plan... 

We have both `Carousel` and `Data Carousel` in the widget palette, but given Data Carousel accepts both comma-separated user-input and data file input, should we hide plain Carousel?

Making priority high for M7, because regardless of the answer, the Carousel parts of the "Widget Palette: Mobile Data Store Based (Basic)" test plan needs to be updated appropriately.

**Comment by doronrosenberg** [comment]
I think keeping the regular carousel around is usefull because it doesn't create a datastore, and I didn't want to remove DataCarousel's inline editing feature since we already had it working.  I will update the docs.
