### ISSUE TITLE
Chrome: Caret sometimes disappears in source editor, no longer receives focus/blur events

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2839]
...making it impossible to type in the source editor.  Clicking on a native element like a text input in the properties common panel (title) then back in the source editor makes the caret re-appear.

To reproduce, open Sample1.html and go to split view.  Click back and forth between the source and the design views, and the caret should generally re-appear when you click in (focus on) the source editor.  Now, click on the "New" button in the Tasks panel and then on the source editor.  See if the caret is still there.  If it is, try clicking on New again, then back.  Usually this makes the caret disappear.  When this happens, the source editor (Orion textView) no longer receives focus or blur events.

Not sure if/when this regressed, or whether it regressed with a Chrome upgrade.  Can reproduce in M6 on maqetta.org.   I'm using Chrome v20.

@doronrosenberg, can you take a look?

**Comment by doronrosenberg** [comment]
Safari on mac works fine, so this looks like a Chrome bug.  Seems the focus remains in the VE iframe, even though the source editor is getting click events (as the clicked line gets that indicator in the right gutter).

**Comment by doronrosenberg** [comment]
@peller You seem to have fixed when you fixed the other focus bug (fac9b150b1d0d8471888051d96cac3770fb9e373)
