### ISSUE TITLE
UIMakeover - Properties palette exception with dropdown

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2843]
@doronrosenberg @peller @childsb 

This bug only happens in the UI makeover (which hasn't been merged into master at this time this bug was created). I expetct it has to do with the Properties palette floating above the canvas.

I ran through the mobile tutorial. When on the second view (alerts view), I select the Heading, set the "back" property to something, and then attempt to use the dropdown on the 'moveTo' property. I get an exception deep in the bowels of Dojo. Before all of this is happening, there is some strange flickering in the Properties palette. I suspect the "floating" nature of the new palette is triggering some event listeners in the middle of Dojo handling the opening of the menu. Fixing this is likely a multi-hour adventure.

**Comment by doronrosenberg** [comment]
Does the dropdown open even with the exception?

**Comment by JonFerraiolo** [comment]
I just logged the bug quickly during a testing pass. I'll study in more depth later. However, to my best memory, I think the exception prevents the popup from opening with the first click on the dropdown arrow, but the second click on the dropdown arrow brings up the menu correctly.

**Comment by JonFerraiolo** [comment]
I saw this again today, but then I tried to reproduce for 15 minutes and couldn't make it happen again.

**Comment by JonFerraiolo** [comment]
Reducing to Prio-Med since it is hard to reproduce and if debugger is off this exception does no harm, except that the user has to click a second time on dropdown arrow to see menu for moveTo control.

**Comment by JonFerraiolo** [comment]
Closing. I haven't seen this issue recently.
