### ISSUE TITLE
Exception loading page with mobile views

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2847]
- Create a new page
- Dnd a dojox.mobile.View.
- reload page

```
TypeError: this.rootNode is undefined

Line 1830 Context.js
```

**Comment by doronrosenberg** [comment]
@jhpedemonte @JonFerraiolo 

I think this is a timing issue, as adding a rootNode check exposes another error in ThemeHelper.js (header.styleSheets is undefined).

**Comment by doronrosenberg** [comment]
Seems to be consistent on Firefox but only when I clear my chrome cache

**Comment by peller** [comment]
I see something different.  I see an exception at Context.js in loadTheme(), line 805:

```
        var body = model.find({elementType:'HTMLElement', tag:'body'},true);
805     body.setAttribute("class", defaultTheme.className);
```

where loadTheme was called at Context.js:843 after loading the metadata for html.body... but is it reasonable to assume that the model exists for the body tag at this point?

@billreed63

**Comment by doronrosenberg** [comment]
Did some more debugging, ThemeHelper::widgetAddedOrDeleted is getting called before the rootNode exists.  I put the debugger on it and a few secs after hitting it the rootNode is there.

**Comment by billreed63** [comment]
Can someone add  the page html that they are using.. I am not seeing this on my system

**Comment by doronrosenberg** [comment]
Create a new html page, save it.  Reload browser.  Seeing this consistently on Firefox and sometimes on Chrome after a cache clear

**Comment by doronrosenberg** [comment]
here is the generated source:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'packages':[{'name':'dojo-src','location':'..'},{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'widgets','location':'../../widgets'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates"
]);
</script>
<style>@import "themes/claro/document.css";@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
</head>
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
</body>
</html>

```

**Comment by peller** [comment]
seems like code referencing the model should not be in _setSource(), at least not before the window onload event completes and parse() is called.  Perhaps that code could be relocated to continueLoading() or _setSourceData()?
