### ISSUE TITLE
Safari: Error using New file in NewHTMLFileOptions

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2849]
Bring up a new workspace. Hit the button for new sketch file.  Exception is shown on the console:

```
            this.deviceLabel.innerHTML = langObj.nhfoDevice;
```

this.deviceLabel is undefined.

**Comment by JonFerraiolo** [comment]
Feel free to send this issue to me. I wrote all of the NewHTMLFileOptions and probably my recent mega checkin for the UI makeover is a contributor to this issue.

**Comment by doronrosenberg** [comment]
@peller hmm, I don't see this on any browser using trunk
