### ISSUE TITLE
Size and resize behavior of tree (and table) input dialogs is off when there is limited vertical screen real estate

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2852]
@doronrosenberg 

Using Chrome on Mac...
1. Reduce vertical size of browser (such as if you you have Developer Tools showing)
2. Create new HTML file
3. Drop tree onto page
4. Initial size of dialog is off... at the very least I think scrollbar should only be on the div of the white area of the dialog. E.g., there should never be vertical scrolling required to see the OK/Cancel buttons. And, I thought that's how this dialog worked prior to it being converted to the resizable variety.

![screenshot](http://i.imgur.com/gG5pD.png)

Then, I tried to resize the dialog and I ended up with a gap between the dialog contents and the button area:

![screenshot](http://i.imgur.com/BmOIZ.png)

**Comment by aerwin** [comment]
Same thing happens with GridX, but even worse because can't see buttons at all:

![screenshot](http://i.imgur.com/b7LEH.png)

**Comment by aerwin** [comment]
@doronrosenberg Reopening... I guess I can't tell where anything changed for the better here. Things are perhaps even worse.

**Comment by doronrosenberg** [comment]
Still some issues left.

Need to change the logic of resize.  Resize logic should go into an _resize.  Resize calls it and then checks if the dialog was shrunk by dojo.  If so, resize again using new coords.

**Comment by JonFerraiolo** [comment]
@doronrosenberg and @jhpedemonte - Is this fixed or not? It looks like near-simultaneous comments, one from @doronrosenberg saying still some problems left.
