### ISSUE TITLE
New icons needed for various new/modifed UI functionality in M7 Maqetta

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2854]
@JonFerraiolo 

Per ST, just creating a placeholder issue so we can start building one list of new icons needed for M7.

As a start, I'd like to add toolbar icons for new tree smart input (#2689) to the list.

**Comment by JonFerraiolo** [comment]
@jmockler 

We need small icons for various dropdown menus. 

On the top-most black banner, have a handful of dropdown menus, and none of the commands have icons, but I think that's fine, at least for the M7 release.

On the toolbar:
- We already have icons for Save and SaveAs.
- (!) We have a placeholder icon for SaveAs Widget. We need to decide whether we need a different icon for that command.
- We already have icon for the view modes (source only, split-h, split-v)
- (!) We need icons for flow vs absolute
- We already have icons for the document settings commands (Switch theme, choose device, rotate)

On the action bar:
- (!) For indicating that an icon is disabled, I am using opacity:.6. Is that ok?
- (!) We need to review and possibly update all of the icons that appear on the action bar
- (!) In particular, the show/hide properties icon needs two icons
- (!) We need to decide whether to create icons for the "Select" menu: select parent, select ancestor, unselect all
- (!) We need to decide whether to create icons for the "Other" menu: Surround with DIV, Surround with SPAN , Surround with A and Application States.
- (!) If a table cell is selected, a Table icon appears on the Action Bar. We need to decide whether to create icons for the "Table" menu: Select table, insert row after, etc.

Page editor context menu:
- (!) Right now we have icons for the first five commands (cut, copy, paste, delete, duplicate) but none of the others

**Comment by JonFerraiolo** [comment]
During a discussion today, we decided we need icons for everything on the Create and Open menus.

**Comment by JonFerraiolo** [comment]
We also need 9 new icons for the welcome page.

**Comment by jinsil** [comment]
Hi Jon,
What size do you want?
Could you specify?

Tanks,
