### ISSUE TITLE
Selection box does not scroll with theme editor

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2859]
With the new UI 

Create a clone of android theme
select the heading widget
then with the scroll bar scroll the theme editor content.

The blue box does not scroll with the canvas

**Comment by billreed63** [comment]
Select the top widget, Global widget in claro theme editor
Scroll down so that the Global widgets scrolls under the top banner, notice that the selection box is now over the banner

**Comment by billreed63** [comment]
Border selection overlays properties palette

DnD TabContainer
Select tab container
notice that the selection is (blue box) is over the tab container.

**Comment by billreed63** [comment]
Create a html  file1.html and a theme calro1
DnD a couple widgets onto the canvas of file 1
Select a widget and click the drop down arrow  select background from the tabs and Stretch the box

Now switch to claro1, pick a widget and select drop down and select background..

Now switch back to file1.html

Note the properties palette is collapsed instead of expanded and that the box is still the stretch size..

**Comment by JonFerraiolo** [comment]
@billreed63: Could you please pull and try this again? I submitted a fix this morning: 3ee715a69902d23a296561c3f479b9336370bcb0

**Comment by JonFerraiolo** [comment]
I've fixed the 2nd and 3rd problems reported by @billreed63. Regarding the first problem:

> Select the top widget, Global widget in claro theme editor
> Scroll down so that the Global widgets scrolls under the top banner, notice that the selection box is now over the banner

That's still pending. My best idea is:
- Continuously reposition the focusContainer DIV to be the same size as the current editor's iframe (actually, a few pixels bigger on all sides). For "continuous reposition", would need to listen for resize events on various other objects.
- The focusContainerDiv would have pointer-events:none and overflow:hidden
