### ISSUE TITLE
Files dialog UI cleanups

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#286]
To emulate Windows Save as dialog (or similar dialog from other platforms), add the following features:

Change the current list box to a drop-down.
Add an "Up" button.
Add a "New folder" button.

------- Comment #1 -------

Also add a Cancel button to:

Create new file dialog
Save As dialog
Add Files dialog

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg

**Comment by doronrosenberg** [comment]
Also see #2945.

We should use this bug to combine all the file selection UI into one true dialog class.  I used #2966 to do some of that and ended up using the OpenFile dialog.

**Comment by JonFerraiolo** [comment]
Closing. Worst problems here have been addressed.
