### ISSUE TITLE
StackContainer: Untested -> Dojo Containers

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2863]
We need to move StackContainer from the Untested section to the Dojo Containers section. Probably need to copy/paste the metadata for StackContainer within package.json to place StackContainer alphabetically between MenuBar and TabContainer so that we can preserve alphabetical listing within the Dojo Containers section of the Widgets palette.

**Comment by JonFerraiolo** [comment]
BTW - We will be removing the Untested section from the shipping version of M7.

**Comment by doronrosenberg** [comment]
I was going to do this once we figured out if we need to add docs for strackcontainer
