### ISSUE TITLE
Rearrange widgets within Dojo Mobile section of Widgets palette

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2864]
@jhpedemonte 

Right now, Ratings appears as the first entry in the Dojox Mobile section of the Widgets palette. We want the *Views to be the first entries because in most cases that's the first thing the user needs to add to his page. To push Ratings down lower, just need to cut/paste its metadata entry within packages.json to a different location in the file.

IMO, we need subgroups within the Widgets palette because there are too many widgets in some of the sections, particularly Dojox Mobile. However, we don't have a spec for subgroups at this time, and at this point it doesn't seem advisable to attempt to sneak subgroups into M7. 

So, for M7, I recommend we follow the ordering approach from M6, where:
- View widgets at the top
- Then Heading-related widgets
- Then list-related widgets
- Then form control widgets
- Then TabBar-related widgets
- Then IconContainer-related widgets
- Then everything else

One possible approach for the "everything else" section would to list those widgets alphabetically. All of the this are just ideas for what to do for M7, and none of this has come from UI experts. The one thing though is that I think it's important to put Views, Headings and List widgets at the top.

**Comment by jhpedemonte** [comment]
I noticed that _ScrollablePane_ was at the top of the listings and decided to rearrange the widgets better, following (more or less) the listings here: http://dojotoolkit.org/reference-guide/1.8/dojox/mobile.html
