### ISSUE TITLE
Orion workspaces different than user name

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2865]
Currently the Orion folder name for the workspace doen't match the user name. 

1) How are we going to map existing users from  current maqetta to orion.
2) How are we going to find users workspaces once we deploy?

**Comment by childsb** [comment]
User migration has moved to a server side process. Look at maqetta.server.orion.hosted / MigratUser6to1.java

As far as finding the users directory, there is some Orion admin pages that should give us access to the users data.
