### ISSUE TITLE
StackContainer issues that need to be addressed

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2867]
@doronrosenberg @aerwin 

@billreed63: Sending this to you at first to update this issue appropriately, then please reassign to @doronrosenberg.

I played around a bit with StackContainer and I see various issues that we need to review. @billreed63 (and @aerwin): you have sacrified some blood, sweat and tears over widgets with similar issues, such as Tree, where adding a single widget (e.g., Tree) brings in one or more companion widgets (e.g., ItemFileReadStore and ForestStoreModel). In this case, when the user adds a StackContainer, he gets a companion StackController widget.

The way things stand now with StackContainer, you can drag/drop it onto the canvas and things seem to work fine. However, if you delete the StackContainer, the StackController isn't deleted, and if you add a second StackContainer, things go badly.

What I'd like to do is turn this issue into a spec for all of the various page editing scenarios with StackContainer, and discuss what should happen in each scenario. Here is a first pass:
- If the user deletes a StackContainer:
  - We should also delete the corresponding StackController
- If the user deletes a StackController:
  - We should also delete the corresponding StackContainer

Are there other things?

**Comment by billreed63** [comment]
Most likly they should be treated as a pair for all user operation,  cut, copy, paste, re-parent

**Comment by JonFerraiolo** [comment]
@billreed63: anything else? if not, please reassign to @doronrosenberg

**Comment by doronrosenberg** [comment]
@peller Filed a bug on dojo - http://bugs.dojotoolkit.org/ticket/15815

StackController can't be destroyed without an exception being thrown, making StackController not work at all with move/delete/etc in Maqetta.
