### ISSUE TITLE
Context..js:deactivate() never called

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2871]
@billreed63 

To my surprise, I've discovered that ve/Context..js:deactivate() is never called except by VisualThemeEditor.js, and in that case it is a nop because the check at the top of deactivate() (`if(this.isActive())`) always returns false.

My guess is that we have major memory leaks due to not calling deactivate().

It looks like activate() is only called when a new editor is first opened. It doesn't seem to get called with source editor changes. Therefore, deactivate() probably should be called when an editor is closed.

Remember, we have multiple types of editors: page editor, theme editor, review editor, and source editors (e.g., CSS and JS files)

Note this is not a recent regression. I checkout out Preview6 and Preview5 and deactivate() is not called in either of those releases, either.

**Comment by peller** [comment]
Good catch.  Moving -> prio high for M8 so it's addressed early in the cycle.

**Comment by JonFerraiolo** [comment]
@jhpedemonte 

-> M8 Prio-Med

**Comment by peller** [comment]
We have both deactivate() and destroy()  @billreed63 created the destroy method here: 92cd35f1   Only destroy() gets called. Perhaps we can combine?
