### ISSUE TITLE
Downloaded workspace is too large

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2874]
Had email conversation with @peller yesterday and he advised opening an issue as appears to be a regression from M6...
1. Click button to download workspace
2. Uncheck everything but dojo (also uncheck dojo-src)
3. Click OK and end up with zip file that's around 21.8 MB

The goal (at a minimum) is to get under 10 MB.

**Comment by peller** [comment]
Somewhere along the way, it seems I checked in a full copy of Dojo with tests.  My git rm/git add didn't seem to properly remove files which are not in the latest Dojo (such as the tests)  I will try again to get it right with 1.8.0 final in the coming days.

**Comment by peller** [comment]
With 840ce12, the workspace download of dojo only is a mere 5.7M, down from 21M(!)  We can do better, but hopefully this fixes the regression.   The upside is that the accidental checkin of all of those extra files led us to discover the performance benefits of avoiding jar packaging on static OSGi libraries.
