### ISSUE TITLE
Logout does not do anyting

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2875]
From the user icon click the logout drop down menu item... Nothing happends..

**Comment by childsb** [comment]
is this built or unbuilt?

i checked in a fix yesterday that should logout and redirect to login page

**Comment by billreed63** [comment]
I have not pulled since yesterday morning so it is most likely fixed...

**Comment by billreed63** [comment]
The built version running local server from following the User management basic tests case. 
Logging out just returns the user back to maqetta.

**Comment by jhpedemonte** [comment]
Build running on maqetta-test also has this problem (built from b6bbf7003b7c88b0c210166f190cd99b4467e627).  Logout just reloads maqetta.

**Comment by JonFerraiolo** [comment]
-> childsb He was working on the logout logic.

**Comment by childsb** [comment]
Changed to sync post to logout in 4e1d85dfd786a8989e24f76d81bdeb99b4d6f67a
