### ISSUE TITLE
Clone claro theme - no document.css for theme editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2881]
Running http://maqetta-app-test.austin.ibm.com/maqetta/ on Mac/FF

I cloned claro into myclaro. The fonts used in the theme editor are what you get when document.css isn't there.

![picture](http://i.imgur.com/PVgLG.png)

**Comment by billreed63** [comment]
I left a helper out, but checked it in last yesterday. It is working today.
If you still are seeing this issue reopen
