### ISSUE TITLE
Theme editor selection chrome doesn't deal with scrolling

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2882]
I thought I fixed this a few days ago...

In Dojo theme editor, select TitlePane. Then scroll the theme editor vertically.

Note: selection rectangle doesn't adjust.

**Comment by JonFerraiolo** [comment]
I don't see this anymore with latest code. There is still the pending problem where the selection rectangle can overlap the banner, described #2859, but selection seems to be accurate now when the theme editor canvas is scrolled. Closing.

**Comment by billreed63** [comment]
On page editor DnD a content pane onto the canvas
Set the size to width 923px

Now drag the vertical divider so that the properties palette is taking up half the screen.. The selection rectangle is over the properties palette

**Comment by JonFerraiolo** [comment]
Closing as dupe again. This problem with page editor will be fixed by the same fix for #2859. The fix is to put an extra wrapper DIV around any of the editor, and put the selection chrome inside of that DIV, and then putting an overflow:hidden on that DIV.
