### ISSUE TITLE
Need way to switch projects from welcome page

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2883]
@JonFerraiolo 

On welcome page, there's no way to no what project you're currently working on and there's no way to switch projects. At the very least, we probably need an Open -> Project... menu option.

**Comment by JonFerraiolo** [comment]
How about adding an Open project command, similar to what you just did for opening a review?

**Comment by aerwin** [comment]
Sure, that's what I meant by Open -> Project... menu option. I can do that.

**Comment by jhpedemonte** [comment]
What about taking inspiration from Eclipse:

```
------
|Open|
|-------------------
| ...              |
| Switch Project > |  ---------------------------
| ...              |  | Current: My Project     |  <-- disabled
--------------------  |-------------------------|
                      | Another Project         |
                      | Different Project       |
                      | No Way! A Third Project |
                      ---------------------------
```

Gets rid of a dialog...

**Comment by JonFerraiolo** [comment]
I expect we would have to add a new feature to Workbench.js to allow for sub-menus, and there might be a minor ripple effect going into a couple of other places in the code.

**Comment by doronrosenberg** [comment]
If an Open -> Projects dialog is OK I can take this on. Submenus would be too complicated for m7

**Comment by aerwin** [comment]
I think the dialog is sufficient. Thanks, @doronrosenberg !
