### ISSUE TITLE
Need easier access to workbench (and preference to stay in workbench)

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2884]
@JonFerraiolo 

As a "power" user who is used to working with the workbench and the tabs within it, I think we need the following:
- link from welcome page to the workbench. E.g., I find myself "playing games" where I create an unnecessary file just to get my workbench back. [The flip of this where you could get to the welcome page from the workbench would also be really good for folks who prefer the welcome page interface for creating files, etc.) 
- user preference not to be taken back to the welcome page just because I close all of my editors. E.g., common scenario would be using file palette to find the file I want to work with. I might open and close several before finding the one I want. And, it's annoying to have to go back to the welcome page every time and lose my place in the file palette.

**Comment by peller** [comment]
Moving the welcome page back down in the hierarchy as a peer to the palettes would seem to solve both of these problems.

**Comment by aerwin** [comment]
Yes, agreed. I opened this up before our discussion yesterday. We can probably close this (unless @JonFerraiolo was going to use to track the work for moving the welcome page).
