### ISSUE TITLE
EdgeToEdgeDataList: data source menu doesn't work

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2887]
@billreed63 

The data source menu on the EdgeToEdgeDataList's SmartInput dialog is inoperable.

I suspect this is because I changed the code recently to insert an overlay DIV over the canvas to capture click events to fix a different issue.

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg . I took a look at this and I'm scratching my head about why the menu doesn't come up. Could you take a look and see if you can figure out what's wrong?

**Comment by doronrosenberg** [comment]
@JonFerraiolo 

davinci.css

```
.inlineEdit {
    display: none;
    position: absolute;
    z-index: 1000110;
}
```

The dropdown gets a z-index of 4000.  smartInputLoading, the coverup is set to 1000110.

Dijit dialog sets z-index to 999 and its overlay to 998, I think we should use those numbers too.  It seems to work fine for me when I make the changes, but not sure how that affects the new UI stuff.

@peller in case dojo changed something relating to z-index calculations.

**Comment by peller** [comment]
@doronrosenberg AFAIK, Dojo (Dijit, really) just sets its z-index in static CSS and doesn't do any calculations.

**Comment by JonFerraiolo** [comment]
I can't think of anything in the new UI stuff that using a lower z-index for SmartInput would break, and if it does break, we would discover it during testing.
