### ISSUE TITLE
New file stays in file palette even if didn't save on close

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2889]
Using Chrome on Mac with Orion... 
1. Create new HTML file
2. Click save on new HTML file
3. Create 2nd HTML file
4. Close 2nd file without saving
5. 2nd file stays in Files palette

**Comment by jhpedemonte** [comment]
cc @JonFerraiolo

**Comment by JonFerraiolo** [comment]
There is a chance that my UI makeover changes might be the cause of this, but if @childsb could investigate, that would be most appreciated.

**Comment by jhpedemonte** [comment]
-> @doronrosenberg, since he recently looks at related issues.

**Comment by doronrosenberg** [comment]
So in the failure case this is what is happening in `Factory.js::closeModel`:

```
var resource = systemResource.findResource(url);
  if (resource && modelResource.dirtyResource){ // models can be created without a real resource.
    resource.removeWorkingCopy();
     resource.dirtyResource = false;
} 
```

`modelResource.dirtyResource` is null, but `resource.dirtyResource` is true.

It would see, changing the `modelResource.dirtyResource` to `resource.dirtyResource` fixes the issue in some simple testing, is there a reason not to make that change?

**Comment by jhpedemonte** [comment]
@childsb, do you know anything about the code mentioned above?
