### ISSUE TITLE
Can not select widget in widget palette

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2892]
Widget test case:

Click on a widget to select it, and then click on the canvas. This should also add the widget to the canvas.

**Comment by doronrosenberg** [comment]
Might be a dupe of #2877

**Comment by JonFerraiolo** [comment]
@peller - I wonder if the deferred logic you added with https://github.com/maqetta/maqetta/commit/f33d380dc6418c627539c87176d013090f5a9f20 is causing this regression.

**Comment by JonFerraiolo** [comment]
BTW - I am seeing exceptions at the same point (AddCommand.js:21: where parent is undefined) when I've been doing operations that have nothing to do with adding widgets. I haven't nailed it down, and don't have a reproducible case. It's just that when doing other things that have nothing to do with adding widgets, I see an exception at AddCommand.js:21.

**Comment by doronrosenberg** [comment]
@JonFerraiolo I am seeing other widgets like AccordionContainer/TabContainer fail to be added with a exception, is this the same issue?

**Comment by doronrosenberg** [comment]
@JonFerraiolo To be more exact, I can't dnd accordion/tabcontainer into a <div>, seems to work fine into a blank ve

**Comment by JonFerraiolo** [comment]
@doronrosenberg - did you type in some markup that GitHub tossed away? I just see `into a ,`

**Comment by doronrosenberg** [comment]
@JonFerraiolo Oops yeah, dnd into a div doesn't work for me, dnd into a blank canvas works

**Comment by JonFerraiolo** [comment]
I'm pretty sure you meant `can't dnd accordion/tabcontainer into a DIV`. I tried this just now with latest code and that operation fails.

And I believe I see the culprit. I think the problem is in LayoutContainerHelper:34. getData() sometimes returns null for data.children and LayoutContainerHelper isn't checking for null.

So reassigning to @aerwin

**Comment by doronrosenberg** [comment]
@peller ccing you just because this exception isn't being logged in rc1 for me, bad dojo?

**Comment by peller** [comment]
@doronrosenberg are you sure there's an exception?  If so, what is it?

**Comment by doronrosenberg** [comment]
@peller The exception (drag a div, drag a tab container into it) is in LayoutContainerHelper line 46 (parentChildren is null).  I see it going to Deferred.js line 49:

```
signalDeferred(deferred, REJECTED, error);
```

Error is:

```
TypeError: parentChildren is null
```

I don't see anything in the console in firefox

**Comment by aerwin** [comment]
--> @doronrosenberg 

Just noticed this assigned to me, but guessing it should be @doronrosenberg 's based on the discussion?
