### ISSUE TITLE
Need strategy for showing user id as displayable name in Maqetta UI (when one doesn't exist)

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2894]
This is how I was identified in a R&C e-mail:

```
H (apeller@us.ibm.com) has invited you to review the page.
```

With "H" instead of a real name. I'm not sure I had an opportunity to provide a real name when registering.

**Comment by aerwin** [comment]
@peller @childsb 

-> Prio High
-> Changing title to "Need strategy for showing user id as displayable name in Maqetta UI (when one doesn't exist)"

We've got a number of places where the result of person.getUserID() (in server side code) is to build strings that are shown to the user in one form or another:
- E-mail invitation mentioned by @peller 
- Toaster when hover over review

![screenshot](http://i.imgur.com/dBvsy.png)
- 3rd panel of publish wizard (in review info grid and type ahead search)

![screenshot](http://i.imgur.com/m0AMl.png)

I imagine this also ties into the user ID vs. e-mail discussions in different user management systems that's taking place in #2932.

**Comment by childsb** [comment]
I did a refactoring such that userID = unique/generated and not actually the username (or email).  This was to support Orion's userID scheme.

A couple options--

I could add a Workbench.getUserName(...) or something to be used in the UI.  Then you could go back and use that call instead of getUserId(..) wherever its needed

Or you can just remove anything that references getUserId(...) and use only the email.

**Comment by aerwin** [comment]
@childsb @JonFerraiolo @jhpedemonte 

> I could add a Workbench.getUserName(...) or something to be used in the UI. Then you could go back and use that call instead of getUserId(..) wherever its needed

What would this return? I'm assuming you would add an equivalent on the server side too?

> Or you can just remove anything that references getUserId(...) and use only the email.

So, guess I'd like agreement from the group that we're OK with Orion driving that we stop ever showing both a user name and an e-mail in the UI and just always use e-mail from here on out.

**Comment by peller** [comment]
Can/should Orion provide us with a "real" name along with an e-mail?  I'm totally ok with Maqetta getting out of that business.

**Comment by childsb** [comment]
So it looks like we're already returning this info--->

Runtime.getUserInfo() returns:

{ userId: userId,
isLocalInstall: boolean,
userFirstName: firstName,
userLastName, lastName,
email:email}

so Runtime.getUserInfo().userFirstname  should get the users first name where you need it.

**Comment by aerwin** [comment]
> so Runtime.getUserInfo().userFirstname should get the users first name where you need it.

Well, not really though, right? :) Is the registration screen asking for first name now with Orion?

**Comment by aerwin** [comment]
@peller @jhpedemonte @JonFerraiolo @childsb 

So, here's a proposal for every place (client and server) where we currently generate a string or label of the form `NAME <E-MAIL>`

psuedo-code:

```
var label = "";
var name = userInfo.firstName ? userInfo.firstName : userInfo.userID;
if (name) {
    label = name + "<" + userInfo.email + ">";
} else {
    label = userInfo.email;
}
```

Do folks agree?

**Comment by jhpedemonte** [comment]
Seems legit.

**Comment by aerwin** [comment]
Except... where it falls apart (which I forgot when I typed up the algorithm) is that userInfo.userID is going to be "A" or "B" or something like that in Orion.

So, probably need to eliminate userId from the algorithm (which sucks because there are server platforms which have valid user ids). So, algorithm becomes:

if (userInfo.firstName) {
    label = userInfo.firstName + "<" + userInfo.email + ">";
} else {
    label = userInfo.email;
}

which for all intents and purposes means we're just using email from here on out.

**Comment by childsb** [comment]
Looks good to me.  All we'd have to do for firstname/lastname is add fields on signup that require them.

**Comment by jhpedemonte** [comment]
> All we'd have to do for firstname/lastname is add fields on signup that require them.

Not so sure about this.  I like the simplicity of only requiring an email and password on sign up.

I'd prefer these be optional, maybe add a **Profile** page to **Preferences**, where a user can add his/her real name.

**Comment by JonFerraiolo** [comment]
It's really not too much to ask a user to enter their name at registration time, is it?

**Comment by aerwin** [comment]
@peller @JonFerraiolo @jhpedemonte @childsb 

Not sure when this moved to M8, but we don't really want "A", "B", "C", "D", etc. all over the UI, do we?

**Comment by jhpedemonte** [comment]
Sure thing for M7 to use the email.  Not so sure about adding fields for user's name; that might have to wait for M8.

-> M7

**Comment by aerwin** [comment]
--> @aerwin 

I can take this one then (minus adding field's to collect user name). I'll open a separate issue for that one.

**Comment by aerwin** [comment]
Closing with above commit.
