### ISSUE TITLE
review link does not open review editor

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2895]
(with orion integration)

click the link on a review invitation, and you are taken to the workbench.  The review(s) does not open, and it's not obvious to the user that there are reviews to look at.

question: if you include multiple files in the review, are they all supposed to open?

**Comment by aerwin** [comment]
Haven't tried yet with multiple files in the review, but review link looks when only one file in the review.

**Comment by aerwin** [comment]
Closing with above commit.
