### ISSUE TITLE
Incorrect email domains in "from:"

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2896]
The account registration emails are _always_ sent from "admin@maqetta.org".  New review emails come from "noreply@website.org".  Both should be **configurable**.

@aerwin @childsb 

---

**Proposal** in [this comment](https://github.com/maqetta/maqetta/issues/2896#issuecomment-8158386).

**Comment by aerwin** [comment]
Re-routing this to @childsb ... I don't know anything about how the mail server is set-up with Orion...

**Comment by jhpedemonte** [comment]
-> Prio High, I just got bit by this.

This email should:
1. use the current server's hostname instead of "website.org", by default.
2. be configurable, in order to override (1).

**Comment by jhpedemonte** [comment]
Updated summary with another email which needs to be configurable.

**Comment by childsb** [comment]
We should just take in the "from" email as a launch parameter and forget about determining the hostname.

To determine the host name, we need an incoming servlet request ((which we dont have until a user logs in))

String requestUrl = req.getRequestURL().toString();
String host = requestUrl.substring(0, requestUrl.indexOf('/', "http://".length()));

And theres some spots in the code where getting at the request ((if there is one)) isn't easy.

**Comment by jhpedemonte** [comment]
For registration, there's the server request when the user hits "Register".

For reviews, there's the server request when someone creates a new review or add a comment.

**Comment by jhpedemonte** [comment]
@childs, there's a few issues with this patch:
1. You use the string "http://" all over the place, but it can also be "https://".  Can't you pull the **protocol** from the `req` object?
2. You specify the user as "admin".  Would be good to make this configurable.
3. Looks like there was a way to configure the sending address (`getCommonNotificationId`).  Why did you remove this?  I think my previous proposal is the way to go: First, check for configurable option; else, default to server's domain (using either "admin" or "noreply" as the default user).

**Comment by childsb** [comment]
closing from commit.

**Comment by jhpedemonte** [comment]
I still see registration emails sent from "noreply@website.org".  I set the command line arg `-Dsmtp.notifcationId="foobar@foobar.org"`, but that didn't change anything.

**Comment by jhpedemonte** [comment]
I think I see the issue with ad971deb509cffdfbac27bc4b38249f2800cc5e4:

First, `getCommonNotificationId()` returns _noreply@website.org_ if notificationId isn't set.

Second, this chunk is duplicated in a couple of Java files:

```
if(emailAdd==null){
  int offset = (requestUrl.indexOf("https://") > -1 ? "https://".length():"http://".length() );
  String domain = requestUrl.substring(offset, requestUrl.indexOf('/', offset));
    if(domain.indexOf(":") > -1)
      domain = domain.substring(0,domain.indexOf(":"));
    emailAdd = "admin@" + domain;  
}
```

It looks like that chunk should be moved into `getCommonNotificationId()`, right?  That way, by default that function will return _admin@[domain]_.

**Comment by jhpedemonte** [comment]
@childsb, please review my commit.
