### ISSUE TITLE
Source menu says split on when it's not

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2898]
1. New HTML file
2. Show source (e.g., split top/bottom)
3. Save and close file
4. Reopen file and source button says "Split-H" even though it's not showing source:

![screenshot](http://i.imgur.com/juhsm.png)

I also thought clicking on the "Split-H" button would show the source in a split-pane, but it actually showed source only.

**Comment by JonFerraiolo** [comment]
Two problems here, both of which represent incomplete implementation of the UI:
- We need to highlight which mode is currently active, where if it's Design view only, the Design button is highlighted, whereas if it's Source or Source-H or Source-V, that button is highlighted instead
- When opening a new file, we need to properly deliver the mode shown on the source button (i.e., Source vs Split-H vs Split-V).

**Comment by jhpedemonte** [comment]
For the 2nd bullet there, I assume we'll make the source selection sticky across all files for the user, right?  That is, opening a new file won't reset the source selection back to _Source_ (if it had previously been set to one of the split options).

**Comment by JonFerraiolo** [comment]
Updated UI is in the UIMakeover4 branch, which I will probably merge into master within the next couple of days.

**Comment by JonFerraiolo** [comment]
This was fixed by the big UI makeover commit from this past weekend.
