### ISSUE TITLE
Properties panel doesn't handle no selection well

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2901]
- Select a widget
- Go to say background and click on one of the arrow buttons
- Now deselect all widgets.  The prop panel still shows the previous arrow button UI.  Probably should hide all the UI if nothing is selected

**Comment by jhpedemonte** [comment]
Not sure what you propose.  Do you mean that the Properties UI should be hidden when a widget isn't selected?

**Comment by doronrosenberg** [comment]
Yeah, hide the UI - that way all you see is no_selection and nothing else underneath.

**Comment by jhpedemonte** [comment]
Why do that?  Currently, every widget in the Properties view is disabled when a widget isn't selected.  Seems fine to me.  If we completely hide the UI, then we just have a blank rectangle of space.

**Comment by JonFerraiolo** [comment]
-> M8

**Comment by JonFerraiolo** [comment]
Closing - this wasn't really a bug, just a UI topic to discuss.
