### ISSUE TITLE
Keyboard navigation - we no longer have one dialog for creating a new file

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2904]
@jhpedemonte @JonFerraiolo 

In the new UI world we live in, there is no generic "new file" dialog.  We used to have ctrl-e bind to it.

Perhaps we should map ctrl-e to open the top Open dropdown and give it focus?  I believe that should work.

**Comment by JonFerraiolo** [comment]
Yes, I noticed that. I think we just drop Cmd-N/Ctrl-N from the list of shortcuts. I think the positives from having the New command offer discrete choices (New Mobile App, ..., New Sketch ...) outweighs having a Cmd-N/Ctrl-N shortcut.

We could add a dialog just for  Cmd-N/Ctrl-N, but that's extra work and we are out of time for M7.

Can we turn this into a documentation issue - just remove Cmd-N/Ctrl-N from the docs? I can make the docs change in seconds.

**Comment by doronrosenberg** [comment]
@JonFerraiolo I'll do the changes since I have to remove code as well and update test plan

**Comment by jhpedemonte** [comment]
Reopening:

> Perhaps we should map ctrl-e to open the top Open dropdown and give it focus?

I like this idea: let's have keyboard bindings for the **Create** and **Open** menus at the top.

`{Accl} O` opens up the **Open File** dialog, right?  Use `{Accl} Shift O` for focusing the Open menu?

We can't use `{Accl} C` for Create menu; any ideas?

**Comment by doronrosenberg** [comment]
I would say Accl E / Accel O to open the dropdowns (and then add the underline in the button to the character we choose) and then accl shift o opens the open dialog

**Comment by jhpedemonte** [comment]
Well, it depends if opening the **Open File** dialog is going to be a very common item (I would assume yes).  In that case, it would make more sense to use `{Accl} O` for that.

@JonFerraiolo, what do you think?

**Comment by doronrosenberg** [comment]
I was thinking having the top buttons have different accls would be confusing.

**Comment by doronrosenberg** [comment]
@JonFerraiolo @jhpedemonte need to decide on this for m7

**Comment by doronrosenberg** [comment]
MOving out to m8

**Comment by JonFerraiolo** [comment]
@doronrosenberg - can't we close this one? Cmd/Ctrl-O brings up file open dialog now.

**Comment by doronrosenberg** [comment]
@JonFerraiolo There is still no keybinding to create a new file.

**Comment by JonFerraiolo** [comment]
duh, sorry

**Comment by JonFerraiolo** [comment]
-> M8 Prio-Med

**Comment by JonFerraiolo** [comment]
Closing. Cmd/Ctrl-O works fine, and we don't have a single dialog for Cmd/Ctrl-N, and Cmd/Ctrl-N isn't in the docs.
