### ISSUE TITLE
State not supported layer missing from themeEditor

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2906]
Clone custom theme
select disabled state

most of the widgets do not support disabled but the div that  gray's them out is missing

**Comment by JonFerraiolo** [comment]
@billreed63 - can you provide some additional background info? Which DIV is it that's missing, from which file (dojo-theme-editor.js?), and is there a particular CSS class on that DIV? Any idea what might have caused the DIV to be missing?

**Comment by billreed63** [comment]
When the user selects a state in theme editor the `disableWidgetFocusFrame` is placed over widgets that do not support the state. 

I did a little looking yesterday and the `disableWidgetFocusFrame` is added but  the geo Coordinates are wrong now.

**Comment by billreed63** [comment]
I will take a shot at this
