### ISSUE TITLE
Maqetta getting slower & availablity issues

### ISSUE THREAD

**Issue by megaD** [maqetta/maqetta#2911]
I noticed recently that downloading the workspace is getting very slow. I had to download my work file by file. Today I can't get into my files in Maqetta. They don't load.

**Comment by jhpedemonte** [comment]
@JonFerraiolo @peller 

What do you see when the files refuse to load?

Do you see any errors in the browser's error console?

**Comment by JonFerraiolo** [comment]
I just tried things on maqetta.org as a guest user and everything seemed very snappy, including download. I wonder if @megaD has slowness with his laptop (e.g., everything has slowed down) or his browser (maybe it needs to be restarted?). Another potential problem might be that his workspace at maqetta.org or one of his files has something in it that would slow things down.

**Comment by megaD** [comment]
I recorded videos of the problem in Firefox 14 and Chrome 21 showing the error console.

Firefox: http://screencast.com/t/mWx70ClQw
Chrome: http://screencast.com/t/Wa3NDkALTh

Account: megadupek@yahoo.de

Screenshot of Firefox error console: http://screencast.com/t/SW1f4kVe
Screenshot of Chrome error console: http://screencast.com/t/khIt9Kd6BJ

I'm running a desktop machine (AMD Phenom II 920@3,1 GHz) and all other websites and the system is responsive. I'm using OpenDNS and Speed DNS in Firefox. Windows 7 64-bit.

I recorded a video of the downloading problem. The more and the larger files I select the longer it takes: http://screencast.com/t/jHsU3yofyNZ

I would really great if this can be fixed. I don't want to move my project to another editor or environment.

Thanks,

Piotr

**Comment by megaD** [comment]
As mentioned in the parallel thread on the user group the loading issue is fixed now. I never played around with any /lib settings nor added a /lib folder (or not that I'm aware of) so I guess it was something related to the Preview5 to Preview6 migration that has been mentioned.

The slow downloading of the entire workspace still occurs.

Piotr

**Comment by aerwin** [comment]
--> no milestone to M7 to get tracked better

**Comment by jhpedemonte** [comment]
@megaD, we just released v7 out on maqetta.org, with many performance and server enhancements.  Please test again and let us know if you still see issues.

-> M8

**Comment by megaD** [comment]
v7 indeed solved it! I can download now all my files at the same time. thanks so much
