### ISSUE TITLE
Preview in browser shows Orion icon instead of Maqetta icon

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2916]
This is a nice-to-have for M7.

I fixed the Maqetta page editor such that the Maqetta browser tab shows a Maqetta icon instead of an Orion icon, but for Preview-in-browser, we still have the 3-dotted Orion icon showing in the browser tab.

To fix the Maqetta page editor, I "cheated" by adding this line to pagedesigner.html:

```
<link rel="shortcut icon" href="app/davinci/img/maqetta.png" />
```

For preview in browser, we really can't use the same approach because this is the user's file, not the Maqetta page editor. Therefore, the LINK approach isn't viable. Instead, we will have to figure out how the Orion server deals with the browser tab icon. The standard thing is to put a favicon.ico file into the root folder for a web page, but I didn't find any matches for "favicon" in our code or Orion's code. We will probably have to ask the Orion folks about whether anyone remembers how they are making the 3-dot icon appear in browser tabs.

**Comment by jhpedemonte** [comment]
Dupe to #3095, which has more info.

**Comment by JonFerraiolo** [comment]
closing this as dupe
