### ISSUE TITLE
Source editors need to resize more often

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2918]
@peller could you look into this? It's undoubtedly the result of the UI makeover changes that I've been making, but I'm really swamped these days.

With the left-side palettes popping out to the right, and right-side palettes popping out to the left, the interior canvas size changes. I'm seeing various cases where source editors (e.g., double click on app.css) open up with too little width, probably because the last time the code remembers, the canvas size was smaller (because of side palettes being open).

I expect we will need to add a new published event in response to each call to Workbench.js routines `expandPaletteContainer()` and `collapsePaletteContainer()`, and then have one of the editor routines (EditorContainer.js? ModelContainer.js?) listen to that topic and call resize() on the appropriate widgets.

**Comment by peller** [comment]
The Orion source editor is not a Dijit Widget so its geometry is not managed by the resize.  Need to look at how we were managing this before.  Might need something like this 801ebbc6 but event-driven.
