### ISSUE TITLE
Prevent views/palettes from being smaller than size of their tabs

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2920]
@peller 

RIght now, it is possible to pull on the splitter that separates the left-side palettes from the currently open editor and pull that splitter all the way to within 20px of the left edge of the browser window. We should find a way to prevent pulling on that splitter such that the tabs are always fully visible.

**Comment by peller** [comment]
Should be as simple as setting the minWidth property on the BorderContainer constructor
