### ISSUE TITLE
Outline view breaks in Source view

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2922]
@JonFerraiolo 
- Drag bordercontainer to canvas
- save and reload page
- go to source mode
- open outline palette
- Can't expand border container

**Comment by doronrosenberg** [comment]
@JonFerraiolo Looks like outline isn't being notified when editors are changed (design to source, etc).  Looks like the events aren't being fired?

**Comment by JonFerraiolo** [comment]
I don't think we ever had an event for changing between design/source/split modes. My guess is that we've had various obscure bugs forever due to the lack of such events. If such a solution would help, feel free to add a dojo.publish() to PageEditor.js so that the outline palette can listen to the new event.

**Comment by doronrosenberg** [comment]
@JonFerraiolo @jhpedemonte 

So here is a more general question.  What is happening is that when we switch to source mode, the Border container widget reference I have in the Outline view is now pointing to a widget that has no domNode - it seems that the widgets have been replaced with new versions and that I am holding on to a reference to a destroyed widget.

I have a bug on me to change Outline to not store referenced but instead ids.  But is the fact that the widgets are being replaced by switching to source view a bug?

**Comment by JonFerraiolo** [comment]
@peller 

I'm not 100% I understand what's going on with destroyed widgets, but my guess is that the source editor repeatedly causes the source code to be reparsed and modeled (almost with each keystroke), which causes a whole new Context.js to be created, and maybe a new VisualEditor object. So I wouldn't be surprised if there are objects that get destroyed when the source editor is active.

I  believe there is an event (maybe even a couple of events) that get fired whenever new source code is parsed and modeled. Something named `pagerebuilt` if my memory serves me correctly.
