### ISSUE TITLE
Prop panel always shows up and then collapses

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2923]
Perhaps render it offscreen first? I can probably take a look as well

**Comment by JonFerraiolo** [comment]
> I can probably take a look as well

Feel free to reassign this to yourself, or ok to leave it with me, too. 

Note that the "properties palette" is now 10 separate palettes. When Workbench.js processes ve.plugin.js, it calls the constructor for SwitchingStyleViews.js, which triggers the dojo widget create process, causes buildRendering() and similar functions to get called in SwitchingStyleViews.js at the appropriate point of the widget lifecycle. In one of those lifecycle callbacks, the code builds the other 9 tabs. So, if the idea is to render offscreen, you may have to render all 10 offscreen, not just the one.

I'm not sure if offscreen is necessary. I would first try to see what breaks if the right-side BorderContainer (and therefore its TabContainers at the top and bottom) starts off with the smaller width (i.e., the collapsed width).

**Comment by doronrosenberg** [comment]
@jhpedemonte moving to m8

**Comment by JonFerraiolo** [comment]
for time being, reassigning to me for M7 Prio-Med to see if there is something I can do that is reasonably safe and effective. The current expand/collapse behavior is annoying.

**Comment by JonFerraiolo** [comment]
I believe I fixed this yesterday when addressing a different issue. Closing.
