### ISSUE TITLE
Cannot build Maqetta+Orion from source

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2925]
The PDE build system which Orion uses pulls the Maqetta code from GitHub.  Currently, there is no way to override this and build from local source.  That means that we have no way of testing out builds before committing code.

For the _base_ build, we can specify the `maqettaCode` environment variable for these purposes.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte M8 Prio-Med

**Comment by jhpedemonte** [comment]
Dupe to #2807.
