### ISSUE TITLE
Orion: open id login icons misplaced on login screen

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2932]
Prio High.  Hoping this is an easy fix for a very valuable feature.

The g/y/etc. icons show up in gray and are misplaced to the left of the page.  I asked Simon about this and he said the Orion login page appeared to be modified and didn't match the style sheet:

> it looks like div id="openIDLogin" should be wrapped with div id="orionOpen"

**Comment by peller** [comment]
Should be

```
   <div class="orion-open" id="orionOpen">
               <div id="openIDLogin" class="orion-open-header">Log in with:</div>
               <div class="orion-open-images">
                   <a id="googleLoginLink" class="loginWindow" aria-labelledby="openIDLogin googleLogin"> 
                       <div class='openIdWrapper'>
                           <div id="googleLogin" class="googleIcon" alt="Google" title="Google"></div>
                       </div>
                   </a> 
                   <a id="yahooLoginLink" class="loginWindow" aria-labelledby="openIDLogin yahooLogin"> 
                       <div class='openIdWrapper'>
                           <div id="yahooLogin" class="yahooIcon" alt="Yahoo!" title="Yahoo!"></div> 
                       </div>
                   </a> 
                   <a id="myopenidLoginLink" class="loginWindow" aria-labelledby="openIDLogin myopenidLogin"> 
                       <div class='openIdWrapper'>
                           <div id="myopenidLogin" class="openIdIcon" alt="myOpenID" title="myOpenID"></div> 
                       </div>
                   </a>
               </div>
           </div>
```

**Comment by peller** [comment]
According to Simon, there are other styling issues on the page.  The content should be updated to match or directly use the Orion sources.

**Comment by childsb** [comment]
Is this hosted or standalone?

For our hosted instance, I removed the open ID, gmail, facebook login and only allow signup with an email address.

**Comment by peller** [comment]
Hosted.  I see this on maqetta-app-test.  I recommend not removing the feature, since it otherwise seems to work and could be extremely useful.

**Comment by childsb** [comment]
Does open ID guarantee an email association with the ID?

Theres a few assumptions that ID == email address in code

**Comment by peller** [comment]
Yes, I believe it does imply an e-mail address, but I don't know if or how that's passed back or what sort of token you're using with Orion.  Is there a particular API you're thinking of?  Perhaps @skaegi can shed some light on this?

**Comment by JonFerraiolo** [comment]
We need an email address for the review/commenting feature to work.

An OpenId is sometimes an email address (e.g., joesmith@gmail.com) but usually it's just a string. When connecting to an OpenID provider for verification, they return info as described here: https://rpxnow.com/docs/providers. 

Most of the providers send back the verification email address, but some of them don't. Therefore, there will be a percentage of the time when we would have no email address at all.

For those that send verification email addresses, I would expect some of the time the verification email address is the same email address that the user would like Maqetta to send messages to, but in other cases they might want Maqetta to send emails to an alternate email address. Therefore, even when we have an email address, some of the time it will be the wrong email address.

Therefore, my conclusion is that we have to disable OpenId until we have a way for people to register where we force them to provide an email address in the case that their login ID isn't their email address (e.g., OpenID).

(Remember how I've been pounding the table for almost 2 years saying we need to implement our logic such that it is possible for us to support usernames that aren't necessarily their email addresses?)

**Comment by peller** [comment]
There are currently three providers.  For now, can't we look at each and determine if they provide e-mail addresses, and only disable those which don't?

**Comment by JonFerraiolo** [comment]
like I said, the email addresses that you get from the provider might not be email address that users want Maqetta to send them notifications. Let's wait on OpenID until we have a robust solution for getting the user to tell us about the email address to which Maqetta should send correspondence.

**Comment by peller** [comment]
That's a problem which we could document around, but if we choose to defer, having a robust login system should be high priority for our next milestone.   Either way, the HTML structure should be corrected as described here, and the buttons fully enabled or disabled.

**Comment by childsb** [comment]
deferring to 0.8

**Comment by JonFerraiolo** [comment]
@jhpedemonte 

-> @JonFerraiolo M8 Prio-Med

**Comment by jhpedemonte** [comment]
Closing.  We don't currently show these icons at all.

**Comment by peller** [comment]
We should.  Reopen?

**Comment by jhpedemonte** [comment]
Well, then that's a different bug.  Also, best to just wait for Orion and piggyback on that work.

**Comment by peller** [comment]
my observation was that if the icons weren't misplaced and disabled, that it _was_ working.
