### ISSUE TITLE
asynchronous loadRequires() call must be removed from _getCreateCommand

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2935]
5 CreateTools have calls to loadRequires() from _getCreateCommand()

> StackContainerCreateTool, TreeCreateTool, ComboBoxCreateTool, EdgeToEdgeListCreateTool, DataGridCreateTool (obsolete?)

These actions should probably be factored out into a separate method returning a `Deferred`, called prior to `_getCreateCommand()`.  It might be worth exploring if some or all of these dependencies should be encoded in metadata instead of js logic.

@jhpedemonte 

Blocks #2126

**Comment by doronrosenberg** [comment]
@jhpedemonte @peller 

Looks like I would have to change PasteTool when calling addPasteCreateCommand on the widget-specific Tool class to support Defereds

**Comment by doronrosenberg** [comment]
@peller Hopefully this is now fixed
