### ISSUE TITLE
Can type in project name drop down File Palette

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2936]
- Go to file palette
- Notice I can type in project name drop-down (which should be read-only) 

![screenshot](http://i.imgur.com/8kyBR.png)
- Hit Rename button and get taken back to welcome page
- Select Open -> File... and see strange contents in file dialog

![screenshot](http://i.imgur.com/YJ5uq.png)

**Comment by JonFerraiolo** [comment]
-> @childsb 

I'll guess that the fix consists of replacing ComboBox with Select.
