### ISSUE TITLE
Open File Dialog: Dbl-click should open file

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2937]
I think every time I go to the Open File dialog I double click on the file I want, then realize double-click doesn't work, then go click the OK button. It would be nice if dbl-click just opened the file.

Not a stop ship, but opening as high priority because I think it would have to be really easy to add and would be a nice usability enhancement.

[NOTE: I suppose this should apply to the new Open Review dialog and any other similar dialogs as well.]

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg 

I would make this a ship-stopper, actually. It's a really bad early impression and should be not that hard to fix.

**Comment by peller** [comment]
perhaps even more important than double click, selecting a file and hitting 'return' should trigger the 'ok' button.  ('escape' does seem to trigger 'cancel')

**Comment by aerwin** [comment]
This should also cover the "Select a file" dialog (which I'm not sure reuses the same code as open file or not).
