### ISSUE TITLE
Download Dialog: Default file name should be based on project name

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2938]
It would be really nice if the Download dialog defaulted to `[project name].zip` rather than `workspace1.zip`. Reasons:
- we're really downloading the project, not the entire workspace
- easier to keep track of on file system
- better flow from start to finish when moving to RAD between Maqetta project name, zip file name, and final RAD project name

**Comment by JonFerraiolo** [comment]
-> @childsb

**Comment by JonFerraiolo** [comment]
@jhpedemonte 

-> M8

**Comment by jhpedemonte** [comment]
Actually, moving back to M7.  This should be easy enough to do and low risk.
