### ISSUE TITLE
Can't set font-size for label

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2946]
Using Chrome... working through "Adding event handling to nodes" section of tree test case...
1. create new scene called "myState"
2. add label to canvas
3. select myState in Scenes palette
4. In the Properties Palette, go into Font Properties for the label. Follow the cascade for the size field, check the "Apply to this state only", and change the size to something like 50px. The size of the label should change in the page editor.
5. See exception and no change in label size:

```
Uncaught TypeError: Cannot read property 'readOnly' of undefined Cascade.js:207
declare._onFieldChange Cascade.js:207
lang.hitch lang.js:373
target.(anonymous function).dispatcher aspect.js:94
declare._onChange MultiInputDropDown.js:188
lang.hitch lang.js:373
target.(anonymous function).dispatcher aspect.js:94
(anonymous function) _FormWidgetMixin.js:202
lang.hitch lang.js:375
(anonymous function) _WidgetBase.js:1106
lang.hitch
```

**Comment by aerwin** [comment]
I was able to reproduce just by doing the following (so I don't think related state-related)...
1. New HTML file
2. Drop label onto canvas
3. try to change font size via widget palette

**Comment by JonFerraiolo** [comment]
@billreed63 

Might be a bug introduced as I modified the Properties palette code to fit in with the new UI
