### ISSUE TITLE
No "push" feedback from toolbar buttons

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2947]
@JonFerraiolo 

This might still be on your list of clean-up items, but I was struggling with the toolbar buttons. E.g., you click on them and there's no indication that the a press occurred. E.g., I found myself hitting "Save" multiple times because I didn't think my click registered.

**Comment by JonFerraiolo** [comment]
Note that standard dojo buttons (with claro) don't actually have a different visual presentation for "pressed" in their own styling definition. However, what they do have (which provides visual feedback upon clicking on a dojo button):
- They have a different visual state for "hover" (and when you are pressing, the mouse will indeed by hovering over the button)
- The **browser** provides its own visual effect to indicate that the button is in a selected state. (On Chrome, it's a blue rectangle)

Note that @jmockler and @jinsil have sent specs on how buttons should look under various scenarios. I hope to implement those specs today.

**Comment by JonFerraiolo** [comment]
I believe I have implemented hover and push feedback for everything except the left-side buttons (cut, copy, paste, undo, redo, delete). I broke something with those icons, and I hope to fix that shortly.
