### ISSUE TITLE
(Orion) Login screen doesn't tell me I entered wrong password

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2949]
@childsb 
1. Go to Orion login screen
2. Enter user name
3. Type wrong password and nothing happens except for following in console:

```
POST http://maqetta-app-test.austin.ibm.com/login/form 401 (Unauthorized) LoginWindow.js:221
confirmLogin LoginWindow.js:221
document.getElementById.onclick LoginWindow.js:415
```

**Comment by peller** [comment]
I actually see an exception in the code.   Using the build on app-test, I get a 403, and the LoginWindow code attempts to parse the responseText as JSON when it's really a full HTML error page

**Comment by jhpedemonte** [comment]
Duplicate of 8246 in our bugzilla.  Closing.

**Comment by aerwin** [comment]
@jhpedemonte This isn't an internal driver issue, so not sure BugZilla is right tracking mechanism. But, guess that's up to you.
