### ISSUE TITLE
Performance: Unresponsive script trying to create file in Firefox

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2953]
NOTE: I saw this kind of stuff happen the other day when I suggested we wait until Dojo build in place before continuing with test matrix. Apparently, this still happens even after there's a Dojo build.

Imagine this is intermittent... my steps using Firefox on Mac going to our Orion test server...
1. Clear browser cache
2. Login to Maqetta
3. Create new HTML file

![Screenshot](http://i.imgur.com/jMies.png)

Stuff ended up loading after I clicked the continue button.

**Comment by jhpedemonte** [comment]
@peller recently committed changes to the VE code to make it more asynchronous.  Hopefully that will help in this instance.

**Comment by peller** [comment]
Don't see a connection.  If you hit stop script, do you get a stack trace?

**Comment by aerwin** [comment]
Not having much luck with stop script and not always seeing unresponsive script errors, but here are two representative scenarios (one with cache cleared and one without) and associated data based on stopwatch timing:
1. logout with empty file1.html showing in workbench
2. clear cache
3. hit signin
4. At this point, roughly 13 seconds to see first signs of Maqetta (e.g., something other than white screen and files starting to load in console.
5. From here, about 4 seconds until see the work bench (some pause on welcome page)
6. Next, about 10 seconds until files stop loading in console (always stops at PUT http://maqetta-app-test.austin.ibm.com/maqetta/cmd/setWorkbenchState)
7. Then, about 30 seconds until "Loading" disappears from file1.html editor and right palettes are minimized. It's during this step that seemed most useful for stopping the script, but the stop script button is unresponsive. [Total time: ~58 seconds]

If I don't clear the cache between logging out and logging back in, Step 7 basically disappears:
1. Hit sign-in
2. At this point, roughly 10 seconds to see first signs of Maqetta (e.g., something other than white screen and files starting to load in console.
3. From here, about 4 seconds until see the work bench (some pause on welcome page)
4. Next, about 7 seconds until files stop loading in console (always stops at PUT http://maqetta-app-test.austin.ibm.com/maqetta/cmd/setWorkbenchState)
5. Then, very quickly "Loading" disappears from file1.html editor and right palettes are minimized. [Total time: ~23 seconds]

As a side note, it's always amazing to me how many files are loaded even if the cache isn't cleared.]

**Comment by aerwin** [comment]
And, also... while different than going to maqetta-test over the VPN, I did a test speedtest.net test from laptop to a server in Ausin. And, I clocked in at 30.4 Mbps. So, I'm on a pretty fast connection.

**Comment by peller** [comment]
Looking at the network panel, at several points during page load, it seems like the server stalls.  Short files take ~10 seconds to load.  Does not seem to be related to network throughput or client processing.

**Comment by jhpedemonte** [comment]
Assigning to @peller for now.

**Comment by peller** [comment]
not seeing this problem anymore.  seemed to be machine config/load related
