### ISSUE TITLE
Update Developer-Setup to include Orion instructions, and tell users to not import certain projects

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2959]
@jhpedemonte @peller @aerwin 

I have tried rebuilding using Orion from a clean "git clone" and have been unsuccessful. I believe the instructions we have at github.com are a combination of incomplete, inaccurate and too complicated.

Don't we need to update https://github.com/maqetta/maqetta/wiki/Developer-Setup to tell users to not import the following projects:
- Any project name that matches `*dojotoolkit*`
- Any project name that matches `*apache*`
- Any project name that matches `*zazl*`
- org.cyberneko.html
- org.json
- org.mozilla.javascript

Also, I hope that the wiki page on Orion isn't what we expect open source developers to do. I am pretty sure there is a shortcut to becoming a full-fledged Orion open source developer. Isn't the key things that developers need to do just this:
- They have to "git clone" the orion server and orient client projects, and store these as siblings to the "maqetta" local repository
- They have to set "Target platform", which I believe entails:
  - Pulling down a build and storing it persistently somewhere on his file system
  - Going to Eclipse preferences and changing Target platform to that folder

**Comment by peller** [comment]
The plugins you mention are all optional, but should be imported and should work.  Going forward, I've been told we should be relying on Eclipse features more to package our code and make deployment easier.

**Comment by childsb** [comment]
I removed the base developer setup and merged them into one:

https://github.com/maqetta/maqetta/wiki/Maqetta-with-Orion-Developer-Setup

**Comment by JonFerraiolo** [comment]
> I removed the based developer setup...

Are you sure? The old page still seems to be there, without any notice about being obsolete:

https://github.com/maqetta/maqetta/wiki/Developer-Setup

Maybe what you are saying is that you removed the link to the above page from the wiki's root page, but it's still accessibility via the "All pages" feature in the wiki. Could you please wipe the content from the old page and add a hyperlink to the new page?

**Comment by JonFerraiolo** [comment]
@childsb: Reopened to request the above minor cleanup.

**Comment by childsb** [comment]
i left the old page intact for reference.  do you want it deleted?

**Comment by JonFerraiolo** [comment]
How about putting a note at the top telling users to use the new page instead?

**Comment by childsb** [comment]
done! closing.
