### ISSUE TITLE
Exception DnD button Absolute layout

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2960]
FF/Win 7

create page
switch flow to absolute
DnD button

note the following exception. the button does get place in the correct position. so the exception is non distructive

VisualEditorOutline._widgetChanged: e = TypeError: this.domNode is null
http://maqetta-app-test.austin.ibm.com/maqetta/app/davinci/davinci.js?@revision@
Line 55312

**Comment by doronrosenberg** [comment]
Possible timing issue, sounds like outline is getting a widget that is not part of a dom tree.

**Comment by doronrosenberg** [comment]
Hmm, I can't reproduce on trunk
