### ISSUE TITLE
Wrong heading styling on iPhone header?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2961]
With Win/FF running on maqetta-test today:
- New Mobile App
- Add a ScrollbarView
- Add a Heading

Result below=> (isn't this wrong? With Preview 6, the heading's background is dark gray)

![wrong heading styling](http://i.imgur.com/2VloN.png)

**Comment by billreed63** [comment]
This seems to be a timing issue on FF
