### ISSUE TITLE
Dialog appears (disabled) behind smart input

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2968]
**_Tests > Widget Palette: Mobile Data Store Based > EdgeToEdgeDataList: Data file from workspace**_:

Clicking on folder icon in smart input brings up the "Select a source" dialog **behind** the smart input.  Also, dialog is disabled (smart input still has focus), so cannot complete test.

**Comment by doronrosenberg** [comment]
dupe of #2965
