### ISSUE TITLE
Multiple workspaces

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#297]
@jonferraiolo
Maybe this falls out of other short-term work, but may have to wait.

**Comment by JonFerraiolo** [comment]
Assigning for M4, presumably as part of Orion file client effort

**Comment by JonFerraiolo** [comment]
Pushed to M5

**Comment by jhpedemonte** [comment]
-> M6

What exactly is this for?

We currently have multiple project -- why do we need multiple workspaces?

Would this be handled by Orion?

**Comment by childsb** [comment]
stale issue.
