### ISSUE TITLE
Cannot edit source in split view after selecting widget

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2970]
1. Open Sample1.html.
2. Enable source split view.
3. Select the **_New**_ button in the visual editor.  This should also select the source in the source view.
4. Try to edit the source.

You can edit the source in spilt view as long as you don't select a widget in the VE.

**Comment by peller** [comment]
Chrome only bug.  Editor does not seem to regain focus unless you click on a native widget (like a properties textbox) then back into the source editor.  Investigating.
