### ISSUE TITLE
"Absolute" text is cut off in toolbar

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2972]
When switching from "Flow" to "Absolute" in the toolbar, the icon shows up as "Abs...".

**Comment by JonFerraiolo** [comment]
That's what we decided to do when talking with @jmockler. Maybe it's better to make the button bigger (because it has the whole word "Absolute")

**Comment by jmockler** [comment]
@JonFerraiolo I recall we reviewed this issue in the UI meeting. And I mentioned that it may not work, since folks may not understand what 'Abs...' means. So I agree we need to show the full text, or at minimum have a 'hover help' that shows the full name.
