### ISSUE TITLE
Hidden left-hand panel pops out automatically when switching files

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2975]
1. Open mutliple files.
2. Hide the left-hand panel.
3. Switch to another file, then back to original file.

The left-hand panel automatically pops out when switching files, even though I just hid it.

**Comment by JonFerraiolo** [comment]
-> M8

**Comment by jhpedemonte** [comment]
Can we reconsider for M7?  It's an annoying behaviour.  Is the fix too risky?

**Comment by JonFerraiolo** [comment]
Moved back to M7 for further consideration.
