### ISSUE TITLE
Need icons for new widgets

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2979]
Need icons for these widgets:

**[Dojox Mobile](http://dojotoolkit.org/reference-guide/1.8/dojox/mobile.html)**:
- SearchBox
- GridLayout
- ProgressIndicator
- ValuePicker
- ValuePickerSlot
- ValuePickerDatePicker
- ValuePickerTimePicker
- DatePicker
- TimePicker

**HTML**:  _(This one must have fallen through the cracks.)_
- `<p>`

**Comment by JonFerraiolo** [comment]
@jinsil @jmockler 

I went through the widgets to double-check the list provided by @jhpedemonte and I believe his list is correct.

I went through the existing widgets to see which existing widget icons we could reuse. Here is my assessment:
- **SearchBox** - we could re-use the widget icon from "Search" from the ClipArt section
- **GridLayout** -  best to have a new icon (maybe a variation of the HTML table icon, but without the header row?) 
- **ProgressIndicator** - best to have a new icon (although we could conceivably reuse the ProgressBar icon from Untested section)
- **ValuePicker** and **ValuePickerSlot** - can share the same icon - best to have a new icon (although we could conceivably reuse the CheckedMenuItem icon from Untested section)
- **ValuePickerDatePicker and **DatePicker** -  - can share the same icon - best to have a new icon (although we could conceivably reuse the DateTextBox icon from Dojo Controls section)
- **ValuePickerTimePicker and **TimePicker** -  - can share the same icon - best to have a new icon
