### ISSUE TITLE
Rearrange "Dojo Control" widgets into logical groupings

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2982]
Similar to #2864, we should group the widgets in "Dojo Controls" into logical groupings.

Currently, the widgets are (roughly) alphabetized.  But this leads to odd sorting: HorizontalSlider is no where near VerticalSlider.

---

Proposal:

The [Dojo docs](http://dojotoolkit.org/reference-guide/1.8/dijit/index.html) provide groupings.  We could do something like this:
- **Buttons** (Button, ComboButton, DropDownButton, ToggleButton)
- **Text Boxes** (TextBox, TextArea, SimpleTextArea, ValidationTextBox, CurrencyTextBox, DateTextBox, NumberTextBox, TimeTextBox, NumberSpinner, TimeSpinner)
- **Select Widgets** (Select [1], ComboBox, FilteringSelect, MultiSelect)
- **Other Form Widgets** (CheckBox, Form, RadioButton)
- **Sliders** (HorizontalSlider, VerticalSlider)
- Tree
- **Misc** (Calendar, ColorPalette, Rating)

[1] **Note:** `dijit.form.Select` is named "DropDownSelect" in package.json.  Should change back to "Select".

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
I was thinking we would focus on cleaning up the UI in the widget and properties palettes for M8. There are a number of UI issues to discuss there, including which widget groups should appear for which editors, and in what order. We also want to switch to bigger icons in the widget palette. I think we should leave everything alone for M7 and then thrust a new UI for widgets with M8.

@jmockler

**Comment by jhpedemonte** [comment]
I'm fine with creating a new UI for the Palette in M8 -- I've been throwing out suggestions for a while.

This issue is just to simply rearrange the widgets to be better grouped.  Takes 5 mins and very low risk.

**Comment by jhpedemonte** [comment]
-> M8

**Comment by jhpedemonte** [comment]
This was fixed in M8 by @JonFerraiolo's widget palette UI reworking.
