### ISSUE TITLE
themesets add/remove theme icon is doubled

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#2984]
In FireFox the + and - buttin within the theme sets dialog is doubled.  

Recreate:
1) launch maqetta
2) bring up the theme sets dialog (click on the gears icon, and select "theme sets")
3) Under the Them Sets box on the left notice that theres
+
Triangle shape

for the plus

and 
- -

for the minus icon

**Comment by JonFerraiolo** [comment]
-> me with Prio-High to investigate. Probably a regression due to my CSS hacking

**Comment by JonFerraiolo** [comment]
Fixed by checkins I did last night.
