### ISSUE TITLE
Cleanup for "unsaved changes" dialog when switching themes

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2985]
_(Offshoot from #2930)_

This dialog should be better:
1. Change text to read:
   
   ```
   "The file \"${0}\" has unsaved changes.  Click \"Save\" to save the file and switch the theme."
   ```
2. Change the "OK" button to "Save".
3. Use a Dijit Dialog instead of an alert.

**Comment by jhpedemonte** [comment]
Side note: why exactly do we have this dialog?  What does it matter that there are unsaved changes when switching themes?

@JonFerraiolo

**Comment by billreed63** [comment]
The user can modify the theme CSS files from the page designer using  cascade in the properties palette. If they do not save the changes when they switch to a different theme the working copy of the CSS files for the old theme will be removed if they where the only reference holder.
