### ISSUE TITLE
Selection chrome not cleaned up correctly

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2986]
- New HTML Page
- dnd a dijit button
- Make sure its selected
- Close the page
- Notice how the selection chrome remains for a bit before going away (FF Windows)
- Now open a new HTML page
- The button selection chrome is still there.

**Comment by JonFerraiolo** [comment]
I was able to reproduce in last night's build using Mac/FF, I think I know what causes the bug, and I believe this was fixed by 7d3187ccf2f0012fa667d27d776c7385d293bfa7. Not closing yet, though. I'll wait until the next build is available to see if it is fixed there.

**Comment by JonFerraiolo** [comment]
Tested with new build and I don't see the problem anymore. Closing.
