### ISSUE TITLE
Mobile scenes not appearing in scenes palette

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2988]
Something broke in the Scenes palette. Mobile views aren't appearing there in today's nightly build.

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte 

@peller @aerwin @billreed63 

I set some breakpoints. I believe the problem is that we are loading the Dojo library metadata (and callbacks.js) at least twice instead of just once. When running from Eclipse, the timing tends to be that we do the N-times processing of callbacks.js (and the $callbacks property) before we invoke the `invokeCallbacks` routine for onDocInit. However, when running a build, the timing is different, and we have appear to be calling `invokeCallbacks` between the first and second times we process the descriptor for the dojo library, such that the first descriptor object (in memory) has $callbacks, but the second one (which is probably the new active one) doesn't yet have a value for $callbacks. 

Clearly, one fix that we need is that we should only process each library once.

My guess is that the gridx dependency on dojo is trigger this issue.

**Comment by peller** [comment]
see #2955

**Comment by jhpedemonte** [comment]
> I believe the problem is that we are loading the Dojo library metadata (and callbacks.js) at least twice instead of just once.

Indeed.  The call to **cmd/getUserLibs** returns the following:

```
[{
    "userLibs": [{
        "id": "dojo",
        "version": "1.8",
        "metaRoot": "app/metadata/dojo/1.8",
        "required": false,
        "root": "lib/dojo"
    }, {
        "id": "dojo-src",
        "version": "1.8",
        "metaRoot": "app/metadata/dojo/1.8",
        "required": false,
        "root": "lib/dojo"
    }, {
        "id": "DojoThemes",
        "version": "1.8",
        "metaRoot": "",
        "required": false,
        "root": "themes"
    }, {
        "id": "gridx",
        "version": "1.0.0",
        "metaRoot": "app/metadata/gridx/1.0.0",
        "required": false,
        "root": "lib/dojo/gridx"
    }, {
        "id": "html",
        "version": "0.8",
        "metaRoot": "app/metadata/html/0.8",
        "required": false
    }, {
        "id": "clipart",
        "version": "1.0",
        "metaRoot": "app/metadata/clipart/1.0",
        "required": false,
        "root": "lib/clipart"
    }, {
        "id": "maqettaSamples",
        "version": "1.0",
        "metaRoot": "app/metadata/maqetta/core/0.3",
        "required": false,
        "root": "samples"
    }, {
        "id": "maqetta",
        "version": "0.3",
        "metaRoot": "app/metadata/maqetta/core/0.3",
        "required": false,
        "root": "lib/maqetta"
    }, {
        "id": "shapes",
        "version": "1.0",
        "metaRoot": "app/metadata/shapes/1.0",
        "required": false,
        "root": "lib/shapes"
    }]
}]
```

Notice the entries for **dojo** and **dojo-src**: both have the same `metaRoot`, which means we end up loading `app/metadata/dojo/1.8/package.json` twice (and eventually, also _widgets.json_ and _callbacks.json_).

I really don't like **dojo-src** -- does it have to be a "library"?

(Using `require()` to load these files would prevent loading the files twice.  But it might make the code in _metadata.js_ a bit convoluted.)

**Comment by jhpedemonte** [comment]
Actually, that is the case.  Specifying **dojo-src** as a "library" is completely wrong.  We're bending the meaning of the `ajaxLibrary` element in _plugin.xml_ in order to get dojo-src into Maqetta.  There should be **only one `ajaxLibrary` element**. [1]

How do we currently make use of _dojo-src_?

**Proposal:** Add a `<sourcePath>` child element to `<ajaxLibrary>`, pointing it to the unbuilt source for the library.  Something like this:

``` xml
<ajaxLibrary name="dojo" id="dojo" version="1.8">
   <libraryPath location="WebContent/dojo" name="/lib/dojo"></libraryPath>
   <metadata location="app/metadata/dojo/1.8" />
   <sourcePath location="WebContent/dojo-src" name="/lib/dojo-src" />
</ajaxLibrary>
```

[1] "DojoThemes" is also guilty of this offense, but at least that one has different values for `location` and `name`.

**Comment by peller** [comment]
+1  Zazl is the only consumer of the -src libraries, so the ajaxLibrary is really just there to make it known to zazl.  Exposing it as a library means it's exposed in the UI, which is both good and bad  RAD users like to have sources in downloads, but generally they're unwanted and make the downloads too large (see #2769)

@rbackhouse and I were talking about doing something very much like this to the plugin metadata, if only to make the relationship more clear between the libraries and its 'sources' (and perhaps help design a better UI for the download/user libraries dialogs see #2769 #3035

**Comment by JonFerraiolo** [comment]
Might be also causing #3051.

Note that Sample1.html lists dojo-src as a package, therefore making it so that Sample1.html loads dojo twice. Haven't looked at Sample2 and Sample3.

**Comment by jhpedemonte** [comment]
Another issue!  The GridX plugin also specifies two `ajaxLibrary` elements, causing the unbuilt source files to be returned by the server instead of the built files.  See #2954.

So need to make `<sourcePath>` change to GridX's plugin.xml as well.

**Comment by jhpedemonte** [comment]
Reassign to @peller, since he is currently coding this up.

**Comment by rbackhouse** [comment]
FYI for Zazl support I had to add a new method to the Library interface to obtain URL objects from the source location. 

public abstract URL getSourceURL(String path);

org.davinci.ajaxLibrary.Library and org.davinci.ajaxLibrary.LibraryManager were modified for this change

**Comment by peller** [comment]
-> @JonFerraiolo can you take another look?  I'm still not seeing any mobile scenes, and the -src libraries are effectively gone now.

**Comment by JonFerraiolo** [comment]
I'm seeing mobile views in the Scenes palette when running from Eclipse using Mac/Chrome, so closing.
