### ISSUE TITLE
Outline - src editor changes doesn't refresh outline

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2989]

**Comment by doronrosenberg** [comment]
@peller You know the source editor, do you know where the code lies that updates widgets in the VE after changes have been made to the source?

**Comment by peller** [comment]
in `davinci/ui/Editor`, `handleChange` is called from the `onTextChanged` method.  That method is bound to `_srcChanged` in `davinci/ve/PageEditor` which calls `VisualEditor.setContent`...
