### ISSUE TITLE
Icons for flow vs absolute?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2992]
@jinsil @jmockler 

Do we have icons for the flow-vs-absolute dropdown menu? I searched my hard disk and I couldn't find any image files that matched the name "_abs_".

We could use the old flow icon, but we need to find an icon for the absolute menu item on the dropdown menu.

**Comment by aerwin** [comment]
--> assigning from "no milestone" to "M7" so it gets tracked better
