### ISSUE TITLE
metadata.init() called twice

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3002]
The `init()` function from **metadata.js** is called twice:  once in Workbench.js, then later in EditorContainer.js.  This results in the init routine being run twice, which is unnecessary.

@JonFerraiolo added the call to EditorContainer.js to ensure that the action sets from the HTML library were properly added.  Before adding that, sometimes the table commands wouldn't show up in the UI.

Proposal:  cache the Deferreds array returned by `metadata.init()`.  Then, the call `Metadata.init()` in EditorContainer.js would immediately return the cached Deferred **if** the metadata has been fully resolved;  otherwise, it waits.

@peller, does that sound good?

**Comment by peller** [comment]
I prefer a more explicit approach of wiring up the deferreds so that there is only one call to init() and that we don't encourage multiple calls, but I don't understand the situation here and exactly how the second piece of code is getting called

**Comment by jhpedemonte** [comment]
Turns out the 2nd `metadata.init()` call was unnecessary, since it was further down in the stack of when the first `init()` in called in Workbench.js.
