### ISSUE TITLE
Disable undo/redo from source editor? Under which circumstances?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3011]
@doronrosenberg @jhpedemonte 

@peller - When fooling around with the product, the toolbar is visible even when in source editing mode, and in particular the Undo command sometimes is active. Once when I clicked on Undo, I got an exception.

I don't know the source editor code as well as you. Any insights about what we should do about the toolbar commands when in source-only mode or in split view? I wouldn't be surprised if there are focus issues - maybe different things should happen if keyboard focus is in the source pane vs the design pane.

Any insights on this issue? Please reassign back to me after responding. Thanks

**Comment by peller** [comment]
Right now, undo/redo should be wired up to the visual editor, even when in split mode.  At least in the basic cases, that appears to be working.  The command stack is not wired up to the Orion editor's undo/redo, but keystrokes (ctrl-y/z) are.
