### ISSUE TITLE
ThemeEditor - changing claro textbox doesn't reflect visually

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#3013]
Going through Claro Basic ThemeEditor tests.

Changing the following properties of TextBox don't reflect visually in the canvas:
- font-family
- font-weight
- font-size
- text-decoration

Note that reloading the page removed all those settings for the ones that don't work.

Assigning to Jon, not sure who owns ThemeEditor.

**Comment by JonFerraiolo** [comment]
-> @billreed63
