### ISSUE TITLE
R&C: live application note looks bad

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3017]
--> @aerwin 

@JonFerraiolo 

Making high priority just so we make sure we take care of for M7.

As part of #1519, I made a tweak so the R&C note to the user was made visible again. However, it looks bad.

Opening this issue so we can work on tweaking it separately while debating how it should look with new UI design, whether to shorten text, etc. 

Here's how it looks:

![screenshot](http://i.imgur.com/7hHrI.png)

And, for reference, here is the full text as currently written:

> Note: The page below is a "live" web application (e.g., may respond to mouse clicks or touches). You can add comments and on-screen annotations using the Comments palette. You can change the currently active scene in the Scenes palette.

**Comment by aerwin** [comment]
Closing with above commit.

**Comment by JonFerraiolo** [comment]
I tweaked the visual styling with this commit: https://github.com/maqetta/maqetta/commit/6e7b1f44e6ece490cb825bc9a496798c09e58f06
