### ISSUE TITLE
R&C: Delete annotation icon is too big (and maybe doesn't fit with other R&C icons)

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3018]
@JonFerraiolo @jinsil @jmockler

For the new delete annotations button (#1519), I used the same "X" icon found n the main toolbar for deleting widgets:

![screenshot](http://i.imgur.com/ApQfi.png)

While it works for now, it's too big and it's style perhaps doesn't fit too well with the other R&C icons.

To do this, I referenced the main davinci sprite.png instead of the review-specific sprite.png. There is a more properly sized "X" in the review-specific sprite.png, but there's no disabled counterpart:

![screenshot](http://i.imgur.com/nKhGK.png)

**Comment by jmockler** [comment]
we shouldn't use the larger 'delete' icon from the main toolbar. its too large for the current set. We haven't redesigned the toolbar for the review section yet.

I would recommend staying with the image in the second screen capture. To disable the image please do so pro grammatically by reducing the opacity of the icon by 50%.

**Comment by JonFerraiolo** [comment]
+1 to @jmockler's recommendations

**Comment by aerwin** [comment]
Closing with above commit.
