### ISSUE TITLE
Unclear why OK button is bolded

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3024]
Making Prio High just for discussion in M7...

Noticing OK button has become bolded recently in a lot of smart input dialogs. I had assumed this must be an indication this is the default button if you press the ENTER/RETURN key. But, I don't see any such behavior. So, it's unclear to me why they are bolded?

![screenshot](http://i.imgur.com/u0aok.png)

**Comment by jhpedemonte** [comment]
Assigning to @doronrosenberg for now.  cc @JonFerraiolo 

For **smart inputs** (the tooltip dialogs with a simple text entry), the default action is invoked when pressing **Ctrl Enter**.  For smart inputs that only take a single line of text, **Enter** works also.

What you show above is a **wizard**.  For those, we should make sure that **Enter** works to invoke the default action.

**Comment by doronrosenberg** [comment]
@jhpedemonte ctrl-enter works for the tree smartinput

**Comment by JonFerraiolo** [comment]
We should only bold the OK button when the Enter key will result in the OK action. For situations where you have to enter Ctl-Enter, we shouldn't bold the OK button

**Comment by doronrosenberg** [comment]
if we only do it for certain widgets it would be inconsistent.
