### ISSUE TITLE
MenuHelper console messages

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3027]
1. New HTML file
2. Drag button onto page and click OK on smart input
3. See 28 messages from MenuHelper

![screenshot](http://i.imgur.com/Q2zW6.png)

I don't think this really hurts anything, but fair number of unnecessary MenuHelper console messages. Severity of issue is lessened by the fact that Google dev tools groups like messages.

**Comment by jhpedemonte** [comment]
-> @peller.  Can we get rid of these?  They don't seem to provide any utility.

**Comment by peller** [comment]
they do reflect a problem that had to be resolved in the code.  Please comment them out, for now.

**Comment by peller** [comment]
dup #2274
