### ISSUE TITLE
gridx-src needs to be handled like dojo-src

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3035]
@childsb @jhpedemonte @peller 

I believe the fix for #1512 removed dojo-src from download/user lib dialogs. But, I see gridx-src is still there. In general, I think we need to handle [lib]-src consistently across libraries (when it exists for a library).

[But, not sure anything since should be done with this until #2769 is addressed. As it is, #2769 may necessitate some reversal of #1512.]

**Comment by peller** [comment]
@rbackhouse and I discussed possibly changing the metadata such that instead of defining peer -src ajaxLibraries, we add a tag to the existing library to reference sources

**Comment by aerwin** [comment]
--> assigning from "no milestone" to "M7" so it gets tracked better

**Comment by peller** [comment]
dojo-src should now be handled like gridx-src.  Exactly how source libraries will be downloaded is being handled in #2769. Can we close this issue?

**Comment by aerwin** [comment]
Fine with me if covered elsewhere. Closing.
