### ISSUE TITLE
Rich Text/Sticky Note: Unselectable sub-elements have outline borders

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3037]
1. New HTML file
2. Drag HTML Rich Text onto canvas and enter some text in smart input
3. Drag sticky note onto canvas and enter text into smart intput
4. See outline borders around unselectable sub-elements

![screenshot](http://i.imgur.com/SLZnF.png)

**Comment by JonFerraiolo** [comment]
-> @billreed63 I'm not sure how to fix, but one approach that I would see if it could be made to work would be to add rules in content.css that had a selector that looked something like this:

```
.stickyNoteClass DIV, .stickyNoteClass SPAN,
.richHTMLClass DIV, .richHTMLClass SPAN {
  outline:none;
}
```
