### ISSUE TITLE
Can't change position of button to absolute

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3038]
Using Chrome on Mac and following VE 3 test case...

Told I can't change position of button to absolute:

![GitHub Logo](http://i.imgur.com/XPwg3.png)

**Comment by aerwin** [comment]
Also, happens on TextBox. Works on Calendar and ColorPalette, so not sure how pervasive.

**Comment by JonFerraiolo** [comment]
-> @billreed63
