### ISSUE TITLE
Tree SmartInput: event handlers are live in VE

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3040]
I was playing with Tree SmartInput and put alert('open') and alert('close') as the onOpen and onClose values for a particular tree node. Upon clicking OK to the SmartInput dialog, the screen showed an alert with the word "open" in it.

What we probably need to do is add the on\* event handlers only to the model, and not the user iframe's DOM nodes.

**Comment by aerwin** [comment]
Closing. Dup of #2715.
