### ISSUE TITLE
Snap lines don't show while dragging shape handles

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3041]
@JonFerraiolo 

Using Chrome on Mac, and doing VE 3 test case....
1. New HTML sketch
2. Drag widget onto canvas (like Calendar)
3. Drag shape onto canvas (like line)
4. Move line handle around to reisze and no snap lines appear

**Comment by JonFerraiolo** [comment]
I suspect this is a regression due to the selection chrome DIVs moving from the user iframe into the Maqetta frame. Probably need to add an offset to the x and y positions to fix.
