### ISSUE TITLE
Cannot call method 'getWidgetTopDom' of undefined

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3046]
Using Chrome on Mac...

Unfortunately, having trouble locking down a reliable scenario for this... but, basically, (intermittently) when I select a widget and try to open one of the props palettes (like Background) I get an exception. This exception appears to have negative consequences in that props palette does not show selection info and changing attributes has no impact.

```
Uncaught TypeError: Cannot call method 'getWidgetTopDom' of undefined davinci.js:44009
_1f17._widgetSelectionChanged davinci.js:44009
_19f5._updatePaletteValues davinci.js:36647
_19f5._initialPerspectiveReady._alreadySplitIntoMultipleTabs davinci.js:36848
lang.hitch dojo.js:4960
_55f.(anonymous function)._564 dojo.js:6939
_1535.onButtonClick davinci.js:30157
_1535.postCreate davinci.js:30087
lang.hitch dojo.js:4960
```

![GitHub Logo](http://i.imgur.com/uJ5Iz.png)

The first time I hit this I was just starting the "Properties 3" test case. I reloaded browser to try and replicate and it seemed to work. But, then I've seen it several times since then. Each time reloading the browser clears things up, but then I eventually end up hitting it again. So, not sure if weird timing things going on or what.

This was my scenario the first time I saw it:
1. New HTML file
2. Drag Content Pane onto canvas
3. Drag label, Dojo Button, and Dojo TextBox into Content Pane
4. Select label
5. Open background props tab

**Comment by JonFerraiolo** [comment]
-> me

**Comment by JonFerraiolo** [comment]
-> @billreed63 because it might be same issue as #3052. Feel free to send either or both bugs to me.

**Comment by billreed63** [comment]
at start up we can end up with no context or editor set in cascade.js  due to async editor selection getting published before the cascade is built  so best to set this in  widget selection
