### ISSUE TITLE
Add support for undo/redo commands to state actions

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#305]
The current outline actions, such as adding and removing states, do not support
undo/redo. We should fix this when undo/redo are active again.

**Comment by JonFerraiolo** [comment]
@billreed63, @peller

Probably won't have time to fix this safely for M3.

**Comment by jhpedemonte** [comment]
-> M6

Also see #343 -- integrating source editor into command stack (for undo/redo).

This would be a good **usability** win.

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo

**Comment by JonFerraiolo** [comment]
I actually fixed the Outline palette part of this bug in the M6 cycle, but the States palette part isn't done yet. Just need to make a command for various states actions. Probably not a huge deal, but not something I would want to attempt this late in the M6 cycle.

Pushing to M7 Prio High.

**Comment by JonFerraiolo** [comment]
Getting close, but not yet fully completed.

-> M8

**Comment by JonFerraiolo** [comment]
This was fixed in either M7 or M8. Closing.

**Comment by JonFerraiolo** [comment]
Reopening and changing title. The outline palette part of bug has been fixed, but not the states palette part of the bug.

**Comment by JonFerraiolo** [comment]
Will close this issue after updated the test plan
