### ISSUE TITLE
GridX - jsonp support broken

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#3050]
Using http://maqettaservice.appspot.com/sampleservice with GridX initially seems to work, except there are JS errors in the console.  Reloading the page however shows the "Failed to load data".

**Comment by aerwin** [comment]
I was able to reproduce... 

I think the first set of exceptions is a dup of #2910 ("Using JSONP with GridX floods developer console with messages").

The stuff that happens in the console after reloading the page is really weird...

```
FAILED: failure for loading dojox.io.xhrScriptPlugin(http://maqettaservice.appspot.com/sampleservice,callback); ItemFileReadStoreHelper.js:65
```

```
OPTIONS http://maqettaservice.appspot.com/sampleservice 500 (Internal Server Error) xhr.js:216
xhr xhr.js:216
dojo.xhr xhr.js:607
dojo.xhrGet xhr.js:630
declare._fetchItems ItemFileReadStore.js:371
simpleFetch.fetch simpleFetch.js:235
declare._storeFetch _Cache.js:273
declare._fetchByIndex Async.js:369
array.map array.js:282
declare._fetchByIndex Async.js:368
declare.when Async.js:160
notify Deferred.js:187
dojo.Deferred.promise.then.then Deferred.js:297
declare.when Async.js:159
declare._call _Extension.js:59
declare._call _Extension.js:59
declare._cmdRequest Model.js:350
array.map array.js:282
declare._cmdRequest Model.js:341
declare._exec.func Model.js:379
declare._exec Model.js:397
declare.when Model.js:222
declare.load Body.js:107
declare._initMod Core.js:473
notify Deferred.js:187
dojo.Deferred.promise.then.then Deferred.js:297
declare._initMod Core.js:471
declare._load Core.js:425
declare._reset Core.js:220
declare.postCreate Grid.js:79
declare.create _WidgetBase.js:380
declare.postscript _WidgetBase.js:299
(anonymous function) declare.js:390
Grid.markupFactory Grid.js:209
parser.construct parser.js:425
(anonymous function) parser.js:170
array.map array.js:278
parser._instantiate parser.js:164
parser.parse parser.js:841
signalListener Deferred.js:37
Deferred.then.promise.then Deferred.js:252
parser.parse parser.js:840
_21c8._processWidgets davinci.js:48136
dojo.ready.dojo.addOnLoad.callback ready.js:104
onLoad ready.js:35
requestCompleteSignal ready.js:51
onLoad ready.js:43
requestCompleteSignal ready.js:51
onLoad ready.js:43
requestCompleteSignal ready.js:51
onLoad ready.js:43
requestCompleteSignal ready.js:51
onLoad ready.js:43
requestCompleteSignal ready.js:51
onLoad ready.js:43
requestCompleteSignal ready.js:51
onLoad ready.js:43
requestCompleteSignal ready.js:51
onLoad ready.js:43
requestCompleteSignal ready.js:51
onLoad ready.js:43
req.signal dojo.js:332
forEach dojo.js:93
req.signal dojo.js:331
guardCheckComplete dojo.js:1230
checkComplete dojo.js:1240
onLoadCallback dojo.js:1402
req.injectUrl.onLoad
```

```
XMLHttpRequest cannot load http://maqettaservice.appspot.com/sampleservice. Origin http://maqetta-app-test.austin.ibm.com is not allowed by Access-Control-Allow-Origin.
```

And, then some other/similar related things...

**Comment by aerwin** [comment]
Even when "Failed to load data" shows up in the visual editor, preview still works. So, I don't think there's anything wrong with the HTML.

**Comment by doronrosenberg** [comment]
Harm looks like the code is trying to xhr rather than use a script tag to do crossdomain loading.  CC @peller in case this rings any bells.  If you are too busy I can take a look at this.

**Comment by aerwin** [comment]
--> @doronrosenberg 

Thanks for the offer... If you want to work on this, I won't argue... :)

I had just turned on break on all errors and the issue appears to be that that `dj.require` in the first line of the try block below is `undefined`. The `dj` variable has a value, but `require` does not. This code is from `ItemFileReadStoreHelper`:

```
      var dj = context.getDojo();
           try{
              dj.require('dojo/data/ItemFileReadStore'); // needed for first loading of html file
               dj.require('dojox/io/xhrScriptPlugin');    // needed for first loading of html file
               dj.dojox.io.xhrScriptPlugin(xhrParams.url,xhrParams.callback);
           }catch(e){
               console.warn("FAILED: failure for loading dojox.io.xhrScriptPlugin("+xhrParams.url+","+xhrParams.callback+");");
           }
```

I've not investigated any further, so I have no idea why `require` would not have a value.

Also, I know @peller has recently warned against the immediate form of `require`, so that could potentially end up being an issue once we figure out why there is no longer a `require` on the `dj`.

**Comment by jhpedemonte** [comment]
Shouldn't we be using `require` instead of `dojo.require` (they are different -- the latter is the legacy API).

**Comment by aerwin** [comment]
I didn't write the code, but I was assuming the intent was to require it using the Dojo in the page. Is there a way to do that? Maybe that's what the `withDoc` stuff does for you?

**Comment by peller** [comment]
Looks like I missed something in the async conversion.  I don't think we have a 'proper' way to use require inside an iframe.  What we have been doing is to substitute `context.getGlobal()["require"]` for `context.getDojo().require` and dj.dojox.io.xhrScriptPlugin should instead use the returned value from the require.  As @aerwin points out, it can only use the immediate form if the code is already loaded, which probably isn't the case here, so the code will also need to be restructured to use callbacks.
