### ISSUE TITLE
Exception when opening background properties palette

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3052]
on FF/win http://maqetta-app-test.austin.ibm.com/maqetta/

new desktop html claro
DnD div
click on background in properties palette

note the following exception:
this.context is undefined

Line 44009

**Comment by billreed63** [comment]
Note that I can't set teh background color on the div after the exception

**Comment by billreed63** [comment]
exception on button also

**Comment by aerwin** [comment]
Sounds like a dup of #3046?

**Comment by billreed63** [comment]
could be but on FF it happens every time, so it may be easier to reproduce using FF

**Comment by billreed63** [comment]
was fixed by #3046
