### ISSUE TITLE
On refresh, Files palette and New HTML can default to images/ folders

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3061]
@peller @childsb 

Some of our Tree widgets are saving some cookies. Here are my cookies running on localhost:

```
Cookie:dijit_Tree_10SaveSelectedCookie=.%2Fproject1%2F.%2Fproject1%2Ffile14.html; dijit_Tree_7SaveSelectedCookie=.%2Fproject1%2F.%2Fproject1%2Ffile7a.html; dijit_Tree_2SaveSelectedCookie=project1%2Ffile9.html; dijit_Tree_12SaveSelectedCookie=project1%2Ffile21.html; dijit_Tree_0SaveSelectedCookie=project1%2Ffile10.html; dijit_Tree_1SaveSelectedCookie=eproj1; dijit_Tree_4SaveSelectedCookie=eproj1%2FWebContent%2Ffile1.css; dijit_Tree_5SaveSelectedCookie=eproj1%2FWebContent%2Ffolder1%2Ffile1.js; resourceTreeSaveSelectedCookie=project1%2Fsamples%2Fsample_data%2Fimages%2Fclose.gif; maqExplorer=.%2Fproject1%2C.%2Fproject1%2F.%2Fproject1%2Fsamples%2C.%2Fproject1%2F.%2Fproject1%2Flib%2C.%2Fproject1%2F.%2Fproject1%2Flib%2F.%2Fproject1%2Flib%2Fwidgets%2Cproject1%2Cproject1%2Flib%2Fdojo%2Cproject1%2Flib%2Fdojo%2Fdijit%2Fthemes%2Cproject1%2Flib%2Fdojo%2Fdijit%2Fthemes%2Fclaro%2Cproject1%2Fthemes%2Fipad2%2Cproject1%2Flib%2Fdojo%2Fdijit%2Cproject1%2Fsamples%2Ceproj1%2Ceproj1%2FWebContent%2Ceproj1%2FWebContent%2Ffolder1%2Ceproj1%2FWebContent%2Fsamples%2Ceproj1%2FWebContent%2Ffolder2%2Cproject1%2Fsamples%2Fsample_data%2Cproject1%2Fsamples%2Fsample_data%2Fimages; 
```

The first big problem here is `resourceTreeSaveSelectedCookie=project1%2Fsamples%2Fsample_data%2Fimages%2Fclose.gif;` What that cookie is doing is preserving the last selection in the Files palette across sessions. The side effect of this is that the "current folder" at startup is determined by the currently selected resource in the Files palette, which in my case is the read-only file `close.gif`, which is in a folder that is also read-only. When any of the "Create ..." dialogs comes up (including Create HTML file), at startup, the current folder will be "images" instead of the root project folder. (Note: we had the same cookie in M6, but on browser refresh, the file listed by that cookie did not become selected.)

I got into the above situation by going into the images folder, dragging close.gif onto the canvas, and then hitting browser refresh.

I'm not sure exactly what we should do to address this situation. Here are some options:
- **Don't save cookies for the Files palette (and maybe other Tree widgets).** There is a real problem if we have large cookies and going beyond the limits of the Jetty server for a GET request. We've run into 403's in the past when our cookies were too large.
- **Don't save the `resourceTreeSaveSelectedCookie` cookie**. 
- Other ideas?

**Comment by jhpedemonte** [comment]
I've gotten in similar issues with the _samples_ folder being selected on refresh -- when I go to create a new file, the **Create** button is disabled, because the _samples_ dir is selected and it is read-only.  I can see a user getting confused by this situation.

**Comment by doronrosenberg** [comment]
So Dojo 1.8 added the feature that Tree stores the last selection - before it only stored expansion of the tree.  There is only one parameter to set, so its either all or nothing.  I would say we remove storing any cookies related to the Files pallete as we have little time for m7.  Anyone against that?

**Comment by doronrosenberg** [comment]
@peller This is weird, why would the Tree in the dialog get the cookie of the the files palette Tree? Different ids should mean they won't share data right?

**Comment by doronrosenberg** [comment]
@peller nevermind, it isn't cookie based after all

**Comment by doronrosenberg** [comment]
@jhpedemonte @JonFerraiolo 

So when we build the new file dialog, we look if anything is selected in the Files Palette and use that directory as the default for the dialog.  Since tree now by default selects previous selections, it seems our only choice is to turn off all persisting in the files palette

**Comment by jhpedemonte** [comment]
Yes, I'm fine with not persisting selection in the Files view across app refreshes.

**Comment by peller** [comment]
According to @JonFerraiolo's original report, it looks like other trees are saving cookies.   We tried turning off persistence of trees a few releases ago.  Unfortunately, it has to be done on each tree, as persist:true is the default.  It looks like there's a tree without a dialog doing the persistence... perhaps a new dialog somewhere?

**Comment by peller** [comment]
open file dialog: #3087
