### ISSUE TITLE
Tab-less file

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3066]
While testing on Firefox, I was able to close a file's tab, but not it's contents:

![tabless](http://i.imgur.com/sAIln.png)

I was able to reproduce this a couple of times:
1. Click **Create > Desktop Application**, click **Create** button to open a new HTML page.  Don't add content.
2. Repeat for a 2nd file.
3. Right-click on current tab and select **Close all tabs**.
4. Click on **OK** when the unsaved changes alerts appear (one for each open file).
5. Repeat (1) again.
6. Drop a Dijit Button on the page.  Click **OK** on the smart input.
7. Click on close button in file's tab.  Click **OK** on the unsaved changes alert.

**Comment by JonFerraiolo** [comment]
I haven't been able to reproduce this yet. Were you running off of a server, off of a local install, or running from Eclipse? On a Mac, right?

**Comment by jhpedemonte** [comment]
Testing on maqetta-test, using Firefox/Mac.

**Comment by jhpedemonte** [comment]
I was able to reproduce this on Firefox and Chrome (Mac) when running from source.  I updated the summary with more detailed recreation steps.
