### ISSUE TITLE
Reopening saved CSS file leads to error, bad UI

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3068]
Running **Tests > Main Menubar: Overview > Create menu: Create CSS File**.  Closed and reopened CSS file and Maqetta looked like this:

![css file gone bad](http://i.imgur.com/24wdG.png)

Notice the **white rectangle** overlaying the text and the beige border.

Saw this error in the console: `Error: Tried to register widget with id==davinci.js.cut but that id is already registered`

Afterwards, all CSS editors showed this error.  Only solution was to refresh the page.  Of course, that only works for the first CSS file.

**Comment by jhpedemonte** [comment]
Oh, affects JavaScript editor as well.

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg The stack trace shows that OutlineView.js is trying to create a popup menu, undoubtedly trying to use IDs that were used in a previously created popup menu. I'm not sure what exactly is going wrong. Maybe the old menu isn't getting destroyed properly?
