### ISSUE TITLE
Cookies never forget files you have opened in the past

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#307]
I think I figured out why I was getting 413 errors on my windows machine. My
resourceTreeSaveStateCookie cookie had grow due to repeated usage and contained
a long list of file names that I haven't used in a long time. Probably, the
HTTP GET request was dying because making the GET request too big. When I
deleted my daVinci cookies, daVinci started running fine again.

I'm not absolutely sure I diagnosed the problem correctly - I didn't trace
things through in the code, but I'm pretty sure about it.

**Comment by childsb** [comment]
jon - did you mean to assign this to me? i'm not sure what the original issue is here?  it sounds like the dijit.tree (or our custom tree) cookie handling. this may be a non issue with @pellers recent 1.7 changes.

**Comment by JonFerraiolo** [comment]
Closing this issue. Given Adam's recent work with the cookies used by dijit.Tree, I now understand the problem better and better able to analyze. This problem appears to have been fixed since this bug was logged original (several months ago). resourceTreeSaveStateCookie isn't growing continuously like it had been doing previously.
