### ISSUE TITLE
Update mime-type of sample services for JSONP

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3075]
--> @jhpedemonte (as a start)

@billreed63 

Sprin-off from #2910...

When we configure JSONP using one of our sample services, we get messages like "Resource interpreted as Script but transferred with MIME type text/html".  And, at creation type we get a lot of them. 

Looking at the response headers, this is true:

```
HTTP/1.1 200 OK
Date: Fri, 24 Aug 2012 00:00:32 GMT
Content-Type: text/html
Server: Google Frontend
Content-Length: 347
```

Response content:

```
parent.dojo.io.script.jsonp_dojoIoScript7._jsonpCallback({ identifier: 'id',    label: 'name',  items: [        { id: '0', name:'Foods', numberOfItems:1},      { id: '1', name:'<b>Fruits</b>', numberOfItems:1},      { id: '4' ,name:'Citrus', numberOfItems:1},         { id: '2', name:'Vegetables', numberOfItems:0},     { id: '3', name:'Cereals', numberOfItems:0} ] } )
```

In #2910, @jhpedemonte wrote:

> Well, one is on maqetta.org, so we'd need to properly set up the mime type for that file.
> 
> The one on appspot was uploaded by @billreed63, correct?  Not sure how that works or how to edit the mime type.

**Comment by jhpedemonte** [comment]
First, on moketta, http://moketta.org/sampleService doesn't work;  I need to use http://moketta.org/sampleService.php.  Is that fine?

Secondly, what should the _Content-type_ for this be?  `application/javascript`?

**Comment by jhpedemonte** [comment]
I was able to fix this for http://moketta.org/sampleService.php by adding `header("Content-type: application/javascript");` to top of PHP file.  However, when going through GridX with this, goes into infinite loop of breaking in debugger.

Reopen if there are any other instances.

**Comment by aerwin** [comment]
--> Reopening for discussion...

@jhpedemonte @billreed63 

What about the one on appspot? Or, should we stop using that one?

**Comment by aerwin** [comment]
@jhpedemonte FYI... tried the service with new mime-type and that successfully eliminates the infinite mime warning messages. As you note, the inifnite JS errors still occur, but that's covered by #2910 and a bug against Dojo. So, think we're good. Thanks!

**Comment by jhpedemonte** [comment]
I think @billreed63 created the **appspot** one, right?  If that's a PHP file, we can fix by adding the header line as [mentioned here](https://github.com/maqetta/maqetta/issues/3075#issuecomment-8335217).  Otherwise, not sure we can do anything about that.

**Comment by aerwin** [comment]
@billreed63 If that's simple for you to follow @jhpedemonte 's instructions, I think it's worth keeping around the second service. I know one has HTML tags in a cell and one doesn't.

**Comment by billreed63** [comment]
I updated the content type on the app spot service

```
Cache-Control:private
Content-Encoding:gzip
Content-Length:165
Content-Type:application/javascript; charset=ISO-8859-1
Date:Thu, 06 Sep 2012 18:50:56 GMT
Server:Google Frontend
Vary:Accept-Encoding
```

**Comment by aerwin** [comment]
Thanks, @billreed63 ... re-closing.
