### ISSUE TITLE
Better UI for read-only files/folders

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3080]
I don't like the UI for read-only files folders.  They look **disabled**, as if they cannot be used.  But I can open up 'samples' folder and open up 'Sample1.html'.

**Proposal:** Create a special icon for read-only files, maybe with a lock in the lower right of the icon.  Show items with normal text color (i.e. not disabled).

---

**Proposal Addendum:** _(from Jon)_

> I think we would still want to have the "text" to be styled differently, maybe a slightly different color than black, rather than the very disabled look it has now.

**Comment by jhpedemonte** [comment]
-> @doronrosenberg / M7

Doron, how easy would it be to fix this?  We would still need to get special icons to denote the read-only nature, but want an estimate/risk analysis first.

**Comment by doronrosenberg** [comment]
@jhpedemonte pretty straightforward once we have an icon

**Comment by jhpedemonte** [comment]
OK.  For now, put in some random, place holder icons, so we can test it.  @JonFerraiolo will take care of getting the real icons.

**Comment by doronrosenberg** [comment]
We already have a readOnlyResource class we use, so really easy

**Comment by doronrosenberg** [comment]
@JonFerraiolo Are we planning to have read only icons for each type or just a general folder/file one?

**Comment by doronrosenberg** [comment]
@JonFerraiolo checked in the style changes, temp icons

**Comment by jhpedemonte** [comment]
When I talked to Jon, he mentioned having three icons:
- read-only file
- read-only closed folder
- read-only open folder

**Comment by jhpedemonte** [comment]
Still don't like the "faded" look of the read only files -- they still look disabled.

@JonFerraiolo, what about keeping them black, but using italics instead?  At least they wouldn't look disabled, but there would be a distinction between read-only and other files (in addition to different icons).

**Comment by JonFerraiolo** [comment]
I think italics would be fine. Note that we haven't gotten a response about special read-only versions of the file/openfolder/closedfolder icons. If we don't get icons in time, we might need to restore the default Dojo icons and/or fuss with the icons ourselves just for this release.

See #3186

**Comment by JonFerraiolo** [comment]
IMO, the remaining part of this issue is that we have generic file icons for read-only files (i.e., all read-only files get the generic "File" icon) but for read-write files, we have different icons for different file types (HTML vs JS vs CSS vs etc). 

@doronrosenberg - could you see how much effort it would take to have read-only versions for the various file-type-specific icons that we show in the Files palette?

**Comment by doronrosenberg** [comment]
@JonFerraiolo I could fire up Photoshop and create some icons

**Comment by JonFerraiolo** [comment]
Go for it. The read-only overlay icon is in davinci/img/sprite.png, roughly at location (36,1174).

**Comment by doronrosenberg** [comment]
Just committed the icons, I think I got all of them.  The only issue really is for style sheets - that icon is different dimensions so I placed the lock icon relative to the "document" part rather than the big S.

**Comment by JonFerraiolo** [comment]
IMO, perfect work on the icons.
