### ISSUE TITLE
Need icon for "Orion Navigator" menu item

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3082]
Currently, the icon for **Open > Orion Navigator** is a scissor.  We should put in something more appropriate.

**Comment by JonFerraiolo** [comment]
@jmockler @jinsil 

Yes, we need a proper icon. Let me study this. My first inclination is to use the same 3 small dark circles (Orion's belt) that they use in various parts of their UI, and to scour around for a 16x16 icon with the 3 circles.

**Comment by JonFerraiolo** [comment]
Moving to Prio-High - it's really ugly now and should be a snap to fix.
