### ISSUE TITLE
Fix UI startup sequence, to not be so chaotic

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3083]
When loading Maqetta (or refreshing) I see the welcome page appear, then the empty left and right panels appear, before finally closing.  Doesn't look good.  Test on Firefox, which is slower and will show this better.

Is there a way to show the left/right panels with first opening them up fully?

**Comment by JonFerraiolo** [comment]
There probably is a way to pull this off. I intended to get to this sooner or later, just haven't done so yet. I expect fixing this takes a certain amount of work and entail some risk.
