### ISSUE TITLE
license not shown in Readme.md

### ISSUE THREAD

**Issue by painbank** [maqetta/maqetta#3086]
please document what the code is licensed under.

**Comment by aerwin** [comment]
-> no milestone to M7 to get tracked better

@painbank 

I just downloaded the nightly build (http://maqetta.org/nightly/) and see a LICENSE file right in the top directory. Is there something else you are looking for? Or, perhaps, you have a older driver that maybe didn't have this LICENSE file in it for some reason?

**Comment by jhpedemonte** [comment]
Right, we have the license in the downloads, but not in the top level of the source.

@JonFerraiolo, I suggest copying [releng/davinci.product/LICENSE](https://github.com/maqetta/maqetta/blob/master/releng/davinci.product/LICENSE) to the top level.  Therefore, anyone viewing the code on GitHub will see the LICENSE file on the first page.  Sound good?

**Comment by JonFerraiolo** [comment]
> I suggest copying releng/davinci.product/LICENSE to the top level.

Absolutely! Gosh, how did we miss that?

**Comment by painbank** [comment]
I see the license now in the download of the nightly build, but having at
the top level makes it obvious to someone doing a cursory look..

thanks.

On Sun, Aug 26, 2012 at 10:41 PM, Jon Ferraiolo notifications@github.comwrote:

> I suggest copying releng/davinci.product/LICENSE to the top level.
> 
> Absolutely! Gosh, how did we miss that?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/maqetta/maqetta/issues/3086#issuecomment-8045972.

## 

Rich Elswick
