### ISSUE TITLE
Can't close last editor

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3091]
At some point today I did a "git pull" and lost ability to close the last editor:
1. Open HTML file file (so there's one open editor)
2. Close the file and get exception:

Uncaught TypeError: Cannot read property 'editorID' of null Workbench.js:1758
(anonymous function) Workbench.js:1758
Runtime.getExtensions Runtime.js:230
Runtime.getExtensions Runtime.js:229
Workbench._bringPalettesToTop Workbench.js:1757
Workbench._switchEditor Workbench.js:1743
Workbench._editorTabClosed Workbench.js:1888
lang.hitch lang.js:375
target.(anonymous function).dispatcher aspect.js:94
Workbench._shadowTabClosed Workbench.js:1918
lang.hitch lang.js:375
target.(anonymous function).dispatcher aspect.js:94
okToClose Workbench.js:1439
Workbench._createEditor.shadowTab.onClose Workbench.js:1452
declare.closeChild StackContainer.js:319
declare.onCloseButtonClick StackController.js:267
declare.postCreate StackController.js:102
lang.hitch

**Comment by JonFerraiolo** [comment]
I saw this problem earlier today and fixed it as part of this commit: 9c519cb46ac5cfed65c9592e962ea62823d10e26#maqetta.core.client/WebContent/davinci/Workbench.js
