### ISSUE TITLE
States not working in preview (I have a fix)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3092]
@doronrosenberg @peller 

With latest code, custom states aren't working in preview, but the good news is I have a fix.

Sometime recently, we changed the outline palette from using `display:none` to `display:none !important`. It's a known browser problem that you can't do an element.style assignment with a value that includes `!important` - the browser will just toss it away. The `!important` works ok in the page editor because the page editor ultimately does a complete style attribute assignment as a text string, and browser can deal with `!important` in a `setAtttribute("style", value)`.

If you need to set `!important` in conjunction with an element.style assignment such as `element.style.display="none !important", you have to use the`element.style.setProperty()` method, which according to quirksmode isn't available on IE9. 

My fix is to add some runtime logic to AppStates.js. My fix should deal with the IE9 situation. (For IE9, the !important will be stripped from the `element.style.display=` assignment.)

**Comment by peller** [comment]
shouldn't we just use CSS rules to set display:none?  This is what Dijit does.  I think if you have a specific rule, it might have the same effect as applying !important?

**Comment by JonFerraiolo** [comment]
I'll let @doronrosenberg explain why he changed it to `display:none !important`, but my guess is that `!important` definitions within stylesheets will take precedence over inline style, so to absolutely ensure that inline style will win the cascade, you need to say `style="display:none !important"`
