### ISSUE TITLE
Orion icon appears in browser tab for preview

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3095]
Assigning to @childsb because he is the Orion and build expert, but maybe someone else can take this one on.

@jhpedemonte @peller @doronrosenberg @billreed63 @aerwin 

The browser tab for preview-in-browser shows the Orion 3-dots icon rather than the Maqetta icon. I managed to override the Orion browser tab icon for the page designer by adding a LINK tag to pagedesigner.html, but for preview we are using the user's HTML document, so I don't want to stuff in a Maqetta-specific LINK tag.

I did a unix `find` and then a `grep` to look for suspects in how the Orion icon appears in the preview tab. I found the following, but I'm not sure that the browser tab icon actually comes from this file:

```
$ find . -iname '*.ico' -print
./releng/davinci.releng/orion/builder/html/orion.ico
$ grep -rn 'orion.ico' *
releng/davinci.releng/orion/builder/maqettaOrion.product:30:         <ico path="html/orion.ico"/>
$ 
```

![Browser tab for preview in browser](http://oi45.tinypic.com/2eds3l5.jpg)

**Comment by JonFerraiolo** [comment]
@doronrosenberg - you interested in figuring out how to either put a Maqetta browser tab icon on preview, or at least wipe out the Orion icon? If so, please reassign this to yourself.

**Comment by jhpedemonte** [comment]
-> @doronrosenberg

**Comment by doronrosenberg** [comment]
We could upload an ico version of the maqetta icon into /releng/davinci.releng/orion/builder/html/ and override orion.ico.

Edit: or not, didn't work. hmm

**Comment by JonFerraiolo** [comment]
Looks like preview is now showing a generic icon. That's acceptable. Closing.
