### ISSUE TITLE
Widget id/class not showing in any prop panel other than "Widget"

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#3097]
Widget id/class not showing in any prop panel other than "Widget"

Seems those 2 fields are not hooked up in all the other panels

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg Are you sure? Maybe I'm missing something. Could you please elaborate and then send back to me?

What I'm seeing when I run the latest code with Mac/Chrome:
- I see class and id fields at the top of all of the property sections (Widget, Event, ..., SVG)
- If I have class and id fields on a widget, and I unselect and reselect the widget, the class and id fields correctly show the class and ID on the given widget, for all of the different property sections 
- If I have a class and id fields on a widget, and I unselect and reselect the widget, the "label" (for:...) about the class and property fields), for all of the property sections (Widget, Event, ..., SVG)
- If I change class or id for the currently selected width in any of the property sections (Widget, Event, ..., SVG), the change seems to have an effect

But I do see one bug. If you select a widget with values for class or id, and then deselect, the class and id fields don't get cleared. (Maybe I'll fix that today if I find some time)

**Comment by JonFerraiolo** [comment]
Wait, sending back to me. First I discovered an exception in Cascade.js, and then upon fixing that bug, I'm seeing that the class and id fields are not getting updated properly in the other sections.
