### ISSUE TITLE
Need to update README.html due to Orion differences

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3100]
Per #1702, we no longer have a single-user mode. We need to review README.html that is the root file in the download ZIP and make sure it is accurate, given the changes due to using Orion.

@childsb @jhpedemonte

**Comment by JonFerraiolo** [comment]
Might be fixed by 8881f802ba1fdfe08fe4125d461a5ea3f6b0ade0, but I'm waiting for an answer to #3197

Also, need to copy the README.html file into the appropriate Orion build project.

**Comment by JonFerraiolo** [comment]
-> @peller 

@peller: I believe I have updated the content of README.html for M7 within our old (obsolete) project `releng/davinci.product/README.html` (in public repository). Somehow or other this file (`releng/davinci.product/README.html`) needs to get included in our ZIP downloads using the new approaches. Probably needs to be copied somewhere near this folder: `releng/davinci.releng/orion/builder/scripts`

**Comment by peller** [comment]
see #3196

**Comment by peller** [comment]
fixed in 6b9c03d8eb86921a49708410db5286f629abcf73
