### ISSUE TITLE
Preview broken with zazl

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3105]
@peller @jhpedemonte 

Doing test cases against internal server and preview is failing with this HTML file. There are no errors in the browser console.

![GitHub Logo](http://i.imgur.com/1VSWu.png)

```

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dijit/form/Button",
  "dijit/ColorPalette"
]);
</script>
<style>@import "themes/claro/document.css";@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
</head>
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
 <input type="button" data-dojo-type="dijit.form.Button" intermediateChanges="false" label="Button" iconClass="dijitNoIcon"></input>
 <div data-dojo-type="dijit.ColorPalette"></div>
</body>
</html>
```

If I remove "?zazl=true" from the URL it renders. If I put it back, then it doesn't.

Proper rendering:

![GitHub Logo](http://i.imgur.com/cBZph.png)

**Comment by aerwin** [comment]
The bad rendering appears every time I preview. But, if I reload the preview window without closing it, it seems to work (even with zazl=true in the URL).

**Comment by peller** [comment]
Hrm.  I'm seeing this intermittently.  Seems like everything loads correctly, but for some reason parseOnLoad isn't working. Typing `dojo.parser.parse()` in the console makes everything appear.

@rbackhouse

**Comment by rbackhouse** [comment]
I'm trying this out with my dev environment the preview works everytime for me.

**Comment by jhpedemonte** [comment]
Saw this last night when testing Dijit Tree.  The non-Dijit elements load fine, but Tree wouldn't appear; no errors in console.  A shift-reload of the preview page made it render correctly.

**Comment by peller** [comment]
I have seen this only on the maqetta-test server, not in a local environment

**Comment by peller** [comment]
must have something to do with difficulties supporting dojo/ready?

**Comment by rbackhouse** [comment]
FYI I can't recreate when running the server locally but can with the test server.

**Comment by rbackhouse** [comment]
I have been able to recreate by running a server on another machine although the occurrence is far less frequent. I does allow me to debug it better that with the test server.

**Comment by rbackhouse** [comment]
This should be fixed now.
