### ISSUE TITLE
Migrate page appears briefly on maqetta-test

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3106]
@childsb 

(Just logging this - probably will get immediately closed)

After activating my new account on maqetta-test, and entered my password twice on the page pointed to by the activation email, an HTML page appeared briefly that said something about migrating workspace yes or no. But it was soon replaced by the Maqetta application.

What's with that migrating workspace page?

**Comment by jhpedemonte** [comment]
-> @childsb

**Comment by childsb** [comment]
this is part of the design of the migration feature--

after the user verifies their account, it redirects them to /maqetta/cmd/migrate  ((or similar, forgot the exact URL). and that page determines if the users workspace is up for migration.  if it is, then it shows the "do you want to migrate" screen.  if not, it redirects to base maqetta.

i'll fix this to hide by default and only unhide if the user needs to migrate.  so if users have no workspace to migrate, they'll just see a blank page before the quick redirect.
