### ISSUE TITLE
Remove untested widgets

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3107]
I couldn't find an issue for this. Sorry if this is a dupe.

**Comment by jhpedemonte** [comment]
-> @doronrosenberg.  Take a look in Palette.js (I think).

**Comment by JonFerraiolo** [comment]
I expect two fixes are needed:
1. Comment out all JSON structures in the widgets.json file(s) for all of the widgets that are in the untested group. Probably just dojo
2. Remove untested from one or two arrays in the Palette*.js files, which lists the preferred section ordering for the Palette

**Comment by jhpedemonte** [comment]
I don't think we need to do (1), just make sure that the category doesn't show.  I'd rather keep the widgets.json files as is.

**Comment by JonFerraiolo** [comment]
I think they'll show unless they are commented out. I'm pretty sure that if you remove the Untested section only, the widgets will end up in some other section.
