### ISSUE TITLE
DateTextBox - 'value' should show a valid entry value, not a formatted value

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3108]
@peller @billreed63 

With DateTextBox, there is a 'value' field in the Widget-specific properties that requires a particular date format, such as `2012-08-15`. Upon entering such a value, the widget shows the string you entered (i.e., `2012-08-15`) but the value field in the properties palette shows a formatted value (e.g., `Wed Aug 15 2012 00:00:00 GMT-0700 (Pacific Daylight Time)`). If a user then tried to incrementally edit the formatted value (e.g., change the 15 to 16, as in `Wed Aug 16 2012 00:00:00 GMT-0700 (Pacific Daylight Time)`, the widget will treat the value as invalid.

Seems to me we shouldn't be showing the formatted value in the Properties palette.

(Also see #2432)

**Comment by peller** [comment]
looks like a dup of #659

**Comment by peller** [comment]
see also #65

**Comment by doronrosenberg** [comment]
M8
