### ISSUE TITLE
Outline palette - can no longer drop onto container TreeNode

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3113]
@peller 
- Create new Desktop app
- Add a DIV, and inside the DIV drop a button
- Add an Accordion under the DIV
- Go to Outline palette, open up the Accordion to show the 2 empty ContentPane's
- Click select the DIV in the Outline palette
- in outline palette, drag the selected DIV and attempt to drop onto the first ContentPane child of the Accordion

Result => No drop occurs, and you are left with a phantom green drag widget.

With M6, this operation was supported: you could drop a widget onto a container node, and the widget being dropped would be added as the last child of the container node.

**Comment by doronrosenberg** [comment]
Fallout from outline model changes

**Comment by doronrosenberg** [comment]
fixed by c16a528f41d310c92b8b7a834be6fc4f9a799a73
