### ISSUE TITLE
HTML textarea SmartInput doesn't support rich text properly

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3116]
@billreed63 @doronrosenberg 

If you bring up SmartInput for an HTML TEXTAREA element, and then enter this string as the value in the SmartInput user interface:

```
<b>abc</b>
```

the radio buttons appear (which is good). If you then select the "HTML" radio button and click OK, the widget on the screen shows this as its content:

```
&lt;b&gt;abc&lt;/b&gt;
```

**Comment by aerwin** [comment]
@JonFerraiolo @billreed63 @doronrosenberg 

The TEXTAREA element only supports plain text, so this bug really needs to be to turn off showing the radio buttons.

From http://www.w3.org/wiki/HTML/Elements/textarea :

```
The <textarea> element represents a multiline plain text edit control for the element's raw value.
```

**Comment by aerwin** [comment]
Closing with above commit.
