### ISSUE TITLE
After deleting row in HTML table, exceptions when click on canvas

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3118]
Using Chrome on Mac with internal test server... not sure exception has an impact, but making Prio High for investigation
1. New HTML file
2. Drag HTML table onto page
3. Click OK on smart input
4. Select cell in first row
5. Choose Remove Row menu option
6. Every time click on white space in cavas see this exception... Haven't looked at code, but guessing nothing really to do with HTML tables per se...

```
_143a.setSelected davinci.js:28223
_19fc.deselectAll davinci.js:36465
lang.hitch dojo.js:4960
_507.forEach dojo.js:6443
_19fc.deselectAll davinci.js:36461
_279b.deselect davinci.js:55967
lang.hitch dojo.js:4956
_55f.(anonymous function)._564 dojo.js:6939
_2804.onMouseDown davinci.js:56202
_21fc.onMouseDown davinci.js:49038
lang.hitch dojo.js:4956
```

**Comment by aerwin** [comment]
-> Sev 3 to Sev 2

There are side effects... e.g., I see exception when clicking in outline view as well and can't select the table from the outline view.

**Comment by doronrosenberg** [comment]
@aerwin I fixed 3125 and am not seeing this, can you retest?

**Comment by aerwin** [comment]
@doronrosenberg Just restested and think you fixed it! Thanks. Closing.
