### ISSUE TITLE
FF: widget outlines in VE get cut-off

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3120]
Using FF on Mac:
1. New HTML File
2. Drag a widget that takes up the full width (like HTML div, table, etc.)
3. Outline cut-off on top and sides. for example, see DIV below:

![GitHub Logo](http://i.imgur.com/r4WFC.png)

**Comment by JonFerraiolo** [comment]
What's going on is that there are 8px-wide DIVs on each side of the canvas that render a 7px-wide gradient. These DIVs end up above the canvas in stacking order and therefore obliterate the outline. This might be a very quick fix if I'm lucky.
