### ISSUE TITLE
Can't undo after previewing file

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3124]
@billreed63 @jhpedemonte @JonFerraiolo 

Opening a spin-off of #3104 to deal with undo/redo stack after previewing a page.

**Comment by JonFerraiolo** [comment]
Closing this issue. If we fix #3104 (which we should), then this issue becomes moot. Note that undo continues to work even after the user manually clicks on the Save icon - you can go back in time before the save.
