### ISSUE TITLE
Widget deleted if id already in use.

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3128]
Create new desktop html
DnD content pane 
in Properties palette set the ID to  'contentpane_testcase1'
DnD TabConatiner 
in Properties palette set the ID to  'contentpane_testcase1'

Note that the TabContaine is gone from the canvase but is still in the Outline..

**Comment by JonFerraiolo** [comment]
What should we be doing in this case? Dojo will die if 2 widgets use the same ID. Seems to me we need to head this off at the pass and do a check on the ID value entered into Properties palette to see if it's already in use. If everyone agrees, then -> @doronrosenberg

**Comment by jhpedemonte** [comment]
Yes, agreed.

**Comment by doronrosenberg** [comment]
So an alert if the I'd is already is used?  Or we could use a validation textbox

**Comment by jhpedemonte** [comment]
Validation textbox; no alert.

**Comment by doronrosenberg** [comment]
fixed by 344da9f4bd04d4e0fdba0a8f3970460138783c62
