### ISSUE TITLE
Regiser new user - can't re-edit Password field

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#313]
(Generally only applies when using the default welcome page, which isn't used all that often. Usually a site-specific welcome page overrides the default welcome page.)

When entering the password for a new user, my finger accidentally hit an extra
key in the Password field, so then the text in Confirm Password didn't match. I
 tried to re-edit Password but the system would not let me exit out of the
Confirm Password entry field. I had to close the dialog and refresh the browser
in order to re-register with the same user name.

Maybe not a bug, but not user-friendly.

------- Comment #1 From Adam Peller 2010-09-11 17:44 [reply] -------

looks like bad usability.  it's a dojox component. we can file a ticket there. 
it appears you can click on anything except the other password field.

**Comment by JonFerraiolo** [comment]
Not sure if this problem still exists, and even if it does, maybe it only exists with the "standalone" welcome page.

**Comment by peller** [comment]
we don't use this anymore
