### ISSUE TITLE
border-color automatically capitalizes first letter: rgba=>Rgba

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3130]
Long-standing bug, but a bad one.

@childbs @billreed63 
- Add a DIV
- Go to Borders section of properties palette
- For Show, choose "props"
- Try to enter `rgba(255,0,0,.5)` into the border-color field

Result=> Field automatically capitalizes first letter. You get `Rgba(255,0,0,.5)`

I'm not sure who is doing the auto-capitalization

**Comment by doronrosenberg** [comment]
@JonFerraiolo This is happening I think because we match Remove Value in the dropdown - try entering `r` and wait a sec.  Then type `g` and notice the R remains capitalized.

@peller is there a way to have autocomplete in dijits skip certain values?  If not we may need to disable auto completion

**Comment by peller** [comment]
not aware of any way to customize the autocomplete besides using data stores and perhaps filtering them.  auto complete doesn't feel like the right UI for this anyway.

**Comment by JonFerraiolo** [comment]
disabling auto-complete is ok with me
