### ISSUE TITLE
Login screen exception doing document.getElementById('googleLoginLink')

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3131]
@jhpedemonte 

With Win/Firefox, running maqetta-test, I'm getting an exceptoin at LoginWindow.js:460:

```
document.getElementById("googleLoginLink").href = createOpenIdLink("https://www.google.com/accounts/o8/id");
```

Could it be that we are missing a few DIVs? We really shouldn't be shipping with these exceptions.

I might be able to look into this, too.

**Comment by jhpedemonte** [comment]
Dupe of #3102.
