### ISSUE TITLE
Visual problems with IconContainer - default width is 400px

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3132]
@aerwin @jhpedemonte 

IconContainer defaults to width:400px. Not a good default given that the default mobile application is 320px wide. Ideally, we could just set width to 100%, but when I tried that, the IconContainer was just a bit too wide.

**Comment by doronrosenberg** [comment]
@JonFerraiolo I don't see the 400px width when I drop it into the iphone canvas, it takes 100% width, no set width

**Comment by JonFerraiolo** [comment]
Sorry, I meant IconMenu. (I changed the title). Here is the entry in widgets.json:

```
        {
            "name": "IconMenu",
            "type": "dojox.mobile.IconMenu",
...
            "properties": {
                    "cols": 3,
                "style": "width:400px; height:200px"
            },
```
