### ISSUE TITLE
Accordion at width:100% is too wide for user iframe

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3133]
@peller @jhpedemonte 

When I drop an Accordion into the default iPhone silhouette, the Accordion spills over the right edge of the user iframe by about 20px.

I haven't investigated any further to figure out what exactly is going wrong here. Certainly Dojo didn't design a widget that looks wrong?? But maybe that's what's going on. When I try previewing, I see the same problem. Same problem if I get rid of the silhouette.

**Comment by doronrosenberg** [comment]
iphone.css

`.mblAccordionRoundRect {
    border: 1px solid #ADAAAD;
    border-radius: 8px 8px 8px 8px;
    margin: 7px 9px 16px;
    padding: 0;
}`

removing the margin fixes the issue.  Not sure why this exists...

**Comment by JonFerraiolo** [comment]
Maybe we should check with the dojo mobile guys and find out why those margins are there.

**Comment by doronrosenberg** [comment]
@peller might be able to get answers?

**Comment by ykami** [comment]
The same reason as the one for RoundRectList. Did you see the same problem with RoundRectList?

**Comment by doronrosenberg** [comment]
The issue is we are somehow setting width:100%
