### ISSUE TITLE
Local install on Windows/XP: get prompted for registration email

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3134]
@jhpedemonte 

I'm running the User Management tests, and at the end of those tests, I'm supposed to download local installs, unzip the zips, and trigger the launch scripts.

On Mac, when I clicked on the Register button, I was taken to a screen with 3 fields: username/email, password1, password2, but on Windows, I was taken to a "Request an account" screen with 1 field that asked for an email address to which the registration must go.

Maybe I didn't get the prompt on my Mac because I had completed the email-based registration previously???

Whatever, for local install, a user should be able to just create an account without any email activation. Is this feasible?

**Comment by jhpedemonte** [comment]
There are both "hosted" and non-hosted builds (the former say "hosted" in their name).  Sounds like you downloaded the "hosted" build, which uses email to authenticate the user.

Closing; reopen if my understanding is wrong.

**Comment by JonFerraiolo** [comment]
Yeah, that was probably it, I'm retesting now with non-hosted version
