### ISSUE TITLE
Style "migrate workspace" page

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3136]
Jon, if you have time, can you style the **migrate workspace** page which @childsb wrote?  Right now, it appears as a simple line with a couple of buttons, all positioned at the top left.  Should be consistent in style with the login page.

**Comment by JonFerraiolo** [comment]
I'm getting specs for the login screen soon. I'll work on migration page after I update the login screen.

**Comment by JonFerraiolo** [comment]
Besides waiting on login screen specs, I'll need to talk with @childsb and @jhpedemonte about migrate.html and migrate.js so I am sure I understand what's going on and what exactly is needed from me before making UI changes.

**Comment by childsb** [comment]
removed migrate workspace page
