### ISSUE TITLE
DateTimeBox - sometimes calendar pops up

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#314]
One user reports: "If I'm in editing mode and I select a DateTimeBox the
calender might pop up"

------- Comment #1 From Jon Ferraiolo 2010-09-19 21:55 [reply] -------

I think a calendar is supposed to pop up at _runtime_ when the user clicks on a
DateTimeBox widget. In daVinci, though, the overlay rectangle should be masking
this and capturing mouse events.

**Comment by peller** [comment]
unable to reproduce this
