### ISSUE TITLE
Post Orion-based nightly builds

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3140]
The builds posted to maqetta.org/nightly are still the old non-Orion builds.  Need to post the Orion-based builds there, once #2841 is fixed.

---

_old summary:_

@childsb 

When I downloaded a recent build from http://maqetta.org/nightly, there were 6 launch scripts. Should there be only 3? Also, why are there different downloads for different platforms in some scenarios, but only one ZIP download at http://maqetta.org/nightly?

I'm trying to understand things before I modify the README files

**Comment by jhpedemonte** [comment]
maqetta.org/nightly still contains the older, non-Orion build of Maqetta.  Still waiting on #2841 before posting Orion-based builds there.

Updating summary to "Post Orion-based nightly builds" (from "maqetta.org/nightly has old-style launch scripts").

**Comment by jhpedemonte** [comment]
Using the scripts from #2841 and it's working well.  One build from last night posted.  Closing this;  further discussion can happen in #2841.
