### ISSUE TITLE
Mac builds are ~13MB larger than others

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3142]
This will be obsoleted by fixing #2841, but until that time, worth investigating.

The Mac builds are ~120MB, but Linux and Windows builds are ~107MB.

**Comment by peller** [comment]
The tree diff. @jhpedemonte here ya go: http://pastebin.com/RaVsuJvR  All sorts of stuff, including launcher and other platform-specific dependencies.  Seems like a lot of that is UI code which we should not depend on for a headless server, perhaps lots of it coming from Orion

**Comment by JonFerraiolo** [comment]
Don't forget that the Orion UI appears in its full glory if you go to Open menu and issue an "Open Orion Navigator" command.

**Comment by jhpedemonte** [comment]
The [Orion/Mac builds](http://download.eclipse.org/orion/drops/R-0.5-201206221139/index.html) themselves are bigger than the other 2 platforms (39M vs 30M).

**Comment by peller** [comment]
@JonFerraiolo by ui, I'm thinking Eclipse client ui.  But perhaps the division isn't always as clear as it should be.  I see things like emf and batik, which I suppose could be used as client-side abstractions.  Maybe they in turn are coupled with client-side Eclipse plugins?

**Comment by JonFerraiolo** [comment]
> emf and batik

OK, I'll bet there is a whole ton of similar stuff that neither Maqetta nor Orion actually use.

**Comment by JonFerraiolo** [comment]
-> M8 Prio-Med

**Comment by peller** [comment]
possible dup of #3432

**Comment by jhpedemonte** [comment]
Closing.  Any remaining issues will be handled in #2841 and #3432.
