### ISSUE TITLE
Unable to "Add Maqetta Settings and Open" to bring up Maqetta from orion

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3150]
Unable to do step 6

Steps
1 Connect to a Maqetta/Orion instance. Navigate to the root of the server (as opposed to /maqetta/). This will bring up the Orion landing page.
2 Create a new user or login with an existing user.
3 Click the Navigator link in the upper left hand corner.
4 Create a new folder.
5 Under the folder you just created, create another new folder.
6 Click the twisty for the nested folder and select "Add Maqetta Settings and Open" to bring up Maqetta.
7 When maqetta opens, verify that the Maqetta default project files are there. Also verify that the proper project is open in the project drop down.
8 Open Sample1.html. Add a widget. Save/Preview/Then close.
9 In the Explorer view, click the Orion icon to go back to the Orion page.
10 Once Orion loads, click the Navigator link.
11 Expand folders until you're in the nested project created. Open Sample1.html and verify that the buttonw as added to the source.

**Comment by childsb** [comment]
I've replaced the "add maqetta settings and open" with just a "open in maqetta".  

'open in maqetta' will ad project settings if they dont exist.

**Comment by childsb** [comment]
TODO: Update test case to reflect changes
