### ISSUE TITLE
Editing review title causes loss of comments/annotations

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3154]
I created a review between 2 users and added comments/annotations.

Then I edited the review and changed the **Title**.  Since change didn't show in UI, I had to refresh for it to take.

Refreshed on both users and opened review again.  All comments/annotations are gone.

(Tested on Safari, secondary user on Chrome/Mac.)

@JonFerraiolo

**Comment by jhpedemonte** [comment]
According to the test plan, the title change should be reflected in the UI immediately after hitting **Publish** in the wizard, when editing the review.  So that's also an issue here.

**Comment by jhpedemonte** [comment]
Opened #3155 for UI refresh issue.

**Comment by aerwin** [comment]
Closing with above commit.
