### ISSUE TITLE
Reviews pane UI doesn't refresh as expected

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3155]
Seen in a couple of cases:
- Edit an existing review and change its **Title**.  Title doesn't change accordingly in the Reviews tree.
- Create a Draft Review.  Review tree should show item with "(Draft)" in title.  Edit draft review and **publish**.  Review tree still shows it as a draft.

May affect more scenarios, as well.

Tested on Safari.

**Comment by aerwin** [comment]
Just went out to see if this was still an issue on the server, but can't create a review (#3143). I don't think much can happen on this one until #3143 is resolved.

**Comment by aerwin** [comment]
I think the above commit should fix the problem, but will wait until deployed to a test server (with working email notifications) to test before officially closing.

**Comment by aerwin** [comment]
Closing... Tested on recently updated internal server, and appears my commit fixed things.
