### ISSUE TITLE
R&C: type ahead for e-mail address in 3rd panel of wizard can cause redirect to handle error page

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3157]
--> @aerwin

Was noticing this happening quite regularly on the internal test server, and then got it to happen reliably in my local by adding a Thread.sleep in the `GetBluePageInfo.java` part...
1. Open new review wizard
2. Start typing in the "add" text box, and see the following in console. In addition, Maqetta redirects to the handle error page 

```
Failed to load url=cmd/getBluePageInfo?searchname=a&start=0&count=10 message=Request canceled status=undefined 
```

I don't think there's actually any error here. There are no console or server exceptions, and it makes sense the type ahead would cancel unneeded queries that result from typing characters quickly.

**Comment by jhpedemonte** [comment]
Also see 8277 in our internal bugzilla.

**Comment by aerwin** [comment]
@jhpedemonte @peller @JonFerraiolo 

Does anyone know the `handleIoError` code in `Workbench` very well? 

It contains the following code (which I assume) is to not crap out on JSONP calls?

```
    // Filter on XHRs for maqetta server commands.  Possible values which we
        // test for:
        //     cmd/findResource
        //     ./cmd/createResource
        //     http://<host>/maqetta/cmd/getComments
        var reCmdXhr = new RegExp('(^|\\.\\/|' + document.baseURI + '\\/)cmd\\/');
        var url = deferred.ioArgs.url;
        if (!reCmdXhr.test(url)) {
            return;
        }
```

I'd like to add an exception for the soon to be renamed `getBluePageInfo` like so:

```
 // Filter on XHRs for maqetta server commands.  Possible values which we
        // test for:
        //     cmd/findResource
        //     ./cmd/createResource
        //     http://<host>/maqetta/cmd/getComments
        var reCmdXhr = new RegExp('(^|\\.\\/|' + document.baseURI + '\\/)cmd\\/');
        var url = deferred.ioArgs.url;
        if (reCmdXhr.test(url)) {
            // Make exception for "getBluePageInfo" because it regularly gets cancelled
            // by the type ahead searching done from the combo box on the 3rd panel of
            // the R&C wizard. The cancellation is not really an error.
            if (url.indexOf("getBluePageInfo") >= 0) {
                return;
            }
        } else {
            // Must not be a Maqetta URL (like for JSONP on GridX), so skip
            return;
        }
```

Does anyone know of a problem with that?

It would obviously be better not to hard code info about `getBluePageInfo` and perhaps we could look at some sort of command metadata in M8 (or some other time in the future).

**Comment by billreed63** [comment]
This looks good to me, we do have an open issue #1954 that is a dojo.xhr does not publish error on put/get when server is down. This may be something to keep in mind when dealing with this..

**Comment by aerwin** [comment]
Thanks, @billreed63 ... Closing with above commit.
