### ISSUE TITLE
Need to collect some identifying string from user during sign-up (e.g., first name, user id, etc.)

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3165]
--> @childsb 
--> Prio High (for evaluation at least)
--> M8

Follow-up to #2894

**Comment by jhpedemonte** [comment]
-> M9

**Comment by jhpedemonte** [comment]
Going to close this as "won't fix".  We already have an email.  Don't currently need more info.

@JonFerraiolo
