### ISSUE TITLE
Maqetta should show load indicator earlier

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#3168]
Example: create a new html file on maqetta-test.  Using Chrome, it can take 2 seconds before anything happens after confirming the dialog, sometimes longer.  We really should show the progress indicator/loading screen much earlier, or perhaps some other form of notification that things are happening (Gmail's little top centered loading messages for example).

This would be a relatively easy/low impact fix that would make maqetta more usable in slow conditions.

**Comment by JonFerraiolo** [comment]
-> @peller

**Comment by peller** [comment]
yeah, I think we had this working pretty well until we turned on async in the iframe, now stuff happens earlier...
