### ISSUE TITLE
Preview not working with Zazl and Eclipse projects 

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3171]
@rbackhouse 

When you create a new project in Maqetta, and turn on the "Elipse support" checkbox, we create a directory structure that is modeled after how Eclipse sets up web projects, where all of the web content goes into a `MYPROJECT/WebContent` folder instead of just going into the `MYPROJECT` folder.

To reproduce:
- Create a new project, make sure the "eclipse support" checkbox is checked
- Create New Desktop Application
- Add a Dijit Button
- Click on the preview-in-browser button

Result=> Button appears corrupted, and console has this message:

```
Failed to load resource: the server responded with a status of 500 (AST parsing error for [dijit/dijit] error : Unable to obtain source for Module [/maqetta/user/B/ws/workspace/eproj1/WebContent/main]) 
```

**Comment by rbackhouse** [comment]
The Zazl resource loader needs to know whether the project created is an eclipse one. I see no way currently in the code to find this out programmatically. Without this knowledge I don't know whether to strip one or two segments from the path.

**Comment by jhpedemonte** [comment]
@childsb, see @rbackhouse's comment above.

**Comment by rbackhouse** [comment]
It looks like I might be able to just look for the existence of the ".project" file in the project root.

**Comment by rbackhouse** [comment]
Using IUser.getResource(projectname+"./project") as an indicator works

**Comment by childsb** [comment]
.project is a pretty good indicator of an eclipse project, but we will have problems if our path calculation is based on if its an eclipse project.  having an eclipse project or not doesn't guarantee anything on the path.

for instance, i could have a regular project with folder1, and map dojo to /folder1/dojo or folder1/webcontent/lib/dojo

same goes for eclipse projects.  they may or may not have the WebContent folder.  They could also have nested subufolders.

users are free to map/move libraries to any directory or subdirectory within a project.  same goes for the location of raw HTML files.

**Comment by jhpedemonte** [comment]
@rbackhouse, so one thing to test with Zazl would be to remap Dojo (in **Files** view, click on the 3rd icon [Modify Libraries]) to something like `/lib/a/b/c/dojo` and see if it works.

@childsb, do you have a suggestion for a good solution?

**Comment by childsb** [comment]
I'd read the libs.settings ((or go through the library API)) to determine the path, then do relativity path math based on that.

**Comment by peller** [comment]
@rbackhouse fixed the Eclipse project issue.  Will open a new issue for modified libs, where the zazl filter does not inject zazl, but the preview still works.
