### ISSUE TITLE
Can't copy/paste a Tree or GridX within same document

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3172]
For both Mac/Firefox and Mac/Safari, I can't successfully copy/paste a Tree widget.
- New Desktop App
- Drag/drop a Tree, accept default values
- Copy
- Paste

Result=> Nothing gets copied. On Safari and Chrome, nothing in console, but with Firebug, there are some messages about undefined values.

**Comment by doronrosenberg** [comment]
Seems to be in TreeCreateTool::_loadRequires, so cc:@peller

**Comment by peller** [comment]
hrm.  this._data is an object, not an array, in this case.  We had this problem before... it's unfortunate we don't have a better definition for "data"

In this particular case, it seems that there's nothing to process for loadRequires.  Should we skip the map if this._data isn't an array?  Could check to see if this._data.map is truthy, and if not, pass [] or undefined to all()... might work to say `all(this._data.map && this._data.map(...))`

**Comment by aerwin** [comment]
Closing with above commit.
