### ISSUE TITLE
Last column table cells can become unreachable

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3173]
(I'm using Win/FF)

Setting to M7 Prio-High just to evaluate, I wouldn't be surprised if we have to defer to M8.
- New Desktop App
- Add a table, accept defaults (i.e., 2x2 table)
- Double click on top/left table cell, enter "red1"

Result=> column 1 takes up nearly the entire width of the page canvas. I couldn't click into a cell in the second column. Only way I found to select a cell in second column was via Outline palette.

**Comment by aerwin** [comment]
@JonFerraiolo 

Closing with above commit... Two parts to this fix: 
- Switched to using &nbsp; instead of &#8288; for empty table cells
- Default table-layout to "fixed" instead of "auto"
