### ISSUE TITLE
Download dialog polish

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3178]
The Download workspace dialog (from the Files view) could use some polish:
1. Add links to select all/none of the libraries, enabling/disabling all of the checkboxes.  Just something like:  `Select:  _all_ / _none_`.  Placed right under the list of libraries.
2. Move the 2 options (Dojo Web Builder and Full Source) below the list of libraries (and below the select all/none).  Put the checkboxes first and the text to the right of the checkboxes.
3. The options checkboxes are styled differently than the library checkboxes.
4. "Download Full Source" isn't a good way to describe this feature.  Maybe something like "Download unbuilt source for libraries (if available)."  Maybe @JonFerraiolo can word-smith it.

**Comment by jhpedemonte** [comment]
Reopening.

I think this regressed the hiding of libraries.  Now, I see DojoThemes, maqettaSamples, and maqetta libraries, all of which were hidden by @childsb's fix to #2769.

**Comment by peller** [comment]
I was also going to suggest changing the wording for "download full source"  Perhaps download unoptimized sources or download unoptimized sources, where available?

**Comment by doronrosenberg** [comment]
@childsb @jhpedemonte Hmm, looking at the json libs array there is nothing that says if it should be skipped or not.  Don't think this casued it.

**Comment by JonFerraiolo** [comment]
@peller 

How about these two changes:
1. Replace `Download Full Source` with `Download full uncompressed source for selected libraries`. I guess I'm thinking along the same lines as Adam, where the release downloads are named something like `dojo-release-1.8.0` and the source downloads are named something like `dojo-release-1.8.0-src`. On the Dojo download page, these words are used: "A full, uncompressed source release of the Dojo Toolkit"
2. Let's move the checkbox for `Download full uncompressed source for selected libraries` above the "experimental web builder" checkbox.

Which brings us to the question - does it still make sense to include the "experimental web builder" checkbox?

**Comment by JonFerraiolo** [comment]
@peller: does it still make sense to include the "experimental web builder" checkbox?

**Comment by peller** [comment]
The word "full" doesn't do anything for me.  In the Dojo download, perhaps it's referring to the fact that the entire toolkit is included... we do this whether or not this checkbox is checked, and the box applies to any library with a source property, not just Dojo.  Is "uncompressed" sufficent?

The experimental web builder is orthogonal to this (and not fully working)  I suggest leaving it there.

**Comment by jhpedemonte** [comment]
I take it back: the libs are properly hidden in today's builds.  The [other issues](https://github.com/maqetta/maqetta/issues/3178#issuecomment-8196868) still stand.

**Comment by JonFerraiolo** [comment]
Then how about `Download uncompressed source for selected libraries` (i.e., remove the word "full")?

**Comment by peller** [comment]
+1

**Comment by jhpedemonte** [comment]
I would also add in "(if available)", since we only have this option for Dojo and GridX.  So:

> Download uncompressed source for selected libraries (if available)
