### ISSUE TITLE
CSS/JS editors move Files/Reviews tabs to top of left pane

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3180]
When I created a CSS editor, I was confused that I didn't see the Files/Reviews tabs at the lower left.  Turns out they moved to the top left.  Also happens for JS editors.

This is jarring to the user, who expects those to be in the lower left.  The Files/Reviews tabs **should always stay at the lower left**, even if we don't have a Palette and Outline.

This behaviour also leads to a bug:
1. Open a CSS editor.
2. Open a JS editor.
3. Open an HTML editor.
4. With the HTML editor at the front, click to open the Files view.
5. Click on the JS editor tab.  Notice that there is an empty Palette at the top and the Files/Reviews tabs stay at the bottom.
6. Click on the CSS editor tab.  Notice that the left pane closes and the Files/Reviews tabs move to the top.

@JonFerraiolo

**Comment by jhpedemonte** [comment]
Reopening.  Wrong bug number in commit.

**Comment by aerwin** [comment]
@jhpedemonte @JonFerraiolo 

Per scrum, we agreed to leave behavior as is for at least another day to give folks a chance to experience it a little more.

In meantime, I can look into the bug @jhpedemonte lists at bottom.

**Comment by aerwin** [comment]
Above commit fixes the 2nd part of this defect.

**Comment by aerwin** [comment]
We discussed this at today's scrum, and decided to leave the current behavior (moving the Files/Review palette to top for certain editors) in place for M7. 

We can certainly re-evaluate in the future if folks complain about the behavior, but for now I don't think there are any open defects/issues. So, closing.
