### ISSUE TITLE
Can not set background color in theme editor 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3182]

**Comment by jhpedemonte** [comment]
Need more info:  which widget, which theme?

**Comment by billreed63** [comment]
All themes, broken by commit 325e12a6b10c40fd7d1cf0328b0063905564d170

**Comment by jhpedemonte** [comment]
@doronrosenberg, your fix may have broken this.

**Comment by billreed63** [comment]
fixed by commit b5d54705484038f63d62ffd4a6964d95123de5dc

**Comment by doronrosenberg** [comment]
Crap, thanks for fixing this.  I need to stop coding so late.

**Comment by billreed63** [comment]
No worries, cascade is a bit of a mystery to me.... It is not evident that is used my theme editor also...
