### ISSUE TITLE
main menu : new sketch not working

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#3185]
1) login to maqetta
2) create---> sketch (high or low fidelity yields same result)
3) add dojo controls to the page, or look at the current theme.  notice it's claro and not sketch.

**Comment by jhpedemonte** [comment]
@billreed63, related to the Cascade.js issue?

**Comment by jhpedemonte** [comment]
Closing.  This is working for me with latest builds.

@childsb, **Sketch (high fidelity)** uses Claro, while **Sketch (low fidelity)** uses the sketch theme.
