### ISSUE TITLE
Exception when using JSONP in Gridx

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3187]
Using Widgets Gridx basic test case.

Data from URL (JSONP)

Steps
Continuing from the test case above, open the HTML File from the Data from workspace test case.
Double click on the GridX Widget in the design view to display the smart input.
SmartInput is displayed. Choose Data from URL (JSONP) from the drop down list on the first panel.
In the text area enter the following URL: http://maqettaservice.appspot.com/sampleservice
Click the Finish button on the wizard.
The GridX should be updated with the data from the service. Notice that the data is displayed with HTML tags rendered (for example Fruits).
Save and close the file.
Reopen the file
Click on the preview icon in the toolbar, this should open a new browser window and the grid should be displayed with the data from the service.

I see the following error FF/Win7  http://maqetta-app-test.austin.ibm.com/maqetta/

TypeError: (doc || win.doc).getElementById is not a function
[Break On This Error]   

...);var _350=_33a(_34e,{el:1});var qt=_34e.tag;var _351=("*"==qt);var ecs=_300()["...

dojo.js (line 15)

TypeError: (doc || win.doc).getElementById is not a function

**Comment by aerwin** [comment]
Closing. Dup of #2910.
