### ISSUE TITLE
Forgot password UI flashes then disappears

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3190]
@childsb @jhpedemonte 

Where is the UI for people who forget their password? Our login screen looks like this:

![current Maqetta login screen](http://i.imgur.com/Im599.png)

Note that for a brief moment the words "forgot password" appear on the screen, but then they go away

Note that it is common for sites to include a forgot password link right there next to the login/password fields:

![login screen with forgot password](http://i.imgur.com/DlvKQ.png)

**Comment by jhpedemonte** [comment]
@childsb, didn't you hide/remove some elements from that screen?

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte 

I'm testing on `maqetta-app-test`

I looked at the code in LoginWindow.js (which is duplicated in 2-3 different projects) and here is the code that makes the "forgot password" UI disappear:

```
        checkemailrequest.onreadystatechange = function() {
            if (checkemailrequest.readyState === 4) {
                if (checkemailrequest.status === 200) {
                    var responseObject = JSON.parse(checkemailrequest.responseText);
                    if (responseObject.emailConfigured === false) {
                        document.getElementById("resetUserLink").style.display = 'none';
                    }

                }
            }
        };

        checkemailrequest.open("POST", "../useremailconfirmation/cansendemails", true);
        checkemailrequest.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        checkemailrequest.setRequestHeader("Orion-Version", "1");
        checkemailrequest.send();

```

I figure you and @childsb would know more about this than me.

**Comment by jhpedemonte** [comment]
-> @childsb, I don't know this code.

**Comment by jhpedemonte** [comment]
I don't see this any more, after brad and Jon's latest changes.  Closing.
