### ISSUE TITLE
Zazl error with GridX

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3193]
Tested on maqetta-test.  I dropped GridX on a page, taking defaults, then did a Preview.  It showed up fine, but I did see these errors in the server log:

```
INFO: AST parsing [dojox/data/CsvStore] using the Rhino AST API
Aug 30, 2012 3:39:12 PM org.dojotoolkit.optimizer.amd.rhinoast.AMDJSOptimizer scanForCircularDependencies
INFO: Circular dependency found : dijit/dijit->dijit/_base->dijit/a11y->dojo/dom-attr->dojo/dom-prop->dojo/dom-construct->dojo/dom-attr
Library file not found! :WebContent/dojo-src/gridx/core/model/Model.js
Library file not found! :WebContent/dojo-src/gridx/core/Row.js
Library file not found! :WebContent/dojo-src/gridx/core/Column.js
Library file not found! :WebContent/dojo-src/gridx/core/Cell.js
Library file not found! :WebContent/dojo-src/gridx/core/_Module.js
Library file not found! :WebContent/dojo-src/gridx/core/Core.js
Library file not found! :WebContent/dojo-src/gridx/core/model/_Extension.js
Library file not found! :WebContent/dojo-src/gridx/core/model/extensions/Query.js
...
```

_(Thought we already had a bug for this, but can't find it.)_

@peller

**Comment by rbackhouse** [comment]
The Zazl Resource Loader takes all the configured Libraries that have a non null value for their source attribute and attempts to load the required resources from them. The messages occur because the gridx resouces are first looked for in the dojo library are not found.

**Comment by jhpedemonte** [comment]
So when trying to load the GridX sources, it'll first go through (for example) Dojo, HTML, Shapes, etc libraries, appending the required resource to the base path of each lib, until it finds one that works?

**Comment by rbackhouse** [comment]
Only the Libraries that have their source attributes set are searched. At the moment that is dojo and gridx. The IUser.getResource() API is used for the others.

**Comment by peller** [comment]
-> M8 prio med

So should Zazl be able to search according to the packages config, which associates namespaces with the paths? This is not going to make any significant difference in performance.  While it's unlikely, I suppose there could be some ambiguity if we don't search the correct path?

**Comment by peller** [comment]
don't see the error anymore
