### ISSUE TITLE
We lost README.html, LICENSE and build.level from downloadable ZIP

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3196]
@childsb  @peller 

With the switch to the ORION server, we lost the README.html, LICENSE and build.level files that used to be included in ZIP downloads. Instead of our LICENSE file, there is a notice.html file which includes boilerplate legalese from Eclipse Foundation.

@childsb - Regarding README.html and LICENSE, is that solved by simply putting appropriate copies of those files into folder `releng/davinci.releng/orion/builder/scripts/'? Will they get included in the ZIP by simply being in that folder?

@childsb, @peller, @jhpedemonte - Do you know what the build.level file did in previous releases? It holds a commit number. Maybe it was never used in previous releases?

Regarding the LICENSE file(s), we need to figure out how to reference the licensing terms for the various modules used in M7, including Orion, gridx and zazl. (gridx is dojo licensing, right?)

**Comment by peller** [comment]
I think build.level may have been used back in our appcache fishing expedition.  Don't think it's needed anymore.

**Comment by peller** [comment]
gridx and zazl use the standard dojo dual license, correct.  Gridx has a LICENSE file at its web root.  @rbackhouse  Zazl doesn't seem to include a copy of the LICENSE file in optimizer-release.

**Comment by jhpedemonte** [comment]
-> @childsb, since he knows the build better than I.

**Comment by JonFerraiolo** [comment]
-> @peller 

Here is my list of things to do:
1. Make sure our LICENSE file (from davinci.product) is in the new Orion build folder (`releng/davinci.releng/orion/scripts/builder`)
2. Tweak LICENSE to say that licensing information for some technologies used in Maqetta can be found in the `licenses/` folder
3. Move `notices.html` into `licenses/Eclipse-Orion-notices.html`
4. Research ZAZL dependencies and put either plain text or HTML files into `licenses/` for whatever ZAZL dependencies we need to mention

**Comment by peller** [comment]
I suggest we go with the strategy of including LICENSE files in each plugin (directory or jar)  That's what Orion does, explicitly mentioning it in their readme.  We need to get our top-level README/license info copied over to the build as well.  Currently, there's just Eclipse launcher info there.

@childsb
