### ISSUE TITLE
Where is users/ folder for local install?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3197]
@jhpedemonte @peller 

The launch scripts found in the downloadable ZIP files echo a message that says:

```
Using directory: <INSTALLDIR>/users
```

but I'm pretty sure that's not actually happening, and instead user workspaces are going into `<HOMEDIR>/maqetta-workspace`

Whatever, the message should be accurate with what's actually happening.

(I think it's best to put the users/ folder within the installation area. That way users can segregate their work between different versions of Maqetta, which might be particularly important for people who want to work with nightly builds, which aren't always stable and might wipe out all of the work.)

**Comment by childsb** [comment]
closing per checkin
