### ISSUE TITLE
Error when downloading Eclipse project

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3199]
Running **Tests > Eclipse Project > Create and Download Eclipse Project** on maqetta-test.

Clicked to download workspace, keeping defaults.  Clicked download and broke in debugger.  Workspace did not download.

Stack:
- Theme.isThemeHTML
- obj.rewriteUrls
- obj.rewriteUrls
- obj.okButton

Broke on the line `return _1b00.getName().indexOf("dojo-theme-editor.html") > -1;`, where `_1b00` was null.

@billreed63

**Comment by childsb** [comment]
I can't recreate this. Tried local/build w/firefox and chrome.

**Comment by jhpedemonte** [comment]
-> @doronrosenberg, please try to recreate.  Close if unable.

**Comment by doronrosenberg** [comment]
Cannot reproduce, closing.
