### ISSUE TITLE
M7 release notes

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3200]
I created a skeleton file, but need to write all of the content. Note: there is a lot to talk about with this release!

**Comment by JonFerraiolo** [comment]
Release notes are complete except for migration notes. 

Sending to @aerwin who I believe was going to update the release notes around one of our migration issues. @aerwi:
- Please add your updates to bottom of release7.html
- Please remove the red-colored note about under construction
- After complete, please reassign to @jhpedemonte to add other migration notes as appropriate

**Comment by aerwin** [comment]
@JonFerraiolo  wrote

> After complete, please reassign to @jhpedemonte to add other migration notes as appropriate

So, with my commit and note above, reassigning to @jhpedemonte .

**Comment by jhpedemonte** [comment]
-> fixed.
