### ISSUE TITLE
Button width change on instance impacts calendar width

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3201]
Create new HTML page
Add a button
set the class of the button to 'myclass'
set the width in the layout properties panel to 300px
drag a calendar on to the page
the calendar has a non-standard width, apparently the button in the calendar is 300px, even though the class 'myclass' is not involved.  The rule established in app.css looks like this:

```
#myapp.claro .myclass.dijitButton .dijitButtonNode, .claro .dijitDropDownButton .dijitButtonNode, .claro .dijitComboButton .dijitButtonNode, .claro .dijitToggleButton .dijitButtonNode {
    width : 300px;
}
```

Also, I noticed the following error on the console when establishing the 300px wide button, somewhere in davinci.js:

```
TypeError: 'undefined' is not an object (evaluating 'xpath.charAt') 
```

**Comment by billreed63** [comment]
The issues is the myapp should only be applied to the one rule. the dijitDropDownButton also gets the rule..
