### ISSUE TITLE
JSON parse error on bad password

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3202]
At the main login screen, enter a bad password.  A parse error occurs and is printed on the console.  Nothing appears on the screen to indicate that the password was incorrect.

```
POST http://maqetta-app-test.austin.ibm.com/login/form 403 (Forbidden)
LoginWindow.js:202SyntaxError: JSON Parse error: Unrecognized token '<'
```

I'm pretty sure I filed an issue on this, but can't find it.

See also #1950

**Comment by childsb** [comment]
Issue was in an integrated plugin and not base code.  Fixed in integrated plugin, closing issue.
