### ISSUE TITLE
Add to Maqetta and Open option missing in Orion Navigator

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3203]
Might be good if top-level folders got all the Maqetta stuff automatically when created, since a user might launch Maqetta and try to switch to those projects whether or not an action is selected from a menu.  Perhaps we'd just have an "Open in Maqetta" action instead?

**Comment by childsb** [comment]
I had upgraded my workspace to latest Orion code.  They've changed their service provider registration to:

```
provider.registerService('orion.navigate.command', {
```

where i was using

```
provider.registerServiceProvider('orion.navigate.command', {
```
