### ISSUE TITLE
Orion navigator automatically add maqetta files to new top-level folders

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3209]
Rather than adding maqetta behavior to a new folder when it is opened from the navigator using a special action, it would be preferable to have the dot files, etc., added to the folder upon creation.  Otherwise, a user could go directly to maqetta and see new projects which do not function.

see #3203

**Comment by jhpedemonte** [comment]
I'm a bit confused.  I thought the point of this functionality was that a user could create a folder ("project") in Orion, then select **Open in Maqetta**, which would add the Maqetta-required files (if not already present) before opening up in Maqetta.

So in that scenario, "creation" happens in Orion -- it wouldn't make sense to add Maqetta files then.

**Comment by peller** [comment]
When the user creates a top-level folder, it immediately becomes available as a project in Maqetta, whether you open from the navigator or not.  Trying to switch to that project will presently result in an error if you didn't open it directly from the navigator page using that special option...

So, I'd suggest either somehow having the navigator add the special files, or having maqetta add them when opening the project, without asking the user to do anything special or navigate a special way.

**Comment by jhpedemonte** [comment]
> ... having maqetta add them when opening the project ...

Ah, I understand now.  Yes, agreed with the quoted proposal.

**Comment by jhpedemonte** [comment]
With the latest code, if a user switches to a "project" which is really just an empty dir, Maqetta will copy in the necessary files.  So no error.
