### ISSUE TITLE
HTML table columns change size on TD data entry on Chrome

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3211]
--> @aerwin 

@JonFerraiolo 

Found in conjunction with @JonFerraiolo at the same time as #3210, in Chrome (despite having table-layout set to "fixed") that table columns are changing size as TD contents are updated via TD smart input. The resizing clears up if you reload the page. This does not happen in FF.

**Comment by aerwin** [comment]
@JonFerraiolo 

I had really good initial luck using the stuff I put in for sliders to refresh the parent on props change (e.g., turn on `refreshParentOnPropChange` in widgets.json for TD, TR, and TBODY elements) to fix the core problem.

But, now the selection chrome is off on the TD that got the new data (small box in corner). Really not sure on this one. Would almost have thought the wrong element was selected (like a stale copy of the TD), but changing background in widgets palette updates right cell, the outline selection is correct, etc.

So, not sure about fixing this for M7 at this point...

![GitHub Logo](http://i.imgur.com/r0Myz.png)

**Comment by aerwin** [comment]
@JonFerraiolo @jhpedemonte 

--> M8

**Comment by JonFerraiolo** [comment]
@aerwin - If you need help with selection chrome problem, I wrote most of that code.

**Comment by billreed63** [comment]
Sending to  @JonFerraiolo   (Master of chrome selection) you can send back if you would like
