### ISSUE TITLE
Smart input OK button can indicate ready for mouse clicks, but then ignore them

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3217]
@doronrosenberg @billreed63 @JonFerraiolo 

This has started to annoy me quite a bit... happens in both Chrome and Firefox on Mac, but might be easier to cause in Firefox...
1. Open up smart input on widget like Button, ComboButton, etc.
2. Mouse over the OK button to click and clicks will often be ignored... in playing around a little bit, it seems to happen when mouse pointer is too close to the edge of the button, but far enough in to highlight the button.

Screen shot below from Firefox with focus highlight (mouse didn't make it through screenshot process). In this state, I can just click and click and click, and nothing happens until I move mouse into the center and click again.

![GitHub Logo](http://i.imgur.com/nhly8.png)

Making Prio High as a start because while doesn't break anything, makes it seem like something is broken...

**Comment by jhpedemonte** [comment]
-> @doronrosenberg, have any ideas?

**Comment by JonFerraiolo** [comment]
My first three guesses as to what's going wrong: (1) something happened in dojo 1.8, (2) there are a number of floating invisible DIVs in the page editor and maybe one of them is causing trouble, (3) maybe the mousedown handler on the blue DIV under the buttons is grabbing the event for some reason.

@billreed63

**Comment by doronrosenberg** [comment]
The issue is actually a coding bug - we are listening for click events on the domNode rather than on the dijit
