### ISSUE TITLE
SmartInput exception

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3222]
@doronrosenberg @peller 

I've seen this exception multiple times during the past few months, and I'm getting it today using latest code running from Eclipse. Upon clicking OK on SmartInput, I'm getting a Dojo exception at _ButtonMixin.js:44 at this line:

```
if(!preventDefault && this.type == "submit" && !(this.valueNode||this.focusNode).form){ // see if a non-form widget needs to be signalle
```

because the OK button has `type="submit"` and in that scenario Dojo is attempting to reference to a `form` property on either `this.valueNode` or `this.focusNode` and both are undefined.

Here is the stack trace:

```
declare._onClick (_ButtonMixin.js:44)
inherited (declare.js:189)
declare._onClick (Button.js:64)
lang.hitch (lang.js:373)
handles (a11yclick.js:84)
```

What I was doing at the time:
- New mobile application
- Add a View, and in the View, I had a Heading, a couple of HTML buttons, and then a 2x2 HTML table
- I double-clicked on one of the table cells, entered "aaa", and then clicked OK on the SmartInput popup.

**Comment by JonFerraiolo** [comment]
I poked into this some, and I believe what's wrong is that the `dijit.form.Button` widget for the OK button somehow isn't getting its attachpoints processed. 

On the widget object (the button widget object), the property `this._attachPoints` is an empty array, whereas for other similar "submit" buttons this array with have roughly 5 entries. Furthermore, `this.valueNode` doesn't exist, whereas for other similar "submit" buttons, there is a `this.valueNode` and it points to the INPUT node within the generated DOM tree for the Button.

SmartInput.js creates the OK button by doing a `widget.set("content", ...)` command at either line 357 or 360:

```
            this._inline.set("content",t);
```

The textual content `t` does cause the INPUT node to have attribute `data-dojo-attach-point`. When I check the DOM tree for the OK button, I see this in the debugger;

```
<input type="submit" value="" class="dijitOffScreen" tabindex="-1" role="presentation" data-dojo-attach-point="valueNode">
```

The Dojo parser must be running because the Button looks like a dijit button when it appears on the screen, but I don't know what the attachpoints aren't processed properly.

**Comment by JonFerraiolo** [comment]
See #3240

**Comment by JonFerraiolo** [comment]
Somehow I forgot to set milestone and priority! -> M7 Prio High

**Comment by billreed63** [comment]
sending to @doronrosenberg
