### ISSUE TITLE
Infinite loop when switching mobile themes

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3224]
@doronrosenberg @peller @jhpedemonte 

On Mac/Chrome running from Eclipse, the page editor goes into an infinite loop when changing mobile themes. Sometimes it takes a couple of "switch themes" to trigger the infinite loop.
- Clone custom into custom2 or whatever
- Change background color to red
- Cllck the save button
- Create new mobile application, choose smallest android device
- Add a ScrollableView
- Switch themes to custom2

Result=> every second or so the page flashes. It looks like there is an infinite loop in updating the themes. I noticed this when I was seeing an exception in outline palette (which is a totally a separate issue), but what I noticed is that the `_pageRebuilt()` function in OutlineView.js keeps getting called over and over again. This method is listening to the `/davinci/ui/context/pagerebuilt` event.

When I first started to play with this, I didn't get the infinite loop with the first try. So, if the above sequence doesn't cause the infinite loop, try to repeat the switch themes operation back-and-forth between the new custom theme and the "default themes".

**Comment by peller** [comment]
I was trying to remember the source of the pagerebuilt code, but haven't yet tracked it down in github, as it was merged manually here: 047b1315

**Comment by aerwin** [comment]
Sounds same as #3167?

**Comment by billreed63** [comment]
dup #3167
