### ISSUE TITLE
Extra copy of *.js files in maqetta.core.client build

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3226]
It looks like the code temporarily copied into the maqetta.core.client plugin may not be deleted.  On the app test server, I noticed:

```
# ls plugins/maqetta.core.client_1.0.0.201209021127/WebContent/release/dojo
build-report.txt  davinci  dijit  dojo  dojox  orion  preview  system

# du -s plugins/maqetta.core.client_1.0.0.201209021127/WebContent/release/
53588   plugins/maqetta.core.client_1.0.0.201209021127/WebContent/release/
```

**Comment by aerwin** [comment]
@peller 

Yes, downloaded the driver and see a release folder in core.client. I didn't have anything to do with building core.client, so I'll have to go find that build script. What prio/sev would you put on this?

**Comment by aerwin** [comment]
--> @peller 

Per ST, sending back to @peller .
