### ISSUE TITLE
What happened to FixedSplitterPane?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3227]
@jhpedemonte @peller 

What happened to FixedSplitterPane? We had it in M6 and I don't see it in M7

**Comment by doronrosenberg** [comment]
http://dojotoolkit.org/reference-guide/1.8/dojox/mobile/FixedSplitterPane.html

```
FixedSplitterPane is a pane widget that is used in a dojox.mobile.FixedSplitter. It is a widget, but can be regarded as a simple <div> element. In V1.8, this widget was deprecated and replaced by dojox.mobile.Container.
```

1.8 dojox.mobile did a lot of renaming/deprecation so there would be more reuse.
