### ISSUE TITLE
Download ZIP install - no login screen

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3233]
@peller @jhpedemonte 

I pulled down last night's ZIP from maqetta.org/nightly and the software does not show the login screen upon startup and instead goes immediately into the application.

Is this by design? I swear that last week all versions of Maqetta (download or otherwise) showed the login screen at startup.

**Comment by jhpedemonte** [comment]
-> M8

**Comment by JonFerraiolo** [comment]
Closing. The nightly builds include Orion now and post a login screen.
