### ISSUE TITLE
Mobile themes in theme editor don't look right

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3236]
@billreed63 

Using FF on Mac going to moketta...

See theme editor below with cloned iPhone theme. E.g., button's not an arrow and colors are off:

![GitHub Logo](http://i.imgur.com/wlI5L.png)

Compare to iphone rendering in page editor:

![GitHub Logo](http://i.imgur.com/6EEge.png)

**Comment by billreed63** [comment]
We do not support mobile theme editing in FF M8, this is due to the way dojo deals with non webkit browsers

issue #2372 deals with this.

**Comment by jhpedemonte** [comment]
Do we warn the user about this any where?

@JonFerraiolo

**Comment by aerwin** [comment]
Wondered about that too... don't think we warn our team about it either... e.g., wouldn't have wasted time with FF testing of mobile theme editor had I known of this limitation... e.g., be nice to include in test plan or test matrix info.
