### ISSUE TITLE
Mobile theme editor: selection chrome leaves widget when scroll

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3239]
@billreed63 @JonFerraiolo 

Using FF on Mac going to moketta..
1. Clone theme
2. Select heading background, and see selection chrome is right:

![GitHub Logo](http://i.imgur.com/GzXpG.png)
1. Scroll the theme editor and see selection chrome has moved off widget:

![GitHub Logo](http://i.imgur.com/D0tMm.png)

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo (me)
