### ISSUE TITLE
Auto-migration issues

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3242]
Issues:
- ~~"dojo" and "gridx" libraries were disabled after migration.~~
- Samples are migrated, but also show up as read-only _samples_ directory.
- ~~Mobile page [doesn't load theme](https://github.com/maqetta/maqetta/issues/3242#issuecomment-8277964).~~
- Files added outside of WebContent folder in Eclipse project:  [[1](https://github.com/maqetta/maqetta/issues/3242#issuecomment-8278121)] ~~and [[2](https://github.com/maqetta/maqetta/issues/3242#issuecomment-8278305)]~~
  - See #3284 in regards to [1]
- ~~[Failure](https://github.com/maqetta/maqetta/issues/3242#issuecomment-8278786) loading custom theme.~~
- ~~Error when [creating project](https://github.com/maqetta/maqetta/issues/3242#issuecomment-8279504).~~
- [No action](https://github.com/maqetta/maqetta/issues/3242#issuecomment-8296895) with _Open in Maqetta_ with migrated project.  => #3262

**Comment by JonFerraiolo** [comment]
This is likely a result of "dojo" and "gridx" having to be manually added in our current testing scenario, but I'm seeing two filter fields in the Widgets palette:

![Two search fields](http://i.imgur.com/JzF8n.png)

**Update:** This is #2712.

**Comment by jhpedemonte** [comment]
Yes, that's a known issue.

**Comment by JonFerraiolo** [comment]
@billreed63 

Whereas my simple mobile page using default themes works fine, my simple mobile page WITH A CUSTOM MOBILE THEME doesn't load its CSS themes properly after migration:

![Mobile themes not loading on migrated file](http://i.imgur.com/SY5xz.png)

**Comment by doronrosenberg** [comment]
Custom theme or built in theme?

**Comment by JonFerraiolo** [comment]
Custom theme (I amended my note above).

**Comment by jhpedemonte** [comment]
For Eclipse project, _app.css_ and _app.js_ get added outside of _WebContent_ folder:

![eclipse](http://i.imgur.com/JPIU9.png)

**Comment by JonFerraiolo** [comment]
Poorly formed back arrow on Heading widget in previewer when running Mac/Chrome on a migrated file.

![Poorly formed back arrow on Heading widget](http://i.imgur.com/RoZXX.png)

@peller (UPDATED) When I change the URL bar to set zazl=false, then arrow renders correctly. Looking in the debugger at various CSS rule defintions, I see that various classnames that are mixed case without zazl (e.g., .mblToolBarButtonText) end up as all lower-case when zazl is active (e.g., .mbltoolbarbuttontext). I don't know CSS rules about case very well, but I suspect that WebKit's inheritance logic requires exact case-sensitive class name matches.

**Comment by jhpedemonte** [comment]
After migration, loaded Eclipse project, then had to modify libs in order to re-enable "dojo" and "gridx".  After refreshing the page, _lib_, _samples_ and _themes_ folders were now outside of the _WebContent_ directory:

![eclipse](http://i.imgur.com/ohGra.png)

After this, cannot load files from this project.

**Comment by jhpedemonte** [comment]
Tried to open Theme Editor for a custom theme of "custom".  I got an error trying to load `/app/static/lib/dojo/1.7/dojo/dojo.js`, followed by an error that `require is not defined`.  @billreed63

**Comment by jhpedemonte** [comment]
No reviews were carried over for me.  Assuming this is what we want for M7. (Might be a different issue in later milestones).

**Comment by aerwin** [comment]
Error in console on migration page:

```
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must to be declared in the document or in the transfer protocol.
```

Using FF on Mac.

**Comment by JonFerraiolo** [comment]
Yeah, I can't successfully open any of the migrated files that were in an Eclipse project, even after attempting to tell the Modify Libraries pane where Dojo needs to go (i.e., ./WebContent/lib/dojo)

**Comment by aerwin** [comment]
Didn't take me to my last project (e.g., I was taken to "project1" instead of the one I just created before migration).

**Comment by aerwin** [comment]
Error in console trying to open file in "project1" and page just spins:

```
Error opening editor for filename: ./project1/file1.html

TypeError: _224c.getLibrary(libId) is undefined
```

using FF on MAc

**Comment by jhpedemonte** [comment]
> `_224c.getLibrary(libId) is undefined`

@aerwin, that probably means it's trying to find a disabled library.  Check "Modify Libraries" dialog.

**Comment by aerwin** [comment]
@jhpedemonte you're correct. thanks :)

**Comment by jhpedemonte** [comment]
After migration, couldn't create another project.  Got this in server log:

```
2012-09-04 16:23:38.460 [qtp1033806195-117] WARN  o.e.jetty.servlet.ServletHandler - /maqetta/cmd/createProject
java.lang.NullPointerException: null
    at java.lang.String.compareTo(String.java:1176) ~[na:1.6.0_24]
    at maqetta.server.orion.VOrionWorkspaceStorage.get(VOrionWorkspaceStorage.java:95) ~[na:na]
    at maqetta.server.orion.VOrionWorkspaceStorage.createProj(VOrionWorkspaceStorage.java:49) ~[na:na]
    at maqetta.server.orion.VOrionWorkspaceStorage.create(VOrionWorkspaceStorage.java:38) ~[na:na]
    at maqetta.server.orion.VOrionStorage.newInstance(VOrionStorage.java:212) ~[na:na]
    at maqetta.core.server.user.User.addBaseSettings(User.java:209) ~[na:na]
    at maqetta.server.orion.user.OrionUser.createProject(OrionUser.java:174) ~[na:na]
    at maqetta.core.server.user.User.createProject(User.java:154) ~[na:na]
    at maqetta.core.server.command.CreateProject.handleCommand(CreateProject.java:23) ~[na:na]
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:52) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
```

**Comment by aerwin** [comment]
Error opening mobile page in Eclipse project using FF on Mac:

```
resource.findResoure: Folder preMigM7_Eclipse_20120904/WebContent/themes not found
findResource(name=

"*.theme"

, _2a55=

true

, _2a56=

undefined

, _2a57=

undefined

)davinc...vision@ (line 58926)
getThemes(base=

"preMigM7_Eclipse_20120904"

, _2ab9=

undefined

, _2aba=

undefined

)davinc...vision@ (line 59377)
loadTheme(_229a=

undefined

)davinc...vision@ (line 48268)
(?)()davinc...vision@ (line 48312)
_447(_448=

[

undefined

, function(), 

undefined

]

, type=

1

, _449=

[

[]

, 

undefined

, 

undefined

]

, _44a=

undefined

)dojo.j...vision@ (line 5518)
then(_462=function(), _463=

undefined

, _464=

undefined

)dojo.j...vision@ (line 5628)
_setSource(_22a2=Object { elementType=

"HTMLFile"

, startOffset=

0

, endOffset=

2516

, more...}, _22a3=function(), scope=Object { _pageEditor={...}, contentPane=[Widget dijit.layout.ContentPane, dijit_layout_ContentPane_10], silhouetteiframe={...}, more...}, _22a4=

undefined

)davinc...vision@ (line 48313)
_setContentRaw(_1c39=

"preMigM7_Eclipse_201209...tent/folder1/file1.html"

, _1c3a=Object { elementType=

"HTMLFile"

, startOffset=

0

, endOffset=

2516

, more...}, _1c3b=

undefined

)davinc...vision@ (line 39266)
_setContent(_1c36=

"./preMigM7_Eclipse_2012...tent/folder1/file1.html"

, _1c37=Object { elementType=

"HTMLFile"

, startOffset=

0

, endOffset=

2516

, more...}, _1c38=

undefined

)davinc...vision@ (line 39245)
setContent(_1c30=

"./preMigM7_Eclipse_2012...tent/folder1/file1.html"

, _1c31=Object { elementType=

"HTMLFile"

, startOffset=

0

, endOffset=

2516

, more...}, _1c32=

undefined

)davinc...vision@ (line 39241)
setContent(_2081=

"./preMigM7_Eclipse_2012...tent/folder1/file1.html"

, _2082=

"<!DOCTYPE html>\n<html>\n...</div>\n</body>\n</html>\n"

, _2083=

undefined

)davinc...vision@ (line 45122)
_1742()davinc...vision@ (line 32881)
(?)()davinc...vision@ (line 32900)
_447(_448=

[

undefined

, function(), function()]

, type=

1

, _449=

[

undefined

]

, _44a=

undefined

)dojo.j...vision@ (line 5518)
then(_462=function(), _463=function(), _464=

undefined

)dojo.j...vision@ (line 5628)
setEditor(_1740=function())davinc...vision@ (line 32906)
_c5(_c6=Object { mid=

"require*_39"

, pack=

0

, executed=

5

, more...}, _c7=

[function()]

)dojo.j...vision@ (line 607)
_36(_d9=Object { mid=

"require*_39"

, pack=

0

, executed=

5

, more...}, _da=

0

)dojo.j...vision@ (line 688)
(?)()dojo.j...vision@ (line 393)
_37(_de=function())dojo.j...vision@ (line 696)
_16(a1=

[

"davinci/ve/PageEditor"

]

, a2=function(), a3=

undefined

, _7c=Object { pid=

"davinci"

, mid=

"davinci/workbench/EditorContainer"

, pack={...}, more...}, _7d=function())dojo.j...vision@ (line 392)
_85(a1=

[

"davinci/ve/PageEditor"

]

, a2=function(), a3=

undefined

)dojo.j...vision@ (line 409)
setEditor(_173b=Object { id=

"davinci.ve.HTMLPageEditor"

, name=

"HTML Visual Editor"

, extensions=[3], more...}, _173c=

"./preMigM7_Eclipse_2012...tent/folder1/file1.html"

, _173d=

"<!DOCTYPE html>\n<html>\n...</div>\n</body>\n</html>\n"

, file=Object { elementType=

"File"

, name=

"file1.html"

, startOffset=

0

, more...}, _173e=div#editor-._preMigM7_Eclipse_20120904_WebContent_folder1_file1.html.dijitLayoutContainer, _173f=

undefined

)davinc...vision@ (line 32917)
_createEditor(_19a3=Object { id=

"davinci.ve.HTMLPageEditor"

, name=

"HTML Visual Editor"

, extensions=[3], more...}, _19a4=

"./preMigM7_Eclipse_2012...tent/folder1/file1.html"

, _19a5=Object { fileName={...}, content=

"<!DOCTYPE html>\n<html>\n...</div>\n</body>\n</html>\n"

, isDirty=

false

}, _19a6=

undefined

)davinc...vision@ (line 36003)
openEditor(_1995=Object { fileName={...}, content=

"<!DOCTYPE html>\n<html>\n...</div>\n</body>\n</html>\n"

, isDirty=

false

}, _1996=

undefined

)davinc...vision@ (line 35928)
_dblClick(node=Object { elementType=

"File"

, name=

"file1.html"

, startOffset=

0

, more...})davinc...vision@ (line 60660)
_3c6()dojo.j...vision@ (line 4960)
_564()dojo.j...vision@ (line 6939)
_onDblClick(_14af=[Widget dijit._TreeNode, dijit__TreeNode_24] { _attachPoints=[8], _attachEvents=[0], _connects=[0], more...}, e=dblclick clientX=191, clientY=615)davinc...vision@ (line 28721)
(?)(evt=dblclick clientX=191, clientY=615)davinc...vision@ (line 28387)
(?)(_4d5=dblclick clientX=191, clientY=615)dojo.j...vision@ (line 6096)


console.error("resource.findResoure: Folder "+_2a5a+" not found");
```

**Comment by aerwin** [comment]
@doronrosenberg 

Error for mobile page with carousel on page:

```
dojo/parser::parse() error

Error: Use StoreCarousel or DataCarousel instead of Carousel.
[Break On This Error]   

throw new Error("Use StoreCarousel or DataCarousel instead of Carousel.");

Carousel.js (line 55
```

Do we at least have something in release notes for the carousel issue?

**Comment by JonFerraiolo** [comment]
I didn't put anything in the release notes. You can see the current release notes by going to Help->Documentation and looking for "Release 7" under release notes. The source file is at maqetta.core.client/WebContent/docs/releaseNotes/release7.html

**Comment by jhpedemonte** [comment]
I had an issue with my migrated workspace, so I switched over to Orion.  I deleted the problem project, then selected one of the remaining projects and selected **Open in Maqetta**.  Nothing happened.  No errors in browser console or server log.

**Comment by jhpedemonte** [comment]
Committed and ran a migration script (see #3256).  Most of these issues should be fixed by that.

**Comment by jhpedemonte** [comment]
I updated the summary, striking out issues that have been fixed by migration script.

For Eclipse projects, **app.js** and **app.css** still [show up outside](https://github.com/maqetta/maqetta/issues/3242#issuecomment-8278121) of **WebContents** folder.

**Comment by jhpedemonte** [comment]
Closing this bug.  The "samples" discussion can take place in #3256.  The other 2 remaining issues are handled in other bugs and don't seem to be migration specific.

If you encounter any other migration bugs, open a specific issue.
