### ISSUE TITLE
Whole UI slides down when closing folder in Files view

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3243]
Noticed on Chrome/Mac when testing migration:
1. Open Files view.
2. Open one of the folders.
3. Scroll down.
4. Close the opened folder.

The entire UI will slide down:

![ui](http://i.imgur.com/EMvIK.png?1)

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
I have been trying to reproduce using my migrated projects (both Eclipse and regular) and haven't been able to make this happen. To the best of my knowledge, we are just using Dojo widgets (BorderContainer and TabContainer mostly) without doing anything fancy.

**Comment by doronrosenberg** [comment]
Yeah, I can't reproduce this as well.

**Comment by jhpedemonte** [comment]
OK.  My migrated workspace is totally hosed right now, so can't test again with that.  I'll close but reopen if I can reproduce.

**Comment by doronrosenberg** [comment]
@jhpedemonte if it happens, be sure to check for js errors
