### ISSUE TITLE
Email sent message looks like an error message (e.g., red, no further words that it will contain a link to sign up etc.)

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3245]
@JonFerraiolo 

Email sent message looks like an error message (e.g., red color, no further words that it will contain a link to sign up etc.).

![GitHub Logo](http://i.imgur.com/ql3NQ.png)

**Comment by JonFerraiolo** [comment]
Reopening for testing once new builds are deployed

**Comment by JonFerraiolo** [comment]
Closing. All messages now have grayscale coloring.

![After Register](http://i.imgur.com/eG2lS.png)
