### ISSUE TITLE
SaveAs Widget preview not working on staging server when zazl=true

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3248]
@childsb @jhpedemonte 

I'm running the SaveAs WIdget tests. Works fine when I run from Eclipse, but not when I run off of the staging server. Assigning to @peller because of zazl aspect, but likely @childsb will need to be involved. Steps:
- New Desktop App
- Add a DIV
- Put a Button in the DIV
- Select the DIV
- SaveAs Widget (dialog values: aaa, bbb, unchecked)
- Close current document
- New Desktop App
- Drag/drop the "bbb" widget from User widgets section
- Preview

Result=> 

```
GET https://app.moketta.org/_javascript?modules=dijit/dijit,dojo/parser,maqetta/space,maqetta/AppStates,dijit/form/Button,widgets/aaa/bbb&writeBootstrap=false&locale=en-us&config=%7B%22directInject%22%3Atrue%2C%22injectUrl%22%3A%22%2F_javascript%22%2C%22packages%22%3A%5B%7B%22name%22%3A%22dojo%22%2C%22location%22%3A%22lib%2Fdojo%2Fdojo%22%2C%22main%22%3A%22main%22%7D%2C%7B%22name%22%3A%22dijit%22%2C%22location%22%3A%22lib%2Fdojo%2Fdijit%22%2C%22main%22%3A%22main%22%7D%2C%7B%22name%22%3A%22dojox%22%2C%22location%22%3A%22lib%2Fdojo%2Fdojox%22%2C%22main%22%3A%22main%22%7D%5D%2C%22paths%22%3A%7B%22DojoThemes%22%3A%22themes%22%2C%22gridx%22%3A%22lib%2Fdojo%2Fgridx%22%2C%22clipart%22%3A%22lib%2Fclipart%22%2C%22maqettaSamples%22%3A%22samples%22%2C%22maqetta%22%3A%22lib%2Fmaqetta%22%2C%22shapes%22%3A%22lib%2Fshapes%22%7D%2C%22baseUrl%22%3A%22%2Fmaqetta%2Fuser%2FB%2Fws%2Fworkspace%2Fproject2%2F%22%2C%22scanCJSRequires%22%3Afalse%2C%22debug%22%3Afalse%2C%22config%22%3A%7B%7D%7D&exclude= 500 (AST parsing error for [widgets/aaa/bbb] error : Unable to obtain source for Module [/maqetta/user/B/ws/workspace/project2/widgets/aaa/bbb]) zazl.js:217
```

When I edit the URL bar and change `zazl=true` to `zazl=false`, the custom widget previews correctly

**Comment by jhpedemonte** [comment]
cc @rbackhouse 

I thought Zazl skipped over widgets for which it could not get source (or something like that; my mind is fuzzy today).

**Comment by peller** [comment]
No, Zazl is a replacement for the Dojo loader.  It needs to resolve all the references server-side. It's probably unable to locate the package, since no linkage is specified.

**Comment by peller** [comment]
@childsb take a look at <a href="https://github.com/maqetta/maqetta/blob/master/zazl/maqetta.zazl/src/maqetta/zazl/Activator.java#L74">zazl/maqetta.zazl/src/maqetta/zazl/Activator.java#L74</a>  The filter is including libraryManager.getAllLibraries() for paths.  Should we include the custom widgets in this result?

**Comment by peller** [comment]
-> M8

**Comment by childsb** [comment]
"Custom" libraries dont have any server implications-- it's all client side.

The custom widgets are properly qualified AMD imports.  They work just like dijit.form.Button, or any custom templated widgets a user might create.  There's no server magic.

Why isn't zazl pulling the imports from the AMD module spec?  What does it need to do with the server?

**Comment by peller** [comment]
@childsb please take a look at the maqetta.zazl code <a href="https://github.com/maqetta/maqetta/issues/3248#issuecomment-8321008">mentioned above</a>  The zazl version of the page (and zazl's config object) is constructed based on what is given for "all libraries" in the LibraryManager configured for that user.  That seems to be everything except for the custom widget.  I'm not suggesting there has to be any server magic for custom widgets to work, just that it may make sense to expose the existence of the library on the page to these APIs.  If not, we could use a way to query for it to construct this page without having to mine the HTML.

**Comment by childsb** [comment]
@peller so looking at the code, it looks like zazl is going through all the JS libraries and doing its compression algorithms.  can you explain this process more?  does it just blindly concatenate all the JS for every directory it knows about?  Is there no AMD module resolution going on to determine paths?

((from my understanding)) the dojo build will look at an HTML or JS file, grep out its AMD dependancies, and resolve those modules and compress them.  So for this example:

```
define([
    "davinci/Runtime",
    "davinci/model/Path",
    "davinci/ve/themeEditor/metadata/CSSThemeProvider"
],
function(Runtime,  Path, CSSThemeProvider) {

// some code

});

```

For each of those 3 AMD modules, Dojo builder will resolve the path, reduce the dependency and smush the code together.  The file is loaded based on the module path.

Isn't zazl doing the same type of thing?  Aren't the paths resolved based on the module dependancies?

**Comment by peller** [comment]
@childsb yes, it's doing AMD path resolution and walking the dependencies list recursively to build the result, just as the Dojo builder does, but on demand.  In order to do this, zazl inserts its loader (zazl.js) in place of dojo.js, which is Dojo's bootstrap + loader.  That's basically what MaqettaHTMLFilter does, when zazl=true.   You'll see that MaqettaHTMLFilter has to pass zazl a zazlConfig so it knows where to find all the packages, just like the packages list passed to Dojo.  That's where things are going wrong.  The library list passed in to MaqettaHTMLFilter (and Zazl) is missing the custom library, so it can't resolve widget.\* references.

**Comment by peller** [comment]
That code in Activator is just gathering the library list. Look at MaqettaHTMLFilter to see it actually assemble the page, and take a look at a view-source of the preview with zazl to see what it looks like.  If you preview a page with custom widget and zazl, you'll see the 'paths' list (like packages) and what it's missing.

**Comment by rbackhouse** [comment]
The library list appears to be static in nature loaded from the plugin extension list. If new libraries are created for custom widgets then the Zazl code needs to be able to prgrammatically resolves these and add to the paths configuration.

**Comment by childsb** [comment]
Ah, ok. So it sounds like for client side we used packages : [] in the boothstrap to specify the pathspace, but zazl isn't parsing that and needs a configuration object to do so.

**Comment by rbackhouse** [comment]
@childsb So I'm assuming there is nothing on the server-side where I could get this without having to parse the data-dojo-config attribute to obtain the packages ?

**Comment by childsb** [comment]
No.  For custom widgets, there's nothing server side.  There's a workbench configuration setting which specifies the path to the custom widgets, but there's nothing library related for them on the server.

**Comment by rbackhouse** [comment]
Ok, so then it sounds like the Zazl code will have to grab it from the data-dojo-config attribute.

**Comment by rbackhouse** [comment]
In trying this out I see that the the custom widgets appear to be always placed in a path of "lib/custom"using "widgets" as the name. Assuming this is true the Zazl fix is to simply add this to its paths configuration ensuring that the current path is taken into consideration (it already does this for the other libraries)

**Comment by peller** [comment]
that would probably work.  right now, the packages list is static.  we need to work to make it more extensible and reflect only what's on the page (#2516)

**Comment by jhpedemonte** [comment]
> ... widgets appear to be always placed in a path of "lib/custom"using "widgets" as the name.

I'm not sure if we can always assume that path and name.  @childsb ?

**Comment by childsb** [comment]
It's based on a users preference-- they could in theory change the custom widgets folder.

**Comment by rbackhouse** [comment]
Currently the Zazl HTML Parser is using details from the Libraries configured on the server. This is always going to be a problem when a user can modify the path to the custom widgets and also when the User Library paths are modified for the project. 

With this in mind I have modified the code to instead use the package configurations provided in data-dojo-config for all the libraries. What I have discovered is that the default resolved "baseUrl" config property that the dojo AMD loader creates is different to what the AMD common config defines 

From dojo/_base/config.js

```
// baseUrl: String
//      The directory in which `dojo.js` is located. Under normal
//      conditions, Dojo auto-detects the correct location from which it
//      was loaded.
```

From the spec :

"baseUrl
String: Indicates the root used for ID-to-path resolutions. Relative paths are relative to the current working directory. In web browsers, the current working directory is the directory containing the web page running the script."

This results in the locations declared in data-dojo-config to be relative to the dojo.js and not the web page loading it. 
I have the code working somewhat but it is still a problem when the dojo User Library path is modified. I need to find a reliable algorhythm that will enable me to find the path to the zazl.js loader. Once done this should fix #3208 too

**Comment by rbackhouse** [comment]
For zazl.js path resolution I have come up with the following :

1) Use the pathInfo data obtained from the filter request object. An example is as follows

/user/maqettaUser/ws/workspace/project1/file1.html

2) Strip off the "/user/maqettaUser/ws/workspace". The assumption I'm making here is that "/ws/workspace" will alway be the last bit before the project path.

3) Strip off the last segments (in this example "/file1.html") This should result is a segmented path that can be used to resolve the relational path to <project>/lib/zazl.js by counting the segments and adding "../" for each one found.

The assumptions I'm making are that the project path with always be preceeded by "/ws/workspace" and that a project name will always be only one segment.

While this enables the fix for custom widgets it does not fully fix #3208. I have addtional details how to fix that in that issue.

**Comment by peller** [comment]
with today's code, when I attempt to preview the test case at the top with user widget aaa/bbb, I get:

```
Failed to load resource: the server responded with a status of 500 (AST parsing error for [widgets/aaa/bbb] error : Unable to obtain source for Module [/maqetta/user/A/ws/workspace/project1/widgets/aaa/bbb]) 
```

**Comment by peller** [comment]
apparently the path to the custom widget source is `http://localhost:8081/maqetta/user/A/ws/workspace/project1/lib/custom/aaa/bbb.js`

**Comment by rbackhouse** [comment]
Using the sample in the first comment I have no problem previewing via Zazl

**Comment by peller** [comment]
I needed to do a recursive submodule update to get the latest version of Zazl. (see #2708)  Works fine in 0.4.4.  Thanks!
