### ISSUE TITLE
Zazl filter must carry over config info (was: Mobile preview with zazl doesn't honor edited theme)

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3252]
@peller @billreed63 

Using Chrome on Mac going to moketta...

I noticed that when I preview a mobile page with an edited theme that with zazl on the rendering doesn't match what I see in the page editor. Removing the zazl tag seems to clear it up.

From page editor:

![GitHub Logo](http://i.imgur.com/uteWL.png)

Preview with zazl:

![GitHub Logo](http://i.imgur.com/t66k0.png)

**Comment by jhpedemonte** [comment]
cc @rbackhouse

**Comment by peller** [comment]
@aerwin I tried the following and it worked:

create a mobile document with a calendar widget
clone claro as claro2
change the background color on widgets to red
switch the document to use claro2
preview with zazl

...and it worked

Zazl shouldn't have any impact on CSS.  It only fiddles with the JS bits.  Perhaps it was some sort of caching issue and the reload resolved it?

**Comment by aerwin** [comment]
Reloading the page with zazl turned on doesn't do any good either.

I notice when you tried to reproduce you cloned desktop theme and used desktop widgets. Not sure if that makes any diff.

Here's the HTML for my page (which BTW takes a REALLY long time to load on first preview as well):

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'async':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}],'themeMap':[['Android',null,['themes/android2/android2.css']],['BlackBerry',null,['themes/blackberry2/blackberry2.css']],['iPad',null,['themes/ipad2/ipad2.css']],['iPhone',null,['themes/iphone2/iphone2.css']],['.*',null,['themes/custom2/custom2.css']]],'mblThemeFiles':[], mblLoadCompatPattern: /\/test20120904\/themes\/.*\.css$/"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dojox/mobile",
  "dojox/mobile/deviceTheme",
  "dojox/mobile/compat",
  "dojo/hash",
  "dojox/io/xhrScriptPlugin",
  "dojo/data/ItemFileReadStore",
  "dojox/mobile/EdgeToEdgeDataList",
  "dojox/mobile/Button",
  "dojox/mobile/Slider",
  "dojox/mobile/TextBox",
  "dojox/mobile/TabBar",
  "dojox/mobile/TabBarButton",
  "dijit/form/ToggleButton",
  "dijit/form/ComboBox",
  "dojox/mobile/TextArea"
]);
</script>
<style>@import "themes/claro/claro.css";@import "lib/dojo/dojox/mobile/themes/common/domButtons/DomButtonRedBadge.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"></meta>
</head>
<body class="claro" data-maq-device="iphone" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
 <div id="View_0" data-dojo-type="dojox.mobile.View" style="height: 100%;" selected="selected">
  <span data-dojo-type="dojo.data.ItemFileReadStore" id="ItemFileReadStore_1" jsId="ItemFileReadStore_1" data="{&quot;identifier&quot;:&quot;label&quot;,&quot;items&quot;:[{&quot;label&quot;:&quot;Label 1&quot;,&quot;moveTo&quot;:&quot;transitionToPage&quot;},{&quot;label&quot;:&quot;Label 2&quot;,&quot;moveTo&quot;:&quot;transitionToPage&quot;}]}"></span><h1 label="Heading" data-dojo-type="dojox.mobile.Heading"></h1>
<ul data-dojo-type="dojox.mobile.EdgeToEdgeDataList" store="ItemFileReadStore_1" query="{&quot;label&quot;:&quot;*&quot;}"></ul>
<button data-dojo-type="dojox.mobile.Button">
Button</button>
<button data-dojo-type="dojox.mobile.Button" disabled="disabled">
  Button</button>
<input type="button" data-dojo-type="dijit.form.ToggleButton" intermediateChanges="false" label="ToggleButton" iconClass="dijitCheckBoxIcon"></input>
<input type="range" data-dojo-type="dojox.mobile.Slider"></input>
<input type="text" data-dojo-type="dojox.mobile.TextBox"></input>
<div data-dojo-type="dojox.mobile.Switch"></div>
<ul data-dojo-type="dojox.mobile.TabBar">
<li label="Tab 1" data-dojo-type="dojox.mobile.TabBarButton" icon1="samples/sample_data/images/i-icon-1.png" icon2="samples/sample_data/images/i-icon-1.png" selected="selected"></li>
<li label="Tab 2" data-dojo-type="dojox.mobile.TabBarButton" icon1="samples/sample_data/images/i-icon-2.png" icon2="samples/sample_data/images/i-icon-2.png"></li>
<li label="Tab 3" data-dojo-type="dojox.mobile.TabBarButton" icon1="samples/sample_data/images/i-icon-3.png" icon2="samples/sample_data/images/i-icon-3.png"></li>
</ul>
<select data-dojo-type="dijit.form.ComboBox" value="Item 1" intermediateChanges="false" trim="false" uppercase="false" lowercase="false" propercase="false" invalidMessage="$_unset_$" pageSize="Infinity" searchDelay="200">
<option value="Item 1" selected="selected">
Item 1</option>
<option value="Item 2">
Item 2</option>
<option value="Item 3">
Item 3</option>
</select>
<textarea data-dojo-type="dojox.mobile.TextArea" value="some text!!"></textarea>
</div>
</body>
</html>


```

**Comment by peller** [comment]
MaqettaHTMLFilter is not carrying over the dojo-data-config parameter, thus dropping the themeMap and perhaps other important bits.

-> M8

**Comment by rbackhouse** [comment]
So is this just a matter of taking the properties (minus paths, packages and async) from the dojo-data-config param and adding them to the dojoConfig object the Zazl page generates ?

**Comment by peller** [comment]
I think so.  If it's easier/simpler to copy them all, I suppose paths+packages+async would go ignored on dojoConfig?

**Comment by rbackhouse** [comment]
I'm trying to take the dojo-data-config and convert it to a json string so it can be parsed, some properties removed and then serialized out for the dojoConfig object. 

The theme example has this which is not json parsable :

mblLoadCompatPattern: /\/test20120904\/themes\/.*.css$/

Can this be made json friendly ?

**Comment by peller** [comment]
What if we just took the string verbatim?

**Comment by rbackhouse** [comment]
Yes, just taking the value, surrounding with { } and assigning to the dojoConfig var seems to work. I'm not able to validate this with the provided markup though. I get a 404 on 

/maqetta/user/maqettaUser/ws/workspace/project1/themes/iphone2/iphone2.css

**Comment by peller** [comment]
you need to create a theme (create menu up top) and clone from the iphone theme and call it iphone2, and change something like the background color of the global widget to red

**Comment by peller** [comment]
AFAIK, Dojo does not have any strict requirements on data-dojo-config, but it is almost JSON... seems like it might be nice for it to have those properties.  Something we should consider for 2.0.  @ykami, wonder if we should accept the regexp also as a string?

@wkeese

**Comment by rbackhouse** [comment]
@peller I have a fix for this that works. Do you want me to hold off delivering as its marked M8 ?

**Comment by peller** [comment]
@rbackhouse nah, go for it.   

M7 <-

**Comment by rbackhouse** [comment]
https://github.com/maqetta/maqetta/commit/db8c9342a99bbc53bc1e2fbf8e6cdfeaf7e4b340 is the commit

**Comment by ykami** [comment]
> @ykami, wonder if we should accept the regexp also as a string?

@peller make sense, you can create a ticket if necessary.
