### ISSUE TITLE
No message after clicking "Register" button

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3253]
There used to be a message saying that an email had been sent after clicking the **Register** button.  With latest build, I see nothing.

Also, the _Cancel_ and _Sign Up_ buttons disappear (although that may have been the case previously).

-> @JonFerraiolo, but feel free to reassign as necessary.

**Comment by jhpedemonte** [comment]
Broken by cfec354f6eebf5ea86b36da06da63c9c9fc812d4?  @childsb

**Comment by JonFerraiolo** [comment]
Yes, broken by Broken by cfec354. The DIV that holds the (error) message used to be on the "outside" of the various sections (login, signup, reset) but with that commit the (error) message is now inside the login section, so it doesn't show in the other two sections (signup and reset).

I'll ping @childsb about it...

**Comment by JonFerraiolo** [comment]
Reopening for testing once new builds are deployed

**Comment by JonFerraiolo** [comment]
On the staging server, after clicking on "Register", you get this:

![After Register](http://i.imgur.com/eG2lS.png)

**Comment by JonFerraiolo** [comment]
Closing, seems to be working now
