### ISSUE TITLE
Warning with mobile theme editors when using FF

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3255]
@jhpedemonte @aerwin 

My first thoughts on this one:
- **How to cause the prompt to appear for mobile theme editors and not the desktop theme editors?** Can we add the prompt to the mobile theme editor HTML files (and not to desktop theme editor HTML files)? Otherwise, it's hard in our code to distinguish between mobile theme editors and desktop theme editors. The best technique I've figured out for that is to look for class "mobile" on the HTML element (using dojo.hasClass), but obviously that's a hack. Maybe there is a flag on the *.theme data structure we can use?
- **How to post the message** I was thinking to just use an `alert()` or `prompt()`, and maybe log a bug to use a properly-styled Maqetta dialog down the road.

**Comment by jhpedemonte** [comment]
Do not use `alert()`.  Use our dialog code that puts up a Dijit Dialog.  Should be fairly straight forward. Doron can quickly do it.
