### ISSUE TITLE
M7 Shell Script Migration TODOs

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#3256]
Ref Issue: #3242
### General Changes
- Remove Samples1.html and Samples2.html from the users workspace.
- For every dojo-theme-editer.html (custom themes), find and replace the dojo 1.7 string with 1.8
### libs.settings changes:
- Find and replace 1.7 with 1.8 for dojo regular, and dojo themes
- Find and replace 1.0prebeta2 to 1.0.0  (gridx)
- Add  required="true" on lines:

`<library id="html" name="html" version="0.8"/>`
`<library id="maqetta" name="maqetta" version="0.3" virtualRoot="lib/maqetta"/>`
- Add these lines:
  `<library id="zazl" name="zazl" required="true" version="0.3.0" virtualRoot="lib/zazl"/>`

`<library id="maqettaSamples" name="maqettaSamples" required="true" version="1.0" virtualRoot="samples"/>`

**Comment by jhpedemonte** [comment]
> For every dojo-theme-editer.html (custom themes), find and replace the dojo 1.7 string with 1.8

@billreed63, is that correct? Anything else I need to look out for?

**Comment by jhpedemonte** [comment]
@JonFerraiolo, what do you think we should do about sample files?  I'm thinking we leave them, in case the user has edited them in any fashion.  They can always create a new (clean) project.

**Comment by billreed63** [comment]
For every dojo-theme-editer.html (custom themes), find and replace the dojo 1.7 string with 1.8
replace

```
<script type="text/javascript" src="/maqetta/app/static/lib/dojo/1.7/dojo/dojo.js" data-dojo-config="parseOnLoad: true, async: true"></script>
```

with 

```
<script type="text/javascript" src="/maqetta/app/static/lib/dojo/1.8/dojo/dojo.js" data-dojo-config="parseOnLoad: true, async: true"></script>
```

**Comment by jhpedemonte** [comment]
Committed a migration script to 8013696afb246989d0fef9e7c43672c64a76c569.

**Comment by jhpedemonte** [comment]
Another commit here: bc8ee114938d815337c8f2a69c994a4016a28c29

Closing this, all known issues fixed.
