### ISSUE TITLE
Another pass through release notes

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3258]
Need to update release notes per various last-minute changes. Off the top of my head:
- Zazl as an opt-in feature
- Don't use FF for mobile theme editor

(Note to @billreed63 @peller @jhpedemonte @aerwin @doronrosenberg @childsb: If you think of something that needs to be added to the release notes, just go and change the HTML content at maqetta.core.client/WebContent/docs/releaseNotes/release7.html)

**Comment by aerwin** [comment]
@doronrosenberg Per discussion in migration bug yesterday, could you add something on the mobile carousel?
