### ISSUE TITLE
Problems with setting button opacity and float (perhaps bad test case)

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3259]
Making Prio High as a start for investigation

Using Chrome on Mac going to moketta... doing Properties 2 test plan (the "display, opacity, float, clear, overflow" section)...
1. New HTML file
2. Drag Dojo button onto page
3. Set opacity to 0.5. The instructions say: "The button should now be semi-transparent." However, I get the message that the value can't be set. Perhaps this one is correct, but then test case should be updated.
4. Set float to right. Instructions say: "The button should shift to the right, and LABEL should move to top/left." Again, get the read-only message. In this case, shouldn't I be able to set float? If not, then again I guess instructions should be updated.

**Comment by jhpedemonte** [comment]
-> @billreed63
