### ISSUE TITLE
Proposed new rule feature broken

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3264]
This commit  18008340d7 broke the "proposed new CSS rule" feature (as described in the documentation page about adding a new rule to app.css). I did a checkout of the previous commit (3a3ef472121972b7af5cf9a378468b2ccf4fd525) and the feature is working with that commit.

**Comment by billreed63** [comment]
I looked at the documentation "Using the Detailed CSS pane on the Properties palette to add/modify style rules in app.css" And it appears to me to be working as documented.
@JonFerraiolo  can you give a more detailed description of the deviation?

**Comment by JonFerraiolo** [comment]
Using staging server:
- Create Desktop Application
- Add a Button
- Open Layout section
- Add class 'qqq' or whatever to the Button
- Show cascade for 'width'
- New rule radio button should be selected
- Enter "15em" for value

Result=> Text field goes blank, button is still is original width
