### ISSUE TITLE
Smart Input not coming up for any advanced widgets on create

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3278]
Using FF on MAc going to moketta...
1. New HTML file
2. Drag complex widget (e.g., Slider, GridX, Tree, etc.)
3. No smart input comes up
4. Also note that while new widget looks selected, toolbar items like delete icon are disabled

**Comment by aerwin** [comment]
Having trouble reproducing this one now... maybe it was related to some other exception... still playing around...

**Comment by aerwin** [comment]
Closing this one... must have been a glitch or related to one of the other issues I've logged today. Pretty much everyone's test plan should require using such widgets today, so imagine it will get caught if really an issue here.

**Comment by jhpedemonte** [comment]
Could have been a caching issue, maybe, given that we've changed several things at once on the server.
