### ISSUE TITLE
widgetHash leak

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3280]
davinci/ve/widget adds references to widgetHash, but never removes them

@JonFerraiolo

**Comment by peller** [comment]
dup of #861?

**Comment by peller** [comment]
may have been resolved by a0b10bdce2f6a682ff89c5d73bc61c41f8986462  @JonFerraiolo, do you agree?

**Comment by jhpedemonte** [comment]
Looking at that commit, the change in Context.js:  does this mean that `widgetHash` is reset and reconstructed every time `widgetChanged()` is called?  Won't this be a performance hit if there are a lot of widgets on the page?  Seems like there should be a better way to do this, not reseting it every time.

**Comment by peller** [comment]
Iterating through a hashtable of dozens of elements and collecting references may not be efficient, but it shouldn't be a performance issue.

**Comment by JonFerraiolo** [comment]
I'm pretty sure the leak is gone, even though as @jhpedemonte points out, we tax the CPU with each command to recompute widgetHash. Note that the choice was either fixing bugswith widgetHash (which I did via atom bomb approach) or removing it, but removing it means that widget lookups will be slower.
