### ISSUE TITLE
eclipse project has two app.css and app.js files

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3284]
I created an eclipse projected and noticed that I have 
app.css and app.js in the root folder as well as an app.css and app.js in the WebContent folder

**Comment by childsb** [comment]
closed per checkin

**Comment by JonFerraiolo** [comment]
Reopening. I'm seeing this with latest code.

**Comment by JonFerraiolo** [comment]
Closing - I don't see this in M701
