### ISSUE TITLE
Creation of HTML files in theme folders allowed which leads to missing css file

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3291]
Making prio high just for input/investigation, but surely an M8 issue...

Using FF on Mac going to staging server...

Found this one accidentally doing the Claro Theme Editor tests because I had opened my cloned theme from the files palette (as part of the test case) which lead to the default folder being in the theme directory...
1. Clone theme
2. Create HTML file in the cloned theme's directory... [I'd question whether this should be allowed in first place]
3. Notice error in console when open new file.

```
"NetworkError: 404 ProxyServlet: /document.css - http://app.moketta.org/document.css"

document.css
```

**Comment by jhpedemonte** [comment]
Yeah, pushing to M8.  @JonFerraiolo 

Ideally, we should only allow **theme folders** in the _themes_;  disallow any other type of creation or moving.

**Comment by JonFerraiolo** [comment]
-> me

What I'm thinking is that the new html file logic should have a list of folders where you can't create new files, and reset the current "where" folder to a parent folder which is ok for creating new files.
