### ISSUE TITLE
Files/Reviews palettes jump to upper-left for ThemeEditor

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3296]
Switch to a theme editor.  Observe that Files and Reviews are in the upper-right corner, not lower left like other editors.

**Comment by aerwin** [comment]
For the moment, this is working as designed... Page editor is actually the only editor that has files/reviews in lower left. There was another issue open about whether to go with the current behavior or not, and we decided to move forward with it. I guess you'd +1 yourself against that other issue that you don't like this?

**Comment by peller** [comment]
I don't recall that discussion.  Could close this as a dup then.  Just seems like the user will expect the location of those panels to stay constant.

**Comment by JonFerraiolo** [comment]
I'm having second thoughts about the Files palette jumping around. But for M7 we should leave things as they are now.

**Comment by jhpedemonte** [comment]
Just want to clarify: the Files/Review views move to the upper-**right**, not upper-left as mentioned in the summary.  If you see otherwise, @peller, then we have a bigger issue.

**Comment by peller** [comment]
I see upper-left. Upper-right has the properties, as it should.
