### ISSUE TITLE
Theme Editor: Background dialog doesn't change global background

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3297]
@billreed63 

Using FF on Mac going to staging server...
- Clone claro theme
- Select global background widget
- Bring up background dialog and change entry in gradient

![GitHub Logo](http://i.imgur.com/kULMT.png)
- Click OK and no change in theme editor

![GitHub Logo](http://i.imgur.com/fjbxO.png)
- If I bring the background dialog back up, my change is still in there

**Comment by aerwin** [comment]
Using background pull down and choosing and entry (like "red") appears to work... and, interestingly, I think the rest of the gradient info is maintained.

**Comment by billreed63** [comment]
in the desktop theme editor, the global widget only supports background-color and various font properties.
We have an issue already open to support this in the future #2907
