### ISSUE TITLE
Migration: file missing

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3298]
in my project1 I have a file called 'file1.html' in 'folder1'.  on the migration, folder1 is empty

**Comment by jhpedemonte** [comment]
-> @childsb 

My script did nothing to remove files.  If a file is missing, it must have happened during the in-app migration process.

@peller, do you see the file missing when you switch over to Orion Navigator?

**Comment by peller** [comment]
weird.  the file is there now.  can't explain that.

**Comment by jhpedemonte** [comment]
I think we have some issues with the Files view code and how it reads files from the server.  I've noticed inconsistencies as well, but nothing reproducible.
