### ISSUE TITLE
Tooltip and Dialog missing from palette

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3305]
When we remove the untested widget we removed tooltip and dialog. 
Tooltip and Dialog are in the desktop theme editor
I think we should add back in the untested widget and change the title to "Maqetta Labs" or something like that...

**Comment by JonFerraiolo** [comment]
No, my strong opinion is let's leave things as is. For this release, it's OK if theme editor has widgets that aren't in page editor.

**Comment by aerwin** [comment]
I think it's a shame we don't have dialogs anymore... but, as an fyi they are broken anyway (#2957).

**Comment by JonFerraiolo** [comment]
@jhpedemonte and @JonFerraiolo agree to push to M8

**Comment by jhpedemonte** [comment]
We had other things to focus on and never got around to dealing with the **overlay** widgets.  Closing this one as dupe of #2957.
