### ISSUE TITLE
Opening review doesn't show Comments, doesn't auto-hide/auto-show left/right panes

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3307]
(M7 for investigation.)

Testing on **Firefox ESR 10.0.7**.
1. Close all editors.
2. Click on Reviews in left pane.
3. Open a review.

Should close _left pane_ and open _right pane_, which should show **Comments** at the top and **Scenes** at the bottom.

But the panes don't auto-show/auto-hide, and **Comments** view is missing.

No errors in JS console.  Works correctly in Chrome.

@JonFerraiolo

**Comment by jhpedemonte** [comment]
Works fine in latest Firefox (v15).

**Comment by jhpedemonte** [comment]
@aerwin 

This make R&C unusable on Firefox ESR, since the **Comments** view isn't shown.

**Comment by aerwin** [comment]
Any exceptions or anything? I don't think I'm going to have time to find a place to install Firefox ESR to evaluate until I deal with newly acquired (and more crititcal) #2939.

**Comment by aerwin** [comment]
Oh, nevermind... guess you gave it to @doronrosenberg . :)

**Comment by jhpedemonte** [comment]
Nope, nothing in the JS console.

**Comment by doronrosenberg** [comment]
Out to m8

**Comment by JonFerraiolo** [comment]
-> M8 Prio-Med.

I'm hoping we can just forget about the current FF ESR and support the second FF ESR when it comes out within next few months.

**Comment by JonFerraiolo** [comment]
Closing. Our docs don't claim support for FF ESR1.
