### ISSUE TITLE
Migrated files point to incorrect 'maqetta' lib files

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3309]
Files from M6 have the following:

``` html
<script type="text/javascript" src="../maqetta/maqetta.js"></script>
<script type="text/javascript" src="../maqetta/States.js"></script>
```

We could setup our migration script to change that to:

``` html
<script type="text/javascript" src="../lib/maqetta/spaces.js"></script>
<script type="text/javascript" src="../lib/maqetta/AppStates.js"></script>
```

@JonFerraiolo @peller Is that correct?

**Comment by JonFerraiolo** [comment]
yes, I believe the proposed change is correct.

**Comment by peller** [comment]
filenames are right, but the maqetta directory didn't move, did it?  New modules are AMD and, I think, need to be in the big require()

**Comment by peller** [comment]
So didn't we decide it would just take a save cycle to fix this?  Is leaving the old script tags in place a problem? Maybe just remove them?

**Comment by jhpedemonte** [comment]
@peller is correct:  _spaces.js_ and _AppStates.js_ aren't loaded as `<script>` tags.  This is a file that I had saved in M7 after opening it, so it does have the correct files in the `require()` statement.

So do we have to do anything then?  I get 404 errors in the browser console for the old files, but things tend to work.

**Comment by jhpedemonte** [comment]
Migrated files may also have duplicated `require()` statements, such as this:

``` html
<script type="text/javascript">
require([
 "dijit/dijit",
 "maqetta/space",
 "maqetta/AppStates",
 "dojox/io/xhrScriptPlugin",
 "dojo/data/ItemFileReadStore",
 "dojox/mobile",
 "dojox/mobile/deviceTheme",
 "dojox/mobile/compat",
 "dojo/hash",
 "dojox/mobile/ScrollableView",
 "dojox/mobile/EdgeToEdgeDataList",
 "dojox/mobile/RadioButton",
 "dojox/mobile/SpinWheelTimePicker"
]);
require(["dojo/parser"]);
require(["dojox/mobile"]);
require(["dojox/mobile/deviceTheme"]);
require(["dojox/mobile/compat"]);
require(["dojox/mobile/ScrollableView"]);
require(["dojo/data/ItemFileReadStore"]);
require(["dojox/mobile/EdgeToEdgeDataList"]);
require(["dojox/mobile/RadioButton"]);
require(["dojox/mobile/SpinWheelTimePicker"]);</script>
```

I guess we could use some RegExp magic in order to consolidate `require` statements into one, but I don't know where to begin with that.

**Comment by peller** [comment]
you could probably just remove the extra require() calls, but it may be safest to just ignore them

**Comment by jhpedemonte** [comment]
-> fixed
