### ISSUE TITLE
Activation link login page logic problems

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3310]
@childsb @jhpedemonte 

Using the staging server, I clicked register and the email came to my gmail account correctly (yeah!). When I click on the link though, 2 problems:

1) I just see a blank screen. The JS logic isn't exposing the login DIV.
2) In debugger, if I make the appropriate DIV visible, the JS logic doesn't successfully pull the URL parameter and stuff it into the userid field

**Comment by jhpedemonte** [comment]
Fixed by Brad's commit here: ce1ccfacb2faaa756dd29c6b57dcb7c3676bf11c

I'll post a new build when ready.
