### ISSUE TITLE
Rename project seems to create new project rather than rename

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3315]
Probably for M8, but opening against M7 for evaluation...

Using Chrome on Mac going to staging server...
1. Go to files palette
2. Rename current project
3. After rename operation is complete, notice the old project is still listed in the list of projects (e.g., you'll see project with old name and project with new name). And, this old project seems to be selectable.

**Comment by jhpedemonte** [comment]
@childsb @JonFerraiolo 

What do you see in Orion Navigator?

**Comment by aerwin** [comment]
That's interesting... _fancyProject_ was the project I renamed to _fancyProject2_... in the navigator, I see two folders, but the one for _fancyProject2_ is empty:

![GitHub Logo](http://i.imgur.com/6az3m.png)

**Comment by jhpedemonte** [comment]
To @childsb to investigate.

**Comment by childsb** [comment]
closing per commit
