### ISSUE TITLE
"hosted" builds still have "test" dirs, etc

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3327]
Noticed that the "hosted" builds are noticeably bigger, by roughly 10MB.  I noticed that **dojo-src** still had its **test** directories.

So whatever build fix you added to remove those, it doesn't seem to be working for the "hosted" builds. 

@childsb

**Comment by peller** [comment]
@childs can you point me at what might differ in the build scripts for 'hosted'?  Removing the dojo-src files is part of the build script for the widgetPlugins now.  Does that script still run?

**Comment by peller** [comment]
see #3009

**Comment by peller** [comment]
@aerwin @childsb "tests" are still appearing.  Any ideas?

-> M8

**Comment by peller** [comment]
weird.  they're gone now.  both builds are essentially the same size. closing.
