### ISSUE TITLE
Table - wrong default height? (100%)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3330]
I added a 1x2 table inside of a ContentPane as its first child, and it defaulted to width=100% and height=100%. When I add a table as a child of BODY, the height does not have a value of 100%, (And doesn't happen if TABLE is not first child of ContentPane)

I think we are trying too hard to outguess the user. I think we should remove the logic that sets height to 100% when TABLE is a child of ContentPane. Whereas users will often nest Dojo container widgets such as BorderContainer and TabContainer, and just like Dojo, it's fine for us to default to w=h=100% if there is only one child widget, tables are use for lots of things. In the scenario where I ran into this, I was just going to use a table to line up a few controls at the top of a ContentPane.

**Comment by aerwin** [comment]
--> back to M7... can be fixed by very safe, easy fix to widgets.json

**Comment by aerwin** [comment]
Closing with above commit.
