### ISSUE TITLE
Can't delete project

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3332]
@childsb @JonFerraiolo @jhpedemonte 

Using Chrome on Mac going to staging server...

If you try to delete a project from the files palette, on first glance it works. However, if you look at your list of projects it's still there and you can still switch to it. In addition, I see the project in Orion Navigiator.

**Comment by jhpedemonte** [comment]
Hmm, I think this was working recently, probably within last week.

**Comment by childsb** [comment]
closing per commit
