### ISSUE TITLE
Hitting "Enter" after Smart Input appears clears out default content

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3334]
Drop a Button on the page.  Smart Input appears.  Without making any changes, simply hit "Enter", to accept the default value.

Instead, the default value is cleared (it was selected, so hitting "Enter" replaces the content with a new line), and then the smart input closes.

---

I think it is good that the content is **selected automatically**, so that the user can immediately start typing and replace the default content.

However, the user should just be able to hit "Enter" to take the default content.

This'll probably have to wait for M8, but want to get feedback for M7.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
I think we should fix this for M7, but I'd like to see what the code change would be before putting this fix into M7.

**Comment by JonFerraiolo** [comment]
M6 has the same problem. Amazing we didn't notice and no one complained.

**Comment by JonFerraiolo** [comment]
I pushed a fix into branch 3334SmartInputEnter. Commit c6b66cc267e1577fea2526d364f2778639f9ba6b. Although the fix looks simple, I think it's too risky for M7.

**Comment by jhpedemonte** [comment]
-> M8

**Comment by JonFerraiolo** [comment]
-> M701 - I have a fix already and it seems safe enough with a full testing cycle. @jhpedemonte

**Comment by JonFerraiolo** [comment]
Closing. I had fixed off in a branch during M7 cycle. Just merged that fix in.
