### ISSUE TITLE
Exception when adding View to mobile page

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3336]
Tested on Firefox:
1. Refresh Maqetta page.
2. Create a mobile page, iPhone device.
3. Drop a Dojox Mobile View into device.

Get error `this.rootNode is null` in **dijit/Tree.js**.  Stack is all Dojo.

@JonFerraiolo

**Comment by doronrosenberg** [comment]
Tree in question is StatesView, and the exception happens in Tree:resize.  Seems timing related, also happens in desktop page.

**Comment by doronrosenberg** [comment]
Hmm, I think this is because we are destroying the the tree on each update.  Still investigating

**Comment by doronrosenberg** [comment]
_hideShowToolBar() is the culprit doing the resize.

**Comment by JonFerraiolo** [comment]
I think we can remove the `d.resize();` line in _hide_showToolBar(). It was overkill programming - telling the "palette widget" to resize itself (probably triggering a Tree resize in the process) even though the only thing that is happening is that the DIV for the toolbar is becoming visible or invisible.

**Comment by doronrosenberg** [comment]
@jhpedemonte the other resize in StatesView also causes the issue:

```
        // In some scenarios, necessary to resize the ContentPane that surrounds the Tree
        if(this._tree.getParent){
            var parent = this._tree.getParent();
            if(parent.resize){
                parent.resize();
            }
        }
```

Any chance you remember what you were trying to fix? I disabled it and don't run into any issues

**Comment by doronrosenberg** [comment]
Or not - I see issues if we don't resize the parent, hmm.

**Comment by doronrosenberg** [comment]
So a fix that works is remove the d.resize() but put a setTimeout(func, 0) on the other resize call.
