### ISSUE TITLE
If Maq hangs on a file, no way to resetWorkbench

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3338]
@jhpedemonte @peller 

Making it an M7 issue for discussion. 

I got myself into a case where Maqetta was hanging on me with a particular file open. Other users have had this situation in the past. It doesn't happen often, but when it does happen, a user can't use the product.

@childsb invented `?resetWorkbenchState=1` to provide a workaround. However, with our new Orion-based login screens, if a user restarts his browser or session has timed out, they are taken to the Orion Login screen, which has a different URL that the Maqetta application, and there is no way right now to launch the app with `?resetWorkbenchState=1`

**Comment by childsb** [comment]
the workaround is to log in, and after the browser freezers stop the page and reload with the ?resetWorkbenchState=1 in the URL.

**Comment by JonFerraiolo** [comment]
Reopened so we remember to test.

**Comment by JonFerraiolo** [comment]
Works on staging server. Closing.

**Comment by JonFerraiolo** [comment]
Reopening. Still need to verify the other staging server, which isn't running latest code yet.

**Comment by JonFerraiolo** [comment]
Closing. Verified on other staging server.
