### ISSUE TITLE
Change all daVinci dv* attributes to data-davinci-*

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#334]
HTML5's convention is to use data-<appname>-\* as the new alternative to XML
Namespaces (aka the root of all evil). We need to follow the Hixie and change
all daVinci dv\* attributes to data-davinci-*. For example:

dvFlowLayout => data-davinci-flowlayout

Last I heard, Dojo was making this change for dojo 1.6.

**Comment by peller** [comment]
@JonFerraiolo do we want to use data-maqetta-\* now?  data-maq-*? note that we already have data-davinci-ws

**Comment by JonFerraiolo** [comment]
data-maq-*, try to do it for 1.0

**Comment by JonFerraiolo** [comment]
@peller - when you get to `dvStates`, can the new attribute please have the name `data-maq-appstates`? I'm working on the states reconciliation issue (#1547) and that name best matches the reconcilation approach I'm working on.

**Comment by JonFerraiolo** [comment]
@peller - Actually, could you _not_ migrate `dvStates` and let me do that as part of the states reconciliation issue (#1547)? I'm afraid of code collisions. I think it will save both of us time if you leave `dvStates` to me.

**Comment by peller** [comment]
Ok, that's fine.  It's a one-liner to change the value (`prototype.ATTRIBUTE`) though there are still _two_ instances of the AppStates.js file to modify.  I'm concerned about migration.  If we alter the AppStates.js file, will we need to manually replace the AppStates.js files in existing projects as part of our migration?  If so, perhaps we should only include dvStates back-compat code in the file we use for migration.  There's no point in including it in new projects.  I'd also question whether there is any point in keeping the `_upgrade_p4_p5` method.

**Comment by JonFerraiolo** [comment]
I think I have this all coded. I took care of migration of dvStates by making the new code look for both the old attribute name and also the new attribute _names_. Part of the task for #1547 is to have one attribute `data-maq-appstates` for the list of states, currently only available on BODY, and another for the per-widget CSS deltas using attribute `data-maq-deltas`.

The approach I took allows old user files (with dvStates) to work in preview-in-browser with the latest version of AppStates.js.

I'm also cleaning up the property names that are attached to the DOM nodes. In previous version, we were attaching a 'states' property to DOM nodes. This always made me uncomfortable because it seems like some other software might use that same property name. I've change the code to use a property that begins with `_maq`

**Comment by peller** [comment]
Would we be better off migrating the users' code and not carrying this forward in the AppStates.js code?  Is there any reason to keep the `_upgrade_p4_p5` method around anymore?

**Comment by peller** [comment]
Jon added some migration code here: 62c8999f0911a9f5c74caa92b31fb89c86f093d1  I'm still -1 on migration code going into Context.js

**Comment by jhpedemonte** [comment]
Is this still open to handle remaining cases?  If so, push to M8.

**Comment by peller** [comment]
nah, just thought there were migration issues, but @JonFerraiolo decided  to implement the migration code at runtime, so I think we're all set
