### ISSUE TITLE
Nightly build doesn't launch

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3341]
I downloaded last night's nightly standalone build and tried to double-click on the maqetta.server.mac.command launch script. A Terminal window opened with this message:

```
Last login: Mon Sep 10 09:35:32 on ttys001
$ /path/to/maqetta.server.mac.command ; exit;
Java version=1.6
maqetta.conf not found
logout

[Process completed]

```

**Comment by JonFerraiolo** [comment]
Also, need to switch the port back to 50000 (vs Orion default of 8080). 8080 will conflict with various other software out there, and the docs tell the user that we use port 50000 when running locally.

@doronrosenberg

**Comment by jhpedemonte** [comment]
Fixed with above commit.

**Comment by JonFerraiolo** [comment]
Reopening so we don't forget to test.

**Comment by jhpedemonte** [comment]
Much better now.  Closing.
