### ISSUE TITLE
Can't drop EdgeToEdgeDataList onto second view in this file

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3347]
Just noticed this on the staging server. With the following file open, I switched to the second scrollable view, and attempted to drop an EdgeToEdgeDatalist widget onto the blank part of canvas under the DIVs and above the fixed TabBar.

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'async':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}],'themeMap':[['Android','',['themes/iphone/iphone.css']],['BlackBerry','',['themes/blackberry/blackberry.css']],['iPad','',['themes/ipad/ipad.css']],['iPhone','',['themes/iphone/iphone.css']],['.*','',['themes/custom/custom.css']]],'mblThemeFiles':[], mblLoadCompatPattern: /\/project1\/themes\/.*\.css$/"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dojox/mobile",
  "dojox/mobile/deviceTheme",
  "dojox/mobile/compat",
  "dojo/hash",
  "dojox/mobile/ScrollableView",
  "dijit/form/Button",
  "dojox/mobile/TabBar",
  "dojox/mobile/TabBarButton",
  "dojox/io/xhrScriptPlugin",
  "dojo/data/ItemFileReadStore",
  "dojox/mobile/EdgeToEdgeDataList",
  "dojox/mobile/Button"
]);
</script>
<style>@import "themes/claro/claro.css";@import "lib/dojo/dojox/mobile/themes/common/domButtons/DomButtonRedBadge.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"></meta>
</head>
<body data-maq-flow-layout="true" data-maq-ws="collapse" data-maq-device="iphone" class="claro" id="myapp" data-maq-appstates="{}">
 <div data-dojo-type="dojox.mobile.ScrollableView" id="v0" keepScrollPos="false" scrollBar="true" style="display: none;">
 <h1 label="My Mobile App" data-dojo-type="dojox.mobile.Heading"></h1>
   <ul data-dojo-type="dojox.mobile.RoundRectList">
<li data-dojo-type="dojox.mobile.ListItem">

       News</li>
<li data-dojo-type="dojox.mobile.ListItem" moveTo="v1">
       Alerts</li>
     <li data-dojo-type="dojox.mobile.ListItem">
       Status</li>
   </ul>
   <input type="button" data-dojo-type="dijit.form.Button" intermediateChanges="false" label="Button" iconClass="dijitNoIcon"></input>
 </div>
 <div data-dojo-type="dojox.mobile.ScrollableView" id="v1" keepScrollPos="false" scrollBar="true" selected="selected">
  <h1 label="Alerts" data-dojo-type="dojox.mobile.Heading" back="Home" moveTo="v0"></h1>
  <div style="margin: 1em;">
  Today's alerts:</div>
  <div style="margin: 1em;">
    10:30am 80% capacity </div>
  <ul data-dojo-type="dojox.mobile.TabBar" fixed="bottom">
    <li label="Tab 1" data-dojo-type="dojox.mobile.TabBarButton" icon1="samples/sample_data/images/i-icon-1.png" icon2="samples/sample_data/images/i-icon-1.png" selected="selected"></li>
    <li label="Tab 2" data-dojo-type="dojox.mobile.TabBarButton" icon1="samples/sample_data/images/i-icon-2.png" icon2="samples/sample_data/images/i-icon-2.png"></li>
    <li label="Tab 3" data-dojo-type="dojox.mobile.TabBarButton" icon1="samples/sample_data/images/i-icon-3.png" icon2="samples/sample_data/images/i-icon-3.png"></li>
  </ul>
</div>
</body>
</html>

```

**Comment by doronrosenberg** [comment]
Was there an exception?

**Comment by JonFerraiolo** [comment]
=> M8 Too risky to fix at this point.

I figured out what is going on. The problem is that the widget hierarchy and the DOM hierarchy are not parallel, but the code expects the two hierarchies to be the same. You see, with ScrollableView, when there is a widget that is fixed to top or bottom, ScrollableView alters the DOM tree so that the header and/or footer widgets are outside all of the other widgets, and the remaining widgets are in a DIV with class ScrollableViewContainer or something like that.

Simpler case: 
- New Mobile App
- Add a ScrollableView
- Add a TabBar, set fixed=bottom
- Try to add an EdgeToEdgeDataList

Result=> Dies at ve/_Widget.js:201

**Comment by JonFerraiolo** [comment]
-> M7.0.1, at least for investigation

**Comment by JonFerraiolo** [comment]
Reopening - problem has returned in today's M701 build on the testing server.

**Comment by JonFerraiolo** [comment]
I think we need to update the addChild() method in ve/_Widget.js to look for and use helper.addChild if it is available instead of directly adding the node as in:

```
containerNode.insertBefore(child.domNode, children[index].domNode);
```

and

```
containerNode.appendChild(child.domNode);
```

**Comment by JonFerraiolo** [comment]
More info: 

I see that ItemFileReadStore ends up being a generic widget (going through class _Widget.js) and not a Dijit widget (i.e., going through class DijitWidget). This causes the following logic in DijitWidget.js:addChild() to fail this check:

```
        if (this.dijitWidget.addChild && child.dijitWidget) {
```

**Comment by jhpedemonte** [comment]
If I recall correctly, I think a lot of the stores (and other non-UI widgets) are treated as "object" widgets, rather than "dijit" widgets.

**Comment by JonFerraiolo** [comment]
Possible movement towards fix is in branch 3347DataListInScrollableView, with first commit being 7c9d2553aebf843b5ca790286a36d7de3fcbc9c0. THAT COMMIT IS AN INCOMPLETE IMPLEMENTATION. It changes the signature on the addChild helper function. Several other addChild helpers still need to be updated to reflect the new signature. @billreed63 - internal helpers might also be affected.

**Comment by JonFerraiolo** [comment]
Also, I noticed that the "index" used in ScrollableViewHelper isn't always adjusting things to take into account child order number. It works fine if adding to the end, but if dragging/dropping widgets into the middle of ScrollableView, it sometimes places the new widget at the wrong drop point.

**Comment by doronrosenberg** [comment]
Could we perhaps add some metdata flag to ScrollableView to say "always let me handle adding of children, no matter what widget is being dropped"?  That would localize the change to ScrollableView without having to change other helpers

**Comment by JonFerraiolo** [comment]
For M8, I say clean up the code and fix all of the helpers. 

For 701, if we want to localize changes for M701 so that we only change ScrollableView's addChild method, then I would suggest temporarily adding a helper with a different name or something like that for M701 or temporarily putting an IF statement in _Widget.js or whatever to do special-case logic if widget.type==dojox.mobile.ScrollableView or something like that.
