### ISSUE TITLE
Download as zip: getOnUnloadWarningMessage

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3352]
Using Chrome on Mac going to staging server... Not sure this exception has any impact, but opening as Prio High for assessment...
1. Select file in files palette
2. Right-click and choose Download
3. Click OK on download dialog
4. See exception below, but download starts and completes

```
Uncaught TypeError: Object [object Object] has no method 'getOnUnloadWarningMessage' davinci.js:22823
_107c.run davinci.js:22823
```

**Comment by jhpedemonte** [comment]
-> M8

**Comment by JonFerraiolo** [comment]
-> @aerwin M8 Prio-High

**Comment by billreed63** [comment]
No seeing this with the latest code or maqetta.org
Version: 7
Date: Nov 11, 2012 8:45:31 PM
Build: c7a79624a47c023...
