### ISSUE TITLE
Annotations not displayed correctly - user compare problem

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3355]
User name comparisons aren't working sometimes in review/commenting. What's going on is that the annotations are storing a single letter username like B or G, and somehow or other the letter assigned to the current user doesn't match the letter assigned when the annotation is created. For example, on staging server, there are two users, let's call them USER1 and USER2. When the invite goes out, USER1 is B and USER2 is G. But then when USER1 attempts to add an annotation, now he is C, which isn't either B or G, so his own annotations are filtered.

.

**Comment by JonFerraiolo** [comment]
Pushing to M8.

@childsb 

I'm not sure why the single letter usernames are different at different times. The server code for listVersions calls user.getUserID() which goes to the person manager (which I assume is Orion code) where returns the "username" field. I'm not sure if that ends up being the same username that Orion uses as the unique ID or the username field that might be something like "Mike Smith".

Nevertheless, I see how to make this more robust by changing everything to use emails rather than usernames. Involves changing multiple places:
- In CommentView.js:641 and two other places (669, 955), where event enableEditing is published, we need to add another parameter to payload: `Runtime.userEmail`
- In Context.js:165, we need to add an addition argument for `reviewerEmail` somewhere around line 173, add `surface.currentReviewerEmail = reviewerEmail;`
- In ArrowAction.js, EllipseAction.js, RectAction.js and TextAction.js, add `reviewerEmail:surface.currentReviewerEmail,`
- (this is one sketchier) Modify all code that uses "coloraliases" to use email addresses instead. In other words, use email addresses instead of IDs. A grep found these lines:

```
$ grep -rni coloraliases *
editor/Context.js:227:           connect.subscribe(this.fileName+"/davinci/review/drawing/setShownColorAliases", dojo.hitch(this,function(colorAliases) {
editor/Context.js:229:               surface.filterColorAliases = colorAliases;
editor/Context.js:287:                  dojo.some(surface.filterColorAliases, function(colorAlias) {
view/CommentView.js:909:        dojo.publish(this._currentPage+"/davinci/review/drawing/setShownColorAliases", [reviewers]);
$ 

```

**Comment by JonFerraiolo** [comment]
@aerwin

**Comment by JonFerraiolo** [comment]
@jhpedemonte 

Moving to 7.0.1 for evaluation at least. Might be too involved and too risky to attempt to fix in such a short release cycle, though.

**Comment by aerwin** [comment]
--> @aerwin

**Comment by aerwin** [comment]
@JonFerraiolo 

I don't know how to get the user id's to change, but I think I found a way to simulate it. It seems that `PersonManager` on the server only works with users that have logged in since the last time the server was started. So, if I restart the server, user id's for all of the reviewers (that haven't re-logged in) are "", so they don't match the user id's in comments. I'm going to open separate issues for that.

**Comment by aerwin** [comment]
Closing with above commit.
