### ISSUE TITLE
Change the way style elements are rendered in the source tab

### ISSUE THREAD

**Issue by aditya0901** [maqetta/maqetta#3358]
Hi,
I'm trying to create custom widgets and adding style elements to it in maqetta. The sourse tab is getting populated with the style element as...

``` html
<button style="position: absolute; z-index: 900; width: 82px; height: 50px; left: 55px; top: 24px;">
   Button</button>
```

However i want this to be rendered as 

``` html
<button position="absolute" z-index="900" left="55px" top="24px" width="82px" height="50px">Button</button>
```

is there any way to perform this change?
Please help!

Thanks.

**Comment by jhpedemonte** [comment]
(@aditya0901, when pasting in HTML code, make sure to wrap it in lines that have three back-ticks.  Click on the link on this page named "GitHub Flavored Markdown" to see more info.  I've updated the summar to properly show your HTML content.)

-> M8, High, so we answer this soon.  @JonFerraiolo

**Comment by JonFerraiolo** [comment]
The proposed HTML markup:

```
<button position="absolute" z-index="900" left="55px" top="24px" width="82px" height="50px">Button</button>
```

isn't valid HTML. Maqetta generates actually executable HTML (i.e., the pages the Maqetta creates will actually run in the browser) and therefore Maqetta has to create code that the browsers will understand. Things that are CSS properties like 'position', 'z-index', and 'top' have to be defined either within the 'style' attribute (e.g., `style="position:absolute; z-index:900;"`) or in a CSS style sheet. The browsers won't process CSS properties that are expressed as HTML attributes (i.e., this won't work: `position="absolute") except in rare cases, and most of those rare cases have been officially deprecated.

Note that SVG **does** support CSS properties as attribute (e.g., `<text font-size="14px" color="blue">abc</text>`) but that syntax approach was never adopted by the HTML side of the world.

Closing this issue.
