### ISSUE TITLE
Need to update new Dojo 1.8 dojox.mobile icons on widget palette

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3361]

**Comment by JonFerraiolo** [comment]
@jhpedemonte moved to 7.0.1 (in case we do a 7.0.1) since this change is trivial and low risk and would make @jinsil happy

**Comment by jinsil** [comment]
I should point out where all the icons are.. it is all my fault.. I will make sure to let you know what/where you can find..
Thank YOU!!!!

**Comment by JonFerraiolo** [comment]
verified that the widget icons are indeed there in today's build
