### ISSUE TITLE
Download selected files should only download selected files

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3364]
@aerwin (sorry if this is dupe - github search isn't working very well right now)

In testing the context menu on the Files palette, I selected only one file and said "download". Up comes a dialog showing all of the libraries. I unchecked the libraries and clicked OK. In addition to selected files, I also got:
- all of the themes
- all of the samples
  - lib/zazl
- lib/maqetta

**Comment by jhpedemonte** [comment]
This is a fallout of @childsb's "required libs" fix.  We didn't think about this.
- The 'maqetta' lib **must** be downloaded for things to work.
- 'zazl' shouldn't be downloaded at all.
- 'samples' should probably be an option to download.
- Not sure how best to handle 'themes'.

**Comment by JonFerraiolo** [comment]
-> M9 Prio-Med

@jhpedemonte

**Comment by JonFerraiolo** [comment]
-> @peller M9 Prio-High

@peller - could you please take this on for the M9 timeframe? What I recommend is:
- The first icon (download entire workspace) simply change its wording to say download entire project
- The second icon and the context menu Download command should simply ZIP up selected files and not include libraries, samples or anything else that isn't selected

The reason why I'm making this request (and elevating priority) is that we have users who want to exchange files with each other, including custom widgets. With the way Maqetta works today, it's not really feasible for mortal users to create a ZIP of just a particular set of files (e.g., a custom widget or a custom theme). 

The other side of the equation is #344 - ability to upload a ZIP
