### ISSUE TITLE
Delay for editor to open making it seem like user action didn't register

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3365]
Opening against M8...

Using Chrome on Mac going to staging server...

Mentioned this to @JonFerraiolo yesterday, and I think he had been seeing it too...

Basically, when starting from the welcome page, there's a noticeable delay (multiple seconds) before anything happens when double-clicking file in the palette, creating new file, etc. Finally, the page editor opens with the loading indicator in it.

I'm certain up until very recently, the editor and loading indicator came up fairly quickly. Sometimes I wonder if my action was ignored or there's an exception or something somewhere, but then finally editor comes up.

**Comment by JonFerraiolo** [comment]
-> @peller

**Comment by jhpedemonte** [comment]
Yes, the tab for that page/editor should come up immediately and show wait indicator, so user knows that something is happening.

**Comment by peller** [comment]
dup of #3168
