### ISSUE TITLE
ThemeSets - applying custom themeset to mobile page doesn't work, requires reload

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#3366]
@jhpedemonte @JonFerraiolo 
- Create a claro clone called claro2.  Change bg color to say green.
- Create a custom clone called custom2, change bg color to red.
- Create a custom themeset and use claro2/custom2.
- Create a mobile iphone page, change to the custom themeset.
- dnd a header.

Header is the default claro look.  Reload page and now the page is red like it should be.

**Comment by jhpedemonte** [comment]
It's working for me.

**Comment by doronrosenberg** [comment]
Oh wait I was using Firefox, could that have been it?

**Comment by jhpedemonte** [comment]
Perhaps?  I tested on Chrome.  Deferring to @billreed63 on this one.

**Comment by doronrosenberg** [comment]
Reproduced this on Chrome as well.

**Comment by billreed63** [comment]
I can't reproduce this on chrome/win 7 do you have the debugger open?

**Comment by jhpedemonte** [comment]
@billreed63, he saw this on Firefox.

**Comment by doronrosenberg** [comment]
I saw it on chrome, but I think this is user confusion

**Comment by doronrosenberg** [comment]
Chrome on windows:
- Create a new theme called iphonegbug based on the iphone theme.
- Change the page background color to red
- Change the heading background to green.
- Create a ThemeSet called bug.  For iPhone select iphonebug
- Create a new iphone page
- Drag and drop a Heading
- Go to switch theme and select the bug ThemeSet.  Press ok.  I don't see any changes until I reload.  This is on moketta

**Comment by billreed63** [comment]
dup #3483 which was fixed
