### ISSUE TITLE
states - can't change CSS across states

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#3368]
1) new html file
2) add a calendar widget
3) add 2 buttons
4) create 2 states
for state 1, set the calendars background to a color
for state 2 set the calendars background to another color

notice that when you swtich between states to try and change the color, the color always remains the same.

**Comment by JonFerraiolo** [comment]
Closing. I tried various scenarios and everything worked for me with 701 as released on Maqetta.org. I tried the above scenario not only with Calendar, but also with a dijit TextBox, and the background color changes properly when changing states so long as you set the "apply to this state only" checkbox prior to changing the background-color value.
