### ISSUE TITLE
tar.bz vs zip: investigate winzip

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3371]
(Prio-High just in case this turns out to be a significant problem for some users)

When I used WinZip to decompress one of our nightlies, all of the JARs decompressed and it took a really long time to finish (like an hour). Was this just misoperation of WinZip or something else?

**Comment by JonFerraiolo** [comment]
@childsb 

OK, I figured out what's going on, sending to @jhpedemonte with Prio-Low

WinZip is preserving the JARs. The issue here is that all of the Eclipse projects (e.g., maqetta.core.client) end up in the archive as exploded folders instead of JARs. With Preview6 and earlier, the Eclipse projects end up in the archive as JARs.

The very slow decompress on Windows is due to the zillions of separate files, and the slowness of WinZip and Windows, with maqetta.core.client probably being the chief culprit.

**Comment by jhpedemonte** [comment]
@peller, we kept some of those directories out of JARs for performance reasons, wasn't it?

**Comment by peller** [comment]
yes, that's right.  Otherwise, Equinox has to explode them or search them on demand.  Not good, especially for static content.  Plugins with static content (generally the larger ones) are not packaged in jars, others are still in jars.

**Comment by jhpedemonte** [comment]
All Maqetta bundles are now JARed, not "exploded".  Closing.
