### ISSUE TITLE
Deadlock in EclipsePreferences (Maqetta server hangs)

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3374]
Every so often, the Maqetta server stops accepting connections.  Saw it this morning on the new maqetta.org.  Here's one line from Nginx server log:

> 2012/09/13 15:42:51 [error] 5254#0: *354114 upstream timed out (110: Connection timed out) while reading response header from upstream, client: XXX.XXX.XXX.XXX, server: app.maqetta.org, request: "GET /maqetta/ HTTP/1.1", upstream: "http://127.0.0.1:8080/maqetta/", host: "app.maqetta.org", referrer: "http://app.maqetta.org/mixloginstatic/LoginWindow.html?redirect=../maqetta/"

Thing is, I could load the **login page** just fine. After entering my credentials, though, the browser just looped.  Only recourse was to restart Maqetta server.

So part of the server (login page) is accessible, but nothing beyond that.  Unfortunately, didn't think of trying to load Orion Navigator when in this state.

Can anyone think of how the server could get into such a situation?

@aerwin, you've successfully setup remote debugging of the Maqetta server.  Can you please post (or email) directions on how to do this?  Maybe we can try that next time the server gets into this state, to at least see what's going on.

@JonFerraiolo @peller

**Comment by peller** [comment]
M7.0.1?

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte

**Comment by jhpedemonte** [comment]
Happened again just now.  Could load LoginWindow, but redirect back to app.maqetta.org/maqetta/ just hangs.

Tried to go to Orion Navigator (app.maqetta.org/):  that showed some of the Orion UI, but with a message that said "Loading...".  So that was also hung.

@aerwin

**Comment by jhpedemonte** [comment]
@peller, could this be memory issues again?  I don't see any errors pointing to that in the log files (although I'm not sure if there would be any).  We are running with the flag `-Xmx768m`.

First hang, the app was up for 16 hours.  Next one, almost 26 hours.

**Comment by jhpedemonte** [comment]
Happened again.

Hung:

```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
28626 maqetta   18   0 5351m 547m  12m S  0.0 26.7  37:53.62 java
```

Fresh restart:

```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
17912 maqetta   20   0 3747m 342m  12m S  0.7 16.7   0:31.00 java
```

There seems to have also been a sizeable increase in the number of threads.  May be purely coincidental, but it did decrease when I restarted Maqetta:

![number of threads](http://i.imgur.com/0uSYn.png)

There was also a similar spike in "inode table usage", but it wasn't as clear as in the above chart.

**Comment by jhpedemonte** [comment]
Maqetta gets deadlocked, trying to handle Eclipse Preferences.  See the [jstack dump files](https://gist.github.com/3721431).

**Comment by jhpedemonte** [comment]
Found this [Equinox bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=359698), which [removes `synchronized`](http://git.eclipse.org/c/equinox/rt.equinox.bundles.git/commit/?id=2607f050eb20c418a2b56437cdb388a397ebc207) from EclipsePreferences.flush() call.

Looks like it was fixed in **3.7.2**.  But in plugins I see **org.eclipse.equinox.preferences_3.5.0.v20120522-1841.jar**.  Guess we need to build on a newer version of Equinox.

**Comment by skaegi** [comment]
The version of the platform might be 3.7.2 but that version of preferences looks to me to be current -- see http://git.eclipse.org/c/equinox/rt.equinox.bundles.git/tree/bundles/org.eclipse.equinox.preferences/META-INF/MANIFEST.MF -- looking at stack now...

**Comment by skaegi** [comment]
that call in internalFlush 453 seems incredibly risky to me as it changes lock direction for parent->child to child->parent. Log this against Equinox and I can help bring it to their attention

**Comment by skaegi** [comment]
http://git.eclipse.org/c/equinox/rt.equinox.bundles.git/tree/bundles/org.eclipse.equinox.preferences/src/org/eclipse/core/internal/preferences/EclipsePreferences.java -- line 453

**Comment by jhpedemonte** [comment]
Opened bug on Eclipse: https://bugs.eclipse.org/bugs/show_bug.cgi?id=389630

**Comment by jhpedemonte** [comment]
@childsb has suggested that we add `synchronize` to `maqetta.server.orion.user.OrionUserManager.getUser()`, implying that it might lessen (but not totally fix) the impact of this deadlock.

I'm not fully convinced, though.  One of the code paths for the deadlock does indeed show that method.  And all of the blocked threads (waiting on semaphore) go through that method.

However, the other side of the deadlock doesn't go through Maqetta code at all -- it's a straight user creation call directly into Orion.

So I'm skeptical that this "workaround" would help at all.

**Comment by peller** [comment]
Right, we probably couldn't work around this in Maqetta, but we could perhaps see if Orion could synchronize the two methods leading to this deadlock (or any others calling into preferences code) `org.eclipse.orion.internal.server.servlets.workspace.WebUser.fromUserName` and `org.eclipse.orion.internal.server.servlets.workspace.authorization.AuthorizationService.saveRights`.  I guess it depends on what sort of turnaround we might get on the Equinox bug.

@skaegi

**Comment by jhpedemonte** [comment]
The Eclipse bug has been fixed.  However, a new version of Equinox with that fix won't come out for a while.

Given that, the Orion team has implemented a [workaround](http://git.eclipse.org/c/orion/org.eclipse.orion.server.git/commit/?id=256f45c3daf7f3bd6ec24cc3cb1168ada4d56054) in their code.  Unfortunately, this is for Orion v1.0;  we're built on top of Orion v0.5.

Some options:
1. Convince Orion to backport workaround to v0.5 (v0.5.1?).
2. Fork Orion v0.5 ourselves and backport workaround, changing URLs in map files to point to forked URL.

**Comment by jhpedemonte** [comment]
After building with the deadlock workaround in Orion 0.5, users cannot switch between projects in Maqetta.  The workbench state (which includes the current project) isn't getting saved within the Eclipse preference store.  Currently investigating.

@JonFerraiolo

**Comment by jhpedemonte** [comment]
Added calls to `flush()` after instances of `IEclipsePreferences.put()`.  This matches what the Orion code seems to be doing.  Also, this fixes the [issue with switching projects](https://github.com/maqetta/maqetta/issues/3374#issuecomment-8902113).

**Comment by jhpedemonte** [comment]
Closing for now.
