### ISSUE TITLE
"@revision@" in requests

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3376]
I'm seeing a lot of requests which contain the string `@revision@`, which implies that it wasn't properly substituted during the build.

Some samples:

/maqetta/app/davinci/workbench.css?@revision@
/maqetta/app/davinci/ve/resources/content.css?@revision@
/maqetta/app/davinci/review/resources/Comment.css?@revision@
/maqetta/app/dojox/grid/nls/DataGrid_en-us.js?@revision@
/maqetta/app/metadata/dojo/1.8/callbacks.js?@revision@
/maqetta/app/metadata/html/0.8/html/table/TableAction.js?@revision@

Correct:

/maqetta/app/metadata/dojo/1.8/package.json?f940814741d832335cf203555c0e7236f56925ad
/maqetta/app/metadata/dojo/1.8/widgets.json?f940814741d832335cf203555c0e7236f56925ad
/maqetta/app/metadata/dojo/1.8/dojox/mobile/Heading_oam.json?f940814741d832335cf203555c0e7236f569

@peller

**Comment by peller** [comment]
The [custom ant code](https://github.com/maqetta/maqetta/blob/master/maqetta.core.client/customBuildCallbacks.xml#L44) replaces the pattern `@revision@` in welcome.html and pagedesigner.html.  We need to apply a similar ant rule to the equivalent HTML file for Maqetta-Orion integration

**Comment by peller** [comment]
looks like that would be maqetta.client.orion which has a copy of WebContent/pagedesigner.html (also preview.html, testbed.html and welcome.html, which probably should be removed)

@jhpedemonte @childsb @aerwin

**Comment by JonFerraiolo** [comment]
I verified with today's build that the files that had @revision@ in original bug report now have a proper version string
