### ISSUE TITLE
Investigate creating projects with dot in name

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3384]

**Comment by jhpedemonte** [comment]
Or any other character.  We should properly escape the name, as necessary.

**Comment by JonFerraiolo** [comment]
In the particular user scenario that instigated this issue, turns out his project was named ".".

**Comment by JonFerraiolo** [comment]
Above comment doesn't apply to this issue. Please ignore.

**Comment by JonFerraiolo** [comment]
Closing. I tested `foo.bar`, `.foo`, and `foo.` and everything works fine. Only issue is when the project name is just a `.`
