### ISSUE TITLE
Validate username to conform to email address syntax

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3385]

**Comment by JonFerraiolo** [comment]
On login screens...

**Comment by JonFerraiolo** [comment]
Our old welcome.html used a dojo widget (ValidationTextBox) with this regexp: `regexp="^\w(\w|[.@]){4,20}$"`. Right now we aren't including Dojo for our login screens. Regarding the regex, the HTML5 spec provides this regex for email validation: `/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:.[a-zA-Z0-9-]+)*$/`

This could be accomplished trivially by simply putting a `type='email'` on the appropriate INPUT element, but Safari 5.1 doesn't yet support that feature (nor `type='pattern'`).

**Comment by JonFerraiolo** [comment]
ab941580f2bf7c724afd57e71a32cbbb93ccc0ff

Should address #3384 (email validation on login forms). Committing now but not closing until testing against builds.

**Comment by JonFerraiolo** [comment]
verified on *standard and *hosted, still need to check on the internal hosted build

**Comment by jhpedemonte** [comment]
One thing I forgot here:  need to allow "admin" user name.

**Comment by JonFerraiolo** [comment]
I moved the "admin" part into a separate issue: #3471

**Comment by JonFerraiolo** [comment]
verified on internal build, closing
