### ISSUE TITLE
EdgeToEdgeDataList inside a tabcontainer - cut/psate of tabcontainer throws error

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#3386]
@JonFerraiolo @jhpedemonte @aerwin 
- dnd a tabcontainer
- dnd a EdgeToEdgeDataList into the first tab
- cut the container, paste it

```
Error: Tried to register widget with id==ul_1 but that id is already registered
http://192.168.1.126:8081/maqetta/user/A/ws/workspace/sdsd/lib/dojo/dijit/dijit.js
Line 15
```

The ul_1 is part of the EdgeToEdgeDataList.  The page seems to work fine even with the exception but that isn't a good thing.  

Seems we are not destroying things correctly during the cut, which might be the cause of random failures we sometimes see where widgets can't be selected/etc.

Thoughts before I dig into this?

**Comment by JonFerraiolo** [comment]
> Thoughts before I dig into this?

No, I agree that this should at least be investigated ASAP to see if there is a more general, deeper bug.

**Comment by doronrosenberg** [comment]
@jhpedemonte @JonFerraiolo 

So CutAction does a RemoveCommand on the widget we are cutting, but it seems that we are leaking the EdgeToEdgeDataList and the TabContainer here since we never destroy any of the widgets.  It would seem that adding a dijitWidget check and calling destroyRecursive is in order, but wanted to get insight from you guys since I don't know much about widget lifecycles.

**Comment by JonFerraiolo** [comment]
I'm looking at this.

I traced through the code myself and I see that ultimately RemoveCommand calls widget.destroy, which for a TabContainer ends up at ve/_Widget.js:771, which does indeed call `this.dijitWidget.destroyRecursive()`. So, we are definitely _attempting_ to remove the widgets.

**Comment by doronrosenberg** [comment]
@JonFerraiolo Then something is failing in destroyRecursive as after `widget.destroyWidget` I still can run `Widget.byId("ul_0")` and get the widget.

**Comment by JonFerraiolo** [comment]
I have a theory about what's wrong. I think there are two things that are both attempting to remove the DOM nodes. First, the removeChild() function in Maqetta does two things: (1) remove node from DOM, (2) remove node from the model. This gets called from RemoveCommand.js:48. Then we call widget.destroyWidget() at line 55. This ultimately calls into dojo to do a destroyRecursive(), which also attempts to destroy the same DOM node(s) that RemoveCommand.js has already removed.

**Comment by doronrosenberg** [comment]
It seems to me based on some debugging that the issue is quite different - we seem to be registering the `<ul>` EdgeToEdgeList (none-data one works as well and is simpler) twice, my guess based on a the trace is content pane is re-parsing its content after we created the child widget for it.

@peller any thoughts from dojo land?  Content panes scare me.

**Comment by peller** [comment]
where is the contentpane in relationship to edgetoedgelist, and is it a dojox content pane supporting the parser or a dijit one which does not?

**Comment by doronrosenberg** [comment]
TabContainer -> ContentPane -> EdgeToEdge

Content pane is the regular dijit one

**Comment by peller** [comment]
Oh, right.  That ContentPane is simply a container and shouldn't be running the parser, unless Maqetta is hooking anything special to ContentPanes... I don't believe it is.

**Comment by doronrosenberg** [comment]
@peller 

```

parse(rootNode=Object { rootNode=div#div_2.dijitContentPane, noStart=true, inherited={...}, more...}, options=undefined)parser.js (line 815)
_parse()html.js (line 309)
onEnd()html.js (line 249)
set(cont=DocumentFragment { constructor=DocumentFragment, nodeName="#document-fragment", nodeType=11, more...}, params=Object { extractContent=false, parseContent=true, parserScope="dojo", more...})html.js (line 148)
_setContent(cont=DocumentFragment { constructor=DocumentFragment, nodeName="#document-fragment", nodeType=11, more...}, isFakeContent=undefined)ContentPane.js (line 545)
_setContentAttr(data=DocumentFragment { constructor=DocumentFragment, nodeName="#document-fragment", nodeType=11, more...})ContentPane.js (line 301)
set(name="content", value=DocumentFragment { constructor=DocumentFragment, nodeName="#document-fragment", nodeType=11, more...})_WidgetBase.js (line 762)
_applyAttributes()_WidgetBase.js (line 441)
create(params=Object { content=DocumentFragment, id="div_2", title="Tab 1", more...}, srcNodeRef=div#div_2.dijitContentPane)_WidgetBase.js (line 364)
inherited(args=[Object { content=DocumentFragment,  id="div_2",  title="Tab 1",  more...}, div#div_2.dijitContentPane], a=[Object { content=DocumentFragment,  id="div_2",  title="Tab 1",  more...}, div#div_2.dijitContentPane], f=function())declare.js (line 189)
create(params=Object { content=DocumentFragment, id="div_2", title="Tab 1", more...}, srcNodeRef=div#div_2.dijitContentPane)ContentPane.js (line 157)
postscript(params=Object { id="div_2", title="Tab 1", extractContent=false, more...}, srcNodeRef=div#div_2.dijitContentPane)_WidgetBase.js (line 299)
chainedConstructor()declare.js (line 390)
construct(ctor=function(), node=div#div_2.dijitContentPane, mixin=Object { title="Tab 1", extractContent=false, preventCache=false, more...}, options=Object { noStart=true}, scripts=[], inherited=undefined)parser.js (line 425)
(?)(obj=Object { node=div#div_2.dijitContentPane, types=[1]})parser.js (line 170)
map(arr=[Object { node=div#div_2.dijitContentPane,  types=[1]}], callback=function(), thisObject=Object { _clearCache=function(), _functionFromScript=function(), instantiate=function(), more...}, Ctr=undefined)array.js (line 278)
_instantiate(nodes=[Object { node=div#div_2.dijitContentPane,  types=[1]}], mixin=Object { title="Tab 1", extractContent=false, preventCache=false, more...}, options=Object { noStart=true})parser.js (line 171)
instantiate(nodes=[div#div_2.dijitContentPane], mixin=Object { title="Tab 1", extractContent=false, preventCache=false, more...}, options=Object { noStart=true})parser.js (line 138)
constructor(mixin=Object { title="Tab 1", extractContent=false, preventCache=false, more...}, node=div#div_2.dijitContentPane, dijitWidget="dijit.layout.ContentPane", metadata=Object { id="http://dojotoolkit.org/dijit/layout/ContentPane", name=dijit.layout.ContentPane", spec="1.0", more...}, srcElement=Object { elementType="HTMLElement", startOffset=0, endOffset=0, more...})DijitW...vision@ (line 56)
chainedConstructor()declar...vision@ (line 384)
createWidget(widgetData=Object { type="dijit.layout.ContentPane", properties={...}, tagName="div", more...})widget...vision@ (line 551)
(?)(c=Object { type="dijit.layout.ContentPane", properties={...}, tagName="div", more...})widget...vision@ (line 521)
forEach(arr=[Object { type="dijit.layout.ContentPane",  properties={...},  tagName="div",  more...}, Object { type="dijit.layout.ContentPane",  properties={...},  tagName="div",  more...}], callback=function(), thisObject=undefined)array....vision@ (line 244)
createWidget(widgetData=Object { type="dijit.layout.TabContainer", properties={...}, tagName="span", more...})widget...vision@ (line 505)
```

**Comment by doronrosenberg** [comment]
I guess the question is why is there a content attribute I assume

```
set(name="content", value=DocumentFragment { constructor=DocumentFragment, nodeName="#document-fragment", nodeType=11, more...})_WidgetBase.js (line 762)
```

**Comment by doronrosenberg** [comment]
```
create(params=Object { content=DocumentFragment, id="div_2", title="Tab 1", more...}, srcNodeRef=div#div_2.dijitContentPane)ContentPane.js (line 157)
postscript(params=Object { id="div_2", title="Tab 1", extractContent=false, more...}, srcNodeRef=div#div_2.dijitContentPane)_WidgetBase.js (line 299)

```

Weirdly enough, params in postscript has no content, yet in create it does.  Will debug furthur

**Comment by doronrosenberg** [comment]
dijit/Layout/ContentPane.js

```
 create: function(params, srcNodeRef){
// Convert a srcNodeRef argument into a content parameter, so that the original contents are
// processed in the same way as contents set via set("content", ...), calling the parser etc.
// Avoid modifying original params object since that breaks NodeList instantiation, see #11906.
if((!params || !params.template) && srcNodeRef && !("href" in params) && !("content" in params)){
  srcNodeRef = dom.byId(srcNodeRef);
  var df = srcNodeRef.ownerDocument.createDocumentFragment();
  while(srcNodeRef.firstChild){
    df.appendChild(srcNodeRef.firstChild);
  }
  params = lang.delegate(params, {content: df});
}
this.inherited(arguments, [params, srcNodeRef]); 
```

Looks like extractContent no longer works in 1.8.

**Comment by peller** [comment]
Ok, looks like I'm a couple of revs behind.  Dijit may not have had this functionality when the visual editor was written.

**Comment by doronrosenberg** [comment]
@jhpedemonte @JonFerraiolo 

So looks like we need to add parseOnLoad=false to contentpane, but make sure that it isn't written to the source.  It looks like if you paste a tabContainer, CreateTool::create or _create aren't called for the contentpane.

Looks like I would have to create a new helper method to do some massaging of getData() results, unless there happens to be a way that isn't documented in the Helper docs?

**Comment by JonFerraiolo** [comment]
I verified that this bug is still fixed in today's build
