### ISSUE TITLE
Should download entire workspace be download entire project?

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3389]
To reflect the fact that it's only going to provide what's in the current project?

@JonFerraiolo @aerwin

**Comment by aerwin** [comment]
@peller +1

**Comment by jhpedemonte** [comment]
Yes.

**Comment by aerwin** [comment]
Also, a while back I had opened #2938 to change the default file name from workspace.zip .

**Comment by peller** [comment]
-> M9/Med
