### ISSUE TITLE
deleting project doesn't work

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3390]
with multiple projects on the workspace, hit the delete project button.
the workbench reloads with a different project selected, but the project you deleted is still there.

**Comment by jhpedemonte** [comment]
And everything looks fine if you look at it in the Orion Navigator?  All the expected files are there?

**Comment by peller** [comment]
yah, still there

**Comment by jhpedemonte** [comment]
@peller, still seeing this?

**Comment by peller** [comment]
yup, still see it.

**Comment by jhpedemonte** [comment]
@peller, is this #3595?

**Comment by peller** [comment]
yes, it appears to be.  works fine now
