### ISSUE TITLE
Developer setup instructions - launch config - zazl project needed to be unchecked

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3393]
@childsb @jhpedemonte 

Setting to M7.0.1 Prio-High because I think we have a problem that will block folks on maqetta-devs, and I hope the fix is simple.

When I tried to follow the instructions on https://github.com/maqetta/maqetta/wiki/Maqetta-with-Orion-Developer-Setup to pull down from scratch onto a virgin computer, everything worked except that when I tried to run the "maqetta-orion multi user" launch script, I got an error about `maqetta.zazl.feature` having a dependency that Eclipse couldn't resolve. I had to uncheck the `maqetta.zazl.feature` so that I could actually run the server.

**Comment by peller** [comment]
what was the error?

**Comment by JonFerraiolo** [comment]
> what was the error?

Because the launch configuration has `maqetta.zazl.feature` checked by default, when you click run (or validate bundles), Eclipse tries to resolve dependencies, and the validation error dialog appears saying "Missing Constraint: Resource-Bundle: org.cyberneko.html...", and Eclipse will not launch the server.

**Comment by peller** [comment]
did you do the submodules update step?

**Comment by JonFerraiolo** [comment]
I did a set up on a virgin machine and indeed clicked on the "clone submodules" checkbox on the Import dialog.

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo after talking with @peller I will do some more investigation

**Comment by peller** [comment]
@rbackhouse This may or may not be related, but I noticed that org.cyberneko.html is used by another part of Maqetta (Orion?) and that we end up with two different versions of the cyberneko plugin in our download.

```
org.cyberneko.html_1.9.14.v201105210654.jar
org.cyberneko.html_1.9.15/
```

Perhaps egit is having trouble resolving the semantic versioning?  Is there a way we could reduce this so we only need one version of the plugin?  org.json may be a similar situation, except that Zazl's version was renamed so that it is treated as a separate entity.

**Comment by rbackhouse** [comment]
They should be able to co-exist as their Bundle-Version values in their Manifest are different. The Zazl code should work with either 1.9.14 or 1.9.15 so if you want to not include the one from the optimizer-dependencies submodule in the download that should be fine.

**Comment by rbackhouse** [comment]
RE org.json. I re-named to org.json.js to avoid the conflict with the org.json java bundle orion depends on. I did this a while back

**Comment by peller** [comment]
oh right, then the org.json.\* plugins really are unrelated, then (both happen to be 1_0_0)

Is it possible (or even a good idea) for Orion and Zazl to use the same version of cyberneko?  Yes, they do generally co-exist... _maybe_ this is all about eGit having some bug and being unable to do right thing looking for a version match.

**Comment by rbackhouse** [comment]
I would think they should be fine using the same version. There shouldn't be state (statics) shared between usage, at least from Zazl's perspective. 

Zazl's version should be under a different directory (/maqetta/zazl/dependencies) so I don't see why egit would have an issue.

**Comment by peller** [comment]
guess I was wondering if using the same version would trigger some osgi magic to have them actually share a copy... maybe not.

**Comment by rbackhouse** [comment]
The Zazl code references the cyberneko classes via OSGi package imports in its Manifest. There is not version reference so that means if either of the cyberneko bundles are loaded and resolved the Zazl code will use it. If Orion has prereq'd the 1.9.14 and that is the one loaded both orion and zazl will use it.

**Comment by JonFerraiolo** [comment]
Not a ship-stopper for M7_0_1, pushing to M8

**Comment by JonFerraiolo** [comment]
Pushing to M9.

When I tried to re-clone my workspace from scratch recently, I got the error from Run Configurations about zazl not being resolved, but the server launched nonetheless. Still need to make things work without the zazl error message, though.

**Comment by JonFerraiolo** [comment]
Closing. @jhpedemonte's various fixes eliminated this problem along the way.
