### ISSUE TITLE
Provide facility to get direct, non-preview URL for mobile pages

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3396]
When the user previews a mobile page from Maqetta, a new browser tab is opened with a URL like the following:

http://app.maqetta.org/maqetta/?preview=1&device=iphone&file=http%3A%2F%2Fapp.maqetta.org%2Fmaqetta%2Fuser%2FG%2Fws%2Fworkspace%2FphoneGapProject%2Ffile1.html

However, there are some use cases where it would be nice for the user to be able to easily get the direct, non-preview URL like: 

http://app.maqetta.org/maqetta/user/G/ws/workspace/phoneGapProject/index.html

(Of course, the info is in the preview URL, but in an encoded form.)

Use cases include:
- Using Ripple Emulator for PhoneGap previews
- Manually running Dojo Web Builder (which perhaps diminishes in importance once issues with Dojo Web Builder in our download dialog are fixed)
- Probably others

This might be a relatively simple thing to add to the mobile preview page itself. For example, when using the Mobile Browser Simulator from RAD, there's a field with the web page in it:

![GitHub Logo](https://www.ibm.com/developerworks/mydeveloperworks/blogs/MaqettaAuthoring/resource/BLOGS_UPLOADED_IMAGES/rad13MobileSimulatorShowingIPhone.png)

**Comment by JonFerraiolo** [comment]
@billreed63 

The hard part here is to figure out how to expose "preview without silhouette" in the Maqetta UI. I don't want to clutter to toolbar with another icon or turn the preview button into a dropdown button. Instead, here are my best suggestions:
- Add a preference to show mobile applications running inside of a device silhouette (with default of true)
- Option-click on preview icon causes preview to happen with the opposite value to what the current preference is (i.e., if silhouette preview is on, then preview would happen without using the silhouette)

**Comment by billreed63** [comment]
If the user sets the device type to "none" and then previews the page they get the URL without the preview
`http://app.maqetta.org/maqetta/user/Be/ws/workspace/tri_sec/m_index.html`

If we want to add the url of the page why not just add the URL of the preview to the Previews frame that displays the silhouette. We currently have the text device and zoom So just add a line above that states "Displaying: http://app.maqetta.org/maqetta/user/Be/ws/workspace/tri_sec/m_index.html" or something like that.

**Comment by aerwin** [comment]
@JonFerraiolo 

Any chance you think this would be low-risk enough to cherry pick for 7.0.2? I could use it for Part 3 of my article for sure. And, one of of @jhpedemonte 's comments on Part 1 was that I should mention to folks they can point their mobile browsers at their prototype. It would be a lot easier to do that if this fix were there (rather than tell them they need to change device top to none, preview, and use that URL).

**Comment by JonFerraiolo** [comment]
@aerwin @jhpedemonte - cherry-pick'd into M7 via above commit
