### ISSUE TITLE
EdgeToEdgeDataList Smart Input won't allow duplicate labels but JSON file does

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3410]
Using Chrome on Mac going to maqetta.org...
- Create mobile application
- Drag EdgeToEdgeDataList
- Enter data like the following and it renders fine:

```
128.5, details
130.5, details
```
- Bring smart input back up and add a 3rd row duplicating the second like so:

```
128.5, details
130.5, details
130.5, details
```
- Edge to edge data list goes to height 0 and no indication there's a problem. (NOTE: The data does not go away... if I go to outline to bring smart input back up the 3 rows are there)
- At first, I thought maybe this was a limitation of EdgeToEdgeDataList... but, if I create a JSON file with all sorts of duplicate labels (like below) and point the EdgeToEdgeDataList at it then things work fine:

```
// sample2.json
{
    "items": [
        {label: "128.5", moveTo: "details"},
        {label: "130.5", moveTo: "details"},
        {label: "131.3", moveTo: "details"},
        {label: "132.7", moveTo: "details"},
        {label: "128.5", moveTo: "details"},
        {label: "130.5", moveTo: "details"},
        {label: "128.5", moveTo: "details"},
        {label: "130.5", moveTo: "details"},
        {label: "128.5", moveTo: "details"},
        {label: "130.5", moveTo: "details"},
        {label: "128.5", moveTo: "details"},
        {label: "130.5", moveTo: "details"},
        {label: "128.5", moveTo: "details"},
        {label: "130.5", moveTo: "details"},
        {label: "128.5", moveTo: "details"},
        {label: "130.5", moveTo: "details"},
        {label: "128.5", moveTo: "details"},
        {label: "130.5", moveTo: "details"},
        {label: "128.5", moveTo: "details"},
        {label: "130.5", moveTo: "details"},
        {label: "128.5", moveTo: "details"},
        {label: "130.5", moveTo: "details"},
        {label: "128.5", moveTo: "details"},
        {label: "130.5", moveTo: "details"},
        {label: "128.5", moveTo: "details"},
        {label: "130.5", moveTo: "details"},
        {label: "128.5", moveTo: "details"},
        {label: "130.5", moveTo: "details"},
        {label: "128.5", moveTo: "details"},
        {label: "130.5", moveTo: "details"}  
    ]
}
```

**Comment by JonFerraiolo** [comment]
The bug here is that our code doesn't handle repeated lines. I'm not sure why, but that's the key factor. (OOPS - says same thing in bug title: )

**Comment by JonFerraiolo** [comment]
-> @aerwin - can you please investigate this bug that you discovered?

**Comment by aerwin** [comment]
@JonFerraiolo As a potential item for 7.0.1?

**Comment by jhpedemonte** [comment]
Unless this is an easy fix, I feel this can wait for M8.

**Comment by aerwin** [comment]
--> M7.0.1

Turns out fix is really simple, so might as well move into M7.0.1...

The `EdgeToEdgeDataListInput` was populating the data store with data of the form:

```
{'identifier':'label',
'items':[{'label':'Label 1','moveTo':'transitionToPage'},{'label':'Label 2','moveTo':'transitionToPage'}]}"
```

The inclusion of `'identifier':'label'` was the problem. So, just removed it (which matches the examples given in the Dojo docs for `EdgeToEdgeDataList`.

**Comment by aerwin** [comment]
Closing with above commit.
