### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3411]
Create Orion plugin to support LDAP authentication.

---

**Tasks:**
1. (Phase 1) Authenticate users credentials (user ID & password) using an LDAP server.  LDAP parameters should be pulled from **maqetta.conf**.
2. (Phase 2) Pull relevant user data from LDAP server to populate Maqetta (Orion) user objects -- info such as **display name** and **email address** (the latter is needed for Review & Commenting).

**Comment by JonFerraiolo** [comment]
-> M8 Prio-Med

**Comment by jhpedemonte** [comment]
-> M9

**Comment by jhpedemonte** [comment]
Assigned to @billreed63 and updated the summary.

**Comment by billreed63** [comment]
For the ldap feature I have added the project /maqetta.server.orion.authentication.ldap you will need to import this project into your workspace once this project is imported. 

To enable LDAP authentication  modify the config options in `releng\davinci.releng\orion\builder\scripts\maqetta.conf` 

```
#
# Use LDAP authentication, un commit the orion.auth.name=LDAP 
# and set the maqetta.auth.ldap.* attributes to use LDAP for authentication 
#
orion.auth.name=LDAP
# the ldap url to use when authenticating a user
maqetta.auth.ldap.provider.url=ldaps://bluepages.ibm.com:636
# the ldap url to use when looking up a uses ldap information
# non ssl is faster.
maqetta.auth.ldap.lookup.provider.url=ldap://bluepages.ibm.com:389
# the jndi directory context to use, optional, if not defined defaults to com.sun.jndi.ldap.LdapCtxFactory
maqetta.auth.ldap.initial.context.factory=com.sun.jndi.ldap.LdapCtxFactory
# Optional if not defined defaults to com.sun.jndi.url
maqetta.auth.ldap.url.pkg.prefixes=com.sun.jndi.url
# Optional if not defined  defaults to ignore
maqetta.auth.ldap.referral=ignore
# Used when authenticating a user
maqetta.auth.ldap.security.authentication=SIMPLE
# Used when looking up a user
maqetta.auth.ldap.lookup.security.authentication=none
# used when when authenticating a user
maqetta.auth.ldap.security.protocol=ssl
# used when when looking up a user, comment out for none
#maqetta.auth.ldap.lookup.security.protocol=ssl
# ldap base to use when searching for user
maqetta.auth.ldap.base=ou=bluepages,o=ibm.com
# ldap attribute to use when searching for user, eg. email or employeenumber etc...
# whatever you uses as a login attribute
#maqetta.auth.ldap.user.filter=email
maqetta.auth.ldap.user.filter=uid
# ldap attribute that will be used as the users display name
maqetta.auth.ldap.user.displayname=callupname
# ldape attribute that will be used as users email
maqetta.auth.ldap.user.email=email
```

@jhpedemonte  I am still unable to replace the login page with one that does not have the Registration button, Registration is not valid for ldap authentication.  Also the check for valid email address for user name is not a valid assumption for ldap users

**Comment by billreed63** [comment]
fixed by above commits
