### ISSUE TITLE
Register/activation - not handling user already exists well

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3413]
In testing on maqetta-test, I went to "Register" using my iBM email address, and got the activation email. Then after clicking on the link in the email, I went to the activation page. So far so good. But then I tried to enter my new password(s), and I got "user already exists". At that point, there is no button to press to return to the login screen.

Seems like we should check for existing users on the Register page, and have a back link of some sort from Activation page to the login page.

**Comment by jhpedemonte** [comment]
See #3333, wherein Brad added a check for _Reset Password_ to see if user exists before sending out email.

**Comment by jhpedemonte** [comment]
One small issue: after use gets "Email already registered" error message, there is no way to go back to login screen (to login or reset password) other than reloading the page.  I think the best solution would be to keep the **Cancel** button visible.
