### ISSUE TITLE
No dotted border for various mobile container widgets

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3416]
@doronrosenberg 

I am testing some of the new dojox.mobile widgets (Pane, ContentPane, ScrollablePane, etc) and they don't get a dotted border like DIVs and SPANs do. As a result, when they are on the page, there is no visual indication about their borders, and when dragging them around (in sketch mode) there are no bounds for the user to see.

**Comment by aerwin** [comment]
Sounds like a dup of #3400.
