### ISSUE TITLE
GridLayout - exception - selection goes to top-left corner on create

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3417]
@doronrosenberg 

With Mac/Firefox using today's build on maqetta-test:
- New mobile app, use ipad as device
- Drag a GridLayout onto canvas

I get an exception in the console

```
TypeError: _28e7 is undefined [Break On This Error]     
if(_28e7.domNode.tagName=="BODY"){  davinc...vision@ (line 57226
```

This is dying in `selectionSameParentNotBody` in an attempt to call `getParent()`, which is probably failing because the widget handle is stale. 

Should fix for 7..0.1. I've seen this exception regularly when testing this week, and the fix should be easy and safe.

**Comment by aerwin** [comment]
Sounds like a dup of #3402... though #3402 was closed only fixing FixedSplitter.
