### ISSUE TITLE
SaveAsWidget - exception

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#3418]
- dnd a div 
- dnd a calendar and a button into the div
- select the div
- Save As Widget
- Fill out the form and press save

The following error happens, as.sfsf being my group name and widget name:

```
Error: Unable to resolve constructor for: 'as.sfsf'
[Break On This Error]   

throw new Error("Unable to resolve constructor for: '"+obj.types.join()+"'");
```

**Comment by JonFerraiolo** [comment]
-> @peller M8 Prio-Med. 

Note that I fixed an exception with SaveAsWidget recently (9af65498e7cf6547a30cd87e692c6004eaf06985) but this might be something else.

**Comment by peller** [comment]
sounds like a dup of #3533
