### ISSUE TITLE
SpinWheel does not correctly distribute slot widths causing the slots to be wider than the parent

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3419]
@JonFerraiolo @jhpedemonte @doronrosenberg 

Opening against M8 because I suppose isolated and assuming difficult for us to do anything about, but unfortunate because looks kind of bad...

Using Chrome on Mac going to local server...
1. New Mobile Application
2. Drag and drop RoundRect
3. Drag and drop SpinWheel into the RoundRect
4. Drag and drop SpinWheelSlot into the last slot of the SpinWheel
5. Rendering and selection chrome get messed up (and stays so after dismissing smart input):

![GitHub Logo](http://i.imgur.com/nDkEl.png)

Perhaps this is a Dojo issue... as far as I can tell the HTML looks right, but when I preview the rendering is wrong as well...

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'async':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dojox/mobile",
  "dojox/mobile/deviceTheme",
  "dojox/mobile/compat",
  "dojox/mobile/SpinWheel"
]);
</script>
<style>@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"></meta>
</head>
<body class="claro" data-maq-device="iphone" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
 <div data-dojo-type="dojox.mobile.RoundRect">
  <div data-dojo-type="dojox.mobile.SpinWheel">
    <div data-dojo-type="dojox.mobile.SpinWheelSlot" labels="A,B,C,D,E"></div>
    <div data-dojo-type="dojox.mobile.SpinWheelSlot" labels="A,B,C,D,E"></div>
    <div data-dojo-type="dojox.mobile.SpinWheelSlot" labels="A,B,C,D,E" value="A"></div>
  </div>
</div>
 </body>
</html>
```

**Comment by aerwin** [comment]
--> Changing title to "SpinWheel does not correctly distribute slot widths causing the slots to be wider than the parent"

I was messing around some more and noticed this has nothing to do with RoundRect... I think it's all about the width of the slots...

Independent of RoundRect, I had a 3 slotted spin wheel taking up the full width and tried to set the margin and noticed the same thing happening.

So, I've discovered if I make the width of the slots smaller, then I can use SpinWheel within a RoundRect:

![GitHub Logo](http://i.imgur.com/CuYl0.png)

So, not entirely sure what Maqetta can do here... off top of my head I suppose some sort of helper function could try and be smart about resizing existing slots, but that seems like a hack since the problem is really in SpinWheel.

So, in the end, probably have to log a Dojo bug.

**Comment by JonFerraiolo** [comment]
-> @aerwin who has mostly figured everything out already

**Comment by billreed63** [comment]
-> M9
@JonFerraiolo @jhpedemonte

**Comment by peller** [comment]
~~possibly related~~ does not seem to be related to #3715 and #3584

**Comment by billreed63** [comment]
spinWheelSlots. by default the width of the slot is set in the css files for the theme. iphone for example: 

```
.mblSpinWheelSlot {
position: relative;
top: 0px;
float: left;
width: 100px;
height: 100%;
border-left: solid 2px #000000;
border-right: solid 2px #000000;
-webkit-tap-highlight-color: rgba(255, 255, 255, 0);
}
```

If is not calculated at runtime based on the number of slots. The user can override the width of the slot by adding the width to the element style.

**Comment by aerwin** [comment]
I'm of course long gone from the team so if you want to close it that's fine. But, just be aware of the number of steps and difficulty a user has setting up a simple spin wheel as described in my article:

http://www.ibm.com/developerworks/mobile/library/mo-maqetta-1/index.html

Even if this is just the expected behavior of the widget (as described by @billreed63), I'd think Maqetta could take steps with smart input or some other means to make it far easier.
