### ISSUE TITLE
Tree Smart Input doesn't work with legacy trees

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3422]
--> @aerwin to assess for M7.0.1

Doing the "Editing "legacy" tree (optional)" section of the Trees test case... tree does not render in the smart input... There's nothing in the console, but turning on break on errors leads me to line 78 of `dijit.tree.ObjectStore` model:

```
                            throw new Error("dijit.tree.ObjectStoreModel: root query returned " + items.length +
                                " items, but must return exactly one");
```

The fact that this break in unbuilt source looks to be a 2nd issue that I'll open up separately.

**Comment by aerwin** [comment]
Closing with above commit.

**Comment by JonFerraiolo** [comment]
I ran the test plan on legacy trees today and verified against today's build that legacy trees work, at least to some extent.
