### ISSUE TITLE
RSOD due to Heading implementation change in Dojo 1.8 where 'back' results in a magically generated ToolBarButton

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3425]
If you add a Heading and then set the 'back' property to any value, under the hood, Dojo 1.8 creates a ToolBarButton widget. The Outline palette shows it, but because that automatically generated widget doesn't go through all of the dvWidget creation logic, bad things happen down the road.

Dojo 1.7 did not create an extra ToolBarButton widget and instead created a special DIV. (Which Maqetta was properly handling).

After studying this at length, the only solution is for Maqetta to successfully ignore this automatically created widget and treat it as one of those non-widget DIVs that Dojo stuffs into the user iframe that Maqetta just ignores.

**Comment by aerwin** [comment]
@JonFerraiolo 

I'm assuming what you're doing for this (making Maqetta stop seeing that widget as standalone)  would address this issue I also noticed last night (but forgot to open) where I can double click on the Back button and get a useless smart input:

![GitHub Logo](http://i.imgur.com/22VVI.png)

**Comment by JonFerraiolo** [comment]
@aerwin - could you please pull the latest code with my fix above and verify that the picture you are showing above doesn't happen anymore?

**Comment by aerwin** [comment]
@JonFerraiolo 

Think it's fixed... this is what happens now... which feels a little weird since I think I'm clicking on the Cancel button, but I think it's the right thing (bringing up smart input for the Heading):

![GitHub Logo](http://i.imgur.com/w5NRa.png)

**Comment by JonFerraiolo** [comment]
Spin-off issue for SmartInput location.: #3442
