### ISSUE TITLE
Undo doesn't work in source view of Visual Editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#343]
@billreed63

To recreate:
1) Open an HTML file.
2) Click on "Display Source" button in toolbar.
3) Delete some text.
4) Click on undo button in toolbar.

This should undo the text deletion, but it does nothing.

In UndoAction.js, there are the following lines:
   var e = davinci.Workbench.getOpenEditor(); 
   e.getContext().getCommandStack().undo();

The variable "e" in this case points to an instance of the PageEditor.  The
PageEditor contains an instance of the VisualEditor and of the HTMLEditor --
the latter is what is displayed when clicking on the "Display Source" button.

However, PageEditor.getContext() consists of this line:
   return this.visualEditor.context;

It only looks at the VE context, even if the HTMLEditor is currently in use.

The quick fix would be to change PageEditor.getContext() to check which editor
(VE or HTMLEditor) is currently in use by the user, and return the appropriate
'context'.  However, since they both are views on the same model, this may not
be the best solution.  There should probably be some convergence of contexts.

------- Comment #1 From Javier Pedemonte 2011-02-22 11:44 [reply] -------

The base class davinci.ui.Editor creates a CommandStack instance.  Both
PageEditor and HTMLEditor are descendants of Editor and as such already have a
CommandStack instance.  VisualEditor does not inherit from anything.

First, PageEditor creates its own CommandStack (at "this._commandStack") rather
than using the inherited one at "this.commandStack".  The PageEditor code then
saves this newly created CommandStack instance into the VisualEditor's context.
 So PageEditor and VisualEditor share the same CommandStack instance, but not
the one inherited from the base class Editor.

But HTMLEditor has a different commandstack.

Maybe the PageEditor code should be changed to:
1) not create a new command stack, but instead use the inherited one from
"this.commandStack";
2) or, use HTMLEditor's command stack for all 3, in order to share.

We should at least do (1), so as not to create unnecessary objects.  (2) would
be better, since there we would be sharing the command stack across the visual
and source editors.

One concern is that the user may get confused when undoing something in the
visual view, but the undo action just changes code which causes no visible
changes.  The user may think that the undo command was unsuccessful or didn't
occur.  We should provide some visual feedback, in this case, so the user knows
that the undo/redo command took place.

For example, the user makes a change in the source view, then switches to
visual view.  If the user does an undo, there may be no actual changes in the
visual view, although the change has been undone in the source.  This also
applies to changes made in the Properties view.

Maybe we can check which view is currently focused, and if an undo/redo takes
place that was from another view, create a hovering tooltip/transparent-dialog
that pops up for 1 or 2 seconds to say that the undo/redo took place.

**Comment by jhpedemonte** [comment]
#1555 has a more involved **recreation scenario**, involving changes both in the VE and the source.

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo M7 Prio-High

**Comment by JonFerraiolo** [comment]
Downgraded to M7/Prio-Med

**Comment by JonFerraiolo** [comment]
@peller @jhpedemonte 

Pushing to future. In M7, all of the editor icons on toolbar (undo, redo, etc) are disabled when in source-only view, so the worst parts of this issue have been addressed. 

However, any source editor changes right now are not stored on the undo stack. We really should allow source changes to be undone. To implement, we would probably have to store the entire old HTML text and new HTML text as simple text strings, and undo/redo would result in simply replacing the source entirely. But also source changes would have to remove all existing undo stack entries because we can't count on the older undo data still being valid.
