### ISSUE TITLE
Print request info to logs when printing stack trace

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3430]
Right now, we see stack traces for exceptions caught by `jetty.servlet.ServletHandler`.  Would be nice to also have a printout of the request info -- may add valuable information to help us track down the errors.

@peller

**Comment by jhpedemonte** [comment]
Sending to @peller, who said he had an idea how to handle this, at least partially.

**Comment by peller** [comment]
I'll just put try/catches around the doGet/doPost/doPut calls in our two servlets, catching RuntimeExceptions and rethrowing them.  @jhpedemonte What info should I print out form the request?
