### ISSUE TITLE
typo in reset password link

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3437]
this link is visible in the e-mail sent to the user.  "resetTolken" should probably be "resetToken"

`http://myhost/mixloginstatic/LoginWindow.html?login=user@somedomain&resetTolken=12345678&redirect=../maqetta/`

**Comment by jhpedemonte** [comment]
Watch out, the "tolken" misspelling (I believe it was purposeful) is all over the code.

**Comment by jhpedemonte** [comment]
No longer relevant.  Using Orion APIs.
