### ISSUE TITLE
Upload ZIP 

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#344]
@jhpedemonte, @childsb

It would really help users out a lot for various scenarios if they could upload
a ZIP and have it expand into their workspace, as the complement of the
download-as-Zip feature.

Javier might end up delivering this feature as a side effect to his
import/export widget enhancements. We want to make sure that the ZIP upload
though isn't restricted only to widgets.

One issue: what happens if the unzipping might wipe out existing files? We
should have some UI to allow user to overwrite all, overwrite none, overwrite
newer, or prompt for each file whether to overwrite (yes, no, newer). Maybe ask
for each file one at a time, with an apply to all checkbox.

**Comment by JonFerraiolo** [comment]
-> @peller M9 Prio-Med

**Comment by peller** [comment]
Note that the Orion Navigator already has this functionality.  Might we be better off if we start to redirect the user to the Orion navigator to upload and/or restructure content in their project?

**Comment by JonFerraiolo** [comment]
@jinsil 

To summarize the current state of affairs: (1) In Maqetta, we have a somewhat clumsy and inflexible facility for uploading one or more files into a single folder, (2) With Orion Navigator, you have a very geeky and clumsy (but pretty flexible) facility for uploading and expanding ZIPs.

Given the Orion workaround and how much effort it would be to present a nice UI for uploading files, let's push this to M10 for the time being.

**Comment by peller** [comment]
Orion uploads to a named folder, not directly to the target, which would require handling of collisions.  Filed <a href="https://bugs.eclipse.org/bugs/show_bug.cgi?id=403136">a ticket</a> with Eclipse Orion to request direct zip upload.  It would be best if Orion provided this functionality, I think.

**Comment by peller** [comment]
TODO: zip upload always unzips at top-level directory

**Comment by JonFerraiolo** [comment]
I don't think you want to always upload to top-level directory. Long-term, the upload dialog should allow the user to pick a base folder into which the files will be unzipp'd. Short-term, user should pick a base folder in Files palette before launching the Upload command.

**Comment by peller** [comment]
@JonFerraiolo, sorry, I meant to say, there's a bug: it always uploads the zip to the top-level directory, even though the code seems to explicitly put it in the folder specified.
