### ISSUE TITLE
Best practices: Use java.util.logging for server side trace

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3443]
For M8...

Related to #2598 & #3430 (and maybe others)... we should start using java.util.logging on the server side instead of System.out.println, e.printStackTrace, etc.

**Comment by jhpedemonte** [comment]
Or use Orion's logging facilities.  For example, see `org.eclipse.orion.server.core.LogHelper`.

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte Prio-Med

**Comment by jhpedemonte** [comment]
Dupe to #3717.
