### ISSUE TITLE
Double-click on image brings up empty "Select a source" dialog

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3446]

**Comment by aerwin** [comment]
@JonFerraiolo Do you have a more specific use case? When I double click on an img it brings up a properly populated select a source dialog.

**Comment by JonFerraiolo** [comment]
Closing this bug until a reproducible case emerges. 

Must be something intermittent because I just tried again and the dialog came up just fine. I was running through the States test plan at the time and accidentally double-clicked on the image of SampleBanner.jpg that I had on my page and there was an empty dialog.
