### ISSUE TITLE
Unable to register new user

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3450]
When I click on the activation link to activate my account I enter in the new password and see the following exception after pressing the save button

```
POST http://maqetta-app-test.austin.ibm.com/users

403 Forbidden
        76ms    
LoginWindow.js (line 305)

"NetworkError: 403 Forbidden - http://maqetta-app-test.austin.ibm.com/users"

users

SyntaxError: JSON.parse: unexpected character
[Break On This Error]   

var responseObject = JSON.parse(mypostrequest.responseText);
```

 the response from the request

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 403 Forbidden</title>
</head>
<body>
<h2>HTTP ERROR: 403</h2>
<p>Problem accessing /users. Reason:
<pre>    Forbidden</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
```

**Comment by billreed63** [comment]
I think maybe this was an age issue, I registered yesterday afternoon but did not try to use the activation link until this morning. Does the activation have a freshness date?

**Comment by jhpedemonte** [comment]
Yes, I believe the activation link only lasts for 12 or 24 hours.  Closing. Reopen if you see this again.
