### ISSUE TITLE
Source code input not responsive on Preview 7

### ISSUE THREAD

**Issue by megaD** [maqetta/maqetta#3457]
For whatever reason on my MacBook Pro (Mac OS X 10.7/Safari) the source code entry is not responsive. On my PC (Windows 7/Firefox) that doesn't happen.

Could you investigate?

Please let me know if you need more details.

**Comment by itamarro** [comment]
Happens to me too - source code editing has a considerable delay after any change I make (even just typing text in without changing elements). Happens to me both on Chrome and FF, on Win XP.

**Comment by megaD** [comment]
Ok, it just occured to me on Windows 7 and Firefox as well so it's not limited to the Mac and XP.

**Comment by megaD** [comment]
Any news about this issue?

**Comment by jhpedemonte** [comment]
-> M8/High, need to investigate this soon.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
I've seen this too and talked with @peller about it. This is probably due to the re-parsing that happens after you type characters into the source pane. Best guess is that during the re-parsing, the source editor is unresponsive.

**Comment by JonFerraiolo** [comment]
@peller, @doronrosenberg - do either of you know whether the reparsing happens even when in source-only mode? For long-haul, we need to make source editing responsive in split view, but maybe there is a quicker fix we could apply if the user is only looking at the source code?

**Comment by peller** [comment]
yes, reparsing happens for any text editor.  Right now, the only difference between split view and source-only is whether the visual editor is hidden.  Because everything is architected around the model, we have to update the model, but we certainly could postpone it a lot longer for source-only.

**Comment by peller** [comment]
@megaD is the file you're editing complex or contain a large number of widgets?  What happens now is that Maqetta should let you type freely in the source editor.  When you stop typing for a certain interval (a second or so) then it refreshes the visual view.  That normally doesn't take too long (less than a second) but with a longer document it would be longer.   Could you clarify what you mean by not responsive?  Does it hang indefinitely?  Or is there just a delay that makes it difficult to type?  If it hangs, could you check your javascript console?

**Comment by megaD** [comment]
My document is not really long nor do I use any widgets. Just plain HTML and some JavaScript. The delay is like for half a second or second. I'll try to take a look at the Error Console to see what comes up.

**Comment by megaD** [comment]
The console doesn't throw any error but I took a screenshot of the network tab: http://screencast.com/t/DxMaqa30Xhww

I think the  ~0.7s entries is what I experience as a delay.

**Comment by peller** [comment]
Thanks, @megaD.  Yes, those transactions could be the issue.  They're still synchronous XHR calls, made from `davinci/html/CSSFile.js`  line 32:

```
                txt = file.getText();
```

Because they're synchronous, they're probably interfering with keyboard and mouse activity.   We'll have to look at moving that over to the asynchronous file.getContent() call.

Also, I'm wondering why these are network HTTP hits and not cache hits.

**Comment by peller** [comment]
```
xhr (:8081/maqetta/app/dojo/request/xhr.js?@revision@:216)
dojo.xhr (:8081/maqetta/app/dojo/_base/xhr.js?@revision@:607)
dojo.xhrGet (:8081/maqetta/app/dojo/_base/xhr.js?@revision@:630)
Runtime.serverJSONRequest (:8081/maqetta/app/davinci/Runtime.js?@revision@:380)
declare.getContentSync (:8081/maqetta/app/davinci/model/resource/File.js?@revision@:88)
declare.getText (:8081/maqetta/app/davinci/model/resource/File.js?@revision@:84)
declare.constructor (:8081/maqetta/app/davinci/html/CSSFile.js?@revision@:32)
(anonymous function) (:8081/maqetta/app/dojo/_base/declare.js?@revision@:384)
Factory.newCSS (:8081/maqetta/app/davinci/model/Factory.js?@revision@:77)
Factory.getModel (:8081/maqetta/app/davinci/model/Factory.js?@revision@:29)
declare.load (:8081/maqetta/app/davinci/html/CSSImport.js?@revision@:72)
visit.visit (:8081/maqetta/app/davinci/html/HTMLFile.js?@revision@:156)
declare.visit (:8081/maqetta/app/davinci/html/CSSImport.js?@revision@:28)
declare.visit (:8081/maqetta/app/davinci/html/HTMLElement.js?@revision@:471)
declare.visit (:8081/maqetta/app/davinci/html/HTMLElement.js?@revision@:471)
declare.visit (:8081/maqetta/app/davinci/html/HTMLElement.js?@revision@:471)
declare.visit (:8081/maqetta/app/davinci/model/Model.js?@revision@:149)
declare.setText (:8081/maqetta/app/davinci/html/HTMLFile.js?@revision@:152)
declare.handleChange (:8081/maqetta/app/davinci/ui/ModelEditor.js?@revision@:30)
dispatcher.around.advice (:8081/maqetta/app/dojo/aspect.js?@revision@:106)
target.(anonymous function).dispatcher (:8081/maqetta/app/dojo/aspect.js?@revision@:88)
(anonymous function) (:8081/maqetta/app/davinci/ui/Editor.js?@revision@:66)
(anonymous function) (:8081/maqetta/app/dojox/timing/doLater.js?@revision@:38)
```

**Comment by JonFerraiolo** [comment]
@billreed63 @childsb - do either of you know why we are doing a sync call to get a CSS file?

**Comment by peller** [comment]
The model is built out of xhr calls, specifically using the old Resource API.

**Comment by doronrosenberg** [comment]
@peller Does dojo have a web worker wrapper?  That would be a potential quick fix.

**Comment by peller** [comment]
@JonFerraiolo @billreed63 please review.  @billreed63 is it ok to load CSS model asynchronously like this?

**Comment by peller** [comment]
HTTP hits are apparently Cache-Control: no cache.  @billreed63 was this necessary for the theme editor? any way we can take advantage of the cache here?

**Comment by billreed63** [comment]
I don't see why we could not load the CSS files async, The CSS files are loaded two way's  the CSS files are loaded through xhr and added to the model. This has to be done through the Factory so that the CSSFile model is shared by ThemeEditor, VisualEditor and PageEditor. The CSS files are also loaded by http in the browser for styling the page. We do not want the CSS files cached If the CSS is cached it can be out of sync with the CSSFile in the model when the page is loaded. We want to ensure that the CSSFIle (model) matches the HTTP CSS file in the browser when the page loads

**Comment by peller** [comment]
see #3502 for no cache discussion
