### ISSUE TITLE
Exception when expanding TabContainer in outline 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3463]
1) Create desktop html
2) DnD TabContainer
3)DnD BorderContainer
4) Expand BorderContainer
5) from outline DnD TabContainer and drop in center ContentPane of BorderContainer
6) Try to expand TabContainer

Note the following exception

Uncaught TypeError: Cannot read property 'parentNode' of null dijit.js:3278
_2da.getParent dijit.js:3278
_1462.setChildItems.isExpandable davinci.js:28304
_507.forEach dojo.js:6439
_1462.setChildItems davinci.js:28300
_1462._expandNode davinci.js:28798
_27e0.getChildren davinci.js:56051
(anonymous function) davinci.js:52671
lang.hitch dojo.js:4960
_1462._expandNode davinci.js:28796
_1462._onExpandoClick davinci.js:28752
_1462._onClick davinci.js:28726
_1462.postCreate._148e davinci.js:28406
on.selector dojo.js:6096

**Comment by JonFerraiolo** [comment]
I just tried this on both the testing server and then running from Eclipse and I don't see the exception. 

I assume the TC and BC are siblings before attempt to dnd the TC into the BC's center pane.

-> @billreed63 to try this again. Maybe there are some details missing from the steps?

**Comment by JonFerraiolo** [comment]
@doronrosenberg - 

leaving this as Prio-High for @billreed63 to investigate. After investigation, we need to reset priority based on what we learn.

**Comment by billreed63** [comment]
Works now
