### ISSUE TITLE
ScrollableView - SmartInput doesn't work on RoundRectList if there is fixed Heading and TabBar

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3470]
SmartInput fails to open for the RoundRectList because Widget.byId() doesn't find the container widget which is because widgetHash doesn't have the container widget in its widget list. Has to do with our old nemesis, where ScrollableView rearranges the DOM hierarchy if there are widgets with fixed=top or bottom.

No problem with Release 7, but on investigation, I think this worked in Release 7 because there were two bugs that cancelled each other out, and I think we fixed one of those bugs as part of 701. But still investigating.

**Comment by JonFerraiolo** [comment]
Here are steps to reproduce on Mac/Chrome:
- New Mobile app
- Add ScrollableView
- Add Heading, set fixed=top
- Add TabBar, set fixed=bottom
- Drag/drop RoundRectList. 

Result=> SmartInput doesn't show up

**Comment by doronrosenberg** [comment]
Might be a dojo bug as scroll view get children doesn't return them

**Comment by JonFerraiolo** [comment]
I think it's a Maqetta bug - we aren't putting the non-fixed children inside of the mblScrollableViewContainer DIV. The getChildren() method is looking for children in that DIV. If we were putting children in there correctly, then getChildren() would find them.

**Comment by doronrosenberg** [comment]
ScrollableView should implement a addChild that adds the widget to the containerNode, I'll file a bug with dojo

**Comment by jhpedemonte** [comment]
Please add link to the Dojo bug.

~~Also, we have some Dojo checked in and some coming in from submodules.  Does this one need to go in both?~~ _(nevermind)_

@peller
