### ISSUE TITLE
Scrollbar for widget palette resets to top

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3472]
1) Open a desktop page
2) Expand Dojo controls
3) Scroll down and select a widget
4) Expand Files palette scroll down and select wideg
5) Now do back to the widget palette and click in the scroll area below the scroll bar knob
 Note that the widget palette resets to the top of the scroll area

**Comment by JonFerraiolo** [comment]
Seems to be fixed. Closing.
