### ISSUE TITLE
IE problems with login screen

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3475]
LoginWindow.js uses addEventListener, which isn't support in IE8. From a user perspective, right now the login screens just don't do anything. There is a JavaScript error under the hood, but this is not surfaced to a user.

We should surface the errors somehow to users. One approach for the short-term would be to have the login screens post a message about how Maqetta doesn't support IE, try another browser. Once we have IE support (IE10?) then maybe we can post a message to users who are trying to use older versions of IE that those versions aren't supported. (Probably would be good to do the same thing for older versions of FF, Safari, etc)

**Comment by JonFerraiolo** [comment]
Closing. Dupe of some other bug. I added a red-color message to login screen for IE saying "use a different browser"

**Comment by JonFerraiolo** [comment]
Reopening for future. When I tried a release candidate build of M10 on maqetta-test, I was able to reproduce the problem listed in this bug report, with no red-colored message.

Pushing to future because we've had this problem forever and the community seems to be surviving.

**Comment by JonFerraiolo** [comment]
@billreed63 Can you please open IE9 or IE10, go to the maqetta-test home page, and click on the Launch Maqetta button. What do you see? A message about using a different browser (which is what I hope you'll see)?

**Comment by billreed63** [comment]
When I tried it get a script error, 

```
SCRIPT5007: Unable to get value of the property 'style': object is null or undefined 

```

which is this line of code:

```
browser_not_supported.style.display = "";
```

it appears that the code is running before the document is loaded. so `var browser_not_supported = document.getElementById("browser_not_supported");` in loginwindow.js returns null

if I change the code so that we put the check for IE in a dojo.ready 

```
     ready(function(){
            var ua = window.navigator.userAgent;
            var ieIndex = ua.indexOf('MSIE');
            var isIE = (ieIndex>=0) ? parseInt(ua.substr(ieIndex+4), 10) : false;
            if(isIE){
                var browser_not_supported = document.getElementById("browser_not_supported");
                browser_not_supported.style.display = "";
                browser_not_supported.style.color = "red";
                browser_not_supported.style.fontSize = "16px";
                browser_not_supported.style.padding = "20px 15px";
                return;
            }
            var userCreationEnabled;
            var registrationURI;

            var GENERIC_SERVER_MSG = 'A unexpected error prevented the operation from completing.  ' +
                    'Please try again.  If the problem persists, please contact the server administrator.';
            var ADMIN_USERID = 'admin';
            var ID_PREFIX = '00MaqTempId00'; // keep in sync w/ LoginFixUpFilter.java
      });
```

then I get the following 
![image](https://f.cloud.github.com/assets/717822/430883/84b7a3a0-ae79-11e2-8cda-4b6d90708824.png)
