### ISSUE TITLE
Changes not showing in preview 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3478]
If I make changes to a HTML file in the source editor and then immediately  preview the page the changes sometimes are not displayed in the preview.

I suspect that the working copy has not been saved to the server yet so We are see the old version. If I wait a few seconds then refresh the page I see the changes. like wise if I wait a few seconds before previewing then I do see the updates

This was noticed of FF/win7 on http://maqetta-app-test.austin.ibm.com/maqetta/

**Comment by JonFerraiolo** [comment]
-> @peller M8 Prio-Med (which probably means it will get deferred)

I suspect we just need to add some logic which see if any source editor changes are pending but not yet "committed" (due to delayed processing of source->design) and commit those changes when the user clicks the Preview button.
