### ISSUE TITLE
Outline is regenerated twice on source change.

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#348]
When making a change in the source view, I see that Outline get regenerated
twice based on a single change.

To reproduce:
1) Open Sample1.html.
2) Open split view, to show both visual and source views.
3) In the source view, find the 'title="Tasks"' line and add a letter to the
end of "Tasks"

You will see that the Outline "blinks" twice as it is regenerated based on the
change.  Also, the visual editor isn't updated until the 2nd "blink" of the
Outline.

**Comment by aerwin** [comment]
--> @JonFerraiolo  (thinking no longer an issue a year later?)
--> no milestone to M7 to get tracked better

**Comment by JonFerraiolo** [comment]
@doronrosenberg rewrote the Outline palette and there is no blinking now. Closing.
