### ISSUE TITLE
Tooltips for widgets in Widgets Palette

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#3485]
@JonFerraiolo 

The idea is to have tooltips show when hovering over widgets in the widgets palette.  `widgets.json` would have 2 new fields - `detailedInformation` and `detailedInformationBase64`.  

`detailedInformation` would point at a relative resource file that would get displayed in the tooltip and the base64 one would have the cached contents.  The resource could be text or html.

Pretty straight forward implementation wise. Perhaps have a eclipse-like thing where F2 will turn the tooltip into a tooltipdialog that the user can then scroll.

**Comment by jhpedemonte** [comment]
Talked to Jon about this, and I'm not sure about adding even more information to _widgets.json_.  It adds to how much we need to bring up on startup, making the user wait even more.

A better solution would be to put a small information button on each widget (a small _i_ would do) which, when clicked, pops up the tooltip dialog for that widget.  The information for that widget is loaded on demand.  The incoming data will be small and should be relatively quick.

**Comment by JonFerraiolo** [comment]
Closing. We added a ? icon at bottom right of every widget in widget palette in M8 release.
