### ISSUE TITLE
 file typeerror: cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by hoodieboy** [maqetta/maqetta#3486]
when using jsonp in the gridx dialog I get above error message.  My url is pointing to my local host and Im using a down loaded version on my desktop. my url looks like this http://localhost/Services/LG/GetCouponReg.php?output_type=j&callback=j and I'm assuming the Callback is appended to the url by maqetta to get the results in javascript function format.  I know it is making the call because of the time it takes to get the error and the message I see at bottom of browser.

**Comment by jhpedemonte** [comment]
@JonFerraiolo @aerwin

**Comment by hoodieboy** [comment]
i cannot see your comment.  Did you comment?  I checked my jsonp output with jslint and it is good.

**Comment by jhpedemonte** [comment]
I just copied some other devs on this bug, so they'll take a look.

Does the error actually prevent GridX from pulling in the information?

**Comment by JonFerraiolo** [comment]
@doronrosenberg @aerwin @billreed63 - where is the code that actually invokes JSONP services? 

I played around with scenario where I was trying to run Maqetta at localhost:8081 and issue a JSONP request to http://localhost, but ran into a wall because the gridx dialog appears to be disabling the OK button if the URL has the string 'localhost' in it. I grep'd dojo for 'localhost' and I see by default that its URL validation logic by default precludes 'localhost' within URLs. However, this isn't code I've worked with before so I don't know any of the code paths on the Maqetta side or the dojo side.

**Comment by hoodieboy** [comment]
yes.  The dialog never advances to the next stage, selection of columns.
 Just in case it helps, I have attached the json and jsonp output that is
being passed back.

On Fri, Sep 28, 2012 at 11:24 AM, Javier Pedemonte <notifications@github.com

**Comment by aerwin** [comment]
@hoodieboy Thanks for attaching your data. The GridX widget gets its data from an instance of [dojo.data.ItemFileReadStore](http://dojotoolkit.org/reference-guide/1.8/dojo/data/ItemFileReadStore.html). If you follow the link you'll see that it has a spec for the format of the data it expects, and it does not appear that your data conforms to that spec. E.g., from the docs:

```
{
  "label": "some attribute",   // Optional attribute used to indicate which attribute on an item should act as a human-readable label for display purposes.


  "identifier": "some attribute",  // Optional attribute used to indicate which attribute on an item acts as a unique identifier for that item. If it is not defined, then the ItemFileReadStore will simply number the items and use that number as a unique index to the item.


  "items:" [  // The array of JavaScript objects that act as the root items of the data store
    { /* Some set of name/value attributes */ },
    { /* ... */ },
    ...
  ]
}
```

So, for example, you use `rows` instead of `items`.

Apologies that the GridX wizard does not provide better feedback when the data isn't what's expected. We need to do better here and we have an open issue for that (see #1631).

Finally, as an example of a JSONP service that our GridX wizard works with see http://maqetta.org/sampleService.php ). It conforms to the spec by returning data like the following:

```
({ identifier: 'id', label: 'name',  items: [  { id: '0', name:'Foods', numberOfItems:1},  { id: '1', name:'Fruits', numberOfItems:1},  { id: '4' ,name:'Citrus', numberOfItems:1},  { id: '2', name:'Vegetables', numberOfItems:0},  { id: '3', name:'Cereals', numberOfItems:0} ] } )
```

---

So, I'm going to go ahead and close this issue based on the explanation above and the already open #1631. I'll also raise the priority of #1631.

**Comment by hoodieboy** [comment]
Javier,
Thanks...I changed my jsonp output to look like your sample, but that still
did not work.  I no longer get the error message or anything else.  So I
used your sample jsonp url to get Maqetta to generate the html and the
other libs, then I modified the generated output to use my url and
fields....that worked.  So I think it is something that Magetta does not
like about either localhost, hardcoded ip address that points to localhost
or no ones jsonp url but the ones it knows about :)

Just in case I attached the new output

**Comment by aerwin** [comment]
@hoodieboy 

This is actually @aerwin (Tony) helping you out...

Looking at an item in your new output I see:

```
{"CouponCodeSkey":"10000077","CouponCode":"RCT-F66-IB ","promoID":"REDCARPET","firstName":"John","lastName":"Young","email":"johny@williams-helde.com","zipCode":"98109","mailingListOptIn":"Y","ipAddress":"4.226.110.166","trackingTagCreative":"wedding","trackingTagMedium":"banner","trackingTagPublisher":"condenast","dateOfRequest":"Aug 3 2012 1:14PM"}
```

And, it looks like all of the your keys in the key value pairs are quoted. With JSONP, it should be more like (not quoted):

```
{CouponCodeSkey:"10000077",CouponCode:"RCT-F66-IB ",promoID:"REDCARPET",firstName:"John",lastName:"Young",email:"johny@williams-helde.com",zipCode:"98109",mailingListOptIn:"Y",ipAddress:"4.226.110.166",trackingTagCreative:"wedding",trackingTagMedium:"banner",trackingTagPublisher:"condenast",dateOfRequest:"Aug 3 2012 1:14PM"}
```

**Comment by aerwin** [comment]
--> Reopening to make sure we get this resolved

**Comment by aerwin** [comment]
@hoodieboy 

I'm not sure if you've had any more luck, but as a test I deployed Maqetta's sampleService.php to a web server running on my localhost and things seemed to work ok with GridX (from a Maqetta server also running on localhost). So, I don't think there are issues connecting to localhost with JSONP.

FYI, here is a copy of sampleService.php if you wanted to try it in your environment:

```
<?php
header("Content-type: application/javascript");

$callback = $_GET['callback'];
$json = "{ ";
$json .= "identifier: 'id',";
$json .= " label: 'name', ";
$json .= " items: [ ";
$json .= " { id: '0', name:'Foods', numberOfItems:1}, ";
$json .= " { id: '1', name:'Fruits', numberOfItems:1}, ";
$json .= " { id: '4' ,name:'Citrus', numberOfItems:1}, ";
$json .= " { id: '2', name:'Vegetables', numberOfItems:0}, ";
$json .= " { id: '3', name:'Cereals', numberOfItems:0} ";
$json .= "] ";
$json .= "} ";
echo $callback."(".$json.")";
?>
```

**Comment by hoodieboy** [comment]
Ok, I'll try that to see if that's what's confusing Maqetta, but the
ItemFileReadStore is able to process it correctly.  The double quotes come
from the backend php json_encode() function.

**Comment by aerwin** [comment]
> Ok, I'll try that to see if that's what's confusing Maqetta, but the
> ItemFileReadStore is able to process it correctly. The double quotes come
> from the backend php json_encode() function. 

I don't really think its matter of confusing or not confusing Maqetta... we (e.g., Maqetta code) don't connect to the JSONP service directly nor do we parse the output from the service. We rely on the combination of dojox/io/xhrScriptPlugin and dojo/data/ItemFileReadStore. So, my suggestion to remove the quotes was only based on a comparison with what I know works in a working sample.

If you think the quotes should work with ItemFileReadStore and JSONP, then it occurs to me another test you could do is create a new HTML file in Maqetta with the source below (from Maqetta after going through the GridX wizard with a working JSONP service), but replace the two occurrences of `http://maqetta.org/sampleService.php` with the URL to your service. Then, preview the page. At this point, Maqetta's GridX wizard would be totally out of the picture. If the HTML below works with your service as it is, but the
GridX wizard still fails, then we'd know we have a problem in Maqetta code (aside from the previously mentioned issue that we're not providing very good feedback on errors we encounter).

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'async':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dojox/io/xhrScriptPlugin",
  "dojo/data/ItemFileReadStore",
  "gridx/Grid",
  "gridx/core/model/cache/Async",
  "dojox/data/CsvStore"
]);
</script>
<style>@import "themes/claro/document.css";@import "themes/claro/claro.css";@import "lib/dojo/gridx/resources/claro/Gridx.css";@import "lib/dojo/gridx/resources/claro/Gridx_rtl.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
<script type="text/javascript">
require(["dojox/io/xhrScriptPlugin"],function(xhrScriptPlugin){
    xhrScriptPlugin("http://maqetta.org/sampleService.php","callback");
});
</script>
</head>
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
<span data-dojo-type="dojo.data.ItemFileReadStore" id="ItemFileReadStore_1" jsId="ItemFileReadStore_1" url="http://maqetta.org/sampleService.php"></span>
<table data-dojo-type="gridx.Grid" style="min-width: 1em; min-height: 1em; width: 100%; height: 300px;" data-dojo-props="cacheClass: 'gridx/core/model/cache/Async',structure:[{width:'auto',name:'ID',field:'id'},{width:'auto',name:'name',field:'name'},{width:'auto',name:'numberOfItems',field:'numberOfItems'}],store:ItemFileReadStore_1"></table>
</body>
</html>
```

**Comment by aerwin** [comment]
@hoodieboy 

I think the test I suggested above is still worthwhile to help figure out what's going on with your service, but you are probably right that the quotes on the keys don't matter. I just updated my php file deployed to localhost to have quotes and it appears to work within the GridX wizard (and the preview):

```
<?php
header("Content-type: application/javascript");

$callback = $_GET['callback'];
$json = "{ ";
$json .= "identifier: 'id',";
$json .= " label: 'name', ";
$json .= " items: [ ";
$json .= " { 'id': '0', 'name':'Foods', 'numberOfItems':1}, ";
$json .= " { 'id': '1', 'name':'Fruits', 'numberOfItems':1}, ";
$json .= " { 'id': '4' ,'name':'Citrus', 'numberOfItems':1}, ";
$json .= " { 'id': '2', 'name':'Vegetables', 'numberOfItems':0}, ";
$json .= " { 'id': '3', 'name':'Cereals', 'numberOfItems':0} ";
$json .= "] ";
$json .= "} ";
echo $callback."(".$json.")";
?>
```

It gives this output:

```
({ identifier: 'id', label: 'name',  items: [  { 'id': '0', 'name':'Foods', 'numberOfItems':1},  { 'id': '1', 'name':'Fruits', 'numberOfItems':1},  { 'id': '4' ,'name':'Citrus', 'numberOfItems':1},  { 'id': '2', 'name':'Vegetables', 'numberOfItems':0},  { 'id': '3', 'name':'Cereals', 'numberOfItems':0} ] } )
```

**Comment by billreed63** [comment]
-> M9
@JonFerraiolo @jhpedemonte 

@hoodieboy are you having this issue or can we close this?

**Comment by hoodieboy** [comment]
Found a work around.  Issue never went away.
