### ISSUE TITLE
Outline - drag/drop of contentpane with child throws error

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#3490]
- dnd a contentpane
- dnd a button into it
- dnd a div into the document
- dnd the contentpane into the div

try to expand the contentpane:

```
TypeError: this.domNode is null
http://maqetta-app-test.austin.ibm.com/maqetta/app/dijit/dijit.js?3773ee26d1da0e59eda6a108772a6b8990d2c25c
Line 3278
```

**Comment by doronrosenberg** [comment]
@peller

Caused by dijit tree - when you remove a tree node, it destroys the node and all children.  However it does not remove child tree nodes from its internal cache (_itemsNodeMap), so if you readd a node that has the same id as a child tree node, it finds a cached item and tries to use it, but the cached item is null.

**Comment by JonFerraiolo** [comment]
Incidentally, I think we need a mechanism for the outline to know that it might have stale references and needs to rebuild either the entire tree or at least parts of the tree. We have various operations in Maqetta that recreate widget objects (and maybe dom nodes). For example, ModifyCommand calls createWidget() to create a whole new widget whenever any widget properties change.

**Comment by doronrosenberg** [comment]
@JonFerraiolo I already did that in M7.  I decoupled it from the widget model - now we just store the widget ids in the tree model and fetch the widget whenever we need to do something on it.
