### ISSUE TITLE
Performance issue with maqetta.org

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3499]
@jhpedemonte @JonFerraiolo @peller 

Using Chrome on Mac going to maqetta.org... 

Mentioned this to @jhpedemonte yesterday after he asked me to do a sanity check of the 7.0.1 upgrade... guess it's possible I'm really the only one seeing this, but since still happening this morning, I thought I should get it on the books because maqetta.org is basically unusable for me.

Despite being on a 35+ Mbps connection, I'm seeing numbers like the following:
- it takes about 10+ seconds for login screen to disappear
- it takes about another 90 seconds for workbench to appear and loading indicator to show up in my last open page
- takes around a total of 2:18 for last open page (just containing a calendar) to fully render

This is with a loaded cache as well (e.g. did not clear my cache before login). 

Looking at the network tab, I've seeing some surprisingly high times for each request. As a sampling:

![GitHub Logo](http://i.imgur.com/o5Bkb.png)

I'm seeing similar results in FF. Also, I've rebooted and such to try as much as possible to eliminate anything odd on my end.

**Comment by peller** [comment]
What I see is very different.  My waterfall looks fine, except for the occasional _very_ long delay, usually on a small request (on the order of 15-30 seconds)  After a few of these, all the browser I/O blocks until they clear.

![GitHub Logo](http://i.imgur.com/kLToO.png)

**Comment by JonFerraiolo** [comment]
One thing I'll note: file operations on the maqetta.org server can be very slow. For those with admin priveleges, go to the users folder and type "ls". It takes a long time before the server responds and starts to list files.

**Comment by jhpedemonte** [comment]
Release 7.0.2 attempted to do 2 things to help this situation:
1. ensure that the Maqetta plugins were JARs and not "exploded" directories.
2. remove the "no-cache" header from many static resources.

Unfortunately, (1) turned out to be a red herring; it provided no improvement once the 7.0.2 build was deployed to maqetta.org.

(2) did help, but I'm still seeing very big delays for the "cmd/*" network requests.

After some investigation, this is due to the (ever increasing) size of the users' workspaces -- it seems that Maqetta gets slower as more users register.

I am currently profiling the app...

**Comment by jhpedemonte** [comment]
Each `cmd/` call does a call to `DavinciCommandServlet.checkLogin()`, which is where most of the performance impact occurs.  Following the chain of calls, it always ends up in calls to `EclipsePreferences`, particularly when called from `org.eclipse.orion.internal.server.servlets.workspace.WebElement.<init>()` -- this constructor always does a call to  `EclipsePreferences.sync()`.

I found that Orion changed this behaviour for v1.0 -- see [bug 390480](https://bugs.eclipse.org/bugs/show_bug.cgi?id=390480).  For performance reasons, they removed the call to `EclipsePreferences.sync()` in `WebElement`.

I made a similar change locally:  server startup with a large "users" directory was almost instantaneous (would take over a minute before), and loading to the Maqetta welcome page went from 20 s to 4 s.

So looks like we need to backport that `WebElement` fix to Orion v0.5.

@skaegi

**Comment by aerwin** [comment]
@jhpedemonte @JonFerraiolo @peller 

With the first part of my article set to come out this month (and the potential to add a significant number of new users), I was curious (and worried) where we were at since @jhpedemonte discovered the unjarring was a red herring...

And, unfortunately, I'm now seeing far worse numbers than in 7.0.1 when I login to my account with it taking **7-8 mins** after login to see my workbench and **another couple** to see the correct rendering of my mobile page.

Obviously this is really bad and far different that what @jhpedemonte and @peller seem to see. So, I created a brand new account, and I think the numbers when using that one are more in line with what @jhpedemonte and @peller typically see. (This is good for the article since new users would obviously be starting with fresh accounts). 

So, I think in addition to @jhpedemonte 's discovery that number of users makes a difference, I think the size of an individual user's account makes a big difference for that user. I guess something to keep in mind. At least it explains why I consistently see unusable performance and others just see slow performance.

**Comment by jhpedemonte** [comment]
I'm still waiting for help from the Orion folks, to backport the performance fix.  Hopefully it will happen soon and we can deploy a new build to maqetta.org.

**Comment by skaegi** [comment]
Sorry for the delay -- I'll follow up and make sure the backport gets done today.

**Comment by skaegi** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=390480#c3

**Comment by jhpedemonte** [comment]
Applied to both M7 and master.  Closing.
