### ISSUE TITLE
revisit cache-control: no cache

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3502]
the page servlet is setting the  cache-control server heading to no cache for html, css, and js files

@billreed63 and I discussed the possibility of handling html and css files with cacheBusting, but what's the requirement for no cache on js files?  

@jhpedemonte @JonFerraiolo

**Comment by jhpedemonte** [comment]
Which HTML, CSS and JS files?  "no cache" should (at most) only be set for files from the user's workspace, which could potentially change often.

The static files (Maqetta, libraries) should all have a cachebusting param for that particular build.

**Comment by peller** [comment]
the cache bust (query string) is set on the client for workspace files.  I'm not sure the writePage code on the page servlet makes any distinction for which files it processes, or if so, where it makes that distinction.

So I sort of understand the html and css problem, but for js, at least when it comes to all the library js files, "no cache" seems unnecessary and definitely generates more server traffic and degrades client performance.

**Comment by peller** [comment]
closing, for now.  Should cover most of the impact.  We could look at using cache-busting techniques to cover the remaining cases.

Opened a new issue #3539 on expiration of cached documents
