### ISSUE TITLE
Back-end and build fixes for site-specific configuration files

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3503]
@jhpedemonte @peller @childsb @billreed63 @doronrosenberg 

For M8, we need to support the ability to have different widget palette setups and different default themes for different deployments. For example, a particular company might have their own widget libary and their own themes. It is common that a particular company will want their company-specific widgets to appear before other similar widgets in the widget palette, and their company-specific CSS theme to be the default theme.

After studying the code, I have concluded that it's time to bite the bullet and finally implement support for a general mechanism for site-specific settings, where widget palette configuration is just one instance of a site-specific setting.

My particular proposal:
- Add a "siteConfig" runtime variable to the Maqetta application. This "siteConfig" variable would be a sibling parameter to "baseDirectory". (Just grep for 'baseDirectory' from the root folder of the maqetta repository). This variable would point to a folder which contained site-specific configuration files. To add such a variable will involve changes to:
  - the *.launch files that define the "Run Configurations" in Eclipse
  - the product launch scripts found in `maqetta.server.mac.command`, `maqetta.server.win.bat` and `maqetta.server.sh` found in `davinci.releng/orion/builder/scripts/`
  - the product files `maqettaOrion.product` and `maqettaOrionHosted.product` found in `davinci.releng/orion/builder/`
  - maybe a change to `davinci.releng/orion/builder/scripts/maqetta.conf`
  - and maybe a couple of other places
- We need a new "/maqetta/cmd" for the client to pull down site configuration information at program initialization time. 
  - What I propose is to consolidate our two initialization commands `/maqetta/cmd/getUserinfo` and `/maqetta/cmd/getWorkbenchState` into a single command `/maqetta/cmd/getInitializationInfo` that returns a single JSON object that contains all startup-time data. I actually implemented this consolidation in this branch: https://github.com/maqetta/maqetta/commits/WidgetPaletteConfigurable
  - One suggestion I have is would to have the server look for any foo.json files in the "siteConfig" folder. For each of those files, validate the JSON (assuming this is easy to do on the server), and if the JSON is valid, then add a new "foo" property to the getInitializationInfo object, where the value for the "foo" property is the JSON contents from foo.json. To illustrate:

Return value from getInitializationInfo:

```
{
    'userInfo':{...},
    'workbenchState':{...},
    'foo':{...contents of foo.json file...}
}
```

Ideally, it would be nice to think ahead to providing a mechanism whereby users could modify the default settings from the "siteConfig" folder and store away their own personal versions. However, that's not for M8 except to do a little thinking ahead.

**Comment by billreed63** [comment]
for site specific themes we need a structure that would support themes sets something along the lines of

```
"siteDefaultThemeSets":
    {
        "name":"custom_default",
        "desktopTheme":"claro", /* theme name */
        "mobileTheme":[
            {
                "theme":"custom", /* theme name */
                "device":"Android"
            },
            {
                "theme":"custom",
                "device":"BlackBerry"
            },
            {
                "theme":"custom",
                "device":"iPad"
            },
            {
                "theme":"custom",
                "device":"iPhone"
            },
            {
                "theme":"custom",
                "device":"other"
            }
        ]
    }
```

**Comment by billreed63** [comment]
I have added a Java argument  `-Dmaqetta.siteConfigDirectory=%scriptdir%\siteConfig` that points to the the site configuration folder. In the folder json files are store that have site specific configuration information. 

The server look for any *.json files in the "siteConfigDirectory" folder. For each of those files, the server validates the JSON  and if the JSON is valid, then add a new "property to the getInitializationInfo object, where the value for the object name is the file name that the JSON was read from. For example "foo.json":

Return value from getInitializationInfo:

```
{
    'userInfo':{...},
    'workbenchState':{...},
    'foo':{...contents of foo.json file...}
}

```
