### ISSUE TITLE
Site-specific default themes and/or themesets

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3508]
@aerwin @jhpedemonte

A particular company might want their own CSS themes to be used by default on the version of Maqetta that they install on their company servers. We need a site configuration option where a site administrator can install a JSON file that tells the Maqetta client which default themes to use. (Right now, the client defaults to claro and the default dojox mobile themes)

This is almost certainly dependent on #3503.

On the client side, the main coding change should be fairly easy. When creating a new HTML file, the theme choice logic is in either NewFile.js or NewHtmlFileOptions.js and is only a few lines of code.

**Comment by billreed63** [comment]
until #3503 is ready I added code to check the server environment variable MAQ_DEFAULT_DESKTOP_THEME  and use that. I added a set to the bat and command files. the user can also set the environment variable in the eclipse run configs
