### ISSUE TITLE
Show user's first name instead of email address on banner

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#351]
Right now we show the user's ID on the banner (e.g., joe@smith.com).
Instead, we should be more user-friendly and show the user's first name on the
banner (Welcome back, Joe!).

I realize that different user management scenarios might not have the ability
to determine the user's first name, so this might be a bit harder to implement
than maybe it appears on the surface.

**Comment by jhpedemonte** [comment]
@aerwin, what's the bug you opened to handle this issue, where we discuss adding fields for a user's name?  Need to dupe this to that one.

**Comment by aerwin** [comment]
Closing. Dup to 3165 ("Need to collect some identifying string from user during sign-up (e.g., first name, user id, etc.)")
