### ISSUE TITLE
Undo for source edits

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3525]
@rubimazaki @megaD

It might be a huge boost for users if source changes were undo-able. Not just a feature, but help with data recovery if an incorrect source edit occurs (which might crash the Maqetta parser) or user encounters just a plain old Maqetta bug.

See #3521

**Comment by JonFerraiolo** [comment]
@peller @doronrosenberg @billreed63

**Comment by JonFerraiolo** [comment]
Too risky for M8, even though I have some preliminary code for this feature. Pushing to M9 (which we hope won't be that much after M8)

**Comment by ghost** [comment]
Just thought about it, simplest thing to do is this:
Lets say user entered wrong text to the source editor, and the parser think this is an error and cuts the xml (current behavior ...) why not just check if there's a big difference between what the user entered and what the parser thinks should be, and show a warning before removing the whole chunk of code?

This is really 2 lines of code. And as source code is editable through Maqetta's editor, it's better be protected from the parser's craziness.

**Comment by JonFerraiolo** [comment]
@rubimazaki  Interesting idea. Because of the way the code works (somewhat convoluted), I don't think it would be a 2-line change, but something in the direction you propose is definitely something we should explore.
