### ISSUE TITLE
Mobile theme not being displayed on page create

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3528]
1) from project1 create a mycustom  mobile theme
2) Create a mobile page that use mytheme for all devices
3) save the file
4) create a new project 
5)Create a new mobile page, do not change the theme.

 notice that a themeMap gets added to the source but the .\* but that the theme location is empty.

I think that  we are using a themeMap in a sticky somewhere and the theme is not valid in the new project.

**Comment by JonFerraiolo** [comment]
I see a file `.settings/maqetta.dojo.themesets.settings` in each project area. I'm not sure who saves that file to make things sticky.

**Comment by billreed63** [comment]
The issue is that the new file options are save in the workbench `Workbench._state.nhfo` and this value is not reset when the project is changed. So the values for themes could contain themes that so not exists in the current project.
The new file option should be saved on a project level not a workspace level I opened issue #3534 for this feature.

**Comment by billreed63** [comment]
@JonFerraiolo @jhpedemonte  If we are doing a 7.0.2 we should really consider this one also.
