### ISSUE TITLE
New HTML File options should be saved as project prefference

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3534]
New file options are currently saved as a workbench setting `Workbench._state.nhfo` one of the things in the options is the themes to use when creating the page. The themes are at the project level not the workbench so When the user switches to a new project they  `Workbench._state.nhfo`  are reset to the defaults. It would be nice to save the last used options for this project and reuse them when in this project 

Related to #3528

**Comment by JonFerraiolo** [comment]
Should be easy to do. Just enhance the workbench state to save the new html file options in an associative array indexed by project name. 

Hope it's ok - I reassigned this to me because I've messed with the workbench state in the past and I think I know where all the gotchas are.

**Comment by billreed63** [comment]
That's fine, don't forget to back out the change I made in #3528 that clears the options when the project is changed.
