### ISSUE TITLE
Major source editor problems with 702

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3540]
@jhpedemonte 

On Mac/FF, running today's build off of the maqetta-test server, the source editor only shows the first N lines and nothing is editable.
- Open samples/Sample1.html
- Go to Source view

Result=> Only the first 20 lines show of the source code, and you can't edit the lines that show.

**Comment by JonFerraiolo** [comment]
I'll keep investigating this to see if same problems exist in Chrome and when running from Eclipse.

**Comment by JonFerraiolo** [comment]
Same sort of problem in Mac/Chrome. Here is stack track:

```
clone (davinci.js:16511)
_ced (davinci.js:16464)
_1bf6._updateStyler (davinci.js:37801)
_1bf6.setVisible (davinci.js:37734)
_1a02.switchDisplayMode (davinci.js:34850)
_1a02.switchDisplayModeSourceLatest (davinci.js:34816)
_1af9.run (davinci.js:36048)
_980._runAction (davinci.js:12849)
lang._hitchArgs (dojo.js:4947)
_1deb._onClick (davinci.js:40421)
_272 (dojo.js:2802)
_2df3._onClick (davinci.js:65352)
lang.hitch (dojo.js:4963)
_20a (dijit.js:2101)
```

Appears to be crashing deep in the bowels of the Orion source editor.

**Comment by JonFerraiolo** [comment]
Works in Eclipse with M7 branch.

Reassigning to @jhpedemonte because I suspect the build is pulling in the wrong version of Orion and/or Orion text editor code.

**Comment by jhpedemonte** [comment]
cc @peller, who's worked with Orion editor in the past.

**Comment by jhpedemonte** [comment]
Compared the plugins between this latest M7 build and 701.  Some Eclipse/Equinox plugins had minor updates, as well as some of the Zazl dependencies.  But I don't think any of that should cause what we are seeing.

**Comment by peller** [comment]
the actual exception appears to be related to line 455 in textMateStyler.js (Orion code):

```
clone: function clone(obj) {
```

shrinksafe seems to be getting confused about the local function name for "clone" (The JS rules about this are admittedly very awkward)  Why this was never a problem before, I do not know. It appears that shrinksafe renames references to clone as _cf2, but never changes the definition so it's undefined.  Somehow, perhaps some other change made which ends up in the davinci layer is affecting the way Shrinksafe runs overall?

**Comment by peller** [comment]
It looks like the JS layer is in an entirely different order.  Given that Rhino does not guarantee order in hashes, I guess this isn't surprising.  So it's possible that there was always a Shrinksafe bug on this expression but we were lucky not to hit it until now.  It may be nearly impossible to address that bug, so...

The easiest thing, I think, would be to just avoid it and rewrite the clone method at the top of the closure.  There's no reason it has to be a member of the object.  We'd want to get this change into the main Orion code as well.

@skaegi

**Comment by jhpedemonte** [comment]
@peller, @JonFerraiolo, have either of you tested "master" builds with this fix?  If it works, we need to merge into M7 branch as well.

**Comment by peller** [comment]
works for me

**Comment by JonFerraiolo** [comment]
> works for me

Which one works? M7, master, or both? Are you pulling down nightly builds or running from Eclipse? When I tried a nightly build of M7 yesterday, I saw the same problem.

**Comment by peller** [comment]
downloaded a build of master this morning and it worked. As @jhpedemonte points out, the fix has not yet been cherry-picked to M7

**Comment by peller** [comment]
filed [a request](https://bugs.eclipse.org/bugs/show_bug.cgi?id=392666) to have this change made to the Orion repository

**Comment by jhpedemonte** [comment]
Just cherry-picked onto M7 branch.  Will test again when those builds are ready.

**Comment by jhpedemonte** [comment]
Working now.  Closing.
