### ISSUE TITLE
SpinWheel labels property incorrectly processed in props palette

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3543]
Working on my article, for SpinWheelSlot I notice if I paste "0,1,2,3,4,5,6,7,8,9" into the the `label` field in the Properties palette (instead of putting it into smart input) that it processes it incorrectly and puts commas into the SpinWheel slot:

![GitHub Logo](http://i.imgur.com/2U1D0.png)

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte for time being
