### ISSUE TITLE
Null values in comment emails

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3548]
@aerwin 

I was testing a 702 build and added comments to a review page (I was the author). I got emails about the comments that looked like this:

```
foo@example.com added comment on your page file2.html:
Comment owner:  null
Comment subject:    aaa
Comment content:    
Page name:  null
Page state: null
Time:   Tue Oct 23 13:42:13 CDT 2012
```

Maybe we need to update the logic that sends out notifications about review comments to reflect new data structures?

**Comment by jhpedemonte** [comment]
I changed (a bit) how we handle user IDs vs emails, with regards to Orion users.  This issue could have been caused by that.  My guess is that we just need to update the logic that constructs the email.

**Comment by JonFerraiolo** [comment]
Closing - I don't see the nulls with latest build on maqetta-test

**Comment by jhpedemonte** [comment]
Right, this was fixed when I updated the email templates to work with Orion email APIs.  I took the time to redo our email contents, removing most of these (unnecessary) fields.
