### ISSUE TITLE
Today's build: Scenes palette didn't Normal upon creating first HTML file

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3553]
(Prio-Critical to investigate for M8)

@jhpedemonte @billreed63 

When I first run today's build and created a new HTML file (desktop app in this case), the Scenes palette didn't show Normal. Upon save, close, reopen, "Normal" appeared.

Knowing how StatesView.js works, I suspect a timing problem, and probably an exception. StatesView is supposed to always show a Normal state. If the "refresh" logic in StatesView.js gets called, it should end up showing a Normal state in all cases.  (The Normal state isn't stored in the file - it's just assumed to be there always.)

**Comment by jhpedemonte** [comment]
I haven't been able to reproduce this on maqetta-test.

**Comment by JonFerraiolo** [comment]
I couldn't reproduce this either. Moving from Prio-Critical to Prio-Medium for M8.

**Comment by JonFerraiolo** [comment]
Couldn't reproduce on maqetta-test either with latest build. Closing.
