### ISSUE TITLE
Can add data  DataCarousel: Data file from workspace

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3555]
from the test case DataCarousel: Data file from workspace

Steps
Open the Dojox Mobile folder in the Widget palette.
Drag a View widget onto the canvas.
Drag an DataCarousel widget onto the canvas.
SmartInput is displayed. Choose Data file from workspace from the drop down list on the first panel of the wizard.
Click on the folder icon.
The select a source dialog will be displayed, navigate to the samples/sample_data folder and then select the DataCarousel_data.json file. Click the OK button
The DataCarousel should be updated with the data from the file.
Save and close the file.
Reopen the file
Click on the preview icon in the toolbar, this should open a new browser window and the DataCarousel should be displayed with the data from the file.

**Comment by jhpedemonte** [comment]
This worked just fine for me (with the one difference being that the data file is called _carousel_data.json_).  Please reopen if you still see any issues.
