### ISSUE TITLE
Support Dialog added in source

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3566]
While we don't currently support drag/drop of **dijit.Dialog**, we should allow users to add it in source and support the loading of that page.

A [user tried to do just that](https://groups.google.com/d/topic/maqetta-users/O0FJH1se0No/discussion), but got an error when reloading the page:

```
oh oh! An error has occurred:
_2304 is undefined
file: http://localhost:50001/maqetta/app/davinci/davinci.js?3773ee26d1da0e59eda6a108772a6b8990d2c25c
line: 48950
```

The page he created contained the following HTML:

``` html
<div data-dojo-type="dijit/Dialog"
      data-dojo-id="dropTextDialogConfirm" title="Bestätigung">
      <div class="dijitDialogPaneContentArea">
        <span>Möchten Sie diesen Eintrag wirklich löschen?</span>
      </div>
      <div class="dijitDialogPaneActionBar">
        <input type="hidden" name="dropTextOid" id="dropTextOid">
        <button data-dojo-type="dijit/form/Button" type="submit"
          id="dropTextYes">Ja</button>
        <button data-dojo-type="dijit/form/Button" type="button"
          onClick="dropTextDialogConfirm.hide();editTextDialog.show();">Nein</button>
      </div>
    </div>
```

@JonFerraiolo @peller 

(Assigning to myself for now, but feel free to take it if you want.)

**Comment by peller** [comment]
works for me on master...

**Comment by jhpedemonte** [comment]
Hmm, quite.  I just tried on M7:  I created a new Desktop App, added the above code into the `<body>`, and added "dijit/Dialog" to the `require` statement.  Saved, closed, reopened -> works fine.

I'll post back to the users group, asking for more details and a better recreate scenario.

Closing for now.
