### ISSUE TITLE
Outline view should expand parents & scroll to show selected widget

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#357]
@jhpedemonte

If I click on a widget that is inside of another widget and the Outline view
only shows the parent widget (it hasn't been expanded to show child widgets),
then the click should force the parent widget to expand in the Outline view and
the correct child widget should be highlighted.  This may also involve
scrolling the selected widget into view.

**Comment by jhpedemonte** [comment]
@peller, didn't you just fix this?

**Comment by peller** [comment]
indeed. see #1823
