### ISSUE TITLE
damaged zip file

### ISSUE THREAD

**Issue by gsmida** [maqetta/maqetta#3573]
Windows 7 SP1 - Chrome 23.0.1271.64 m - Tested 3 times.
After downloading a file (from my workspace .zip) when I try to open it I got this error:
The archive file is either in unknown format or damaged.

**Comment by JonFerraiolo** [comment]
@billreed63 - can you please try this out on your W7 box?

**Comment by billreed63** [comment]
This worked for me, have you tried using another zip utility? Maybe try downloading without the libraries?

**Comment by billreed63** [comment]
@gsmida  if you are still having this issue please reopen.
