### ISSUE TITLE
Server error w/ cmd/setWorkbenchState

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3581]
While testing Review&Commenting (on Firefox), I kept seeing errors when invoking `cmd/setWorkbenchState`.  Here's the associated stack from the server code:

```
2012-11-28 19:11:39.494 [qtp6526955-25] WARN  o.e.jetty.servlet.ServletHandler - Error for /maqetta/cmd/setWorkbenchState
java.lang.AssertionError: commandDescriptor is null or is Put in Get processing
        at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:60) ~[na:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]
        at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:129) ~[na:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
        at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180) ~[na:na]
        ...
```

I don't really have a recreate scenario -- I just started using the latest Maqetta build on maqetta-test.

_Note:_  This was tested using workspaces created for M7; there may be migration issues.

@JonFerraiolo @peller @billreed63

**Comment by jhpedemonte** [comment]
This may be related:  I created a review of a mobile app page.  However, when loading the review, I saw the error above and the **device silhouette was not displayed in the review**.

**Comment by jhpedemonte** [comment]
Don't know what's going on here.  I only see this issue with Firefox (v.17, on OS X).

In the _Web Console_, I see:

```
no element found                      setWorkbenchState:1
```

When I click on that, it shows me:

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 commandDescriptor is null or is Put in Get processing</title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /maqetta/cmd/setWorkbenchState. Reason:
<pre>    commandDescriptor is null or is Put in Get processing</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>




















</body>
</html>
```

However, I don't always see a corresponding error on the server, which I would expect -- it only shows up sometimes.

What's odd is that if I look at the network request for the PUT to "cmd/setWorkbenchState", it seems correct;  it returns with HTTP code 200.

Can you guys please test with the latest FF to confirm?  I always see this when opening up a review, but also in many other situations.

**Comment by JonFerraiolo** [comment]
I created reviews and opened them using Mac/FF with Firebug open (running on the test server) and did not see any setWorkbenchState errors. I have FF 16.0.2.

**Comment by jhpedemonte** [comment]
Haven't seen this error lately.  Closing; will reopen if I see it again.

**Comment by jhpedemonte** [comment]
This is what I think is happening:

I am running the latest Firefox (v.17) with the **Web Console** open.  For many of the REST calls, the Web Console shows errors for "no element found" or "syntax error".  They all seem to do with invalid JSON (assuming very strict parsing).  All of these are innocuous.

One such error is one for "no element found" with a link to `setWorkbenchState:1`.  When I click on this link, up pops a dialog showing the [500 error](https://github.com/maqetta/maqetta/issues/3581#issuecomment-10888598) I posted above.

The issue is that when I click on that link to `setWorkbenchState:1` inside of Web Console, the Web Console code opens up another window and does a completely new GET request for the URL (in this case ending in "setWorkbenchState").  The Maqetta server code isn't expecting a GET for `/cmd/setWorkbenchState` and throws an error.

I had assumed that Web Console worked like the network panel in WebKit or Firebug, where it would show me the request.  Instead, it is generating an entirely new request, one which the server isn't expecting...
