### ISSUE TITLE
use slashes instead of dots when assigning data-dojo-type

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3583]
data-dojo-type should use the AMD module id "mid" syntax with slash delimiters instead of dots.  Both formats are supported until Dojo 2.0.

Would be nice to start spitting out this format SRTL if it's not too difficult.  Should probably continue to support both so we don't have to migrate documents over.

**Comment by peller** [comment]
rather than try to fudge this with a replace(/./g,"/") in the code, we should probably fix this throughout the metadata.  @jhpedemonte are we still generating the metadata, and if so how would we make that change?

**Comment by peller** [comment]
Necessary to take advantage of [auto require](http://livedocs.dojotoolkit.org/dojo/parser#auto-require) in Dojo 1.8+.  See #3189

**Comment by jhpedemonte** [comment]
No, it was auto-generated once, in order to get the JSON metadata files.  But now just directly edit the JSON files themselves.

**Comment by peller** [comment]
de88c0a79efdf441152178bf6c1228dd727aca51

**Comment by peller** [comment]
1318b17a5069a71f9be55227636da1a3740d601e
