### ISSUE TITLE
R&C doesn't show mobile device outline

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3590]
When I create a new review of a **mobile app**, the review page does not show a device outline.  This is a regression from M7.

**Comment by JonFerraiolo** [comment]
Sending back to @jhpedemonte to test this again and if it fails, provide more detail.

I don't see this problem, at least with a simple case. Using the external test server, I created a mobile app and added only one widget (a Heading), saved it, then created a review, inviting my alter ego (a second login). Using Mac/FF for my first login, I see the device silhouette, and I also see the device silhouette for my second login (using Mac/Chrome).

**Comment by jhpedemonte** [comment]
OK, I wasn't able to reproduce this with a new mobile file.  However, I have an older mobile file which exhibits this issue.  I sent you a review request under the title "old mobile file".  Not sure why this file causes the problem.

**Comment by JonFerraiolo** [comment]
Reopening and assigning to @jhpedemonte to test again the next posted build on maqetta-test to verify that the fix actually worked in a production build.

**Comment by jhpedemonte** [comment]
Confirmed.
