### ISSUE TITLE
New project creation fails

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3593]
Testing on maqetta-test using Chrome, tried to create a new project called "foobar".  Maqetta loads as if the new project has been created, however the project dropdown in the Files view shows I'm still on "project1" and that no "foobar" project exists.

I even switched over to Orion view, but saw no "foobar" directory.

@peller @JonFerraiolo

**Comment by jhpedemonte** [comment]
Deleting an existing project also doesn't work!

**Comment by jhpedemonte** [comment]
Sometimes works, sometimes fails.  When it fails, here's the request:

```
http://localhost:8081/maqetta/cmd/createProject?name=&initContent=true&eclipseSupport=false
```

Notice that `name` doesn't have a value.

**Comment by jhpedemonte** [comment]
In **NewProject.js**, the `okButton()` function pulls the project name from the dialog and creates the server request.

Testing on Chrome, if I enter the project name and hit **Enter**, this line:

``` javascript
    var newProjectName = dojo.attr(this._projectName, "value");
```

returns an **empty string**.  But I don't understand why.

`this._projectName` is a attached to Dijit Textbox widget, where its `displayedValue` and `focusNode.value` are both set to "foobar" (the project name I entered).  But querying its "value" returns an empty string.

@peller, any idea why?

**Comment by peller** [comment]
dojo.attr takes a DOM node.  It's best to get the value from the widget object (the Dijit TextBox) like myTextBox.get("value")
