### ISSUE TITLE
Two css files slow down page load

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3594]
@JonFerraiolo 

I think this goes back to Orion integration.  Both Maqetta's workspace.css and an orionMaqetta.css file are @imported directly into the top HTML file.  Unfortunately, that means two separate HTTP requests (immediately on page load, blocking other requests like JS loading) and the build tool cannot optimize them.  If the orionMaqetta.css reference were placed within workspace.css, the build tool would inline the content.  Perhaps this was difficult because of the plugin architecture.

It would seem we're doing this just for the Orion icon (only thing in the orionMaqetta.css file)  Perhaps we could just copy the CSS into the main file, for now to work around this problem?

**Comment by JonFerraiolo** [comment]
I wouldn't mess with this for M8.

**Comment by jhpedemonte** [comment]
-> M9
