### ISSUE TITLE
Deleting project doesn't fully complete

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3595]
After deleting a project, it still shows up in the project list.

**To reproduce:**
1. Starting with clean user, there will be a single project listed: "project1".  Also, if you look at the files on the file system, there will be a single directory (i.e. "a") in the users dir.
2. Create a new project.  After Maqetta reloads, the new project should be shown in the Files view.  On the file system, there will now be 2 directories (i.e. "a", "b").
3. Delete the new project: click on the red **X** next to the project name in the Files view.  This will cause Maqetta to reload and load the "project1" project.

**Expected results:**

There is only one project listed in the Files view dropdown ("project1").  On the file system, there is only the single directory corresponding to "project1" (i.e. "a").

**Actual results:**

The new project is still listed in the Files view dropdown (i.e. "project1", "foobar").  On the file system, there are 2 directories (i.e. "a", "c").  However, the dir corresponding to the new project has a **different name** than before the project was deleted; also, this dir has no contents.

(Spun off from #3593)

**Comment by jhpedemonte** [comment]
This has been broken since M7.

The following line in `OrionUser.getUserFile()` has a side-effect that it creates a directory if it doesn't already exist:

``` javascript
        /*
         * security check, dont want to return a resource BELOW the workspace
         * root
         */
        IStorage parentStorage = this.userDirectory.newInstance(a.toString());
```

Not sure if that's intended for that API, or if it's a bad side-effect.

**Comment by jhpedemonte** [comment]
Looks like @childsb made a mistake when creating `OrionUser.getUserFile()`.  Compare to `User.getUserFile()` (which was used before the move to Orion) -- the latter function checks for the existence of the given path, returning `null` if it doesn't exist.

Conversely, `OrionUser.getUserFile()` will create the file (by calling `newInstance()`) if it doesn't exist -- therefore, `OrionUser.getUserFile()` will never return `null`.

**Comment by jhpedemonte** [comment]
There's a few issues here.  The biggest is that **VOrionWorkspaceStorage.java** always creates a file (directory) on the file system (`VOrionWorkspaceStorage.exists()` always returns true).  This is different than how all of the other `IStorage` impls work, and has something to do with how Orion treats top-level directories (projects).

I'd like to fix that, but I'm still not sure how.  And a fix would be too risky for M8.

The other issue is in the client code:  when the project is deleted, `Resource.delete` sends out an event which get caught by `system/resource.resourceChanged`.  The code flows through the [first if statement](https://github.com/maqetta/maqetta/blob/b1fe3db77d3957b4efcb1338c667262285f4e247/maqetta.core.client/WebContent/system/resource.js#L18-L23), meant to catch a resource change on a project (the "root" here).

The problem is that that code tries to take actions on the resources children.  However, the resource (project) and its children have already been deleted.  In trying to get the children, the code does a request to `/cmd/listFiles` which, as stated above, recreates the directory for the (previously deleted) project.

It doesn't make much sense to go down this path for a deleted project.  So a quick fix for M8 would be to just skip over that `if` block for deleted resources.

**Comment by jhpedemonte** [comment]
@JonFerraiolo @peller I'd appreciate it if you guys could review my commit and my [logic](https://github.com/maqetta/maqetta/issues/3595#issuecomment-11315658).

**Comment by peller** [comment]
seems reasonable.

**Comment by jhpedemonte** [comment]
Closing.  The fix above is good for now.  The remainder will have to wait for when we can get rid of our server side files and go directly to Orion APIs.
