### ISSUE TITLE
Source editing problems with this file

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3601]
Source editing problems with the file listed at the bottom of this report. Assigning to myself for the moment to investigate further (particularly to make sure the file isn't corrupted somehow). Might end up with @peller or @billreed63 at some point.
- When I am split view, clicking on the button label's text ('qadfadfadfwerwe') causes the cursor to jump to the top of the source editor. (Also sometimes in pure source view)
- When I go to source-only mode, and attempt to add a character to this button with label 'qadfadfadfwerwe', I'm getting an exception when running development version in Mac/Chrome:

```
Factory.closeModel (Factory.js:41)
declare.close (CSSImport.js:55)
declare.close.visit.visit (CSSFile.js:53)
declare.visit (CSSImport.js:28)
declare.visit (Model.js:149)
declare.close (CSSFile.js:50)
declare.close (ThemeModifier.js:223)
declare.close (ThemeModifier.js:222)
declare._updateDojoConfig (Context.js:3234)
declare.addJavaScriptSrc (Context.js:2939)
_loadJSFile (Context.js:433)
declare.loadRequires (Context.js:460)
declare.loadRequires (Context.js:448)
declare._setSource (Context.js:862)
ret.withDoc (window.js:121)
declare.setSource (Context.js:687)
declare._setContentRaw (VisualEditor.js:310)
declare._setContent (VisualEditor.js:266)
declare.setContent (VisualEditor.js:258)
declare._srcChanged (PageEditor.js:315)
lang.hitch (lang.js:373)
target.(anonymous function).dispatcher (aspect.js:94)
onTextChanged (Editor.js:66)
dxt.doLater (doLater.js:38)
```

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'async':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'idx','location':'../../idx'},{'name':'idxThemes','location':'../../../themes'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}],'themeMap':[['Android','',['themes/oneui_android/oneui_android.css']],['BlackBerry','',['themes/oneui_ios/oneui_ios.css']],['iPad','',['themes/oneui_ios/oneui_ios.css']],['iPhone','',['themes/oneui_ios/oneui_ios.css']],['.*','',['themes/oneui_ios/oneui_ios.css']]],'mblThemeFiles':[], mblLoadCompatPattern: /\/p22\/themes\/.*\.css$/"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dojox/mobile",
  "dojox/mobile/deviceTheme",
  "dojox/mobile/compat",
  "dojo/hash",
  "dojox/mobile/ScrollableView",
  "dojox/mobile/Accordion",
  "dojox/mobile/ContentPane",
  "dojox/mobile/Button"
]);
</script>
<style>@import "themes/oneui/oneui.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"></meta>
</head>
<body class="oneui" data-maq-device="iphone" data-maq-flow-layout="true" data-maq-comptype="mobile" data-maq-ws="collapse" data-maq-appstates="{}" id="myapp">
 <div id="ScrollableView_0" data-dojo-type="dojox.mobile.ScrollableView" selected="true">
  <div data-dojo-type="dojox.mobile.Accordion" fixedHeight="true" roundRect="true" style="height: 209px;">
    <div data-dojo-type="dojox.mobile.ContentPane" label="Pane 1" selected="true">
     <button data-dojo-type="dojox.mobile.Button">
       Button</button>
   </div>
    <div data-dojo-type="dojox.mobile.ContentPane" label="Pane 2">
     <button data-dojo-type="dojox.mobile.Button">

       bbb</button>
     <button data-dojo-type="dojox.mobile.Button">
     qadfadfadfwerwe</button>
     <div id="View_0" data-dojo-type="dojox.mobile.View" style="height: 92px;" selected="true">
      <h1 label="0" data-dojo-type="dojox.mobile.Heading" style="width: 174px; height: 62px;"></h1>
      <div>
     <div>
       <input></input>
       <label>
       bbb</label>
       <label>
         ccc</label>
     </div>
     <label>
         aaa</label>
       <input style="width: 166px;"></input>
     </div>
      </div>
     <div id="View_1" data-dojo-type="dojox.mobile.View" style="height: 106px;">
      <h1 label="1" data-dojo-type="dojox.mobile.Heading"></h1>
    </div>
   </div>
  </div>
</div>
</body>
</html>
```

**Comment by JonFerraiolo** [comment]
@jhpedemonte 

I looked into this issue some, and am pushing to M9. 

Can be reproduced by simply creating a new mobile app, adding a View, add a LABEL, then split view, and click on the label's text.

The problem is a combination of the source->design->source logic in combination with the view management logic in ViewHelper.js and the attempt in Context.js:setStatesScenes to restore previous values for states and scenes.

The source->design->source logic really should restore the scroll amount and cursor position at the end of the cycle where updated source is sent to VE, which causes new source creation, which it then sent back to Orion TE. Especially if oldsourcecode == newsourcecode (which I believe is the majority case). This fix would address the majority of the problems users still have where the cursor jumps up to the top.

Regarding ViewHelper.js, one change that appears advisible for early in M9 is to change line 114 from this:

```
                        if(domClass.contains(n,"mblView")){
```

to this (because we shouldn't be checking the current node both for being visible and being invisible):

```
                        if(n != node && domClass.contains(n,"mblView")){
```

Regarding `setStatesScenes`, it is calling `Context.select()` to force selection of the current "scene" (in this case, a mobile view). It seems overkill to call `select()` when the objective is simply to restore visibility. However, a fix in that area is likely to have ripple effects across our view management logic.

**Comment by JonFerraiolo** [comment]
Reopening -> @peller 

I tried tonight's last night's nightly (http://maqetta.org/nightly/maqetta-orion-201304050100.zip) and followed these steps:
- Open Sample3-Mobile.html
- SaveAs into a different name (e.g., <root>/a1.html)
- Switch to second scene in Scenes palette
- Go into split-h mode
- In source pane, scroll towards bottom and type some extra characters into the string "Today's alerts"

Result=> after short delay (for consolidating key events), cursor jumps to top of source pane

**Comment by peller** [comment]
@JonFerraiolo see note on commit 77a2d13, above.  It seems the addition of davinci/commands/SourceChangeCommand generates an additional event on execute which may be resetting the text and the cursor.  Not sure how to avoid this, as there are timeouts involved and a very long, convoluted pub/sub model.

**Comment by JonFerraiolo** [comment]
Reopening. I just pulled latest code and tried the file listed at top of bug report, and I'm still seeing problems. The one difference, though, is that now the cursor jumps to the bottom of the file instead of the top of the file.

Also, see comments I added to d0b307af211b9a17f5d2fa2885fbd8a129bb85fc

**Comment by peller** [comment]
@JonFerraiolo I tried the example at the top, also the Sample3-mobile steps cited somewhere in the middle, all seem to work fine.   What steps did you take? Which browser?

**Comment by JonFerraiolo** [comment]
I tried again with "correct check-in" (1c539f6c0d1e678325152de1fdf83e1d23371577) and cursor is still jumping for me.

**Comment by JonFerraiolo** [comment]
Mac/Chrome

**Comment by JonFerraiolo** [comment]
@peller: I don't see the jumping in latest build on maqetta-test. OK with me to close again.
