### ISSUE TITLE
Restore editable property on *List and IconContainer

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3607]
Need to restore the 'editable' property on RoundRectList,
RoundRectDataList, EdgeToEdgeList, EdgeToEdgeDataList, IconContainer.

**Comment by JonFerraiolo** [comment]
Amounts to undoing this commit: c27f42da4fd3910be21e1fabae26c971b974293b

**Comment by jhpedemonte** [comment]
See discussion in #3606 for correct fix (in addition to restoring `editable` prop).

**Comment by jhpedemonte** [comment]
-> M10

**Comment by jhpedemonte** [comment]
This was already reverted in 12c30c1f7959380fd35f229515d14cce63330c5b.
