### ISSUE TITLE
Hosted build: register button doesn't check to see if user already exists

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3609]
In the standalone configuration, if a given user exists, the server responds with an error code and error message, which LoginWindow.js displays properly. However, for the hosted confirmation, the server responds with "OK" even if the user already exists, and there is no logic in LoginWindow.js to look at the POST response and post the error message properly.

**Comment by jhpedemonte** [comment]
Isn't this fixed by commit to #3413?

**Comment by JonFerraiolo** [comment]
I can't remember what I was thinking when I logged this bug. I think there was an aspect that was different than #3413 but I can't remember it right now. Let's leave it open and see if my memory improves.

**Comment by JonFerraiolo** [comment]
I looked at this again, and yes I believe that the fix for #3413 takes care of this issue. Closing.
