### ISSUE TITLE
Do we need a $library setting for custom widgets for non-Dojo libraries?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3613]
@jhpedemonte - For M8, please look at the FIXME I will be adding (later today) to maqetta.core.client/WebContent/davinci/de/DijitTemplatedGenerator.js about whether we need to include a $library property for non-Dojo libraries.

**Comment by jhpedemonte** [comment]
I don't know that code well, but I don't think you need that line.
