### ISSUE TITLE
Add "clear" icon inside filter text area at top of widget palette

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3616]
It would be nice to have a "clear" icon inside the filter text area in the widget palette, which would quickly clear out the text and revert the widget palette to pristine shape.

A small X (standalone or in a circle) would work.  Should only be shown when there is text.  Also, we may only want to show it when the mouse cursor is inside the text area bounds.

If too much of a pain to implement, can push off to M9.

**Comment by JonFerraiolo** [comment]
Pushing to M9
