### ISSUE TITLE
Cannot open/view projects in Orion

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3619]
Some of us have run into an (intermittent) issue where, when switching to Orion, we cannot open/view some project folders.  Orion reports:

```
undefinedYou are not allowed to access
```

@skaegi, have you guys ever run into a similar issue?  We are still running Orion 0.5.

@JonFerraiolo @peller

**Comment by skaegi** [comment]
I've never seen it and even then am not sure why it would be intermittent. I did a search for "allowed" of our current code base and saw nothing that could match the string you mention. Do you see anything in the console?

**Comment by jhpedemonte** [comment]
The actual message is `undefinedYou are not authorized to access http://localhost:8081/file/u/`, in the Orion Navigator area:

![Screen Shot 2012-12-12 at 10 55 09 AM](https://f.cloud.github.com/assets/711365/8635/c6162ca2-447c-11e2-88da-77648afa39cc.png)

I think some of this may be due to #3595.  Maqetta shows 3 projects:

```
project1
foobar
samples
```

"project1" is my currently active project.  "foobar" is a project that I deleted, but the listing came back (see #3595).  I don't know where "samples" came from.

@JonFerraiolo, you ran into a similar issue.  For the project which you could open in Orion, was it a legit project or one you had previously deleted?

**Comment by jhpedemonte** [comment]
-> M10

**Comment by jhpedemonte** [comment]
Closing.  As part of moving to Orion 1.0+, had to change how Orion user rights are set, which should have fixed most of the issues here.  Any remaining work will take place in linked issues.
