### ISSUE TITLE
No reset passord link for "maqetta-orion multi user" configuration

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3620]
While the "maqetta-orion hosted" run configuration does show a reset password link, the "maqetta-orion multi user" one does not.

**Comment by JonFerraiolo** [comment]
I think the reason one of our former team members did that was that maqetta-orion multi-user (i.e. standalone) usually doesn't have a hook into an email system, so the normal reset password capability usually won't work.

What we would need instead is a more direct mechanism for resetting password that doesn't involving looping through the email system.

**Comment by jhpedemonte** [comment]
Hmm, yes, I see.  Of course, we can't make it too easy, or anyone could come along and reset passwords for any user, defeating the point of having passwords!

**Comment by JonFerraiolo** [comment]
Best idea I have: we could provide an additional API in the server that allows JavaScript to reset password and this API would only be active in the standard version. Make it off by default and then the "standard" version could override that default to enable the password reset shortcut.

**Comment by jhpedemonte** [comment]
FYI: the **administrator** for the server can change the password as follows:
1. In your Maqetta directory, edit the file **maqetta.conf**.  Uncomment the line which contains `orion.auth.admin.default.password`; if you wish, you may also change the default admin password there.  Save the conf file and close.
2. Start up the Maqetta server.
3. Load http://localhost:50000/profile/user-list.html in your browser.  Log in as `admin`, using the password from **maqetta.conf**.
4. For the user whose password you want to change, click on that user's **Change Password** button.  Enter the new value.

**Comment by JonFerraiolo** [comment]
-> future

**Comment by jhpedemonte** [comment]
Closing.  We now follow Orion more closely: if email is hooked up on the server, then a reset link is provided.
