### ISSUE TITLE
Drawing tools circle not working on FF 17

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3628]
on FF 17 win 7

created new hifi desktop sketch 
DnD circle onto VE

I get a pin point circle that I am unable to resize

**Comment by JonFerraiolo** [comment]
No problems for me with Mac/FF17. I'll have to try it on my Windows box.

**Comment by JonFerraiolo** [comment]
Worked for me on Win/FF17.0.1

**Comment by JonFerraiolo** [comment]
Pushing to M9. Appears to be a graphics bug in FF when running on particular systems.

**Comment by JonFerraiolo** [comment]
-> @billreed63 to verify if he sees bug with M9

**Comment by billreed63** [comment]
Works now
