### ISSUE TITLE
trouble registering e-mail with "+" sign

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3635]
I tried registering peller+test@gmail.com (a valid e-mail) and ended up getting the activation e-mail, but clicking on the link and submitting the form resulted in a 403.

1) The responseText was a full HTML doc, not a JSON message, so JSON.parse in loginWindow.js threw instead of posting an error to the screen
2) I'm thinking maybe the "+" in the url ought to be escaped.  Otherwise, it might be interpreted as a space, unencoded?

**Comment by jhpedemonte** [comment]
This was fixed by using the Orion 1.0+ email APIs.
