### ISSUE TITLE
can't scroll to "register" when screen is vertically small

### ISSUE THREAD

**Issue by not-a-kiwi** [maqetta/maqetta#3639]
Register button is not visible unless I go "full screen" using F11; moreover scrollling does not work.
Using Firefox 17, 1360x530 viewport (1360x720 screen with various system and browser toolbars).

**Comment by JonFerraiolo** [comment]
Thanks for the report! We'll making the login screens scrollable for the first release that comes out in 2013. Until then, our apologies and hope you can find a way to click on that register button. 

But note that the whole Maqetta UI will probably not work well with such a small screen. Fixing that would be a much more difficult effort than making the signup screen scrollable.

**Comment by JonFerraiolo** [comment]
-> M10
