### ISSUE TITLE
Paste tool and click/click behavior on widget palette broken

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3649]
When pasting, I get this exception:

```
Uncaught TypeError: Object [object Object] has no method 'getContentPosition' CreateTool.js:88
declare.onMouseDown CreateTool.js:88
declare.onMouseDown Context.js:2323
lang.hitch
```

To reproduce:
- New desktop app
- Add an HTML button
- Copy, then paste that button

The exception also happens when trying to add a widget by first clicking on the widget in Widget Palette and then click again on the canvas.
- New desktop app
- In widget palette, click on a Dojo button widget in widget palette, then click on canvas.

**Comment by JonFerraiolo** [comment]
Looks like we are simply missing an underscore in a few places within CreateTool.js

**Comment by peller** [comment]
oops.  c55d9500c3c798701c417f370db787462dae6a8b  I'm on it.  (Thanks!)
