### ISSUE TITLE
Make asterisk for unsaved changes more prominent

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3654]
Add extra space between asterisk and filename?

Can we make asterisk bigger or bolder?

@jinsil

**Comment by JonFerraiolo** [comment]
@jinsil I moved the asterisk to the right side (used to be on the left) due to my fix for #3675, and it now looks like this:

![Screen Shot 2013-02-28 at 9 52 51 AM](https://f.cloud.github.com/assets/706721/205735/981ea212-81b6-11e2-92c7-e540ed912aa8.png)

Do you have any suggested additional styling tweaks, such as making the asterisk a little bit bigger, or is it OK as is? It would be super-easy for me to do pixel-tweaking on the space between the file name and the asterisk, to shift the asterisk up or down by a pixel or two, or make the asterisk bigger or smaller (relative to the file name).

Note that the text and the asterisk are both bold in the picture above because that tab is currently selected. (Unselected tabs have normal).

**Comment by JonFerraiolo** [comment]
Got feedback from @jinsil that current implementation is fine, so closing this issue.

**Comment by JonFerraiolo** [comment]
I added a hard-crafted asterisk image (instead of just telling browser to render an asterisk character), and this is how things look now:

![Screen Shot 2013-02-28 at 2 49 21 PM](https://f.cloud.github.com/assets/706721/206998/6f8a2e50-81e0-11e2-84fc-a98138179d8d.png)

**Comment by jinsil** [comment]
Hi Jon, Looks good to me... 
It is courier size 18 px. If you would like to use with text instead image....
Thanks,

**Comment by JonFerraiolo** [comment]
@jinsil: Image is fine. At runtime, it's embedded into a sprite, so no impact on performance for having it in an image.
