### ISSUE TITLE
Update to dojo 1.8.3

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3655]
The [Dojo 1.8.3 release](http://bugs.dojotoolkit.org/milestone/1.8.3) is trivial, but there's no reason not to update to the latest tag.  There was [a typo in one of the buildscripts](http://bugs.dojotoolkit.org/ticket/16487) that triggered this extra release.

**Comment by peller** [comment]
@JonFerraiolo Need your help again.  My dojo-src/dojox still seems to be stuck at 1.8.1 and isn't getting new git tags.  Could you please do the following:

```
cd davinci.dojo_1_8/WebContent/dojo-src/dojox
git fetch --tags
git checkout 1.8.3
cd ..
git add dojox
git commit
```

Thanks!

**Comment by JonFerraiolo** [comment]
See 3a4fe4605ad623d8982b323714aefe835f8d048d
