### ISSUE TITLE
Thoroughly test gridx (gridx data sometimes disappears)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3667]
One user reports: 

I had a table with 6 columns and when I would go to edit it, either the edit field would be empty or it would have a few of the columns listed, but not all. So I had to keep typing them in and then moving them over to the right select list. This happened for 75% of the time I was working on the prototype. Then suddenly it saved all of my columns. I don't know what I did differently to make it stick.

**Comment by JonFerraiolo** [comment]
-> M10

**Comment by JonFerraiolo** [comment]
->@billreed63 in hope he has some familiarity with SmartInpuyt for gridx.

Enter this data to reproduce:

```
1,2,3,4,5,6
a,b
```

Then close the gridx wizard and then double-click to reopen the wizard. You'll see something like this:

```
1,2,3,unique_id
a,b,1,1
```

**Comment by billreed63** [comment]
fixed by above commit
