### ISSUE TITLE
File tab should show asterisk to right side, as superscript

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3675]
@jinsil

![file_tab_dirty](https://f.cloud.github.com/assets/706721/87562/aecd827c-64c8-11e2-9712-a150256287e2.png)

**Comment by jinsil** [comment]
Looks good to me... if anyone have problem with the current implementation in the future, then I would go with red color: #cc0000. But I am OK as the current implemented bold black. Text and the asterisk are both bold #333333.  Thank YOU!!!

**Comment by jinsil** [comment]
I attached asterisk image file as I found a bit different between actual screen caputer and the enlarge size of your screen capture
