### ISSUE TITLE
500 error getInitializationInfo needs UI

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3691]
for example, if loading from a war, but siteConfig info is not provided, the login will bomb out with this error.  Needs to be surfaced through the HTML page somehow.  Right now, you see an empty page and the error appears only on the console.

**Comment by billreed63** [comment]
These are site configuration issues, that can not be addressed by the average user, I would suggest that we need administration pages that the site administrator would use to check the health and proper configuration of the server. 
The user could login to this page and this page/code would integrate the site configuration.
@JonFerraiolo
