### ISSUE TITLE
Review URL doesn't come up successfully after clicking hyperlink

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3695]
@peller @jhpedemonte @billreed63 

On Mac/FF, Maqetta did not successfully open a review URL via clicking on the hyperlink in an email. The review editor does not seem to initialize properly. I have been seeing problems in this area the past couple of weeks but haven't had time to scope out the problem. 

I've seen problems such as the Properties palette from the page editor are still visible (vs showing the Comments palette) and when I tried it just now, the review page loaded OK and the Comments palette was there, but the Scenes palette was empty. Below are console messages from Firebug for the case when the Scenes palette was empty:

```
TypeError: this._srcDocument is undefined
https://maqetta-test.austin.ibm.com:60000/maqetta/maqetta/app/davinci/davinci.js?945b59ee2465811b8dc66e28188f32ef7fdb59f9
Line 57392
```

```
TypeError: cs is null
https://maqetta-test.austin.ibm.com:60000/maqetta/maqetta/user/C/ws/workspace/aaa/lib/dojo/dijit/dijit.js
Line 414
```

```
TypeError: this._srcDocument is undefined
https://maqetta-test.austin.ibm.com:60000/maqetta/maqetta/app/davinci/davinci.js?945b59ee2465811b8dc66e28188f32ef7fdb59f9
Line 57392
```

**Comment by peller** [comment]
-> @peller
