### ISSUE TITLE
(WAR) Theme editor hangs on open with WAR build

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3702]
@jhpedemonte @peller 

(Note: works with maqetta.org / external build)

I'm running Mac/FF. Using the WAR build, when I try a Create->Theme command 
cloning claro, the spinner just keeps spinning. The network panel shows this
message:

```
GET dojo.js

404 Not Found

maqetta-test.austin.ibm.com:60000
```

**Comment by billreed63** [comment]
mobile theme editor has similar issue

**Comment by billreed63** [comment]
Fixed by above commits
