### ISSUE TITLE
(WAR) Session timeout -> welcome page -> Tomcat error page

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3704]
My session timed out in the WAR build, and I got redirected to https://maqetta-test.austin.ibm.com:60000/maqetta/welcome` instead of `https://maqetta-test.austin.ibm.com:60000/maqetta/welcome`

```
HTTP Status 404 - ProxyServlet: /maqetta/welcome

type Status report

message ProxyServlet: /maqetta/welcome

description The requested resource is not available.
Apache Tomcat/7.0.35
```

**Comment by JonFerraiolo** [comment]
@billreed63 @peller

**Comment by billreed63** [comment]
Fixed by the above commit's in the latest build
