### ISSUE TITLE
Add msg that email is required, for hosted build registration page

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3706]
We have a lot of people that try to register using non-sensical email addresses.  We should add text to the registration page which states that users must provide a valid email in order to register their account.  Also, that the user should check the entered email carefully:  I see a lot of "hotmial.com" and "gamil.com" mispellings.

> A **valid email** is required in order to create an account.  Please check that your email is spelled correctly before submitting.

Something like that?

**Comment by JonFerraiolo** [comment]
![Screen Shot 2013-01-29 at 11 19 36 AM](https://f.cloud.github.com/assets/706721/108305/e3c511a4-6a48-11e2-9072-765c14922823.png)
