### ISSUE TITLE
References to 'top' prevent maqetta from running in an iframe

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3710]
Pretty far-fetched, I know, but I ran into this browsing to a review link in iNotes, where the link is followed in-place in an iframe.

References to the global "top" may result in a security exception if Maqetta is embedded in an iframe and the "top" is therefore some other document in another domain (like iNotes)  I hit this first in shouldInitialize in appStates, but we probably have many references like this.

**Comment by jhpedemonte** [comment]
Yes, we should clean these up.  Relying on `top` can be sloppy and lazy -- better to be direct and more strict, by using `parent`, etc.

**Comment by peller** [comment]
see 28763243f3466b859495e2e47889634a4a7b4488

**Comment by peller** [comment]
->M10  @JonFerraiolo there's one reference to top.davinci.Runtime in AppStates that needs to be changed.  Either we find a way to remove the global top.davinci reference, or we'll need to put the definition back for davinci.Runtime, which is now referenced via AMD everywhere else.

After that, if there are other 'top' references remaining in the code, we can defer this bug again.
