### ISSUE TITLE
Can not create Maqetta Project from Orion in War environment 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3719]
Create Project from Orion

Steps
Login to Maqetta. Select Open > Orion Navigator to open Orion in a new tab.
In Orion, select New > Folder. Click to open the newly created folder.
Create another new folder here.
Select the new folder by clicking on the same line, but to the right of the folder text (the whole row should be highlighted). Select Actions > Open in Maqetta.
When Maqetta opens, verify that the default project files are listed in the Files view. Also verify that the proper project is open in the project drop down.
Open Sample1.html. Add a widget. Save/preview/close.
Select Open > Orion Navigator to go back to Orion.
Expand the folders you created. Open Sample1.html and verify that the widget you previously added is in the source.

**Comment by jhpedemonte** [comment]
Yes, Orion side of things are still broken when running from a WAR.

@peller

**Comment by jhpedemonte** [comment]
This has now been fixed, on master and M9 branch.
