### ISSUE TITLE
can not Create New User as Orion Administrator in war environment.

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3721]
Create New User as Administrator

Steps
Log out of Maqetta.
Load the URL http(s)://maqetta_base:port/profile/user-list.html (include "/context" if testing WAR build).
Login as user "admin". You should see a list of all registered users.
Click on Create User and create a dummy user.
Try to login as that user.
NOTE: You may want to use a different browser for the dummy user, so you don't have to log out of "admin" account.
Log back in as "admin" and change dummy user's password. Try to login as user again, using new password.
Log back in as "admin" and delete user. Make sure that you cannot log in as dummy user.

**Comment by jhpedemonte** [comment]
This won't work when using LDAP or similar authentication features, since users are checked against an authorization server -- creating a user and password here won't work.

I'll update the test case to state that this will only work when Maqetta/Orion itself is handling the authentication.
