### ISSUE TITLE
Cannot open theme editor on Claro clone

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3723]
Tried to create a new theme based on _claro_ on FF/OS X, but Theme Editor hung displaying "Loading".  This is with our WAR build.

Tried to close/reopen and even reloading Maqetta page, but the Theme Editor will not open.

In the FF console, I see:

```
ReferenceError: require is not defined @ https://maqetta-test.austin.ibm.com:60000/maqetta/maqetta/:16
```

That line corresponds to this:

``` html
    <script type="text/javascript" src="app/dojo/dojo.js?57f3646f2efee129bb4ea1f3a7e0f5396bed8ba0" data-dojo-config="
        async: true,
        parseOnLoad: true,
        modulePaths:{'preview':'../preview', 'system':'../system'},
        aliases:[['i18n', 'dojo/i18n']],
        cacheBust: '57f3646f2efee129bb4ea1f3a7e0f5396bed8ba0',
        ioPublish:true
    "></script>
```

@peller @JonFerraiolo

**Comment by jhpedemonte** [comment]
Hmm, I created a new project and was able to properly create a new theme.  Corrupted project?  What should I check?

(Personal note: corrupted project is "project1", working project is "testing_2013_02_03")

**Comment by peller** [comment]
Able to do this fine on Mac/Chrome.  Any failures in the network panel?

**Comment by billreed63** [comment]
The very first war file build had an invalid path to the dojo libraries, we corrected the path so now the theme editor opens. Check the path in the theme editor html.  

I saw this same issue, but after correcting the path and using clean projects (projects that have been created after the first build) I have not seen the issue again.

**Comment by jhpedemonte** [comment]
Yeah, I'm going to close this out as due to a corrupted project.
