### ISSUE TITLE
Zazl preview fails with WAR build in Mac/FF

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3724]
@rbackhouse 

I created a file with a TabContainer and a Button inside of the TabContainer, turned the zazl preference to on, then clicked the preview button. On Mac/FF, the preview is empty and the firebug console says this: (Note: haven't tried on Chrome)

"NetworkError: 404 Not Found - https://maqetta-test.austin.ibm.com:60000/_javascript?modules=dijit/dijit,dojo/parser,maqetta/space,maqetta/AppStates,dijit/layout/TabContainer,dijit/layout/ContentPane,dijit/form/Button&writeBootstrap=false&locale=en-us&config=%7B%22directInject%22%3Atrue%2C%22injectUrl%22%3A%22%2F_javascript%22%2C%22packages%22%3A%5B%7B%22name%22%3A%22dojo%22%2C%22location%22%3A%22..%2Flib%2Fdojo%2Fdojo%22%2C%22main%22%3A%22main%22%7D%2C%7B%22name%22%3A%22dijit%22%2C%22location%22%3A%22..%2Flib%2Fdojo%2Fdijit%22%2C%22main%22%3A%22main%22%7D%2C%7B%22name%22%3A%22dojox%22%2C%22location%22%3A%22..%2Flib%2Fdojo%2Fdojox%22%2C%22main%22%3A%22main%22%7D%5D%2C%22paths%22%3A%7B%22gridx%22%3A%22..%2Flib%2Fdojo%2Fgridx%22%2C%22clipart%22%3A%22..%2Flib%2Fclipart%22%2C%22maqettaSamples%22%3A%22..%2Fsamples%22%2C%22maqetta%22%3A%22..%2Flib%2Fmaqetta%22%2C%22shapes%22%3A%22..%2Flib%2Fshapes%22%2C%22widgets%22%3A%22..%2Flib%2Fcustom%22%7D%2C%22baseUrl%22%3A%22%2Fmaqetta%2Fmaqetta%2Fuser%2FC%2Fws%2Fworkspace%2Fe1%2FWebContent%2Fa1%2F%22%2C%22scanCJSRequires%22%3Afalse%2C%22debug%22%3Afalse%2C%22config%22%3A%7B%7D%2C%22map%22%3A%7B%7D%7D&exclude="

**Comment by rbackhouse** [comment]
The 404 indicates that the mapping for /_javascript has not been registered. This is handled by the "maqetta.zazl" bundle. It would have to be in ACTIVE state for the registration to take place. Perhaps the WAR configuration is not ensuring its activated ?

**Comment by peller** [comment]
@jhpedemonte I don't get an osgi> prompt anymore.  How do we turn that back on?

**Comment by jhpedemonte** [comment]
@peller, edit the `WEB-INF/web.xml` in the WAR and add `-console` as stated in one of the comments.

**Comment by peller** [comment]
```
osgi> start 24
gogo: BundleException: Exception in maqetta.zazl.Activator.start() of bundle maqetta.zazl.
```

**Comment by peller** [comment]
stepping into the line

```
httpServiceTracker = new HttpServiceTracker(bundleContext);
```

results in

```
Exception occurred: java.lang.NullPointerException (to be caught at: org.maqetta.server.ServerManager.readConfigFile(), line=115 bci=131)"thread=Gogo shell", java.io.FileInputStream.<init>(), line=116 bci=62

  [1] java.io.FileInputStream.<init> (FileInputStream.java:116)
  [2] java.io.FileInputStream.<init> (FileInputStream.java:79)
  [3] org.maqetta.server.ServerManager.readConfigFile (ServerManager.java:96)
  [4] org.maqetta.server.ServerManager.<init> (ServerManager.java:72)
  [5] org.maqetta.server.ServerManager.getServerManger (ServerManager.java:124)
  [6] maqetta.zazl.Activator.register (Activator.java:73)
  [7] maqetta.zazl.Activator$HttpServiceTracker.addingService (Activator.java:123)
  [8] org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding (ServiceTracker.java:932)
  [9] org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding (ServiceTracker.java:1)
  [10] org.osgi.util.tracker.AbstractTracked.trackAdding (AbstractTracked.java:256)
  [11] org.osgi.util.tracker.AbstractTracked.trackInitial (AbstractTracked.java:183)
  [12] org.osgi.util.tracker.ServiceTracker.open (ServiceTracker.java:317)
  [13] org.osgi.util.tracker.ServiceTracker.open (ServiceTracker.java:261)
  [14] maqetta.zazl.Activator.start (Activator.java:40)
  [15] org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run (BundleContextImpl.java:711)
```

We had talked about putting in a log there and checking for a null config file.  Something like that shouldn't fail silently or fail as a NullPointerException.

**Comment by peller** [comment]
@rbackhouse Looking athead at maqetta.zazl.Activator.register() line 94:

```
httpService.registerFilter("/maqetta/user/*.html", maqetaHTMLFilter, null, null);
```

Should we be using a servletContext root instead?  For the war, the URL would have to match `/maqetta/maqetta/user/*.html`

**Comment by rbackhouse** [comment]
The OSGi bridge code should handle context root hookup. You don't want to have specify it in code otherwise a context root rename (e.g just by changing the name of the WAR) would be problematic

**Comment by jhpedemonte** [comment]
That exception means that you haven't specified the .conf file as an environment variable.  Search for `orion.core.configFile` on the [server setup page](https://github.com/maqetta/maqetta/wiki/Server-Installation-and-Setup).

> Should we be using a servletContext root instead?

I think the servlet code is smart enough to handle that and separate the servlet context from the request path.  I think that code is fine as is.

**Comment by peller** [comment]
@rbackhouse Ok, resolved all my setup issues and I still get the 404.  The maqetta.zazl bundle appears to have loaded.  'ss' shows it as `ACTIVE`

http://pastebin.com/uQqD5xRS

**Comment by rbackhouse** [comment]
Can I download the war from somewhere ?

**Comment by rbackhouse** [comment]
I think the issue now is that the context path is missing from the Zazl configuration written into the html by the filter. I have checked in some code that should prefix it now.

**Comment by peller** [comment]
Need to try @rbackhouse's [suggestion](https://github.com/maqetta/maqetta/commit/802f48815f32053515d9051b23758fbcce373040#commitcomment-2706954) to use the real servlet prefix with the osgi loader

**Comment by rbackhouse** [comment]
I have the changes ready to commit. To clarify MaqettaOSGiResourceLoader is now passed the context path and does this on the segment check in _getResource(path) :

```
    IPath ipath = new Path(path);
    if (ipath.segment(0).equals(contextPathSegment)) {
        ipath = ipath.removeFirstSegments(1);
    }
    if (ipath.segment(0).equals("maqetta")) {
        if (ipath.segment(1).equals("user")) {
            ipath = ipath.removeFirstSegments(2);
```

If this looks ok I'll deliver

**Comment by peller** [comment]
looks great. thanks, @rbackhouse

**Comment by peller** [comment]
_still_ getting a 404 on maqetta.org for _javascript (on all browsers) even without a war build, though I know we had this working previously.  Could be a deploy issue, perhaps unrelated to the original report

-> @future

**Comment by peller** [comment]
Looks like the path for dijit/popup is off somehow and it's just looking for 'popup':

```
Jun 10, 2013 1:32:00 PM org.dojotoolkit.optimizer.servlet.JSHandler$OptimizerRunnable run
INFO: Obtaining Optimization Data for [dijit/dijit dojo/parser maqetta/space maqetta/AppStates dijit/form/Button ]
Jun 10, 2013 1:32:00 PM org.dojotoolkit.optimizer.amd.rhinoast.AMDJSOptimizer _getAnalysisData
INFO: AST parsing [dijit/dijit] using the Rhino AST API
Jun 10, 2013 1:32:03 PM org.dojotoolkit.optimizer.amd.rhinoast.AMDJSOptimizer _getAnalysisData
INFO: AST parsing error for [dijit/dijit] error : Unable to obtain source for Module [/maqetta/user/E/ws/workspace/project2/WebContent/popup]
Jun 10, 2013 1:32:03 PM org.dojotoolkit.optimizer.servlet.JSHandler$OptimizerRunnable OptimizerRunnable
SEVERE: IOException while attempting to obtain Optimization Data for [dijit/dijit dojo/parser maqetta/space maqetta/AppStates dijit/form/Button ]
java.io.IOException: AST parsing error for [dijit/dijit] error : Unable to obtain source for Module [/maqetta/user/E/ws/workspace/project2/WebContent/popup]
        at org.dojotoolkit.optimizer.amd.rhinoast.AMDJSOptimizer._getAnalysisData(AMDJSOptimizer.java:149)
        at org.dojotoolkit.optimizer.CachingJSOptimizer.getAnalysisData(CachingJSOptimizer.java:86)
        at org.dojotoolkit.optimizer.servlet.JSHandler$OptimizerRunnable.run(JSHandler.java:330)
        at java.lang.Thread.run(Thread.java:722)
```

**Comment by rbackhouse** [comment]
Sounds like the dojo config is messed up or has changed.

Related to https://github.com/maqetta/maqetta/commit/f1b578e942fc88c6128251ae7b2dd107ae123a36 ?

**Comment by peller** [comment]
I think that checkin from @jhpedemonte looks ok...  Dojo redid the repository, so all the hashcodes needed to be redone.  I think the rest of the references remain the same (at least that was the intent)

I was wondering if somehow the -src references now point at built content.  Perhaps that would produce the kind of error I'm seeing?

**Comment by rbackhouse** [comment]
Yes if the src is no longer resolvable this is probably the sort of problem that would be seen

**Comment by rbackhouse** [comment]
@peller I just did a fresh setup using http://maqetta.org/nightly/maqetta-orion-201305240100.zip as a target and checkout from the repo. Preview works fine for me. 

I should note that I did the hack to remove the orion help servlet to get Zazl loading 100%

Removed this from the "org.eclipse.orion.server.configurator_1.0.0.xxxxx" plugin.xml in my target platform instance :

```
  <servlet
        alias="/help"
        class="org.eclipse.equinox.http.servlet.HttpServiceServlet"
        httpcontextId="org.eclipse.help.webapp.help"
        load-on-startup="true">
     <init-param
           name="other.info"
           value="org.eclipse.help">
     </init-param>
     <init-param
           name="server.description"
           value="Orion Help">
     </init-param>
  </servlet>
```

**Comment by peller** [comment]
seems to work fine on a new account.  
->m10, closing.
