### ISSUE TITLE
Download error message if unsaved dirty files

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3725]
Just logging this for now. Haven't investigated fully, but here is what I did on Mac/FF:
- New Eclipse project
- New desktop app
- Added TabContainer and Button inside the TC
- Preview
- Click on download entire workspace

Result-> Console error messages having to do with file1.html.workingcopy

I clicked Save on file.html and tried again and no console messages.

**Comment by peller** [comment]
Not able to reproduce this.  Any idea what the console error messages were?

**Comment by peller** [comment]
If you mean the "no element found" warnings, that seems to be a lint-type message that indicates there's no DOCTYPE on the file.  That's in the same class of errors as json not well formed, etc.  @JonFerraiolo, can you confirm?

**Comment by JonFerraiolo** [comment]
Reassigning to me to see if problem still exists. If it does, include console message text and send back to @peller.

**Comment by JonFerraiolo** [comment]
Closing. Not happening in latest build. I suspect this was fixed when we got Eclipse projects working properly with Orion 2.0.
