### ISSUE TITLE
Accented characters in files/folders handled incorrectly (only WAR?)

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3726]
Steps:
1. Open dialog to create a new desktop or mobile app.
2. Set file name to "éclair.html".
3. Click on twisty to show files view and click on **New Folder**.  Set name to "ümlaut".  Click **Create** button.
4. Add some widgets to page, save, preview, close & reopen.  Should all work as expected.
5. Refresh Maqetta page and try to reopen new file

The new folder now displays as "Ã¼mlaut" and shows up as empty;  the new file is not visible and cannot be opened.

I was able to make this fail when running from WAR but not standalone.  Not sure what the difference is.

**Comment by peller** [comment]
It looks like it's getting saved to disk with the messed up encoding, is that right?  The folder name is sent url-encoded in the GET request, so I'm not sure if the mime-type headers come into play.  encodeURI should always use UTF-8.  Perhaps the servletbridge is doing something to the encoding of the url?  We should check the url as it is received by the servlet.

**Comment by peller** [comment]
Amazingly, Tomcat [seems to decode URL parameters](http://wiki.apache.org/tomcat/FAQ/CharacterEncoding#Q2) using ISO-8859-1 by default, while the browser standard is to use UTF-8.  It seems the answer is to configure the [URIEncoding](http://tomcat.apache.org/tomcat-6.0-doc/config/http.html#Common_Attributes) property on Connector in Tomcat's `conf/server.xml` file

**Comment by peller** [comment]
One [other possibility](http://stackoverflow.com/questions/3029401/java-servlet-and-utf-8-problem#3029405) is to grab the query string directly and manually parse it using UTF-8, but this seems like something that ought to work as configured by the web server (see above)

**Comment by peller** [comment]
@jhpedemonte @JonFerraiolo Where is a good place to document this?  Should we have a README for the war file?

**Comment by peller** [comment]
Added a step to the [install instructions](https://github.com/maqetta/maqetta/wiki/Server-Installation-and-Setup) on the wiki.

-> M9
