### ISSUE TITLE
Tree folder sprite icons appear to be off by a pixel

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3728]
![Screen Shot 2013-02-03 at 4 44 13 PM](https://f.cloud.github.com/assets/46139/122333/e10993da-6e4a-11e2-8221-a9eb23dd1371.png)

**Comment by JonFerraiolo** [comment]
Which browser and which server are you running off of? I don't see it running the WAR version on Mac/FF.

**Comment by peller** [comment]
Mac/Chrome

**Comment by peller** [comment]
seeing similar behavior for the eyeball icon in the scenes palette

**Comment by JonFerraiolo** [comment]
I'm running the WAR version on maqetta-test using Mac/Chrome and I'm not seeing the shift. Below is a snapshot with a Tree widget on the canvas, and then a picture of the Scenes palette:

![Screen Shot 2013-02-04 at 10 54 07 AM](https://f.cloud.github.com/assets/706721/124749/61404c86-6efc-11e2-84aa-47bf1fdeb827.png)

The question is why you are seeing this. First question: are you running a release build or from Eclipse?

**Comment by JonFerraiolo** [comment]
Looking in debugger, here is what what I see when I look at one of the Tree icons in the Scenes palette:

```
.dijitIconFile, .dijitLeaf {
background-position: -352px;
}
.dijitIconSave, .dijitIconPrint, .dijitIconCut, .dijitIconCopy, .dijitIconClear, .dijitIconDelete, .dijitIconUndo, .dijitIconEdit, .dijitIconNewTask, .dijitIconEditTask, .dijitIconEditProperty, .dijitIconTask, .dijitIconFilter, .dijitIconConfigure, .dijitIconSearch, .dijitIconApplication, .dijitIconBookmark, .dijitIconChart, .dijitIconConnector, .dijitIconDatabase, .dijitIconDocuments, .dijitIconMail, .dijitLeaf, .dijitIconFile, .dijitIconFunction, .dijitIconKey, .dijitIconPackage, .dijitIconSample, .dijitIconTable, .dijitIconUsers, .dijitFolderClosed, .dijitIconFolderClosed, .dijitFolderOpened, .dijitIconFolderOpen, .dijitIconError {
background-image: url("../dijit/icons/images/commonIconsObjActEnabled.png");
width: 16px;
height: 16px;
}
```

If you are seeing this in Eclipse but not in a build, then my guess is that you have a different set of files in your Eclipse configuration than what we are using for our builds.

**Comment by peller** [comment]
I was running the war created by @jhpedemonte

**Comment by JonFerraiolo** [comment]
More questions:
- You running a war build locally or off of maqetta-test?
- Is your browser zoomed in or out? 
- If you clear you cache and restart the browser, do things get better?
- Could you get into debugger Elements view and click on one of the bad tree icons and see what the values are for background-image and background-position?

**Comment by peller** [comment]
ok, it looks like it happened because my browser zoom was not 100%.  Some sort of rounding error, perhaps?

**Comment by JonFerraiolo** [comment]
I am 99% certain this is either a dojo bug or a browser bug and not a Maqetta bug (except in that Maqetta uses Dojo and the browser).

**Comment by peller** [comment]
probably, though it does occur with at least one of our icons also.  Perhaps there's something about the sprite technique that makes it work for some and not others?  Ok with closing this or treating as extremely low priority

**Comment by JonFerraiolo** [comment]
Closing because it's not a common case and probably won't ever fix.
