### ISSUE TITLE
Investigate use of Web Workers

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#373]
There may be areas of the code that would improve through the use of Web
Workers, to offload work on to a separate thread.  In particular:
(1) intensive, non-UI calculations,
(2) I/O bound code (i.e. XHR - but this can be mitigated by using 'async' mode)

One issue is that IE and older browsers do not support Web Workers.  Here are
some pages that implement fallbacks for non-implementing browsers:

http://codecube.net/2009/07/cross-platform-javascript-webworker/
https://gist.github.com/462880
http://www.nonblocking.io/2009/03/offloading-arbitrary-js-objects-to.html

**Comment by peller** [comment]
closing this.  haven't encountered any situations where web workers would be needed.
