### ISSUE TITLE
Error opening multiple reviews

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3732]
review tab comes up blank, then clicking on add comment results in this exception:

```
CommentView.js:974TypeError: 'undefined' is not an object (evaluating 'this._cached[this._currentPage].focusedComments')
```

@jhpedemonte @JonFerraiolo

**Comment by peller** [comment]
@jhpedemonte sent me this review.  There were two files open, foobar.html and file1.html.  this._cached only seemed to have an entry for file1.html (the one that rendered)  The other tab, where I tried entering the comment, was blank

**Comment by jhpedemonte** [comment]
The review should only contain _foobar.html_.  Was _file1.html_ something that you had open?

**Comment by peller** [comment]
hrm, it probably was something from a previous review

**Comment by peller** [comment]
cannot reproduce this.  seems to have been something from an old workspace.
