### ISSUE TITLE
Convert docs to async AMD

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3738]
@JonFerraiolo 

Ought to be able to just remove the dojo.require statements for widgets and rely on the parser instead, then flip async on.

**Comment by JonFerraiolo** [comment]
Right. We need to do a full update to modern Dojo, including switching the xhr call to the newer API.

So why is this Prio-High?

**Comment by peller** [comment]
> So why is this Prio-High?

AMD has huge payback, and it will have huge impact on the page for relatively little effort.  Take a look at the network panel waterfall graph.  The newer APIs have relatively little impact..

**Comment by peller** [comment]
looks like the samples need to be converted also, perhaps update the states module references also

**Comment by peller** [comment]
see 24a54cc2ad8e6a9b9948f7baaad763ed39d27e14 and 0700ec9aef8b2e647960edfb84e3d81ed1192b51 on [doc-fixup branch](https://github.com/maqetta/maqetta/tree/doc-fixup)
