### ISSUE TITLE
SmartInput exception in EdgeToEdgeListInput.js after davinciRuntimeGlobal branch merge

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3742]
With latest code:
- New mobile app
- Add a View
- Add a RoundRectList, and add a 3rd line of text to SmartInput that appears

Result=> Undefined exception at EdgeToEdgeListInput.js:134

Works OK with the commit just before the davinciRuntimeGlobal branch merge (30030de94ca079f290f943333e168f83041625a9) but fails when checking out the davinciRuntimeGlobal commit (28763243f3466b859495e2e47889634a4a7b4488). I couldn't figure out after studying things for a bit why it's crashing due to davinciRuntimeGlobal, so assigning it to the expert.

**Comment by peller** [comment]
It looks like I missed a bunch of davinci.Runtime references in helpers, like MobileComboBoxInput.js:

```
    _getEditor: function() {
        return top.davinci && top.davinci.Runtime && top.davinci.Runtime.currentEditor;
    },
```
