### ISSUE TITLE
The included Dojo library has bugs

### ISSUE THREAD

**Issue by Tauvic** [maqetta/maqetta#3743]
I tried to use the dojo.request.script function for cross domain JSON requests but that failed due to a bug in the Dojo toolkit library. This bug has been fixed but the public Dojo build 1.8.3 does not include the fix. And that is the version currently available in Maqetta.

I understand you cannot constantly build new versions of Maqetta because the Dojo library has bugs. Is there a way that i can fix this myself? For example replacing or overriding Dojo libraries?

**Comment by jhpedemonte** [comment]
Dupe to #3744.
