### ISSUE TITLE
CSS Pseudo-Classes are moved incorrectly by Maqetta's system

### ISSUE THREAD

**Issue by angelfcm** [maqetta/maqetta#3745]
Hi

I have this html:
<code>

<div id="content">
    <a href="#" style="margin: 10px;">A link</a>
</div>

And CSS file:
# content a:hover {

//Any code
}

Then, if I use right panel of Maqetta to edit margin style and I change the value to any other value, the new CSS code in that file is:

a#content:hover {
//Any code
}

As you can see, the new CSS code is bad interpretation as I expected before.

Greetings

**Comment by angelfcm** [comment]
The HTML in above example is:

&lt;div id=&quot;content&quot;&gt;
    &lt;a href=&quot;#&quot; style=&quot;margin: 10px;&quot;&gt;A link&lt;/a&gt;
&lt;/div&gt;

**Comment by billreed63** [comment]
I am unable to reproduce this issue, could you please provide a more detailed set of instructions on how to reproduce this. along with the what browser and version and code examples.

**Comment by angelfcm** [comment]
Sorry, I have made a bad interpretation.

Maqetta's HTML snippet:
<code>&lt;div id=&quot;content&quot;&gt; 
    &lt;a href=&quot;#&quot;&gt;A link&lt;/a&gt; 
&lt;/div&gt;
</code>

CSS:
<code><b>#content a:hover</b> {
    color : green;
}
#content {
    margin : 5px;
}
</code>

Save both files and reload the page then select Design mode, select #content element and edit the margin by right panel of Maqetta, reload the page again and the new CSS is:

<code><b>a#content:hover </b>{
    color : green;
}
#content {
    margin : 5px;
}
</code>

Chrome 24.0.1312.57 m  and Firefox 18.0.2

THANK YOU! :+1:
