### ISSUE TITLE
Maqetta starts but unable to connect via the browser

### ISSUE THREAD

**Issue by akesterton** [maqetta/maqetta#3751]
Hi

I have installed release 9 on Windows7 Professional (64-bit).  I open a command shell as an administrator and start Maqetta.

However, when I try and access Maqetta via http://localhost:50000/maqetta - the browser (Chrome) times out with error

Error 324 (net::ERR_EMPTY_RESPONSE): The server closed the connection without sending any data.

Any idea where I am going wrong?

thanks, anthony

C:\IBM\maqetta-release-9\maqetta>maqetta.server.win.bat

Java version:
java version "1.6.0"
Java(TM) SE Runtime Environment (build pwa6460sr9ifix-20110211_02(SR9+IZ94423))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Windows 7 amd64-64 jvmwa6460sr9-20101
124_69295 (JIT enabled, AOT enabled)
J9VM - 20101124_069295
JIT  - r9_20101028_17488ifx2
GC   - 20101027_AA)
JCL  - 20110211_02

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
NOTE: CLOSING THIS WINDOW WILL
      STOP THE MAQETTA SERVER PROCESS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Using directory : C:\IBM\maqetta-release-9\maqetta\users
start your browser at http://localhost:50000/maqetta
15:15:19,028 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT
 find resource [logback.groovy]
15:15:19,028 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT
 find resource [logback-test.xml]
15:15:19,028 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found res
ource [logback.xml] at [bundleresource://2.fwk1986557544:1/logback.xml]
15:15:19,041 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@380c
380c - URL [bundleresource://2.fwk1986557544:1/logback.xml] is not of type file
15:15:19,054 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction -
 debug attribute not set
15:15:19,055 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About t
o instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:15:19,056 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming
appender as [STDOUT]
15:15:19,081 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This append
er no longer admits a layout as a sub-component, set an encoder instead.
15:15:19,081 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure c
ompatibility, wrapping your layout in LayoutWrappingEncoder.
15:15:19,081 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also ht
tp://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
15:15:19,081 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Settin
g level of logger [org.eclipse.orion.server.login] to INFO
15:15:19,081 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Settin
g level of logger [org.eclipse.orion.server.config] to INFO
15:15:19,081 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Se
tting level of ROOT logger to WARN
15:15:19,081 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Atta
ching appender named [STDOUT] to Logger[ROOT]
15:15:19,082 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@608e608e -
 Registering current configuration as safe fallback point

2013-02-19 15:15:19.089 [Start Level Event Dispatcher] INFO  org.eclipse.orion.s
erver.config - Server configuration file loaded from: C:\IBM\maqetta-release-9\m
aqetta\maqetta.conf
Registering Zazl JavaScript servlet
Registering Maqetta HTML Filter for Zazl
osgi>

**Comment by billreed63** [comment]
This might be your issue
https://groups.google.com/forum/?fromgroups=#!searchin/maqetta-users/billreed63/maqetta-users/WlK_cFLnb7I/ohMXSLFokaMJ

**Comment by akesterton** [comment]
Thanks for the suggestion Bill.  I have unzipped the files into my Document directory - and this does not appear to have made any difference.  Is there any logging I can turn on to debug the problem?

thanks

**Comment by billreed63** [comment]
No, you might ask on the users group other may have experienced  the same problem

**Comment by akesterton** [comment]
Thanks Bill - I will ask there.
