### ISSUE TITLE
Login page needs scroll bars

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3758]
The log in page needs scroll bars when registration button is off screen
If the user has a small browser window the registration button is off the bottom of the screen where the user can't see it. There are no scroll bars to let them know there is more here...

**Comment by billreed63** [comment]
When you connect to eclipse port 81 I get scroll bars but not when connecting to the build on port 50000
![without](https://f.cloud.github.com/assets/717822/186631/b9ecbeb0-7d33-11e2-8e52-03ca89644236.JPG)
![with](https://f.cloud.github.com/assets/717822/186632/cb4ebf50-7d33-11e2-9bed-c8ebf00191a9.JPG)

**Comment by JonFerraiolo** [comment]
Could it be that the reason you are seeing it in 8081 but not 50000 is that I fixed this in M10 (#3639)? Was the 50000 version the M9 release?

**Comment by billreed63** [comment]
The `overflow:auto;` is missing in the loginWindow.css on the 50000 but is present in the 8081 I searched the code and only found it missing in the ldap auth version of loginWindow.css  all other @JonFerraiolo  fixed 5 days ago. by commit 511fdd41d300387f92f5adcb09922bbaf4a563cc
