### ISSUE TITLE
Download selected files messes up path to dojo.js

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3760]
@jhpedemonte @billreed63 

I found this preparing for a customer demo. We should produce a fix for this ASAP in case we find we need to do a quick dot release. For serious customers, this will prove to be a commonly used feature.

If you download selected files using the Download context menu (and presumably also the second icon on the Files palette toolbar), the path to dojo.js in the downloaded HTML files is wrong. It says "dojo/dojo.js" instead of "lib/dojo/dojo/dojo.js". (NOTE: We don't have this problem for download entire workspace.)
- New HTML file
- Add a Button
- Save, close
- In Files palette, put mouse over the new file and choose the Download command. This will put a ZIP file in your browser downloads folder.
- Unzip the ZIP, and the download file should be there
- Open the downloaded file in a text editor. Notice that the path to dojo.js is "dojo/dojo.js" instead of "lib/dojo/dojo/dojo.js".
- Back in Maqetta, create a new project
- Upload the file you downloaded
- Open file in page editor - notice the Button looks fine. (Not sure why - probably because we toss out the reference to Dojo in the HTML file and substitute our own reference)
- Preview

Result => button displays incorrectly, console shows that dojo.js was not loaded correctly and "require()" is not defined

Note that doing a SaveAs of the new file will fix up the source code and the file will be fine thereafter. Therefore, we have three workarounds for users in the meantime:
1. Download entire project instead of selected files
2. Use an immediate SaveAs to fix up the HTML files that were downloaded then uploaded
3. Use Orion Navigator to hand-edit all of the HTML files that were downloaded then uploaded to fix up the reference to dojo.js

**Comment by peller** [comment]
hopefully fixed now
