### ISSUE TITLE
Firefox - click on review hyperlink when workspace has an HTML file open causes initialization logic to fail

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3763]
When running off of Maqetta.org using FF, if you have a html file open, close your browser window (with file still open), then click on a hyperlink to a review, there will be exceptions in the console, the software won't initialize properly, and the toolbar for the review is the page editor toolbar, not the review toolbar.

When I try in Chrome, I cannot reproduce the problem.

When I can reproduce, I see these errors in the Firefox console:

```
dojo.j...46b8114 (line 4745)`

TypeError: this._srcDocument is undefined
    return this._srcDocument.getDocumentElement();
    davinc...46b8114 (line 57346)
...
GET http://app.maqetta.org/maqetta/app/metadata/dojo...am.json?dafd47698ee1096a5ab74b667dbeffa8a46b8114 304 Not Modified        90ms    dojo.j...46b8114 (line 4745)

TypeError: cs is null
    ...89=cs.backgroundImage,hc=(cs.borderTopColor==cs.borderRightColor)||(_89&&(_89=="...
    dijit.js (line 414)

TypeError: this._srcDocument is undefined
    return this._srcDocument.getDocumentElement();
```

The first exception is in Context.js:getDocumentElement(). Looking at the call stack, we are calling updateToolbars(), but somehow the code is mixed up between the HTML editor and the review editor. davinci.Runtime.currentEditor points to a page editor, but when looking at the state of things in getDocumentElement(), the Context object has a declaredClass of "davinci.review.editor.Context".

**Comment by billreed63** [comment]
Look at maqetta.client.orion, pagedesigner.html and search for loadReviews. I suspect that the async call to Workbench.openEditor() is clashing with the openEditor() calls in Workbench.js:initializeWorkbenchState()
1:26:07 PM: Jon Ferraiolo: At this point, I'll leave it to you

**Comment by billreed63** [comment]
I can reproduce this locally, in IDE
Running on FF with firebug open and no breakpoint, this seems to slow FF down enough t expose the bug

The setup:
Create about 5 open html editors, save all htmls
Create a review with two of the html files that were created above
Copy the link from the review notice, you will need it later
Close FF
reopen FF and open firebug
Paste the review link in the address bar

The review loads then the other htmls load and then the review editor is replace with html editor on review file.

**Comment by billreed63** [comment]
By moving the opening of reviews to Workbench.initializeWorkbenchState we are able to remove the cap on opening review files. The initializeWorkbenchState  creates the EditContainers but the file contents are not loaded until the user selects the tab. So if we have 100 files in the review 100 tabs will be opened but only the contents of the first file in the review will be loaded at start up, the other 99 are loaded on demand.
