### ISSUE TITLE
Create review should open all N review files or no review files

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3767]
@jhpedemonte @peller @jinsil

@billreed63 - with a recent commit, you made it so that if someone clicks on the hyperlink of a multi-page review invitation, Maqetta opens up all of the HTML files when the application launches.

This leaves the application with an inconsistent UI -- even more inconsistent than before. 

Previously (e.g., M9):
- With single file, create review opened that review file. Hyperlink click on review URL also opened that review file.
- With multiple files, create review opened no files. Hyperlink click on review URL opened the first review file.

Current code:
- With single file, create review opened that review file. Hyperlink click on review URL also opened that review file.
- With multiple files, create review opened no files. Hyperlink click on review URL opens all review files.

We should make both operations behave similarly, or at least in a more reasonable manner. Since with recent changes we open all N files for a multi-page review when you click on the review URL, I suggest that upon clicking publish, we should one of the following: 
- Open all review files
- Open no review files

I think we could argue either way. My personal preference would be to never open any review files with Publish. I would expect users will get confused because there will be all of those open editors, probably some of them HTML editors and some of the review editors, with users having trouble distinguishing between *.html and the corresponding *.html.rev.

The logic for opening review editors in response to the Publish command is in davinci/review/widgets/PublishWizard.js, starting around line 711.

**Comment by peller** [comment]
Could impact #3765.  If we open no review files, we could immediately prime the zazl cache for all of them.  Conversely opening all the files immediately would lead to slow loading and a poor experience.

I'm with Jon.  I think it might be more natural not to open the files immediately and let the user take action to create the tabs as needed (conveniently works well with performance issue, above)  It might be nice if we could have some other user action to make sure the user is aware that there are multiple files, such as making sure the review panel is open (Jon mentioned that this runs counter to making screen real estate available)  Or perhaps using a toaster message to alert the user.

**Comment by billreed63** [comment]
When we open the review files at Workbench start up (the user clicks a review link from email) we uses: 

```
Workbench.openEditor({
    fileName: resource,
    noSelect: noSelect,
    isDirty: resource.isDirty(),
    startup: false,
    initializationTime: true
});
```

I think the ''''initializationTime: true'''' keeps the content from being loaded in the Editor until the tab is selected by the user @peller knows this code better than I. I think we could re-leave the performance penalty at publish time by using the  `initializationTime: true` on all the review files except for the first one in the review. This would open all review files in tabs and allow us to prime zazl in the background for the review files...

I just tested changing the PublishWizard code to:

```
                                    if (node) {
                                        node.getChildren(function(childs) {
/*                                          if(childs.length > 1) {
                                                return;
                                            }*/
                                            var index;
                                            dojo.forEach(childs, function(child, index){
                                                if (index == 0) {
                                                    Workbench.openEditor({
                                                        fileName: child,
                                                        content: node.getText()
                                                    });
                                                } else {
                                                    Workbench.openEditor({
                                                        fileName: child,
                                                        noSelect: true,
                                                        isDirty: child.isDirty(),
                                                        startup: false,
                                                        initializationTime: true
                                                    });
                                                }
/*                                              Workbench.openEditor({
                                                    fileName: child,
                                                    content: node.getText()
                                                });*/
                                            });
                                        }.bind(this));
```

Indeed it works, only the first file in the review is loaded, the others are loaded on demand when the user selects them.

**Comment by JonFerraiolo** [comment]
Right - OK to prime zazl, but @peller and @JonFerraiolo say we shouldn't open up the review HTML files at Publish time for usability reasons.
