### ISSUE TITLE
Update docs to reflect new behavior for opening review editors

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3768]
@billreed63 

Depends on #3767 

We have changed the behavior for clicking on review hyperlinks. We now open all files in the review. Need to update docs, and add a bullet to the release notes for M10.

**Comment by billreed63** [comment]
@JonFerraiolo I can put the cap back on the reviews if that is the behavior we want, I just took it of because the performance problem that was the reason for the cap no longer exists...

**Comment by JonFerraiolo** [comment]
I wouldn't put the cap back in. See my comments on #3767 with my analysis and recommendation.
