### ISSUE TITLE
Menubar broken when save and reopen

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3778]
Create a new desktop app, add a Menubar widget, save, close, reopen - you'll see some error text from the parser at the top of the canvas. I suspect it has to do with the switch from slashes to dots.

**Comment by peller** [comment]
really odd. I tried searching for the changeset that broke this (wondering if it was the slash-mid change) and it no longer breaks for me, even on master.

**Comment by peller** [comment]
dup of #3870
