### ISSUE TITLE
ReferenceError: CSSThemeProvider_replacePseudoClass is not defined

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3779]
I'm not sure what caused this to happen, but when running through the test matrix (VE1), I noticed that the Firebug console had this error:

ReferenceError: CSSThemeProvider_replacePseudoClass is not defined

I noticed that the toolbar had an error (showed Flow instead of Absolute), so I suspect the exception prevented the toolbar from completing its update.

I had two page editors open, so I wonder if perhaps the pseudo class code doesn't take into account multiple open files properly?

@billreed63 - could you please look at related code to see if you see anything suspicious?

**Comment by jhpedemonte** [comment]
Dupe to #3787, which has more info/work.
