### ISSUE TITLE
Split view selection not working in either direction with Orion 1.0 build

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3782]
@jhpedemonte 

(Using Mac/FF versus the Orion 1.0 build on maqetta-test)
- New desktop
- Add a DIV, then add a Button and TextBox
- Split view
- Try clicking on Button and TextBox on design canvas => no selection appears in source pane
- Try clicking on Button and TextBox in source pane => no selection appears in design pane

**Comment by peller** [comment]
confirmed that this is working fine on master with build.
