### ISSUE TITLE
Drag/drop in Outline palette, then mouseover Scenes palette - null exception in dojo/dnd/Manager.js

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3785]
@wkeese 

Logging on Maqetta issue tracker first, but I believe this is a dojo issue.

Since I added drag/drop to the Scenes palette, there are now two Tree widgets in Maqetta that have drag/drop enabled. When I do a drag/drop operation in one of the Tree widgets (Outline palette) and then move the mouse over a tree node in the other Tree widget (Scenes palette), I get an exception in dojo/dnd/Manager.js:94 with the call to `this.avatar.update();` because `this.avatar` is null or undefined.

I believe the underlying cause is that dnd uses publish/subscribe, which makes it so that widgets that have DND enabled will get events from any other widget. Because of this, some bulletproofing is necessary, such as verifying in various places that this.avatar isn't null and that `source == this` and that sort of thing.

What I believe is happening in the Maqetta case is that there is a mouseover event before the drag/drop operation has happened (because mousedown hasn't happened yet) and therefore there is no avatar yet. (Not sure about that - I don't know the dnd code)

I believe that Dojo needs to add an `if` check to `canDrop` to make sure that `this.avatar` isn't null or undefined before calling `this.avatar.update()`.

@peller: could you please take a look at this and work with the Dojo team on this as appropriate to determine if we are doing something wrong on the Maqetta side, or whether Dojo does need the extra bulletproofing I suggest.

**Comment by peller** [comment]
@JonFerraiolo From what I can tell, in `StatesView.js` you're overriding `onDndDrop: dndDone` so it calls your local handler function instead of the onDndDrop function in dndSource.js.  The latter sets up the appropriate state for DnD, such as setting isDragging to false when a DnD operation completes over another tree.  As it is now, isDragging stays true even after the operation is over, so as soon as you mouse over the StatesView, it looks for an avatar and an exception occurs.

Perhaps you want to connect to the dndSource method rather than bypass it?

**Comment by peller** [comment]
-> @JonFerraiolo

**Comment by JonFerraiolo** [comment]
I hacked on my own local copy of dojo and put a bunch of console.log() statements into various dojo dnd routines, including some files in dojo/dnd/\* and dijit/tree/*, and I'm absolutely convinced there is a dojo bug when you have two tree widgets on a page and enable dnd on both of the trees. I attached different random numbers to various dnd objects so I could see which objects were getting invoked in which circumstances.

What I'm seeing is that when a drag operation starts on a tree, `dojo/dnd/Manager.js:startDrag()` is called. In turn, it issues this call:

```
        topic.publish("/dnd/start", source, nodes, this.copy);
```

If you have two trees with dnd enabled, then each of the dndSource objects corresponding to the two trees will have `/dnd/start` subscribers (via function `onDndStart()`, and as a result, both dndSource objects will be flagged as being in the midst of a dragging operation (because `onDndStart()` sets `this.isDragging = true;`). But only one of the dndSource objects is actually involved in the dragging operation.

When you finally drop, for some reason (that I haven't figured out yet), the `/dnd/drop` event only goes to the tree where the dragging is actually occurring. As a result, the second tree (where no dragging has occurred), still has `this.isDragging = true;` Then when you mouseover that second tree, kaboom (as described above) with an exception because this.avatar is null.

I got the exception to go away by hacking my own copy of dojo where I added a check to make sure that `source` was the same as `this` at the top of `onDragStart()` in dndSource:

```
    onDndStart: function(source, nodes, copy){
        if(source != this){
            return;
        }
```

However, I'm not sure if this is a good fix or not. It would seem better if Manager.js would only invoke the onDragStart routine for the dndSource to which the drag operation applies, versus having each of the clients verify that they are the correct client for the operation.

@wkeese

**Comment by JonFerraiolo** [comment]
Wait a minute - I looked at something else and maybe there is indeed something wrong on the Maqetta side. Nevermind for now.

**Comment by wkeese** [comment]
> both dndSource objects will be flagged as being in the midst of a dragging operation (because onDndStart() sets this.isDragging = true;). But only one of the dndSource objects is actually involved in the dragging operation.

FYI, both dndSource objects are involved in the DnD because you are dragging from one dndSource and _might_ drop onto the other  dndSource.   No way to predict where the user is going to drop the object.   So, isDragging simply means that "the user is dragging something".

As Adam wrote a month ago the problem was with you overriding onDndDrop, preventing one of the trees from getting the notification.   Perhaps that's still the issue?
