### ISSUE TITLE
As admin, can't create user, activate user, and then log in with Orion 1.0 build

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3786]
I was running through the Orion test plan with the latest Orion 1.0 build. and couldn't finish, and I'm not sure how much was user error, how much is just the say things work, and how much is incomplete implementation towards moving onto Orion 1.0.

 I could create a new user, but I couldn't use an email address as the user name on the admin page. I entered jon@jon.com for the email and jonjon as the user name, and then tried to see how far I could go. Is it possible to create a user on the admin panel using the same tricks we use on our login screens?

Then I tried to log in and it said email hasn't been activated yet. Where is the admin feature to activate a user?

**Comment by jhpedemonte** [comment]
Ok, I was able to get this to work with the updated test case instructions.  Closing.
