### ISSUE TITLE
(Orion 1.0) Review invitation emails have messed up formatting

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3793]
This is what review invitations look like in email readers. I think that the message is getting sent as plain text even though HTML is used:

``` html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head></head><body><div>jferrai@us.ibm.com has invited you to review the page.</div><div>Description: 20130304d 20130304d</div><br /><div>Click on the Review Link below to enter Maqetta's review and commenting module. If you haven't registered yet with Maqetta and/or are not currently logged into Maqetta, you may need to go through a registration and/or sign-in process before you can start reviewing. If so, you may need to click on the Review Link below once to go to the login and/or registration pages, and then once logged in, you may need to click on the Review Link again.</div><br /><div>Review Link: <a href="http://maqetta-app-test.austin.ibm.com/maqetta?reviewDesigner=B&reviewVersion=20130304T210150Z">http://maqetta-app-test.austin.ibm.com/maqetta?reviewDesigner=B&reviewVersion=20130304T210150Z
```

(NOTE: most email clients will wrap the above text, but the markup will show in the email client)

---

**Tasks:**
- [x] Fix formatting.
- [x] Edit content for better legibility.
- [x] Fix _add comment_ email content to not have HTML elements (text only).

**Comment by peller** [comment]
also noticed that ISO-8859-1 encoding is used, probably on all pages by default.  Won't play well with Unicode usernames and filenames, once that's available in the template.

**Comment by jhpedemonte** [comment]
So the Orion mail code just sends text emails.  I believe there's no easy way to do HTML emails.

However, from the looks of it, there really isn't a reason to use HTML anyway.

**Comment by JonFerraiolo** [comment]
Also, review notification emails (not just invitations)

**Comment by jhpedemonte** [comment]
I changed the email content for _publish_ and _add comment_ thusly:
- converted from HTML to plain text (Orion email APIs only do text)
- rearranged and edited the content to be more legible.

The invitation email looks like this:

![Screen Shot 2013-04-03 at 7 09 14 PM](https://f.cloud.github.com/assets/711365/337035/a0652060-9cbc-11e2-8f13-7d2b068f6051.png)

And the comment email looks like this:

![Screen Shot 2013-04-03 at 7 09 26 PM](https://f.cloud.github.com/assets/711365/337039/aee75202-9cbc-11e2-9adf-a1e2d3331a37.png)

As you can see in the comment email, there's still the issue that the comment text comes back with HTML code.
