### ISSUE TITLE
Background color can be set on dijit Button when claro is active theme

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3794]
- New desktop app
- Add a Button (using claro theme)
- Try to set background color to any value (red, yellow, #888, whatever)

Result=> color swatch on palette changes to show that color, source view shows element.style having `color:whatever` but the widget still has the blue background from claro.

Instead, an error dialog is supposed to appear that says you cannot modify a read-only theme.

**Comment by billreed63** [comment]
With the latest code from git I am seeing the error message, do you still see this error?

**Comment by JonFerraiolo** [comment]
Closing. With latest build on maqetta-test, I do indeed see the error dialog.
