### ISSUE TITLE
app.css background changes on Button not showing immediately in page editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3795]
- New page
- Add a Button
- Add a class to the button (e.g., class1)
- In properties palette, go to background-color property and bring up cascade
- Select "new style rule in app.css"
- Type "yellow" as value for background-color property

Result=> color swatch shows yellow but Button stays blue.
- Preview

Result=> Button has yellow background
- Save, close reopen

Result=> Button has yellow background

**Comment by billreed63** [comment]
I am unable to reproduce this with the latest code from git, do you still see this issue? If so what browsers?

**Comment by JonFerraiolo** [comment]
Closing. I re-tested on maqetta-test and I don't see this problem with latest build.
