### ISSUE TITLE
Auto-save with each change in visual page editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#380]
@childsb, @jhpedemonte, @peller

As I remember, the page editor auto-saves every N seconds. We should instead
auto-save with each change, or at least schedule the auto-update to happen a
short-time into the future (e.g., to minimize autosave with rapid-fire changes
such as clicking the "+" icon on Properties palette of typing text into source
view). The basic goal here is to minimize the chance that a user might lose the
most recent N seconds of changes that he made if he navigates away from daVinci
or issues a Ctrl-R (refresh).

**Comment by JonFerraiolo** [comment]
@waynevicknair, @childsb: this was the issue I mentioned on today's call. Last I looked, we have heartbeat logic to update server every N seconds. I think we should update server with each change instead. We'll need this if we get into true collaborative authoring where multiple people are working on same doc at once. Also, we really need to update review/commenting so that if person A adds a comment, the server sends a notification to person B's sessions so person B sees real-time updates from other reviewers.

**Comment by peller** [comment]
we probably want both, right?  Can we just keep the heartbeat and check a dirty bit before writing?

**Comment by jhpedemonte** [comment]
Isn't that a bit excessive?  Having a timer go off every N seconds all the time?  Even if the user isn't doing anything that requires saving.

Why not create a timer for X ms, whenever a change is made.  If a timer already exists, don't create.  Timer goes off, sends save to server and is destroyed.  Afterwards, another change recreates the timer.  Of course, downside of this approach is creation/destruction of timers; not sure what the overhead is on that.  But might be worth it to remove the "heartbeat" timer.

**Comment by peller** [comment]
The cost of a timer firing and running a no-op certainly isn't that high, and performance when there's no user interaction isn't a priority anyway.  It's not immediately obvious to me that it's worth avoiding a single, long-lived timer.  It's certainly simpler to code.

**Comment by JonFerraiolo** [comment]
Closing. We do this today.
