### ISSUE TITLE
Exception if attempt to change background color for subwidget in hover state

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3806]
(Seeing this in M9, too)
- Clone claro
- Select Calendar
- Choose Selected date
- In States palette, change to Hover state
- Try to pick a different background color

Result=> `TypeError: this._values[this._targetValueIndex] is undefined`

**Comment by billreed63** [comment]
no cascade rules this should only happen when we are in theme editor and the  user has selected a widget or subwidget and then a state not supported by the widget  then changes a property that  the true fix to this will be when #226 is implemented  until then we will check for cascade rules to prevent exception.
