### ISSUE TITLE
HTML widget helpers don't load on page load

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3812]
I believe I discovered a problem where Maqetta isn't loading the helpers for HTML widgets on page load, and helpers are only loaded when HTML widgets are added via the CreateTool. I think it's because the helper loading logic only happens on page load in response to `data-dojo-type` attributes, and HTML widgets don't have those attributes.

**Comment by jhpedemonte** [comment]
cc @peller
