### ISSUE TITLE
bracket pair highlighting would be a great feature

### ISSUE THREAD

**Issue by lpmontx** [maqetta/maqetta#3824]
Some editors highlight the corresponding grouping character like  (  {  [    when one is selected.  This is a great tool and time saver when trying to find an unmatched grouping character.

**Comment by JonFerraiolo** [comment]
-> @peller 
Does Orion support this (or will an upcoming release support this)? After answering that question, next question is whether we can (or should) enable it in the source pane within visual editor, or only enable it for using Orion's own UI (via Open->Orion Navigator)

**Comment by peller** [comment]
Orion does support this.  Need to find out why it's not active in our editor.
