### ISSUE TITLE
Update M10 docs

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3826]
@peller @billreed63 @jhpedemonte 

Usual task with each release where we need to update the docs.

Could people please either directly update the release notes in the docs/ folder (Release10.html) or at a minimum add notes to this issue about items that need to be included in the release notes? Here are some things that come to mind that we probably should mention in release notes:
- Update to Orion
- New features in source editing mode
- New clipart icons
- Project templates feature
- UI changes to Files palette toolbar
- Upload as ZIP

**Comment by jhpedemonte** [comment]
> Update to Orion

The big change here is that we've updated **maqetta.conf**.  Mainly added properties, but also some have changed (i.e. mail).

**Comment by peller** [comment]
@JonFerraiolo beat me to it 5cca8bfe03cdf2959a463d2bd9f012210b0d6e1c

**Comment by peller** [comment]
I'll add a few notes about the source editor.   Only features I'm aware of so far are little things like bracket matching and folding ruler for JS comments
