### ISSUE TITLE
Review session with SampleMobile - Scenes palette not working correctly

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3834]
- Open Sample3-Mobile.html
- Save in root of project
- Create a review with that file
- Open the corresponding *.rev file 

=> Notice that the current view isn't selected in Scenes palette
- Click on the first ListItem. The canvas will animate to second view.

=> Notice that nothing happens in Scenes palette
- Click on the scenes in Scenes palette.

=> Notice that nothing changes on the canvas

**Comment by JonFerraiolo** [comment]
@peller any ideas on this one?

**Comment by peller** [comment]
So the problem is that scenes associated with views do not work in review, right?  Is this a regression?  I confirmed that it also fails in M9.  At first, I thought perhaps it was related to some AMD changes to the states code, but I think we can rule that out if it worked in M9

**Comment by JonFerraiolo** [comment]
I checked M9 on maqetta.org. What I see is that if I create the content from scratch, the review features are working correctly. 

However, when I try to recreate the content from scratch with M10, and create a review with the newly created mobile app, when I try to open the *.rev file, the canvas shows this:
![Screen Shot 2013-03-31 at 2 48 15 PM](https://f.cloud.github.com/assets/706721/322437/c820b01e-9a4c-11e2-8a8a-b924c077c12c.png)

Regarding Sample3-Mobile.html, I believe things are messed up in both M9 and M10. If I try to create a review with Sample3-Mobile.html, the review file comes up blank. In fact, if I try to save Sample3-Mobile.html under a different name, I get a blank document. I'm not sure what exactly is broken, but clearly whatever it is we need to fix it for M10.

**Comment by peller** [comment]
@JonFerraiolo what steps are necessary to get to the error you show above?  If I create a mobile app from scratch in M10 with two views and some buttons, it seems to open fine in preview (though still no state updates)  What was the url for the 404?  Was this in an Eclipse project, perhaps?  Sounds like a separate issue?

**Comment by peller** [comment]
could have been this fe38c0ce0603643d85adbc38cc61e4e55fbddcc5
