### ISSUE TITLE
Review tooltips sometimes don't go away

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3836]
This has been a problem forever. If you hover over a review to bring up the review tooltip, and then click some something to cause the palettes to move around, the tooltip will never go away (until a browser refresh)

**Comment by jhpedemonte** [comment]
@peller, any Dojo magic we should be aware of for this?

**Comment by peller** [comment]
If they're standard Tooltips, setting focus somewhere else in the document ought to trigger the action to teardown the tooltip.  Perhaps there's some iframe confusion going on?

**Comment by JonFerraiolo** [comment]
Not standard tooltips - the review palette is showing and hiding the tooltip itself, and controlling timers itself. It uses mouseover to trigger a 1sec timer to show the Tooltip, and then uses mouseleave to trigger a 1 sec timer to hide the Tooltip. I suspect the problem is that mouse events only get triggered when the mouse moves, and sometimes Maqetta changes the position of things underneath.

What I propose doing is having things work such that the tooltip will come down whichever comes first: (1) mouseleave event or (2) 10 seconds have elapsed. Therefore, the tooltips may hang around for 10 seconds, and that will be annoying, but at least users won't have to do a browser refresh to fix the problem.

**Comment by JonFerraiolo** [comment]
Actually, let's talk about the review tooltips with our UI team. I'm not sure that the tooltips provide much value. It might be better to have a small "i" info icon that the user has to press to see info about the review, and then put a close box on the popup that appears.
