### ISSUE TITLE
Update Mac local install instructions to deal with stricter privacy settings

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3843]
@jhpedemonte 

If a Mac user has his security settings to say "only allow apps from app store and identified developers", then Maqetta local install launch script won't run, due to being suspected malware.

See this page: http://support.apple.com/kb/ht5290

**Comment by jhpedemonte** [comment]
Hmm, right.  So a user would have to right click on the **.command** file and select **Open**, rather than simply double-clicking.  The workaround is to sign the app (& .command file?), but I think workaround instructions are fine for now.
