### ISSUE TITLE
Left and top properties don't appear in Properties palette for absolutely positioned dijit.form.Button

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3844]
Weird one.
- New sketch
- Drag/drop a dijit.form.Button
- Look at Layout section of properties palette

Result=> No values for left and top. However, if you drag/drop a ComboButton or almost any other widget, you will see values for left and top

**Comment by billreed63** [comment]
The theme meta data can contain a `element.$root` property that is used by the palette and cascade to determine where a property is to be applied to a widget

```
 "Button": {
            "displayName": "Button",
            "states": {
                "Normal": {
                    "elements":{ 
                        "$root": [ 
                            "font-size",
                            "font-weight",
                            "position", 
                            "opacity",
                            "float",
                            "z-index",
                            "left",
                            "top",
                            "right",
                            "bottom"
                        ]
                    },
```

The button was missing `left, top, right, bottom` 
When this feature was added it was never documented as to how it was intended to work and the meta data has never been updated completely.  We have been fixing it as issues arise.

It would seem to me that some style properties should always be applied to the `element.$root`

**Comment by JonFerraiolo** [comment]
> It would seem to me that some style properties should always be applied to the element.$root

Yes. Some that come to mind are position, opacity, float, z-index, left, top, right, bottom.
