### ISSUE TITLE
Replace Orion's email templates for registration, password reset, etc.

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3846]
We are now using Orion's email APIs. Unfortunately, the Orion code uses its own mail templates and they cannot currently be (easily) overridden.  See Orion bug [403261](https://bugs.eclipse.org/bugs/show_bug.cgi?id=403261).

Until that bug is fixed, we have several options:
1. As part of the build step, overwrite the Orion mail templates with our own.
2. Use Java reflection to change the visibility of the private members in `UserEmailUtil.java`, which store the mail templates.  Then, set them to our own.
3. Use AspectJ to dynamically intercept the API calls in `UserEmailUtil.java` and use our mail templates instead.

---

**Tasks:**
- [x] Override Orion templates.
- [x] Cleanup/additions to template text.

**Comment by jhpedemonte** [comment]
References:
- [Using AspectJ for Accessing Private Members without Reflection](https://blogs.vmware.com/vfabric/2012/04/using-aspectj-for-accessing-private-members-without-reflection.html)
- [Equinox Weaving](wiki.eclipse.org/Equinox_Weaving_QuickStart) - Using AspectJ with Equinox/OSGi bundles.
- [AspectJ & PDE Build](http://contraptionsforprogramming.blogspot.com/2010/03/ajdt-pde-builds-redux.html)

**Comment by jhpedemonte** [comment]
Above commit adds our own email templates (located at `maqetta.server.orion/emails`).  I made minimal changes from the Orion templates, mainly specifying "Maqetta/Orion" instead of simply "Orion".

Todo:
1. Is "Maqetta/Orion" fine?  Or should we just use "Maqetta"?
2. Any other cleanup/additions to these templates?

Regarding (2), I think it would be good to add some text explaining to the user how they can change the generated password they receive when doing a reset (i.e. load Orion, go to profile page, edit password).

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
> 1.    Is "Maqetta/Orion" fine? Or should we just use "Maqetta"?

We should just say "Maqetta"
