### ISSUE TITLE
Allow CSS model code to work on string instead of file

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#386]
@jhpedemonte, @childsb

At some point the CSS model code should
be refactored to work on a single style rule passed in as a string versus
requiring a complete style sheet file. This is so it is possible to run the
parser and modeler against an inline style string.

**Comment by childsb** [comment]
Support for this is really there, we just call our top level CSS Model Object "CSSFile".  But there are a few spots in code where we instantiate a new CSSFile, set text to a snipit, then run queries.

To simplify this (and provide better design), i added a CSSFragment class that simply extends CSSFile.  Currently theres no functional difference, but it will read better in code if we wish to use just a sniippit.

**Comment by JonFerraiolo** [comment]
Thanks for taking care of this. One main use case is inline STYLE element, which is a different bug: #156
