### ISSUE TITLE
Paste source code produces blank page

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3861]
- Open Sample1.html
- Save-as into the root folder (e.g., as a1.html)
- Go to source view, select all, and "copy"
- Close a1.html
- Create new desktop app
- Go to source view
- Select all, then "paste"
- Go to design view

Result=> blank page
- Save, close, reopen

Result=> page is still blank (and source view shows a default page)

I haven't debugged to see where things aren't working. I can successfully make incremental source edits, but for some reason replacing the entire source contents isn't working now.

**Comment by peller** [comment]
yet if you paste a second time, it seems to work...  no obvious exceptions

**Comment by peller** [comment]
Seems to be an issue with the _dontNotifyChange flag, established in this commit fb8fbe047bf684400829a5bcb941a415a704c2f1
