### ISSUE TITLE
Can't enter a value for DateTextBox

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3867]
I added a DateTextBox and in "Widget" part of properties palette tried to enter various date values such as "2013/04/02". The value went into the source code, but no value appears inside the widget itself on the canvas, the widget palette shows a blank value for the "value" property, and with preview, nothing appears inside the widget at preview time.

**Comment by peller** [comment]
The widget only accepts values in ISO format (yyyy-mm-dd)  At one time, we had a DateTextBox in the properties palette instead of a plain text field, though we then have the problem of how to handle an empty value.

**Comment by peller** [comment]
see #65, #659

**Comment by billreed63** [comment]
see #3868

**Comment by JonFerraiolo** [comment]
Seems to a user that the widget is inconsistently designed. The value must be of the format yyyy-mm-dd, whereas the value that displayed inside the widget itself has the format yyyy/mm/dd, and then in the Widget area of the properties palette, we how something like Fri Jan 04 2013 00:00:00 GMT-0800 (PST).

Would be good if the same format were used in all 3 cases. We might be able to improve things via helper functions on the value property for DateTextBox, but I took a quick look at our list of helpers and I'm not sure whether we have sufficient helpers already. Maybe `helper.preProcessData` could convert yyyy/mm/dd into yyyy-mm-dd before invoking the widget constructor, and maybe `helper.getPropertyValue` could convert the current value into yyyy/mm/dd, but that's just a theory.

**Comment by peller** [comment]
The fact that we see "Fri Jan 04 2013 00:00:00 GMT..." is because the existing property editor just does a toString() on the Date object.  We shouldn't be dealing in yyyy/mm/dd at all, ever.  The widget property is a Date object.  When the property is a Date object, we should either convert to/from ISO format or present a DateTextBox in the properties panel instead of a TextBox.  This is basically a dup of #659
