### ISSUE TITLE
gridx data from url keepings spinning when reopen file in page editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3876]
Saw this on maqetta-test with Win/FF and running in Eclipse using Mac/Chrome.
- New desktop app
- Add a gridx. Choose data from URL, and enter this URL: http://maqettaservice.appspot.com/sampleservice
- Save, close, reopen

RESULT=> gridx just says "Loading..." - data never appears

Works in preview, however.

**Comment by jhpedemonte** [comment]
Hmm, I ran into this as well while running the tests. But only once -- afterwards, I couldn't reproduce. (On FF/Mac)

**Comment by billreed63** [comment]
When Gridx or and data store based widget is using JSONP we add 

```
<script type="text/javascript">
require(["dojox/io/xhrScriptPlugin"],function(xhrScriptPlugin){
    xhrScriptPlugin("http://localhost:8888/sampleservice","callback");
});
</script>
```

Win the page is loaded the requires are run, when `xhrScriptPlugin("http://localhost:8888/sampleservice","callback");` is executed the xhrScriptPlugin code adds the following iframe and scripts to the body of document 

![image](https://f.cloud.github.com/assets/717822/362324/019ba98e-a1e6-11e2-8bee-542205e5e956.png)

After all requires have loaded we then process the widgets on the page, as part of this processing we remove the script and onload attributes to prevent page scripts from running.  So after processing the iframe that was add by xhrScriptPlugin looks like:

![image](https://f.cloud.github.com/assets/717822/362348/9a5c5ce0-a1e6-11e2-8e61-2cb0768a0858.png)
Becouse the onclick and script have been removed the cross domain call to the JSONP service never happens. leaving the loading message in the gridx

To further complicate the issue, the addition of the iframe for cross domain must be added to the document before the gridx widget is constructed by dojo.

**Comment by JonFerraiolo** [comment]
I've always figured that we would need to make our rules about filtering out SCRIPT and on\* attributes (e.g., onload) would need some extensions to deal with special cases, where particular widgets could override the default filtering rule (which is remove all SCRIPT and all on\* attributes).

In this case, though, I'm not sure exactly how to add such a hook given that we are trying to use a particular technology (xhrScriptPlugin). One possibility is that we could create a callbacks.js for gridx that gets activated with onDocInit() and registers a new callback function (implemented in callbacks.js) which the page editor calls before eliminating on event attribute (e.g., onload) and tells the page editor whether to leave that attribute or not based on its return value.

**Comment by billreed63** [comment]
A more generic fix is to use the toolkit callback approach like dojo 1.8:
package.json

```
{
  "name": "dojo",
  "description": "Dojo core is a powerful, lightweight library that makes common tasks quicker and easier. Animate elements, manipulate the DOM, and query with easy CSS syntax, all without sacrificing performance.",
  "version": "1.8",
  "keywords": ["JavaScript", "Dojo", "Toolkit"],
  "bugs": "http://bugs.dojotoolkit.org/",
  "licenses": [
     {
         "type": "AFLv2.1",
         "url": "http://trac.dojotoolkit.org/browser/dojo/trunk/LICENSE#L43"
     },
     {
         "type": "BSD",
         "url": "http://trac.dojotoolkit.org/browser/dojo/trunk/LICENSE#L13"
     }
  ],
  "directories": {
    "lib": "../dojo"
  },
  "homepage": "http://dojotoolkit.org/",
  "overlays": {
    "oam": {
      "directories": {
        "metadata": "."
      }
    },
    "maqetta": {
      "scripts": {
        "widget_metadata": "./widgets.json",
        "callbacks": "maq-metadata-dojo/callbacks"
      }
    }
  }
}
```
