### ISSUE TITLE
"Loading" indicator stays for way too long when opening empty file

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3886]
While testing on Firefox and maqetta-test today, I created a new blank page (first time this session) and was greeted with a **Loading** indicator for close to 10 seconds.  Not sure what's going on, but an empty file should load immediately.

**Comment by peller** [comment]
It was pretty snappy when I tried it. It would be good to know if there was anything suspicious on the console or in the network panel.  Were there any other open windows?

**Comment by jhpedemonte** [comment]
![2013-04-09 10 38 59 am](https://f.cloud.github.com/assets/711365/357668/e2e61fde-a12b-11e2-9c32-c08b6fdd24ad.png)

The bottom says ~16s, but I counted about 12s or so that the **Loading** indicator was up (some reqs came in before/after the indicator).

As you can see, the biggest delay is in the middle, where it calls `findResource` and `listFiles` on the theme files.  I assume all of those are still synchronous and that's why they don't show up running parallel.

I thought we fixed something related to this, to cut down on the requests to get the theme files.  @billreed63 ?

**Comment by jhpedemonte** [comment]
I updated the [above comment](https://github.com/maqetta/maqetta/issues/3886#issuecomment-16109676) with a better image, showing more of the URLs involved.

To recreate in FF:
1. Clear cache.
2. Reload Maqetta.
3. Select _Create a New Desktop Application_, but don't yet click on **Create**.
4. Clear the Net Panel in Firebug.
5. Click on **Create**.

**Comment by peller** [comment]
@billreed63 referred me to #886 and this checkin 1a8614f2b5580908c0578d5dab0be4ca81110b7c, which should have reduced the number of theme requests.  What we're seeing might be a regression.  The iterating over *.theme files seems to be originating from Theme.getDojoxMobileThemeMap:

```
Resource.findResource (resource.js:259)
(anonymous function)(theme.getFile) (library.js:128)
Theme.getDojoxMobileThemeMap (Theme.js:265)
declare._dojoxMobileAddTheme (ChangeThemeCommand.js:255)
declare._setSourcePostLoadRequires (Context.js:856)
(anonymous function) (Context.js:841)
signalListener (Deferred.js:37)
then.promise.then (Deferred.js:258)
declare._setSource (Context.js:838)
declare._setContentRaw (VisualEditor.js:310)
declare._setContent (VisualEditor.js:271)
declare.setContent (VisualEditor.js:263)
declare.setContent (PageEditor.js:433)
(anonymous function) (EditorContainer.js:82)
(anonymous function) (EditorContainer.js:111)
```

**Comment by peller** [comment]
of particular interest is this line from Theme.js: 265

```
var ssPath = new Path(theme.getFile().parent.getPath()).append(theme.files[0]);
```

which was probably a no-op before, since these dirs were already cached.  But now it's initiating a findResource call in order to calculate some paths.  Hopefully we can avoid fetching the theme and metadata file for other themes.

**Comment by peller** [comment]
-> @billreed63 

It should be possible to replace the line above with logic that gets theme.path and parses out the parent path
