### ISSUE TITLE
createResource ignores existing files

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3889]
In davinci/model/resource/Folder.js:

```
            /* resource already exists on server, so just be gracefull about it. */
```

Graceful here sounds like a bug.

@jhpedemonte @JonFerraiolo

**Comment by jhpedemonte** [comment]
I would imagine that if the client makes a call to create a resource that already exists, that is a bug in our code.  Not sure how we want to handle that on the client side ("Error creating file.  Please open a bug [<- that's a link] with the contents of the console" or something; but asking our users to go to the console isn't ideal).

**Comment by peller** [comment]
It's unlikely, but there's no guarantee that our client-side cache is current.  But ignoring the error seems wrong also.

We ought to have error toasters or something, but that's a different issue.

**Comment by peller** [comment]
dup of #2840
