### ISSUE TITLE
Review alert if email is not working comes up somewhat garbled

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3891]
The dialog that appears if you create a review and email is not working comes up somewhat garbled:

![Screen Shot 2013-04-09 at 10 31 37 AM](https://f.cloud.github.com/assets/706721/358287/59f476dc-a13d-11e2-8c54-8d8ffbcf93ee.png)

**Comment by jhpedemonte** [comment]
Ah, that would be because I converted the email template from HTML to plain text (to accommodate Orion APIs).  Seems that this dialog expects HTML.
