### ISSUE TITLE
run the source code but cannot regist

### ISSUE THREAD

**Issue by licai** [maqetta/maqetta#3892]
Hey guys,
i've setup the source code in windows and run it. but i cannot regist it succeed. i trace the code and find the regist and login is handle in LoginFixUpFilter, int the handleRegistration(), the user in follow line is null, 

User user = userAdmin.getUser(UserConstants.KEY_EMAIL, email);

this cause the user in handleLogin() is null also

User user = userAdmin.getUser(UserConstants.KEY_EMAIL, email);

how to fix this?

when i setup the source code, the eclipse notice that cannot find the bandle of follow:
org.eclipse.orion.server.configurator(1.0);
org.eclipse.orion.server.useradmin(1.0);

and i change it to:
org.eclipse.orion.server.configurator(0.5);
org.eclipse.orion.server.useradmin(0.2);

is it the problem?

**Comment by jhpedemonte** [comment]
Your **target platform** is not set correctly.  Please re-read the [developer setup](https://github.com/maqetta/maqetta/wiki/Maqetta-with-Orion-Developer-Setup) instructions.  At this point, it's best to use a Maqetta nightly or Orion 2.0 for your target platform.
