### ISSUE TITLE
how to run in Linux?

### ISSUE THREAD

**Issue by licai** [maqetta/maqetta#3893]
hi guys:
i want to run the service in CentOS(one branch of Linux), can i do it? how to?

thanks any feedback.

**Comment by billreed63** [comment]
Questions are best asked on the maqetta users group
https://groups.google.com/forum/?fromgroups#!forum/maqetta-users

But yes you gan run on linux down load the zip file from maqetta.org the readme describes how to run on linux

**Comment by jhpedemonte** [comment]
This page may be of help: https://github.com/maqetta/maqetta/wiki/Server-Installation-and-Setup
