### ISSUE TITLE
Issues when creating & copying files from regular to Eclipse project

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3899]
While in a "regular" project, I created an Eclipse project and selected to copy the files of the existing project.  This resulted in a bad project, with many files outside of the _WebContent_ dir.

Also had issues going in the opposite direction.

---

Easiest solution would be to disable or enforce the Eclipse checkbox if the user checks the copy option, such that when copying is enabled, user can only create a project of the same type (i.e. regular -> regular; Eclipse -> Eclipse).

**Comment by JonFerraiolo** [comment]
At this point, my inclination would be to go with the "easiest solution" and log a bug for posterity about a better long-term solution
