### ISSUE TITLE
[UI POLISH] New drop down menu should show icons for each entry

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#39]
Currently, the New... menu in the application header area does not
contain icons. Which forces the user to read through each entry. Adding icons
will help with instant recognition of available actions.

Changes that should be made...
1. Icons should be added for each action
2. The word 'New' should be removed from the menu, since the word New invokes
the actions.. its a bit redunnant

The menu should read as such.. 

New [ARROW]
  [ICON] HTML File...
  [ICON] CSS File...
  [ICON] JavaScript File...
##   [ICON] File...

  [ICON] Review...

**Comment by peller** [comment]
should we create tags like "UI" and "polish" rather than using the summary?

**Comment by JonFerraiolo** [comment]
-> M7/Prio-Low just in case we have time to address this as part of UI makeover

**Comment by JonFerraiolo** [comment]
This has been fixed in things that went into M6 and M7.
