### ISSUE TITLE
Test plan instructions wrong for restoring dojo default theme?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3908]
I ran the theme sets test plan, and in the last section there is a claim in the test plan that the theme map markup will get deleted from the source code if the themes match the default set of themes. However, when I followed the instructions, the theme map markup is still in the file.

@billreed63 - could you please take a quick look at this? We probably don't want to change the source code at this point, but maybe the test plan needs to be updated?

**Comment by billreed63** [comment]
The test plan is wrong, I have not really be keeping it updated. It is better to run the SeleiumIDE test case. But I will update the testcase
