### ISSUE TITLE
pushComment undefined exception

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#391]
Saw this in FF - simply loading the workbench with exception catching on, you break in the debugger at davinci/html/CSSParser.js line 229

``` js
if (pushComment)
```

pushComment is apparently a global reference -- there is no var declaration in this file -- so if it is undefined, it throws.  The global reference should be avoided.  It gets caught in a giant try/catch/squelch one level higher on the stack.

**Comment by JonFerraiolo** [comment]
-> @billreed63 M7 Prio-Med

**Comment by billreed63** [comment]
no longer an issue in M10
