### ISSUE TITLE
maqetta-test needs updated siteConfig files, particularly widgetPalette.json?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3910]
On maqetta-test, all of the new clipart icons end up in the "Other" category at bottom of widget palette. I suspect that siteConfig/widgetPalette.json wasn't updated on the maqetta-test server to include the latest and greatest files from the git repository.

**Comment by jhpedemonte** [comment]
Fixed.  Also added note to the M10 Migration bug, so we remember to do this during deployment.
