### ISSUE TITLE
IconContainer and IconMenu SmartInput dialogs are empty

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3911]
On Mac/FF using maqetta-test -
- New Mobile App
- Add a View
- Add an IconContainer or IconMenu

Result=> SmartInput comes up with an empty white area - no options show. If then you click OK in the empty dialog, then no child widgets are added to the IconContainer or IconMenu

**Comment by billreed63** [comment]
Need to change create tool, no need to create iconItems just send child data to addCommand
