### ISSUE TITLE
SpinWheel displays correctly in editor and preview but not after exporting and viewing as standalone

### ISSUE THREAD

**Issue by andipfaff** [maqetta/maqetta#3916]
I was creating a simple 1-slot spinwheel in a View. This is correctly displayed in the WYSIWYG Editor and the Preview. Then I have exported all the files in the Project and saved them in my Webserver root. All objects work fine but the spinwheel shows noting except the vertical black lines, the Labels and the horizontal blue bar with the selected value. I am using the same browser (FF current release). What did I forget?

**Comment by jhpedemonte** [comment]
@billreed63, is this fixed in the **master**?  Or is this something else?

**Comment by billreed63** [comment]
This works for me, did you have any messages in the browser console?

**Comment by andipfaff** [comment]
No error javascript message. Many CSS errors but these is due to the definitions for the other browsers.

**Comment by billreed63** [comment]
fixed by above commit

**Comment by andipfaff** [comment]
Sorry for my question but what does that mean?

**Comment by billreed63** [comment]
The fix will be in M10 which should be posted by the end of the month. Do you require a fix before then?

**Comment by andipfaff** [comment]
Looking onto my bank account it is already end of month ;-)
No I am not in a hurry, still developping. The functionality is given, it is just a cosmetic isue.
