### ISSUE TITLE
Upload zip on maqetta-test puts files in root folder rather than currently selected folder

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3925]
I got this problem to happen on maqetta-test with both Win/Chrome and Mac/Firefox. Couldn't make it fail when running from Eclipse. Therefore, might be a tough bug.
- I selected 3 *.gif files from the same folder and created a ZIP out of those files such that the *.gif files were in the root of the ZIP. (i.e., if you expanded the zip, the files would end up as ./1.gif, ./2.gif, ./3.gif).
- In maqetta on maqetta-test, I created a folder (e.g., folder1) and made sure it was selected
- I clicked on the upload-zip icon, selected the ZIP I created, and then clicked upload

RESULT=> 3 images end up in root of workspace, and not in folder1

I couldn't reproduce this if the images were in a subfolder within the ZIP. Seems like the problem only occurs if the images are at the root of the ZIP.

**Comment by peller** [comment]
I tried this and it worked on both Chrome and FF against maqetta-app-test.  No subfolder in the zip, files ended up in folder1

**Comment by peller** [comment]
@JonFerraiolo

**Comment by JonFerraiolo** [comment]
I'll close this. I did indeed see the problem, but I can't reproduce today. Worst case is that we have a great new feature in M10 that is sometimes flaky, whereas in M9 we offered nothing at all.
