### ISSUE TITLE
anchor tag has standard CSS definitions

### ISSUE THREAD

**Issue by andipfaff** [maqetta/maqetta#3928]
This is not really a bug but I am wondering that the a tag is displayed in blue and underlined (standard/undefined CSS layout). How can I format this tag globally in order to get it displayed white on black on Android/Blackberry respectively black on grey on iPhones?
Thanks in advance

**Comment by billreed63** [comment]
Since this is not a bug, could you please submit the question to the user group https://groups.google.com/forum/?fromgroups#!forum/maqetta-users
