### ISSUE TITLE
Renamed JSON files with theme cloning?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#393]
@childsb, @jhpedemonte

If we clone the claro theme into a new myclaro theme, the claro.json file does not get renamed. 

This bug is mostly a question to Bill and Brad: when cloning a new theme, should we also rename the json file? Brad points out that this isn't actually necessary. The JSON file could have any arbitrary name. This renaming would be more for "cosmetic" reasons. Another way to skin this cat would be to name the JSON files with a generic name such as theme_metadata.json versus (e.g.) claro.json.

This is potentially related to #144 (Move *.theme files up into themes/ folder). Should we move both the *.theme and *.json files up to the parent folder? That would allow the theme folders (e.g., claro/) to be original/unmodified from the original library distribution, which of course is a good thing. If we move both the *.theme and *.json files up to parent folder, then we probably do want to rename the *.json file.

**Comment by billreed63** [comment]
With the delta theme #23 the theme.json file is not copied. it is left in the original theme folder. The .theme file is copied and update to reflect the correct location of the original .json
