### ISSUE TITLE
Validation for name in New Project dialog too restrictive

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3931]
The validation for a new project name is too restrictive, disallowing names that include an underscore ("_") and possibly other common characters.

**Comment by JonFerraiolo** [comment]
Why do we have to fix this for M10?

The reason that underscore is disallowed is that the project template feature creates a file on the server that is named PROJECTNAME+'_'+USEREMAIL. To fix this bug, we'd have to change that convention, which seems too risky.

**Comment by JonFerraiolo** [comment]
What happened is that I had put validation logic in NewProjectTemplate.js and then moved it over to NewProject.js. For NewProjectTemplate.js, the underscore is a problem, but for NewProject, it isn't. (We allowed underscores in project names for all previous releases.)

I logged a separate bug for the future on allowing underscore in project template names: #3940
