### ISSUE TITLE
Cannot un-disable an HTML input widget

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3938]
New file, drop an HTML `<input>` widget and set the **disabled** property in the **Widget** section of the Properties view.

Afterwards, user cannot unset **disabled** prop nor does the smart input appear.

Tested on Firefox/Mac.

@JonFerraiolo

**Comment by billreed63** [comment]
same issue with html widgets  SELECT, TEXTAREA, VIDEO, AUDIO

**Comment by billreed63** [comment]
fixed by 27df75155ec1135298d8b399f7c5382fd95a274f
