### ISSUE TITLE
Error when closing & saving file in Firefox

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3939]
1. New desktop file.
2. Drop a button on page.
3. Click on close icon to close the file.
4. Click **Save** button to save file, when dialog appears.

=> File closes and is saved but get exception when calling `setDirty` > `setTitle`: `this["domNode"]` is null.

@JonFerraiolo @billreed63

**Comment by peller** [comment]
inclined not to touch this, as the promise isn't chained and the exception has no effect, right?  Oh, I take it back, bill's new UI should get called, but I don't see it. Do you?
