### ISSUE TITLE
Error message when initializing theme editor with migrated theme

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3949]
I created a custom theme ("custom2") in M9, and my M9 session had the custom2 theme editor open, along with another HTML file (which was the active file). Upon switching to the custom2 theme editor, the following error message appeared in the console:

```
dijit-all.js:15171
_4ca {stack: "Error: Unable to load app/metadata/dojo/1.8/dojox/…s?6392b8210ff2454dc51d7eb2a2ec1d76b6a15ee2:402:6)", message: "Unable to load app/metadata/dojo/1.8/dojox/mobile/…392b8210ff2454dc51d7eb2a2ec1d76b6a15ee2 status: 0", response: Object, status: 0, responseText: ""…}
 dojo.js:4587
ERROR: Could not load metadata for type: dojox/mobile/RadioButton davinci.js:51468
dojo/parser::parse() error Error {} parser.js:411
Resource interpreted as Document but transferred with MIME type image/svg+xml: "http://maqetta-app-test.austin.ibm.com/maqetta/app/preview/images/iphone.svg". davinci.js:50479
dijit-all may include much more code than your application actually requires. We strongly recommend that you investigate a custom build or the web build tool dijit-all.js:15171
```

I'm not sure how big of a problem this is...

**Comment by jhpedemonte** [comment]
Ah, so "dojox/mobile/RadioButton" was one of the [changes I made yesterday.](1318b17a5069a71f9be55227636da1a3740d601e)  Does the file under review have the dot notation?  Or is this something else?

@peller

**Comment by peller** [comment]
does the console really truncate the paths with "..."?  That's annoying...

**Comment by billreed63** [comment]
@JonFerraiolo  can you reproduce this? could it have been a one time network problem?
I have opened mobile themes migrated from M9 and have not seen this issue?

**Comment by JonFerraiolo** [comment]
Closing this.

>  can you reproduce this?

Not easily. I subsequently changed my migrated themes.

> I have opened mobile themes migrated from M9 and have not seen this issue

Things worked for me, too, except for the console message.

Closing.

**Comment by billreed63** [comment]
with the themes now using delta's and just referencing the theme.json and html files I do not see how any thing in the   themes could have caused the error. The `ERROR: Could not load metadata for type: dojox/mobile/RadioButton davinci.js:51468` sure sounds like some kind of network problem, Did you look at the network pannel to see if we had a 404 or 500 on the RadioButton_oam.json file?
