### ISSUE TITLE
Page with "data:" URL break device silhouette preview on WebKit

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3954]
I you have a page that loads an image using a `data:` URI, then the `onload` event does not fire on WebKit browsers.  This causes mobile Preview to fail, because the silhouette is drawn when the `onload` even fires.

**Comment by jhpedemonte** [comment]
To test, create a mobile page and add an Icon Container.  The child Icon Item widgets use `data:` URIs to load images.

**Comment by jhpedemonte** [comment]
Regression from M9.  @peller @JonFerraiolo @billreed63, what could have changed to cause this bug?

**Comment by JonFerraiolo** [comment]
I don't see why `data:` could be causing problems.

I see two commits in the preview code since M9:
- a3146a7aeb2fe33c473ccde56fc3d425e85cddff
- 4521fadc9f48cff8234621d2cd4e153b3f312ce7

@peller

**Comment by jhpedemonte** [comment]
I reverted those locally but the issue still occurred.

**Comment by JonFerraiolo** [comment]
I see the problem regularly when the Chrome debugger is active, but most of the time the silhouette works correctly if the debugger is closed.

**Comment by JonFerraiolo** [comment]
@jhpedemonte - do you see the problem on maqetta-test, locally or both?

**Comment by jhpedemonte** [comment]
Huh, only locally, not on maqetta-test.  Weird!

**Comment by JonFerraiolo** [comment]
I'll close this because I suspect it doesn't have to do with `data:` and instead is just a timing thing (and potentially a debugger thing), and I can't see us fooling around with the preview code at this point.
