### ISSUE TITLE
resetWorkbenchState=1 not working

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3955]
This commit d148f89c8f03b8ffc858123ff1f58c0d8fa26d33 removed function `clearWorkbenchState` from Workbench.js, but that function is called in pagedesigner.html if `resetWorkbenchState=1` is passed as a URL parameter.

I didn't fully understand all of the changes from the above commit, so sending to @peller to look at.

**Comment by peller** [comment]
Oops.  I grepped for clearWorkbenchState, and thought it was unused, but I must have only checked the core.client project.  I'll put the method back.

The changeset was to simplify the logic to update the state and make it more reliable.  There was some odd deferred logic there before.
