### ISSUE TITLE
maqetta release 9 failed to launch

### ISSUE THREAD

**Issue by darkelf2003** [maqetta/maqetta#3968]
I download and extract the release 9 version, after configured as the tutorial it failed to start.
The error log shows:

!ENTRY maqetta.core.server 4 0 2013-05-02 11:08:02.550
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: The bundle "maqetta.core.server_1.0.0.qualifier [1]" could not be resolved. Reason: Missing Constraint: Require-Bundle: org.eclipse.orion.server.core; bundle-version="0.3.0"

Could somebody help with the problem, please?

**Comment by billreed63** [comment]
The best place to questions of this nature is the users group Please join the users group and post this question there.
Also could you please include what OS you are using? Have you tried Release 10?
