### ISSUE TITLE
Outline view: get browser context menu instead of davinci's

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#397]
- New HTML file
- Add a DIV
- Set width/height to 250px
- Add a TabContainer inside of the DIV
- Select the DIV in Outline palette

If the mouse is over blank area of Outline palette, you get the
browser context menu instead of daVinci context menu

**Comment by JonFerraiolo** [comment]
-> @peller future

**Comment by JonFerraiolo** [comment]
Fixed in M6
