### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by leovicio** [maqetta/maqetta#3971]
How do I use google maps v3 and jquery mobile?

**Comment by jhpedemonte** [comment]
Please post questions such as these on the [users](https://groups.google.com/forum/?fromgroups=#!forum/maqetta-users) or [developers](https://groups.google.com/forum/?fromgroups=#!forum/maqetta-devs) groups.  For example, [here is a previous post that talks about using Google Maps](https://groups.google.com/d/msg/maqetta-users/2uo0u5KDNgE/lQLGNCxorCAJ).

Closing, this isn't a bug.
