### ISSUE TITLE
damaged zip file

### ISSUE THREAD

**Issue by ceeroover** [maqetta/maqetta#3973]
download of the entire workspace results in damaged zip file

Tried on Firefox17.0.5 ESR and 21.0 and Chrome 26.0.1410.64 and 27.0.1453.110, other zipfiles (from other sources) work...
OS: Win8 / Win7
Tools: WinZip / 7Zip

I'm using my own Maqetta server:

Version: 10
Date: 02.05.2013 10:12:13
Build: f1554971890cef6693dcc67abd889d64370fcabd

but I have the same issue with the current maqetta.org server version

There was an issue before (#3573), any solution?

**Comment by jhpedemonte** [comment]
We'll take a look.

**Comment by jhpedemonte** [comment]
I can't reproduce this on Chrome/Mac OS X running from maqetta.org.  I clicked the **Download Entire Project** toolbar button for one of my projects, then just took the defaults (all libraries selected).

While I do see some odd activity in the Network Panel (the request to `/maqetta/cmd/download` gets canceled), the download completes and the ZIP seems fine.

Could this be an issue specific to the Windows tools?

@ceeroover, does it fail for you with a completely new project with only the default files ( **Create > Project** )?  With a failing project, can you test on a non-Windows machine -- does it also fail there?

@billreed63

**Comment by ceeroover** [comment]
Does work for maqetta.org now (??). The download size of the zip-files before was 1.2MB, now it's about (6-8MB). Plain new projects on my own server still end up with corrupted 1.2MB zip-files, i will reinstall the server and check this again... Thanks

**Comment by JonFerraiolo** [comment]
I fired up Windows 7 running under Parallels (on top of MacOS), downloaded Release 10 from maqetta.org, launched the app at http://localhost:5000, created file1.html, then clicked the button to download my entire workspace (accepting all of the defaults). Then I unzip'd using the Windows "Extract all" command on the context menu for ZIP files. When I look at the folder containing the contents of the extract-all command, I see everything I should see: file1.html, themes/, libs/, etc. The ZIP file was 8M.

**Comment by peller** [comment]
On Mac/Chrome when this problem was first reported, I also saw a 1.2M download that was incomplete.  Logs showed no errors.  Now it works fine.

**Comment by ceeroover** [comment]
Restart of the maqetta server solved the problem. (I forgot to check this before, because I had the issue online and offline at first).
