### ISSUE TITLE
entire project = read only (+severe damage to existing files)

### ISSUE THREAD

**Issue by rogueyoshi** [maqetta/maqetta#3974]
for some reason, i cannot save any changes made to files through either maqetta itself or orion. also i seemed to have lost all data that i've worked on this past day and am not even able to upload my local backups... what's going on?

**Comment by rogueyoshi** [comment]
ok, i believe this may be browser related. restarted chromium and it seems to be saving again.

**Comment by jhpedemonte** [comment]
Were you running against a local server or maqetta.org?

If local, did you see any errors from the server?  Did you see any errors in the browser's error console?

**Comment by rogueyoshi** [comment]
i was running through maqetta.org. if it happens again, i'll post a new ticket with error output.
