### ISSUE TITLE
unable to change style of instantiated ListItem's labelNode inside of inactive View

### ISSUE THREAD

**Issue by rogueyoshi** [maqetta/maqetta#3975]
code sample: http://jsfiddle.net/K2msC/2/

this works flawless in vanilla dojo as seen above but when done in maqetta, the labelNode's style.display will be "block" no matter what. am i missing something?

UPDATE: it seems this only occurs if it is instantiated inside of an inactive View. is this intentional?

**Comment by jhpedemonte** [comment]
What exactly are you trying to do?

I was able to create a mobile page with 2 **View**s, each with an **EdgeToEdgeList**, where the first items contained a **Slider**:

![screen shot 2013-07-02 at 1 08 58 pm](https://f.cloud.github.com/assets/711365/738261/80a08cac-e342-11e2-8458-c0a9d863ae59.png)

After adding the Slider, I had to change its properties to `display: inline-block` and `vertical-align: middle`.  Works fine in both Views in the visual editor and in preview.

If you did something different, please explain in detail how you got it to fail.

**Comment by jhpedemonte** [comment]
For reference, here's the [file created by Maqetta](https://gist.github.com/jhpedemonte/5911767).

**Comment by rogueyoshi** [comment]
though js, i'm trying to generate a bunch of listitems for a list and set each listitem's labelNode's display style to inline-block. the problem is that if i try to do it right after instantiating it, it seems to get overwritten with the default value of block anyways. i realize now that the problem is that maqetta doesn't use the latest version of dojo. i updated my project to use the new version and it works fine. i found another bug though, which i think is a fault in dojo, so i'll be opening a ticket in the appropriate section.

thanks for the response.
