### ISSUE TITLE
TitlePane localhost URL only works on canvas 

### ISSUE THREAD

**Issue by pramsey-home** [maqetta/maqetta#3977]
Trying to use the URL property of a Dojo TitlePane to insert content from a locally stored file (same folder).

url="test.html" works in the canvas - but not browser preview or downloaded project. "! Sorry, an error occurred."

Neither relative nor absolute paths are successful.

Bizarrely, uploading test.html to a public Dropbox folder, creating a public link via their context menu, and pasting that url into the TitlePane url property, does work.

I'm in Chrome  29.0.1547.62 m, on Windows 7, non-war version of maqetta.

**Comment by billreed63** [comment]
Development on maqetta has been suspend, so the best avenue to get questions like this answered is the users group where other users may have encountered the same issue.
