### ISSUE TITLE
Unable to create new html file

### ISSUE THREAD

**Issue by rvdb1** [maqetta/maqetta#3980]
Created a new project (Test01)
Tried to create a new desktop application.
No file gets created.
When I switch to an another project and back to this project, I get the following error:
Problem accessing /maqetta/cmd/configProject. Reason:
    org.eclipse.core.runtime.CoreException: Could not write file: /var/lib/maqetta/users/Iks/app.css.
at the url http://app.maqetta.org/maqetta/cmd/configProject?configOnly=true&project=Test01

**Comment by billreed63** [comment]
This is most likely a setup issue, please post to maqetta users group. https://groups.google.com/forum/#!forum/maqetta-users
