### ISSUE TITLE
build in phonegap but only shows html page

### ISSUE THREAD

**Issue by adenaan** [maqetta/maqetta#3982]
Hi there!I did a build with my app i did on maqeeta but when on the device it only shows the page and text.Dont show any embeded content and formating on the page.its like its not seeing the lib and them folders.Is the a correct way to do the build on phonegap.

btw,maqetta is a great way to make your application.Thanks for this.

Thanks
Adenaan

**Comment by billreed63** [comment]
Please post this on the maqetta user group, https://groups.google.com/forum/#!forum/maqetta-users
search the users group for phonegap
Here is one post that may help https://groups.google.com/forum/#!searchin/maqetta-users/phonegap/maqetta-users/JN3EkAoLpVo/ahM0d3Dy2tQJ
