### ISSUE TITLE
Can't find org.eclipse.orion.server.configurator

### ISSUE THREAD

**Issue by wcnjeusr** [maqetta/maqetta#3983]
Can't find org.eclipse.orion.server.configurator,how can I run it?
坑货。。。

**Comment by jhpedemonte** [comment]
Please post questions like this to the [users](https://groups.google.com/forum/#!forum/maqetta-users) or [developers](https://groups.google.com/forum/#!forum/maqetta-devs) forums.

Closing as this is not a bug.
