### ISSUE TITLE
my user account can not use,Error starting Maqetta:Can not read property '0' of undefined

### ISSUE THREAD

**Issue by ssiloveyouday** [maqetta/maqetta#3984]
I install a Maqetta in my computer, and register many user accounts. two of these user account can not be loggined in. When I login in , it shows: Error starting Maqetta:Can not read property '0' of undefined. these two users' operations are as follows:
1.rename a project , and then craete a new project and copy files from current projcet
2.I register a user account and login in only three times, then log out. After a long time, when I login in the maqetta, it shows:Error starting Maqetta:Can not read property '0' of undefined.
thank you very much for your answers.

**Comment by jhpedemonte** [comment]
Please post this to the [users](https://groups.google.com/group/maqetta-users) group.  This is most likely a setup issue rather than a bug. Please include more information/details about what you are doing and any errors/stack traces that the server may output.
