### ISSUE TITLE
Controls don't display

### ISSUE THREAD

**Issue by gullbyrd** [maqetta/maqetta#4]
Just checking out maqetta for the first time... The editor displays as expected, but when I open a page or drop a control on a new page, nothing happens. In Firefox 4 and Chrome 10, on Vista. Pretty much default settings in both, as far as security, popups, etc.

**Comment by gullbyrd** [comment]
P.S. I should add, this is in the one-time try it now mode... And when I start over and try it again, it works, at least in Firefox. But still.

**Comment by jhpedemonte** [comment]
Known issue, which we've fixed.  Will be in next release.
