### ISSUE TITLE
repository/maqetta not found

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#405]
When running the build scripts from Eclipse (Export) I get this error

/Users/peller/maqetta-src/maqetta/davinci.core/customBuildCallbacks.xml:215: The following error occurred while executing this line:
/Users/peller/maqetta-src/maqetta/davinci.core/customBuildCallbacks.xml:73: The directory /Applications/eclipse/Eclipse.app/Contents/MacOS/repository/maqetta does not exist

I can't find anything in the script which is supposed to create the ${users.dir}/repository directory.  It appears to be a staging area.

**Comment by waynevicknair** [comment]
i'm lobbying for external build support (i.e. from command line) only at this time. it should be OK as long as people can test by running a local launch configuration which I will verify.

the current build is setup (by build.sh) to run from a 'build' directory. the (external) build relies on the ${users.dir} property being set (automatically by the JVM as it's a Java system property) to the working directory which should always be the build directory for command line builds, but will be set to whatever path Eclipse runs from when referenced from inside Eclipse.

**Comment by waynevicknair** [comment]
per today's scrum and subsequent build meeting, we will do external builds only. i have tested the local launch configuration in Eclipse and it works fine.
