### ISSUE TITLE
The oval in review mode appeared at the wrong place 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#406]
The oval you put over the buttons in review mode appeared at the wrong place when returning to page editor
Here is a link to an image
https://picasaweb.google.com/lh/photo/W0RRwzW926XjM9kMy-FqV_9PDopVreWVkUYJIPt3s80?feat=directlink

**Comment by jhpedemonte** [comment]
-> @billreed63, can you please retest this?

**Comment by billreed63** [comment]
looks like it is fixed
