### ISSUE TITLE
Allow default version in widget metadata

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#409]
see workaround in 4e9e17af3a15a1b6e4e9ff6c1a537aab07d0d12e when upgrading Dojo (#16)

FYI: @childsb

The widget-specific check for "version" was commented out.  It should be put back, and I suggest removing the version definitions from the metadata.  I'm not sure if the fallback for davinci.library.getUserLibs() is correct, though.

**Comment by jhpedemonte** [comment]
@childsb Please review this fix.
