### ISSUE TITLE
DataGrid creation is broken (regression)

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#411]
After migrating to Dojo 1.6 (#16) an exception is thrown when adding a DataGrid to the page

The culprit appears to be the use of `inDef.cellType` in `dojox.grid._Layout.addCellDef` which is a string, but assumed to be a constructor.  I need to get with Evan on this:
http://bugs.dojotoolkit.org/ticket/10657

**Comment by peller** [comment]
@billreed63: ready for review

**Comment by billreed63** [comment]
Code looks good to me
