### ISSUE TITLE
Compile Time Warnings in Build

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#412]
@JonFerrraiolo @jhpedemonte

There are over 250 compiler warnings in the build output. Many of them are trivial to fix and very low risk to improve code hygiene. 

Brad, Please analyze the list which I will attach here (somehow) or send to you in email.

**Comment by jhpedemonte** [comment]
See d0ab56b620aa46bf717feb71c752f48d911ebb49 & 27c5529ac50fcd8615a9751fe5eb20d91737f2cb.

**Comment by jhpedemonte** [comment]
@JonFerraiolo Please review the two commits.  Should be pretty straight forward.

**Comment by JonFerraiolo** [comment]
I reviewed the commits and everything looks good.

**Comment by JonFerraiolo** [comment]
Is this issue complete? Can we close it now?

**Comment by waynevicknair** [comment]
i'll close it with the request that folks clean up files as they touch them. no point in wasting time with compile warnings right now. it would just add risk.
