### ISSUE TITLE
Menubar problems with empty menus

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#414]
(Using Mac/Chrome, not sure what happens with FF4, but I guess same thing)

Create a menubar with non-empty menus, such as:

Menu 1

> Menu Item 1.1
> Menu 2
> Menu Item 2.1

and everything works OK, but add an empty menu "Menu 3" at bottom:

Menu 1

> Menu Item 1.1
> Menu 2
> Menu Item 2.1
> Menu 3

and then try to re-edit the data for the Menubar, then the following text appear on the canvas instead of inline edit re-appearing (except less-than and greater-than instead of [ and ]):

[span dojotType="dijit.PopupMenuBarItem" label="Menu 1" disabled="false"][ span dojoType="dijit.Menu"][ span dojoType="dijit.MenuItem" label="Menu Item 1.1"][/span]
[/span]
[/span][span dojotType="dijit.PopupMenuBarItem" label="Menu 2" disabled="false"][span dojoType="dijit.Menu"][span dojoType="dijit.MenuItem" label="Menu Item 2.1"][/span]
[/span]
[/span][span dojotType="dijit.PopupMenuBarItem" label="Menu 3" disabled="false"][span dojoType="dijit.Menu"][/span]
[/span]

Furthermore, if I try to remove the last menu item from an existing menu, for example, remove "Menu Item 1.1" from "Menu 1", as show below:

Menu 1
Menu 2

> Menu Item 2.1

The above attempt doesn't take because when I double-click on the menubar to re-edit, "Menu Item 1.1" is still there:

Menu 1

> Menu Item 1.1
> Menu 2
> Menu Item 2.1

**Comment by billreed63** [comment]
Fixed June 2011
