### ISSUE TITLE
SaveAs within nested folder messes up URLs to dojo/etc.

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#416]
If you create a new file1.html in a nested folder, then save, close, reopen, and then SaveAs file2.html in the same nested folder, the URLs in the HEAD get an extra ../. The HEAD of file2.html looks as shown below. Note that the URLs have ../../ instead of just ../

<!DOCTYPE html>
<html>
<head>
<title>Untitled</title>

<style type="text/css">
@import "../../themes/claro/claro.css";
@import "../../app.css";
@import "../../lib/dojo/dojo/resources/dojo.css";
@import "../../lib/dojo/dojo/resources/dojo.css";
</style>

<script type="text/javascript" src="../../lib/dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script>

<script type="text/javascript">
dojo.require('dijit.MenuBar');
dojo.require('dijit.PopupMenuBarItem');
dojo.require('dijit.MenuItem');
dojo.require('dijit.Menu');
dojo.require('dijit.Toolbar');
dojo.require('dijit.form.Button');</script>

<script src="../../maqetta/States.js"></script>

<script src="../../maqetta/maqetta.js"></script>

</head>

**Comment by childsb** [comment]
Fixed in commit 4ff1a286b1a2e7e072d4 and others..
