### ISSUE TITLE
Source view/split view broken

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#423]
Regressed with #16: Workbench upgrade to Dojo 1.6.  This is the very fragile code that makes the split view and moves the border container regions around dynamically, something BC isn't really supposed to do, and the panes never really have the right dimensions, even when this works.  Since moving to 1.6, you have to resize the panes to get them to appear.  We had a very similar regression a few months ago.  I need to recall what the workaround was.

@JonFerraiolo

**Comment by peller** [comment]
Jon and Javier say they're still seeing the problem (see #479)

**Comment by jhpedemonte** [comment]
A few things:
- Is there any way to avoid using that "private" function on BorderContainer?
- Is this a bug in BC, or just in how we are using it?
- Please open a future issue to reevaluate your "kludge" fix.

**Comment by peller** [comment]
Note there's still a resize call at the top of the routine which seems unnecessary... taking it out breaks the views on some browsers.

I left it with far fewer kludges than we started with.  I'm satisfied with the private "kludge".  Against my recommendation, we're doing something BorderContainer does not support, hence the private method call.  Setting the size directly on the DOM without calling bordercontainer at all and just calling resize a few times and praying that it works (the old kludges) were even less portable.
