### ISSUE TITLE
New theme... broken in latest code

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#425]
(Probably because read-only themes are only partly implemented)
## I just pulled the latest code, and (using development build) first thing in a new session I tried to use the "New Theme..." command, and clicking on OK in the dialog causes nothing to happen (dialog stays up) and I got the following in the console:

GET http://localhost:55557/maqetta/cmd/copy?source=.%2Fthemes%2Fclaro&dest=.%2Fthemes%2Fddd&recurse=true 500 (Internal Server Error)
app/dojo/./_base/xhr.js:609Error: Unable to load ./cmd/copy?source=.%2Fthemes%2Fclaro&dest=.%2Fthemes%2Fddd&recurse=true status:500
app/dojo/../davinci/Runtime.js:315unknown error: status=500
app/dojo/./_base/Deferred.js:213Error: Unable to load ./cmd/copy?source=.%2Fthemes%2Fclaro&dest=.%2Fthemes%2Fddd&recurse=true status:500
app/dojo/./_base/Deferred.js:213Error: Unable to load ./cmd/copy?source=.%2Fthemes%2Fclaro&dest=.%2Fthemes%2Fddd&recurse=true status:500
app/dojo/./_base/Deferred.js:213ReferenceError: result is not defined

**Comment by peller** [comment]
It dies in copyDirectory.  The attempt to initalize r=destination.create("Calendar.css") returns null.  It thinks that destination.isDirectory() is false, even though the previous command was destination mkdir()

**Comment by childsb** [comment]
fixed.

**Comment by peller** [comment]
see also #453?

**Comment by childsb** [comment]
commit  ec06a864025b0e898837
