### ISSUE TITLE
Review mode tooltipdialog never goes away

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#426]
@peller, @EldonReturn

I haven't had time to characterize this bug, but thought I should log it before forgetting. With latest code pulled from GitHub, and testing when integrated with IBM internal mail (by including the IBM-specific intranet-only davinci.w3ibm project), I can successfully create a New Review and open up the review UI, but when I double-clicked on Sample1.html.rev, the tooltip dialog that shows metadata about the review doesn't go away, obscuring the middle pane (where the document to be reviewed shows).

I wonder if this is a regression associated with the move to Dojo 1.6?

**Comment by peller** [comment]
Thanks, Jon.  I noticed this also and forgot to log it.  There is an exception on the console coming from davinci.review.view.CommentExplorerView:126

``` javascript
dijit.popup.moveOffScreen(widget.domNode);
```

which calls _createWrapper in the dialog code, which returns true instead of a node... could be a Dijit regression.  I'll investigate further.

**Comment by peller** [comment]
FWIW, the documentation says not to use moveOffScreen for accessibility issues.  Should we just tear down the dialog?
