### ISSUE TITLE
Add toolbar for editing arbitrary files

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#43]
~~New File... doesn't have a toolbar. Either we need to add a toolbar, or remove the command. As is, not particularly useful since there is no way to save the new file you just created.~~

**Updated 2012-03-13:** Allow users to edit arbitrary text files, not just _.html, *.js and *.css.  Need to add a toolbar for such files, with at least *Save_ and _Save As_.

**Comment by jhpedemonte** [comment]
Do you think we should just comment this out for now?  Should be an easy enough fix, low risk.

**Comment by JonFerraiolo** [comment]
Leaving open, but removing M2 milestone. Commit 1e361262ab2fb2c4dd45 temporarily removed New File command but we should restore it once we have Save, SaveAs buttons working on toolbar for this scenario.

**Comment by peller** [comment]
still a problem for M4.  CSS has save buttons, JS does not.  Why?

see #1227

**Comment by JonFerraiolo** [comment]
Was unassigned. Assigned to @waynevicknair and pushed to M5 with Priority-Med

**Comment by jhpedemonte** [comment]
Affects **JSON** files as well (of which there are several in our **sample_data** folder.

**Comment by JonFerraiolo** [comment]
The title says either either add toolbar or remove the command. We really want to add the toolbar and allow people to edit arbitrary text files, not just *.html, *.js and *.css.

**Comment by waynevicknair** [comment]
changed this to a feature. sounds like we want to add general editing capabilities. i assume we would support arbitrary file editing, but still only model the three types we model today (HTML, JS, CSS).

**Comment by JonFerraiolo** [comment]
yes. users should be able to do plain text editing on *.txt, *.xml, *.whatever

**Comment by jhpedemonte** [comment]
Updated title and summary (was "Remove "New File" command, or add toolbar?").

-> M6

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo to decide whether this issue has been resolved

**Comment by JonFerraiolo** [comment]
This issue has not been resolved yet. We still don't put a toolbar with Save/SaveAs icons.

-> @doronrosenberg - could you please look into this and see if there is a safe fix for M6? Note that we provide a toolbar for *.js, *.css, *.json and *.svg (and maybe a few more)
