### ISSUE TITLE
Dialog for creating a review contains a 'Window Size' field and its not clear what it does

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#430]
We need to help the user have a better understanding of what setting the 'Window Size' is useful for in defining a Review. Currently its not very clear.

Review on May 12 2011

**Comment by JonFerraiolo** [comment]
Maybe we should add a ? icon next to the control with help text? (Probably same thing for due date control)

**Comment by jmockler** [comment]
Yes - I think that would help users with understanding what this control is referring to.
