### ISSUE TITLE
Review and commenting hover presentation and interaction polish

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#432]
Review and Commenting hovers in the Review View

See this image for mark-up polish: http://skitch.com/janetmockler/fb3kw/review-hovers-432
1. The hover pops up at some distance from the folder/resources
2. The hover should only show when the user hovers over the folder
3. The alignments, text capitalization and other elements need to be fixed in the hover 

@jmockler @JonFerraiolo @EldonReturn
 Review and Commenting Review - May 12, 2011

**Comment by EldonReturn** [comment]
Fixed. http://skitch.com/eldon/ff1jb/1
