### ISSUE TITLE
New Review dialog artifact

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#434]
When creating a review, the user clicks publish. And a really tiny dialog shows up in the window briefly. 

During the review, there was some discussion around this element. And it was thought to be a bug.

@jmockler @JonFerraiolo @EldonReturn
 Review and Commenting Review - May 12, 2011

**Comment by EldonReturn** [comment]
This bug is fixed in the commit: https://github.com/maqetta/maqetta/commit/54a175ea3478067f547579f8920f80841bcf6307
