### ISSUE TITLE
Review and Commenting Email notifications should be more useful

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#435]
1. Subject line should have a default initial message that a site admin can customize
2. Subject line should be a point of configuration for the user from the 'Title' field in the Review and Commenting Dialog

So would look like this

Maqetta Review Invitation: Title that the user has defined

@jmockler @JonFerraiolo @EldonReturn
 Review and Commenting Review - May 12, 2011

**Comment by JonFerraiolo** [comment]
The site customization features are lower priority than changing the default message as Janet has suggested.

**Comment by EldonReturn** [comment]
Fixed. Added a template file so that the admin can configure it.
