### ISSUE TITLE
Review and Commenting Email notifications content revision

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#436]
Email message content:

Janet Mockler (email address) has invited you to review the page

Description: some comment that the user enters in the dialog

Review Link: http://www.maqetta.org... (and this should be live)

@jmockler @JonFerraiolo @EldonReturn
 Review and Commenting Review - May 12, 2011

**Comment by EldonReturn** [comment]
Fixed. Added a template file so that the admin can configure it.
