### ISSUE TITLE
Review and Commenting review requests do not open a default document to begin a review

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#439]
Problem: When a user clicks on a review request URL - it opens the Review and Commenting application, and a document is not opened in the content area. Which is a bit confusing. 

Solution: It would help a reviewer to comment on a set of documents if a default first page was set to open when anyone clicked on a review. So a solution may be to allow the Person who sent the review request to select which page to open up in the review and commenting mode when the define which files are in the Review.

@jmockler @JonFerraiolo @EldonReturn
 Review and Commenting Review - May 12, 2011

**Comment by JonFerraiolo** [comment]
@childsb fixed this. closing
