### ISSUE TITLE
Type to filter field should span the width of the view

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#441]
Currently the Type to filter field is ~3/4 the width of the view.  It should span the full width of a view, and dynamically resize based on the users interaction.

http://img.skitch.com/20110527-r6hcrrw3b3dbwuuidqqaggeaus.png

@jmockler @JonFerraiolo @EldonReturn
 Review and Commenting Review - May 26, 2011

**Comment by JonFerraiolo** [comment]
Closing - this was fixed during widget palette cleanup during M8
