### ISSUE TITLE
Icons in the Review toolbar for the review author

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#443]
Icons in the author toolbar.. should be larger and more tactile.. currently they are combined with the 'Review' metaphor, which is repeated, and are often overlooked. The hover help also needs to be refined.

The actions & hover help should align with the states of a review:
1. STOP a review (red stop control)
2. Pause a review (yellow pause control)
3. Resume a review (green arrow with a yellow bar to the left)
4. Edit a review (a pencil)

@jmockler @JonFerraiolo @EldonReturn
 Review and Commenting Review - May 26, 2011

**Comment by EldonReturn** [comment]
Fixed
