### ISSUE TITLE
Need to show the status of a Review

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#444]
Problem: there isn't an obvious way currently that shows 'status' of a review in the Review and Commenting view.

Solution: create icons for the icons in the tree with 4 states as overlays.. 

The states are
1. Review is in Draft state
2. Review is Stopped
3. Review is Active
4. Review is Paused

Please work with Flan (don't know his ID) to do the following
1. Confirm the interaction 
2. Design the icons

@jmockler @JonFerraiolo @EldonReturn
 Review and Commenting Review - May 26, 2011

**Comment by EldonReturn** [comment]
Fixed
