### ISSUE TITLE
Comments view of the review and commenting

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#445]
When setting the Type and Severity.. the horizontal text jumps.. 

I would propose Right align the Severity under the comment.

@jmockler @JonFerraiolo @EldonReturn @dfliang
 Review and Commenting Review - May 26, 2011

**Comment by JonFerraiolo** [comment]
Possibly implementation solutions: HTML table (with 2nd column text-align:right) or float:right on the SPAN surrounding the Severity controls.

**Comment by EldonReturn** [comment]
Fixed. https://github.com/maqetta/maqetta/commit/174befaa49671e7c443caf834a8fab05a988f150
