### ISSUE TITLE
Download workspace as ZIP exception if changing location of Dojo

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#450]
I thought this was working at one time.
- Start Maqetta fresh (or refresh browser window with Maqetta application in it)
- In files palette, click on first icon (download entire workspace)
- Change /lib/dojo to /dojo and click OK
  Result=> Exception shows in console:

Uncaught ReferenceError: foundImport is not defined
dojo.forEach.srcdavinci.js:24743
dojo.mixin.forEachdojo.js:859
dojo.declare.loadRequiresdavinci.js:24722
dojo.declare.rebuildSourcedavinci.js:24604
dojo.declare._rewriteUrlsdavinci.js:24851
dojo.declare.okButtondavinci.js:24864
dojo.hitchdojo.js:726
dojo._listener.getDispatcherdojo.js:1311
dojo.declare._onClickdavinci-common.js:2615
dojo.declare._onButtonClickdavinci-common.js:2617
dojo.hitch

**Comment by childsb** [comment]
Fixed with commit  4ff1a286b1a2e7e072d4

**Comment by JonFerraiolo** [comment]
Reopening. The exception did go away, but the download ZIP doesn't put dojo in the correct location. In the download-everything dialog, I asked for Dojo to go into the "dojo" folder rather than "lib/dojo". When I looked at the ZIP, dojo was still at "lib/dojo", not "dojo" as I had requested.

**Comment by childsb** [comment]
Fixed with this checkin: e7fdd3f914bd72d7787
