### ISSUE TITLE
Need icons for new dojox.mobile widgets

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#457]
@jmockler @JonFerraiolo

Need new icons for the new dojox.mobile widgets introduced in Dojo 1.7.  See #372 for more info and list of new widgets.

**Comment by jhpedemonte** [comment]
See https://docs.google.com/document/pub?id=1lzdeIsZBMyU18t-Z4L8z6fqGkgJPnP9Aa29RZflYV9E&pli=1 for images of documented dojox.mobile widgets.  Most of them are hold overs from Dojo 1.5, but there are some new ones:
- RoundRectDataList (use RoundRectList icon?)
- EdgeToEdgeDataList (use EdgeToEdgeList icon?)
- SpinWheel
- SpinWheelSlot
- SpinWheelDatePicker
- SpinWheelTimePicker

**Comment by jhpedemonte** [comment]
Here are some screenshots for the form controls: http://imgur.com/a/93JGv

New widgets in Dojo 1.7 (since Dojo 1.5):
- CheckBox
- ToggleButton (toggable button with checkmark)
- RadioButton
- Slider
- ComboBox
- TextArea
- ExpandingTextArea
- TextBox

Some of these are pretty common widget types, and we can just reuse the icons for the Dijit equivalents.

**Comment by jhpedemonte** [comment]
Remaining new widgets:
- Carousel
  - Side-scrollable list
  - See example here: http://archive.dojotoolkit.org/nightly/dojotoolkit/dojox/mobile/tests/test_Carousel.html
- ContentPane
  - A very simple content pane to embed an HTML fragment.
  - No UI, just a container.
- FixedSplitter
  - Another container without its own UI, which splits page.
  - See example here: http://archive.dojotoolkit.org/nightly/dojotoolkit/dojox/mobile/tests/test_FixedSplitter-H2.html
- FixedSplitterPane
  - Above FixedSplitter may contain pure HTML DIVs or FixedSplitterPanes
  - Again, no UI of its own.
- Overlay
  - A non-templated widget that animates up from the bottom, overlaying the current content
  - See example here: http://archive.dojotoolkit.org/nightly/dojotoolkit/dojox/mobile/tests/test_Overlay.html

**Comment by jmockler** [comment]
Will start processing these with @jinsil

@jhpedemonte - for widgets that have changed a bit - not a huge amount in dojo 1.7 from 1.5, I would do as you'd suggested and reuse existing icons

**Comment by jhpedemonte** [comment]
@jmockler - Added the icons you sent me and reused existing icons for similar mobile widgets.  But have some questions:
- **dojox.mobile.Slider** - For now, I'm reusing the icon from **dijit.form.HorizontalSlider**. One difference between the two widgets is that HorizontalSlider has a pointy grippy, whereas mobile's Slider has a circular grippy.  Should we get a specific icon for this one?
- **dojox.mobile.ToggleButton** - Didn't get an icon for this widget.  It's a button with a togglable checkmark on the left. You can see it in action here: http://archive.dojotoolkit.org/nightly/dojotoolkit/dojox/mobile/tests/test_FormControls.html
- **dojox.mobile.ExpandingTextArea** - Don't have a specific icon for this one; just using the icon for **TextArea**.  Should this one have a specific icon?  This widget is a textarea that dynamically and automatically grows as new lines are written.

**Comment by jmockler** [comment]
1. dojox.mobile.Slider - a new icon would likely be better
2. dojox.mobile.ToggleButton - I'll create one and send it to you
3. dojox.mobile.ExpandingTextArea - I think you can re-use the TextArea icon.
