### ISSUE TITLE
Calendar broken in dojo17

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#458]
on the dojo17 branch, drop a Calendar on the canvas and this.value is null

**Comment by waynevicknair** [comment]
I encountered this today testing in Safari 5.0.5.

**Comment by peller** [comment]
the problem is in Dijit, but only seems to affect us because we do unusual things like round trip properties without changing their values.  The default value of CalendarLite, by design, is an invalid Date (NaN)

http://bugs.dojotoolkit.org/ticket/13362
