### ISSUE TITLE
How to handle dojox.mobile.View - only one visible at a time

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#459]
The dojox.mobile widgets all work within a `dojox.mobile.View` (or subclass).  Only one `View` is visible at a time, denoted by the `selected` property.

The question is how should we handle this in Maqetta?  There are two separate issues.

First, how do we handle the `selected` property of `View`?  Ideally, when a `View` is dropped on the page and there isn't an existing `View`, then `selected` should automatically be set to `true`.  Otherwise, we stick with the default, which is `false`.

If there are multiple `View`s, and a user clicks on `selected` in **Properties->Widget-specific**, then Maqetta should set `selected` to `false` for the previously selected `View`.

Second, how will a user select between different Views?  Since one will have `selected` set to `true`, this will be the `View` that is shown by default -- the others will be invisible until they are selected through some action.  But we need to provide some facility to allow the user to switch between the different Views on the page and add content to each, without changing the `selected` properties.

@JonFerraiolo @peller

**Comment by jhpedemonte** [comment]
Re: first issue - handling `selected` property

I had previously stated that perhaps we could use States for this, but I think that would overload the intent of States and we should therefore stay away from that.

I think this can be handled by some of the proposed APIs in https://github.com/maqetta/maqetta/wiki/JS-Library-API.  In particular, `onAdd()`.  That callback would provide the type of widget being added to the page.  We can check if it is a `dojox.mobile.View` widget (or inherits from it) and if so take appropriate action.  In particular, we would need a way to query the `Context` to see if there are any other widgets of that type and if not, set `selected` to `true` for the widget being added.

We can also use `onPropertyChange` to see if `selected` is getting changed on a `dojox.mobile.View` and if so, take action.  If it is being set to `true`, then we'll need to set `selected = false` for the currently selected View.  If it is getting set to `false`, we might need to bring up a dialog telling the user that at least one `View` must be selected.

**Comment by jhpedemonte** [comment]
Re: second issue - allowing user to switch between Views

This one is a bit more complex.  My current thinking is to add another toolbar across the top of the VE that shows UI representations of the Views currently on the page.  This would allow the user to select between the Views in order to edit them.  It would also allow the user to rearrange them (actually, I don't think it matters in the case of Views what order they are in, but it might be a useful feature for some other widget type).

This would require adding some sort of API (https://github.com/maqetta/maqetta/wiki/JS-Library-API) that the library code could use to instantiate and fill this new toolbar.

Thoughts?

**Comment by JonFerraiolo** [comment]
My first reaction is that this is a lot like the overlay widgets that Adam is working on, and the obvious conclusion is that, like what Adam is doing for the overlay widgets, the mobile views need to be integrated with our states feature. However, that's a 5000ft comment. Devils in the details.

**Comment by jhpedemonte** [comment]
Like I said, I had initially thought of integrating this with States.  But I don't want to overload what States do.  I see that functionality as an easier way to specify user actions.  If we were to integrate View selection with States, now States isn't just handling those user actions.

For example, we could use the eyeballs to allow the user to switch between visible views.  But there is no other corresponding state in the States palette.  And what if a user becomes confused and thinks that he/she needs to create a separate state for each View that is added to the page?

**Comment by JonFerraiolo** [comment]
This is likely the same question we have with Adam's overlay widgets. We have the same dilemma there. Initially, we thought this should be integrated with states, then I thought more about it and said no, don't overload states, but then going even deeper, we decided again that we should integrate with states, and now that Adam is 80% done, I'm feeling states are still the way to go but Adam is having doubts.

One of the main reasons for leveraging states is that when you have things which only appear some of the time, an author will need a way to tell Maqetta to allow authoring into Thingee 1 instead of Thingee 2, and what do we provide to let a user switch thingees? A Thingee palette? Then we have palette explosion, where we have a States palette for user-defined states, a Mobile Views palette for the View elements in dojox.mobile, a Dialogs palette for all dialogs in the page, a Tooltips palette, a Menus palette, etc.

**Comment by JonFerraiolo** [comment]
Closing this. With a bunch of commits submitted in and about the same time, including with this one (5fd726f21a42e85c6258), I added code that ensures that only one View is visible at a time in the page editor.
