### ISSUE TITLE
Auto-add data store when dropping RoundRectDataList/EdgeToEdgeDataList?

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#461]
Dojo 1.7 adds two new widgets, `RoundRectDataList` and `EdgeToEdgeDataList`, which work with data stores.  By default, should we also add a data store to the page when dropping either of these widgets?  Or should we extend `SmartInput` to allow user to select from a list of data stores?

@JonFerraiolo @peller @billreed63

**Comment by JonFerraiolo** [comment]
I haven't looked at those widgets, but I would guess that we will want the same flexibility for those widgets as we provide for various dijit widgets, where we provide a SmartInput option for users to type in dummy data. As MVC roles out, we want all widgets to be to support data binding and all data binding to go through MVC. But that's long-term, with Dojo 1.8 being when MVC is available on a mostly universal basis in Dijit.

**Comment by JonFerraiolo** [comment]
I reassigned this to Bill - he's up to his ears now with similar data-binding issues with the mobile combobox. The hope is that the same mechanisms for combobox can apply to RoundRectDataList and EdgeToEdgeDataList. But if Javier wants this bug back, I'm sure Bill will be OK with that.

**Comment by billreed63** [comment]
EdgeToEdgeDataList and RoundRecDataList appear to have a different implementation of DataStores than DataGrid or Tree. 
With DataGrid we could create the ItemFileReadStore and the DataGrid using a declarative approach. We would assign the data store an ID and then use that id as a parameter to the data grid. 

EdgeToEdgeDataList and RoundRecDataList do not support this, from what I can determine they seem to require that the data store be created with JavaScript and that the data store object be passed to the EdgeToEdgeDataList.

``` html
<script language="JavaScript" type="text/javascript">
    var store = new dojo.data.ItemFileWriteStore({url: "settings.json", clearOnClose: true});
</script>

<ul dojoType="dojox.mobile.RoundRectDataList" id="list" store="store" query="{label: '*'}"></ul>
```

I would think this is part of the MVC approach of separating data from view, but it makes the ItemFileReadStore part of a script tag and not a dijitWidget in the model.

Any thoughts?

**Comment by jhpedemonte** [comment]
I don't see why there would be a difference.  As far as I know, you should be able to declaratively create a store, assign it a **jsId**, and then reference that jsId in the **store** attribute for *DataList.

What error did you see when trying that?

**Comment by jhpedemonte** [comment]
I was able to modify **dojox/mobile/tests/test_EdgeToEdgeDataList.html** to specify the ItemFileWriteStore declaratively.  Of course, the data used by the store is still defined in JS, so not sure how much that gets us.

**Comment by billreed63** [comment]
It was my bug, I was missing a parm

**Comment by billreed63** [comment]
EdgeToEdgeDataList with smart input is complete, user can enter list labels in the format:
    Label 1, page_to_move_to
    Label 2, page_to_move_to

The page to move to is optional.

Or the user can choice a json file from the work space, I have provided an example json file sample_data/mobile_edge_to_edge_data_list.json

**Comment by billreed63** [comment]
added RoundRecDataList and renamed sample file as it can be used for both RoundRec and EdgeToEdge.

July 2011
