### ISSUE TITLE
Firefox mobile previews misaligned by a few pixels relative to silhouette

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#465]
On Chrome and Safari, mobile previews are perfectly aligned within the various mobile device silhouettes, but in Firefox4, the iframe is shifted a few pixels to the left and top relative to the mobile silhouette. I'm pretty sure the bug is in FF not in Maqetta, but we'll probably have to create a workaround somehow until FF fixes the bug.

**Comment by jhpedemonte** [comment]
What about FF 5?  What kind of workaround?
