### ISSUE TITLE
Progress indication when first logging into maqetta is awkward

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#474]
1. Hide the loading application with a 100% opaque white overlay, while the application loads
2. In the center of the screen show the animating circular dojo GIF to help users know that the loading process has not frozen on them
3. Beside the loading animating GIF, show the words 'Loading Maqetta...' in hex 666666 to help the user know exactly what is happening

Note: do not use the same sequence for when the application is already loaded and the user has opened a file. Instead.. 
1. Open the file, with the content overlaid with a white opaque screen, and at the top of the screen show a 'Loading page...' indicator.
2. Do not use an overlay across the entire application in this case
3. Do not jitter or adjust the layout or content of the various views unless the contents of the views were expanded from the previous application layout.

Links to design specs for Application loading and individual document loading: http://img.skitch.com/20110617-b69hwagbw362j6fwqgdu1dgt9k.png

Blueprints for 'Loading text': http://img.skitch.com/20110617-gmyes18tb4xa6cp3sq3mpetbx9.png

Based on discussion with @jmockler @JonFerraiolo @jhpedemonte @peller 
UI Review - Jun 10, 2011
Using Firefox 4.0

**Comment by jhpedemonte** [comment]
Similar to #87, but more encompassing.

**Comment by billreed63** [comment]
I changed the overlays as describe, they are visible in FF 5, but chrome does not show them do to the nature of the performance  improvements in chrome. Chrome does not redraw the canvas until our code gives up control, as a result we do not see the overlays unless debugging and installing break points. The real solution to this is to force out code to give up control by using async requests to the server.

Fixing the "jetter" is more involved, we need to add overlays <div> over each object that "jetters" like widget palette an cover the palette while it is constructed. Although I have not spent time investigation this problem in detail. I am creating issue #498 just for "jitter"  for the next milestone

**Comment by JonFerraiolo** [comment]
I can certainly understand that fixing the jittering is a more involved (and risky) feature, so it makes sense to split that off into a separate bug and push to the next milestone. But I'm scratching my head a bit on the loading DIV not showing in Chrome. I would expect that adding a DIV would cause an immediate redraw event in the browser, but it sounds like Chrome is batching redraw events. Is that correct? If so, maybe there is a hacky way to force the browser to do an immediate redraw. The scriptaculous folks mention a couple of things that might help in this case, such as

http://mir.aculo.us/2009/09/25/force-redraw-dom-technique-for-webkit-based-browsers/

http://mir.aculo.us/2009/01/11/little-javascript-hints-episode-3-force-redraw/

I see a defer() call in the second example, and I'm not sure what that does exactly. (setTimeout?) But setting the transform to scale(1) (identity scale transformation) in the first link above seems worth a try, but I would try this code instead:

var style=myelement.style;
style.transform=style.WebkitTransform=style.MozTransform=style.msTransform="scale(1)";

**Comment by billreed63** [comment]
We could add setTimeout's for example we would need to put the context.setContent inside the timeout  Chrome would draw the loading div, but I fear that by doing this we change the timing of all the code that follows setContent. 

Option 1 from above has no effect, I would assume that we have not paused in the code execution allowing chrome to redraw.

Option 2 (defer() ) sounds like it would be similar to async'ing  and could disrupt timing.

**Comment by jmockler** [comment]
Just added specification document links to the description above for loading the application and loading a document.
