### ISSUE TITLE
Support CSS files in localization bundles

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#476]
We should allow localization bundles to provide CSS files that can override the main CSS rules.  This could come in handy, for example, if a language is verbose and would need to increase the size of a dialog, in order to make the text fit properly.

@peller @cindyskach

**Comment by peller** [comment]
flow layout is always better...   we've managed to avoid this sort of approach in dijit

**Comment by jhpedemonte** [comment]
Perhaps.  But that only handles the example I described above.  There may be other use cases.

**Comment by peller** [comment]
name 'em,

**Comment by jhpedemonte** [comment]
Well, off the top of my head:
- BIDI (although, not sure how that's handled by Dojo)
- colors - In some cultures, certain colors (particularly red) can have a strong negative reaction and should therefore be avoided.

**Comment by jhpedemonte** [comment]
You know, this may be getting too esoteric.  It was always a low priority issue, but probably best to just close this and come back to it if necessary.

**Comment by peller** [comment]
Agreed.  I know, we always had this requirement in the back of our heads at Dojo, but were able to avoid it with careful design.  Flow layout almost always solved size problems (BiDi poses no special size constraints) and neutral designs for colors, pictures, etc.
