### ISSUE TITLE
Master tooltip appears at end of Outline palette

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#478]
With latest code, when I run through the tutorial, an extra widget appears at the bottom of the Outline palette, with a widget name of _MasterTooltip. I don't see anything in source view, though.

Assigning to Adam because I see tooltip in there. If it's not a side effect of work on the tooltip widget, maybe it's a side effect of Dojo 1.7.

**Comment by peller** [comment]
I wonder if this goes back to 1.6?  Possibly related to fce5c9181fe17b08feebb06f0ef5dbbf5aedd7a2
