### ISSUE TITLE
Source pane in split view comes up blank on Mac Chrome

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#479]
At least for me in Mac/Chrome, with latest code, when I go into split view, I'm getting a blank area where the source code should be. If I jiggle a splitter, the source code appears.

**Comment by peller** [comment]
dup of #423, which I thought I just fixed?  Still works for me

**Comment by JonFerraiolo** [comment]
I've been pulling the latest code from master and I'm seeing this problem when I launch from Eclipse and use Mac/Chrome.

**Comment by jhpedemonte** [comment]
I am also seeing this issue.

**Comment by peller** [comment]
closing as dup of #423
