### ISSUE TITLE
Include a SampleData.json file in samples

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#489]
@billreed63, @jhpedemonte, @peller

With the new feature in DataGrid where a user can pull in data from a file in his workspace, we really should have an existing data file for us to use, at least for demos. Even though this would make the default workspace bigger, I think this makes sense. What I propose is copying countries.json from Dojo and renaming it SampleData.json at the root of the workspace.

I'll hold off on making this trivial change to see if anyone wants to post feedback on this.

**Comment by billreed63** [comment]
I already added a sample_data folder to the workspace that has a sample.json file
It does not have country data but I could change that

Closed 2011

**Comment by jhpedemonte** [comment]
How will this affect existing users?  They won't get this new file, unless we do some server copying, or something of the sort.

**Comment by JonFerraiolo** [comment]
@waynevicknair

good point! My first thought is to auto-add the sample data folder into existing workspaces. It does highlight a more general long-term issue about how we should handle samples. I've been thinking we should put all of the sample files into a single samples/ folder. Then we could make that read-only and then it would automatically update with new releases, just like libs/ and themes/
