### ISSUE TITLE
Smart input causes user's page to disappear until clicking OK

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#490]
@peller, @jhpedemonte

Not sure when this problem first started to manifest itself, but I'm pretty sure this is a recently introduced problem. I'm seeing this on Mac/Chrome and Mac/FF4.

To reproduce:
- Relaunch Maqetta
- New HTML file
- Add a Button

Result=> Smart Input appears just fine, but underlying page (with the Button on it) goes white until Smart Input goes away.

**Comment by billreed63** [comment]
smart input was using the same css class as loading, now that loading is solid white smart input needs it's own css class

**Comment by billreed63** [comment]
Closed June 2011
