### ISSUE TITLE
SaveAs on JavaScript and CSS files not working

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#492]
@jhpedemonte, @peller
- Double click on Sample1.js to open in source editor
- Click on SaveAs icon, and then set filename to 'file1.js'
- Click "Save" button

Result=> Sample1.js editor goes away (which is fine). file1.js editor appears, but with empty content.

Note that if you made modifications to Sample1.js before doing SaveAs, the changes are saved back to Sample1.js (which is wrong).

Same problem with CSS files. It's not a new bug. This has been broken probably forever.

**Comment by waynevicknair** [comment]
fixed with commit cf846c3f687d40e54a8086f0469f34ef732ae642
