### ISSUE TITLE
Download selected files only downloading first selected file

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#493]
To reproduce:
- In Files palette, select Sample1.html and app.css
- Click on 2nd icon in Files palette toolbar (download selected files)

Result=> Dialog comes up but only shows Sample1.html and doesn't show app.css. Furthermore, if you proceed with the download, only one of the selected files is in the ZIP

**Comment by childsb** [comment]
Fixed with commit commit 1ab21171f857fc0e1d52608f60cf8b7ab5bc71a3
