### ISSUE TITLE
Modify libraries lib/dojo/=>dojo/ results in dojo not defined

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#494]
To reproduce:
- Click on 3rd icon in Files palette toolbar
- Change Dojo's path from lib/dojo to dojo
- Open Sample1.html

Result: No widgets show for Sample1.html and console shows 'dojo is not defined'

**Comment by childsb** [comment]
fixed with 4ff1a286b1a2e7e072d48e0446cbdd603007d857
