### ISSUE TITLE
Create New HTML file throws exceptions

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#500]
1) New -> HTML File 
2) File1.html (or any file name)
in the console log I see..

Content Dojo version: 1.5.0 (22487)
app/dojo/./_base/connect.js:27Uncaught TypeError: Object [object DOMWindow] has no method 'apply'
app/dojo/../davinci/Workbench.js:1410Error while autosaving file:TypeError: Object [object DOMWindow] has no method 'apply'

**Comment by JonFerraiolo** [comment]
Not sure which check-in fixed this, but I'm no longer seeing this either after pulling latest GitHub sources and I'm not seeing this with the auto-build posted today at http://maqetta.org/nightly
