### ISSUE TITLE
Explorer view no longer using Tree filters to sort items.

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#503]
After Adams switch to the dojo Tree widget, the Explorer view no longer sorts entries.

There are filter/sort classes in davinci.resource that were used previously.  Looking through the tree code, I dont see a filtering mechanism being used.

@peller

**Comment by jhpedemonte** [comment]
What's the status on this one?  Have @peller or @childsb taken a look at this yet?

@JonFerraiolo

**Comment by peller** [comment]
Is this a must have for M2?  I thought Jon said it could wait?  It does seem that we'd have to put back some subclass or monkey patch to achieve this.  I was going to look at whether monkey patching the change to dijit.Tree was possible.

**Comment by JonFerraiolo** [comment]
This is a must have for M2.
