### ISSUE TITLE
Explorer View - Missing Read Only decoration

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#504]
Missing the read X decoration for read only resources in the Explorer view.

I believed this was wiped out when Adam changed from davinci.tree to dijit.tree.  I had a custom DIV in the previous tree widget for the decoration.

@peller

**Comment by peller** [comment]
Used the dijit.Tree override to set a class on the row, rather than the image, for readOnly items.  This should allow more flexibility for applying styles.  For now, I just made the text of the node italic, which probably isn't ideal.

**Comment by peller** [comment]
style taken out by @JonFerraiolo in 7897ba6fce8dd9fb720c3fad87cd624bd464d9cf but class and logic remain

**Comment by JonFerraiolo** [comment]
Isn't @childsb actively working on this? We chatted today about using opacity:.5 on both the icon and text.

**Comment by peller** [comment]
he is.  we were trying to track down the latest changes to figure out what code was in place.  using opacity:0.5 should be easy.
