### ISSUE TITLE
Mobile tutorial(s)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#506]
@jhpedemonte

We need one or more mobile tutorials

**Comment by jhpedemonte** [comment]
Documents from which to draw inspiration:
- [Mobile Gallery](http://chrism.dojotoolkit.org/mobile-0.2/make_samples/dojo-samples/demos/mobile-gallery/demo.html)
- [Dojox Mobile Docs](http://docs.dojocampus.org/dojox/mobile) from DojoCampus (with examples)
- [Dojox Mobile Tests](http://archive.dojotoolkit.org/nightly/dojotoolkit/dojox/mobile/tests/index.html)
- [Dojo Docs](http://dojotoolkit.org/documentation/) has a set of tutorials on creating a **TweetView** mobile app
