### ISSUE TITLE
Dropping non-Dojo widget into _Container descendant throws error

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#514]
To test (using dojox.mobile widgets):
- Drop `View`.
- Drop `RoundRect` inside of `View`.
- Drop HTML `label` inside of `RoundRect`.

This will throw an error in `_Container.addChild()`.  The problem is this code in **davinci/ve/widget.js** (~ line 1524):

``` javascript
    addChild: function(child,index)
    {
        if(this.dijitWidget.addChild){
            if(index === undefined || index === -1){
                index = "last";
                this._srcElement.addChild(child._srcElement);
            }else {
                var children = this.getChildren();
                if(index < children.length){
                    this._srcElement.insertBefore(child._srcElement,children[index]._srcElement);
                }else{
                    this._srcElement.addChild(child._srcElement);
                }
                if(index === 0){
                    index = "first";
                }
            }
            this.dijitWidget.addChild(child.dijitWidget, index);
            return;
        }
        this.inherited(arguments);
    },
```

Specifically the 3rd line of code from the bottom, which references `child.dijitWidget`.  That value will be `null` for anything other than a Dijit widget.

@JonFerraiolo @peller

**Comment by jhpedemonte** [comment]
The description of `_Container.addChild()` says that it only takes objects of type `dijit._Widget`.  So I guess we should only call `addChild()` if the incoming widget is of that type? @peller, have any experience here?

**Comment by jhpedemonte** [comment]
Another thing to keep track of with the test scenario above: whatever solution we use, need to make sure that `label` is displayed as a child of `RoundRect` in the **Outline** view.

**Comment by peller** [comment]
sorry for the late response on this... yes, the addChild API on Dijit as well as the _Container object assume all children are Dijits.

**Comment by JonFerraiolo** [comment]
Reassigning to Javier after I did a detailed code analysis. I concluded that this bug is highly intertwined with #224.

**Comment by jhpedemonte** [comment]
Not related to #224.

As you can see by the source of http://archive.dojotoolkit.org/nightly/dojotoolkit/dojox/mobile/tests/test_iPhone-Switch.html, there isn't any issue with **RoundRect** taking simple HTML (non-Dijit/Dojox) children (the example shows several RoundRect widgets with `<span>` elements).

Rather, the issue (I think) is that the `addChild()` code I referenced in the summary above expects that `child` is a Dijit widget.  Need to update that function to work with non-Dijit `child` widgets.

@peller, does that sound correct?  Is there any particular trick to adding generic DOM children to a Dijit widget?  Any `addChild()` equivalent?

**Comment by peller** [comment]
So there are a whole class of widgets which will accept or tolerate HTML in portions of their DOM, like buttons or menus, which aren't explicitly 'containers' in the Dijit sense (an addChild/setContent sort of API)  I'm not sure there's any standard convention for those.

**Comment by JonFerraiolo** [comment]
I'm pretty sure we handle whether widgets accept HTML in the "content" (e.g., markup inside of a button label) via the inline edit metadata. If certain flags are set, then if inline edit senses a markup character (e.g., less-than character), then the radio buttons appear in the inline edit tooltip asking user whether the content should be treated as HTML markup or plain text. If plain text, then we uses entities (e.g., &lt;) for the markup characters.

**Comment by jhpedemonte** [comment]
From email from Jon:

> But the addChild() logic within the davinci.ve._Widget base class not only is in violation of OO principles, it also prevents RoundRect from accepting HTML children. I haven't looked deeply enough at the code, but maybe we can replace the addChild() checks with allowedChildren checks somehow.

**Comment by jhpedemonte** [comment]
Previous 2 commits fix this particular issue, but **Label** still doesn't show up in **Outline** view.  I think this is related to `getChildren()` call in **widget.js**, which has a check for `this.acceptsHTMLChildren`.  This is falsy for **RoundRectList**, so code doesn't see Label as a child.

Quick fix might be to replace check for `acceptsHTMLChildren` with:

``` javascript
allowedChild === 'ANY' || 'HTML' in allowedChild
```

However, the code for `davinci.ve.DijitWidget.getChildren()` may be wrong as is.  After all, shouldn't we always iterate over a widget's child DOM nodes, looking for one with the `_dvWidget` property?  Why resort to the Dijit specific function here?

But that discussion may have to wait for M3.

**Comment by JonFerraiolo** [comment]
IMO, at some point (maybe right away) we should replace all use of acceptsHTMLChildren with allowedChildren (or whatever it is called), or at least set acceptsHTMLChildren from allowedChildren rather than looking for a particular Dijit private function (_setContentAttr).

**Comment by jhpedemonte** [comment]
Yes, that's what I was working on yesterday.  Will probably commit another patch this morning.

**Comment by jhpedemonte** [comment]
With latest checkin, any Dijit with `allowedChild` set to `'ANY'` (default) or that includes `'HTML'` will accept HTML children.

**Comment by jhpedemonte** [comment]
Seems to be working well in limited testing.  Closing.  Open any issues as new bugs.
