### ISSUE TITLE
Fully test use of dojox.mobile.IconContainer and IconItem

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#517]
User should be able to drop an `IconContainer` and start adding `IconItem`s.  Also should be able to upload custom images to workspace and use those images in these two widgets.

@JonFerraiolo

**Comment by jhpedemonte** [comment]
Jon's comment:

> I was able to drag/drop this onto canvas, but there isn't a prompt to pick an image like we have for the IMG element. Maybe this widget doesn't point directly to a widget and instead points to a CSS class. There are about 12 widget-specific options, including icon, iconPos, href, hrefTarget and url - which one of these would cause an icon to appear inside of the rectangle on the page editor canvas?

Answering to one of the questions above: the 'icon' property holds a plain URL (unlike a CSS property, where the URL has to be specified inside of a url(...) construct).

**Comment by JonFerraiolo** [comment]
The 'icon' property does indeed work. Should we close this bug and create a different bug for M3 to have smart input prompt for an image file name?

**Comment by jhpedemonte** [comment]
Spun off smart input issue to #775.
