### ISSUE TITLE
Define inline-edit for dojox.mobile widgets

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#519]
Need to define the inline-edit for some **dojox.mobile** widgets:
- SpinWheelSlot
  - Can be either a range of numbers (using properties `labelFrom` and `labelTo`) or an array of strings (i.e. `['A', 'B', 'C']`)
- ComboBox
  - Use same or similar inline-edit as `dijit.form.ComboBox`?
- ExpandingTextArea
- TextArea
- TextBox

@billreed63

**Comment by jhpedemonte** [comment]
This has docs on `SpinWheel` and related widgets: https://docs.google.com/document/pub?id=1lzdeIsZBMyU18t-Z4L8z6fqGkgJPnP9Aa29RZflYV9E#h.ayvrhdms4pdv

The others are very similar to Dijit widgets.  But if you need help, probably best to take a look at the tests: http://archive.dojotoolkit.org/nightly/dojotoolkit/dojox/mobile/tests/index.html.  In particular, the **test_FormControls.html**.

**Comment by billreed63** [comment]
mobile.ComboBox is a different beast from form.ComboBox it uses a DataList to get options.

```

    <!DOCTYPE html>
    <html>
    <head>
    <title>Untitled</title>
    <style type="text/css">
    @import "themes/claro/claro.css";
    @import "app.css";
    @import "./lib/dojo/dojo/resources/dojo.css";
    @import "./lib/dojo/dojox/mobile/themes/iphone/iphone.css";
    </style>
    <script type="text/javascript" djConfig="parseOnLoad: true" src="./lib/dojo/dojo/dojo.js"></script>
    <script type="text/javascript">
    dojo.require('dijit.form.DataList');
    dojo.require('dojox.mobile');
    dojo.require('dojox.mobile.parser');
    dojo.requireIf(!dojo.isWebKit, 'dojox.mobile.compat');
    dojo.require('dojox.mobile.ComboBox');
    dojo.require('dojox.mobile.TextArea');</script>
    <script src="maqetta/States.js"></script>
    <script src="maqetta/maqetta.js"></script>
    </head>
    <body class="claro lotusui" dvFlowLayout="true" data-davinci-ws="collapse" id="myapp">

      <div dojoType="dojox.mobile.View">
      <textarea dojoType="dojox.mobile.TextArea"></textarea>
      <select dojoType="dijit.form.DataList" data-dojo-props="id:&quot;items&quot;">
          <option dvwidget="html.option" value="Item 1">
                   Item 1</option>
           <option value="Item 2">
           Item 2</option>
         <option value="Item 3">
          Item 3</option>
     </select>


     <input id="mobile_mine" data-dojo-type="dojox.mobile.ComboBox" data-dojo-props="value:&quot;Item 1&quot;,   list:&quot;items&quot;">
    </input>
      </div>
     </body>
    </html>

```

**Comment by billreed63** [comment]
ComboBox, ExpandingTextArea, TextArea, TextBox are done.

**Comment by jhpedemonte** [comment]
Setting to **Priority Low**, since all that is left is **SpinWheelSlot**, and there are other issues around that widget.  This may actually slip in to M3.

**Comment by billreed63** [comment]
creating seperate issue for SpinWheelSlot. #730

July 2011
