### ISSUE TITLE
How to handle inline-edit for RoundRectList & EdgeToEdgeList

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#523]
@billreed63 @JonFerraiolo

**dojox.mobile** defines two list types (`RoundRectList` and `EdgeToEdgeList`) which take (as children) another widget, `ListItem`.

Currently, I've only set both list types to default to having 2 items each when a user drops one of the list widgets on the page.  But only the `ListItem` widgets have inline-edit.

Jon was saying that this is inconsistent with other Dijit widgets, where double-clicking inside a list-type would bring up inline-edit for the whole list, not the individual items.

I pointed out that this is a bit different, since we do have another widget (`ListItem`) which the user can drop into the list in order to add more.  It's a bit more work, but gets the job done.

But I guess I can see Jon's point: doing the inline-edit on the full list would allow the user to add/remove `ListItem` widgets as well as editing the text content of the `ListItem`s.

Bill, does that seem correct to you?

**Comment by jhpedemonte** [comment]
I'm still leaning towards keeping this as is and not having an inline edit for the List widgets.

For one thing, the individual widgets here (**ListItem**) are much different than in order sort of list widgets (i.e. `<option>` elements in `ComboBox`).  There's a lot more to them than just the label, which is all we could change in adding inline edit to RoundRectList/EdgeToEdgeList.

Especially when you consider ListItems as navigation UI -- we can't define the extra features of ListItem in a simple format for inline edit.  Plus, if the user does edit some additional properties and later invokes the inline edit, the previous properties will probably get overwritten, unless we add some sort of checking code, which would be straight-forward.

I think we should just keep this as is.  Bill or Jon, care to comment?

**Comment by JonFerraiolo** [comment]
I'm strongly in favor of inline edit for these two *List widgets. Also, *DataList. 'm not seeing why RoundRectList and EdgeToEdgeList is any different than ComboBox, either from the point of view of the user or the point of view from a Maqetta core code developer, especially given that we are offering inline edit on all sorts of other similar container widgets. Just from a consistency perspective, users will expect it.

It is a huge productivity boost to be able to say:

```
aaa
bbb
ccc
ddd
```

versus adding a RoundRectList, double-clicking to edit text on first item, double-click to edit text on second item, drag/drop a 3rd, and drag/drop a 4th. When I created the tutorial, I found it really frustrating having to go through this monkey business. The usual order of operation is create an initial list and then customize each list item, such as setting 'moveTo' property.

The one bit of trickiness that we really should do is attempt to preserve any customizations that a user made to ListItems if double-clicking on the container to do inline edit, versus wiping them out after inline edit. @billreed63 do we do this sort of preservation for other widgets, such as ComboBox?

**Comment by JonFerraiolo** [comment]
Note: if this is difficult or risky or we just plain run out of time, OK to postpone inline edit on the container widgets until M3.

**Comment by jhpedemonte** [comment]
This is different than a ComboBox, in that the user can select the individual widgets in a RoundRectList, but cannot do so in a ComboBox.

How is inline edit going to work for these *List widgets?  There is no UI that belongs to the List widget -- it consists entirely of its children widget.  So when a user double-clicks, they'll be double-clicking on a ListItem, not a RoundRectList.  That means we would have to create some sort of mechanism to have the inline edit bubble up to the parent, which we don't currently have.

But I do agree with your scenario, of being able to initially create the list and then edit each list individually.  But preserving customizations if a user later invokes inline-edit again is going to be very hard.  If the user merely renames one of the items, it's straight forward to match it up with the existing structure.  But what happens if a user deletes on and changes the label of another?  There's no way to divine the user's intent.

**Comment by JonFerraiolo** [comment]
I was wrong to compare to ComboBox. It's more like dijit.Toolbar and dojox.mobile.TabBar, and to some extent DIV and SPAN. For those widgets, you can do inline edit on the container or the individual children. If you do inline edit on the container, the children get replaced. To bring up inline edit on the container, either double-click on an area of the screen that belongs to container but doesn't have a child in it, or select the container and then double-click on the selection chrome.

**Comment by jhpedemonte** [comment]
> To bring up inline edit on the container, either double-click on an area of the screen that belongs to container but doesn't have a child in it, or select the container and then double-click on the selection chrome.

Again, this is the part that makes it tricky for these to List containers: there is no chrome that belongs to the container, so the only option is to double-click on the selection box.  And that is **very unintuitive**.  It would be good if there were another way to handle this.

**Comment by billreed63** [comment]
I have not spent a great deal of time looking at RoundRec but I though  RoundRec requires a ItemFileReadStore which would make it closer to mobile.ComboBox, or DataGrid. When you edit RoundRec the ItemFileStore gets reaplace.

**Comment by jhpedemonte** [comment]
@billreed63 - You're thinking of **RoundRectDataList**, which does work with a **store**.  RoundRectList and EdgeToEdgeList are just declarative and work with **ListItem** widgets.

**Comment by jhpedemonte** [comment]
OK, so here's the consensus:
- Show smart input for RoundRectList/EdgeToEdgeList when first added to page, allowing user to enter text for contained ListItems (one per line of text).
- Afterwards, user can bring up smart input for each individual ListItem.
- Or, if they find out about double-clicking on the RoundRectList/EdgeToEdgeList selection grid, they can bring up that smart input.  But any changes here recreate the contained ListItems, overriding any user changes therein.

**Comment by JonFerraiolo** [comment]
> But any changes here recreate the contained ListItems, overriding any user changes therein.

Maybe for M2 we can take the shortcut to override user changes to ListItems, but long term we should preserve them. Takes more effort, but we do this in other cases already, such as TabContainer.

**Comment by billreed63** [comment]
added smartInput for roundRec and EdgeToEdge

July 2011

**Comment by JonFerraiolo** [comment]
Great job, Bill! You are preserving any widget-specific attributes on the ListItem and even preserving embedded Switch widgets within the ListItems.
