### ISSUE TITLE
Open theme not working in nightly build

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#527]
@jhpedemonte, @billreed63

I pulled down http://maqetta.org/nightly/maqetta-20110616-0602.zip to my Mac, launched the localhost server, and then in Mac/Chrome went to http://localhost:50000/maqetta. I was able to clone claro to a new a1 theme using New Theme..., but when I tried to open the theme editor on a1, I got 'dojo not defined' in the Chrome console and the server console also included an error message.

**Comment by jhpedemonte** [comment]
`dojo` is not defined because **dojo.js** failed to load.  The request is for this URL: http://localhost:50000/maqetta/user/maqettaUser/ws/workspace/%root%/dojo/dojo.js.  I'm guessing the **%root%** is wrong.

**Comment by childsb** [comment]
Fixed the dojo undefined error--

Also added prompt to prevent user from opening themes not in their workspace.

So the theme editor works with dojo 1.5, but wont load completely with 1.7. I'm guessing some of the widgets changed?
@peller @billreed63

**Comment by JonFerraiolo** [comment]
Bill, I reassigned this to you - hope that's OK. Adam has other urgent things on his plate.

**Comment by billreed63** [comment]
The theme editor is not opening with dojo 1.7 do to the tooltip and dialog code that was added to theme editor to support those two widgets. Adam is looking into the reason why..
