### ISSUE TITLE
Dialog buttons are inconsistent

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#529]
Some of our dijit.Dialogs have an ok button, some ok/cancel, some no buttons at all (like the About box)  All have close boxes.  We should make these consistent.  OK/Cancel is what I'm used to seeing, though I can see how the close box is redundant.  What's the right answer?
@jmockler

**Comment by JonFerraiolo** [comment]
Some of the UI folks have noticed this and proposed a standard policy for the button labels on dialogs. Usually, the OK button should say "Save" or "Create" or something like that rather than just "OK". I need to inventory the product and log detailed bugs so that the cleanups actually happen.

**Comment by jhpedemonte** [comment]
Yes, Jon is correct:  we should use appropriate verbs, instead of a generic "OK".

I'm fine with or without the close buttons.  Not really causing much issue as is.

**Comment by JonFerraiolo** [comment]
Pushing to M4.

**Comment by JonFerraiolo** [comment]
Pushing to M5

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg

**Comment by doronrosenberg** [comment]
Have we decided on how the buttons should work?

Right now I assume right aligned, cancel [Save] is the preference?  Cancel being a html link and Save a button

**Comment by doronrosenberg** [comment]
Fixed in rev b731265d00aeac3cd10e29fdfa113050c4c717af
