### ISSUE TITLE
Build script minor improvements

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#532]
Two things that would be nice with build scripts:
- Some sort of option to build from local repository instead of pulling from GitHub. Wayne explained how to do this via manual directory copies and manually changing build.sh. Would be very nice (and encourage people to do test builds before pushing changes) if there was an option at top of build.sh that could provided a local repository folder and then would copy that folder into the build area instead of cloning/pulling from GitHub.
- Since maqettaCode isn't working as is, best to remove it from build.sh

**Comment by waynevicknair** [comment]
maqettaCode is now working.
