### ISSUE TITLE
Error message in console when doing Preview for page w/ mobile widgets

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#533]
@peller

I checked in fixes so that preview-in-browser works for desktop widgets, but with latest code mobile widget preview isn't working. This has nothing to do with mobile silhouettes. To reproduce:
- New HTML File
- Add RoundedRectList
- Click Preview-in-Browser icon

Result=> Nothing shows in browser tab for the preview, and console says 

dojox/mobile:14Uncaught Error: Tried to register widget with id==dojox_mobile_RoundRectList_0 but that id is already registered

I'm not sure what happened recently. I swear this was working yesterday.

**Comment by peller** [comment]
I'm getting errors just placing it on the page.  Are there any layers missing?

**Comment by JonFerraiolo** [comment]
Maybe we can close this bug. Preview does work if you put RoundedRectList inside of a View widget.

**Comment by jhpedemonte** [comment]
Yes, **RoundRectList** must go inside of a **View**.  Doing so and the widgets appear just fine in **Preview**.

However, still see the `already registered` error on the console, even with the Dojo nightly.  Not sure what's going on with that.

For now, keeping this open on M2, but dropping to **Priority Low**.  May get moved to M3 or later.

**Comment by jhpedemonte** [comment]
Repurposing issue to track error msg in console.

Changed title from `Preview not working for mobile widgets, silhouettes or not` to `Error message in console when doing Preview for page w/ mobile widgets`

**Comment by jhpedemonte** [comment]
OK, this is caused by **States.js**.  It has a require for **dojo.parser**, even though mobile should only be using **dojox.mobile.parser**.  The end result is that 2 parsers are used on the page, and the 2nd one throws the _already registered_ error.

**Comment by jhpedemonte** [comment]
@peller, I would appreciate your guidance on the commit above.  From the [docs](http://docs.dojocampus.org/dojo/parser), it seems that we do need to `dojo.require("dojo.parser")` if we intend to use it.  So in the commit, I added a check around that line to see if the mobile parser is already on the page and if so, don't do the require for the regular parser.

I don't particularly like the fix, but hopefully all this code can go away when we redo States.
