### ISSUE TITLE
'dojo' null exceptions when following tutorial

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#534]
These errors appears in console when running the page editor tutorial. Need to investigate and fix. I think it has to do with doing things in the States palette.

davinci.js:1606TypeError: Cannot read property 'dojo' of null
davinci.js:1606TypeError: Cannot read property 'dojo' of null
davinci.js:1606TypeError: Cannot read property 'dojo' of null
davinci.js:25927aaa:State aaa
davinci.js:1606TypeError: Cannot read property 'dojo' of null
davinci.js:25927bbb:State bbb
davinci.js:1606TypeError: Cannot read property 'dojo' of null

Only happens in built version of product. Doesn't happen when launching from Eclipse.

Simple reproducible case:
- New HTML File
- Create new state aaaaa
- Switch to state aaaaa
  Result=> Console shows davinci.js:1606TypeError: Cannot read property 'dojo' of null

NOTE: This has nothing to do with the change where I cloned workspace/maqetta/States.js into davinci/maqetta/State.js. The same problem existed in a build created the day before I made the change.

NOTE: Changing states goes into onSelected callback function (StatesView.js:315) for the DataGrid used by the States palette. Maybe something is different with DataGrid in Dojo 1.6.1 than in 1.5.

**Comment by billreed63** [comment]
Since there is a DataGrid widget involved, I was wondering if you might look at this bug. If we are lucky, you're great knowledge of DataGrid will help you figure out what's wrong quickly. If you don't have time, maybe Adam or I can try to get to the bottom of it.

Unfortunately, the bug only manifests itself in builds. If you (or maybe Adam) can't guess where the problem might be, this might turn into an extended exercise involving attempting to debug in a build. (Maybe Adam has tips for most time-efficient way to investigate why something fails in a build.)

**Comment by waynevicknair** [comment]
the exception is coming from this code snippet:

```
        this._fadeOutDeferred = new dojo.Deferred(dojo.hitch(this, function(){
            fadeOut.stop();
            __delete this._fadeOutDeferred;__
        }));

        fadeOut = dojo.fadeOut({
            node: this.domNode,
            duration: this.duration,
            onEnd: dojo.hitch(this, function(){
                this.domNode.style.display = "none";
                dijit._DialogLevelManager.hide(this);
                this.onHide();
                this._fadeOutDeferred.callback(true);
                __delete this._fadeOutDeferred;__
            })
         }).play();
```

NOTE THE DOUBLE DELETE

**Comment by JonFerraiolo** [comment]
Wayne, which file is this in?

**Comment by waynevicknair** [comment]
dijit/Dialog.js

**Comment by waynevicknair** [comment]
opening a ticket at Dojo Foundation for this one per Adam's advice.

**Comment by waynevicknair** [comment]
see Dojo Ticket #13262 

double delete in Dialog show() and hide() methods

**Comment by waynevicknair** [comment]
never mind. the workbench is running dojo1.6 where this problem was opened with ticket #12436 which is fixed in dojo1.7. so, we can either patch the current dojo1.6 or update the workbench to use dojo1.7. (i don't think we'll update to dojo1.7 internally before M2. i'll patch) @peller
