### ISSUE TITLE
Dojo fx console error messages upon adding a new state

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#535]
Upon creating a new state, the following messages appear in the console:

app/dojo/./_base/fx.js:153 exception in animation handler for: onEnd
app/dojo/./_base/fx.js:154 TypeError: Cannot call method 'callback' of undefined

I poked around some and my _guess_ is that the destroy() method is called before the fadeOut animation is completed, and the destroy() does not clear out the fadeOut animation, which tries to call the onEnd logic, but maybe that function is no longer around. Maybe Dojo 1.7 is trying to do clever animation effects and it's not completed and correctly implemented yet?

**Comment by peller** [comment]
dup of #534?

**Comment by JonFerraiolo** [comment]
Yeah, I'm pretty sure this is the same problem at #534
