### ISSUE TITLE
Do we really need Outline for CSS files?

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#536]
Opened **themes/claro/Calendar.css** and noticed that basically **_all**_ of the CSS files contents were duplicated in the **Outline** view as a tree structure.

Seems unnecessary and doesn't really add anything.  We should just get rid of this functionality.

@JonFerraiolo @peller @billreed63

**Comment by peller** [comment]
guess it doesn't hurt?  it may not be a very deep structure, but it would act like a table of contents on a very long file

**Comment by jhpedemonte** [comment]
Well, it's not just a table of contents -- it shows top-level nodes for the selectors, and then each node has a child for each rule.  So it basically duplicates the whole CSS file, in tree form.  The only things not shown in the Outline view are the comments.  That's why I'm questioning the use of this.

**Comment by peller** [comment]
so maybe just show the selectors?

**Comment by JonFerraiolo** [comment]
Outline palette should show nothing when a source editor is open (instead of visual editor). Maybe in the future we can show JS functions or CSS style rules or whatever, but we don't have time right now to think through all of these features, so we should just disable outlines except when using visual editor.

**Comment by JonFerraiolo** [comment]
-> M7/Prio-Low because it should be a quick and easy fix if @doronrosenberg has a few free minutes

**Comment by JonFerraiolo** [comment]
Closing. Outline palette is not visible for for source files since M7.
