### ISSUE TITLE
OK/Cancel buttons on deletion confirmation dialog have reversed actions

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#537]
Testing on Chrome/Mac.  Went to delete file I had created.  Get confirmation dialog.  Clicking on **OK** did nothing.

However, clicking on **Cancel** (or hitting **Esc** key) results in file being deleted.

@JonFerraiolo @childsb @peller

**Comment by peller** [comment]
my bad, and I forgot the "fixes #" comment, to boot.  See e5fec8db37c3b346c526
