### ISSUE TITLE
Context menu actions in Files view don't always affect resource user clicked on

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#538]
The action a users selects using the context menu in the **Files** view doesn't always affect the resource the user expects.  For example:
- Select **Sample1.html**.
- Right-click on **Sample2.html**, in order to make the context menu appear.
- Select **Delete Resource** from context menu.

The user will expect this action to affect **Sample2.html**, since that is the resource the user right-clicked on.  However, the deletion confirmation dialog will list **Sample1.html** as the file to be deleted.

This might be a known issue from a while back, but I think it is important since it can result in unexpected loss of data (wrong file gets deleted).

@JonFerraiolo @childsb

**Comment by peller** [comment]
this is code I've been messing with recently... but I tried what you said, and it works for me. What am I missing?  Are you running the very latest as of Thursday night?

**Comment by JonFerraiolo** [comment]
Javier is saying that "delete resource" will delete the selected file instead of the file that is under the mouse. I just tried and I'm seeing the same thing as Javier.

**Comment by peller** [comment]
so I just tried this with the 20110617-1057 build and it works for me.  I click on Sample1.html.  Then I right-click on Sample2.html.  I can see the selection change beneath, the delete resource dialog says it's going to delete Sample2.html and it operates on Sample2 when I delete.

I did this on Chrome/Mac, FWIW

**Comment by JonFerraiolo** [comment]
How are you testing this? With an actual mouse or using Ctrl-touchpad or what? What I'm seeing is that Ctrl-touchpad acts as you describe above (i.e., file under mouse gets selected, then menu appears) but when I use an actual mouse and click on RMB, the selection does not change, and instead the previously selected file gets deleted, not the file under the mouse.

**Comment by jhpedemonte** [comment]
I can confirm what Jon said about using a mouse, can still reproduce issue.

**Comment by JonFerraiolo** [comment]
I just tried latest code again and I'm still having this issue using a 2 button mouse on Mac/Chrome and Mac/FF.
