### ISSUE TITLE
After dragging out a DIV, cannot drag/drop other DIVs

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#54]
- New HTML File
- Click on DIV widget in widget palette
- Move mouse over canvas and drag out a rectangle to define the size of the new
  DIV
- Now try to drag a second DIV from the widget palette and drop onto canvas

Result=> Nothing happens. The DIV cannot be added to the page
- Once again click on DIV widget in widget palette, move mouse over canvas, and
  drag out a rectangle to define the size of the new DIV

Result=> New DIV is created successfully
- Refresh the browser
- Now try to drag a 3rd DIV from the widget palette and drop onto canvas

Result=> Works. 

Must be some state variable in the widget drag/drop logic that isn't getting
restored properly after dragging out a rectangular region for a widget.

**Comment by peller** [comment]
Console output -- if this is the same bug I'm seeing:

args is undefined in Context.js:25 (constructor, var editor = args.editor)  onDragStart calls clone on data.data which then tries to call the constructor on Context.js without an arg.

**Comment by JonFerraiolo** [comment]
Setting this to M3 with Priority-Medium and assigning to Adam.

Just tried this again and bug is still there. Here is what appears in Chrome console:

Uncaught TypeError: Cannot read property 'domNode' of null app/dojo/../davinci/ve/VisualEditor.js:22
dojo.declare.constructor app/dojo/../davinci/ve/VisualEditor.js:22
a app/dojo/./_base/declare.js:360
dojo.clone app/dojo/./_base/lang.js:267
dojo.clone app/dojo/./_base/lang.js:258
dojo.clone app/dojo/./_base/lang.js:258
dojo.clone app/dojo/./_base/lang.js:276
dojo.clone app/dojo/./_base/lang.js:276
dojo.clone app/dojo/./_base/lang.js:276
dojo.declare.onDragStart app/dojo/../davinci/ve/palette/Palette.js:282
dojo.hitch app/dojo/./_base/lang.js:128
dojo._listener.getDispatcher app/dojo/./_base/connect.js:27
dojo.declare.onMouseMove app/dojo/../davinci/ui/dnd/DragManager.js:96
dojo.hitch

**Comment by JonFerraiolo** [comment]
I just tried this again and I'm seeing different results now. To repeat the scenario:
- Click on DIV in Widget palette, then move mouse over canvas, then drag out a rectangle. Result: you get a DIV that reflects the rectangular you dragged out.
- Try to repeat to drag out a second DIV

Result=> The second DIV has default size, not the size of the rectangle you dragged out

**Comment by JonFerraiolo** [comment]
@peller: you working on this? If not, please reassign to me. I'll be rolling up sleeves and fixing a bunch of stuff in this area in coming weeks.

**Comment by JonFerraiolo** [comment]
Fixed by 9be291ad2c9c98305d93bfe1691be4d19ef3a0ff. (Shouldn't have put words between Fixed and the bug number)
