### ISSUE TITLE
Combobox created with no default content, inline edit always shows as blank

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#540]
Drop Dojo ComboBox on to page.  Notice that inline edit dialog comes up, but without any content (even though you can see _Item 1_ in the widget).

Enter text, such as:

> one
> - two
>   three

This works, and those contents are shown when opening the page in preview.  However, if you double-click on the ComboBox again, inline edit shows up as blank once again, instead of showing previously entered content.

Build info:

> Version: Preview 2
> Build: c0d42a94569520b...
> Date: 2011-06-16T23:30:25Z

**Comment by jhpedemonte** [comment]
Also affects **FilteringSelect**.

**Comment by billreed63** [comment]
ComboBox was using the wrong store in inlineEdit.
