### ISSUE TITLE
Context onload callback gets called twice

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#541]
@jhpedemonte

a regression.  you'll see the console.info that prints out dojo.version twice per editor

**Comment by JonFerraiolo** [comment]
that might explain why it's now slower to create a new file

**Comment by jhpedemonte** [comment]
I locally updated Dojo 1.7 to the 2011-06-21 nightly and now I only see the version outputed **once** to the console:

```
Content Dojo version: 0.0.0dev (23930)
```

**Comment by JonFerraiolo** [comment]
You only see one version outputted now probably because of Bill's checkin: 715a46bc4654f8d8a5637b9802a05ab282131e9a

**Comment by jhpedemonte** [comment]
Nope, I can confirm that upgrading Dojo did indeed fix this issue.  My local repo does not yet have Bill's fix.  Switched back to 1.7 beta and saw the 2 instances of `Content Dojo version...`.  Going to Dojo nightly made this go away.

**Comment by jhpedemonte** [comment]
I think we should keep this bug open until we upgrade Dojo.  Then verify if the new Dojo does indeed fix this issue without Bill's change and, if so, remove the fix.

**Comment by jhpedemonte** [comment]
I confirmed that using Dojo 1.7b2, Bill's check isn't necessary (although we should still keep the `this` -> `context` changes -- good catch there).
