### ISSUE TITLE
Log in through maqetta.org needs polish

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#543]
Currently the maqetta.org log in is a bit awkward. We can clean up this area of the UI in the short term:
1. Specifications for the cleanup: http://skitch.com/janetmockler/fferi/maqetta.org-log-in-shortterm
2. The remember button does not remain selected: see issue #473

For the long term we'd like the log in to be accessed from the log in link at the top of the page: http://img.skitch.com/20110617-t8gixhgk87y4g1yyytckg91c3m.jpg

@jmockler @JonFerraiolo @jinsil @jhpedemonte @peller
UI Review - Jun 10, 2011
Using Firefox 4.0

**Comment by jhpedemonte** [comment]
Copying @waynevicknair

**Comment by JonFerraiolo** [comment]
-> @childsb M7/Prio-High to include the right login dialog design provided by the UI team. Feel free to send this issue once the dialog is implemented if you need help with pixel tweaking.

**Comment by jhpedemonte** [comment]
We are now using the Orion login screen, which is different than what we had previously:

![orion login screen](http://i.imgur.com/bayG5.png)

Although, it could be massaged to resemble the image that Janet posted...

**Comment by childsb** [comment]
Fixed in #2862
