### ISSUE TITLE
Welcome in maqetta needs to be polished

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#544]
@jmockler @jinsil
UI Review - Jun 10, 2011
Using Firefox 4.0

http://img.skitch.com/20110617-r1srhcf4xf2us6rhk49qnqr2dx.png
1. Until we add in the 'Recent Files' feature, we should remove it from the Welcome
2. Titles of the Quick start sections on the left should use 'Claro Hyperlink color' - #0000EE
3. Content of the topics should not be hyperlinks, just formatted with black text, only the button and the Title should be hyperlink style
4. Reduce the space between the topics by 5 pixels or more, so that the scroll bar does not appear at 1024x768 resolution
5. Reduce the spacing between New Review and New CSS theme, so that it is consistent with the spacing between the other sections
6. Common Actions and Tasks. The action labels for the 3 actions should be formatted using the hyperlink styling
7. The text for these actions should be bottom aligned across the top line. Currently they are center aligned which makes reading them difficult.
8. The spacing between text strings that wrap should be reduced to the same spacing used on the left side of the welcome sections
9. Try to avoid the use of a vertical scroll for the welcome at the minimum size of 1024x768.

.

**Comment by JonFerraiolo** [comment]
-> M7/Prio-Med Will probably work on this as part of M7 UI makeover effort.

**Comment by JonFerraiolo** [comment]
Closing. We have a nice welcome page now.
