### ISSUE TITLE
Rearrange views, so that the file view is on the top of stack instead of the bottom

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#547]
@jmockler @jinsil 
UI Review - Jun 10, 2011
Using Firefox 4.0

 When the application is first opened the explorer is at the bottom of the left stack. Which seems inappropriate since its one of the first places where we need to go to open new files.
1. First visual ensure that the Files view is at the top and in front... Otherwise it is very empty.

In the current implementation, this is important, however once we allow users to customize their working area, this will simply be the first area in the UI where they can access files.

**Comment by JonFerraiolo** [comment]
Closing this: we have decided on initial palette layout for M7 UI makeover and there is a different issue to allow user to rearrange where palettes go.
