### ISSUE TITLE
Create new... dialog needs to be improved

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#548]
@jmockler @jinsil
UI Review - Jun 10, 2011
Using Firefox 4.0

Will post specifications that detail an improved design for the Creation dialog.

 Improve the create new dialog.. update terminology, etc.
     - Dialog title
     - File name alignment
     - Folder picker should show a 'new folder'.
     - OK | Cancel (text)
     - Fade out the background when a dialog is open
     - Should remove the 'parent folder' or improve on the OOB
     - selection in the dialog tree is strange.. grey with blue strokes

**Comment by peller** [comment]
-> @doronrosenberg

**Comment by JonFerraiolo** [comment]
-> M7/Prio-Low and me in case I'm able to get to this as part of M7 UI makeover effort

**Comment by JonFerraiolo** [comment]
Closing. We've done all sorts of UI changes in the "new html file" area since this original issue was created.
