### ISSUE TITLE
Interaction around the Creation of a new theme should be improved

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#550]
@jmockler @jinsil 
UI Review - Jun 10, 2011
Using Firefox 4.0

Problem: 
1. After I create a clone of a new theme via the dialog.. I don't get a toaster or any notification to let me know that my theme was created. 
2. So i click OK a second time - cause I thought it didn't work. 
3. Then I get a message that I already created a theme with that name. 

Confusing interaction. Instead it should open the theme editor after I create the clone, with the theme I've created displaying.

**Comment by JonFerraiolo** [comment]
Closing. We now open the theme editor after clicking Create on the New Theme dialog.
