### ISSUE TITLE
Cannot open a theme file

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#552]
@jmockler @jinsil
UI Review - Jun 10, 2011
Using Firefox 4.0

Tried to open a theme file from the explorer, and the application freezes and does not load it.
1. We should use the new progress indication interaction as described in Issue #474
2. Test on multiple browsers to see if the theme editor opens

**Comment by JonFerraiolo** [comment]
Probably related to #263

**Comment by waynevicknair** [comment]
i created a new theme and tried to open the theme editor, but it hangs with the Loading... progress indicator.

**Comment by JonFerraiolo** [comment]
Closing. You can open themes successfully with latest code, either via Open Theme... command or double-clicking on a *theme file in Files palette.
