### ISSUE TITLE
dirty HTML editor

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#554]
@jmockler @jinsil
UI Review - Jun 10, 2011
Using Firefox 4.0

After a new HTML document is open, it is automatically dirty. It should not be showing as dirty until a user makes a change in the content of the document.

**Comment by jhpedemonte** [comment]
It's automatically **dirty** because the file hasn't been created yet.  As such, that is the unsaved state.  You can press the **Save** button and it will then save the file to your workspace, empty.  To me, this looks like the right behavior.

@JonFerraiolo @peller

**Comment by jhpedemonte** [comment]
OK, just discussed this on the call.

First issue:  If a user creates a new file, then immediately closes it without saving (having made no changes to file), the user is still presented with a confirmation dialog, stating that unsaved changes will be lost.  This shouldn't happen.  The confirmation dialog should only come up if actual changes have been made to the file.

Second issue: On a newly created file, there is a **dirty** indicator, even though no changes have been made.

Resolution: There should actually be 3 states for a file.  An initial **new_file** state and the existing **dirty** and **not_dirty** states.  Flow would go something like this:

```
 new_file
    |
    v
  dirty   <--->   not_dirty
```

Confirmation dialog only appears when file is in **dirty** state.

**Comment by wnm3** [comment]
If you open a file in Display Design mode and then switch to the Display Source mode, it also marks the editor "dirty" even though nothing was explicitly changed by the user.

**Comment by jhpedemonte** [comment]
-> M6/Med

**Usability** issue, especially [this comment](https://github.com/maqetta/maqetta/issues/554#issuecomment-3588518).

**Comment by jhpedemonte** [comment]
-> @doronrosenberg
