### ISSUE TITLE
Page editor and theme editor shouldn't die if bad theme in user workspace

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#557]
@jhpedemonte, @billreed63, @childsb, @peller, @jmockler

Janet and Jin tried to create new themes with a space in the theme name and ran into #263. We should validate the theme names, sure, but the code shouldn't die if a bad theme exists in user workspace. 

Right now, you can't open the theme editor if one of the themes has a space character in its name.

**Comment by peller** [comment]
I think the spec says you can escape characters in identifiers, though I've never seen that done.  We'd also need to make sure to use encodeURI for our rest calls, also for our APIs with filenames (e.g. load/save) which presently don't handle special characters like "@" well.

**Comment by jmockler** [comment]
I also expected to be able to use spaces or any special characters in naming the cloned theme I created. Is that something that will be fixed in Maqetta?

**Comment by JonFerraiolo** [comment]
Given underlying technology constraints, we can't have theme names with spaces. However, we could convert spaces to underscores. If this sounds like a good idea, then the follow-on question is whether we would do this space-to-underscore conversion silently and automatically, or post a prompt telling the user we did this conversion for them.

Right now we have an open issue to add validation logic to prevent users from entering names that will cause things to break: #263. That shouldn't be that hard of a bug to fix. Might make it into the next imminent release.

**Comment by JonFerraiolo** [comment]
Closing this. Opened #591 about the notification UI.
