### ISSUE TITLE
Some old files?

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#558]
It looks like some of the files in davinci/ve/widgets aren't used anymore.
They're required in davinci/ve/views/SwitchingStyleView.js but don't appear to actually be used beyond that. However, on closer inspection it does look like code from these files was pasted into davinci/ve/views/SwitchingStyleView.js
- Background.js
- Border.js
- BorderRadius.js

The rest of the files in the widgets folder appear to be used in either davinci/ve/views/SwitchingStyleView.js or davinci/ve/widgets/HTMLStringUtil.js

**Comment by JonFerraiolo** [comment]
I'll look at this after the M2 release.

**Comment by JonFerraiolo** [comment]
Pushing now to M4.
