### ISSUE TITLE
Encode URI throughout

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#564]
@peller

Adam says this in #557, which seems to me its own separate issue, hence this bug:

We'd also need to make sure to use encodeURI for our rest calls, also for our APIs with filenames (e.g. load/save) which presently don't handle special characters like "@" well.

**Comment by JonFerraiolo** [comment]
-> @peller M7/Prio-Med

**Comment by peller** [comment]
see f178487411c09ea57510c85223dc2a3e4c41827e and 5bd11df084c31317e9645e1cf94df781a72c9e4d for preview url
