### ISSUE TITLE
Review wizard exception - needs update to refactoring

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#565]
@EldonReturn, @jhpedemonte

New Review wizard is dying at davinci.review/WebContent/davinci/review/widgets/PublishWizard.js:454:

```
            var file = new davinci.resource.File(item.name,targetTreeModel.root);
```

This is because Brad refactored some of the core files. I'm pretty sure that this one line can be fixed by changing it to:

```
            var file = new davinci.model.Resource.File(item.name,targetTreeModel.root);
```

But even if this change is correct for this one case, someone needs to inventory davinci.review and make sure all of the references to _resource_ have been updated correctly.

**Comment by peller** [comment]
I should go an refactor the tree also.  I'll take care of this.
