### ISSUE TITLE
Right click on the node of davinci.ui.widgets.Tree should select that node

### ISSUE THREAD

**Issue by EldonReturn** [maqetta/maqetta#570]
Right click on the node of davinci.ui.widgets.Tree should select that node. Currently, only clicking that node can user select the node.

**Comment by peller** [comment]
This seems to be standard dijit.Tree behavior, judging from the themeTester.  I'll check with wildbill.

**Comment by peller** [comment]
checkin from Eldon: 54390c83a5388f767198ce78ecbf0fc08c9b8919

**Comment by peller** [comment]
see http://bugs.dojotoolkit.org/ticket/15600
