### ISSUE TITLE
Exception when loading page with mobile widgets (fixed by Dojo 1.7 nightly)

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#571]
1) Create new html page desktop.html
2) Add textBox and TextArea widgets to desktop.html then save page
3) Create new html file mobile.html
4) Add mobile widgets, view, textBox, TextArea and save page
5) reload browser window

In console the following exception is displayed
Uncaught TypeError: Cannot read property 'style' of undefined

At this point if I select the textArea on the mobile page, the widget that is selected by the focus/select tool is the widget from the desktop page. I think the exception stops the model from building the model.

**Comment by JonFerraiolo** [comment]
Reassigning to Javier.
I see the same problem with these steps:
- New HTML File
- Add View and RoundRectList inside of View
- Add TextBox
- Browser refresh
  Result=> Uncaught TypeError: Cannot read property 'style' of undefined
  @peller

**Comment by peller** [comment]
This does seem to be specific to Dojo 1.7.  Running the same davinci.core against dojo 1.6, everything is fine. this.textbox is null.  it should be an attachpoint in the template.

**Comment by jhpedemonte** [comment]
Just locally updated Dojo 1.7 to the 2001-06-21 nightly and this error no longer happens.

**Comment by peller** [comment]
Good call.  There's supposed to be a new beta this week.  I'll find out the status tomorrow.

**Comment by jhpedemonte** [comment]
Fixed in Dojo 1.7b2.
