### ISSUE TITLE
exception setting class on button

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#572]
Create a new HTML document
Add a dijit Button
go to the properties panel and try to set the classname to 'foo'
Exception in ModifyCommand - widget is null

**Comment by JonFerraiolo** [comment]
I'm not seeing this with today's daily build on Mac/Chrome. Which version of software are you using and which browser? Note that I checked in a fix to ModifyCommand on Friday: 707e084b80577f1b07b9

**Comment by peller** [comment]
Sorry, I was using a build from Friday.
