### ISSUE TITLE
Consolidate samples into samples/ folder and make read-only?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#574]
@jhpedemonte

To make it easier to migrate users to subsequent releases of Maqetta (where we might modify old sample files, add new sample files or retire old sample files), we might do any or all of the following:
- Consolidate all sample files into a samples/ folder
- Make the sample files read-only and/or the samples/ folder read-only (users would need to save-as if they want to incrementally modify the samples)
- For extra credit, we could generalize the "manage libraries" dialog into a "manage workspace" dialog where we treat samples/ as (pretty much) yet another library that users can include or exclude and move to a different location in their workspace (Not sure this is a good idea)

**Comment by childsb** [comment]
Fixed--

Moved the samples to a library and left them in the root directory.  

If the user modifies one of these files thens saves it, the file is saved on the workspace.  There is no read-only prompt or need to save-as.

Commit 5170b5b265d7e2759d04edcb05ed9efe6017408f

We could prompt, but I felt this was more disruptive to the UI and best to either not do it or leave for milestone.  If tweaks to this behavior is desired please re-open and target/prioritize accordingly.
