### ISSUE TITLE
Copy/paste a widget with display:none in Normal state doesn't redraw even if visible in current state

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#576]
- New HTML File
- Add <label>, give it text "Normal"
- Add <label>, give it text "aaa"
- Create new state "aaa"
- Make label "aaa" invisible in Normal state but visible in aaa state
- Go into aaa state
- Select "aaa" label
- Copy it, then paste it

Result=> Cloned copy does not appear even though we are in aaa state
- Now switch to Normal state then back to aaa state

Result=> Cloned copy appears now

Somehow or other we need to trigger a recomputation of the cloned widget so that the visual editor will temporarily mess with the display property (and other properties) on the cloned widget to reflect what is needed to reflect the current state. Maybe we need a new listener to create widget?

**Comment by JonFerraiolo** [comment]
@jhpedemonte, @billreed63, @peller - This bug might relate to Javier's library API proposals and/or Bill's recent work with Paste command.

**Comment by JonFerraiolo** [comment]
Adam, reassigning to you for time being. I think there is something fishy with 4b0b7c6b6940d5fee8c47446f7050a86d9cd5a4c with loadRequiresForTree() and the use of dojo.hitch. In the debugger, the "d" value passed into this internal function:

```
dojo.hitch(this, function(d){
                if(d.children){
                    d.children.forEach(loadRequiresForTree, this);
                }
                if(!this._context.loadRequires(d.type)){
                    throw "Failed to load dependencies for " + d.type;
                }               
            });
```

seems to get random values. Sometimes "d" is a string and not an object. Some funky JavaScript thing is going on that I'm not seeing, and since this is code you added recently, can you look at it?

**Comment by peller** [comment]
@billreed63 was making updates relevant to this._data... perhaps fallout from my change also? I'll take a look... though I don't think it's the hitch. Perhaps it's my misunderstanding of what this._data is supposed to look like? Can you tell me how to get a situation where d is a string?

**Comment by peller** [comment]
ignore comment above about test case.  I missed the description.  Will investigate.

**Comment by peller** [comment]
@JonFerraiolo, hopefully that last patch gets you back to where you were.  I now see the node getting pasted, it's just not visible.

**Comment by JonFerraiolo** [comment]
I pinged @peller. Things are better. Simple widgets now copy/paste, but any widget that has a subtree of elements (e.g., ComboBox) still raise an internal error on paste.
