### ISSUE TITLE
New theme dialog doesn't show sketch theme

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#580]
@billreed63, @jhpedemonte

With this morning's build (http://maqetta.org/nightly/maqetta-20110620-0603.zip), if I immediately do a New Theme, the dialog only shows "claro" and doesn't show "sketch". There are other problems in the area of theme operations, but this one is at the head of the chain. Maybe fixing it will fix the others.

**Comment by peller** [comment]
somewhere in the commits, I think there was a "1.5" where there should have been a "1.7"?

**Comment by jhpedemonte** [comment]
@peller, are you referring to c473615819c0ae72ceb59c7347a2d88edac4fb0c?

**Comment by peller** [comment]
@jhpedemonte: yah

**Comment by childsb** [comment]
this is working for me now.  i dont think the version was the issue.. themes are located by doing findResource(*.theme)...

the commit for the version fix is 5511347fd163c4bcf70d3d21d3961c67f0d76081
