### ISSUE TITLE
setting app.css class on button has no effect

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#585]
Test case failed (properties palette part 4, app.css test)

Steps
Create a virgin user environment navigating away from daVinci, clearing browser cache, killing the server, removing users/ folder, restarting the server, and navigating browser back to daVinci. (For server-hosted, create a new user)
Double-click on the app.css file in the Files palette.
Add the following lines to the bottom of the file:
.myapp.claro .class1.dijitButton .dijitButtonNode {
    width:200px;
}
# label1 {

```
font-size:30px;
```

}

Save and close the file.
Issue a "New HTML File" command.
Drag two Buttons and two LABELs onto canvas.
Select the second Button, go to Properties palette and set class to 'class1'.
Select the second LABEL, go to Properties palette and set id to 'label1'.
Click on the "Save" icon on the main toolbar to save the new file. The asterisks that indicates that the file is "dirty" should go away.
Click on the "X" close button for the editor tab for this file
In the Files palette, double-click on the file you just created to re-open the file.

Expected results
Second button should have width of 200px and second LABEL should have font size of 30px.

Actual Results
Label has new font, and the button shows the CSS rule in the cascade but has no value.

**Comment by waynevicknair** [comment]
I added label/button/label/button. applied 'class1' to button and it got wider. applied 'label1' to second label and no font change occurred. i'm thinking it's the same bug.
