### ISSUE TITLE
Mobile updates for review/commenting (silhouettes, View support)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#586]
@EldonReturn, @jhpdemonte, @peller, @billreed63, @childsb

Gosh, how could I have overlooked this?

Review and commenting needs to use mobile silhouettes. For example, if an author is using the iPhone silhouette at the time he initiates a review session, then reviewers should do their review in the context of the iPhone silhouette.

Integrating the silhouette logic into review.html might not be all that difficult, but there some issues to take into account. Bug #143 (last mobile silhouette used is persisted into HTML file) is probably a pre-requisite. We'll need to think through whether to include the two mobile icons (select device, rotate device) in the editor toolbar for review and commenting mode. The silhouettes result in different size canvases, which will affect layout and therefore will affect some of the location logic for the annotations. We might have to tell authors that they can only send one device and one rotation with each HTML file.

Assigning this to me, but this probably will require a combination of Eldon and me.

**Comment by JonFerraiolo** [comment]
Decided to push off adding mobile support to R&C until M4 because there are multiple things needed to do before R&C works well for mobile UIs, and too risky to attempt all of these for M4. Better to do all of them for M4 rather than something that sort of works and appears broken.

Here is a partial list of changes needed for mobile R&C:
- R&C inside of silhouettes (this bug)
- Silhouettes are likely to cause offset problems with annotations, so annotations need to be offset
- dojox.mobile.View widgets are used all of the time and they need to be integrated into the review feature in a good way. Probably involves adding mobile views to the States palette (potentially renamed to Views palette and/or moved onto toolbar) both so that the user can navigate to particular Views but also we need to attach comments and annotations to particular views
- The dimensions feature on the review wizard doesn't make sense with silhouettes, which are fixed size
- R&C probably needs to be tied to one particular silhouette and disallow changing that silhouette or rotating that silhouette. Otherwise, annotation locations will be messed up.

**Comment by jhpedemonte** [comment]
Based on last comment, updated title to be more general (not just silhouettes).

**Comment by jhpedemonte** [comment]
cc @waynevicknair

**Comment by JonFerraiolo** [comment]
Pushing to M5 to be included after review/commenting integration into core

**Comment by JonFerraiolo** [comment]
I've sketched out how to integrate silhouettes into the review editor. I'd paste here but it's quite lengthy and the discussion is already quite large. Seems straightforward. One concern: not sure whether some of the (x,y) calculations in review editor (eg annotations) will need adjusting.

**Comment by JonFerraiolo** [comment]
@waynevicknair: I'm almost certain we need to include two new parameters with each HTML file included in a review: the device name and the orientation. Then ReviewEditor.js will need to access that data so it can pass the device and orientation to `new SilhouetteIframe()`

**Comment by waynevicknair** [comment]
@JonFerraiolo: we can stuff those parms into the ReviewObject which holds other info about the file under review.

**Comment by JonFerraiolo** [comment]
All of the key stuff is working now, so closing this bug. We can create other bugs for detailed problems we discover.
