### ISSUE TITLE
Clicking checkboxes in Prop view doesn't do anything

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#587]
Clicking on checkboxes in the **Properties** view has no effect (checkbox does not change state).  This seems to have regressed in the past few days.

Easy to reproduce:  Just drop a **Button** on a new page, open the **Widget-specific** properties and try to click on one of the checkboxes.

@JonFerraiolo @peller

**Comment by JonFerraiolo** [comment]
Works for me on Mac/Chrome and Mac/FF4 after pulling latest code from GitHub into Eclipse and using this morning's build. I dropped a Button and TextBox and clicked on various checkboxes under Widget-Specific and everything was operational.

**Comment by jhpedemonte** [comment]
Hmm, quite.  I wonder what was the issue?
