### ISSUE TITLE
No drag indicator or resize handles on dojox.mobile widgets

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#590]
@peller

This is an odd one.  Drop a **dojox.mobile.View** on the page.  Notice that it has resize handles and that if you hover on the outline, you'll see the drag indicator and will be able to drag it around the page.

Now, drop any widget inside of the view.  The widget will not show resize handles or the drag indicator and you will not be able to drag the widget at all.

Adam, any idea what could be going on here?

**Comment by jhpedemonte** [comment]
OK, so the issue here is that in **davinci.ve.Focus** `allow()`, `op.move` comes in as false for the case where a widget is in **dojox.mobile.View**.  This is because in **Context.js** `select()`, there is this line:

``` javascript
    op = {move: !(parent && parent.isLayout())};
```

In the case of a **Button** added to the top-level of the page, `parent` is the `body` element, represented by an instance of **davinci.ve._Widget**.  That object's `isLayout()` always returns false, so `op.move` is true.

In the failing case, `parent` is a **dojox.mobile.View**, represented by an instance of **davinci.ve.DijitWidget**, whose `isLayout()` looks like this:

``` javascript
    isLayout: function()
    {
        return this.dijitWidget.addChild;
    },
```

I guess since **dojox.mobile.View** is a container, then it has an `addChild()` property.

Can anyone explain the logic of all this?  Why should the move cursor be disabled in the case of a widget inside of a Dijit container?

@JonFerraiolo @childsb

**Comment by jhpedemonte** [comment]
`isLayout()` only seems to be called from `Context.select()`.

**Comment by JonFerraiolo** [comment]
As I remember, everything in the code that has various utilities such as isLayout, canHaveChildren, isContainer (and maybe other things) have not been carefully coded and things are working today mostly on a tenuous and not well-designed basis, and we need to clean all of that up. Maybe we are forced to do that now.

**Comment by peller** [comment]
ah, yes.  So this is because _usually_ layout containers control the position of their children (e.g. TabContainer, BorderContainer) so that you shouldn't be able to move the children from the tool.  View must be different... what exactly does a View do?  Is it just a container?  If so, why does it have isLayout()? [edit: just re-read your note above... yeah, sounds like there were assumptions that addChild meant the widget controlled layout... perhaps true for the rest of Dijit.  We need a better indicator]

Clearly, this code is makes some assumptions about Dijit APIs, which may not even be right, and is not toolkit-generic.  Perhaps we need metadata that says whether a widget controls layout/movement/sizing of its children?

**Comment by jhpedemonte** [comment]
Not sure what's going on with this.  `addChild()` comes from `_Container`, which has the following summary:

``` javascript
        // summary:
        //      Mixin for widgets that contain a set of widget children.
        // description:
        //      Use this mixin for widgets that needs to know about and
        //      keep track of their widget children. Suitable for widgets like BorderContainer
        //      and TabContainer which contain (only) a set of child widgets.
        //
        //      It's not suitable for widgets like ContentPane
        //      which contains mixed HTML (plain DOM nodes in addition to widgets),
        //      and where contained widgets are not necessarily directly below
        //      this.containerNode.   In that case calls like addChild(node, position)
        //      wouldn't make sense.
```

Whereas the description for `dojox.mobile.View` (which does mix in _Container) specifically says that it can handle HTML or widgets:

``` javascript
        //      View acts as a container for any HTML and/or widgets. An entire HTML page
        //      can have multiple View widgets and the user can navigate through
        //      the views back and forth without page transitions.
```

So there's a discrepancy here.  At the very least, there's a Dojo bug with the docs.  Adam, you agree?

**Comment by peller** [comment]
That does sound like a direct contradiction, yes.  Add to the list of questions for the dojox.mobile team.

**Comment by jhpedemonte** [comment]
Here's the dependency tree for `_Container` "subclasses":
- _Container
  - dijit.layout._LayoutWidget
    - StackContainer
      - AccordionContainer
      - _TabContainerBase
        - TabContainer
      - dojox.layout.RadioGroup
      - dojox.layout.RotatorContainer
    - BorderContainer
    - LayoutContainer
    - SplitContainer
    - dojox.layout.GridContainerLite
    - dojox.layout.TableContainer
  - dijit._TreeNode
  - dojox.layout.ExpandoPane
  - DropDownButton
  - dojox.mobile._ItemBase
  - dojox.mobile.Carousel
  - dojox.mobile.ContentPane
  - dojox.mobile.FixedSplitter
  - dojox.mobile.FixedSplitterPane
  - dojox.mobile.Heading
  - dojox.mobile.IconContainer
  - dojox.mobile.RoundRect
  - dojox.mobile.RoundRectList
  - dojox.mobile.SpinWheel
  - dojox.mobile.TabBar
  - dojox.mobile.View
  - dojox.widget.FishEyeList
  - dojox.widget.Portlet

It seems that we might want to make use of `_LayoutWidget` instead of `_Container`.  Here's its summary:

``` javascript
//  _LayoutWidget Base class for a _Container widget which is responsible for laying out its children.
```

So maybe change `isLayout()` thusly:

``` javascript
    isLayout: function() {
        return this.dijitWidget.isLayoutContainer;
    },
```

**Comment by jhpedemonte** [comment]
Oh, I hate Dojo so much!

Using `isLayoutContainer` doesn't work, since not only is it set `true` by `_LayoutWidget` and descendants, but it is also set by `_ContentPaneResizeMixin`, which gets mixed in to `dijit.layout.ContentPane`.

Meaning that if we change `isLayout()` as I mentioned in the previous comment, then resize handles aren't shown for widgets inside of `ContentPane`.

Maybe do:

``` javascript
this.dijitWidget.isInstanceOf(dijit.layout._LayoutWidget)
```
