### ISSUE TITLE
SaveAs to different folder doesn't remove old items from HEAD

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#592]
I tested SaveAs into different folders. So far, so good, except that old @import and old SCRIPT tags aren't removed properly. After multiple SaveAs operations into various different folders, the HEAD looked as follows. Note how there are multiple references to claro.css, dojo.css, and dojo.js, and multiple instances of dojo.require() on same classes. (I thought there was already an issue on this latter problem, but I couldn't find it.)

<!DOCTYPE html> 
<html> 
<head> 
<title>Untitled</title> 

<style type="text/css"> 
@import "themes/claro/claro.css";
@import "../../app.css";
@import "../../lib/dojo/dojo/resources/dojo.css";
@import "../themes/claro/claro.css";
@import "../themes/claro/claro.css";
@import "../lib/dojo/dojo/resources/dojo.css";
@import "../../lib/dojo/dojox/grid/resources/Grid.css";
@import "../../lib/dojo/dojox/grid/resources/claroGrid.css";
@import "./themes/claro/claro.css";
@import "../../themes/claro/claro.css";
</style> 

<script type="text/javascript" djConfig="parseOnLoad: true" src="../../lib/dojo/dojo/dojo.js"></script> 

<script type="text/javascript" src="./lib/dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script> 

<script type="text/javascript"> 
dojo.require('dijit.form.Button');
dojo.require('dijit.form.TextBox');</script> 

<script type="text/javascript" src="../lib/dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script> 

<script type="text/javascript" src="../lib/dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script> 

<script type="text/javascript" src="../lib/dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script> 

<script type="text/javascript"> 
dojo.require('dijit.form.Button');
dojo.require('dijit.form.TextBox');
dojo.require('dijit.form.ComboBox');
dojo.require('dojo.data.ItemFileReadStore');
dojo.require('dojox.grid.DataGrid');</script> 

<script src="../../maqetta/States.js"></script> 

<script src="../../maqetta/maqetta.js"></script> 

<script type="text/javascript"> 
dojo.require('dijit.form.Button');
dojo.require('dijit.form.TextBox');</script> 

<script type="text/javascript"> 
dojo.require('dijit.form.Button');
dojo.require('dijit.form.TextBox');
dojo.require('dijit.form.ComboBox');
dojo.require('dojo.data.ItemFileReadStore');
dojo.require('dojox.grid.DataGrid');</script> 

<script type="text/javascript"> 
dojo.require('dijit.form.Button');
dojo.require('dijit.form.TextBox');
dojo.require('dijit.form.ComboBox');
dojo.require('dojo.data.ItemFileReadStore');
dojo.require('dojox.grid.DataGrid');</script> 

</head>

**Comment by JonFerraiolo** [comment]
I classifed this as M2 priority medium. Would really like to fix before M2, but not absolutely essential. It's pretty ugly to write out files like we are doing now but in general things seem to work.

**Comment by childsb** [comment]
Fixed with checking 409bbf709a33ad8d5050de7b908af5750aa5b88e
