### ISSUE TITLE
Cookie busting?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#599]
@jhpedemonte, @childsb, @waynevicknair

M2 Priority High since this might be an important upward migration issue. Assigning to Adam for the moment since a lot of the existing cookies might be coming from Dojo/Dijit.

We have added cache busting logic. Based on New Review problem, maybe we should add cookie busting with new releases? What I'm thinking is that we could have a new cookie that holds the most recent build#. If that cookie doesn't exist or doesn't match the currently running build#, we remove all existing cookies.

But before doing this, we should really understand what all of those cookies are doing.

**Comment by peller** [comment]
I would probably design a separate counter which is incremented only when we think we need to clear cookies.  But first, we should do a round of testing to confirm this is needed.  I still don't feel confident I understand what caused the New Review problem #573

**Comment by JonFerraiolo** [comment]
I'm really sure the New Review problem was with cookies. Look at comments in #573. Clearing cookies got New Review to work in both Chrome and Firefox. With Firefox, I actually didn't restart the app. Instead, I just navigated away from Maqetta, then cleared all localhost cookies, and then navigated back to Maqetta. Before clearing cookies, I got the exception. After clearing cookies, no more exception. 

There are some cookies with the string "Tree" in the name.

**Comment by JonFerraiolo** [comment]
In issue #573, @peller says: So we'll need a way to transition the cookies.

**Comment by peller** [comment]
@EldonReturn

or perhaps just squelch the exception of fix the bug which causes this state.  Review has its own TreeModel.  What is it for?

**Comment by peller** [comment]
The easiest and safest way to avoid this problem for the next release is to rename the review tree.  The cookie is based on the id name.  I've asked @EldonReturn to give this a shot.  Unfortunately, still neither of us can reproduce the bug for testing.

**Comment by EldonReturn** [comment]
I just pushed in a fix that specified ids for the trees in the review explicitly. The trees will share the same state cookie if no ids are assigned to them when creation. This may result in inconsistent tree state. And the renaming also avoids the legacy cookie problem.

**Comment by EldonReturn** [comment]
The commit url is:
3dd1c4546bc14c15f6761264f8445aa337399222

I'm now working on the migration of the tree model on a local branch so that all the trees in the review can use the standard TreeStoreModel at last.

**Comment by peller** [comment]
See also http://bugs.dojotoolkit.org/ticket/12735 for the cookie problem in dijit.Tree
