### ISSUE TITLE
Security Vulnerabilites

### ISSUE THREAD

**Issue by jbrumwell** [maqetta/maqetta#6]
Hi,

I didn't have a chance to download the program to provide patches, but I did come across the following vulnerabilities. 

File browsing:
http://maqetta.org:55555/maqetta/cmd/loadFile?path=<PATH TO FILE>

Directory Transversal:
http://maqetta.org:55555/maqetta/cmd/listFiles?path=<PATH TO FOLDER>
http://maqetta.org:55555/maqetta/cmd/findResource?path=<PATH TO FILE>&ignoreCase=true

Best Regards,

Jason Brumwell

**Comment by JonFerraiolo** [comment]
@waynevicknair

Flagged this as a nice-to-have for M5. This is a pretty big topic.

**Comment by childsb** [comment]
this was fixed a while ago, not sure why/when it was reopened.
