### ISSUE TITLE
is findResource *.theme necessary

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#603]
@childsb, @JonFerraiolo

It seems like either we could search a known subset of the user's space for *.theme files, perhaps even locating them all at a known single directory, or if libraries are now shared, why should we have to search at all?  We could look once at server startup and just cache the value.

**Comment by JonFerraiolo** [comment]
Assigning to Bill and putting on M2 - not necessarily to fix, just to evaluate. Only fix if critical, otherwise we can fix in M3. (And it doesn't have to be Bill)

**Comment by childsb** [comment]
Fixed in commit ac5c562b93698c12cde9
