### ISSUE TITLE
Two SaveAs operations in a row causes Uncaught TypeError

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#609]
To reproduce (in Mac/Chrome):
- New HTML File
- Add a Button
- SaveAs a1.html
- Immediate do another SaveAs a2.html

Result=> Uncaught TypeError: Cannot call method 'removeWorkingCopy' of undefined Resource.js: 254

**Comment by childsb** [comment]
turned out to be an async loading issue.  worked through it and found a couple potential speedups.

commit: c0dcb5a83fdd25f3658ad567677c113c44ca2be1
