### ISSUE TITLE
Major performance problems with MultiSelect on WebKit

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#61]
I'm seeing this problem in WebKit browsers on all platforms (Chrome/Win,
Chrome/Mac, Safari/Mac). No problems with Firefox3.x
- Make sure no editors are open
- Navigate browser away from app, clear caches, navigate browser back to
  app (probably not necessary to clear the caches)
- New HTML File
- Drag/drop a MultiSelect widget
- Open up Layout section of Properties palette.
- Move the mouse over the input field for the height property and wait until
  the input field changes colors to show "hover" state for the input field

Result => You have to wait many, many seconds for input field to recognize the
fact that the mouse is hovering over it
- Move the mouse over the "x" on the close box for the editor and wait until
  the "x" highlights to show the "hover" state for the small "x" button

Result => You have to wait many, many seconds for "x" button to recognize the
fact that the mouse is hovering over it

**Comment by peller** [comment]
@childsb

It looks like most of the time is being spent in _updateCascadeList, Cascade.js line 443

``` js
            column.innerHTML = "<div class='cascadeRuleText'>" + valueString + "</div>";
```

it looks like it's looping and calling this hundreds of times

**Comment by JonFerraiolo** [comment]
There might be some inefficiencies in Cascade.js, but the same computations happen for all widgets, and everything is instantaneous everywhere else. There's something special going on with MultiSelect that doesn't happen with other Dojo widgets. It might be the above line of code, but I'm not sure why. That same line of code doesn't slow down the other widgets. The one thing that I can see that's different with MultiSelect is that it's underlying DOM representation is <select> with <option> children. Even DropDownSelect doesn't do this - instead DropDownSelect is a bunch of DIVs and SPANs.

**Comment by peller** [comment]
In _updateCascadeList, the for loop which iterates through this._values iterates through 183 items for MultiSelect.  For Button, it's more like 6.  It seems like for some reason, it's going through every style rule in Claro.  It repeats this loop about 17 times (once per widget instance)   We need to find out why it's not getting back a filtered list of style rules, but also how hard would it be to create the UI in a lazy fashion?  I think it's the innerHTML settings (183x17) which is causing the slowness, not the model traversal.  Because this is in a TABLE, each innerHTML generating a parse and layout slows things down significantly.

**Comment by JonFerraiolo** [comment]
I may have found the bug. I believe there is a bug in CSSModel.js:566 in davinci.html.CSSSelector.prototype.matches(). When the domNode for which we are computing the CSS cascade has no explicit ID, nor explicit classes assigned, then the existing logic matches lots of rules, returning a specificity 0 (which is what you get when you match the "*" rule). I believe I have a fix, but I want to stare at it some more and then talk to the original author of that code to make sure my theory is correct and the fix is correct.

**Comment by JonFerraiolo** [comment]
We still need to have the original author review this bug fix.
