### ISSUE TITLE
RadioButton doesn't drag to the canvas in some instances

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#612]
- new HTML file
- Drag RadioButton onto canvas
  it doesn't work
  Console reports: Uncaught TypeError: Cannot read property 'prototype' of undefined
- Drag MultiSelect onto canvas
- Drag RadioButton onto canvas
  it works

**Comment by JonFerraiolo** [comment]
Assigning to Adam for time being in case this is a Dojo 1.6 or 1.7 issue

**Comment by peller** [comment]
need to change the metadata.  there was a refactor and modules got moved out of CheckBox.js

**Comment by peller** [comment]
fixed in 819fc989dd16b8bd39dc2d94b931005e077b8a68
