### ISSUE TITLE
Differentiate between mobile and non-mobile widgets in Widget Filter

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#613]
If you search for "checkbox" (or another one that has a mobile version) in the widget filter, it brings up  both the one under Dojox Mobile and the one under Dojo Controls with nothing to help designate which is which prior to dragging them onto the canvas.

**Comment by JonFerraiolo** [comment]
@jmockler 
Some good UI issues raised by this one.

**Comment by jhpedemonte** [comment]
I mentioned once (can't find an open bug on this) that when showing search results, we should show the name of the category next to the widget name -- of course, properly styled in such a way that the widget name is most prominent.

> ---
> 
>   **ComboBox**    _Dojo Controls_
> 
> ---
> 
>   **ComboBox**    _Dojox Mobile_
> 
> ---

Also, having an informational tooltip appear when hovering over the widget name would help (#338).

**Comment by JonFerraiolo** [comment]
Good idea, but probably need different words for the widget category. "Dojo Controls" isn't all that helpful to users. What we really mean is "Dojo Desktop Controls", but I'm not sure that's the best string, either.

These naming questions interact with the question of how we want to group widgets in the Widgets Palette going forward. I've said this before, but here goes again. I expect we will have hundreds of widgets. Let's say 400 widgets for now. We can't have 20 top-level categories each with 20 widgets. That's too many categories to present to the user, and too many widgets within each category. I'm pretty sure we are going to need at least 2 levels of widget grouping. First thought is that we would have 2 top-level groups named "Dojo Desktop" and "Dojo Mobile" (along with other top-level groups, such as HTML), and then attempt to have common sub-groups for each top-level group (e.g., Containers, Form Controls, Popups, ...).
