### ISSUE TITLE
iframe widget sometimes doesn't show contents

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#615]
@peller

Intermittent bug, only seeing it so far with (Mac) Chrome. Set to M2 release for time being, but if this doesn't happen very often, we can deal with this problem after M2.
- New HTML file
- Add iframe widget, choose Sample1.html

Result=> Sometimes you just see a white rectangle in the page editor. If you save, reopen, the contents of Sample1.html appears. If you preview-in-browser, you also see contents of Sample1.html

I wonder if this is the same WebKit timing bug I noticed while implementing the SVG silhouettes. What I was seeing is that the OBJECT tag would trigger the onload event on the OBJECT tag before the SVG was actually ready for rendering. To work around that bug, I had to check the URL of the target on the load event against the URL that we were actually requesting, and if they didn't match, then force another reload inside of a timeout. (Look in preview/silhouetteiframe.js and search for setTimeout). I haven't reported this bug yet. I don't remember if Safari has same problem.

**Comment by billreed63** [comment]
I have tested this on Chrome/FF5/Safari windows,  I have not been able to reproduce.

**Comment by JonFerraiolo** [comment]
Reassigning to me for testing.

I tried today and couldn't reproduce. I've seen some issues with Chrome where mystery bugs disappeared if you exit and restart Chrome, such as #663. 

Let's test this bug once we have M2 running off of a server. If we can't reproduce off of a server, then let's close this.

**Comment by JonFerraiolo** [comment]
I tried to reproduce off of server macwayne2 and couldn't reproduce. Closing.
