### ISSUE TITLE
Surround with should select the new container (outline palette, too)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#62]
After choosing Surround with DIV/SPAN/A, the original element is still
selected. Instead, the newly created container element should be selected.

Also, need to make sure that the Outline palette correctly reflects the newly
selected element.

**Comment by JonFerraiolo** [comment]
-> M7 Prio-Low. Nice to have, but can be pushed to M8.

**Comment by peller** [comment]
-> M8

**Comment by JonFerraiolo** [comment]
Closing. Fixed by da13d4be5cfa9eaa7ad6183d71eb795c7e3ae8ce
