### ISSUE TITLE
Cancel button with widgets prevents selection of other widgets on canvas

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#621]
- New HTML page
- Drop some widgets onto a page: button, Label, div
- After dropping them all onto the canvas, double-click the button to change its content.
- Click Cancel so that you don't change the content
- Try to select the div or label on the canvas. It won't let you. But you can still select them from the Outline.

Testing with latest lab14 build on Windows/Chrome.

**Comment by JonFerraiolo** [comment]
Assigning to Bill for time being since inline edit is involved.

**Comment by billreed63** [comment]
July 2011
