### ISSUE TITLE
Background Color for AccordionContentPane changes depending on mouse location

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#624]
- Clone new theme
- Open theme editor on new theme
- Select AccordionContentPane
- Change AccordionContentPane's background color to green
- Hover the mouse over different parts of the accordion. 
  The color switches back and forth between white and green. When the mouse is over the text "Accordion - Pane 1," the ContentPane changes to white. Move mouse away and the ContentPane switches back to green. 

If you use the theme on an html file, the same thing occurs on the canvas and while previewing in browser.

Tested in Windows/Chrome

**Comment by JonFerraiolo** [comment]
-> M7/Prio-Low - in case @billreed63 can look at this as part of his complete review of theme editor with dojo 1.8
