### ISSUE TITLE
img/masthead_blue_gradient2.png missing from BorderContainer tutorials

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#625]
Need to do an inventory to see whether other referenced image files might be missing

**Comment by JonFerraiolo** [comment]
Removed M2 milestone after investigating. The issue is that the BCExample.html file that ships with the docs tells the user to drag two image files (masthead_blue_gradient2.png, powered_by_dojo.png) onto canvas. However, we don't have a convenient way to stuff a couple of sample images into the user workspace for the purposes of the tutorials. There is a bigger architectural issue with organizing the docs, samples and tutorials such that this particular issue could be addressed in the right manner. Also, not high enough priority to simply change the tutorial to navigate around this. This is also time-consuming, so putting everything off for now.

**Comment by airazabal** [comment]
Has this issue been resolved? It would be nice to finish the tutorials...or at the very least can the file be downloaded from the wiki or some other place???

**Comment by JonFerraiolo** [comment]
Hasn't been resolved yet. I'll try to address this before we get the next release out (should be this month).

**Comment by JonFerraiolo** [comment]
Some image files that are referenced in tutorials: masthead_blue_gradient2.png, wg_swoosh.jpg, powered_by_dojo.png, wg_hero_dojo.gif

**Comment by airazabal** [comment]
Thanks
