### ISSUE TITLE
Cannot click to select IFRAME

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#632]
Create a new HTML document
Drag an IFRAME on to the document
you get the same exception as in #630 (possibly related)
Immediately click on the body element in the outline view to de-select. You'll see the exception:
`TypeError: Object [object HTMLHtmlElement] has no method 'selectChild'`
Then click off the element and try to click back on. You don't get a focus ring.  You can, however, usually get the selection to work by clicking in the outline.

**Comment by JonFerraiolo** [comment]
I verified that M6 on maqetta.org generates a TypeError when I follow the steps listed above.

@billreed63

**Comment by peller** [comment]
works now
