### ISSUE TITLE
Cannot set cursor at beginning of line

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#634]
Whether by clicking or by using arrow keys, and cannot insert content there by typing.

**Comment by jhpedemonte** [comment]
I cannot reproduce this when running from source, latest code.

Created new HTML file, switched to source view -- I can use arrow keys to move anywhere within file, adding content at beginning.  Clicking also works.

**Comment by JonFerraiolo** [comment]
I tried with latest code from GIthub on both Mac/Chrome and Mac/FF and had no trouble putting type-in at start of line.

**Comment by peller** [comment]
me too.  how odd.
