### ISSUE TITLE
[regression] states associated with overlay widgets are not operational

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#636]
Create a Tooltip or Dialog.  You will see a state created associated with that widget.
Clicking on the state does nothing.  It is supposed to make the widget visible.

**Comment by JonFerraiolo** [comment]
@jhpedemonte, @billreed63

Do we really need to fix this for M2? Tooltip and Dialog have not yet made their way out of Untested widgets. Not that I'm against fixing this...

**Comment by peller** [comment]
no, this shouldn't hold up M2

**Comment by JonFerraiolo** [comment]
I changed this to Priority Low and left as M2. Adam, feel free to make the call and change to M3.

**Comment by jhpedemonte** [comment]
Jon, I think that's wise.  Right now, anything that's M2/Low priority I wouldn't feel bad if it slipped into M3.

**Comment by peller** [comment]
fixed by 1238fa41d656688d418bf569024f34a0ab6b2654
