### ISSUE TITLE
Why is there a lib/html folder in workspace?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#638]
@jhpedemonte

Why do we show lib/html/ in the Files palette? Seems like it shouldn't be there. If we do get rid of it, can we create another bug to fix the docs, which right now show pictures of lib/html/ and mention it in passing.

**Comment by jhpedemonte** [comment]
Good point.  The HTML "library" is really a special case, merely there to make coding easier.  But we shouldn't show it to users.

**Comment by childsb** [comment]
Unfortunatly, this change is a bit bigger than it appears.  The XML Java utility that reads/writes to libs.settings  assigns empty string to undefined tags/attributes.  This will have to be fixed before we can test if a library isn't defined and hide it in the UI.

Too risky for m3, setting as high priority for m4.
