### ISSUE TITLE
Download - Dojo not relocated if not included

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#639]
For the download-as-Zip feature, these things are working:
- If you uncheck Dojo, the ZIP will not include Dojo
- If you check Dojo and change the relative URL for Dojo, the ZIP will automatically fix up HTML files before stuffing into the ZIP so that the HTML files will point to the revised location for Dojo

However, if you uncheck Dojo and type in a different relative URL for Dojo, the HTML files do not get modified before being put into the ZIP. We still need the relocation feature to work even if Dojo isn't included for the scenario where the developer has Dojo in a different location than Maqetta, and the developer doesn't need or want a copy of Dojo within the ZIP files he receives from the designer (usually because Dojo is already in his development environment).

To reproduce:
- Create a new HTML file (e.g., file1.html), add a Button, Save
- Click the Download Entire Workspace icon at the top/left of the Files palette
- Uncheck Dojo, but change the location from "lib/dojo" to "dojo"
- Click the OK button
- After the download finishes, unzip and look at the HTML file. You'll notice that the HTML file includes references to "./lib/dojo/*" instead of "./dojo"

**Comment by childsb** [comment]
Fixed in commit 8d35bc965d2999efa32e45f658b6bf062bab74d3

**Comment by JonFerraiolo** [comment]
Glad to see this fix. This particular option is part of our new Tutorial 4 (Exporting to Developer Tools Tutorial) was down at the very bottom of the tutorial when talking about how to integrate with RAD.

**Comment by JonFerraiolo** [comment]
I tried this feature again with M3 code and this bug has come back. If you uncheck dojo in the download entire workspace dialog and change the text field from "lib/dojo" to "dojo", the HTML files still reference dojo at "lib/dojo" instead of "dojo".

But only fix for M3 if super-safe. Can be easily pushed to M4.

**Comment by JonFerraiolo** [comment]
Unfortunate to have to push this bug to M4, but we are out of time. One of the tutorials tells users how to relocate Dojo within the ZIP. If anyone notices the bug, we can tell them, sorry, you have to tell your developer to replace "lib/dojo" with "dojo" in the source files manually. (I think 2 places per HTML file)
