### ISSUE TITLE
PropertiesPalette2 says DIV should have "text content" field in "widget-specific" view

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#641]
The **PropertiesPalette2** test plan says the following:

> Set DIV's text content (under widget-specific) to "abc def ghi abc def ghi abc def ghi".

However, DIV doesn't have anything under widget specific.  In order to set text content, the user must double click in DIV in order to bring up inline edit.

I'm thinking that there should indeed be a **text content** field under **Widget-specific**, if for nothing else than that having to double-click in order to set text content is not obvious and discoverable for DIVs.

**Comment by JonFerraiolo** [comment]
Yes, we had a UI discussion some months back and decided that all data/properties that show up in inline edit should also show in the Properties palette (usually, widget-specific). I figure OK to fix this in M3 milestone.

**Comment by peller** [comment]
not sure it belongs under the widget.  perhaps we should show text nodes separately?

**Comment by JonFerraiolo** [comment]
Brad pointed out in #725: no "widget specific" properties for table, h1, h2, span or HTML Rich Text either.

**Comment by JonFerraiolo** [comment]
Given that we are running out of time on M3, I suggest that we update the test plan for now to tell people that we currently don't have a text content value for DIV, and point to #641 and #725, and once that is done, then push this bug to M4.

@peller, @billlreed63, @waynevicknair - would be good if one of you updated the test plan as I am suggesting and then moved this bug to M4.
