### ISSUE TITLE
Switching between states in theme editor results in error

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#642]
Following **testplan/ThemeEditors/DojoClaro/basic.html**, when I get to step 6 (change state to _Hover_), I get an error in the browser console and the theme editor state does not seem to change:

> TypeError: Cannot read property 'dojo' of null

@JonFerraiolo

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
@jhpedemonte - I'm scratching my head on why this was pushed to M6. Does the bug still exist? If so, shouldn't we fix for M5? If not, shouldn't we close.

**Comment by billreed63** [comment]
This does not happen anymore, closing
