### ISSUE TITLE
Widget-specific properties not saved in all cases

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#643]
- new HTML file
- drag text box onto canvas
- Under 'widget-specific' type a number for the 'max length' property
- After typing the number, click on the canvas so that the widget is no longer selected
- Select the text box again -- the 'max length' property will be blank.

The same thing occurs for other properties that you have to type in within the widget-specific palette. 
Hitting [enter] or clicking somewhere within the properties palette after typing the value saves the value.

Tested with latest build on lab14 with Windows/Chrome

**Comment by jhpedemonte** [comment]
@JonFerraiolo  This one is odd -- would expect the Properties code to save values onblur.  Marking this for M3, for now.

**Comment by JonFerraiolo** [comment]
Wait, I misunderstood the problem. Changing back to M3. 

We've had this bug forever. We need to fix, but users seem to have managed to work around this bug so far.

**Comment by childsb** [comment]
We've added visual editor click-away interception to the other properties palette items, added to widget specific as well.
