### ISSUE TITLE
faster alternative to findResource *.theme

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#645]
With today's build (after Brad's performance fix for findResource *.theme (#603), I'm still seeing between .35 and .4 seconds for the findResource *.theme web request on running Win/FF4 and launching Maqetta on http://localhost. Somehow or other we need to eliminate this time time or at least shrink its size.

Lots of potential ways to skin this cat, but 2 come to mind right now:

(1) We could implement a server-side and client-side caching mechanism where the server stores a list of themes for each workspace somewhere, either in .settings or in a place outside of the user's workspace. Then, at launch time(eg, cmd/getUserInfo), the server could send down the list of themes, and then the JavaScript side keeps its own list and never asks the server again. This approach, like any caching scheme, opens up potential maintenance and reliability issues. As the code evolves, we might not remember to adapt the caching scheme to changes elsewhere in the code.

(2) We could implement a more constrained and faster theme search algorithm. Instead of scanning a hole subtree for *.theme files, we could only search for files that match the pattern ./themes/THEMENAME/THEMENAME.css.

Need to coordinate this fix with #144 (moving *.theme files up on level in hierarchy)

**Comment by peller** [comment]
I vote for #2, but we could do both.

**Comment by childsb** [comment]
Added project settings for theme folder (opened issue #882 to track the implementation of this setting over the entire product).Also added caching mechanism to library request.  So unless the user creates a new theme, this search will only happen once.

A better fix would involve fixing the findResource(*.theme) command to NOT always hit the server (issue #866).  Then theme caching wouldn't be necessary.
