### ISSUE TITLE
Claro theme for user workspace isn't getting built

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#646]
@peller, @childsb, @billreed63, @jhpedemonte

With today's build, I watched the Firebug console, which shows all of the web requests as they happen. With a New HTML file command, we are issuing cmd/loadFile on every CSS file in the claro theme. With Preview 1 builds (and all earlier releases), we were shipping a built version of claro.css.

Note that there used to be a magic flag in the build script that resulted in a minified/built version of claro.css and sketch.css, but preserved newlines to take into account a performance issue that we have with our CSS parser.

**Comment by peller** [comment]
IIRC, we were building these CSS files "by accident" along with the copy of Dojo in davinci.dojo_1_x plugins.  The Dojo build scripts basically crawl the directory and inline all the @import statements, in the Dojo directories as well as in peer directories.  When we created the plugins for Dojo 1.6 and 1.7, we checked in the built (optimized) Dojo and no longer ran the script which did the inlining

**Comment by peller** [comment]
In the process of upgrading Dojo, we need to also upgrade the css in the claro metadata directories, and it should be the optimized version which we check in.

@billreed63: I thought I did this, but I don't see it in the logs.  Didn't you and I have that discussion?   I'm thinking it should be replaced with the built CSS for claro.css concurrent with checking in the plugin itself.

@waynevicknair: I'm thinking re-introducing the build tool is totally unnecessary here, and I'm not even confident that we could inline css without going through the entire Dojo build process, which we don't need anymore for the davinci.dojo_1_x plugins
