### ISSUE TITLE
Unable to create new file in users root from file exploer

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#647]
The root folder is missing in file explorer, so the user is unable to create a new file in the root as described in test plan
file:///C:/Users/billreed/maqetta/davinci.core/WebContent/test/testplan/ExplorerPalette/basic.html

**Comment by JonFerraiolo** [comment]
We didn't have a root folder in Preview 1 either, so the task here is to fix the test plan. Assigning to moi.
