### ISSUE TITLE
Can't change current date on Calendar

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#65]
When a Calendar selected, go to Widget-specific properties and attempt to
change the "value". Calendar widget goes away and console says: Uncaught
TypeError: Property 'getFullYear' of object Mon Mar 30 2011 01:23:26 GMT-0700
(PDT) is not a function

The root cause of this is this line in widget.js:
    dojo.date.stamp.toISOString(value, {selector: "date"});

The "value" that is coming in is a string, but the code assumes it is a Date
object and trying to turn it into a string.  Not sure where to add a check for
this.  Shouldn't it be going through some Calendar-specific code?  I see that
CalendarInput (used for inline edit) creates a new Date() for anything entered
through inline edit.

Aside: ModifyCommand creates a whole new widget when changing a simple
property?  That seems nuts.  Will have to open bug on that.

------- Comment #2 From Adam Peller 2011-03-31 18:24 [reply] -------

The date should probably never make it to RFC822 (toString) format.  It would
be better to keep it as a Date object, but if we're going to use plain text
fields to edit the value instead some sort of calendar control, I'd recommend
using the ISO date format for editing.

**Comment by peller** [comment]
Dates are not being handled properly.  Need to fix this. See #659

**Comment by JonFerraiolo** [comment]
With latest code in advance of Preview 2, we are now roughly at the same level with Calendar date changing as we were with Preview 1. You can type "2011-07-24" into inline edit and the date will change. However, lots of detailed things need to be fixed. Widget-specific property setting isn't working. As Adam says, we should show and accept RFC822 format.

**Comment by peller** [comment]
We should never show RFC822 IMO.  We could accept it, but we shouldn't go out of our way to.

**Comment by JonFerraiolo** [comment]
Oops. I was confused by RFCs. IMO, we should only accept and show only what ECMAScript5 supports (ISO 8601). We should mention this in the help information for inline edit for Calendar. Really, we should validate calendar inline edit values (and the corresponding value in the Properties palette) against ISO8601 with a regular expression for that format. We should do nothing regarding supporting RFC822. 

@childsb
Longer-term, regarding how the UI should really work, whenever we ask the user to enter a date value, we should pop up a calendar widget in the maqetta ui to let the user choose a date. That way, the user doesn't have to type and our code controls the format of the date value.

**Comment by peller** [comment]
yeah, RFC3339 is the subset of ISO8601, of what's used by ECMAScript5, more or less.  There are lots of details, of course, but it's basically yyyy-MM-ddThh:mm:ss

We ought to be able to use a dijit.form.DateTextBox for input to abstract this detail from the user (roughly what Jon is suggesting, I think)  We used to do this, but at the time the properties panel had performance issues and was extremely widget heavy.

**Comment by aerwin** [comment]
--> no milestone to M7

Moving to M7 because tagged with both Prio High and Prio Low.... assuming it's a low? If so, could be moved to M8 or future probably.
