### ISSUE TITLE
Application gets in bad state if delete resource on HTML file that is currently being edited

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#651]
@peller, @childsb, @jhpedemonte

(Bug with Preview 1 code. I expected it's still there in Preview 2 code, but because of delete resource bugs that are currently open, I can't verify this with Preview 2)

(Discovered with Win/FF5)
- New HTML file (e.g., file1.html)
- Add a Button
- In Files Palette using context menu, put mouse over the new file (eg, file1.html) and issue "delete resource" command. As you would expect, you get an "are you sure" prompt, and the file gets deleted and the editor closes.
- New HTML file (same name, e.g., file1.html)

Result=> Exception in console

**Comment by peller** [comment]
please record the exception in the ticket

**Comment by JonFerraiolo** [comment]
Assigning to Brad. Here is the stack track and exception:

```
Resource.js:289 Uncaught ReferenceError: langObj is not defined
dojo.mixin.deleteActionapp/dojo/../davinci/ui/Resource.js:289
(anonymous function):1
dojo.mixin._runActionapp/dojo/../davinci/Workbench.js:754
dojo._hitchArgsapp/dojo/./_base/lang.js:81
dojo.declare.onItemClickapp/dojo/../dijit/Menu.js:212
dojo.declare._onClickapp/dojo/../dijit/MenuItem.js:91
dojo.hitch
```

**Comment by peller** [comment]
This probably isn't the same exception as when the bug was originally reported.  langObj is the localization object (recently added) and it appears it just wasn't initialized.

**Comment by peller** [comment]
ok, now I get this:

```
Uncaught TypeError: Cannot call method 'set' of undefined
dojo.declare.onSelectChildapp/dojo/../dijit/layout/StackController.js:158
dojo.hitchapp/dojo/./_base/lang.js:128
dojo._listener.getDispatcherapp/dojo/./_base/connect.js:27
dojo.publishapp/dojo/./_base/connect.js:274
dojo.declare.selectChildapp/dojo/../dijit/layout/StackContainer.js:174
dojo._listener.getDispatcherapp/dojo/./_base/connect.js:19
dojo.mixin.openEditorapp/dojo/../davinci/Workbench.js:921
dojo.mixin._createFileapp/dojo/../davinci/ui/Resource.js:349
dojo.mixin.createFileapp/dojo/../davinci/ui/Resource.js:330
anonymous:2
dojo.declare._onClickapp/dojo/../dijit/form/Button.js:58
dojo.declare._onButtonClickapp/dojo/../dijit/form/Button.js:64
dojo.hitchapp/dojo/./_base/lang.js:128
```

line 158 is

```
newButton.set('checked', true);
```

and newButton is undefined.  A bit further down the stack in Workbench.js openEditor, line 921, you'll see we're falling into the condition where it thinks the page is still open, so something isn't getting cleaned up.

**Comment by peller** [comment]
taking from @childsb

**Comment by childsb** [comment]
@peller

in Workbench.js there's this method:

``` javascript
    _resourceChanged: function (type,changedResource){
        if (type=='deleted'){
            fileName=changedResource.getPath();
            var tab = dijit.byId(davinci.Workbench._filename2id(fileName));
            if (tab){
                var tabContainer = dijit.byId("editors_tabcontainer");
                // force the editor to close
                tab.editor.isDirty = false;
                tabContainer.closeChild(tab);

            }
        }
    }
```

i traced through the tab closing event (user clicks the X to close instead of deleting the file), and it uses the closeChild(..) on tab container.

Previously the workbench/delete method was just calling removeChild, and the node DOM wasn't getting destroyed.  i haven't checked the workbench code in as it still doesn't work properly ( but it seems closer to correct ).  There still some widget DOM dangling reference.

**Comment by childsb** [comment]
I believe the closeChild(..) wasn't being called since it would prompt the user to close the tab if the resource was dirty. (hence the dirty bit).  Also, theres a resource . removeWorkingCopy(..) call causing a race condition. i'm checking in a fix to that.

**Comment by peller** [comment]
it seems reasonable to call removeChild directly here, since delete has its own prompt to delete the resource.  Should the normal prompt come up to also say that there are unsaved resources?  If so, we'd need a way to undo the delete.
