### ISSUE TITLE
Lightweight build - JARs but no minification

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#654]
@peller, @childsb, @jhpedemonte

At IBM, we have done prototypes of integrating Maqetta into desktop Eclipse and ran into this issue:

---

Also, let me use this email to share with you a problem we had when tried to create a new Feature in Eclipse to share this integration plugin . It seems that when creating the feature some Maqetta Bundle's ANT build files were executed , and in turn they were requesting access to GIT server which gave errors in our machines. 
In the end we ended up not creating the feature patch, and just shared the entire workspace with Jim , so he could demo the integration.
Is there any way to create a maqetta "lightweight" build that can be used during development ? I think a build that doesn't need to minify CSS etc . Just creating the bundles jars .

---

Such a lightweight build would be useful in other scenarios.

**Comment by peller** [comment]
two different issues here... separation from git, and turning off the dojo build optimization stuff which is time consuming, but not network-dependent.  I'm not sure I see the usefulness of turning off the optimizations, except for debugging.  You can do that right now by editing the ant file directly.

**Comment by JonFerraiolo** [comment]
Yes, the request was for "debugging". What was going on is that a team was trying to integrate Maqetta into another application, with regular updates from GitHub (every few days, not continuous updates). Manually editing the build scripts with each cycle was enough of a barrier that they gave up.

This isn't a time-critical request. Just something we should get around to at some point that would provide high value to teams that are integrating Maqetta into some other larger software product. There is likely to be a number of these integration scenarios in the future.

**Comment by peller** [comment]
demoing != debugging.  both are legitimate requests

**Comment by waynevicknair** [comment]
i'm not sure this issue is still valid. the property "lightweight" clashes with the property "debug". and, our use of 'git' is not likely to change any time soon.

@childsb, @jhpedemonte, @JonFerraiolo, @peller,
i propose we narrow the scope of this issue to setting the optimization levels for the dojo build from environment variables or java properties.

**Comment by JonFerraiolo** [comment]
I think we need 2 things here:

1) The ability to build from a local copy of the repository instead of pulling from Git. I believe this feature is now in our build scripts via davinci.releng/build.sh and configuration variable 'maqettaCode'.

2) Some ability to set parameters such that the Dojo build system doesn't run, and instead the build scripts create JARs that have the original/unbuilt source files inside. This is so that developers who are integrating Maqetta into a host application can debug into Maqetta easily to make sure their bridge code works correctly. Therefore, somehow or other we would need to pass a flag into davinic.core/customBuildCallbacks.xml so that the build won't happen if a particular flag is set. As an alternative, we could tell developers to hand-edit customBuildCallbacks.xml as they test/debug their bridge code.

I'll find one of the IBM engineers that ran into these issues and ask for a deeper review, but my feeling right now is to remove the M3 milestone for this issue. Let's hold off a bit before doing that to see what feedback we get.

**Comment by waynevicknair** [comment]
Yep, feature (1) is implemented via the 'maqettaCode' variable.

I agree that it is a good idea to wait on feature (2). Maqetta's performance suffers when we run non-built Dojo. We should tightly control distribution of that kind of build.

**Comment by JonFerraiolo** [comment]
Isn't @childsb implementing (2) today?

**Comment by childsb** [comment]
Issue #1 is implemented for both internal and external (maqettaCode and maqettaCodeInternal env variable). The user can now edit the build scripts or set the DOJO_BUILD=false to disable dojo build.

**Comment by JonFerraiolo** [comment]
Maybe it would be a little better if the environment variable had the 7 letters "maqetta" in it? Such as MAQETTA_BUILD_DOJO=false

**Comment by jhpedemonte** [comment]
Agreed with Jon's last comment: we should namespace all relevant variables.

**Comment by childsb** [comment]
Moved DOJO_BUILD_ --> MAQETTA_DOJO_BUILD
