### ISSUE TITLE
no selection in tree widget

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#657]
No selection being set when choosing a file in tree widget.  this prevents individual context menu items from working

1) right click sample1.html
2) click "delete"  

result : "No files selected"

1) right click sample1.html
2) try and choose "download"

result
download grayed out

1) select 1 or more resources
2) click the "download selected icon

result
No files selected to download

@jhpedemonte

**Comment by peller** [comment]
dup of #628?

**Comment by JonFerraiolo** [comment]
I expect this bug is the result of the same underlying problem for #628, #648 and #538

**Comment by jhpedemonte** [comment]
dupe to #628.
