### ISSUE TITLE
smartinput and property editor should use ISO values for Date types

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#659]
@billreed63, @childsb

e.g. Calendar.value attribute should be serialized to and from an ISO format, like 2011-07-05.  Currently, if you edit the value in the property editor, it will change to something like `Wed Jul 06 2011 00:00:00 GMT-0400 (EDT)` which is browser-specific and does not conform to the Dijit spec -- it will probably work as long as you serialize to/from that same browser.

**Comment by jhpedemonte** [comment]
-> M6/Med

**Comment by peller** [comment]
see also #65

**Comment by JonFerraiolo** [comment]
-> M8 Prio-High

**Comment by JonFerraiolo** [comment]
-> @peller

**Comment by JonFerraiolo** [comment]
-> M8 Prio-Med
