### ISSUE TITLE
Cannot select the tree node in Files palette

### ISSUE THREAD

**Issue by EldonReturn** [maqetta/maqetta#660]
I pulled the latest code from the master.
Click the tree node in Files palette. And you'll find that it is not selected.

**Comment by EldonReturn** [comment]
@peller

Sorry Javier, but It turns out to me that I cannot remove you from the assignees' list when I create an issue.

**Comment by peller** [comment]
I'm unable to reproduce this problem.

**Comment by jhpedemonte** [comment]
@EldonReturn If you are still seeing this issue with the latest code, please provide more information about what you are seeing.

@peller We previously discussed how selected items look in the tree.  With the current code, after selecting, there is only a **blue halo** around the item.  However, if you load http://archive.dojotoolkit.org/nightly/dojotoolkit/dijit/tests/tree/test_Tree.html, you will see that selected items in a tree have a **full widget blue box** around them -- the blue halo only represents which item has the current focus.

**Comment by peller** [comment]
@EldonReturn says he's seeing a general failure of the workbench to load, with only the lib folder and missing a bunch of stuff.  He sees no exceptions in the console or on the server.  I don't think this is related to #628 or focus issues.

**Comment by EldonReturn** [comment]
The workbench loading problem was resolved. I re-installed chrome & FF and it works now. 

However, I'm still experiencing the un-selectable tree node problem with the latest build. No exception is thrown in either the browser console or the server console. The only symptom is that I cannot select the tree node by clicking (the blue square is not shown around the node) and thus I cannot delete the file. But I can select the node in preview 1 build.

See if you can re-produce this problem. My configuration is: Chrome + Linux

**Comment by EldonReturn** [comment]
@peller, I asked my colleague to verify it. It seems this problem only occurs on my machine. So I'd like to close this issue. This backup machine is weird to some extent even after I re-installed Chome and FF. I miss my T61 ;-)
