### ISSUE TITLE
Cannot select mobile widgets sometimes

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#661]
@peller,

(Maybe ScrollableView isn't completed coded yet?)
- New HTML File
- Add ScrollableView
- Add RoundRectList into SV
- Add ListItem into RRL
- Try to select the ListItems - works fine
- Click below ListItems, which selects ScrollableView
- Try to click-select the ListItems
  Result=> Cannot select ListItems on the canvas
  Haven't yet investigated why. Might be a z-index issue?

**Comment by jhpedemonte** [comment]
Possibly related to #590?

**Comment by peller** [comment]
Conflict between overlay div in dojox/mobile/scrollable.js  Disabled the scrolling mechanism in a helper.  Fixed by 9aa897b77c519c53f372d0bb52cbb066593a3304
