### ISSUE TITLE
Copy/paste mobile widgets produces "is undefined" alert

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#662]
@peller

Copy/paste of mobile widgets doesn't seem to be working at all. One scenario:
- New HTML File
- Add View
- Add RoundRectList
- Select one of the ListItem's in the RoundRectList
- Copy
- Paste, and click anywhere on page as the target for the paste
  Result=> Alert comes up 'Cannot read property 'allowedParent' of undefined

I tried Heading and couldn't copy/paste that either.

**Comment by jhpedemonte** [comment]
Related to #224.

**Comment by jhpedemonte** [comment]
This brings up the question of how to handle this with `allowedParent`/`allowedChild`: multiple widgets can be copied at once, so when pasting, the code should go through the array, calling `_getAllowedTargetWidget()` on each type.  If one of the selected widgets fails, then the whole **paste** operation should fail.  Right?

**Comment by JonFerraiolo** [comment]
Yes, entire paste operation should get cancelled. If we manage to produce a reasonable error message, just maybe the user will be able to figure out what happened and how to do whatever he was trying to do.

**Comment by jhpedemonte** [comment]
I'm thinking I need to update `_getAllowedTargetWidget` to work both with a single widget and an array of widgets.

**Comment by jhpedemonte** [comment]
> If we manage to produce a reasonable error message, just maybe the user will be able to figure out what happened and how to do whatever he was trying to do.

I have an error message there now, but I think it needs a lot of work.  I would be open to suggestions.

**Comment by JonFerraiolo** [comment]
Good enough message for now.
