### ISSUE TITLE
[Chrome] SpinWheel inside of View - poof!

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#663]
Maybe SpinWheel doesn't make M2, but if it is in M2, then we definitely need to fix this one.
- New HTML File
- Add View
- Drop SpinWheel into View

Result=> Poof! 

In Mac/Chrome, the Maqetta browser window becomes fully transparent, showing the Mac desktop behind it. If you immediately refresh (such as before auto-save commits the SpinWheel), you might be able to recover, but if the workingcopy gets updated via a PUT request to Maqetta server in background, then refresh will result in the same poof! once the file gets reloaded.

No problem with SpinWheel in Mac/FF5

**Comment by jhpedemonte** [comment]
Not seeing this with build or with files on my system.  I do, however, see that the slot values don't really make much sense (#588).

**Comment by JonFerraiolo** [comment]
Closing this bug. There is clearly a problem on the Chrome side. I was able to reproduce it with my currently running Chrome, but when I restarted Chrome, I couldn't reproduce. I expect Maqetta users will run into this, but there is a workaround: restart Chrome!
