### ISSUE TITLE
TabBarButton inline edit not working

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#666]
@jhpedemonte

Not critical for M2, so definite candidate for M3 instead, but on the other hand might be a quick metadata change.
- New HTML File
- Add TabBar widget
- Double-click on one of the TabBarButton widgets

Result=> Nothing happens.

You can edit the text for the button in the widget-specific section of Properties palette, but we have trained users to use inline edit for everything else.

**Comment by billreed63** [comment]
added inline edit for mobile.TabBar and mobile.TabBarButton

July 2011
