### ISSUE TITLE
Mobile list container widgets should have inline edit such like desktop container widgets

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#667]
@jhpedemonte

If the user drag/drops a RoundRectList (or other *List widget) onto canvas, they should be presented with an inline edit UI just like Accordion, [DropDown]Select, ComboBox, etc, and then Maqetta creates as many list items as the user enters.

I realize this may be somewhat of a challenge to implement. Probably requires helper functions.

**Comment by billreed63** [comment]
already complete in M2
