### ISSUE TITLE
Widget-specific properties show for widget from last unsaved file

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#670]
- new HTML file
- drag button onto canvas
- Close the file without saving
- new HTML file
- Before doing anything else, select Widget-specific from the properties palette
  It will still show the properties for the button though no widgets have been added to the new file.

Testing in Windows/Chrome

**Comment by JonFerraiolo** [comment]
@childsb - probably the fix will come from either Brad or me

**Comment by JonFerraiolo** [comment]
Closing, now fixed.
