### ISSUE TITLE
FilePalette basic tests - theme editor 'alerts' on claro.theme open

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#672]
double click on 'claro.theme' in file tree. editor starts to open and alerts following message:

```
error loading:./themes/claro/claro.themeTypeError: Result of expression '_715[0]' [undefined] is not an object.
```

after clearing the alert by clicking OK, the theme editor finishes opening and behaves correctly.

**Comment by JonFerraiolo** [comment]
@childsb, @peller

I classified this as an M2 bug mostly because it's a regression and this is a feature that is essential for users to open theme editor when integrating Maqetta into RAD for theme editor functionality.

**Comment by peller** [comment]
I didn't see this when I ran the tests on Chrome/Mac

**Comment by JonFerraiolo** [comment]
@waynevicknair: wayne, can you try to reproduce this? I'm not seeing this bug, either. If you can't reproduce, please close.

**Comment by waynevicknair** [comment]
cannot reproduce on Safari 5.0.5 on maqetta-20110713-0902.zip build. closing.
