### ISSUE TITLE
Exception when clicking on Dialog in theme editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#673]
In #598, Javier reports that clicking on Dialog in theme editor causes this:

Uncaught TypeError: Cannot read property 'property' of undefined         WidgetProperties.js:42

I was able to reproduce on Mac/Chrome with latest code from GitHub.

**Comment by jhpedemonte** [comment]
I'm going to put this as **Priority Med**, since it is not a regression (happens in Preview 1).
