### ISSUE TITLE
MobileWidgets-Gray box follows mouse after alert about MobileView if click to add rather than drag to add

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#679]
- new HTML file
- in a mobile silhouette try to add a heading to the canvas by selecting Heading in the widget palette and then click on the canvas to add it (rather than dragging)
- the message will come up saying you need DojoxMobileView
- click OK
- Move the mouse across the silhouette and a gray resizing box will follow the mouse

Nothing truly breaks with this bug. The user can continue on as usual. The gray box just might cause confusion until another widget is added, which makes the gray box disappear.

**Comment by jhpedemonte** [comment]
@JonFerraiolo

Moving this to M2. It'll be confusing to the user, especially since continually clicking on the editor results in the error dialog again.  Hitting **Esc** doesn't reset this.  Only way is to click on a widget in the **Widget** view.

I'm thinking that when I bring up the error dialog, I haven't properly canceled the drag operation.  @peller, any idea on how to do that?

**Comment by peller** [comment]
get rid of the dialog? :)  Ideally, I think we'd provide feedback before dropping.  Not sure exactly how.  We could change the cursor, but that still doesn't offer a lot of information.

**Comment by peller** [comment]
It looks like there's a return in the middle of CreateTool.onMouseUp.  Perhaps the code that resets the tool should still be run... a finally block might work well here.

**Comment by jhpedemonte** [comment]
We'll probably get rid of the dialog in M3 and provide feedback during the **drop** operation, as the user hovers over the page.  In another bug, I had stated that it might be useful to also display info at the bottom of the page, detailing **why** the drop operation isn't permitted at a given target.

But for M2, I didn't want to mess around with all that code -- hence the dialog.

I'll try resetting the tool, see if that fixes it.
