### ISSUE TITLE
Investigate widget.parent

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#681]
@peller, @jhpedemonte, @billreed63

I was looking at Adam's check-in ed70e8909d0de25836b75ba697fbb43ce19d4ae6 and there is a line he added to WidgetProperties.js that says:

```
if (this._widget.parent && this._widget.parent.isWidget) {
```

and I started scratching my head, wondering why I don't remember a 'parent' property on a davinci.ve._Widget. I searched through widget.js and I couldn't find any code that assigns a value to the 'parent' property of a davinci.ve._Widget object, so I did a grep of the ve/ subtree and got these results:

```
$ grep -rn 'widget\.parent' *
VisualEditorOutline.js:188:    widget.parent = parentItem;
commands/ModifyRichTextCommand.js:59:   this._parentWidget = widget.parent; // maybe this
commands/StyleCommand.js:89:  var parent = widget.parent; 
commands/StyleCommand.js:92:  if (/*widget.parent && widget.*/parent.dijitWidget){
themeEditor/VisualThemeOutline.js:124:     subwidget.parent = widget;
widget.js:1627:  var parentNode = widget.parentNode;
widgets/WidgetProperties.js:30:  if (this._widget.parent && this._widget.parent.isWidget) {
widgets/WidgetProperties.js:31:   var parentMetadata = davinci.ve.metadata.query(this._widget.parent);
```

Does anyone know about this 'parent' property? Is it true that it is given a value in the Outline palette logic? If so, that's bad. In the MVC world, the Outline palette should be providing a view of the model (which should only be available via accessor functions) that can be included or excluded and should not be a requirement for the model part of MVC to work, right?

Adam responds:

I didn't add that line.  I only unindented an else section that didn't need to be an else clause.

I guess the first question is, what is '_widget'?  I'm not convinced it's a davinci.ve._Widget.  It seems to get assigned in ViewLite as part of a change event, and it has other properties like 'subwidget'.  I'm guessing it's just a selection from the outline view or some sort?

**Comment by peller** [comment]
confirmed, it's a davinci.ve.dijitWidget

**Comment by jhpedemonte** [comment]
Assigning to Jon for further investigation (what do we do with this issue?).  If there's something that actually needs to be fixed here, then the issue can be reassigned to the proper person.

**Comment by JonFerraiolo** [comment]
Did some research. I'm pretty sure we can move to M4 and that there is indeed some cleanup that is needed that is described below:

Re:
`VisualEditorOutline.js:188:    widget.parent = parentItem;`
Yes, this is bad coding. We should remove this line early in the M4 cycle.

Re:
`commands/ModifyRichTextCommand.js:59:   this._parentWidget = widget.parent; // maybe this
commands/StyleCommand.js:89:  var parent = widget.parent; 
commands/StyleCommand.js:92:  if (/*widget.parent && widget.*/parent.dijitWidget){`
These routines try both widget.parent and widget.getParent(). We should remove the reference to widget.parent from these routines.

Re:
`themeEditor/VisualThemeOutline.js:124:     subwidget.parent = widget;`
This whole file might not be actually used today. See #912

Re: `widget.js:1627:  var parentNode = widget.parentNode;` not applicable to this issue

Re:
`widgets/WidgetProperties.js:30:  if (this._widget.parent && this._widget.parent.isWidget) {
widgets/WidgetProperties.js:31:   var parentMetadata = davinci.ve.metadata.query(this._widget.parent);`
Replace widget.parent with widget.getParent().

**Comment by JonFerraiolo** [comment]
Moving to M5. Haven't noticed any problems. Mainly just a code cleanup as described above and too much risk for too little gain at this stage of M4 cycle.

**Comment by JonFerraiolo** [comment]
Pushing to M6, Prio High to encourage finally closing this stupid bug
