### ISSUE TITLE
Mobile widgets (allowedParents) when using absolute positioning

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#682]
@peller, @jhpedemonte, @billreed63

Interesting dilemma about what to do when in absolute positioning mode and adding mobile widgets to the page.

In absolute positioning mode, we want to provide a simple drawing-tool-like approach where user can build up a UI by simply placing widgets absolutely on the canvas. For what's coming in M3, see https://github.com/maqetta/maqetta/wiki/Drawing-tools. One of the linchpins of existing absolute-positioning in the current code and in the M3 proposal is that new widgets are added as children of the BODY (the new last child of BODY). This provides the expected z-order behavior, where widgets at the bottom of the DOM (and Outline palette) draw on top of earlier widgets.

However, mobile widgets make heavy use of allowedParents. We currently disallow adding various mobile widgets as children of BODY. For example, a Heading has to be a child of a View, ScrollableView or SwapView.

We sort of have a bug now in the current code that makes absolute positioning of mobile widgets sort-of-work some of the time. If you are in absolute positioning mode and drop a Heading over a View, the drop action is considered OK, but the Heading then gets added as a child of the BODY, not of the View.

This requires more thought and investigation, but I think there is a good answer here: continue to enforce allowedParents in absolute mode, and make the new widget a child of its allowedParent instead of BODY.

**Comment by JonFerraiolo** [comment]
Pushing this to M4. This isn't as simple as I hoped. For Dijit widgets, the current default for absolutely positioned widgets (i.e., append as last child of BODY) is a good default for "sketch mode" because Maqetta then works like common drawing tools (e.g., PowerPoint or Illustrator). However, for Dojo Mobile widgets, where almost every app has multiple Views, it would be a better default for the absolutely positioned widgets to be appended as the last children of the current View.

I'm thinking that the best approach here is:
- 1) Add the feature that I have partially implemented where the user can choose the parent widget upon adding a new widget to the page. (Also, need similar functionality for drag/drop rearrangement and paste)
- 2) Add a helper function at the library level which would allow Dojo Mobile specific logic to choose a default parent for the add command, where the helper gets passed the list of allowable parents as an array and whether we are in absolute positioning mode.

**Comment by JonFerraiolo** [comment]
Another factor to consider is the 'width' property for various mobile widgets, such as RoundRectList/ListItem, where 'width' is not set and therefore defaults to "auto". In flow layout and block-level elements, "auto" is pretty much equivalent to 100% and the ListItem extends the full width of the page, but if position:absolute, then "auto" means "as big as the text content". So, absolutely positioning a RoundRectList results in a widget that is only as wide as the text labels (e.g., "Item1" and "Item2"), which is not what users typically want. We could force width:100% onto the UL wrapper element, but this needs more investigation across the full mobile widget set.

Yet another question is what happens when adding a ListItem with absolute positioning into an existing RoundRectList. Seems like that should be disallowed and users should not be able to set position:absolute on a ListItem. Maybe OK to allow RoundRectList to be absolutely positioned down the road, but ListItems are more like subwidgets than real widgets.

Because of the various complexities, this is in risk of getting pushed to M5.

**Comment by JonFerraiolo** [comment]
After trying out various dojox.mobile widgets when in absolute positioning mode, about half of them have major problems with absolute positioning (RoundRectList, Heading, ToggleButton), and about half of them work OK with absolute positioning (e.g., CheckBox and Slider). The ones that are problematic generally set position:relative as part of widget startup, which overrides the position:absolute that we try to stuff in during widget creation.

What I suggest is that we add a new metadata property that says whether the given widget can be positioned absolutely. Perhaps positioning:any|absolute|flow, with default to any. Then set positioning:flow for widgets that don't support absolute positioning.

Postponing to M5 to actually address this issue.

**Comment by JonFerraiolo** [comment]
Pushing to M6 with Prio High

**Comment by JonFerraiolo** [comment]
Actually, things are working a little better now than I expected. Here are some remaining problems:
- Heading appears to defaults to width:100% or width:auto, with result that Heading is way to wide. For absolutely positioning, should default to 300px or something like that.
- Same for RoundRect, RoundRectList, EdgeToEdgeList but opposite result, widgets have near zero widget. Need to default o 300px or something like that.
- *tDataList is messed up in multiple ways. Widget (and SmartInput) are placed initially off screen, position is not set ot absolute, z-index:900 is not applied, initial width is way too big.
- ComboBox is messed up in multiple ways. Widget (and SmartInput) are placed initially off screen, position is not set ot absolute, z-index:900 is not applied.
- Double-click on TabBarButton puts SmartInput at left edge rather than by the widget.
- ContentPane comes in with zero width/height (see issue #2188)
- IconContainer loses it position:absolute setting on creation
- Dragging new IconItem into existing IconContainer makes it a child, but it is incorrectly positioned
- Fixed splitter seems way to big

**Comment by jhpedemonte** [comment]
What about adding a helper for all mobile widgets that sets width/height (depending on values from page) if the page is set to absolute positioning/sketch mode?  Only issue with such an approach is that users wouldn't be able to easily switch between portrait and landscape modes, since dimensions would be fixed.

**updated:** But that might not be such a big issue, since the user is in _sketch mode_ -- shouldn't be considered a live page.

**Comment by JonFerraiolo** [comment]
> What about adding a helper ...

I expect I'll need to use a helper. I haven't dived in to this one yet, but I believe I had to do this for TabContainer and some other Dijit widgets in order to have a different default for absolute vs flow.

> updated: ...shouldn't be considered a live page.

yep

**Comment by JonFerraiolo** [comment]
fixed by bc86f5ed48
