### ISSUE TITLE
New file dialog should allow user to pick initial mobile device

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#685]
@jmockler, @jhpedemonte, @childsb, @billreed63, @peller

We'll probably need to update the New File dialog for M3 for various reasons, and here is one. 

We should allow an author to pick an initial mobile device in the New HTML File dialog so that when the page editor opens for first time, the proper mobile silhouette appears initially. We may also want to offer the ability to indicate whether to start in portrait or landscape view. Maybe both of these settings should be sticky so that subsequent New HTML File actions use the same settings as were used for the previous document.

There is a related feature. We also might want to consider offering an option for desktop user interfaces in New HTML File dialog that allows the author to specify the canvas size, such as 1024x768. See #684.

**Comment by peller** [comment]
Why complicate the new file dialog or provide multiple ways to do the same thing?  It should be simple to change devices.

**Comment by jmockler** [comment]
it should be simple to change devices. But often when a user is beginning a design project, they know at least one of the devices they are designing for. It would be good to start them off in at least on of the resolutions that their design will be displayed in. I like @JonFerriallo suggestion to pick the resolution/device that they are designing for while creating the file.

**Comment by jhpedemonte** [comment]
I'm siding with Adam on this one.  Why add complexity to the new file dialog, when the user can just set the device after the file has been created?  Same for canvas size and any other options.

**Comment by peller** [comment]
and I realize I'll probably lose this one.  I just want to side towards a minimalist UI in general, and I feel we're going in the wrong direction every time we add a button or dialog, especially when there's more than one way to accomplish the same thing.

To me, the question is whether best practice is to design flexible layouts or to pigeon-hole and work on a particular device, Flash-style.  I imagine the former is the web-geek, W3C way, the latter is what most people end up doing in practice.  So many web pages are fixed width for 600px or some such with gutters down the side.

**Comment by JonFerraiolo** [comment]
Fixed by 6f38e9c53a
