### ISSUE TITLE
Smart input on Heading removes any embedded buttons

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#687]
@jhpedemonte
- New HTML File
- Add View
- Add Heading
- Add  ToolbarButton within the Heading
- Double-click on Heading, change text to "aaa"

Result=> ToolbarButton has been removed from the page

My guess is that SmartInput is doing a complete replacement of the inner content for the Heading's DIV, but needs to be smarter and only update the inner elements that contain text content and leave everything else in place.

**Comment by jhpedemonte** [comment]
Heading currently defines this in widgets.json:

``` javascript
"inlineEdit": {
    "property": "label",
    "displayOnCreate": true,
    "supportsHTML": true
},
```

Shouldn't SmartInput only update the **label** prop, and not overwrite **innerHTML**?  Or am I misunderstanding the **inlineEdit** properties?

**Comment by billreed63** [comment]
it should...
