### ISSUE TITLE
dojox.mobile.ComboBox shows gets confused with Smart Input

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#688]
@jhpedemonte

For some reason I can't fathom at this point, dojox.mobile.ComboBox has trouble when you enter a seemingly innocuous set of values.
- New HTML File
- Add dojox.mobile.ComboBox
- Enter the following values:

```
+Alerts
Reports
```

Result=> The ComboBox shows the string "Alert" instead of "Alerts", and if you double-click to re-edit, the "+" that you entered doesn't appear. If you click OK immediately, then the ComboBox text becomes "undefined", instead of (what I would think would be better) an empty string.

Happens on both Mac/Chrome and Mac/Firefox.

**Comment by billreed63** [comment]
regex stripping white s from end of word

July 2011
