### ISSUE TITLE
Can't drag/drop dojox.mobile.ListItems on canvas

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#689]
@jhpedemonte
- New HTML File
- Add a View
- Add a RoundRectList
- Double click on first ListItem, change text to "aaa"
- Double click on second ListItem, change text to "bbb"
- Drop a 3rd ListItem onto the RoundRectList, set text to "ccc"
- With "ccc" selected, try to drag it up between "aaa" and "bbb"

Result=> Can't drag the ListItem on the canvas. (Workaround: users can rearrange using Outline palette)

**Comment by peller** [comment]
What I saw was a little different... you can drag the list item, but it tries to drop it within another list item, which is legal, at least in the generic sense. I even got myself into a situation where I got in an infinite loop by dragging li's, though I haven't been able to reproduce that yet.  

@jhpedemonte: do we want to introduce some sort of restrictions here for li's in RoundRectLists? (would be awkward)  Any other suggestions?

**Comment by JonFerraiolo** [comment]
Isn't it just adding extra logic into DND within the canvas along the lines of what Javier added for when dragging from widget palette onto canvas, honoring allowedParent:

```
            "allowedParent": "dojox.mobile.RoundRectList, dojox.mobile.EdgeToEdgeList",
            "allowedChild": "dojox.mobile.Switch"
```

I'm pretty sure most of the allowedParent logic we have today is in CreateTool.js
