### ISSUE TITLE
Extra SCRIPT element (dojo.js) with each new widget

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#692]
@peller

(Note: used to say "with each new mobile widget", but same problem exists with desktop widgets.)

With each new widget, an extra SCRIPT tag is added to the HEAD. If you have 6 widgets, you get 5 extra SCRIPT tags.

**Comment by peller** [comment]
dojo.js should only be loaded once.  shouldn't mobile widgets be the same as dijits in this regard?

**Comment by JonFerraiolo** [comment]
@childsb

Adding Brad. Brad, did you do the fix to make sure that only one copy of dojo.js and dojo.css were added to a page?

**Comment by jhpedemonte** [comment]
I'm overloaded, reassigning to Brad.

**Comment by childsb** [comment]
Fixed with commit 9918fded5be76cc17615b85e14e1172b5c7839bf
