### ISSUE TITLE
Can't set moveTo attribute for some scenarios with dojox.mobile

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#693]
@childsb

(Maybe Brad can help with this if he gets through his bug list)

I'm working on a simple demo showing how to author a very simple slide-in/slide-out example with Maqetta. Here is what I'm trying to build:

```
View (id='v1')
  Heading (heading label='v1')
  RoundRectList
    ListItem (moveTo='v2')
    ListItem
View (id='v2')
  Heading (back="Back" moveTo='v1')
```

Creating this simple demo is quite difficult due to #686, which makes it difficult to use more than one View on a page. But after working around #686, the next big problem is that changing the 'moveTo' and 'back' attributes in the Properties palette doesn't result in changes to the file you are editing. The only way to set these two attributes when building the sample I describe above is to set the 'moveTo' and 'back' attributes in the source pane.

These attributes are very fundamental to mobile UI authoring. It's pretty much impossible to create anything even remotely realistic without using 'moveTo'. It's the way you switch between views.

**Comment by JonFerraiolo** [comment]
Same problem with 'icon' attribute on ListItem

**Comment by childsb** [comment]
i'm not sure how anything in the widget specific area was working!

the onChange for dijit widgets nor HTML dom elements wasn't bound to the _onChange function, causing the commands to change the values to never be executed.

the value now serializes properly, but i'm not sure what exactly goes there.. (Move to coordinates??)

commit 0ef230aab3a63c19d34511765b11a8197d496640
