### ISSUE TITLE
Setting widget-specific properties doesn't work

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#695]
- new HTML file
- drag button onto canvas
- go to 'widget-specific' in the properties palette
- change the label to 'button-test'
  It doesn't change the button's label.
  If you click on the canvas so that the button is no longer selected and then select it again, you'll see that the label is still set to 'button.'

Tested in Windows/Chrome with this morning's build from lab14.

**Comment by JonFerraiolo** [comment]
@jhpedemonte

Assigned to Brad. Likely this is the same problem as with #693

**Comment by childsb** [comment]
Fixed in commit 0ef230aab3a63c19d34511765b11a8197d496640
