### ISSUE TITLE
100%px

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#698]
@jhpedemonte

I think I found the bug that one of the users at Maqetta.org was reporting last week.
- New HTML File
- Add a DIV
- In Properties palette, go to 'width' property and use dropdown to select 100%. (Notice that after mouse-up on the dropdown menu, the type-in bar is in the edit box for the 'width' property)
- Immediately go to Outline palette click on eyeball for DIV to make it invisible

Result=> 'width' property now has the value 100%px

**Comment by childsb** [comment]
i traced this down to the iframe states.js. 

the states code saves the style for the widget on the widget (in it's own data structure).  the px piece is being added somewhere around this area.  it's not being added in the properties palette.

i'll keep looking into this as time permits unless someone else has a chance to look at it.
