### ISSUE TITLE
Replace "error loading plugins" dialog with something more descriptive

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#70]
Right now, if a user who has a valid appcache reloads maqetta, but the app is
offline, they are greeted with the "error loading plugins" dialog.  We need to
replace this with something better.

"There was an error initializing the application.  The Maqetta application may
be offline.  Please try again later."

**Comment by peller** [comment]
is this still valid?

**Comment by JonFerraiolo** [comment]
Assigning to me to research.

**Comment by JonFerraiolo** [comment]
We've cleaned up this area of code. Closing.
