### ISSUE TITLE
Theme editor and theme switcher warning if opening an old theme file

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#702]
@jhpedemonte, @childsb

Theme editor and theme switcher icon should check to see if the version# in the *.theme file matches the current version of Dojo that is used in the user's workspace, and if not, print a message that warns of potential problems and suggests recreating the custom theme from scratch using the current version of Maqetta and deleting the existing theme.

Ideally, this message would pop up exactly once per theme per session, but if this is too hard, then OK if warning comes up each time user opens an old theme or switches to an old theme.

**Comment by billreed63** [comment]
Added message, ok cancel  that is displayed at bottom of theme switch dialog if theme selected is different version, 
If user selects ok session cookie is added so message will not be displayed again.

Added dialog that is displayed when theme editor is opened if theme does not match dojo version. session cookie is added.

cookie is themeName+version
July 2011
