### ISSUE TITLE
Add support for dijit.form.ComboButton

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#703]
@JonFerraiolo @peller

The docs for [dijit.Toolbar](http://docs.dojocampus.org/dijit/Toolbar) state that it can take any **Button**-based Dijit, including DropDownButton and **ComboButton**.  We support the first but not the latter.

**Comment by jhpedemonte** [comment]
Same goes for **dijit.form.ToggleButton**, another Button-based Dijit.

**Comment by jhpedemonte** [comment]
Assigning to Cindy for now.

**Comment by peller** [comment]
to clarify, this issue is about supporting the widgets, not how they interact with dijit.Toolbar which presently has no restrictions on content in Maqetta

**Comment by jhpedemonte** [comment]
When adding **ComboButton** and **ToggleButton**, make sure to add `"class": "DijitButtons"` to their **widgets.json** definitions.  See 8f9d2ef63be0199597d2e7fdc6003561fcecc042 for an example, using **DropDownButton**.
