### ISSUE TITLE
Migration script Preview1->Preview2

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#704]
@childsb, @jhpedemonte, @billreed63

Just before releasing Preview 2, we need to run a fixup script on all existing accounts at Maqetta.org:
- Delete .settings/libs.settings 
- Add theme library to each users workspace (<library id="DojoThemes" name="DojoThemes" verion="1.7" virtualRoot="themes"/>)
- Just to be extra careful, update .settings/workbenchState.settings to clear out the list of open editors 
- Delete the two themes that have become read-only in M2: ./themes/{claro,sketch}
- Delete the two CSS files that have become read-only in M2: ./themes/{dijit.css,dijit_rtl.css}
- Replace the old maqetta/ folder from M1 with the new maqetta/ folder from M2
- Good to update all existing HTML files in user workspaces to remove the string " lotusui" (leading space in that string)
- Copy the sample_data/ folder from M2 default workspace into existing user workspaces
- Remove all review/commenting sessions (rm -rf ./.review). Apologizies to anyone who has as active review session.
- For all existing custom themes, we need to run a sed script on each themes/<themename>/dojo-theme-editor.html to do the following:
  - Update this line: `<script type="text/javascript" src="../../%root%/dojo/dojo.js" djConfig="parseOnLoad: true"></script>` to this line: `<script type="text/javascript" src="../../../../../../app/static/lib/dojo/1.7/dojo/dojo.js" djConfig="parseOnLoad: true"></script>` (i.e., replace "../../%root%/dojo/dojo.js" with "../../../../../../app/static/lib/dojo/1.7/dojo/dojo.js")
  - Update this line: `<div dojoType="dijit.Calendar" class="dvThemeWidget" datePackage="dojo.date" style="-moz-user-select: none;"></div>` to this line: `<div dojoType="dijit.Calendar" class="dvThemeWidget" datePackage="dojo.date" value="now" style="-moz-user-select: none;"></div>` (i.e., addition of `value="now"`)

We should also have the theme editor and theme switcher icon check the version# on the *.theme file and if less than the currently supported Dojo (i.e., 1.7) then print a warning about potential problems and suggest the user recreate the theme using the current version of Maqetta. I created a separate bug for this: #702

**Comment by waynevicknair** [comment]
added `mass_migration.sh` and `migrate_workspace.sh` to the **internal** **repository** on commit 6f751a5c26cbb989a9032b68c898b072042a7fab in `internal/util/` directory.
