### ISSUE TITLE
setTarget logic not working with mobile widgets

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#705]
@peller, @jhpedemonte

Something happened with a recent check-in. The logic that we have where we mask out most widgets so that mouse events (particularly click) is intercepted by an overlay DIV isn't working on some of the dojox.mobile widgets, with the result that attempting to click-select on those widgets causes the "moveTo" action to happen inside the Maqetta VE.

I will try to track this down today.

**Comment by JonFerraiolo** [comment]
Not a new bug. Was in yesterday morning's build, also.

**Comment by jhpedemonte** [comment]
Where is the code that puts the overlay DIV?

**Comment by peller** [comment]
I think it's `this._feedback` in davinci/ve/tools/_Tool.js

**Comment by JonFerraiolo** [comment]
Incidentally, I think I've figure out the ins and outs for _setTarget. I'll add comments to the code to document what I've learned. Still working on this bug, though.

**Comment by jhpedemonte** [comment]
Whatever we come up with needs to work for the following scenario:
- Drop mobile View.
- Drop Heading into View.
- With Heading selected, in Properties->Widget specific, set "back" to "view2".
- Drop ToolBarButton into Heading.

Should be able to select Heading and ToolBarButton.  But clicking on the back button labeled "view2" should have no effect.
