### ISSUE TITLE
dojox.mobile.ComboBox preview exception when inside RoundRect with LABEL

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#706]
@billreed63, @peller, @jhpedemonte

Jon to investigate. Maybe a dojox.mobile bug?
- New HTML File
- Add RoundRect
- Add LABEL inside of RoundRect
- Add dojox.mobile.ComboBox inside of RoundRect. (RoundRect now has a LABEL and ComboBox inside)
- Preview in browser
- Click on ComboBox to try to bring up menu

Result=> Uncaught TypeError: Cannot call method 'query' of undefined - dijit/form/_AutoCompleterMixin:261

The above steps work if you don't include the LABEL

**Comment by JonFerraiolo** [comment]
BIll, giving this to you, at least for starters. What I think I'm seeing is that if you follow the directions above, the DOM looks like this immediately after dropping the ComboBox:

```
DIV (RoundedRect)
  LABEL
  SELECT (DataList)
  INPUT (ComboBox)
```

but after SmartInput, things gets reordered to look as follows:

```
DIV (RoundedRect)
  LABEL
  INPUT (ComboBox)
  SELECT (DataList)
```

Somehow or other things are getting reordered in the DOM. I traced through some of the code, but maybe SmartInput is involved, and Bill knows that code better than me.

**Comment by billreed63** [comment]
changed the combobox create tool to always place data list  the first element under the body tag. The DataList must be parsed and created by dojo before combobox attempts to use it.

I still see and issue with the combobox jumping in front of the label after editing issue #728, but this is a more wide spread bug than just combobox

July 2011
