### ISSUE TITLE
Widget dijit.Menu has name "ContextMenu" <-- confusing

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#707]
The Dijit widget **dijit.Menu** has the short name of **ContextMenu**.  While working as a context menu is one of its functions, it isn't the only one (see http://docs.dojocampus.org/dijit/Menu).

This name might be confusing for users looking for the dijit.Menu widget.  Should probably just be renamed **Menu**.  Do you guys agree?

@JonFerraiolo @peller

**Comment by JonFerraiolo** [comment]
Yes, I agree with the proposed change.
