### ISSUE TITLE
yui calendar widget doesn't work

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#710]
1) create a new html file
2) add a YUI calendar widget
3) observer that only a div shows up
4) try and close the file
5) "win is null" error

**Comment by JonFerraiolo** [comment]
@waynevicknair

Javier, a build issue, right? Maybe reassign to Wayne? Or is this a dupe?

**Comment by waynevicknair** [comment]
the 'gnat.dojo.reliam.com' external builds have included the jquery and yui widgets since 6/17/2011.

**Comment by JonFerraiolo** [comment]
YUI calendar works for me on latest nightly build on maqetta.org/nightly, so closing this.
