### ISSUE TITLE
Ask dojox.mobile team why theme CSS files set BODY visibility:hidden

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#712]
@peller, @billreed63, @jhpedemonte

The dojox.mobile theme files include BODY { visibility:hidden; } only to turn visibility:visible within JavaScript. Pretty sure this is to minimize flicker, but it messes up Maqetta and caused bug #700 (for which we submitted a workaround).

**Comment by JonFerraiolo** [comment]
Adam, could you please draft an email to the dojox.mobile developers and cc Javier, Bill and me? Also, I thought there was one more "ask the dojox.mobile team" issue but I haven't been able to find it.

**Comment by peller** [comment]
Haven't heard back yet, but it seems like with the workaround, this shouldn't be an M2 issue.

**Comment by peller** [comment]
The answer is to prevent unformatted text from appearing at page load time.  Our workaround appears to be working.

**Comment by JonFerraiolo** [comment]
OK to close this?
