### ISSUE TITLE
Duplicate iphone.css files in user iframe

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#713]
I hope this one is very easy to fix. If not, OK to postpone to M3.

Do the following:
- New HTML File
- Add RoundRect
- Switch to iPhone silhouette
- Go into debugger and look at HEAD for inner iframe container the user's HTML doc

Result => 2 LINK elements for iphone.css. One has href="lib/.../iphone.css". The other has "./lib/...iphone.css"

**Comment by billreed63** [comment]
issue resolved by #460
