### ISSUE TITLE
Create new file results in type error in debugger

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#715]
- new HTML file
- go into debugger
  The console gives the following error: TypeError: Cannot call method 'removeChild' of null

I noticed this with my latest pull from git this morning.
Testing in Windows/Chrome

**Comment by billreed63** [comment]
removed extra removeChild on loading div

**Comment by jhpedemonte** [comment]
Commit e49c3e8a274f7ffc6907
