### ISSUE TITLE
Double-click on (read-only) claro.theme brings up theme editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#716]
@billreed63

If you go into Files palette and double-click on claro.theme or sketch.theme, the theme editor comes up. That's a good thing to do down the road once we instrument the theme editor to deal with read-only themes (so theme editor comes up in view-only mode), but we don't have that today, and we have instrumented the "Open->Theme Editor" command to only allow users to open cloned themes.

For short term, maybe we should add a check to Files palette to see if file is read-only and post an error dialog telling users sorry cannot edit a read-only file.

**Comment by childsb** [comment]
Right now if you try and modify the values in the prop palette, you're prevented with the prompt "Can't modify read only theme", preventing the user from modifying this theme.  So it's in "read only" mode.

Another feature/option that I recently implemented allows the user to only save the modified files in their workspace.  So a user could open a read only theme, and as they make changes/save the theme, the server auto-magically saves only the changed files to their workspace.

I assume the current read only prompt is adequate and closing the issue.  if we want to beef up the feature (selective file saving) i would suggest moving to another milestone for safety.
