### ISSUE TITLE
Heading and "allowedChild: HTML" : Outline shows DIV and SPAN children to Heading

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#717]
**dojox.mobile.Heading** can take HTML children, according to [examples](http://docs.dojocampus.org/dojox/mobile/Heading).  For example:

``` html
<h1 dojoType="dojox.mobile.Heading" align="center">
  <table cellpadding="0" cellspacing="0" style="width:100%;"><tr>
  <td><div dojoType="dojox.mobile.ToolBarButton" class="mblDomButton mblDomButtonPlus_2"></div></td>
  <td align="center"><div dojoType="dojox.mobile.TabBar" barType="segmentedControl" style="margin:auto;">
    <div dojoType="dojox.mobile.TabBarButton" selected="true" style="width:80px">Search</div>
    <div dojoType="dojox.mobile.TabBarButton" style="width:80px">Directions</div>
  </div></td>
  <td align="right"><div dojoType="dojox.mobile.ToolBarButton" icon="images/tab-icon-15h.png" style="float:right;"></div></td>
  </tr></table>
</h1>
```

However, when adding Heading to page, the **Outline** view shows **DIV** and **SPAN** children for Heading, which isn't correct. (Well, those children are there in the DOM, but they aren't Maqetta-managed widgets.)

Issue is in `Context.attach()`, which has this code:

``` javascript
if(widget.isHtmlWidget || widget.acceptsHTMLChildren || (isContainer && (widget.isGenericWidget || widget.isOpenAjaxWidget))){ //TODO: need a better test for ContentPane
        // Plain HTML content here.  Recurse on all tags
        dojo.query("> *", widget.containerNode ||widget.domNode).map(davinci.ve.widget.getWidget).forEach(this.attach, this);
}else{
        // Recurse down widget hierarchy
        dojo.forEach(widget.getChildren(true), this.attach, this);
}
```

If Heading has `"allowedChild": "HTML"`, then `acceptsHTMLChildren` will be `true`, and the code takes the first branch above, which calls `davinci.ve.widget.getWidget()` on each DOMNode child of Heading.

Here's what I don't understand:  `davinci.ve.widget.getWidget()` creates a "managed" widget object for the given nodes (adding the `_dvWidget` property to the object, which denotes a "managed" widget).  But I don't understand why this is so.

Any widget that gets added to page (whether Dojo or HTML) becomes "managed".  So it should just be fine to traverse through the children, looking for an object that has the `_dvWidget` prop.  Instead, in this case, we create managed widget objects for the child DIV and SPAN of Heading.

(In fact, that's what the 2nd branch of the code above does:  it calls `widget.getChildren()`, which iterates over children looking for an object with `_dvWidget` prop.)

So, before attempting to change the code in `Context.attach()`, I want to understand why it is the way it is.  Do you guys have any idea?

@JonFerraiolo @peller @childsb

**Comment by jhpedemonte** [comment]
@JonFerraiolo @peller @childsb Pinging again -- do you guys have any idea about the above?  Wondering why the code is like it is.

**Comment by JonFerraiolo** [comment]
The code in attach() that you are asking about above looks generally good to me as a serviceable short-term hack, but probably needs to be cleaned up at some point. Fixing this code would be risky and we would need a good chunk of time for lots and lots of testing. If we can push off to M4, that would be good.

If IF part is meant to look for widgets that can take HTML children, the ELSE part is for widgets that can only take dijit children. Obviously, this is Dojo-specific code in the main body of text in the product, and that's not good. Your proposal to just traverse through children and look for _dvWidget sounds like something to try.

Note: I just added a Heading and I don't see DIV and SPAN children. Are you thinking about changing Heading metadata to allow HTML children and if you make that change then DIV and SPAN children will appear in Outline palette?

**Comment by peller** [comment]
so getWidget() has a _major_ side effect.  It's what makes the widget managed, IIRC.  Probably not the greatest name for that method.

**Comment by JonFerraiolo** [comment]
Yeah, good point. This is one of the reasons why I'm hesitant to change this code if we can avoid it in short-term. Changing the logic might end up pulling on a string. My instincts are that we need to do an overhaul of the createWidget code (which gets called _twice_ for each new widget, doing different things with each call) and change getWidget to not have this side-effect.

**Comment by jhpedemonte** [comment]
This doesn't seem to happen any more. Not sure what changed; closing.

Further discussion on `getWidget()` at #750.
