### ISSUE TITLE
Exception in built version running tutorial in _updatePickerLocations

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#718]
@jhpedemonte

I pulled down today's build and tried to go through our standard tutorial using Win/FF and Win/Chrome, and on both browsers I ran into an error when adding a CombBox widget to the page. In Win/FF5, I got an exception in _updatePickerLocations because 'col' is undefined (second line the routine, I believe). The stack trace shows this is coming very indirectly from _updateCascadeList.

Happens in unbuilt code, too.

To reproduce:
- New HTML File
- In Properties palette, show "Fonts and Text" pane
- Add a dijit.ComboBox to page

Result=> Exception as outlined above

Note: exception only occurs if "Text and Fonts" section of palette is visible. I'm not sure why, but Background and Border are OK even though those palettes have properties that bring up the color picker.

**Comment by childsb** [comment]
Fixed with commit cfde61d394e5a384edc9f06f51cf5ecdb5cbf6e5
