### ISSUE TITLE
Calendar widget exception when dragging 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#719]
Select the Calendar. There should be resize handles for both Width and Height and the Width and Height properties should be enabled on the Properties palette. Change both the width and the height on the Properties palette. You will get a prompt asking ok to change global CSS rule. Answer yes.
Select the Calendar. The Position property should say either "relative" or "static". Try to move the widget on the canvas. It should snap back to its original position.

the following exception in console

Uncaught TypeError: Property 'getFullYear' of object 2011-07-13 is not a function

**Comment by peller** [comment]
See also #65, #659, #668

**Comment by peller** [comment]
can no longer recreate this. perhaps it was fixed by 17d36204c867c3e85526ae3f234e24e07d330328
