### ISSUE TITLE
Define inline-edit for dojox.mobile.SpinWheelSlot

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#730]
Need to define the inline-edit for SpinWheelSlot
Can be either a range of numbers (using properties labelFrom and labelTo) or an array of strings (i.e. ['A', 'B', 'C'])

**Comment by billreed63** [comment]
Added smart Input  SpinWheelSlot, also fixed SpinWheel create.

July 2011

**Comment by JonFerraiolo** [comment]
Reopening. With latest code from github on Mac/Chrome, I added a View, then added a SpinWheel, and then dragged/dropped a SpinWheelSlot onto the SpinWheel. Smart input shows this content: 

```
[,',A,',,,',B,',,,',C,',,,',D,',,,',E,',]
```

instead of

```
A,B,C,D,E
```

**Comment by billreed63** [comment]
Wrong format for spinwheelslot in widget.json
