### ISSUE TITLE
dojox.mobile.Button missing btnClass from base class

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#736]
@peller, @childsb, @jhpedemonte, @billreed63

In Maqetta, the bug is that for dojox.mobile.Button, property btnClass value is not persisting across save, close, reopen. Steps to reproduce:
- New HTML file
- Add View
- Add mobile Button
- Under Widget-Specific, set btnClass to 'foo'
- Save, close, reopen

Result=> In Properties palette, btnClass is empty even though source view shows btnClass="foo".

Note: the other widget-specific properties for dojox.mobile.Button work across save and reopen.

Poking through the code and tracing things in the debugger, I'm pretty sure the problem is that none of the base classes (e.g., dojox.mobile.Button) includes btnClass, so the parser doesn't convert attribute 'btnClass' into a property at run-time.

Therefore, assigning to Adam to work with dojox.mobile team on this (hopefully trivial to fix) issue.

**Comment by peller** [comment]
btnClass, while noted in the [1.5 documentation](http://docs.dojocampus.org/dojox/mobile/Button), does not seem to be in the Button.js code.  I filed a [ticket at Dojo](http://bugs.dojotoolkit.org/ticket/13474) about this, which I'll monitor.  I'll take this out of the button metadata.
