### ISSUE TITLE
ListItem should have isContainer:true, allowedChild:Switch

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#738]
@billreed63, @peller

(Temporarily classified as M2 so that it gets its day in court, but if too difficult or risky for M2, then M3)

There is an example in https://docs.google.com/document/pub?id=1lzdeIsZBMyU18t-Z4L8z6fqGkgJPnP9Aa29RZflYV9E#h.aeva9ex1ln7g that shows a Switch as a child of a ListItem. This seems like a common UI design scenario and we should support it. But there are some small-to-medium-level complexities to supporting it:
- Need to change widgets.json for ListItem to have isContainer:true, allowedChild:Switch. (The isContainer:true probably isn't dangerous so long as we allowChild only set to a specific list, such as [Switch])
- Need to research and/or ask dojox.mobile team whether other widgets are possible as children of ListItem
- We probably have to move the text content for the ListItem into a child text node instead of label attribute
- When Switch is a child of ListItem, we need to add class mblItemSwitch to the Switch (adjusts position on the Switch). Sounds like we need a create helper on Switch to pull this off. 
- (Testing) We have to make sure that inline edit shows the full innerHTML including any markup for embedded Switch elements
- (Testing) One thing I'm not sure about is whether when Modify*Command happens from changes on Switch or ancestors, will the right things happen on widget recreation? I think so, but we would want to test changing IDs on the Switch and parents to see what happens.

**Comment by JonFerraiolo** [comment]
Reopening. I just sync'd and the following steps did not work on Mac/Chrome:
- New HTML File
- Add a View
- Add RoundRectList
- Try to drop a Switch onto a ListItem

Result=> Error dialog appears that says "The action was interrupted by an internal error."

**Comment by JonFerraiolo** [comment]
Actually, the error dialog appears whenever dropping a Switch - no matter if dropping into ListItem or not

**Comment by jhpedemonte** [comment]
Not seeing this with latest code (b13b67ee35d0084a3ecfdf40732b25eabc3921a6) on Chrome/Mac.
