### ISSUE TITLE
Exception when adding extra TabBarButton to TabBar via inline edit

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#742]
@jhpedemonte
- New HTML File
- Add View
- Add TabBar widget
- When inline edit comes up upon widget creation, add ",abc" to end of inline edit so that there are now 4 values entered

Result=> 

```
app/dojo/../davinci/ve/widget.js:1440  Uncaught TypeError: Cannot read property 'prototype' of undefined
```

What's curious is that the metadata object seems to be pointing to a dijit.form.button instead of a dojox.mobile.TabBarButton

**Comment by billreed63** [comment]
I was reusing ToolbarInput.js which declares the childtype
instead od retrieving from metadata. For M2 I created a new
TabBarInput.js that declares the correct child class. Issue #743 is
for the proper fix for M3

**Comment by billreed63** [comment]
July 2011
