### ISSUE TITLE
Box around widget stretches too far if at end of canvas in firefox

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#747]
- new HTML file
- drag Calendars onto the canvas until the last requires for the canvas to lengthen (4 total calendars for me)
- scroll down and you'll see that the box around the last calendar you dropped onto the canvas will stretch far beyond the calendar widget.

If you select another widget on the canvas, the canvas will get shorter to fit the widgets but if you click the last calendar widget again, the canvas will lengthen again to accommodate the over-sized box around the final calendar widget.

Tested on latest lab14 build with Windows/Firefox. 
It doesn't seem to occur in Safari or Chrome.

**Comment by JonFerraiolo** [comment]
No urgent to fix this

**Comment by peller** [comment]
cannot reproduce this

**Comment by JonFerraiolo** [comment]
I tried to reproduce also using Win/FF (which was the browser where bug was reported) and I cannot reproduce either.
