### ISSUE TITLE
tab container broken

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#748]
- new HTML file
- drag tab container onto canvas
  In debugger it gives the error: Uncaught TypeError: Cannot read property 'nodeType' of null

-try to drag button onto canvas
Maqetta gives the error: The action was interrupted by an internal error.
In debugger it gives the error: Uncaught TypeError: Cannot read property 'className' of null

Tested in Windows/Firefox and Chrome with latest lab14 build.

**Comment by jhpedemonte** [comment]
Cannot recreate.  Tested on Chrome and Firefox on Mac, using:

> Version: Preview 2
> Date: Jul 20, 2011 3:19:04 PM
> Build: cabe58f791f11f2...

**Comment by cindyskach** [comment]
Looks like it got fixed today. I pulled the latest build, and I'm no longer getting the error.
