### ISSUE TITLE
moveTo not working for mobile *DataList widgets

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#749]
@jhpedemonte, @peller

I just tried the newly committed support for RoundRectDataList. I created 3 View elements with IDs v1, v2, v3, and put a Heading at the top of each View where the heading text was v1, v2, v3. Then on View v1, I added a RoundRectDataList and entered the following into smart input:

aaa,v2
bbb,v3

and then ran preview-in-browser. When I clicked on the "aaa" item, I should see a slide-out/slide-in transition from View v1 to View v2, but nothing happens. I haven't dug in deeper to determine if this is a Maqetta problem or a dojox.mobile problem.

**Comment by billreed63** [comment]
need to strip leading white space from view name
