### ISSUE TITLE
Download from Files Palette broken

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#752]
- select sample1.html in Files Palette
- right click it and select download
  The dialog shows that the proper file will be downloaded into the zip file. However, after selecting "download now" and opening the zip file, it's empty.

Tested with latest lab14 build on Windows/Firefox

**Comment by JonFerraiolo** [comment]
I did a quick test on my Mac running Maqetta from Eclipse in developer mode, using both Mac/Chrome and Mac/FF, and in both cases a download.zip file was created and existed in my browser Downloads folder, and that ZIP contained the proper file. However, haven't tried to reproduce on Win/FF using the built version of the product.

**Comment by JonFerraiolo** [comment]
Cindy, you sure this is broken? I just tried to reproduce with the latest build running on Win/FF5 and it worked for me. Maybe we need to talk on phone to walk through the exact steps? Maybe you are doing something a little different than I am doing.

**Comment by cindyskach** [comment]
Talked with Jon. It's a Windows issue. The solution is to use a third-party zip utility rather than the built-in Windows Explorer function to open the archive. I was able to access the file with 7-zip.

**Comment by childsb** [comment]
encountered this bug while testing on windows/FF as well, so went ahead and fixed it in commit d03722a92ab63bcf9c374af29eb0aa915294b5fa

Turns out all our paths were zipped with the prefix ./, which was harmless on unix (and other unzip utils) but didn't work with the windows default archive utility.
