### ISSUE TITLE
Copy and paste in source editor errors if spacing not precise

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#754]
- new HTML file
- drag div onto canvas
- drag button and textbox onto canvas
- In source editor copy the entire line containing the textbox and paste on new line just below it so that it's in the div as well.

This works. 
- Erase the spaces in front of the input textbox tag
- Select the textbox on the canvas. It gives the error: Index or size is negative or greater than the allowed amount" code: "1

This is a minor thing but if a user doesn't heed the white space in the source editor, it could break and cause confusion.

Tested on Windows/Firefox and Chrome.

**Comment by JonFerraiolo** [comment]
-> @peller M7/Prio-Low, if time permits, please review and see if bug still exists.

**Comment by peller** [comment]
error no longer occurs
