### ISSUE TITLE
Absolute positioning problems with containers

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#756]
While this isn't a pressing issue, I noticed some problems with absolute positioning while performing VE Part 2 tests.
- new HTML file
- switch layout to absolute positioning
- drag accordionContainer onto canvas
  - accordionContainer should probably not have width and height of 100% but 200px
- drag a TitlePane within the AccordionContainer
  - it looks like it'll be a child of AccordionContainer but it's a sibling
- in the outline palette make it so that the TitlePane is a child of AccordionContainer's first ContentPane
  - you'll have to drag the TitlePane to its desired place since it retains the positioning properties from when it was first dropped (the "top" and "left" positioning values relative to the canvas rather than its new parent)
- drop button within the TitlePane
  - Again it looks like it'll be a child, but it's a sibling
- in the outline palette make it so that the button is a child of the TitlePane
  - the button will not be visible within the TitlePane due to its current absolute positioning properties, so the button's position must be changed by the user for the canvas to have the desired appearance

While I'm not sure we'd want to implement automatic parent and child work when dropping widgets onto the canvas since we can't be sure whether the user wants it within the container or just on top (for whatever reason), it might be useful that when the user makes a widget a child of another widget in the Outline Palette that the code resets the positioning to left: 0 and top:0 so that there's less chance of a widget not being visible when the change is made.

**Comment by jhpedemonte** [comment]
Assigning to Jon for now, so he can decide the best course of action here.

**Comment by JonFerraiolo** [comment]
@billreed63, @peller

Good job pointing out these problems, and good call assigning this to me. I had already put all of the above things on my own mental list of things to address as part of "drawing tools", but good to have them listed in a bug report. One thing we may need to collaborate on is the (current) width/height default of 100%. I think we need to put width/height for container widgets as part of the smart input UI because sometimes 100% is exactly what the user wants, but other times not. And maybe we need different defaults when creating for a flow versus absolute.

**Comment by JonFerraiolo** [comment]
This will probably get deferred out of M3, but leaving as M3 for time being.

**Comment by JonFerraiolo** [comment]
Won't be able to address these issues for M3. Pushing to M4. Note that one thing that will help is turning on the feature I have prototyped which allows a user to choose the target parent upon dropping a new widget.

**Comment by JonFerraiolo** [comment]
I fixed all of this when I redid the parenting logic. Now, even in abs posn mode, dropping onto a parent makes the new widget a child of that parent.
