### ISSUE TITLE
Datagrid inline edit - support embedded markup

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#76]
DataGrid can support HTML, http://dojotoolkit.org/reference-guide/dojox/grid/DataGrid.html 

IMPORTANT INFORMATION about Formatting and Security¶
Preventing cross-site scripting (XSS) attacks
To avoid cross-site scripting (XSS) attacks, the grid will escape any HTML data that comes from an external source (datastore). This escaping also applies to any values that are returned from a custom get function on a cell. If you would like to format your data using HTML, you should create a custom formatter function for the cell and apply your formatting there instead.
Site developers who can guarantee that their data is safe can add a formatter function to convert all &lt; back to < if they need the datastore information parsed by the browser.
Finally, you can use the escapeHTMLInData option - however, this is VERY HIGHLY DISCOURAGED as it opens your application up to XSS attacks

The use of the "formatter" requires that we add a javascript function to format the item:

&lt;script type="text/javascript"&gt;
  dojo.require("dijit.dijit");
  dojo.require("dojox.grid.DataGrid");
  dojo.require("dojo.data.ItemFileWriteStore");
  dojo.require("dojo.parser");

  function my_formatter(item){
  debugger;
  return item.label;
  }
 &lt;/script&gt;

&lt;table dojoType="dojox.grid.DataGrid" escapeHTMLInData="false" 
  jsid="grid" id="grid" 
  store="jsonStore" query="{ label: '*' }" rowsPerPage="20" rowSelector="20px"&gt;
  &lt;thead&gt;
   &lt;tr&gt;
    &lt;th field="_item" formatter="my_formatter" width="300px"&gt;Country/Continent Name&lt;/th&gt;
    &lt;th field="type" width="auto"&gt;Type&lt;/th&gt;
   &lt;/tr&gt;
  &lt;/thead&gt;
 &lt;/table&gt;

The use of the escapeHTMLInData  is consistent with the way the rest of the widgets handle HTML, easier to implement and for the end user. 

I don't see the use of escapeHTMLInData being a security issues with the mockups we generate, does anyone else?

**Comment by billreed63** [comment]
Regarding XSS attacks, if the author turns on HTML markup whenever data comes from an external data store, we should post a warning dialog about this (Something like: Warning - There is a potential security vulnerability when allowing injection of HTML markup that comes from a remote data store. You should only allow HTML markup when the remote data store is trusted.).

**Comment by billreed63** [comment]
Added escapeHTMLInData parm to DataGrid and extra lodgic in DataGridInput to support

May 2011

**Comment by billreed63** [comment]
Review by @peller
To test this feature:
- drop a DataGrid widget on the page
- When inline edit is displayed replace:

```
ID,Label
1,Label 1
2,Label 2
```

with

```
ID,Label
1,<input type="submit" onclick="alert('Hi');" style="background-color:red;"></input>
2,Label 2
```
- click the HTML Markup radio button
- click Ok Button

Result: The data grid should display a red submit button in the first row under the Label column.
Now preview the page, in the preview click on the red button in the data grid. You should be presented with and alert box with the test "Hi".Click ok. Close the preview window.
- Double click on the DataGrid in PageDesigner
- Click the Plan text radio button, then click ok

Result you should now see the Raw HTML in the first row under the Label column of the data grid. Click on preview this time you should see the HTML text in the cell where the button was last time.

You are done, have a cold one!

**Comment by peller** [comment]
+1
