### ISSUE TITLE
Files palette shows duplicate files after upload

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#761]
@childsb

Reproducible on both Mac/Chrome and Mac/FF. Assigning to Adam since he is on front-end of this bug, but might be more of a Resource.js issue.
- Add a new folder to the workspace (e.g., "aaa/")
- Select the new folder
- With mouse over new folder, issue an "Upload" command
- In dialog that comes up, find a folder on your system with 4 image files (e.g., *.png) and select the 4 image files, and then click on the button to upload. Then close the dialog
- In Files palette, open up the new folder ("aaa/").

Result=> I'm seeing 7 entries instead of 4. The last 3 files are listed twice each. If you refresh the browser, the Files palette now only shows 4 files (which of course is correct).

**Comment by peller** [comment]
The code is largely as it was before.  I just migrated to the new & slightly improved upload control which supports the multiple upload.  I suspect the problem has something to do with the callback which creates "localOnly" resources in the resource tree, while there also appears to be a call to listFiles to get the list from the server.   @childsb, should we still be adding the files to Resource locally like this?

Possibly related: we should also have code which prevents uploading a file where that filename is already present.
