### ISSUE TITLE
Modify libraries not working in this case

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#762]
@jhpedemonte

I brought up Modify Libraries and tried to simultaneously move things as follows:
- Dojo: /lib/dojo/ => /lib2/dojo/
- Themes: themes/ => /lib2/themes/

I clicked on OK and the dialog did not go away. I clicked on "x" for dialog to close it. It seems like only part of the operation succeeded. There is a /lib2 folder, but the dojo folder appears both under /lib/dojo and /lib2.dojo

**Comment by childsb** [comment]
Fixed the UI problem with commit b538646a3563321307d056b199bb7c3b826106d2

There is a larger issue around changing the /themes directory through this screen.  Many spots in code assume /themes for themes.  I've opened issue 882 to track.
