### ISSUE TITLE
Landscape mobile preview has icon to switch to landscape rather than portrait

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#763]
- new HTML file
- change to the iPhone silhouette
- switch to landscape
- preview in browser

The arrow-icon to switch between portrait and landscape is set up to change the view to landscape even though it's already in landscape. If you click it, it shows the animation for switching to landscape and remains in landscape. So if the user previews with the device set for landscape, he has to click the arrow twice to switch to portrait.

Tested in Windows/Firefox 
Version: Preview 2
Date: Jul 21, 2011 7:02:02 AM
Build: 09fca203d8fe228...

**Comment by JonFerraiolo** [comment]
I'll try to fix this for M2 if other bugs are still pending.

**Comment by JonFerraiolo** [comment]
Fixed by d70e84ee67e4b3f90040 (not sure why GitHub didn't close this bug automatically)
