### ISSUE TITLE
Outline missing icon decorations

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#765]
I'm guessing because of the tree changes by @peller that the decorations on the items in the Outline view are missing.

Here's Preview 1:
![Preview 1 Outline View](http://i.imgur.com/XDo2L.png)

And here's the current state:
![M2 Outline View](http://i.imgur.com/91yzs.png)

Adam, if you can, would be good for M2, since it's a regression.  But if it's too risky a fix or too involved, we may push off to M3.

@JonFerraiolo

**Comment by jhpedemonte** [comment]
This may only be an issue on my machine, as no one else is seeing this.

**Comment by peller** [comment]
Sorry for the late reply.  My github mails seem to be on an 8 hour delay :-(   The outline view is actually Phil's original tree subclass.  It's the only one I didn't try to replace, because of the toggle functionality.  It still may have been impacted by the 1.7 upgrade, but as you mentioned, I don't see this particular problem.

**Comment by jhpedemonte** [comment]
So if I load up a build, I see the icons.  But I've cleared everything (cache, cookies, site data) and I still don't see them when running from source.

**Comment by JonFerraiolo** [comment]
I just pulled down latest from GitHub, cleared everything (cache, cookies, site data), closed my Eclipse server, deleted my user workspace, restarted my Eclipse server, and then sent the browser to http://localhost:NNNN/maqetta, and I see the icons after opening Sample1.html. I tried both Mac/Chrome and Mac/FF5

**Comment by jhpedemonte** [comment]
Yeah, I did the same, but still see the problem.  Not sure what's going on, but it's completely on my end, so closing this bug.
