### ISSUE TITLE
EdgetoEdgeDataList eats the letter "s"

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#766]
- new HTML file
- drag View onto Canvas
- drag EdgetoEdeDataList onto Canvas
- In inlineEdit change "transitionToPage" to something containing an 's' like "secondView"
- Click OK
- Double-click on the EdgetoEdeDataList

It now contains:
Label1, econdView
Label 2, transitionToPage

This is likely a regexp thing.

Tested in Win/FF
lab14 build:
Version: Preview 2
Date: Jul 21, 2011 7:02:02 AM
Build: 09fca203d8fe228...

**Comment by cindyskach** [comment]
It looks like only "s" at the beginning and end of the string are eaten like "sos" => "o" while "12s34" => "12s34"

**Comment by billreed63** [comment]
use trim instead of regex

July 2011
