### ISSUE TITLE
Accordion Container not rendered correctly

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#770]
On Chrome/Win:
New html file
Drag drop AccordionContainer
New html file
Switch tabs back to first html file
Reload browser

The open pane of the AccordionContainer does not fill the accordion. I have to click split view (source) to get the accordion to refresh

**Comment by billreed63** [comment]
Also after the steps about click on the accordion and receive the following exception
Uncaught TypeError: Cannot call method 'getSelection' of undefined    ve/PageEditor.js 124

Switching tabs seems to clear it up.

**Comment by JonFerraiolo** [comment]
Yes, this is a must-fix. I'm seeing problems with BorderContainer, too.

**Comment by peller** [comment]
It's not widget-specific, AFAICT
