### ISSUE TITLE
If logged in and click on review link, get sent to odd Joomla page

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#773]
If a user is logged in to site and they click on a review link, they get sent to a Joomla page with heading **Login** that states **"You are logged in to a private area of this site."**  There is only a single button labeled **Logout**.

Work around is to log out and then click on the review link.

What should happen is that if user clicks on review link and is already logged in, they should be taken directly to the review page.

Setting to **M2** for initial investigation, but let me know if this needs to get pushed to **M3**.

@JonFerraiolo

**Comment by waynevicknair** [comment]
the description is not quite accurate. this only occurs if you have logged out of page designer by clicking the "logout" link. this will return you to joomla where you will still be logged in to joomla. 

the correct workflow is to logoff from joomla.
