### ISSUE TITLE
No way for user to launch app from main site if logged in

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#774]
If a user is logged in and they load the main site (i.e. maqetta.org), there is no way to launch the application.

Here's what I propose, for users that are logged in:
- Replace `Logout | Sign Up | Try It` in top right with `Log Out | Launch Maqetta`.
  - If user is already logged in, then there is no point in having the "Sign Up" and "Try It" links.
- Replace the large `SIGN UP!` and `GIVE IT A TRY` buttons with a single `LAUNCH MAQETTA` button.
  - As above, the former 2 buttons don't make much sense when user is already logged in.

**Comment by jhpedemonte** [comment]
@JonFerraiolo Take a look, let me know if you agree with proposal.

**Comment by JonFerraiolo** [comment]
Enthusiastic +1. I had noticed this problem but was always so busy focusing on other issues to log a bug on this very significant user issue. 

I'll research and see if I have the ability to create a LAUNCH MAQETTA button or I need to get help from one of our graphics guys.

**Comment by waynevicknair** [comment]
i checked-in jon's changes under commit e21171 in the internal repository

**Comment by JonFerraiolo** [comment]
Reassigning to Wayne. Didn't we take care of this? If so, please close.
