### ISSUE TITLE
Smart input for IconContainer and IconItem

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#775]
**IconContainer** is a collection of **IconItems**.  Each IconItem can have an image and a label.
1. How do we handle smart input for IconItem? Should it just handle image, label or both?  I'd vote for the latter (based on presumed common usage scenario).  I guess that means a custom input object.
2. How do we handle smart input for IconContainer? We'd want it to appear when user first adds IconContainer to page. And we'd want it to handle both icons and labels for each IconItem.

@JonFerraiolo @billreed63

**Comment by jhpedemonte** [comment]
Something like this for **IconContainer**:

![IconContainer Smart Input](http://i.imgur.com/FS3gz.png)

Clicking on the **+** button adds a new line, each line corresponds to one **IconItem**.

**Comment by JonFerraiolo** [comment]
I don't have any magic answers at this time, but will just point out that we have similar issues for other widgets, both container widgets (as in this case) and with data-bound widgets such as Tree where we want to set properties on individual items. Possibly related bug: #79. One approach to consider is that smart input on container can only set text properties. To set other properties, you have to individually select each child and then set things via smart input or properties palette on the child. We are using this approach today for RoundRectList/EdgeToEdgeList as containers for ListItem. You can drop a child Switch into ListItem, and then subsequently double-click on the *List container widget to change text labels, where any property settings and/or children on the ListItems get preserved. See #523

**Comment by jhpedemonte** [comment]
> One approach to consider is that smart input on container can only set text properties.

I don't think that makes sense for IconContainer.  If we want to make the process as quick and seamless as possible, then we'd need to be able to set both **label** and **icon** at the same time.

**Comment by billreed63** [comment]
Maybe a combination of what we do for EdgeToEdgeDataList and EdgeToEdgeList. EdgeToEdgeDataList has a file explorer  that populates the edit box with the path/fileName.  When the user selects a file from the explorer the fileName get populated in the editbox at the current cursor position.

We could use that format 

```
Path/FileName, Label
Path/FileName2, Label

```

**Comment by JonFerraiolo** [comment]
One of the things I've been wondering if whether the 'moveTo' property should be promoted to inline edit for various widgets that usually only make sense if they have a moveTo property

**Comment by billreed63** [comment]
We do it for EdgeToEdgeDataList where the moveto is stored in the DataStore

**Comment by jhpedemonte** [comment]
Assigning to Bill for now, but I (or someone else) can take it if necessary.

**Comment by jhpedemonte** [comment]
-> M6

**Comment by doronrosenberg** [comment]
@jhpedemonte mockup makes the most sense.  Editing text is usually troublesome for less technical folks

**Comment by JonFerraiolo** [comment]
I pulled latest code but I'm not seeing the new SmartInput for IconContainer. I did these steps: 
- New HTML File - iPhone
- Add ScrollableView
- Add IconContainer

I would have expected SmartInput to appear at this point, but it doesn't. Double-clicking on IconContainer or any of the IconItems results in nothing either.

**Comment by doronrosenberg** [comment]
Which browser? I still have small work to do to make it look better, but it seems to work fine here.
