### ISSUE TITLE
Figure out alternative at maqetta.org if activation email never gets through

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#776]
@waynevicknair, @jhpedemonte

We have a problem at maqetta.org where the Joomla activation emails (sent from PHP) often don't get to the end user mailboxes. For example, I don't get activation emails send to anything at ferraiolo.com. I have heard of others having the same problem. It's weird because the review&commenting emails (sent from Java) come through just fine. 

Maybe spam filters don't like the headers sent by Joomla/PHP? Maybe we need to have the PHP side invoke a servlet and then have that servlet send the activation email?

Assign to myself to UI questions first of all.

**Comment by JonFerraiolo** [comment]
Removing the M3 designation. We might be able to close this bug due to Wayne's fixes to the maqetta.org mail logic, but leaving this open so we'll look at it again down the road to make sure everything is ok.

**Comment by aerwin** [comment]
--> no milestone to M7 

Maybe we can just close this one?

**Comment by jhpedemonte** [comment]
Let's keep this open for now.  Our big hope is that getting rid of the odd port in the URL contained in the email will keep it from getting snatched by spam filters.

But there may be other things we can do to make this easier.  For one, having a "resend activation email" might be useful.

Also, mention that users should check their spam folders if they haven't gotten the notification.

@childsb

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte

**Comment by jhpedemonte** [comment]
A user can click again on **Register** in order to resend an activation email.  Of course, if the first activation email went to a spam folder, chances are the second one will as well.  But that should cover this bug -- agreed, @JonFerraiolo?

**Comment by JonFerraiolo** [comment]
-> me (to think about it).

It's not intuitive that you would click on **Register** to resend the activation email. On other sites, I've seen UI that says "send activation email" or something like that.

**Comment by jhpedemonte** [comment]
@childsb implemented a "reset password" feature.  If emails fail to get through, I'm not sure what we can really do -- the user will just have to contact us somehow.

Closing.
