### ISSUE TITLE
Redirect all :55555 requests to home page

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#777]
@childsb, @jhpedemonte

Here is some code I added to httpd-vhosts.conf and got working using XAMPP and localhost:

```
Listen 55555
NameVirtualHost 127.0.0.1:55555
<VirtualHost 127.0.0.1:55555>
    ServerName dummyhost2.localhost
    DocumentRoot "C:/xampp/htdocs"
    RewriteEngine On
    RewriteCond %{SERVER_PORT} ^55555$
    RewriteRule ^/(.*)         http://localhost/index.html [L,R]
</VirtualHost>
```

Wayne, can you please research and study all of the above directives carefully to make sure we fully understand what is happening and have confidence we are doing the right thing?

**Comment by waynevicknair** [comment]
This is working on the staging server. I will close the bug after we update 'maqetta.org'.

**Comment by jhpedemonte** [comment]
Confirm that this is working properly on maqetta.org.  Closing.
