### ISSUE TITLE
CSS caching investigation

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#778]
@jhpedemonte, @billreed63, @childsb, @peller

There are still cases where a user makes changes in theme editor and the corresponding changes don't appear in HTML files until doing a browser refresh.

Assigned to Jon to come up with reproducible cases.

**Comment by jhpedemonte** [comment]
I started a wiki to track the different file sets we maintain and what type of caching strategy we should use for each:  https://github.com/maqetta/maqetta/wiki/Caching.

Theme editor files are mentioned under _"(3) editable files"_.

**Comment by JonFerraiolo** [comment]
Pushing this out of M3. I don't think we should mess with caching logic between now and the M3 release.

**Comment by jhpedemonte** [comment]
Also an issue with **app.css** (in addition to **theme editor** changes).

---

Moved this to M4, assigned to Adam for now.

**Comment by JonFerraiolo** [comment]
Whoever fixes this bug, make sure that #1013 is indeed fixed as a result of fixing this bug.

**Comment by peller** [comment]
In M3, edits to app.css didn't take in a preview without a browser refresh.  In trunk updates are visible by merely closing and doing a preview again.  Perhaps it was @waynevicknair's fix to the cache header that did it?
