### ISSUE TITLE
Remove deprecated grid widgets from widget palette

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#78]
As we promote gridx, we should figure out how best to disable or deprecate various legacy grid widgets.

This issue is a catch-all to review package.json and determine what to do about DataGrid, EnhancedGrid, TreeGrid, etc., in terms of what should be shown in Widgets palette and what widgets we need to attempt some level of backwards compatibility. (My instincts tend towards dropping support on old grids as soon as we can.)

**Comment by aerwin** [comment]
Marking closed with above commit.
