### ISSUE TITLE
(FF) If Calendar causes scrollbar, causes Calendar to be too tall

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#784]
@billreed63, @jhpedemonte, @childsb

Can't make this happen in Chrome, but was able to make it happen on both Mac/FF and Win/FF
- New HTML File
- Keep dragging/dropping Calendar widgets until there isn't room for the last one and the page editor canvas has to include a scrollbar

Result=> The last Calendar widget is way too tall, and you can't resize it easily by pulling on drag handles.

**Comment by JonFerraiolo** [comment]
I poked around on this one. Looks like Calendar is OK, it's just that the selection chrome is too big. The selection chrome causing the page to be too tall is the result of calling focus.show at Context.js:1456.

**Comment by JonFerraiolo** [comment]
Here is a theory about what's happening. The culprit appears to be this logic at Focus.js:132

```
        if(b.t + b.h > container.scrollHeight){
            b.h = container.scrollHeight - this.size * 2;
        }
```

The problem is that with Firefox, scrollHeight on BODY appears to be incorrect. With Firefox, if you set BODY's height to 100% (such as we do in Context.js:669 and in the default app.css file), then body.scrollHeight is not set to the height of the BODY's content, but instead to the height of the viewport. For example, suppose you have 2 Calendar widgets, each of which is 216px high, but the page editor canvas is only 300px high. On Firefox, when tracing with Firebug, the scrollHeight of BODY will be 300px instead of 432px, despite the fact that the definition of scrollHeight on MDC (https://developer.mozilla.org/en/DOM/element.scrollHeight) is: "An element's scrollHeight is a measurement of the height of an element's content including content not visible on the screen due to overflow."

I'm not sure how to fix or workaround this problem. It would be very risky to remove the height:100% setting on the BODY just before the M2 release.

**Comment by JonFerraiolo** [comment]
Moved to M3. We have the same bug with Preview 1.0.1

**Comment by peller** [comment]
My recollection is that these lines are intended to apply only to the case where we have a single widget occupying 100%x100%, such that the focus box itself does not extend beyond that 100%, causing scrollbars and messing up the geometry.  That situation, unfortunately, is broken also.

**Comment by peller** [comment]
@billreed63, please review.  Also, I'm a bit confused about this._context._selectedWidget.  Where does that get set?

So the old code was failing for a few reasons.  The measurements as to whether the box was out of the canvas bounds (scrollHeight/Width) seemed to be giving inconsistent results, off by a few pixels in one browser vs. another.  My guess is some sort of box model thing.  I've devised a new test which I think is simpler, more specific and is limited to top-level widgets, the only ones which I think would mandate tweaking the focus box size this way.
