### ISSUE TITLE
properties of type "number" are reset when working with files that have been saved and reopened

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#785]
I stumbled upon a kind of strange bug while working with the AnalogGauge that occurs with widgets that have properties with datatype: number.
- new HTML file
- drop multiSelect onto canvas
- under widget-specific change the size to 9
- save and close the file
- open the file
- select the multiSelect
- under widget-specific give it a name

Notice that the size property changes back to its default of 7 after you change the name. 

Tested in Win/Chrome
lab14 build:
Version: Preview 2
Date: Jul 25, 2011 7:02:01 AM
Build: b2d468762389a3e...

**Comment by JonFerraiolo** [comment]
Javier, assigned to you. Sounds like a metadata issue, but might be a properties palette issue, in which case, bounce it back to me.

**Comment by waynevicknair** [comment]
Following the steps outlined about I could not recreate this bug on the latest commit. Closing.
