### ISSUE TITLE
Source editor selection doesn't show in visual editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#788]
@jhpedemonte, @peller

Earlier versions of Maqetta used to have a feature in split view (design and source showing at same time) where:

1 Selecting a widget in design pane highlighted the corresponding source code in the source pane
2 Selection anything in the source pane caused the corresponding widget to be selected in the design pane

Right now, only (1) works. The Maqetta marketing materials have promised both (1) and (2) to our users, so it is a major bug that (2) isn't working at this point. Also, users have complained about the lack of (2).

**Comment by waynevicknair** [comment]
fixed with commit c73c98567c6646acbc2c1bf4cff114d51ad0fa7b
