### ISSUE TITLE
Widget disappears when dragged into written DIV

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#789]
Steps to recreate:
- Create new HTML file.
- Add **Button**, **TextBox**, and **ComboBox** to page.
- Open **split view** for source editor.
- Add `<div></div>` as first element in `<body>` (above the other widgets).
- Click on ComboBox, then Cmd+click on TextBox and Button (to select the 3 widgets).
- Drag the 3 widgets up into the DIV.

For some reason, then TextBox disappears after the drag.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
Assigning to Adam just so it's assigned to someone (minimize chances of falling through cracks)

**Comment by peller** [comment]
works for me

**Comment by peller** [comment]
...though they get reversed in order  #963
