### ISSUE TITLE
Users need to set properties on sub-items of complex widgets: Trees

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#79]
For example:
- For MenuItems, setting iconClass and attaching an onclick handler (or hyperlink)
- For TreeNode, setting iconClass and attaching an onclick handler (or hyperlink)
- For DataGrid cells, inserting an image (or other complex markup), cell-specific styling and attaching an onclick handler (or hyperlink)
- For DataGrid columns, controlling datatype for cells in the column and column width

Jon and I are leaning towards a UI approach where users can select sub-items by clicking on the canvas, and then adjusting properties in the properties palette. To implement such an approach, I expect we need to beef up the helper classes as follows:
- Select cell, select row, select column
- ModifyCommand and ModifyStyleCommand (maybe there are helper hooks for these already)
- Some ability to have a whitelisting feature in the Properties palette such that only certain properties are active (everything else disabled). For example, for MenuItem, maybe everything is disabled except iconClass (under widget-specific) and onclick (under events)
- We probably need various sorts of bulletproofing in existing commands to prevent bad things from happening. For example, we might not want to allow DELETE on a table or DataGrid cell.

Thoughts?

**Comment by billreed63** [comment]
http://evan.dojotoolkit.org/grid2.0/dojox/grid/gridx/tests/mini_grid.html
http://evan.dojotoolkit.org/grid2.0/dojox/grid/gridx/tests/demo_grid.html
https://github.com/evanhw/grid-2.0/blob/master/gridx/tests/mini_grid.html

7511

**Comment by billreed63** [comment]
Users need to set properties on sub-items of complex widgets. For example:
- For MenuItems, setting iconClass and attaching an onclick handler (or hyperlink)
-  MenuItems are currently selectable on the canvas, we should be able to set MenuItem properties from the Widget Specific palette.
- For TreeNode, setting iconClass and attaching an onclick handler (or hyperlink)
  -  IconClass of the tree are created by dojo code at runtime from the DataStore, I do not believe it is possible to change the "iconClass" if the user wants a different icon the user needs to update the theme css files. But this is at the tree level not TreeNode
  -  onclick setting event handlers on tree nodes is not possible, the Tree is a black box. to catch onclicks on nodes the user needs to define an onClick handler for the tree and then in that function determine the node by interrogating the item passed to the onclick handler.
    
    &lt;div id="mytree" data-dojo-type="dijit.Tree" data-dojo-props='model:continentModel, openOnClick:true, onLoad:function(){ console.log("loaded mytree (first tree)"); }'&gt;
        &lt;script type="dojo/method" data-dojo-event="onClick" data-dojo-args="item">
            console.log("Execute of node " + continentStore.getLabel(item)
                +", population=" + continentStore.getValue(item, "population"));
        &lt;/script>
        &lt;script type="dojo/method" data-dojo-event="onOpen" data-dojo-args="item">
            console.log("Open of node " + continentStore.getLabel(item)||"root");
        &lt;/script>
        &lt;script type="dojo/method" data-dojo-event="onClose" data-dojo-args="item">
            console.log("Close of node " + continentStore.getLabel(item)||"root");
        &lt;/script>
    &lt;/div>
- Node data is actually contained in the DataStore so the data store must be updated not the Tree itself.
- For DataGrid cells, inserting an image (or other complex markup), cell-specific styling and attaching an onclick handler (or hyperlink)
- inserting an image (or other complex markup),  This is accomplished by updating the datastore with the HTML markup &lt;img src=.....> and adding the escapeHTMLInData="true" to the DataGrid widget
- cell-specific styling the colum width can be set by &lt;th width="...> but style can not be set. DataGrid generates a completely different structure at run time and ignores styles and class set on &lt;th>. The user needs to change the theme css to update style on dataGridCell
- onclick handler (or hyperlink) the onclick is handled be the Tree widget the user needs to create a javascript function onRowClick(e) Fired when a row is clicked. The event contains references to the grid, cell and rowIndex. isn't a hyperlink covered by html markup?
- For DataGrid columns, controlling datatype for cells in the column and column width
-  to do this the user needs to add the width and cellType parms to the &lt;th> element, we should also add the other supported parms that can be added to the &lt;th>. In our case we generate a structure JSON object that defines the table structure. The code that generates this structure would need to be updated. the "structure" is a parm to DataGrid 
  &lt;span dojoType="dojox.grid.DataGrid" structure="[{&quot;cellType&quot;:&quot;dojox.grid.cells.Cell&quot;,&quot;width&quot;:&quot;auto&quot;,&quot;name&quot;:&quot;ID&quot;,&quot;field&quot;:&quot;id&quot;},{&quot;cellType&quot;:&quot;dojox.grid.cells.Cell&quot;,&quot;width&quot;:&quot;auto&quot;,&quot;name&quot;:&quot; Label&quot;,&quot;field&quot;:&quot;_label&quot;}]" autoWidth="false" autoHeight="false" singleClickEdit="false" columnReordering="false" selectable="false" delayScroll="false" style="width: 289px; height: 100px;" store="ItemFileReadStore_1"></span

**Comment by billreed63** [comment]
To simulate setting styling and attaching events to a data grid cell we could set the escapeHTMLInData="true" in the DataGrid table definition. Then in the data store data for that cell add a top level &lt;DIV> element that could have class, onclick, style, etc... attributes 
example:

``` html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" 
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Test dojox.grid.DataGrid Basic</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <style type="text/css">
        @import "../../../dojo/resources/dojo.css";
        @import "../resources/Grid.css";
        @import "../resources/tundraGrid.css";
        body {
            font-size: 0.9em;
            font-family: Geneva, Arial, Helvetica, sans-serif;
        }
        .heading {
            font-weight: bold;
            padding-bottom: 0.25em;
        }
        #grid, #grid2 {
            width: 65em;
            height: 25em;
            padding: 1px;
        }
        .aaaa{
            background-color: red;
            background-image: url('http://edweb.tusd.k12.az.us/crauser/A.gif');
            background-repeat:no-repeat;
            background-position:center; 
            width: 300px;
            height: 250px;
        }
    </style>
    <script type="text/javascript" src="../../../dojo/dojo.js" 
        djConfig="isDebug:false, parseOnLoad: true"></script>
    <script type="text/javascript">
        dojo.require("dijit.dijit");
        dojo.require("dojox.grid.DataGrid");
        dojo.require("dojo.data.ItemFileWriteStore");
        dojo.require("dojo.parser");

        function clicktest(){
            alert('onclick from datagrid cell html div');
        }
    </script>
    <script type="text/javascript" src="support/test_data.js"></script>
</head>
<body class="tundra">
    <div class="heading">dojox.grid.DataGrid Basic Test</div>
    <span dojoType="dojo.data.ItemFileWriteStore" 
        jsId="jsonStore" data="{&quot;identifier&quot;:&quot;id&quot;,
                               &quot;label&quot;: &quot;label&quot;,
                               &quot;items&quot;: [
                                  { &quot;id&quot;:&quot;AF&quot;,&quot;label&quot;:&quot;&lt;b&gt;IMx&lt;/b&gt;&quot;, &quot;type&quot;:&quot;continent&quot;}, 
                                  { &quot;id&quot;:&quot;AR&quot;,&quot;label&quot;:&quot; <div class=\&quot;aaaa\&quot; onclick=\&quot;clicktest();\&quot;><\div> &quot;, &quot;type&quot;:&quot;country&quot; } 
                                  ]
                               }"
        >
    </span>
    <table dojoType="dojox.grid.DataGrid" escapeHTMLInData="false" 
        jsid="grid" id="grid" 
        store="jsonStore" query="{ label: '*' }" rowsPerPage="20" rowSelector="20px">
        <thead>
            <tr>
                <th field="label" class="myGridCell" width="300px">Country/Continent Name</th>
                <th field="type" width="auto">Type</th>
            </tr>
        </thead>
    </table>

    <div class="aaaa" onclick="clicktest();"></div>
</body>
</html>
```

**Comment by billreed63** [comment]
The challenge with DataGrid an Dijit Tree that separates them from HTML Tables and Dojo Menus and MenuItems is that DataGrid and Tree at runtime is a combination of Widget definition and runtime presentation of that data.  When the user drags and drops the data grid widget on the canvas A DataGrid and a ItemFileReadStore widget are added to the model. What is displayed on the canvas is the "runtime" presentation of the widget. The DataGrid headers are retrieved from the DataGrid widget along with the structure of the DataGrid. All of the following rolls are runtime data that is retrieved from the ItemFileReadStore and used to populate the DataGrid based on the structure definition of the DataGrid.
A DataGrid declaration might look something like:

``` html
   <table dojoType="dojox.grid.DataGrid" escapeHTMLInData="false" 
        jsid="grid" id="grid" 
        store="jsonStore" query="{ label: '*' }" rowsPerPage="20" rowSelector="20px">
        <thead>
            <tr>
                <th field="label" class="myGridCell" width="300px">Country/Continent Name</th>
                <th field="type" width="auto">Type</th>
            </tr>
        </thead>
    </table>
```

But at runtime it expand to:

``` html
  <div style="-moz-user-select: none;" aria-readonly="true" widgetid="grid" id="grid"
  class="dojoxGrid" aria-multiselectable="true" tabindex="0" hidefocus="hidefocus" role=
  "grid" dojoattachevent="onmouseout:_mouseOut" align="left">
    <div style="display: block; height: 20px;" class="dojoxGridMasterHeader"
    dojoattachpoint="viewsHeaderNode" role="presentation">
      <div style="visibility: hidden; width: 20px; left: 1px; top: 0pt;" class=
      "dojoxGridHeader" dojoattachpoint="headerNode" role="presentation">
        <div dojoattachpoint="headerNodeContainer" style="width: 9000em;" role=
        "presentation">
          <div dojoattachpoint="headerContentNode" role="row"></div>
        </div>
      </div>

      <div style="width: 776px; left: 21px; top: 0pt;" class="dojoxGridHeader"
      dojoattachpoint="headerNode" role="presentation">
        <div dojoattachpoint="headerNodeContainer" style="width: 9000em;" role=
        "presentation">
          <div dojoattachpoint="headerContentNode" role="row">
            <table style="width: 776px;" class="dojoxGridRowTable" role="presentation"
            border="0" cellpadding="0" cellspacing="0">
              <tbody>
                <tr>
                  <th tabindex="-1" aria-readonly="true" role="columnheader" id=
                  "gridHdr0" colspan="1" class="dojoxGridCell dojoDndItem" idx="0" style=
                  "width: 300px;" dndtype="gridColumn_grid">
                    <div class="dojoxGridSortNode">
                      Country/Continent Name
                    </div>
                  </th>

                  <th tabindex="-1" aria-readonly="true" role="columnheader" id=
                  "gridHdr1" colspan="1" class="dojoxGridCell dojoDndItem" idx="1" style=
                  "width: auto;" dndtype="gridColumn_grid">
                    <div class="dojoxGridSortNode">
                      Type
                    </div>
                  </th>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div class="dojoxGridMasterView" dojoattachpoint="viewsNode" role="presentation">
      <div style="width: 20px; height: 288px; left: 1px; top: 0px;" widgetid=
      "dojox_grid__RowSelector_1" id="dojox_grid__RowSelector_1" class="dojoxGridView"
      role="presentation">
        <input class="dojoxGridHiddenFocus" dojoattachpoint="hiddenFocusNode" role=
        "presentation" type="checkbox" /> <input class="dojoxGridHiddenFocus" role=
        "presentation" type="checkbox" />

        <div style="overflow: hidden; height: 288px;" class="dojoxGridScrollbox"
        dojoattachpoint="scrollboxNode" role="presentation">
          <div style="height: 283px;" class="dojoxGridContent" dojoattachpoint=
          "contentNode" hidefocus="hidefocus" role="presentation">
            <div style="position: absolute; left: 0pt; top: 0px;" role="presentation">
              <div role="presentation" class=
              "dojoxGridRowbar dojoxGridNonNormalizedCell">
                <table class="dojoxGridRowbarTable" style="width: 18px; height: 24px;"
                role="presentation" border="0" cellpadding="0" cellspacing="0">
                  <tbody>
                    <tr>
                      <td class="dojoxGridRowbarInner">&nbsp;</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <div role="presentation" class=
              "dojoxGridRowbar dojoxGridNonNormalizedCell">
                <table class="dojoxGridRowbarTable" style="width: 18px; height: 259px;"
                role="presentation" border="0" cellpadding="0" cellspacing="0">
                  <tbody>
                    <tr>
                      <td class="dojoxGridRowbarInner">&nbsp;</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div style="width: 776px; height: 288px; left: 21px; top: 0px;" widgetid=
      "dojox_grid__View_1" id="dojox_grid__View_1" class="dojoxGridView" role=
      "presentation">
        <input class="dojoxGridHiddenFocus" dojoattachpoint="hiddenFocusNode" role=
        "presentation" type="checkbox" /> <input class="dojoxGridHiddenFocus" role=
        "presentation" type="checkbox" />

        <div style="height: 288px;" class="dojoxGridScrollbox" dojoattachpoint=
        "scrollboxNode" role="presentation">
          <div style="height: 283px; width: 776px;" class="dojoxGridContent"
          dojoattachpoint="contentNode" hidefocus="hidefocus" role="presentation">
            <div style="position: absolute; left: 0pt; top: 0px;" role="presentation">
              <div style="" aria-selected="false" role="row" class="dojoxGridRow">
                <table style="width: 776px; height: 24px;" class="dojoxGridRowTable"
                role="presentation" border="0" cellpadding="0" cellspacing="0">
                  <tbody>
                    <tr>
                      <td tabindex="-1" role="gridcell" colspan="1" class="dojoxGridCell"
                      idx="0" style="width: 300px;"><b>IMx</b></td>

                      <td tabindex="-1" role="gridcell" colspan="1" class="dojoxGridCell"
                      idx="1" style="width: auto;">continent</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <div style="" aria-selected="false" role="row" class=
              "dojoxGridRow dojoxGridRowOdd">
                <table style="width: 776px; height: 259px;" class="dojoxGridRowTable"
                role="presentation" border="0" cellpadding="0" cellspacing="0">
                  <tbody>
                    <tr>
                      <td tabindex="-1" role="gridcell" colspan="1" class="dojoxGridCell"
                      idx="0" style="width: 300px;">
                        <div class="aaaa" onclick="clicktest();"></div>
                      </td>

                      <td tabindex="-1" role="gridcell" colspan="1" class="dojoxGridCell"
                      idx="1" style="width: auto;">country</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="dojoxGridMasterMessages" style="display: none;" dojoattachpoint=
    "messagesNode"></div>
  </div>

```

<b>How do we do:</b>

<ul>
<li>Canvas</li>
<ul>
<li>Select DataGrid Row</li>
<li>Select DataGrid Cell or TreeNode</li>
</ul>

<li>Outline view </li>

<ul>
<li> View should show DataGrid, A child DataGrid Header Row and a DataGrid Data Row for each row of Data in the Grid. The DataGrid Header Row should have a child DataGrid Header Cell for each Column in the Grid including hidden columns. The DataGrid Data Row should have a child for each DataGridCell of data displayed in the Grid for that row. The information for the DataGridCells is not present until after the Dojo DataGrid widget is created by Dojo.  
</li>
</ul>

<li>Source View</li>

<ul>
<li>If the user is in split view what do we select if the user has selected a DataGrid data cell to edit? In reality that information is in the DataStore do we select the ItemFileReadStore, do we try to select the actual data in the data parameter?
</li>
</ul>

<li>Properties Palette </li>
</ul>

**Comment by billreed63** [comment]
Interesting file: https://github.com/evanhw/grid-2.0/blob/master/gridx/tests/demo_grid.html
 the thing that leaps out at me is that there are extensibility points for cell selection and column selection. We could override those in a Maqetta helper where we did something different at author time but used the regular old selection handler for runtime
 I see that the above gridx test file is still using ItemFileWriteStore, not mvc (not surprising, but noteworthy)
 Jon Ferraiolo: Some docs: https://docs.google.com/document/d/1tR3jm2cgsSx518y7ClYlpB0hl9avyL2Z4c_XdcBCvpY/edit?hl=en&authkey=CK3GtacD&pli=1#
 That page shows the following API: DOMNode
getCellNode(rowId, columnId)
Jon Ferraiolo: Might be useful

**Comment by JonFerraiolo** [comment]
Regarding "How do we...Source View", what I would propose is that our selection data structures get enhanced to indicate both the real widget that is the target of the selection (in this case, the grid widget) and also supplemental information about the currently selected sub-widget (e.g., cell(s) or column(s)). The source view highlights would just use the real widget and ignore the sub-widget info.

**Comment by JonFerraiolo** [comment]
@jhpedemonte: Push this to M5?

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
I just spent time working with a user on creating custom JavaScript that will listen to TreeNodes and performs actions if the user clicks on particular nodes. Here is the app.js file I created for them:

```
var ApplicationsTreeEvents=[
    {treeLabel:"aaa", action:"ChangeTab", target:"MainTabContainer", subtarget:"Welcome"},
    {treeLabel:"bbb", action:"ChangeTab", target:"MainTabContainer", subtarget:"Files"},
    {treeLabel:"ccc", action:"ChangeState", target:"SDAnode", subtarget:null}
];
window.addEventListener("load", function(){     // Browser load event: browser is ready
    dojo.ready(function(){                      // dojo ready event: dojo is ready
        var ApplicationsTree = dijit.byId('ApplicationsTree');
        ApplicationsTree.onClick = function(item){
            var treeLabel = item.label[0];
            for(var i=0; i<ApplicationsTreeEvents.length; i++){
                if(ApplicationsTreeEvents[i].treeLabel === treeLabel){
                    DoAction(ApplicationsTreeEvents[i]);
                    return;
                }
            }
        };
        function DoAction(Event){
            if(!Event){
                return;
            }
            if(Event.action==='ChangeTab'){
                if(Event.target && Event.subtarget){
                    var container = dijit.byId(Event.target);
                    if(container && container.getChildren && container.selectChild){
                        var children = container.getChildren();
                        if(children){
                            for(var i=0; i<children.length; i++){
                                if(children[i].get('title') == Event.subtarget){
                                    container.selectChild(children[i]);
                                    return;
                                }
                            }
                        }
                    }
                }
            }else if(Event.action==='ChangeState'){
                if(Event.target){
                    var targetState = Event.target;
                    var states = davinci.states.getStates();
                    if(states.indexOf(targetState)){
                        davinci.states.setState(targetState);
                    }
                }
            }
        }
    }); 
}, false);
```

My conclusion is that SmartInput for Tree should allow for the following information for each node of the tree:
- Label
- Icon
- Events (onclick being most important, but in some cases users might need any of the mouse/touch events). The events UI should be the same as in the Properties palette, with a dropdown to switch to a different state (and whatever else we add to Events section down the road)
  We would need some buttons to help control indent levels, and probably some buttons to add/delete/move-up/move-down

**Comment by aerwin** [comment]
This issue will now be entirely focused on trees. The following spin-off issues have been created to handle Menus and GridX:
- #2638: Users need to set properties on sub-items of complex widgets: Menus
- #2639: Users need to set properties on sub-items of complex widgets: GridX

**Comment by aerwin** [comment]
With the commit above, there's still some needed polish, but I believe the core functionality is in place. E.g., there's a full visual editor for specifying the tree contents and properties can be set on the selected node.

When you drop a Tree on a page, you'll get the new Tree Configuration dialog. There's a toolbar to create nodes, delete nodes, move nodes, etc. In addition dnd is turned on so you can drag and drop nodes to move them around the tree.

When you select a node, you can set its _label_, _icon_, _onClick_, _onDblClick_, and _onClose_ properties. As a quick test, if you select a node you could set the _icon_ property to something like `samples/sample_data/images/i-icon-1.png`. In addition, you could enter some JS into the _onClick_ field like `console.log("onClick!")` (and then if you click OK and preview the page that JS should be executed). I've also done a quick test of state changing (e.g., putting things like `davinci.states.setState('Normal')` and `davinci.states.setState('test')`) into the _onClick_ field will change states at runtime.

Below are some high-level things that need to be polished and/or considered. I'll likely clean up some things this weekend and/or open some new issues for some of the items below:
- the _onClick_, _onDblClick_, and _onClose_ fields:
  - need to reuse stuff from the events portion of the Visual Editor's property palette (e.g., provide drop-down of available events)
  - on the back end (in the runtime JS) I end up leveraging `dojo.eval`. I'm not sure there are really any better alternatives, but I know some folks might worry about the use of `dojo.eval` so potentially worth a discussion
- the _icon_ field:
  - decided to go with the approach of using `getIconStyle` rather than `getIconClass` even though the latter would likely be what would be recommended to a developer. I thought that requiring a class doesn't lend itself to quick prototyping and is error prone. In addition, it's inconsistent with the abiltiies to we provide throughout the rest of Maqetta to set inline styles for images, etc.
  - should probably try and reuse some of the stuff in the background part of the Visual Editor's property palette:
    - at the very least a button to launch a file selector would make things better, but of course there are also other style props related to the node icon that can be set besides the file itself
  - probably need to provide an `openIcon` field in addition to `icon` since folks often want to change icon based on the state of the node
  - need some sample icons appropriate for tree nodes (the ones like `samples/sample_data/images/i-icon-1.png` are too big)
- could add properties related to _labelStyle_ and/or _labelClass_ (which would imply trying to make use of things from the font portion of the Visual Editor's properties palette)
- tedious to set props on each node
  - general concern I have is that in practice (especially for larger trees) developers typically wouldn't set these things on each individual nodes (e.g., most nodes would have all of the same settings and they would provide a `getIconClass` function with logic to return a different icon class based on the type of node and it's open/closed state)… I don't think there's a super good way to facilitate that for designers, but we might want to at least consider adding pull-downs to the various property fields containing values set on other nodes (e.g., make it easy to choose previously used icons, etc.)
- toolbar icons
  - the toolbar for manipulating the tree looks a little clunky, and would probably be improved with some icons 
- migration considerations
  - moved from using `ItemFileReadStore` and `ForestTreeStoreModel` to using `Memory` and `ObjectStoreModel`
  - moved to different JSON format stored in the `data` field of the store
- when click OK on smart input dialog, Tree gets selected, but selection chrome is too small (seems to be using min-height)
- should make dialog resizable
- probably need a feature request to handle more advanced data source configurations (e.g., files, JSONP, etc. like we have with `GridX`, etc.)
- think I want to try and be a little smarter in terms of not creating unneeded script blocks (e.g., if user hasn't set _onClose_ on any node, then perhaps don't want an `onClose` handler generated)
- had to do some hacks (_well_ beyond those documented) to get Dnd and maintaining of order working like it should in the input dialog (plan to talk with dijit team to discuss)

**Comment by aerwin** [comment]
couple other points:
- should add _onOpen_ event to go with _onClose_
- if add label styling (to go with icon styling) could also consider adding support for `getRowStyle` stuff

**Comment by aerwin** [comment]
Added improved node icon setting with above commit... a couple additional issues to deal with:
- if onChange in text field is generated by selecting different node in preview tree then changes get applied to wrong node
- completely removing node icon from properties doesn't cause icon to disappear from preview tree (but it does persist when clicking OK)
