### ISSUE TITLE
setWorkbenchState not called always when closing editor tabs

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#790]
@peller, @jhpedemonte

If a user runs into this bug, it will be a bad situation. I found myself in a state running Maqetta where I couldn't figure out how to close editor tabs.

I wonder if this bug is a result of lazy loading of editor tabs?
- New HTML file (file1.html)
- Add a button or whatever, don't save
- Open Sample1.html. If dirty bit comes on, hit Save to get rid of dirty bit
- Open app.css
- Click on file1.html tab to make it current
- Browser refresh
- With file1.html selected, click on "x" on Sample1.html to close it
- Browser refresh

Result=> Sample1.html appears again even though you just closed it

Looking at network panel, the setWorkbenchState PUT request doesn't happen when clicking the "x" on Sample1.html. Looking at things in debugger, my guess is that "page.editor.fileName" is undefined at Workbench.js:1339 because of the lazy loading logic, which prevents setWorkbenchState from getting called on the tab for Sample1.html.

Not sure how to fix this. Maybe at startup we need to loop through all open editors and make sure fileName gets a value?

**Comment by peller** [comment]
f4b29bdaae94fb5423b9ccb89bda5cacfe610ad8
