### ISSUE TITLE
Preview with mobile silhouettes broken can't refresh on changes

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#794]
To recreate:
- New HTML page with iPhone silhouette.
- Drop Dojox Mobile View.
- Add Heading and Slider in to View.
- Click on Preview.  Should look correct.
- Close Preview.
- Add ToolBarButton to Heading.
- Open Preview again. Notice that ToolBarButton doesn't show.

Even hitting Shift+Refresh doesn't make it work.

Also, if we create the same page but without silhouettes, then it works fine.  Problem with `/maqetta?preview=1` URL call?

@JonFerraiolo @cindyskach

**Comment by JonFerraiolo** [comment]
This might be a Chrome caching issue.

**Comment by JonFerraiolo** [comment]
OK, I have theories. I think there are 2 problems. First, preview=1 isn't grabbing workingcopy file if it exists. Second, Ctl-Refresh on Chrome keeps on reusing the old iframe. You have to explicitly clear cache via Preferences for iframe to redraw correctly.

**Comment by JonFerraiolo** [comment]
Right now I'm inclined to defer to M3.

**Comment by cindyskach** [comment]
I'm seeing this issue on firefox as well.

**Comment by jhpedemonte** [comment]
Brad pointed out that this might be an issue because mobile preview is using an iframe and Shift+Refresh may only refresh the top-level doc, not iframes.

If we want to handle this for **M2**, we can add a rule to the servlet that sets no-cache headers on URLs of form `<protocol>://<host>/maqetta/?preview=1&...`.

Would be good as well for non-mobile previews, but their URL looks like `http://localhost:8081/maqetta/user/maqettaUser/ws/workspace/file2.html`.  Not sure if that's unique to Preview.

@childsb

**Comment by jhpedemonte** [comment]
Workaround for Chrome:  right-click in page (inside of frame) and select **Reload Frame**.

**Comment by jhpedemonte** [comment]
Workaround for Firefox: right-click in page (inside of frame) and select **This Frame** -> **Reload Frame**.

No such menu item exists for Safari.

**Comment by JonFerraiolo** [comment]
Regarding this question:

> Would be good as well for non-mobile previews, but their URL looks like http://localhost:8081/maqetta/user/maqettaUser/ws/workspace/file2.html. Not sure if that's unique to Preview.

That URL isn't just Preview. It's the real URL for that HTML file. You can go to that URL from a web browser even if not logged into Maqetta. I would suggest turning off caching for those URLs at least as a short-term fix. But that's lower priority than the silhouette preview issue.

**Comment by jhpedemonte** [comment]
I'd already added a section on "Preview" to the [Caching](https://github.com/maqetta/maqetta/wiki/Caching) plan.

@peller, you previously added something to the servlet for caching, didn't you?

**Comment by JonFerraiolo** [comment]
I have a fix by changing silhouette JavaScript logic to add an extra URL parameter to the iframe's 'src' attribute. 3-line fix that seems very safe. There are two lines of code in singlepreview.js that attach ?theme=whatever as URL parameter. Just add &somerandomnumber=1 so that src attribute looks like this: http://....file1.html?theme=whatever&somerandomnumber=1

**Comment by jhpedemonte** [comment]
I'm fine with this for now, but I think the proper fix is to use HTTP headers, and fallback to URL params if headers aren't appropriate for the situation.  I'll open a bug to track caching issues, if we don't have one already.

**Comment by peller** [comment]
we could do a no-cache, I guess, but this seems fine
