### ISSUE TITLE
Adding an HTML comment in source pane prevents updates to design pane

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#799]
@peller
- Open Sample1.html
- Go into split view
- In source pane, just before the <body> tag, add an HTML comment such as 
- In source pane, find the "New" button and change the text to something else (e.g., "New task")

Result=> Design view isn't updated to show the new button text. If you save, close, reopen, the string "New task" is there now. 

I suspect that there is code in the parser and/or modeller that thinks the user is still entering the comment.

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo M7 Prio High

**Comment by JonFerraiolo** [comment]
-> @peller

**Comment by peller** [comment]
works for me
