### ISSUE TITLE
Don't use email address in Preview-in-Browser

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#8]
The URL created when opening preview-in-browser contains the user's email address.  Look into changing that so email address isn't used.  Perhaps each user can have a unique number associated with their workspace, and that is used in the URL instead of email.

**Comment by JonFerraiolo** [comment]
@childsb will preview url change when we switch to orion?

**Comment by JonFerraiolo** [comment]
Closing. User emails no longer appear in preview in browser url address.
