### ISSUE TITLE
Duplicate themes due to migration scripts creating foo_workingcopy.theme

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#800]
@jhpedemonte, @peller, @billreed63, @childsb

The M1->M2 migration scripts seems to have changed all instances of foo.xyz.workingcopy into foo_workingcopy.xyz. If a user's most recent session had a theme with unsaved changes, then there will be both a foo.theme file and a foo_workingcopy.theme file, with the result that the "foo" theme will show twice in the "New Theme" and "Open Theme" dialogs.

This is a tricky problem. I wouldn't mess with this issue for M2. Maybe after we post M2, we can run another script that removes all _workingcopy_ files under the themes/ folder.

**Comment by jhpedemonte** [comment]
I thought @waynevicknair added code to script to delete the workingcopy instances for themes during migration.

**Comment by waynevicknair** [comment]
i did. 

```
 #
 # Rename a '.workingcopy' file 
 #
 # param $1 is fully qualified file name
 #

 fqname=$1
 dir=`dirname $fqname`
 file=`basename $fqname`
 seg1=`echo $file | cut -d . -f 1`
 seg2=`echo $file | cut -d . -f 2`

 if [ $seg2 -ne "theme" ] 
 then
     mv $fqname ${dir}/${seg1}_workingcopy.${seg2}
     echo "\t\tRename $fqname to ${seg1}_workingcopy.${seg2} rc="$? 
 else
    rm -f $fqname
    echo "\t\tRemove $fqname rc="$? 
 fi
```

**Comment by JonFerraiolo** [comment]
I'm not sure what's going on here. When I ran Maqetta on Win/FF, the Files palette showed both a a1.theme and an a1_workingcopy.theme, and the New Theme and Open Theme dialogs showed 2 listings for a1. But then I VNC'd over to macwayne2 and there is no a1_workingcopy.theme file there. For another reason, I had cleared my browser cache on Win/FF, and refreshed Maqetta, and now the Files palette doesn't show the a1_workingcopy.theme file anymore. Very strange.

Let's keep this open for awhile in case we see other similar issues, but if not, then close this.

**Comment by waynevicknair** [comment]
that was a fix i made after the fact. the migration scripts are not written to perform incremental updates. thus i was unable to go back and re-migrate the users on the staging machine. i have since run a different script to delete the incorrect files.
