### ISSUE TITLE
Outline shows full name for dojox widgets

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#802]
- new HTML file
- drop DataGrid onto canvas (or go the mobile route and drop a View and a Heading)

For these widgets, the outline shows the full name like "dojox.grid.DataGrid" or "dojox.mobile.View" while for dijit widgets, it shows only "Button" or "ComboBox."

Perhaps we want this for at least the mobile widgets to help differentiate between dijit.button and mobile.button? I'm not sure, but this presents a small consistency issue.

**Comment by jhpedemonte** [comment]
That's not the only difference. For Dijit widgets, it shows the **short name** and a **descriptor** -- in the case of Dijit Button, the descriptor is the text content (which can be set using smart input).  Dojox Mobile widgets don't show a descriptor.  Not sure where this comes from.

Maybe we can add a metadata entry for generating the descriptor.  For Button (either Dijit or Dojox Mobile), it use the `label` property.  For dojox.mobile.View, it uses `id`, etc.

@JonFerraiolo @peller @billreed63 Any of you guys know how Outline gets the relevant info from each widget?

**Comment by JonFerraiolo** [comment]
Assigning to me. I've been through this code before.

**Comment by JonFerraiolo** [comment]
@billreed63, @peller, @waynevicknair

This might be a good one for someone else to grab.

**Comment by jhpedemonte** [comment]
Assigning to Wayne for now.
