### ISSUE TITLE
In page editor, go to Reviews tab, open a review, then New File - default folder is .review/*

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#803]
@EldonReturn, @peller, @childsb

In the page editor, if the user goes to the Reviews tab, opens a review, and then issues a New File command, the New File dialog defaults to one of the subfolders of .review/. If a user accepts this default, then the new file ends up in the reviews area. This is bad - the files palette's default folder shouldn't be affected by navigating through the Reviews palette.

**Comment by JonFerraiolo** [comment]
@billreed63, @waynevicknair

Might be good if someone snatched this bug from me.

**Comment by JonFerraiolo** [comment]
Brad, this is a nice to have, but I'm wondering whether a suitable fix for this might be easy. Maybe code things up so that if the path contains any segments with a "." as the first character, then change the default folder to the project root folder? Beware that this might not be a simple 3-line fix. The resource engine maintains a global variable that holds the current folder. Just changing the field in the dialog might not be sufficient.

**Comment by peller** [comment]
we shouldn't rely on ./ for relative paths.

**Comment by JonFerraiolo** [comment]
If "eclipse-compatible" is turned on, should go to WebContent as default folder instead of project root folder, right?

**Comment by JonFerraiolo** [comment]
Closed by above commit
