### ISSUE TITLE
TypeError "undefined" in checkItemAcceptance()

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#804]
In `VisualEditorOutline.js` the `checkItemAcceptabce()` method gets this error in the default case of the switch statement.

**Comment by JonFerraiolo** [comment]
Did some of the bug report get lost? You say "this error", but which error? And what things were going on when this error occurred?

**Comment by waynevicknair** [comment]
the error in the _title_ of the issue: TypeError "undefined". this error occurred while i was dragging an item in the outline view.
- i created an HTML file with a border container. 
- dropped three LABELs into left
- dropped H1 into head
- dropped DataGrid into middle
- dropped two H2s into footer

the second H2 dropped outside the footer on first try. i selected the H2 and started to drag in the outline view and saw the error in the console. the problem is that the code checking item acceptance, in its default case, assumes that all items have enclosing widgets. in this case, the H2 was hung off of the BODY element. so, `var item = dijit.getEnclosingWidget(target).item` set `item` to `"undefined"` after which we try to invoke a method on `item`. i believe the fix is to `return false;` if `item` is undefined. i don't think it is ever a safe assumption to think that all drop targets will be enclosed in widgets.

**Comment by waynevicknair** [comment]
I cannot recreate this problem on the current commit. Closing.
