### ISSUE TITLE
Copy/paste tree needs to duplicate the data store

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#805]
@peller

If you copy/paste a Tree widget, the new Tree uses the same data store as the cloned Tree. As a result, if you subsequently double-click on one of the trees and change the data, both trees will reflect the changes.

**Comment by billreed63** [comment]
added addPasteCreateCommand to TreeCreateTool

August 2011

**Comment by jhpedemonte** [comment]
commit: 3954a2a7fe793b50ffc69b9733ab3b9cd774ce7e
