### ISSUE TITLE
remove absolute link in theme file

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#811]
the dojo-theme-editor.html has an absolute link for dojo.  Move this to servlet code.

**Comment by peller** [comment]
see 8bc68d256f354719c261c8c5da5f94a226a9b961

**Comment by jhpedemonte** [comment]
How important is this for M3?  What's the priority?

**Comment by JonFerraiolo** [comment]
I set this to Priority-Low for M4. Things seem to be working for most cases as is.

**Comment by JonFerraiolo** [comment]
Pushing to M5, Priority-Med

**Comment by jhpedemonte** [comment]
-> M6

@childsb @peller, still an issue?

**Comment by childsb** [comment]
i consider this issue resolved

we have a static location on the server for dojo, so its OK for the theme editor to reference that version.  replacing a sentinal string with the users workspace URL wasn't good and has been removed.
