### ISSUE TITLE
Could not load 'davinci.ve.input.StackContainerInput'; last tried '../davinci/ve/input/StackContainerInput.js'

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#813]
@peller, @jhpedemonte

Assigning to Bill to scope out this bug and figure out who should fix.

With latest GitHub code, when I try to drag/drop a TabContainer, I get a popup alert that says "internal error" and when I look at console I see the following message:

Could not load 'davinci.ve.input.StackContainerInput'; last tried '../davinci/ve/input/StackContainerInput.js'

**Comment by billreed63** [comment]
missed TabContainer in widget.json

August 2011
