### ISSUE TITLE
Promoted Color Palette widget waiting for Dojo fix

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#815]
Setting the value property to something (like #0000ff) shows it on the canvas, but upon previewing we get a SyntaxError. 
It's a dojo problem. The bug has been reported to dojo: http://bugs.dojotoolkit.org/ticket/13560

**Comment by JonFerraiolo** [comment]
Had not been assigned to anyone. -> @peller M7 Prio-Low just to see if issue still exists and if so then please update milestone and priority as appropriate.
