### ISSUE TITLE
Drag/drop scenarios

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#82]
Case 1:
- New HTML File
- Drag/drop Button
- Drag/drop DIV
- Drag/drop TextBox under DIV
- Try to drag/drop TextBox to be a next sibling of Button
  Result=> Can't do it. Can drop the TextBox to left of Button, but can't drop it
  to right of Button

Case 2:
- New HTML File
- Drag/Drop Button, TextBox and DIV (in order)
- Try to drag TextBox to after the DIV
  Result=> Can't do it

Case 3:
- New HTML File
- Drag/Drop Button, TextBox, DIV, and ComboBox under DIV
- Try to drag ComboBox to be next sibling to TextBox
  Result=> Can't do it. Can drag before Button or before TextBox, but not after
  TextBox.

**Comment by JonFerraiolo** [comment]
Closing. All of the above cases are working now.
