### ISSUE TITLE
Resize down or right doesn't work on DIV (maybe other widgets)

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#820]
1. Drop DIV on new HTML page.
2. Try to resize vertically by dragging resize indicator in middle of bottom edge.

==> Cannot drag, error in console.

Seems to be due to ade351f1600e5653cc62f5729d6d9145f9aab656, where Adam changed `Focus.resize()` to take a 2nd parameter of `widget`.

However, `Focus.onMove()` calls `this.resize(b)` and doesn't pass in a 2nd param.  Results in uncaught error.

**Comment by JonFerraiolo** [comment]
Looking at the code, I think the safest and best thing to do is to simply wrap the logic that uses the 2nd parameter ("widget") (lines 125-135 of Focus.js) inside of an: `if(widget){...}` block. If we want other calling routines to trigger the adjustment at 125-135, then those calling routines can invoke getSelection() beforehand and pass in the currently selected widget.

But before I check in my proposed fix, I'll wait for Adam and Javier to review this comment.

**Comment by peller** [comment]
Sorry for the late response.  I'm concerned about the case where someone resizes a top-level widget from a fixed size to 100%x100% -- where the adjustment in question is important -- and that case is currently broken (but only after selecting a child widget)  May or may not be a regression.
