### ISSUE TITLE
davinci.core/WebContent/ui/templates/newtheme.html can't find NLS string

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#822]
when loading the new theme dialog it is unresponsive due to an error in its template file. the error is that it cannot find the $invalidThemeName NLS variable value.

**Comment by JonFerraiolo** [comment]
This works for me. With commit bf23c1c8 I checked in 2 files, the davinci/ui/templates/newtheme.html and davinci/ui/nls/ui.js where I renamed ${invalidCSS} to ${invalidThemeName}. Are you sure that what you have on your local system matches what's in the GitHub repository?

**Comment by JonFerraiolo** [comment]
Another thought - maybe you need to clear your browser cache?

**Comment by peller** [comment]
Templates should be inlined by the build, so cachebusting should cover this.  Without a build, it's quite possible you could have a stale cache situation.

**Comment by waynevicknair** [comment]
i was running from inside eclipse. i'll test again on a build monday. for some reason my VPN quit working here at home. :(

**Comment by JonFerraiolo** [comment]
Wasn't assigned to anyone. -> @billreed63 to see if it still exists. If not, please close. If yes, then please update milestone and priority as appropriate.
