### ISSUE TITLE
Absolute positioning broken in Safari with Preview 2

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#824]
@jhpedemonte, @waynevicknair, @billreed63

Looks like no one tested absolute positioning with Safari before we released Preview 2. Gulp.
- New HTML File
- Switch to absolute positioning
- Drag/drop a Button near top/left corner of canvas

Result=> Button gets positioned about 200px too far to right and about 100px too far down.

**Comment by JonFerraiolo** [comment]
This might not help, but one thing I've noticed in working with drawing tools is that the DOM properties offsetLeft/offsetTop/offsetWidth/offsetHeight seem to be reliable across all modern browsers and sometimes provides easier-to-use and more reliable metrics that dojo.coords, dojo.position or dojo.marginBox.

**Comment by jhpedemonte** [comment]
I cannot reproduce.  Tested on maqetta.org with Safari 5.1 (Lion).

**Comment by JonFerraiolo** [comment]
Just reproduced with Mac/Safari 5.0.5. I restarted Safari, emptied my cache, I went to http://maqetta.org, clicked on "Give it a Try", launched the application, and followed steps listed above, and same thing happened. I'm updating to Safari 5.1 now. (Requires system reboot)

**Comment by JonFerraiolo** [comment]
Closing. Works fine with Safari 5.1. I'll create bugs to update our code and docs to say Safari 5.1 or better is required. #826, #827
