### ISSUE TITLE
Absolute positioning misplaces new widgets if page is scrolled

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#825]
This problem exists for all browsers.
- New HTML file
- Go into absolute positioning
- Add two calendar widgets, one in middle of canvas, one at bottom of canvas
- Change window size so that the canvas gets a vertical scrollbar
- Scroll the canvas vertically
- Drag/drop a Button such that its top/left upon mouseup is very near the bottom/right of the first calendar (the one in the middle of the canvas)

Result => Button is shifted down by the amount that the canvas is scrolled

**Comment by peller** [comment]
dup of #147, fixed by bd539241f4c9505ef34f06285ee868f82a330641
