### ISSUE TITLE
Update browser check logic to require Safari 5.1 or better

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#826]
@jhpedemonte

**Comment by peller** [comment]
Is there something which requires 5.1?

**Comment by JonFerraiolo** [comment]
Yes. See #824

**Comment by peller** [comment]
versions in this message are pretty meaningless now, since the older versions are no longer available in the wild.

**Comment by peller** [comment]
@WayneVicknair: for completeness, was there a line of code checking dojo.isSafari >= 5 somewhere in Joomla?  If so, can you change it?
