### ISSUE TITLE
Update Dojo 1.7 as new stable releases appear

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#829]
@jhpedemonte

(For M3, leave Maqetta app on Dojo 1.6. This is about the version of Dojo we are using for the widgets.)

Ideally, we'd like Maqetta Preview 3 to use the officially shipping version of Dojo 1.7.0, but because of the likelikhood that Dojo 1.7 might be very late in arriving, we will probably have to ship a release candidate of Dojo 1.7 with Preview 3, and then maybe we might want to do a silent dot release update a bit later so that Preview 3.0.1 (or something like that)  includes the official final version of Dojo 1.7.

**Comment by peller** [comment]
This will be an ongoing task.  We're not able to take beta5, so we're probably staying put until M4.  moving to M4.  We did discover several beta5 issues which have been  reported to the Dojo team.

**Comment by peller** [comment]
7dacba4848a1bcb855ecd0ad5398121f5507ed0a upgrade to dojo 1.7.0b6

**Comment by peller** [comment]
see also 26824b4e2ecb4c63865eb51fe44a352c41cc5415 and 467898f93c96972152bba28f178cf0fecb653514
