### ISSUE TITLE
Work with Dojo team on JSONP support in data stores

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#830]
@jhpedemonte

For Preview 3, @billreed63 was forced to add some Maqetta-specific runtime logic in order to get cross-domain data stores to work. It seems like such a feature should be available as part of Dojo. Dojo does support JSONP in various parts of the toolkit, and with Dojo 1.7, supports cross-domain data stores via JSON-REST, but JSON-REST requires servers to support a new protocol, whereas JSONP has been around for a number of years and is likely already supported on many REST-oriented servers.

**Comment by peller** [comment]
Kris says you can use dojox.io.xhrPlugins with dojo.data also...

> kriszyp: well, for basic functionality, you could do store.get = function(id){ return dojo.io.script.get({url: id, callback:"callback"}); }; and something similar for query...
> kriszyp: or you could use dojox.io.xhrPlugins to use JSONP as an XHR provider
> kriszyp: and use JsonRest without touching the store at all (or not very much)

**Comment by billreed63** [comment]
We considered all these option before deciding that the cleans approach was to add a ItemJsonpReadStore, below are the limitations of each option.

Option 1)

We would need to add a bit of script to the HTML file that is something like for preview, but only if the user has choice jsonp as the store and we must remove it if they change their mind.

```
    <script>
        var callbackParmFor_ItemFileReadStore_1 = 'call_back_parm_for_service';

         function jsonpReplacementGet (args){
                   dojo.io.script.get({url: args.id, callback: args.callbackParm}); 
                    .
                    .
                    .
         }

        dojo.addOnLoad( function(){

               var store = dijit.byId('ItemFileReadStore_1');
                store.get = function(id){ return jsonpReplacementGet ({url: id, callback: callbackParmFor_ItemFileReadStore_1}); };  
                store.query = something_similar.... 

             }
        );
    </script>

    <span dojoType="dojox.data.ItemFileReadStore" id="ItemJsonpReadStore_1" url="http://ibm.com/jsonpService" jsId="ItemJsonpReadStore_1"></span>

</body>

```

And change all the helpers that deal with DataStores to do something equivalent for design time..

Option 2)  dojox.io.xhrPlugins to use JSONP as an XHR provider - If I understand xhrPlugins for cross site it still requires that the server add  Access-Control: allow <*>  to the header. Jon thinks this is an unreasonable requirement on the users.

Option 3) JsonRest - Jon does not think that REST services are widely implemented yet.

**Comment by billreed63** [comment]
Why do they put the close with the comment button!!!

**Comment by billreed63** [comment]
issue #469 is dependent on this issue

**Comment by billreed63** [comment]
resolved by using dojox.io.xhrScriptPlugin
