### ISSUE TITLE
Context/VisualEditor point to unknown DOM nodes

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#832]
- Reload Maqetta.
- Open Sample1.html.  Cycle through states.
- Close and reopen Sample1.html.
- Cycle through states.

After reopening the file, an error appears in the console when switching states. A TypeError as a result of a call in [Context.js](https://github.com/maqetta/maqetta/blob/0ae721d504c55874530b9a1de18922fd88b364da/davinci.core/WebContent/davinci/ve/Context.js#L716).  The error appears because `Context.getGlobal()` returns `null`.

Did some further research.  This is all done using Chrome:
1. Set breakpoint at line linked above (line # may have changed).
2. In new instance of Maqetta, open Sample1.html. 
3. Switch to a different state. You should hit your breakpoint.
4. In the console, type `this._editor.contentDiv`.  This should produce an HTML node, which when hovered over causes the Visual Editor iframe to be highlighted.
5. In the console, type `this._editor.contentDiv.parentNode.parentNode`.  Should be non-null and should highlight all of the VE when highlighted.
6. Close and reopen Sample1.html.
7. Redo steps 3-5.

You should see that after reopening Sample1.html, `this._editor.contentDiv` result, when hovered over, does not highlight anything on the page.  And `this._editor.contentDiv.parentNode.parentNode` is now null.

Somehow, `Context` and `VisualEditor` instances are out of sync with what is happening in the DOM, pointing to no longer usable DOM nodes.

My first guess is that this might have something to do with @peller's changes to not load the editor until the editor tab is viewed.  But that's just a wild guess at this point...

@JonFerraiolo @childsb

**Comment by peller** [comment]
My observation -- and coincidentally we talked about this on the call this morning -- is that the pub/sub for VisualEditor listens (subscribes) to three events for _each_ editor in its constructor, but the events are probably only relevant to the current editor, making this wasteful at best.  With the lazy loading changes, it means the event will get processed by dormant editors with null contexts and lead to an error.

**Comment by JonFerraiolo** [comment]
of course, you usually want to bulletproof such callback code. For example, make sure the context is not null.

**Comment by peller** [comment]
I disagree.  If context is null, it's sometimes an indication that it shouldn't be getting called.  The lazy loading has brought out some unnecessary processing, I think.

**Comment by JonFerraiolo** [comment]
Can't we agree that both sides should be cleaned up? We should define events and do event publishing in a manner that minimizes wasted processing, but callback functions should be paranoid and make sure everything is ok.

**Comment by peller** [comment]
I've been trained not to bullet proof code in JS with unnecessary null checks.  It's more of a coding habit about keeping code minimized than a performance issue.  In this particular case, a null check would have hidden a problem.
