### ISSUE TITLE
subscribe() getting called multiple times in Context.js

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#833]
In commit 0ae721d504c55874530b9a1de18922fd88b364da back from May, @peller added a `subcribe()` call in [`Context._processWidgets()`](https://github.com/maqetta/maqetta/blob/0ae721d504c55874530b9a1de18922fd88b364da/davinci.core/WebContent/davinci/ve/Context.js#L714)

However, this code is called from `Context._setSource()`, which is called many times during a Context instance's life, primarily if the user edits the source directly.

At the very least, I think that the `subscribe()` return value should be stored and that function should only be called once.  Correct?

Also, it doesn't look like there's any real reason why that call should be in `_processWidgets()`.  Can it be moved to the constructor, or some other place that isn't called as often as `_processWidgets`?

**Comment by JonFerraiolo** [comment]
First, for short-term, I'm pretty sure it would be OK to comment that code. The overlay widget logic in incomplete anyway at this point and if it causes bugs elsewhere, then deactivate the code until Adam finishes up the overlay widgets.

Regarding the subscribe() inside of _processWidgets, that is indeed a head-scratcher. I don't see any closure variables in scope, so it does seem that the subscribe should happen once and only once, such as what you suggest - in the constructor for that class.

**Comment by jhpedemonte** [comment]
Yes, I already talked to Adam about this over email.  He recognized the issues.  He asked me to open this bug in order to track this, and he'll fix it when he gets back.
