### ISSUE TITLE
Session expiration message / logic incorrect

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#834]
If the user leaves the web browser open, the session expires after some time and gets an "error loading plugins" message when the user returns.

The message needs to change on error handled properly on client.

**Comment by childsb** [comment]
From Jon-

Hi Wayne and Brad,
One problem which I do not believe is in the bug base yet is session timeout handling. If I click the "Try It" button on Maqetta.org, fool around for a bit in the app, and then leave that browser window open overnight, the session seems to have timed out, but the browser window is still open, so on the next day, when I try to use the application, I get a cryptic error message such as "plugin error" or "loading error". (Sorry I forgot to write down what the message was exactly.) We need to recover better in this scenario. I suspect this scenario will happen all of the time with Maqetta users. Other web apps will recognize that a session has timed out and redirect to a welcome/login page.

Could one of you create a bug for this for M4? I thought it better for one of you to volunteer to write up the bug because you know these technologies better than me and might provide a bug description that is more meaningful.

Thanks.
Jon

**Comment by JonFerraiolo** [comment]
@waynevicknair

Set to Priority-Medium at least to put some cycles into studying this issue to determine how bad this problem is, and suggest what changes we should make.
