### ISSUE TITLE
element IDs MUST be unique

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#835]
"Uncaught TypeError: Cannot call method 'getContext' of undefined" error shows up in console when a non-unique ID is entered into an HTML file.

Test Scenario:
- New HTML File
- Add a Button
- In Properties palette, set ID to "foo"
- In split view, copy/paste the INPUT element for the Button such that there are now two INPUT elements both with ID of "foo"

**Comment by JonFerraiolo** [comment]
The above case is just one symptom of a more general issue with the code. We have piecemeal logic to prevent duplicate IDs but don't have a robust approach. We need to identify all of the scenarios where there might be a duplicate ID created and do something to prevent it, either manufacture a new unique ID or stop the operation with a message to the user.

**Comment by peller** [comment]
duplicate ids aren't legal, but they are tolerated.  Perhaps we have to find a way to tolerate them, too?  The file may be imported with duplicated ids... it's not always a matter of catching user input.

**Comment by JonFerraiolo** [comment]
Duplicate IDs are not tolerated by dijit. If there are two dijits with the same ID, dijit posts an exception. 

In Maqetta, probably not totally fatal to have duplicate IDs, but will definitely end up causing things to break from a user perspective. Preventing duplicate IDs is one of those things that a tool should do on behalf of the user.

**Comment by peller** [comment]
perhaps, but it's not just a matter of catching bad user input.

**Comment by waynevicknair** [comment]
@peller @JonFerraiolo 
my thinking was to start with input validation. but, in the example scenario we would have to filter copy or paste actions. probably paste as we don't always copy from editor source.

**Comment by JonFerraiolo** [comment]
Yes, best to implement as part of paste action. 

Paste fix be a bit involved. Paste can happen both in visual pane and source pane. There are both permanent IDs that are serialized into user document and temporary IDs that Maqetta creates for its own use. Need to make sure neither permanent or temporary IDs are duplicated. For paste, I think the best thing is to run a check after the paste operation to see if the paste operation produced any duplicate IDs. If so, then replace all of the duplicate IDs with some other ID by postfixing some text to the original ID to make it unique (e.g., change "foo" to "foo_0") and then post an alert to user that lists all of the ID changes we made to ensure there were no duplicate IDs.

**Comment by JonFerraiolo** [comment]
Pushing to M5 with Priority-Med

**Comment by waynevicknair** [comment]
on the latest code (commit 73c8e41d22584741d69fccb8bdbffaa78e327dc2) visual editor displays message "Unable to parse HTML source.  See console for error.  Please switch to \"Display Source\" mode and correct the error." in 'canvas' giving user opportunity to correct error. javascript console contains "Tried to register widget with id==foo but that id is already registered" message which is right on the nose in terms of what to fix.

i believe this is as good as it gets as long as we re-parse the source on updates including paste operations.
