### ISSUE TITLE
m3 project migration

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#836]
Added projects to users folders, so need to migrate users workspace.

Method:

1) create <username>/project1 folder
2) move </username>/_._ to project1 folder

**Comment by waynevicknair** [comment]
plus, as with last migration:

3) remove .reviews directory

**Comment by waynevicknair** [comment]
4) remove .settings/workbenchState.settings file

**Comment by childsb** [comment]
Per issue #574 -  the sample files have moved to a read only plugin. Each users current sample files should be compared with the original and if no diff delete them.

---------------EDIT

This is no longer needed.  reverting change from issue 574 due to problems when relocating library.

**Comment by waynevicknair** [comment]
Reminder: possible impact from #889.

**Comment by JonFerraiolo** [comment]
@childsb, @jhpedemonte

Yes, we need to replace the existing ./maqetta/States.js in the users workspace with the new version. Probably best to replace the whole ./maqetta folder.

**Comment by childsb** [comment]
can just delete the maqetta folder.  maqetta/\* is now a library.

**Comment by waynevicknair** [comment]
need to copy a base 'libs.settings' file into the '.settings' directory as that file no longer gets auto generated.

**Comment by waynevicknair** [comment]
also needed to patch `dojo-theme-editor.html` to replace `../../../../../../app/static/lib/dojo/1.7/dojo/dojo.js` with `/maqetta/app/static/lib/dojo/1.7/dojo/dojo.js` in `<script>` tag.
