### ISSUE TITLE
Not purging dojo.require for widgets no longer in document

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#845]
@jhpedemonte
- New HTML file
- Add a Calendar
- Delete the Calendar
- Save, close, reopen

Result-> There is a dojo.require('djit.Calendar'); in the HEAD even though there are no Calendar widgets in the document.

**Comment by jhpedemonte** [comment]
This one will be tough.  You might have several widgets of the same type and you only want to remove that widget's `<head>` resources when the last one is removed.

I'd previously proposed creating a **widget model** which lives on top of the existing **file-level model**.  Whereas the latter tracks HTML elements, the widget model would track widgets and their dependencies.

One way to handle this particular issue would be for the widget model to keep track of everything that a particular widget adds to the page.  If there is a line that is used by more than one widget, then there is a reference counter that tracks how many widgets use that line.

Therefore, when a widget is deleted, we go through the widget model, which decrements the ref counters for associated lines.  Any lines with refcount of zero are deleted from the file-level model.

**Comment by peller** [comment]
How bad would the brute-force solution be, to iterate through widgets when one is deleted and regenerate the require list or compare and regenerate as needed?

**Comment by JonFerraiolo** [comment]
Brute force is probably ok. It's not like it's happening in a loop or anything. We are talking about something that would happen as a cleanup operation after finishing up a command (e.g., AddCommand, RemoveCommand, etc).

**Comment by wnm3** [comment]
How about an option to perform "Clean Up" which could remove unnecessary requires lines, and optionally might also perform some formatting to either allow the long html lines to be indented, or to compress with minimal white space (for publishing).

**Comment by JonFerraiolo** [comment]
If my memory is correct, we clean up the list of requires when a file is opened in the page editor. So, if user opens and saves, then that particular aspect of the file gets cleaned up.

Regarding formatting, we  indeed need improvements and enhancements in that area. (@waynevicknair) See #1417 for part of the problem: widgets that use SPAN for their root notes get concatenated on same line now. Because of that, Maqetta creates unreadable source code in lots of cases now. I think that's the biggest pain point now, but there are several other problems in this general area that also need to be addressed.

Regarding compression, we are hoping to do some sort of automatic build on user compositions so that preview-in-browser and installing the creations on a web server will run as quickly as possible. Automatic builds will also speed up opening up files in the review/commenting UI.

**Comment by wnm3** [comment]
It would be nice if such cleansing did occur, but I've tested as you've suggested and there remain requires statements for items like these that have no corresponding widgets in the html:

require(["dijit/layout/TabContainer"]);
require(["dijit/layout/AccordionContainer"]);
require(["dojo/data/ItemFileReadStore"]);
require(["dijit/Tree"]);
require(["dojox/grid/TreeGrid"]);
...

**Comment by JonFerraiolo** [comment]
@wnm3 is right, I was wrong, in Preview 4 we aren't cleaning up the `require` statements after widgets are deleted from the document. Maybe the old require removal logic was removed from the code or maybe the old require removal logic is only looking for dojo.require() and not require().

**Comment by peller** [comment]
I don't think we ever implemented the removal logic.  Is #1213 a dup?

**Comment by JonFerraiolo** [comment]
Yes, I believe #1213 is a dupe. I'll leave it to @peller and @jhpedemonte to figure out whether to close @peller's issue or close @jhpedemonte's issue.

**Comment by peller** [comment]
see also #1750

**Comment by jhpedemonte** [comment]
-> M6

Too risky for M5.  We've got several issues around this area and should fix them all for M6.

**Comment by jhpedemonte** [comment]
Dupe to #1213.
