### ISSUE TITLE
adding dojo Calendar generates internal error

### ISSUE THREAD

**Issue by stepheneb** [maqetta/maqetta#849]
I followed these instructions: https://github.com/maqetta/maqetta/wiki/Developer-Setup to setup a new maqetts instance and then the first tutorial about creating and editing an html file.

When I dragged a dojo calendar widget intio the canvas a dialog appeared that stated: _The action was interrupted by an internal error._ 

Here's what the screen looked like:

![screenshot](https://img.skitch.com/20110823-gisnc4h3yprf1y1dgy27m9afd.jpg)

Looking in the Chrome console I see many resources failed to load however here's the specific error when the claendar widget is placed:

```
GET http://localhost:55555/maqetta/app/davinci/ve/input/CalendarInput.js?revision 404 (ProxyServlet: /maqetta/app/davinci/ve/input/CalendarInput.js)
app/dojo/../davinci/ve/tools/CreateTool.js:144
Error
arguments: undefined
get stack: function getter() { [native code] }
message: "Could not load 'davinci.ve.input.CalendarInput'; last tried '../davinci/ve/input/CalendarInput.js'"
set stack: function setter() { [native code] }
type: undefined
__proto__: ErrorPrototype
```

I see a similar issue with FF V6

**Comment by stepheneb** [comment]
I also noticed these (possible) issues in the osgi console:

```
Setting [user space] to: /Users/stephen/dev/test/maqetta
servlet parm 'maqetta.maxUsers' is : null
Library file not found! :WebContent/jquery-ui-1
Library file not found! :WebContent/yui
Library file not found! :WebContent/jquery-ui-1
Library file not found! :WebContent/yui
```

**Comment by JonFerraiolo** [comment]
@jhpedemonte

I'm pretty sure I know what's wrong with the message "Could not load 'davinci.ve.input.CalendarInput'...". I believe we recently moved the _Input.js files out of davinci.core/WebContent/davinci/ve/input into davinci.dojo_1_7/WebContent/metadata/dijit/_, but we didn't update the references within davinci.dojo_1_7/WebContent/metadata/widgets.json.

Regarding the OSGI messages for jQuery and YUI, I think @jhpedemonte might be able to help.

**Comment by jhpedemonte** [comment]
The Developer Setup page hadn't been updated to state that we are running from the `dojo_1_7` plugin (not the old `dojo_1_6`).

@stepheneb, in Eclipse, open the **Run Configurations**, select your Maqetta run config, and in the **Bundles** tab, deselect **davinci.dojo_1_6** and instead select **davinci.dojo_1_7**.  **Run** and you shouldn't get that issue any more.

(Actually, you may have to clear out your user space at `/Users/stephen/dev/test/maqetta`, since one of the settings files may still point to `dojo_1_6` bundle.)

**Comment by stepheneb** [comment]
I had both davinci.dojo_1_6 and davinci.dojo_1_7 selected in the bundles. I removed davinci.dojo_1_6 and ran the app.

I no longer get the error message after dragging a Calendar object into the html canvas.

I do not get any properties/edit dialog when double clicking the Calendar however. I've just started playing with maqetta and am not certain if I should see some sort of inspector/editor when double-clicking the Calendar. I do see one when double-clicking the Button.

What do you mean by "clear out the user space"? Here's what's in `/Users/stephen/dev/test/maqetta` now:

```
$ ls -l /Users/stephen/dev/test/maqetta
total 0
drwxrwxrwx   2 stephen  staff   68 Aug 23 12:10 files
drwxr-xr-x  19 stephen  staff  646 Aug 23 11:41 maqetta
drwxr-xr-x  11 stephen  staff  374 Aug 24 00:15 project1
```

FYI: I'm using these arguments in the run configuration:

```
-Declipse.ignoreApp=true -Dosgi.noShutdown=true 
-Dorg.eclipse.equinox.http.jetty.context.path=/maqetta 
-Dorg.eclipse.equinox.http.jetty.http.port=55555
-Dmaqetta.baseDirectory=/Users/stephen/dev/test/maqetta
-Dmaqetta.localInstall=true
```

**Comment by billreed63** [comment]
For preview 2 dojo_1_7 we removed the Smart Input for the Calendar widget #668

**Comment by jhpedemonte** [comment]
Stephen, if it's working for you now, then just ignore my comment about clearing out the user space.  No need.
