### ISSUE TITLE
Does our metadata cover AMD?

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#854]
Right now, we insert dependencies for Dojo (dojo.require) using the $text property in our metadata.

With AMD, for Dojo and potentially for non-Dojo code, this would require inserting an AMD wrapper with a dependency list and a function closure.  Is this possible using metadata?  Is this also an issue for OAA?

**Comment by jhpedemonte** [comment]
Could you please post an example of what the `<head>` should look like with AMD?  For example, after adding a `dijit.form.Button`.

**Comment by peller** [comment]
``` xml
    <meta charset="utf-8"> 

    <link rel="stylesheet" href="path/to/dijit/themes/claro/claro.css"/> 
    <script type="text/javascript" src="path/to/dojo/dojo.js" data-dojo-config="..."></script> 

    <script type="text/javascript"> 
        require(["dijit/form/Button", ...]);
    </script>
```

**Comment by jhpedemonte** [comment]
Oh, so you're saying that if we add multiple widgets, their type would get added to the string within `require()`, right?

Of the top of my head, I don't think this can be handled by OAM.  It would only work if each widget type got it's own `require()` statement (which I guess would still work).

At the moment, I'm not sure about the best way to handle this.  Might be we need to make use of the `onAdd()` library callback.

**Comment by jhpedemonte** [comment]
Dupe to #1174, where most discussion it taking place.
