### ISSUE TITLE
Implement states for overlay widgets

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#86]
Create states for dialog, tooltip widgets to show/hide widgets in visual editor, but not at runtime.  To be used in review & commenting mode

**Comment by peller** [comment]
A few obvious problems we need to look at:

1) Tooltip is different from Dialog in that its state at runtime is implicit and not programmatic.  The state presently is only used at design time.
1a) review and commenting uses the runtime mode, so the state presently does not bring up the tooltip the way it brings up dialog
2) you can't overlap states.  only one is active at a time, and the state is directly tied to showing and hiding a particular widget.  For example, suppose there's a dialog and a tooltip.  The states let you show one or the other, not both.
3) dialog states make a lot of sense when used consistently, to show and hide the widget.  however, if some other code shows or hides the dialog (e.g. the close button) then the states no longer reflect reality.  binding visibility changes to the state sounds complicated.

**Comment by peller** [comment]
review by @JonFerraiolo

**Comment by JonFerraiolo** [comment]
Adam and I walked through the testplan and the UI and came up with various follow-on tasks which will be addressed in coming weeks. Great progress so far.
