### ISSUE TITLE
NPE when closing visual editor

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#860]
0) enable halt on errors in FF debugger
1) Open sample1.html
2) close sample1.html
3) observe error: "davinci.Runtime.currentEditor is null "

**Comment by JonFerraiolo** [comment]
Assigning to @peller just so that it isn't unassigned but maybe should go to @waynevicknair

**Comment by peller** [comment]
I can't reproduce this.  @childsb, can you?
