### ISSUE TITLE
remove davinci.ve.widget.widgetHash

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#861]
need to replace this, probably with something bound to the Context object.  widgetHash is presently keeping a single hashtable for all editor instances, so there are collisions (and leaks)

@jhpedemonte

**Comment by peller** [comment]
tried removing in 3002a235441c8121a09af36f5085f28940da42ea

**Comment by jhpedemonte** [comment]
What happened here?  Why did you revert the first commit?

**Comment by peller** [comment]
'cause without a replacement for the hash, you can't add a widget to the page.  Well, now I know where it fails.  I put it back until we have something else working.

**Comment by peller** [comment]
I'm not comfortable reworking the widget initialization in M3, so pushing to M4.  This is important cleanup, but will only cause instability in the near term.

**Comment by JonFerraiolo** [comment]
Closing. widgetHash logic is ok now.
