### ISSUE TITLE
Changes are wiped out in Source edit view

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#865]
typing is getting eaten in source view and caret is getting positioned at top of file on each keystroke.

Open Sample1.html
Click on a split view or source view
Position caret in <label> tag and try to add a 'title' attribute

**Comment by jhpedemonte** [comment]
Is this really fixed? If so, please close issue.

FYI, GitHub only recognizes a few phrases during commits in order to close an issue, such as "fixes #XXX", "fix #XXX" or the same but using "close" instead of "fix".
