### ISSUE TITLE
Source editor does moves cursor to position 1,1 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#866]
If I am typing in the middle of the page and pause for a second the source editor does a setSource which causes the cursor to move to the first line and first position (1,1). The effect is that if I am deleting or add content in unintended places making the source editor unusable

**Comment by peller** [comment]
@WayneVicknair, is this what you're seeing?

**Comment by waynevicknair** [comment]
duplicate of #865

**Comment by billreed63** [comment]
fixed by #865
