### ISSUE TITLE
Better hourglass implementation

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#87]
## I put this comment into the wrong bug report! Here it is, on the correct bug:

As we talked about in today's call, one of the challenges with adding hourglass
support (such as using the Standby widget) is that the animation gets blocked
when using syncXHR, with the result that even an initial view of the standby
icon might not appear without some ugly, hard-to-maintain code hacks, which we
really don't want to do because we want to replace syncXHR with asyncXHR
anyway.

For the short-term, in some scenarios (such as welcome screen launching the
app), we might be able to post an overlay DIV that says something like
"Loading..." just before changing window.location.href to switch to the main
application. Even though "Loading..." isn't animated, at least the user will
have _some_ visual feedback that the button click was registered and something
is about to happen.

**Comment by jhpedemonte** [comment]
Fix commit: 5d8b34afb65df264df2190fc3b3eb7062e79c4bc

**Comment by billreed63** [comment]
June 2011

**Comment by JonFerraiolo** [comment]
Reopening we have made progress but lots of work still to do. ->@peller  M6 Prio-Med. (if not M6, then M7 Prio-High)

**Comment by JonFerraiolo** [comment]
-> @peller

**Comment by peller** [comment]
we have async loading now, so the spinning graphic actually spins.  That was the original problem here, so I think we can close.  If there are other long-running operations which require some sort of loading UI, we should open separate issues.
