### ISSUE TITLE
Icon problems in page editor with dojox.mobile widgets

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#878]
@jhpedemonte

Using Mac/FF6 and today's build (2011-08-30) and running the mobile tutorials, some dojox.mobile icons look wrong in the page editor (but look fine in preview-in-browser). The two bad icons are the arrow icon on ListItem:

![alt text](http://i51.tinypic.com/20gnq8h.png)

 and the back arrow icon on Heading:

![alt text](http://i53.tinypic.com/30c5eko.png)

**Comment by peller** [comment]
I'm unable to reproduce this on FF7.  Have not yet tried FF6

**Comment by JonFerraiolo** [comment]
Today I can't reproduce with FF6.0.1 on Mac. I'll try on Win/FF later. As you can see from the pictures above, I didn't dream this :-)

**Comment by JonFerraiolo** [comment]
I'm closing this bug. I couldn't reproduce in Win/FF601 either. Maybe Javier's fix for dealing better with theme CSS files had a pleasant side effect. If we see this problem again, we can re-open.
