### ISSUE TITLE
Missing icons for "new folder" & "upload file" in Files context menu

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#884]
Since it's been bothering me for a while, I added the red-X delete icon to the **Delete** item in the Files view context menu.  While there, I also added an icon for **Download**:

![Files view context menu](http://i.imgur.com/HUzQX.png)

But we need icons for **New folder** and **Upload File**.  I looked through our existing icons, but didn't find anything we could use.

@jmockler, any chance you could whip something up for these two?

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
Push to M5?

**Comment by jhpedemonte** [comment]
Pushed to M5.

**Comment by jhpedemonte** [comment]
-> M6/Med

**Comment by jhpedemonte** [comment]
@JonFerraiolo, did we ever get these icons?

**Comment by jhpedemonte** [comment]
-> M7

**Comment by JonFerraiolo** [comment]
-> M7 Prio-Med not a ship stopper and anyway we want to move those features from context menu to toolbar on palette

**Comment by JonFerraiolo** [comment]
This has been fixed. Closing.
