### ISSUE TITLE
Update "Done" back to "Upload" after selecting more files

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#888]
Two small UI issues with Upload command:

1) The Upload command doesn't reset the button text to "Upload" if you select another set of files:
- In Files palette, bring up context menu and select "Upload"
- Select one or more files
- Click "Upload" to upload. Button changes from "Upload" to "Done"
- With dialog still up, click "Select files" again and pick one or more files

Result=> Button still says "Upload". Should have changed to "Done" upon selecting more files

2) The dialog title should be "Upload Files" instead of "Add Files"

**Comment by peller** [comment]
I just disabled the select files button and made the dialog a single-use. Seems more straightforward.  See #591 for long-term discussion.

**Comment by JonFerraiolo** [comment]
That's OK for M3, but I'm not sure that this change overall is better than the bad label.

IMO the dialog wasn't great but was actually serviceable except for the button label issue I reported. It's common for designers to have a bunch of files they need to upload, so allowing the same dialog to be available for multiple uploads was a good thing. With this change, they have to use context menu multiple times. With old approach, they could upload one after another and then click "x" to pull down. Old dialog seemed fine to me so long as we could change "Done" to "Upload" after user selected a new set of files.

**Comment by peller** [comment]
Yeah, ok, but it seems inconsistent to have a long running Dialog.  I could very easily flip it to do what you describe, but our other dialogs don't work that way.  Note that the dialog lets you upload multiple files already.  The temporary status message in the dialog, I thought, only makes things more confusing -- something I'm sure we'll address in #591.

**Comment by JonFerraiolo** [comment]
If "very easily" is true, could you please indulge me? :-) I realize it's inconsistent with everything else, but for next N months, this change would be a reasonable stopgap for a feature that a large percentage of real users say that they use.

**Comment by peller** [comment]
It feels wrong for so many reasons... including the fact that a slow download could mean the user is selecting new files (while the status may or may not be present) and be faced with a "Done" button rather than an upload... but ok, I'll give it a shot

**Comment by peller** [comment]
tried to fix button enablement logic also.  it's still possible to cancel out of the file selection and hit upload, which is just ends up being a no-op.  Good enough for now.
