### ISSUE TITLE
Migrate recent changes from davinci/maqetta/States.js to runtime States.js

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#889]
I've made a few changes to the version of States.js used by Maqetta. These changes need to be merged into the version of States.js that is used for preview-in-browser and review-and-commenting.

**Comment by waynevicknair** [comment]
This impacts #836 right? We now have to update the States.js in the users' workspaces.

**Comment by JonFerraiolo** [comment]
Fixed by c570437b3f
