### ISSUE TITLE
Sometimes Sample1.html disappears from files palette

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#890]
@jhpedemonte

Haven't been able to find a sequence of steps reproduce, but I swear Sample1.html sometimes disappears from the Files palette. Logging this bug to be on the lookout for a reproducible scenario.

**Comment by childsb** [comment]
changing priority until we find a recreate.

**Comment by JonFerraiolo** [comment]
I still haven't reproduced, but I continue to see it. It's not just Sample1.html. I saw it yesterday with file1.html. It disappeared from Files palette, but when I did a browser refresh, it showed up again. Somehow or other the data store behind the Files palette is dropping items even though nothing has happened on the server.

**Comment by JonFerraiolo** [comment]
Reproducible case: 

1) OpenSample1.html
2) Refresh browser. Sample1.html reopens, but with dirty bit on
3) Close Sample1.html editor window

Result=> Sample1.html disappears from Files palette

**Comment by childsb** [comment]
Fixed with commit b0d06b84c565a23b50e5f061e2e3cd010ab2e05b

Thanks for finding this test case!
