### ISSUE TITLE
Sometimes select jumps to top in source view

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#891]
@jhpedemonte, @peller

Just saw this, and not sure how often it happens or whether it is reproducible. Logging this for us to be on lookout.

I was running the mobile tutorial. At the point in the tutorial where the user creates a DIV with the text "Today's alerts", sets margin to 1em, then is about to copy/paste that DIV. Because of a paste bug that we have, I tried to copy/paste in split view within source pane. However, whenever I tried to select the DIV with "Today's alerts" inside, the selection (and source pane) jumped to the 0.0 point. I was trying to drag select the lines with the DIV for "Today's alerts" by starting the drag at the left edge of the first line for that DIV. I am using Mac/Chrome.

**Comment by waynevicknair** [comment]
I cannot reproduce on latest commit on Chrome/Mac. Adam could not reproduce either. I will continue attempts during my testing this afternoon.

**Comment by JonFerraiolo** [comment]
I'm seeing this all of the time today, but when I tried just now to package up a set of steps to recreate, problem went away. I'll keep trying to reproduce.

**Comment by JonFerraiolo** [comment]
I tried to reproduce and couldn't. I'm closing this bug, but it @billreed63, @peller and @jhpedemonte could also try to reproduce, and reopen if they see this problem during their testing, then that would be great.

**Comment by peller** [comment]
will keep watching. I saw this weeks ago, but have not seen since.

**Comment by billreed63** [comment]
I have not seen this in a while, I do see this behavior if I have the debugger running and break points set in ve.context setContent. After a few changes in the source editor the model is change which will invoke context.setContent..

But should not happen to the user
