### ISSUE TITLE
Exception: could not find resource projects1/themes/claro/claro.blah

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#892]
@peller

I ran into this but so far haven't been able to find a set of steps to reproduce.

I loaded Sample1.html, had the Properties palette showing the cascade for the 'color' property, and then I clicked on the "New' button on the canvas. I got an exception at Cascade.js:107 (last line of _canModifyRule) because variable resource was null. The path for the resource was projects1/themes/claro/claro.blah (I think "blah" was "css" but I'm not sure). Tracing through the debugger, resource is null if findResource returns null. Looking at findResource, what I was seeing was that segment #1 was failing (i.e., "themes"). 

But when I tried to reproduce, everything worked fine. I wonder if recent changes to how the themes/ folder is managed might have introduced a bug or maybe if lazy loading logic might contribute to problem. (I did have 2 files open when I ran into this bug.)

**Comment by childsb** [comment]
i'll test this, but for now, changing priority until we can find a way to reproduce

**Comment by childsb** [comment]
This seems to be working fine now-- i tested for a bit and couldn't reproduce.
