### ISSUE TITLE
Style rules changes to app.css not working

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#893]
@jhpedemonte

Attempts to add new style rules to app.css are no longer working. I suspect it has to do with our new support for projects, where app.css is shifting inside of the proejct1/ folder.
- New HTML file
- Add a Button
- In Properties palette, go to "Fonts and Text" and the click on right arrow to show cascade for 'color' property
- At top of Properties palette, enter "bbb" into the class attribute. A new entry should appear in cascade that says "New style rule" using class "bbb".
- Click the radio button by the new style rule entry in the cascade
- Using menu, choose "green" or any other color value

Result => Error message in console

app/dojo/../davinci/ve/VisualEditor.js:147 Cascade._changeValue: can't find targetFile

**Comment by childsb** [comment]
This started working after commit 98877c79afb4127ef94ba4b480a926f02cc8ad3e
