### ISSUE TITLE
Sometimes dropping Dojox Mobile widget produces unstyled widget

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#899]
Sometimes, dropping a Dojox Mobile widget doesn't produce the expected result.  It looks like the CSS isn't getting loaded in to the page, and the widget shows up unstyled.

This doesn't always happen.  And many times, it will right itself, with the CSS being loaded in to the page and the widget appearing correctly.

Opening Preview or closing/reopening the page correctly show the widget.

@JonFerraiolo @waynevicknair

**Comment by jhpedemonte** [comment]
So, today, I have it consistently breaking on my system.  I'm using Chrome on Mac OS X Lion:
1. Clear cache and reload Maqetta.
2. Open new HTML page.
3. Drop Dojox Mobile **Heading** widget on page.

The Heading widget consistently shows up broken.

---

I added some `console.log` calls in the code, but everything seems to be loading correctly and in the proper order:

```
Context.loadSTyleShee(themes/claro/claro.css)
Context.loadSTyleShee(app.css)
Context.loadSTyleShee(http://localhost:8081/maqetta/app/davinci/ve/resources/content.css)
Context.addJavaScript(./lib/dojo/dojo/dojo.js, null)
Context.addJavaScript(null, dojo.require('dojox.mobile');)
Context.addJavaScript(null, dojo.require('dojox.mobile.parser');)
Context.addJavaScript(null, dojo.require('dojox.mobile.compat');)
Context.loadSTyleShee(./lib/dojo/dojox/mobile/themes/iphone/iphone.css)
AddCommand.execute()
```

---

If I inspect the DOM, I see the `<link>` tag that brings in the **iphone.css** file.  But the CSS doesn't seem to be loaded in the page.

**Comment by peller** [comment]
Is this specific to Chrome?  I can only recall seeing it on Chrome.

**Comment by jhpedemonte** [comment]
Cannot reproduce on Firefox 5, but can recreate on Safari 5.1.  Maybe it's a WebKit issue?

**Comment by jhpedemonte** [comment]
Man, I am boned!

So I found a workaround: instead of creating a `<link>` element in order to load the CSS into the DOM, I rewrote `Context.loadStyleSheet()` to load the CSS file using XHR and then add the file contents into a `<style>` element.  In order to test, I reverted to an old version of **Heading_oam.json** which directly included the **iphone.css** resource, instead of the current use of **deviceTheme.js** (which automatically loads the appropriate device CSS).

So I finally have it working well and this problem seems fixes, when I undo the changes to **Heading_oam.json**.  Now, I'm still seeing the same issue, even with my workaround.  The problem is that with the Dojox Mobile widgets all using **deviceTheme.js**, the code in that file loads the CSS by creating a `<link>`!  So, I'm back to square one.

Any suggestions, @peller?

**Comment by peller** [comment]
That was a good try!  No great ideas here... I see the style sheet even show up in the resources view of the debugger, so not only does the stylesheet load, but it seems to get associated with the iframe.  It feels like a browser bug.  Perhaps you could try shortening the stylesheet, perhaps even to a single rule (one you'll know would be applied to the document) and see if that works, then build up from there?   Perhaps there's something in the css that's tripping up the initial association, or perhaps it's something to do with the size/complexity of the stylesheet?

**Comment by JonFerraiolo** [comment]
I don't know if this helps, but when I was doing the SVG silhouette stuff, I noticed Chrome was showing that it had loaded foo.svg, and the document was pulled down off of the net, but an older file was there and not foo.svg. I worked around this by doing an explicit verification that contentDocument's URL was in fact a match for the URL I was attempted to pull down, and if not, then try again in a timeout loop. Look at the comment and code at preview/silhouetteiframe.js:206. One thing in common with the silhouette scenario and this situation is that in both case there is an inner iframe.

**Comment by jhpedemonte** [comment]
You can view a page's style sheets by checking the `document.styleSheets` list. In the failing case, I do not see an element for the **iphone.css** style sheet, even though **Inspector->Resources** says it is there and there is a network call to retrieve it.  But later, when the DOM rights itself, I do in fact see **iphone.css** in `document.styleSheets`.

So the CSS file is getting loaded by the browser, but not evaluated in the page.

---

Putting a `setTimeout` of zero around `dojo.require('dojox.mobile.deviceTheme')` works to fix the issue.  With this, the CSS file is loaded **after** the widget node has been added to the page.  This doesn't necessarily prove that this is a timing issue, since now the browser may be going down different paths.

Unfortunately, to use this workaround, we'd need to add the `setTimeout` to all the mobile widget metadata files.

**Comment by jhpedemonte** [comment]
Pre-caching (doing an XHR Get of **iphone.css** before adding **Heading**) doesn't fix the issue.

**Comment by peller** [comment]
With @JonFerraiolo's help, I think I understand what's going on here.  It seems Context.setMobileDevice is setting the css after all (I'm not sure if dojox.mobile is also)  What's suspect is that the method is called in the middle of the bootstrapping, which I guess didn't work (see #460) and Bill's workaround to do a setTimeout in d63285a0c4fda0d3359c.  I broke in this method and noticed that although the LINK elements had been (removed and) added to the DOM, document.styleSheets.length was 0.  @jhpedemonte noticed that when the bug occurs, document.styleSheets.length == 3 and is missing the dojox.mobile stylesheet, even though it's in the DOM.  I have a feeling ripping the css out of the DOM and replacing it in the middle of page load is a bad thing... I'm going to try moving it.

**Comment by peller** [comment]
w00t!

**Comment by jhpedemonte** [comment]
So, not totally fixed.  Save a page with a non-iPhone silhouette and reopen -> page has iPhone CSS (should have CSS corresponding to silhouette).

**Comment by jhpedemonte** [comment]
```
_setSource()
   mobileDevice = context.getMobileDevice()
   visualEditor.setDevice(mobileDevice)
      context.setMobileTheme(mobileDevice)
         oldDevice = context.getMobileDevice()
         if (oldDevice === mobileDevice) return;   *
```

`* denotes new code`

When opening a saved page, `oldDevice` will always equal `mobileDevice`, and therefore the non-iPhone CSS doesn't get loaded.

**Comment by jhpedemonte** [comment]
An attempt to fix the remaining issue.  Not closing this bug yet.  Adam (and anyone else), please review and let me know what you think.
