### ISSUE TITLE
duplicated adding css to html code when drawing.

### ISSUE THREAD

**Issue by Jawf** [maqetta/maqetta#9]
Browser type: Google Chrome
Browser version:8.0
OS and OS Version: Windows XP
All steps necessary to reproduce the issue:

```
  1. Drag and drop the dojo TabContainer widget to designer editor. The HTML code will add below code:
  @import "./lib/dojo/dojo/resources/dojo.css";

  2. Delete the TabContainer widget.

  3. repeat the 1 step. The duplicated code generated:
  @import "./lib/dojo/dojo/resources/dojo.css";
  @import "./lib/dojo/dojo/resources/dojo.css";
```

Reporter: Jawf Lee(homcto@gmail.com)

**Comment by JonFerraiolo** [comment]
Probably highly related to #71

**Comment by JonFerraiolo** [comment]
We fixed this. Closing.

**Comment by Jawf** [comment]
Great Thanks:)

On Wed, Jul 18, 2012 at 6:15 AM, Jon Ferraiolo <
reply@reply.github.com

> wrote:
> 
> We fixed this. Closing.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maqetta/maqetta/issues/9#issuecomment-7051232

## 

Yours sincerely,
       Jawf Neo Lee

--------Do well when you do!--------
