### ISSUE TITLE
FixedSplitterPane and SpinWheelSlot generate exceptions when dropped on invalid parent

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#900]
@peller, @billreed63

Maybe this bug was introduced by recent related changes from @jonferraiolo, @peller, @billreed63.

New HTML file. Then try to drag/drop either FixedSplitterPane or SpinWheelSlot onto canvas. You get an "internal error" dialog instead of the "invalid target" dialog.

**Comment by peller** [comment]
see 726a1139b9833e671b09913d23a858fa5bc38dca which fixes mistakes I made in d1e1e111254c8e999beb

**Comment by JonFerraiolo** [comment]
For me, checkin  726a113 breaks a whole bunch of other widgets. Can't drag/drop add a dijit.form.Button now.

**Comment by peller** [comment]
yah, it did, sorry.  aea4686496baf857029ba237bc81b4ec88af0b2c should have fixed it.
