### ISSUE TITLE
SaveAs CSS drops current content

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#901]
- New CSS File (e.g., file1.css)
- Enter a CSS comment (e.g., /\* hello */)
- Immediately do a SaveAs to file1a.css

Result=> file1a.css has no content. (Same thing happens if you do a Save and then immediately a SaveAs)

Not essential for M3, but since SaveAs for CSS was supposedly one of our fixes, would be nice to fix.

**Comment by waynevicknair** [comment]
Turns out this issue is narrower in scope than previously thought. I can add a CSS rule instead of a comment and the saveAs works just fine. I can also add a comment above the newly added rule and that works as well. That narrows it down to CSS comments at the end of a file get dropped.

**Comment by waynevicknair** [comment]
temporary fix e9cbca30da

**Comment by waynevicknair** [comment]
moving to M5

**Comment by waynevicknair** [comment]
i cannot recreate this one on the latest code.
