### ISSUE TITLE
dojo not defined with New HTML File after creating Eclipse-compatible workspace

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#904]
- Remove users/ folder, restart server, to create a virgin user workspace
- New Project "myproject1" with checkbox turned on for Eclipse compatibility
- New HTML File, for file1.html, selecting myproject1/WebContent as parent folder

Result=> Console says "1Uncaught ReferenceError: dojo is not defined". After seeing this message, I went into split view and looked at the HTML file source code, and there is no SCRIPT tag for dojo.js

**Comment by childsb** [comment]
Fixed with commit de6c781742d1e8329fcc1a6c4938496a454c47d8
