### ISSUE TITLE
New theme: dojo.css not found - URL missing "project1"

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#905]
@billreed63
- Clean, brand new user workspace
- Launch Maqetta
- New Theme "a1" built from claro

Result=> Console shows error message saying unable to load resource http://localhost:55557/maqetta/user/maqettaUser/ws/workspace/lib/dojo/dojo/resources/dojo.css. The URL is missing the "project1" segment.

**Comment by childsb** [comment]
Is this causing a bug besides the console?

Neither myself or @billreed63 can find where dojo.css is being included, and it doesn't seem like it has an impact on the theme editor functionality.  The claro.css file appears to have merged all of dojo/dijit CSS into a top level file and not include them any longer.

lowering priority for now.

**Comment by childsb** [comment]
fixed with f02efe9028ce4b534127ecd60d9834b95d83b252 , also noticed CSS paths are incorrect.. fixing in separate checkin
