### ISSUE TITLE
New theme dying in States.js

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#906]
Bill, this might be my bug, but sending this to you because I don't understand what the theme editor is trying to do.
- Fresh new user workspace (e.g., restart server)
- Launch Maqetta
- Immediate issue a New Theme command to create theme a1 out of claro

Result=> Uncaught TypeError: Object $all has no method 'getParent'. Stack trace:

```
Uncaught TypeError: Object $all has no method 'getParent'
subscribedapp/dojo/../davinci/ve/States.js:123
dojo.hitchapp/dojo/./_base/lang.js:130
dojo._listener.getDispatcherapp/dojo/./_base/connect.js:27
dojo.publishapp/dojo/./_base/connect.js:274
initialSetapp/dojo/../davinci/ve/themeEditor/VisualThemeEditor.js:108

```

The line where this dies contains code that I added in the last 24 hours to deal with other bugs. But with the theme editor, the value of widget is $all instead of a pointer to a real widget. What is supposed to happen with $all?

**Comment by billreed63** [comment]
States is not used by ThemeEditor so we should not be getting to that line of code...

the code should be checking for themeEditor and bailing.

**Comment by billreed63** [comment]
states was checking for the wrong class name for theme editor
