### ISSUE TITLE
CSS files have wrong URL when creating HTML file in nested folder

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#907]
- Virgin workspace (close server, remove users/ folder, restart server, clear cache, relaunch Maqetta)
- New folder "folder1"
- New HTML file inside of folder1
- Add a Button

Result => Button has no styling. Console shows messages:

```
claro.css GET http://localhost:55557/maqetta/user/maqettaUser/ws/workspace/themes/claro/claro.css 404 (Not Found)
app.css GET http://localhost:55557/maqetta/user/maqettaUser/ws/workspace/app.css 404 (Not Found)
```

**Comment by childsb** [comment]
Fixed with commit de6c781742d1e8329fcc1a6c4938496a454c47d8
