### ISSUE TITLE
EventCommand.js basically broken

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#908]
Undo doesn't seem to be working when changing event properties in the Properties palette, which goes through EventCommand.js.
- New HTML file
- Add a LABEL
- Set onclick property, such as onclick: console.log('ccc')
- Undo

Result=> onclick property still show console.log('ccc'). I don't think this is simply a redraw problem in Properties palette. If you have 2 widgets and select the other than go back to the LABEL, the onclick property is still there. (Changing selection updates all fields in the Properties palette)

**Comment by JonFerraiolo** [comment]
Pushing to M5, Priority-Med. We might want to reassign to @childsb or @JonFerraiolo

**Comment by jhpedemonte** [comment]
Reassign to Doron.  Take a look and assess risk for M5.

**Comment by doronrosenberg** [comment]
The issue is that we call:

```
  widget.setProperties(this._oldProps);
```

during undo.  That won't remove any new properties such as the onclick.  No risk here really, should be easy to fix

**Comment by doronrosenberg** [comment]
@JonFerraiolo the event properties is not being refreshed during undo/redo as well, where does that code live?
