### ISSUE TITLE
Anyone actually use davinci.ve.themeEditor.VisualThemeOutline?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#912]
(I recommend not rocking any boats for M3)

I put a break point in the constructor for davinci.ve.themeEditor.VisualThemeOutline, opened the theme editor, and the break point is never reached. Is this JS file obsolete?

**Comment by peller** [comment]
There's no outline in themeEditor, so what you say makes sense.  I suspect most of the classes were cloned based on the naming pattern.

**Comment by billreed63** [comment]
removed long ago
