### ISSUE TITLE
Hang in split view with Sample1.html

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#915]
@peller, @billreed63

(using http://maqetta.org/nightly/maqetta-20110901-0603.zip on Mac/Chrome and Mac/FF601. Also happens in Win/Chrome. Haven't tested Win/FF yet.)
- Open Sample1.html
- Go into split view (top/bottom)
- Put type-in the <title> element just before "Sample1.html"
- Type a letter

Result=> "Loading" appears in visual canvas and never goes away. Either infinite loop or an event that triggers removal of the "Loading" overlay is never received.

**Comment by waynevicknair** [comment]
Bill's fix d1be24b438413833ec586d3cc3fa8b565660ebe6 took care of this one.
