### ISSUE TITLE
YUI and jQuery widgets not displaying properly

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#918]
@childsb, @peller, @waynevicknair

YUI and jQuery widgets don't display properly using today's nightly from Maqetta.org

The lib/ folder in the workspace doesn't show jQuery or YUI folders inside

**Comment by waynevicknair** [comment]
i'm seeing this in the console output:

```
Library file not found! :WebContent/jquery-ui-1
Library file not found! :WebContent/yui
```

while loading the `Sample1.html` file.

**Comment by waynevicknair** [comment]
I checked the external build machine and found that the build script had not kept up with the latest build modifications. It is now up to date. A new external build was published here http://maqetta.org/nightly/maqetta-20110901-1422.zip. I ran it and was able to drag and drop JQueryUI and YUI widgets into a newly created HTML file.

**Comment by JonFerraiolo** [comment]
Reopening. (@childsb)

Running from both daily builds and launching from Eclipse, jQuery and YUI widgets aren't working. HTTP requests for jQuery libraries is failing with 404:

```
Problem accessing /maqetta/user/maqettaUser/ws/workspace/project1/lib/jquery-ui/jquery-1.4.4.min.js. Reason:
NOT_FOUND
```

One hint: I don't see jQuery and YUI folders in my workspace within ./lib

**Comment by jhpedemonte** [comment]
This was already closed for M3.  Moving discussion to #1229.
