### ISSUE TITLE
File upload does not refresh tree

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#921]
1) create new folder 'wwww'
2) right click on folder 'wwww' 
3) upload file

If I upload the file again I do not receive a file exist warning

File is successfully uploaded but file explorer is not refreshed. I have to refresh the browser to see the file.

**Comment by childsb** [comment]
Good bug, thanks bill.

Fixed with checking b158322b78d594f321b597d316efedddd830b711
