### ISSUE TITLE
uniqName_1 appears in Outline palette instead of ComboBox for Sample1.html

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#928]
@jhpedemonte, @peller

With today's build (http://maqetta.org/nightly/maqetta-20110906-0603.zip), I opened Sample1.html and then looked at the Outline palette. There is a strange entry towards the bottom where the ComboBox should be. Instead of showing a ComboBox widget, the Outline palette shows the string "uniqName_1"

**Comment by peller** [comment]
I'll take this one.  See also #859

**Comment by peller** [comment]
It's a Dojo 1.7 back-compat issue with TextBoxes that only appears with ComboBox and TextBox definitions clobbering the declaredClass property in a mozilla-specific branch of the code.  This is also causing problems in themeEditor on FF (part of #859)

http://bugs.dojotoolkit.org/ticket/13854
