### ISSUE TITLE
BorderContainer with Tree: changing splitter causes corruption

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#93]
- New HTML File
- Add BorderContainer, accept defaults (e.g., 5 panes)
- Add Tree to left-side pane
- Select left-side ContentPane (e.g., by clicking under the Tree)
- In Properties palette, go to Widget-Specific, click on "Splitter" checkbox

Result=> Left-side ContentPane disappears

**Comment by billreed63** [comment]
Another variation:
- New HTML File
- Add BorderContainer, accept defaults (e.g., 5 panes)
- Add Tree to left-side pane
- Double-click on BorderContainer border to bring up BorderContainer dialog
- Uncheck the right-size pane's checkbox

Result=> BorderContainer all messed up

It looks like there is something wrong when mixing Tree with Bordercontainer,
which of course is a really common thing in user interfaces.

**Comment by billreed63** [comment]
I had to add a ForestStoreModelHelper to deal with the case where Tree is a child.

**Comment by billreed63** [comment]
May 2011

**Comment by billreed63** [comment]
review by @jhpedemonte

**Comment by jhpedemonte** [comment]
Added note on a small nit to commit #79f9417c243327ffd675.  But looks fine to me.
