### ISSUE TITLE
HTML files in WebContent/ folder can't find claro.css or app.css

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#930]
@jhpedemonte

(This might be a dupe, but I couldn't find any bugs that matched exactly this. Likely the same problem as #907. If so, OK to delete this bug as a dupe)

I created a new project with Eclipse Support checked, and then tried to create a new HTML file in the WebContent/ folder, and claro.css and app.css are not loaded properly. The Firebug console (I'm using Win/FF6) says:

```
"NetworkError: 404 Not Found - http://localhost:50000/maqetta/user/maqettaUser/ws/workspace/app.css"
app.css
"NetworkError: 404 Not Found - http://localhost:50000/maqetta/user/maqettaUser/ws/workspace/themes/claro/claro.css"
claro.css
```

Steps to reproduce:
- New Project ("myproject1"), setting Eclipse Support to checked
- Once page editor refreshes, in Files palette, select the WebContent/ folder
- New HTML page, accepting default name (file1.html)

Result=> Console shows above error messages
- Add a Button to page

Result=> Button is not properly styled

**Comment by childsb** [comment]
Fixed with commit de6c781742d1e8329fcc1a6c4938496a454c47d8
