### ISSUE TITLE
Selection from outline fails

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#931]
@billreed63 @childsb @jonferraiolo

Create a new document
Drop a widget on the page, like a dijit.form.Button
click on the button on the outline view
in FF, if you click off the element first, then click in the outline, you'll see an exception s == null in dojo.style during the firing of a davinci/ui/selectionChanged event.  Firebug's stack appears to be bogus, so I'm not sure yet exactly where it's being called
in Chrome, there's no exception, but the selection doesn't work either

**Comment by childsb** [comment]
Fixed with commit 79765bc36cc699c6bf59f46d398b18c0ba625e4e
