### ISSUE TITLE
Wrong default project name in review servlet?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#934]
@EldonReturn, @jhpedemonte

The following file (https://github.com/maqetta/maqetta/blob/master/davinci.review/src/org/davinci/server/review/DavinciProject.java) shows default project name of "Project", whereas davinci.core (https://github.com/maqetta/maqetta/blob/master/davinci.core/src/org/davinci/server/IDavinciServerConstants.java) defaults to "project1". Is this a problem?

See commit cf4d6b2a0585150287073abff726ececde7d37e3

**Comment by JonFerraiolo** [comment]
Pushing to M4. Haven't seen any problems during testing.

**Comment by EldonReturn** [comment]
The default project name is reserved for advanced project concept. For example, the review now can publish files among the projects listed (actually they are directories. so it's easy to list the directories). If we'd like to constrain the files within the current project open in future, this reserved field can be used.

**Comment by JonFerraiolo** [comment]
@EldonReturn, thanks for the response. Makes sense to me. I've tested having a single review publish files from 2 different projects in the same review and miraculously that seems to work. So, I think we are good for now and it looks like you have thought about the future, too.

**Comment by JonFerraiolo** [comment]
@waynevicknair - FYI

**Comment by JonFerraiolo** [comment]
@EldonReturn - should we close this bug?

**Comment by EldonReturn** [comment]
Yes. Let me close it. This is not a defect. The "project" introduced in the review serlvet is a reserved attribute for further use.
