### ISSUE TITLE
Exception selecting root node from outline view

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#935]
@childsb

select the root node of the document in the outline view, and an exception occurs in Context.js select() around line 1381:

`parent.selectChild(widget)` where "widget" is the widget-ized BODY element and parent is the unwidgetized HTML element, so there is no selectChild method.

We could just throw in an if parent.selectChild(), but we need to understand how this regressed.  What was/should be the behavior for selecting the root node?

**Comment by peller** [comment]
@waynevicknair

of particular interest is why the test in the first line of select

`widget == this.rootWidget`

fails.  Both represent BODY elements, but for different windows.  I'll take a look at the initialization sequence and see if wires are crossed there.

**Comment by JonFerraiolo** [comment]
Is there a more detailed reproducible scenario? I tried using today's build, opened Sample1.html, and then clicked on the ./project/Sample1.html line in the Outline palette, and I don't see any exceptions in the console. (Running Mac/Chrome)

**Comment by peller** [comment]
you need to have two tabs and switch tabs, whether they're newly created or from a previous session

**Comment by jhpedemonte** [comment]
@peller, what were the "selection problems" fixed by last commit?

**Comment by peller** [comment]
@JonFerraiolo noticed that as you type in source or split view, selection events would grab large portions of text and make the source editor unusable.
