### ISSUE TITLE
Eclipse-compatible projects should enforce/encourage content in WebContent

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#937]
With M3, if you create an Eclipse-compatible project, the default root folder is "myproject" rather the "myproject/WebContent". As a result, new HTML files end up in "myproject" by default instead of "myproject/WebContent".

We should at least set the default folder to be "myproject/WebContent", but I wonder if we should go further to force all files to be in "myproject/WebContent" and therefore never allow any File dialogs to ever allow the user to choose the project root folder.

**Comment by childsb** [comment]
Fixed with checkin 28a64827e90491de8ae0262286be0f8aee1d058a
