### ISSUE TITLE
Remove ?project=myproject2 from URL bar?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#938]
@jhpedemonte, @peller

Right now, the URL bar says something like: `http://localhost:50000/maqetta/?project=myproject2`

Wouldn't it be better to put current project information into the user's workspace somewhere instead of in the URL? After all, we aren't putting the list of open files in the URL bar and instead relying on workspaceSettings.

**Comment by childsb** [comment]
Project in the URL is design to allow better maqetta/browser integration--
- Bookmark projects
- Have multiple workspaces open at once.

**Comment by JonFerraiolo** [comment]
@jhpedemonte, @peller

I'll stick to my guns - let's get rid of the project URL parameter. Details:

I don't think we want to enable bookmarking projects, at least with the current design of the product. We just remember the user's last editing state and restore that state when the user returns, just like we do for currently open files. If we want to add bookmarking functionality, we need to think it through across all aspects of the product, not just projects.

Regarding multiple workspaces open at once, I also don't think we want to go there anytime soon. Same sort of argument - if we want N different Maqetta windows open at once, why do that at a workspace (or project) level and instead why not provide different browser windows for different files? That's a rhetorical question for time being. Actually, for short-term, I think we should stick with one and only one Maqetta browser window open at once, and then deal with possible multiple Maqetta browser windows down the road, and then decide whether to allow different workspaces in each browser window, different projects or different files. 

Also, I expect we will allow multiple workspaces when we add file client support because Orion will push us in that direction. Their current Orion navigator allows shows multiple file clients at once, and in my thinking right now, once we integrate into Maqetta, Orion file client ~== <Maqetta workspace.

**Comment by jhpedemonte** [comment]
Agreed on bookmark-ability: just remember user's last open project and open that.

Multiple workspaces support needs some thought, as Jon points out.  All-in-all, agreed with Jon that we should remove project name from URL.

**Comment by JonFerraiolo** [comment]
> All-in-all, agreed with Jon that we should remove project name from URL.

I assume everyone agrees that we should leave things as they are currently for M3 (i.e., http://localhost:50000/maqetta/?project=myproject2) and remove the project URL parameter for M4
