### ISSUE TITLE
Files palette download command on context menu not working

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#94]
Maybe we broke this when adding the two Download icons to the Files palette

**Comment by childsb** [comment]
There is a regression in the Tree.js after the upgrade from Dojo 1.6.

Selection changes aren't showing up, and the "download" is never enabled.

The problem is also evident in the "Download Selected" icon above the File Explorer.

**Comment by peller** [comment]
_selectNode went away in 1.6: http://bugs.dojotoolkit.org/changeset/23347/dijit/trunk/Tree.js
