### ISSUE TITLE
Exception if adding widgets as siblings to text nodes

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#941]
@jhpedemonte, @peller

Probably this bug has been in product forever...
- New HTML file
- In split view, type "abc" as the content of the BODY tag
- Add a Button

Result=> Internal error dialog comes up. Studying things in the debugger, the exception is deep within the Orion source editor. My guess is that the Orion source editor problem isn't the last fix we will need to deal with "mixed content" for a particular DOM node (i.e., text content along with element content).

**Comment by peller** [comment]
Confirmed with OrionM3 integration.  The exception seems to originate from TextView._showCaret.  It appears there is no caret when this happens.  the selection object looks like {start:NaN, end:NaN}  which ends up looking for line -1, etc.  Bad stuff happens.

Looking further up the stack, this caret code is triggered by selectModel from our code (which calls setSelection which calls _showCaret...)    ModelEditor.selectModel seems to be setting the bogus selection.

**Comment by JonFerraiolo** [comment]
I couldn't reproduce just now. Maybe the new Orion code fixed this bug?

**Comment by waynevicknair** [comment]
I couldn't reproduce this one on the current build.
