### ISSUE TITLE
Exception in source editor deleting some content

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#942]
@waynevicknair, @jhpedemonte

(Discovered in Mac/Chrome)
- New HTML File
- Accordion
- Add a Button and ComboBox to first pane of Accordion
- Split view
- Select the HTML for the Button and ComboBox, and then Ctl-C to cut

Result=> DOM Exception in eclipse/Editor.js:4093. I don't see any undefined objects or properties. Maybe we are trying to remove a child node from a parent which isn't the current parent of the child node. I suspect this is plain and simple an Orion bug.

**Comment by peller** [comment]
I'd want to try upgrading to their latest, but that would be risky right now.  We're pretty far behind.

**Comment by peller** [comment]
I cannot reproduce this.  did you mean apple-x?  (I don't get any exception, whether doing cut or copy using apple keys or the toolbar)

**Comment by jhpedemonte** [comment]
Testing with latest nightly, I get a **DOMException** in `_setClipboardText()`, at line `self._clientDiv.removeChild(child);`.

`self._clientDiv` is a `DIV` element with class of `editorContent`;  `child` is a `PRE` element which looks like this:

``` html
<pre style="position: fixed; left: -1000px; "> </pre>
```

`_clientDiv` doesn't seem to contain such a child element.

**Comment by JonFerraiolo** [comment]
It's too late to roll in a new Orion text editor, but is there a way that we can patch the Orion text editor code safely to prevent the exception in our M3 release or catch the exception and recover gracefully?

**Comment by JonFerraiolo** [comment]
I was able to reproduce as follows:
- New HTML file. Create using the steps above (Accordion, Button, ComboBox, etc)
- Try to cut per the instructions above (Cmd-X). For me, this worked
- Then open Sample1.html
- Then New HTML file again, with other two editors still open. Create a new file per the steps above:  (Accordion, Button, ComboBox, etc). Try to cut per the instructions above (Cmd-X). 

Result=> DOM exception as described above.

**Comment by peller** [comment]
still don't see it

**Comment by JonFerraiolo** [comment]
Pushed to M4, although @jhpedemonte, could you please try again on your side?

What I'm seeing is that I can reproduce this sometimes on Mac/Chrome using today's build on our staging server if I follow all of the steps above: New HTML file (Accordion, Button, ComboBox, split view, cut the Button and ComboBox text from source pane), then open Sample1.html, then once again New HTML file (Accordion, Button, ComboBox, split view, cut the Button and ComboBox text from source pane). If debugger is open, I get a DOMException. However, if debugger is not open, everything seems to proceed just fine, which is why I'm pushing this to M4.

**Comment by peller** [comment]
Confirmed in OrionM3.  Exception now occurs as

orion/textview/textView:4445  Uncaught Error: NOT_FOUND_ERR: DOM Exception 8
orion.textview.TextView._setClipboardText.cleanup

``` javascript
        self._clientDiv.removeChild(child);
```

**Comment by peller** [comment]
I can recreate this in the "minimaleditor" standalone orion Editor.  The "pre" that they create seems to get clobbered by the native cut operation, then the 'cleanup' method fails to remove it.  This is harmless.  cleanup is the only thing on the stack, the exception removing a missing child simply fails.

**Comment by peller** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=361464

**Comment by JonFerraiolo** [comment]
This wasn't assigned a milestone or priority. Set to M7 Prio Low so that @peller can at least see if issue still exists and then either close issue or update milestone/priority appropriately.
