### ISSUE TITLE
DataGrid in BorderContainer - can't set height to nothing, then change to 200px

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#945]
- New HTML File
- Add a BorderContainer with only a left pane and a center pane
- Add a DataGrid into left pane
- With DataGrid selected, go to Layout section of Properties pane. Note that height is 300px
- Remove the height property (i.e., select "300px" and hit backspace, then enter, or choose the first empty line in dropdown menu). Note that the DataGrid now snaps to auto-filling the height of the left pane's ContentPane. (My guess is that this is because Dojo defaults to the logic where if there is only one child, set its height to 100%)
- In Properties palette, now try to set height to 200px 

Result=> No change in the height of the DataGrid visually on the canvas. However, if you save, close, reopen, the 200px height takes effect.

**Comment by peller** [comment]
The behavior you describe where one child is set to fill the pane is controlled by doLayout, which is false here, so I'm not sure why this would happen.  It is worth noting that there could be some strange interactions because of the extra calculated width/height settings which are serialized in the DOM, redundant with the bordercontainer layout scheme.

**Comment by JonFerraiolo** [comment]
@peller - here is one you might look at if you have time

**Comment by billreed63** [comment]
This seems to be a side effect of the way DataGrid dynamically builds/adjusts the grid based on data and structure...

If I remove the height,  the source shows no style value for height but the property height shows a value of 693px which is the height of the center pane (more or less)...

I am not sure what we can do about this as it seems to be dojo code, mucking up the works, maybe @peller has an idea

**Comment by JonFerraiolo** [comment]
Aren't we going to move to gridx?

**Comment by jhpedemonte** [comment]
-> M6

**Comment by peller** [comment]
-> M7

**Comment by jhpedemonte** [comment]
cc @aerwin 

Is this also an issue with GridX?  If it only affects DataGrid, then we can close this.

**Comment by aerwin** [comment]
I just tried with GridX and it seemed to work pretty well. However, I had to set the height to 100% to get it to auto-fill vertical area in Step 5 (removing value of 300px wasn't sufficient), but that doesn't seem terribly surprising to me. So, I'll go ahead and close this.
