### ISSUE TITLE
Network errors with dojox.mobile

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#947]
Logging bug while I have information at hand. Haven't fully fleshed this out yet. Only discovered with Win/FF601. Haven't tested other browsers yet.

@peller

I created the mobile tutorial and saved the file (see below) and upon reopening, the Firebug console is showing the following errors on Win/FF601

```
"NetworkError: 404 Not Found - http://localhost:50000/maqetta/user/maqettaUser/ws/workspace/project1/app-compat.css"
app-compat.css
"NetworkError: 404 Not Found - http://localhost:50000/maqetta/user/maqettaUser/ws/workspace/project1/themes/claro/claro-compat.css"
claro-compat.css
"NetworkError: 404 ProxyServlet: /maqe...rces/content-compat.css - http://localhost:50000/maqetta/app/davinci/ve/resources/content-compat.css"
conten...pat.css
```

What's curious is that there is no file named "app-compat.css", but there are files iphone-app-compat.css and android-app-compat.css.

Here is source code for file that produces the errors upon reload:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<style>@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="maqetta/maqetta.js"></script>
<script type="text/javascript" djConfig="parseOnLoad: true" src="lib/dojo/dojo/dojo.js"></script>
<script type="text/javascript">
dojo.require('dojox.mobile');
dojo.require('dojox.mobile.parser');
dojo.require('dojox.mobile.deviceTheme');
dojo.require('dojox.mobile.compat');</script>
<script type="text/javascript" src="maqetta/States.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"></meta>
</head>
<body class="claro" dvFlowLayout="true" data-davinci-ws="collapse" data-maqetta-device="iphone" id="myapp">
 <div dojoType="dojox.mobile.View" id="root_view" style="display: none; height: 100%;">
<h1 label="My Mobile App" dojoType="dojox.mobile.Heading"></h1>
<ul dojoType="dojox.mobile.RoundRectList">
  <li label="Alerts" dojoType="dojox.mobile.ListItem" sync="true" moveTo="alerts_view"></li>
  <li label="Status" dojoType="dojox.mobile.ListItem" sync="true"></li>
  <li label="News" dojoType="dojox.mobile.ListItem"></li>
</ul>
</div>
 <div dojoType="dojox.mobile.View" id="alerts_view" style="height: 100%;" selected="true">
  <h1 label="Alerts" dojoType="dojox.mobile.Heading" back="Home" moveTo="root_view"></h1>
  <div style="margin: 1em;">
    adfafd</div>
  <div style="margin: 1em;">
    adfafd</div>

</div>
</body>
</html>
```

**Comment by jhpedemonte** [comment]
My first reaction is that this is from **compat.js** file in Dojox Mobile, so probably nothing much to concern ourselves with.

**Comment by jhpedemonte** [comment]
Yes, this is due to the function `dojox.mobile.loadCompatCssFiles()` in **dojox/mobile/_compat.js**, which only gets loaded in non-WebKit browsers.

There's a bug in this code, here:

``` js
if((href.match(dojox.mobile.loadCompatPattern) || location.href.indexOf("mobile/tests/")) && href.indexOf("-compat.css") == -1){
```

`location.href.indexOf("mobile/tests/")` returns `-1`, which is a "truthy" value, probably not what was expected.  Also, they may have meant to do the `indexOf()` call on `href` rather than `location.href`.

This means that it finds all of our CSS files (such as **app.css**) and try to load the "-compat.css" version.

I'll see if later versions have fixed this.

**Comment by jhpedemonte** [comment]
Latest Dojo code does in fact do a check for `!== -1`.  So for now we can ignore these network errors and we'll get the fix when we upgrade Dojo.
