### ISSUE TITLE
Changing theme on document leads to loading... hang

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#948]
It seems any attempt to change the theme leads to a loading... indicator which never resolves.
New File
Add a Dijit button
Switch from claro to sketch or a custom theme
See "Loading..." but it never refreshes the document

**Comment by billreed63** [comment]
the loading div overlay is added to the editor, this seems to be new. I don't remember this being part of the theme switching in the past. At any rate the loading div is not being removed.

**Comment by JonFerraiolo** [comment]
I suspect the fix to this will fix some other similar hangs. I am finding that sometimes changes in source view cause Loading to appear and never go away. 

One possible fix to get M3 out the door is to disable the offending Loading logic until we have time to get it right.

**Comment by billreed63** [comment]
the Context.unloadSheets method was losing scope to this...
