### ISSUE TITLE
Dojo 1.7 dojox.io.xhrScriptPlugin uses wrong callback for url

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#951]
if I have two services on the same host but with differnt callback parms the xhrScriptPlugin will always call the first callback parm

For example:

```
    dojox.io.xhrScriptPlugin("http://localhost:8081/test4/TestService","callback");
    dojox.io.xhrScriptPlugin("http://localhost:8081/test4/TestService2","callback2");
```

xhrScriptPlugin request:
Request URL:

```
http://localhost:8081/test4/TestService?callback=parent.dojo.io.script.jsonp_dojoIoScript1._jsonpCallback
Request URL:http://localhost:8081/test4/TestService2?callback=parent.dojo.io.script.jsonp_dojoIoScript2._jsonpCallback
```

The current code uses a substring of the url

```
function(method,args){
             return args.sync !== true &&
                (method == "GET" || httpAdapter) &&
                (args.url.substring(0,url.length) == url);
        },

```

If I replace the test to use the complete url the issue is resolved

```
function(method,args){
             return args.sync !== true &&
                (method == "GET" || httpAdapter) &&
                (args.url == url);
        },

```

**Comment by peller** [comment]
@billreed63 is consulting with @kriszyp on this one

**Comment by kriszyp** [comment]
If we didn't use the substring, we couldn't define a whole set of URLs with a single call. Can't you just reverse the order of callback registration:
dojox.io.xhrScriptPlugin("http://localhost:8081/test4/TestService2","callback2");
dojox.io.xhrScriptPlugin("http://localhost:8081/test4/TestService","callback");

**Comment by billreed63** [comment]
I could do that, but others could hit the same issue. could we not change the code to first look for an exact match and then a substring match?

**Comment by kriszyp** [comment]
Not sure what you mean, the code does match the string. Are you suggesting that the adapter go through two matching passes, one for exact and then for non-exact? That would be a much bigger change and would probably mean we could no longer use the AdapterRegistry. Or am I missing something?

**Comment by billreed63** [comment]
No that is what I was suggesting, I am now in an area I know very little about so I am more asking for my own understanding...

**Comment by billreed63** [comment]
leave url.substring compare for groups reg definitions
