### ISSUE TITLE
Reviews palette should show reviews started by self and all others

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#953]
@jmockler, @jhpedemonte, @waynevicknair, @childsb

(Eldon, please correct any factual errors below and of course please voice your opinions on my proposal. You know this stuff better than me.)

I'm pretty sure that with the current design, the Reviews palette in either the page editor or review editor only shows reviews that correspond to one particular review creator. In the page editor, I believe user A will only see reviews that user A himself created. In the review UI, the reviewer clicks on a hyperlink where URL parameters contain the name of the user who launched the review (e.g., bill@ibm.com), and then only sees reviews that were created by that user (i.e., bill@example.com). To see reviews created by a different user (e.g., harry@example.com), he has to find the invitation email from harry@example.com and click on that hyperlink. If users end up participating in multiple review sessions from multiple people, and maybe launching his own review sessions (and that is exactly what we would like to see), then many users will get lost within the current setup.

To change this will require coordination with our server logic (I'm looking at you, @childsb), some of the site-specific scripts (e.g., Maqetta.org's PHP files - eyes on @waynevicknair), and of course the reviews palette UI (@EldonReturn).

What I propose is:
- Reviews palette in the page editor and review editor should show all reviews where the given user is a participant, either as an author or reviewer, and the user can open any of the HTML files listed in the Reviews palette. (For time being, we would preserve the behavior where if the user is in the page editor, double-clicking on a *.rev file would launch a new browser window with the review UI showing, and if in the review UI, would open up another editor tab.)
- Then I'm thinking we should change the URL parameters in the review invitation to remove the author's user name (which I believe appears now in 2 places, right after the "review/" and in the revieweeuser URL parameter) and instead add a unique token number that represents an ID for a particular review. The review UI would then use this ID to close the tree container nodes for all other reviews and only open up the child nodes for the review whose token was in the URL parameter.

Of course, we have to bear in mind that ultimately we want to merge the review UI into the page editor UI. My proposals above are a short-term fix that I hope will be consistent with longer-term and more substantial coding efforts.

**Comment by JonFerraiolo** [comment]
Maybe reassign to @waynevicknair as part of phase 2 work with integrating R&C into core?

**Comment by waynevicknair** [comment]
surely, i'd be happy to work on and coordinate efforts for this issue.

**Comment by JonFerraiolo** [comment]
reassigned to @waynevicknair for M5

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
Hold on a minute - if we don't do this bug, how will users see all of the reviews with which they are participating? Is the assumption that the Reviews palette shows all reviews to which you have been invited, and an author will always invite himself? If so, then OK for M6, otherwise, need to fix for M5.

**Comment by jhpedemonte** [comment]
Not sure.  I was only going under the assumption that this isn't anything new, this is how R&C has been working.  And that this is in fact a new feature, not a regression.  Please let me know if I am wrong.

**Comment by JonFerraiolo** [comment]
Pushing back to M5 until we are sure that the list of Reviews that authors and reviewers see in the Reviews palette is working acceptably.

**Comment by waynevicknair** [comment]
what i'm seeing on Mac chrome and safari is that the Reviews list appears correctly for both designers (authors) and reviewers. i believe that is the desired result. will test on an official build tomorrow morning.

**Comment by waynevicknair** [comment]
ok. i believe this is working as required.
