### ISSUE TITLE
jQuery/YUI widgets not rendered correctly when opening file in VE

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#954]
To reproduce:
- New HTML file.
- Drop jQuery Button.
- Save, close, reopen.

---

The issue is that the JS needed to instantiate the widgets (in a `<script>` in the body) isn't getting run.

I can't figure out, though, why it works in the case when dropping the widget on the page vs. opening a saved page.

---

**Working Case (adding widget to page) :**

In **widget.js**, we create DOM element(s) from the content string (using `dojo._toDom()`).  The DOM node is attached to a widget instance.  Later, when executing an **AddCommand**, the generated node is added to the page's DOM:

``` javascript
containerNode.appendChild(child.domNode);
```

where `containerNode` points to `<body>`.

---

**Failing Case (opening saved page) :**

The body content comes in as a string and is added using `innerHTML` in `Context._setSourceData()`:

``` javascript
containerNode.innerHTML = content;
```

But scripts added through `innerHTML` don't get executed.

In order to fix that, I decided to mimic what happens when a widget is added to the page.  I replaced the `innerHTML` code with this:

``` javascript
dojo.place(content, containerNode, 'only');
```

Internally, `dojo.place()` does the `_toDom()` call, then does an `appendChild()` to the body (`containerNode`).  However, this still doesn't work -- the script in the source doesn't get executed.

---

@peller, any thoughts/ideas/wild guesses?

**Comment by jhpedemonte** [comment]
Best way to test this: add `debugger;` to the **javascript** property of jQuery's **button_oam.json** file.

**Comment by peller** [comment]
I'm confused... what would the `debugger;` show if the script does not get executed?

**Comment by peller** [comment]
Not sure why adding script through place and _toDom wouldn't work, but you might look at _ContentSetter in dojox/html/_base.js which is used by dojox.layout.ContentPane to process script from inserted markup (and I want to say we did something like this in OAM also...)

**Comment by jhpedemonte** [comment]
We did do something like that (remove `<script>` elements from content and evaluate them later), but that was because of an IE issue.

Here, I'm plainly seeing (what appears to me) similar code work in one instance but not another.

**Comment by jhpedemonte** [comment]
Just keeps getting stranger...

So I was able to mostly make `dojox.html.set()` work for my simple test case, but it fails when loading Sample1.html.  Almost all of the DOM nodes are missing for some reason.

Some more investigating and it seems to do with `dojo.place()`.  If I replace `containerNode.innerHTML = content` with `dojo.place(content, containerNode, 'only')` in `Context._setSourceData`, I see the issue with Sample1.html.

It doesn't make much sense as to why it would fail.  If I compare the success vs. failure cases, `containerNode.innerHTML` look identical after setting the content.
