### ISSUE TITLE
Wrong path to claro.css for new file inside of download ZIP

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#955]
(I don't know if all of these steps are necessary. I might update issue with simpler set of steps after more investigation)
- New Eclipse-compatible project ("eproj2" in my case)
- New folder "folder1" as a child of WebContent/
- New HTML file "file1a.html" within folder1
- Add some widgets and save
- In Files palette, select the file just created (file1a.html), click on second icon (Save selected files). In dialog, accept all defaults and click OK.
- After the download is complete, upzip into a localhost web server's HTML file area (e.g., htdocs/ or public_html/ or whatever). (Warning: you will probably want to create a new folder into which you unzip because sometimes unzipping will overwrite existing files in htdocs/).
- Attempt to load in browser via http://localhost/<somefolders...>/WebContent/folder1/file1a.html

Result=> Unstyled results. Looking at debugger, the path to claro.css is wrong. Looking at file1a.html found in ZIP file, it contains the following line:

```
<style>@import "../../../project1/themes/claro/claro.css";@import "../app.css";@import "../lib/dojo/dojo/resources/dojo.css";
```

The path to claro.css is clearly wrong. For one thing, I'm in "eproj2", not "project1". Also, I'm not sure why the project name is in the path at all.

**Comment by JonFerraiolo** [comment]
I did some more testing in this area. It's looking like the problem is with custom projects and/or the Eclipse support checkbox. I tried creating a ZIP from the default project (project1) and root folder, and there was no problem with the HTML file in the ZIP. I then tried creating an HTML file in a subfolder, again using the default project, and again everything worked fine.

**Comment by childsb** [comment]
The Context wasn't using the proper project/base when searching for themes, and project1/themes/claro/claro.theme was the first one found.  So the include was linking to the theme in project1
