### ISSUE TITLE
JQueryUI widgets lose style/formatting on source change

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#959]
Create a new HTML file
DND all the JQueryUI widgets onto the VisualEditor canvas
Click on the Split View icon in the toolbar
Click in the source view and change the button label (or any text)

Result: All widgets lose there styling.

**Comment by JonFerraiolo** [comment]
Probably the same as #954, which was fixed an hour ago. Please test against latest build and if still present, then reassign to @jhpedemonte

**Comment by waynevicknair** [comment]
looks like the 954 fix got this one too. just verified. 

DUPLICATE of issue #954
