### ISSUE TITLE
Drag/drop on Outline can leave phantom widgets that never go away

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#96]
(Need to work on this bug to come up with a reproducible set of steps)

If you start a drag operation in the outline palette with LMB, and then (while over a container widget) bring up RMB, the dragged object gets duplicated or becomes a phantom overlay that never goes away unless doing a browser refresh.

**Comment by aerwin** [comment]
--> no milestone to M7
--> @peller (only because I think you may have opened base Dojo against this before?)

Think this can be dup'ed against something (or perhaps fixed in Dojo 1.8)?

**Comment by peller** [comment]
there was a bug like that when dragging over the scrollbar.  We have a workaround for that.  I take it this is something else.

**Comment by JonFerraiolo** [comment]
from @peller -> @doronrosenberg . Is that OK? If not, please switch it back to @peller

**Comment by doronrosenberg** [comment]
back to @peller as he wrote all the DND hacks

**Comment by peller** [comment]
@JonFerraiolo I don't understand the description.  Assuming LMB == left mouse button and RMB == right mouse button, is the suggestion to start dragging with the left, then press the right while holding the left?  If so, I don't have a two button mouse.  Could you please test?  Otherwise, I'm unable to see any phantom widgets doing dnd from the outline palette, so I'd suggest closing.

**Comment by peller** [comment]
Ok, what I do see: if you mouse down in the outline view and drag a widget to the canvas/visual editor and mouse up, the avatar stays until you go back and click in the outline view.  No right mousing involved.  Is that the bug?  Probably some variation of the cross-iframe drag and drop bugs, which are sometimes cross-browser quirks.

**Comment by JonFerraiolo** [comment]
OK, I played around with this some. I'll bet the original bug from long ago is no longer present. Regarding:

> ok, what I do see...

maybe we should close the dnd handler with onmouseout on the DIV that surrounds the outline palette? how often would a user temporarily drag outside of the palette's bounds and then move the mouse back in to complete the drop operation?

**Comment by peller** [comment]
I think it's not uncommon for a user to drag, but not in a straight line.  Losing the selection when straying outside the div might be frustrating.  Perhaps we can make the mouse up event work, since we have a similar challenge in the createtool going from the widget palette to the canvas.

**Comment by peller** [comment]
The idea is to connect the mouseup event in the iframe to the dndController in OutlineTree, something like

```
connect.connect(this.context.getContainerNode(), "onmouseup", this.dndController, "onMouseUp"));
```

probably from Context itself, since OutlineTree is instantiated first.  I got it to fire, but the onMouseUp event did not tear down the avatar.

-> M8

**Comment by peller** [comment]
maybe @doronrosenberg might have some ideas here

**Comment by JonFerraiolo** [comment]
@doronrosenberg: maybe we could have Context.js:onMouseUp publish an event (e.g., /maqetta/pageeditor/events/mouseup) and then the Outline palette could listed for that event, and stop the drag/drop processing.
