### ISSUE TITLE
Duplicate script blocks containing dojo.require()s

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#966]
Over the course of testing, I edited Sample1.html maybe 8 to 10 times. I was using the VisualEditor. However, I happened to open the source view and noticed that 

```
<script type="text/javascript">
dojo.require('dijit.layout.TabContainer');
dojo.require('dijit.layout.ContentPane');
dojo.require('dijit.form.Button');
dojo.require('dijit.form.ComboBox');
dojo.require('dijit.form.MultiSelect');
dojo.require('dijit.form.TextBox');</script>
```

the above block appeared 9 times in the source.

**Comment by jhpedemonte** [comment]
I'm having a hard time recreating this one.

@JonFerraiolo

**Comment by jhpedemonte** [comment]
Well, I've been trying for a while now to recreate, but got nowhere.  Closing for now.
