### ISSUE TITLE
Mobile tutorial: clicking on #root_view in Outline palette doesn't select

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#968]
@peller, @jhpedemonte

This used to work at least sometimes. Not absolutely critical for M3 because there is an alternate path to success (i.e., click on eyeball).
- Go through mobile tutorial up to point where second View has been created and has an ID. The second View will have it's eyeball "on" and first view will be off'
- Click on first View in Outline palette. 

Result=> Nothing happens. Proper behavior is that first View is selected, becomes visible, and second View becomes invisible.

Workaround is to click on eyeball to the left of first View instead of clicking on the first View's entry in Outline palette.

**Comment by JonFerraiolo** [comment]
Adam, Did you grab this bug from me, or did I mistakenly assign it to you? If you are going to fix, I want to warn you that there might be some complexities in all of this. I don't remember the details at this time, but I wouldn't be surprised if some of the processing goes through the ViewHelper.js logic.

**Comment by jhpedemonte** [comment]
Hmm, this was working earlier this week, I believe.  Must be a recent regression.

**Comment by peller** [comment]
I was going to take a look, but feel free to grab it back.  I won't get to it today.

**Comment by JonFerraiolo** [comment]
I grabbed it back

**Comment by JonFerraiolo** [comment]
Closing. Neither @jhpedemonte or @jonferraiolo can reproduce on latest build
