### ISSUE TITLE
Smart input exception after browser refresh with 2 open docs

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#974]
@peller, @jhpedemonte
- Open Maqetta
- Clear any currently open documents
- Browser refresh to get Maqetta into its initial state
- New HTML File, add a LABEL, save
- Once more, New HTML file, add LABEL, save. (There are now two editor tabs)
- Browser refresh
- The second editor tab should be on top after refresh
- Double click on the label to bring up smart input. Nothing happens. Double-click to try again.

Result=> Exception in console (see below). Further investigation shows that Smart Input was attached to the hidden editor, not to the current editor.

```
dijit.js:128 Uncaught Error: Tried to register widget with id==ieb but that id is already registered
dojo.declare.adddijit.js:128
dojo.declare.createdijit.js:1599
_a6dojo.js:1045
dojo.declare.createdijit.js:1864
_a6dojo.js:1045
dojo.declare.createdavinci-common.js:1254
dojo.declare.postscriptdijit.js:1583
adojo.js:1142
dojo.declare._loadingdavinci.js:15904
dojo.declare._createInlinedavinci.js:15851
dojo.declare.showdavinci.js:15809
dojo.declare.showInlinedavinci.js:17641
dojo.declare.onDblClickdavinci.js:17725
dojo.hitch
```

**Comment by JonFerraiolo** [comment]
@billreed63 - Reassigning to me. I have a fix and am now going through a testing cycle. To fix, I moved widgetHash from a global static list that applied to all documents to a document-specific list on the Context object. This is mostly a bandaid fix, but should be localized and relatively safe. We still will need to look at widgetHash with fresh eyes to look for a more fundamental fix.

**Comment by JonFerraiolo** [comment]
Closed by 9dcea85

**Comment by jhpedemonte** [comment]
@peller should take a look at this.  He tried to do something similar a few weeks ago but ran in to some issues and had to back out the patch.

**Comment by peller** [comment]
Yeah, I was hoping to remove the hash entirely, as it's only really needed in a few code paths, but I think this is a good improvement.
