### ISSUE TITLE
Wrong background image url when creating new style rule

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#976]
OK to push to M4 because not many users will run into this one.
- New HTML file
- Add a TextBox
- Go to Background section of Properties palette
- Enter a custom class name for the 'class' property, for example "ccc"
- Show cascade for background-image by clicking on ">" to right of background-image
- Click on radio button for "Add new rule..." for the new class (e.g., "ccc")
- Click on the "..." button and choose SampleBanner.png

Result=> No background image applies to TextBox and console shows the following. As you can see, "project1" is listed twice in the URL.

`GET http://macwayne2.austin.ibm.com:55556/maqetta/user/ab@ferraiolo.com/ws/workspace/project1/project1/SampleBanner.jpg 404 (Not Found)`

Note that element.style works just fine - it computes the correct URL for the background image.

**Comment by childsb** [comment]
fixed with commit 74dc9e83f9b9eb186a82218af967ca31b2b5ffac  (the baseLocation wasn't being set for proposed rules such as app.css)
