### ISSUE TITLE
SCRIPT tag shows in Outline palette

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#977]
@jhpedemonte
- Close all current editor tabs
- Refresh Maqetta browser window
- New HTML file

Result=> SCRIPT element shows at top of Outline palette

**Comment by peller** [comment]
somehow it appears to have regressed here: 3b38df670ad6055d121ffa6edb6a29100b35cff6  I'll take a look at this tonight

**Comment by jhpedemonte** [comment]
This was fixed earlier by 95232d5c99cab194bb94553f3ec4d1ccfd8bf869.
