### ISSUE TITLE
Labels not visible in RoundRectDataList with Android device

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#980]
- New HTML file
- Choose device Android340x480
- Add a ScrollableView then a RoundRectDataList

Result=> text doesn't show. Note that text does show if you do the above steps using iPhone theme, and text will reappear if you save and reopen the file.

**Comment by jhpedemonte** [comment]
This looks like a CSS issue. Notice that the background is grey and the text color is black (that's why text doesn't show, since ListItem background is also black).

But if you do a Preview or close/reopen then background is black and text color is white.

**Comment by jhpedemonte** [comment]
You can see the loaded CSS files in the VE by inspecting `frames[1].document.styleSheets`.

When choosing the Andriod device, the style sheets list contains **andriod.css**.

But when adding a Mobile device, **iphone.css** is also added and takes precedence over the android.css rules.

I think this has to do with the MobileCreateTool code, which attempts to set the device when dropping a mobile widget.

**Comment by jhpedemonte** [comment]
I was hoping this might be an easy fix, but I'm not sure how to handle it and not reintroduce previous bugs.

Setting the device to "Android" adds the **android.css** style sheet.

Then, adding a Dojox Mobile widget adds the **deviceTheme.js**, which adds the **iphone.css** file.  Now the page contains both android.css and iphone.css.

At this point, the **MobileCreateTool** is called, and it calls `Context.setMobileTheme()`. However, the device passed in comes from `getMobileDevice()`; `setMobileTheme` then compares that to `getMobileDevice()` and does nothing.  So basically my fix for #899 undid the fix for #767 (this issue is the same as #767).

I think the only way to properly fix this will be to make the iframe reload whenever adding deviceTheme.js to the page.

**Comment by jhpedemonte** [comment]
Is there a document event that specifies when a dynamically loaded CSS file has been added to the page?  If the "unload" event has already fired, it won't fire again.  There might be an option for an "unload" on the `<link>` element itself, but that isn't an option here (would require editing deviceTheme.js).

@peller

**Comment by peller** [comment]
apparently, link onload is not available in all browsers.  This post suggests a pretty odd method that seems reliable -- use the IMG tag to get an event to fire when the resource (a CSS file) is ready.  Better than looping.

http://www.backalleycoder.com/2011/03/20/link-tag-css-stylesheet-load-event/

**Comment by JonFerraiolo** [comment]
@billreed63

Does this commit remove the check that sees if the new device is same as the current device? We don't want to reload CSS files over and over again.

**Comment by JonFerraiolo** [comment]
Moved this back to M3 to discuss at today's phone call. This is a bad bug given the nature of this release. The way things are now, you can't author within any silhouette other than an Apple silhouette.

**Comment by jhpedemonte** [comment]
Jon, as you can see by my pull request, the check for the new device against current device wasn't necessary.  In fact, it was getting in the way and basically meant that MobileCreateTool was unnecessary (see description in pull request).

Adam's fix still has the same problem: MobileCreateTool calls `getMobileDevice()` and passes that to `setMobileTheme()`, which itself calls `getMobileDevice()` and checks that against the incoming device.  End result is that when being called from MobileCreateTool, `setMobileTheme()` is a no-op.

Now, Adam's commit also added code to MobileCreateTool that removes "iphone.css".  First of all, I don't like that code being there -- better to keep all CSS juggling code in one location (setMobileTheme).  Second, I'm not exactly sure how that is supposed to work, given what I've said about the function being a no-op when called from MobileCreateTool.

**Comment by jhpedemonte** [comment]
So there's no confusion: my pull request (https://github.com/maqetta/maqetta/pull/990) was added so that Adam and Jon could review it before being committed.  It has **not been committed**.

**Comment by peller** [comment]
My commit d6870739d3bc7d56c0a2d04bf0325a42ca4614a6 did two separate things: 1) it explicitly removed the iphone.css link added by dojox.mobile initialization, when adding the first widget, iff the theme was already set to something else (like android) 2) it loosened the existing setMobileDevice regexp to remove "compat" files, if any.  It still suffers from all the problems @jhpedemonte notes and also the removal of iphone.css reopens the race condition in #899.
