### ISSUE TITLE
yui calendar focus box is incorrect

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#984]
the focus box appears zero height and full width of the screen and does not surround the calendar widget.

**Comment by JonFerraiolo** [comment]
Probably have to push this to M5.

**Comment by jhpedemonte** [comment]
-> M7

We need to re-evaluate and redo our jQuery/YUI support.  Probably won't have time in M6 for that.

**Comment by jhpedemonte** [comment]
Closing since we no longer support YUI.
