### ISSUE TITLE
Remove "Using JAR" line from maqetta.*.mac.command

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#986]
The Mac launch scripts echos a line that points to the JAR file being used, the Win launch scripts do not. This JAR line is not useful to users. Let's remove that line from the Mac launch scripts. (And Unix launch scripts if there, also)

**Comment by JonFerraiolo** [comment]
-> M7 Prio/Low. We still have echo statement. Should be trivial to fix - just remove that line of code.

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg Low priority, but if you run out of things to do, maybe you could remove the echo statement about which JAR is being used. Not really that useful for our users.

**Comment by doronrosenberg** [comment]
I actually think the jar is not a bad thing to output, an invalid path could be used for debugging.

**Comment by JonFerraiolo** [comment]
But how could there be an invalid path to the jar file? Only if the user hand-edits the file, in which case he is on his own.

**Comment by JonFerraiolo** [comment]
Closing. Launch scripts no longer way "using JAR"
