### ISSUE TITLE
Widget palette doesn't allow drag/drop if using filter

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#991]
- Type "but" into filter field at top of widget palette
- Try to drag/drop the first Button widget shown onto the canvas

Result=> Doesn't work. You can click on the first widget in the Widgets palette and then click onto the canvas at a particular location, but drag/drop doesn't work. What's weird is that the 2nd, 3rd, 4th widgets can be dragged/dropped successfully.

**Comment by jhpedemonte** [comment]
This was working for me over the weekend, when I was testing with **IconContainer**.  I would type in "icon", which would show IconContainer and IconItem.  And I could drag either one just fine.

**Comment by JonFerraiolo** [comment]
Closing this. I can't reproduce now, either.
