### ISSUE TITLE
Silhouette not restored after save/reopen

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#993]
@jhpedemonte, @billreed63, @peller

To my shock and disappointed, we have a regression in mobile authoring versus Preview 2, and I think this regression has been introduced recently.
- New HTML file
- Choose iPhone silhouette
- Save, close, reopen

Result=> iPhone silhouette doesn't show, and it should.

**Comment by JonFerraiolo** [comment]
Further testing. This problem only happens on a release build using Mac/Firefox. (Haven't done any Windows testing yet). Works find with release build and Mac/Chrome and works fine in Mac/Firefox when launching from Eclipse. No messages in console. Probably a timing bug.

**Comment by JonFerraiolo** [comment]
Silhouette is not restore when running today's build using Mac/Firefox on the staging server. Mac/Chrome doesn't have the problem on the staging server. So, it's just Firefox and when using a build.

**Comment by billreed63** [comment]
onload not firing consistently on FF, so I moved the SetDevice to dojo.addOnLoad
