### ISSUE TITLE
Exception if trying to create new HTML file within 2 levels of nested folders

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#994]
Probably will have to push this one to M4, but leaving for M3 to see if @childsb can take a look.
- Create new folder (e.g., project1/aaa)
- Within that new folder, create another folder (e.g., project1/aaa/bbb)
- Select the new folder bbb
- New HTML file

Result=> Exception davinci/ui/Resource.js:238 resource is undefined

Note: no problem creating a new HTML file in project1/aaa

**Comment by peller** [comment]
likely a dup of #982... perhaps there was no selection in the dialog

**Comment by waynevicknair** [comment]
more information: if you select the 'bbbb' folder in the file view contained in the File Create Dialog, the HTML file will get created correctly. it looks as though the tree model in the File View has lost selection information. 

continuing to investigate.

**Comment by childsb** [comment]
Workaround in commit e6e11b341e814ce3d557d95d9ec3865e015626a0

Using text field with path above the tree for selection instead of the tree.  There's probably still a Dijit bug here, but this should work for us for now.

**Comment by JonFerraiolo** [comment]
I pinged @childsb about this. Fixed one exception but introduced another. He is working on the newly introduced exception.

**Comment by JonFerraiolo** [comment]
Seems to be fixed now with 683aaffc03
