### ISSUE TITLE
SmartInput for DataGrid has too much space for radio button area

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#996]
Probably defer this to M4. Only listing as M3 for time being in case @billreed63 has time to try to reproduce and study. Much lower priority than #993. I am running Win/FF using staging server with latest build. 

`Version: Preview 3
Date: Sep 12, 2011 8:12:07 AM
Build: b253606b5677864...`
- New HTML file
- Add DataGrid
- In SmartInput, choose "Data file from workspace"

Result => Large amount of vertical space for the two radio buttons (plain text vs HTML markup)

**Comment by billreed63** [comment]
Is this on FF/FB I have seen this when on FF/FB FB seems to add a div that messes up the SmartInput table

**Comment by JonFerraiolo** [comment]
I'm seeing this with FB turned off on Win/FF602 and Mac/FF602

**Comment by billreed63** [comment]
If I create an new html file
drop dataGrid
change DataStore to workspace

I see no extra spaces and the HTML for smart input look as below:

``` html
<tr>
<td class="smartInputTd1">
<td class="smartInputTd2">
<div id="davinci.ve.input.SmartInput_radio_text_width_div" class="smartInputRadioTextDiv" style="width: 190px;">
<div class="dojoxEllipsis">Plain text </div>
</div>
</td>
</tr>
<tr>
```

When I refresh the browser for that same page I see the following when opening smartinput

``` html
<tr>
<td class="smartInputTd1">
<td class="smartInputTd2">
<div id="davinci.ve.input.SmartInput_radio_text_width_div" class="smartInputRadioTextDiv" style="width: 190px;">
<div class="dojoxEllipsisContainer">
<div class="dojoxEllipsis">Plain text </div>
<div class="dojoxEllipsisShown" style="display: none;"></div>
<iframe class="dojoxEllipsisIFrame" src="javascript:'<html><head><script>if("loadFirebugConsole" in window){window.loadFirebugConsole();}</script></head><body></body></html>'">
</div>
</div>
</td>
</tr>
```

**Comment by billreed63** [comment]
fixed by the above commit
