### ISSUE TITLE
"node is null" when closing Visual Editor

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#998]
In FireFox:

1) new HTML file
2) close html file
3) notice "node is null" in console.

if you have break on error enabled, it will stop inside some dojo class.

**Comment by childsb** [comment]
caused by commit 03b0e7b5fc05ae5145dc949dae7759d3087ee6d2

**Comment by peller** [comment]
the tab is getting removed twice because in the middle of the dijit code which closes the tab, the onClose callback calls removeWorkingCopy, which triggers the resourceChanged event which also closes the tab
